include::./index.adoc[]

[[v31-2-0]]
=== Lamentações, 2
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Lamentações 2 descreve a destruição de Jerusalém pelo exército babilônico e a aflição do povo que ficou sem abrigo e alimento. O capítulo retrata a cidade de Jerusalém como uma viúva desolada que chora e clama por ajuda, mas ninguém a socorre. Abaixo estão cinco versículos relacionados com os temas abordados em Lamentações 2:
* Salmos 137:5-6: "Se eu me esquecer de ti, ó Jerusalém, esqueça-se a minha direita da sua destreza. Se me não lembrar de ti, apegue-se-me a língua ao paladar; se não preferir Jerusalém à minha maior alegria." Este salmo retrata a dor e a saudade que os judeus exilados sentiam por sua cidade natal, Jerusalém, após a destruição dela pelos babilônios. Essa saudade é uma temática presente em Lamentações 2.
* Isaías 3:26: "E as suas portas gemerão e prantearão; ela, desolada, se assentará no chão." Assim como em Lamentações 2, Isaías 3 descreve uma cidade (Jerusalém) desolada e sem esperança. Isaías também utiliza a imagem de portas gemendo e pranteando, que é uma figura de linguagem presente em Lamentações 2.
* Ezequiel 27:30-31: "E prantearão sobre ti com amargura de alma, e farão sobre ti pranto amargo, dizendo: Quem houve cidade semelhante a Tiro, destruída no meio do mar? Quando os teus negociantes eram príncipes, e os teus mercadores os mais ilustres da terra..." Esse versículo descreve o lamento dos habitantes de Tiro, que também foi destruída. O pranto e a lamentação são temas comuns em Lamentações 2.
* Joel 2:12-13: "Ainda assim, agora mesmo diz o Senhor: Convertei-vos a mim de todo o vosso coração; e isso com jejuns, e com choro, e com pranto. E rasgai o vosso coração, e não as vossas vestes, e convertei-vos ao Senhor vosso Deus; porque ele é misericordioso e compassivo, tardio em irar-se e grande em beneficência, e se arrepende do mal." Joel exorta o povo a se arrepender de seus pecados e se voltar para Deus, que é misericordioso. Essa mensagem é similar àquela presente em Lamentações 2, onde o povo é descrito como merecedor da punição divina.
* Zacarias 1:15: "E estou muito indignado contra as nações em segurança; porque eu estava um pouco indignado, mas eles agravaram o mal." Nesse versículo, Deus se mostra indignado com as nações que se sentem seguras enquanto Jerusalém foi destruída. Essa raiva divina também é presente em Lamentações 2, onde o povo sofre a punição de Deus por seus pecados.
****

[[v31-2-1]]

^<<v31-2-1,1>>^ ALEF. Como cobriu o Senhor de escuridão, no seu furor, a filha de Sião? Precipitou do céu sobre a terra a glória de Israel; não se lembrou do estrado de seus pés, no dia do seu furor. (ver nota)

[[v31-2-2]]

^<<v31-2-2,2>>^ BET. O Senhor destruiu, sem piedade, todas as moradas de Jacob: destruiu no seu furor as fortificações da filha de Judá, lançou-as por terra; rebaixou o reino e os seus príncipes.

[[v31-2-3]]

^<<v31-2-3,3>>^ CHIMEL. Quebrou, no transporte do seu furor, todo o poderio de Israel; retirou a sua direita, em face do inimigo, e ateou em Jacob um incêndio que devora tudo em volta. (ver nota)

[[v31-2-4]]

^<<v31-2-4,4>>^ DALET. Estendeu o seu arco como inimigo, firmou a sua direita como adversário, matou tudo o que era formoso à vista na tenda da filha de Sião, derramou como fogo a sua indignação.

[[v31-2-5]]

^<<v31-2-5,5>>^ HE. O Senhor tornou-se como um inimigo; destruiu Israel, destruiu todos os seus palácios, arrasou as suas fortificações e encheu a filha de Judá de gemidos e mais gemidos.

[[v31-2-6]]

^<<v31-2-6,6>>^ VAU. Destruiu a sua cerca como a dum jardim, demoliu o seu lugar de reunião; o Senhor suprimiu em Sião as festas e o sábado; rejeitou, na indignação do seu furor, o rei e o sacerdote. (ver nota)

[[v31-2-7]]

^<<v31-2-7,7>>^ ZAIN. O Senhor perdeu a estima pelo seu altar, sentiu repulsa pelo seu santuário, entregou nas mãos dos Inimigos os muros das suas fortalezas; ergueram-se gritos na casa do Senhor, como em dia de solenidade.

[[v31-2-8]]

^<<v31-2-8,8>>^ HET. O Senhor resolveu destruir os muros da filha de Sião; estendeu o seu cordel, e não retirou a sua mão, sem que ficasse tudo arruinado; enlutou o muro e antemuro, que estão, igualmente, desolados.

[[v31-2-9]]

^<<v31-2-9,9>>^ TET. As suas portas estão sepultadas na terra; (o Senhor) destruiu, fez em pedaços as suas trancas; o seu rei e os seus príncipes estão entre as nações; já não há lei; os seus profetas já não conseguem visões do Senhor.

[[v31-2-10]]

^<<v31-2-10,10>>^ JOD. Sentaram-se em terra, em silêncio, os velhos da filha de Sião; cobriram as suas cabeças de cinza, cingiram-se de cilícios. Inclinaram as suas cabeças até à terra, as virgens de Jerusalém.

[[v31-2-11]]

^<<v31-2-11,11>>^ CAF. Os meus olhos enfraqueceram de tanto chorar, as minhas entranhas turbaram-se, o meu fígado derramou-se por terra vendo a ruína da filha do meu povo, quando caíam mortos os meninos e as crianças de peito nas praças da cidade.

[[v31-2-12]]

^<<v31-2-12,12>>^ LAMED. Eles diziam a suas mães: Onde está o trigo e o vinho? - quando, como feridos, iam desfalecendo nas praças da cidade, quando entregavam as suas almas no regaço de suas mães.

[[v31-2-13]]

^<<v31-2-13,13>>^ MEM. A quem te compararei, a quem te assemelharei, é filha de Jerusalém? Quem acharei igual a ti, para te consolar, ó virgem, filha de Sião? É grande como o mar a tua ruína: quem poderá curar-te?

[[v31-2-14]]

^<<v31-2-14,14>>^ NUM. Os teus profetas anunciaram, a teu respeito, visões vãs e insensatas, e não te manifestaram a tua iniquidade, para te evitarem o cativeiro, mas anunciaram-te visões de engano e de mentira.

[[v31-2-15]]

^<<v31-2-15,15>>^ SAMEC. Batiam com as mãos, vendo-te todos os que passavam pelo caminho; assobiavam e abanavam a cabeça contra a filha de Jerusalém. Eis a cidade (diziam eles) de perfeita formosura, as delícias de toda a terra!

[[v31-2-16]]

^<<v31-2-16,16>>^ FB. Abriam contra ti a sua boca todos os teus inimigos; assobiavam e rangiam os dentes, dizendo; Devorámo-la! Eis o dia que esperávamos; aqui o temos, aqui o vemos.

[[v31-2-17]]

^<<v31-2-17,17>>^ AIN. O Senhor fez o que tinha planejado, cumpriu a palavra que tinha pronunciado desde os tempos antigos; destruiu sem piedade, alegrou o inimigo a teu respeito, exaltou o poder dos teus adversários.

[[v31-2-18]]

^<<v31-2-18,18>>^ SADE. O seu coração clama ao Senhor! Ó muralha da filha de Sião, faze correr uma como torrente de lágrimas de dia e de noite; não te dês descanso algum. não repouse a pupila dos teus olhos.

[[v31-2-19]]

^<<v31-2-19,19>>^ COF. Levanta-te, ergue clamores de noite, no princípio das vigílias; derrama o teu coração como água diante do Senhor; levanta as tuas mãos para ele, (chorando) pela vida dos teus filhinhos, que desfalecem de fome a todos os cantos das ruas.

[[v31-2-20]]

^<<v31-2-20,20>>^ RBS. Vê, Senhor, e considera: a quem trataste, alguma vez, assim? Há mulheres que comem os frutos das suas entranhas, os filhinhos embalados no seu regaço! São mortos no santuário do Senhor o sacerdote e o profeta!

[[v31-2-21]]

^<<v31-2-21,21>>^ SIN. Jazem por terra, nas ruas, a criança e o velho; as minhas virgens e os meus jovens caíram mortos à espada; tu os mataste no dia do teu furor, feriste-os sem compaixão alguma.

[[v31-2-22]]

^<<v31-2-22,22>>^ TAU. Chamaste, como a um dia de solenidade, os que deviam aterrar-me de todas as partes; não houve no dia do furor do Senhor quem escapasse, quem ficasse com vida; aqueles que acarinhei e criei o meu Inimigo os exterminou.

'''

xref:031-lamentacoes/031-lamentacoes-001.adoc#v31-1-0[&#60; Capítulo Anterior] | <<v31-2-0,Topo>> | xref:031-lamentacoes/031-lamentacoes-003.adoc#v31-3-0[Próximo Capítulo &#62;]