include::./index.adoc[]

[[v52-9-0]]
=== Romanos, 9
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Romanos 9 discute a eleição divina e a soberania de Deus na salvação. Paulo fala sobre como a escolha de Deus não depende do esforço humano ou da linhagem genealógica, mas é baseada na misericórdia e vontade divina. Ele também discute a relação entre judeus e gentios na salvação.
* Mateus 22:14: "Porque muitos são chamados, mas poucos escolhidos". Este versículo enfatiza que a escolha divina é seletiva, e nem todos aqueles que são chamados são escolhidos.
* Efésios 1:5: "Em amor nos predestinou para ele mesmo, para a adoção de filhos por meio de Jesus Cristo, segundo o beneplácito de sua vontade". Isso mostra que Deus nos escolheu para sermos seus filhos antes mesmo da criação do mundo, de acordo com a sua vontade soberana.
* 1 Pedro 2:9: "Mas vós sois a raça eleita, o sacerdócio real, a nação santa, o povo adquirido, para que anuncieis as virtudes daquele que vos chamou das trevas para a sua maravilhosa luz". Este versículo fala sobre como os crentes são um povo escolhido por Deus para proclamar a sua glória.
* João 15:16: "Não fostes vós que me escolhestes a mim; pelo contrário, eu vos escolhi a vós outros e vos designei para que vades e deis fruto, e o vosso fruto permaneça; a fim de que tudo quanto pedirdes ao Pai em meu nome, ele vo-lo conceda". Isso mostra que a escolha daqueles que seguiriam a Jesus é feita por Ele, e não pelo homem.
* Atos 13:48: "Os gentios, ouvindo isto, regozijavam-se e glorificavam a palavra do Senhor; e creram todos quantos haviam sido destinados para a vida eterna". Isso demonstra a ideia de que aqueles que crêem são aqueles que foram destinados à vida eterna por Deus.
****

[[v52-9-1]]

^<<v52-9-1,1>>^ Eu digo a verdade em Cristo, não minto, dando-me testemunho disso a minha consciência (esclarecida) no Espírito Santo:

[[v52-9-2]]

^<<v52-9-2,2>>^ tenho grande tristeza e contínua dor no meu coração.

[[v52-9-3]]

^<<v52-9-3,3>>^ Em verdade, eu mesmo desejava ser anátema separado de Cristo, por amor de meus irmãos, que são do mesmo sangue que eu, segundo a carne, (ver nota)

[[v52-9-4]]

^<<v52-9-4,4>>^ que são israelitas, os quais possuem a adopção de filhos (de Deus), a glória, as alianças, a lei, o culto e as promessas;

[[v52-9-5]]

^<<v52-9-5,5>>^ dos quais (são) os patriarcas, e dos quais é (descendente) o Cristo, segundo a carne, que está sobre todas as coisas. Deus bendito por todos os séculos. Amen.

[[v52-9-6]]

^<<v52-9-6,6>>^ Não é que tenha faltado a palavra de Deus. Porque nem todos os que descendem de Israel, são verdadeiros israelitas (herdeiros das promessas);

[[v52-9-7]]

^<<v52-9-7,7>>^ nem os que são da linhagem de Abraão (são) todos (seus) filhos; mas é em Isaac que terás uma posteridade com o teu nome. (Gn. 21, 12).

[[v52-9-8]]

^<<v52-9-8,8>>^ Isto é, não são os filhos da carne que são filhos de Deus, mas os filhos da promessa é que são considerados como descendentes (de Abraão). (ver nota)

[[v52-9-9]]

^<<v52-9-9,9>>^ Com efeito os termos da promessa são os seguintes: Por este tempo virei, e Sara terá um filho (Gn. 18, 10).

[[v52-9-10]]

^<<v52-9-10,10>>^ E não sòmente ela, mas também (recebeu a promessa) Rebeca, a qual, de um só homem, Isaac, nosso pai, concebeu (dois filhos).

[[v52-9-11]]

^<<v52-9-11,11>>^ Não tendo eles ainda nascido, nem tendo ainda feito bem ou mal (para que permanecesse firme o decreto de Deus (decreto que é) segundo a (sua) escolha),

[[v52-9-12]]

^<<v52-9-12,12>>^ não em vista das obras, mas por causa daquele que chama, foi-lhe dito a ela: O mais velho servirá ao mais novo (Gn. 25, 23),

[[v52-9-13]]

^<<v52-9-13,13>>^ segundo o que está escrito: Amei Jacob, e aborreci Esaú (Ml. 1, 13). (ver nota)

[[v52-9-14]]

^<<v52-9-14,14>>^ Que diremos pois? Há porventura em Deus injustiça? Longe disso.

[[v52-9-15]]

^<<v52-9-15,15>>^ Porque ele disse a Moisés: Eu terei misericórdia com quem me aprouver ter misericórdia e terei piedade de quem me aprouver ter piedade (Ex. 33, 19).

[[v52-9-16]]

^<<v52-9-16,16>>^ Logo (isto) não depende do que quer, nem do que corre, mas de Deus, que usa de misericórdia.

[[v52-9-17]]

^<<v52-9-17,17>>^ De facto, a Escritura diz a Faraó : Para isto te suscitei: para mostrar em ti o meu poder, e a fim de que seja anunciado o meu nome por toda a terra (Ex. 9, 16).

[[v52-9-18]]

^<<v52-9-18,18>>^ Logo, ele tem misericórdia de quem quer e endurece a quem quer. (ver nota)

[[v52-9-19]]

^<<v52-9-19,19>>^ Dir-me-ás, porém : "De que se queixa, pois. Deus? Quem pode resistirá sua vontade?"

[[v52-9-20]]

^<<v52-9-20,20>>^ O homem, quem és tu, para replicares a Deus? Porventura o vaso, de barro, diz a quem o fez : "Por que me fizeste assim ?"

[[v52-9-21]]

^<<v52-9-21,21>>^ Porventura não é o oleiro senhor do barro para poder fazer da mesma massa um vaso para uso honroso, e outro para uso vil ?

[[v52-9-22]]

^<<v52-9-22,22>>^ E se Deus, querendo mostrar a sua ira e tornar manifesto o seu poder, suportou com muita paciência os vasos de ira, preparados (por sua culpa) para a perdição, (ver nota)

[[v52-9-23]]

^<<v52-9-23,23>>^ a fim de mostrar as riquezas da sua glória sobre os vasos de misericórdia, que preparou para a glória (onde está a injustiça ?).

[[v52-9-24]]

^<<v52-9-24,24>>^ (Esses vasos de misericórdia somos) nós, a quem ele também chamou, não só dos Judeus, mas ainda dos gentios.

[[v52-9-25]]

^<<v52-9-25,25>>^ Como diz em Oseias( Os. 2, 23 ; Os. 1, 10 ): Chamarei meu povo o povo não meu, e amado o não amado, e objecto de misericórdia o que não tinha alcançado misericórdia,

[[v52-9-26]]

^<<v52-9-26,26>>^ E acontecerá que, no lugar em que lhes foi dito : Vós não sois meu povo, a i serão chamados filhos de Deus vivo.

[[v52-9-27]]

^<<v52-9-27,27>>^ Acerca de Israel, Isaías exclama: Se for o número dos filhos de Israel como a areia do mar, sòmente as relíquias serão salvas.

[[v52-9-28]]

^<<v52-9-28,28>>^ Porque Deus cumprirá a sua palavra com justiça plena e prontamente sobre a terra (10,22-23).

[[v52-9-29]]

^<<v52-9-29,29>>^ E, ainda como predisse Isaías (Is. 1, 9): Se o Senhor dos Exércitos não tivesse deixado de nós semente, ter-nos-íamos tornado como Sodoma, semelhantes a Gomorra.

[[v52-9-30]]

^<<v52-9-30,30>>^ Que diremos, pois? Que os gentios, que não seguiam a justiça, obtiveram a justiça, aquela justiça que vem da fé.

[[v52-9-31]]

^<<v52-9-31,31>>^ Mas Israel, que se esforçava por praticar uma lei feita para a justiça, não chegou à lei da justiça,

[[v52-9-32]]

^<<v52-9-32,32>>^ Por que causa? Porque (procurou atingi-la ) não pela fé, mas (como se fosse possível) pelas obras. Tropeçou na pedra de tropeço, (ver nota)

[[v52-9-33]]

^<<v52-9-33,33>>^ conforme está escrito: Eis que ponho em Sião uma pedra de tropeço, uma pedra de escândalo; mas todo aquele que crê nele, não será confundido ( Is. 8, 14 ; Is. 28, 16 ).

'''

xref:052-romanos/052-romanos-008.adoc#v52-8-0[&#60; Capítulo Anterior] | <<v52-9-0,Topo>> | xref:052-romanos/052-romanos-010.adoc#v52-10-0[Próximo Capítulo &#62;]