include::./index.adoc[]

[[v52-8-0]]
=== Romanos, 8
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Romanos 8 é um capítulo fundamental na teologia cristã, apresentando a vida no Espírito e a esperança da salvação para todos os que creem em Jesus Cristo. Entre os temas abordados neste capítulo estão a libertação do pecado, a adoção como filhos de Deus, a vida no Espírito e a segurança da salvação.
* 2 Coríntios 3:17: "Ora, o Senhor é o Espírito e, onde está o Espírito do Senhor, ali há liberdade." Paulo fala sobre a vida no Espírito em Romanos 8 e em 2 Coríntios 3, destacando a liberdade que é encontrada em Cristo.
* Gálatas 4:5-7: "para resgatar os que estavam sob a lei, a fim de que recebêssemos a adoção de filhos. E, porque vocês são filhos, Deus enviou o Espírito de seu Filho ao nosso coração, o qual clama: "Aba, Pai!" Assim, você já não é mais escravo, mas filho; e, por ser filho, Deus também o tornou herdeiro." Romanos 8 fala sobre a adoção como filhos de Deus e a libertação da escravidão do pecado, e esses temas também são abordados em Gálatas 4.
* Efésios 1:13-14: "Nele, quando vocês ouviram e creram na palavra da verdade, o evangelho que os salvou, vocês foram selados com o Espírito Santo da promessa, que é a garantia da nossa herança até a redenção daqueles que pertencem a Deus, para o louvor da sua glória." Paulo destaca a segurança da salvação em Romanos 8 e em Efésios 1, lembrando que os crentes são selados pelo Espírito Santo como garantia da herança eterna.
* João 1:12-13: "Mas a todos que o receberam, aos que creem em seu nome, deu-lhes o direito de se tornarem filhos de Deus, os quais não nasceram por descendência natural, nem pela vontade da carne nem pela vontade de algum homem, mas nasceram de Deus." A adoção como filhos de Deus é um tema central em Romanos 8, e João 1 também destaca que aqueles que creem em Jesus Cristo recebem o direito de se tornarem filhos de Deus.
* Hebreus 9:14: "quanto mais o sangue de Cristo, que pelo Espírito eterno se ofereceu de forma imaculada a Deus, purificará a nossa consciência de atos que levam à morte, para que sirvamos ao Deus vivo!" Romanos 8 destaca a libertação do poder do pecado e da morte, e Hebreus 9 enfatiza que é o sangue de Cristo que purifica nossas consciências de atos que levam à morte.
****

[[v52-8-1]]

^<<v52-8-1,1>>^ Não há, pois, agora nenhuma condenação para os que estão em Jesus Cristo.

[[v52-8-2]]

^<<v52-8-2,2>>^ Com efeito, a lei do espirito de vida em Jesus Cristo me livrou da lei do pecado e da morte. (ver nota)

[[v52-8-3]]

^<<v52-8-3,3>>^ Porquanto, o que era impossível à lei, porque se achava sem força por causa da carne. Deus o realizou, enviando seu Filho em carne semelhante à do pecado, por causa do pecado condenou o pecado na carne, (ver nota)

[[v52-8-4]]

^<<v52-8-4,4>>^ para que a justiça prescrita pela lei fosse cumprida em nós, que não andamos segundo a carne, mas segundo o espírito.

[[v52-8-5]]

^<<v52-8-5,5>>^ Os que são segundo a carne, gostam das coisas que são da carne; mas os que são segundo o espírito gostam das coisas que são do espirito.

[[v52-8-6]]

^<<v52-8-6,6>>^ Ora a aspiração da carne é morte, e a aspiração do espírito é vida e paz.

[[v52-8-7]]

^<<v52-8-7,7>>^ Porque a aspiração da carne é inimiga de Deus, pois não está sujeita à lei de Deus, nem mesmo pode estar.

[[v52-8-8]]

^<<v52-8-8,8>>^ E os que estão na carne, não podem agradar a Deus.

[[v52-8-9]]

^<<v52-8-9,9>>^ Vós, porém, não estais na carne, mas no espírito, se é que o Espírito de Deus habita em vós. Se algum não tem o Espirito de Cristo, não é dele.

[[v52-8-10]]

^<<v52-8-10,10>>^ Se, pois, Cristo está em vós, o corpo verdadeiramente está morto por causa do pecado, mas o espirito é vida, graças à justiça. (ver nota)

[[v52-8-11]]

^<<v52-8-11,11>>^ E, se o Espírito daquele que ressuscitou a Jesus dos mortos, habita em vós, ele, que ressuscitou a Jesus Cristo dos mortos, também dará vida aos vossos corpos mortais, por meio do seu Espírito, que habita em vós.

[[v52-8-12]]

^<<v52-8-12,12>>^ Portanto, Irmãos, não somos devedores à carne, para que vivamos segundo a carne.

[[v52-8-13]]

^<<v52-8-13,13>>^ Efectivamente, se viverdes segundo a carne, morrereis (para a vida da graça), mas se, pelo espirito, fizerdes morrer as obras da carne, vivereis.

[[v52-8-14]]

^<<v52-8-14,14>>^ Porque todos aqueles que são conduzidos pelo Espírito de Deus, são filhos de Deus.

[[v52-8-15]]

^<<v52-8-15,15>>^ Com efeito, não recebestes o espírito de escravidão para estardes novamente com temor, mas recebestes o espírito de adopção (de filhos), mercê do qual clamamos: "Abba, Pai." (ver nota)

[[v52-8-16]]

^<<v52-8-16,16>>^ O mesmo Espírito dá testemunho ao nosso espírito, de que somos filhos de Deus.

[[v52-8-17]]

^<<v52-8-17,17>>^ Se (somos) filhos, também (somos) herdeiros: herdeiros de Deus e co-herdeiros de Cristo; mas isto, se sofrermos com ele, para ser com ele glorificados.

[[v52-8-18]]

^<<v52-8-18,18>>^ Sim, eu tenho por certo que os sofrimentos do tempo presente não têm proporção com a glória vindoura, que se manifestara em nós.

[[v52-8-19]]

^<<v52-8-19,19>>^ Pelo que este mundo espera ansiosamente a manifestação dos filhos de Deus.

[[v52-8-20]]

^<<v52-8-20,20>>^ De facto, o mundo foi sujeito à vaidade, não por seu querer, mas pelo daquele que o sujeitou com a esperança

[[v52-8-21]]

^<<v52-8-21,21>>^ de que também o mundo será livre de sujeição à corrupção, para participar da liberdade gloriosa dos filhos de Deus.

[[v52-8-22]]

^<<v52-8-22,22>>^ Porque sabemos que todas as criaturas gemem e estão como que com dores de parto até agora. (ver nota)

[[v52-8-23]]

^<<v52-8-23,23>>^ E não só elas, mas também nós, que temos as primícias do Espirito; também gememos dentro de nós mesmos, esperando a adopção (de filhos de Deus), a redenção do nosso corpo. (ver nota)

[[v52-8-24]]

^<<v52-8-24,24>>^ Com efeito, na esperança é que fomos salvos. Ora a esperança que se vê, não é esperança; porque, como esperar aquilo que se vê?

[[v52-8-25]]

^<<v52-8-25,25>>^ E, se esperamos o que não vemos, com paciência o esperamos. (ver nota)

[[v52-8-26]]

^<<v52-8-26,26>>^ O Espírito ajuda também a nossa fraqueza, porque não sabemos o que havemos de pedir, como convém, mas o mesmo Espírito ora por nós com gemidos inefáveis.

[[v52-8-27]]

^<<v52-8-27,27>>^ E o que perscruta os corações, sabe o que deseja o Espirito, porque ele pede segundo (a vontade de) Deus pelos santos.

[[v52-8-28]]

^<<v52-8-28,28>>^ Ora nós sabemos que todas as coisas concorrem para o bem daqueles que amam a Deus, para o bem daqueles que, segundo o seu desígnio, foram chamados.

[[v52-8-29]]

^<<v52-8-29,29>>^ Porque os que ele conheceu na sua presciência, também os predestinou para serem conformes à imagem de seu Filho, para que ele seja o primogênito entre muitos irmãos.

[[v52-8-30]]

^<<v52-8-30,30>>^ E aqueles que predestinou, também os chamou; e aqueles que chamou, também os justificou; e aqueles que justificou, também os glorificou.

[[v52-8-31]]

^<<v52-8-31,31>>^ Que diremos, pois, à vista destas coisas? Se Deus é por nós, quem será contra nós?

[[v52-8-32]]

^<<v52-8-32,32>>^ O que não poupou nem o seu próprio Filho, mas por nós todos o entregou ( à morte), como não nos dará também com ele todas as coisas?

[[v52-8-33]]

^<<v52-8-33,33>>^ Quem acusará os escolhidos de Deus? Deus é que justifica.

[[v52-8-34]]

^<<v52-8-34,34>>^ Quem os condenará? Jesus Cristo é o que morreu, e ainda mais o que ressuscitou, o que está à direita de Deus, o que também intercede por nós.

[[v52-8-35]]

^<<v52-8-35,35>>^ Quem nos separará, pois, do amor de Cristo? (Será) a tribulação? a angústia? a perseguição? a fome? a nudez? o perigo? a espada?

[[v52-8-36]]

^<<v52-8-36,36>>^ Segundo está escrito: Por ti somos entregues à morte todos os dias, somos reputados como ovelhas para o matadouro (Ps. 43, 23).

[[v52-8-37]]

^<<v52-8-37,37>>^ Mas de todas estas coisas saímos mais que vencedores por aquele que nos amou.

[[v52-8-38]]

^<<v52-8-38,38>>^ Porque eu estou certo que nem a morte, nem a vida, nem os anjos, nem os principados, nem as coisas presentes, nem as futuras, nem as virtudes,

[[v52-8-39]]

^<<v52-8-39,39>>^ nem a altura, nem á profundidade, nem nenhuma outra criatura nos poderá separar do amor que Deus nos manifesta em Jesus Cristo Nosso Senhor.

'''

xref:052-romanos/052-romanos-007.adoc#v52-7-0[&#60; Capítulo Anterior] | <<v52-8-0,Topo>> | xref:052-romanos/052-romanos-009.adoc#v52-9-0[Próximo Capítulo &#62;]