include::./index.adoc[]

[[v52-7-0]]
=== Romanos, 7
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Romanos 7 aborda a luta interna do cristão entre a carne e o Espírito. O capítulo destaca a natureza pecaminosa da carne e a incapacidade do homem em alcançar a justiça por suas próprias forças. Paulo expressa sua própria batalha contra o pecado e a sua necessidade de um Salvador para libertá-lo da escravidão do pecado.
* Salmos 51:5: "Eis que em iniquidade fui formado, e em pecado me concebeu minha mãe." Este versículo destaca a natureza pecaminosa do homem desde o seu nascimento e se relaciona com a ideia apresentada em Romanos 7:18-20, em que Paulo reconhece a sua natureza pecaminosa.
* Romanos 6:23: "Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus nosso Senhor." Este versículo destaca a necessidade de salvação pela fé em Jesus Cristo, tema que é enfatizado em Romanos 7:24-25.
* Gálatas 5:16-17: "Digo, porém: Andai no Espírito, e jamais satisfareis à concupiscência da carne. Porque a carne cobiça contra o Espírito, e o Espírito contra a carne; e estes opõem-se um ao outro, para que não façais o que quereis." Este versículo se relaciona com a luta entre a carne e o Espírito que é abordada em Romanos 7:14-23.
* Romanos 8:2: "Porque a lei do Espírito da vida, em Cristo Jesus, te livrou da lei do pecado e da morte." Este versículo destaca a libertação do homem da escravidão do pecado por meio de Jesus Cristo, tema que é apresentado em Romanos 7:24-25.
* 1 João 1:8-10: "Se dissermos que não temos pecado nenhum, a nós mesmos nos enganamos, e a verdade não está em nós. Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados, e nos purificar de toda injustiça. Se dissermos que não temos cometido pecado, fazemo-lo mentiroso, e a sua palavra não está em nós." Este versículo destaca a necessidade de reconhecer a própria natureza pecaminosa e de buscar a salvação em Jesus Cristo, temas que são abordados em Romanos 7:14-25.
****

[[v52-7-1]]

^<<v52-7-1,1>>^ Porventura ignorais vós, irmãos (pois que falo com pessoas que conhecem a lei), que a lei só tem domínio sobre o homem enquanto ele vive ?

[[v52-7-2]]

^<<v52-7-2,2>>^ Assim a mulher está ligada pela lei ao marido, enquanto ele vive ; mas ao morrer seu marido, fica livre da lei do marido.

[[v52-7-3]]

^<<v52-7-3,3>>^ Por isso, vivendo o marido, será chamada adúltera, se estiver com outro homem; mas se morrer seu marido, fica livre desta lei, de maneira que não é adúltera, se se tornar mulher de outro homem.

[[v52-7-4]]

^<<v52-7-4,4>>^ Assim, Irmãos meus, também vós estais mortos à lei pelo corpo de Cristo, para que sejais de outro, daquele que ressuscitou dos mortos, a fim de que demos frutos para Deus. (ver nota)

[[v52-7-5]]

^<<v52-7-5,5>>^ Enquanto estávamos na carne, os afectos pecaminosos, excitados pela lei, actuavam em nossos membros, para produzirem frutos de morte. (ver nota)

[[v52-7-6]]

^<<v52-7-6,6>>^ Mas agora estamos livres da lei, mortos para aquilo que nos tinha cativos, a fim de que sirvamos (a Deus) segundo o novo espirito (que é a graça do Espirito Santo), e não segundo a antiga letra (da lei de Moisés).

[[v52-7-7]]

^<<v52-7-7,7>>^ Que diremos pois? A lei é pecado? Longe disso. Mas eu não conheci o pecado, senão pela lei, porque eu não conheceria a concupiscência, se a lei não dissesse: não desejarás o mal (Ex. 20, 17).

[[v52-7-8]]

^<<v52-7-8,8>>^ E o pecado, tomando ocasião daquele mandamento, fez nascer em mim toda a concupiscência. Com efeito, sem a lei, o pecado estava morto. (ver nota)

[[v52-7-9]]

^<<v52-7-9,9>>^ Eu outrora vivia sem lei, mas, quando veio o mandamento, reviveu o pecado. (ver nota)

[[v52-7-10]]

^<<v52-7-10,10>>^ E eu morri, e viu-se que o mandamento, que me era para vida, foi para morte,

[[v52-7-11]]

^<<v52-7-11,11>>^ porque o pecado, tomando ocasião do mandamento, seduziu-me e por ele me matou.

[[v52-7-12]]

^<<v52-7-12,12>>^ Assim pois, a lei (é) santa, e o mandamento (é) santo, justo e bom.

[[v52-7-13]]

^<<v52-7-13,13>>^ Uma coisa boa foi, então, para mim causa de morte? Não, absolutamente. Mas foi o pecado que, para se mostrar pecado, me deu a morte (espiritual) por meio de uma coisa boa, a fim de que, pelo mandamento, o pecado mostrasse ao máximo a sua nocividade.

[[v52-7-14]]

^<<v52-7-14,14>>^ Efectivamente sabemos que a lei é espiritual, mas eu sou carnal, vendido como escravo ao pecado. (ver nota)

[[v52-7-15]]

^<<v52-7-15,15>>^ Em verdade, não entendo o que faço; não faço o (bem) que quero, mas faço o (mal) que não quero.

[[v52-7-16]]

^<<v52-7-16,16>>^ Ora, se eu faço o que não quero, reconheço (por isso), que a lei é boa.

[[v52-7-17]]

^<<v52-7-17,17>>^ Neste caso já não sou eu (na parte mais nobre do meu ser) que faço isto, mas sim o pecado (isto é a concupiscência), que habita em mim.

[[v52-7-18]]

^<<v52-7-18,18>>^ Eu sei que em mim, isto é, na minha carne, não habita o bem. Querer o bem encontra-se ao meu alcance, mas não fazê-lo.

[[v52-7-19]]

^<<v52-7-19,19>>^ Porque eu não faço o bem que quero, mas faço o mal que não quero.

[[v52-7-20]]

^<<v52-7-20,20>>^ Se eu, porém, faço o que não quero, não sou eu já que o faço, mas sim o pecado que habita em mim.

[[v52-7-21]]

^<<v52-7-21,21>>^ Eu encontro, pois, esta lei em mim : quando quero fazer o bem, o mal está junto de mim,

[[v52-7-22]]

^<<v52-7-22,22>>^ porque me deleito na lei de Deus, segundo o homem interior,

[[v52-7-23]]

^<<v52-7-23,23>>^ mas vejo dos meus membros uma outra lei, que se opõe à lei do meu espírito e que me faz escravo da lei do pecado, que está nos meus membros.

[[v52-7-24]]

^<<v52-7-24,24>>^ Infeliz de mim! Quem me livrará deste corpo de morte (isto é, em que habita o pecado, que é causa de morte espiritual)?

[[v52-7-25]]

^<<v52-7-25,25>>^ Sejam dadas graças a Deus, por Jesus Cristo Nosso Senhor. Assim, pois, eu mesmo sirvo à lei de Deus com o espírito; e sirvo à lei do pecado com a carne. (ver nota)

'''

xref:052-romanos/052-romanos-006.adoc#v52-6-0[&#60; Capítulo Anterior] | <<v52-7-0,Topo>> | xref:052-romanos/052-romanos-008.adoc#v52-8-0[Próximo Capítulo &#62;]