include::./index.adoc[]

[[v52-3-0]]
=== Romanos, 3
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Romanos 3 trata sobre a universalidade do pecado e a justificação pela fé em Jesus Cristo. O capítulo enfatiza que todos pecaram e estão destituídos da glória de Deus, e que a salvação não é alcançada por meio da observância da lei, mas pela fé em Jesus Cristo.
* Isaías 53:6: "Todos nós andávamos desgarrados como ovelhas; cada um se desviava pelo seu caminho; mas o Senhor fez cair sobre ele a iniquidade de nós todos." Este versículo retrata a condição universal do pecado, que é mencionada em Romanos 3:23.
* Salmos 14:3: "Desviaram-se todos e juntamente se fizeram imundos: não há quem faça o bem, não há sequer um." Este versículo também ressalta a universalidade do pecado, que é enfatizada em Romanos 3:10-12.
* Gálatas 2:16: "Sabendo que o homem não é justificado pelas obras da lei, mas pela fé em Jesus Cristo, temos também crido em Jesus Cristo, para sermos justificados pela fé em Cristo, e não pelas obras da lei; porquanto pelas obras da lei nenhuma carne será justificada." Este versículo reflete o tema central de Romanos 3, que é a justificação pela fé em Jesus Cristo, e não pelas obras da lei.
* Efésios 2:8-9: "Porque pela graça sois salvos, mediante a fé; e isto não vem de vós, é dom de Deus; não de obras, para que ninguém se glorie." Estes versículos também falam sobre a justificação pela fé e não pelas obras, tema que é central em Romanos 3.
* Hebreus 9:22: "E quase todas as coisas, segundo a lei, se purificam com sangue; e sem derramamento de sangue não há remissão." Este versículo enfatiza a importância do sacrifício de Jesus Cristo como forma de expiação dos pecados, tema que é abordado em Romanos 3:25-26.
****

[[v52-3-1]]

^<<v52-3-1,1>>^ Que tem, pois, a mais o judeu? Ou qual é a utilidade da circuncisão?

[[v52-3-2]]

^<<v52-3-2,2>>^ Muita (vantagem têm os Judeus sobre os gentios) de toda a maneira. Principalmente porque lhes foram confiados os oráculos de Deus.

[[v52-3-3]]

^<<v52-3-3,3>>^ Que importa se alguns deles não creram? Porventura a sua incredulidade destruirá a fidelidade de Deus? Não, certamente.

[[v52-3-4]]

^<<v52-3-4,4>>^ Deus é verdadeiro, e todo o homem é mentiroso, como está escrito: Para que sejas (ó Deus) justificado nas tuas palavras e venças quando fores julgado (Ps. 60, 6). (ver nota)

[[v52-3-5]]

^<<v52-3-5,5>>^ Se, porém, a nossa injustiça faz brilhar a justiça de Deus, que diremos? Porventura é injusto Deus que castiga?

[[v52-3-6]]

^<<v52-3-6,6>>^ (Falo à maneira dos homens.) Não, por certo ; doutra maneira, como julgaria Deus este mundo? (ver nota)

[[v52-3-7]]

^<<v52-3-7,7>>^ Com efeito, se a verdade de Deus, pela minha mentira cresceu para glória sua, porque sou eu assim julgado como pecador? (ver nota)

[[v52-3-8]]

^<<v52-3-8,8>>^ E porque e que (como dizem caluniosamente de nós, como alguns afirmam que nós dizemos) não havemos de fazer o mal para que venham bens? Destes é justa a condenação.

[[v52-3-9]]

^<<v52-3-9,9>>^ Que (concluir) pois? Temos alguma vantagem sobre eles? De nenhuma sorte. Porque já demonstramos que Judeus e Gregos estão todos sob o pecado,

[[v52-3-10]]

^<<v52-3-10,10>>^ como está escrito: Não há nenhum justo;

[[v52-3-11]]

^<<v52-3-11,11>>^ não há quem tenha inteligência, não há quem busque a Deus.

[[v52-3-12]]

^<<v52-3-12,12>>^ Todos se extraviaram, todos à uma se tornaram inúteis, não há quem faça o bem, não há sequer um (8. 14-1-3).

[[v52-3-13]]

^<<v52-3-13,13>>^ A garganta deles é um sepulcro aberto; com as suas línguas tecem enganos. Um veneno de áspides se encobre debaixo dos seus lábios (Ps. 5, 10 ; Ps. 140, 4);

[[v52-3-14]]

^<<v52-3-14,14>>^ a sua boca está cheia de maldição e de amargura (Ps. 10, 7).

[[v52-3-15]]

^<<v52-3-15,15>>^ Os seus pés são velozes para derramar sangue;

[[v52-3-16]]

^<<v52-3-16,16>>^ a dor e a infelicidade estão nos seus caminhos,

[[v52-3-17]]

^<<v52-3-17,17>>^ e não conheceram o caminho da paz (Is. 59, 7-8).

[[v52-3-18]]

^<<v52-3-18,18>>^ Não há temor de Deus diante dos seus olhos (Ps. 36, 2).

[[v52-3-19]]

^<<v52-3-19,19>>^ Ora nós sabemos que tudo aquilo que a lei diz, o diz para aqueles que estão sob a lei, para que toda a boca seja fechada e todo o mundo caia sob a justiça de Deus.

[[v52-3-20]]

^<<v52-3-20,20>>^ Pelas obras da lei não será justificado nenhum homem diante dele. Efetivamente, pela lei vem o conhecimento do pecado. (ver nota)

[[v52-3-21]]

^<<v52-3-21,21>>^ Mas agora manifestou-se sem a lei a justiça de Deus, testificada pela lei e pelos profetas. (ver nota)

[[v52-3-22]]

^<<v52-3-22,22>>^ A justiça de Deus (é infundada) pela fé de Jesus Cristo em todos e sobre todos os que crêem nele, sem distinção,

[[v52-3-23]]

^<<v52-3-23,23>>^ porque todos pecaram e estão privados da glória de Deus

[[v52-3-24]]

^<<v52-3-24,24>>^ e são justificados gratuitamente pela sua graça, por meio da redenção, que está em Jesus Cristo, (ver nota)

[[v52-3-25]]

^<<v52-3-25,25>>^ a quem Deus pôs, pelo seu sangue derramado, como um meio de propiciação, que opera pela fé, a fim de manifestar a sua justiça, por haver tolerado, com a sua paciência divina os pecados de outrora,

[[v52-3-26]]

^<<v52-3-26,26>>^ a fim de manifestar a sua justiça no tempo presente, de maneira a ser reconhecido justo e fonte de justiça para aquele que tem fé em Jesus Cristo.

[[v52-3-27]]

^<<v52-3-27,27>>^ Onde está, pois, (ó judeu) a tua glória? Foi excluída. Por que lei? Pela das obras? Não; mas pela lei da fé. (ver nota)

[[v52-3-28]]

^<<v52-3-28,28>>^ Porquanto sustentamos que o homem é justificado pela fé, sem as obras da lei. (ver nota)

[[v52-3-29]]

^<<v52-3-29,29>>^ Porventura Deus só o é dos Judeus? Não o é ele também dos gentios? Sim, certamente, ele o é também dos gentios, (ver nota)

[[v52-3-30]]

^<<v52-3-30,30>>^ porque há um só Deus, que justifica pela fé os circuncidados e que também pela fé justifica os incircuncidados.

[[v52-3-31]]

^<<v52-3-31,31>>^ Destruímos nós, pois, a lei com a fé? Longe disso; antes confirmamos a lei.

'''

xref:052-romanos/052-romanos-002.adoc#v52-2-0[&#60; Capítulo Anterior] | <<v52-3-0,Topo>> | xref:052-romanos/052-romanos-004.adoc#v52-4-0[Próximo Capítulo &#62;]