include::./index.adoc[]

[[v15-3-0]]
=== Esdras, 3
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Esdras 3 descreve a reconstrução do altar e a celebração da Festa dos Tabernáculos pelos judeus recém-chegados a Jerusalém. O capítulo também menciona o início da construção do templo e a alegria dos sacerdotes e levitas diante desse projeto.
* Salmos 100:4: "Entrai pelas portas dele com gratidão, e em seus átrios com louvor; louvai-o, e bendizei o seu nome." Este versículo incentiva os crentes a entrar no templo de Deus com gratidão e louvor, como os judeus fizeram durante a celebração da Festa dos Tabernáculos.
* Esdras 6:16: "E os filhos de Israel, os sacerdotes e os levitas, e o restante dos filhos da cativeira, fizeram a dedicação desta casa de Deus com alegria." Esse versículo descreve a dedicação do templo reconstruído em Jerusalém, que foi um momento de grande alegria para os judeus.
* Esdras 6:22: "E celebraram a festa dos pães asmos por sete dias com alegria; porque o SENHOR os alegrara, e tinha mudado o coração do rei da Assíria para com eles, a fim de fortalecê-los na obra da casa de Deus, o Deus de Israel." Este versículo descreve como os judeus celebraram a Festa dos Pães Asmos depois de completarem a construção do templo em Jerusalém.
* 1 Crônicas 16:34: "Louvai ao SENHOR, porque ele é bom; porque a sua benignidade dura para sempre." Este versículo é um convite para louvar a bondade de Deus, o que é relevante para a celebração da Festa dos Tabernáculos em Esdras 3.
* Ageu 2:9: "A glória desta última casa será maior do que a da primeira, diz o SENHOR dos Exércitos, e neste lugar darei a paz, diz o SENHOR dos Exércitos." Esse versículo é uma profecia que aponta para a glória do templo reconstruído e é relevante para a emoção sentida pelos judeus durante a construção do templo em Esdras 3.
****

[[v15-3-1]]

^<<v15-3-1,1>>^ Tinha já chegado o sétimo mês, e os filhos de Israel estavam nas suas cidades, quando o povo se reuniu como um só homem em Jerusalém.

[[v15-3-2]]

^<<v15-3-2,2>>^ Josué, filho de Josedec, levantou-se com seus irmãos sacerdotes, com Zorobabel, filho de Salatiel, e seus irmãos, e começaram a edificar o altar do Deus de Israel, para oferecerem nele holocaustos, conforme o que está escrito na lei de Moisés, homem de Deus.

[[v15-3-3]]

^<<v15-3-3,3>>^ Colocaram o altar de Deus sobre as suas bases, apesar de os povos dos países circunvizinhos lhes incutirem terror, e ofereceram ao Senhor sobre o altar o holocausto da manhã e da tarde.

[[v15-3-4]]

^<<v15-3-4,4>>^ Depois celebraram a solenidade dos tabernáculos, como está prescrito, e ofereceram o holocausto quotidiano, segundo a sua ordem, conforme está mandado observar, dia por dia.

[[v15-3-5]]

^<<v15-3-5,5>>^ Depois disto, ofereceram o holocausto perpétuo, os das neoménias e de todas as solenidades consagradas ao Senhor, assim como os daqueles que faziam uma oferta espontânea ao Senhor.

[[v15-3-6]]

^<<v15-3-6,6>>^ Desde o primeiro dia do sétimo mês começaram a oferecer o holocausto ao Senhor, porém ainda não tinham sido lançados os fundamentos do templo de Deus.

[[v15-3-7]]

^<<v15-3-7,7>>^ Deram dinheiro aos canteiros e carpinteiros, e deram víveres, bebidas e azeite aos Sidónios e aos Tirios, para que transportassem madeira de cedro do Líbano, por mar, até Jope, conforme o que lhes linha ordenado Ciro, rei dos Persas.

[[v15-3-8]]

^<<v15-3-8,8>>^ No segundo ano da sua chegada ao (lugar do) templo de Deus em Jerusalém, no segundo mês, Zorobabel, filho de Salatiel, e Josué, filho de Josedec, e os outros seus irmãos sacerdotes e Levitas, bem como todos os que tinham vindo do cativeiro para Jerusalém, puseram mãos à obra e encarregaram os Levitas, de vinte anos para cima, de vigiar os trabalhos do templo do Senhor.

[[v15-3-9]]

^<<v15-3-9,9>>^ Josué, com seus filhos e seus irmãos, Cedmiel e seus filhos, filhos de Judá, dispuseram-se unânimamente a dirigir os que trabalhavam no templo de Deus; igualmente (se dispuseram) os filhos de Henadad, com seus filhos e irmãos, Levitas.

[[v15-3-10]]

^<<v15-3-10,10>>^ Lançados, pois, os fundamentos do templo do Senhor pelos pedreiros, apresentaram-se os sacerdotes revestidos dos seus ornamentos e com as trombetas, e os Levitas, filhos de Asaf, com címbalos, para louvarem a Deus com os salmos de David, rei de Israel.

[[v15-3-11]]

^<<v15-3-11,11>>^ Cantavam hinos e davam glória ao Senhor (dizendo): Que ele é bom, e é eterna a sua misericórdia sobre Israel. Todo o povo também levantava grandes clamores, louvando o Senhor, por terem sido lançados os fundamentos do templo do Senhor.

[[v15-3-12]]

^<<v15-3-12,12>>^ Muitos dos sacerdotes, dos Levitas, dos chefes das familias e dos anciãos, que tinham visto o primeiro templo, vendo lançar diante dos seus olhos os fundamentos deste outro templo, choravam em alta voz; (por outro lado) muitos soltavam gritos de alegria, de contentamento.

[[v15-3-13]]

^<<v15-3-13,13>>^ Ninguém podia distinguir os gritos dos que se regozijavam, da voz de choro do povo, porque o povo gritava confusamente com grande clamor, cujo ruído se ouvia ao longe.

'''

xref:015-esdras/015-esdras-002.adoc#v15-2-0[&#60; Capítulo Anterior] | <<v15-3-0,Topo>> | xref:015-esdras/015-esdras-004.adoc#v15-4-0[Próximo Capítulo &#62;]