include::./index.adoc[]

[[v15-10-0]]
=== Esdras, 10
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 10 de Esdras fala sobre a restauração da aliança de Deus com o povo de Israel, após a descoberta de que muitos dos líderes judeus haviam se casado com mulheres estrangeiras, o que era proibido pela Lei de Deus. A solução encontrada foi que esses líderes deveriam se divorciar dessas mulheres, a fim de se purificar e se reconciliar com Deus. Aqui estão cinco versículos relacionados com os temas abordados neste capítulo:
* Deuteronômio 7:3-4: "Não se unam em matrimônio com elas, e não permitam que seus filhos se casem com os filhos delas, pois eles os desviariam para adorar outros deuses. Isso levaria à ira do Senhor contra vocês e resultaria na sua destruição rapidamente." Este versículo se relaciona com o tema de Esdras 10, já que os líderes judeus haviam se casado com mulheres estrangeiras, o que era considerado uma violação da Lei de Deus.
* Esdras 9:2: "Eles trouxeram algumas das filhas deles como esposas para os seus filhos, e assim a raça santa ficou misturada com os povos estrangeiros que viviam naquela terra. Os líderes e autoridades judeus foram os primeiros a fazer isso, e isso se tornou um grave pecado." Esse versículo mostra como o casamento com mulheres estrangeiras era considerado um pecado grave pelos líderes judeus.
* Malaquias 2:11: "Judá tem sido infiel, e um ato abominável foi cometido em Israel e em Jerusalém. Judá profanou o santuário do Senhor, o qual ele ama, e se casou com a filha de um deus estrangeiro." Este versículo se relaciona com o tema de Esdras 10, pois mostra como o casamento com mulheres estrangeiras era considerado uma forma de infidelidade e uma profanação do santuário de Deus.
* Esdras 10:3: "Portanto, façamos agora uma aliança com o nosso Deus, para repudiarmos todas essas mulheres estrangeiras e seus filhos, conforme o conselho do meu senhor e dos que tremem diante dos mandamentos do nosso Deus. Que se faça conforme a Lei!" Este versículo mostra como os líderes judeus decidiram se arrepender e se purificar, seguindo a Lei de Deus e repudiando as mulheres estrangeiras.
* 1 Coríntios 7:39: "A mulher está ligada a seu marido enquanto ele viver. Mas se o marido morrer, ela fica livre para se casar com quem quiser, contanto que seja no Senhor." Esse versículo fala sobre a importância de se casar com pessoas que compartilham da mesma fé e valores, o que está relacionado ao tema de Esdras 10, já que os líderes judeus foram exortados a se divorciar das mulheres estrangeiras e buscar uma reconciliação com Deus.
****

[[v15-10-1]]

^<<v15-10-1,1>>^ Enquanto Esdras, chorando, fazia esta oração e esta confissão, prostrado diante do templo de Deus, uma grande multidão de Israel, de homens, mulheres e meninos, juntou-se ao pé dele, e o povo irrompeu num pranto desfeito.

[[v15-10-2]]

^<<v15-10-2,2>>^ Então Sequenias, filho de Jeiel, dos filhos de Elão, respondeu a Esdras: Nós prevaricámos contra o nosso Deus, tomámos mulheres estrangeiras dos povos desta terra. Contudo, agora, se Israel se arrepende disto,

[[v15-10-3]]

^<<v15-10-3,3>>^ façamos um pacto com o Senhor nosso Deus, de que lançaremos fora todas as mulheres e os filhos nascidos delas, conformando-nos com a vontade do Senhor e com a dos que respeitam os preceitos do Senhor nosso Deus. Faça-se segundo a Lei.

[[v15-10-4]]

^<<v15-10-4,4>>^ Levanta-te, a ti pertence resolver. Nós seremos contigo. Cobra alento, e põe mãos à obra.

[[v15-10-5]]

^<<v15-10-5,5>>^ Levantou-se Esdras e obrigou a jurar aos chefes dos sacerdotes, dos Levitas e de todo o Israel, que fariam como se acabava de dizer, e eles o juraram .

[[v15-10-6]]

^<<v15-10-6,6>>^ Esdras partiu de diante da casa de Deus, e foi a casa de Joanan, filho de Elisib; entrando ali, não comeu pão nem bebeu água, porque chorava o pecado daqueles que tinham voltado do cativeiro.

[[v15-10-7]]

^<<v15-10-7,7>>^ Deitou-se um pregão, em Judá e em Jerusalém, a todos os filhos que tinham vindo do cativeiro, para que se juntassem em Jerusalém.

[[v15-10-8]]

^<<v15-10-8,8>>^ A todo o que não comparecesse dentro de três dias, conforme a ordem dos chefes e dos anciãos, lhe seriam confiscados todos os seus bens; (além disso) esse tal seria lançado fora do ajuntamento dos que tinham vindo do cativeiro.

[[v15-10-9]]

^<<v15-10-9,9>>^ Concorreram, portanto, todos os homens de Judá e de Benjamim, dentro de três dias, a Jerusalém, no dia vinte do nono mês. Todo o povo compareceu na praça do templo de Deus, tremendo por causa dos seus pecados e por causa das chuvas. (ver nota)

[[v15-10-10]]

^<<v15-10-10,10>>^ O sacerdote Esdras levantou-se e diese-lhes: Vós prevaricastes, casando com mulheres estrangeiras, acrescentando este aos outros delitos de Israel.

[[v15-10-11]]

^<<v15-10-11,11>>^ Agora, confessai o vosso pecado ao Senhor Deus de vossos pais e fazei o que é do seu agrado ; separai-vos dos povos desta terra e das mulheres estrangeiras.

[[v15-10-12]]

^<<v15-10-12,12>>^ Toda a multidão respondeu em alta voz: Faça-se como nos disseste.

[[v15-10-13]]

^<<v15-10-13,13>>^ Todavia, como o povo é numeroso e é tempo de chuva, não podemos estar de fora; demais, isto não é obra de um dia nem de dois, porque gravissimamente pecámos.

[[v15-10-14]]

^<<v15-10-14,14>>^ Estabeleçam-se alguns chefes para representar toda a multidão; todos os que em nossas cidades casaram com mulheres estrangeiras venham em tempos determinados, juntamente com os anciãos e os magistrados de cada cidade, até que se aparte de nós a ira do nosso Deus, por causa deste pecado.

[[v15-10-15]]

^<<v15-10-15,15>>^ Opuseram-se a isto Jonatan, filho de Azael, e Jaasia, filho de Tecué, apoiados pelos Levitas Mosolão e Sebetai.

[[v15-10-16]]

^<<v15-10-16,16>>^ Todavia os filhos (que tinham vindo) do cativeiro fizeram conforme havia sido proposto. Esdras, sacerdote, e os chefes das familias segundo as casas dos seus pais designados todos pelos seus nomes, sentaram-se (no seu tribunal) no primeiro dia do décimo mês para examinar o assunto.

[[v15-10-17]]

^<<v15-10-17,17>>^ Acabaram de fazer a conta de todos os homens que tinham tomado mulheres estrangeiras, no primeiro dia do primeiro mês,

[[v15-10-18]]

^<<v15-10-18,18>>^ Dos filhos dos sacerdotes, achou-se que tinham casado com mulheres estrangeiras os seguintes: Dos filhos de Josué, filho de Josedec, e seus irmãos, acharam -se : Maasia, Eliezer, Jarib e Godolia.

[[v15-10-19]]

^<<v15-10-19,19>>^ Estes prometeram, estendendo a sua mão, despedir suas mulheres e oferecer um carneiro do rebanho pelo seu delito.

[[v15-10-20]]

^<<v15-10-20,20>>^ Dos filhos de Emer: Hanani e Zebedia.

[[v15-10-21]]

^<<v15-10-21,21>>^ Dos filhos de Harim : Maasia, Elia, Semeia, Jeiel e Ozias.

[[v15-10-22]]

^<<v15-10-22,22>>^ Dos filhos de Fasur: Elioenai, Maasia, Ismael, Nalauael, Jozabed e Blasa.

[[v15-10-23]]

^<<v15-10-23,23>>^ Dos filhos dos Levitas: Jozabed, Semei e Celaia, chamado também Calila, Falaia, Judà e Eliezer.

[[v15-10-24]]

^<<v15-10-24,24>>^ Dos cantores: Eliasib. Dos porteiros: Seium, Telem e Uri.

[[v15-10-25]]

^<<v15-10-25,25>>^ (Do povo) de Israel : Dos filhos de Faros: Remeia, Jezia, Melquia, Miamin, Eliezer, Melquia e Banaias;

[[v15-10-26]]

^<<v15-10-26,26>>^ dos filhos de Elão: Matania, Zacarias, Jeiel, Abdi, Jerimot e Elia;

[[v15-10-27]]

^<<v15-10-27,27>>^ dos filhos de Zetua : Elioenai, Eliasib. Matania, Jerimot, Zabad e Aziza;

[[v15-10-28]]

^<<v15-10-28,28>>^ dos filhos de Bebai: Joanan, Hanauia, Zabai e Alalai;

[[v15-10-29]]

^<<v15-10-29,29>>^ dos filhos de Bani: Mosolão, Meiuc, Adaia, Jasub, Saal e Ramot;

[[v15-10-30]]

^<<v15-10-30,30>>^ dos filhos de Faat-Moab: Edna, Calai, Banaias. Maasias, Màtanias, Beseleel, Benui e Manassés;

[[v15-10-31]]

^<<v15-10-31,31>>^ dos filhos de Harim: Eliezer, Jesias, Melquias. Semeias, Simeão,

[[v15-10-32]]

^<<v15-10-32,32>>^ Benjamim, Maloc, Samarias;

[[v15-10-33]]

^<<v15-10-33,33>>^ dos filhos de Hasom : Matanai, Malata, Zabad, Elifelet, Jermai, Manassés e Semei;

[[v15-10-34]]

^<<v15-10-34,34>>^ dos filhos de Bani: Maadí, Amrão, Vel,

[[v15-10-35]]

^<<v15-10-35,35>>^ Banaias, Badaias, Queliau,

[[v15-10-36]]

^<<v15-10-36,36>>^ Vania, Merimul, Eliasib,

[[v15-10-37]]

^<<v15-10-37,37>>^ Malanías, Malanai, Jasi,

[[v15-10-38]]

^<<v15-10-38,38>>^ Bani, Benui, Semei,

[[v15-10-39]]

^<<v15-10-39,39>>^ Salmias, Natan, Adaías,

[[v15-10-40]]

^<<v15-10-40,40>>^ Mecnedebai, Sisai, Sarai,

[[v15-10-41]]

^<<v15-10-41,41>>^ Ezrel, Selemiau, Semeria,

[[v15-10-42]]

^<<v15-10-42,42>>^ Seium, Amaria, José;

[[v15-10-43]]

^<<v15-10-43,43>>^ dos filhos de Nebo; Jeiel, Matalias, Zabad, Zabina, Jedu, Joel, Banaias.

[[v15-10-44]]

^<<v15-10-44,44>>^ Todos estes tinham tomado mulheres estrangeiras, e destas havia algumas que tinham tido filhos.

'''

xref:015-esdras/015-esdras-009.adoc#v15-9-0[&#60; Capítulo Anterior] | <<v15-10-0,Topo>> | xref:016-neemias/016-neemias-001.adoc#v16-1-0[Próximo Capítulo &#62;]