include::./index.adoc[]

[[v61-6-0]]
=== I Timóteo, 6
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 6 de 1 Timóteo trata principalmente de temas relacionados ao dinheiro e à riqueza, enfatizando a importância de não colocar nossa confiança em bens materiais, mas em Deus. Além disso, o capítulo aborda a importância de se evitar contendas e conflitos desnecessários, e de se manter uma vida de retidão e santidade.
* Provérbios 23:4-5: "Não se preocupe em ficar rico, pare de pensar em como você pode ganhar dinheiro. Porque o dinheiro certamente desaparecerá com o tempo. Pode voar como uma águia e desaparecer no céu". Este verso destaca a importância de não se preocupar em ficar rico e acumular riquezas, em linha com o ensinamento de 1 Timóteo 6 sobre a necessidade de não colocar nossa confiança na riqueza material.
* 1 Timóteo 6:10 (outro capítulo): "Porque o amor ao dinheiro é a raiz de todos os males. Algumas pessoas, ansiosas por dinheiro, se desviaram da fé e se atormentaram com muitos sofrimentos". Esse verso, embora seja do mesmo livro, está em um capítulo diferente e reforça a mensagem principal de 1 Timóteo 6 sobre a perigosa obsessão pela riqueza.
* Provérbios 15:27: "Aquele que é ganancioso perturba a sua própria casa, mas quem odeia o suborno viverá". Este verso enfatiza os perigos de se colocar o dinheiro acima de tudo e da importância de viver uma vida justa e honesta, sem ceder à ganância e corrupção.
* 2 Timóteo 2:22: "Foge, porém, das paixões da mocidade. Segue a justiça, a fé, o amor e a paz com os que, de coração puro, invocam o Senhor". Esse verso destaca a importância de buscar a justiça e a santidade, em vez de se deixar levar pelas paixões e desejos carnais.
* 1 Pedro 2:11: "Amados, insisto em que, como estrangeiros e peregrinos no mundo, vocês se abstenham dos desejos carnais que guerreiam contra a alma". Esse verso reforça a mensagem de 2 Timóteo 2:22 e destaca a importância de manter uma vida de retidão e santidade, em vez de se deixar levar pelos desejos carnais.
****

[[v61-6-1]]

^<<v61-6-1,1>>^ Todos os escravos, que estão sob o jugo, considerem os seus senhores dignos de toda a honra, para que o nome do Senhor e a sua doutrina não sejam blasfemados.

[[v61-6-2]]

^<<v61-6-2,2>>^ Os que têm senhores fiéis, não os desprezem, porque são irmãos, antes os sirvam melhor, pelo facto de serem fiéis e amados (de Deus) aqueles que recebem os seus serviços. Isto ensina e exorta.

[[v61-6-3]]

^<<v61-6-3,3>>^ Se alguém ensina de modo diferente, e não abraça as sãs palavras de Nosso Senhor Jesus Cristo e aquela doutrina que é conforme a piedade,

[[v61-6-4]]

^<<v61-6-4,4>>^ é um soberbo, que nada sabe, um espírito doente, que se ocupa de questões e contendas de palavras, donde se originam invejas, contendas, maledicências, más suspeitas,

[[v61-6-5]]

^<<v61-6-5,5>>^ altercações de homens com o espírito pervertido, que estão privados da verdade e pensam que a piedade é uma fonte de lucro.

[[v61-6-6]]

^<<v61-6-6,6>>^ Verdadeiramente a piedade é uma grande fonte de lucro, tornando-nos contentes com o que basta (para viver).

[[v61-6-7]]

^<<v61-6-7,7>>^ Como nada trouxemos para este mundo, também, sem dúvida, não podemos levar nada dele.

[[v61-6-8]]

^<<v61-6-8,8>>^ Tendo, pois, os alimentos (necessários) e com que nos cobrir, contentemo-nos com isto,

[[v61-6-9]]

^<<v61-6-9,9>>^ porque os que querem enriquecer, caem na tentação e no laço (do demônio) e em muitos desejos insensatos e perniciosos, que submergem os homens na ruína e na perdição.

[[v61-6-10]]

^<<v61-6-10,10>>^ Com efeito, a raiz de todos os males é o amor ao dinheiro, por causa do qual alguns se desencaminharam da fé e se enredaram em muitas aflições.

[[v61-6-11]]

^<<v61-6-11,11>>^ Mas tu, ó homem de Deus, foge destas coisas e segue a justiça, a piedade, a fé, a caridade, a paciência, a mansidão.

[[v61-6-12]]

^<<v61-6-12,12>>^ Combate o bom combate da fé, conquista a vida eterna, para a qual foste chamado e fizeste uma bela confissão (da divindade de Jesus) diante de muitas testemunhas.

[[v61-6-13]]

^<<v61-6-13,13>>^ Eu te ordeno, diante de Deus, que dá vida a todas as coisas, e diante de Jesus Cristo, que perante Pôncio Pilatos fez uma tão bela confissão (da sua divindade),

[[v61-6-14]]

^<<v61-6-14,14>>^ que observes este mandamento, (conservando-te) sem mácula, irrepreensível, até à vinda de Nosso Senhor Jesus Cristo,

[[v61-6-15]]

^<<v61-6-15,15>>^ que mostrará, a seu tempo, o bem-aventurado e o único poderoso, o Rei dos reis e Senhor dos senhores,

[[v61-6-16]]

^<<v61-6-16,16>>^ o único que possui a imortalidade, que habita numa luz inacessível, que não foi nem pode ser visto por nenhum homem. A ele, honra e império sempiterno ! Amém.

[[v61-6-17]]

^<<v61-6-17,17>>^ Manda aos ricos deste mundo que não sejam altivos, nem confiem na incerteza das riquezas, mas em Deus, o qual nos dá abundantemente todas as coisas para nosso uso.

[[v61-6-18]]

^<<v61-6-18,18>>^ que façam bem, que se tornem ricos em boas obras, que sejam generosos, que repartam,

[[v61-6-19]]

^<<v61-6-19,19>>^ que juntem (assim) para si um sólido tesouro para o futuro, a fim de alcançarem a verdadeira vida.

[[v61-6-20]]

^<<v61-6-20,20>>^ Ó Timóteo, guarda o depósito (da fé), evitando as disputas vãs e ímpias e as contradições de uma ciência de falso nome,

[[v61-6-21]]

^<<v61-6-21,21>>^ professando a qual alguns se desviaram da fé. A graça seja convosco!

'''

xref:061-i-timoteo/061-i-timoteo-005.adoc#v61-5-0[&#60; Capítulo Anterior] | <<v61-6-0,Topo>> | xref:062-ii-timoteo/062-ii-timoteo-001.adoc#v62-1-0[Próximo Capítulo &#62;]