include::./index.adoc[]

[[v50-21-0]]
=== São João, 21
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Em João 21, o capítulo narra uma das aparições de Jesus aos seus discípulos após a sua ressurreição. Nesse encontro, Jesus realiza um milagre ao permitir que os discípulos pescassem uma grande quantidade de peixes e, em seguida, faz uma refeição com eles. Além disso, Jesus pede a Pedro que o siga e o ame, e profetiza sobre o futuro de Pedro. A seguir, são cinco versículos relacionados com os temas abordados em João 21:
* Gênesis 22:8: "Respondeu Abraão: Deus proverá para si o cordeiro para o holocausto, meu filho." Nesse versículo, vemos a confiança de Abraão em Deus, que sempre provê para suas necessidades. Essa confiança também é exemplificada pelos discípulos em João 21, quando seguem as instruções de Jesus para pescar no lado direito do barco e acabam capturando uma grande quantidade de peixes.
* Salmo 23:1: "O SENHOR é o meu pastor; nada me faltará." Esse salmo retrata a confiança do salmista em Deus, que cuida dele e o guia. Essa mesma confiança é demonstrada pelos discípulos em João 21, quando seguem as instruções de Jesus para pescar no lado direito do barco e confiam na sua sabedoria e autoridade.
* Mateus 28:19: "Portanto, ide, fazei discípulos de todas as nações, batizando-os em nome do Pai, e do Filho, e do Espírito Santo." Esse versículo apresenta a Grande Comissão de Jesus aos seus discípulos, ordenando-lhes que preguem o evangelho a todas as nações. Em João 21, Jesus pede a Pedro que o siga e o ame, e o comissiona para cuidar do seu rebanho.
* Atos 12:3-4: "Vendo que isso agradara aos judeus, procedeu a prender também a Pedro. Eram então os dias dos pães ázimos." Nesse versículo, vemos Pedro sendo preso por causa da sua fé em Jesus. Em João 21, Jesus profetiza sobre o futuro de Pedro, dizendo que ele também seria levado para onde não queria ir.
* Apocalipse 22:20: "Aquele que dá testemunho destas coisas diz: Certamente venho sem demora. Amém! Vem, Senhor Jesus!" Esse versículo apresenta a promessa de que Jesus retornará para buscar a sua igreja. Em João 21, Jesus aparece aos seus discípulos após a sua ressurreição, mas deixa claro que esse encontro é temporário e que ele voltará para estar com eles novamente.
****

[[v50-21-1]]

^<<v50-21-1,1>>^ Depois disto, Jesus tornou a mostrar-se aos seus discípulos, junto do mar de Tiberíades. Mostrou-se deste modo:

[[v50-21-2]]

^<<v50-21-2,2>>^ Estavam juntos Simão Pedro, Tomé, chamado Dídimo, Natanael, que era de Caná da Galileia, os filhos de Zebedeu e dois outros dos seus discípulos.

[[v50-21-3]]

^<<v50-21-3,3>>^ Simão Pedro disse-lhes: "Vou pescar." Responderam-lhe: "Também nós vamos contigo." Partiram e entraram numa barca. Naquela noite nada apanharam.

[[v50-21-4]]

^<<v50-21-4,4>>^ Chegada a manhã, Jesus apresentou-se na praia; os discípulos todavia não conheceram que era ele.

[[v50-21-5]]

^<<v50-21-5,5>>^ Jesus disse-lhes: "Ó moços, tendes alguma coisa de comer?" Responderam-lhe: "Nada."

[[v50-21-6]]

^<<v50-21-6,6>>^ Disse-lhes: "Lançai a rede para o lado direito da barca, e encontrareis. Lançaram a rede, e não a podiam tirar, por causa da grande quantidade de peixes.

[[v50-21-7]]

^<<v50-21-7,7>>^ Então aquele discípulo, a quem Jesus amava, disse a Pedro: "É o Senhor." Simão Pedro, ao ouvir dizer que era o Senhor, cingiu-Se com a túnica (porque estava nu), e lançou-se à água. (ver nota)

[[v50-21-8]]

^<<v50-21-8,8>>^ Os outros discípulos, que não estavam distantes de terra, senão duzentos côvados foram na barca, tirando a rede cheia de peixes. (ver nota)

[[v50-21-9]]

^<<v50-21-9,9>>^ Logo que saltaram em terra, viram umas brasas acesas, peixe em cima delas, e pão.

[[v50-21-10]]

^<<v50-21-10,10>>^ Jesus disse-lhes: "Trazei dos peixes que agora apanhastes."

[[v50-21-11]]

^<<v50-21-11,11>>^ Simão Pedro subiu à barca e tirou a rede para terra, cheia de cento e cinqüenta e três grandes peixes. E, sendo tantos, não se rompeu a rede.

[[v50-21-12]]

^<<v50-21-12,12>>^ Jesus disse-lhes: "Vinde jantar." Nenhum dos discípulos ousava perguntar-lhe: "Quem és tu?" sabendo que era o Senhor.

[[v50-21-13]]

^<<v50-21-13,13>>^ Jesus aproximou-se, tomou o pão e deu-lho, e igualmente do peixe.

[[v50-21-14]]

^<<v50-21-14,14>>^ Foi esta a terceira vez que Jesus se manifestou aos seus discípulos, depois de ter ressuscitado dos mortos.

[[v50-21-15]]

^<<v50-21-15,15>>^ Tendo eles jantado, disse Jesus a Simão Pedro: "Simão, filho de João, amas-me mais do que estes?" Ele disse-lhe: "Sim, Senhor, tu sabes que eu te amo." Jesus disse-lhe: "Apascenta os meus cordeiros." (ver nota)

[[v50-21-16]]

^<<v50-21-16,16>>^ Disse-lhe outra vez; "Simão, filho de João, amas-me?" Ele disse-lhe: "Sim, Senhor, tu sabes que eu te amo." Jesus disse-lhe: "Apascenta as minhas ovelhas."

[[v50-21-17]]

^<<v50-21-17,17>>^ Disse-lhe pela terceira vez: "Simão, filho de João, amas-me?" Ficou Pedro triste, porque, pela terceira vez, lhe disse: "Amas-me?" E disse-lhe: "Senhor, tu conheces tudo; sabes que eu te amo." Jesus disse-lhe: "Apascenta as minhas ovelhas."

[[v50-21-18]]

^<<v50-21-18,18>>^ Em verdade, em verdade te digo: Quando tu eras mais moço, cingias-te e ias onde desejavas; mas, quando fores velho, estenderás as tuas mãos, e outro te cingirá e te levará para onde tu não queres."

[[v50-21-19]]

^<<v50-21-19,19>>^ Disse isto, indicando com que gênero de morte havia Pedro de dar glória a Deus. Depois de assim ter falado, disse: "Segue-me."

[[v50-21-20]]

^<<v50-21-20,20>>^ Pedro, tendo-se voltado, viu que o seguia aquele discípulo que Jesus amava, o qual na ceia estivera reclinado sobre o seu peito, e lhe perguntara: "Senhor, quem é o que te há-de entregar?"

[[v50-21-21]]

^<<v50-21-21,21>>^ Por isso Pedro, vendo-o, disse a Jesus: "Senhor, e deste que será?" (ver nota)

[[v50-21-22]]

^<<v50-21-22,22>>^ Jesus disse-lhe: "Se quero que ele fique até que eu volte, que tens tu com isso? Tu segue-me." (ver nota)

[[v50-21-23]]

^<<v50-21-23,23>>^ Correu esta voz entre os irmãos que aquele discípulo não morreria. Todavia Jesus não disse a Pedro: "Não morrerá", mas: "Se quero que ele fique até que eu venha, que tens tu com isso?"

[[v50-21-24]]

^<<v50-21-24,24>>^ Este é aquele discípulo que dã testemunho destas coisas e que as escreveu, e sabemos que é verdadeiro o seu testemunho.

[[v50-21-25]]

^<<v50-21-25,25>>^ Muitas outras coisas fez Jesus. Se se escrevessem, uma por uma, creio que nem no mundo todo poderiam caber os livros que seria preciso escrever. (ver nota)

'''

xref:050-sao-joao/050-sao-joao-020.adoc#v50-20-0[&#60; Capítulo Anterior] | <<v50-21-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-001.adoc#v51-1-0[Próximo Capítulo &#62;]