include::./index.adoc[]

[[v50-10-0]]
=== São João, 10
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 10 do livro de João apresenta Jesus como o bom pastor que dá a vida por suas ovelhas e fala sobre sua relação com aqueles que o seguem. Além disso, Jesus faz uma analogia entre o pastor e suas ovelhas, destacando a importância da relação de confiança entre eles. Aqui estão cinco versículos relacionados com os temas abordados em João 10:
* Salmos 23:1 - "O Senhor é o meu pastor, nada me faltará." Este salmo fala sobre a relação de confiança entre Deus e aqueles que o seguem, assim como a relação entre o pastor e suas ovelhas.
* Ezequiel 34:11-12 - "Porque assim diz o Senhor Deus: Eis que eu mesmo procurarei pelas minhas ovelhas, e as buscarei. Como o pastor busca o seu rebanho, no dia em que está no meio das suas ovelhas dispersas, assim buscarei as minhas ovelhas; livrá-las-ei de todos os lugares por onde foram espalhadas no dia de nuvens e de escuridão." Este versículo fala sobre como Deus se importa com suas ovelhas, buscando-as e livrando-as de perigos.
* Isaías 40:11 - "Como pastor, ele apascentará o seu rebanho; entre os seus braços recolherá os cordeirinhos, e os levará no seio; as que amamentam ele as guiará mansamente." Este versículo destaca como Deus cuida de suas ovelhas com gentileza e amor.
* 1 Pedro 5:4 - "E, quando se manifestar o Sumo Pastor, recebereis a imarcescível coroa da glória." Este versículo fala sobre Jesus como o Sumo Pastor que um dia retornará para buscar suas ovelhas e recompensá-las.
* Salmo 100:3 - "Sabei que o Senhor é Deus; foi ele que nos fez, e não nós a nós mesmos; somos povo seu e ovelhas de seu pasto." Este salmo destaca que aqueles que seguem a Deus são suas ovelhas, e Ele é o bom pastor que cuida delas.
****

[[v50-10-1]]

^<<v50-10-1,1>>^ Em verdade, em verdade, vos digo que quem não entra pela porta no aprisco das ovelhas, mas sobe por outra parte, é ladrão e salteador.

[[v50-10-2]]

^<<v50-10-2,2>>^ O que entra pela porta, é pastor das ovelhas.

[[v50-10-3]]

^<<v50-10-3,3>>^ A este o porteiro abre, e as ovelhas ouvem a sua voz, ele as chama pelo seu nome, e as tira para fora.

[[v50-10-4]]

^<<v50-10-4,4>>^ Quando as tirou todas para fora, vai adiante delas, e as ovelhas seguem-no, porque conhecem a sua voz.

[[v50-10-5]]

^<<v50-10-5,5>>^ Mas não seguem o estranho, antes fogem dele, porque não conhecem a voz dos estranhos."

[[v50-10-6]]

^<<v50-10-6,6>>^ Jesus disse-lhes esta alegoria, mas eles não compreenderam o que lhes dizia.

[[v50-10-7]]

^<<v50-10-7,7>>^ Tornou, pois, Jesus a dizer-lhes: "Em verdade, em verdade, vos digo que eu sou a porta das ovelhas.

[[v50-10-8]]

^<<v50-10-8,8>>^ Todos os que vieram antes de mim são ladrões e salteadores; mas as ovelhas não os ouviram.

[[v50-10-9]]

^<<v50-10-9,9>>^ Eu sou a porta; se alguém entrar por mim, será salvo; entrará, e sairá, e encontrará pastagens.

[[v50-10-10]]

^<<v50-10-10,10>>^ O ladrão não vem senão para roubar, matar e destruir. Eu vim para que elas tenham vida e estejam na abundância.

[[v50-10-11]]

^<<v50-10-11,11>>^ Eu sou o bom pastor. O bom pastor expõe a sua vida pelas suas ovelhas.

[[v50-10-12]]

^<<v50-10-12,12>>^ O mercenário, o que não é pastor, de quem não são próprias as ovelhas, vê vir o lobo, deixa as ovelhas, e foge; e o lobo arrebata e faz desgarrar as ovelhas,

[[v50-10-13]]

^<<v50-10-13,13>>^ porque é mercenário, e porque não se importa com as ovelhas.

[[v50-10-14]]

^<<v50-10-14,14>>^ Eu sou o bom pastor, e conheço as minhas ovelhas, e as minhas ovelhas conhecem-me.

[[v50-10-15]]

^<<v50-10-15,15>>^ Como o Pai me conhece, assim eu conheço o Pai; e dou a minha vida pelas minhas ovelhas.

[[v50-10-16]]

^<<v50-10-16,16>>^ Tenho outras ovelhas que não são deste aprisco; importa que eu as traga; elas ouvirão a minha voz, e haverá um só rebanho e um só pastor.

[[v50-10-17]]

^<<v50-10-17,17>>^ Se o Pai me ama, é porque dou a minha vida para outra vez a assumir.

[[v50-10-18]]

^<<v50-10-18,18>>^ Ninguém me tira, mas eu por mim mesmo a dou, e tenho poder de a dar, e tenho poder de a reassumir. Este é o mandamento que recebi de meu Pai."

[[v50-10-19]]

^<<v50-10-19,19>>^ Originou-se por causa destas palavras uma nova dissenção entre os Judeus.

[[v50-10-20]]

^<<v50-10-20,20>>^ Muitos deles diziam: "Ele está possesso do demônio; delira; porque estais a ouvi-lo?"

[[v50-10-21]]

^<<v50-10-21,21>>^ Outros diziam: "Estas palavras não são de quem está possesso do demônio. Porventura pode o demônio abrir os olhos aos cegos?"

[[v50-10-22]]

^<<v50-10-22,22>>^ Celebrava-se em Jerusalém a festa da dedicação. Era inverno.

[[v50-10-23]]

^<<v50-10-23,23>>^ Jesus andava passeando no templo, no pórtico de Salomão.

[[v50-10-24]]

^<<v50-10-24,24>>^ Rodearam-no os Judeus, e disseram-lhe: "A té quando nos terás tu perplexos? Se és o Cristo, dize-no-lo claramente."

[[v50-10-25]]

^<<v50-10-25,25>>^ Jesus respondeu-lhes: "Eu digo-vo-lo, e vós não me credes. As obras que faço em nome de meu Pai, essas dão testemunho de mim;

[[v50-10-26]]

^<<v50-10-26,26>>^ porém vós não credes, porque não sois das minhas ovelhas,

[[v50-10-27]]

^<<v50-10-27,27>>^ As minhas ovelhas ouvem a minha voz; eu conheço-as, e elas seguem-me.

[[v50-10-28]]

^<<v50-10-28,28>>^ Eu dou-lhes a vida eterna; elas jamais hão-de perecer, e ninguém as arrebatará da minha mão.

[[v50-10-29]]

^<<v50-10-29,29>>^ Meu Pai, que me deu, é maior que todas as coisas; e ninguém pode arrebatá-las da mão de meu Pai.

[[v50-10-30]]

^<<v50-10-30,30>>^ Eu e o Pai somos um."

[[v50-10-31]]

^<<v50-10-31,31>>^ Os Judeus, então, pegaram em pedras para lhe atirarem.

[[v50-10-32]]

^<<v50-10-32,32>>^ Jesus disse-lhes: "Tenho-vos mostrado muitas obras boas que fiz por virtude de meu Pai; por qual destas obras me apedrejais?"

[[v50-10-33]]

^<<v50-10-33,33>>^ Os Judeus responderam-lhe: "Não é por causa de nenhuma obra boa que te apedrejamos, mas pela blasfêmia, e porque sendo homem, te fazes Deus."

[[v50-10-34]]

^<<v50-10-34,34>>^ Jesus respondeu-lhes: "Não está escrito na vossa lei: Eu disse: Vós sois deuses? (Ps. 81, 6)."

[[v50-10-35]]

^<<v50-10-35,35>>^ Se ela chamou deuses àqueles a quem a palavra de Deus foi dirigida, e a Escritura não pode falar,

[[v50-10-36]]

^<<v50-10-36,36>>^ a mim, a quem o Pai santificou e enviou ao mundo, vós dizeis: Tu blasfemas, por eu ter dito: Sou filho de Deus?

[[v50-10-37]]

^<<v50-10-37,37>>^ Se eu não faço as obras de meu Pai, não me acrediteis;

[[v50-10-38]]

^<<v50-10-38,38>>^ mas se as faço, quando não queirais crer em mim, crede nas minhas obras, para que saibais e reconheçais que o Pai está em mim, e eu no Pai."

[[v50-10-39]]

^<<v50-10-39,39>>^ Então os Judeus procuravam novamente prendê-lo, mas ele escapou-se das suas mãos.

[[v50-10-40]]

^<<v50-10-40,40>>^ Retirou-se novamente para a banda de além do Jordão, para o lugar em que João tinha começado a baptizar; e ficou lá.

[[v50-10-41]]

^<<v50-10-41,41>>^ Foram muitos ter com ele, e diziam: "João não fez nenhum milagre,

[[v50-10-42]]

^<<v50-10-42,42>>^ mas tudo o que disse deste era verdadeiro." E muitos creram nele.

'''

xref:050-sao-joao/050-sao-joao-009.adoc#v50-9-0[&#60; Capítulo Anterior] | <<v50-10-0,Topo>> | xref:050-sao-joao/050-sao-joao-011.adoc#v50-11-0[Próximo Capítulo &#62;]