include::./index.adoc[]

[[v50-13-0]]
=== São João, 13
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* São João 13 descreve a última ceia de Jesus com seus discípulos, onde Ele lava os pés deles e compartilha suas últimas palavras de ensinamentos antes da crucificação. Abaixo estão cinco versículos relacionados com os temas abordados no capítulo:
* Filipenses 2:3-4: "Não façam nada por ambição egoísta ou por vaidade, mas humildemente considerem os outros superiores a si mesmos. Cada um cuide, não somente dos seus interesses, mas também dos interesses dos outros." Este versículo enfatiza a importância da humildade e do cuidado com os outros, mostrando o exemplo de Jesus ao lavar os pés de seus discípulos.
* João 15:12-13: "O meu mandamento é este: amem-se uns aos outros como eu os amei. Ninguém tem maior amor do que aquele que dá a sua vida pelos seus amigos." Esses versículos reforçam o ensinamento de Jesus sobre o amor ao próximo, que é exemplificado em suas ações durante a última ceia.
* Colossenses 3:13: "Suportem-se uns aos outros e perdoem as queixas que tiverem uns contra os outros. Perdoem como o Senhor lhes perdoou." O ato de Jesus de lavar os pés de seus discípulos mostra seu amor e disposição em servir, e este versículo destaca a importância de perdoar e amar os outros em nossas ações diárias.
* Mateus 20:26-28: "Entre vocês, porém, não será assim. Ao contrário, quem quiser tornar-se importante entre vocês deverá ser servo, e quem quiser ser o primeiro deverá ser escravo; como o Filho do homem, que não veio para ser servido, mas para servir e dar a sua vida em resgate por muitos." Esses versículos mostram o exemplo de Jesus em servir e cuidar dos outros, e como devemos imitar seu exemplo em nossas próprias vidas.
* João 14:15: "Se vocês me amam, obedecerão aos meus mandamentos." Durante a última ceia, Jesus enfatizou a importância de obedecer aos seus ensinamentos e mandamentos, como uma expressão de amor e devoção a Ele.
****

[[v50-13-1]]

^<<v50-13-1,1>>^ Antes da festa da Páscoa, sabendo Jesus que tinha chegado a sua hora de passar deste mundo ao Pai, tendo amado os seus, que estavam no mundo, amou-os até ao extremo.

[[v50-13-2]]

^<<v50-13-2,2>>^ Durante a ceia, tendo já o demônio posto no coração de Judas Iscariotes, filho de Simão, a determinação de o entregar,

[[v50-13-3]]

^<<v50-13-3,3>>^ Jesus, sabendo que o Pai tinha posto em suas mãos todas as coisas, que saíra de Deus e voltava para Deus,

[[v50-13-4]]

^<<v50-13-4,4>>^ levantou-se da mesa, depôs as vestes, e, pegando numa toalha, cingiu-se com ela.

[[v50-13-5]]

^<<v50-13-5,5>>^ Depois lançou água numa bacia, e começou a lavar os pés dos discípulos e a enxugá-los, com a toalha com que estava cingido.

[[v50-13-6]]

^<<v50-13-6,6>>^ Chegou, pois, a Simão Pedro. Pedro disse-lhe: "Senhor, tu lavares-me os pés?"

[[v50-13-7]]

^<<v50-13-7,7>>^ Jesus respondeu-lhe: "O que eu faço, tu não o compreendes agora, mas compreendê-lo-ás depois."

[[v50-13-8]]

^<<v50-13-8,8>>^ Pedro disse-lhe: "Não me lavarás jamais os pés." Jesus respondeu-lhe: "Se eu não te lavar, não terás parte comigo."

[[v50-13-9]]

^<<v50-13-9,9>>^ Simão Pedro disse-lhe: "Senhor, não somente os meus pés, mas também as mãos e a cabeça."

[[v50-13-10]]

^<<v50-13-10,10>>^ Jesus disse-lhe: "Aquele que se banhou, não tem necessidade de se lavar, pois todo ele está limpo. Vós estais limpos, mas não todos."

[[v50-13-11]]

^<<v50-13-11,11>>^ Ele sabia qual era o que o ia entregar, por isso disse: "Não estais todos limpos."

[[v50-13-12]]

^<<v50-13-12,12>>^ Depois que lhes lavou os pés e que retomou as suas vestes, tendo-se tornado a pôr à mesa disse-lhes: "Compreendeis o que vos fiz?"

[[v50-13-13]]

^<<v50-13-13,13>>^ Chamais-me Mestre e Senhor, e dizeis bem, porque o sou.

[[v50-13-14]]

^<<v50-13-14,14>>^ Se eu, pois, sendo vosso Senhor e Mestre, vos lavei os pés, também vós deveis lavar os pés uns aos outros. (ver nota)

[[v50-13-15]]

^<<v50-13-15,15>>^ Dei-vos o exemplo, para que, como eu vos fiz, assim façais vós também.

[[v50-13-16]]

^<<v50-13-16,16>>^ Em verdade, em verdade, vos digo: O servo não é maior do que seu senhor, nem o enviado é maior do que aquele que o enviou.

[[v50-13-17]]

^<<v50-13-17,17>>^ Se compreendeis estas coisas, bem-aventurados sereis se as praticardes.

[[v50-13-18]]

^<<v50-13-18,18>>^ Não falo de todos vós; sei os que escolhi; porém é necessário que se cumpra o que diz a Escritura: O que come o pão comigo levantará o seu calcanhar contra mim (Ps. 40, 10).

[[v50-13-19]]

^<<v50-13-19,19>>^ Desde agora vo-lo digo, antes que suceda, para que, quando suceder, creiais que sou eu (o Messias).

[[v50-13-20]]

^<<v50-13-20,20>>^ Em verdade, em verdade, vos digo, que quem recebe aquele que eu enviar, a mim recebe, e o que me recebe, recebe aquele que me enviou."

[[v50-13-21]]

^<<v50-13-21,21>>^ Tendo Jesus dito estas coisas, turbou-se em seu espírito e declarou abertamente: "Em verdade, em verdade, vos digo, que um de vós me há-de entregar."

[[v50-13-22]]

^<<v50-13-22,22>>^ Olhavam, pois, os discípulos uns para os outros, não sabendo de quem falava.

[[v50-13-23]]

^<<v50-13-23,23>>^ Ora um dos seus discípulos, ao qual Jesus amava, estava recostado sobre o seio de Jesus.

[[v50-13-24]]

^<<v50-13-24,24>>^ A este fez Simão Pedro sinal, para lhe dizer: "De quem fala ele?"

[[v50-13-25]]

^<<v50-13-25,25>>^ Aquele discípulo, pois, tendo-se reclinado sobre o peito de Jesus, disse-lhe: "Senhor, quem é esse?" (ver nota)

[[v50-13-26]]

^<<v50-13-26,26>>^ Jesus respondeu; "É aquele a quem eu der o bocado que vou molhar." Molhando, pois, o bocado, deu-o a Judas Iscariotes, filho de Simão.

[[v50-13-27]]

^<<v50-13-27,27>>^ Atrás do bocado, entrou nele Satanás. Jesus disse-lhe então: "O que queres fazer, faze-o depressa."

[[v50-13-28]]

^<<v50-13-28,28>>^ Nenhum, porém, dos que estavam à mesa percebeu por que lhe dizia isto.

[[v50-13-29]]

^<<v50-13-29,29>>^ Alguns, como Judas era o que tinha a bolsa, julgavam que Jesus lhe dissera: "Compra as coisas que nos são precisas para o dia da festa", ou: "Dá alguma coisa aos pobres."

[[v50-13-30]]

^<<v50-13-30,30>>^ Ele, pois, tendo recebido o bocado, saiu logo. Era já noite.

[[v50-13-31]]

^<<v50-13-31,31>>^ Depois que ele saiu, Jesus disse: "Agora é glorificado o Filho do homem, e Deus é glorificado nele.

[[v50-13-32]]

^<<v50-13-32,32>>^ Se Deus foi glorificado nele, também Deus o glorificará em si mesmo; e glorificá-lo-á sem demora.

[[v50-13-33]]

^<<v50-13-33,33>>^ Filhinhos já pouco tempo estou convosco. Buscar-me-eis, mas, assim como disse aos Judeus: Para onde eu vou, vós não podeis vir, também a vós o digo agora.

[[v50-13-34]]

^<<v50-13-34,34>>^ Dou-vos um novo mandamento: Que vos ameis uns aos outros, que, assim como vos amei, vos ameis também uns aos outros.

[[v50-13-35]]

^<<v50-13-35,35>>^ Nisto conhecerão todos que sois meus discípulos, se tiverdes amor uns aos outros."

[[v50-13-36]]

^<<v50-13-36,36>>^ Simão Pedro disse-lhe: "Senhor, para onde vais tu?" Jesus respondeu-lhe: "Para onde eu vou, não podes tu agora seguir-me, mas seguir-me-ás mais tarde."

[[v50-13-37]]

^<<v50-13-37,37>>^ Pedro disse-lhe: "Porque não posso eu seguir-te agora? Darei a minha vida por ti."

[[v50-13-38]]

^<<v50-13-38,38>>^ Jesus respondeu-lhe:"Darás a tua vida por mim? Em verdade, em verdade, te digo: Não cantará o galo sem que me tenhas negado três vezes.

'''

xref:050-sao-joao/050-sao-joao-012.adoc#v50-12-0[&#60; Capítulo Anterior] | <<v50-13-0,Topo>> | xref:050-sao-joao/050-sao-joao-014.adoc#v50-14-0[Próximo Capítulo &#62;]