include::./index.adoc[]

[[v50-1-0]]
=== São João, 1
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 1 do Evangelho de João apresenta Jesus como a Palavra de Deus encarnada, que veio para iluminar a todos e revelar a graça e a verdade de Deus ao mundo. Além disso, o capítulo apresenta o testemunho de João Batista a respeito de Jesus e a rejeição de Jesus pelos seus próprios. Seguem abaixo cinco versículos relacionados com os temas abordados em João 1:
* Isaías 40:3: "Uma voz clama: ‘No deserto preparem o caminho para o Senhor; façam no ermo uma estrada para o nosso Deus.’" Este versículo é citado em João 1:23, quando João Batista se apresenta como aquele que cumpre a profecia de Isaías, preparando o caminho para o Messias.
* João 3:19-20: "Este é o julgamento: a luz veio ao mundo, mas os homens amaram mais as trevas do que a luz, porque as suas obras eram más. Quem pratica o mal odeia a luz e não se aproxima da luz, temendo que as suas obras sejam expostas." Estes versículos se relacionam com o tema da luz apresentado em João 1:4-5, que afirma que "Nele estava a vida, e esta era a luz dos homens. A luz brilha nas trevas, e as trevas não a derrotaram".
* João 5:39: "Vocês estudam cuidadosamente as Escrituras, porque pensam que nelas vocês têm a vida eterna. E são as Escrituras que testemunham a meu respeito". Este versículo se relaciona com a ideia apresentada em João 1:1-2, de que Jesus é a Palavra de Deus que existia desde o princípio e estava com Deus.
* Colossenses 1:15-17: "Ele é a imagem do Deus invisível, o primogênito de toda a criação, pois nele foram criadas todas as coisas nos céus e na terra, as visíveis e as invisíveis, sejam tronos ou soberanias, poderes ou autoridades; todas as coisas foram criadas por ele e para ele. Ele existe antes de todas as coisas, e nele todas as coisas subsistem." Estes versículos se relacionam com a afirmação de João 1:3 de que todas as coisas foram feitas por meio de Jesus e nada do que foi feito foi feito sem Ele.
* Hebreus 1:1-2: "No passado Deus falou muitas vezes e de várias maneiras aos nossos antepassados por meio dos profetas, mas nestes últimos dias falou-nos por meio do Filho, a quem constituiu herdeiro de todas as coisas e por meio de quem fez o universo." Este versículo se relaciona com a ideia de João 1:14 de que a Palavra se fez carne e habitou entre nós, revelando a graça e a verdade de Deus ao mundo.
****

[[v50-1-1]]

^<<v50-1-1,1>>^ No principio existia o Verbo, e o Verbo estava junto de Deus, e o Verbo era Deus.

[[v50-1-2]]

^<<v50-1-2,2>>^ Estava no princípio junto de Deus,

[[v50-1-3]]

^<<v50-1-3,3>>^ Todas as coisas foram feitas por ele; e sem ele nada foi feito.

[[v50-1-4]]

^<<v50-1-4,4>>^ Nele estava a vida, e a vida era a luz dos homens,

[[v50-1-5]]

^<<v50-1-5,5>>^ e a luz resplandece nas trevas, e as trevas não o receberam.

[[v50-1-6]]

^<<v50-1-6,6>>^ Apareceu um homem enviado por Deus que se chamava João.

[[v50-1-7]]

^<<v50-1-7,7>>^ Veio como testemunha para dar testemunho da luz, a fim de que todos crêssem por meio dele.

[[v50-1-8]]

^<<v50-1-8,8>>^ Não era a luz, mas veio para dar testemunho da luz,

[[v50-1-9]]

^<<v50-1-9,9>>^ O Verbo era a luz verdadeira, que ilumina todo o homem que vem a este mundo.

[[v50-1-10]]

^<<v50-1-10,10>>^ Estava no mundo, e o mundo foi feito por ele, e o mundo não o conheceu.

[[v50-1-11]]

^<<v50-1-11,11>>^ Veio para o que era seu, e os seus não o receberam.

[[v50-1-12]]

^<<v50-1-12,12>>^ Mas a todos os que o receberam, deu poder de se tornarem filhos de Deus, àqueles que crêem no seu nome;

[[v50-1-13]]

^<<v50-1-13,13>>^ os quais não nasceram do sangue, nem da vontade da carne, nem da vontade do homem, mas de Deus.

[[v50-1-14]]

^<<v50-1-14,14>>^ E o Verbo se fez carne, e habitou entre nós; e nós vimos a sua glória, glória como de Filho Unigénito do Pai, cheio de graça e de verdade.

[[v50-1-15]]

^<<v50-1-15,15>>^ João dá testemunho dele e clama: Este era aquele de quem eu disse: O que há-de vir depois de mim, é mais do que eu, porque existia antes de mim.

[[v50-1-16]]

^<<v50-1-16,16>>^ Todos nós participamos da sua plenitude, e recebemos graça sobre graça;

[[v50-1-17]]

^<<v50-1-17,17>>^ porque a lei foi dada por Moisés, mas a graça e a verdade foi trazida por Jesus Cristo.

[[v50-1-18]]

^<<v50-1-18,18>>^ Ninguém jamais viu Deus; o Filho Unigénito, que está no seio do Pai, ele mesmo é que o deu a conhecer.

[[v50-1-19]]

^<<v50-1-19,19>>^ Eis o testemunho de João, quando os Judeus lhe enviaram de Jerusalém sacerdotes e levitas a perguntar-lhe: "Quem és tu"?

[[v50-1-20]]

^<<v50-1-20,20>>^ Ele confessou a verdade, não a negou; e confessou: "Eu não sou o Cristo".

[[v50-1-21]]

^<<v50-1-21,21>>^ Eles perguntaram-lhe: "Quem és pois? És tu Elias"? Ele respondeu: "Não sou". "És tu o profeta"? Respondeu: "Não".

[[v50-1-22]]

^<<v50-1-22,22>>^ Disseram-lhe então: "Quem és, pois, para que possamos dar resposta aos que nos enviaram? Que dizes de ti mesmo?"

[[v50-1-23]]

^<<v50-1-23,23>>^ Disse-lhes então: Eu sou a vos do que clama no deserto; Endireitai o caminho do Senhor, como disse o profeta Isaías (Is. 40, 3)."

[[v50-1-24]]

^<<v50-1-24,24>>^ Ora os que tinham sido enviados eram fariseus.

[[v50-1-25]]

^<<v50-1-25,25>>^ Interrogaram-no, dizendo: "Com o baptizas, pois, se não és o Cristo, nem Elias, nem o profeta?"

[[v50-1-26]]

^<<v50-1-26,26>>^ João respondeu-lhes: "Eu baptizo em água, mas no meio de vós está quem vós não conheceis.

[[v50-1-27]]

^<<v50-1-27,27>>^ Esse é o que há-de vir depois de mim, ao qual eu não sou digno de desatar a correia das sandálias."

[[v50-1-28]]

^<<v50-1-28,28>>^ Estas coisas passaram-se em Betânia, da banda de além do Jordão, onde João estava baptizando.

[[v50-1-29]]

^<<v50-1-29,29>>^ No dia seguinte João viu Jesus, que vinha ter com ele, e disse: "Eis o Cordeiro de Deus, eis o que tira o pecado do mundo.

[[v50-1-30]]

^<<v50-1-30,30>>^ Este é aquele, de quem eu disse: Depois de mim vem um homem que é superior a mim, porque era antes de mim,

[[v50-1-31]]

^<<v50-1-31,31>>^ e eu não o conhecia, mas vim baptizar em água, para ele ser reconhecido em Israel."

[[v50-1-32]]

^<<v50-1-32,32>>^ João deu este testemunho: "Vi o Espírito descer do céu em forma de pomba, e repousou sobre ele.

[[v50-1-33]]

^<<v50-1-33,33>>^ Eu não o conhecia, mas o que me mandou baptizar em água, disse-me: Aquele, sobre quem vires descer e repousar o Espírito, esse é o que baptiza no Espírito Santo.

[[v50-1-34]]

^<<v50-1-34,34>>^ Eu o vi, e dei testemunho de que ele é o Filho de Deus."

[[v50-1-35]]

^<<v50-1-35,35>>^ Ao outro dia João lá estava novamente com dois de seus discípulos.

[[v50-1-36]]

^<<v50-1-36,36>>^ Vendo Jesus que ia passando, disse: "Eis o Cordeiro de Deus."

[[v50-1-37]]

^<<v50-1-37,37>>^ Ouvindo as suas palavras, os dois discípulos seguiram Jesus.

[[v50-1-38]]

^<<v50-1-38,38>>^ Jesus, voltando-se para trás, e vendo que o seguiam, disse-lhes: "Que buscais vós?" Eles disseram-lhe: "Rabi (que quer dizer Mestre), onde habitas?"

[[v50-1-39]]

^<<v50-1-39,39>>^ Jesus disse-lhes: "Vinde ver." Foram, viram onde habitava, e ficaram com ele aquele dia. Era então quase a hora décima.

[[v50-1-40]]

^<<v50-1-40,40>>^ André, irmão de Simão Pedro, era um dos dois que tinham ouvido o que João dissera, e que tinham seguido Jesus.

[[v50-1-41]]

^<<v50-1-41,41>>^ Este encontrou primeiro seu irmão Simão, e disse-lhe: "Encontramos o Messias" (que quer dizer Cristo).

[[v50-1-42]]

^<<v50-1-42,42>>^ Levou-o a Jesus. Jesus, fixando nele o olhar, disse: "Tu és Simão, filho de João, tu serás chamado Cefas, que quer dizer Pedro ou Pedra."

[[v50-1-43]]

^<<v50-1-43,43>>^ No dia seguinte Jesus resolveu ir à Galileia. Encontrou Filipe, e disse-lhe: "Segue-me."

[[v50-1-44]]

^<<v50-1-44,44>>^ Filipe era natural da cidade de Betsaida, pátria de André e de Pedro.

[[v50-1-45]]

^<<v50-1-45,45>>^ Filipe encontrou Natanael, e disse-lhe: "Encontramos aquele de quem escreveram Moisés na lei e os profetas: Jesus de Nazaré, filho de José."

[[v50-1-46]]

^<<v50-1-46,46>>^ Natanael disse-lhe: "De Nazaré pode porventura sair coisa que seja boa?" Filipe disse-lhe: "Vem ver."

[[v50-1-47]]

^<<v50-1-47,47>>^ Jesus viu Natanael, que ia ter com ele, e disse dele: "Eis um verdadeiro Israelita, em quem não há dolo."

[[v50-1-48]]

^<<v50-1-48,48>>^ Natanael disse-lhe: "Donde me conheces tu?" Jesus respondeu-lhe: "Antes que Filipe te chamasse, te vi eu, quando estavas debaixo da figueira."

[[v50-1-49]]

^<<v50-1-49,49>>^ Natanael respondeu: "Mestre, tu és o filho de Deus, tu és o rei e Israel."

[[v50-1-50]]

^<<v50-1-50,50>>^ Jesus respondeu-lhe: "Porque eu te disse que te vi debaixo da figueira, crês; verás coisas maiores que esta."

[[v50-1-51]]

^<<v50-1-51,51>>^ E acrescentou: "Em verdade, em verdade vos digo, vereis o céu aberto, e os anjos de Deus subindo e descendo sobre o Filho do homem."

'''

xref:049-sao-lucas/049-sao-lucas-024.adoc#v49-24-0[&#60; Capítulo Anterior] | <<v50-1-0,Topo>> | xref:050-sao-joao/050-sao-joao-002.adoc#v50-2-0[Próximo Capítulo &#62;]