include::./index.adoc[]

[[v50-6-0]]
=== São João, 6
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* São João 6 trata da multiplicação dos pães e peixes, do discurso de Jesus como o pão da vida e da incredulidade dos discípulos. Os versículos selecionados são:
* 1 Coríntios 10:17: "Visto que há um único pão, nós, que somos muitos, somos um só corpo, pois todos participamos do único pão." Este versículo se relaciona com a ideia de que Jesus é o pão da vida e como participamos dele.
* João 1:14: "E o Verbo se fez carne e habitou entre nós, e vimos a sua glória, a glória como do único Filho do Pai, cheio de graça e verdade." Este versículo se relaciona com a ideia de que Jesus é o pão da vida que desceu do céu.
* João 3:16: "Porque Deus tanto amou o mundo que deu o seu Filho unigênito, para que todo aquele que nele crer não pereça, mas tenha a vida eterna." Este versículo se relaciona com a ideia de que Jesus é a oferta de vida eterna para aqueles que creem nele.
* João 14:6: "Respondeu Jesus: Eu sou o caminho, a verdade e a vida. Ninguém vem ao Pai, a não ser por mim." Este versículo se relaciona com a ideia de que Jesus é o único caminho para a salvação e a vida eterna.
* João 20:31: "Mas estes foram escritos para que vocês creiam que Jesus é o Cristo, o Filho de Deus, e para que, crendo, tenham vida em seu nome." Este versículo se relaciona com a ideia central de São João 6 de que Jesus é o pão da vida que dá vida eterna e como devemos crer nele para ter essa vida.
****

[[v50-6-1]]

^<<v50-6-1,1>>^ Depois disto, passou Jesus à outra banda do mar da Galileia, isto é, de Tiberíades?

[[v50-6-2]]

^<<v50-6-2,2>>^ Seguia-o uma grande multidão, porque via os milagres que fazia em favor dos enfermos.

[[v50-6-3]]

^<<v50-6-3,3>>^ Jesus subiu a um monte e sentou-se ali com seus discípulos

[[v50-6-4]]

^<<v50-6-4,4>>^ Ora a Páscoa, a festa dos Judeus, estava próxima.

[[v50-6-5]]

^<<v50-6-5,5>>^ Jesus, então, tendo levantado os olhos e visto que vinha ter com ele uma grande multidão, disse a Filipe: "Onde compraremos nós pão, para dar de comer a esta gente?"

[[v50-6-6]]

^<<v50-6-6,6>>^ Dizia, porém, isto para o experimentar, porque sabia o que havia de fazer.

[[v50-6-7]]

^<<v50-6-7,7>>^ Filipe respondeu-lhe: "Duzentos dinheiros de pão não bastam para que cada um receba um pequeno bocado."

[[v50-6-8]]

^<<v50-6-8,8>>^ Um de seus discípulos, André, irmão de Simão Pedro, disse-lhe:

[[v50-6-9]]

^<<v50-6-9,9>>^ "Está aqui um jovem, que tem cinco pães de cevada e dois peixes, mas que é isto para tanta gente?"

[[v50-6-10]]

^<<v50-6-10,10>>^ Jesus, porém, disse: "Mandai sentar essa gente." Havia naquele lugar muita erva. Sentaram-se, pois, os homens, em número de cerca de cinco mil.

[[v50-6-11]]

^<<v50-6-11,11>>^ Tomou, então, Jesus os pães. e, tendo dado graças, distribuiu-os entre os que estavam recostados; e igualmente dos peixes quanto queriam.

[[v50-6-12]]

^<<v50-6-12,12>>^ Estando saciados, disse a seus discípulos: "Recolhei os pedaços que sobejaram, para que nada se perca."

[[v50-6-13]]

^<<v50-6-13,13>>^ Eles os recolheram e encheram doze cestos de pedaços dos cinco pães de cevada, que sobejaram aos que tinham comido.

[[v50-6-14]]

^<<v50-6-14,14>>^ Vendo então aqueles homens o milagre que Jesus fizera, diziam: "Este é verdadeiramente o profeta que deve vir ao mundo."

[[v50-6-15]]

^<<v50-6-15,15>>^ Jesus, sabendo que o viriam arrebatar para o fazerem rei, retirou-se, de novo, ele só para o monte.

[[v50-6-16]]

^<<v50-6-16,16>>^ Quando chegou a tarde, seus discípulos desceram para junto do mar,

[[v50-6-17]]

^<<v50-6-17,17>>^ e, tendo subido para uma barca, atravessaram o mar em direção a Cafarnaum. Era já escuro, e Jesus ainda não tinha ido ter com eles.

[[v50-6-18]]

^<<v50-6-18,18>>^ Entretanto o mar começava a empolar-se, por causa do vento forte que soprava.

[[v50-6-19]]

^<<v50-6-19,19>>^ Tendo remado cerca de vinte e cinco ou trinta estádios, viram Jesus caminhando sobre o mar, em direção à barca, e ficaram atemorizados.

[[v50-6-20]]

^<<v50-6-20,20>>^ Mas ele disse-lhes: "Sou eu, não temais."

[[v50-6-21]]

^<<v50-6-21,21>>^ Quiseram então recebê-lo na barca; e logo a barca chegou à terra, para onde iam.

[[v50-6-22]]

^<<v50-6-22,22>>^ No dia seguinte, a multidão, que tinha ficado da outra banda do mar, advertiu que não havia ali mais que uma barca, e que Jesus não tinha entrado nela com seus discípulos, mas que os seus discípulos tinham partido sós.

[[v50-6-23]]

^<<v50-6-23,23>>^ Entretanto arribaram de Tiberíades outras barcas, perto do lugar onde haviam comido o pão, depois de o Senhor ter dado graças.

[[v50-6-24]]

^<<v50-6-24,24>>^ Tendo, pois, visto a multidão que não estava lá nem Jesus nem os seus discípulos, entrou naquelas barcas e foi a Cafarnaum, em busca de Jesus.

[[v50-6-25]]

^<<v50-6-25,25>>^ Tendo-o encontrado da banda de além do mar, disseram lhe: "Mestre, quando chegaste aqui?"

[[v50-6-26]]

^<<v50-6-26,26>>^ Jesus respondeu-lhes: "Em verdade, em verdade, vos digo: Vós buscais-me, não porque vistes os milagres, mas porque comestes dos pães e ficastes saciados.

[[v50-6-27]]

^<<v50-6-27,27>>^ Trabalhai não pela comida que perece, mas pela que dura até à vida eterna, a qual o Filho do homem vos dará. Porque nele imprimiu Deus Pai o seu selo."

[[v50-6-28]]

^<<v50-6-28,28>>^ Eles, então, disseram-lhe: "Que devemos nós fazer para praticar obras de Deus?"

[[v50-6-29]]

^<<v50-6-29,29>>^ Jesus respondeu: "A obra de Deus é esta: Que acrediteis naquele que enviou."

[[v50-6-30]]

^<<v50-6-30,30>>^ Mas eles disseram-lhe: "Que milagre fazes tu, para que o vejamos e acreditemos em ti? Que fazes tu?

[[v50-6-31]]

^<<v50-6-31,31>>^ Nossos pais comeram o maná no deserto, segundo está escrito: Deu-lhes a, comer o pão do céu. (Ps. 77, 24)."

[[v50-6-32]]

^<<v50-6-32,32>>^ Jesus respondeu-lhes: "Em verdade, em verdade, vos digo: Moisés não vos deu o pão do céu, mas meu Pai é que vos dá o verdadeiro pão do céu.

[[v50-6-33]]

^<<v50-6-33,33>>^ Porque o pão de Deus é o que desceu do céu e dá a vida ao mundo."

[[v50-6-34]]

^<<v50-6-34,34>>^ Então disseram-lhe: "Senhor, dá-nos sempre desse pão"

[[v50-6-35]]

^<<v50-6-35,35>>^ Jesus respondeu-lhes: "Eu sou o pão da vida; o que vem a mim, não terá jamais fome, e o que crê em mim, não terá jamais sede.

[[v50-6-36]]

^<<v50-6-36,36>>^ Porém já vos disse que vós me vistes e que não credes.

[[v50-6-37]]

^<<v50-6-37,37>>^ Tudo o que o Pai me dá, virá a mim; e aquele que vem a mim, não o lançarei fora.

[[v50-6-38]]

^<<v50-6-38,38>>^ Porque desci do céu, não para fazer a minha vontade, mas a vontade daquele que me enviou.

[[v50-6-39]]

^<<v50-6-39,39>>^ Ora a vontade daquele que me enviou, é que eu não perca nada do que me deu, mas que o ressuscite no último dia.

[[v50-6-40]]

^<<v50-6-40,40>>^ A vontade de meu Pai, que me enviou, é que todo o que vê o Filho e crê nele tenha a vida eterna; e eu o ressuscitarei no último dia."

[[v50-6-41]]

^<<v50-6-41,41>>^ Murmuravam, pois, dele os Judeus, porque dissera: "Eu sou o pão que desceu do céu."

[[v50-6-42]]

^<<v50-6-42,42>>^ Diziam: "Por ventura não é este aquele Jesus, filho de José, cujo pai e mãe nós conhecemos? Como, pois, diz ele: Descido céu?"

[[v50-6-43]]

^<<v50-6-43,43>>^ Jesus, replicando, disse-lhes: "Não murmureis entre vós.

[[v50-6-44]]

^<<v50-6-44,44>>^ Ninguém pode vir a mim, se o Pai que me enviou, o não atrair; e eu o ressuscitarei no último dia.

[[v50-6-45]]

^<<v50-6-45,45>>^ Está escrito nos profetas: E serão todos ensinados por Deus (Is. 54, 13). Portanto todo aquele que ouve e aprende do Pai ; vem a mim.

[[v50-6-46]]

^<<v50-6-46,46>>^ Não porque alguém tenha visto o Pai, excepto aquele que vem de Deus; esse viu o Pai.

[[v50-6-47]]

^<<v50-6-47,47>>^ Em verdade, em verdade, vos digo: O que crê em mim, tem a vida eterna.

[[v50-6-48]]

^<<v50-6-48,48>>^ Eu sou o pão da vida.

[[v50-6-49]]

^<<v50-6-49,49>>^ Vossos pais comeram o maná, no deserto, e morreram.

[[v50-6-50]]

^<<v50-6-50,50>>^ Este é o pão que desceu do céu, para que aquele que dele comer não morra,

[[v50-6-51]]

^<<v50-6-51,51>>^ Eu sou o pão vivo, descido do céu. Quem comer deste pão, viverá eternamente; e o pão que eu darei, é a minha carne (que será sacrificada) para a salvação do mundo."

[[v50-6-52]]

^<<v50-6-52,52>>^ Disputavam, então, entre si os Judeus: "Como pode este dar-nos a comer a sua carne?"

[[v50-6-53]]

^<<v50-6-53,53>>^ Jesus disse-lhes: "Em verdade, em verdade, vos digo: Se não comerdes a carne do Filho do homem, e não beberdes o seu sangue, não tereis a vida em vós.

[[v50-6-54]]

^<<v50-6-54,54>>^ O que come a minha carne e bebe o meu sangue, tem a vida eterna, e eu o ressuscitarei no último dia.

[[v50-6-55]]

^<<v50-6-55,55>>^ Porque a minha carne é verdadeiramente comida, e o meu sangue verdadeiramente bebida.

[[v50-6-56]]

^<<v50-6-56,56>>^ O que come a minha carne e bebe o meu sangue, permanece em mim e eu nele.

[[v50-6-57]]

^<<v50-6-57,57>>^ Assim como me enviou o Pai que vive, e eu vivo pelo Pai, assim o que me comer a mim, esse mesmo também viverá por mim

[[v50-6-58]]

^<<v50-6-58,58>>^ Este é o pão que desceu do céu. Não é como o pão que comeram os vossos pais, que morreram. O que come deste pão viverá eternamente."

[[v50-6-59]]

^<<v50-6-59,59>>^ Jesus disse estas coisas, ensinando em Cafarnaum, na Sinagoga

[[v50-6-60]]

^<<v50-6-60,60>>^ Muitos de seus discípulos, ouvindo isto, disseram: "Dura é esta linguagem; quem a pode ouvir?"

[[v50-6-61]]

^<<v50-6-61,61>>^ Jesus, conhecendo em si mesmo que seus discípulos murmuravam por isto, disse-lhes: "Isto escandaliza- vos?

[[v50-6-62]]

^<<v50-6-62,62>>^ Que será quando virdes subir o Filho do homem para onde estava antes?

[[v50-6-63]]

^<<v50-6-63,63>>^ E o espírito que vivifica; a carne para nada aproveita. As palavras que eu vos disse, são espírito e vida.

[[v50-6-64]]

^<<v50-6-64,64>>^ Mas há alguns de vós que não crêem. Com efeito Jesus sabia desde o princípio quais eram os que não criam, e quem havia de o entregar

[[v50-6-65]]

^<<v50-6-65,65>>^ Depois acrescentou: "Por isso eu vos disse que ninguém pode vir a mim, se lhe não for concedido por meu Pai."

[[v50-6-66]]

^<<v50-6-66,66>>^ Desde então muitos de seus discípulos tornaram atrás, e já não andavam com ele.

[[v50-6-67]]

^<<v50-6-67,67>>^ Por isso Jesus disse aos doze: "Quereis vós também retirar-vos?"

[[v50-6-68]]

^<<v50-6-68,68>>^ Simão Pedro respondeu-lhe: "Senhor, para quem havemos nós de ir? Tu tens palavras de vida eterna.

[[v50-6-69]]

^<<v50-6-69,69>>^ E nós acreditamos e conhecemos que tu és o Santo de Deus."

[[v50-6-70]]

^<<v50-6-70,70>>^ Jesus replicou: "Não fui eu que vos escolhi, a vós os doze? E contudo um de vós é um demônio."

[[v50-6-71]]

^<<v50-6-71,71>>^ Falava de Judas, filho de Simão Iscariote, porque era este que o havia de entregar, não obstante ser um dos doze.

'''

xref:050-sao-joao/050-sao-joao-005.adoc#v50-5-0[&#60; Capítulo Anterior] | <<v50-6-0,Topo>> | xref:050-sao-joao/050-sao-joao-007.adoc#v50-7-0[Próximo Capítulo &#62;]