include::./index.adoc[]

[[v50-15-0]]
=== São João, 15
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 15 de João contém as palavras de Jesus sobre a videira verdadeira e seus ramos. Ele ensina a importância de permanecer nele e nos seus mandamentos para produzir frutos. Além disso, ele fala sobre o amor que deve existir entre seus discípulos e que o mundo os odiará por causa dele. Abaixo estão cinco versículos relacionados aos temas abordados em João 15:
* Filipenses 4:13: "Tudo posso naquele que me fortalece." Este versículo fala sobre a importância de confiar em Deus para nos dar força em todas as situações, assim como Jesus enfatiza a importância de permanecer nele para dar frutos.
* Colossenses 1:10: "De modo que possais andar dignamente diante do Senhor, agradando-lhe em tudo, frutificando em toda boa obra, e crescendo no conhecimento de Deus." Assim como Jesus instrui seus discípulos a permanecerem nele para dar frutos, Paulo também enfatiza a importância de frutificar em boas obras e crescer no conhecimento de Deus.
* 1 João 2:6: "Aquele que diz que permanece nele, esse deve também andar assim como ele andou." Este versículo destaca a importância de seguir o exemplo de Jesus e andar em seus caminhos para permanecer nele.
* João 17:14: "Eu lhes dei a tua palavra, e o mundo os odiou, porque não são do mundo, assim como eu não sou do mundo." Assim como Jesus ensina que o mundo odiará seus discípulos por causa do amor que têm uns pelos outros, este versículo destaca a separação entre os seguidores de Cristo e o mundo.
* 1 João 4:7: "Amados, amemo-nos uns aos outros, porque o amor é de Deus; e todo o que ama é nascido de Deus e conhece a Deus." Este versículo enfatiza a importância do amor entre os seguidores de Cristo, assim como Jesus ensina em João 15:12-13 que eles devem amar uns aos outros como ele os amou.
****

[[v50-15-1]]

^<<v50-15-1,1>>^ Eu sou a verdadeira vide, e meu Pai é o vinhateiro.

[[v50-15-2]]

^<<v50-15-2,2>>^ Toda a vara que não dá fruto em mim, ele a cortará; e toda a que der fruto, podá-la-á, para que dê mais abundante fruto.

[[v50-15-3]]

^<<v50-15-3,3>>^ Vós já estais puros em virtude da palavra que vos anunciei.

[[v50-15-4]]

^<<v50-15-4,4>>^ Permanecei em mim, e eu permanecerei em vós. Como a vara não pode de si mesma dar fruto, se não permanecer na videira, assim também vós, se não permanecerdes em mim.

[[v50-15-5]]

^<<v50-15-5,5>>^ Eu sou a videira, vós as varas. O que permanece em mim e eu nele, esse dá muito fruto, porque, sem mim, nada podeis fazer.

[[v50-15-6]]

^<<v50-15-6,6>>^ Se alguém não permanecer em mim, será lançado fora, como a vara, e secará; depois enfeixá-lo-ão, lançá-lo-ão no fogo, e arderá.

[[v50-15-7]]

^<<v50-15-7,7>>^ Se permanecerdes em mim, e as minhas palavras permanecerem em vós, pedireis tudo o que quiserdes, e ser-vos-á concedido.

[[v50-15-8]]

^<<v50-15-8,8>>^ Nisto é glorificado meu Pai, em que vós deis muito fruto e sejais meus discípulos.

[[v50-15-9]]

^<<v50-15-9,9>>^ Como o Pai me amou, assim eu vos amei. Permanecei no meu amor,

[[v50-15-10]]

^<<v50-15-10,10>>^ Se observardes os meus preceitos, permanecereis no meu amor, como eu observei os preceitos de meu Pai, e permaneço no seu amor.

[[v50-15-11]]

^<<v50-15-11,11>>^ Disse-vos estas coisas, para que a minha alegria esteja em vós, e para que a vossa alegria seja completa.

[[v50-15-12]]

^<<v50-15-12,12>>^ O meu preceito é este: Amai-vos uns aos outros, como eu vos amei.

[[v50-15-13]]

^<<v50-15-13,13>>^ Não há maior amor do que dar a própria vida pelos seus amigos.

[[v50-15-14]]

^<<v50-15-14,14>>^ Vós sois meus amigos, se fizerdes o que vos mando.

[[v50-15-15]]

^<<v50-15-15,15>>^ Não mais vos chamarei servos, porque o servo não sabe o que faz o seu senhor; mas chamo-vos amigos, porque vos dei a conhecer tudo o que ouvi de meu Pai.

[[v50-15-16]]

^<<v50-15-16,16>>^ Não fostes vós que me escolhestes, mas fui eu que vos escolhi a vós, e vos destinei para que vades e deis fruto, e para que o vosso fruto permaneça, a fim de que tudo o que pedirdes a meu Pai em meu nome, ele vo-lo conceda.

[[v50-15-17]]

^<<v50-15-17,17>>^ Isto vos mando: Amai-vos uns aos outros.

[[v50-15-18]]

^<<v50-15-18,18>>^ Se o mundo vos aborrece, sabei que, primeiro do que a vós, me aborreceu a mim.

[[v50-15-19]]

^<<v50-15-19,19>>^ Se fosseis do mundo, o mundo amaria o que era seu; mas, porque não sois do mundo, antes eu vos escolhi do meio do mundo, por isso o mundo vos aborrece.

[[v50-15-20]]

^<<v50-15-20,20>>^ Lembrai-vos da palavra que eu vos disse: Não é o servo maior do que o senhor. Se eles me perseguirem a mim, também vos hão-de perseguir a vós; se guardaram a minha palavra, também hão-de guardar a vossa.

[[v50-15-21]]

^<<v50-15-21,21>>^ Mas tudo isto vos farão por causa do meu nome, porque não conhecem aquele que me enviou.

[[v50-15-22]]

^<<v50-15-22,22>>^ Se eu não tivesse vindo e não lhes tivesse falado, não teriam culpa, mas agora não têm desculpa do seu pecado.

[[v50-15-23]]

^<<v50-15-23,23>>^ Aquele que me aborrece, aborrece também meu Pai.

[[v50-15-24]]

^<<v50-15-24,24>>^ Se eu não tivesse feito entre eles tais obras, quais nenhum outro fez, não teriam culpa, mas agora viram-nas, e, contudo, odeiam-nos, a mim e a meu Pai.

[[v50-15-25]]

^<<v50-15-25,25>>^ Mas isto aconteceu para se cumprir a palavra que está escrita na sua Lei: Odiaram-me sem motivo (Ps. 34, 19 ; Ps. 68, 6).

[[v50-15-26]]

^<<v50-15-26,26>>^ Quando, porém, vier o Paráclito, que eu vos enviarei do Pai, o Espirito da verdade, que procede do Pai, ele dará testemunho de mim.

[[v50-15-27]]

^<<v50-15-27,27>>^ E vós também dareis testemunho, porque estais comigo desde o princípio.

'''

xref:050-sao-joao/050-sao-joao-014.adoc#v50-14-0[&#60; Capítulo Anterior] | <<v50-15-0,Topo>> | xref:050-sao-joao/050-sao-joao-016.adoc#v50-16-0[Próximo Capítulo &#62;]