include::./index.adoc[]

[[v28-23-0]]
=== Eclesiástico, 23
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Eclesiástico 23 trata principalmente da importância de se controlar os desejos carnais e de se manter a pureza sexual. O autor adverte sobre as consequências desastrosas do adultério, da fornicação e da luxúria, e aconselha a buscar a sabedoria divina para evitar esses pecados. Abaixo estão cinco versículos relacionados com os temas abordados em Eclesiástico 23:
* Provérbios 6:32: "O que adultera com uma mulher é falto de entendimento; aquele que faz isso destrói a sua própria alma." Este versículo destaca a tolice do adultério e os danos que ele pode causar à pessoa que o comete.
* 1 Coríntios 6:18: "Fugi da fornicação. Todo o pecado que o homem comete é fora do corpo; mas o que fornica peca contra o seu próprio corpo." O apóstolo Paulo também enfatiza a importância de se manter longe da imoralidade sexual e destaca que esse pecado é especialmente prejudicial ao corpo.
* Mateus 5:27-28: "Ouvistes que foi dito aos antigos: Não cometerás adultério. Eu, porém, vos digo que qualquer que olhar para uma mulher com intenção impura, em seu coração já cometeu adultério com ela." Jesus ensina que a pureza sexual não se limita apenas às ações, mas também aos pensamentos e desejos.
* Colossenses 3:5: "Mortificai, pois, os vossos membros, que estão sobre a terra: a prostituição, a impureza, o apetite desordenado, a vil concupiscência, e a avareza, que é idolatria." O apóstolo Paulo instrui os cristãos a mortificar seus desejos carnais e a buscar as coisas do alto.
* Hebreus 13:4: "Digno de honra entre todos seja o matrimônio e o leito sem mácula; porém aos que se dão à prostituição, e aos adúlteros, Deus os julgará." Este versículo destaca a santidade do casamento e a seriedade do pecado da prostituição e do adultério.
****

[[v28-23-1]]

^<<v28-23-1,1>>^ Senhor, que és meu pai e dono da minha vida, não me abandones ao conselho dos meus lábios, nem permitas que eu caia por causa deles.

[[v28-23-2]]

^<<v28-23-2,2>>^ Quem aplicará ao meu pensamento o açoite (das correcções)e (fará sentir) ao meu coração a disciplina da sabedoria, para eu não ser poupado no respeitante às minhas faltas, a fim de que não apareçam os meu pecados.

[[v28-23-3]]

^<<v28-23-3,3>>^ para que se não aumentem as minhas ignorâncias, se não multipliquem os meus delitos, não abundem os meus pecados, e eu não caia diante dos meus adversários.

[[v28-23-4]]

^<<v28-23-4,4>>^ e folgue de me ver arruinado o meu inimigo? Senhor, meu pai e Deus da minha vida, não me abandones às suas sugestões.

[[v28-23-5]]

^<<v28-23-5,5>>^ Não permitas a imodéstia dos meus olhares, e afasta de mim todo o (mau) desejo.

[[v28-23-6]]

^<<v28-23-6,6>>^ Afasta de mim a intemperança, e não se apodere de mim a paixão da impureza, e não me entregues a uma alma sem vergonha e sem recato.

[[v28-23-7]]

^<<v28-23-7,7>>^ Ouvi, filhos, as regras que vos dou sobre a moderação da língua Aquele que as guardar, não perecerá pelos lábios, nem cairá em acções criminosas.

[[v28-23-8]]

^<<v28-23-8,8>>^ O pecador será colhido na sua leviandade, e o soberbo e o maldizente encontrarão nela motivos de queda.

[[v28-23-9]]

^<<v28-23-9,9>>^ A tua boca não se acostume ao juramento, porque isto é causa de muitas quedas.

[[v28-23-10]]

^<<v28-23-10,10>>^ O nome de Deus não esteja sempre na tua boca (para jurar), e não mistures nas tuas conversas os nomes dos santos, porque nisto não serás isento de falta.

[[v28-23-11]]

^<<v28-23-11,11>>^ Pois, assim como o escravo, posto frequentemente à tortura, não se livra das pisaduras, assim todo o homem que jura e invoca (a cada passo) o nome de Deus, não será de todo isento de pecado.

[[v28-23-12]]

^<<v28-23-12,12>>^ O homem que jura muito será cheio de iniquidade, e a desgraça não se apartará de sua casa.

[[v28-23-13]]

^<<v28-23-13,13>>^ Se não cumprir o juramento, o seu pecado será sobre ele; se dissimular, peca duplamente.

[[v28-23-14]]

^<<v28-23-14,14>>^ Se jurar em vão, não terá desculpa, e a sua casa será cheia de castigos.

[[v28-23-15]]

^<<v28-23-15,15>>^ Há uma outra palavra que merece a morte, e nunca ela se ouça entre os descendentes de Jacob. (ver nota)

[[v28-23-16]]

^<<v28-23-16,16>>^ Tudo isto será retirado dos homens pios, que não serão envoltos em tais pecados.

[[v28-23-17]]

^<<v28-23-17,17>>^ Não se acostume a tua boca a palavras desordenadas, porque nelas há sempre pecado.

[[v28-23-18]]

^<<v28-23-18,18>>^ Lembra-te do teu pai e da tua mãe, quando te sentares no meio dos grandes,

[[v28-23-19]]

^<<v28-23-19,19>>^ para não acontecer que Deus se esqueça de ti, diante desses mesmos grandes, e, enfatuado com a tua familiaridade, sofras algum impropério, (para não acontecer que) chegues a desejar antes não ter nascido, e amaldiçoes o dia do teu nascimento.

[[v28-23-20]]

^<<v28-23-20,20>>^ O homem acostumado a dizer impropérios nunca se corrigirá em toda a sua vida.

[[v28-23-21]]

^<<v28-23-21,21>>^ Duas sortes de pessoas pecam muitas vezes, e a terceira atrai a ira e a perdição.

[[v28-23-22]]

^<<v28-23-22,22>>^ A alma ardente como um fogo aceso não se acalma sem ter devorado alguma coisa.

[[v28-23-23]]

^<<v28-23-23,23>>^ O homem, que abusa do seu corpo, não terá sossego enquanto não acender o fogo.

[[v28-23-24]]

^<<v28-23-24,24>>^ Todo o pão é doce para o homem voluptuoso; não se cansará de pecar até ao fim da vida.

[[v28-23-25]]

^<<v28-23-25,25>>^ Todo o homem que desonra o seu tálamo (conjugal), despreza a sua alma, dizendo: Quem me vê?

[[v28-23-26]]

^<<v28-23-26,26>>^ As trevas cercam-me, as paredes escondem-me, e ninguém de parte alguma olha para mim; de quem tenho eu receio? O Altíssimo não se lembrará dos meus pecados.

[[v28-23-27]]

^<<v28-23-27,27>>^ (Esse homem) não considera que os olhos do Senhor vêem todas as coisas, que um semelhante temor humano expele de si o temor de Deus, e que os olhos dos homens são unicamente os que o fazem temer.

[[v28-23-28]]

^<<v28-23-28,28>>^ Não sabe que os olhos do Senhor são muito mais luminosos do que o Sol, que em torno estão vendo todos os caminhos dos homens, que penetram o profundo do abismo e os corações dos mesmos homens, até aos mais ocultos esconderijos.

[[v28-23-29]]

^<<v28-23-29,29>>^ Com efeito, o Senhor Deus, assim como conhecia todas as coisas antes de as ter criado, assim também agora, depois que as criou, as vê todas.

[[v28-23-30]]

^<<v28-23-30,30>>^ Este tal será punido nas praças da cidade, será posto em fuga como um potro de égua, e, onde ele menos o esperar, será apanhado. (ver nota)

[[v28-23-31]]

^<<v28-23-31,31>>^ Será vexado diante de todos. por isso mesmo que não compreendeu o temor do Senhor.

[[v28-23-32]]

^<<v28-23-32,32>>^ Assim (perecerá) também toda a mulher que deixa o seu marido, e que lhe dá por herdeiro o fruto duma união adúltera.

[[v28-23-33]]

^<<v28-23-33,33>>^ Porque primeiramente ela foi desobediente à lei do Altíssimo; em segundo lugar pecou contra o seu marido: em terceiro lugar cometeu um adultério. e deu-se a si filhos doutro, que não era seu esposo.

[[v28-23-34]]

^<<v28-23-34,34>>^ Esta mulher será levada à assembleia, e serão lançados os olhares sobre seus filhos.

[[v28-23-35]]

^<<v28-23-35,35>>^ Os seus filhos não lançarão raízes, os ramos dela não darão fruto.

[[v28-23-36]]

^<<v28-23-36,36>>^ Deixará uma memória maldita, e nunca mais se apagará a sua infâmia.

[[v28-23-37]]

^<<v28-23-37,37>>^ E os que vierem depois dela conhecerão que não há coisa melhor do que o temor de Deus e que nada há mais doce do que observar os mandamentos do Senhor.

[[v28-23-38]]

^<<v28-23-38,38>>^ É uma grande glória seguir o Senhor, porque é dele que se receberá larga vida.

'''

xref:028-eclesiastico/028-eclesiastico-022.adoc#v28-22-0[&#60; Capítulo Anterior] | <<v28-23-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-024.adoc#v28-24-0[Próximo Capítulo &#62;]