include::./index.adoc[]

[[v28-45-0]]
=== Eclesiástico, 45
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 45 do livro de Eclesiástico descreve o papel e as realizações de Moisés como um grande líder e profeta na história do povo de Israel. Alguns dos temas abordados incluem a escolha de Deus de Moisés como líder, a forma como ele libertou o povo de Israel do Egito, sua relação especial com Deus e sua liderança exemplar.
* Deuteronômio 34:10-12: "E nunca mais se levantou em Israel profeta como Moisés, a quem o SENHOR conhecera face a face; segundo todos os sinais e maravilhas que o SENHOR lhe mandou fazer na terra do Egito, a Faraó, e a todos os seus servos, e a toda a sua terra; e segundo aquela mão poderosa, e segundo todos os grandes e terríveis feitos que Moisés fez à vista de todo o Israel." Este versículo destaca a singularidade de Moisés como um profeta e líder em Israel, e como ele realizou muitos sinais e maravilhas em nome do Senhor.
* Êxodo 33:11: "E falava o SENHOR a Moisés face a face, como qualquer fala a seu amigo; depois tornava-se ao arraial; mas o seu servidor, o jovem Josué, filho de Num, nunca se apartava do meio da tenda." Este versículo destaca a relação especial que Moisés teve com Deus, que lhe permitiu falar com ele face a face.
* Deuteronômio 34:5: "Assim Moisés, servo do SENHOR, morreu ali na terra de Moabe, conforme a palavra do SENHOR." Este versículo descreve a morte de Moisés e como ele foi um servo fiel do Senhor até o fim.
* Êxodo 14:21-22: "Então Moisés estendeu a sua mão sobre o mar, e o SENHOR fez retirar o mar por um forte vento oriental toda aquela noite; e o mar tornou-se em seco, e as águas foram partidas. E os filhos de Israel entraram pelo meio do mar em seco; e as águas foram-lhes como muro à sua direita e à sua esquerda." Este versículo descreve a ação de Moisés em liderar o povo de Israel através do Mar Vermelho, com a ajuda do Senhor.
* Números 12:7-8: "Não é assim com o meu servo Moisés, que é fiel em toda a minha casa. Cara a cara falo com ele, e claramente, e não por enigmas; pois ele contempla a semelhança do SENHOR. Por que, pois, não tivestes temor de falar contra o meu servo, contra Moisés?" Este versículo destaca novamente a relação especial entre Moisés e Deus, e como ele foi fiel em sua liderança do povo de Israel.
****

[[v28-45-1]]

^<<v28-45-1,1>>^ Moisés foi amado de Deus e dos homens; a sua memória está em bênção.

[[v28-45-2]]

^<<v28-45-2,2>>^ (O Senhor) fê-lo semelhante em glória aos santos, engrandeceu-o e tornou-o terrível aos seus inimigos; (o mesmo Senhor) com as palavras dele (Moisés) fez cessar os prodígios.

[[v28-45-3]]

^<<v28-45-3,3>>^ Glorificou-o diante dos reis, prescreveu-lhe preceitos diante do seu povo, e fez-lhe ver a sua glória.

[[v28-45-4]]

^<<v28-45-4,4>>^ Pela sua fé e mansidão o santificou, e o escolheu dentre todos os homens.

[[v28-45-5]]

^<<v28-45-5,5>>^ (Deus) ouviu-o a ele, escutou a sua voz, e fê-lo entrar na nuvem.

[[v28-45-6]]

^<<v28-45-6,6>>^ Deu-lhe os seus preceitos, frente a frente; e a lei da vida e da ciência, para ensinar a sua aliança a Jacob, e as suas ordens a Israel. (ver nota)

[[v28-45-7]]

^<<v28-45-7,7>>^ Exaltou seu irmão Aarão, semelhante a ele, da tribo de Levi.

[[v28-45-8]]

^<<v28-45-8,8>>^ Estabeleceu com ele um pacto eterno, deu-lhe o sacerdócio do seu povo, encheu-o de felicidade e de glória,

[[v28-45-9]]

^<<v28-45-9,9>>^ cingiu-o dum cinto de honra, revestiu-o duma vestidura de glória, coroou-o com as insígnias do poder.

[[v28-45-10]]

^<<v28-45-10,10>>^ Pôs-lhe a vestidura talar, a túnica interior e o éfode, com uma cercadura de numerosas campainhas ouro,

[[v28-45-11]]

^<<v28-45-11,11>>^ a fim de que elas tocassem quando ele andasse, e se ouvisse o seu som no templo para advertir os filhos do seu povo.

[[v28-45-12]]

^<<v28-45-12,12>>^ (Deu-lhe) uma vestidura santa, tecida de ouro, de jacinto e de púrpura, obra dum varão sábio, dotado de juízo e de verdade. (ver nota)

[[v28-45-13]]

^<<v28-45-13,13>>^ Era uma obra de artista, de fio de escarlate, com pedras preciosas gravadas encastoadas em ouro, e trabalhadas por indústria do lapidário, para memória das doze tribos de Israel.

[[v28-45-14]]

^<<v28-45-14,14>>^ Sobre a sua tiara (colocou) uma coroa de ouro, onde estava gravado o selo da santidade e a glória soberana; era uma obra primorosa e um adorno que arrebatava os olhos. (ver nota)

[[v28-45-15]]

^<<v28-45-15,15>>^ Não houve, nunca, antes deste (adorno sacerdotal) coisas tão preciosas, desde o princípio do mundo.

[[v28-45-16]]

^<<v28-45-16,16>>^ Dele se não vestiu pessoa alguma doutra família, mas só os seus filhos e os seus netos, por todo o decurso das idades.

[[v28-45-17]]

^<<v28-45-17,17>>^ Os seus sacrifícios eram diariamente consumidos pelo fogo.

[[v28-45-18]]

^<<v28-45-18,18>>^ Moisés encheu-lhe as mãos, e ungiu-o com óleo santo.

[[v28-45-19]]

^<<v28-45-19,19>>^ Foi-lhe concedido, por um pacto eterno, e aos seus descendentes enquanto durarem os dias do céu, o exercer as funções do sacerdócio, cantar os louvores (de Deus), e abençoar o seu povo em seu nome.

[[v28-45-20]]

^<<v28-45-20,20>>^ Ele o escolheu dentre os viventes para oferecer a Deus o sacrifício, o incenso e o perfume de lembrança, e para fazer a expiação pelo povo.

[[v28-45-21]]

^<<v28-45-21,21>>^ Deu-lhe poder relativamente aos seus preceitos e às disposições dos seus julgamentos, para ensinar os seus mandamentos a Jacob, e para dar a Israel a inteligência da sua lei.

[[v28-45-22]]

^<<v28-45-22,22>>^ Sublevaram-se contra ele uns estranhos (ao sacerdócio); por inveja o cercaram no deserto homens, que eram do partido de Datan e Abiron, e a facção de Coré, toda acesa em ira.

[[v28-45-23]]

^<<v28-45-23,23>>^ Viu isto o Senhor Deus, e não lhe agradou, e foram consumidos pela impetuosidade da sua cólera.

[[v28-45-24]]

^<<v28-45-24,24>>^ Operou contra eles prodígios, e consumiu-os com chamas de fogo.

[[v28-45-25]]

^<<v28-45-25,25>>^ Acrescentou a glória a Aarão, deu-lhe uma herança, concedeu-lhe as primícias dos frutos da terra.

[[v28-45-26]]

^<<v28-45-26,26>>^ Nas primícias preparou-lhe alimento em abundância; com efeito (os sacerdotes) devem comer dos sacrifícios do Senhor, os quais lhe deu a ele e à sua descendência.

[[v28-45-27]]

^<<v28-45-27,27>>^ Mas não tem herança na terra das nações. nem porção entre os do seu povo, porque o mesmo Deus é a sua porção e herança.

[[v28-45-28]]

^<<v28-45-28,28>>^ Fineias, filho de Eleazar, é o terceiro em glória, imitando-o (a Moisés) no temor do Senhor.

[[v28-45-29]]

^<<v28-45-29,29>>^ Permaneceu firme no meio da queda vergonhosa do povo; pela bondade e zelo da sua alma aplacou Deus em favor de Israel.

[[v28-45-30]]

^<<v28-45-30,30>>^ Por isso é que Deus fez com ele uma aliança de paz, constituindo-o príncipe do santuário e do seu povo. a fim de que a dignidade sacerdotal pertencesse sempre a ele e à sua descendência.

[[v28-45-31]]

^<<v28-45-31,31>>^ (Deus) também fez uma aliança (semelhante) com o rei Davide, filho de Jessé, da tribo de Judá, constituindo-o herdeiro (do reino), a ele e à sua linhagem, a fim de dar sabedoria ao nosso coração, e julgar o seu povo com justiça. para que não se perdesse a sua felicidade. É tornou eterna a glória destes (rarões) em sua nação. (ver nota)

'''

xref:028-eclesiastico/028-eclesiastico-044.adoc#v28-44-0[&#60; Capítulo Anterior] | <<v28-45-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-046.adoc#v28-46-0[Próximo Capítulo &#62;]