include::./index.adoc[]

[[v28-21-0]]
=== Eclesiástico, 21
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Eclesiástico 21 fala sobre a sabedoria e os caminhos de Deus, destacando a importância de escolher a justiça e a humildade. O capítulo também aborda os perigos da arrogância e da ignorância. Abaixo estão cinco versículos da Bíblia que abordam temas relacionados a este capítulo.
* Provérbios 3:7: "Não seja sábio aos seus próprios olhos; tema o Senhor e evite o mal." Este versículo enfatiza a importância de temer a Deus e de não confiar na própria sabedoria.
* Salmos 25:9: "Ele guia os humildes na justiça e ensina aos seus caminhos." Deus guia aqueles que são humildes e escolhem o caminho da justiça.
* Provérbios 16:18: "A arrogância precede a ruína, e a altivez do espírito precede a queda." Este versículo adverte sobre os perigos da arrogância e da altivez.
* Provérbios 17:27: "Quem tem conhecimento controla as palavras; quem é prudente e tem discernimento é calmo." A sabedoria vem com o autocontrole e a prudência, permitindo que sejamos calmos e cuidadosos com nossas palavras e ações.
* Tiago 1:5: "Se algum de vocês tem falta de sabedoria, peça a Deus, que a todos dá livremente, de boa vontade; e lhe será concedido." Este versículo destaca a importância de pedir a Deus sabedoria e de confiar nele para nos guiar em nossas decisões.
****

[[v28-21-1]]

^<<v28-21-1,1>>^ Filho, pecaste? Não tornes a pecar, mas faze oração pelas tuas faltas passadas, para que te sejam perdoadas.

[[v28-21-2]]

^<<v28-21-2,2>>^ Foge dos pecados como de uma serpente, porque, se te aproximares, serás apanhado.

[[v28-21-3]]

^<<v28-21-3,3>>^ Os seus dentes são dentes de leão, que matam as almas dos homens.

[[v28-21-4]]

^<<v28-21-4,4>>^ Todo o pecado é como uma espada de dois fios; a sua ferida não tem cura.

[[v28-21-5]]

^<<v28-21-5,5>>^ O ultraje e as violências aniquilam a riqueza; a mais opulenta casa será destruída pela soberba; do mesmo modo os bens do soberbo serão arrancados pela raiz.

[[v28-21-6]]

^<<v28-21-6,6>>^ A súplica do pobre chegará desde a sua boca até aos ouvidos de Deus, e prontamente lhe será feita justiça.

[[v28-21-7]]

^<<v28-21-7,7>>^ Aquele que aborrece a repreensão caminha por cima das pegadas do pecador; aquele que teme a Deus converter-se-á do (intimo do) seu coração.

[[v28-21-8]]

^<<v28-21-8,8>>^ O homem poderoso de língua insolente dá-se a conhecer ao longe, mas o sábio sabe escapar-se dele.

[[v28-21-9]]

^<<v28-21-9,9>>^ Aquele que edifica a sua casa à custa alheia, é como o que ajunta as suas pedras no inverno.

[[v28-21-10]]

^<<v28-21-10,10>>^ A assembleia dos pecadores é como um montão de estopa: o seu fim será a fogueira.

[[v28-21-11]]

^<<v28-21-11,11>>^ O caminho dos pecadores é calcetado de pedras unidas entre si, mas vai dar à habitação dos mortos, às trevas e aos tormentos.

[[v28-21-12]]

^<<v28-21-12,12>>^ Aquele que guarda a justiça penetrará o espírito dela.

[[v28-21-13]]

^<<v28-21-13,13>>^ A sabedoria e o bom senso são a consumação do temor de Deus.

[[v28-21-14]]

^<<v28-21-14,14>>^ Aquele que não é sábio no bem, nunca será (bem) instruído.

[[v28-21-15]]

^<<v28-21-15,15>>^ Há uma sabedoria que é fecunda no mal, e não há bom senso onde há amargura.

[[v28-21-16]]

^<<v28-21-16,16>>^ A ciência do sábio derrama-se abundantemente, como (água de) uma inundação, e o seu conselho permanece como uma fonte de vida.

[[v28-21-17]]

^<<v28-21-17,17>>^ O coração do insensato é como um vaso rachado: nada pode reter da sabedoria.

[[v28-21-18]]

^<<v28-21-18,18>>^ O sábio, ouvindo qualquer palavra judiciosa, louvá-la-á e aplicá-la-á a si; se porém a ouve o voluptuoso, não lhe agradará, e deitá-la-á para trás das costas.

[[v28-21-19]]

^<<v28-21-19,19>>^ A conversação do insensato é (aborrecida) como uma carga durante a viagem, mas nos lábios do sensato achar-se-á a graça.

[[v28-21-20]]

^<<v28-21-20,20>>^ A boca do homem prudente é buscada na assembleia: as pessoas pensarão nas suas palavras dentro dos seus corações.

[[v28-21-21]]

^<<v28-21-21,21>>^ A sabedoria é para o insensato como uma casa arruinada; a ciência do insensato reduz-se a palavras sem sentido.

[[v28-21-22]]

^<<v28-21-22,22>>^ A doutrina é para o insensato como grilhões nos pés, e como algemas na mão direita. (ver nota)

[[v28-21-23]]

^<<v28-21-23,23>>^ O insensato, quando se ri, levanta a sua voz; mas o varão sábio apenas se sorri discretamente.

[[v28-21-24]]

^<<v28-21-24,24>>^ A ciência é para o homem prudente um ornamento de ouro, e como um bracelete no seu braço direito.

[[v28-21-25]]

^<<v28-21-25,25>>^ O pé do insensato é fácil em se meter em casa do vizinho, porém o homem educado retrai-se diante duma pessoa poderosa.

[[v28-21-26]]

^<<v28-21-26,26>>^ O insensato olha pela janela dentro duma casa, mas o homem educado conserva-se fora.

[[v28-21-27]]

^<<v28-21-27,27>>^ É má educação escutar a uma porta; ao prudente será insuportável esta grosseria.

[[v28-21-28]]

^<<v28-21-28,28>>^ Os lábios dos imprudentes dirão fatuidades, mas as palavras dos homens prudentes serão pesadas na balança.

[[v28-21-29]]

^<<v28-21-29,29>>^ O coração dos insensatos está na sua boca, e a boca dos sábios está no seu coração.

[[v28-21-30]]

^<<v28-21-30,30>>^ Quando o ímpio amaldiçoa o inimigo, amaldiçoa-se a si mesmo.

[[v28-21-31]]

^<<v28-21-31,31>>^ O mexeriqueiro mancha-se a si próprio, e é aborrecido de todos; o que mora com ele será odioso; o homem prudente, que se cala, será honrado.

'''

xref:028-eclesiastico/028-eclesiastico-020.adoc#v28-20-0[&#60; Capítulo Anterior] | <<v28-21-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-022.adoc#v28-22-0[Próximo Capítulo &#62;]