include::./index.adoc[]

[[v28-33-0]]
=== Eclesiástico, 33
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Eclesiástico 33 trata principalmente sobre a sabedoria divina e como essa sabedoria é transmitida aos seres humanos. O capítulo também destaca a importância da obediência e da humildade em relação a Deus. Os versículos a seguir estão relacionados aos temas abordados em Eclesiástico 33:
* Provérbios 3:7 - "Não sejas sábio a teus próprios olhos; teme ao Senhor e aparta-te do mal." Este versículo enfatiza a importância de não confiar na própria sabedoria e de ter temor a Deus.
* Provérbios 19:20 - "Ouve o conselho e recebe a correção, para que sejas sábio no teu futuro." Este versículo destaca a importância de ouvir os conselhos e de aceitar a correção para que possamos crescer em sabedoria.
* Salmos 25:9 - "Ele guiará os mansos no juízo e ensinará aos mansos o seu caminho." Este versículo destaca a importância da humildade e da mansidão em relação a Deus, que guiará e ensinará aqueles que têm esse espírito.
* Isaías 55:8-9 - "Porque os meus pensamentos não são os vossos pensamentos, nem os vossos caminhos os meus caminhos, diz o Senhor. Porque, assim como os céus são mais altos do que a terra, assim são os meus caminhos mais altos do que os vossos caminhos, e os meus pensamentos mais altos do que os vossos pensamentos." Este versículo destaca a diferença entre a sabedoria divina e a sabedoria humana, e a importância de confiar na sabedoria de Deus.
* Provérbios 1:7 - "O temor do Senhor é o princípio da sabedoria; os loucos desprezam a sabedoria e a instrução." Este versículo enfatiza a importância do temor a Deus como ponto de partida para a sabedoria, e destaca a loucura daqueles que desprezam a sabedoria e a instrução.
****

[[v28-33-1]]

^<<v28-33-1,1>>^ Aquele que teme o Senhor não sobrevirão desgraças, antes Deus o guardará na tentação e o livrará dos males.

[[v28-33-2]]

^<<v28-33-2,2>>^ O sábio não aborrece os mandamentos nem as leis, e não se fará em pedaços como o navio na tempestade.

[[v28-33-3]]

^<<v28-33-3,3>>^ O homem sensato crê na lei de Deus, e a lei é fiel para com ele.

[[v28-33-4]]

^<<v28-33-4,4>>^ Prepara o teu discurso, e, deste modo, serás ouvido; junta o teu saber e depois responde.

[[v28-33-5]]

^<<v28-33-5,5>>^ O coração do insensato é como as rodas de um carro, e o seu pensamento é como um eixo que gira.

[[v28-33-6]]

^<<v28-33-6,6>>^ O amigo zombador é como um garanhão, que relincha debaixo de qualquer que o monta.

[[v28-33-7]]

^<<v28-33-7,7>>^ Por que é que um dia é preferido a outro dia, uma luz a outra luz, e um ano a outro ano, provindo todos do mesmo Sol?

[[v28-33-8]]

^<<v28-33-8,8>>^ Foi a ciência do Senhor que os diferenciou, quando criou o Sol, o qual obedece às suas ordens.

[[v28-33-9]]

^<<v28-33-9,9>>^ Distinguiu as estações e os seus dias de festa, em que (os homens) celebram as solenidades a hora determinada.

[[v28-33-10]]

^<<v28-33-10,10>>^ Destes mesmos dias fez Deus a uns grandes e sagrados, e a outros pôs no número dos dias comuns. Assim, igualmente, todos os homens são feitos do pó, da terra de que Adão foi formado.

[[v28-33-11]]

^<<v28-33-11,11>>^ O Senhor, porém, pela grandeza da sua sabedoria, distinguiu-os, diversificou os seus caminhos.

[[v28-33-12]]

^<<v28-33-12,12>>^ A uns abençoou e exaltou; a outros santificou e tomou para si; a outros amaldiçoou e humilhou, e deitou abaixo do seu lugar. (ver nota)

[[v28-33-13]]

^<<v28-33-13,13>>^ Como o barro está nas mãos do oleiro, para lhe dar a forma e disposição que deseja,

[[v28-33-14]]

^<<v28-33-14,14>>^ e para o empregar nos usos que lhe aprouver, assim o homem se encontra na mão daquele que o criou, e que lhe dará segundo o seu juízo. (ver nota)

[[v28-33-15]]

^<<v28-33-15,15>>^ Contra o mal está o bem, e contra a morte a vida; assim também contra o homem justo está o pecador. Considera assim todas as obras do Altíssimo; achá-las-ás duas a duas, e uma oposta à outra.

[[v28-33-16]]

^<<v28-33-16,16>>^ E eu fui o ultimo que despertei, e fui como o que ajunta os bagos atrás dos vindimadores.

[[v28-33-17]]

^<<v28-33-17,17>>^ Eu também esperei na bênção de Deus, e enchi o lagar como o que vindima.

[[v28-33-18]]

^<<v28-33-18,18>>^ Olhai que eu não trabalhei só para mim, mas para todos os que buscam a instrução.

[[v28-33-19]]

^<<v28-33-19,19>>^ Ouvi-me, ó grandes e todos os povos, e vós, os que presidis às assembleias, aplicai os ouvidos.

[[v28-33-20]]

^<<v28-33-20,20>>^ Ao teu filho, à tua mulher, ao teu irmão, ao teu amigo não dês em tua vida poder sobre ti; não dês a outro os bens que possuis, para que não suceda arrependeres-te disso e tomares a pedir-lhos.

[[v28-33-21]]

^<<v28-33-21,21>>^ Enquanto viveres e respirares, ninguém te faça mudar sobre este ponto.

[[v28-33-22]]

^<<v28-33-22,22>>^ porque melhor é que teus filhos te peçam, do que estares tu olhando para as mãos de teus filhos.

[[v28-33-23]]

^<<v28-33-23,23>>^ Em todas as tuas obras conserva a tua superioridade.

[[v28-33-24]]

^<<v28-33-24,24>>^ Não manches o teu bom nome. No dia em que terminar o curso da tua vida, no tempo da tua morte, reparte a tua herança.

[[v28-33-25]]

^<<v28-33-25,25>>^ Ao asno, penso, vara e carga; ao escravo, pão, correcção e trabalho.

[[v28-33-26]]

^<<v28-33-26,26>>^ Ele trabalha quando o castigam, doutra sorte não cuida senão em descansar; afrouxa-lhe as mãos, e buscará a liberdade.

[[v28-33-27]]

^<<v28-33-27,27>>^ O jugo e as correias fazem curvar o pescoço duro, assim as tarefas contínuas amansam o escravo.

[[v28-33-28]]

^<<v28-33-28,28>>^ Ao escravo malévolo, tortura e ferros: manda-o para o trabalho a fim de que não esteja ocioso,

[[v28-33-29]]

^<<v28-33-29,29>>^ porque a ociosidade ensina muita malícia.

[[v28-33-30]]

^<<v28-33-30,30>>^ Põe-no ao trabalho, porque assim lhe convém. Mas, se ele te não obedecer, aperreia-o com grilhões; porém não cometas excessos seja com quem for, e não faças coisa alguma grave sem ter reflectido.

[[v28-33-31]]

^<<v28-33-31,31>>^ Se tens um escravo fiel, estima-o como a ti próprio, trata-o como um irmão, porque o adquiriste à custa do teu sangue. (ver nota)

[[v28-33-32]]

^<<v28-33-32,32>>^ Se o tratares mal sem razão, fugir-te-á:

[[v28-33-33]]

^<<v28-33-33,33>>^ e se ele se afasta de ti e se retira, não saberás a quem perguntar, nem por que caminho o hás-de buscar.

'''

xref:028-eclesiastico/028-eclesiastico-032.adoc#v28-32-0[&#60; Capítulo Anterior] | <<v28-33-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-034.adoc#v28-34-0[Próximo Capítulo &#62;]