include::./index.adoc[]

[[v28-18-0]]
=== Eclesiástico, 18
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 18 do livro de Eclesiástico trata sobre a grandeza e a sabedoria de Deus, enfatizando a importância da obediência a Ele e da confiança em Seus caminhos. Além disso, o capítulo discute a justiça e a punição dos ímpios, bem como a bênção da paz e da harmonia entre os seres humanos. Abaixo estão cinco versículos relacionados aos temas abordados em Eclesiástico 18:
* Provérbios 1:7: "O temor do Senhor é o princípio da sabedoria; os insensatos desprezam a sabedoria e a disciplina." Este versículo fala sobre a importância do temor e do respeito a Deus como base para a sabedoria.
* Salmos 37:7: "Descanse no Senhor e aguarde por Ele com paciência; não se aborreça com o sucesso dos outros, nem com aqueles que maquinam o mal." Este versículo enfatiza a importância da confiança em Deus e da paciência, mesmo quando os ímpios prosperam.
* Isaías 48:18: "Ah, se tivesses prestado atenção aos meus mandamentos! Então, a tua paz seria como um rio, e a tua justiça como as ondas do mar." Este versículo destaca a conexão entre a obediência aos mandamentos de Deus e a paz e justiça que resultam disso.
* Provérbios 11:21: "Asseguração de que o ímpio não ficará impune, mas a descendência dos justos será salva." Este versículo destaca a justiça divina e a punição dos ímpios.
* Salmos 34:14: "Afaste-se do mal e faça o bem; busque a paz com perseverança." Este versículo enfatiza a importância de buscar a paz e evitar o mal através da perseverança.
****

[[v28-18-1]]

^<<v28-18-1,1>>^ Aquele que vive eternamente, criou todas as coisas, sem excepção. Só o Senhor será reconhecido justo. Ele é o rei invencível que subsiste para sempre.

[[v28-18-2]]

^<<v28-18-2,2>>^ Quem é capaz de contar as suas obras?

[[v28-18-3]]

^<<v28-18-3,3>>^ Quem poderá penetrar as suas maravilhas?

[[v28-18-4]]

^<<v28-18-4,4>>^ Quem poderá descrever o poder (soberano) da sua grandeza? Quem empreenderá enumerar as suas misericórdias?

[[v28-18-5]]

^<<v28-18-5,5>>^ Nada se pode diminuir ou acrescentar, nem é possível compreender as maravilhas de Deus.

[[v28-18-6]]

^<<v28-18-6,6>>^ Quando o homem tiver acabado, então estará no começo, e, quando cessar (a pesquisa), ficará perplexo. (ver nota)

[[v28-18-7]]

^<<v28-18-7,7>>^ Que é o homem, e para que presta? E que bem ou que mal pode ele fazer? (ver nota)

[[v28-18-8]]

^<<v28-18-8,8>>^ A duração dos dias do homem, quando muito, é de cem anos, mas, qual gota de água do mar, ou grão de areia, assim são estes poucos anos comparados com o dia da eternidade.

[[v28-18-9]]

^<<v28-18-9,9>>^ Por isso é que o Senhor é paciente com os homens, e derrama sobre eles a sua misericórdia.

[[v28-18-10]]

^<<v28-18-10,10>>^ Ele vê que a presunção do seu coração é má, e reconhece que o seu fim é deplorável.

[[v28-18-11]]

^<<v28-18-11,11>>^ Por isso é que os trata com a plenitude da sua doçura, e mostra-lhes o caminho da equidade.

[[v28-18-12]]

^<<v28-18-12,12>>^ A misericórdia do homem tem por objecto o seu próximo, porém a misericórdia de Deus estende-se a todo o ser vivo.

[[v28-18-13]]

^<<v28-18-13,13>>^ Cheio de compaixão, ensina e disciplina (os homens), como um pastor faz ao seu rebanho.

[[v28-18-14]]

^<<v28-18-14,14>>^ Compadece-se daquele que recebe a doutrina da sua misericórdia, e do que se apressa a cumprir os seus mandamentos.

[[v28-18-15]]

^<<v28-18-15,15>>^ Filho, não mistures a repreensão com o benefício, nem juntes às tuas dádivas a tristeza duma palavra má. (ver nota)

[[v28-18-16]]

^<<v28-18-16,16>>^ Porventura o orvalho não mitiga o calor ardente? Assim vale mais a palavra (doce) do que a dádiva.

[[v28-18-17]]

^<<v28-18-17,17>>^ Porventura a palavra (doce) não vale mais que o próprio dom? Mas uma e outra coisa se encontra no homem justo.

[[v28-18-18]]

^<<v28-18-18,18>>^ O insensato impropera àsperamente; o dom do invejoso consome os olhos.

[[v28-18-19]]

^<<v28-18-19,19>>^ Antes de Julgar (os outros) procura ser justo, e aprende, antes de falar.

[[v28-18-20]]

^<<v28-18-20,20>>^ Antes da enfermidade emprega cuidados (para a evitar), interroga-te a ti mesmo antes do juízo, e encontrarás misericórdia diante de Deus.

[[v28-18-21]]

^<<v28-18-21,21>>^ Humilha-te antes da doença, e mostra o teu proceder no tempo da enfermidade.

[[v28-18-22]]

^<<v28-18-22,22>>^ Nada te embarace de orar sempre, e não te envergonhes de praticar boas obras até à morte, porque a recompensa de Deus dura para sempre.

[[v28-18-23]]

^<<v28-18-23,23>>^ Prepara a tua alma antes da oração, e não sejas como um homem que tenta a Deus.

[[v28-18-24]]

^<<v28-18-24,24>>^ Lembra-te da ira do último dia, e do tempo em que Deus castigará, desviando o seu rosto.

[[v28-18-25]]

^<<v28-18-25,25>>^ Lembra-te da pobreza no tempo da abundância, e das necessidades da indigência no dia das riquezas.

[[v28-18-26]]

^<<v28-18-26,26>>^ Desde manhã até à tarde se muda o tempo, e tudo isto se faz num momento aos olhos de Deus.

[[v28-18-27]]

^<<v28-18-27,27>>^ o homem sábio andará com temor em tudo, e nos dias do pecado se guardará da preguiça, (ver nota)

[[v28-18-28]]

^<<v28-18-28,28>>^ Todo o homem hábil conhece a sabedoria, e dá louvor ao que a encontrou.

[[v28-18-29]]

^<<v28-18-29,29>>^ Os homens sensatos nas palavras, obram também com sabedoria, compreendem a verdade e a justiça, e espalham como chuva provérbios e sentenças.

[[v28-18-30]]

^<<v28-18-30,30>>^ Não te deixes ir atrás das tuas más tendências e refreia os teus apetites.

[[v28-18-31]]

^<<v28-18-31,31>>^ Se condescenderes com a tua alma no que deseja, ela fará de ti a alegria dos teus inimigos.

[[v28-18-32]]

^<<v28-18-32,32>>^ Não te comprazas em ir às assembleias, mesmo as mais pequenas, porque nelas comete-se incessantemente o mal.

[[v28-18-33]]

^<<v28-18-33,33>>^ Não te empobreças, pedindo dinheiro emprestado para rivalizares (com os outros em despesas), não tendo tu nada no bolso; isto equivaleria a seres inimigo da tua própria vida.

'''

xref:028-eclesiastico/028-eclesiastico-017.adoc#v28-17-0[&#60; Capítulo Anterior] | <<v28-18-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-019.adoc#v28-19-0[Próximo Capítulo &#62;]