include::./index.adoc[]

[[v28-46-0]]
=== Eclesiástico, 46
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Eclesiástico 46 apresenta uma lista de líderes e heróis bíblicos que foram abençoados por Deus e honrados pelo povo de Israel. Entre eles, destaca-se a figura do rei Davi, que é elogiado por sua coragem, sabedoria e piedade. Os versículos a seguir estão relacionados com os temas abordados neste capítulo:
* 1 Samuel 16:13: "Então Samuel tomou o chifre do azeite, e o ungiu no meio de seus irmãos; e desde aquele dia em diante o Espírito do Senhor se apoderou de Davi; então Samuel se levantou, e voltou para Ramá." Este versículo se refere à unção de Davi como rei de Israel por Samuel, mostrando como ele foi escolhido por Deus para liderar o povo.
* 1 Samuel 17:45: "Então disse Davi ao filisteu: Tu vens a mim com espada, e com lança, e com escudo; porém eu venho a ti em nome do Senhor dos Exércitos, o Deus dos exércitos de Israel, a quem tens afrontado." Este versículo descreve a coragem de Davi ao enfrentar Golias, mostrando como ele confiava em Deus para ajudá-lo a vencer seus inimigos.
* 1 Reis 2:10-11: "E Davi dormiu com seus pais, e foi sepultado na cidade de Davi. E reinou em seu lugar Salomão, seu filho, o qual estabeleceu o trono do reino do Senhor sobre Israel." Este versículo se refere à morte de Davi e sua sucessão por seu filho Salomão, mostrando como Davi deixou um legado duradouro como um grande rei de Israel.
* Salmos 51:10: "Cria em mim, ó Deus, um coração puro, e renova em mim um espírito reto." Este versículo faz referência ao Salmo 51, que é tradicionalmente atribuído a Davi e descreve sua oração de arrependimento após seu pecado com Bate-Seba. Ele mostra a humildade de Davi e seu desejo de ter um coração puro diante de Deus.
* Hebreus 11:32: "E que mais direi? Porque o tempo me faltaria contando de Gideão, e de Baraque, e de Sansão, e de Jefté, e de Davi, e de Samuel e dos profetas." Este versículo faz parte da "Galeria da Fé" em Hebreus 11, que destaca figuras notáveis do Antigo Testamento que viveram pela fé. Davi é incluído nesta lista, mostrando como ele foi reconhecido como um grande herói da fé.
****

[[v28-46-1]]

^<<v28-46-1,1>>^ Josué, filho de Nun, valente na guerra, sucedeu a Moisés na missão de profeta; foi grande, grande como denota o seu nome,

[[v28-46-2]]

^<<v28-46-2,2>>^ muito grande salvador dos escolhidos de Deus, para derrotar os inimigos que contra ele se levantavam, a fim de conseguir para Israel a sua herança.

[[v28-46-3]]

^<<v28-46-3,3>>^ Que glória não alcançou ele em levantar as suas mãos, e em brandir a lança contra as cidades (dos Amorreus)!

[[v28-46-4]]

^<<v28-46-4,4>>^ Quem antes dele combateu assim? De facto, o mesmo Senhor lhe trouxe às mãos os seus inimigos.

[[v28-46-5]]

^<<v28-46-5,5>>^ Não é assim que, por impulso do seu zelo, o sol parou, e que um só dia se tornou tão longo como dois?

[[v28-46-6]]

^<<v28-46-6,6>>^ Ele invocou o Altíssimo Poderoso, quando atacava os inimigos por todas as partes, e o grande e santo Deus o ouviu, e fez cair saraiva de grande força.

[[v28-46-7]]

^<<v28-46-7,7>>^ Investiu impetuosamente contra as hostes Inimigas, e derrotou os contrários na descida (do vale),

[[v28-46-8]]

^<<v28-46-8,8>>^ para que as nações conhecessem o poder divino, (e aprendessem) que não é fácil pelejar contra Deus. Ele seguiu sempre o Todo-Poderoso,

[[v28-46-9]]

^<<v28-46-9,9>>^ e nos dias de Moisés fez uma acção de misericórdia, ele e Caleb, filho de Jefone, resolvendo fazer frente ao inimigo, impedindo o povo de pecar, e apaziguando a murmuração que a malícia tinha excitado. (ver nota)

[[v28-46-10]]

^<<v28-46-10,10>>^ Sendo escolhidos estes dois, foram livres de perigo, dentre o número de seiscentos mil homens de pé, para introduzir o povo na sua herança, na terra que mana leite e mel.

[[v28-46-11]]

^<<v28-46-11,11>>^ O Senhor deu fortaleza ao mesmo Caleb; o seu vigor durou até à velhice, para subir a um lugar elevado do país, que a sua descendência possuiu por herança,

[[v28-46-12]]

^<<v28-46-12,12>>^ para que todos os filhos de Israel vissem que é bom obedecer ao Deus santo.

[[v28-46-13]]

^<<v28-46-13,13>>^ Em seguida vieram os juízes, apontados cada um por seu nome, cujo coração não foi pervertido, e que não se apartaram do Senhor.

[[v28-46-14]]

^<<v28-46-14,14>>^ para que a sua memória seja abençoada, para que os seus ossos reverdeçam nos sepulcros,

[[v28-46-15]]

^<<v28-46-15,15>>^ e dure perpétuamente o seu nome, passando aos seus filhos com a glória desses santos varões.

[[v28-46-16]]

^<<v28-46-16,16>>^ Samuel, profeta do Senhor, amado do Senhor seu Deus, instituiu um governo novo, e ungiu príncipes na sua nação.

[[v28-46-17]]

^<<v28-46-17,17>>^ Julgou o povo segundo a lei do Senhor, e Deus olhou propiciamente para Jacob. Pela sua fidelidade manifestou-se como profeta,

[[v28-46-18]]

^<<v28-46-18,18>>^ foi reconhecido fiel nas suas palavras, porque viu o Deus de luz.

[[v28-46-19]]

^<<v28-46-19,19>>^ Invocou o Senhor omnipotente, quando os inimigos o cercavam de todos os lados, e ofereceu um cordeiro sem mancha.

[[v28-46-20]]

^<<v28-46-20,20>>^ O Senhor trovejou do céu, com um grande estrondo fez ouvir a sua voz,

[[v28-46-21]]

^<<v28-46-21,21>>^ e destroçou os príncipes de Tyro e todos os chefes dos Filisteus.

[[v28-46-22]]

^<<v28-46-22,22>>^ Antes do tempo do sono eterno, deu testemunho, na presença do Senhor e do seu Ungido, de que não tinha recebido, de pessoa alguma, dinheiro nem sequer umas sandálias, e ninguém o pôde acusar.

[[v28-46-23]]

^<<v28-46-23,23>>^ Depois disto, Samuel morreu e apareceu ao rei (Saul), predizendo-lhe o fim da sua vida; levantou a sua voz de debaixo da terra, profetizando, para destruir a impiedade do povo.

'''

xref:028-eclesiastico/028-eclesiastico-045.adoc#v28-45-0[&#60; Capítulo Anterior] | <<v28-46-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-047.adoc#v28-47-0[Próximo Capítulo &#62;]