include::./index.adoc[]

[[v28-35-0]]
=== Eclesiástico, 35
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 35 de Eclesiástico trata principalmente do tema da oração e da generosidade. O autor enfatiza que Deus está sempre ouvindo as nossas orações, mas que a generosidade e a justiça são igualmente importantes para alcançar o favor divino. Abaixo estão cinco versículos da Bíblia que se relacionam com esses temas e que podem ajudar a iluminar o significado do capítulo 35 de Eclesiástico:
* Tiago 5:16b: "A oração de um justo é poderosa e eficaz." Tiago enfatiza que a oração é uma ferramenta poderosa, mas que ela deve ser acompanhada de justiça e retidão.
* Provérbios 11:25: "A alma generosa prosperará e quem saciar os outros, também será saciado." Esse versículo destaca a conexão entre a generosidade e a recompensa divina.
* Salmos 51:17: "O sacrifício aceitável a Deus é um espírito quebrantado; um coração quebrantado e contrito, ó Deus, não desprezarás." Esse salmo ensina que Deus valoriza a humildade e a sinceridade do coração.
* Mateus 6:6: "Mas quando você orar, vá para seu quarto, feche a porta e ore a seu Pai, que está em secreto. Então seu Pai, que vê em secreto, o recompensará." Esse versículo destaca a importância da oração sincera e pessoal, feita em privacidade e sinceridade.
* Provérbios 22:9: "O generoso será abençoado, pois dá do seu pão aos pobres." Esse provérbio enfatiza a importância da generosidade e do cuidado com os mais necessitados, algo que é enfatizado no capítulo 35 de Eclesiástico.
****

[[v28-35-1]]

^<<v28-35-1,1>>^ Aquele que observa a lei (por isso mesmo, como que) multiplica as oferendas. (ver nota)

[[v28-35-2]]

^<<v28-35-2,2>>^ É um sacrifício salutar estar atento aos mandamentos, e apartar-se de toda a iniquidade.

[[v28-35-3]]

^<<v28-35-3,3>>^ É oferecer um sacrifício de propiciação pelas injustiças e orar pelos pecados, o afastarmo-nos da injustiça.

[[v28-35-4]]

^<<v28-35-4,4>>^ Aquele que oferece a flor da farinha dá graças a Deus; e o que exerce a misericórdia oferece um sacrifício.

[[v28-35-5]]

^<<v28-35-5,5>>^ É agradável ao Senhor o fugir da iniquidade; é uma deprecação pelos pecados o retirar-se da injustiça.

[[v28-35-6]]

^<<v28-35-6,6>>^ Não apareças com as mãos vazias diante do Senhor,

[[v28-35-7]]

^<<v28-35-7,7>>^ porque todas estas coisas se fazem por causa do mandamento de Deus.

[[v28-35-8]]

^<<v28-35-8,8>>^ A oblação do justo torna pingue o altar, e é um suave perfume diante do Altíssimo.

[[v28-35-9]]

^<<v28-35-9,9>>^ O sacrifício do justo é agradável (a Deus), o Senhor não se esquecerá dele.

[[v28-35-10]]

^<<v28-35-10,10>>^ De bom ânimo tributa glória a Deus, e não diminuas as primícias de tuas mãos.

[[v28-35-11]]

^<<v28-35-11,11>>^ Tudo o que dás, dá-o com semblante alegre, santifica os teus dízimos com regozijo.

[[v28-35-12]]

^<<v28-35-12,12>>^ Dá ao Altíssimo segundo o que ele te tem dado, oferece-lhe com ânimo generoso, segundo as tuas posses,

[[v28-35-13]]

^<<v28-35-13,13>>^ porque o Senhor é remunerador, recompensar-te-á tudo sete vezes mais.

[[v28-35-14]]

^<<v28-35-14,14>>^ Não lhe ofereças donativos perversos, porque os não receberá.

[[v28-35-15]]

^<<v28-35-15,15>>^ Não esperes nada dum sacrifício injusto, porque o Senhor é juiz, e não há para ele distinção de pessoas.

[[v28-35-16]]

^<<v28-35-16,16>>^ O Senhor não fará acepção de pessoas contra o pobre, e ouvirá a oração do oprimido.

[[v28-35-17]]

^<<v28-35-17,17>>^ Não desprezará os rogos do órfão, nem a viúva que lhe fala com os seus gemidos.

[[v28-35-18]]

^<<v28-35-18,18>>^ Não correm as lágrimas à viúva pelas suas faces, e não clama ela contra aquele que lhas faz derramar?

[[v28-35-19]]

^<<v28-35-19,19>>^ Efectivamente, elas das faces (da viúva) sobem até ao céu, e o Senhor, que a ouve, não gostará de a ver chorar.

[[v28-35-20]]

^<<v28-35-20,20>>^ Aquele que adora a Deus com alegria será bem acolhido, e a sua prece chegará até às nuvens.

[[v28-35-21]]

^<<v28-35-21,21>>^ A oração do que se humilha penetrará as nuvens; ele não se consolará, enquanto ela não chegar (até Deus), e não se retirará, enquanto o Altíssimo não puser nela os olhos.

[[v28-35-22]]

^<<v28-35-22,22>>^ O Senhor não diferirá por muito tempo, mas julgará os justos e lhes fará justiça: o Fortíssimo não usará mais de paciência (com os opressores), mas quebrar-lhes-á o dorso.

[[v28-35-23]]

^<<v28-35-23,23>>^ Vingar-se-á das nações, até desfazer a multidão dos soberbos e quebrar os ceptros dos iníquos;

[[v28-35-24]]

^<<v28-35-24,24>>^ até retribuir aos homens segundo as suas acções, segundo as obras e presunção de (qualquer descendente de) Adão;

[[v28-35-25]]

^<<v28-35-25,25>>^ até fazer justiça ao seu povo e alegrar os justos com a sua misericórdia.

[[v28-35-26]]

^<<v28-35-26,26>>^ A misericórdia de Deus, no tempo da tribulação, é agradável, como a nuvem que se desfaz em chuva no tempo da seca.

'''

xref:028-eclesiastico/028-eclesiastico-034.adoc#v28-34-0[&#60; Capítulo Anterior] | <<v28-35-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-036.adoc#v28-36-0[Próximo Capítulo &#62;]