include::./index.adoc[]

[[v28-36-0]]
=== Eclesiástico, 36
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 36 do livro de Eclesiástico começa com uma oração do autor pedindo a Deus que o ouça e o ajude em sua necessidade. Em seguida, ele fala sobre a importância da humildade e do perdão, dizendo que Deus se aproxima daqueles que são humildes e perdoadores. O capítulo termina com o autor pedindo a Deus que abençoe seu povo e que o proteja daqueles que o oprimem. A seguir estão cinco versículos relacionados aos temas abordados em Eclesiástico 36:
* Provérbios 15:33: "O temor do Senhor é a instrução da sabedoria; e a humildade precede a honra." Este versículo destaca a importância da humildade, que é um tema central em Eclesiástico 36.
* Colossenses 3:13: "Suportando-vos uns aos outros, e perdoando-vos uns aos outros, se alguém tiver queixa contra outro; assim como Cristo vos perdoou, assim fazei vós também." Esse versículo fala sobre a importância do perdão, outro tema destacado em Eclesiástico 36.
* Salmos 102:17: "Ele atentará para a oração do desamparado, e não desprezará a sua oração." Assim como o autor de Eclesiástico pede a Deus que ouça sua oração, este versículo destaca que Deus sempre ouve a oração dos desamparados.
* Salmos 68:5: "Pai dos órfãos e juiz das viúvas é Deus, no seu lugar santo." Este versículo destaca a preocupação de Deus com aqueles que são oprimidos, um tema abordado pelo autor de Eclesiástico 36.
* 1 Pedro 5:7: "Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós." Este versículo destaca a confiança que o autor de Eclesiástico deposita em Deus e o pedido para que Deus cuide de seu povo.
****

[[v28-36-1]]

^<<v28-36-1,1>>^ Tem piedade de nós, ó Deus de todas as coisas, volta para nós os teus olhos e mostra-nos a luz das tuas misericórdias;

[[v28-36-2]]

^<<v28-36-2,2>>^ espalha o teu temor sobre as nações, que te não buscaram, para que elas reconheçam que não há outro Deus senão tu, e publiquem as tuas maravilhas,

[[v28-36-3]]

^<<v28-36-3,3>>^ Levanta a tua mão contra as nações estranhas, para que reconheçam o teu poder.

[[v28-36-4]]

^<<v28-36-4,4>>^ Assim como diante dos seus olhos mostraste em nós a tua santidade, assim também, à nossa vista, mostra nelas a tua grandeza, (ver nota)

[[v28-36-5]]

^<<v28-36-5,5>>^ para que reconheçam, como também nós reconhecemos, que fora de ti, Senhor, não há outro Deus.

[[v28-36-6]]

^<<v28-36-6,6>>^ Renova os teus prodígios, faze novas maravilhas,

[[v28-36-7]]

^<<v28-36-7,7>>^ glorifica a tua mão e o teu braço direito.

[[v28-36-8]]

^<<v28-36-8,8>>^ Excita o teu furor e derrama a tua ira.

[[v28-36-9]]

^<<v28-36-9,9>>^ Destrói o adversário e aflige o inimigo.

[[v28-36-10]]

^<<v28-36-10,10>>^ Apressa o tempo, lembra-te do fim, para que publiquem as tuas maravilhas.

[[v28-36-11]]

^<<v28-36-11,11>>^ Na voracidade das chamas consumido seja o que escapar, e os que tiranizam o teu povo caiam na perdição.

[[v28-36-12]]

^<<v28-36-12,12>>^ Esmaga a cabeça aos chefes dos inimigos, que dizem: Não há outro (Senhor) fora de nós.

[[v28-36-13]]

^<<v28-36-13,13>>^ Ajunta todas as tribos de Jacob, para que conheçam que não há outro Deus senão tu, para que publiquem as tuas grandezas, e sejam herança tua como o foram desde o principio.

[[v28-36-14]]

^<<v28-36-14,14>>^ Tem misericórdia do teu povo, que foi chamado do teu nome, e de Israel, a quem tu tens tratado como teu primogênito.

[[v28-36-15]]

^<<v28-36-15,15>>^ Tem piedade da cidade que santificaste, de Jerusalém, cidade do teu repouso.

[[v28-36-16]]

^<<v28-36-16,16>>^ Enche Sião das tuas palavras inefáveis, e o teu povo da tua glória.

[[v28-36-17]]

^<<v28-36-17,17>>^ Dá testemunho em favor daqueles que, desde o princípio, são tuas criaturas, e suscita (o cumprimento dos) oráculos que em teu nome proferiram os primeiros profetas.

[[v28-36-18]]

^<<v28-36-18,18>>^ Dá a recompensa aos que pacientemente esperam em ti, para que os teus profetas sejam achados fiéis; ouve as orações dos teus servos,

[[v28-36-19]]

^<<v28-36-19,19>>^ segundo a bênção de Aarão ao teu povo, e encaminha-nos pela estrada da justiça, a fim de que todos os que habitam a terra saibam que tu és o Deus que contempla os séculos.

[[v28-36-20]]

^<<v28-36-20,20>>^ O estômago recebe toda a casta de alimentos, mas entre os alimentos um é melhor que outro.

[[v28-36-21]]

^<<v28-36-21,21>>^ O paladar discerne pelo gosto o prato de caça, e o coração sensato as palavras mentirosas.

[[v28-36-22]]

^<<v28-36-22,22>>^ O coração depravado causa tristeza, mas o homem hábil resistir-lhe-á.

[[v28-36-23]]

^<<v28-36-23,23>>^ A mulher pode tomar por esposo a qualquer homem, mas entre as filhas uma é melhor que outra.

[[v28-36-24]]

^<<v28-36-24,24>>^ A formosura da mulher alegra o rosto do seu marido, e ultrapassa todos os desejos do homem.

[[v28-36-25]]

^<<v28-36-25,25>>^ Se a sua língua sabe curar, possui também a doçura e a bondade: o seu marido não será (infeliz ou pouco feliz) como os (outros) filhos dos homens.

[[v28-36-26]]

^<<v28-36-26,26>>^ O que possui uma mulher boa começa a formar a sua fortuna; tem um auxílio, que lhe é semelhante, e uma coluna de apoio.

[[v28-36-27]]

^<<v28-36-27,27>>^ Onde não há sebe, será roubada a fazenda; onde não há mulher, o homem suspira na indigência. (ver nota)

[[v28-36-28]]

^<<v28-36-28,28>>^ Quem é que se fia daquele que não tem ninho, que passa a noite onde quer que ela o surpreende, como salteador pronto para tudo, que vagueia de cidade em cidade?

'''

xref:028-eclesiastico/028-eclesiastico-035.adoc#v28-35-0[&#60; Capítulo Anterior] | <<v28-36-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-037.adoc#v28-37-0[Próximo Capítulo &#62;]