include::./index.adoc[]

[[v28-6-0]]
=== Eclesiástico, 6
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Eclesiástico 6 fala sobre a importância de se ter amigos verdadeiros e da sabedoria em escolher bem as amizades. Também enfatiza a necessidade de ser humilde e aprender com os mais sábios. Abaixo seguem cinco versículos relacionados com esses temas:
* Provérbios 17:17: "Em todo tempo ama o amigo e na angústia se faz o irmão" Este versículo destaca a importância da amizade verdadeira, que se mantém presente em todos os momentos, inclusive nos mais difíceis.
* Provérbios 27:17: "Como o ferro com o ferro se aguça, assim o homem afia o rosto do seu amigo" Esse versículo ressalta a importância da amizade na busca pela sabedoria e crescimento pessoal. Amigos verdadeiros nos ajudam a nos aprimorar e a sermos melhores.
* Eclesiástico 6:14: "Um amigo fiel é uma poderosa proteção: quem o achou, descobriu um tesouro." Esse verso destaca o valor inestimável de ter amigos verdadeiros e leais, que são uma fonte de apoio e proteção em nossas vidas.
* Provérbios 22:24-25: "Não te associes com o homem iracundo nem andes com o colérico, para que não aprendas as suas veredas e tomes um laço para a tua alma." Esse versículo alerta sobre a importância de escolher bem nossas amizades, evitando pessoas que podem nos influenciar negativamente.
* Eclesiástico 6:36: "Se quiseres adquirir sabedoria, ama a justiça e o Senhor te dará uma sábia compreensão." Esse verso destaca a importância da humildade em nossa busca pela sabedoria. Para aprender e crescer, precisamos ser humildes e buscar a justiça e a verdade.
****

[[v28-6-1]]

^<<v28-6-1,1>>^ De amigo não te tornes inimigo do teu próximo, porque o mau terá por sorte a vergonha e a ignomínia, como todo o pecador invejoso e de língua dobre.

[[v28-6-2]]

^<<v28-6-2,2>>^ Não te eleves como um touro no pensamento do teu coração, para não suceder que a tua loucura quebre a tua força,

[[v28-6-3]]

^<<v28-6-3,3>>^ consuma as tuas folhas e perca os teus frutos, e tu venhas a ficar como uma árvore seca no deserto.

[[v28-6-4]]

^<<v28-6-4,4>>^ A alma maligna perderá aquele que a tem, torná-lo-á a alegria dos seus inimigos. e conduzi-lo-á à sorte dos ímpios.

[[v28-6-5]]

^<<v28-6-5,5>>^ A palavra doce multiplica os amigos e amansa os inimigos; a linguagem amável abunda no homem bom.

[[v28-6-6]]

^<<v28-6-6,6>>^ Dá-te bem com muitos, mas seja teu conselheiro um entre mil.

[[v28-6-7]]

^<<v28-6-7,7>>^ Se queres ter um amigo, toma-o depois de o teres provado, e não te fies facilmente nele.

[[v28-6-8]]

^<<v28-6-8,8>>^ Com efeito, há tal amigo que somente o é quando nisso acha a sua conveniência, e que deixará de o ser no dia da tribulação.

[[v28-6-9]]

^<<v28-6-9,9>>^ E há amigo que se muda em inimigo; e há amigo que porá a descoberto ódios, disputas e rixas;

[[v28-6-10]]

^<<v28-6-10,10>>^ e há amigo que só o é para a mesa, e que o não será no dia da necessidade.

[[v28-6-11]]

^<<v28-6-11,11>>^ Se o teu amigo perseverar firme, será para ti como um igual, tratará à vontade com os da tua casa.

[[v28-6-12]]

^<<v28-6-12,12>>^ Se ele se humilhar diante de ti e se apagar na tua presença, terás uma amizade excelente na união dos corações. (ver nota)

[[v28-6-13]]

^<<v28-6-13,13>>^ Separa-te dos teus inimigos, e está alerta com os teus amigos.

[[v28-6-14]]

^<<v28-6-14,14>>^ O amigo fiel é uma forte protecção; quem o encontrou, encontrou um tesouro.

[[v28-6-15]]

^<<v28-6-15,15>>^ Nada se pode comparar com um amigo fiel, e o ouro e a prata não merecem ser postos em balança com a sinceridade da sua fé.

[[v28-6-16]]

^<<v28-6-16,16>>^ O amigo fiel é uma medicina de vida e de imortalidade; os que temem o Senhor acharão um tal amigo.

[[v28-6-17]]

^<<v28-6-17,17>>^ O que teme a Deus será, por isso mesmo, feliz na amizade, porque o seu amigo será semelhante a ele.

[[v28-6-18]]

^<<v28-6-18,18>>^ Filho, desde a tua mocidade recebe a Instrução, e adquirirás uma sabedoria que te dure até à velhice,

[[v28-6-19]]

^<<v28-6-19,19>>^ Aproxima-te da sabedoria, como o que lavra e semeia, e espera os seus bons frutos.

[[v28-6-20]]

^<<v28-6-20,20>>^ Trabalharás (apenas) um pouco na sua cultura, e depressa comerás dos seus frutos.

[[v28-6-21]]

^<<v28-6-21,21>>^ Quão excessivamente áspera é a sabedoria para os néscios! Não permanecerá junto dela o insensato.

[[v28-6-22]]

^<<v28-6-22,22>>^ Será para eles como uma pedra pesada que serve para provar, e não tardarão em se descarregarem dela. (ver nota)

[[v28-6-23]]

^<<v28-6-23,23>>^ Porque a sabedoria que instrui é como o seu nome, não se manifesta a muitos (à maioria das pessoas); mas naqueles que a conhecem, permanece até (os levar) à presença de Deus.

[[v28-6-24]]

^<<v28-6-24,24>>^ Ouve, filho, recebe uma sábia advertência, não rejeites o meu conselho.

[[v28-6-25]]

^<<v28-6-25,25>>^ Mete os teus pés nos seus grilhões, e o teu pescoço nas suas cadelas. (ver nota)

[[v28-6-26]]

^<<v28-6-26,26>>^ Baixa o teu ombro, leva-a às costas, e não te aborreças com as suas prisões.

[[v28-6-27]]

^<<v28-6-27,27>>^ Aproxima-te dela de todo o teu coração, guarda os seus caminhos com todas as tuas forças.

[[v28-6-28]]

^<<v28-6-28,28>>^ Segue os seus vestígios, e ela se te manifestará; quando já a possuíres, não a deixes,

[[v28-6-29]]

^<<v28-6-29,29>>^ porque nela encontrarás, no fim, o teu descanso,e ela se converterá para ti em gosto.

[[v28-6-30]]

^<<v28-6-30,30>>^ Os seus grilhões serão para ti uma forte protecção e um firme apoio, as suas cadeias um vestido de glória:

[[v28-6-31]]

^<<v28-6-31,31>>^ nela está realmente uma beleza que dá a vida, e os seus vínculos são ligaduras que saram.

[[v28-6-32]]

^<<v28-6-32,32>>^ Tu te revestirás dela como duma veste de glória, e a porás sobre ti como uma coroa de regozijo.

[[v28-6-33]]

^<<v28-6-33,33>>^ Filho, se me deres atenção, aprenderás, e, se aplicares o teu espírito, serás sábio.

[[v28-6-34]]

^<<v28-6-34,34>>^ Se me ouvires, receberás a instrução, e se fores amigo de ouvir, serás sábio.

[[v28-6-35]]

^<<v28-6-35,35>>^ Frequenta a reunião dos velhos prudentes, une-te de coração à sua sabedoria; a fim de poderes ouvir tudo o que te disserem de Deus, e de não te escaparem as suas louváveis sentenças.

[[v28-6-36]]

^<<v28-6-36,36>>^ Se vires um homem sensato, madruga para ir ter com ele, e gastem os teus pés os degraus da sua porta.

[[v28-6-37]]

^<<v28-6-37,37>>^ Fixa a tua atenção nos preceitos de Deus medita continuamente os seus mandamentos, que ele mesmo te dará um coração (firme no bem), e ser-te-á dada a desejada sabedoria.

'''

xref:028-eclesiastico/028-eclesiastico-005.adoc#v28-5-0[&#60; Capítulo Anterior] | <<v28-6-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-007.adoc#v28-7-0[Próximo Capítulo &#62;]