include::./index.adoc[]

[[v28-38-0]]
=== Eclesiástico, 38
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Eclesiástico 38 é um capítulo que fala sobre a importância da medicina e dos médicos, e sobre a necessidade de cuidarmos bem da nossa saúde. Abaixo estão cinco versículos relacionados com os temas abordados nesse capítulo:
* Provérbios 17:22: "O coração alegre é bom remédio, mas o espírito abatido faz secar os ossos." Esse versículo mostra que a felicidade e o bem-estar emocional podem contribuir para a saúde física.
* Provérbios 4:20-22: "Filho meu, atenta para as minhas palavras, inclina o teu ouvido às minhas instruções. Não as deixes apartar-se dos teus olhos; guarda-as no íntimo do teu coração. Porque são vida para os que as acham e saúde para o seu corpo." Esse versículo mostra que a sabedoria pode trazer vida e saúde ao nosso corpo.
* Isaías 38:21: "Então tomaram um pedaço de figo e o colocaram sobre a úlcera; e ele sarou." Esse versículo mostra a importância das terapias naturais e dos remédios caseiros para a cura de doenças.
* Mateus 9:12: "Mas Jesus, ouvindo, disse-lhes: Não necessitam de médico os sãos, mas sim os doentes." Esse versículo mostra que Jesus reconhecia a importância dos médicos e dos tratamentos médicos.
* Lucas 5:31: "E Jesus, respondendo, disse-lhes: Não necessitam de médico os que estão sãos, mas sim os que estão enfermos." Esse versículo é semelhante ao anterior e também mostra a importância dos médicos e dos tratamentos médicos.
****

[[v28-38-1]]

^<<v28-38-1,1>>^ Honra o médico, por causa da necessidade; com efeito, foi o Altíssimo que o criou.

[[v28-38-2]]

^<<v28-38-2,2>>^ Toda a medicina vem de Deus. e (o médico) receberá donativos do rei.

[[v28-38-3]]

^<<v28-38-3,3>>^ A ciência do médico exaltará a sua cabeça, e ele será louvado na presença dos grandes.

[[v28-38-4]]

^<<v28-38-4,4>>^ O Altíssimo produziu da terra os medicamentos; o homem prudente não os aborrecerá.

[[v28-38-5]]

^<<v28-38-5,5>>^ Porventura não foi por meio dum lenho que se tornou doce a água amargosa?

[[v28-38-6]]

^<<v28-38-6,6>>^ Ao conhecimento dos homens chegou a virtude dos medicamentos. O Altíssimo deu aos homens a ciência para ser por eles honrado nas suas maravilhas.

[[v28-38-7]]

^<<v28-38-7,7>>^ Com eles cura e mitiga a dor; o farmacêutico faz compostos agradáveis, compõe unguentos salutares, de forma que as criaturas de Deus não pereçam.

[[v28-38-8]]

^<<v28-38-8,8>>^ (Pela sua acção) a paz de Deus estende-se sobre a face da terra.

[[v28-38-9]]

^<<v28-38-9,9>>^ Filho, não te descuides na tua enfermidade, mas faze oração ao Senhor, e ele te curará. (ver nota)

[[v28-38-10]]

^<<v28-38-10,10>>^ Aparta-te do pecado, endireita as tuas mãos, purifica o teu coração de todo o delito.

[[v28-38-11]]

^<<v28-38-11,11>>^ Oferece um (incenso de) cheiro suave, uma lembrança de flor de farinha imola vitimas pingues; (depois disto) dá lugar ao médico,

[[v28-38-12]]

^<<v28-38-12,12>>^ pois para isso é que o Senhor o estabeleceu. E não se aparte de ti, porque te é necessária a sua assistência.

[[v28-38-13]]

^<<v28-38-13,13>>^ Virá tempo em que cairás nas mãos deles,

[[v28-38-14]]

^<<v28-38-14,14>>^ e eles mesmos rogarão ao Senhor que envie por meio deles o alívio e a saúde, em atenção à sua vida recta.

[[v28-38-15]]

^<<v28-38-15,15>>^ Aquele que peca na presença de quem o criou, virá a cair nas mãos do médico.

[[v28-38-16]]

^<<v28-38-16,16>>^ Filho, derrama lágrimas sobre o morto, põe-te a chorar como quem recebeu um rude golpe: enterra o seu corpo segundo o costume, e não desprezes a sua sepultura.

[[v28-38-17]]

^<<v28-38-17,17>>^ Chora-o amargamente durante um dia, para evitar a maledicência, e depois consola-te da tua tristeza;

[[v28-38-18]]

^<<v28-38-18,18>>^ Toma este nojo segundo o merecimento da pessoa, um dia ou dois, para não dares lugar à detracção.

[[v28-38-19]]

^<<v28-38-19,19>>^ Porque a tristeza faz apressar a morte, tira o vigor, e a melancolia do coração faz descair a cabeça.

[[v28-38-20]]

^<<v28-38-20,20>>^ A tristeza conserva-se na solidão; e a vida do pobre é como o seu coração.

[[v28-38-21]]

^<<v28-38-21,21>>^ Não entregues o teu coração à tristeza, mas lança-a fora de ti; lembra-te do teu fim.

[[v28-38-22]]

^<<v28-38-22,22>>^ Não te esqueças dele, porque não há retorno; em nada aproveitarás ao morto, e a ti mesmo farás um grave dano.

[[v28-38-23]]

^<<v28-38-23,23>>^ Lembra-te da minha sorte (te dirá o morto): a tua será semelhante; ontem para mim, hoje para ti.

[[v28-38-24]]

^<<v28-38-24,24>>^ No repouso do morto deixa descansar a sua memória; e consola-o ao exalar o último suspiro.

[[v28-38-25]]

^<<v28-38-25,25>>^ O letrado adquire sabedoria no tempo do ócio, e o que tem poucas ocupações alcançará a sabedoria. De que sabedoria será cheio

[[v28-38-26]]

^<<v28-38-26,26>>^ o que pega no arado, que faz timbre de saber picar os bois com o aguilhão, que se ocupa constantemente com os trabalhos deles, e cuja conversação é somente sobre novilhos de touros?

[[v28-38-27]]

^<<v28-38-27,27>>^ Ele aplicará o seu coração em tirar (bem) os sulcos, e os seus desvelos em engordar as bezerras.

[[v28-38-28]]

^<<v28-38-28,28>>^ Assim sucede com todo o carpinteiro e arquitecto, que passa trabalhando a noite e o dia; com o que grava as figuras dos sinetes, e que todo se cansa em as variar, que aplica o seu coração em reproduzir o debuxo, e, à força de vigílias, completa a obra.

[[v28-38-29]]

^<<v28-38-29,29>>^ Assim sucede com o ferreiro, assentado ao pé da bigorna, atento ao ferro que está trabalhando; o vapor do fogo cresta as suas carnes, e ele aguenta-se contra o calor da frágua.

[[v28-38-30]]

^<<v28-38-30,30>>^ O estrondo do martelo fere-lhe sem cessar os ouvidos, e os seus olhos estão fixos no modelo da sua obra.

[[v28-38-31]]

^<<v28-38-31,31>>^ Aplica o coração a completar os seus trabalhos, com o seu desvelo os aformoseia, dando-lhes a última demão.

[[v28-38-32]]

^<<v28-38-32,32>>^ Assim sucede com o oleiro que, assentado a realizar a sua tarefa, dá voltas à roda com os pés, sempre cuidadoso pela sua obra, levando por conta tudo o que faz.

[[v28-38-33]]

^<<v28-38-33,33>>^ Com seu braço dá forma ao barro, e com os seus pés torna-o flexível.

[[v28-38-34]]

^<<v28-38-34,34>>^ Ele aplica o seu coração a vidrar a obra perfeitamente, e a sua diligência em limpar o forno.

[[v28-38-35]]

^<<v28-38-35,35>>^ Todos estes têm confiança na indústria das suas mãos, e cada um é sabido na sua arte.

[[v28-38-36]]

^<<v28-38-36,36>>^ Sem eles não se edificaria uma cidade.

[[v28-38-37]]

^<<v28-38-37,37>>^ não se habitaria nela, nem se passearia. Porém esses mesmos não entrarão nas assembleias.

[[v28-38-38]]

^<<v28-38-38,38>>^ não se assentarão nas cadeiras dos juízes, não entenderão as leis da justiça, não ensinarão as regras da moral nem do direito, e não se acharão ocupados nas parábolas.

[[v28-38-39]]

^<<v28-38-39,39>>^ Entretanto sustentam as coisas temporais, e os seus votos são para fazerem bem as obras da sua arte.

'''

xref:028-eclesiastico/028-eclesiastico-037.adoc#v28-37-0[&#60; Capítulo Anterior] | <<v28-38-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-039.adoc#v28-39-0[Próximo Capítulo &#62;]