include::./index.adoc[]

[[v28-24-0]]
=== Eclesiástico, 24
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Eclesiástico 24 apresenta a Sabedoria falando sobre si mesma e sua origem divina. Ela se apresenta como tendo sido criada antes de todas as coisas e descreve sua presença em diversas figuras bíblicas importantes. Além disso, a Sabedoria faz um convite para que todos a busquem e sigam seus ensinamentos. Seguem abaixo cinco versículos relacionados com os temas abordados em Eclesiástico 24:
* Provérbios 3:13-15: "Feliz é o homem que acha sabedoria, e o homem que adquire entendimento, porque o lucro dela é melhor que o lucro da prata, e o seu ganho mais do que o ouro mais fino. Mais preciosa é do que as jóias, e tudo o que podes desejar não se pode comparar a ela." Este versículo destaca a importância da sabedoria e o seu valor incomparável.
* Jó 28:28: "E disse ao homem: Eis que o temor do Senhor é a sabedoria, e o apartar-se do mal é o entendimento." Esse versículo destaca a conexão entre a sabedoria e o temor do Senhor.
* Provérbios 8:17: "Eu amo aqueles que me amam, e os que me procuram diligentemente me encontrarão." Este versículo é semelhante ao convite feito pela Sabedoria em Eclesiástico 24, onde ela convida as pessoas a buscá-la.
* Colossenses 2:3: "em quem estão escondidos todos os tesouros da sabedoria e da ciência." Esse versículo fala sobre como em Cristo está oculta toda a sabedoria e conhecimento.
* Tiago 1:5: "Se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente, e não o censura, e ser-lhe-á dada." Este versículo destaca a fonte da sabedoria e o fato de que Deus está disposto a concedê-la a todos que pedem com fé.
****

[[v28-24-1]]

^<<v28-24-1,1>>^ A sabedoria faz o seu próprio elogio, honra-se em Deus, gloria-se no meio do seu povo;

[[v28-24-2]]

^<<v28-24-2,2>>^ abre a sua boca na Assembleia do Altíssimo, glorifica-se diante dos seus exércitos, (ver nota)

[[v28-24-3]]

^<<v28-24-3,3>>^ é exaltada no meio do seu povo, e admirada na assembleia santa.

[[v28-24-4]]

^<<v28-24-4,4>>^ Entre a multidão dos escolhidos, recebe louvores, e entre os abençoados recebe bênçãos.

[[v28-24-5]]

^<<v28-24-5,5>>^ Ela diz: Eu saí da boca do Altíssimo, primogénita antes de todas as criaturas.

[[v28-24-6]]

^<<v28-24-6,6>>^ Eu fiz com que nascesse nos céus uma luz indefectível, e como uma névoa cobri toda a terra.

[[v28-24-7]]

^<<v28-24-7,7>>^ Eu habitei nos lugares mais altos, e o meu trono é sobre uma coluna de nuvem.

[[v28-24-8]]

^<<v28-24-8,8>>^ Sozinha percorri a abóbada celeste, penetrei na profundidade do abismo, andei sobre as ondas do mar.

[[v28-24-9]]

^<<v28-24-9,9>>^ Caminhei por toda a terra. Imperei sobre todos os povos

[[v28-24-10]]

^<<v28-24-10,10>>^ e sobre todas as nações.

[[v28-24-11]]

^<<v28-24-11,11>>^ Tive debaixo dos meus pés, com o meu poder, os corações de todos os grandes e pequenos; entre todos busquei um lugar de repouso, e uma morada na herança do Senhor.

[[v28-24-12]]

^<<v28-24-12,12>>^ Então o Criador de tudo deu-me os seus preceitos, falou-me; aquele que me criou descansou no meu tabernáculo.

[[v28-24-13]]

^<<v28-24-13,13>>^ Disse-me: Habita em Jacob, possui a tua herança em Israel, e lança raízes entre os meus escolhidos.

[[v28-24-14]]

^<<v28-24-14,14>>^ Eu fui criada desde o princípio, antes dos séculos, e não deixarei de existir até ao fim dos séculos, e exerci diante dele o meu ministério na morada santa.

[[v28-24-15]]

^<<v28-24-15,15>>^ Assim me fixei em Sião, repousei na cidade santa, e em Jerusalém está o meu poder.

[[v28-24-16]]

^<<v28-24-16,16>>^ Deitei raízes no meio dum povo glorioso, cuja herança está na parte do meu Deus, e na assembleia dos santos estabeleci a minha morada.

[[v28-24-17]]

^<<v28-24-17,17>>^ Elevei-me como o cedro do Líbano, como o cipreste do monte Sião. (ver nota)

[[v28-24-18]]

^<<v28-24-18,18>>^ Cresci como a palmeira de Cades, como as roseiras de Jericó.

[[v28-24-19]]

^<<v28-24-19,19>>^ Elevei-me como uma formosa oliveira nos campos, como o plátano no caminho à beira das águas.

[[v28-24-20]]

^<<v28-24-20,20>>^ Difundi um perfume como o cinamomo e o bálsamo aromático, e como mirra escolhida exalei suave odor.

[[v28-24-21]]

^<<v28-24-21,21>>^ Perfumei a minha habitação como o estoraque, o gálbano, o onix e a mirra, e como a gota de incenso caída por si própria; a minha fragrância é como a dum bálsamo sem mistura.

[[v28-24-22]]

^<<v28-24-22,22>>^ Estendi os meus ramos como o terebinto; os meus ramos são ramos de honra e de graça.

[[v28-24-23]]

^<<v28-24-23,23>>^ Como a vide lancei flores dum agradável cheiro; e as minhas flores dão frutos de glória e de riqueza.

[[v28-24-24]]

^<<v28-24-24,24>>^ Eu sou a mãe do amor formoso, do temor, da ciência e da santa esperança.

[[v28-24-25]]

^<<v28-24-25,25>>^ Em mim há toda a graça do caminho e da verdade, em mim toda a esperança da vida e da virtude.

[[v28-24-26]]

^<<v28-24-26,26>>^ Vinde a mim todos os que me desejais, e enchei-vos dos meus frutos,

[[v28-24-27]]

^<<v28-24-27,27>>^ porque o meu espírito é mais doce do que o mel, e possuir-me é mais suave que o favo de mel.

[[v28-24-28]]

^<<v28-24-28,28>>^ A minha memória durará por toda a série dos séculos.

[[v28-24-29]]

^<<v28-24-29,29>>^ Aqueles que me comem terão ainda fome. e os que me bebem terão ainda sede. (ver nota)

[[v28-24-30]]

^<<v28-24-30,30>>^ Aquele que me ouve não será confundido, e os que agem por mim não pecarão.

[[v28-24-31]]

^<<v28-24-31,31>>^ Aqueles que me tornam conhecida terão a vida eterna.

[[v28-24-32]]

^<<v28-24-32,32>>^ Tudo isto é o livro da vida, a aliança do altíssimo e o conhecimento da verdade. (ver nota)

[[v28-24-33]]

^<<v28-24-33,33>>^ Moisés deu-nos a lei com os preceitos da justiça, a herança da casa de Jacob e as promessas feitas a Israel.

[[v28-24-34]]

^<<v28-24-34,34>>^ (O Senhor) prometeu a Davide, seu servo, que faria sair dele um rei fortíssimo, o qual se sentaria sobre um trono de glória para sempre.

[[v28-24-35]]

^<<v28-24-35,35>>^ É ela (a lei) que espalha ,a sabedoria como o Fison (as suas águas), e como o Tigre no tempo dos frutos novos.

[[v28-24-36]]

^<<v28-24-36,36>>^ É ela que faz transbordar a inteligência como o Eufrates, como o Jordão no tempo da ceifa.

[[v28-24-37]]

^<<v28-24-37,37>>^ É ela que derrama a ciência como o Nilo, e que aumenta as suas águas como o Geon no tempo da vindima.

[[v28-24-38]]

^<<v28-24-38,38>>^ Nem o primeiro (que a estudou) a acabou de conhecer, nem, igualmente, o último de a descobrir.

[[v28-24-39]]

^<<v28-24-39,39>>^ Os seus pensamentos são mais vastos do que o mar, e os seus conselhos mais profundos do que o grande abismo.

[[v28-24-40]]

^<<v28-24-40,40>>^ Eu, a Sabedoria, fiz correr os rios. (ver nota)

[[v28-24-41]]

^<<v28-24-41,41>>^ Eu sou como o caminho da água imensa derivada dum rio, como o canal duma ribeira, e como um aqueduto que sai do paraíso.

[[v28-24-42]]

^<<v28-24-42,42>>^ Eu disse: Regarei as plantas do meu jardim, saciarei de água os frutos do meu prado.

[[v28-24-43]]

^<<v28-24-43,43>>^ E eis que o meu curso de água se tornou um caudaloso rio, e o meu rio se tornou um mar.

[[v28-24-44]]

^<<v28-24-44,44>>^ Com efeito, a luz da doutrina, com que a todos ilustro, é como a luz da aurora; eu a manifestarei ao longe.

[[v28-24-45]]

^<<v28-24-45,45>>^ Penetrarei todas as partes inferiores da terra, lançarei os olhos por todos os que dormem, e iluminarei todos os que esperam no Senhor.

[[v28-24-46]]

^<<v28-24-46,46>>^ Continuarei a espalhar a minha doutrina como uma profecia, e deixá-la-ei aos que andam em busca da sabedoria, e não cessarei (de estar presente), de geração em geração, até ao século santo.

[[v28-24-47]]

^<<v28-24-47,47>>^ Vede que eu não trabalhei só para mim, mas para todos os que buscam a verdade.

'''

xref:028-eclesiastico/028-eclesiastico-023.adoc#v28-23-0[&#60; Capítulo Anterior] | <<v28-24-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-025.adoc#v28-25-0[Próximo Capítulo &#62;]