include::./index.adoc[]

[[v28-2-0]]
=== Eclesiástico, 2
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Eclesiástico 2 fala sobre a importância de perseverar na fé e na justiça, apesar das dificuldades e tentações que possam surgir ao longo da vida. O capítulo encoraja os fiéis a confiarem em Deus e a se manterem firmes em suas convicções, prometendo que aqueles que permanecem fiéis serão recompensados. Abaixo estão cinco versículos relacionados ao tema:
* Salmos 34:19: "Muitas são as aflições do justo, mas o SENHOR o livra de todas." Este verso fala sobre como os justos podem enfrentar dificuldades em suas vidas, mas Deus sempre os livrará de todas as aflições.
* Romanos 5:3-4: "E não somente isso, mas também nos gloriamos nas tribulações, sabendo que a tribulação produz perseverança; e a perseverança, experiência; e a experiência, esperança." Este verso destaca como as tribulações e dificuldades podem ajudar a fortalecer a fé e a perseverança dos cristãos.
* Tiago 1:2-4: "Meus irmãos, tende por motivo de toda alegria o passardes por várias provações, sabendo que a provação da vossa fé, uma vez confirmada, produz perseverança. Ora, a perseverança deve ter ação completa, para que sejais perfeitos e íntegros, em nada deficientes." Tiago exorta os cristãos a encararem suas provações como oportunidades para fortalecer a fé e a perseverança, levando à perfeição e integridade.
* 1 Pedro 1:7: "para que a prova da vossa fé, mais preciosa do que o ouro que perece e é provado pelo fogo, redunde para louvor, glória e honra na revelação de Jesus Cristo." Este verso destaca como as provações podem provar a fé dos cristãos e levá-los a serem recompensados com louvor, glória e honra.
* Gálatas 6:9: "E não nos cansemos de fazer o bem, porque a seu tempo ceifaremos, se não desfalecermos." Este verso encoraja os cristãos a continuarem a fazer o bem, mesmo quando enfrentam dificuldades e provações, lembrando-os de que serão recompensados no tempo certo.
****

[[v28-2-1]]

^<<v28-2-1,1>>^ Meu filho, se entrares no serviço de Deus, persevera firme na justiça e no temor, e prepara a tua alma para a prova.

[[v28-2-2]]

^<<v28-2-2,2>>^ Humilha o teu coração e tem paciência, inclina o teu ouvido e recebe as palavras da sabedoria, e não te precipites no tempo do infortúnio. (ver nota)

[[v28-2-3]]

^<<v28-2-3,3>>^ Sofre as demoras de Deus; conserva-te unido a Deus, espera pacientemente, para que no fim a tua vida cresça.

[[v28-2-4]]

^<<v28-2-4,4>>^ Aceita (de boamente) tudo o que te suceder, aguenta-te no sofrimento, no tempo da humilhação tem paciência,

[[v28-2-5]]

^<<v28-2-5,5>>^ porque no fogo se prova o ouro e a prata, e os homens amados (de Deus provam-se) no cadinho da humilhação.

[[v28-2-6]]

^<<v28-2-6,6>>^ Confia em Deus, e ele te salvará, dirige bem o teu caminho e espera nele; conserva o seu temor até à velhice.

[[v28-2-7]]

^<<v28-2-7,7>>^ Vós, os que temeis o Senhor, esperai a sua misericórdia e não vos desvieis dele, para não cairdes.

[[v28-2-8]]

^<<v28-2-8,8>>^ Vós, os que temeis o Senhor, tende fé nele, e não se perderá a vossa recompensa.

[[v28-2-9]]

^<<v28-2-9,9>>^ Vós, os que temeis o Senhor, esperai nele: para vossa consolação virá sobre vós a sua misericórdia.

[[v28-2-10]]

^<<v28-2-10,10>>^ Vós, os que temeis o Senhor, amai-o, e os vossos corações serão alumiados.

[[v28-2-11]]

^<<v28-2-11,11>>^ Considerai, filhos, as gerações humanas, e sabei que ninguém, que esperou no Senhor, foi confundido.

[[v28-2-12]]

^<<v28-2-12,12>>^ Quem permaneceu firme nos seus mandamentos, e foi desamparado? Ou quem o invocou, e foi dele desprezado?

[[v28-2-13]]

^<<v28-2-13,13>>^ Porque Deus é bom e misericordioso, e perdoará os pecados no dia da tribulação; ele é o protector de todos os que o buscam em verdade.

[[v28-2-14]]

^<<v28-2-14,14>>^ Ai do coração dobre, dos lábios criminosos, das mãos que fazem o mal, do pecador que anda sobre a terra por dois caminhos!

[[v28-2-15]]

^<<v28-2-15,15>>^ Ai dos fracos de coração, que não confiam em Deus. Coragem: e que, por isso, não serão protegidos por ele!

[[v28-2-16]]

^<<v28-2-16,16>>^ Ai dos que perderam a paciência, que deixaram os caminhos rectos e se extraviaram por veredas malignas!

[[v28-2-17]]

^<<v28-2-17,17>>^ Que farão eles, quando o Senhor começar a examinar (tudo)?

[[v28-2-18]]

^<<v28-2-18,18>>^ Os que temem o Senhor não são incrédulos à sua palavra, e os que o amam continuam no seu caminho.

[[v28-2-19]]

^<<v28-2-19,19>>^ Os que temem o Senhor procuram o que lhe é agradável, e os que o amam saciam-se da sua lei.

[[v28-2-20]]

^<<v28-2-20,20>>^ Os que temem o Senhor preparam os seus corações, e santificam as suas almas na sua presença. (ver nota)

[[v28-2-21]]

^<<v28-2-21,21>>^ Os que temem o Senhor, guardam os seus mandamentos, e têm paciência até que lance os olhos sobre eles, dizendo: Se não fizermos penitência, cairemos nas mãos do Senhor, e não nas mãos dos homens.

[[v28-2-22]]

^<<v28-2-22,22>>^ Porque, na medida em que é elevada a sua grandeza, assim o é a sua misericórdia.

'''

xref:028-eclesiastico/028-eclesiastico-001.adoc#v28-1-0[&#60; Capítulo Anterior] | <<v28-2-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-003.adoc#v28-3-0[Próximo Capítulo &#62;]