include::./index.adoc[]

[[v5-31-0]]
=== Deuteronômio, 31
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Deuteronômio 31 aborda a transição do comando de Moisés para Josué e a importância da obediência à lei de Deus. Moisés instrui o povo a seguir os mandamentos de Deus, lembrando-os de que a rebelião trará consequências graves. Abaixo estão cinco versículos relacionados com os temas abordados em Deuteronômio 31:
* Josué 1:7-8: "Tão-somente sê forte e mui corajoso para teres o cuidado de fazer conforme toda a lei que meu servo Moisés te ordenou; dela não te desvies, nem para a direita nem para a esquerda, para que sejas bem sucedido por onde quer que andares. Não se aparte da tua boca o livro desta lei, antes medita nele dia e noite, para que tenhas cuidado de fazer conforme tudo quanto nele está escrito; porque então farás prosperar o teu caminho, e serás bem sucedido." Josué é encarregado de liderar o povo, e Deus lhe ordena que seja forte e corajoso e obedeça à lei de Moisés para ter sucesso.
* Josué 23:6: "Sede, pois, mui esforçados para guardardes e para fazerdes tudo quanto está escrito no livro da lei de Moisés, não vos desviando dele nem para a direita nem para a esquerda." Josué lembra o povo da importância de obedecer à lei de Deus e não se desviar dela.
* Salmos 119:165: "Grande paz têm os que amam a tua lei, e para eles não há tropeço." A obediência à lei de Deus traz paz e evita o pecado.
* Provérbios 3:5-6: "Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento. Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas." Confiança em Deus e obediência à sua lei são importantes para a orientação na vida.
* Romanos 2:13: "Porque os simples ouvidores da lei não são justos diante de Deus, mas os que praticam a lei hão de ser justificados." A obediência à lei de Deus é importante para a justificação diante Dele.
****

[[v5-31-1]]

^<<v5-31-1,1>>^ Moisés dirigiu ainda estas palavras a todo o Israel.

[[v5-31-2]]

^<<v5-31-2,2>>^ Disse-lhes: Eu estou hoje com idade de cento e vinte anos, já não posso ir e vir, principalmente tendo-me dito o Senhor: Tu não passarás este Jordão.

[[v5-31-3]]

^<<v5-31-3,3>>^ O Senhor teu Deus passará, pois, diante de ti; ele mesmo exterminará diante de ti todas estas nações, tu as possuirás, Josué passará adiante de ti, como o Senhor disse.

[[v5-31-4]]

^<<v5-31-4,4>>^ O Senhor fará a estes povos, como fez a Seon e a Og, reis dos Amorreus, e ao seu país, destruindo-os.

[[v5-31-5]]

^<<v5-31-5,5>>^ Quando ele, pois, tiver também entregado estes, vós lhes fareis como vos ordenei.

[[v5-31-6]]

^<<v5-31-6,6>>^ Procedei varonilmente, tende coragem; não temais nem tremais, à vista deles, porque o Senhor vosso Deus é ele mesmo o guia, que não vos deixará, nem desamparará.

[[v5-31-7]]

^<<v5-31-7,7>>^ Moisés chamou Josué e disse-lhe diante de todo o Israel: Tem ânimo, sê forte, porque tu hás-de introduzir este povo na terra que o Senhor jurou a seus pais que lhes havia de dar, e tu a repartirás por sorte.

[[v5-31-8]]

^<<v5-31-8,8>>^ O Senhor, que é o vosso guia, ele mesmo será contigo; não te deixará, nem te desamparará: não temas, nem te assustes.

[[v5-31-9]]

^<<v5-31-9,9>>^ Escreveu Moisés esta lei, e a entregou aos sacerdotes filhos de Levi, que levavam a arca da aliança do Senhor, e a todos os Anciães de Israel.

[[v5-31-10]]

^<<v5-31-10,10>>^ Deu-lhes esta ordem: Todos os sete anos, no ano da remissão, na solenidade dos Tabernáculos,

[[v5-31-11]]

^<<v5-31-11,11>>^ quando todos os filhos de Israel se juntarem para aparecer diante do Senhor teu Deus, no lugar que o Senhor tiver escolhido, lerás as palavras desta lei diante de todo o Israel, de maneira que ouça.

[[v5-31-12]]

^<<v5-31-12,12>>^ Junta todo o povo num mesmo lugar, tanto homens, como mulheres, meninos e estrangeiros, que estão dentro das tuas portas, para que, ouvindo, aprendam a temer o Senhor vosso Deus, guardem e cumpram todas as palavras desta lei:

[[v5-31-13]]

^<<v5-31-13,13>>^ para que também seus filhos, que agora (as) ignoram, (as) possam ouvir, e temam o Senhor seu Deus durante todos os dias que viverem na terra, da qual, passado o Jordão, ides tomar posse.

[[v5-31-14]]

^<<v5-31-14,14>>^ O Senhor disse a Moisés: Avizinham-se os dias da tua morte; chama Josué, e apresentai-vos no tabernáculo da reunião, para eu lhe dar as minhas ordens. Foram, pois, Moisés e Josué, e apresentaram-se no tabernáculo da reunião,

[[v5-31-15]]

^<<v5-31-15,15>>^ e o Senhor apareceu ali na coluna de nuvem, a qual parou à entrada do tabernáculo.

[[v5-31-16]]

^<<v5-31-16,16>>^ O Senhor disse a Moisés: Eis que vais dormir com teus pais, e este povo levantando-se se prostituirá a deuses estranhos na terra, em que entra para habitar nela: ali me abandonará, e violará o pacto que fiz com ele.

[[v5-31-17]]

^<<v5-31-17,17>>^ O meu furor se acenderá então contra ele: eu o abandonarei, esconderei dele a minha face, e ele será devorado; sobre ele cairão todos os males e aflições, de tal modo que dirá naquele dia: Verdadeiramente porque Deus não está comigo, me vieram estes males.

[[v5-31-18]]

^<<v5-31-18,18>>^ Eu ocultarei a minha face naquele dia, por causa de todos os males que ele fez, por ter seguido deuses estranhos.

[[v5-31-19]]

^<<v5-31-19,19>>^ Agora escrevi para vós este cântico e ensinai-o aos filhos de Israel, para que eles o saibam de cor e o cantem, e este cântico me sirva de testemunho contra os filhos de Israel.

[[v5-31-20]]

^<<v5-31-20,20>>^ Com efeito, eu o introduzirei na terra que prometi com juramento a seus pais, terra que mana leite e mel; porém depois que tiverem comido, e se tiverem saciado e engordado, voltar-se-ão para deuses estranhos e os servirão, falarão contra mim e violarão o meu pacto.

[[v5-31-21]]

^<<v5-31-21,21>>^ Depois que tiverem caído sobre ele muitos males e aflições, deporá contra ele como testemunha este cântico, o qual não será tirado por nenhum esquecimento da boca da sua posteridade. Eu conheço os seus pensamentos, e o que ele há-de fazer hoje, antes que eu o introduza na terra que lhe prometi.

[[v5-31-22]]

^<<v5-31-22,22>>^ Moisés neste dia, escreveu o cântico e ensinou-o aos filhos de Israel.

[[v5-31-23]]

^<<v5-31-23,23>>^ O Senhor deu as suas ordens a Josué, filho de Nun, e disse-lhe: Tem coragem e sê forte, porque tu introduzirás os filhos de Israel na terra que eu lhes prometi, e eu serei contigo.

[[v5-31-24]]

^<<v5-31-24,24>>^ Quando Moisés acabou de escrever num livro as palavras desta Iei,

[[v5-31-25]]

^<<v5-31-25,25>>^ deu aos Levitas, que levavam a arca da aliança do Senhor, esta ordem.

[[v5-31-26]]

^<<v5-31-26,26>>^ Tomai este livro, e ponde-o ao lado da arca da aliança do Senhor vosso Deus, para aí servir de testemunho contra ti.

[[v5-31-27]]

^<<v5-31-27,27>>^ De facto, eu conheço a tua obstinação e a grande dureza da tua cerviz. Ainda vivendo eu e andando convosco, vos portastes sempre obstinados contra o Senhor; quanto mais depois de eu morrer?

[[v5-31-28]]

^<<v5-31-28,28>>^ Reuni junto de mim todos os anciães de cada uma das vosas tribos e os doutores, e eu pronunciarei diante deles estes palavras, invocando contra eles o céu e a terra.

[[v5-31-29]]

^<<v5-31-29,29>>^ Sei que depois da minha morte procedereis iniquamente, que depressa vos afastareis do caminho que eu vos prescrevi; cairão sobre vós calamidades no decorrer dos tempos, quando fizerdes o mal diante do Senhor, irritando-o com as obras das vossas mãos.

[[v5-31-30]]

^<<v5-31-30,30>>^ Moisés pronunciou até ao fim as palavras deste cântico, ouvindo-o todo o ajuntamento de Israel.

'''

xref:005-deuteronomio/005-deuteronomio-030.adoc#v5-30-0[&#60; Capítulo Anterior] | <<v5-31-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-032.adoc#v5-32-0[Próximo Capítulo &#62;]