include::./index.adoc[]

[[v5-24-0]]
=== Deuteronômio, 24
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Deuteronômio 24 contém leis sobre o divórcio, o perdão de dívidas, a colheita e a proteção dos direitos dos trabalhadores. O capítulo também enfatiza a importância de tratar os outros com justiça e misericórdia.
* Provérbios 22:22-23: "Não roube o pobre, porque é pobre, nem esmague o necessitado no tribunal, pois o Senhor defenderá a causa deles e tirará a vida daqueles que os roubam." Este versículo enfatiza a importância de tratar os necessitados com justiça e não explorá-los.
* Tiago 5:4: "Eis que o salário dos trabalhadores que ceifaram os vossos campos, e que por vós foi retido com fraude, está clamando; e os clamores dos ceifeiros penetraram até aos ouvidos do Senhor dos Exércitos." Este versículo fala sobre a importância de pagar os trabalhadores de forma justa e não retê-los de seus salários.
* Isaías 61:8: "Porque eu, o Senhor, amo a justiça e odeio o roubo e o mal em suas diversas formas. Eu lhes darei pagamento justo e farei uma aliança eterna com eles." Este versículo destaca a importância da justiça e condena o roubo e a exploração.
* 1 João 3:17: "Mas se alguém tem recursos materiais e vê seu irmão passando necessidade, mas fecha o coração para ele, como pode estar nele o amor de Deus?" Este versículo destaca a importância de ajudar aqueles que estão em necessidade e não ser egoísta com nossos recursos.
* Mateus 6:14-15: "Pois se perdoarem as ofensas uns dos outros, o Pai celestial também perdoará vocês. Mas se não perdoarem uns aos outros, o Pai celestial não perdoará as ofensas de vocês." Este versículo destaca a importância do perdão e da misericórdia, que é enfatizado em Deuteronômio 24 em relação ao cancelamento das dívidas.
****

[[v5-24-1]]

^<<v5-24-1,1>>^ Se um homem, tomando uma mulher, se casar com ela, e não a achar agradável diante dos seus olhos por qualquer coisa inconveniente, escreverá um libelo de repúdio lho dará na mão, e a despedirá da sua casa. (ver nota)

[[v5-24-2]]

^<<v5-24-2,2>>^ Se ela, depois de ter saído, tomar outro marido,

[[v5-24-3]]

^<<v5-24-3,3>>^ e este também a aborrecer, e, dando-Ihe libelo de repúdio, a despedir de sua casa, ou se ele veio a morrer,

[[v5-24-4]]

^<<v5-24-4,4>>^ não poderá o primeiro marido tomá-la a tomar por mulher, dado que ela está contaminada, porque isso é abominável dante do Senhor; não faças pecar a terra cuja posse te der o Senhor teu Deus.

[[v5-24-5]]

^<<v5-24-5,5>>^ Quando um homem tiver tomado uma mulher há pouco tempo, não irá à guerra, nem se lhe imporá cargo algum público, mas estará livremente em sua casa, a fim de passar alegre um ano com sua mulher.

[[v5-24-6]]

^<<v5-24-6,6>>^ Não receberás por penhor a mó inferior e a superior, porque te deu por penhor a própria vida.

[[v5-24-7]]

^<<v5-24-7,7>>^ Se se encontrar um homem que raptou um seu irmão, dos filhos de Israel, e que o tenha feito seu escravo ou vendido, será morto, e tu tirarás (assim) o mal do meio de ti.

[[v5-24-8]]

^<<v5-24-8,8>>^ Evita diligentemente contrair a praga da lepra, fazendo tudo o que te ensinarem os sacerdotes da linhagem de Levi, conforme o que lhes prescrevi; cumpre tudo à risca.

[[v5-24-9]]

^<<v5-24-9,9>>^ Lembrai-Vos do que o Senhor vosso Deus fez a Maria no caminho, quando saístes do Egipto.

[[v5-24-10]]

^<<v5-24-10,10>>^ Quando requereres de teu próximo alguma coisa que ele deve, não entrarás em sua casa para tomar (algum) penhor,

[[v5-24-11]]

^<<v5-24-11,11>>^ mas estarás fora, e ele te trará o que tiver.

[[v5-24-12]]

^<<v5-24-12,12>>^ Se ele é pobre, o penhor não pernoitará em tua casa,

[[v5-24-13]]

^<<v5-24-13,13>>^ mas tornarás a dar-lho antes de se pôr o sol a fim de que ele, dormindo na sua roupa, te abençoe: isso será para ti uma justiça diante do Senhor teu Deus.

[[v5-24-14]]

^<<v5-24-14,14>>^ Não negarás a paga do indigente e do pobre quer ele seja teu irmão, quer um estrangeiro, que mora contigo na terra, e está dentro das tuas portas,

[[v5-24-15]]

^<<v5-24-15,15>>^ mas pagar-Ihe-ás no mesmo dia o preço do seu trabalho antes do sol-posto, porque é pobre, e com isso sustenta a sua vida. De contrário ele clamaria contra ti ao Senhor, e pesaria sobre ti um pecado,

[[v5-24-16]]

^<<v5-24-16,16>>^ Não se farão morrer os pais pelos filhos, nem os filhos pelos pais, mas cada um morrerá pelo seu pecado.

[[v5-24-17]]

^<<v5-24-17,17>>^ Não perverterás a justiça (na causa) do estrangeiro e do órfão, nem tirarás por penhor o vestido da viúva.

[[v5-24-18]]

^<<v5-24-18,18>>^ Lembra-te que foste escravo no Egipto e que o Senhor teu Deus te tirou de lá. Por isso te mando que faças isto.

[[v5-24-19]]

^<<v5-24-19,19>>^ Quando segares a messe no teu campo, e deixares por esquecimento alguma gavela, não voltarás para a Ievar, mas deixá-las-ás tomar ao estrangeiro, ao órfão e à viúva, a fim de que o Senhor teu Deus te abençoe em todas as obras das tuas mãos.

[[v5-24-20]]

^<<v5-24-20,20>>^ Se tiveres colhido o fruto das oliveiras, não voltarás a colher algum resto que tenha ficado nas árvores, mas deixá-lo-ás ao estrangeiro, ao órfão e à viúva

[[v5-24-21]]

^<<v5-24-21,21>>^ Se tiveres vindimado a tua vinha, não irás colher os cachos que ficaram; serão para o estrangeiro, paia o órfão e para a viúva.

[[v5-24-22]]

^<<v5-24-22,22>>^ Lembra-te que foste também escravo no Egipto; por isso te mando que façais assim.

'''

xref:005-deuteronomio/005-deuteronomio-023.adoc#v5-23-0[&#60; Capítulo Anterior] | <<v5-24-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-025.adoc#v5-25-0[Próximo Capítulo &#62;]