include::./index.adoc[]

[[v5-15-0]]
=== Deuteronômio, 15
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Deuteronômio 15 trata sobre as leis da remissão das dívidas e da libertação dos escravos, enfatizando a importância da justiça social e da generosidade. Os versículos relacionados são:
* Provérbios 22:7 - "O rico domina sobre os pobres; e o que toma emprestado é servo do que empresta." Este versículo aborda a relação desigual entre ricos e pobres na questão das dívidas, que é abordada em Deuteronômio 15.
* Isaías 58:6 - "Porventura não é este o jejum que escolhi, que soltes as ligaduras da impiedade, que desfaças as ataduras do jugo, e que deixes livres os oprimidos, e despedaces todo o jugo?" Este versículo destaca a importância da libertação dos escravos e da justiça social, que é um tema central em Deuteronômio 15.
* Mateus 6:14-15 - "Porque, se perdoardes aos homens as suas ofensas, também vosso Pai celestial vos perdoará a vós; se, porém, não perdoardes aos homens as suas ofensas, também vosso Pai vos não perdoará as vossas ofensas." Este versículo aborda a questão do perdão, que está presente na remissão das dívidas em Deuteronômio 15.
* Lucas 6:34-35 - "E se emprestais àqueles de quem esperais receber, qual é a vossa gratidão? Também os pecadores emprestam aos pecadores, para receberem outro tanto. Amai, porém, os vossos inimigos, fazei bem e emprestai, sem nada esperardes em troca; e grande será o vosso galardão, e sereis filhos do Altíssimo; porque ele é benigno até para com os ingratos e maus." Este versículo destaca a importância da generosidade e da benevolência, que são incentivadas em Deuteronômio 15.
* 2 Coríntios 9:7 - "Cada um contribua segundo propôs no seu coração, não com tristeza ou por necessidade; porque Deus ama ao que dá com alegria." Este versículo reforça a ideia da generosidade voluntária, que é um tema presente em Deuteronômio 15, onde a remissão das dívidas e a libertação dos escravos são incentivadas de forma voluntária e generosa.
****

[[v5-15-1]]

^<<v5-15-1,1>>^ No sétimo ano farás a remissão,

[[v5-15-2]]

^<<v5-15-2,2>>^ a qual será celebrada desta maneira: Aquele a quem é devida alguma coisa por seu amigo, ou por seu próximo, ou por seu irmão, não a poderá exigir, porque é o ano da remissão do Senhor.

[[v5-15-3]]

^<<v5-15-3,3>>^ Poderás exigi-la do peregrino e do estrangeiro, mas não terás direito de a exigir dos teus compatriotas nem de teu vizinho.

[[v5-15-4]]

^<<v5-15-4,4>>^ Não haverá entre vós nenhum pobre nem mendigo, para que o Senhor teu Deus te abençoe na terra, que te entregou como herança.

[[v5-15-5]]

^<<v5-15-5,5>>^ Se ouvires a voz do Senhor teu Deus, se guardares tudo o ele te mandou, o que eu hoje te prescrevo, ele te abençoará, como prometeu.

[[v5-15-6]]

^<<v5-15-6,6>>^ Tu emprestarás a muitos povos, e de nenhum receberás empréstimos. Dominarás sobre muitas nações, nenhuma te dominará.

[[v5-15-7]]

^<<v5-15-7,7>>^ Se um dos teus irmãos, que moram dentro das portas da tua cidade, na terra, que o Senhor teu Deus está para te dar, cair em pobreza, não endurecerás o teu coração, nem fecharás a tua mão,

[[v5-15-8]]

^<<v5-15-8,8>>^ mas abri-la-ás ao pobre e lhe emprestarás o que vires que ele precisa.

[[v5-15-9]]

^<<v5-15-9,9>>^ Acautela-te, não te deixes cair num ímpio pensamento, não digas no teu coração: Está próximo o sétimo ano da remissão — e não afastes (com tal pensamento) os olhos do teu irmão pobre, não lhe querendo emprestar o que ele te pede, não suceda que ele clame contra ti ao Senhor, e isto se torne para ti num pecado.

[[v5-15-10]]

^<<v5-15-10,10>>^ Conceder-lhe-ás (o empréstimo), não usarás de astúcia alguma em o socorrer nas suas necessidades, para que o Senhor teu Deus te abençoe em todo o tempo e em todas as coisas em que puseres a mão.

[[v5-15-11]]

^<<v5-15-11,11>>^ Não faltarão pobres na terra da tua habitação, por isso eu te ordeno que abras a mão para o teu irmão necessitado e pobre, que vive contigo na terra.

[[v5-15-12]]

^<<v5-15-12,12>>^ Quando te for vendido um teu irmão hebreu, homem ou mulher, e te tiver servido seis anos, no sétimo ano deixa-lo-ás ir livre.

[[v5-15-13]]

^<<v5-15-13,13>>^ Não deixarás ir com as mãos vazias àquele a quem deres a liberdade,

[[v5-15-14]]

^<<v5-15-14,14>>^ mas dar-lhe-ás provisão para o caminho, dos rebanhos, da eira e do lagar; dar-lhe-ás dos bens com que o Senhor teu Deus te tiver abençoado.

[[v5-15-15]]

^<<v5-15-15,15>>^ Lembra-te que também tu foste escravo na terra do Egipto, e que o Senhor teu Deus te libertou; por isso eu te ordeno hoje isto.

[[v5-15-16]]

^<<v5-15-16,16>>^ Porém se (o teu escravo) te disser: Eu não quero sair porque ele te ama a ti e à tua casa, porque se encontra bem em tua casa,

[[v5-15-17]]

^<<v5-15-17,17>>^ tomarás uma sovela, furar-lhe-ás a orelha à porta de tua casa, e ele te servirá para sempre; o mesmo farás à tua escrava.

[[v5-15-18]]

^<<v5-15-18,18>>^ Não apartes dele os teus olhos, quando o tiveres posto em liberdade, porque ele serviu-te seis anos com o salário de um mercenário, para que o Senhor teu Deus te abençoe em todas as coisas que fizeres.

[[v5-15-19]]

^<<v5-15-19,19>>^ Consagrarás ao Senhor teu Deus todos os machos primogênitos do teu gado graúdo e miúdo. Não trabalharás com o primogênito da vaca, nem tosquiarás animais, o primogênito das ovelhas,

[[v5-15-20]]

^<<v5-15-20,20>>^ mas comê-los-ás cada ano tu e a tua família na presença do Senhor teu Deus, no lugar que o Senhor escolher.

[[v5-15-21]]

^<<v5-15-21,21>>^ Se tiver algum defeito, se for coxo, cego, ou disforme em alguma parte (do corpo), ou mutilado, não será imolado ao Senhor teu Deus.

[[v5-15-22]]

^<<v5-15-22,22>>^ Comê-lo-ás dentro das tuas portas; comerão igualmente dele o homem puro e o impuro, como (se come) da gazela ou do veado.

[[v5-15-23]]

^<<v5-15-23,23>>^ Terás somente o cuidado de não lhe comer o sangue, mas derramá-lo-ás por terra como água.

'''

xref:005-deuteronomio/005-deuteronomio-014.adoc#v5-14-0[&#60; Capítulo Anterior] | <<v5-15-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-016.adoc#v5-16-0[Próximo Capítulo &#62;]