include::./index.adoc[]

[[v5-18-0]]
=== Deuteronômio, 18
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Deuteronômio 18 fala sobre a posição dos levitas e profetas na comunidade de Israel, bem como a proibição da prática da adivinhação, feitiçaria e outras formas de magia. O capítulo enfatiza que o povo deve seguir somente as orientações que Deus fornece por meio dos profetas e que não deve recorrer a outras formas de consulta para obter informações. Abaixo estão cinco versículos relacionados com os temas abordados em Deuteronômio 18:
* Números 18:20: "O SENHOR disse a Arão: Você não terá herança na terra deles, nem terá parte alguma entre eles. Eu sou a sua parte e a sua herança entre os israelitas." Este versículo destaca a posição dos levitas na comunidade de Israel e como eles são responsáveis por cuidar do santuário e das ofertas.
* Jeremias 23:16: "Assim diz o SENHOR dos Exércitos: Não deem ouvidos às palavras dos profetas que entre vocês falam. Eles os enganam. Falam de visões de suas próprias mentes, não da boca do SENHOR." Este versículo reforça a ideia de que os israelitas devem confiar somente nas palavras dos profetas que falam em nome de Deus, e não em outros que não são inspirados por Ele.
* Levítico 19:31: "Não se voltem para os médiuns nem para os que consultam espíritos, nem os busquem para ficarem impuros por meio deles. Eu sou o SENHOR, o Deus de vocês." Este versículo enfatiza a proibição da prática da adivinhação e outras formas de magia mencionadas em Deuteronômio 18.
* 1 Reis 22:22: "O SENHOR disse a ele: Com que meio? Ele disse: Sairei e serei um espírito de mentira na boca de todos os seus profetas. O SENHOR disse: Você o enganará e também terá sucesso. Saia e faça isso." Este versículo mostra como os falsos profetas podem enganar o povo de Israel se eles não seguirem as orientações dadas por Deus.
* Isaías 8:19: "Quando disserem a vocês: Consultem os médiuns e os que consultam espíritos, que murmuram e sussurram, não recorram a tais coisas. Um povo não deve consultar o seu Deus pelos mortos, em favor dos vivos?" Este versículo reforça a importância de seguir somente as orientações de Deus e não recorrer a outras formas de consulta para obter informações.
****

[[v5-18-1]]

^<<v5-18-1,1>>^ Os sacerdotes e os Levitas, e todos os que são da mesma tribo, não terão parte nem herança com o resto de Israel, porque se alimentarão dos sacrifícios do Senhor e das ofertas que lhe forem feitas:

[[v5-18-2]]

^<<v5-18-2,2>>^ não receberão nenhuma herança com seus irmãos, porque o mesmo Senhor é a sua herança, como ele lhes disse:

[[v5-18-3]]

^<<v5-18-3,3>>^ Este será o direito dos sacerdotes sobre o povo, e sobre os que oferecerem vítimas: Se sacrificarem um boi ou uma ovelha, darão ao sacerdote a espádua e o peito,

[[v5-18-4]]

^<<v5-18-4,4>>^ as primícias do pão, do vinho e do azeite, e uma parte das lãs da tosquia das ovelhas.

[[v5-18-5]]

^<<v5-18-5,5>>^ Com efeito, o Senhor teu Deus escolheu-o dentre todas as tuas tribos, para que assista e sirva ao nome do Senhor, ele e seus filhos para sempre.

[[v5-18-6]]

^<<v5-18-6,6>>^ Se um Levita sair duma das tuas cidades, de qualquer parte (do território) de Israel, onde ele habita, e quiser por devoção ir ao lugar que o Senhor tiver escolhido,

[[v5-18-7]]

^<<v5-18-7,7>>^ exercerá o seu ministério em nome do Senhor seu Deus, como todos os Levitas seus irmãos, que nesse tempo assistirem diante do Senhor.

[[v5-18-8]]

^<<v5-18-8,8>>^ Receberá a mesma porção de alimentos que os outros, independentemente do produto dos seus bens patrimonais.

[[v5-18-9]]

^<<v5-18-9,9>>^ Quando tiveres entrado na terra que o Senhor teu Deus te der, guarda-te de querer imitar as abominações daquelas gentes.

[[v5-18-10]]

^<<v5-18-10,10>>^ Não se ache entre vós quem purifique seu filho ou sua filha, fazendo-os passar pelo fogo, nem quem consulte adivinhos ou observe sonhos e agouros, nem quem use maIefícios,

[[v5-18-11]]

^<<v5-18-11,11>>^ nem quem seja encantador, nem quem consulte espíritos ou adivinhos, ou indague dos mortos a verdade.

[[v5-18-12]]

^<<v5-18-12,12>>^ O Senhor abomina todas estas coisas, e por tais maldades exterminará estes povos à tua entrada.

[[v5-18-13]]

^<<v5-18-13,13>>^ Serás perfeito e sem mancha diante do Senhor teu Deus.

[[v5-18-14]]

^<<v5-18-14,14>>^ Estes povos, cujo país tu possuirás, ouvem os agouteiros e os adivinhos; tu, porém, foste instruído doutro modo pelo Senhor teu Deus.

[[v5-18-15]]

^<<v5-18-15,15>>^ O Senhor teu Deus te suscitará um PROFETA, como eu, da tua nação, e dentre teus irmãos: ouvi-lo-ás

[[v5-18-16]]

^<<v5-18-16,16>>^ como o pediste ao Senhor teu Deus em Horeb, quando todo o povo estava junto, e disseste: Não ouça eu mais a voz do Senhor meu Deus, nem torne a ver mais este grandíssimo fogo, para não acontecer que morra.

[[v5-18-17]]

^<<v5-18-17,17>>^ O Senhor disse-me: Eles falavam bem em tudo.

[[v5-18-18]]

^<<v5-18-18,18>>^ Eu lhes suscitarei do meio de seus irmãos um profeta semelhante a ti, e porei na sua boca as minhas palavras, e ele lhes dirá tudo o que eu lhes mandar.

[[v5-18-19]]

^<<v5-18-19,19>>^ Mas o que não quiser ouvir as palavras que lhe disser em meu nome, pedir-lhe-ei contas disso.

[[v5-18-20]]

^<<v5-18-20,20>>^ O profeta que, corrompido pela arrogância, quiser dizer em meu nome o que eu lhe não mandei dizer, ou falar em nome dos deuses estranhos, será morto.

[[v5-18-21]]

^<<v5-18-21,21>>^ Se tu disseres no teu coração: Como posso eu conhecer a palavra que o Senhor não disse?

[[v5-18-22]]

^<<v5-18-22,22>>^ Terás este sinal: Se o que aquele profeta predisse em nome do Senhor, não sucedeu, o Senhor não disse; o profeta, por presunção do seu ânimo, o inventou; por isso, não o temerás.

'''

xref:005-deuteronomio/005-deuteronomio-017.adoc#v5-17-0[&#60; Capítulo Anterior] | <<v5-18-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-019.adoc#v5-19-0[Próximo Capítulo &#62;]