include::./index.adoc[]

[[v5-12-0]]
=== Deuteronômio, 12
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Deuteronômio 12 trata principalmente das orientações dadas por Moisés ao povo de Israel sobre o local e o modo correto de adoração a Deus, destacando a importância de não seguir as práticas pagãs das nações vizinhas. Abaixo estão cinco versículos relacionados com os temas abordados neste capítulo:
* Josué 24:15: "Porém, se vos parece mal aos vossos olhos servir ao Senhor, escolhei hoje a quem sirvais; se aos deuses a quem serviram vossos pais, que estavam além do Rio, ou aos deuses dos amorreus, em cuja terra habitais; porém eu e a minha casa serviremos ao Senhor." Este versículo mostra a importância da escolha de adorar somente ao Senhor, e não se curvar diante de outros deuses.
* 2 Reis 17:35: "O Senhor fez aliança com eles e lhes ordenou: Não temais outros deuses, nem os adorai, nem os servi, nem lhes ofereçais sacrifícios." Este versículo reforça a importância da aliança entre Deus e seu povo, e destaca a necessidade de não adorar outros deuses.
* Jeremias 7:3-4: "Assim diz o Senhor dos Exércitos, Deus de Israel: Emendai os vossos caminhos e as vossas obras, e vos farei habitar neste lugar. Não confieis em palavras falsas, dizendo: Templo do Senhor, templo do Senhor é este." Este versículo mostra a importância da sinceridade no culto a Deus, em contraste com a mera observância de rituais religiosos.
* Miquéias 6:6-8: "Com que me apresentarei ao Senhor, e me inclinarei diante do Deus altíssimo? Virei perante ele com holocaustos, com bezerros de um ano? Agradar-se-á o Senhor de milhares de carneiros, ou de dez mil ribeiros de azeite? Darei o meu primogênito pela minha transgressão, o fruto do meu corpo pelo pecado da minha alma? Ele te declarou, ó homem, o que é bom; e que é o que o Senhor pede de ti, senão que pratiques a justiça, e ames a benignidade, e andes humildemente com o teu Deus?" Este versículo destaca a importância da justiça, bondade e humildade como elementos centrais da adoração a Deus.
* João 4:23-24: "Mas a hora vem, e agora é, em que os verdadeiros adoradores adorarão o Pai em espírito e em verdade; porque o Pai procura a tais que assim o adorem. Deus é Espírito, e importa que os que o adoram o adorem em espírito e em verdade." Este versículo reforça a importância de adorar a Deus de maneira genuína, em espírito e verdade, em vez de simplesmente seguir rituais vazios.
****

[[v5-12-1]]

^<<v5-12-1,1>>^ Estes são os preceitos e ordenações, que vós deveis cumprir na terra, que o Senhor Deus de vossos pais vos há-de dar, para a possuirdes todos os dias que andardes sobre a terra.

[[v5-12-2]]

^<<v5-12-2,2>>^ Destruí todos os lugares em que as nações, que haveis de subjugar, adoraram os seus deuses sobre os altos montes e colinas, e debaixo de qualquer árvore frondosa.

[[v5-12-3]]

^<<v5-12-3,3>>^ Derribai os seus altares, quebrai as suas estátuas, ponde fogo aos seus Ascherim, fazei em pedaços os ídolos e extingui os seus nomes daqueles lugares. (ver nota)

[[v5-12-4]]

^<<v5-12-4,4>>^ Não fareis assim com o Senhor vosso Deus,

[[v5-12-5]]

^<<v5-12-5,5>>^ mas ireis ao lugar que o Senhor vosso Deus escolher entre todas as vossas tribos, para aí pôr o seu nome e habitar nele,

[[v5-12-6]]

^<<v5-12-6,6>>^ e oferecereis neste lugar os vossos holocaustos e sacrifícios, os dízimos e as primeiras das vossas mãos, os vossos e dons, os primogênitos das vacas e das ovelhas.

[[v5-12-7]]

^<<v5-12-7,7>>^ Aí comereis na presença do Senhor vosso Deus, e vos regozijareis vós e as vossas famílias em todas as coisas que as vossas mãos adquirirem e com que o Senhor vosso Deus vos abençoar.

[[v5-12-8]]

^<<v5-12-8,8>>^ Não fareis nesse lugar o que nós fazemos hoje aqui, cada um o que bem Ihe parece,

[[v5-12-9]]

^<<v5-12-9,9>>^ porque ainda não chegastes ao repouso e herança, que o Senhor vosso Deus está para vos dar.

[[v5-12-10]]

^<<v5-12-10,10>>^ Passareis o Jordão, e habitareis na terra que o Senhor vosso Deus vos dará; então estareis seguros de todos os inimigos que vos cercam, e habitareis sem temor algum.

[[v5-12-11]]

^<<v5-12-11,11>>^ No lugar que o Senhor vosso Deus escolher para nele estar o seu nome, lá levareis todas as coisas que eu prescrevo, os holocaustos, os sacrifícios, os dízimos, as primícias das vossas mãos e tudo o que há de melhor entre os dons que oferecerdes, por voto, ao Senhor.

[[v5-12-12]]

^<<v5-12-12,12>>^ Aí vos banqueteareis diante do Senhor vosso Deus, vós, os vossos filhos e as vossas filhas, servos e servas, e o Levita que habita nas vossas cidades, porque ele não recebeu quinhão ou herança convosco.

[[v5-12-13]]

^<<v5-12-13,13>>^ Abstém-te de oferecer os teus holocaustos em qualquer lugar, que vires,

[[v5-12-14]]

^<<v5-12-14,14>>^ mas oferecê-lo-ás naquele que o Senhor tiver escolhido em uma das tuas tribos, e farás aí tudo o que te mando.

[[v5-12-15]]

^<<v5-12-15,15>>^ Se, porém, quiseres comer e gostares de comer carne, mata e come, segundo a bênção que o Senhor teu Deus te deu nas tuas cidades: tanto pode comê-la o impuro como o puro, como se come a gazela e o veado.

[[v5-12-16]]

^<<v5-12-16,16>>^ Somente não comerás o sangue, que espalharás sobre a terra como água.

[[v5-12-17]]

^<<v5-12-17,17>>^ Não poderás comer nas tuas cidades o dízimo do teu trigo, do teu vinho, do teu azeite, os primogênitos das vacas e das ovelhas, nem aquilo que ofereceres por voto, ou que voluntariamente quiseres oferecer, nem as primícias das tuas mãos,

[[v5-12-18]]

^<<v5-12-18,18>>^ mas comerás estas coisas diante do Senhor teu Deus, no lugar que o Senhor teu Deus tiver escolhido, tu e o teu filho e a tua filha, o servo, a serva, e o Levita, que habita nas tuas cidades; aí te alegrarás e te reconfortarás diante do Senhor teu Deus em todas as coisas que a tua mão tiver adquirido.

[[v5-12-19]]

^<<v5-12-19,19>>^ Abstém-te de abandonar o Levita durante todo o tempo que viveres sobre a terra.

[[v5-12-20]]

^<<v5-12-20,20>>^ Quando o Senhor teu Deus tiver dilatado os teus limites, como te prometeu, e tu quiseres comer das carnes que a tua alma deseja,

[[v5-12-21]]

^<<v5-12-21,21>>^ se estiver longe o lugar que o Senhor teu Deus escolheu, para nele estar o seu nome, matarás do gado graúdo ou miúdo que tiveres, como eu te ordenei, e comerás nas tuas cidades, como te aprouver.

[[v5-12-22]]

^<<v5-12-22,22>>^ Como se come carne de gazela e de veado, assim comerás destas carnes; comerá delas indistintamente o (homem) puro e impuro.

[[v5-12-23]]

^<<v5-12-23,23>>^ Abstém-te sòmente de comer o sangue, porque o sangue é vida, e, por isso, não deves comer a vida com a carne,

[[v5-12-24]]

^<<v5-12-24,24>>^ mas espalhá-lo-ás sobre a terra como água,

[[v5-12-25]]

^<<v5-12-25,25>>^ para que suceda bem a ti e aos teus filhos depois de ti, tendo feito o que é agradável aos olhos do Senhor,

[[v5-12-26]]

^<<v5-12-26,26>>^ Todavia as coisas que tiveres santificado e votado ao Senhor, tu as tomarás e irás ao lugar que o Senhor tiver escolhido;

[[v5-12-27]]

^<<v5-12-27,27>>^ aí oferecerás os teus holocaustos, carne e sangue, sobre o altar do Senhor teu Deus. Derramarás o sangue dos outros sacrifícios Sobre o altar, e comerás as carnes.

[[v5-12-28]]

^<<v5-12-28,28>>^ Observa e ouve tudo o que eu te ordeno, para que suceda bem a ti e aos teus filhos depois de ti perpètuamente, tendo feito o que é bom e agradável aos olhos do Senhor teu Deus.

[[v5-12-29]]

^<<v5-12-29,29>>^ Quando o Senhor teu Deus tiver exterminado diante de ti e das nações em que entrares para as possuir, quando as possuíres e habitares,

[[v5-12-30]]

^<<v5-12-30,30>>^ abstém-te de as imitar, depois que elas estiverem sido destruídas à tua entrada. Tem cuidado, não sigas os seus deuses, dizendo: Assim como estas nações adoraram os seus deuses, de mesmo modo também eu os adorarei.

[[v5-12-31]]

^<<v5-12-31,31>>^ Não farás assim com o Senhor teu Deus, porque elas fizeram pelos seus deuses todas as abominações, que o Senhor aborrece, oferecendo-lhes seus filhos e filhas, e queimando-os no fogo.

[[v5-12-32]]

^<<v5-12-32,32>>^ Faze sòmente em honra do Senhor aquilo que eu te ordeno; não acrescentes nem tires nada.

'''

xref:005-deuteronomio/005-deuteronomio-011.adoc#v5-11-0[&#60; Capítulo Anterior] | <<v5-12-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-013.adoc#v5-13-0[Próximo Capítulo &#62;]