include::./index.adoc[]

[[v65-4-0]]
=== Hebreus, 4
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Hebreus 4 fala sobre a importância de entrarmos no descanso de Deus por meio da fé em Jesus Cristo, mostrando que aqueles que não entraram no descanso de Deus por meio da incredulidade de seus corações não experimentaram a promessa de Deus. O capítulo também destaca a natureza da Palavra de Deus como viva e poderosa, capaz de discernir os pensamentos e intenções do coração. Além disso, exorta os crentes a se achegarem com confiança ao trono da graça para obterem misericórdia e graça em tempo de necessidade.
* Deuteronômio 1:32-33: "No entanto, vocês não quiseram ir, mas se rebelaram contra o mandamento do Senhor, o seu Deus. Vocês murmuraram em suas tendas e disseram: ‘O Senhor nos odeia; por isso nos trouxe do Egito para nos entregar nas mãos dos amorreus e nos destruir". Este versículo mostra como a incredulidade pode impedir as pessoas de entrar no descanso de Deus, como aconteceu com os israelitas que se recusaram a confiar em Deus e rebelaram-se contra Ele, mesmo depois de terem visto todos os milagres que Ele fez por eles no Egito.
* Salmo 95:7-8: "pois ele é o nosso Deus, e nós somos o povo do seu pastoreio, o rebanho que ele conduz. Se tão somente vocês ouvirem hoje a sua voz, não endureçam o coração como em Meribá, como em Massá, no deserto". Este verso destaca a importância de ouvirmos a voz de Deus e obedecermos a Ele, para que possamos entrar no descanso de Deus e não endurecer nossos corações pela incredulidade.
* Jeremias 23:29: "Não é a minha palavra como fogo, declara o Senhor, e como um martelo que quebra uma rocha?". Este versículo mostra a natureza poderosa e penetrante da Palavra de Deus, que é capaz de discernir os pensamentos e intenções do coração e nos guiar para a verdadeira fé em Jesus Cristo.
* Tiago 4:16: "Como é que vocês sabem o que acontecerá amanhã? A vida de vocês é como a neblina ao amanhecer: é passageira". Este versículo lembra-nos da brevidade da vida e da importância de buscarmos a Deus enquanto ainda temos tempo, para que possamos entrar no descanso de Deus por meio da fé em Jesus Cristo.
* Hebreus 11:6: "Sem fé é impossível agradar a Deus, porque quem dele se aproxima precisa crer que ele existe e que recompensa aqueles que o buscam". Este versículo destaca a importância da fé em Deus para que possamos nos aproximar do trono da graça com confiança e receber misericórdia e graça em tempo de necessidade.
****

[[v65-4-1]]

^<<v65-4-1,1>>^ Temamos pois que, desprezando a promessa (de Deus) de entrar no seu descanso, haja algum dentre vós que dele seja excluído. (ver nota)

[[v65-4-2]]

^<<v65-4-2,2>>^ Da mesma forma que eles (Israelitas), também nós recebemos a boa nova; porém a palavra que eles ouviram, não lhes aproveitou, por não ser acompanhada da fé por parte daqueles que a tinham ouvido.

[[v65-4-3]]

^<<v65-4-3,3>>^ Porém nós, que cremos, entraremos no descanso (do céu), segundo disse: Como jurei na minha ira , não entrarão no meu descanso (S. 95,11). Com certeza (Deus fala daquele descanso que teve lugar quando) estavam concluídas as suas obras depois da criação do mundo. (ver nota)

[[v65-4-4]]

^<<v65-4-4,4>>^ Com efeito, em certo lugar falou assim do sétimo dia: E Deus descansou no sétimo dia de todos as suas obras (Gn. 2, 2).

[[v65-4-5]]

^<<v65-4-5,5>>^ E outra vez: Não entrarão no meu descanso (Ps. 94, 11).

[[v65-4-6]]

^<<v65-4-6,6>>^ Como, pois, alguns entram nele, e aqueles, a quem primeiro foi anunciada a boa nova, não entraram por causa da sua incredulidade,

[[v65-4-7]]

^<<v65-4-7,7>>^ (Deus) fixa de novo um certo dia (que ele chama). Hoje, dizendo, por meio de David, muito tempo depois, o que acima foi citado: Hoje, se ouvirdes a sua voz, não endureçais os vossos corações.

[[v65-4-8]]

^<<v65-4-8,8>>^ De fato, se Josué lhes tivesse dado o descanso, Deus não teria falado, depois disso, de um outro dia.

[[v65-4-9]]

^<<v65-4-9,9>>^ Resta portanto um repouso sabático ( no céu) para o povo de Deus.

[[v65-4-10]]

^<<v65-4-10,10>>^ Realmente aquele que entrou no descanso de Deus, também repousa das suas obras, como Deus das dele.

[[v65-4-11]]

^<<v65-4-11,11>>^ Apressemos-nos, pois, a entrar naquele descanso, para que ninguém caia, dando tal exemplo de desobediência.

[[v65-4-12]]

^<<v65-4-12,12>>^ Porque a palavra de Deus é viva, eficaz e mais penetrante do que toda a espada de dois gumes; chega até à separação da alma e do espírito, das junturas e das medulas, e discerne os pensamentos e intenções do coração.

[[v65-4-13]]

^<<v65-4-13,13>>^ Não há nenhuma criatura invisível na sua presença, mas todas as coisas estão a nu e a descoberto, aos olhos daquele de quem falamos.

[[v65-4-14]]

^<<v65-4-14,14>>^ Tendo nós, pois, um grande pontífice, que penetrou os céus, Jesus, Filho de Deus, sejamos firmes na profissão da nossa fé.

[[v65-4-15]]

^<<v65-4-15,15>>^ Não temos um pontífice que não possa compadecer-se das nossas enfermidades, mas que foi tentado em tudo á nossa semelhança, excepto no pecado.

[[v65-4-16]]

^<<v65-4-16,16>>^ Aproximemo-nos, pois, confiadamente do trono da graça, a fim de alcançar misericórdia e de encontrar graça, para sermos socorridos em tempo oportuno.

'''

xref:065-hebreus/065-hebreus-003.adoc#v65-3-0[&#60; Capítulo Anterior] | <<v65-4-0,Topo>> | xref:065-hebreus/065-hebreus-005.adoc#v65-5-0[Próximo Capítulo &#62;]