include::./index.adoc[]

[[v73-21-0]]
=== Apocalipse, 21
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 21 do livro de Apocalipse fala sobre a nova Jerusalém, a cidade santa de Deus que desce do céu. Ele descreve a beleza e glória dessa cidade eterna, onde não haverá mais dor, morte ou tristeza. Os versículos a seguir foram selecionados por sua relação com os temas abordados neste capítulo.
* Isaías 65:17: "Pois eis que eu crio novos céus e nova terra; e não haverá lembrança das coisas passadas, nem mais se recordarão." Este versículo fala sobre a criação de novos céus e nova terra, que é um tema semelhante ao novo céu e a nova terra mencionados em Apocalipse 21:1.
* 2 Pedro 3:13: "Mas, segundo a sua promessa, esperamos novos céus e nova terra, nos quais habita justiça." Este versículo também fala sobre a criação de novos céus e nova terra e menciona a justiça que habita lá, assim como Apocalipse 21:27 menciona que nada impuro entrará na nova Jerusalém.
* Mateus 5:8: "Bem-aventurados os limpos de coração, porque verão a Deus." Este versículo se relaciona com Apocalipse 21:3, que fala sobre a habitação de Deus com os homens na nova Jerusalém. A pureza de coração é uma condição para ver a Deus.
* Isaías 25:8: "Aniquilará a morte para sempre, e assim enxugará o Senhor DEUS as lágrimas de todos os rostos, e tirará o opróbrio do seu povo de toda a terra; porque o SENHOR o disse." Este versículo fala sobre a eliminação da morte e do sofrimento, um tema comum em Apocalipse 21:4, que menciona a ausência de morte, luto, pranto e dor na nova Jerusalém.
* Hebreus 12:22-24: "Mas tendes chegado ao monte Sião, e à cidade do Deus vivo, à Jerusalém celestial, e aos muitos milhares de anjos; À universal assembléia e igreja dos primogênitos, que estão inscritos nos céus, e a Deus, o juiz de todos, e aos espíritos dos justos aperfeiçoados; E a Jesus, o Mediador de uma nova aliança, e ao sangue da aspersão, que fala melhor do que o de Abel." Este versículo se relaciona com Apocalipse 21:2, que fala sobre a descida da nova Jerusalém do céu. Ambos descrevem a cidade celestial de Deus e a habitação dos santos.
****

[[v73-21-1]]

^<<v73-21-1,1>>^ Depois vi um novo céu e uma nova terra, porque o primeiro céu e a primeira terra desapareceram, e o mar já não existia.

[[v73-21-2]]

^<<v73-21-2,2>>^ E vi a cidade santa, a nova Jerusalém, que descia do céu, de junto de Deus, adornada Como uma esposa ataviada para o seu esposo. (ver nota)

[[v73-21-3]]

^<<v73-21-3,3>>^ E ouvi uma grande voz, vinda do trono, que dizia: "Eis o tabernáculo de Deus com os homens: habitará com eles, eles serão o seu povo, e o mesmo Deus será com eles.

[[v73-21-4]]

^<<v73-21-4,4>>^ Enxugar-lhes-á todas as lágrimas dos seus olhos; não haverá mais morte, nem luto, nem grito, nem dor, porque as primeiras coisas passaram.

[[v73-21-5]]

^<<v73-21-5,5>>^ E o que estava sentado no trono disse: "Eis que renovo todas as coisas." E ajuntou: "Escreve, porque estas palavras são seguras e autênticas."

[[v73-21-6]]

^<<v73-21-6,6>>^ Depois disse-me: "Está feito! Eu sou o Alfa e o Ómega, o princípio e o fim (de tudo). Darei gratuitamente da fonte da água da vida ao que tiver sede. (ver nota)

[[v73-21-7]]

^<<v73-21-7,7>>^ Aquele que vencer, terá esta herança, e eu serei seu Deus, e ele será meu filho.

[[v73-21-8]]

^<<v73-21-8,8>>^ Mas, pelo que toca aos tímidos, aos incrédulos, aos execráveis, aos homicidas, aos fornicadores, aos feiticeiros, aos idólatras e a todos os mentirosos, a sua parte será no tanque ardente de fogo e de enxofre: o que é a segunda morte."

[[v73-21-9]]

^<<v73-21-9,9>>^ Então veio um dos sete anjos, que tinham as sete taças cheias das sete últimas pragas, e falou comigo, dizendo: "Vem , e eu te mostrarei a noiva, a esposa do Cordeiro."

[[v73-21-10]]

^<<v73-21-10,10>>^ E transportou-me em espírito a uma grande e alta montanha e mostrou-me a cidade santa. Jerusalém, que descia do céu de junto de Deus,

[[v73-21-11]]

^<<v73-21-11,11>>^ a qual tinha a glória de Deus; o seu brilho era semelhante a uma pedra muito preciosa, a uma pedra de jaspe cristalino.

[[v73-21-12]]

^<<v73-21-12,12>>^ Tinha um muro grande e alto com doze portas, e nas portas doze anjos e uns nomes escritos, que são os nomes das doze tribos dos filhos de Israel.

[[v73-21-13]]

^<<v73-21-13,13>>^ Três portas (estavam) ao oriente, três portas ao setentrião, três portas ao meio-dia e três portas ao ocidente.

[[v73-21-14]]

^<<v73-21-14,14>>^ O muro da cidade tinha doze fundamentos, e neles os doze nomes dos doze Apóstolos do Cordeiro.

[[v73-21-15]]

^<<v73-21-15,15>>^ E o que falava comigo tinha uma cana de ouro de medir, para medir a cidade, as suas portas e o muro.

[[v73-21-16]]

^<<v73-21-16,16>>^ A cidade é quadrangular, tão comprida como larga. Mediu a cidade com a cana; doze mil estádios. O seu comprimento, a sua altura e a sua largura são iguais. (ver nota)

[[v73-21-17]]

^<<v73-21-17,17>>^ Mediu também o seu muro; cento e quarenta e quatro côvados, medida de homem, que é também medida de anjo, (ver nota)

[[v73-21-18]]

^<<v73-21-18,18>>^ O muro é construído de pedra de jaspe, e a cidade é de ouro puro, semelhante a puro cristal.

[[v73-21-19]]

^<<v73-21-19,19>>^ Os fundamentos do muro da cidade são ornados de toda a qualidade de pedras preciosas. O primeiro fundamento é de jaspe; o segundo de safira; o terceiro de calcedónia; o quarto de esmeralda;

[[v73-21-20]]

^<<v73-21-20,20>>^ o quinto de sardónica; o sexto de sárdio; o sétimo de crisólito; o oitavo de berilo; o nono de topázio; o décimo de crisópraso; o undécimo de jacinto, o duodécimo de ametista.

[[v73-21-21]]

^<<v73-21-21,21>>^ As doze portas são doze pérolas; cada porta é feita de uma só pérola, e a praça da cidade é de ouro puro, translúcido como cristal.

[[v73-21-22]]

^<<v73-21-22,22>>^ Não vi templo nela, porque o Senhor Deus omnipotente com o Cordeiro é o seu templo.

[[v73-21-23]]

^<<v73-21-23,23>>^ A cidade não tem necessidade do sol, nem da lua, que a iluminem, porque a glória de Deus a ilumina, e o seu luzeiro é o Cordeiro.

[[v73-21-24]]

^<<v73-21-24,24>>^ As nações caminharão à sua luz, e os reis da terra lhe trarão a sua glória.

[[v73-21-25]]

^<<v73-21-25,25>>^ As suas portas não se fecharão durante todo o dia, porque ali não haverá noite.

[[v73-21-26]]

^<<v73-21-26,26>>^ Levar-lhe-ão a glória e a honra das nações.

[[v73-21-27]]

^<<v73-21-27,27>>^ Não entrará nela coisa alguma contaminada, nem quem cometa abominação ou mentira, mas sòmente aqueles que estão inscritos no livro da vida do Cordeiro.

'''

xref:073-apocalipse/073-apocalipse-020.adoc#v73-20-0[&#60; Capítulo Anterior] | <<v73-21-0,Topo>> | xref:073-apocalipse/073-apocalipse-022.adoc#v73-22-0[Próximo Capítulo &#62;]