include::./index.adoc[]

[[v73-2-0]]
=== Apocalipse, 2
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Apocalipse 2 é um capítulo da Bíblia que contém cartas escritas por Jesus Cristo para sete igrejas na Ásia Menor. Cada carta começa com uma mensagem específica para a igreja e termina com a frase "Quem tem ouvidos, ouça o que o Espírito diz às igrejas". Essas cartas abordam temas como a fidelidade, a perseverança, a correção, a tolerância e a recompensa.
* Hebreus 3:14: "Porque nos tornamos participantes de Cristo, se é que guardamos firme até ao fim a confiança que desde o princípio tivemos" A carta aos Hebreus exorta os crentes a perseverarem em sua fé e confiança em Jesus Cristo até o fim. Isso está relacionado com a mensagem de Apocalipse 2, que incentiva as igrejas a permanecerem fiéis e perseverantes.
* 2 Pedro 2:1: "Assim como, no meio do povo, surgiram falsos profetas, assim também haverá entre vós falsos mestres, os quais introduzirão, dissimuladamente, heresias destruidoras, até ao ponto de renegarem o Soberano Senhor que os resgatou, trazendo sobre si mesmos repentina destruição." A segunda carta de Pedro alerta sobre a existência de falsos mestres que introduzem heresias perigosas. Isso está relacionado com a mensagem de Apocalipse 2, que repreende as igrejas por tolerarem falsos mestres.
* Efésios 4:15: "Mas, seguindo a verdade em amor, cresçamos em tudo naquele que é a cabeça, Cristo" A carta aos Efésios exorta os crentes a seguirem a verdade em amor e a crescerem em Cristo. Isso está relacionado com a mensagem de Apocalipse 2, que incentiva as igrejas a se arrependerem e voltarem ao caminho correto, a fim de receberem recompensas eternas.
* 1 Coríntios 9:27: "Mas esmurro o meu corpo e o reduzo à escravidão, para que, tendo pregado aos outros, não venha eu mesmo a ser desqualificado." O apóstolo Paulo fala sobre a necessidade de disciplina e autocontrole em sua vida. Isso está relacionado com a mensagem de Apocalipse 2, que repreende as igrejas por não se corrigirem e se disciplinarem adequadamente.
* Colossenses 3:23-24: "Tudo quanto fizerdes, fazei-o de todo o coração, como para o Senhor e não para homens, cientes de que recebereis do Senhor a recompensa da herança. A Cristo, o Senhor, é que estais servindo." A carta aos Colossenses incentiva os crentes a servirem ao Senhor com todo o coração, cientes de que receberão recompensas. Isso está relacionado com a mensagem de Apocalipse 2, que promete recompensas aos que perseverarem e superarem as provações.
****

[[v73-2-1]]

^<<v73-2-1,1>>^ Escreve ao anjo da Igreja de Éfeso: "Isto diz aquele que tem as sete estrelas na sua direita, e anda no meio dos sete candeeiros de ouro:

[[v73-2-2]]

^<<v73-2-2,2>>^ Conheço as tuas obras, o teu trabalho, a tua paciência, sei que não podes suportar os maus, que experímentaste os que dizem ser apóstolos e não o são, e os achaste mentirosos.

[[v73-2-3]]

^<<v73-2-3,3>>^ Tens paciência, sofreste pelo meu nome e não desanimaste.

[[v73-2-4]]

^<<v73-2-4,4>>^ Mas tenho contra ti que deixaste a tua primeira caridade.

[[v73-2-5]]

^<<v73-2-5,5>>^ Lembra-te pois (do estado) donde caíste, arrepende-te e volta às tuas primeiras obras; de contrário, virei a ti e removerei o teu candeeiro do seu lugar, se não fizeres penitência. (ver nota)

[[v73-2-6]]

^<<v73-2-6,6>>^ Isto, porém, tens (de bom) que aborreces as acções dos Nicolaítas, que eu também aborreço.

[[v73-2-7]]

^<<v73-2-7,7>>^ Aquele que tem ouvidos, ouça o que o Espírito diz às Igrejas: Ao vencedor darei a comer da árvore da vida, que está no paraíso de Deus."

[[v73-2-8]]

^<<v73-2-8,8>>^ E ao anjo da Igreja de Smirna escreve: "Isto diz o primeiro e o último, o que foi morto e que retomou a vida:

[[v73-2-9]]

^<<v73-2-9,9>>^ Conheço a tua tribulação e a tua pobreza mas és rico e que és caluniado por aqueles que se dizem Judeus, e não o são, antes são uma sinagoga de Satanás.

[[v73-2-10]]

^<<v73-2-10,10>>^ Não temas nada do que terás que sofrer. Eis que o demônio fará meter na prisão alguns de vós, a fim de serdes provados; tereis tribulação durante dez dias. Sê fiel até à morte, é eu te darei a coroa da vida. (ver nota)

[[v73-2-11]]

^<<v73-2-11,11>>^ Aquele que tem ouvidos, ouça o que o Espírito diz às Igrejas: O que sair vencedor, ficará ileso da segunda morte." (ver nota)

[[v73-2-12]]

^<<v73-2-12,12>>^ E ao anjo da Igreja de Pérgamo escreve: "Isto diz aquele que tem a espada afiada de dois gumes:

[[v73-2-13]]

^<<v73-2-13,13>>^ Sei onde habitas (que é um lugar) onde Satanás tem o trono; sei que te conservas ligado ao meu nome e não renegaste a minha fé, mesmo naqueles dias em que Antipas, minha fiel testemunha, foi morto entre vós, onde Satanás habita.

[[v73-2-14]]

^<<v73-2-14,14>>^ Mas tenho contra ti alguma coisa: Tens contigo sequazes da doutrina de Balaão, o qual ensinava Balac a pôr tropeços diante dos filhos de Israel, impelindo-os a comer carnes imoladas aos ídolos e a praticar a fornicação.

[[v73-2-15]]

^<<v73-2-15,15>>^ Assim tens tu também sequazes da doutrina dos Nicolaítas.

[[v73-2-16]]

^<<v73-2-16,16>>^ Faze, pois, penitência; de contrário, virei a ti, brevemente, e pelejarei contra eles com a espada da minha boca.

[[v73-2-17]]

^<<v73-2-17,17>>^ Aquele que tem ouvidos, ouça o que o Espírito diz às Igrejas: Darei ao vencedor maná escondido, dar-lhe-ei uma pedrinha branca e um nome novo escrito na pedrinha, o qual ninguém conhece, senão quem o recebe."

[[v73-2-18]]

^<<v73-2-18,18>>^ E ao anjo da Igreja de Tiatira escreve: "Isto diz o Filho de Deus, que tem os olhos como uma chama de fogo, e cujos pés são semelhantes ao bronze.

[[v73-2-19]]

^<<v73-2-19,19>>^ Conheço as tuas obras, a tua caridade, a tua fé e o teu serviço, a tua paciência; sei que as tuas últimas obras são mais numerosas que as primeiras.

[[v73-2-20]]

^<<v73-2-20,20>>^ Porém, tenho contra ti que toleras Jezabel, essa mulher que se diz profetiza: ela ensina e desvia os meus servos, para fornicarem e comerem das carnes sacrificadas aos ídolos.

[[v73-2-21]]

^<<v73-2-21,21>>^ Dei-lhe tempo para fazer penitência, e ela não quer arrepender-se da sua prostituição.

[[v73-2-22]]

^<<v73-2-22,22>>^ Eis que a reduzirei a um leito (de dor); e aos seus companheiros de adultério (lançá-los-ei) numa grande tribulação, se não fizerem penitência das suas obras.

[[v73-2-23]]

^<<v73-2-23,23>>^ Ferirei de morte os seus filhos, e todas as Igrejas conhecerão que eu sou aquele que sonda os rins e os corações; "darei a cada um de vós segundo as vossas obras.

[[v73-2-24]]

^<<v73-2-24,24>>^ Quanto a vós, os restantes (fiéis) de Tiatira, que não seguis esta doutrina e que não conhecestes as profundidades, como eles lhes chamam, de Satanás, declaro-vos que não porei sobre vós outro peso.

[[v73-2-25]]

^<<v73-2-25,25>>^ Todavia guardai bem aquilo que tendes (recebido de Deus), até que eu venha (pedir-vos contas).

[[v73-2-26]]

^<<v73-2-26,26>>^ Aquele que vencei e que praticar as minhas obras até ao fim, eu lhe darei poder sobre as nações,

[[v73-2-27]]

^<<v73-2-27,27>>^ e as regerá com vara de ferro, como se quebram vasos de argila,

[[v73-2-28]]

^<<v73-2-28,28>>^ como também eu o recebi de meu Pai. E dar-lhes-ei a estrela da manhã. (ver nota)

[[v73-2-29]]

^<<v73-2-29,29>>^ Aquele que tem ouvidos, ouça o que o Espírito diz às Igrejas."

'''

xref:073-apocalipse/073-apocalipse-001.adoc#v73-1-0[&#60; Capítulo Anterior] | <<v73-2-0,Topo>> | xref:073-apocalipse/073-apocalipse-003.adoc#v73-3-0[Próximo Capítulo &#62;]