include::./index.adoc[]

[[v73-12-0]]
=== Apocalipse, 12
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Apocalipse 12 fala sobre uma mulher grávida que é perseguida pelo dragão e seu filho é arrebatado para Deus e seu trono. Cinco versículos que se relacionam com os temas deste capítulo são:
* Isaías 54:17: "Nenhum instrumento forjado contra você terá êxito, e você refutará toda língua que a acusar. Esta é a herança dos servos do Senhor, e esta é a defesa que faço do nome deles", declara o Senhor. Este versículo enfatiza a proteção divina contra a perseguição e as tentativas de destruição dos inimigos do povo de Deus.
* Salmos 2:9: "Com vara de ferro os esmigalharás como um vaso de oleiro". Este versículo retrata a vitória do Filho de Deus sobre Seus inimigos e Sua autoridade sobre as nações.
* Isaías 7:14: "Portanto, o próprio Senhor lhes dará um sinal: a virgem ficará grávida e dará à luz um filho, e o chamará Emanuel". Este versículo faz uma conexão com a mulher grávida em Apocalipse 12, indicando que ela representa a nação de Israel.
* 1 Tessalonicenses 4:16-17: "Pois o Senhor mesmo descerá do céu com brado de comando, com voz de arcanjo e com trombeta de Deus, e os mortos em Cristo ressuscitarão primeiro. Depois nós, os que estivermos vivos seremos arrebatados juntamente com eles nas nuvens, para encontrar o Senhor nos ares. E assim estaremos para sempre com o Senhor". Este versículo descreve o arrebatamento dos santos, que se relaciona com o arrebatamento do filho da mulher em Apocalipse 12.
* Daniel 7:13-14: "Eu continuei olhando nas minhas visões noturnas, e ali estava, vindo nas nuvens do céu, alguém como um filho de homem. Ele se aproximou do Ancião de Dias e foi conduzido à sua presença. Ele foi dado autoridade, glória e poder sobre todos os povos, nações e línguas, e todos o adorarão". Este versículo também se relaciona com a autoridade e a vitória do Filho de Deus, que é enfatizada em Apocalipse 12.
****

[[v73-12-1]]

^<<v73-12-1,1>>^ Depois apareceu no céu um grande sinal: uma Mulher vestida de sol, com a lua debaixo de seus pés, e uma coroa de doze estrelas sobre a sua cabeça. (ver nota)

[[v73-12-2]]

^<<v73-12-2,2>>^ Ela está grávida, e clama com dores, atormentada para dar a luz.

[[v73-12-3]]

^<<v73-12-3,3>>^ Foi visto ainda um outro sinal no céu: era um grande Dragão, cor de fogo, que tinha sete cabeças e dez pontas, e nas suas cabeças sete diademas.

[[v73-12-4]]

^<<v73-12-4,4>>^ A sua cauda arrasta a terça parte das estrelas do céu, e precipitou-as na terra. Depois o Dragão parou diante da Mulher, que estava para dar à luz, a fim de devorar o seu filho, logo que ela o tivesse dado à luz. (ver nota)

[[v73-12-5]]

^<<v73-12-5,5>>^ Ela deu à luz um filho varão, que deve reger todas as gentes com vara de ferro. E o seu filho foi arrebatado para Deus e para o seu trono.

[[v73-12-6]]

^<<v73-12-6,6>>^ A Mulher fugiu para o deserto, onde tinha um retiro que Deus lhe havia preparado, para aí a sustentarem durante mil e duzentos e sessenta dias. (ver nota)

[[v73-12-7]]

^<<v73-12-7,7>>^ Houve no céu uma batalha: Miguel e os seus anjos pelejavam contra o Dragão, e o Dragão com os seus anjos pelejava contra ele;

[[v73-12-8]]

^<<v73-12-8,8>>^ porém estes não prevaleceram, nem o seu lugar se encontrou mais no céu.

[[v73-12-9]]

^<<v73-12-9,9>>^ E foi precipitado o grande Dragão, a antiga Serpente, que se chama Demônio e Satanás, que seduz todo o mundo, foi precipitado na terra, e foram precipitados com ele os seus anjos.

[[v73-12-10]]

^<<v73-12-10,10>>^ E ouvi uma grande voz no céu, que dizia: "Agora foi estabelecida a salvação, a força, o reino do nosso Deus e o poder do seu Cristo, porque foi precipitado (do céu) o acusador de nossos irmãos, que os acusava de dia e de noite diante do nosso Deus.

[[v73-12-11]]

^<<v73-12-11,11>>^ Porém eles venceram-no pelo (mérito do) sangue do Cordeiro e pela palavra do seu testemunho, e desprezaram a sua vida, até morrer (por Cristo).

[[v73-12-12]]

^<<v73-12-12,12>>^ Por isso, ó céus, alegrai-vos, e vós os que habitais neles. Ai da terra e do mar, porque o Demônio desceu a vós com grande ira, sabendo que lhe resta pouco tempo (para perder almas)."

[[v73-12-13]]

^<<v73-12-13,13>>^ Quando o Dragão se viu precipitado na terra, perseguiu a Mulher que tinha dado à luz o filho varão,

[[v73-12-14]]

^<<v73-12-14,14>>^ mas foram dadas à Mulher duas asas de uma grande águia, a fim de voar para o deserto, ao lugar do seu retiro, onde é sustentada por um tempo, por (dois) tempos e por metade de um tempo, fora da presença da Serpente. (ver nota)

[[v73-12-15]]

^<<v73-12-15,15>>^ Então a Serpente lançou da sua boca, atrás da Mulher, água (de perseguições) como um rio, para fazer que ela fosse arrebatada pela corrente.

[[v73-12-16]]

^<<v73-12-16,16>>^ Porém a terra ajudou a Mulher: abriu a sua boca e enguliu o rio que o Dragão tinha vomitado da sua boca. (ver nota)

[[v73-12-17]]

^<<v73-12-17,17>>^ O Dragão irou-se contra a Mulher e foi fazer guerra aos outros seus descendentes, que guardam os mandamentos de Deus e retêm a confissão de Jesus Cristo. (ver nota)

[[v73-12-18]]

^<<v73-12-18,18>>^ E postou-se sobre a areia do mar.

'''

xref:073-apocalipse/073-apocalipse-011.adoc#v73-11-0[&#60; Capítulo Anterior] | <<v73-12-0,Topo>> | xref:073-apocalipse/073-apocalipse-013.adoc#v73-13-0[Próximo Capítulo &#62;]