include::./index.adoc[]

[[v73-16-0]]
=== Apocalipse, 16
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Apocalipse 16 descreve a série de sete taças da ira de Deus que são derramadas sobre a terra, trazendo juízo e destruição sobre aqueles que rejeitaram a salvação e se opuseram a Deus. Os versículos abaixo foram selecionados por sua relação com os temas abordados neste capítulo.
* Jeremias 25:15-16: "Porque assim me disse o Senhor, o Deus de Israel: Toma da minha mão este cálice do vinho da ira e faze-o beber a todas as nações, às quais eu te envio; para que bebam, e cambaleiem, e enlouqueçam, por causa da espada que enviarei entre eles." Este versículo fala sobre a ira de Deus sendo derramada sobre as nações por causa de sua desobediência.
* Salmos 79:6: "Derrama o teu furor sobre as nações que não te conhecem, e sobre os reinos que não invocam o teu nome." Este salmo clama a Deus para trazer juízo sobre aqueles que não o reconhecem como Senhor e Salvador.
* Isaías 51:17: "Desperta, desperta, levanta-te, ó Jerusalém, que bebeste da mão do Senhor o cálice da sua ira; pois o cálice tremendo bebeste até ao fundo." Este versículo descreve o juízo que caiu sobre Jerusalém por causa da desobediência do povo.
* Êxodo 7:20: "Moisés e Arão fizeram como o Senhor ordenara, e, levantando a vara, feriu as águas que estavam no rio, à vista de Faraó e dos seus servos; e todas as águas do rio se tornaram em sangue." Este versículo lembra da praga das águas que se tornaram em sangue, que foi uma das dez pragas enviadas sobre o Egito como juízo divino.
* Apocalipse 11:18: "As nações se iraram; e chegou a tua ira. É chegada a hora de julgares os mortos e de dares recompensa aos teus servos, os profetas, aos santos e aos que temem o teu nome, tanto aos pequenos como aos grandes, e de destruíres os que destroem a terra." Este versículo fala sobre a ira de Deus que será derramada sobre aqueles que destroem a terra, e a recompensa que será dada aos seus servos fiéis.
****

[[v73-16-1]]

^<<v73-16-1,1>>^ E ouvi uma grande voz (que saía) do templo, a qual dizia aos sete anjos: "Ide e derramai sobre a terra as sete taças da ira de Deus."

[[v73-16-2]]

^<<v73-16-2,2>>^ E foi o primeiro e derramou a sua taça sobre a terra, e formou-se uma úlcera cruel e maligna nos homens que tinham o sinal da Besta e se prostravam diante da sua estátua.

[[v73-16-3]]

^<<v73-16-3,3>>^ O segundo (anjo) derramou a sua taça sobre o mar, que se tornou em sangue, como de um corpo morto, e morreu todo o ser vivo, que existia no mar,

[[v73-16-4]]

^<<v73-16-4,4>>^ O terceiro (anjo) derramou a sua taça sobre os rios e sobre as fontes das águas, que se converteram em sangue.

[[v73-16-5]]

^<<v73-16-5,5>>^ E ouvi o anjo das águas, que dizia: "Justo és, Senhor, que és e que eras, tu, o Santo, porque executaste estes juízos!

[[v73-16-6]]

^<<v73-16-6,6>>^ Porque eles derramaram o sangue dos santos e dos profetas, lhes deste também a beber sangue, pois assim o merecem."

[[v73-16-7]]

^<<v73-16-7,7>>^ E ouvi o altar que dizia: "Sim, Senhor Deus omnipotente, são verdadeiros e justos os teus juízos."

[[v73-16-8]]

^<<v73-16-8,8>>^ O quarto (anjo) derramou a sua taça sobre o sol, e foi-lhe dado (poder de) queimar os homens pelo fogo.

[[v73-16-9]]

^<<v73-16-9,9>>^ Os homens foram atingidos com queimaduras grandes e blasfemaram do nome de Deus, que tem poder sobre estas pragas, e não se arrependeram para lhe darem glória.

[[v73-16-10]]

^<<v73-16-10,10>>^ O quinto(anjo) derramou a sua taça sobre o trono da Besta: o reino dela tornou-se tenebroso, e (os homens) mordiam a língua com a veemência da dor,

[[v73-16-11]]

^<<v73-16-11,11>>^ e blasfemaram do Deus do céu por causa das suas dores e das suas úlceras, e não se arrependeram das suas obras.

[[v73-16-12]]

^<<v73-16-12,12>>^ O sexto (anjo) derramou a sua taça sobre o grande rio Eufrates, e secaram-se as suas águas, a fim de se abrir caminho aos reis do Oriente. (ver nota)

[[v73-16-13]]

^<<v73-16-13,13>>^ Vi sair da boca do Dragão, da boca da Besta e da boca do falso profeta, três espíritos imundos semelhantes a rãs,

[[v73-16-14]]

^<<v73-16-14,14>>^ que são espíritos de demônios, que fazem prodígios, e que vão aos reis de toda a terra, a fim de os juntar para a batalha do grande dia do Deus omnipotente.

[[v73-16-15]]

^<<v73-16-15,15>>^ Eis que venho como um ladrão (diz o Senhor)! Bem-aventurado aquele que vigia e guarda os seus vestidos (da graça e da fé), para que não ande nu e não deixe ver a sua vergonha!

[[v73-16-16]]

^<<v73-16-16,16>>^ Eles os juntaram num lugar que, em hebraico, se chama Harmagedon.

[[v73-16-17]]

^<<v73-16-17,17>>^ O sétimo (anjo) derramou a sua taça pelo ar, e saiu uma grande voz do templo, (vinda) do trono, que dizia; "Está feito" (ver nota)

[[v73-16-18]]

^<<v73-16-18,18>>^ E seguiram-se relâmpagos, vozes e trovões; depois houve um grande terramoto, tão grande que nunca houve outro igual desde que existem homens sobre a terra.

[[v73-16-19]]

^<<v73-16-19,19>>^ E a grande cidade foi dividida em três partes, e as cidades das nações caíram. Babilônia, a grande, foi recordada por Deus, para lhe dar a beber o cálice do vinho da indignação da sua ira. (ver nota)

[[v73-16-20]]

^<<v73-16-20,20>>^ Todas as ilhas fugiram e as montanhas não foram achadas.

[[v73-16-21]]

^<<v73-16-21,21>>^ E caiu do céu sobre os homens uma grande descarga de saraiva, do peso de um talento; e os homens blasfemaram de Deus, por causa da praga da saraiva, porque a praga desta saraiva é extremamente grande.

'''

xref:073-apocalipse/073-apocalipse-015.adoc#v73-15-0[&#60; Capítulo Anterior] | <<v73-16-0,Topo>> | xref:073-apocalipse/073-apocalipse-017.adoc#v73-17-0[Próximo Capítulo &#62;]