include::./index.adoc[]

[[v73-11-0]]
=== Apocalipse, 11
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 11 do livro de Apocalipse descreve a medição do templo de Deus, a presença de duas testemunhas que profetizam e realizam milagres, a batalha contra a Besta, a ressurreição das testemunhas e o terremoto que destrói a décima cidade. Aqui estão cinco versículos de outros livros da Bíblia que se relacionam com os temas abordados em Apocalipse 11:
* Zacarias 4:2-3: "E perguntei: Que é isto? E ele me disse: Isto é o candelabro todo de ouro, que está diante do Senhor de toda a terra. E duas oliveiras há junto dela, uma à direita do vaso do azeite, e outra à sua esquerda." Este versículo fala de um candelabro de ouro, que pode ser relacionado com a medição do templo de Deus em Apocalipse 11.
* 1 Reis 17:1: "Elias, o tesbita, dos moradores de Gileade, disse a Acabe: Vive o Senhor Deus de Israel, perante cuja face estou, que nestes anos nem orvalho nem chuva haverá, senão segundo a minha palavra." As duas testemunhas em Apocalipse 11 têm o poder de fechar o céu para que não chova, como Elias fez.
* 2 Reis 2:11: "E sucedeu que, indo eles andando e falando, eis que um carro de fogo, com cavalos de fogo, os separou um do outro; e Elias subiu ao céu num redemoinho." A ascensão de Elias pode ser comparada com a ascensão das duas testemunhas em Apocalipse 11.
* Daniel 7:21-22: "Eu olhava, quando esse chifre fazia guerra contra os santos, e prevalecia contra eles, até que veio o Ancião de dias, e fez justiça aos santos do Altíssimo; e chegou o tempo em que os santos possuíram o reino." Esse versículo fala da batalha contra os santos, que é semelhante à batalha contra as duas testemunhas em Apocalipse 11.
* Isaías 26:19: "Os teus mortos viverão, juntamente com o meu corpo morto ressuscitarão. Despertai e cantai, os que habitais no pó; porque o teu orvalho, ó Deus, será como o orvalho das ervas, e a terra lançará de si os mortos." A ressurreição das testemunhas em Apocalipse 11 é semelhante à ressurreição mencionada neste versículo.
****

[[v73-11-1]]

^<<v73-11-1,1>>^ Depois foi-me dada uma cana semelhante a uma vara, e foi-me dito: "Levanta-te e mede o templo de Deus, o altar e os que nele adoram. (ver nota)

[[v73-11-2]]

^<<v73-11-2,2>>^ Mas o átrio, que está fora do templo, deixa-o de parte, não o meças, porque ele foi dado aos gentios, e eles calcarão a cidade santa durante quarenta e dois meses.

[[v73-11-3]]

^<<v73-11-3,3>>^ E darei às minhas duas testemunhas o poder de profetizar, revestidos de saco, durante mil duzentos e sessenta dias:

[[v73-11-4]]

^<<v73-11-4,4>>^ são as duas oliveiras e os dois candeeiros, postos diante do Senhor da terra. (ver nota)

[[v73-11-5]]

^<<v73-11-5,5>>^ Se alguém lhes quer fazer mal, sai fogo da sua boca, que devora os seus inimigos; se alguém os quer prejudicar, é assim que deve morrer.

[[v73-11-6]]

^<<v73-11-6,6>>^ Eles têm poder de fechar o céu, para que não chova durante o tempo da sua profecia, e têm poder sobre as águas, para as converter em sangue, e de ferir a terra com todo o gênero de pragas, todas as vezes que quiserem.

[[v73-11-7]]

^<<v73-11-7,7>>^ E, quando tiverem acabado de dar o seu testemunho, a Besta que sobe do abismo fará guerra contra eles, vencê-los-á e matá-los-á. (ver nota)

[[v73-11-8]]

^<<v73-11-8,8>>^ Os seus cadáveres ficam estendidos nas praças da grande cidade, que se chama espiritualmente Sodoma e Egipto, onde também o Senhor deles foi crucificado.

[[v73-11-9]]

^<<v73-11-9,9>>^ E homens de todos os povos, tribos, línguas e nações, olham os seus cadáveres, durante três dias e meio, sem permitir que estes cadáveres sejam sepultados.

[[v73-11-10]]

^<<v73-11-10,10>>^ E os habitantes da terra se alegram por causa deles e se felicitam; e mandarão presentes uns aos outros, porque estes dois profetas tinham atormentado os que habitavam sobre a terra. (ver nota)

[[v73-11-11]]

^<<v73-11-11,11>>^ Mas, depois de três dias e meio, um espírito de vida entrou neles da parte de Deus, e eles puseram-se de pé, e apoderou-se um grande temor dos que os contemplavam.

[[v73-11-12]]

^<<v73-11-12,12>>^ E ouviram uma grande voz do céu, que lhes dizia: "Subi para cá." E subiram ao céu na nuvem, á vista dos seus inimigos.

[[v73-11-13]]

^<<v73-11-13,13>>^ Naquela mesma hora deu-se um grande terramoto: caiu a décima parte da cidade, e no terramoto foram mortos sete mil homens; os restantes foram atemorizados e deram glória ao Deus do céu.

[[v73-11-14]]

^<<v73-11-14,14>>^ Passou o segundo ai; o terceiro ai virá em breve.

[[v73-11-15]]

^<<v73-11-15,15>>^ O sétimo anjo tocou a trombeta, e ouviram-se no céu grandes vozes, que diziam: "O reino deste mundo passou a ser de Nosso Senhor e do seu Cristo, e ele reinará pelos séculos dos séculos."

[[v73-11-16]]

^<<v73-11-16,16>>^ Então os vinte e quatro anciães, que estão sentados diante de Deus sobre os seus tronos, prostraram-se sobre os seus rostos e adoraram a Deus, dizendo:

[[v73-11-17]]

^<<v73-11-17,17>>^ "Graças te damos. Senhor Deus omnipotente, que és e que eras, porque assumiste o teu grande poder e reinaste.

[[v73-11-18]]

^<<v73-11-18,18>>^ As nações irritaram-se (contra ti), mas chegou o teu furor, assim como o tempo de julgar os mortos e de dar a recompensa aos profetas, teus servos, aos santos e aos que temem o teu nome, peque-nos e grandes, e de exterminar os que destruíam a terra.

[[v73-11-19]]

^<<v73-11-19,19>>^ Então abriu-se o templo de Deus, o do céu, e apareceu a arca da sua aliança no seu templo. E sobrevieram relâmpagos, vozes, trovões, um terramoto e uma grande saraivada.

'''

xref:073-apocalipse/073-apocalipse-010.adoc#v73-10-0[&#60; Capítulo Anterior] | <<v73-11-0,Topo>> | xref:073-apocalipse/073-apocalipse-012.adoc#v73-12-0[Próximo Capítulo &#62;]