include::./index.adoc[]

[[v73-18-0]]
=== Apocalipse, 18
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Apocalipse 18 fala sobre a queda da grande cidade, Babilônia, que é vista como uma figura simbólica do sistema mundial de poder e corrupção. A cidade é vista como responsável por todas as coisas malignas e abomináveis que têm ocorrido na terra. Aqui estão cinco versículos de outras partes da Bíblia que se relacionam com os temas abordados em Apocalipse 18:
* Jeremias 50:32: "A soberba de Babilônia cairá e não se levantará mais; destruirei as suas imagens esculpidas e as suas estátuas; e ela será para sempre um objeto de horror." Este versículo fala sobre a queda da cidade de Babilônia e sua soberba, o que é semelhante ao que é descrito em Apocalipse 18.
* Jeremias 51:7: "A Babilônia foi um cálice de ouro nas mãos do Senhor, que embriagou toda a terra. As nações beberam do vinho da sua ira; por isso, elas agora estão loucas." Este versículo descreve como a Babilônia foi usada por Deus para punir outras nações, mas agora ela mesma será punida.
* Jeremias 51:45: "Saiam do meio dela, povo meu! Salvem-se, cada um de vocês, da ira ardente do Senhor." Este versículo é um apelo para que as pessoas saiam da cidade de Babilônia antes que ela seja destruída, o que é semelhante ao que é descrito em Apocalipse 18.
* Isaías 47:8-9: "Agora, porém, ouça isto, ó delicada, que vive despreocupada e diz em seu coração: ‘Eu sou a única, e não há mais ninguém como eu. Não ficarei viúva, nem perderei os meus filhos’. Ambas essas coisas virão sobre você num instante, num mesmo dia: a perda de seus filhos e a viuvez. Elas virão sobre você em toda a sua plenitude, apesar de suas muitas feitiçarias e do grande número de seus encantamentos." Este versículo se refere à cidade de Babilônia como uma figura simbólica de uma mulher arrogante e autoconfiante que será punida por suas maldades.
* Isaías 48:20: "Saiam de Babilônia! Fugam dos babilônios! Anunciem isto com gritos de alegria, e proclamem-no. Mandem-no até os confins da terra; digam: ‘O Senhor resgatou o seu servo Jacó!’" Este versículo é um chamado para as pessoas deixarem a cidade de Babilônia antes que ela seja destruída.
****

[[v73-18-1]]

^<<v73-18-1,1>>^ Depois disto, vi descer do céu outro anjo, que tinha um grande poder, e a terra foi iluminada com a sua glória.

[[v73-18-2]]

^<<v73-18-2,2>>^ Gritou com vós forte, dizendo: "Caiu, caiu Babilônia, a grande! Tornou-se habitação de demônios, guarida de todo o espírito imundo e albergue de toda a ave impura e abominável,

[[v73-18-3]]

^<<v73-18-3,3>>^ porque todas as nações beberam do vinho da cólera da sua furiosa impudicícia e os reis da terra fornicaram com ela, e os mercadores da terra tornaram-se ricos com o excesso do seu luxo."

[[v73-18-4]]

^<<v73-18-4,4>>^ Depois ouvi outra voz do céu, que dizia: "Sai dela, povo meu, para não seres participante dos seus delitos, e para não seres compreendido nas suas pragas,

[[v73-18-5]]

^<<v73-18-5,5>>^ porque os seus pecados se acumularam até ao céu, e Deus lembrou-se das suas iniquidades.

[[v73-18-6]]

^<<v73-18-6,6>>^ Tratai-a como ela tratou e dai-lhe o dobro conforme as suas obras; na taça em que ela derramou, derramai-lhe o dobro.

[[v73-18-7]]

^<<v73-18-7,7>>^ Quanto ela se glorificou e se deu ao luxo, tanto lhe dai de tormento e pranto, porque diz no seu coração: estou sentada como rainha, não sou viúva e não verei o pranto.

[[v73-18-8]]

^<<v73-18-8,8>>^ Por isso, num mesmo dia, cairão sobre ela as pragas, a morte, o pranto e a fome, e será abrasada em fogo, porque é forte o Senhor Deus que a julgou."

[[v73-18-9]]

^<<v73-18-9,9>>^ Chorá-la-ão e lamentá-la-ão os reis da terra, que pecaram com ela e viveram em delícias, quando virem o fumo do seu incêndio.

[[v73-18-10]]

^<<v73-18-10,10>>^ Estando de longe, com medo dos tormentos dela, dirão; "Ai, ai daquela grande cidade de Babilônia, daquela cidade forte! Num momento veio o seu juízo!"

[[v73-18-11]]

^<<v73-18-11,11>>^ E os negociantes da terra choram-na e lamentam-na, porque ninguém compra mais os seus carregamentos,

[[v73-18-12]]

^<<v73-18-12,12>>^ carregamentos de ouro, de prata, de pedras preciosas, de pérolas, de linho fino, de púrpura, de seda, de escarlate, de toda a madeira odorífera, de todos os objectos de marfim, de todos os objectos da mais preciosa madeira, de bronze, de ferro, de mármore,

[[v73-18-13]]

^<<v73-18-13,13>>^ de ciuamomo, amorno, perfumes, mirra, incenso, vinho, azeite, flor da farinha, trigo, animais de carga, ovelhas, cavalos, carroças, escravos e até almas humanas! (ver nota)

[[v73-18-14]]

^<<v73-18-14,14>>^ Os frutos desejados pela tua alma se retiraram de ti, e todas as coisas delicadas e magníficas se perderam para ti, e não mais, não mais se encontrarão.

[[v73-18-15]]

^<<v73-18-15,15>>^ Os mercadores destas coisas, que se enriqueceram, estarão longe dela com medo dos seus tormentos, chorando e lamentando-se,

[[v73-18-16]]

^<<v73-18-16,16>>^ dizendo: "Ai, ai da grande cidade, que estava vestida de linho fino, de púrpura e de escarlate, e que se adornava de ouro, de pedras preciosas e de pérolas,

[[v73-18-17]]

^<<v73-18-17,17>>^ porque num momento foram reduzidas a nada tantas riquezas!" E todos os pilotos, todos os que fazem navegação costeira, os marinheiros e quantos vivem do mar, ficaram ao longe,

[[v73-18-18]]

^<<v73-18-18,18>>^ e, vendo o fumo do seu incêndio, clamavam, dizendo: "Que cidade era semelhante a esta grande cidade?"

[[v73-18-19]]

^<<v73-18-19,19>>^ E lançavam pó sobre as suas cabeças e clamavam, chorando e lamentando-se assim: "Aí, ai daquela grande cidade, de cujas riquezas se enriqueceram todos os que têm navios no mar! Num momento foi arruinada!"

[[v73-18-20]]

^<<v73-18-20,20>>^ Exulta sobre ela, ó céu, e vós, os santos, os apóstolos e os profetas, porque Deus, julgando-a, fez-vos justiça.

[[v73-18-21]]

^<<v73-18-21,21>>^ Então um anjo forte levantou uma pedra, como uma grande mó de moinho, e lançou-a ao mar, dizendo: "Com este ímpeto será precipitada Babilônia, a grande cidade, e não será jamais encontrada.

[[v73-18-22]]

^<<v73-18-22,22>>^ Não se ouvirá mais em ti a voz dos tocadores de citara, dos músicos, dos tocadores de flauta e de trombeta; não se encontrará mais em ti artista algum de qualquer arte, nem se tornará mais a ouvir o ruído da mó,

[[v73-18-23]]

^<<v73-18-23,23>>^ nem luzirá mais a luz de uma lâmpada; não se ouvirá mais em ti a voz do esposo e da esposa, porque os teus mercadores eram uns príncipes da terra, porque por causa dos teus encantamentos erraram todas as nações.

[[v73-18-24]]

^<<v73-18-24,24>>^ Nesta cidade foi encontrado o sangue dos profetas e dos santos e de todos os que foram mortos sobre a terra."

'''

xref:073-apocalipse/073-apocalipse-017.adoc#v73-17-0[&#60; Capítulo Anterior] | <<v73-18-0,Topo>> | xref:073-apocalipse/073-apocalipse-019.adoc#v73-19-0[Próximo Capítulo &#62;]