include::./index.adoc[]

[[v73-20-0]]
=== Apocalipse, 20
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Apocalipse 20 descreve a cena em que Satanás é preso por mil anos e Cristo reina com os santos na terra. Cinco versículos relacionados com os temas abordados em Apocalipse 20 são:
* 2 Pedro 3:7: "E os céus e a terra que agora existem pela mesma palavra se reservam como tesouro, e se guardam para o fogo, até o Dia do Juízo, e da perdição dos homens ímpios." Este versículo menciona o Dia do Juízo, que é o evento que ocorre após o reinado de mil anos de Cristo e antes do novo céu e nova terra.
* Mateus 19:28: "Jesus lhes disse: Em verdade vos digo que vós, que me seguistes, quando, na regeneração, o Filho do homem se assentar no trono da sua glória, também vos assentareis sobre doze tronos, para julgar as doze tribos de Israel." Este versículo fala sobre a regeneração, que pode ser interpretada como o reinado de mil anos de Cristo na terra.
* Lucas 22:30: "para que comais e bebais à minha mesa no meu reino, e vos assenteis sobre tronos, julgando as doze tribos de Israel." Este versículo também fala sobre o reino de Cristo e a participação dos santos no julgamento das tribos de Israel.
* 1 Coríntios 6:2: "Ou não sabeis que os santos hão de julgar o mundo? Ora, se o mundo deve ser julgado por vós, sois porventura indignos de julgar as coisas mínimas?" Este versículo reforça a ideia de que os santos participarão do julgamento no reino de Cristo.
* Isaías 2:2: "E acontecerá nos últimos dias que se firmará o monte da casa do SENHOR no cume dos montes, e se elevará por cima dos outeiros; e concorrerão a ele todas as nações." Este versículo fala sobre a universalidade do reino de Cristo, que será estabelecido após o julgamento.
****

[[v73-20-1]]

^<<v73-20-1,1>>^ Vi descer do céu um anjo que tinha na sua mão a chave do abismo e uma grande cadeia.

[[v73-20-2]]

^<<v73-20-2,2>>^ Prendeu o Dragão, a Serpente antiga, que é o Demônio e Satanás, e amarrou-o por mil anos. (ver nota)

[[v73-20-3]]

^<<v73-20-3,3>>^ Meteu-o no abismo, fechou-o e pôs selo sobre ele, para que não seduza mais as nações até se completarem os mil anos. Depois disto, deve ser solto por um pouco de tempo.

[[v73-20-4]]

^<<v73-20-4,4>>^ Em seguida vi tronos, e sentaram-se sobre eles aqueles a quem foi dado o poder de julgar; vi também as almas daqueles que foram degolados por causa do testemunho de Jesus e da palavra de Deus, e todos os que não adoraram a Besta nem a sua estátua, nem receberam o seu sinal sobre a fronte ou sobre a mão; esses viveram e reinaram com Cristo durante mil anos.

[[v73-20-5]]

^<<v73-20-5,5>>^ Os outros mortos não tornaram à vida até que se completassem os mil anos. E’ a primeira ressurreição.

[[v73-20-6]]

^<<v73-20-6,6>>^ Bem-aventurado e santo aquele que tem parte na primeira ressurreição; a segunda morte (que é a condenação eterna) não tem poder sobre estes, mas serão sacerdotes de Deus e de Cristo, e reinarão com ele durante mil anos.

[[v73-20-7]]

^<<v73-20-7,7>>^ Quando se completarem os mil anos. Satanás será solto da sua prisão,

[[v73-20-8]]

^<<v73-20-8,8>>^ sairá a seduzir as nações que estão nos quatro ângulos da terra, a Gog e a Magog, e os juntará para a batalha: o seu número é como a areia do mar.

[[v73-20-9]]

^<<v73-20-9,9>>^ Subiram pela superfície da terra e cercaram os acampamentos dos santos e a cidade querida. Mas desceu do céu um fogo que os devorou.

[[v73-20-10]]

^<<v73-20-10,10>>^ E o demônio, que os seduzia, foi metido no tanque de fogo e de enxofre, onde também a Besta e o falso profeta serão atormentados de dia e de noite pelos séculos doe séculos.

[[v73-20-11]]

^<<v73-20-11,11>>^ Depois vi um grande trono branco e o que estava sentado sobre ele, de cuja vista fugiram a terra e o céu, sem deixar rasto de si. (ver nota)

[[v73-20-12]]

^<<v73-20-12,12>>^ E vi os mortos, grandes e pequenos, de pé diante do trono. Foram abertos livros; e foi aberto um outro livro, que é o da vida; e foram julgados os mortos pelas coisas que estavam escritas nos livros, segundo as suas obras. (ver nota)

[[v73-20-13]]

^<<v73-20-13,13>>^ O mar deu os mortos que estavam nele, a morte e o Hades deram (também) os mortos que estavam neles, e fez-se juízo de cada um segundo as suas obras. (ver nota)

[[v73-20-14]]

^<<v73-20-14,14>>^ Depois, a morte e o Hades foram lançados no tanque de fogo (o tanque de fogo é a segunda morte).

[[v73-20-15]]

^<<v73-20-15,15>>^ E aquele que se não achou inscrito no livro da vida, foi lançado no tanque de fogo.

'''

xref:073-apocalipse/073-apocalipse-019.adoc#v73-19-0[&#60; Capítulo Anterior] | <<v73-20-0,Topo>> | xref:073-apocalipse/073-apocalipse-021.adoc#v73-21-0[Próximo Capítulo &#62;]