include::./index.adoc[]

[[v22-1-0]]
=== I Macabeus, 1
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O livro de 1 Macabeus narra a história dos judeus no período intertestamentário, entre o fim do Antigo Testamento e o início do Novo Testamento. O capítulo 1 descreve a profanação do Templo de Jerusalém pelo rei Antíoco Epifânio IV e sua tentativa de impor a cultura e religião grega aos judeus. Abaixo estão cinco versículos relacionados com os temas abordados em 1 Macabeus 1:
* 2 Macabeus 4:15: "Não mais se preocupando com os ritos sagrados dos pais, mas tendo em vista a glória dos gregos e o seu modo de vida" Esse versículo retrata a influência da cultura grega e a falta de respeito pelos ritos e tradições religiosas judaicas, que foi uma das principais causas da profanação do Templo.
* Daniel 8:11-12: "Ele se engrandeceu até o próprio Príncipe do exército; de sua parte foi tirado o sacrifício contínuo, e foi deitado por terra o lugar do seu santuário. E um exército foi posto em pé contra o sacrifício contínuo, por causa da transgressão; e lançou a verdade por terra, e o que fez prosperou." Esses versículos profetizam a profanação do templo e a suspensão do sacrifício contínuo, que é um elemento central da adoração judaica.
* 2 Macabeus 5:11-12: "E, chegando a Jerusalém com grande exército, mandou Antíoco Epifânio seus amigos, os quais eram líderes da sua hoste, a Jerusalém, para falarem com os judeus com engano, dizendo: Vinde, façamos um acordo de paz convosco, e com o que concordarem todos nós, vos será lícito, no dia de sábado, fazer negócio, e compras, e vender no país dos judeus, sem que ninguém vos inquiete." Esses versículos descrevem a tentativa de Antíoco Epifânio de enganar os judeus e convencê-los a abandonar suas práticas religiosas em troca de liberdade para fazer negócios.
* Ezequiel 7:22-23: "Farei vir sobre eles a maldade dos estranhos, e os entregarei à violência dos ímpios, e a terra será profanada pelo seu sangue. E farei cessar a arrogância dos fortes, e os seus lugares santos serão profanados." Esses versículos falam sobre a profanação dos lugares sagrados pelos estrangeiros e a violência contra os judeus, um tema semelhante ao que é retratado em 1 Macabeus 1.
* Jeremias 25:9-11: "Eis que enviarei, e tomarei a todas as tribos do norte, diz o Senhor, e a Nabucodonosor, rei de babilônia, meu servo, e os trarei contra esta terra, e contra os seus moradores, e contra todas estas nações em redor, e os destruirei totalmente, e farei deles objeto de espanto, e de assobio, e de perpétuo deserto." Estes versículos profetizam a invasão da Babilônia e a destruição da terra e seus moradores, um tema que é retomado em 1 Macabeus 1.
****

[[v22-1-1]]

^<<v22-1-1,1>>^ Quando Alexandre, filho de Filipe da Macedónia, que reinou primeiramente na Grécia, saído do país de Cetim, derrotou Dario, rei dos Persas e dos Medos, ficando a reinar em seu lugar,

[[v22-1-2]]

^<<v22-1-2,2>>^ deu muitas, batalhas, tomou muitas fortalezas e matou reis da terra (que lhe resistiram).

[[v22-1-3]]

^<<v22-1-3,3>>^ Passando até às extremidades do mundo, apoderou-se dos despojos de muitas nações, e toda a terra emudeceu diante dele.

[[v22-1-4]]

^<<v22-1-4,4>>^ Reuniu um exército muito poderoso, e o seu coração elevou-se e ficou todo inchado (de soberba).

[[v22-1-5]]

^<<v22-1-5,5>>^ Tornou-se senhor de províncias, nações e reis, que ficaram sendo seus tributários.

[[v22-1-6]]

^<<v22-1-6,6>>^ Depois disto, caiu enfermo e reconheceu que ia morrer.

[[v22-1-7]]

^<<v22-1-7,7>>^ Chamou os grandes da sua corte, companheiros da sua mocidade, e repartiu por eles o seu reino, estando ainda vivo.

[[v22-1-8]]

^<<v22-1-8,8>>^ Reinou Alexandre doze anos e morreu.

[[v22-1-9]]

^<<v22-1-9,9>>^ Os grandes da sua corte começaram a reinar, cada um no território designado.

[[v22-1-10]]

^<<v22-1-10,10>>^ Depois da morte de Alexandre, puseram todos o diadema, e, após eles, seus filhos, durante muitos anos, multiplicando-se os males sobre a terra.

[[v22-1-11]]

^<<v22-1-11,11>>^ Destes reis saiu aquela raiz do pecado, Antíoco Epífanes, filho do rei Antíoco, que em Boma tinha já estado como refém e que começou a reinar no ano cento e trinta e sete do reino dos Gregos.

[[v22-1-12]]

^<<v22-1-12,12>>^ Naqueles dias saíram de Israel uns filhos iníquos, que seduziram muitos, dizendo: Vamos e façamos aliança com as nações circunvizinhas, porque, desde que nos separamos delas, vieram sobre nós muitos males.

[[v22-1-13]]

^<<v22-1-13,13>>^ E pareceu bem este conselho a seus olhos.

[[v22-1-14]]

^<<v22-1-14,14>>^ Alguns do povo resolveram-se e foram ter com o rei, o qual lhes deu poder de viver segundo os costumes dos gentios.

[[v22-1-15]]

^<<v22-1-15,15>>^ Em seguida edificaram em Jerusalém um ginásio conforme o uso das nações.

[[v22-1-16]]

^<<v22-1-16,16>>^ Dissimularam os sinais da circuncisão, separaram-se da santa aliança, juntaram-se com as nações e venderam-se para fazerem o mal.

[[v22-1-17]]

^<<v22-1-17,17>>^ Quando lhe pareceu bem consolidado o seu reino (da Síria), Antíoco começou a querer reinar no país do Egipto, para ser soberano dos dois reinos.

[[v22-1-18]]

^<<v22-1-18,18>>^ (Com este designo) entrou no Egipto à frente dum poderoso exército, com carros, elefantes, cavalaria e grande número de navios.

[[v22-1-19]]

^<<v22-1-19,19>>^ Fez guerra a Ptolomeu, rei do Egipto, e Ptolomeu, tomado de medo diante dele, fugiu, caindo feridos muitos (dos seus).

[[v22-1-20]]

^<<v22-1-20,20>>^ Antíoco tomou as cidades fortes da terra do Egipto e levou os seus despojos.

[[v22-1-21]]

^<<v22-1-21,21>>^ Depois de ter vencido o Egipto, no ano cento e quarenta e três, Antíoco voltou e marchou contra Israel:

[[v22-1-22]]

^<<v22-1-22,22>>^ Chegado a Jerusalém com um formidável exército,

[[v22-1-23]]

^<<v22-1-23,23>>^ entrou cheio de soberba no santuário e tomou o altar de ouro, o candeeiro dos lumes com todos os seus utensílios, a mesa da proposição, as bacias, os copos, os grais de ouro, o véu, as coroas, e arrancou todo o ornamento de ouro que cobria o templo.

[[v22-1-24]]

^<<v22-1-24,24>>^ Tomou a prata e o ouro, os vasos preciosos e os tesouros escondidos que encontrou. Tendo saqueado tudo, foi-se para o seu país,

[[v22-1-25]]

^<<v22-1-25,25>>^ depois de haver feito grande matança de homens e proferido palavras insolentes.

[[v22-1-26]]

^<<v22-1-26,26>>^ Então houve um grande pranto em Israel, em todo o país.

[[v22-1-27]]

^<<v22-1-27,27>>^ Os príncipes e os anciães gemeram, as virgens e os jovens ficaram sem forças, e a formosura das mulheres desbotou.

[[v22-1-28]]

^<<v22-1-28,28>>^ O desposado entregava-se ao pranto, e a desposada, assentada sobre o seu leito nupcial, derramava lágrimas;

[[v22-1-29]]

^<<v22-1-29,29>>^ o país comoveu-se com a desolação dos seus habitantes, e toda a casa de Jacob se cobriu de confusão.

[[v22-1-30]]

^<<v22-1-30,30>>^ Depois, ao cabo de dois anos, o rei enviou por todas as cidades de Judá um superintendente dos tributos, o qual chegou a Jerusalém com muitas tropas.

[[v22-1-31]]

^<<v22-1-31,31>>^ Dirigiu-lhes astuciosamente palavras de paz, e eles acreditaram.

[[v22-1-32]]

^<<v22-1-32,32>>^ Então deu de repente sobre a cidade, fez eram os nela grande estrago e matou grande número de israelitas.

[[v22-1-33]]

^<<v22-1-33,33>>^ Tomou os despojos da cidade, pôs-lhes fogo e destruiu as suas casas e os muros que a cercavam.

[[v22-1-34]]

^<<v22-1-34,34>>^ (Os seus soldados) levaram cativas as mulheres e as crianças, e apoderaram-se dos seus gados.

[[v22-1-35]]

^<<v22-1-35,35>>^ Seguidamente fortificaram a cidade de Davide com um grande e sólido muro e com firmes torres, fazendo dela uma fortaleza.

[[v22-1-36]]

^<<v22-1-36,36>>^ Guarneceram-na com uma raça de pecado, com homens perversos, e aí se fortificaram. Meteram lá armas e provisões, assim como os despojos de Jerusalém,

[[v22-1-37]]

^<<v22-1-37,37>>^ que puseram de reserva. Deste modo vieram a ser uma perigosa ameaça,

[[v22-1-38]]

^<<v22-1-38,38>>^ uma armadilha para o santuário, inimigos mortais para Israel;

[[v22-1-39]]

^<<v22-1-39,39>>^ derramaram o sangue inocente ao redor do santuário e profanaram-no.

[[v22-1-40]]

^<<v22-1-40,40>>^ Os habitantes de Jerusalém fugiram por causa deles, a cidade tornou-se morada dos estrangeiros, tornou-se estranha aos seus naturais: seus próprios filhos a abandonaram.

[[v22-1-41]]

^<<v22-1-41,41>>^ O seu santuário ficou desolado como um ermo; os seus dias de festa transformaram-se em pranto, os seus sábados em opróbrio, a sua glória em desprezo.

[[v22-1-42]]

^<<v22-1-42,42>>^ À proporção da sua glória se multiplicou a sua ignomínia, e a sua alta elevação transformou-se em luto.

[[v22-1-43]]

^<<v22-1-43,43>>^ Então o rei Antíoco decretou a todo o seu reino que todos os povos não fossem mais que um, que cada qual abandonasse a sua lei particular.

[[v22-1-44]]

^<<v22-1-44,44>>^ Todas as nações se conformaram com esta ordem do rei Antíoco;

[[v22-1-45]]

^<<v22-1-45,45>>^ muitos de Israel submeteram-se a este culto, sacrificaram aos ídolos e violaram o sábado.

[[v22-1-46]]

^<<v22-1-46,46>>^ O rei enviou cartas, por meio de mensageiros, a Jerusalém e a todas as cidades de Judá, ordenando que seguissem (todas) as leis das outras nações (pagãs) da terra;

[[v22-1-47]]

^<<v22-1-47,47>>^ que no templo de Deus se não fizessem holocaustos, sacrifícios e ofertas em expiação dos pecados;

[[v22-1-48]]

^<<v22-1-48,48>>^ que se profanassem os sábados e as solenidades.

[[v22-1-49]]

^<<v22-1-49,49>>^ Mandou (além disto) que se profanassem os lugares santos e o santo povo de Israel.

[[v22-1-50]]

^<<v22-1-50,50>>^ Ordenou que se erigissem altares e templos, que se levantassem ídolos, que se oferecessem em sacrifício suínos (e outros) animais imundos,

[[v22-1-51]]

^<<v22-1-51,51>>^ que deixassem os seus filhos por circuncidar, que contaminassem suas almas com toda a casta de impurezas e abominações, de sorte que se esquecessem da lei de Deus e transtornassem todas as suas prescrições.

[[v22-1-52]]

^<<v22-1-52,52>>^ Todos aqueles que não procedessem conforme a ordem do rei seriam mortos.

[[v22-1-53]]

^<<v22-1-53,53>>^ Publicou todas estas ordens em todo o seu reino e nomeou inspectores sobre, todo o povo.

[[v22-1-54]]

^<<v22-1-54,54>>^ Ordenou também às cidades de Judá que sacrificassem aos ídolos, cidade por cidade.

[[v22-1-55]]

^<<v22-1-55,55>>^ Muitos do povo, todos aqueles que tinham abandonado a lei do Senhor, juntaram-se aos ímpios; fizeram muito mal no país

[[v22-1-56]]

^<<v22-1-56,56>>^ e obrigaram o povo (fiel) de Israel a fugir para lugares afastados, a buscar retiros, onde pudessem esconder-se na sua fuga.

[[v22-1-57]]

^<<v22-1-57,57>>^ No dia quinze do mês de Casleu, no ano cento e quarenta e cinco, edificaram a abominação da desolação sobre o altar de Deus; por toda a parte se edificaram altares (aos ídolos), em todas as cidades de Judá, ao redor.

[[v22-1-58]]

^<<v22-1-58,58>>^ Queimavam Incenso (aos ídolos) e sacrificavam (até) diante das portas das casas e no meio das praças.

[[v22-1-59]]

^<<v22-1-59,59>>^ Rasgavam e queimavam todos os livros da lei de Deus, que podiam encontrar.

[[v22-1-60]]

^<<v22-1-60,60>>^ A todo aquele, em poder de quem se achavam os livros do testamento do Senhor, e a qualquer que observava a lei do Senhor, davam a morte conforme o édito do rei.

[[v22-1-61]]

^<<v22-1-61,61>>^ Com este poder que tinham (do rei) tratavam assim, cada mês, o povo de Israel que se encontrava nas cidades. (ver nota)

[[v22-1-62]]

^<<v22-1-62,62>>^ No dia vinte e cinco de cada mês sacrificavam sobre o altar (idolátrico) que estava sobre o altar (do Senhor).

[[v22-1-63]]

^<<v22-1-63,63>>^ As mulheres que circuncidavam seus filhos eram mortas, segundo a ordem do rei Antíoco,

[[v22-1-64]]

^<<v22-1-64,64>>^ e os meninos pendurados pelo pescoço; também matavam os seus parentes e os que tinham realizado a operação.

[[v22-1-65]]

^<<v22-1-65,65>>^ Entretanto muitos do povo de Israel resolveram não comer nada impuro e preferiram morrer a manchar-se com alimentos (impuros):

[[v22-1-66]]

^<<v22-1-66,66>>^ não quiseram violar a santa lei do Senhor, e foram trucidados.

[[v22-1-67]]

^<<v22-1-67,67>>^ Caiu sobre Israel uma grande cólera.

'''

xref:021-salmos/021-salmos-150.adoc#v21-150-0[&#60; Capítulo Anterior] | <<v22-1-0,Topo>> | xref:022-i-macabeus/022-i-macabeus-002.adoc#v22-2-0[Próximo Capítulo &#62;]