include::./index.adoc[]

[[v22-10-0]]
=== I Macabeus, 10
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* 1 Macabeus 10 descreve a aliança feita entre o rei selêucida, Antíoco VII, e o sumo sacerdote judeu, João Hircano I. Nessa aliança, João Hircano recebe a confirmação de sua posição como sumo sacerdote e líder político dos judeus, além da promessa de paz e cooperação entre o reino selêucida e os judeus.
* 2 Crônicas 9:26: "Ele também reinou sobre todos os reis, desde o Rio até a terra dos filisteus e até a fronteira do Egito." João Hircano I foi um governante judeu que expandiu seu controle sobre uma grande parte da Palestina, incluindo áreas que antes estavam sob domínio estrangeiro.
* Esdras 4:23: "Então, quando a cópia da carta do rei Artaxerxes foi lida perante Reum, e Sinsai, o escrivão, e seus companheiros, eles foram depressa a Jerusalém, aos judeus, e os impediram com mão armada." Esse versículo fala sobre oposição externa ao governo judeu e pode ser visto como um contraste com a aliança pacífica entre João Hircano I e Antíoco VII.
* Isaías 19:19: "Naquele dia haverá um altar para o Senhor no meio da terra do Egito, e uma coluna para o Senhor na sua fronteira." Esse versículo é interessante porque fala sobre um altar para o Senhor em território egípcio, sugerindo que a religião judaica estava se espalhando para além da Palestina.
* Mateus 22:21: "Então ele lhes disse: 'Dêem a César o que é de César e a Deus o que é de Deus'." Esse versículo fala sobre a relação entre a autoridade política e a religião, um tema que é relevante para a aliança entre João Hircano I e Antíoco VII.
* Atos dos Apóstolos 10:34-35: "Então Pedro abriu a boca e disse: Na verdade, compreendo agora que Deus não faz acepção de pessoas; Mas em toda nação aquele que o teme e faz o que é justo é aceitável para ele." Esse versículo fala sobre a ideia de que a religião é uma questão pessoal e pode ser praticada em diferentes culturas e locais, algo que pode ser relacionado à aliança entre João Hircano I e Antíoco VII, que permitiu a coexistência pacífica de diferentes culturas e religiões em uma área geográfica.
****

[[v22-10-1]]

^<<v22-10-1,1>>^ No ano cento e sessenta, Alexandre, filho de Antíoco, cognominado Epífanes, marchou e ocupou a Ptolemaida; foi bem recebido e reinou ali.

[[v22-10-2]]

^<<v22-10-2,2>>^ O rei Demétrio, ao saber disto, levantou um exército muito numeroso e avançou a encontrar-se com ele para lhe dar batalha.

[[v22-10-3]]

^<<v22-10-3,3>>^ Então Demétrio enviou a Jónatas uma carta cheia de expressões de paz, prometendo elevá-lo em dignidade.

[[v22-10-4]]

^<<v22-10-4,4>>^ Antecipemo-nos a fazer a paz com ele, — dizia (Demétrio) consigo — antes que a faça com Alexandre com prejuízo nosso,

[[v22-10-5]]

^<<v22-10-5,5>>^ porque ele (Jónatas) se lembrará de todos os males que lhe fizemos, a ele, a seu irmão e ao seu povo.

[[v22-10-6]]

^<<v22-10-6,6>>^ (Demétrio) deu-lhe, pois poder de levantar um exército, de fazer armas e de se dizer seu aliado, e mandou que lhe entregassem os reféns detidos na cidadela (de Jerusalém).

[[v22-10-7]]

^<<v22-10-7,7>>^ Foi Jónatas a Jerusalém e leu as cartas, ouvindo-o todo o povo, assim como as tropas que ocupavam a cidadela.

[[v22-10-8]]

^<<v22-10-8,8>>^ Estas ficaram tomadas dum grande medo, depois de ouvirem que o rei lhe tinha dado poder de juntar um exército.

[[v22-10-9]]

^<<v22-10-9,9>>^ Foram, pois, entregues os reféns a Jónatas, o qual os restituiu aos seus parentes.

[[v22-10-10]]

^<<v22-10-10,10>>^ Jónatas estabeleceu-se em Jerusalém e começou a edificar e a renovar a cidade.

[[v22-10-11]]

^<<v22-10-11,11>>^ Mandou aos operários que levantassem uma muralha de cintura, em pedras de silharia, em volta do monte Sião, para sua fortaleza, e eles assim o fizeram.

[[v22-10-12]]

^<<v22-10-12,12>>^ Então os estrangeiros, que estavam nas fortalezas que Báquides tinha edificado, fugiram;

[[v22-10-13]]

^<<v22-10-13,13>>^ cada um deixou o seu lugar e foi para a sua terra.

[[v22-10-14]]

^<<v22-10-14,14>>^ Ficaram somente em Betsur alguns daqueles que tinham abandonado a lei e os preceitos de Deus, porque esta cidade lhes servia de refúgio.

[[v22-10-15]]

^<<v22-10-15,15>>^ Entretanto o rei Alexandre soube das promessas que Demétrio tinha feito a Jónatas; contaram-lhe também as batalhas e provas de valor, que ele e seus irmãos tinham dado, e os trabalhos suportados.

[[v22-10-16]]

^<<v22-10-16,16>>^ Disse: Porventura poderemos encontrar um homem como este? Procuremos, pois, fazê-lo nosso amigo e aliado.

[[v22-10-17]]

^<<v22-10-17,17>>^ Escreveu e enviou-lhe uma carta, concebida nestes termos:

[[v22-10-18]]

^<<v22-10-18,18>>^ O rei Alexandre, ao seu irmão Jónatas, saúde.

[[v22-10-19]]

^<<v22-10-19,19>>^ Temos ouvido dizer de ti que és um homem poderoso e apto para seres nosso amigo;

[[v22-10-20]]

^<<v22-10-20,20>>^ portanto constituímos-te hoje sumo pontífice da tua nação e damos-te o título de amigo do rei— nessa ocasião mandou-lhe uma veste de púrpura e uma coroa de ouro — para que cuides dos nossos interesses e nos conserves amizade.

[[v22-10-21]]

^<<v22-10-21,21>>^ No ano cento e sessenta, no sétimo mês, vestiu-se Jónatas da túnica sagrada, no dia da solene festa dos Tabernáculos; e levantou um exército e mandou fazer grande quantidade de armas.

[[v22-10-22]]

^<<v22-10-22,22>>^ Quando Demétrio teve conhecimento destas coisas contristou-se muito e disse:

[[v22-10-23]]

^<<v22-10-23,23>>^ Que proceder foi o nosso, a ponto que Alexandre nos haja precedido em conciliar a amizade dos Judeus para fortificar o seu partido?

[[v22-10-24]]

^<<v22-10-24,24>>^ Escrever-lhes-ei também palavras persuasivas, oferecendo-lhes dignidades e dávidas, para que sejam comigo em minha ajuda.

[[v22-10-25]]

^<<v22-10-25,25>>^ Escreveu-lhes, pois, nestes termos; o rei Demétrio, à nação dos Judeus, saúde.

[[v22-10-26]]

^<<v22-10-26,26>>^ Ouvimos dizer que tendes guardado a aliança que fizestes conosco, que perseverastes firmes na nossa amizade, não vos coligando com os nossos inimigos, e disto nos alegramos.

[[v22-10-27]]

^<<v22-10-27,27>>^ Perseverai, agora, como até aqui, em nos conservar a mesma fidelidade; pagar-vos-emos avantajadamente o que fizerdes por nós:

[[v22-10-28]]

^<<v22-10-28,28>>^ libertar-vos-emos de muitos encargos e cumular-vos-emos de obséquios.

[[v22-10-29]]

^<<v22-10-29,29>>^ Desde agora vos isento, a vós e a todos os Judeus, dos tributos que costumáveis pagar, do imposto do sal e das coroas. À terça parte dos produtos do chão (ver nota)

[[v22-10-30]]

^<<v22-10-30,30>>^ e à metade dos frutos das árvores, a que tinha direito, a tudo isso desde o dia de hoje em diante renuncio, não querendo que se receba mais do país de Judá, nem das três regiões que lhe foram anexas, tiradas da Samaria e da Galileia. Isto, desde hoje e para sempre.

[[v22-10-31]]

^<<v22-10-31,31>>^ (Quero) também que Jerusalém seja santa e livre com todo o seu território, e que os dízimos e os tributos sejam para ela.

[[v22-10-32]]

^<<v22-10-32,32>>^ Igualmente renuncio à posse da fortaleza, que está em Jerusalém, e dou-a ao sumo sacerdote, a fim de que ponha nela os homens que ele mesmo escolher, para que a guardem.

[[v22-10-33]]

^<<v22-10-33,33>>^ Dou mais, sem resgate algum, a liberdade a todos os Judeus, que vieram cativos do país de Judá e se encontrarem em todo o meu reino, isentando-os a todos de pagarem tributos por si e também pelos seus gados.

[[v22-10-34]]

^<<v22-10-34,34>>^ (Quero da mesma sorte) que todas as festas solenes, os dias de sábado, as neoménias, as festas decretadas, assim como os três dias antes de cada festa solene e os três depois dela, sejam todos dias de imunidade e de isenção para todos os Judeus que estão no meu reino;

[[v22-10-35]]

^<<v22-10-35,35>>^ (nesses dias) ninguém terá direito de exigir deles coisa alguma, nem de os molestar, seja por que assunto for.

[[v22-10-36]]

^<<v22-10-36,36>>^ Também (ordeno) que dos Judeus se alistem nas tropas do rei até trinta mil homens, aos quais se dará o mesmo soido que às demais tropas do rei. Deles se escolherão alguns para serem postos nas grandes fortalezas do rei,

[[v22-10-37]]

^<<v22-10-37,37>>^ e outros serão colocados em lugares de confiança do reino; sejam deles mesmos tirados os seus chefes, e viram conforme as suas leis, como o rei ordenou para o país de Judá

[[v22-10-38]]

^<<v22-10-38,38>>^ Que as três regiões da Samaria, anexas à Judeia, sejam consideradas como a própria Judeia, de forma que não estejam sujeitas a nenhum outro poder, que não seja o do sumo pontífice.

[[v22-10-39]]

^<<v22-10-39,39>>^ Quanto à Ptolemaida e a todo o seu território, faço doação dela ao santuário de Jerusalém, para as despesas necessárias ao culto.

[[v22-10-40]]

^<<v22-10-40,40>>^ Afora isto, darei todos os anos quinze mil siclos de prata, que se tomarão dos direitos reais, nos domínios que me pertencem.

[[v22-10-41]]

^<<v22-10-41,41>>^ Tudo aquilo que ultrapasse as despesas feitas nos anos anteriores, será entregue desde hoje para o serviço do templo.

[[v22-10-42]]

^<<v22-10-42,42>>^ Além disto, os cinco mil siclos de prata, cobrados todos os anos das rendas do santuário, ser-lhe-ão deixados, porque pertencem aos sacerdotes, que exercem as funções do seu ministério.

[[v22-10-43]]

^<<v22-10-43,43>>^ Também (quero) que todos aqueles que se refugiarem no templo de Jerusalém, ou dentro da sua cerca, por causa de dívida ao fisco ou por qualquer outro motivo, fiquem imunes, assim como todos os bens que possuem no meu reino!

[[v22-10-44]]

^<<v22-10-44,44>>^ As despesas para edificar ou reparar as obras do santuário serão feitas por conta do rei,

[[v22-10-45]]

^<<v22-10-45,45>>^ como também o que se gastar para reedificar os muros de Jerusalém, para fortificar a sua cerca e para fazer muralhas nas cidades da Judeia.

[[v22-10-46]]

^<<v22-10-46,46>>^ Mas Jónatas e o povo, quando ouviram estas propostas (de Demétrio), não as tiveram por sinceras e não as aceitaram, poi-que se lembravam dos grandes males que ele tinha feito a Israel e de quanto os tinha atribulado.

[[v22-10-47]]

^<<v22-10-47,47>>^ Declararam-se, pois, a favor de Alexandre, visto ter sido o primeiro que lhes falara de paz e auxiliaram-no sempre dali por diante.

[[v22-10-48]]

^<<v22-10-48,48>>^ (Negociado isto) levantou o rei Alexandre um grande exército e marchou com suas tropas contra Demétrio.

[[v22-10-49]]

^<<v22-10-49,49>>^ Os dois reis deram batalha, mas o exército de Demétrio fugiu. Alexandre foi em seu alcance e deu sobre ele.

[[v22-10-50]]

^<<v22-10-50,50>>^ A peleja foi renhida, até que se pôs o sol, e Demétrio foi morto naquele dia.

[[v22-10-51]]

^<<v22-10-51,51>>^ Depois destas coisas, Alexandre enviou embaixadores a Ptolomeu, rei do Egipto, encarregados de lhe dizer o seguinte;

[[v22-10-52]]

^<<v22-10-52,52>>^ Eis que voltei ao meu reino e me assentei no trono de meus pais, tomei conta do poder, derrotei Demétrio e entrei na posse de meus domínios.

[[v22-10-53]]

^<<v22-10-53,53>>^ Vim com ele às mãos, derrotei-o, a ele e às suas tropas, e assentei-me no trono do seu reino.

[[v22-10-54]]

^<<v22-10-54,54>>^ Façamos agora amizade um com o outro; (por isso) dá-me a tua filha por mulher, e eu serei teu genro, e, assim a ti como a ela, darei presentes condignos.

[[v22-10-55]]

^<<v22-10-55,55>>^ O rei Ptolomeu respondeu-lhe: Venturoso o dia em que tornaste a ocupar a terra de teus pais e te assentaste no trono do seu reino!

[[v22-10-56]]

^<<v22-10-56,56>>^ Agora te farei o que me pediste por escrito; mas vem ter comigo a Ptolemaida, para que ali nos vejamos, e far-te-ei meu genro, como disseste.

[[v22-10-57]]

^<<v22-10-57,57>>^ Saiu, pois, Ptolomeu do Egipto, com sua filha Cleópatra, e foi a Ptolemaida, no ano cento e sessenta e dois.

[[v22-10-58]]

^<<v22-10-58,58>>^ Ali compareceu em sua presença o rei Alexandre, a quem Ptolomeu deu sua filha Cleópatra, e celebrou as núpcias em Ptolemaida com grande magnificência, segundo o costume dos reis.

[[v22-10-59]]

^<<v22-10-59,59>>^ O rei Alexandre escreveu também a Jónatas, para que viesse avistar-se com ele.

[[v22-10-60]]

^<<v22-10-60,60>>^ Jónatas foi com grande, pompa a Ptolemaida, onde visitou os dois reis, e deu-lhes, assim como aos seus amigos, prata, ouro e muitos presentes, conquistando o seu favor.

[[v22-10-61]]

^<<v22-10-61,61>>^ Então concertaram-se certos homens perversos de Israel, homens iniquos, para apresentarem uma acusação contra ele, mas o rei não os quis atender.

[[v22-10-62]]

^<<v22-10-62,62>>^ Antes mandou que se tirassem a Jónatas as suas vestes e que o vestissem de púrpura, o que se fez. Depois o rei mandou-o sentar a seu lado

[[v22-10-63]]

^<<v22-10-63,63>>^ e disse aos grandes da sua corte: Ide com ele pelo meio da cidade e fazei publicar em voz alta que ninguém se atreva a formar contra ele queixa, por título algum, e que ninguém lhe seja molesto por qualquer coisa que for.

[[v22-10-64]]

^<<v22-10-64,64>>^ Aqueles que tinham vindo com tenção de o acusar quando o viram públicamente exaltado e vestido de púrpura, fugiram todos.

[[v22-10-65]]

^<<v22-10-65,65>>^ O rei honorificou-o, pô-lo no número dos seus primeiros amigos e constituiu-o general e governador.

[[v22-10-66]]

^<<v22-10-66,66>>^ Jónatas voltou para Jerusalém, em paz e com alegria.

[[v22-10-67]]

^<<v22-10-67,67>>^ No ano cento e sessenta e cinco, Demétrio, filho de Demétrio, voltou de Creta à terra de seus pais.

[[v22-10-68]]

^<<v22-10-68,68>>^ Logo que o rei Alexandre teve conhecimento disto, incomodou-se muito e partiu para Antioquia.

[[v22-10-69]]

^<<v22-10-69,69>>^ O rei Demétrio fez general das suas tropas a Apolónio, que era governador da Celesiria. Este levantou um grande exército e chegou a Jâmnia, donde enviou um mensageiro a Jónatas, sumo sacerdote,

[[v22-10-70]]

^<<v22-10-70,70>>^ a dizer: Tu és o único que nos resistes, e, por isso, estou feito um objecto de riso e de opróbrio. Como poderás aguentar-te contra nós nas montanhas?

[[v22-10-71]]

^<<v22-10-71,71>>^ Se, pois, agora confias nas tuas tropas, desce a nós ao campo, e façamos lá prova das nossas forças, porque o poder das batalhas me acompanha.

[[v22-10-72]]

^<<v22-10-72,72>>^ Pergunta e saberás quem eu sou e quais os meus aliados. Eles dizem que os vossos pés se não podem manter firmes diante da nossa face, porque teus pais foram postos duas vezes em fuga na sua própria terra.

[[v22-10-73]]

^<<v22-10-73,73>>^ Como poderás tu, pois, agora resistir ao ímpeto da cavalaria e dum tão grande exército, num campo, onde não há nem pedra, nem penedo, nem lugar para fugir?

[[v22-10-74]]

^<<v22-10-74,74>>^ Jónatas, quando ouviu estas palavras de Apolónio, ficou muito indignado. Escolheu dez mil homens, partiu de Jerusalém, e Simão, seu irmão, se foi encorporar com ele para o socorrer.

[[v22-10-75]]

^<<v22-10-75,75>>^ Acamparam junto de Jope, mas os da cidade fecharam-lhes as portas, porque dentro de Jope havia uma guarnição de Apolónio. Jónatas combateu-a.

[[v22-10-76]]

^<<v22-10-76,76>>^ Aterrados, os que estavam dentro da cidade abriram as portas, e assim Jónatas apoderou-se de Jope.

[[v22-10-77]]

^<<v22-10-77,77>>^ Quando ouviu isto, Apolónio fez logo avançar consigo três mil cavaleiros e um exército numeroso.

[[v22-10-78]]

^<<v22-10-78,78>>^ Marchando como quem ia pelo caminho de Azot, para passar adiante, logo de improviso se lançou na campina, porque tinha muita cavalaria e nela se fiava. Seguiu-o Jónatas para Azot, e ali deram batalha um ao outro.

[[v22-10-79]]

^<<v22-10-79,79>>^ Apolónio tinha deixado de emboscada mil cavaleiros atrás (para surpreender os Judeus).

[[v22-10-80]]

^<<v22-10-80,80>>^ Jónatas teve notícia de que ficava por detrás dele uma emboscada. Os inimigos rodearam o seu arraial, e, desde manhã 'até à tarde, não cessaram de atirar dardos contra a sua gente.

[[v22-10-81]]

^<<v22-10-81,81>>^ O povo permaneceu firme, conforme a ordem que Jónatas lhe tinha dado, enquanto que os cavalos dos inimigos se fatigaram muito.

[[v22-10-82]]

^<<v22-10-82,82>>^ Então Simão fez avançar as suas tropas e atacou a falange, porque a cavalaria estava cansada, de sorte que foram derrotados e fugiram.

[[v22-10-83]]

^<<v22-10-83,83>>^ Os cavaleiros dispersaram-se pela planície, e os fugitivos acolheram-se em Azot, onde entraram no templo de Dagon, seu ídolo, para ali se porem em segurança.

[[v22-10-84]]

^<<v22-10-84,84>>^ Porém Jónatas queimou Azot e as cidades que estavam nos seus contornos tomou os seus despojos e pôs fogo ao templo de Dagon, queimando-o com todos os que nele se tinham refugiado.

[[v22-10-85]]

^<<v22-10-85,85>>^ Foram perto de oito mil homens os que morreram, entre os passados à espada e os consumidos pelo fogo.

[[v22-10-86]]

^<<v22-10-86,86>>^ Jónatas levantou dali o seu arraial e acampou junto de Ascalon, cujos cidadãos saíram a recebê-lo com grandes honras.

[[v22-10-87]]

^<<v22-10-87,87>>^ Depois Jónatas regressou a Jerusalém com a sua gente carregada de muitos despojos.

[[v22-10-88]]

^<<v22-10-88,88>>^ Quando o rei Alexandre soube destes sucessos, elevou ainda Jónatas a maior glória.

[[v22-10-89]]

^<<v22-10-89,89>>^ Mandou-lhe um alfinete de ouro, daqueles que se costumam dar aos parentes do rei, e deu-lhe o domínio de Acaron com todo o território.

'''

xref:022-i-macabeus/022-i-macabeus-009.adoc#v22-9-0[&#60; Capítulo Anterior] | <<v22-10-0,Topo>> | xref:022-i-macabeus/022-i-macabeus-011.adoc#v22-11-0[Próximo Capítulo &#62;]