include::./index.adoc[]

[[v22-6-0]]
=== I Macabeus, 6
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 6 de 1 Macabeus narra o confronto entre o rei Antíoco IV Epifânio e o líder judeu Judas Macabeu, e a subsequente batalha em Betzur. O capítulo também apresenta a traição de um judeu chamado Lísias, que havia sido colocado no comando das tropas do rei, mas que acabou se unindo aos macabeus. Abaixo estão cinco versículos relacionados com os temas abordados neste capítulo:
* 1 Crônicas 12:8: "Dos gaditas passaram para Davi, à fortaleza no deserto, homens valentes e destros no uso de escudo e lança; seus rostos pareciam faces de leões e eram tão ligeiros como gazelas sobre os montes." Este versículo fala sobre homens valentes e destros em batalha, o que se relaciona com a descrição dos guerreiros macabeus em 1 Macabeus 6.
* Salmos 27:3: "Ainda que um exército se acampe contra mim, não se atemorizará o meu coração; e, se estourar contra mim a guerra, ainda assim terei confiança." Este versículo fala sobre a coragem em face do perigo, e reflete a atitude dos macabeus em sua luta contra o rei Antíoco IV.
* Provérbios 11:14: "Não havendo sábia direção, cai um povo; mas na multidão de conselheiros há segurança." Este versículo enfatiza a importância da sabedoria e do conselho em tempos de crise, e é relevante para a situação dos macabeus, que procuravam orientação divina para vencer a batalha.
* Ezequiel 21:14: "Portanto, ó filho do homem, profetiza, e bate com as mãos; e dobra uma e outra vez a espada, espada de carnificina; é a espada da grande carnificina que os rodeia." Este versículo se refere à espada da destruição que virá sobre o povo de Deus, e pode ser visto como uma alusão à ameaça do rei Antíoco IV contra os judeus.
* Lucas 22:48: "Jesus, porém, lhe disse: Judas, com um beijo trais o Filho do Homem?" Este versículo se refere à traição de Judas Iscariotes contra Jesus, e pode ser visto como um paralelo à traição de Lísias contra o rei Antíoco IV. Ambos os personagens são traidores que acabam ajudando o outro lado.
****

[[v22-6-1]]

^<<v22-6-1,1>>^ Entretanto o rei Antíoco percorria as províncias superiores. Ouvindo dizer que havia na Pérsia, na (província de) Elimaida, uma cidade famosa pelas suas riquezas em prata e ouro.

[[v22-6-2]]

^<<v22-6-2,2>>^ e que havia nela um templo riquíssimo, onde estavam véus de ouro, couraças, escudos, e armas, que lá havia deixado Alexandre, rei da Macedónia, filho de Filipe, que foi o primeiro que reinou na Grécia,

[[v22-6-3]]

^<<v22-6-3,3>>^ marchou sobre ela e tentou tomá-la e saqueá-la, mas não pode, porque o seu desígnio chegou ao conhecimento dos habitantes da cidade.

[[v22-6-4]]

^<<v22-6-4,4>>^ Estes saíram a pelejar contra ele, que fugiu de lá com grande tristeza, para voltar a Babilônia.

[[v22-6-5]]

^<<v22-6-5,5>>^ Quando ainda estava na Pérsia, um mensageiro anunciou-lhe que tinha sido derrotado o seu exército enviado ao país de Judá:

[[v22-6-6]]

^<<v22-6-6,6>>^ que Lísias, tendo passado lá com um forte exército, havia sido posto em fuga pelos Judeus, os quais se tinham tornado mais fortes pelas armas, pela gente e pelos muitos despojos tomados aos exércitos derrotados;

[[v22-6-7]]

^<<v22-6-7,7>>^ que tinham destruído a abominação mandada colocar por ele sobre o altar que estava em Jerusalém, e que tinham cercado o templo de altos muros, como antes, assim como a sua cidade de Betsur.

[[v22-6-8]]

^<<v22-6-8,8>>^ Depois que o rei ouviu estas notícias, ficou cheio de terror e muito perturbado; foi para a cama e enfermou de melancolia, porque não lhe tinham sucedido as coisas como ele desejara.

[[v22-6-9]]

^<<v22-6-9,9>>^ Passou muitos dias assim, porque caía sem cessar na sua grande tristeza, e compreendeu que ia morrer.

[[v22-6-10]]

^<<v22-6-10,10>>^ Chamou, pois, todos os seus amigos e disse-lhes: O sono fugiu dos meus olhos, e vejo-me prostrado, com o coração abatido de pesares.

[[v22-6-11]]

^<<v22-6-11,11>>^ Digo a mim próprio: Quanta tribulação me oprime, em que ondas de tristeza me vejo presentemente mergulhado, eu que era bom e querido no auge do meu poder!

[[v22-6-12]]

^<<v22-6-12,12>>^ Agora, porém, lembro-me dos males que fiz em Jerusalém: não só tirei todos os utensílios de ouro e prata, que havia nela, mas ainda enviei (um exército) a exterminar sem motivo os que habitavam na Judeia.

[[v22-6-13]]

^<<v22-6-13,13>>^ Reconheço, pois, que por isso é que vieram sobre mim todos estes males; e eis que vou morrer de grande melancolia numa terra estrangeira

[[v22-6-14]]

^<<v22-6-14,14>>^ Então chamou Filipe, um dos seus amigos, e constituiu-o regente de todo o seu reino;

[[v22-6-15]]

^<<v22-6-15,15>>^ entregou-lhe o seu diadema, o seu manto real e o seu anel, com o encargo de dirigir seu filho Antíoco e de o educar para o trono.

[[v22-6-16]]

^<<v22-6-16,16>>^ E o rei Antioco morreu ali, no ano cento e quarenta e nove

[[v22-6-17]]

^<<v22-6-17,17>>^ Lísias ao saber que o rei tinha morrido, aclamou rei a Antíoco, seu filho, a quem tinha criado desde menino, e pôs-lhe o nome de Eupator.

[[v22-6-18]]

^<<v22-6-18,18>>^ Ora os que estavam na fortaleza tinham fechado a Israel nos arredores do templo, procurando sempre fazer-lhe mal e apoiar os gentios.

[[v22-6-19]]

^<<v22-6-19,19>>^ Judas resolveu destruí-los, e convocou todo o povo para os cercar.

[[v22-6-20]]

^<<v22-6-20,20>>^ Concorreram, pois, todos a cercá-los, no ano cento e cinqüenta, e fizeram balistas e outras máquinas de guerra.

[[v22-6-21]]

^<<v22-6-21,21>>^ Porém saíram alguns dos que estavam cercados, e agregaram-se a eles muitos ímpios do povo de Israel.

[[v22-6-22]]

^<<v22-6-22,22>>^ Foram ter com o rei e disseram-lhe: Até quando diferes fazer-nos justiça e vingar nossos Irmãos?

[[v22-6-23]]

^<<v22-6-23,23>>^ Resolvemo-nos a servir teu pai, a conduzir-nos pelas suas ordens, a obedecer às suas leis;

[[v22-6-24]]

^<<v22-6-24,24>>^ por esta causa os filhos do nosso povo nos põem cerco, ganharam-nos aversão, mataram de entre nós todos aqueles que encontraram e roubaram as nossas heranças.

[[v22-6-25]]

^<<v22-6-25,25>>^ Estenderam as suas mãos não sòmente sobre nós, mas ainda sobre todas as regiões vizinhas.

[[v22-6-26]]

^<<v22-6-26,26>>^ Agora eis que se aproximaram da fortaleza de Jerusalém, para se fazerem senhores dela, e fortificaram o templo e Betsur.

[[v22-6-27]]

^<<v22-6-27,27>>^ Se te não apressares a reprimi-los, farão ainda maiores males, e não poderás sujeitá-los mais.

[[v22-6-28]]

^<<v22-6-28,28>>^ O rei, quando ouviu isto, ficou irritado e convocou todos os seus amigos, os chefes do seu exército e os comandantes da cavalaria.

[[v22-6-29]]

^<<v22-6-29,29>>^ Também doutros reinos e das Ilhas marítimas lhe vieram tropas mercenárias.

[[v22-6-30]]

^<<v22-6-30,30>>^ O seu exército era de cem mil infantes, vinte mil cavaleiros e trinta e dois elefantes adestrados para a batalha.

[[v22-6-31]]

^<<v22-6-31,31>>^ Marcharam para Idumeia e acamparam em frente de Betsur. Atacaram-na durante muitos dias e construíram máquinas (de guerra); porém os sitiados fizeram uma surtida e deitaram-lhes fogo, pelejando com grande valor.

[[v22-6-32]]

^<<v22-6-32,32>>^ Judas afastou-se da fortaleza e marchou com o seu exército para Betzacaria, para defronte do acampamento do rei.

[[v22-6-33]]

^<<v22-6-33,33>>^ O rei levantou-se antes de amanhecer e fez marchar impetuosamente todas as suas tropas a caminho de Betzacaria; prepararam-se as forças para combate e tocaram as trombetas.

[[v22-6-34]]

^<<v22-6-34,34>>^ Mostraram aos elefantes sumo de uva e de amoras para os incitarem à peleja.

[[v22-6-35]]

^<<v22-6-35,35>>^ Distribuíram estes animais pelas falanges, pondo em volta de cada elefante mil homens armados de cotas de malha e de capacetes de bronze; quinhentos cavaleiros escolhidos tinham ordem de se conservar sempre junto de cada animal

[[v22-6-36]]

^<<v22-6-36,36>>^ Estes precediam o animal para onde quer que ele fosse: para toda a parte para onde ele ia, iam eles, sem jamais se afastarem.

[[v22-6-37]]

^<<v22-6-37,37>>^ Havia também sobre cada elefante uma forte torre de, madeira, bem segura e protegida ,por máquinas de guerra; em cada torre iam homens valentes, que pelejavam, além do seu cornaça.

[[v22-6-38]]

^<<v22-6-38,38>>^ Foi posto o resto da cavalaria dum e doutro flanco, em dois troços, para açoutar o inimigo e proteger as falanges.

[[v22-6-39]]

^<<v22-6-39,39>>^ Quando o sol brilhou sobre os escudos de ouro e de bronze, com o seu reflexo resplandeceram os montes, resplandeceram como fachos de fogo.

[[v22-6-40]]

^<<v22-6-40,40>>^ Uma parte do exército do rei avançou pelo alto dos montes, e outra pelas planícies, caminhando com precaução e ordem.

[[v22-6-41]]

^<<v22-6-41,41>>^ Todos estavam espantados da grita que fazia esta multidão de soldados, do ruído da marcha de tanta gente e do trincolejar das suas armas, porque era um exército multo grande e forte.

[[v22-6-42]]

^<<v22-6-42,42>>^ Judas aproximou-se com o seu exército para dar a batalha, e morreram do exército do rei seiscentos homens.

[[v22-6-43]]

^<<v22-6-43,43>>^ Então Eleazar, por sobrenome Abaran, viu um dos elefantes todo coberto de couraças reais, mais alto que todos os outros. Supondo que o rei iria sobre ele,

[[v22-6-44]]

^<<v22-6-44,44>>^ sacrificou a sua vida para livrar o seu povo e adquirir um nome imortal.

[[v22-6-45]]

^<<v22-6-45,45>>^ Correu a ele animosamente pelo meio da falange, matando à direita e à esquerda; caíam, duma e doutra parte, à força dos seus golpes, todos os que se lhe punham diante.

[[v22-6-46]]

^<<v22-6-46,46>>^ Chegou até aos pés do elefante, meteu-se debaixo dele e matou-o; (o elefante) caiu em terra sobre ele, e (Eleazar) morreu ali.

[[v22-6-47]]

^<<v22-6-47,47>>^ Mas (os Judeus), vendo a força do rei e o ímpeto do seu exército, retiraram-se do combate.

[[v22-6-48]]

^<<v22-6-48,48>>^ Então o exército do rei marchou contra eles para a banda de Jerusalém, dirigindo-se (assim) o rei contra a Judeia e o monte Sião

[[v22-6-49]]

^<<v22-6-49,49>>^ O rei fez paz com os que estavam em Betsur, e eles saíram da cidade, porque não tinham já que comer, para suportar o cerco, pois era o ano sabático da terra.

[[v22-6-50]]

^<<v22-6-50,50>>^ Assim o rei tomou Betsur e pôs nela uma guarnição que a guardasse.

[[v22-6-51]]

^<<v22-6-51,51>>^ Depois fez marchar as suas tropas paira o lugar que cercou durante muitos dias; pôs ali balistas, máquinas, engenhos para lançar fogo, trabucos para atirar pedras e arremessar dardos, e escorpiões para despedir setas, e fundas.

[[v22-6-52]]

^<<v22-6-52,52>>^ (Os sitiados) fizeram também máquinas contra as máquinas dos inimigos e pelejaram durante muitos dias.

[[v22-6-53]]

^<<v22-6-53,53>>^ Mas não havia víveres na cidade, por ser o ano sétimo (ou sabático) e porque os refugiados na Judeia, fugidos aos gentios, tinham consumido o resto das provisões de reserva.

[[v22-6-54]]

^<<v22-6-54,54>>^ Ficaram poucos homens de guarda aos lugares santos, porque os tinha apertado a fome. (Os outros) dispersaram-se cada um para a sua terra.

[[v22-6-55]]

^<<v22-6-55,55>>^ Entretanto Filipe, a quem o rei Antíoco, vivendo ainda, tinha leito aio do seu filho Antíoco, para o fazer reinar depois dele,

[[v22-6-56]]

^<<v22-6-56,56>>^ havia chegado da Pérsia Média com o exército que acompanhara o rei, e preparava-se para tomar o governo dos negócios do reino.

[[v22-6-57]]

^<<v22-6-57,57>>^ Ao saber disto, Lísias tratou apressadamente de se retirar, dizendo ao rei e aos generais do seu exército: Nós vamo-nos consumindo aqui todos os dias, os víveres que temos são poucos, a praça que sitiamos está bem fortificada, e devemos ocupar-nos dos negócios do reino.

[[v22-6-58]]

^<<v22-6-58,58>>^ Demos, pois, agora a mão a estes homens, façamos paz com eles e com toda a sua nação;

[[v22-6-59]]

^<<v22-6-59,59>>^ permitamos-lhes que vivam segundo as suas leis, como dantes, porque, por causa das suas leis, que abolimos, é que eles se irritaram e fizeram tudo isto.

[[v22-6-60]]

^<<v22-6-60,60>>^ Esta proposta agradou ao rei e aos chefes; pelo que mandou tratar de paz com os Judeus, e estes aceitaram.

[[v22-6-61]]

^<<v22-6-61,61>>^ O rei e os chefes lha confirmaram com juramento, e eles saíram da fortaleza que defendiam.

[[v22-6-62]]

^<<v22-6-62,62>>^ Então o rei subiu ao monte Sião e viu as suas fortificações, mas quebrou o juramento que tinha feito, mandando derribar o muro que estava em roda.

[[v22-6-63]]

^<<v22-6-63,63>>^ Dali partiu a toda a pressa e voltou para Antioquia, de que Filipe se tinha apoderado. Pelejou contra ele e recobrou a cidade, à força.

'''

xref:022-i-macabeus/022-i-macabeus-005.adoc#v22-5-0[&#60; Capítulo Anterior] | <<v22-6-0,Topo>> | xref:022-i-macabeus/022-i-macabeus-007.adoc#v22-7-0[Próximo Capítulo &#62;]