include::./index.adoc[]

[[v22-3-0]]
=== I Macabeus, 3
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* 1 Macabeus 3 narra as primeiras vitórias de Judas Macabeu contra as forças gregas, que tentavam impor sua cultura e religião ao povo judeu. O capítulo descreve a organização do exército de Judas e suas estratégias de batalha. A seguir estão cinco versículos relacionados com os temas abordados em 1 Macabeus 3:
* Deuteronômio 20:4: "Pois o Senhor, o seu Deus, os acompanhará e lutará por vocês contra os seus inimigos, para dar a vitória a vocês." Este versículo fala sobre a ajuda divina na luta contra os inimigos e mostra a importância da fé em Deus em tempos de guerra.
* Josué 1:9: "Não fui eu que lhe ordenei? Seja forte e corajoso! Não se apavore nem desanime, pois o Senhor, o seu Deus, estará com você por onde você andar." Essas palavras de Deus a Josué mostram a importância da coragem e da confiança em Deus na luta contra inimigos poderosos.
* 2 Crônicas 20:15: "Não tenham medo nem desanimem por causa desse exército vasto. Pois a batalha não é de vocês, mas de Deus." Essa passagem mostra que Deus é o verdadeiro comandante em tempos de guerra e que a vitória pertence a Ele.
* Provérbios 21:31: "O cavalo é preparado para o dia da batalha, mas a vitória vem do Senhor." Essa passagem mostra a importância da preparação para a guerra, mas também que a vitória depende da ajuda divina.
* Efésios 6:11: "Vistam toda a armadura de Deus, para poderem ficar firmes contra as ciladas do diabo." Essa passagem fala sobre a importância da proteção divina na batalha espiritual e mostra que a luta contra as forças do mal requer uma armadura espiritual.
****

[[v22-3-1]]

^<<v22-3-1,1>>^ Levantou-se em lugar dele seu filho Judas, que tinha o sobrenome de Macabeu.

[[v22-3-2]]

^<<v22-3-2,2>>^ Todos os seus irmãos o ajudavam, assim como todos aqueles que se tinham unido a seu pai, e pelejavam com alegria em defesa de Israel.

[[v22-3-3]]

^<<v22-3-3,3>>^ Dilatou a glória do seu povo, revestiu-se de couraça como um gigante, cingiu-se com as suas armas e travou combates, cobrindo todo o acampamento com a sua espada.

[[v22-3-4]]

^<<v22-3-4,4>>^ Tornou-se semelhante a um leão nas suas acções, a um leãozinho que ruge sobre a presa.

[[v22-3-5]]

^<<v22-3-5,5>>^ Perseguiu os maus, buscando-os por toda a parte, e queimou os que perturbavam o seu povo.

[[v22-3-6]]

^<<v22-3-6,6>>^ Os seus inimigos retiraram-se pelo temor que lhe tinham, todos os obreiros da iniquidade se turbaram, e a sua mão conduziu pròsperamente a salvação (do povo).

[[v22-3-7]]

^<<v22-3-7,7>>^ Exasperou muitos reis, mas alegrou Jacob, e a sua memória será eternamente bem-dita.

[[v22-3-8]]

^<<v22-3-8,8>>^ Percorreu as cidades de Judá, lançou fora delas os ímpios e apartou a ira (de Deus) de cima de Israel.

[[v22-3-9]]

^<<v22-3-9,9>>^ Tornou-se célebre até às extremidades da terra, e reuniu os que estavam a ponto de perecer.

[[v22-3-10]]

^<<v22-3-10,10>>^ (Neste tempo) Apolónio juntou as nações e levantou da Samaria um grande exército para pelejar contra Israel

[[v22-3-11]]

^<<v22-3-11,11>>^ Judas soube-o, saiu-lhe ao encontro, derrotou-o e matou-o; muitos (inimigos) caíram feridos, e o resto fugiu.

[[v22-3-12]]

^<<v22-3-12,12>>^ Tomou os despojos deles e a espada de Apolónio, com a qual, daí por diante, pelejava sempre.

[[v22-3-13]]

^<<v22-3-13,13>>^ Seron, general do exército da Síria, ouviu dizer que Judas tinha reunido uma (grande) multidão, congregado consigo gente fiel, que conduzia ao combate.

[[v22-3-14]]

^<<v22-3-14,14>>^ Disse: Alcançarei grande reputação e ficarei com grande glória no meu reino, combatendo Judas e os que estão com ele, que desprezam as ordens do rei.

[[v22-3-15]]

^<<v22-3-15,15>>^ Preparou-se, pois, para a guerra. Um forte exército de ímpios subiu com ele, servindo-lhe de auxílio, para tomarem vingança dos filhos de Israel.

[[v22-3-16]]

^<<v22-3-16,16>>^ Quando avançaram até Betoron, Judas saiu-lhes ao encontro com pouca gente.

[[v22-3-17]]

^<<v22-3-17,17>>^ Os seus companheiros, logo que viram marchar contra eles o exército inimigo, disseram a Judas: Como poderemos nós, sendo tão poucos e vindo fatigados do Jejum de hoje, pelejar contra um tão poderoso exército?

[[v22-3-18]]

^<<v22-3-18,18>>^ Judas disse-lhes; É coisa fácil virem a cair os muitos nas mãos dos poucos; pois, para o Deus do céu, não há diferença entre salvar com um grande número ou com um pequeno,

[[v22-3-19]]

^<<v22-3-19,19>>^ porque a vitória na guerra não depende da grandeza dos exércitos, mas da força que vem do céu.

[[v22-3-20]]

^<<v22-3-20,20>>^ Eles vêm contra nós com uma grande multidão de gente soberba e insolente, para nos perderem a nós, às nossas mulheres e aos nossos filhos, e para se enriquecerem com os nossos despojos,

[[v22-3-21]]

^<<v22-3-21,21>>^ mas nós havemos de pelejar pelas nossas vidas e pelas nossas leis.

[[v22-3-22]]

^<<v22-3-22,22>>^ O mesmo Senhor quebrará todos os seus esforços diante da nossa face; por isso não temais.

[[v22-3-23]]

^<<v22-3-23,23>>^ Logo que cessou de falar, lançou-se Judas de repente sobre eles, e foi derrotado Seron com o seu exército.

[[v22-3-24]]

^<<v22-3-24,24>>^ Judas perseguiu-o na descida de Betoron Até à planície. Morreram deles (Sírios) oitocentos homens; os outros fugiram para o país dos Filisteus.

[[v22-3-25]]

^<<v22-3-25,25>>^ Então o terror e o medo, que Infundiam Judas e os seus irmãos, espalharam-se por todas as nações circunvizinhas;

[[v22-3-26]]

^<<v22-3-26,26>>^ a fama do seu nome chegou até ao rei, e todos os povos falavam das batalhas de Judas.

[[v22-3-27]]

^<<v22-3-27,27>>^ Logo que o rei Antioco ouviu estas novas, concebeu grande ira e mandou reunir todas as tropas do seu reino, de que formou um exército poderosíssimo.

[[v22-3-28]]

^<<v22-3-28,28>>^ Abriu o seu erário e deu no exército o soldo de um ano, mandando-lhes que estivessem prestes para tudo.

[[v22-3-29]]

^<<v22-3-29,29>>^ Mas viu que lhe faltava o dinheiro de seus tesouros e que rendiam pouco os tributos do país (de Judá), por causa das discórdias e misérias que ele mesmo tinha ocasionado, querendo abolir as leis que estavam em uso desde os tempos antigos.

[[v22-3-30]]

^<<v22-3-30,30>>^ Temeu, portanto, não ter, como uma ou duas vezes antes acontecera, para os gastos e donativos, que anteriormente fazia com mão larga, e em que tinha excedido os reis seus predecessores.

[[v22-3-31]]

^<<v22-3-31,31>>^ Consternado em extremo no seu interior, resolveu ir à Pérsia, a recolher os tributos daquelas províncias e ajuntar muito dinheiro.

[[v22-3-32]]

^<<v22-3-32,32>>^ Deixou Lísias, homem nobre da família real, para que tivesse cuidado dos negócios do reino, desde o rio Eufrates até aos confins do Egipto,

[[v22-3-33]]

^<<v22-3-33,33>>^ e para que cuidasse da educação de seu filho Antioco, até ele voltar.

[[v22-3-34]]

^<<v22-3-34,34>>^ Confiou-lhe metade do exército, com os elefantes, e deu-lhe as suas ordens acerca de tudo, particularmente sobre o que dizia respeito aos habitantes da Judeia e de Jerusalém:

[[v22-3-35]]

^<<v22-3-35,35>>^ mandou-lhe que enviasse contra eles um exército, para destruir e exterminar o poder de Israel e os restos de Jerusalém, para apagar deste lugar até a sua memória,

[[v22-3-36]]

^<<v22-3-36,36>>^ e que estabelecesse no seu território habitantes doutras nações, repartindo por sorte as suas terras.

[[v22-3-37]]

^<<v22-3-37,37>>^ O rei tomou a outra metade do exército, que lhe restava, e partiu de Antioquia, capital do seu reino, no ano cento e quarenta e sete; passou o rio Eufrates e atravessou as províncias superiores.

[[v22-3-38]]

^<<v22-3-38,38>>^ Lísias escolheu Ptolomeu, filho de Dorimeno, e Nicanor e Górgias, que eram chefes valorosos entre os amigos do rei,

[[v22-3-39]]

^<<v22-3-39,39>>^ e enviou com eles quarenta mil homens a pé e sete mil cavaleiros, para que fossem à terra de Judá e a assolassem, conforme a ordem do rei.

[[v22-3-40]]

^<<v22-3-40,40>>^ Eles, pois, marcharam com todas as suas tropas e chegaram lá, acampando na planície do território de Emaús.

[[v22-3-41]]

^<<v22-3-41,41>>^ Quando os mercadores das províncias vizinhas ouviram a noticia da chegada deles, tomaram muita prata, muito ouro e criados, e foram ao acampamento, com o fim de comprarem os filhos de Israel para escravos. Os exércitos da Síria se ajuntaram a eles, como também os de outras nações.

[[v22-3-42]]

^<<v22-3-42,42>>^ Então Judas e seus irmãos, vendo que os males se tinham multiplicado e que os exércitos se aproximavam das suas fronteiras, e tendo noticia das ordens que o rei tinha dado para destruir e exterminar o povo,

[[v22-3-43]]

^<<v22-3-43,43>>^ disseram uns para os outros: Levantemos o nosso povo do seu abatimento e pelejemos pela nossa nação e pelo santuário.

[[v22-3-44]]

^<<v22-3-44,44>>^ Fez-se a convocação de toda a gente, a fim de se prepararem para a peleja e a fim de fazerem oração (ao Senhor) e implorarem a sua misericórdia ,e piedade.

[[v22-3-45]]

^<<v22-3-45,45>>^ Ora Jerusalém não estava então habitada, mas parecia um deserto: entre seus filhos nenhum havia que entrasse e saísse dela; o santuário estava pisado aos pés; os filhos dos estrangeiros ocupavam a fortaleza, a qual servia de habitação aos gentios; foi desterrada de Jacob toda a alegria, não se ouvindo já nem a flauta nem a harpa.

[[v22-3-46]]

^<<v22-3-46,46>>^ Eles, pois, juntaram-se e foram para Masfa, que está defronte de Jerusalém, porque outrora havia em Masfa um lugar de oração para Israel.

[[v22-3-47]]

^<<v22-3-47,47>>^ Jejuaram aquele dia, vestiram-se de cilícios, puseram cinza sobre a sua cabeça e rasgaram as suas vestes.

[[v22-3-48]]

^<<v22-3-48,48>>^ Abriram o livro da lei, para o consultar, assim como fazem os gentios com as imagens dos seus falsos deuses.

[[v22-3-49]]

^<<v22-3-49,49>>^ Trouxeram os ornamentos sacerdotais, as primícias e os dízimos, e fizeram vir os nazarenos, que tinham cumprido o tempo (do seu voto);

[[v22-3-50]]

^<<v22-3-50,50>>^ depois gritaram em alta voz para o céu, dizendo: Que havemos de fazer nós destas coisas, e para onde havemos de conduzir estes homens?

[[v22-3-51]]

^<<v22-3-51,51>>^ O teu santuário foi pisado aos pés e manchado; os teus sacerdotes estão em luto e em humilhação

[[v22-3-52]]

^<<v22-3-52,52>>^ juntaram-se as nações contra nós para nos destruírem; tu sabes (bem) os seus desígnios contra nós.

[[v22-3-53]]

^<<v22-3-53,53>>^ Como poderemos subsistir diante da sua face, se tu, ó Deus, nos não assistires?

[[v22-3-54]]

^<<v22-3-54,54>>^ Então fizeram retinir as trombetas com grande estrondo.

[[v22-3-55]]

^<<v22-3-55,55>>^ Depois disto Judas nomeou chefes do povo; (chefes) de mil homens, de cem, de cinqüenta e de dez.

[[v22-3-56]]

^<<v22-3-56,56>>^ E disse aos que acabavam de edificar casas, de receber mulheres, de plantar vinhas, e aos que eram tímidos, que voltassem para suas casas, conforme a lei.

[[v22-3-57]]

^<<v22-3-57,57>>^ Feito isto, levantaram o acampamento e foram acampar perto de Emaús, do lado do meio-dia.

[[v22-3-58]]

^<<v22-3-58,58>>^ Judas disse-lhes: Preparai-vos, sede homens de valor e estai prontos para amanha, de manhã, pelejardes contra estas nações, que se juntaram contra nós para nos destruírem e às nossas coisas santas,

[[v22-3-59]]

^<<v22-3-59,59>>^ porque melhor nos é morrer em combate, do que ver os males do nosso povo e do nosso santuário.

[[v22-3-60]]

^<<v22-3-60,60>>^ Mas cumpra-se o que for vontade (de Deus) no céu.

'''

xref:022-i-macabeus/022-i-macabeus-002.adoc#v22-2-0[&#60; Capítulo Anterior] | <<v22-3-0,Topo>> | xref:022-i-macabeus/022-i-macabeus-004.adoc#v22-4-0[Próximo Capítulo &#62;]