include::./index.adoc[]

[[v6-13-0]]
=== Josué, 13
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 13 de Josué descreve como Deus ordenou que Josué distribuísse a terra de Canaã entre as tribos de Israel. Esse capítulo apresenta a lista das terras que foram conquistadas e que deveriam ser distribuídas entre as tribos. Abaixo estão cinco versículos relacionados com os temas abordados em Josué 13.
* Números 33:53: "E desapossareis os moradores da terra, e habitareis nela; porque eu vos dei a terra para a possuirdes." Esse versículo fala da promessa de Deus de dar a terra de Canaã para os israelitas possuírem. Essa promessa foi cumprida na conquista de Canaã e na distribuição das terras entre as tribos.
* Ezequiel 47:13: "Assim diz o Senhor Deus: Este é o limite segundo o qual repartireis a terra em herança às doze tribos de Israel; José terá duas partes." Esse versículo fala da divisão da terra de Canaã entre as doze tribos de Israel. Josué recebeu a ordem de distribuir a terra de acordo com as instruções de Deus.
* Deuteronômio 1:8: "Eis que vos dei a terra; entrai e possuí-a, como o Senhor, Deus de vossos pais, vos disse; não temais, nem vos atemorizeis." Esse versículo fala da ordem de Deus para que os israelitas entrassem na terra de Canaã e a possuíssem. Essa ordem foi cumprida por Josué e seu exército, e as terras foram distribuídas entre as tribos.
* Números 34:17: "Estes são os nomes dos homens que hão de repartir a terra entre vós: Eleazar, o sacerdote, e Josué, filho de Num." Esse versículo fala da escolha de Josué para liderar a distribuição da terra de Canaã entre as tribos de Israel. Josué foi o líder escolhido por Deus para essa importante tarefa.
* Deuteronômio 33:21: "E de Naftali disse: Naftali, fartura de satisfação, e cheio da bênção do Senhor; toma posse do mar e do sul." Esse versículo fala da bênção de Deus sobre a tribo de Naftali. Na distribuição da terra de Canaã, essa tribo recebeu uma porção generosa de terras.
****

[[v6-13-1]]

^<<v6-13-1,1>>^ Josué estava velho, avançado em anos, e o Senhor disse-lhe: Tu estás velho, de muita idade, e resta um dilatadíssimo espaço de terra, que ainda não foi repartido por sorte (nem conquistado),

[[v6-13-2]]

^<<v6-13-2,2>>^ a saber: o território dos Filisteus, toda a terra de Gessuri,

[[v6-13-3]]

^<<v6-13-3,3>>^ desde o rio turvo, que rega o Egipto, até aos confins de Acaron, para o norte, que deve ser reputada terra de Canaan; os (territórios pertencentes aos) cinco príncipes dos Filisteus: o de Gaza, o de Azoto, o de Ascalon, o de Get e o de Acaron; (ver nota)

[[v6-13-4]]

^<<v6-13-4,4>>^ os Heveus, ao meio-dia; toda a terra de Canaan, e Maara dos Sidónios, até Afeca e aos confins do Amorreu;

[[v6-13-5]]

^<<v6-13-5,5>>^ a terra dos Gebalitas e todo o território do Líbano, a oriente, desde Baalad na raiz do monte Hermon, até à entrada de Hamath;

[[v6-13-6]]

^<<v6-13-6,6>>^ a terra, daqueles que habitam na Montanha, desde o Líbano até às águas de Maserefot, todos os Sidónios. Sou eu que os hei-de exterminar, diante dos filhos de Israel. Entre pois (todo este terreno) na parte da herança de Israel, como eu te ordenei.

[[v6-13-7]]

^<<v6-13-7,7>>^ E agora reparte a terra, que devem possuir as nove tribos e a meia tribo de Manassés;

[[v6-13-8]]

^<<v6-13-8,8>>^ a outra meia tribo e as tribos de Buben e Gad tomaram já posse da terra, que lhes deu Moisés, servo do Senhor, na outra banda do Jordão, para o oriente,

[[v6-13-9]]

^<<v6-13-9,9>>^ desde Aroer, que está situada na margem da torrente de Arnon e desde a cidade que está no meio do vale, toda a campina de Medaba, até Dibon;

[[v6-13-10]]

^<<v6-13-10,10>>^ e todas as cidades de Seon, rei dos Amorreus, que reinou em Hesebon, até aos confins dos filhos de Amon;

[[v6-13-11]]

^<<v6-13-11,11>>^ e Galaad e os territórios de Gessuri e de Macati, todo o monte Hermon, todo o Basan, até Saleca,

[[v6-13-12]]

^<<v6-13-12,12>>^ todo o reino de Og em Basan, o qual reinou em Astarot e em Edrai, e foi o resto dos Befains que ficaram, aos quais Moisés derrotou e destruíu.

[[v6-13-13]]

^<<v6-13-13,13>>^ Os filhos de Israel não quiseram exterminar os de Gessuri e de Macati, e assim eles ficaram habitando no meio de Israel até ao dia de hoje.

[[v6-13-14]]

^<<v6-13-14,14>>^ À tribo de Levi porém (Moisés) não deu possessão alguma, porque os sacrifícios e as vítimas do Senhor Deus de Israel são a sua herança, como (o Senhor) lho tinha dito.

[[v6-13-15]]

^<<v6-13-15,15>>^ Moisés havia dado a sua parte à tribo dos filhos de Ruben, segundo as suas famílias.

[[v6-13-16]]

^<<v6-13-16,16>>^ Os seus confins foram desde Aroer, que está situada sobre a margem da torrente de Arnon, e desde a cidade que está no meio do vale da mesma torrente, toda a planície que vai até Medaba,

[[v6-13-17]]

^<<v6-13-17,17>>^ e Hesebon com todas as suas aldeias, que estão na planície; e também Dibon, Bamotbaal, a cidade de Baalmaou,

[[v6-13-18]]

^<<v6-13-18,18>>^ Jassa, Cedimot, Mefaat,

[[v6-13-19]]

^<<v6-13-19,19>>^ Cariataim, Sabama, Saratasar no monte do vale,

[[v6-13-20]]

^<<v6-13-20,20>>^ Betofogor e Asedot, Fasga e Betiesimot,

[[v6-13-21]]

^<<v6-13-21,21>>^ todas as cidades da planície, e todos os reinos de Seon, rei dos Amorreus, que reinou em Hesebon, a quem Moisés derrotou com os príncipes de Madiang: Hevi, Recem, Sur, Hur, Rebe, tributários de Seon, que habitavam aquele país.

[[v6-13-22]]

^<<v6-13-22,22>>^ Os filhos de Israel mataram também à espada, como a todos os outros, o adivinho Balaão filho de Beor.

[[v6-13-23]]

^<<v6-13-23,23>>^ Assim, o rio Jordão ficou sendo o limite dos filhos de Ruben. Estas são as cidades e aldeias que possuem os rubenitas, segundo as suas famílias.

[[v6-13-24]]

^<<v6-13-24,24>>^ Moisés deu também à tribo de Gad e aos seus filhos, segundo as suas famílias, a terra que deviam possuir, que é a seguinte:

[[v6-13-25]]

^<<v6-13-25,25>>^ Jazer, todas as cidades de Galaad, metade do país dos filhos de Amon, até Aroer, que está defronte de Raba,

[[v6-13-26]]

^<<v6-13-26,26>>^ desde Hesebon até Ramot, Masfe e Betonim, e desde Manain até aos confins de Dabir;

[[v6-13-27]]

^<<v6-13-27,27>>^ e, no vale, Betaran, Betnemra, Socot e Safon, resto do reino de Seon, rei de Hesebon; o Jordão e os seus territórios até à extremidade do mar de Cenerot, na outra banda do Jordão para o nascente.

[[v6-13-28]]

^<<v6-13-28,28>>^ Esta é a parte, as cidades e aldeias dos filhos de Gad, segundo as suas famílias.

[[v6-13-29]]

^<<v6-13-29,29>>^ Deu também à meia tribo de Manassés, aos seus filhos, segundo as suas famílias, a sua parte,

[[v6-13-30]]

^<<v6-13-30,30>>^ a qual compreendia, começando em Manain, todo o Basan, e todos os reinos de Og, rei de Basan, e todas as aldeias de Jair, que estão em Basan, (ao todo) sessenta povoações;

[[v6-13-31]]

^<<v6-13-31,31>>^ metade de Galaad, e Astarot e Edrai, cidades do reino de Og em Basan; (deu isto) aos filhos de Maquir, filho de Manassés, isto é, à metade dos filhos de Maquir, segundo as suas famílias.

[[v6-13-32]]

^<<v6-13-32,32>>^ Estas são as partes que Moisés distribuiu nas campinas de Moab, na outra banda do Jordão, defronte de Jericó, para o nascente.

[[v6-13-33]]

^<<v6-13-33,33>>^ Porém à tribo de Levi não deu possessão alguma, porque o Senhor Deus de Israel é a sua herança, como (o Senhor) lho tinha dito.

'''

xref:006-josue/006-josue-012.adoc#v6-12-0[&#60; Capítulo Anterior] | <<v6-13-0,Topo>> | xref:006-josue/006-josue-014.adoc#v6-14-0[Próximo Capítulo &#62;]