include::./index.adoc[]

[[v6-19-0]]
=== Josué, 19
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 19 de Josué trata da divisão da terra de Canaã entre as tribos de Israel. Cada tribo recebe uma porção de território como herança, incluindo cidades e vilas para habitar. O capítulo descreve em detalhes a porção dada a cada tribo e as cidades incluídas em cada porção.
* Deuteronômio 19:14: "Não remova os marcos do seu próximo, que os antepassados estabeleceram em sua herança que você receberá na terra que o Senhor, seu Deus, está dando a você para possuir." Esse versículo fala sobre a importância de respeitar os limites de propriedade estabelecidos pelos antepassados, o que é relevante para o capítulo 19 de Josué, onde as tribos recebem suas porções de terra como herança.
* Levítico 25:23: "A terra não pode ser vendida em perpetuidade, porque a terra é minha; vocês são estrangeiros e peregrinos comigo." Este versículo afirma que a terra pertence a Deus e não pode ser vendida em perpetuidade, o que reforça a ideia de que as tribos de Israel receberam sua porção de terra como uma herança de Deus em Josué 19.
* Isaías 54:2-3: "Alargue o lugar da sua tenda, estenda bem as cortinas da sua tenda, não segure nada; estique suas cordas, fortaleça suas estacas. Porque você se espalhará para a direita e para a esquerda; sua posteridade possuirá nações e fará com que as cidades desertas sejam habitadas." Esse versículo fala sobre a expansão e o crescimento, o que é relevante para o capítulo 19 de Josué, onde as tribos de Israel recebem suas porções de terra como uma herança e começam a estabelecer suas cidades e vilas.
* Números 26:52-53: "O Senhor falou a Moisés, dizendo: 'A esses será dividida a terra em herança, de acordo com o número dos nomes. A cada um será dada a sua herança de acordo com o que foi determinado pelos sortes.'" Este versículo fala sobre a divisão da terra de acordo com o número de pessoas em cada tribo, o que é relevante para o capítulo 19 de Josué, onde as tribos de Israel recebem suas porções de terra como herança.
* Deuteronômio 3:18-20: "Eu vos ordenei naquele tempo, dizendo: O Senhor, vosso Deus, vos deu esta terra para possuí-la; todos os seus homens de guerra passarão armados adiante de seus irmãos, os filhos de Israel. Apenas as mulheres, as crianças e os rebanhos, e tudo o que houver na cidade, todas as suas presas, vocês tomarão para si; e comerás o espólio dos teus inimigos que o Senhor, teu Deus, te deu." Esse versículo fala sobre a ordem de Deus para os homens de guerra de Israel tomarem a terra de seus inimigos e possuí-la, o que é relevante para o capítulo 19 de Josué.
****

[[v6-19-1]]

^<<v6-19-1,1>>^ Caiu a segunda sorte aos filhos de Simeão, segundo suas famílias. A herança

[[v6-19-2]]

^<<v6-19-2,2>>^ deles foi no meio da possessão dos filhos de Judá: Bersabec, Sabee, Molada,

[[v6-19-3]]

^<<v6-19-3,3>>^ Hasersual, Bala, Asem,

[[v6-19-4]]

^<<v6-19-4,4>>^ Eltolad, Betul, Harma,

[[v6-19-5]]

^<<v6-19-5,5>>^ Siceleg, Betmarcabot, Hasersusa,

[[v6-19-6]]

^<<v6-19-6,6>>^ Betlebaot e Saroen: treze cidades com as suas aldeias.

[[v6-19-7]]

^<<v6-19-7,7>>^ Ain, Remon, Atar e Asan: quatro cidades com as suas aldeias,

[[v6-19-8]]

^<<v6-19-8,8>>^ assim como todos os lugarejos dos arredores desta cidades até Baalat Beer, que é a Ramat do meio-dia. Esta é a herança dos filhos de Simeão, segundo as suas famílias,

[[v6-19-9]]

^<<v6-19-9,9>>^ na possessão e no território dos filhos de Judá, porque era grande demais (para os filhos de Judá) e, por isso, os filhos de Simeão tiveram a sua possessão no meio da herança daqueles.

[[v6-19-10]]

^<<v6-19-10,10>>^ A terceira sorte caiu aos filhos de Zabulon, segundo as suas famílias. A fronteira da sua herança estende-se até Sarid;

[[v6-19-11]]

^<<v6-19-11,11>>^ sobe para ocidente, até Merala, e chega a Debaset, até à torrente, que está defronte de Jeconan;

[[v6-19-12]]

^<<v6-19-12,12>>^ volta de Sarid para o nascente até aos confins de Ceselettabor; avança a Daberet, e sobe para Jafie;

[[v6-19-13]]

^<<v6-19-13,13>>^ dali passa até ao lado oriental de Get-hefer e de Tacasin e estende-se até ao Remon, Amtar e Noa;

[[v6-19-14]]

^<<v6-19-14,14>>^ dá volta, pelo norte, para Haraton, e termina no vale de Jeftael,

[[v6-19-15]]

^<<v6-19-15,15>>^ Catet, Naalol, Semeron, Jerala e Belém: doze cidades com as suas aldeias.

[[v6-19-16]]

^<<v6-19-16,16>>^ Esta é a herança da tribo dos filhos de Zabulon, segundo as suas famílias, com as suas cidades e aldeias.

[[v6-19-17]]

^<<v6-19-17,17>>^ A quarta sorte caiu a Issacar, segundo as suas famílias.

[[v6-19-18]]

^<<v6-19-18,18>>^ E a sua herança foi: Jezrael, Casalot, Suném,

[[v6-19-19]]

^<<v6-19-19,19>>^ Hafaraim, Seon, Anaarat,

[[v6-19-20]]

^<<v6-19-20,20>>^ Rabot, Cesion, Abes,

[[v6-19-21]]

^<<v6-19-21,21>>^ Ramet, Enganim, Enada e Betfeses.

[[v6-19-22]]

^<<v6-19-22,22>>^ A sua fronteira chega até ao Tabor e Saesima e Betsames, e termina no Jordão: dezasseis cidades com as suas aldeias.

[[v6-19-23]]

^<<v6-19-23,23>>^ Esta é a herança dos filhos de Issacar, segundo as suas famílias, com as suas cidades e aldeias.

[[v6-19-24]]

^<<v6-19-24,24>>^ A quinta sorte caiu à tribo dos filhos de Aser, segundo as suas famílias.

[[v6-19-25]]

^<<v6-19-25,25>>^ O seu território foi: Halcat, Cali, Beten, Axaf,

[[v6-19-26]]

^<<v6-19-26,26>>^ Elmelec, Amaad e Messal; a fronteira chega até ao Carmelo do mar e a Sior e a Labanat;

[[v6-19-27]]

^<<v6-19-27,27>>^ volta pelo oriente para a banda de Betdagon, passa por Zabulon e pelo vale de Jeftael, para o norte, até Betemee e Neiel; estende-se pela esquerda até Cabul,

[[v6-19-28]]

^<<v6-19-28,28>>^ Abran, Roob, Hamon e Cana, até Sidónia, a grande;

[[v6-19-29]]

^<<v6-19-29,29>>^ volta para Horma até à fortíssima cidade de Tiro, e até Hosa; e termina no mar, perto do território de Achziba;

[[v6-19-30]]

^<<v6-19-30,30>>^ (abrange também) Ama, Afec e Boob: vinte e duas e cidades com as suas aldeias.

[[v6-19-31]]

^<<v6-19-31,31>>^ Esta é a herança dos filhos de Aser, segundo as suas famílias, e estas são as suas cidades e aldeias.

[[v6-19-32]]

^<<v6-19-32,32>>^ A sexta sorte caiu aos filhos de Neftali, segundo as suas famílias.

[[v6-19-33]]

^<<v6-19-33,33>>^ A sua fronteira começa em Helef e Elon, vai a Saananim e a Adami, chamada também Neceb, e a Jebnael até Lecum, e avança até ao Jordão;

[[v6-19-34]]

^<<v6-19-34,34>>^ volta para o ocidente até Azanottabor, dali estende-se até Hucuca, passa por Zabulon, pela parte do meio-dia, por Aser, pelo ocidente, e por Judá para o Jordão, pelo oriente.

[[v6-19-35]]

^<<v6-19-35,35>>^ Suas cidades fortificadíssimas (são) Assedim, Ser, Emat, Becat, Ceneret,

[[v6-19-36]]

^<<v6-19-36,36>>^ Edema, Arama, Asor,

[[v6-19-37]]

^<<v6-19-37,37>>^ Cedes, Edrai, Enasor,

[[v6-19-38]]

^<<v6-19-38,38>>^ Jeron, Magdalel, Horem, Betanat e Betsames: dezanove cidades com as suas aldeias.

[[v6-19-39]]

^<<v6-19-39,39>>^ Esta é a herança da tribo dos filhos de Neftali, segundo as suas famílias, e estas são as suas cidades e aldeias.

[[v6-19-40]]

^<<v6-19-40,40>>^ A sétima sorte caiu à tribo dos filhos de Dan, segundo as suas famílias.

[[v6-19-41]]

^<<v6-19-41,41>>^ O limite da sua herança compreendia Sara, Estaol, Hirsemes, isto é, a cidade do Sol,

[[v6-19-42]]

^<<v6-19-42,42>>^ Selebin, Ajalon, Jetela,

[[v6-19-43]]

^<<v6-19-43,43>>^ Elon, Temna, Aeron,

[[v6-19-44]]

^<<v6-19-44,44>>^ Eltece, Gebbeton, Balaat,

[[v6-19-45]]

^<<v6-19-45,45>>^ Jud, Bane, Barac, Getremmon,

[[v6-19-46]]

^<<v6-19-46,46>>^ Merjarcon e Arecon, com os confins que olham para Jope.

[[v6-19-47]]

^<<v6-19-47,47>>^ Aqui termina esta possessão. Todavia os filhos de Dan subiram a pelejar contra Lesem, tomaram-na e passaram-na ao fio de espada. Tomada posse dela, habitaram-na, chamando-lhe Dan, do nome de Dan, seu pai.

[[v6-19-48]]

^<<v6-19-48,48>>^ Esta é a herança da tribo dos filhos de Dan, segundo as suas famílias, e estas são as suas cidades e aldeias.

[[v6-19-49]]

^<<v6-19-49,49>>^ Tendo Josué acabado de repartir a terra por sorte por cada uma das tribos, os filhos de Israel deram a Josué, filho de Nun, por herança, no meio deles,

[[v6-19-50]]

^<<v6-19-50,50>>^ segundo o preceito do Senhor, a cidade que ele pediu, Tamnat Saraa, sobre o monte de Efraim. Josué reedificou a cidade e habitou nela.

[[v6-19-51]]

^<<v6-19-51,51>>^ Estas são as heranças, que o sacerdote Eleázaro, e Josué, filho de Nun, e os chefes de família das tribos dos filhos de Israel distribuiram por sorte em Silo, diante do Senhor, à porta do tabernáculo da reunião. E assim acabaram a partilha da terra (de Canaan).

'''

xref:006-josue/006-josue-018.adoc#v6-18-0[&#60; Capítulo Anterior] | <<v6-19-0,Topo>> | xref:006-josue/006-josue-020.adoc#v6-20-0[Próximo Capítulo &#62;]