include::./index.adoc[]

[[v6-10-0]]
=== Josué, 10
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 10 de Josué descreve a conquista de várias cidades pelo exército israelita, incluindo a batalha contra os cinco reis amorreus que se uniram para lutar contra Gibeom. Deus ajudou os israelitas a vencer a batalha e até mesmo fez o sol parar no céu para dar-lhes mais tempo para completar a vitória. Aqui estão cinco versículos relacionados aos temas abordados em Josué 10:
* Êxodo 23:28: "E enviarei vespas diante de ti, para que lancem fora os heveus, os cananeus e os heteus de diante de ti." Este versículo se relaciona com a ajuda sobrenatural de Deus na luta contra os inimigos dos israelitas em Canaã.
* Deuteronômio 3:22: "Não os temais, porque o Senhor vosso Deus é o que peleja por vós." Este versículo se relaciona com a confiança dos israelitas na ajuda de Deus durante a batalha contra os cinco reis amorreus.
* Salmos 18:39: "Deste-me também o escudo da tua salvação; a tua mão direita me susteve, e a tua mansidão me engrandeceu." Este versículo se relaciona com a proteção de Deus sobre os israelitas durante a batalha e como Ele os susteve e salvou.
* Isaías 30:29: "Tereis uma canção como na noite em que se celebra uma festa santa; e alegria de coração, como a daquele que vai com flauta, para entrar no monte do Senhor, à Rocha de Israel." Este versículo se relaciona com a celebração dos israelitas depois de sua vitória sobre os inimigos e como eles deram graças e louvor a Deus.
* Salmos 46:10: "Aquietai-vos e sabei que eu sou Deus; serei exaltado entre as nações; serei exaltado sobre a terra." Este versículo se relaciona com a soberania de Deus sobre todas as nações e como Ele é exaltado em Suas obras, como a ajuda que Ele deu aos israelitas durante a batalha.
****

[[v6-10-1]]

^<<v6-10-1,1>>^ Adonisedec, rei de Jerusalém, tendo ouvido que Josué tomara Hai e a destruíra (porque fez a Hai e ao seu rei, como tinha feito a Jericó e ao seu rei), e que os Gabaonitas se tinham passado para Israel e se tinham tornado seus aliados,

[[v6-10-2]]

^<<v6-10-2,2>>^ teve muito medo. Com efeito, Gabaon era uma cidade grande, como uma das cidades reais, ainda maior que a cidade de Hai, e todos os seus guerreiros muito valentes.

[[v6-10-3]]

^<<v6-10-3,3>>^ Enviou pois Adonisedec, rei de Jerusalém (mensageiros) a Ohan, rei de Hebron, a Faran, rei de Jerimot, a Jafia, rei de Laquis e a Dabir, rei de Eglon, dizendo:

[[v6-10-4]]

^<<v6-10-4,4>>^ Vinde ter comigo e trazei-me socorro, a fim de tomarmos Gabaon, porque ela passou para Josué e para os filhos de Israel.

[[v6-10-5]]

^<<v6-10-5,5>>^ Unidos pois os cinco reis dos Amorreus, o rei de Jerusalém, o rei de Hebron, o rei de Jerimot, o rei de Laquis, o rei de Eglon, saíram com os seus exércitos, e acamparam junto a Gabaon, sitiando-a.

[[v6-10-6]]

^<<v6-10-6,6>>^ Os habitantes da sitiada cidade de Gabaon mandaram dizer a Josué, que estava então acampado em Galgala: Não recuses a tua mão aos teus servos; vem depressa, livra-nos, dá-nos socorro, porque se coligaram contra nós todos os reis dos Amorreus, que habitam nas montanhas.

[[v6-10-7]]

^<<v6-10-7,7>>^ Josué subiu de Galgala, e com ele todo o exército dos combatentes, homens valentíssimos.

[[v6-10-8]]

^<<v6-10-8,8>>^ O Senhor disse a Josué: Não os temas, porque eu os entreguei nas tuas mãos: nenhum deles te poderá resistir.

[[v6-10-9]]

^<<v6-10-9,9>>^ Josué, tendo marchado toda a noite desde Galgala, deu de repente sobre eles,

[[v6-10-10]]

^<<v6-10-10,10>>^ e o Senhor os desbaratou à vista de Israel; (Israel) infligiu-lhes uma grande derrota, junto de Gabaon, e foi-os perseguindo pelo caminho que sobe a Bet-horon, batendo-os até Azeca e Maceda.

[[v6-10-11]]

^<<v6-10-11,11>>^ Enquanto eles fugiam dos filhos de Israel e estavam na descida de Bet-horon, fez o Senhor cair do céu grandes pedras em cima deles até Azeca, e morreram muitos mais pelas pedras do granizo, do que pelos golpes da espada dos filhos de Israel.

[[v6-10-12]]

^<<v6-10-12,12>>^ Então Josué falou ao Senhor, no dia em que entregou o Amorreu nas mãos dos filhos de Israel, e disse em presença deles: Sol, não te movas de sobre Gabaon, e tu, lua, (não te movas) de sobre o vale de Ajalon. (ver nota)

[[v6-10-13]]

^<<v6-10-13,13>>^ E o sol e a lua pararam, até que o povo se vingou de seus inimigos. Não está isto escrito no livro do Justo? Parou pois o sol no meio do céu, e não se apressou a pôr-se durante quase o espaço de um dia.

[[v6-10-14]]

^<<v6-10-14,14>>^ Não houve nem antes nem depois um dia tão longo, obedecendo o Senhor à voz de um homem, porque combatia por Israel.

[[v6-10-15]]

^<<v6-10-15,15>>^ E Josué voltou com todo o Israel para o acampamento de Galgala.

[[v6-10-16]]

^<<v6-10-16,16>>^ Ora os cinco reis tinham fugido, e tinham-se escondido numa caverna da cidade de Maceda.

[[v6-10-17]]

^<<v6-10-17,17>>^ E noticiaram a Josué que os cinco reis tinham sido encontrados escondidos numa caverna da cidade de Maceda.

[[v6-10-18]]

^<<v6-10-18,18>>^ Ele ordenou aos que o acompanhavam: Rolai pedras grandes para a boca da caverna e ponde homens cuidadosos, que guardem os que nela estão escondidos;

[[v6-10-19]]

^<<v6-10-19,19>>^ vós porém não estejais parados, mas persegui os inimigos e matai os fugitivos que forem ficando atrás; não deixeis entrar nas fortalezas das suas cidades aqueles que o Senhor entregou nas vossas mãos.

[[v6-10-20]]

^<<v6-10-20,20>>^ Tendo sido feito, pois, grande destroço nos inimigos, quase até ao extermínio, aqueles que puderam fugir de Israel, acolheram-se às cidades fortes.

[[v6-10-21]]

^<<v6-10-21,21>>^ Todo o exército salvo e em número completo voltou para Josué, a Maceda, onde então estava o acampamento; ninguém (dos adversários) se atreveu a abrir a boca contra os filhos de Israel.

[[v6-10-22]]

^<<v6-10-22,22>>^ Josué disse: Abri a boca da caverna e trazei-me os cinco reis, que nela estão escondidos.

[[v6-10-23]]

^<<v6-10-23,23>>^ Eles fizeram como Ihes fora mandado, e levaram-Ihe os cinco reis: o rei de Jerusalém, o rei de Hebron, o rei de Jerimot, o rei de Laquis, o rei de Eglon.

[[v6-10-24]]

^<<v6-10-24,24>>^ Quando foram conduzidos perante ele, chamou todos os varões de Israel e disse aos chefes do exército que estavam com ele: Ide e ponde o pé sobre os pescoços destes reis. Tendo eles ido e posto os pés sobre os pescoços dos reis subjugados, (ver nota)

[[v6-10-25]]

^<<v6-10-25,25>>^ disse-lhes de novo: Não temais nem vos acobardeis, tende ânimo, sede fortes, porque assim fará o Senhor a todos os vossos inimigos, contra quem pelejais.

[[v6-10-26]]

^<<v6-10-26,26>>^ Depois disto, Josué feriu-os e tirou-lhes a vida, e mandou-os pendurar em cinco forcas, onde estiveram até à tarde.

[[v6-10-27]]

^<<v6-10-27,27>>^ Ao pôr do sol, mandou aos companheiros que os descessem dos patíbulos. Depois de descidos, lançaram-nos nas cavernas, em que se tinham escondido, e puseram à entrada grandes pedras, que ali se conservam até hoje.

[[v6-10-28]]

^<<v6-10-28,28>>^ No mesmo dia Josué tomou também Maceda, e passou-a a fio de espada, matou o seu rei e todos os seus habitantes, sem deixar um só. E fez ao rei de Maceda, como tinha feito ao rei de Jericó.

[[v6-10-29]]

^<<v6-10-29,29>>^ De Maceda passou com todo o Israel a Lebna, combatia contra ela.

[[v6-10-30]]

^<<v6-10-30,30>>^ O Senhor entregou-a com o seu rei nas mãos de Israel, que passou a fio de espada a cidade com todos os seres vivos que lá se encontravam, não deixando escapar nenhum. Fizeram ao rei de Lebna como tinham feito ao rei de Jericó.

[[v6-10-31]]

^<<v6-10-31,31>>^ De Lebna passou a Laquis com todo o Israel, e, postado o exército em volta da cidade, atacou-a.

[[v6-10-32]]

^<<v6-10-32,32>>^ O Senhor entregou Laquis nas mãos de Israel, que a tomou no dia seguinte, e a passou ao fio de espada, com todos os seres vivos que estavam dentro, como tinha feito a Lebna.

[[v6-10-33]]

^<<v6-10-33,33>>^ Nesta ocasião Horão, rei de Gazer, subiu em socorro de Laquis, mas Josué derrotou-o com todo o seu povo até ao extermínio completo.

[[v6-10-34]]

^<<v6-10-34,34>>^ De Laquis foi a Eglon, sitiou-a,

[[v6-10-35]]

^<<v6-10-35,35>>^ e no mesmo dia a tomou; passou a fio de espada todos os seres vivos, que estavam dentro, conforme tudo o que tinha feito a Laquis.

[[v6-10-36]]

^<<v6-10-36,36>>^ Passou, depois, com todo o Israel, de Eglon a Hebron, e combateu contra ela;

[[v6-10-37]]

^<<v6-10-37,37>>^ tomou-a e passou-a também a fio de espada com o seu rei, todos os povos daquela região e todos os seres vivos que nela moravam; não deixou ali ninguém com vida; como tinha feito a Eglon, assim fez a Hebron, passando à espada tudo o que encontrou,

[[v6-10-38]]

^<<v6-10-38,38>>^ Dali voltou-se contra Dabir,

[[v6-10-39]]

^<<v6-10-39,39>>^ tomou-a e destruiu-a; passou também a fio de espada o seu rei e todas as cidades circunvizinhas; não deixou nela resto algum; como tinha feito a Hebron e a Lebna e aos seus reis, assim fez a Dabir e ao seu rei.

[[v6-10-40]]

^<<v6-10-40,40>>^ Josué destruiu todo o território das montanhas, do meio dia e da planície e Asedot com os seus reis; não deixou ali resto algum, mas matou todo o ser vivo, como lhe tinha ordenado o Senhor Deus de Israel,

[[v6-10-41]]

^<<v6-10-41,41>>^ desde Cadesbarne até Gaza. Toda a terra de Gozen até Gabaon,

[[v6-10-42]]

^<<v6-10-42,42>>^ todos os seus reis e todos os seus países, os tomou e devastou duma só expedição, porque o Senhor Deus de Israel combateu por ele.

[[v6-10-43]]

^<<v6-10-43,43>>^ Depois voltou com todo o Israel para o lugar onde estava o acampamento em Galgala.

'''

xref:006-josue/006-josue-009.adoc#v6-9-0[&#60; Capítulo Anterior] | <<v6-10-0,Topo>> | xref:006-josue/006-josue-011.adoc#v6-11-0[Próximo Capítulo &#62;]