include::./index.adoc[]

[[v11-17-0]]
=== I Reis, 17
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 17 de 1 Reis é uma história notável de milagres e fé. Neste capítulo, Deus envia o profeta Elias para uma cidade em Zarefate, onde uma viúva o recebe e, apesar de ter apenas um pouco de farinha e azeite, Deus faz com que sua provisão nunca acabe. Mais tarde, a viúva tem um filho que fica gravemente doente e aparentemente morre, mas Elias intercede junto a Deus e o menino é trazido de volta à vida. Abaixo estão cinco versículos de outros livros da Bíblia que se relacionam com os temas abordados em 1 Reis 17.
* Salmos 37:25: "Fui jovem e agora sou velho, mas nunca vi os justos abandonados nem seus filhos mendigando pão." Este versículo destaca a fidelidade de Deus em prover para os justos e aqueles que confiam nele, mesmo em tempos difíceis, como no caso da viúva em 1 Reis 17.
* Mateus 6:33: "Mas busque primeiro o Reino de Deus e a sua justiça, e todas essas coisas lhe serão acrescentadas." Este versículo enfatiza a importância de buscar a Deus em primeiro lugar e confiar que Ele fornecerá todas as nossas necessidades, como fez com a viúva em 1 Reis 17.
* Hebreus 11:1: "Ora, a fé é a certeza daquilo que esperamos e a prova das coisas que não vemos." Este versículo destaca a importância da fé em Deus, mesmo quando não podemos ver claramente a solução para nossos problemas. A fé da viúva em 1 Reis 17 permitiu que ela confiasse em Deus para fornecer sua provisão diária.
* Tiago 5:16: "Portanto, confessem seus pecados uns aos outros e orem uns pelos outros, para que vocês sejam curados. A oração de uma pessoa justa é poderosa e eficaz." Este versículo destaca o poder da oração e da intercessão em favor dos outros, como fez Elias ao interceder junto a Deus pela vida do filho da viúva em 1 Reis 17.
* Lucas 1:37: "Porque para Deus nada é impossível." Este versículo enfatiza o poder e a soberania de Deus, que pode realizar milagres e fazer o impossível acontecer, como Ele fez ao multiplicar a farinha e o azeite da viúva em 1 Reis 17 e ao trazer o filho dela de volta à vida por meio de Elias.
****

[[v11-17-1]]

^<<v11-17-1,1>>^ Elias Tesbita, um dos habitantes de Galaad, disse a Acab: Viva o Senhor Deus de Israel, em cuja presença estou, que nestes anos não cairá nem orvalho nem chuva, senão conforme as palavras da minha boca.

[[v11-17-2]]

^<<v11-17-2,2>>^ Dirigiu o Senhor a sua palavra a Elias, nestes termos;

[[v11-17-3]]

^<<v11-17-3,3>>^ Retira-te daqui, vai para a banda do oriente e esconde-te junto da torrente de Carit, que está defronte do Jordão.

[[v11-17-4]]

^<<v11-17-4,4>>^ Beberás da torrente, e eu mandei aos corvos que te sustentem ali mesmo.

[[v11-17-5]]

^<<v11-17-5,5>>^ Partiu, pois, e procedeu segundo a ordem do Senhor: alojou-se junto da torrente de Garit, que está defronte do Jordão.

[[v11-17-6]]

^<<v11-17-6,6>>^ Os corvos traziam-lhe pela manhã pão e carne, e de tarde também pão e carne, e ele bebia da torrente.

[[v11-17-7]]

^<<v11-17-7,7>>^ Decorrido um certo tempo, secou-se a torrente, porque não tinha chovido sobre a terra.

[[v11-17-8]]

^<<v11-17-8,8>>^ Falou-lhe então o Senhor assim:

[[v11-17-9]]

^<<v11-17-9,9>>^ Levanta-te, vai para Sarefta dos Sidónios e fixa lá a tua morada, porque eu ordenei a uma mulher viúva que te sustente.

[[v11-17-10]]

^<<v11-17-10,10>>^ Levantou-se e foi para Sarefta. Tendo ele chegado à porta da cidade, apareceu-lhe uma mulher viúva, que apanhava lenha. Ele chamou-a e disse-lhe: Dá-me num vaso um pouco de água para beber.

[[v11-17-11]]

^<<v11-17-11,11>>^ Quando ela lha ia buscar, Elias chamou-a outra vez e disse: Traze-me também, te peço, um bocado de pão na tua mão.

[[v11-17-12]]

^<<v11-17-12,12>>^ Ela respondeu-lhe: Viva o Senhor teu Deus, que eu não tenho pão, senão sòmente um pouco de farinha na panela, e um pouco de azeite na almotolia. Ando a apanhar um pouco de lenha, a fim de a ir cozer para mim e para meu filho, para comermos e depois (de gasto estes restos) morreremos (de fome).

[[v11-17-13]]

^<<v11-17-13,13>>^ Elias disse-lhe: Não temas, mas vai e faze como disseste; porém faze primeiro para mim desse pouco de farinha um pãozinho cozido, debaixo do rescaldo, e traze-mo; para ti e para teu filho, farás depois.

[[v11-17-14]]

^<<v11-17-14,14>>^ Com efeito, o Senhor Deus de Israel diz assim: A farinha que está na panela não faltará, nem se diminuirá na almotolia o azeite, até ao dia em que o Senhor faça cair chuva sobre a terra.

[[v11-17-15]]

^<<v11-17-15,15>>^ Foi a mulher e fez como Elias lhe tinha dito; durante muito tempo ela teve que comer, e a sua casa e Elias. E desde aquele dia

[[v11-17-16]]

^<<v11-17-16,16>>^ não faltou a farinha na panela, nem se diminuiu o azeite da almotolia, conforme o que o Senhor tinha predito por Elias.

[[v11-17-17]]

^<<v11-17-17,17>>^ Aconteceu depois adoecer o filho desta mãe de família, e a doença era tão grave que já não respirava.

[[v11-17-18]]

^<<v11-17-18,18>>^ Ela disse a Elias: Que te fiz eu, ó homem de Deus? Porventura vieste a minha casa para excitares em mim a memória dos meus pecados e matares o meu filho?

[[v11-17-19]]

^<<v11-17-19,19>>^ Elias disse-lhe: Dá-me o teu filho. (Elias) tomou-o do regaço (da mãe), levou-o à câmara, onde ele estava alojado, e pô-lo em cima do seu leito.

[[v11-17-20]]

^<<v11-17-20,20>>^ Depois clamou ao Senhor, assim: Senhor meu Deus, até a uma viúva, que me sustenta como pode, afligiste, matando-lhe seu filho?

[[v11-17-21]]

^<<v11-17-21,21>>^ Estendeu-se, depois, inclinou-se três vezes sobre o menino, e gritou ao Senhor: Senhor, meu Deus, faze, te rogo, que a alma deste menino volte às suas entranhas.

[[v11-17-22]]

^<<v11-17-22,22>>^ O Senhor ouviu a voz de Elias: a alma do menino voltou a ele, e ele recuperou a vida.

[[v11-17-23]]

^<<v11-17-23,23>>^ Elias tomou o menino, desceu-o da sua câmara à casa de baixo, entregou-o a sua mãe e disse-lhe: Aqui tens vivo o teu filho.

[[v11-17-24]]

^<<v11-17-24,24>>^ A mulher respondeu a Elias: Agora conheço por isto que és um homem de Deus, e que a palavra do Senhor na tua boca é verdade.

'''

xref:011-i-reis/011-i-reis-016.adoc#v11-16-0[&#60; Capítulo Anterior] | <<v11-17-0,Topo>> | xref:011-i-reis/011-i-reis-018.adoc#v11-18-0[Próximo Capítulo &#62;]