include::./index.adoc[]

[[v11-14-0]]
=== I Reis, 14
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 14 do livro de 1 Reis fala sobre o julgamento de Deus sobre o rei Jeroboão de Israel, que havia pecado e levado o povo de Israel a pecar também. O capítulo descreve como Jeroboão perdeu seu filho e sua esposa, além de ser advertido de que sua dinastia seria destruída por causa de sua desobediência.
* 2 Crônicas 13:6: "Mas Jeroboão, filho de Nebate, servo de Salomão, filho de Davi, levantou-se e rebelou-se contra o seu senhor." Este versículo menciona Jeroboão, o foco principal do capítulo 14 de 1 Reis, e como ele se rebelou contra o rei Salomão.
* 1 Reis 12:28: "E, depois de consultar, fez dois bezerros de ouro e disse ao povo: 'Chega de subir a Jerusalém. Aqui estão os seus deuses, ó Israel, que o tiraram do Egito'." Este versículo fala sobre o pecado de Jeroboão de criar bezerros de ouro para adoração em Betel e Dã, levando o povo de Israel a pecar.
* 1 Reis 13:33-34: "Depois disto, Jeroboão não se desviou do seu mau caminho, mas tornou a fazer sacerdotes para os lugares altos dentre o povo em geral; a quem queria, consagrava para que fossem sacerdotes dos lugares altos. E isto foi causa de pecado para a casa de Jeroboão, para extirpá-la e destruí-la da face da terra." Estes versículos descrevem como Jeroboão continuou em seu mau caminho, criando sacerdotes para os lugares altos e levando seu povo a pecar, o que resultou na punição divina sobre a dinastia de Jeroboão.
* 1 Reis 15:29-30: "Assim que Baasa se tornou rei de Israel, matou toda a família de Jeroboão; não deixou ninguém com vida, conforme a palavra do Senhor que dissera por intermédio do seu servo Aías, o silonita, por causa dos pecados que Jeroboão tinha cometido e pelos quais tinha feito Israel pecar, e por causa da sua provocação ao Senhor, o Deus de Israel." Estes versículos descrevem como a dinastia de Jeroboão foi exterminada por causa de seu pecado e desobediência, cumprindo a profecia dada por Deus através do profeta Aías.
****

[[v11-14-1]]

^<<v11-14-1,1>>^ Naquele tempo adoeceu Abia, filho de Jeroboão.

[[v11-14-2]]

^<<v11-14-2,2>>^ Jeroboão disse a sua mulher: Levanta-te e muda de trajo, para que não conheçam que és mulher de Jeroboão, e vai a Silo, onde está o profeta Aias, o qual me predisse que reinaria sobre este povo.

[[v11-14-3]]

^<<v11-14-3,3>>^ Leva contigo dez pães, uma torta e um vaso de mel, e vai ter com ele, porque ele te dirá o que tem de acontecer a este menino.

[[v11-14-4]]

^<<v11-14-4,4>>^ A mulher de Joroboão fez como ele lhe tinha dito. Levantando-se, partiu para Silo e foi a casa de Alas. Ele não podia ver, porque os seus olhos se tinham escurecido por causa da muita idade.

[[v11-14-5]]

^<<v11-14-5,5>>^ O Senhor disse a Aias: Aí vem a mulher de Jeroboão consultar-te sobre seu filho, que está doente: tu lhe dirás isto e isto. Tendo entrado a mulher de Jeroboão, dissimulando quem era,

[[v11-14-6]]

^<<v11-14-6,6>>^ Aias ouviu o ruído dos seus pés, ao entrar pela porta, e disse: Entra, mulher de Jeroboão; para que finges tu ser outra? Eu fui enviado para te dar uma triste nova.

[[v11-14-7]]

^<<v11-14-7,7>>^ Vai e dize a Jeroboão: Eis o que diz o Senhor, Deus de Israel: Eu te elevei do meio do povo e te constitui chefe do meu povo de Israel;

[[v11-14-8]]

^<<v11-14-8,8>>^ dividi o reino da casa de Davide e dei-to a ti, mas tu não foste como meu servo Davide, que guardou os meus mandamentos e que me seguiu de todo o seu coração, fazendo o que me era agradável;

[[v11-14-9]]

^<<v11-14-9,9>>^ fizeste maiores males do que todos quantos têm havido antes de ti, e fabricaste para ti deuses estrangeiros e fundidos, para me provocares a ira, e a mim lançaste-me para trás das costas.

[[v11-14-10]]

^<<v11-14-10,10>>^ Por isso eu farei cair males sobre a casa de Jeroboão, farei morrer da casa de Jeroboão todo o indivíduo do sexo masculino, escravo ou homem livre, e varrerei os restos da casa de Jeroboão, como se costuma varrer o lixo, até não ficar rasto.

[[v11-14-11]]

^<<v11-14-11,11>>^ Os que morrerem da casa de Jeroboão na cidade, serão devorados pelos cães, e os que morrerem no campo, serão comidos pelas aves do céu. É o Senhor que o diz.

[[v11-14-12]]

^<<v11-14-12,12>>^ Vai, pois, torna para tua casa; ao mesmo tempo que puseres os pés na cidade, morrerá o menino.

[[v11-14-13]]

^<<v11-14-13,13>>^ Todo o Israel o chorará e o sepultará, porque só este da casa de Jeroboão será posto no sepulcro, porque o Senhor Deus de Israel, entre os da casa de Jeroboão, sòmente a ele olhou com agrado.

[[v11-14-14]]

^<<v11-14-14,14>>^ O Senhor constituiu para si um rei sobre Israel, que arruinará a casa de Jeroboão neste dia e neste tempo;

[[v11-14-15]]

^<<v11-14-15,15>>^ o Senhor Deus sacudirá Israel, como uma cana costuma ser agitada nas águas; ele arrancará Israel desta excelente terra, que deu a seus pais e dispersá-lo-á para além do rio, porque fez ídolos, que irritam o Senhor.

[[v11-14-16]]

^<<v11-14-16,16>>^ O Senhor abandonará Israel, por causa dos pecados de Jeroboão, que pecou e fez pecar Israel.

[[v11-14-17]]

^<<v11-14-17,17>>^ Levantou-se a mulher de Jeroboão, pôs-se a caminho e chegou a Tersa; quando ela entrava o limiar da porta, morreu o menino.

[[v11-14-18]]

^<<v11-14-18,18>>^ Sepultaram-no, e todo o Israel o chorou, conforme a palavra do Senhor, que tinha proferido pela boca do profeta Alas, seu servo.

[[v11-14-19]]

^<<v11-14-19,19>>^ O mais, porém, das acções de Jeroboão, as guerras que teve, o seu modo de reinar, tudo isso está escrito no livro das Crônicas dos reis de Israel.

[[v11-14-20]]

^<<v11-14-20,20>>^ O tempo que Jeroboão reinou foi de vinte e dois anos. Adormeceu com seus pais, e em seu lugar reinou seu filho Nadab.

[[v11-14-21]]

^<<v11-14-21,21>>^ Roboão, filho de Salomão, reinou em Judá. Tinha quarenta e um anos, quando começou a reinar; reinou dezassete anos na cidade de Jerusalém, que o Senhor tinha escolhido dentre todas as tribos de Israel para estabelecer nela o seu nome. Sua mãe chamava-se Naama, a Amonita.

[[v11-14-22]]

^<<v11-14-22,22>>^ (A tribo de) Judá fez o mal diante do Senhor. Irritaram-no mais do que tinham feito seus pais, com os crimes que tinham cometido.

[[v11-14-23]]

^<<v11-14-23,23>>^ Também eles levantaram para si altares, estátuas e ascherim em cima de todos os outeiros, e debaixo de todas as árvores frondosas.

[[v11-14-24]]

^<<v11-14-24,24>>^ Até houve, no país, consagrados à prostituição Idolátrica. Imitaram todas as abominações daqueles povos que o Senhor tinha destruído à vista dos filhos de Israel.

[[v11-14-25]]

^<<v11-14-25,25>>^ No quinto ano do reinado de Roboão, Sesac, rei do Egipto, avançou contra Jerusalém

[[v11-14-26]]

^<<v11-14-26,26>>^ e levou os tesouros da casa do Senhor, os tesouros do rei, roubou tudo, até mesmo os escudos de ouro, que Salomão tinha feito.

[[v11-14-27]]

^<<v11-14-27,27>>^ Em sua substituição, o rei Roboão fez escudos de bronze, que entregou nas mãos dos capitães da guarda e dos que faziam sentinelas diante da porta do palácio do rei.

[[v11-14-28]]

^<<v11-14-28,28>>^ Quando o rei entrava na casa do Senhor, os que tinham o cargo de ir adiante, levavam estes escudos; depois tornavam-nos a pôr na casa das armas dos guardas.

[[v11-14-29]]

^<<v11-14-29,29>>^ O resto das acções de Roboão, tudo o que ele fez, encontra-se escrito no livro das Crônicas dos reis de Judá.

[[v11-14-30]]

^<<v11-14-30,30>>^ Houve guerra contínua entre Roboão e Jeroboão.

[[v11-14-31]]

^<<v11-14-31,31>>^ Roboão adormeceu com seus pais e foi sepultado com eles na cidade de Davide. O nome de sua mãe era Naama, a Amonita. Abião, seu filho, reinou em seu lugar.

'''

xref:011-i-reis/011-i-reis-013.adoc#v11-13-0[&#60; Capítulo Anterior] | <<v11-14-0,Topo>> | xref:011-i-reis/011-i-reis-015.adoc#v11-15-0[Próximo Capítulo &#62;]