include::./index.adoc[]

[[v47-24-0]]
=== São Mateus, 24
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* São Mateus 24 é conhecido como o "Discurso do Monte das Oliveiras", no qual Jesus fala sobre os sinais do fim dos tempos e do seu retorno. Ele descreve a destruição do templo em Jerusalém, guerras, fomes, terremotos, perseguições e a propagação do Evangelho por todo o mundo. Aqui estão cinco versículos relacionados com os temas abordados em São Mateus 24:
* Marcos 13:7: "Quando, porém, ouvirdes falar de guerras e rumores de guerras, não vos assusteis; é necessário assim acontecer, mas ainda não é o fim." Jesus fala sobre as guerras e conflitos que ocorrerão antes do fim dos tempos, mas adverte que eles não são um sinal imediato do fim.
* 2 Timóteo 3:1: "Sabe, porém, isto: nos últimos dias, sobrevirão tempos difíceis." Paulo alerta Timóteo que haverá tempos difíceis no fim dos tempos, marcados por uma crescente falta de amor e uma busca pelo prazer pessoal.
* Apocalipse 6:8: "E olhei, e eis um cavalo amarelo e o seu cavaleiro, sendo este chamado Morte; e o Inferno o estava seguindo, e foi-lhes dada autoridade sobre a quarta parte da terra, para matar à espada, pela fome, pela mortandade e por meio das feras da terra." O livro do Apocalipse descreve a morte e a destruição que ocorrerão nos últimos dias, incluindo a fome e as feras da terra.
* Mateus 24:31: "E ele enviará os seus anjos com grande clangor de trombeta, os quais lhe ajuntarão os escolhidos desde os quatro ventos, de uma à outra extremidade dos céus." Jesus descreve a vinda dos anjos para reunir os escolhidos de Deus no fim dos tempos.
* Apocalipse 22:20: "Aquele que testifica estas coisas diz: Certamente, venho sem demora. Amém! Vem, Senhor Jesus!" O livro do Apocalipse termina com um apelo à vinda de Jesus, a quem os cristãos aguardam para vir e reinar em glória.
****

[[v47-24-1]]

^<<v47-24-1,1>>^ Tendo saído Jesus do templo, ia-se retirando; e aproximaram-se dele os seus discípulos, para lhe fazerem notar as construções.

[[v47-24-2]]

^<<v47-24-2,2>>^ Mas ele, respondendo, disse-lhes: "Vedes tudo isto? Em verdade vos digo que não ficará aqui pedra sobre pedra que não seja derribada."

[[v47-24-3]]

^<<v47-24-3,3>>^ Estando sentado sobre o monte das Oliveiras, aproximaram- se dele seus discípulos, aparte, e perguntaram: "Diz-nos quando sucederá isto, e qual será o sinal da tua vinda e do fim do mundo?"

[[v47-24-4]]

^<<v47-24-4,4>>^ Jesus respondeu-lhes: "Vede que ninguém vos engane. (ver nota)

[[v47-24-5]]

^<<v47-24-5,5>>^ Porque virão muitos em meu nome, dizendo: Eu sou o Cristo, e seduzirão muitos.

[[v47-24-6]]

^<<v47-24-6,6>>^ Ouvireis falar de guerras e de rumores de guerras. Olhai, não vos turbeis, porque importa que estas coisas aconteçam, mas não é ainda o fim.

[[v47-24-7]]

^<<v47-24-7,7>>^ Levantar-se-á nação contra nação, e reino contra reino, e haverá fomes, pestilências e terremotos em diversos lugares.

[[v47-24-8]]

^<<v47-24-8,8>>^ Todas estas coisas são o princípio das dores.

[[v47-24-9]]

^<<v47-24-9,9>>^ Então sereis sujeitos aos tormentos e vos matarão, e sereis odiados por todas as gentes por causa do meu nome.

[[v47-24-10]]

^<<v47-24-10,10>>^ Muitos então sucumbirão, uns aos outros se entregarão e se odiarão.

[[v47-24-11]]

^<<v47-24-11,11>>^ Levantar-se-ão muitos falsos profetas, e seduzirão muitos.

[[v47-24-12]]

^<<v47-24-12,12>>^ Multiplicando-se a iniquidade, se resfriará a caridade de muitos.

[[v47-24-13]]

^<<v47-24-13,13>>^ Mas o que se perseverar até ao fim, esse será salvo.

[[v47-24-14]]

^<<v47-24-14,14>>^ Será pregado este Evangelho do reino por todo o mundo, em testemunho a todas as gentes. Então chegará o fim.

[[v47-24-15]]

^<<v47-24-15,15>>^ Quando, pois, virdes a abominação da desolação, que foi predita pelo profeta Daniel (Dn. 9, 27; Dn. 11, 31; Dn. 12, 11), posta no lugar santo — leitor atende bem ,— (ver nota)

[[v47-24-16]]

^<<v47-24-16,16>>^ então os habitantes da Judeia, fujam para os montes,

[[v47-24-17]]

^<<v47-24-17,17>>^ o que se acha sobre o telhado, não desça para tomar coisa alguma de sua casa,

[[v47-24-18]]

^<<v47-24-18,18>>^ e o que está no campo, não volte atrás para tomar o seu manto.

[[v47-24-19]]

^<<v47-24-19,19>>^ Ai das (mulheres) grávidas e das que tiverem crianças de peito naqueles dias!

[[v47-24-20]]

^<<v47-24-20,20>>^ Rogai para que não seja a vossa fuga no inverno, ou em dia de sábado,

[[v47-24-21]]

^<<v47-24-21,21>>^ porque então será grande a tribulação, como nunca foi, desde o principio do mundo até agora, nem jamais será.

[[v47-24-22]]

^<<v47-24-22,22>>^ E, se não se abreviassem aqueles dias, não se salvaria pessoa alguma; porém, serão abreviados aqueles dias em atenção aos escolhidos.

[[v47-24-23]]

^<<v47-24-23,23>>^ Então, se alguém vos disser: Eis aqui está o Cristo, ou ei-lo acolá, não deis crédito,

[[v47-24-24]]

^<<v47-24-24,24>>^ porque se levantarão falsos cristos, e falsos profetas, e farão grandes milagres e prodígios, de tal modo que (se fosse possível) até os escolhidos seriam enganados. (ver nota)

[[v47-24-25]]

^<<v47-24-25,25>>^ Eis que eu vo-lo predisse.

[[v47-24-26]]

^<<v47-24-26,26>>^ Se pois vos disserem: Eis que ele está no deserto, não saiais; ei-lo no lugar mais retirado da casa, não deis crédito.

[[v47-24-27]]

^<<v47-24-27,27>>^ Porque, assim como o relâmpago sai do Oriente e se mostra até ao Ocidente, assim será a vinda do Filho do homem.

[[v47-24-28]]

^<<v47-24-28,28>>^ Onde estiver um cadáver aí se ajuntarão as águias.

[[v47-24-29]]

^<<v47-24-29,29>>^ Logo depois da tribulação daqueles dias, escurecer-se-á o sol, a lua não dará a sua luz, as estrelas cairão do céu, e as potestades dos céus serão abaladas.

[[v47-24-30]]

^<<v47-24-30,30>>^ Então aparecerá o sinal do Filho do homem no céu, todas as tribos da terra chorarão, e verão o Filho do homem vir sobre as nuvens do céu com grande poder e majestade.

[[v47-24-31]]

^<<v47-24-31,31>>^ Mandará os seus anjos com poderosas trombetas, e juntarão os seus escolhidos dos quatro ventos, de uma extremidade dos céus até à outra.

[[v47-24-32]]

^<<v47-24-32,32>>^ Compreendei isto por uma comparação tirada da figueira: Quando os seus ramos estão tenros e as folhas brotam, sabeis que está perto o estio;

[[v47-24-33]]

^<<v47-24-33,33>>^ assim também quando virdes ludo isto, sabei que (o Filho do homem) está perto, está às portas.

[[v47-24-34]]

^<<v47-24-34,34>>^ Na verdade vos digo que não passará esta geração, sem que se cumpram todas estas coisas.

[[v47-24-35]]

^<<v47-24-35,35>>^ O céu e a terra passarão, mas as minhas palavras não passarão.

[[v47-24-36]]

^<<v47-24-36,36>>^ Quanto àquele dia e àquela hora, ninguém sabe, nem os anjos do céu, nem o Filho, mas só o Pai.

[[v47-24-37]]

^<<v47-24-37,37>>^ Assim como foi nos dias de Noé, assim será também a (segunda) vinda do Filho do homem.

[[v47-24-38]]

^<<v47-24-38,38>>^ Nos dias que precederam o dilúvio (os homens) estavam comendo e bebendo, casando-se e casando seus filhos, até ao dia em que Noé entrou na arca,

[[v47-24-39]]

^<<v47-24-39,39>>^ e não souberam nada até que veio o dilúvio, e se levou a todos. Assim será também na vinda do Filho do homem.

[[v47-24-40]]

^<<v47-24-40,40>>^ Então, de dois que estiverem num campo, um será tomado e o outro será deixado.

[[v47-24-41]]

^<<v47-24-41,41>>^ De duas mulheres que estiverem moendo com a mó, uma será tomada e a outra será deixada.

[[v47-24-42]]

^<<v47-24-42,42>>^ Vigiai, pois, porque não sabeis a que hora virá o vosso Senhor.

[[v47-24-43]]

^<<v47-24-43,43>>^ Sabei que, se o pai de família soubesse a que hora havia de vir o ladrão, vigiaria, sem dúvida, e não deixaria minar a sua casa.

[[v47-24-44]]

^<<v47-24-44,44>>^ Por isso estai vós também preparados, porque o Filho do homem virá na hora em que menos o pensardes.

[[v47-24-45]]

^<<v47-24-45,45>>^ Quem é, pois, o servo fiel e prudente, a quem o senhor constituiu sobre a sua família para lhe distribuir de comer a seu tempo?

[[v47-24-46]]

^<<v47-24-46,46>>^ Bem-aventurado aquele servo, a quem o seu senhor, quando vier, achar procedendo assim.

[[v47-24-47]]

^<<v47-24-47,47>>^ Na verdade vos digo que lhe confiará o governo de todos os seus bens.

[[v47-24-48]]

^<<v47-24-48,48>>^ Mas, se aquele servo mau disser no seu coração: O meu senhor tarda em vir,

[[v47-24-49]]

^<<v47-24-49,49>>^ e começar a bater nos seus companheiros, a comer e beber com os ébrios,

[[v47-24-50]]

^<<v47-24-50,50>>^ virá o senhor daquele servo no dia em que o não espera, na hora que não sabe,

[[v47-24-51]]

^<<v47-24-51,51>>^ e o cortará em dois e porá a sua parte entre os hipócritas; ali haverá pranto e ranger de dentes.

'''

xref:047-sao-mateus/047-sao-mateus-023.adoc#v47-23-0[&#60; Capítulo Anterior] | <<v47-24-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-025.adoc#v47-25-0[Próximo Capítulo &#62;]