include::./index.adoc[]

[[v47-13-0]]
=== São Mateus, 13
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 13 de São Mateus contém uma série de parábolas contadas por Jesus sobre o Reino dos Céus. Essas parábolas usam imagens da vida cotidiana para explicar conceitos espirituais, como a importância de ouvir a Palavra de Deus e os perigos da incredulidade. Aqui estão cinco versículos relacionados aos temas abordados em São Mateus 13:
* João 15:5: "Eu sou a videira; vocês são os ramos. Se alguém permanecer em mim e eu nele, esse dará muito fruto; pois sem mim vocês não podem fazer coisa alguma." Essa metáfora de Jesus fala sobre a importância de permanecer em Cristo para produzir frutos espirituais.
* Marcos 4:20: "Outros, como a semente lançada em solo bom, ouvem a palavra, a aceitam e dão uma colheita: trinta, sessenta e até cem vezes mais do que foi semeado." Esse versículo fala sobre a importância de ouvir e aceitar a Palavra de Deus para produzir uma colheita abundante.
* Mateus 7:24-27: "Portanto, quem ouve estas minhas palavras e as põe em prática é como um homem prudente que construiu a sua casa sobre a rocha. Caiu a chuva, transbordaram os rios, sopraram os ventos e deram contra aquela casa, e ela não caiu, porque tinha seus alicerces na rocha. Mas quem ouve estas minhas palavras e não as põe em prática é como um insensato que construiu a sua casa sobre a areia. Caiu a chuva, transbordaram os rios, sopraram os ventos e deram contra aquela casa, e ela caiu. E foi grande a sua queda." Este versículo fala sobre a importância de construir nossa vida sobre a Palavra de Deus.
* Lucas 8:18: "Portanto, considerem com cuidado como vocês estão ouvindo. A quem tiver, mais lhe será dado; de quem não tiver, até o que pensa que tem lhe será tirado." Esse versículo fala sobre a importância de ouvir com atenção a Palavra de Deus e estar aberto para receber mais revelação.
* 2 Coríntios 4:3-4: "Mas, se o nosso evangelho está encoberto, para os que estão perecendo é que está encoberto. O deus deste século cegou o entendimento dos descrentes, para que não vejam a luz do evangelho da glória de Cristo, que é a imagem de Deus." Esse versículo fala sobre a realidade espiritual da incredulidade e o papel do diabo em cegar as mentes dos incrédulos para que não vejam a verdade do evangelho.
****

[[v47-13-1]]

^<<v47-13-1,1>>^ Naquele dia, saindo Jesus de casa, sentou-se à beira do mar.

[[v47-13-2]]

^<<v47-13-2,2>>^ E juntou-se em volta dele uma grande multidão de gente, de tal sorte que foi preciso entrar numa barca e sentar-se nela ; e toda a multidão estava em pé sobre a praia.

[[v47-13-3]]

^<<v47-13-3,3>>^ E disse-lhes muitas coisas por parábolas: "Eis que um semeador saiu a semear.

[[v47-13-4]]

^<<v47-13-4,4>>^ Quando semeava, uma parte da semente caiu ao longo do caminho, e vieram as aves do céu e comeram-na.

[[v47-13-5]]

^<<v47-13-5,5>>^ Outra parte caiu em lugar pedregoso, onde não havia muita terra; e logo nasceu, porque não tinha profundidade de terra.

[[v47-13-6]]

^<<v47-13-6,6>>^ Mas, saindo o sol, queimou-se; e porque não tinha raiz, secou.

[[v47-13-7]]

^<<v47-13-7,7>>^ Outra parte caiu entre os espinhos; e cresceram os espinhos, e a sufocaram.

[[v47-13-8]]

^<<v47-13-8,8>>^ Outra parte, enfim, caiu em boa terra, e frutificou; uns grãos deram cem por um, outros sessenta, outros trinta.

[[v47-13-9]]

^<<v47-13-9,9>>^ Quem tem ouvidos para ouvir, ouça."

[[v47-13-10]]

^<<v47-13-10,10>>^ Chegando-se a ele os discípulos, disseram-lhe: "Por que razão lhes falas por meio de parábolas?"

[[v47-13-11]]

^<<v47-13-11,11>>^ Ele respondeu-lhes: "Porque a vós é concedido conhecer os mistérios do reino dos céus, mas a eles não lhes é concedido.

[[v47-13-12]]

^<<v47-13-12,12>>^ Porque ao que tem lhe será dado (ainda mais), e terá em abundância, mas ao que não tem, até o que tem lhe será tirado. (ver nota)

[[v47-13-13]]

^<<v47-13-13,13>>^ Por isso lhes falo em parábolas, porque vendo não vêem, e ouvindo não ouvem nem entendem.

[[v47-13-14]]

^<<v47-13-14,14>>^ E cumpre-se neles a profecia de Isaías (Is. 6, 9-10), que diz: Ouvireis com os ouvidos, e não entendereis; olhareis com os vossos olhos, e não vereis.

[[v47-13-15]]

^<<v47-13-15,15>>^ Porque o coração deste povo tornou-se insensível, os- seus ouvidos tornaram-se duros, e fecharam os olhos, para não suceder que vejam com os olhos, e ouçam com os ouvidos, e entendam com o coração, e se convertam, e eu os sare.

[[v47-13-16]]

^<<v47-13-16,16>>^ Ditosos, porém, os vossos olhos, porque vêem, e os vossos ouvidos, porque ouvem.

[[v47-13-17]]

^<<v47-13-17,17>>^ Em verdade vos digo que muitos profetas e justos desejaram ver o que vedes, e não o viram, ouvir o que ouvis, e não o ouviram.

[[v47-13-18]]

^<<v47-13-18,18>>^ Ouvi, pois, vós o que significa a parábola do semeador:

[[v47-13-19]]

^<<v47-13-19,19>>^ Todo aquele que ouve a palavra do reino (do Evangelho), e não lhe presta atenção, vem o espírito maligno e arrebata o que foi semeado no seu coração; este é o que recebeu a semente ao longo da estrada.

[[v47-13-20]]

^<<v47-13-20,20>>^ O que recebeu a semente no lugar pedregoso, é aquele que ouve a palavra, e logo a recebe com gosto;

[[v47-13-21]]

^<<v47-13-21,21>>^ porém, não tem em si raiz, é inconstante; e, quando lhe sobrevêm tribulação e perseguição por causa da palavra, logo sucumbe.

[[v47-13-22]]

^<<v47-13-22,22>>^ O que recebeu a semente entre espinhos, é aquele que ouve a palavra, porém os cuidados deste século e a sedução das riquezas sufocam a palavra, e fica infrutuosa.

[[v47-13-23]]

^<<v47-13-23,23>>^ O que recebeu a semente em boa terra, é aquele que ouve a palavra, e a compreende, esse dá fruto, e umas vezes dá cem, outras sessenta, e outras trinta por um."

[[v47-13-24]]

^<<v47-13-24,24>>^ Propôs-lhe outra parábola, dizendo: " O reino dos céus é semelhante a um homem que semeou boa semente no seu campo.

[[v47-13-25]]

^<<v47-13-25,25>>^ Porém, enquanto os homens dormiam, veio o seu inimigo, e semeou cizânia no meio do trigo, e foi-se.

[[v47-13-26]]

^<<v47-13-26,26>>^ Tendo crescido a erva e dado fruto, apareceu então a cizânia.

[[v47-13-27]]

^<<v47-13-27,27>>^ Chegando os servos do pai de família, disseram-lhe: Senhor, porventura não semeaste tu boa semente no teu campo? Donde veio pois a cizânia?

[[v47-13-28]]

^<<v47-13-28,28>>^ Ele respondeu-lhes: Foi um inimigo que fez isto. Os servos disseram-lhe: Queres que vamos e a arranquemos?

[[v47-13-29]]

^<<v47-13-29,29>>^ Ele respondeu-lhes: Não. para que talvez não suceda que, arrancando a cizânia, arranqueis juntamente com ela o trigo.

[[v47-13-30]]

^<<v47-13-30,30>>^ Deixai crescer uma e outra coisa até à ceifa, e no tempo da ceifa direi aos segadores: Colhei primeiramente a cizânia, e atai-a em molhos para a queimar; o trigo, porém, recolhei-o no meu celeiro."

[[v47-13-31]]

^<<v47-13-31,31>>^ Propôs-lhes outra parábola, dizendo: O reino dos céus é semelhante a um grão de mostarda, que um homem tomou e semeou no seu campo.

[[v47-13-32]]

^<<v47-13-32,32>>^ É a mais pequena,de todas as sementes, mas, depois de ter crescido, é maior que todas as hortaliças e chega a tornar- se uma árvore, de sorte que as aves do céu vêm aninhar sobre os seus ramos."

[[v47-13-33]]

^<<v47-13-33,33>>^ Disse-lhes outra parábola; "O reino dos céus é semelhante ao fermento que uma mulher toma e mistura em três medidas de farinha, até que o todo fica fermentado."

[[v47-13-34]]

^<<v47-13-34,34>>^ Todas estas coisas disse Jesus ao povo em parábolas; e não lhes falava sem parábolas,

[[v47-13-35]]

^<<v47-13-35,35>>^ a fim de que se cumprisse o que estava anunciado pelo profeta, que diz; Abrirei em parábolas a minha boca, publicarei as coisas escondidas desde a criação (Ps. 77, 2)."

[[v47-13-36]]

^<<v47-13-36,36>>^ Então (Jesus), despedido o povo, foi para casa, e chegaram-se a ele os seus discípulos, dizendo: "Explica-nos a parábola da cizânia no campo."

[[v47-13-37]]

^<<v47-13-37,37>>^ Ele respondeu: "O que semeia a boa semente, é o Filho do homem.

[[v47-13-38]]

^<<v47-13-38,38>>^ O campo é o mundo. A boa semente são os filhos do reino. A cizânia são os filhos do (espírito) maligno.

[[v47-13-39]]

^<<v47-13-39,39>>^ O inimigo que a semeou, é o demônio. O tempo da ceifa é o fim do mundo. Os segadores são os anjos.

[[v47-13-40]]

^<<v47-13-40,40>>^ De maneira que, assim como é colhida a cizânia e queimada no fogo, assim acontecerá no fim do mundo.

[[v47-13-41]]

^<<v47-13-41,41>>^ O Filho do homem enviará os seus anjos, e tirarão do seu reino todos os escândalos e os que praticam a iniquidade,

[[v47-13-42]]

^<<v47-13-42,42>>^ e lançá-los-ão na fornalha de fogo. Ali haverá choro e ranger de dentes.

[[v47-13-43]]

^<<v47-13-43,43>>^ Então resplandecerão os justos como o sol no reino de seu Pai. O que tem ouvidos para ouvir, ouça.

[[v47-13-44]]

^<<v47-13-44,44>>^ O reino dos céus é semelhante a um tesouro escondido num campo, o qual, quando um homem o acha, esconde-o, e, pelo gosto que sente de o achar, vai, e vende tudo o que tem, e compra aquele campo.

[[v47-13-45]]

^<<v47-13-45,45>>^ O reino dos céus é também semelhante a um mercador que busca pérolas preciosas,

[[v47-13-46]]

^<<v47-13-46,46>>^ e, tendo encontrado uma de grande preço, vai, vende tudo o que tem, e a compra.

[[v47-13-47]]

^<<v47-13-47,47>>^ O reino dos céus é ainda semelhante a uma rede lançada ao mar, que colhe toda a casta de peixes.

[[v47-13-48]]

^<<v47-13-48,48>>^ Quando está cheia, os pescadores tiram-na para fora, e, sentados na praia, escolhem os bons para cestos e deitam fora os maus.

[[v47-13-49]]

^<<v47-13-49,49>>^ Será assim no fim do mundo, virão os anjos, e separarão os maus do meio dos justos,

[[v47-13-50]]

^<<v47-13-50,50>>^ e lançá-los-ão na fornalha de fogo. Ali haverá choro e ranger de dentes.

[[v47-13-51]]

^<<v47-13-51,51>>^ Compreendestes tudo isto?" Eles responderam: "Sim."

[[v47-13-52]]

^<<v47-13-52,52>>^ Ele disse-Ihes; "Por isso todo o escriba instruído nas coisas do reino dos céus é semelhante a um pai de família, que tira do seu tesouro coisas novas e velhas." (ver nota)

[[v47-13-53]]

^<<v47-13-53,53>>^ Quando Jesus acabou de dizer estas parábolas partiu dali.

[[v47-13-54]]

^<<v47-13-54,54>>^ E, indo para a sua pátria, ensinava nas suas sinagogas, de modo que se admiravam e diziam; "Donde lhe vem esta sabedoria e estes milagres?

[[v47-13-55]]

^<<v47-13-55,55>>^ Porventura não é este o filho do carpinteiro? Não se chama sua mãe Maria, e seus irmãos Tiago, José, Simão e Judas?

[[v47-13-56]]

^<<v47-13-56,56>>^ Suas irmãs não vivem todas entre nós? Donde vem, pois, a este todas estas coisas?

[[v47-13-57]]

^<<v47-13-57,57>>^ E estavam perplexos a seu respeito." Mas Jesus disse-lhes: "Não há profeta sem prestígio senão na sua pátria e na sua casa."

[[v47-13-58]]

^<<v47-13-58,58>>^ E fez ali poucos milagres, por causa da incredulidade deles.

'''

xref:047-sao-mateus/047-sao-mateus-012.adoc#v47-12-0[&#60; Capítulo Anterior] | <<v47-13-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-014.adoc#v47-14-0[Próximo Capítulo &#62;]