include::./index.adoc[]

[[v47-4-0]]
=== São Mateus, 4
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* São Mateus 4 relata a tentação de Jesus no deserto, após seu batismo. Nesse capítulo, Jesus é tentado três vezes pelo diabo, mas resiste e se fortalece para iniciar seu ministério na Galileia. Além disso, o capítulo também destaca a importância das Escrituras Sagradas e como Jesus começou a reunir seus primeiros discípulos.
* Tiago 4:7: "Portanto, sujeitai-vos a Deus, resisti ao diabo, e ele fugirá de vós." Esse versículo destaca a importância de resistir às tentações do diabo, assim como Jesus fez no deserto.
* 2 Timóteo 3:16-17: "Toda Escritura é divinamente inspirada e proveitosa para ensinar, para repreender, para corrigir, para instruir em justiça; para que o homem de Deus seja perfeito, e perfeitamente preparado para toda boa obra." Assim como Jesus usou as Escrituras para resistir às tentações, esse versículo enfatiza a importância das Escrituras para o crescimento espiritual.
* Mateus 10:38: "E quem não toma a sua cruz, e não segue após mim, não é digno de mim." Esse versículo destaca a importância da renúncia e do sacrifício na vida cristã, um tema que também é abordado na tentação de Jesus.
* Lucas 5:10: "E Jesus disse a Simão: Não temas; de agora em diante serás pescador de homens." Assim como Jesus chamou seus primeiros discípulos para segui-lo, esse versículo destaca como Jesus ainda hoje chama pessoas para se tornarem discípulos e trabalharem para o Reino de Deus.
* Atos dos Apóstolos 10:38: "Como Deus ungiu a Jesus de Nazaré com o Espírito Santo e com poder; o qual andou fazendo o bem, e curando a todos os oprimidos do diabo, porque Deus era com ele." Esse versículo destaca como Jesus iniciou seu ministério fazendo o bem e curando os oprimidos, assim como ele ainda hoje continua a fazer por meio do Espírito Santo agindo na vida dos cristãos.
****

[[v47-4-1]]

^<<v47-4-1,1>>^ Então Jesus foi conduzido pelo Espírito (Santo) ao deserto, para ser tentado pelo demônio.

[[v47-4-2]]

^<<v47-4-2,2>>^ Jejuou quarenta dias e quarenta noites, depois teve fome.

[[v47-4-3]]

^<<v47-4-3,3>>^ E, aproximando-se dele o tentador, disse-lhe: "Se és Filho de Deus, diz que estas pedras se convertam em pães."

[[v47-4-4]]

^<<v47-4-4,4>>^ Jesus respondeu: "Está escrito: Não só de pão vive o homem, mas de toda a palavra que sai da boca de Deus (Dt. 8, 3)."

[[v47-4-5]]

^<<v47-4-5,5>>^ Então o demónio transportou-o à cidade santa, pô-lo sobre o pináculo do templo,

[[v47-4-6]]

^<<v47-4-6,6>>^ e disse-lhe: "Se és Filho de Deus. lança-te daqui abaixo, porque está escrito: Mandou aos seus anjos em teu favor, eles te levarão nas suas mãos, para que o teu pé não tropece em alguma pedra (Ps. 90, 11-12)."

[[v47-4-7]]

^<<v47-4-7,7>>^ Jesus disse-lhe: "Também está escrito: Não tentarás o Senhor teu Deus (Dt. 6, 16)."

[[v47-4-8]]

^<<v47-4-8,8>>^ De novo o demônio o transportou a um monte muito alto, e lhe mostrou todos os reinos do mundo e a sua magnificência,

[[v47-4-9]]

^<<v47-4-9,9>>^ e lhe disse: "Tudo isto te darei, se, prostrado, me adorares."

[[v47-4-10]]

^<<v47-4-10,10>>^ Então Jesus disse-lhe: "Vai-te, Satanás, porque está escrito: O Senhor teu Deus adorarás, e a ele só servirás (Dt. 6, 13)."

[[v47-4-11]]

^<<v47-4-11,11>>^ Então o demónio deixou-o; e eis que os anjos se aproximaram, e o serviram.

[[v47-4-12]]

^<<v47-4-12,12>>^ Tendo (Jesus) ouvido que João fora preso, retirou-se para a Galileia.

[[v47-4-13]]

^<<v47-4-13,13>>^ Depois, deixando Nazaré, foi habitar em Cafarnaum, situada junto do mar, nos confins de Zabulon e Neftali,

[[v47-4-14]]

^<<v47-4-14,14>>^ cumprindo-se o que tinha sido anunciado pelo profeta Isaías, quando disse (Is. 8,23, Is. 9, 1);

[[v47-4-15]]

^<<v47-4-15,15>>^ Terra de Zabulon e terra de Neftali, terra que confina com o mar, pais além do Jordão, Galileia dos gentios!

[[v47-4-16]]

^<<v47-4-16,16>>^ Este povo, que jazia nas trevas, viu uma grande luz; e uma luz levantou-se para os que jaziam na sombra da morte.

[[v47-4-17]]

^<<v47-4-17,17>>^ Desde então, começou Jesus a pregar: "Fazei penitência, porque está próximo o reino dos céus."

[[v47-4-18]]

^<<v47-4-18,18>>^ Caminhando ao longo do mar da Galileia, viu dois irmãos, Simão, chamado Pedro, e, André, seu irmão, que lançavam a rede ao mar, pois eram pescadores.

[[v47-4-19]]

^<<v47-4-19,19>>^ "Segui-me, lhes disse, e eu vos farei pescadores de homens."

[[v47-4-20]]

^<<v47-4-20,20>>^ E eles, imediatamente, deixadas as redes, o seguiram.

[[v47-4-21]]

^<<v47-4-21,21>>^ Passando adiante, viu outros dois irmãos, Tiago, filho de Zebedeu, e João, seu irmão, que estavam numa barca juntamente com seu pai Zebedeu, consertando se suas redes, e chamou-os.

[[v47-4-22]]

^<<v47-4-22,22>>^ Eles, imediatamente, deixando a barca e o pai, o seguiram.

[[v47-4-23]]

^<<v47-4-23,23>>^ Jesus percorria toda a Galileia, ensinando nas sinagogas, e pregando o Evangelho do reino (de Deus), e curando todas as enfermidades entre o povo.

[[v47-4-24]]

^<<v47-4-24,24>>^ A sua fama espalhou-se por toda a Síria, e trouxeram-lhe todos os que tinham algum mal, possuídos de vários achaques e dores: possessos, lunáticos, paralíticos; e curava-os.

[[v47-4-25]]

^<<v47-4-25,25>>^ Seguiram-no grandes multidões (de povo) da Galileia, da Decápole, de Jerusalém, da Judeia e de além do Jordão.

'''

xref:047-sao-mateus/047-sao-mateus-003.adoc#v47-3-0[&#60; Capítulo Anterior] | <<v47-4-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-005.adoc#v47-5-0[Próximo Capítulo &#62;]