include::./index.adoc[]

[[v47-5-0]]
=== São Mateus, 5
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* São Mateus 5 é conhecido como o "Sermão da Montanha", um dos discursos mais famosos de Jesus. Neste capítulo, Jesus fala sobre a natureza do Reino de Deus e ensina sobre a ética cristã, incluindo as bem-aventuranças, o papel do cristão no mundo e o cumprimento da Lei. Aqui estão cinco versículos relacionados aos temas abordados em São Mateus 5:
* Provérbios 16:7: "Quando os caminhos de alguém agradam ao Senhor, até seus inimigos vivem em paz com ele." Este versículo fala sobre a importância de seguir o caminho de Deus para viver em paz com os outros, que é um tema abordado por Jesus na parte do Sermão da Montanha que trata das bem-aventuranças.
* Romanos 12:18: "Se possível, quanto depender de vós, tende paz com todos os homens." Este versículo reforça a ideia de buscar a paz com os outros, que é um tema central das bem-aventuranças em São Mateus 5.
* 1 Pedro 2:9: "Mas vós sois a raça escolhida, o sacerdócio real, a nação santa, o povo adquirido para Deus, a fim de que publiqueis as virtudes daquele que vos chamou das trevas para a sua luz admirável." Este versículo fala sobre o papel do cristão no mundo, que é um tema abordado por Jesus em São Mateus 5.
* Mateus 22:37-39: "Amarás o Senhor, teu Deus, de todo o teu coração, de toda a tua alma e de todo o teu espírito. Este é o maior e o primeiro mandamento. O segundo é semelhante a este: Amarás o teu próximo como a ti mesmo." Este versículo resume a ética cristã em termos de amor a Deus e ao próximo, um tema central do Sermão da Montanha.
* Tiago 1:22: "Sede cumpridores da palavra, e não somente ouvintes, enganando-vos a vós mesmos." Este versículo reforça a ideia de que é importante colocar em prática as palavras de Jesus, que é um tema abordado em São Mateus 5 quando Jesus fala sobre cumprir a Lei e os profetas.
****

[[v47-5-1]]

^<<v47-5-1,1>>^ Vendo (Jesus) aquelas multidões, subiu a um monte, e, tendo-se sentado, aproximaram-se dele os discípulos.

[[v47-5-2]]

^<<v47-5-2,2>>^ Abrindo então a sua boca, os ensinava, dizendo:

[[v47-5-3]]

^<<v47-5-3,3>>^ "Bem-aventurados os pobres de espírito, porque deles é o reino dos céus.

[[v47-5-4]]

^<<v47-5-4,4>>^ Bem-aventurados os mansos, porque possuirão a Terra.

[[v47-5-5]]

^<<v47-5-5,5>>^ Bem-aventurados os que choram, porque serão consolados.

[[v47-5-6]]

^<<v47-5-6,6>>^ Bem-aventurados os que têm fome e sede da justiça, porque serão saciados. (ver nota)

[[v47-5-7]]

^<<v47-5-7,7>>^ Bem-aventurados os misericordiosos, porque alcançarão misericórdia.

[[v47-5-8]]

^<<v47-5-8,8>>^ Bem-aventurados os puros de coração, porque verão a Deus.

[[v47-5-9]]

^<<v47-5-9,9>>^ Bem-aventurados os pacíficos, porque serão chamados filhos de Deus.

[[v47-5-10]]

^<<v47-5-10,10>>^ Bem-aventurados os que sofrem perseguição por amor da justiça, porque deles é o reino dos céus.

[[v47-5-11]]

^<<v47-5-11,11>>^ Bem-aventurados sereis, quando vos insultarem, vos perseguirem, e disserem falsamente toda a sorte de mal contra vós por causa de mim.

[[v47-5-12]]

^<<v47-5-12,12>>^ Alegrai-vos e exultai, porque será grande a vossa recompensa nos céus, pois (também) assim perseguiram os profetas, que existiram antes de vós.

[[v47-5-13]]

^<<v47-5-13,13>>^ Vós sois o sal da terra. Porém, se o sal perder a sua força, com que será ele salgado? Para nada mais serve senão para ser lançado fora e calcado pelos homens.

[[v47-5-14]]

^<<v47-5-14,14>>^ Vós sois a luz do mundo. Não pode esconder-se uma cidade situada sobre um monte;

[[v47-5-15]]

^<<v47-5-15,15>>^ nem se acende uma lucerna, e se põe debaixo do alqueire, mas sobre o candeeiro, a fim de que dê luz a todos os que estão em casa.

[[v47-5-16]]

^<<v47-5-16,16>>^ Assim brilhe a vossa luz diante dos homens, para que vejam as vossas boas obras, e glorifiquem o vosso Pai, que está nos céus.

[[v47-5-17]]

^<<v47-5-17,17>>^ Não julgueis que vim abolir a lei ou os profetas; não vim (para os) abolir, mas sim (para os) cumprir.

[[v47-5-18]]

^<<v47-5-18,18>>^ Porque em verdade vos digo: antes passarão o céu e a terra, que passe da lei um só jota ou um ápice, sem que tudo seja cumprido.

[[v47-5-19]]

^<<v47-5-19,19>>^ Aquele, pois, que violar um destes mandamentos, mesmo dos mais pequenos, e ensinar assim aos homens, será considerado o mais pequeno no reino dos céus; mas o que os guardar e ensinar, esse será considerado grande no reino dos céus.

[[v47-5-20]]

^<<v47-5-20,20>>^ Porque eu vos digo que, se a vossa justiça não exceder a dos escribas e a dos fariseus, não entrareis no reino dos céus.

[[v47-5-21]]

^<<v47-5-21,21>>^ Ouvistes que foi dito aos antigos: Não matarás (Ex. 20, 13...), e quem matar será submetido ao juízo do tribunal.

[[v47-5-22]]

^<<v47-5-22,22>>^ Pois eu digo-vos que todo aquele que se irar contra o seu irmão, será submetido ao juízo do tribunal. E o que chamar "raca" a seu irmão será condenado pelo Sinédrio. E o que lhe chamar louco, será condenado ao fogo da geena. (ver nota)

[[v47-5-23]]

^<<v47-5-23,23>>^ Portanto, se estás para fazer a tua oferta diante do altar, e te lembrares aí que teu irmão tem alguma coisa contra ti.

[[v47-5-24]]

^<<v47-5-24,24>>^ deixa lá a tua oferta diante do altar, e vai reconciliar-te primeiro com teu irmão, e depois vem fazer a tua oferta.

[[v47-5-25]]

^<<v47-5-25,25>>^ Acomoda-te sem demora com o teu adversário, enquanto estás em caminho com ele, para que não suceda que esse adversário te entregue ao juiz, e o juiz te entregue ao seu ministro, e sejas posto em prisão. (ver nota)

[[v47-5-26]]

^<<v47-5-26,26>>^ Em verdade te digo: Não sairás de lá antes de ter pago o último quadrante.

[[v47-5-27]]

^<<v47-5-27,27>>^ Ouvistes que foi dito: Não cometerás adultério (Ex. 20, 14).

[[v47-5-28]]

^<<v47-5-28,28>>^ Eu, porém, digo-vos que todo o que olhar para uma mulher, cobiçando-a, já cometeu adultério com ela no seu coração.

[[v47-5-29]]

^<<v47-5-29,29>>^ Por isso, o teu olho direito é para ti causa de queda, arranca-o e lança-o para longe de ti, porque é melhor para ti que se perca um dos teus membros, do que todo o teu corpo seja lançado na geena.

[[v47-5-30]]

^<<v47-5-30,30>>^ E, se a tua mão direita é para ti causa de queda, corta-a e lança-a para longe de ti, porque é melhor para ti que se perca um dos teus membros, do que todo o teu corpo seja lançado na geena.

[[v47-5-31]]

^<<v47-5-31,31>>^ Também foi dito: Aquele que repudiar sua mulher, dê-lhe libelo de repúdio (Dt. 24, 1).

[[v47-5-32]]

^<<v47-5-32,32>>^ Eu, porém, digo-vos: todo aquele que repudiar sua mulher, a não ser por causa de fornicação, expõe-na ao adultério; e o que desposar a (mulher) repudiada, comete adultério.

[[v47-5-33]]

^<<v47-5-33,33>>^ Igualmente ouvistes que foi dito aos antigos: Não perjurarás, mas guardarás para com o Senhor os teus juramentos (Ex. 20, 7 ...) .

[[v47-5-34]]

^<<v47-5-34,34>>^ Eu, porém, digo-vos que não jureis de modo algum (sem motivo justo), nem pelo céu, porque é o trono de Deus;

[[v47-5-35]]

^<<v47-5-35,35>>^ nem pela terra, porque é o escabelo de seus pés; nem por Jerusalém, porque é a cidade do grande rei.

[[v47-5-36]]

^<<v47-5-36,36>>^ Nem jurarás pela tua cabeça, pois não podes fazer branco ou negro um só dos teus cabelos.

[[v47-5-37]]

^<<v47-5-37,37>>^ Seja o vosso falar: Sim. sim; não não. Tudo o que disto passa, procede do Maligno.

[[v47-5-38]]

^<<v47-5-38,38>>^ Ouvistes que foi dito: Olho por olho, e dente por dente (Lv. 24, 19-20).

[[v47-5-39]]

^<<v47-5-39,39>>^ Eu, porém, digo-vos que não resistais ao (que é) mau; mas, se alguém te ferir na tua face direita, apresenta-lhe também a outra;

[[v47-5-40]]

^<<v47-5-40,40>>^ e ao que quer chamar-te a juízo para te tirar a túnica, cede-Ihe também a capa. (ver nota)

[[v47-5-41]]

^<<v47-5-41,41>>^ Se alguém te forçar a dar mil passos, vai com ele mais dois mil. (ver nota)

[[v47-5-42]]

^<<v47-5-42,42>>^ Dá a quem te pede, e não voltes as costas ao que deseja que lhe emprestes.

[[v47-5-43]]

^<<v47-5-43,43>>^ Ouvistes que foi dito: Amarás o teu próximo (Lv. 19, 18) e aborrecerás o teu inimigo.

[[v47-5-44]]

^<<v47-5-44,44>>^ Eu, porém, digo-vos: Amai os vossos inimigos, fazei bem aos que vos odeiam, e orai pelos que vos maltratam e vos perseguem.

[[v47-5-45]]

^<<v47-5-45,45>>^ Deste modo sereis filhos do vosso Pai que está nos céus, o qual faz nascer o sol sobre maus e bons, e manda a chuva sobre os justos e injustos.

[[v47-5-46]]

^<<v47-5-46,46>>^ Porque, se amais (sòmente) os que vos amara, que recompensa haveis de ter? Não fazem os publicanos também o mesmo?

[[v47-5-47]]

^<<v47-5-47,47>>^ E se saudardes sòmente os vossos irmãos, que fazeis (nisso) de especial? Não fazem também assim os próprios gentios?

[[v47-5-48]]

^<<v47-5-48,48>>^ Sede pois perfeitos, como vosso Pai celestial é perfeito.

'''

xref:047-sao-mateus/047-sao-mateus-004.adoc#v47-4-0[&#60; Capítulo Anterior] | <<v47-5-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-006.adoc#v47-6-0[Próximo Capítulo &#62;]