include::./index.adoc[]

[[v47-12-0]]
=== São Mateus, 12
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* São Mateus 12 trata de diversos eventos e ensinamentos de Jesus, incluindo curas no sábado, a blasfêmia contra o Espírito Santo e a verdadeira família de Jesus. Dentre os temas abordados, destacam-se a importância da misericórdia, a autoridade de Jesus e a necessidade de se produzir bons frutos. A seguir, seguem cinco versículos relacionados com esses temas:
* Lucas 6:36 - "Sede misericordiosos, como também é misericordioso vosso Pai." Jesus ensina a seus discípulos a importância da misericórdia, mostrando que devemos agir com os outros da mesma forma que Deus age conosco.
* João 5:27 - "E deu-lhe autoridade para julgar, porque é o Filho do Homem." Neste versículo, Jesus fala sobre sua própria autoridade para julgar, mostrando que ele é o Filho de Deus e tem poder sobre todas as coisas.
* Lucas 6:43 - "Porque não há árvore boa que dê fruto ruim, nem tampouco árvore ruim que dê fruto bom." Aqui, Jesus enfatiza a importância de produzir bons frutos em nossa vida, mostrando que é impossível produzir frutos bons se não houver um coração bom.
* Efésios 2:8-9 - "Porque pela graça sois salvos, por meio da fé; e isto não vem de vós, é dom de Deus; não vem das obras, para que ninguém se glorie." Este versículo destaca a importância da graça de Deus e da fé em Jesus para nossa salvação, mostrando que não é por nossas obras que alcançamos a salvação, mas sim pelo dom de Deus.
* Lucas 8:21 - "Respondeu-lhes, porém, ele: Minha mãe e meus irmãos são aqueles que ouvem a palavra de Deus e a executam." Neste versículo, Jesus mostra que a verdadeira família é composta não apenas de nossos parentes de sangue, mas daqueles que ouvem e obedecem a palavra de Deus.
****

[[v47-12-1]]

^<<v47-12-1,1>>^ Naquele tempo, num dia de sábado, passava Jesus por umas searas, e seus discípulos, tendo fome, começaram a colher espigas e a comê-las.

[[v47-12-2]]

^<<v47-12-2,2>>^ Vendo isto os fariseus, disseram-lhe: "Eis que os teus discípulos fazem o que não é permitido fazer ao sábado."

[[v47-12-3]]

^<<v47-12-3,3>>^ Jesus respondeu-lhes: "Não lestes o que fez David quando teve fome, ele e os que com ele iam?

[[v47-12-4]]

^<<v47-12-4,4>>^ Como entrou na casa de Deus, e comeu os pães da proposição, os quais não era licito comer, nem a ele, nem aos que com ele iam, mas só aos sacerdotes?

[[v47-12-5]]

^<<v47-12-5,5>>^ Não lestes na lei que aos sábados os sacerdotes no templo violam o sábado e ficam sem culpa?

[[v47-12-6]]

^<<v47-12-6,6>>^ Ora eu digo-vos que aqui está alguém que é maior que o templo.

[[v47-12-7]]

^<<v47-12-7,7>>^ Se vós soubésseis o que quer dizer: Quero a misericórdia e não sacrifício (Os. 6, 6), jamais condenaríeis inocentes.

[[v47-12-8]]

^<<v47-12-8,8>>^ Porque o Filho do homem é senhor do próprio sábado."

[[v47-12-9]]

^<<v47-12-9,9>>^ Partindo dali, foi à sinagoga deles,

[[v47-12-10]]

^<<v47-12-10,10>>^ onde se encontrava um homem que tinha seca uma das mãos; e eles, para terem de que o acusar, perguntaram-lhe: "É permitido curar aos sábados?"

[[v47-12-11]]

^<<v47-12-11,11>>^ Ele respondeu-Ihes: "Que homem haverá entre vós que, tendo uma ovelha, se esta cair no dia de sábado a uma cova, não a tome, e não a tire de lá?

[[v47-12-12]]

^<<v47-12-12,12>>^ Ora quanto mais vale um homem do que uma ovelha? Logo é permitido fazer bem no dia de sábado."

[[v47-12-13]]

^<<v47-12-13,13>>^ Então disse ao homem: "Estende a tua mão." Ele estendeu-a, e ela tornou-se sã como a outra.

[[v47-12-14]]

^<<v47-12-14,14>>^ Os fariseus, saindo dali, tiveram conselho contra ele sobre o modo de o levarem à morte. (ver nota)

[[v47-12-15]]

^<<v47-12-15,15>>^ Jesus, sabendo isto, retirou-se daquele lugar. Muitos seguiram-no, e curou-os a todos.

[[v47-12-16]]

^<<v47-12-16,16>>^ Ordenou-lhes que não o descobrissem,

[[v47-12-17]]

^<<v47-12-17,17>>^ para que se cumprisse o que tinha sido anunciado pelo profeta Isaías (Is. 42, 1-4):

[[v47-12-18]]

^<<v47-12-18,18>>^ Eis o meu servo, que eu escolhi, o meu amado, em quem a minha alma pôs as suas complacências. Farei repousar sobre ele o meu Espirito, e ele anunciará a justiça às nações.

[[v47-12-19]]

^<<v47-12-19,19>>^ Não contenderá, nem clamará, nem ouvirá alguém a sua voz nas praças;

[[v47-12-20]]

^<<v47-12-20,20>>^ não quebrará a cana rachada, nem apagará a torcida que fumega, até que faça triunfar a justiça; (ver nota)

[[v47-12-21]]

^<<v47-12-21,21>>^ e as nações esperarão no seu nome.

[[v47-12-22]]

^<<v47-12-22,22>>^ Então trouxeram-lhe um endemoninhado, cego e mudo, e ele o curou, de sorte que falava e via.

[[v47-12-23]]

^<<v47-12-23,23>>^ E ficaram estupefactas todas as multidões, e diziam: "Não será este o Filho de David?"

[[v47-12-24]]

^<<v47-12-24,24>>^ Mas os fariseus, ouvindo isto, disseram: "Este não lança fora os demônios, senão por virtude de Belzebu, príncipe dos demônios."

[[v47-12-25]]

^<<v47-12-25,25>>^ Porém, Jesus, conhecendo os pensamentos deles, disse-lhes: "Todo o reino, dividido contra si mesmo, será destruído; e toda a cidade ou família, dividida contra si mesma, não subsistirá.

[[v47-12-26]]

^<<v47-12-26,26>>^ Ora, se Satanás lança fora a Satanás, está dividido contra si mesmo; como subsistirá, pois, o seu reino?

[[v47-12-27]]

^<<v47-12-27,27>>^ E se eu lanço fora os demônios por virtude de Belzebu, por virtude de quem os expelem vossos filhos? Por isso é que eles serão os vossos juízes.

[[v47-12-28]]

^<<v47-12-28,28>>^ Se eu, porém, lanço fora os demônios pela virtude do Espírito de Deus, é chegado a vós o reino de Deus.

[[v47-12-29]]

^<<v47-12-29,29>>^ Como pode alguém entrar na casa de um valente, e saquear os seus móveis, se antes não prender o valente? Só então lhe poderá saquear a casa. (ver nota)

[[v47-12-30]]

^<<v47-12-30,30>>^ Quem não é comigo, é contra mim; e quem não junta comigo, derperdiça.

[[v47-12-31]]

^<<v47-12-31,31>>^ Por isso vos digo: Todo o pecado e blasfêmia será perdoado aos homens, porém a blasfêmia contra o Espírito Santo não será perdoada.

[[v47-12-32]]

^<<v47-12-32,32>>^ Todo o que disser alguma palavra contra o Filho do homem, lhe será perdoado; porém o que a disser contra o Espírito Santo, não lhe será perdoado, nem neste século nem no futuro.

[[v47-12-33]]

^<<v47-12-33,33>>^ Ou dizei que a árvore é boa e o seu fruto bom, ou dizei que a árvore é má e o seu fruto mau, pois que pelo fruto se conhece a árvore.

[[v47-12-34]]

^<<v47-12-34,34>>^ Raça de víboras, como podeis dizer coisas boas, vós que sois maus? Porque a boca fala da abundância do coração.

[[v47-12-35]]

^<<v47-12-35,35>>^ O homem bom tira boas coisas do seu bom tesouro, e o mau homem tirá más coisas do seu mau tesouro.

[[v47-12-36]]

^<<v47-12-36,36>>^ Ora eu digo-vos que de qualquer palavra ociosa que tiverem proferido os homens, darão conta dela no dia do juízo.

[[v47-12-37]]

^<<v47-12-37,37>>^ Porque pelas tuas palavras será justificado ou condenado."

[[v47-12-38]]

^<<v47-12-38,38>>^ Então lhe replicaram alguns dos escribas e fariseus, dizendo: "Mestre, nós desejávamos ver algum prodígio teu.

[[v47-12-39]]

^<<v47-12-39,39>>^ Ele respondeu-lhes: "Esta geração má e adúltera pede um prodígio, mas não lhe será dado outro prodígio, senão o prodígio do profeta Jonas.

[[v47-12-40]]

^<<v47-12-40,40>>^ Porque, assim como Jonas esteve no ventre da baleia três dias e três noites (Jn. 2, 1), assim estará o Filho do homem três dias e três noites no seio da terra.

[[v47-12-41]]

^<<v47-12-41,41>>^ Os habitantes de Ninive se levantarão no dia do juízo contra esta geração, e a condenação, porque fizeram penitência com a pregação de Jonas. Ora aqui está quem é mais do que Jonas.

[[v47-12-42]]

^<<v47-12-42,42>>^ A rainha do meio-dia levantar-se-á no dia do juízo contra esta geração e a condenará, porque veio dos confins da terra a ouvir a sabedoria de Salomão. Ora aqui está quem é mais do que Salomão.

[[v47-12-43]]

^<<v47-12-43,43>>^ Quando o espírito imundo saiu de um homem, anda errando por lugares áridos, à busca de repouso, e não o encontra. (ver nota)

[[v47-12-44]]

^<<v47-12-44,44>>^ Então diz: Voltarei para minha casa, donde saí. E, quando vem, a encontra desocupada, varrida e adornada.

[[v47-12-45]]

^<<v47-12-45,45>>^ Então vai, e toma consigo outros sete espíritos piores do que ele, e, entrando, habitam ali; e o último estado daquele homem torna-se pior que o primeiro. Assim também acontecerá a esta geração perversa."

[[v47-12-46]]

^<<v47-12-46,46>>^ Estando ele ainda a falar ao povo, eis que sua mãe e seus irmãos se achavam fora, desejando falar-lhe.

[[v47-12-47]]

^<<v47-12-47,47>>^ Alguém disse-lhe: "Tua mãe e teus irmãos estão ali fora, e desejam falar-te." (ver nota)

[[v47-12-48]]

^<<v47-12-48,48>>^ Ele, porém, respondeu ao que falava: "Quem é minha mãe e quem são os meus irmãos?"

[[v47-12-49]]

^<<v47-12-49,49>>^ E, estendendo a mão para os seus discípulos, disse: "Eis minha mãe e meus irmãos.

[[v47-12-50]]

^<<v47-12-50,50>>^ Porque todo aquele que fizer a vontade de meu Pai, que está nos céus, esse é meu irmão e minha irmã e minha mãe."

'''

xref:047-sao-mateus/047-sao-mateus-011.adoc#v47-11-0[&#60; Capítulo Anterior] | <<v47-12-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-013.adoc#v47-13-0[Próximo Capítulo &#62;]