include::./index.adoc[]

[[v47-19-0]]
=== São Mateus, 19
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* São Mateus 19 apresenta ensinamentos de Jesus sobre o divórcio, a riqueza e a salvação. Jesus fala sobre como o divórcio não estava nos planos originais de Deus, como é difícil para os ricos entrarem no reino dos céus e como seguir a Jesus exige sacrifícios e renúncias. A seguir, cinco versículos relacionados com os temas abordados em São Mateus 19:
* Gênesis 2:24: "Por isso, o homem deixará seu pai e sua mãe e se unirá à sua mulher, e eles se tornarão uma só carne." Este versículo é citado por Jesus em Mateus 19:5, quando ele fala sobre a importância do casamento e como Deus criou o homem e a mulher para serem uma só carne.
* Provérbios 11:28: "Quem confia em suas riquezas cairá, mas os justos florescerão como a folhagem verdejante." Em Mateus 19:23-24, Jesus fala sobre como é difícil para os ricos entrarem no reino dos céus, e este versículo mostra como a confiança na riqueza pode levar à queda.
* Marcos 10:29-30: "Em verdade vos digo que ninguém há que tenha deixado casa, ou irmãos, ou irmãs, ou mãe, ou pai, ou filhos, ou campos por amor de mim e do evangelho, que não receba cem vezes tanto agora, no presente, em casas, irmãos, irmãs, mães, filhos e campos, com perseguições, e no mundo vindouro a vida eterna." Este versículo é citado por Jesus em Mateus 19:29, quando ele fala sobre os sacrifícios que devem ser feitos para seguir a Jesus e como a recompensa é grande.
* Mateus 5:32: "Eu, porém, vos digo que todo aquele que se divorcia de sua mulher, exceto por causa de infidelidade, a expõe a tornar-se adúltera; e aquele que casar com a mulher divorciada comete adultério." Em Mateus 19:3-9, Jesus fala sobre o divórcio e como isso não estava nos planos originais de Deus.
* Mateus 19:21: "Jesus disse a ele: 'Se queres ser perfeito, vai, vende teus bens, dá aos pobres e terás um tesouro no céu; depois vem e segue-me.'" Este versículo mostra como seguir a Jesus exige sacrifícios e renúncias, como também é destacado em Mateus 19:16-22, quando Jesus fala com o jovem rico.
****

[[v47-19-1]]

^<<v47-19-1,1>>^ Tendo Jesus acabado estes discursos, partiu da Galileia e foi para o território da Judeia, além do Jordão.

[[v47-19-2]]

^<<v47-19-2,2>>^ Uma grande multidão o seguia, e curou os seus doentes.

[[v47-19-3]]

^<<v47-19-3,3>>^ Foram ter com ele os fariseus para o tentar, e disseram-lhe: "É lícito a um homem repudiar sua mulher por qualquer motivo?"

[[v47-19-4]]

^<<v47-19-4,4>>^ Ele respondeu-lhes: "Não lestes que no principio, o Criador fez o homem e a mulher, e disse:

[[v47-19-5]]

^<<v47-19-5,5>>^ Por isso deixará o homem pai e mãe, e juntar-se-á com sua mulher, e os dois serão uma só carne (Gn. 2, 24).

[[v47-19-6]]

^<<v47-19-6,6>>^ Por isso não mais são dois, mas uma só carne. Portanto não separe o homem o que Deus juntou."

[[v47-19-7]]

^<<v47-19-7,7>>^ "Porque mandou, pois, Moisés, replicaram eles, dar (o homem, a sua mulher) libelo de repúdio, e separar-se (dela) ?"

[[v47-19-8]]

^<<v47-19-8,8>>^ Respondeu-lhes : "Porque Moisés, por causa da dureza do vosso coração, permitiu-vos repudiar vossas mulheres; mas no principio não foi assim.

[[v47-19-9]]

^<<v47-19-9,9>>^ Eu, pois, digo-vos que todo aquele que repudiar sua mulher, a não ser por causa de fornicação, e casar com outra, comete adultério; e o que se casar com uma repudiada, comete adultério." (ver nota)

[[v47-19-10]]

^<<v47-19-10,10>>^ Disseram-lhe os discípulos: Se tal é a condição do homem a respeito de sua mulher, não convém casar.

[[v47-19-11]]

^<<v47-19-11,11>>^ Ele respondeu-lhes: "Nem todos compreendem esta palavra, mas sòmente aqueles a quem foi concedido.

[[v47-19-12]]

^<<v47-19-12,12>>^ Porque há eunucos que nasceram assim do ventre de sua mãe; há eunucos a quem os homens fizeram tais; e há eunucos que a si mesmos se fizeram eunucos por amor do reino dos céus. Quem pode compreender isto, compreenda."

[[v47-19-13]]

^<<v47-19-13,13>>^ Então lhe foram apresentados vários meninos para que lhes impusesse as mãos e orasse por eles. Mas os discípulos increpavam-nos.

[[v47-19-14]]

^<<v47-19-14,14>>^ Jesus, porém, disse-lhes: "Deixai os meninos, e não os impeçais de vir a mim, porque deles é o reino dos céus."

[[v47-19-15]]

^<<v47-19-15,15>>^ E, tendo-lhes imposto as mãos, partiu dali.

[[v47-19-16]]

^<<v47-19-16,16>>^ Aproximando-se dele um jovem, disse-lhe: "Mestre, que hei-de eu fazer de bom para alcançar a vida eterna?"

[[v47-19-17]]

^<<v47-19-17,17>>^ Jesus respondeu-lhe: "Porque me interrogas acerca do que é bom? Um só é bom, Deus. Porém, se queres entrar na vida (eterna) guarda os mandamentos." (ver nota)

[[v47-19-18]]

^<<v47-19-18,18>>^ "Quais?", perguntou ele. Jesus disse: "Não matarás, não cometerás adultério, não roubarás, não dirás falso testemunho.

[[v47-19-19]]

^<<v47-19-19,19>>^ Honra teu pai e tua mãe, e ama o teu próximo como a ti mesmo (Ex. 20, 12-16; Lv. 19, 18; Dt. 5, 16-20)."

[[v47-19-20]]

^<<v47-19-20,20>>^ Disse-lhe o jovem: "Tenho observado tudo isso desde a minha infância. Que me falta ainda?"

[[v47-19-21]]

^<<v47-19-21,21>>^ Jesus disse-lhe: "Se queres ser perfeito, vai, vende o que tens, e dá-o aos pobres, e terás um tesouro no céu; depois vem e segue-me."

[[v47-19-22]]

^<<v47-19-22,22>>^ O jovem, porém, tendo ouvido esta palavra, retirou-se triste, porque tinha muitos bens.

[[v47-19-23]]

^<<v47-19-23,23>>^ Jesus disse a seus discípulos: "Em verdade vos digo que um rico dificilmente entrará no reino dos céus.

[[v47-19-24]]

^<<v47-19-24,24>>^ Digo-vos mais: É mais fácil passar um camelo pelo fundo de uma agulha, que entrar um rico no reino dos céus."

[[v47-19-25]]

^<<v47-19-25,25>>^ Os discípulos, ouvidas estas palavras, ficaram muito admirados, dizendo: "Quem poderá pois salvar-se?

[[v47-19-26]]

^<<v47-19-26,26>>^ Porém, Jesus, olhando para eles, disse-lhes: "Aos homens isto é impossível, mas a Deus tudo é possível."

[[v47-19-27]]

^<<v47-19-27,27>>^ Então Pedro, tomando a palavra, disse-lhe: "Eis que abandonámos tudo e te seguimos; que haverá então para nós?"

[[v47-19-28]]

^<<v47-19-28,28>>^ Jesus disse-lhes: "Em verdade vos digo que, no dia da regeneração, quando o Filho do homem estiver sentado no trono da sua glória, vós, que me seguistes, também estareis sentados sobre doze tronos, e julgareis as doze tribos de Israel.

[[v47-19-29]]

^<<v47-19-29,29>>^ E todo o que deixar a casa, ou os irmãos ou irmãs, ou o pai ou a mãe, ou os filhos, ou os campos, por causa do meu nome, receberá o cêntuplo, e possuirá a vida eterna.

[[v47-19-30]]

^<<v47-19-30,30>>^ Muitos primeiros serão os últimos, e muitos últimos serão os primeiros. (ver nota)

'''

xref:047-sao-mateus/047-sao-mateus-018.adoc#v47-18-0[&#60; Capítulo Anterior] | <<v47-19-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-020.adoc#v47-20-0[Próximo Capítulo &#62;]