include::./index.adoc[]

[[v47-11-0]]
=== São Mateus, 11
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 11 de São Mateus apresenta a continuação do ministério de Jesus, que começa a enfrentar a incredulidade de algumas pessoas e a rejeição de outras. Ele também envia seus discípulos para realizar milagres e pregar o evangelho. Além disso, Jesus se dirige diretamente ao povo, chamando-os para que venham a Ele e encontrem descanso para suas almas. Abaixo estão cinco versículos relacionados com os temas abordados em São Mateus 11:
* Salmo 86:5: "Pois tu, Senhor, és bom, e pronto para perdoar, e abundante em benignidade para com todos os que te invocam." Jesus convida as pessoas cansadas e sobrecarregadas a virem a Ele e encontrar descanso em sua graça e bondade.
* Isaías 55:1: "Ó vós, todos os que tendes sede, vinde às águas, e os que não tendes dinheiro, vinde, comprai, e comei; sim, vinde, comprai, sem dinheiro e sem preço, vinho e leite." Jesus oferece a todos, independentemente da sua situação financeira ou social, a oportunidade de encontrar vida e satisfação nele.
* João 14:6: "Disse-lhe Jesus: Eu sou o caminho, e a verdade e a vida; ninguém vem ao Pai, senão por mim." Jesus afirma que Ele é a única maneira de se chegar a Deus e encontrar verdadeira vida e paz.
* Mateus 11:28-29: "Vinde a mim, todos os que estai cansados e oprimidos, e eu vos aliviarei. Tomai sobre vós o meu jugo, e aprendei de mim, que sou manso e humilde de coração; e encontrareis descanso para as vossas almas." Jesus convida as pessoas a se aproximarem dele, apegando-se a ele e aprendendo dele, para encontrar descanso e paz em suas almas.
* Lucas 9:23: "Dizia a todos: Se alguém quer vir após mim, a si mesmo se negue, dia a dia tome a sua cruz, e siga-me." Jesus chama as pessoas para deixar tudo e segui-lo, assumindo sua cruz diariamente e encontrando vida em união com Ele.
****

[[v47-11-1]]

^<<v47-11-1,1>>^ Tendo Jesus acabado de dar estas instruções aos seus doze discípulos, partiu dali para ir ensinar e pregar nas cidades deles.

[[v47-11-2]]

^<<v47-11-2,2>>^ E como João, estando no cárcere, tivesse ouvido falar das obras de Cristo, enviou dois de seus discípulos,

[[v47-11-3]]

^<<v47-11-3,3>>^ a perguntar-lhe: "És tu aquele que há-de vir, ou devemos esperar outro?" (ver nota)

[[v47-11-4]]

^<<v47-11-4,4>>^ Jesus respondeu-lhes: "Ide e contai a João o que ouvistes e vistes:

[[v47-11-5]]

^<<v47-11-5,5>>^ Os cegos vêem, os coxos andam, os leprosos são limpos, os surdos ouvem, os mortos ressuscitam, os pobres são evangelizados;

[[v47-11-6]]

^<<v47-11-6,6>>^ e bem-aventurado aquele que não encontrar em mim motivo de escândalo."

[[v47-11-7]]

^<<v47-11-7,7>>^ Tendo eles partido, começou Jesus a falar de João às turbas: "Que fostes vós ver ao deserto? Uma cana agitada pelo vento?

[[v47-11-8]]

^<<v47-11-8,8>>^ Mas que fostes ver? Um homem vestido de roupas delicadas? Mas os que vestem roupas delicadas vivem nos palácios dos reis.

[[v47-11-9]]

^<<v47-11-9,9>>^ Mas que fostes ver? Um profeta? Sim, vos digo eu, e ainda mais do que profeta.

[[v47-11-10]]

^<<v47-11-10,10>>^ Porque este é aquele de quem está escrito: Eis que eu envio o meu mensageiro adiante de ti, o qual te preparará o caminho diante de ti.

[[v47-11-11]]

^<<v47-11-11,11>>^ Na verdade vos digo que entre os nascidos das mulheres não veio ao mundo outro maior que João Baptista. Entretanto, o menor no reino dos céus é maior do que ele.

[[v47-11-12]]

^<<v47-11-12,12>>^ Desde os dias de João Baptista até agora, o reino dos céus adquire-se à força, e são os violentos que o arrebatam.

[[v47-11-13]]

^<<v47-11-13,13>>^ Todos os profetas e a lei profetizaram até João.

[[v47-11-14]]

^<<v47-11-14,14>>^ E, se vós quereis compreender, ele mesmo é o Elias que há-de vir.

[[v47-11-15]]

^<<v47-11-15,15>>^ O que tem ouvidos para ouvir, ouça. (ver nota)

[[v47-11-16]]

^<<v47-11-16,16>>^ A quem hei-de eu comparar esta geração? É semelhante aos rapazes que estão sentados na praça, e que gritam aos seus companheiros,

[[v47-11-17]]

^<<v47-11-17,17>>^ dizendo: Tocámos flauta, e não bailastes; entoámos endechas e não chorastes.

[[v47-11-18]]

^<<v47-11-18,18>>^ Veio João, que não comia nem bebia, e dizem : Ele tem demônio.

[[v47-11-19]]

^<<v47-11-19,19>>^ Veio o Filho do homem, que come e bebe, e dizem: Eis um glutão e um bebedor de vinho, um amigo dos publicanos e dos pecadores. Mas a sabedoria (divina) foi justificada por suas obras."

[[v47-11-20]]

^<<v47-11-20,20>>^ Então começou a exprobar às cidades em que tinham sido operados muitos dos seus milagres, o não terem feito penitência.

[[v47-11-21]]

^<<v47-11-21,21>>^ "Ai de ti, Corozain! Ai de ti, Betsaida! porque, se em Tiro e em Sidónia tivessem sido feitos os milagres que se realizaram em vós, há muito tempo que teriam feito penitência em cilísio e em cinza,

[[v47-11-22]]

^<<v47-11-22,22>>^ Por isso vos digo que haverá menor rigor para Tiro e Sidónia no dia do juízo, que para vós.

[[v47-11-23]]

^<<v47-11-23,23>>^ E tu, Cafarnaum, elevar-te-ás porventura até ao céu? Não, hás-de ser abatida até ao inferno (Is. 14,13-15). Se em Sodoma tivessem sido feitos os milagres que se fizeram em ti, ainda hoje existiria.

[[v47-11-24]]

^<<v47-11-24,24>>^ Por isso vos digo que no dia do juízo haverá menos rigor para a terra de Sodoma que para ti."

[[v47-11-25]]

^<<v47-11-25,25>>^ Então Jesus, falando novamente, disse: "Graças te dou, ó Pai, Senhor do céu e da terra, porque escondeste estas coisas aos sábios e aos prudentes, e as revelaste aos pequeninos.

[[v47-11-26]]

^<<v47-11-26,26>>^ Assim é, ó Pai, porque assim foi do teu agrado.

[[v47-11-27]]

^<<v47-11-27,27>>^ Todas as coisas me foram entregues por meu Pai; e ninguém conhece o Filho senão o Pai; nem alguém conhece o Pai senão o Filho, e aquele a quem o Filho o quiser revelar.

[[v47-11-28]]

^<<v47-11-28,28>>^ Vinde a mim todos os que estais fatigados e carregados, e eu vos aliviarei.

[[v47-11-29]]

^<<v47-11-29,29>>^ Tomai sobre vós o meu jugo, e aprendei de mim, que sou manso e humilde de coração, e achareis descanso para as vossas almas.

[[v47-11-30]]

^<<v47-11-30,30>>^ Porque o meu jugo é suave, e o meu peso leve."

'''

xref:047-sao-mateus/047-sao-mateus-010.adoc#v47-10-0[&#60; Capítulo Anterior] | <<v47-11-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-012.adoc#v47-12-0[Próximo Capítulo &#62;]