include::./index.adoc[]

[[v47-21-0]]
=== São Mateus, 21
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* São Mateus 21 apresenta a entrada triunfal de Jesus em Jerusalém, bem como a purificação do templo e a controvérsia com os líderes religiosos. Alguns dos temas principais deste capítulo incluem a autoridade de Jesus, a sua missão messiânica e a rejeição dos líderes religiosos. A seguir estão cinco versículos relacionados com esses temas:
* Isaías 62:11: "Eis que o Senhor fez ouvir até às extremidades da terra: Dizei à filha de Sião: Eis que vem o teu Salvador; vem com ele a sua recompensa, e diante dele, o seu galardão." Este versículo profético de Isaías descreve a vinda do Salvador, que é uma referência ao Messias. Jesus é o cumprimento desta profecia e o seu papel como o Salvador é enfatizado em São Mateus 21.
* Salmos 118:22-23: "A pedra que os construtores rejeitaram, essa foi posta como pedra angular. Isso veio do Senhor e é maravilhoso aos nossos olhos." Jesus citou este versículo quando falava sobre a sua rejeição pelos líderes religiosos. Embora eles o tenham rejeitado, ele se tornou a pedra angular da igreja e a fonte da salvação.
* Isaías 56:7: "Fá-los-ei chegar ao meu santo monte e alegrá-los-ei na minha casa de oração; os seus holocaustos e os seus sacrifícios serão aceitos no meu altar; porque a minha casa será chamada casa de oração para todos os povos." Este versículo profético de Isaías fala da casa de oração como um lugar de encontro com Deus para todas as nações. Jesus citou este versículo quando expulsou os vendedores do templo, indicando que o templo deveria ser um lugar de adoração a Deus e não de comércio.
* Salmos 69:9: "Pois o zelo da tua casa me consome, e as afrontas dos que te afrontam caem sobre mim." Este salmo de Davi fala do zelo de Deus pela sua casa e do sofrimento do justo por causa da sua fidelidade a Deus. Jesus demonstrou zelo pela casa de Deus quando expulsou os vendedores do templo, e mais tarde sofreu por sua fidelidade a Deus.
* Isaías 53:3: "Era desprezado e o mais rejeitado entre os homens, homem de dores e experimentado nos sofrimentos; e, como um de quem os homens escondiam o rosto, era desprezado, e não fizemos dele caso algum." Este versículo profético de Isaías descreve o sofrimento do Servo Sofredor, que é uma figura messiânica. Jesus cumpriu esta profecia ao ser rejeitado e sofrer pelos pecados da humanidade. A sua rejeição pelos líderes religiosos é um tema importante em São Mateus 21.
****

[[v47-21-1]]

^<<v47-21-1,1>>^ Aproximando-se de Jerusalém, e, chegando a Betfagé, junto do monte das Oliveiras, enviou Jesus dois dos discípulos,

[[v47-21-2]]

^<<v47-21-2,2>>^ dizendo-lhes: "Ide à aldeia que está defronte de vós, e logo encontrareis presa uma jumenta e o seu jumentinho com ela. Desprendei-a, e trazei-ma.

[[v47-21-3]]

^<<v47-21-3,3>>^ Se alguém vos disser alguma coisa, dizei que o Senhor precisa deles, e logo os deixará trazer."

[[v47-21-4]]

^<<v47-21-4,4>>^ Tudo isto aconteceu para que se cumprisse o que tinha sido anunciado pelo profeta (Zc. 9, 9):

[[v47-21-5]]

^<<v47-21-5,5>>^ Dizei à filha de Sião: Eis que o teu rei vem a ti manso, montado sobre uma jumenta, e sobre um jumentinho, filho da que leva o jugo.

[[v47-21-6]]

^<<v47-21-6,6>>^ Indo os discípulos, fizeram como Jesus lhes ordenara.

[[v47-21-7]]

^<<v47-21-7,7>>^ Trouxeram a jumenta e o jumentinho, puseram sobre eles os seus vestidos, e fizeram-no montar em cima.

[[v47-21-8]]

^<<v47-21-8,8>>^ O povo, em grande número, estendia no caminho os seus mantos; outros cortavam ramos de árvores, e juncavam com eles a estrada.

[[v47-21-9]]

^<<v47-21-9,9>>^ E as multidões que o precediam, e as que iam atrás, gritavam, dizendo: "Hosana ao Filho de David! Bendito o que vem em nome do Senhor ! Hosana no mais alto dos céus ! "

[[v47-21-10]]

^<<v47-21-10,10>>^ Quando entrou em Jerusalém, alvoroçou-se toda a cidade. Dizia-se: "Quem é este?"

[[v47-21-11]]

^<<v47-21-11,11>>^ E a multidão respondia: "Este é Jesus, o profeta de Nazaré e da Galileia."

[[v47-21-12]]

^<<v47-21-12,12>>^ Jesus entrou no templo de Deus, expulsou todos os que lá vendiam e compravam; e derrubou as mesas dos banqueiros e as cadeiras dos que vendiam pombas.

[[v47-21-13]]

^<<v47-21-13,13>>^ e disse-lhes : "Está escrito: A minha casa será chamada casa de oração (Is. 56, 7): mas vós fizeste dela covil de ladrões (Je. 7, 11)."

[[v47-21-14]]

^<<v47-21-14,14>>^ Aproximaram-se dele no templo cegos e coxos, e os curou.

[[v47-21-15]]

^<<v47-21-15,15>>^ Quando os príncipes dos sacerdotes e os escribas viram as maravilhas operadas por ele, e os meninos gritando no templo, e dizendo: Hosana ao Filho de David! indignaram-se.

[[v47-21-16]]

^<<v47-21-16,16>>^ e disseram-lhe: "Ouves o que estes dizem?" E Jesus respondeu: "Sim. Nunca lestes: Da boca das crianças e meninos de peito fizestes sair um perfeito louvor ? (Ps. 8, 3)."

[[v47-21-17]]

^<<v47-21-17,17>>^ Tendo-os deixado, retirou-se para fora da cidade, para Betânia; e lá passou a noite.

[[v47-21-18]]

^<<v47-21-18,18>>^ Pela manhã, quando voltava para a cidade, teve fome.

[[v47-21-19]]

^<<v47-21-19,19>>^ Vendo uma figueira junto do caminho, aproximou-se dela, e não encontrou nela senão folhas, e disse-lhe: "Nunca mais nasça fruto de ti." E, imediatamente, a figueira secou. (ver nota)

[[v47-21-20]]

^<<v47-21-20,20>>^ Vendo isto os discípulos, admiraram-se e disseram: "Como secou a figueira imediatamente?"

[[v47-21-21]]

^<<v47-21-21,21>>^ Jesus respondeu: "Na verdade vos digo que, se tiverdes fé e não duvidardes, não só fareis o que foi feito a esta figueira, mas ainda se disserdes a este monte: Sai daí, e lança-te no mar, assim se fará

[[v47-21-22]]

^<<v47-21-22,22>>^ E tudo o que pedirdes com fé na oração o recebereis."

[[v47-21-23]]

^<<v47-21-23,23>>^ Tendo ido ao templo, os príncipes dos sacerdotes e os anciãos do povo aproximaram-se dele, quando estava ensinando, e disseram-lhe: "Com que autoridade fazes estas coisas? E quem te deu tal direito ? "

[[v47-21-24]]

^<<v47-21-24,24>>^ Jesus respondeu-lhes: "Também eu vos farei uma pergunta: Se me responderdes, eu vos direi com que direito faço estas coisas.

[[v47-21-25]]

^<<v47-21-25,25>>^ Donde era o baptismo de João? Do céu ou dos homens?" Mas eles reflectiam consigo:

[[v47-21-26]]

^<<v47-21-26,26>>^ Se lhe dissermos que é do céu, ele dirá: Porque não crestes, pois, nele? Se lhe dissermos que é dos homens, tememos o povo. Porque todos tinham João como um profeta.

[[v47-21-27]]

^<<v47-21-27,27>>^ Portanto, responderam a Jesus: "Não sabemos." Ele disse-lhes também: "Pois nem eu vos digo com que direito faço estas coisas."

[[v47-21-28]]

^<<v47-21-28,28>>^ "Que vos parece? Um homem tinha dois filhos. Aproximando-se do primeiro, disse-lhe: Filho, vai trabalhar hoje na minha vinha.

[[v47-21-29]]

^<<v47-21-29,29>>^ Ele respondeu: Não quero. Mas depois, tocado de arrependimento, foi.

[[v47-21-30]]

^<<v47-21-30,30>>^ Dirigindo-se em seguida ao outro, falou-lhe do mesmo modo. E, ele, respondeu: Eu vou, senhor, mas não foi.

[[v47-21-31]]

^<<v47-21-31,31>>^ Qual dos dois fez a vontade ao pai?" Eles responderam: "O primeiro." Jesus disse-lhes: "Na verdade vos digo que os publicanos e meretrizes vos levarão a dianteira para o reino de Deus.

[[v47-21-32]]

^<<v47-21-32,32>>^ Porque veio a vós João no caminho da justiça, e não crestes nele; e os publicanos e as meretrizes creram nele. E vós, vendo isto, nem assim fizestes penitência depois, para crerdes nele.

[[v47-21-33]]

^<<v47-21-33,33>>^ Ouvi outra parábola: Havia um pai de família, que plantou uma vinha, e a cercou com uma sebe, e cavou nela um lagar, e edificou uma torre (Is. 6, 1-2); depois, arrendou-a a uns vinhateiros, e ausentou-se daquela região.

[[v47-21-34]]

^<<v47-21-34,34>>^ Estando próxima a estação dos frutos, enviou os seus servos aos vinhateiros, para receberem os frutos da sua vinha.

[[v47-21-35]]

^<<v47-21-35,35>>^ Mas os vinhateiros, agarrando os servos, feriram um, mataram outro, e a outro apedrejaram.

[[v47-21-36]]

^<<v47-21-36,36>>^ Enviou novamente outros servos em maior número do que os primeiros, e fizeram-lhes o mesmo.

[[v47-21-37]]

^<<v47-21-37,37>>^ Por último enviou-lhes seu filho, dizendo: Hão-de ter respeito a meu filho.

[[v47-21-38]]

^<<v47-21-38,38>>^ Porém, os vinhateiros, vendo o filho, disseram entre si: Este é o herdeiro; vamos, matemo-lo, e teremos a sua herança.

[[v47-21-39]]

^<<v47-21-39,39>>^ E, lançando-lhe as mãos, puseram-no fora da vinha, e mataram-no.

[[v47-21-40]]

^<<v47-21-40,40>>^ Quando, pois, vier o senhor da vinha, que fará ele àqueles vinhateiros?"

[[v47-21-41]]

^<<v47-21-41,41>>^ Responderam-lhe: "Matará sem piedade esses malvados, e arrendará a sua vinha a outros vinhateiros, que lhe paguem o fruto a seu tempo."

[[v47-21-42]]

^<<v47-21-42,42>>^ Jesus disse-lhes: "Nunca lestes nas Escrituras (Ps. 117, 22-23): A pedra que fora rejeitada pelos que edificavam, tornou-se pedra angular; pelo Senhor foi feito isto, e é coisa maravilhosa aos nossos olhos? (ver nota)

[[v47-21-43]]

^<<v47-21-43,43>>^ Por isso vos digo que vos será tirado o reino de Deus, e será dado a um povo que produza os frutos dele.

[[v47-21-44]]

^<<v47-21-44,44>>^ O que cair sobre esta pedra far-se-á em pedaços, e aquele sobre quem ela cair ficará esmagado."

[[v47-21-45]]

^<<v47-21-45,45>>^ Tendo os príncipes dos sacerdotes e os fariseus ouvido as suas parábolas, conheceram que falava deles.

[[v47-21-46]]

^<<v47-21-46,46>>^ Procuravam prendê-lo, mas tiveram medo do povo, porque este o tinha como um profeta.

'''

xref:047-sao-mateus/047-sao-mateus-020.adoc#v47-20-0[&#60; Capítulo Anterior] | <<v47-21-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-022.adoc#v47-22-0[Próximo Capítulo &#62;]