include::./index.adoc[]

[[v29-28-0]]
=== Isaías, 28
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 28 de Isaías trata da queda de Efraim e do orgulho de Judá. Deus adverte sobre a destruição que virá sobre aqueles que confiam em sua própria sabedoria e força, em vez de confiar no Senhor. Também é enfatizada a importância de ouvir e aprender a palavra de Deus. Abaixo estão cinco versículos relacionados com os temas deste capítulo:
* Provérbios 16:18: "A soberba precede a ruína, e a altivez do espírito precede a queda." Este verso enfatiza a mensagem de que aqueles que confiam em sua própria sabedoria e poder estão destinados a cair.
* Jeremias 9:23-24: "Assim diz o Senhor: não se glorie o sábio na sua sabedoria, nem o forte na sua força, nem o rico nas suas riquezas. Mas o que se gloriar, glorie-se nisto: em compreender e conhecer-me, pois eu sou o Senhor que exerço benignidade, juízo e justiça na terra; porque destas coisas me agrado, diz o Senhor." Este verso destaca a importância de confiar no Senhor e conhecer sua palavra, em vez de se vangloriar de sabedoria, força ou riqueza.
* Provérbios 1:7: "O temor do Senhor é o princípio do conhecimento, mas os insensatos desprezam a sabedoria e a disciplina." Este verso ressalta que aqueles que desconsideram a palavra e a sabedoria de Deus estão destinados a sofrer as consequências.
* Salmo 119:105: "Lâmpada para os meus pés é a tua palavra, e luz para o meu caminho." Este verso enfatiza a importância de seguir a palavra de Deus como uma luz para guiar nossos passos.
* 1 Coríntios 1:27-29: "Pelo contrário, Deus escolheu as coisas loucas do mundo para envergonhar os sábios, e escolheu as coisas fracas do mundo para envergonhar as fortes; e Deus escolheu as coisas humildes do mundo, e as desprezadas, e aquelas que não são, para reduzir a nada as que são; a fim de que ninguém se vanglorie na presença de Deus." Este verso destaca que o orgulho e a vanglória são inúteis diante de Deus, que usa coisas fracas e humildes para cumprir seus propósitos.
****

[[v29-28-1]]

^<<v29-28-1,1>>^ Ai da coroa soberba dos embriagados de Efraim, da flor caduca do brilho da sua glória, que domina o vale fertilíssimo dos ébrios de vinho!

[[v29-28-2]]

^<<v29-28-2,2>>^ Eis que virá, da parte do Senhor, um homem poderoso e forte, como uma saraiva impetuosa, como torvelinho destruidor, como o desabar de muitas águas que tudo inundam e derribam.

[[v29-28-3]]

^<<v29-28-3,3>>^ Será pisada aos pés a coroa soberba dos embriagados de Efraim.

[[v29-28-4]]

^<<v29-28-4,4>>^ E a flor caduca do brilho da sua glória, que domina o vale fertilíssimo, será como um figo temporão, que amadurece antes da estação (própria) o qual, o primeiro que o vê, logo colhe e devora.

[[v29-28-5]]

^<<v29-28-5,5>>^ Naquele dia o Senhor dos exércitos será um diadema cintilante, uma coroa de glória para o resto do seu povo,

[[v29-28-6]]

^<<v29-28-6,6>>^ um espírito de justiça para o que está sentado para (administrar) a justiça, uma fortaleza para os que repelem o assalto (dos inimigos) à porta (da cidade).

[[v29-28-7]]

^<<v29-28-7,7>>^ Mas também eles, extraviados por causa do vinho (demasiado), por causa das bebidas fortes, andara sem se poderem ter de pé; o sacerdote e o profeta, vacilam por causa da embriaguez, são absorvidos pelo vinho, andam atordoados pelas bebidas fortes, erram nas visões e tropeçam no juízo.

[[v29-28-8]]

^<<v29-28-8,8>>^ Todas as mesas se encheram de vómito e de asquerosidade, de modo que não há já lugar que esteja limpo.

[[v29-28-9]]

^<<v29-28-9,9>>^ A quem quer ensinar a sabedoria, a quem quer fazer entender a lição? Aos meninos acabados de desleitar, aos que acabam de ser desmamados?

[[v29-28-10]]

^<<v29-28-10,10>>^ Porque: Manda, torna a mandar; manda, torna a mandar; espera, torna a esperar; espera, torna a esperar; um pouco aqui, um pouco aí. (ver nota)

[[v29-28-11]]

^<<v29-28-11,11>>^ Pois bem! (O Senhor) falará por pessoas que balbuciam, e numa língua bárbara, a este povo (insensato). (ver nota)

[[v29-28-12]]

^<<v29-28-12,12>>^ Tinha dito: Aqui é o descanso, reparai as forças do que está fatigado, este é o refrigério. Mas eles não quiseram ouvir.

[[v29-28-13]]

^<<v29-28-13,13>>^ Ser-lhes-á dita esta palavra do Senhor: Manda, torna a mandar; manda, torna a mandar; espera torna a esperar; espera, torna a esperar; um pouco aqui, um pouco aí - para que vão, caiam para trás e fiquem esmigalhados, e metidos no laço e presos. (ver nota)

[[v29-28-14]]

^<<v29-28-14,14>>^ Por esta causa ouvi a palavra do Senhor, homens escarnecedores, que dominais o povo que está em Jerusalém.

[[v29-28-15]]

^<<v29-28-15,15>>^ Vós dizeis: Nós fizemos um concerto com a morte, fizemos um pacto com o sepulcro. Quando passar o flagelo da inundação, não virá sobre nós, porque fizemos da mentira um abrigo e da fraude um refúgio.

[[v29-28-16]]

^<<v29-28-16,16>>^ Portanto estas coisas diz o Senhor Deus: Eis que coloquei nos fundamentos da (nova) Sião uma pedra, uma pedra provada, angular, preciosa, assentada em (solidíssimo) fundamento; aquele que crer, não se apressará (a fugir).

[[v29-28-17]]

^<<v29-28-17,17>>^ Tomarei o direito como regra, e a justiça como nível. A saraiva derribará o refúgio da mentira, e as águas levarão o vosso abrigo.

[[v29-28-18]]

^<<v29-28-18,18>>^ Será cancelado o vosso concerto com a morte, e o vosso pacto com o sepulcro não subsistirá; quando passar o flagelo da inundação, ele vos arrastará consigo.

[[v29-28-19]]

^<<v29-28-19,19>>^ No momento em que ele for passando, vos arrebatará, porque passará de manhã, passará de dia e de noite; só a aflição vos fará entender os oráculos.

[[v29-28-20]]

^<<v29-28-20,20>>^ O leito será pequeno demais para que (a pessoa) nele se possa deitar, e o cobertor demasiado estreito para que nele se possa envolver. (ver nota)

[[v29-28-21]]

^<<v29-28-21,21>>^ Porque o Senhor se levantará, como no monte Perasim, mostrar-se-á irado, como fez no vale de Gabaon, para executar a sua obra, uma obra singular, para fazer a sua obra, um obra inaudita. (ver nota)

[[v29-28-22]]

^<<v29-28-22,22>>^ Cessai, pois, já, de fazer zombaria, para que não suceda que se apertem mais as vossas cadeias, porque eu ouvi que está determinada pelo Senhor Deus dos exércitos uma destruição completa contra toda a terra (que habitais).

[[v29-28-23]]

^<<v29-28-23,23>>^ Aplicai os ouvidos e ouvi a minha voz; atendei e escutai as minhas palavras. (ver nota)

[[v29-28-24]]

^<<v29-28-24,24>>^ Porventura o lavrador lavrará sempre a fim de semear? Estará ele incessantemente rompendo e sachando a sua terra?

[[v29-28-25]]

^<<v29-28-25,25>>^ Porventura, depois de ter aplanado a superfície dela, não semeará a nigela, não espalhará os cominhos, não lançará o trigo, em filas, a cevada e a espelta nos seus respectivos lugares?

[[v29-28-26]]

^<<v29-28-26,26>>^ O (Senhor) seu Deus lhe dá conhecimento (nas coisas da agricultura) e o instrui (sobre o que deve fazer).

[[v29-28-27]]

^<<v29-28-27,27>>^ Não será debulhada a nigela com trilho armado de dentes de ferro, nem rodará a roda do carro por cima dos cominhos, mas a nigela será sacudida com uma vara, e os cominhos com um pau.

[[v29-28-28]]

^<<v29-28-28,28>>^ Calca-se o trigo (na debulha) mas não se bate interminàvelmente; passa-se sobre ele a roda do carro com os cavalos, mas não se esmaga.

[[v29-28-29]]

^<<v29-28-29,29>>^ Isto vem do Senhor dos exércitos, admirável nos seus conselhos, excelso na sua sabedoria.

'''

xref:029-isaias/029-isaias-027.adoc#v29-27-0[&#60; Capítulo Anterior] | <<v29-28-0,Topo>> | xref:029-isaias/029-isaias-029.adoc#v29-29-0[Próximo Capítulo &#62;]