include::./index.adoc[]

[[v29-53-0]]
=== Isaías, 53
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Isaías 53 é um dos capítulos mais importantes da Bíblia, pois descreve detalhadamente o sofrimento e morte do Servo Sofredor, que é identificado como o Messias. Os versículos a seguir estão relacionados com os temas abordados em Isaías 53:
* Salmos 22:16: "Pois cães me cercam; um ajuntamento de malfeitores me rodeia; traspassaram-me as mãos e os pés." Este versículo profético descreve a crucificação de Jesus, que foi pregado na cruz pelos seus pulsos e pés.
* Mateus 8:17: "para que se cumprisse o que fora dito pelo profeta Isaías: Ele tomou sobre si as nossas enfermidades e carregou as nossas doenças." Este versículo cita Isaías 53:4, que fala sobre como o Servo Sofredor carregou nossas dores e enfermidades.
* Romanos 5:8: "Mas Deus prova o seu próprio amor para conosco pelo fato de ter Cristo morrido por nós, sendo nós ainda pecadores." Este versículo destaca o amor de Deus por nós, demonstrado através da morte sacrificial de Jesus na cruz.
* 1 Pedro 2:24: "levando ele mesmo em seu corpo os nossos pecados sobre o madeiro, para que, mortos para os pecados, vivamos para a justiça; por suas feridas fostes sarados." Este versículo destaca como o sacrifício de Jesus na cruz foi para nos libertar do pecado e nos trazer cura espiritual.
* Hebreus 9:28: "assim também Cristo, oferecendo-se uma vez para sempre para tirar os pecados de muitos, aparecerá segunda vez, sem pecado, aos que o aguardam para a salvação." Este versículo destaca como o sacrifício de Jesus foi suficiente para nos salvar e como sua segunda vinda está relacionada com a salvação eterna.
****

[[v29-53-1]]

^<<v29-53-1,1>>^ Quem deu crédito ao que nós ouvimos? A quem foi revelado o braço do Senhor?

[[v29-53-2]]

^<<v29-53-2,2>>^ Subiu como um pobre arbusto diante dele, como um rebento que sai de terra sequiosa; não tinha graça nem beleza para atrair o nosso olhar, o seu aspecto não excitava o nosso amor. (ver nota)

[[v29-53-3]]

^<<v29-53-3,3>>^ Era desprezado, o último dos homens, homem de dores, experimentado nos sofrimentos; como aqueles, diante dos quais se tapa o rosto, era lançado ao desprezo, nenhum caso fazíamos dele.

[[v29-53-4]]

^<<v29-53-4,4>>^ Verdadeiramente foi ele que tomou sobre si as nossas doenças, carregou com as nossas dores; nós o reputamos como um castigado, como um homem ferido por Deus e humilhado.

[[v29-53-5]]

^<<v29-53-5,5>>^ Mas foi ferido por causa das nossas iniquidades, foi despedaçado por causa dos nossos crimes; o castigo que nos devia trazer a paz, caiu sobre ele, e nós fomos sarados com os seus ferimentos.

[[v29-53-6]]

^<<v29-53-6,6>>^ Todos andávamos desgarrados como ovelhas, cada um seguia seu caminho; o Senhor carregou sobre ele a iniquidade de todos nós.

[[v29-53-7]]

^<<v29-53-7,7>>^ Foi maltratado e resignou-se, não abriu a sua boca, como uma ovelha emudecida levada ao matadouro, como um cordeiro diante do que o tosquia, não abriu a sua boca.

[[v29-53-8]]

^<<v29-53-8,8>>^ Foi arrebatado por um juízo iníquo. Quem, de entre os seus contemporâneos, pensou em o defender, quando era arrancado da terra dos vivos, morto pelas iniquidades do meu povo?

[[v29-53-9]]

^<<v29-53-9,9>>^ Foi-lhe dada sepultura entre os ímpios, e, na sua morte foi posto com os malfeitores, embora não haja cometido iniquidade, e nunca se tenha achado dolo na sua boca.

[[v29-53-10]]

^<<v29-53-10,10>>^ O Senhor quis consumi-lo com sofrimentos: mas quando tiver oferecido a sua vida pelo pecado, verá uma descendência perdurável, e a vontade do Senhor prosperará nas suas mãos.

[[v29-53-11]]

^<<v29-53-11,11>>^ Livrado dos sofrimentos da sua alma, verá, e o que vir saciará os seus desejos. Este mesmo Justo, meu Servo, (diz o Senhor) justificará muitos e tomará sobre si as suas iniquidades.

[[v29-53-12]]

^<<v29-53-12,12>>^ Por isso eu lhe darei por sorte multidões, e ele terá parte nos despojos com os fortes, porque entregou a sua vida à morte e foi posto no número dos malfeitores, tomando sobre si os pecados de muitos e intercedendo pelos pecadores.

'''

xref:029-isaias/029-isaias-052.adoc#v29-52-0[&#60; Capítulo Anterior] | <<v29-53-0,Topo>> | xref:029-isaias/029-isaias-054.adoc#v29-54-0[Próximo Capítulo &#62;]