include::./index.adoc[]

[[v29-65-0]]
=== Isaías, 65
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Isaías 65 fala sobre a diferença entre aqueles que buscam a Deus e os que se afastam dele. Deus promete bênçãos para aqueles que o buscam sinceramente, enquanto julga aqueles que o rejeitam e se envolvem em pecado. Também é abordada a restauração de Israel e a criação de um novo céu e uma nova terra. Seguem abaixo cinco versículos relacionados com os temas abordados em Isaías 65:
* Provérbios 8:17: "Eu amo os que me amam; os que me procuram me encontram." Este versículo mostra que Deus está disposto a se relacionar com aqueles que o buscam e o amam de coração.
* Jeremias 29:13: "Vocês me buscarão e me encontrarão quando me buscarem de todo o coração." Este versículo fala sobre a importância de buscar a Deus com sinceridade e entrega total.
* Mateus 6:33: "Busquem, pois, em primeiro lugar o Reino de Deus e a sua justiça, e todas essas coisas serão acrescentadas a vocês." Este versículo incentiva a priorização de Deus em nossas vidas e promete que Ele suprirá todas as nossas necessidades.
* Apocalipse 21:1: "Então vi um novo céu e uma nova terra, pois o primeiro céu e a primeira terra tinham passado; e o mar já não existia." Este versículo fala sobre a promessa de uma nova criação, conforme também é mencionado em Isaías 65.
* 2 Pedro 3:13: "Nós, porém, segundo a sua promessa, esperamos novos céus e nova terra, nos quais habita a justiça." Este versículo reforça a esperança cristã na restauração total e na justiça que prevalecerá na nova criação, conforme prometido por Deus.
****

[[v29-65-1]]

^<<v29-65-1,1>>^ Eu estava à disposição dos que não perguntavam por mim, deixava-me encontrar dos que me não buscavam. Eu disse a uma nação que não invocava o meu nome: Eis-me aqui, eis-me aqui!

[[v29-65-2]]

^<<v29-65-2,2>>^ Estendia as minhas mãos todo o dia para (Israel) um povo rebelde que andava por caminho mau, após os seus pensamentos,

[[v29-65-3]]

^<<v29-65-3,3>>^ para um povo que, cara a cara, sempre me provocava à ira, imolando vítimas nos jardins; sacrificando sobre tijolos, (ver nota)

[[v29-65-4]]

^<<v29-65-4,4>>^ habitando nos sepulcros, passando a noite em esconderijos, comendo carne de porco e alimentos impuros nos seus pratos,

[[v29-65-5]]

^<<v29-65-5,5>>^ dizendo: Afasta-te, não te aproximes de mim, porque eu te tornaria sagrado; esses são um fumo nas minhas narinas, um fogo que arde sempre.

[[v29-65-6]]

^<<v29-65-6,6>>^ Eis que isto está escrito diante de mim: Não me calarei até lhes dar a paga, até a lançar no seu seio.

[[v29-65-7]]

^<<v29-65-7,7>>^ (Castigarei) as vossas iniquidades e as dos vossos pais, diz o Senhor, os quais sacrificaram sobre os montes e me ultrajaram sobre os outeiros. Lançarei no seu seio o salário merecido.

[[v29-65-8]]

^<<v29-65-8,8>>^ Eis o que diz o Senhor: Como quando se acha sumo num cacho de uvas, se diz: Não o destruas, porque nele há bênção - assim farei eu por amor de meus servos, não destruirei de todo (Israel).

[[v29-65-9]]

^<<v29-65-9,9>>^ Farei sair de Jacob uma posteridade, e de Judá um herdeiro dos meus montes; os meus escolhidos possuirão esta terra, e os meus servos habitarão nela.

[[v29-65-10]]

^<<v29-65-10,10>>^ Saron servirá de tapada de rebanhos, e o vale de Acor de logradouro de bois, para aqueles do meu povo que me buscaram.

[[v29-65-11]]

^<<v29-65-11,11>>^ Quanto a vós, que abandonaste o Senhor, que vos esquecestes do meu santo monte, que pondes uma mesa à (deusa) Fortuna e fazeis libações ao Destino,

[[v29-65-12]]

^<<v29-65-12,12>>^ eu vos farei passar, um por um, ao fio da espada: todos perecereis nesta mortandade, porque eu chamei e vós não respondestes, falei e não ouvistes, fizestes o mal diante de meus olhos e escolhestes o que eu não queria.

[[v29-65-13]]

^<<v29-65-13,13>>^ Por esta causa o Senhor Deus diz isto: Eis que os meus servos comerão, e vós tereis fome; eis que os meus servos beberão, e vós tereis sede;

[[v29-65-14]]

^<<v29-65-14,14>>^ eis que os meus servos se alegrarão, e vós sereis confundidos; eis que os meus servos cantarão louvores na alegria do seu coração, e vós dareis gritos na dor do vosso coração, uivareis na aflição do vosso espírito,

[[v29-65-15]]

^<<v29-65-15,15>>^ deixareis o vosso nome como imprecação aos meus escolhidos; O Senhor Deus te matará - entretanto que os meus servos receberão um nome novo.

[[v29-65-16]]

^<<v29-65-16,16>>^ Todo o que quiser ser abençoado sobre a terra, quererá ser abençoado pelo Deus da verdade, e o que jurar sobre a terra, jurará pelo Deus da verdade, porque foram postas em esquecimento as antigas angústias, desapareceram dos meus olhos.

[[v29-65-17]]

^<<v29-65-17,17>>^ Porque vou criar novos céus e uma nova terra, e não persistirão na memória as coisas passadas, não voltarão mais ao espírito.

[[v29-65-18]]

^<<v29-65-18,18>>^ Antes folgareis e exultareis para sempre naquelas coisas que vou criar porque vou fazer de Jerusalém uma cidade de júbilo, e do seu povo, um povo de alegria.

[[v29-65-19]]

^<<v29-65-19,19>>^ Terei as minhas delícias em Jerusalém, e a minha alegria no meu povo; e não se ouvirá mais, ai, voz de choro nem voz de lamento.

[[v29-65-20]]

^<<v29-65-20,20>>^ Não haverá ali mais menino que viva poucos dias; nem velho que não complete os seus dias; será ainda novo o que morrer aos cem anos, e o pecador sòmente aos cem anos será amaldiçoado.

[[v29-65-21]]

^<<v29-65-21,21>>^ Edificarão casas e habitarão nelas; plantarão vinhas e comerão o seu fruto.

[[v29-65-22]]

^<<v29-65-22,22>>^ Não edificarão casas para outrem as habitar, nem plantarão para outrem comer (o fruto). Os dias do meu povo serão como os dias das árvores (que duram muito), e os meus eleitos usufruirão das obras das suas mãos.

[[v29-65-23]]

^<<v29-65-23,23>>^ Os meus escolhidos não trabalharão debalde, nem gerarão filhos para uma morte súbita, porque serão uma estirpe de abençoados do Senhor, eles e os seus descendentes.

[[v29-65-24]]

^<<v29-65-24,24>>^ Antes que eles clamem, eu os ouvirei; estando eles ainda a falar eu os atenderei.

[[v29-65-25]]

^<<v29-65-25,25>>^ O lobo e o cordeiro pastarão juntos, o leão e o boi comerão palha; o pó será para a serpente o seu alimento. Não haverá quem faça mal nem cause dano em todo o meu santo monte, diz o Senhor. (ver nota)

'''

xref:029-isaias/029-isaias-064.adoc#v29-64-0[&#60; Capítulo Anterior] | <<v29-65-0,Topo>> | xref:029-isaias/029-isaias-066.adoc#v29-66-0[Próximo Capítulo &#62;]