include::./index.adoc[]

[[v29-34-0]]
=== Isaías, 34
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Isaías 34 descreve o julgamento de Deus sobre as nações, especialmente Edom, por causa da sua rebelião contra Ele. O capítulo enfatiza a destruição total e a desolação que virão sobre essas nações ímpias, como resultado da justiça divina. Abaixo estão cinco versículos relacionados com os temas abordados em Isaías 34:
* Jeremias 49:17: "Assim diz o Senhor dos Exércitos: Eis que cortarei a Babilônia e dela farei um objeto de espanto e de escárnio; vazia ficará para sempre." Este versículo fala sobre a queda da Babilônia, uma das nações que receberam o julgamento de Deus.
* Naum 1:8: "Com uma inundação que passará, ele porá fim ao lugar dela; as trevas perseguirão os seus inimigos." Naum profetiza a destruição de Nínive, uma cidade ímpia que foi julgada por Deus por causa de sua crueldade e pecado.
* Ezequiel 25:13: "Por isso diz o Senhor Deus: Também estenderei a minha mão sobre Edom, e tirarei dela homens e animais; e a tornarei em deserto; de Temã até Dedã cairão à espada." Ezequiel profetiza a destruição de Edom, uma nação vizinha de Israel que se rebelou contra Deus e foi julgada por Ele.
* Joel 3:19: "O Egito se tornará em desolação, e Edom em deserto assolado, por causa da violência contra os filhos de Judá, cujo sangue derramaram na sua terra." Joel profetiza a destruição de Edom por causa da sua violência contra os filhos de Judá.
* Amós 1:11: "Assim diz o Senhor: Por três transgressões de Edom, e por quatro, não retirarei o castigo, porque perseguiu com espada a seu irmão, e violou as suas entranhas; e a sua ira despedaçou perpetuamente, e conservou a sua indignação para sempre." Amós denuncia Edom por sua crueldade e violência contra o povo de Israel, e profetiza que Deus irá julgá-los por seus pecados.
****

[[v29-34-1]]

^<<v29-34-1,1>>^ Vinde cá, ó nações, e ouvi; povos, estai atentos; ouça a terra, e o que ela contém; o mundo, e tudo o que ele produz!

[[v29-34-2]]

^<<v29-34-2,2>>^ Porque está indignado o Senhor contra todas as nações, irritado contra todo o seu exército; ele os matará, entregará ao morticínio.

[[v29-34-3]]

^<<v29-34-3,3>>^ Os seus mortos serão atirados (sem sepultura), os cadáveres exalarão um cheiro fétido, os montes serão regados com o seu sangue.

[[v29-34-4]]

^<<v29-34-4,4>>^ Será destruída toda a milícia (ou astros) dos céus, e os céus se enrolarão como um livro; toda a sua milícia cairá como cai a folha da vinha e da figueira.

[[v29-34-5]]

^<<v29-34-5,5>>^ A minha espada se embriagou nos céus; eis que ela vai agora descarregar sobre a Idumeia, sobre um povo que eu destinei ao extermínio, para fazer justiça. (ver nota)

[[v29-34-6]]

^<<v29-34-6,6>>^ A espada do Senhor está cheia de sangue, coberta de gordura, de sangue dos cordeiros e dos bodes, de gordura dos rins dos carneiros, porque há um sacrifício ao Senhor em Bosra, grande matança na terra de Edom.

[[v29-34-7]]

^<<v29-34-7,7>>^ Com eles caem os búfalos, e os bois com os touros. A terra se embriaga com o seu sangue, e o chão com a sua gordura.

[[v29-34-8]]

^<<v29-34-8,8>>^ É um dia de vingança para o Senhor, um ano (tempo) de desforra para fazer justiça a Sião (castigando os seus inimigos).

[[v29-34-9]]

^<<v29-34-9,9>>^ Converter-se-á em pez as torrentes (da Idumeia), e o seu chão em enxofre; a sua terra tornar-se-á pez ardente,

[[v29-34-10]]

^<<v29-34-10,10>>^ que não se apagará nem de noite nem de dia, cujo fumo subirá para sempre; de geração em geração será assolada, por todo o sempre não haverá quem por ela passe.

[[v29-34-11]]

^<<v29-34-11,11>>^ Possuí-la-ão o pelicano e o ouriço; a coruja e o corvo habitarão nela; (Deus) estenderá sobre ela a corda da confusão e o nível do vácuo.

[[v29-34-12]]

^<<v29-34-12,12>>^ Os seus nobres não mais existirão, não haverá mais realeza, e todos os seus príncipes serão aniquilados.

[[v29-34-13]]

^<<v29-34-13,13>>^ Nascerão nos seus palácios espinhos, e urtigas e cardos nas suas fortalezas; ela virá a ser covil de chacais, morada de avestruzes.

[[v29-34-14]]

^<<v29-34-14,14>>^ Cães e gatos selvagens aí se encontrarão, e os sátiros chamarão uns pelos outros; aí fará a sua morada o espectro das noites, aí encontrará o seu repouso.

[[v29-34-15]]

^<<v29-34-15,15>>^ Aí fará o seu ninho a serpente, porá os ovos, incubá-los-á e fará sair deles os filhos, à sua sombra. Aí se juntarão todos os abutres, uns ao pé dos outros.

[[v29-34-16]]

^<<v29-34-16,16>>^ Buscai diligentemente no livro do Senhor e lede; (nada do que vos anuncio deixará de acontecer) nem uma só destas coisas faltará, porque (o que sai da minha boca) Deus o mandou, e o seu mesmo espírito juntou estas coisas.

[[v29-34-17]]

^<<v29-34-17,17>>^ Foi ele que lhes determinou a sua porção, foi a sua mão que lhes repartiu a terra com cordel; desde então para sempre a possuirão; de geração em geração habitarão nela.

'''

xref:029-isaias/029-isaias-033.adoc#v29-33-0[&#60; Capítulo Anterior] | <<v29-34-0,Topo>> | xref:029-isaias/029-isaias-035.adoc#v29-35-0[Próximo Capítulo &#62;]