include::./index.adoc[]

[[v29-50-0]]
=== Isaías, 50
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 50 de Isaías começa com uma pergunta retórica: "Por acaso, eu me divorciei de vocês, ó Israel?". A partir daí, o profeta explica que os problemas enfrentados pelo povo de Israel foram causados por sua própria infidelidade a Deus e sua desobediência aos seus mandamentos. Isaías enfatiza que Deus ainda está presente para ajudá-los, mas é necessário que o povo se arrependa e volte a segui-lo. Abaixo estão cinco versículos relacionados com os temas abordados em Isaías 50:
* Deuteronômio 31:8: "O Senhor, Ele é quem vai adiante de ti; Ele será contigo, não te deixará, nem te desamparará. Não temas, nem te apavores." Este versículo fala da presença constante de Deus e da sua fidelidade para com o Seu povo.
* Salmos 34:18: "Perto está o Senhor dos que têm o coração quebrantado e salva os contritos de espírito." O Salmo 34:18 fala sobre a proximidade de Deus com aqueles que se arrependem e buscam a Sua ajuda.
* Jeremias 3:22: "Voltai, ó filhos rebeldes, eu curarei as vossas rebeliões." Este versículo mostra a disposição de Deus para perdoar e curar aqueles que se afastaram dele.
* João 14:15: "Se me amais, guardai os meus mandamentos." Esse versículo destaca a importância da obediência aos mandamentos de Deus como prova de amor a Ele.
* Hebreus 12:1-2: "Portanto, também nós, que estamos rodeados de tão grande nuvem de testemunhas, deixemos todo peso e o pecado que tão de perto nos rodeia e corramos, com perseverança, a carreira que nos está proposta, olhando firmemente para o Autor e Consumador da fé, Jesus, o qual, em troca da alegria que Lhe estava proposta, suportou a cruz, desprezando a vergonha, e assentou-se à direita do trono de Deus." Esse versículo incentiva os crentes a perseverarem na fé e a manterem os olhos fixos em Jesus, o exemplo perfeito de obediência e fidelidade a Deus.
****

[[v29-50-1]]

^<<v29-50-1,1>>^ Eis o que diz o Senhor: Onde está o libelo de repúdio de vossa mãe, pelo qual me divorciei dela? Ou quem é esse meu credor, a quem vos vendi? Por causa das vossas iniquidades fostes vendidos, por causa dos vossos crimes foi repudiada vossa mãe. (ver nota)

[[v29-50-2]]

^<<v29-50-2,2>>^ Porque eu vim, e não havia ninguém; chamei, e não havia quem respondesse. Encurtou-se, porventura, a minha mão, de forma que vos não possa resgatar? Ou não tenho eu poder bastante para vos livrar? Eis que, com uma simples ameaça, seco o mar e transformo em deserto os rios, até que definham os peixes sem água, e morrem à sede.

[[v29-50-3]]

^<<v29-50-3,3>>^ Envolvo os céus em trevas, e ponho-lhes um saco (de luto) por cobertura.

[[v29-50-4]]

^<<v29-50-4,4>>^ O Senhor deu-me língua de discípulo, para eu saber sustentar com a palavra o que está cansado: ele me chama pela manhã, pela manhã desperta os meus ouvidos, para que eu o ouça como discípulo.

[[v29-50-5]]

^<<v29-50-5,5>>^ O Senhor Deus abriu-me o ouvido, e eu não o contradisse, não me afastei para trás.

[[v29-50-6]]

^<<v29-50-6,6>>^ Entreguei o meu dorso aos que me feriam, e a minha face aos que me arrancavam a barba; não desviei o meu rosto dos que me injuriavam e cuspiam.

[[v29-50-7]]

^<<v29-50-7,7>>^ O Senhor Deus é o meu protetor, por isso não me senti confundido, por isso tornei a minha face como uma pedra duríssima sabendo que não ficaria envergonhado.

[[v29-50-8]]

^<<v29-50-8,8>>^ Ao pé de mim está quem me justifica; quem me contradirá? Apresentemo-nos juntos. Quem é o meu adversário? Aproxime-se de mim.

[[v29-50-9]]

^<<v29-50-9,9>>^ O Senhor Deus é o meu protetor; quem há que me condene? Serão todos consumidos como um vestido: a traça os comerá.

[[v29-50-10]]

^<<v29-50-10,10>>^ Qual de vós teme o Senhor, qual ouve a voz do seu servo? O que anda nas trevas (do exílio) e não tem luz, espere no nome do Senhor, firme-se sobre o seu Deus.

[[v29-50-11]]

^<<v29-50-11,11>>^ Mas vós todos, que estais acendendo o fogo, que vos armais de setas abrasadas, caminhai nas chamas do vosso fogo, por entre as setas que inflamastes. Da minha mão é que vos virá isto: dormireis em dores.

'''

xref:029-isaias/029-isaias-049.adoc#v29-49-0[&#60; Capítulo Anterior] | <<v29-50-0,Topo>> | xref:029-isaias/029-isaias-051.adoc#v29-51-0[Próximo Capítulo &#62;]