include::./index.adoc[]

[[v29-33-0]]
=== Isaías, 33
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 33 de Isaías começa com uma oração pelo livramento do povo de Judá contra os seus inimigos e continua com uma profecia sobre a vinda do Rei e a restauração da cidade de Sião. Os versículos selecionados a seguir estão relacionados com esses temas:
* Isaías 30:15: "Porque assim diz o Senhor Deus, o Santo de Israel: Em vos converterdes e em repousardes, estaria a vossa salvação; no sossego e na confiança estaria a vossa força, mas não quisestes." Este versículo fala sobre a importância de confiar em Deus para a salvação e a força, algo que é ressaltado no capítulo 33 de Isaías.
* Isaías 32:1: "Eis que um rei reinará com justiça, e os príncipes governarão com retidão." Essa passagem se refere à vinda de um rei justo, o que é um tema importante no capítulo 33 de Isaías.
* Isaías 32:18: "Então, o meu povo habitará em morada de paz, em moradas bem seguras, e em lugares quietos de descanso." Esse verso fala sobre a promessa de Deus de dar segurança e paz ao seu povo, algo que é enfatizado em Isaías 33.
* Isaías 35:10: "E os resgatados do Senhor voltarão e virão a Sião com cânticos de júbilo, e alegria eterna haverá sobre as suas cabeças; gozo e alegria alcançarão, e deles fugirá a tristeza e o gemido." Este versículo fala sobre a alegria e a felicidade que o povo de Deus experimentará após o livramento, um tema que é tratado em Isaías 33.
* Isaías 40:31: "Mas os que esperam no Senhor renovarão as suas forças, subirão com asas como águias; correrão e não se cansarão, caminharão e não se fatigarão." Este versículo fala sobre a importância de esperar em Deus para renovar as forças, algo que é uma mensagem importante em Isaías 33.
****

[[v29-33-1]]

^<<v29-33-1,1>>^ Ai de ti, devastador, que ainda não foste devastado, saqueador, que ainda não foste saqueado! Quando acabares de devastar, serás devastado; quando, já cansado, deixares de saquear, serás saqueado.

[[v29-33-2]]

^<<v29-33-2,2>>^ Senhor, tem misericórdia, de nós, porque (sempre) esperámos em ti; sê o nosso braço, todas as manhãs, a nossa salvação no tempo da tribulação.

[[v29-33-3]]

^<<v29-33-3,3>>^ À voz do teu trovão, fogem os povos, quando te levantas, dispersam-se as nações (inimigas).

[[v29-33-4]]

^<<v29-33-4,4>>^ Serão juntados os vossos despojos (ó Assírios), como se juntam gafanhotos, e lançam-se em cima (de vós, os vossos inimigos) como gafanhotos.

[[v29-33-5]]

^<<v29-33-5,5>>^ O Senhor é grande porque habita no alto; enche Sião de retidão e de justiça.

[[v29-33-6]]

^<<v29-33-6,6>>^ Serão seguros os teus tempos (ó Judá); a sabedoria e a ciência assegurarão a tua salvação; o temor do Senhor será o teu tesouro.

[[v29-33-7]]

^<<v29-33-7,7>>^ Eis que os que estiverem vendo clamarão de fora; os anjos (ou {1:embaixadores) da paz chorarão} amargamente.

[[v29-33-8]]

^<<v29-33-8,8>>^ Estão desertos os caminhos, ninguém passa pelas estradas; (o inimigo) rompeu a aliança, desprezou as cidades, não teve em conta os homens. (ver nota)

[[v29-33-9]]

^<<v29-33-9,9>>^ A terra chora e desfalece; o Líbano está em confusão e ressequido; Saron converteu-se num deserto; Basan e o Carmelo perderam a folhagem.

[[v29-33-10]]

^<<v29-33-10,10>>^ Agora me levantarei eu (contra os Assírios), diz o Senhor, agora me erguerei, agora me altearei.

[[v29-33-11]]

^<<v29-33-11,11>>^ Vós (ó Assírios) concebestes feno, dareis à luz palhas; o vosso sopro é o fogo que vos devorará.

[[v29-33-12]]

^<<v29-33-12,12>>^ Estes povos serão calcinados, serão como espinhos cortados que arderão no fogo.

[[v29-33-13]]

^<<v29-33-13,13>>^ Vós os que estais longe, ouvi o que eu fiz, e os que estais vizinhos, conhecei o meu poder.

[[v29-33-14]]

^<<v29-33-14,14>>^ Os pecadores foram aterrados em Sião, o medo apoderou-se dos ímpios. Qual de vós poderá habitar num fogo devorador? Qual de vós poderá habitar entre as chamas eternas?

[[v29-33-15]]

^<<v29-33-15,15>>^ Aquele que anda na justiça e fala verdade, que rejeita as riquezas adquiridas com a extorsão, que sacode de suas mãos todo o presente, que tapa os seus ouvidos, para não ouvir planos sanguinários, e fecha os seus olhos para não ver o mal,

[[v29-33-16]]

^<<v29-33-16,16>>^ esse habitará nas alturas (inacessíveis aos seus inimigos); as altas rochas fortificadas serão o seu abrigo; ser-lhe-á dado pão (em abundância), e a água nunca lhe faltará.

[[v29-33-17]]

^<<v29-33-17,17>>^ Os teus olhos verão o rei (dos céus) no seu esplendor, verão uma terra aberta ao longe.

[[v29-33-18]]

^<<v29-33-18,18>>^ (Então) o teu coração recordar-se-á do (seu passado) temor. Onde está (dirá ele) o escriba? Onde está o que tinha a balança? Onde está o que inspecionava as fortificações? (ver nota)

[[v29-33-19]]

^<<v29-33-19,19>>^ Tu não mais verás o povo insolente, o povo de falar obscuro, ininteligível, que balbucia palavras incompreensíveis.

[[v29-33-20]]

^<<v29-33-20,20>>^ Olha para Sião, cidade das nossas festas; os teus olhos vejam Jerusalém, habitação venturosa, tabernáculo que não poderá de modo algum ser transportado, cujas estacas não serão arrancadas, cujas cordas não serão partidas.

[[v29-33-21]]

^<<v29-33-21,21>>^ Ali é que o Senhor ostenta a sua magnificência em nosso favor, (protegendo-nos como) rios, canais larguíssimos, por onde não passará baixel (inimigo) a remo, nem grande embarcação atravessará. (ver nota)

[[v29-33-22]]

^<<v29-33-22,22>>^ Com efeito, o Senhor é o nosso juiz, o Senhor é o nosso legislador, o Senhor é o nosso rei, é ele que nos há-de salvar.

[[v29-33-23]]

^<<v29-33-23,23>>^ O teu cordame afrouxou, já não segura o mastro, nem mantém estendidas as velas. Então se repartirão os despojos de muitas presas (que tinhas feito); os (próprios) coxos tomarão parte na pilhagem,

[[v29-33-24]]

^<<v29-33-24,24>>^ Nenhum habitante (de Jerusalém) dirá: Estou doente; o povo que aí habitar receberá o perdão dos seus pecados. (ver nota)

'''

xref:029-isaias/029-isaias-032.adoc#v29-32-0[&#60; Capítulo Anterior] | <<v29-33-0,Topo>> | xref:029-isaias/029-isaias-034.adoc#v29-34-0[Próximo Capítulo &#62;]