include::./index.adoc[]

[[v29-49-0]]
=== Isaías, 49
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Isaías 49 é um capítulo que fala sobre o Servo do Senhor, que é chamado por Deus desde o ventre de sua mãe para ser um instrumento de salvação para as nações. O capítulo apresenta uma mensagem de esperança para os exilados de Israel, prometendo-lhes que Deus irá restaurar sua terra e trazer de volta seu povo disperso. Além disso, o capítulo destaca a missão do Servo em trazer salvação para todas as pessoas, incluindo aqueles que estão fora de Israel.
* Salmos 139:13-14: "Pois tu formaste o meu interior, tu me teceste no seio de minha mãe. Eu te louvo porque me fizeste de modo especial e admirável. Tuas obras são maravilhosas! Disso tenho plena certeza." Este versículo destaca a ideia de que Deus tem um plano para cada pessoa desde o momento em que foram formados no ventre de sua mãe, que é um tema central em Isaías 49.
* Lucas 2:30-32: "Pois os meus olhos já viram a tua salvação, que preparaste diante de todos os povos: luz para revelação aos gentios, e para glória de teu povo Israel." Esse versículo destaca a missão do Servo do Senhor, que é trazer salvação para todas as pessoas, incluindo gentios, como é enfatizado em Isaías 49.
* João 3:16: "Porque Deus tanto amou o mundo que deu o seu Filho Unigênito, para que todo aquele que nele crer não pereça, mas tenha a vida eterna." Este versículo fala sobre o amor de Deus por todas as pessoas e sua vontade de trazer salvação para todos, que é um tema importante em Isaías 49.
* Efésios 2:12-13: "Lembrem-se de que naquele tempo vocês estavam sem Cristo, separados da comunidade de Israel, sendo estrangeiros quanto às alianças da promessa, sem esperança e sem Deus no mundo. Mas agora, em Cristo Jesus, vocês, que antes estavam longe, foram aproximados mediante o sangue de Cristo." Este versículo fala sobre a união de todas as pessoas em Cristo, que é um tema central em Isaías 49.
* Atos 13:47: "Porque assim o Senhor nos ordenou: Eu te constituí como luz para os gentios, a fim de que leves a salvação até os confins da terra." Esse versículo destaca a missão do Servo do Senhor em trazer salvação para todas as pessoas, não apenas para aqueles dentro de Israel, que é um tema importante em Isaías 49.
****

[[v29-49-1]]

^<<v29-49-1,1>>^ Ouvi, ilhas, atendei povos de longe. O Senhor chamou-me desde o ventre de minha mãe; quando eu ainda estava no seio materno, pronunciou o meu nome.

[[v29-49-2]]

^<<v29-49-2,2>>^ Tornou a minha boca como uma espada aguda; protegeu-me à sombra da sua mão; fez de mim uma seta afiada, escondeu-me na sua aljava.

[[v29-49-3]]

^<<v29-49-3,3>>^ Disse-me: Israel, tu és meu servo; eu serei glorificado em ti.

[[v29-49-4]]

^<<v29-49-4,4>>^ E eu disse: Em vão tenho trabalhado (pregando ao povo); sem fruto e inutilmente consumi as minhas forças; porém o meu direito está nas mãos do Senhor, no meu Deus está depositada a recompensa da minha obra.

[[v29-49-5]]

^<<v29-49-5,5>>^ E agora o Senhor, que me formou desde o ventre materno para (ser) seu servo, diz-me que lhe reconduza Jacob, que lhe congregue Israel. Sou glorificado aos olhos do Senhor, e o meu Deus é a minha fortaleza.

[[v29-49-6]]

^<<v29-49-6,6>>^ Ele disse-me: É pouco que sejas meu servo para restaurar as tribos de Jacob, reconduzir os que escaparam de Israel. Vou fazer de ti luz das gentes, a fim de que chegue a minha salvação até à última extremidade da terra.

[[v29-49-7]]

^<<v29-49-7,7>>^ Eis o que diz o Senhor, o Redentor, o Santo de Israel, ao homem desprezado e abominado pelo povo, ao escravo dos tiranos: Reis te verão e se levantarão, príncipes se prostrarão, por causa do Senhor que é fiel (em cumprir as suas promessas), do Santo de Israel que te escolheu.

[[v29-49-8]]

^<<v29-49-8,8>>^ Eis o que diz o Senhor: Eu ouvi-to no tempo da graça, auxiliei-te no dia da salvação: conservei-te e constituí-te aliança do povo, para restaurares a terra e repartires as heranças devastadas.

[[v29-49-9]]

^<<v29-49-9,9>>^ para dizeres aos que estão em cadeias: Saí - e aos que estão nas trevas: Vinde à luz. Ao longo dos caminhos encontrarão com que se alimentar, e em todas as planícies haverá que comer para eles.

[[v29-49-10]]

^<<v29-49-10,10>>^ Não padecerão fome, não terão sede, e não serão molestados pelo vento ardente nem pelo sol, porque o que tem compaixão deles os governará e os levará a beber às fontes das águas.

[[v29-49-11]]

^<<v29-49-11,11>>^ Reduzirei a caminho todos os meus montes, e as minhas veredas serão alteadas.

[[v29-49-12]]

^<<v29-49-12,12>>^ Eis que estes virão de longe, aqueles do setentrião e do mar (ou poente), e aqueloutros da terra de Sinim.

[[v29-49-13]]

^<<v29-49-13,13>>^ Cantai, céus; regozija-te, terra; fazei retinir, ó montes, louvores festivos, porque o Senhor consolou o seu povo, compadeceu-se dos seus oprimidos.

[[v29-49-14]]

^<<v29-49-14,14>>^ Dizia Sião: O Senhor desamparou-me, o Senhor esqueceu-se de mim.

[[v29-49-15]]

^<<v29-49-15,15>>^ Porventura (respondeu o Senhor) pode uma mulher esquecer-se do seu menino de peito, não ter compaixão do filho das suas entranhas? Porém, ainda que ela se esquecesse dele, eu não me esqueceria de ti.

[[v29-49-16]]

^<<v29-49-16,16>>^ Eis que eu te gravei nas minhas mãos; as tuas muralhas estão sempre diante dos meus olhos.

[[v29-49-17]]

^<<v29-49-17,17>>^ Chegaram os que te hão-de reedificar; os que te destruíram e devastaram, fogem para longe de ti.

[[v29-49-18]]

^<<v29-49-18,18>>^ Levanta os teus olhos em volta e vê como todos se reúnem e vêm a ti; eu juro pela minha vida, diz o Senhor, que de todos estes serás revestida, como dum ornamento, que pô-los-ás por cintura à roda de ti, como uma esposa.

[[v29-49-19]]

^<<v29-49-19,19>>^ Com efeito as tuas ruínas, os teus desertos, o teu país devastado, tudo isto será agora estreito para os teus muitos habitantes, depois de afugentados para longe os que te devoravam.

[[v29-49-20]]

^<<v29-49-20,20>>^ Então hão-de dizer aos teus ouvidos, os filhos de que estavas privada: Este lugar é apertado para mim, dá-me espaço para habitar.

[[v29-49-21]]

^<<v29-49-21,21>>^ E tu dirás no teu coração: Quem me gerou estes filhos? Eu estava sem filhos e estéril, exilada e repudiada. Quem os criou, estando eu desamparada e só? Estes onde estavam?

[[v29-49-22]]

^<<v29-49-22,22>>^ Isto diz o Senhor Deus: Eis que levantarei para as nações a minha mão, e arvorarei entre os povos o meu estandarte. E trarão os teus filhos nos braços, e levarão as tuas filhas sobre os ombros.

[[v29-49-23]]

^<<v29-49-23,23>>^ Serão reis os que te alimentam, e rainhas as tuas nutrizes; com o rosto inclinado até à terra te adorarão e lamberão o pó dos teus pés. Saberás (então) que eu sou o Senhor e que não serão confundidos os que esperam em mim.

[[v29-49-24]]

^<<v29-49-24,24>>^ Acaso tirar-se-á a presa ao forte? Ou o que for tomado por um homem valente poderá ser-lhe tirado?

[[v29-49-25]]

^<<v29-49-25,25>>^ (Sim), porque o Senhor diz isto: Certamente serão tirados ao homem forte os que ele tiver feito cativos, e serão tirados ao valente os que ele tiver tomado. Quanto aos teus adversários, combatê-los-ei, e pelo que toca aos teus filhos, eu os salvarei.

[[v29-49-26]]

^<<v29-49-26,26>>^ Farei comer aos teus inimigos as suas próprias carnes; eles se embriagarão do seu próprio sangue, como dum vinho novo. E toda a carne saberá que eu sou o Senhor que te salva, que o teu redentor é o Forte de Jacob.

'''

xref:029-isaias/029-isaias-048.adoc#v29-48-0[&#60; Capítulo Anterior] | <<v29-49-0,Topo>> | xref:029-isaias/029-isaias-050.adoc#v29-50-0[Próximo Capítulo &#62;]