include::./index.adoc[]

[[v29-64-0]]
=== Isaías, 64
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Isaías 64 é um capítulo que fala sobre o clamor do povo de Deus pela sua intervenção e redenção diante da sua situação de pecado e afastamento do Senhor. Os versículos selecionados abaixo tratam de temas como a justiça e a misericórdia de Deus, a importância da oração e da busca por Deus, e a promessa de restauração.
* Salmos 85:10: "A misericórdia e a verdade se encontraram; a justiça e a paz se beijaram." Este versículo fala sobre a união entre a justiça e a misericórdia de Deus, que se encontram na obra redentora de Cristo, que pagou o preço pelos nossos pecados e nos concedeu o perdão e a salvação.
* Isaías 65:24: "Antes mesmo de clamarem, eu responderei; ainda falando, atenderei." Aqui Deus promete responder ao clamor do seu povo antes mesmo que eles o expressem em palavras, mostrando a sua atenção e amor por cada um de seus filhos.
* Salmos 80:3: "Ó Deus, restaura-nos e faze resplandecer o teu rosto, para que sejamos salvos." Esse salmo expressa a súplica do povo de Deus por sua restauração e salvação, e reflete o clamor apresentado em Isaías 64.
* Isaías 63:7: "Celebrarei as misericórdias do SENHOR e os seus muitos benefícios, conforme tudo o que o SENHOR nos concedeu e conforme a grande bondade para com a casa de Israel, bondade que lhe concedeu segundo as suas misericórdias e segundo a multidão das suas benevolências." Nesse versículo, Isaías relembra as muitas bênçãos que Deus já concedeu a seu povo, e destaca a importância de celebrar e agradecer por essas bênçãos em oração.
* Isaías 65:17: "Pois eis que eu crio novos céus e nova terra, e não haverá lembrança das coisas passadas, jamais serão lembradas." Esse versículo traz a promessa de Deus de que Ele fará uma obra completamente nova na vida de seu povo, restaurando tudo o que foi perdido pelo pecado e trazendo um novo tempo de paz e alegria.
****

[[v29-64-1]]

^<<v29-64-1,1>>^ Oxalá romperas os céus e desceras de lá, desfazendo os montes diante de ti,

[[v29-64-2]]

^<<v29-64-2,2>>^ como fogo que abrasa a lenha seca, como fogo que faz ferver a água, para que o teu nome se tornasse conhecido dos teus inimigos e ficassem turbadas as nações diante da tua face,

[[v29-64-3]]

^<<v29-64-3,3>>^ vendo-te operar prodígios nunca esperados, de que jamais se ouvira falar - oxalá desceras, que os montes se abalariam diante da tua face!

[[v29-64-4]]

^<<v29-64-4,4>>^ Nunca nenhum ouvido escutou nem nenhum olho viu outro Deus salvar assim os que nele confiam.

[[v29-64-5]]

^<<v29-64-5,5>>^ Sais ao encontro daquele que com alegria pratica a justiça e se lembra de ti nos teus caminhos: agora, porém, tu te iras, porque nós pecámos. Há muito que isto é assim: como seríamos salvos?

[[v29-64-6]]

^<<v29-64-6,6>>^ Todos nos tornámos como um homem imundo, todas as nossas justiças são como um pano sujo; caímos todos como a folha, e as nossas iniquidades, como o vento, nos arrebataram.

[[v29-64-7]]

^<<v29-64-7,7>>^ Não há quem invoque o teu nome, quem se levante para se unir a ti. Escondeste de nós a tua face e deixaste-nos perecer nas nossas iniquidades.

[[v29-64-8]]

^<<v29-64-8,8>>^ Agora, Senhor, tu és o nosso pai; nós não somos senão barro; foste tu que nos formaste, todos nós somos obra das tuas mãos.

[[v29-64-9]]

^<<v29-64-9,9>>^ Não te irrites extremamente, Senhor, e não te lembres mais da nossa iniquidade. Olha para nós; todos nós somos o teu povo.

[[v29-64-10]]

^<<v29-64-10,10>>^ As tuas cidades santas tornaram-se um deserto, Sião ficou erma, Jerusalém uma solidão.

[[v29-64-11]]

^<<v29-64-11,11>>^ O nosso santo e glorioso templo, onde nossos pais te louvavam, tornou-se presa das chamas, e todas as nossas preciosidades converteram-se em ruínas.

[[v29-64-12]]

^<<v29-64-12,12>>^ Porventura conter-te-ás ainda, Senhor, à vista destas desgraças? Ficarás calado e afligir-nos-ás até às últimas?

'''

xref:029-isaias/029-isaias-063.adoc#v29-63-0[&#60; Capítulo Anterior] | <<v29-64-0,Topo>> | xref:029-isaias/029-isaias-065.adoc#v29-65-0[Próximo Capítulo &#62;]