include::./index.adoc[]

[[v29-54-0]]
=== Isaías, 54
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Isaías 54 é um capítulo que traz uma mensagem de encorajamento e esperança para o povo de Deus. O capítulo começa com uma chamada para que o povo se alegre e se expanda, porque Deus prometeu restaurar e abençoar o seu povo. O capítulo destaca a fidelidade e o amor de Deus, que nunca falham, e termina com uma promessa de paz e segurança para o povo de Deus.
* Salmos 30:5: "Porque a sua ira dura só um momento; no seu favor está a vida. O choro pode durar uma noite, mas a alegria vem pela manhã." Este versículo destaca a ideia de que, mesmo em tempos de tristeza e sofrimento, Deus trará alegria e restauração, que é um tema central em Isaías 54.
* Romanos 8:38-39: "Porque estou certo de que, nem a morte, nem a vida, nem anjos, nem principados, nem coisas presentes, nem futuras, nem potestades, nem a altura, nem a profundidade, nem qualquer outra criatura nos poderá separar do amor de Deus, que está em Cristo Jesus, nosso Senhor." Este versículo destaca a fidelidade e o amor de Deus, que é um tema importante em Isaías 54.
* Salmos 46:1-2: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia. Portanto, não temeremos ainda que a terra se mude, e ainda que os montes se projetem para o meio dos mares." Este versículo enfatiza a segurança e a proteção que Deus oferece, que é um tema importante em Isaías 54.
* Salmos 23:4: "Ainda que eu ande pelo vale da sombra da morte, não temerei mal nenhum, porque tu estás comigo; a tua vara e o teu cajado me consolam." Esse versículo destaca a presença e a ajuda de Deus em tempos difíceis, o que é relevante para o tema de consolo e encorajamento em Isaías 54.
* Salmos 121:7-8: "O Senhor te guardará de todo mal; ele guardará a tua alma. O Senhor guardará a tua entrada e a tua saída, desde agora e para sempre." Esse versículo enfatiza a proteção e a segurança que Deus oferece, que é um tema importante em Isaías 54.
****

[[v29-54-1]]

^<<v29-54-1,1>>^ Alegra-te, estéril, que não dás à luz; entoa cânticos de júbilo, tu que não sentes as dores do parto, porque os filhos da desamparada são muito mais do que os daquela que tem marido, diz o Senhor.

[[v29-54-2]]

^<<v29-54-2,2>>^ Alarga o espaço da tua tenda, estende quanto puderes as peles da tua cobertura, estica as tuas cordas e segura as tuas estacas,

[[v29-54-3]]

^<<v29-54-3,3>>^ porque tu te estenderás para a direita e para a esquerda, e a tua posteridade tomará posse das nações e povoará as cidades desertas.

[[v29-54-4]]

^<<v29-54-4,4>>^ Não temas, porque não serás confundida, não te envergonhes porquanto não terás de que te envergonhar, pois te esquecerás da confusão da tua mocidade e não te lembrarás mais do opróbrio da tua viuvez.

[[v29-54-5]]

^<<v29-54-5,5>>^ Com efeito, o teu esposo é o teu Criador, que se chama Senhor dos exércitos; o teu redentor é o Santo de Israel, chamado o Deus de toda a terra.

[[v29-54-6]]

^<<v29-54-6,6>>^ O Senhor te chamou, como uma mulher desamparada e angustiada, como uma mulher repudiada desde a mocidade, disse o teu Deus.

[[v29-54-7]]

^<<v29-54-7,7>>^ Por um momento, por um breve espaço te abandonei, mas (agora) te congrego com grande misericórdia.

[[v29-54-8]]

^<<v29-54-8,8>>^ No momento da minha indignação escondi de ti, por um pouco, a minha face, porém compadeci-me de ti, com um amor eterno, diz o Senhor, teu Redentor.

[[v29-54-9]]

^<<v29-54-9,9>>^ Eu faço por ti como fiz nos dias de Noé, a quem jurei que não mais derramaria as águas (do dilúvio) sobre a terra; jurei não mais me irritar contra ti, nem te aterrorizar.

[[v29-54-10]]

^<<v29-54-10,10>>^ Ainda que os montes sejam abalados e tremam as colinas, o meu amor não se apartará de ti, a minha aliança de paz não se mudará, diz o Senhor, compadecido de ti.

[[v29-54-11]]

^<<v29-54-11,11>>^ Infeliz, combatida da tempestade, sem consolação alguma, eis que te vou edificar sobre jaspe, fundar sobre safiras;

[[v29-54-12]]

^<<v29-54-12,12>>^ farei as tuas ameias de rubis, as tuas portas de carbúnculo, uma muralha envolvente de pedras preciosas.

[[v29-54-13]]

^<<v29-54-13,13>>^ Todos os teus filhos serão instruídos pelo Senhor e gozarão duma grande paz.

[[v29-54-14]]

^<<v29-54-14,14>>^ Serás fundada sobre a justiça; estarás livre da opressão, pois nada terás a temer, e do pavor, pois não chegará a ti.

[[v29-54-15]]

^<<v29-54-15,15>>^ Se te atacarem, não será da minha parte, e quem te atacar cairá diante de ti.

[[v29-54-16]]

^<<v29-54-16,16>>^ Fui eu que criei o ferreiro que sopra sobre os carvões ardentes e que daí retira a arma que deve trabalhar: fui eu que criei o destruidor para destruir (ver nota)

[[v29-54-17]]

^<<v29-54-17,17>>^ Toda a arma fabricada contra ti, não terá préstimo; e tu condenarás toda a língua que se apresente em juízo contra ti. Esta é a herança dos servos do Senhor, esta a justiça que lhes virá de mim, diz o Senhor.

'''

xref:029-isaias/029-isaias-053.adoc#v29-53-0[&#60; Capítulo Anterior] | <<v29-54-0,Topo>> | xref:029-isaias/029-isaias-055.adoc#v29-55-0[Próximo Capítulo &#62;]