include::./index.adoc[]

[[v29-66-0]]
=== Isaías, 66
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Isaías 66 é o último capítulo do livro de Isaías e apresenta uma mensagem sobre o julgamento de Deus e a restauração de Jerusalém. O capítulo começa com Deus questionando quem Ele irá honrar e seguirá os Seus mandamentos, em seguida, apresenta a promessa de restauração de Jerusalém e a vinda de um novo céu e uma nova terra. O capítulo também fala sobre a rejeição dos ímpios e a adoração verdadeira a Deus.
* Isaías 66:13: "Como alguém a quem sua mãe consola, assim eu os consolarei; em Jerusalém vocês serão consolados" Este versículo fala sobre a consolação de Deus para o Seu povo após a restauração de Jerusalém, mostrando o amor e o cuidado de Deus pelos seus filhos.
* Salmos 50:15: "Invoca-me no dia da angústia; eu te livrarei, e tu me glorificarás" Este versículo apresenta a promessa de Deus de ajudar aqueles que O invocam durante suas dificuldades e, assim, serão salvos e glorificarão o Seu nome.
* Apocalipse 21:1: "Vi novo céu e nova terra, pois o primeiro céu e a primeira terra passaram, e o mar já não existia" Este versículo mostra a promessa da criação de um novo céu e nova terra, apresentando a restauração e a perfeição do mundo de Deus.
* João 4:23: "Mas vem a hora e já chegou, em que os verdadeiros adoradores adorarão o Pai em espírito e em verdade; porque são esses que o Pai procura para seus adoradores" Este versículo fala sobre a adoração verdadeira a Deus, onde a sinceridade do coração e a busca pela verdade são fundamentais.
* Malaquias 4:1: "Pois eis que aquele dia vem ardendo como fornalha; todos os soberbos e todos os que cometem maldade serão como palha; e o dia que está para vir haverá de queimá-los, diz o Senhor dos Exércitos, de sorte que não lhes deixará nem raiz nem ramo" Este versículo apresenta a rejeição dos ímpios no dia do julgamento de Deus, mostrando a importância de seguir os Seus mandamentos e viver uma vida justa.
****

[[v29-66-1]]

^<<v29-66-1,1>>^ Eis o que diz o Senhor: O céu é o meu trono, e a terra é o escabelo de meus pés. Que casa, pois, é essa que me edificareis, que lugar será o meu descanso? (ver nota)

[[v29-66-2]]

^<<v29-66-2,2>>^ Todas estas coisas fez a minha mão, todas elas foram assim criadas, diz o Senhor. Quem atrai o meu olhar é o aflito, o contrito do coração, que teme as minhas palavras.

[[v29-66-3]]

^<<v29-66-3,3>>^ O que imola um boi, é como o que mata um homem; o que sacrifica um cordeiro, é como o que degola um cão; o que faz uma oferenda, é como o que oferece sangue de porco; o que se lembra de queimar incenso, é como o que venera um ídolo. Todas estas coisas (proibidos pela lei) gostaram eles de fazer, andando nos seus caminhos, e a sua alma se deleitou nas suas abominações. (ver nota)

[[v29-66-4]]

^<<v29-66-4,4>>^ Por isso também terei gosto em zombar deles, farei vir sobre eles o que temiam: com efeito chamei, e não houve quem me respondesse, falei, e não me deram ouvidos, fizeram o mal diante dos meus olhos, escolheram o que eu não queria.

[[v29-66-5]]

^<<v29-66-5,5>>^ Ouvi a palavra do Senhor, vós que a ouvis com (respeitoso) temor: Os vossos irmãos, que vos aborrecem e que vos repelem por causa do meu nome, disseram: Mostre o Senhor a sua glória, para vermos a vossa alegria. Mas, (não temais) eles serão confundidos.

[[v29-66-6]]

^<<v29-66-6,6>>^ (Já ouço) vozes, um ruído de tumulto vindo da cidade, vozes vindas do templo. É a voz do Senhor, que dá o pago aos seus inimigos.

[[v29-66-7]]

^<<v29-66-7,7>>^ Antes que tivesse dor de parto, deu à luz; antes que chegasse o tempo do parto, deu à luz um filho varão. (ver nota)

[[v29-66-8]]

^<<v29-66-8,8>>^ Quem jamais ouviu tal? Quem viu coisa semelhante a esta? Porventura nasce um povo num só dia? Nasce ao mesmo tempo uma nação inteira? Pois Sião, logo que esteve de parto, deu à luz (todos) os seus filhos.

[[v29-66-9]]

^<<v29-66-9,9>>^ Eu, pois, que faço dar à luz (ou torno fecundos) os outros, não darei à luz eu mesmo, diz o Senhor? Eu, que dou aos outros sucessão, ficarei acaso estéril, diz o Senhor teu Deus? (ver nota)

[[v29-66-10]]

^<<v29-66-10,10>>^ Alegrai-vos com (a nova) Jerusalém, exultai por causa dela todos vós que a amais; regozijai-vos com ela todos os que chorais por ela,

[[v29-66-11]]

^<<v29-66-11,11>>^ a fim de que sugueis dos seus peitos, até ficardes saciados, (o leite) das consolações (celestiais), e saboreeis com delícias a plenitude da sua glória.

[[v29-66-12]]

^<<v29-66-12,12>>^ Porque o Senhor diz isto: Eis que eu farei correr sobre ela como que um rio de paz e a glória das nações como uma torrente que inunda; sugareis o seu leite, aos seus peitos sereis levados, e acariciados sobre o seu regaço.

[[v29-66-13]]

^<<v29-66-13,13>>^ Como uma mãe acaricia o seu filhinho, assim eu vos consolarei, e em Jerusalém sereis consolados.

[[v29-66-14]]

^<<v29-66-14,14>>^ Vós o vereis, folgará o vosso coração, e os vossos ossos retomarão vigor como a erva. E conhecer-se-á a mão do Senhor a favor dos seus servos e a sua indignação contra os seus inimigos.

[[v29-66-15]]

^<<v29-66-15,15>>^ Porque o Senhor virá no meio do fogo, e o seu carro será como um torvelinho, para espalhar a sua indignação num incêndio, e as suas ameaças em labaredas de fogo;

[[v29-66-16]]

^<<v29-66-16,16>>^ com efeito o Senhor, pelo fogo e pela espada, julgará todos os mortais, e serão muitos os que o Senhor matará.

[[v29-66-17]]

^<<v29-66-17,17>>^ Aqueles que se santificam e se purificam para ir aos jardins, atrás dum que está no meio deles, que comem carne de porco, coisas abomináveis e ratos, serão consumidos todos juntos, diz o Senhor.

[[v29-66-18]]

^<<v29-66-18,18>>^ Conheço as suas obras e os seus pensamentos. Virei para reunir todas as gentes e línguas, e eles comparecerão todos e verão a minha glória.

[[v29-66-19]]

^<<v29-66-19,19>>^ Porei entre eles um sinal; enviarei os que dentre eles forem salvos às nações, a Tarsis, a Put, a Lud, a Mosoc, a Ros, a Tubal, e a Javan, às ilhas longínquas, que nunca ouviram falar de mim, nem viram a minha glória. Eles anunciarão a minha glória às gentes,

[[v29-66-20]]

^<<v29-66-20,20>>^ e farão vir todos os vossos irmãos convocados de todas as nações, como um presente para o Senhor, (conduzindo-os) em cavalos, em carros, em liteiras, em machos e em dromedários, ao meu santo monte, a Jerusalém, diz o Senhor, como quando os filhos de Israel levam uma oferta num vaso puro à casa do Senhor.

[[v29-66-21]]

^<<v29-66-21,21>>^ Até escolherei dentre eles sacerdotes e levitas, diz o Senhor. (ver nota)

[[v29-66-22]]

^<<v29-66-22,22>>^ Porque, como os novos céus e a nova terra, que vou criar, subsistirão sempre diante de mim, diz o Senhor, assim subsistirá a vossa posteridade e o vosso nome.

[[v29-66-23]]

^<<v29-66-23,23>>^ Em cada mês, na neoménia, e em cada semana, ao sábado, toda a carne (toda a humanidade) virá prostrar-se diante de mim, diz o Senhor.

[[v29-66-24]]

^<<v29-66-24,24>>^ Quando saírem, verão os cadáveres dos homens que prevaricaram contra mim: o seu verme não morrerá e o seu fogo não se extinguirá, e a sua vista será um objecto de horror para todo o mundo.

'''

xref:029-isaias/029-isaias-065.adoc#v29-65-0[&#60; Capítulo Anterior] | <<v29-66-0,Topo>> | xref:030-jeremias/030-jeremias-001.adoc#v30-1-0[Próximo Capítulo &#62;]