include::./index.adoc[]

[[v29-30-0]]
=== Isaías, 30
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Isaías 30 é um capítulo que trata da rebeldia do povo de Judá em buscar ajuda no Egito em vez de confiar em Deus. O profeta adverte que essa aliança com o Egito será inútil e que a única esperança do povo está em se arrepender e voltar para Deus. Abaixo estão cinco versículos relacionados com os temas abordados em Isaías 30:
* 2 Crônicas 16:7-9: "Naquele tempo, o vidente Hanani foi ao rei Asa de Judá e lhe disse: 'Por teres confiado no rei da Síria e não no Senhor, teu Deus, o exército do rei da Síria escapou-te das mãos. Acaso não foram os etíopes e os líbios um exército imenso, com numerosos carros de guerra e cavaleiros? No entanto, por teres confiado no Senhor, ele os entregou em tuas mãos'". Este versículo fala da importância de confiar em Deus em vez de buscar ajuda em alianças políticas ou militares.
* Isaías 30:7: "Egito, cujos auxílios são inúteis e vãos; por isso, eu o chamo: ‘Rahab, que se estende deitada’". Este verso se refere ao Egito como "Rahab", um nome que significa orgulhoso ou arrogante. Isaías afirma que o orgulho do Egito e sua confiança em sua própria força serão inúteis diante do poder de Deus.
* Jeremias 2:18: "E agora, que fazes em meio aos caminhos do Egito, para beberes as águas do Nilo? E, que fazes em meio aos caminhos da Assíria, para beberes as águas do rio Eufrates?". Este versículo mostra que o povo de Judá buscava ajuda tanto no Egito quanto na Assíria, em vez de confiar em Deus.
* Isaías 30:15: "Assim diz o Soberano, o Senhor, o Santo de Israel: 'No arrependimento e no descanso está a salvação de vocês, na quietude e na confiança está o seu vigor, mas vocês não quiseram'". Neste versículo, Deus adverte o povo de Judá que a única esperança para eles é se arrepender e confiar nele, mas eles se recusam a fazê-lo.
* Salmo 20:7: "Alguns confiam em carros e outros em cavalos, mas nós confiamos no nome do Senhor, o nosso Deus". Este verso fala da importância de confiar em Deus em vez de confiar em coisas materiais como carros e cavalos (ou alianças políticas e militares) para nossa segurança e proteção.
****

[[v29-30-1]]

^<<v29-30-1,1>>^ Ai de vós, filhos rebeldes, diz o Senhor, que formais projetos sem contar comigo, que estabeleceis alianças sem o meu espírito, acumulando assim pecados sobre pecados;

[[v29-30-2]]

^<<v29-30-2,2>>^ que estais postos a caminho para descer ao Egito, e não consultastes a minha vontade, esperando encontrar refúgio na proteção de Faraó, abrigo na sombra (ou proteção) do Egito!

[[v29-30-3]]

^<<v29-30-3,3>>^ Porém a proteção de Faraó será a vossa vergonha, e o refúgio na sombra do Egito a vossa ignomínia.

[[v29-30-4]]

^<<v29-30-4,4>>^ Os teus príncipes foram até Tanis, e os teus embaixadores chegaram até Hanes.

[[v29-30-5]]

^<<v29-30-5,5>>^ Todos ficaram confundidos à vista dum povo, que lhes não pode ser útil para nada, e que, longe de os socorrer e de lhes prestar qualquer serviço, apenas serve para sua vergonha e opróbrio.

[[v29-30-6]]

^<<v29-30-6,6>>^ Oráculo contra os animais do meio-dia. Por uma terra de tribulação e angústia, donde saem o leão e a leoa, a víbora e o dragão voador, levam sobre o dorso dos jumentos as suas riquezas, sobre o dorso dos camelos os seus tesouros, a um povo que lhes não pode prestar para coisa alguma. (ver nota)

[[v29-30-7]]

^<<v29-30-7,7>>^ Porque o Egito debalde e em vão dará socorro; por isso lhe dei o nome de Rahab inerte.

[[v29-30-8]]

^<<v29-30-8,8>>^ Agora, pois, vai gravar isto (esta profecia) sobre uma tàbuazinha, em sua presença, regista-o com cuidado num livro para que seja no futuro um testemunho eterno.

[[v29-30-9]]

^<<v29-30-9,9>>^ Porque este povo é rebelde: são filhos mentirosos, filhos que não querem ouvir a lei de Deus.

[[v29-30-10]]

^<<v29-30-10,10>>^ Dizem aos videntes: Não vejais; e aos profetas: Não nos anuncieis a verdade, falai-nos de coisas agradáveis, profetizai ilusões.

[[v29-30-11]]

^<<v29-30-11,11>>^ Afastai-vos do caminho (da lei); afastai-vos de tal vereda; tirai de diante da nossa face o Santo de Israel.

[[v29-30-12]]

^<<v29-30-12,12>>^ Por este motivo diz o Santo de Israel: Visto que vós rejeitais esta palavra, e pondes a vossa confiança na calúnia e na perversidade, e nestas coisas vos apoiais,

[[v29-30-13]]

^<<v29-30-13,13>>^ por isso esta iniquidade será para vós como uma fenda ameaçadora de ruína, que produz uma gibosidade sobre uma elevada muralha, que subitamente se desmorona, quando menos se espera. (ver nota)

[[v29-30-14]]

^<<v29-30-14,14>>^ Faz-se em pedaços, como se quebra com uma fortíssima pancada uma vasilha de barro, sem se achar entre os seus fragmentos um caco, em que se leve uma brasa da lareira, ou se tire um pouco de água da cisterna.

[[v29-30-15]]

^<<v29-30-15,15>>^ Porque o Senhor Deus, o Santo de Israel, diz assim: Se vos converterdes e vos deixardes estar em calma, sereis salvos; a vossa fortaleza estará no repouso e na confiança. Mas vós não quisestes,

[[v29-30-16]]

^<<v29-30-16,16>>^ antes dissestes : De nenhuma sorte, mas fugiremos sobre cavalos! Pois bem, (digo eu) vós fugireis (dos vossos inimigos). - Montaremos em cavalos ligeiros! - Pois bem, (digo eu) serão mais ligeiros aqueles que vos hão-de perseguir.

[[v29-30-17]]

^<<v29-30-17,17>>^ Mil (dos vossos) homens fugirão da vista do terror de um só; à vista da ameaça de cinco, deitareis a fugir, até que vos reduzais a um destroço, até que fiqueis como um mastro no cume de um monte, como um sinal sobre um outeiro.

[[v29-30-18]]

^<<v29-30-18,18>>^ Por isso o Senhor espera o momento em que vos fará mercê, por isso se levantará, para usar de misericórdia convosco, por que o Senhor é um Deus justo. Ditosos todos os que esperam nele.

[[v29-30-19]]

^<<v29-30-19,19>>^ Ó povo de Sião, que habitas em Jerusalém, tu (ó povo fiel) deixarás de chorar. Ao gritares, suplicante, usará contigo de misericórdia; logo que ouvir a voz do teu clamor, te responderá (benignamente).

[[v29-30-20]]

^<<v29-30-20,20>>^ (Antes desse tempo feliz) o Senhor vos dará o pão da angústia e a água da tribulação; porém (depois) não se esconderão mais os teus mestres, e os teus olhos estarão vendo sempre os que te ensinam.

[[v29-30-21]]

^<<v29-30-21,21>>^ Os teus ouvidos escutarão ressoar, atrás de ti, esta voz: Eis o caminho, anda por ele! - quando te desviares, quer para a direita, quer para a esquerda.

[[v29-30-22]]

^<<v29-30-22,22>>^ Então considerarás impura a prata que cobre os teus ídolos, e o ouro que reveste as tuas estátuas, e arrojá-los-ás para longe de ti como coisa imunda. Fora daqui, lhes dirás tu.

[[v29-30-23]]

^<<v29-30-23,23>>^ Então será dada chuva para o grão que semeares na terra, e o pão que a terra produzir será abundantíssimo e excelente; naquele dia será o teu gado apascentado em espaçosas pastagens;

[[v29-30-24]]

^<<v29-30-24,24>>^ os bois e jumentos, que lavram a terra, comerão uma forragem apetitosa, limpa com a pá e o crivo.

[[v29-30-25]]

^<<v29-30-25,25>>^ Sobre todo o monte alto, sobre todo o outeiro elevado, haverá arroios, correntes de água, no dia da grande mortandade (dos teus inimigos), quando caírem as torres (que os defendiam).

[[v29-30-26]]

^<<v29-30-26,26>>^ A luz da lua será como a luz do Sol, e a luz do Sol será sete vezes maior, como a luz de sete dias, no dia em que o Senhor ligar a ferida do seu povo, curar as chagas dos golpes recebidos.

[[v29-30-27]]

^<<v29-30-27,27>>^ Eis que o nome do Senhor vem de longe, o seu furor é ardente e difícil de suportar; os seus lábios respiram indignação, e a sua língua é como um fogo devorador.

[[v29-30-28]]

^<<v29-30-28,28>>^ O seu sopro é como uma torrente trasbordante, que chega até ao pescoço, para crivar as nações com o crivo da destruição, e pôr um freio de descaminho nas mandíbulas dos povos.

[[v29-30-29]]

^<<v29-30-29,29>>^ Vós (porém) entoareis um cântico, como na noite em que se celebra a festa, e a alegria do vosso coração será como a do que vai caminhando ao som da flauta, para ir ao monte do Senhor, à rocha de Israel.

[[v29-30-30]]

^<<v29-30-30,30>>^ O Senhor fará ouvir a sua voz majestosa, mostrará o terror do seu braço nas ameaças da sua cólera, nas chamas de um fogo devorador, na tempestade, no aguaceiro e nas pedras de saraiva.

[[v29-30-31]]

^<<v29-30-31,31>>^ A voz do Senhor tremerá Assur, ferido com a sua vara.

[[v29-30-32]]

^<<v29-30-32,32>>^ A cada polpe desta vara justiceira, que o Senhor descarregará sobre ele, tocarão tambores e cítaras. Num assinalado combate o atacará.

[[v29-30-33]]

^<<v29-30-33,33>>^ Há muito tempo está preparado o lugar de Tofet; está pronto também para o rei; (o Senhor) fê-lo profundo e espaçoso. Há palha e muita lenha para a fogueira, que o sopro do Senhor, como uma torrente de enxofre, vai acender. (ver nota)

'''

xref:029-isaias/029-isaias-029.adoc#v29-29-0[&#60; Capítulo Anterior] | <<v29-30-0,Topo>> | xref:029-isaias/029-isaias-031.adoc#v29-31-0[Próximo Capítulo &#62;]