include::./index.adoc[]

[[v29-9-0]]
=== Isaías, 9
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Isaías 9 é um capítulo que traz uma mensagem de esperança, prometendo a vinda de um grande líder, que trará a luz para um povo que está em trevas. Este líder é descrito como um filho que será dado a nós, cujo governo trará paz, justiça e segurança. Para encontrar versículos relacionados com os temas abordados em Isaías 9, podemos buscar por passagens que falam sobre a esperança na vinda de um salvador, a luz que ele trará e a paz que seu governo trará.
* Isaías 42:1: "Aqui está o meu servo, a quem sustento, o meu escolhido, em quem tenho prazer. Pus nele o meu Espírito, e ele trará justiça às nações." Este versículo fala sobre o servo escolhido por Deus que trará justiça às nações, semelhante à descrição do líder prometido em Isaías 9.
* Lucas 1:79: "Para iluminar aos que estão sentados em trevas e na sombra da morte, a fim de dirigir nossos pés no caminho da paz." Este versículo fala sobre João Batista, que preparou o caminho para a vinda do Messias, que é a luz para aqueles que estão em trevas, como é descrito em Isaías 9.
* João 14:27: "Deixo-lhes a paz; a minha paz lhes dou. Não a dou como o mundo a dá. Não se perturbe o seu coração, nem tenham medo." Este versículo fala sobre a paz que Jesus deixa para seus discípulos e como essa paz é diferente da paz que o mundo pode oferecer, semelhante à paz que o líder prometido em Isaías 9 trará.
* Atos 26:18: "para que eles recebam o perdão dos pecados e herança entre os que são santificados pela fé em mim". Este versículo fala sobre a herança que é dada a todos aqueles que recebem o perdão de seus pecados pela fé em Jesus, semelhante à promessa de um governo de paz e justiça que é descrito em Isaías 9.
* Apocalipse 21:23: "A cidade não precisa de sol nem de lua para brilhar sobre ela, pois a glória de Deus a ilumina, e o Cordeiro é a sua candeia." Este versículo fala sobre a luz que ilumina a Nova Jerusalém, a cidade de Deus, semelhante à descrição da luz que o líder prometido em Isaías 9 trará.
****

[[v29-9-1]]

^<<v29-9-1,1>>^ Como no tempo passado humilhou a terra de Zabulon e a terra de Neftali, no tempo futuro cobrirá de glória o caminho do mar, o (país de) além-Jordão, a circunscrição dos gentios.

[[v29-9-2]]

^<<v29-9-2,2>>^ O povo, que andava nas trevas, viu uma grande luz; aos que habitavam na região da sombra da morte uma luz apareceu.

[[v29-9-3]]

^<<v29-9-3,3>>^ Multiplicaste o povo, deste-lhe uma grande alegria. Ele se alegrará quando tu lhe apareceres, como os que se alegram no tempo da messe, como exultam os vencedores com a presa que tomaram, quando repartem os despojos.

[[v29-9-4]]

^<<v29-9-4,4>>^ Tu quebraste o pesado jugo que oprimia, a vara que lhe rasgava as espáduas, o bastão do seu exactor, como o fizeste na jornada de Madian.

[[v29-9-5]]

^<<v29-9-5,5>>^ Todo o calçado do guerreiro na refrega, toda a vestidura manchada de sangue serão queimados, ficarão sendo pasto do fogo.

[[v29-9-6]]

^<<v29-9-6,6>>^ Porquanto um menino nasceu para nós, um filho nos foi dado, e foi posto o principado sobre o seu ombro; chama-se Maravilhoso Conselheiro, Deus Forte, Pai eterno, Príncipe da paz.

[[v29-9-7]]

^<<v29-9-7,7>>^ O seu império se estenderá cada vez mais, e a paz não terá fim sobre o trono de Davide e sobre o seu reino. Estabelecê-lo-á e mantê-lo-á pelo direito e pela justiça, desde agora e para sempre. Fará isto o zelo do Senhor dos exércitos.

[[v29-9-8]]

^<<v29-9-8,8>>^ O Senhor dirigiu a sua palavra a Jacob, e ela caiu em Israel.

[[v29-9-9]]

^<<v29-9-9,9>>^ Sabe-lo-á todo o povo. Efraim e os habitantes da Samaria, os quais, cheios de soberba e arrogância de coração, dizem:

[[v29-9-10]]

^<<v29-9-10,10>>^ Os tijolos caíram, mas nós edificaremos com pedras de silharia; cortaram os sicómoros, porém nós poremos cedros em seu lugar.

[[v29-9-11]]

^<<v29-9-11,11>>^ O Senhor suscitará contra eles os adversários de Rasin, estimulará os seus inimigos,

[[v29-9-12]]

^<<v29-9-12,12>>^ os Sírios da parte do oriente, os Filisteus da banda do ocidente; e eles devorarão Israel com toda a boca. Apesar de tudo isto, não se acha aplacado o seu furor, mas ainda está levantada a sua mão.

[[v29-9-13]]

^<<v29-9-13,13>>^ O povo não se voltou para quem o feria, não buscou o Senhor dos exércitos.

[[v29-9-14]]

^<<v29-9-14,14>>^ O Senhor destruirá num só dia a cabeça e a cauda a Israel, a palma e o junco.

[[v29-9-15]]

^<<v29-9-15,15>>^ O ancião e o homem respeitável são a cabeça; o profeta que ensina a mentira é a cauda.

[[v29-9-16]]

^<<v29-9-16,16>>^ O ancião e o homem respeitável são a cabeça; o profeta que ensina a mentira é a cauda.

[[v29-9-17]]

^<<v29-9-17,17>>^ Por esta causa, o Senhor não porá a sua alegria nos seus jovens, e não se compadecerá dos seus órfãos, nem das suas viúvas, porque todos eles são ímpios e maus, e toda a boca só profere loucuras. Apesar de tudo isto, não se acha aplacado o seu furor, mas ainda está levantada a sua mão.

[[v29-9-18]]

^<<v29-9-18,18>>^ Porque a impiedade se acendeu como um fogo, que devora os abrolhos e os espinhos, que abrasa a espessura do bosque, subindo ao alto turbilhões de fumo.

[[v29-9-19]]

^<<v29-9-19,19>>^ Arde a terra pela ira do Senhor dos exércitos, e o povo é pasto de chamas. O irmão não poupa o seu irmão.

[[v29-9-20]]

^<<v29-9-20,20>>^ Corta-se à direita, e fica-se com fome; devora-se à esquerda, e não se fica saciado; cada um devora a carne do seu próximo, ninguém se compadece do seu irmão. Manassés contra Efraim, Efraim contra Manassés, e os dois juntos contra Judá.

[[v29-9-21]]

^<<v29-9-21,21>>^ Apesar de tudo isto, não se acha aplacado o seu furor, mas ainda está levantada a sua mão.

'''

xref:029-isaias/029-isaias-008.adoc#v29-8-0[&#60; Capítulo Anterior] | <<v29-9-0,Topo>> | xref:029-isaias/029-isaias-010.adoc#v29-10-0[Próximo Capítulo &#62;]