include::./index.adoc[]

[[v29-13-0]]
=== Isaías, 13
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Isaías 13 fala sobre o julgamento de Deus sobre a Babilônia e os povos vizinhos por causa de sua idolatria e opressão. Os versículos a seguir se relacionam com os temas do capítulo:
* Jeremias 50:15: "Gritem contra ela por todos os lados! Ela se entregou; caíram suas colunas, foram derrubados os seus muros. Este é o castigo do Senhor; vinguemo-nos dela; façamos a ela o que ela merece!" Este versículo mostra o julgamento de Deus sobre a Babilônia, cumprindo a profecia de Isaías 13.
* Isaías 14:22-23: "Eu me levantarei contra eles, diz o Senhor dos Exércitos, e eliminarei o nome e o restante de Babilônia, seus descendentes e seus filhos, diz o Senhor. Farei dela uma posse de ouriços e a molharei com a água do lagar; e não haverá quem aí more, nem quem habite nela, de geração em geração." Este versículo mostra a destruição completa de Babilônia por Deus.
* Apocalipse 18:6-8: "Retribui-lhe como ela vos tem retribuído, e retribui-lhe em dobro, segundo as suas obras; no cálice em que ela misturou, misturai para ela em dobro. Quanto ela se engrandeceu e viveu luxuosamente, tanto lhe dai de tormento e de pranto; porque ela diz em seu coração: Estou sentada como rainha e não sou viúva, e de modo algum verei o pranto. Por isso, num só dia virão as suas pragas: morte, pranto e fome; e será consumida no fogo; porque poderoso é o Senhor Deus que a julga." Este versículo fala sobre o julgamento de Babilônia nos últimos dias, em conformidade com as profecias de Isaías 13.
* Jeremias 51:7: "A Babilônia era um copo de ouro na mão do Senhor, que embriagava toda a terra; as nações beberam do seu vinho, por isso as nações estão enlouquecidas." Este versículo mostra como a Babilônia se tornou um símbolo de opressão e corrupção para todas as nações, e como Deus a julgará por isso.
* Naum 1:2-3: "O Senhor é Deus zeloso e vingador; o Senhor é vingador e cheio de furor; o Senhor toma vingança contra os seus adversários e guarda a ira para os seus inimigos. O Senhor é tardio em irar-se, mas grande em poder, e de modo algum terá por inocente o culpado." Este versículo mostra que Deus é um Deus justo e vingativo, que não permitirá que a injustiça e a opressão continuem impunes.
****

[[v29-13-1]]

^<<v29-13-1,1>>^ Oráculo sobre Babilônia, revelado a Isaías, filho de Amós.

[[v29-13-2]]

^<<v29-13-2,2>>^ Levantai um estandarte sobre um monte escalvado, chamai-os em alta voz, fazei-lhes sinais com a mão para que entrem pelas portas dos príncipes.

[[v29-13-3]]

^<<v29-13-3,3>>^ Eu dei ordens aos que consagrei (para esta obra), chamei os meus dos seus valentes para (pôr em ação) a minha ira, eles que exultam com a minha glória.

[[v29-13-4]]

^<<v29-13-4,4>>^ Vozearia de gente sobre os montes, como de imensa multidão, ruído confuso de reinos de nações reunidas: É o Senhor dos exércitos que passa revista às tropas para a batalha.

[[v29-13-5]]

^<<v29-13-5,5>>^ Vêm de longínquo país da extremidade dos céus, o Senhor e os instrumentos do seu furor, para destruir toda a terra.

[[v29-13-6]]

^<<v29-13-6,6>>^ Soltai gritos, porque o dia do Senhor está perto: virá do Omnipotente como uma assolação.

[[v29-13-7]]

^<<v29-13-7,7>>^ Por esta causa, todas as mãos perderão o seu vigor, e todo o coração do homem desanimará.

[[v29-13-8]]

^<<v29-13-8,8>>^ Ficarão quebrantados, apoderar-se-ão deles convulsões e dores; torcer-se-ão como a mulher que está de parto; cada um ficará atônito, olhando para o seu vizinho; os seus rostos tornar-se-ão inflamados.

[[v29-13-9]]

^<<v29-13-9,9>>^ A cidade será tomada; horrível massacre.

[[v29-13-10]]

^<<v29-13-10,10>>^ Eis que vem o dia do Senhor, dia cruel, cheio de indignação, de ira e de furor, para transformar a terra numa solidão e para exterminar dela os pecadores.

[[v29-13-11]]

^<<v29-13-11,11>>^ As estrelas do céu, as suas constelações não espalharão a sua luz; cobrir-se-á de trevas o sol no seu nascimento, e a Iua não resplandecerá com a sua claridade.

[[v29-13-12]]

^<<v29-13-12,12>>^ Castigarei a terra por suas maldades, e os ímpios por sua iniquidade; porei fim à insolência dos soberbos, humilharei a arrogância dos opressores.

[[v29-13-13]]

^<<v29-13-13,13>>^ Farei que os homens sejam mais raros que o ouro fino, mais raros que o ouro de Ofir.

[[v29-13-14]]

^<<v29-13-14,14>>^ Farei estremecer os céus, e mover-se-á a terra do seu lugar, por causa da indignação do Senhor dos exércitos, no dia em que se acender o seu furor.

[[v29-13-15]]

^<<v29-13-15,15>>^ Então como a gazela que foge, como o rebanho que ninguém congrega, cada um (deixará Babilônia e) voltará para o seu povo, fugirá para a sua terra.

[[v29-13-16]]

^<<v29-13-16,16>>^ Todo o que for encontrado (na cidade) será morto, todo o que for preso cairá passado à espada.

[[v29-13-17]]

^<<v29-13-17,17>>^ Seus filhinhos serão massacrados, diante dos seus olhos, suas casas serão saqueadas, suas mulheres violadas.

[[v29-13-18]]

^<<v29-13-18,18>>^ Os seus arcos abaterão os jovens; não se compadecerão do fruto do ventre, nem pouparão as criancinhas.

[[v29-13-19]]

^<<v29-13-19,19>>^ Então Babilónia, gloriosa entre os reinos, orgulho dos Caldeus, ficará destruída, como o Senhor destruiu Sodoma e Gomorra.

[[v29-13-20]]

^<<v29-13-20,20>>^ Nunca mais será habitada, nunca mais povoada, no decorrer das idades, nem ali porá as suas tendas o Árabe, nem repousarão nela, com seus gados, os pastores.

[[v29-13-21]]

^<<v29-13-21,21>>^ As feras farão ali o seu covil; encher-se-ão as suas casas de mochos; habitarão ali avestruzes, e sátiros ali dançarão;

[[v29-13-22]]

^<<v29-13-22,22>>^ entre (as minas dos) seus palácios uivarão chacais, e lobos nas suas casas de prazer.

'''

xref:029-isaias/029-isaias-012.adoc#v29-12-0[&#60; Capítulo Anterior] | <<v29-13-0,Topo>> | xref:029-isaias/029-isaias-014.adoc#v29-14-0[Próximo Capítulo &#62;]