include::./index.adoc[]

[[v29-18-0]]
=== Isaías, 18
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Isaías 18 trata da visão profética de Isaías sobre a Etiópia. O capítulo começa com uma descrição da terra que é habitada por um povo alto e esbelto, que vive ao longo das margens dos rios. Em seguida, o profeta fala sobre a mensagem que Deus tem para o povo etíope e como essa mensagem será entregue. Os versículos a seguir são relacionados com os temas abordados em Isaías 18:
* Salmo 68:31: "Príncipes virão do Egito; a Etiópia logo estenderá para Deus suas mãos." Este versículo indica que a Etiópia buscará a Deus e se voltará para Ele.
* Jeremias 46:9: "Subam, ó cavalos; furiosos, ó carros de guerra! Saiam, soldados: homens de Cuxe e de Pute que empunham escudos e homens de Lídia que manejam arcos e flechas." Este versículo faz referência aos exércitos etíopes que foram convocados para lutar.
* Salmos 105:23: "Então Israel foi para o Egito, e Jacó viveu como estrangeiro na terra de Cam." Este versículo se refere ao fato de que a Etiópia também é conhecida como a terra de Cam.
* Amós 9:7: "Não são vocês para mim como os filhos dos etíopes, ó israelitas? Declara o Senhor. "Este versículo indica que Deus considera os etíopes tão preciosos quanto os israelitas.
* Sofonias 3:10: "Desde além dos rios da Etiópia, os meus adoradores, a minha dispersão, me trarão ofertas." Este versículo faz referência aos adoradores de Deus vindos da Etiópia que trarão ofertas a Ele.
****

[[v29-18-1]]

^<<v29-18-1,1>>^ Ai da terra do zumbido de asas, que está além dos rios da Etiópia,

[[v29-18-2]]

^<<v29-18-2,2>>^ a qual envia embaixadores por mar, em barcos de junco sobre as águas. Ide, mensageiros velozes, a um povo de elevada estatura, de pele luzidia, a um povo temido ao longe, nação poderosa e esmagadora, cuja terra é cortada pelos rios.

[[v29-18-3]]

^<<v29-18-3,3>>^ Vós todos, habitantes do mundo, que morais sobre a terra, quando for levantado o estandarte sobre os montes, olhai: quando soar a trombeta, escutai.

[[v29-18-4]]

^<<v29-18-4,4>>^ Porque o Senhor me diz isto: Repousarei e contemplarei do meu lugar, como o calor sereno do sol brilhante, como a nuvem de orvalho no tempo da messe. (ver nota)

[[v29-18-5]]

^<<v29-18-5,5>>^ Porque antes da vindima, quando tiver passado a floração e quando a flor se tornar um cacho maduro serão cortados os sarmentos com a podadeira, serão até tiradas, arrancadas as cepas.

[[v29-18-6]]

^<<v29-18-6,6>>^ E (os cadáveres dos Assírios) serão abandonados aos abutres dos montes e aos animais da terra: lançar-se-ão sobre eles os abutres, durante o estio, e, no inverno, os animais da terra.

[[v29-18-7]]

^<<v29-18-7,7>>^ Naquele tempo serão levadas oferendas ao Senhor dos exércitos por um povo de elevada estatura e pele luzidia, Por um povo temido ao longe, nação poderosa e esmagadora, cuja terra é cortada pelos rios; (essas oferendas serão levadas) à morada do nome do Senhor dos exércitos, ao monte Sião.

'''

xref:029-isaias/029-isaias-017.adoc#v29-17-0[&#60; Capítulo Anterior] | <<v29-18-0,Topo>> | xref:029-isaias/029-isaias-019.adoc#v29-19-0[Próximo Capítulo &#62;]