include::./index.adoc[]

[[v53-12-0]]
=== I Coríntios, 12
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 12 de 1 Coríntios aborda o tema dos dons espirituais e a unidade do corpo de Cristo. Paulo destaca que, embora haja diferentes dons, todos são dados pelo mesmo Espírito e são para o bem comum da igreja. Além disso, ele enfatiza que todos são membros do mesmo corpo, independentemente do seu papel ou dom específico. A seguir estão cinco versículos relacionados com os temas abordados em 1 Coríntios 12:
* Romanos 12:4-5: "Pois, assim como em um corpo temos muitos membros, e nem todos os membros têm a mesma função, assim também em Cristo, sendo muitos, formamos um corpo, e cada membro está ligado a todos os outros." Este versículo destaca a importância da diversidade de dons e papéis dentro do corpo de Cristo, bem como a necessidade de unidade e interdependência.
* Efésios 4:4-6: "Há um só corpo e um só Espírito, assim como também fostes chamados em uma só esperança da vossa vocação; há um só Senhor, uma só fé, um só batismo; um só Deus e Pai de todos, o qual é sobre todos, e por todos e em todos." Aqui, Paulo enfatiza a unidade do corpo de Cristo e a importância de manter essa unidade, apesar das diferenças.
* 1 Pedro 4:10-11: "Cada um exerça o dom que recebeu para servir os outros, administrando fielmente a graça de Deus em suas várias formas. Se alguém fala, faça-o como quem transmite a palavra de Deus. Se alguém serve, faça-o com a força que Deus provê, de forma que em todas as coisas Deus seja glorificado mediante Jesus Cristo, a quem seja a glória e o poder para todo o sempre. Amém." Este versículo destaca a importância de usar os dons espirituais para servir aos outros e trazer glória a Deus.
* Colossenses 3:15-17: "Que a paz de Cristo seja o árbitro em seus corações, visto que vocês foram chamados para viver em paz, como membros de um só corpo. E sejam agradecidos. Habite ricamente em vocês a palavra de Cristo; ensinem e aconselhem-se uns aos outros com toda a sabedoria e cantem salmos, hinos e cânticos espirituais com gratidão a Deus em seu coração. E tudo o que fizerem, seja em palavra, seja em ação, façam-no em nome do Senhor Jesus, dando por meio dele graças a Deus Pai." Este versículo destaca a importância da unidade e da gratidão dentro do corpo de Cristo, bem como a importância de usar os dons espirituais para edificação mútua.
* 1 Coríntios 12:27-31: "Ora, vós sois o corpo de Cristo, e cada um individualmente seus membros. E a uns pôs Deus na igreja, primeiramente apóstolos, em segundo lugar profetas, em terceiro doutores, depois milagres, depois dons de curar, socorros, governos, variedades de línguas. Porventura são todos apóstolos? são todos profetas? são todos doutores? são todos operadores de milagres? têm todos o dom de curar? falam todos diversas línguas? interpretam-nas todos? Portanto, procurai com zelo os melhores dons; e eu vos mostrarei um caminho ainda mais excelente." Nesse capítulo, Paulo trata da diversidade de dons concedidos pelo Espírito Santo aos membros do corpo de Cristo, enfatizando que cada um tem uma função importante e complementar. Assim como cada parte do corpo é importante para o seu funcionamento adequado, cada membro da igreja é fundamental para o bem-estar e crescimento do corpo de Cristo. Esse versículo destaca a diversidade de dons e a importância de buscar os melhores dons para edificar a igreja.
****

[[v53-12-1]]

^<<v53-12-1,1>>^ Sobre os dons espirituais não quero, Irmãos, que estejais na ignorância.

[[v53-12-2]]

^<<v53-12-2,2>>^ Sabeis que, quando éreis gentios, concorríeis aos simulacros mudos, conforme éreis levados.

[[v53-12-3]]

^<<v53-12-3,3>>^ Portanto faço-vos saber que ninguém, que fala pelo Espírito de Deus, diz: "Maldito seja Jesus." E ninguém pode dizer: "Jesus é Senhor", senão pelo Espírito Santo.

[[v53-12-4]]

^<<v53-12-4,4>>^ Há, com certeza, diversidade de graças, mas um mesmo é o Espírito; (ver nota)

[[v53-12-5]]

^<<v53-12-5,5>>^ e os ministérios são diversos, mas um mesmo é o Senhor;

[[v53-12-6]]

^<<v53-12-6,6>>^ e as operações são diversas, mas o mesmo Deus é o que opera tudo em todos.

[[v53-12-7]]

^<<v53-12-7,7>>^ A cada um é dada a manifestação do Espírito para utilidade comum.

[[v53-12-8]]

^<<v53-12-8,8>>^ Assim, a um é dada pelo Espírito a linguagem da sabedoria; a outro, a linguagem da ciência, segundo o mesmo Espírito;

[[v53-12-9]]

^<<v53-12-9,9>>^ a outro, a fé, pelo mesmo Espírito; a outro, o dom das curas, pelo mesmo Espírito;

[[v53-12-10]]

^<<v53-12-10,10>>^ a outro, o dom de operar milagres; a outro, a profecia; a outro, o discernimento dos espíritos; a outro, a variedade de línguas; a outro, a interpretação das línguas.

[[v53-12-11]]

^<<v53-12-11,11>>^ Mas todas estas coisas as opera um só e o mesmo Espírito, repartindo a cada um como quer.

[[v53-12-12]]

^<<v53-12-12,12>>^ Do mesmo modo que o corpo é um e tem muitos membros, mas todos os membros do corpo, embora sejam muitos, são contudo um só corpo, assim é também Cristo. (ver nota)

[[v53-12-13]]

^<<v53-12-13,13>>^ Com efeito, num mesmo Espírito fomos baptizados todos nós, para sermos um só corpo, quer sejamos Judeus ou Gregos, servos ou livres, e todos temos bebido de um só Espírito.

[[v53-12-14]]

^<<v53-12-14,14>>^ Efectivamente, também o corpo não é um membro, mas muitos.

[[v53-12-15]]

^<<v53-12-15,15>>^ Se o pé disser: "Porque não sou mão, não sou do corpo" — acaso deixa ele, por isso, de ser do corpo?

[[v53-12-16]]

^<<v53-12-16,16>>^ E se a orelha disser: "Visto que não sou olho, não sou do corpo" — porventura deixa ela, por isso, de ser do corpo?

[[v53-12-17]]

^<<v53-12-17,17>>^ Se o corpo fosse todo olhos, onde estaria o ouvido? Se fosse todo ouvido, onde estaria o olfacto?

[[v53-12-18]]

^<<v53-12-18,18>>^ Deus, porém, pôs os membros no corpo, cada um deles como quis.

[[v53-12-19]]

^<<v53-12-19,19>>^ Se todos os membros fossem um só membro, onde (estaria) o corpo?

[[v53-12-20]]

^<<v53-12-20,20>>^ Mas a verdade é que são muitos os membros, e um só o corpo.

[[v53-12-21]]

^<<v53-12-21,21>>^ O olho não pode dizer à mão: "Não necessito do teu serviço", nem a cabeça pode dizer aos pés: "Não me sois necessários."

[[v53-12-22]]

^<<v53-12-22,22>>^ Antes, pelo contrário, os membros do corpo, que parecem mais fracos, são os mais necessários,

[[v53-12-23]]

^<<v53-12-23,23>>^ e os que temos por mais vis membros do corpo, a esses cobrimos com mais decoro; e os que em nós são menos honestos, os recatamos com maior decência.

[[v53-12-24]]

^<<v53-12-24,24>>^ Os nossos membros honestos não têm necessidade disso, mas Deus dispôs o corpo, dando maior honra aquele (membro) que a não tinha em si,

[[v53-12-25]]

^<<v53-12-25,25>>^ para que não haja desacordo no corpo, mas os membros tenham o mesmo cuidado uns pelos outros.

[[v53-12-26]]

^<<v53-12-26,26>>^ De maneira que, se um membro sofre, todos os membros sofrem com ele; se um membro recebe glória, todos os membros se regozijam com ele.

[[v53-12-27]]

^<<v53-12-27,27>>^ Ora vós sois corpo de Cristo, e cada um, por sua parte, um dos seus membros. (ver nota)

[[v53-12-28]]

^<<v53-12-28,28>>^ E assim a alguns constituiu Deus na Igreja: em primeiro lugar, apóstolos; em segundo lugar, profetas; em terceiro lugar, doutores; depois, os que têm o poder de operar milagres; depois, os que têm o dom das curas, de assistir (a seus irmãos), de governar, de falar diversas línguas.

[[v53-12-29]]

^<<v53-12-29,29>>^ São porventura todos apóstolos? Todos profetas? Todos doutores? Todos taumaturgos?

[[v53-12-30]]

^<<v53-12-30,30>>^ Têm todos o dom de curar doenças? Falam todas diversas línguas? Têm todos o dom de as interpretar?

[[v53-12-31]]

^<<v53-12-31,31>>^ Aspirai, pois, aos dons superiores. E eu vou mostrar-vos um caminho ainda mais excelente.

'''

xref:053-i-corintios/053-i-corintios-011.adoc#v53-11-0[&#60; Capítulo Anterior] | <<v53-12-0,Topo>> | xref:053-i-corintios/053-i-corintios-013.adoc#v53-13-0[Próximo Capítulo &#62;]