include::./index.adoc[]

[[v53-4-0]]
=== I Coríntios, 4
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* 1 Coríntios 4 aborda o papel dos líderes cristãos na igreja. Paulo enfatiza que eles devem ser fiéis administradores da mensagem de Cristo, e não buscar sua própria glória ou reconhecimento. Ele também adverte os crentes a não julgarem os líderes de forma precipitada, mas sim esperar pelo julgamento de Deus, que é justo e verdadeiro.
* Jeremias 17:10: "Eu, o Senhor, esquadrinho o coração e provo os pensamentos; e isto para dar a cada um segundo os seus caminhos e segundo o fruto das suas ações." Este versículo destaca que somente Deus conhece verdadeiramente o coração humano e julga justamente.
* Mateus 25:23: "Disse-lhe o seu senhor: Muito bem, servo bom e fiel; foste fiel no pouco, sobre o muito te colocarei; entra no gozo do teu senhor." Este versículo enfatiza a importância da fidelidade e do compromisso na administração das coisas de Deus.
* 2 Coríntios 10:18: "Porque não é aprovado quem a si mesmo se louva, mas, sim, aquele a quem o Senhor louva." Este versículo destaca a importância de não buscar a própria glória ou reconhecimento, mas sim ser aprovado por Deus.
* Mateus 7:1-2: "Não julgueis, para que não sejais julgados. Porque com o juízo com que julgais sereis julgados, e com a medida com que medis vos medirão a vós." Este versículo adverte contra o julgamento precipitado e enfatiza que o julgamento justo vem somente de Deus.
* 1 Timóteo 3:1: "Esta é uma palavra fiel: se alguém deseja o episcopado, excelente obra deseja." Este versículo destaca a importância da liderança na igreja, e enfatiza que os líderes devem buscar esse papel com um coração sincero e comprometido com a obra de Deu
****

[[v53-4-1]]

^<<v53-4-1,1>>^ Assim todos nos considerem como servidores de Cristo e despenseiros dos mistérios de Deus.

[[v53-4-2]]

^<<v53-4-2,2>>^ Ora o que se requer nos despenseiros é que sejam fiéis.

[[v53-4-3]]

^<<v53-4-3,3>>^ Quanto a mim, pouco me importa ser julgado por vós ou em juízo humano, pois nem sequer me julgo a mim próprio.

[[v53-4-4]]

^<<v53-4-4,4>>^ Com efeito, de nada me sinto culpado, mas, nem por isso me dou por justificado; o Senhor é quem me julga.

[[v53-4-5]]

^<<v53-4-5,5>>^ Pelo que não julgueis antes do tempo, até que venha o Senhor, o qual não só porá às claras o que se acha escondido nas trevas, mas ainda descobrirá os desígnios dos corações; e, então, cada um receberá de Deus o louvor (que lhe é devido).

[[v53-4-6]]

^<<v53-4-6,6>>^ Ora, Irmãos, fiz aplicação destas coisas a mim e a Apolo, por causa de vós, para que aprendais em nós a não ir além do que está escrito, e não vos ensoberbeçais, tomando o partido de um contra o outro. (ver nota)

[[v53-4-7]]

^<<v53-4-7,7>>^ Porque, quem é que te distingue (declarando-te superior aos outros)? Que tens tu, que não recebesses? E, se o recebeste, porque te glorias, como se o não tiveras recebido?

[[v53-4-8]]

^<<v53-4-8,8>>^ Vós já estais saciados, já estais ricos, reinais sem nós; e queira Deus que reineis, para também reinarmos convosco. (ver nota)

[[v53-4-9]]

^<<v53-4-9,9>>^ Em verdade, entendo que Deus nos expôs a nós, Apóstolos, como dos últimos (dos homens), como destinados à morte (pelo martírio), porque (nos anfiteatros) somos dados em espetáculo ao mundo, aos anjos e aos homens.

[[v53-4-10]]

^<<v53-4-10,10>>^ Nós somos néscios por Cristo, e vós sábios em Cristo; nós fracos, e vós fortes; vós nobres, e nós desprezíveis.

[[v53-4-11]]

^<<v53-4-11,11>>^ Até esta hora, sofremos a fome e a sede, estamos nus, somos esbofeteados, não temos morada certa

[[v53-4-12]]

^<<v53-4-12,12>>^ e cansamo-nos a trabalhar por nossas próprias mãos; amaldiçoam-nos, e bendizemos; perseguem-nos, e sofremos (com paciência);

[[v53-4-13]]

^<<v53-4-13,13>>^ somos caluniados, e encorajamos; tornamo-nos como a imundície deste mundo, a escória de todos até agora.

[[v53-4-14]]

^<<v53-4-14,14>>^ Não escrevo estas coisas para vos envergonhar, mas admoesto-vos como a meus filhos caríssimos.

[[v53-4-15]]

^<<v53-4-15,15>>^ De fato, ainda que tenhais dez mil pedagogos em Cristo, não tendes todavia muitos pais, pois fui eu que vos gerei em Jesus Cristo por meio do Evangelho.

[[v53-4-16]]

^<<v53-4-16,16>>^ Rogo-vos, pois, que sejais meus imitadores.

[[v53-4-17]]

^<<v53-4-17,17>>^ Por isso vos enviei Timóteo, que é meu filho caríssimo e fiel no Senhor, o qual vos lembrará os meus caminhos, que são em Jesus Cristo, como eu ensino por toda a parte em todas as igrejas.

[[v53-4-18]]

^<<v53-4-18,18>>^ Alguns andam inchados (de orgulho) como se eu não estivesse para ir ter convosco.

[[v53-4-19]]

^<<v53-4-19,19>>^ Mas brevemente irei ter convosco, se o Senhor quiser, e examinarei, não as palavras dos que andam inchados, mas o seu poder.

[[v53-4-20]]

^<<v53-4-20,20>>^ Com efeito, o reino de Deus não consiste em palavras, mas em atos.

[[v53-4-21]]

^<<v53-4-21,21>>^ Que quereis? Que eu vá ter convosco com vara, ou com amor e espírito de mansidão?

'''

xref:053-i-corintios/053-i-corintios-003.adoc#v53-3-0[&#60; Capítulo Anterior] | <<v53-4-0,Topo>> | xref:053-i-corintios/053-i-corintios-005.adoc#v53-5-0[Próximo Capítulo &#62;]