include::./index.adoc[]

[[v53-1-0]]
=== I Coríntios, 1
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 1 de 1 Coríntios aborda a questão da sabedoria divina versus sabedoria humana. Paulo exorta os coríntios a não se deixarem levar pelas divisões causadas por diferentes líderes religiosos, mas a permanecerem unidos em Cristo. Ele enfatiza que a sabedoria de Deus é loucura para os homens e que a mensagem da cruz é a força de Deus para a salvação daqueles que creem.
* Provérbios 3:5-6: "Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento. Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas." Este versículo enfatiza a importância da confiança em Deus e da busca da sabedoria divina em vez de depender da sabedoria humana limitada.
* Jeremias 9:23-24: "Assim diz o Senhor: Não se glorie o sábio na sua sabedoria, nem se glorie o forte na sua força; não se glorie o rico nas suas riquezas. Mas o que se gloriar, glorie-se nisto: em me conhecer e saber que eu sou o Senhor, que faço beneficência, juízo e justiça na terra; porque destas coisas me agrado, diz o Senhor." Este versículo enfatiza a superioridade da sabedoria divina em relação à sabedoria humana e a importância de conhecer a Deus.
* Isaías 29:14: "Eis que continuarei a fazer obra maravilhosa no meio deste povo, obra maravilhosa e um prodígio; pois a sabedoria dos seus sábios perecerá, e a prudência dos seus prudentes se esconderá." Este versículo destaca a futilidade da sabedoria humana em comparação com a sabedoria divina e a capacidade de Deus de fazer coisas maravilhosas.
* Colossenses 2:8: "Tende cuidado, para que ninguém vos faça presa sua por meio de filosofias e vãs sutilezas, segundo a tradição dos homens, segundo os rudimentos do mundo e não segundo Cristo." Este versículo adverte contra a sabedoria humana vã e o perigo de se afastar da verdade de Cristo.
* Tiago 1:5: "E, se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente e não o lança em rosto; e ser-lhe-á dada." Este versículo enfatiza a importância da sabedoria divina e a promessa de Deus de conceder sabedoria aos que a pedem.
****

[[v53-1-1]]

^<<v53-1-1,1>>^ Paulo, chamado a ser Apóstolo de Jesus Cristo, por vontade de Deus, e Sóstenes, irmão,

[[v53-1-2]]

^<<v53-1-2,2>>^ à Igreja de Deus, que está em Corinto, aos santificados em Jesus Cristo, chamados a ser santos, com todos os que, em qualquer lugar, invocam o nome de Nosso Senhor Jesus Cristo, seu Senhor e nosso:

[[v53-1-3]]

^<<v53-1-3,3>>^ Graça e paz (vos sejam dadas) da parte de Deus, nosso Pai, e do Senhor Jesus Cristo.

[[v53-1-4]]

^<<v53-1-4,4>>^ Dou graças, incessantemente, ao meu Deus por vós, pela graça de Deus, que vos foi dada em Jesus Cristo,

[[v53-1-5]]

^<<v53-1-5,5>>^ porque nele fostes cumulados de todas as riquezas, de todas as (riquezas) da palavra e da ciência,

[[v53-1-6]]

^<<v53-1-6,6>>^ na medida em que a pregação de Cristo tomou força entre vós,

[[v53-1-7]]

^<<v53-1-7,7>>^ de maneira que nada falte em graça alguma a vós, que esperais a manifestação de Nosso Senhor Jesus Cristo,

[[v53-1-8]]

^<<v53-1-8,8>>^ o qual também vos confirmará até ao fim para que sejais irrepreensíveis no dia da vinda de Nosso Senhor Jesus Cristo.

[[v53-1-9]]

^<<v53-1-9,9>>^ Fiel é Deus, pelo qual fostes chamados à sociedade de seu Filho Jesus Cristo Nosso Senhor.

[[v53-1-10]]

^<<v53-1-10,10>>^ Ora, rogo-vos, Irmãos, pelo nome de Nosso Senhor Jesus Cristo, que digais todos o mesmo e que entre vós não haja discórdias, mas vivei em perfeita harmonia no mesmo espírito e no mesmo parecer.

[[v53-1-11]]

^<<v53-1-11,11>>^ Porque a vosso respeito, Irmãos meus, me foi referido pelos (da casa) de Cloé, que há contendas entre vós.

[[v53-1-12]]

^<<v53-1-12,12>>^ E digo isto, porque cada um de vós diz: "Eu sou de Paulo! Eu de Apolo! Eu de Cefas! Eu de Cristo."

[[v53-1-13]]

^<<v53-1-13,13>>^ Está dividido Cristo? Porventura Paulo foi crucificado por vós? Ou fostes baptizados em nome de Paulo?

[[v53-1-14]]

^<<v53-1-14,14>>^ Dou graças a Deus, porque não batizei nenhum de vós, senão Crispo e Caio,

[[v53-1-15]]

^<<v53-1-15,15>>^ para que ninguém diga que fostes batizados em meu nome.

[[v53-1-16]]

^<<v53-1-16,16>>^ Batizei também a família de Estéfanas. De resto não sei se batizei mais alguém.

[[v53-1-17]]

^<<v53-1-17,17>>^ Com efeito Cristo não me enviou a batizar, mas a pregar o Evangelho, não com a sabedoria das palavras, para que não se torne inútil a Cruz de Cristo.

[[v53-1-18]]

^<<v53-1-18,18>>^ Efetivamente, a palavra da cruz é uma loucura para os que se perdem, mas, para os que se salvam, isto é, para nós, é a virtude de Deus.

[[v53-1-19]]

^<<v53-1-19,19>>^ Porque está escrito: Destruirei a sabedoria dos sábios e reprovarei a prudência dos prudentes (Is. 29, 14).

[[v53-1-20]]

^<<v53-1-20,20>>^ Onde está o sábio? Onde o homem instruído? Onde o disputador deste mundo? Porventura não convenceu Deus de loucura a sabedoria deste mundo?

[[v53-1-21]]

^<<v53-1-21,21>>^ De fato, como ante a sabedoria de Deus o mundo não conheceu a Deus por meio da sabedoria, aprouve a Deus salvar os crentes por meio da loucura da pregação.

[[v53-1-22]]

^<<v53-1-22,22>>^ Enquanto os Judeus exigem milagres e os Gregos buscam a sabedoria,

[[v53-1-23]]

^<<v53-1-23,23>>^ nós pregamos a Cristo crucificado, que é escândalo para os Judeus e loucura para os gentios,

[[v53-1-24]]

^<<v53-1-24,24>>^ mas, para os que são chamados (à fé) quer dos Judeus, quer dos Gregos, é Cristo virtude de Deus e sabedoria de Deus;

[[v53-1-25]]

^<<v53-1-25,25>>^ porque o que é loucura em Deus, é mais sábio que os homens, e o que é fraqueza em Deus, é mais forte que os homens.

[[v53-1-26]]

^<<v53-1-26,26>>^ Considerai, pois, Irmãos, a vossa vocação, (e vereis) que (entre vós não há) nem muitos sábios segundo a carne, nem muitos poderosos, nem muitos nobres;

[[v53-1-27]]

^<<v53-1-27,27>>^ mas as coisas loucas, segundo o mundo, escolheu-as Deus para confundir os sábios, e as coisas fracas, segundo o mundo, escolheu-as Deus para confundir as fortes;

[[v53-1-28]]

^<<v53-1-28,28>>^ Deus escolheu as coisas vis e desprezíveis, segundo o mundo, e aquelas que não são, para destruir as que são, (ver nota)

[[v53-1-29]]

^<<v53-1-29,29>>^ para que nenhuma criatura se glorie diante dele.

[[v53-1-30]]

^<<v53-1-30,30>>^ É por ele que estais em Jesus Cristo, o qual foi feito por Deus, para nós, sabedoria, justiça, santificação e redenção,

[[v53-1-31]]

^<<v53-1-31,31>>^ para que, como está escrito: O que se gloria, glorie-se no Senhor (Je. 9, 24).

'''

xref:052-romanos/052-romanos-016.adoc#v52-16-0[&#60; Capítulo Anterior] | <<v53-1-0,Topo>> | xref:053-i-corintios/053-i-corintios-002.adoc#v53-2-0[Próximo Capítulo &#62;]