include::./index.adoc[]

[[v53-8-0]]
=== I Coríntios, 8
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 8 de 1 Coríntios trata sobre a questão de comer alimentos oferecidos aos ídolos, algo que era comum na cultura da época. Paulo aconselha os coríntios a terem cuidado para não fazerem algo que possa escandalizar os irmãos mais fracos na fé, ainda que eles mesmos saibam que não há problema em comer tais alimentos. É importante lembrar que o foco de Paulo não é a questão da alimentação em si, mas sim a importância de considerar o bem-estar dos irmãos na fé. Abaixo, cinco versículos relacionados com os temas abordados nesse capítulo:
* Romanos 14:13: "Portanto, deixemos de julgar uns aos outros. Em vez disso, façamos o propósito de não pôr pedra de tropeço ou obstáculo no caminho do nosso irmão." Nesse versículo, Paulo fala sobre a importância de não julgar os outros irmãos e de fazer o propósito de não pôr obstáculos no caminho deles, o que se relaciona diretamente com o conselho dado em 1 Coríntios 8.
* 1 Coríntios 10:23: "Todas as coisas são lícitas, mas nem todas são proveitosas. Todas as coisas são lícitas, mas nem todas edificam." Aqui, Paulo reforça que nem tudo que é lícito é benéfico para a edificação da comunidade cristã, o que é uma mensagem semelhante ao que ele diz em 1 Coríntios 8.
* Atos 15:29: "Abstende-vos de alimentos sacrificados a ídolos, do sangue, da carne de animais sufocados e das relações sexuais ilícitas. Fareis bem se vos guardardes dessas coisas." Nesse versículo, vemos o conselho dado pelos apóstolos a respeito de se abster de alimentos oferecidos a ídolos, uma questão similar à que é discutida em 1 Coríntios 8.
* Gálatas 5:13: "Porque vós, irmãos, fostes chamados à liberdade. Não useis, porém, a liberdade como desculpa para viver segundo a carne; antes, servi-vos uns aos outros com amor." Aqui, Paulo fala sobre a liberdade que temos em Cristo, mas também nos adverte para não usá-la como uma desculpa para agir de forma egoísta ou para escandalizar outros irmãos, uma mensagem semelhante à que é dada em 1 Coríntios 8.
* 1 Tessalonicenses 5:22: "Afastai-vos de toda forma de mal." Embora esse versículo não fale especificamente sobre o tema de comer alimentos oferecidos aos ídolos, ele traz uma mensagem importante a respeito de nos afastarmos de tudo aquilo que pode ser prejudicial para a nossa fé e para a edificação da comunidade cristã.
****

[[v53-8-1]]

^<<v53-8-1,1>>^ Relativamente às carnes sacrificadas aos ídolos, sabemos que todos temos ciência. A ciência incha, mas a caridade edifica.

[[v53-8-2]]

^<<v53-8-2,2>>^ Se alguém se lisonjeia de saber alguma coisa, este ainda não conheceu de que modo se deve saber.

[[v53-8-3]]

^<<v53-8-3,3>>^ Mas, se alguém ama a Deus, esse é conhecido dele.

[[v53-8-4]]

^<<v53-8-4,4>>^ Quanto, pois, a comer carnes imoladas aos ídolos, sabemos que o ídolo não é nada no mundo e que não há outro Deus, senão o Deus único.

[[v53-8-5]]

^<<v53-8-5,5>>^ De facto, ainda que haja alguns que se chamem deuses, ou no céu ou na terra (e assim sejam muitos os deuses e muitos os senhores),

[[v53-8-6]]

^<<v53-8-6,6>>^ para nós, contudo, há um só Deus, o Pai, de quem provêm todas as coisas, e para quem existimos, e um só Senhor, Jesus Cristo, por quem todas as coisas foram feitas, e nós também.

[[v53-8-7]]

^<<v53-8-7,7>>^ Mas nem em todos há a ciência, porque alguns, conservando ainda o seu antigo modo de considerar o ídolo, comem como do sacrificado a ídolo, e a consciência destes, estando enferma, fica contaminada.

[[v53-8-8]]

^<<v53-8-8,8>>^ Um alimento não (é coisa que) nos torna recomendáveis a Deus, visto que, nem comendo, teremos a mais alguma coisa, nem teremos alguma coisa a menos, não comendo.

[[v53-8-9]]

^<<v53-8-9,9>>^ Mas vede que esta liberdade que tendes não se torne ocasião de queda para os fracos.

[[v53-8-10]]

^<<v53-8-10,10>>^ Com efeito, se algum te vir a ti, que tens ciência, estar à mesa no templo idolátrico, porventura, com a sua consciência, que está enferma, não se animará a comer da carne sacrificada aos ídolos (que julga ser impura)?

[[v53-8-11]]

^<<v53-8-11,11>>^ E pela tua ciência perecerá o irmão fraco, pelo qual morreu Cristo!

[[v53-8-12]]

^<<v53-8-12,12>>^ Deste modo, pecando contra os irmãos e ofendendo a sua débil consciência, pecais contra Cristo.

[[v53-8-13]]

^<<v53-8-13,13>>^ Pelo que, se um alimento serve de escândalo a meu irmão, jamais comerei carne, para não escandalizar o meu irmão.

'''

xref:053-i-corintios/053-i-corintios-007.adoc#v53-7-0[&#60; Capítulo Anterior] | <<v53-8-0,Topo>> | xref:053-i-corintios/053-i-corintios-009.adoc#v53-9-0[Próximo Capítulo &#62;]