include::./index.adoc[]

[[v53-13-0]]
=== I Coríntios, 13
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 13 de 1 Coríntios é conhecido como o "hino ao amor" e trata da importância do amor em todas as coisas, especialmente na vida cristã e nas relações entre irmãos na fé. Abaixo estão cinco versículos relacionados com os temas abordados neste capítulo:
* Romanos 12:9 - "O amor deve ser sincero. Odeiem o mal e apeguem-se ao bem." - O amor genuíno deve ser verdadeiro e sincero, sem hipocrisia ou falsidade. Isso se relaciona com o capítulo 13 de 1 Coríntios, onde Paulo enfatiza a importância do amor verdadeiro e não fingido.
* 1 João 4:8 - "Quem não ama não conhece a Deus, porque Deus é amor." - O amor é uma característica fundamental de Deus, e aqueles que O conhecem e O amam também devem amar uns aos outros. Isso se relaciona com o capítulo 13 de 1 Coríntios, onde Paulo destaca que sem amor, todas as outras coisas perdem seu valor.
* João 15:13 - "Ninguém tem maior amor do que aquele que dá a sua vida pelos seus amigos." - Jesus deu o exemplo supremo de amor ao sacrificar Sua vida pelos pecadores. Isso se relaciona com o capítulo 13 de 1 Coríntios, onde Paulo enfatiza que o amor não busca seus próprios interesses, mas está disposto a se sacrificar pelos outros.
* Gálatas 5:22-23 - "Mas o fruto do Espírito é amor, alegria, paz, paciência, amabilidade, bondade, fidelidade, mansidão e domínio próprio. Contra essas coisas não há lei." - O amor é uma das manifestações do fruto do Espírito Santo na vida dos crentes. Isso se relaciona com o capítulo 13 de 1 Coríntios, onde Paulo destaca que o amor é um dom divino que deve ser buscado e cultivado.
* Efésios 5:2 - "e vivam em amor, como também Cristo nos amou e se entregou por nós como oferta e sacrifício de aroma agradável a Deus." - O amor é um estilo de vida que deve caracterizar a conduta dos crentes. Isso se relaciona com o capítulo 13 de 1 Coríntios, onde Paulo destaca que o amor é a base para todas as ações e atitudes cristãs.
****

[[v53-13-1]]

^<<v53-13-1,1>>^ Ainda que eu fale as línguas dos homens e dos a anjos, se não tiver caridade, sou como um bronze que soa, ou como um címbalo que tine.

[[v53-13-2]]

^<<v53-13-2,2>>^ E ainda que eu tivesse o dom da profecia e conhecesse todos os mistérios e toda a ciência, e tivesse toda a fé, até ao ponto de transportar montanhas, se não tivesse caridade, não seria nada.

[[v53-13-3]]

^<<v53-13-3,3>>^ E, ainda que distribuísse todos os meus bens para sustento dos pobres, e entregasse o meu corpo para ser queimado, se não tivesse caridade, nada (disto) me aproveitaria.

[[v53-13-4]]

^<<v53-13-4,4>>^ A caridade é paciente, é benéfica; a caridade não é invejosa, não é temerária; não se ensoberbece,

[[v53-13-5]]

^<<v53-13-5,5>>^ não é ambiciosa, não busca os seus próprios interesses, não se irrita, não guarda ressentimento pelo mal sofrido;

[[v53-13-6]]

^<<v53-13-6,6>>^ não folga com a injustiça, mas folga com a verdade;

[[v53-13-7]]

^<<v53-13-7,7>>^ tudo desculpa, tudo crê, tudo espera, tudo sofre.

[[v53-13-8]]

^<<v53-13-8,8>>^ A caridade nunca há-de acabar (nem mesmo no céu), mas as profecias passarão, as línguas cessarão, e a ciência será abolida.

[[v53-13-9]]

^<<v53-13-9,9>>^ Com efeito, imperfeitamente conhecemos e imperfeitamente profetizamos.

[[v53-13-10]]

^<<v53-13-10,10>>^ Mas, quando vier o que é perfeito, será abolido o que é imperfeito.

[[v53-13-11]]

^<<v53-13-11,11>>^ Quando eu era menino, falava como menino, pensava como menino, discorria como menino. Mas, quando me tornei homem feito, dei de mão às coisas que eram de menino.

[[v53-13-12]]

^<<v53-13-12,12>>^ Nós agora vemos (a Deus) como por um espelho, obscuramente, mas então (o veremos) face a face. Agora conheço-o, em parte, mas, então, hei-de conhecê-lo, como sou conhecido.

[[v53-13-13]]

^<<v53-13-13,13>>^ Agora permanecem (como necessárias para todos) estas três coisas: a fé, a esperança, a caridade; porém, a maior delas é a caridade.

'''

xref:053-i-corintios/053-i-corintios-012.adoc#v53-12-0[&#60; Capítulo Anterior] | <<v53-13-0,Topo>> | xref:053-i-corintios/053-i-corintios-014.adoc#v53-14-0[Próximo Capítulo &#62;]