include::./index.adoc[]

[[v53-7-0]]
=== I Coríntios, 7
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 7 de 1 Coríntios aborda diversas questões relacionadas ao casamento e à vida de solteiro, como a importância da abstinência sexual, a possibilidade de divórcio e o estado ideal de vida para servir a Deus. Os versículos a seguir são exemplos de passagens bíblicas que tratam de temas semelhantes:
* Provérbios 5:18-19: "Seja bendito o teu manancial, e alegra-te com a mulher da tua mocidade. Como cerva amorosa, e gazela graciosa, os seus seios te saciem em todo o tempo; e pelo seu amor sejas atraído perpetuamente." Este versículo destaca a importância do casamento e da satisfação sexual dentro dele.
* Mateus 19:9: "Eu vos digo, porém, que qualquer que repudiar sua mulher, não sendo por causa de prostituição, e casar com outra, comete adultério; e o que casar com a repudiada também comete adultério." Este versículo aborda a possibilidade de divórcio, que também é discutida em 1 Coríntios 7.
* Provérbios 31:10-12: "Mulher virtuosa, quem a achará? O seu valor muito excede o de rubis. O coração do seu marido confia nela, e não lhe faltará coisa alguma. Ela lhe faz bem e não mal, todos os dias da sua vida." Este versículo apresenta a figura da mulher virtuosa, que é uma referência para os cristãos que desejam se casar.
* 1 Timóteo 5:8: "Mas, se alguém não tem cuidado dos seus, e principalmente dos da sua família, negou a fé, e é pior do que o infiel." Este versículo ressalta a importância da responsabilidade familiar e da proteção dos entes queridos.
* 1 Pedro 3:7: "Igualmente vós, maridos, coabitai com elas com entendimento, dando honra à mulher, como vaso mais fraco; como sendo vós os seus coerdeiros da graça da vida; para que não sejam impedidas as vossas orações." Este versículo destaca a importância do amor, respeito e compreensão mútua entre marido e mulher, que são temas discutidos em 1 Coríntios 7.
****

[[v53-7-1]]

^<<v53-7-1,1>>^ Quanto àquelas coisas sobre que me escrevestes, (digo que) é bom para o homem não tocar mulher;

[[v53-7-2]]

^<<v53-7-2,2>>^ mas, por causa da fornicação, cada um tenha a sua mulher, e cada uma tenha o seu marido.

[[v53-7-3]]

^<<v53-7-3,3>>^ O marido dê a sua mulher o que lhe deve; e, da mesma maneira, também a mulher ao marido.

[[v53-7-4]]

^<<v53-7-4,4>>^ A mulher não tem poder sobre o seu corpo, mas sim o marido. E, da mesma sorte, o marido não tem poder sobre o seu corpo, mas sim a mulher.

[[v53-7-5]]

^<<v53-7-5,5>>^ Não vos recuseis um ao outro, senão de comum acordo, durante algum tempo, para vos aplicardes à oração; e de novo tornai a coabitar, para que não vos tente Satanás por vossa incontinência.

[[v53-7-6]]

^<<v53-7-6,6>>^ Mas digo-vos isto por condescendência, não por mandamento.

[[v53-7-7]]

^<<v53-7-7,7>>^ Porque eu queria que todos fossem como eu; porém, cada um tem de Deus o seu próprio dom: um de um modo, e outro de outro.

[[v53-7-8]]

^<<v53-7-8,8>>^ Digo aos não casados e às viúvas que lhes é bom permanecer assim, como também eu.

[[v53-7-9]]

^<<v53-7-9,9>>^ Mas, se não se contêm, casem-se. Porque é melhor casar-se do que abrasar-se (no fogo da torpeza).

[[v53-7-10]]

^<<v53-7-10,10>>^ Quanto aqueles que estão unidos em matrimônio, mando, não eu, mas o Senhor, que a mulher se não separe do marido;

[[v53-7-11]]

^<<v53-7-11,11>>^ e, se ela se separar, fique sem casar, ou reconcilie-se com seu marido, E o marido igualmente não repudie sua mulher.

[[v53-7-12]]

^<<v53-7-12,12>>^ Aos outros, sou eu que lhes digo (a minha opinião), não o Senhor: se algum irmão (nosso) tem uma mulher não cristã, e esta consente em habitar com ele, não a repudie;

[[v53-7-13]]

^<<v53-7-13,13>>^ Se uma mulher (cristã) tem um marido não cristão, e este consente em habitar com ela, não deixe esta o seu marido;

[[v53-7-14]]

^<<v53-7-14,14>>^ porque o marido não cristão é santificado pela mulher (cristã), e a mulher não cristã é santificada pelo marido cristão. Doutra sorte os vossos filhos seriam impuros, enquanto que agora são santos. (ver nota)

[[v53-7-15]]

^<<v53-7-15,15>>^ Porém, se a parte não cristã se separa, separe-se. Neste caso, já o irmão ou irmã não estão mais ligados: Deus vos chamou à paz.

[[v53-7-16]]

^<<v53-7-16,16>>^ Porque, sabes tu, ó mulher, se salvarás (ou converterás) teu marido (infiel)? Ou sabes tu, ó marido, se salvarás tua mulher?

[[v53-7-17]]

^<<v53-7-17,17>>^ Somente cada um proceda conforme o Senhor lhe deu, e cada um conforme Deus o chamou (à fé): é assim que eu ordeno em todas as igrejas. (ver nota)

[[v53-7-18]]

^<<v53-7-18,18>>^ É chamado algum, sendo circuncidado? Não procure parecer incircuncidado. É chamado algum incircuncidado? Não se circuncide.

[[v53-7-19]]

^<<v53-7-19,19>>^ A circuncisão nada vale, e a incircuncisão nada vale, mas a observância dos mandamentos de Deus é que vale.

[[v53-7-20]]

^<<v53-7-20,20>>^ Cada um permaneça no estado em que se encontrava quando foi chamado.

[[v53-7-21]]

^<<v53-7-21,21>>^ Foste chamado, sendo servo? Não te dê isso cuidado; ainda que possas tornar-te livre, escolhe antes servir.

[[v53-7-22]]

^<<v53-7-22,22>>^ Em verdade, o servo que foi chamado ao Senhor, é um liberto do Senhor; igualmente o que foi chamado, sendo livre, é um servo de Cristo.

[[v53-7-23]]

^<<v53-7-23,23>>^ Por grande preço fostes comprados! Não vos torneis servos dos homens.

[[v53-7-24]]

^<<v53-7-24,24>>^ Cada um, pois, Irmãos, permaneça diante de Deus no estado em que foi chamado.

[[v53-7-25]]

^<<v53-7-25,25>>^ Quanto, porém, às virgens, não tenho mandamento do Senhor, mas dou conselho, como homem que, pela misericórdia do Senhor, é digno de confiança.

[[v53-7-26]]

^<<v53-7-26,26>>^ Entendo, pois, que isto é bom por causa das dificuldades presentes, que é bom para o homem estar assim. (ver nota)

[[v53-7-27]]

^<<v53-7-27,27>>^ Estás ligado a uma mulher? Não busques desligar-te. Estás livre de mulher? Não busques mulher.

[[v53-7-28]]

^<<v53-7-28,28>>^ Mas, se tomares mulher, não pecas. E, se uma virgem se casar, não peca. Todavia estes sofrerão a tribulação da carne. E eu quisera poupar-vos (a ela).

[[v53-7-29]]

^<<v53-7-29,29>>^ Eis, pois, o que vos digo. Irmãos: o tempo é breve. Resta que os que têm mulheres, sejam como se as não tivessem; (ver nota)

[[v53-7-30]]

^<<v53-7-30,30>>^ os que choram, como se não chorassem; os que folgam, como se não folgassem ; os que compram, como se não possuíssem;

[[v53-7-31]]

^<<v53-7-31,31>>^ os que usam deste mundo, como se dele não usassem, porque a figura deste mundo passa.

[[v53-7-32]]

^<<v53-7-32,32>>^ Ora eu quereria que vivêsseis sem inquietação. O que está sem mulher, está cuidadoso das coisas que são do Senhor, como há-de agradar a Deus.

[[v53-7-33]]

^<<v53-7-33,33>>^ Mas, o que é casado, está cuidadoso das coisas que são do mundo, como há-de dar gosto a sua mulher, e (deste modo) está dividido.

[[v53-7-34]]

^<<v53-7-34,34>>^ Igualmente a mulher solteira e a virgem cuidam das coisas que são do Senhor, para serem santas de corpo e de espírito. Mas a que é casada cuida das coisas que são do mundo, de como agradará ao marido.

[[v53-7-35]]

^<<v53-7-35,35>>^ Digo isto para vosso proveito, não para vos atirar um laço, mas para o que é honesto e que vos dá faculdade de servir ao Senhor sem embaraço.

[[v53-7-36]]

^<<v53-7-36,36>>^ Mas, se algum julga que parece ser desonra, quanto a sua filha donzela, o ir-lhe passando a flor da idade, e que assim convém fazer-lhe o casamento, faça o que quiser; não peca, se ela se casar.

[[v53-7-37]]

^<<v53-7-37,37>>^ Mas o que resolveu firmemente dentro de si, não o obrigando a necessidade, mas podendo dispor à sua vontade, e determinou no seu coração conservar virgem a sua (filha), faz bem. (ver nota)

[[v53-7-38]]

^<<v53-7-38,38>>^ Aquele, pois, que casa a sua filha (virgem) faz bem ; o que a não casa, faz melhor.

[[v53-7-39]]

^<<v53-7-39,39>>^ A mulher está ligada durante todo o tempo que seu marido vive; mas, se morrer o seu marido, fica livre; case com quem quiser, contanto que seja no Senhor.

[[v53-7-40]]

^<<v53-7-40,40>>^ Porém, será mais feliz se permanecer assim, conforme o meu conselho. Ora julgo que também eu tenho o Espírito de Deus.

'''

xref:053-i-corintios/053-i-corintios-006.adoc#v53-6-0[&#60; Capítulo Anterior] | <<v53-7-0,Topo>> | xref:053-i-corintios/053-i-corintios-008.adoc#v53-8-0[Próximo Capítulo &#62;]