include::./index.adoc[]

[[v53-9-0]]
=== I Coríntios, 9
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 9 de 1 Coríntios aborda a questão do direito apostólico de Paulo e como ele escolhe não usar seus direitos para não ser um obstáculo para o evangelho. Ele discute o papel de um apóstolo e o que significa ser um servo de Cristo.
* Mateus 10:10-11: "Não tomem ouro, nem prata, nem cobre em seus cintos; não levem nenhum saco de viagem, nem túnica extra, nem sandálias, nem bordão; pois o trabalhador é digno do seu sustento." Neste versículo, Jesus está instruindo seus discípulos antes de enviá-los em missão e diz para eles não levarem nada com eles. Isso está relacionado ao tema do capítulo 9, onde Paulo fala sobre como ele escolheu não usar seus direitos como um apóstolo.
* Filipenses 4:17: "Não é que eu esteja buscando ofertas, mas que eu esteja buscando fruto que aumente o crédito de vocês." Neste versículo, Paulo fala sobre como ele não está buscando ofertas financeiras, mas sim um fruto que aumente o crédito da igreja. Isso mostra como ele não está interessado em usar sua posição para obter benefícios financeiros pessoais, mas sim para ajudar a igreja.
* 2 Coríntios 11:7-9: "Ou cometi algum pecado me rebaixando para que vocês fossem elevados? Vendi-lhes alguma coisa para que vocês fossem favorecidos? Aos irmãos que vieram da Macedônia eu não fui pesado a vocês em coisa alguma, nem em coisa alguma os hei de ser pesado. Em verdade, tanto em mim como em Tito, não temos procedido de maneira alguma pecaminosa em relação a vocês." Neste versículo, Paulo está falando sobre como ele não cobrou nada dos coríntios, diferentemente de outros pregadores que estavam cobrando pelos seus serviços. Isso mostra como ele escolheu não usar seu direito como um apóstolo para ser pago pelo seu trabalho.
* 1 Pedro 5:2-3: "Pastoreiem o rebanho de Deus que está sob o cuidado de vocês, não por obrigação, mas porque vocês querem servir a Deus; não por ganância, mas de boa vontade; não como dominadores dos que lhes foram confiados, mas como exemplos para o rebanho." Neste versículo, Pedro está falando sobre como pastores devem pastorear o rebanho de Deus. Isso está relacionado ao tema do capítulo 9, onde Paulo está falando sobre como ele escolheu não usar seus direitos apostólicos para ser um exemplo para a igreja.
* Filipenses 2:16: "retendo firmemente a palavra da vida, para que eu possa me orgulhar no dia de Cristo de que não corri nem me esforcei em vão." Este versículo fala sobre a importância de manter a Palavra de Deus e pregá-la com fidelidade, sem desanimar ou desistir. Isso se relaciona com o tema abordado em 1 Coríntios 9 sobre a corrida espiritual e a necessidade de perseverança e autocontrole.
****

[[v53-9-1]]

^<<v53-9-1,1>>^ Não sou eu livre? Não sou eu Apóstolo? Não vi eu a Jesus Nosso Senhor? Não sois vós obra minha no Senhor?

[[v53-9-2]]

^<<v53-9-2,2>>^ E, se para outros não sou Apóstolo, ao menos sou-o para vós, porque vós sois o selo do meu apostolado no Senhor.

[[v53-9-3]]

^<<v53-9-3,3>>^ A minha defesa, perante aqueles que me interpelam, é esta.

[[v53-9-4]]

^<<v53-9-4,4>>^ Porventura não temos direito de comer e de beber ?

[[v53-9-5]]

^<<v53-9-5,5>>^ Porventura não temos direito de levar connosco uma mulher irmã, como também os outros Apóstolos e os irmãos do Senhor e Cefas?

[[v53-9-6]]

^<<v53-9-6,6>>^ Ou só eu e Barnabé não temos direito de não trabalhar ? (ver nota)

[[v53-9-7]]

^<<v53-9-7,7>>^ Quem jamais vai à guerra à sua custa? Quem planta uma vinha e não come do seu fruto? Quem apascenta um rebanho e não se alimenta do leite do rebanho?

[[v53-9-8]]

^<<v53-9-8,8>>^ Porventura digo isto como homem? E não o diz também a lei? Porque está escrito na lei de Moisés: Não atarás a boca ao boi que debulha (Dt. 25, 4).

[[v53-9-9]]

^<<v53-9-9,9>>^ Porventura Deus tem cuidado dos bois?

[[v53-9-10]]

^<<v53-9-10,10>>^ Não é antes por nós mesmos que ele diz isto? Sim, é por causa de nós que isto foi escrito: que o que lavra, deve lavrar com esperança, e o que debulha, deve-o fazer com esperança de participar dos frutos.

[[v53-9-11]]

^<<v53-9-11,11>>^ Se semeamos entre vós as coisas espirituais, é porventura muito, se recolhermos dos vossos bens temporais (o preciso para viver)?

[[v53-9-12]]

^<<v53-9-12,12>>^ Se outros gozam deste direito sobre vós, por que não, mais justamente, nós? Todavia não temos feito uso deste direito, mas sofremos tudo para não criar nenhum obstáculo ao Evangelho de Cristo.

[[v53-9-13]]

^<<v53-9-13,13>>^ Não sabeis que os que trabalham no santuário, comem do que é do santuário, e que os que servem ao altar, têm parte (do que se oferece) no altar ?

[[v53-9-14]]

^<<v53-9-14,14>>^ Assim ordenou também o Senhor, aos que pregam o Evangelho, que vivam no Evangelho.

[[v53-9-15]]

^<<v53-9-15,15>>^ Porém de nada disto tenho usado. Nem tão-pouco escrevi estas coisas para que se faça assim comigo. Antes quereria morrer do que... Ninguém me tirará este titulo de glória.

[[v53-9-16]]

^<<v53-9-16,16>>^ Porquanto, se eu evangelizar, não tenho de que me gloriar, pois me é imposta essa obrigação. Ai de mim, se eu não evangelizar!

[[v53-9-17]]

^<<v53-9-17,17>>^ Pelo que, se o faço de boa vontade, tenho prémio; mas se, constrangido, o faço, isso é simples desempenho de um cargo que me foi confiado.

[[v53-9-18]]

^<<v53-9-18,18>>^ Qual é, pois, a minha recompensa ? É que, pregando o Evangelho, eu dê de graça o Evangelho, sem usar do meu direito de pregador do Evangelho.

[[v53-9-19]]

^<<v53-9-19,19>>^ Embora livre em relação a todos, fiz-me servo de todos, para ganhar o maior número.

[[v53-9-20]]

^<<v53-9-20,20>>^ Fiz-me judeu com os Judeus, para ganhar os Judeus;

[[v53-9-21]]

^<<v53-9-21,21>>^ com os que estão sob a lei, (fiz-me) como se estivesse sob a lei, (não estando eu sob a lei), para ganhar aqueles que estão sob a lei; com os que estão sem a lei, (fiz-me) como se estivesse sem a lei, (não estando sem a lei de Deus, mas estando na lei de Cristo), para ganhar os que estão sem a lei.

[[v53-9-22]]

^<<v53-9-22,22>>^ Fiz-me fraco com os fracos, para ganhar os fracos. Fiz-me tudo para todos, para, por todas as formas, salvar alguns.

[[v53-9-23]]

^<<v53-9-23,23>>^ Tudo isso faço pelo Evangelho, para me tornar participante dos seus bens.

[[v53-9-24]]

^<<v53-9-24,24>>^ Não sabeis que os que correm no estádio, correm, sim, todos, mas um só é que alcança o prémio? Correi, pois, de tal maneira que o alcanceis.

[[v53-9-25]]

^<<v53-9-25,25>>^ Todos os competidores de tudo se abstêm, (e fazem-no) para alcançar uma coroa corruptível; nós porém, (para obter) uma (coroa) incorruptível.

[[v53-9-26]]

^<<v53-9-26,26>>^ Quanto a mim, corro, não como à ventura; combato, não como quem açouta o ar,

[[v53-9-27]]

^<<v53-9-27,27>>^ mas castigo o meu corpo e reduzo-o à escravidão, para que não suceda que, tendo pregado aos outros, eu mesmo venha a ser eliminado.

'''

xref:053-i-corintios/053-i-corintios-008.adoc#v53-8-0[&#60; Capítulo Anterior] | <<v53-9-0,Topo>> | xref:053-i-corintios/053-i-corintios-010.adoc#v53-10-0[Próximo Capítulo &#62;]