include::./index.adoc[]

[[v53-3-0]]
=== I Coríntios, 3
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 3 de 1 Coríntios aborda a questão da maturidade espiritual e da construção da igreja como um edifício espiritual. Paulo exorta os coríntios a deixarem de lado a inveja e as divisões causadas por seguir diferentes líderes religiosos e a se unirem em Cristo. Ele ensina que os líderes religiosos são apenas servos de Deus e que é Deus quem faz crescer a igreja. Paulo também adverte sobre a importância de construir sobre o fundamento de Cristo e da necessidade de se livrar de qualquer coisa que possa destruir a obra de Deus.
* Efésios 2:19-20: "Assim que já não sois estrangeiros, nem forasteiros, mas concidadãos dos santos e da família de Deus, edificados sobre o fundamento dos apóstolos e dos profetas, sendo o próprio Jesus Cristo a pedra angular." Este versículo destaca a importância do fundamento de Cristo e dos apóstolos na construção da igreja como um edifício espiritual.
* Salmos 127:1: "Se o Senhor não edificar a casa, em vão trabalham os que a edificam; se o Senhor não guardar a cidade, em vão vigia a sentinela." Este versículo enfatiza a necessidade da presença e da obra de Deus na construção de qualquer obra espiritual.
* 1 Pedro 2:5: "E vós também, como pedras vivas, sois edificados casa espiritual e sacerdócio santo, para oferecer sacrifícios espirituais agradáveis a Deus por Jesus Cristo." Este versículo destaca a participação dos crentes na construção da igreja como um edifício espiritual, sendo eles mesmos pedras vivas que compõem a casa espiritual.
* Mateus 7:24-25: "Todo aquele, pois, que escuta estas minhas palavras e as pratica, assemelhá-lo-ei ao homem prudente, que edificou a sua casa sobre a rocha. E desceu a chuva, correram as torrentes, sopraram os ventos e bateram com ímpeto contra aquela casa; contudo não caiu, porque estava fundada sobre a rocha." Este versículo enfatiza a importância de construir sobre um fundamento sólido e resistente, assim como na construção da igreja como um edifício espiritual.
* 1 Coríntios 12:12-13: "Porque, assim como o corpo é um e tem muitos membros, e todos os membros, sendo muitos, são um só corpo, assim é Cristo também. Pois todos nós fomos batizados em um Espírito, formando um corpo, quer judeus, quer gregos, quer servos, quer livres, e todos temos bebido de um só Espírito." Este versículo destaca a importância da unidade entre os crentes e da participação de todos na construção da igreja como um edifício espiritual.
****

[[v53-3-1]]

^<<v53-3-1,1>>^ Quanto a mim. Irmãos, não vos pude falar como a espirituais, mas como a carnais, como a pequeninos em Cristo.

[[v53-3-2]]

^<<v53-3-2,2>>^ Nutri-vos com leite, não com alimento sólido, porque não podíeis (digeri-lo) e nem ainda agora podeis, porque sois ainda carnais. (ver nota)

[[v53-3-3]]

^<<v53-3-3,3>>^ Porquanto, havendo entre vós rivalidades e contendas, não é porque sois carnais e andais segundo o homem?

[[v53-3-4]]

^<<v53-3-4,4>>^ Quando um diz: "Eu sou de Paulo!" e outro: "Eu sou de Apolo!" não (se está vendo nisto que) sois homens (carnais)? Que é, pois, Apolo? E que é Paulo?

[[v53-3-5]]

^<<v53-3-5,5>>^ Ministros daquele, em quem vós crestes, e segundo o que o Senhor deu a cada um.

[[v53-3-6]]

^<<v53-3-6,6>>^ Eu plantei. Apolo regou, mas Deus é que deu o crescimento.

[[v53-3-7]]

^<<v53-3-7,7>>^ De modo que não é nada nem o que planta, nem o que rega, mas Deus, que dá o crescimento. (ver nota)

[[v53-3-8]]

^<<v53-3-8,8>>^ Uma mesma coisa é o que planta e o que rega; cada um receberá a sua recompensa segundo o seu trabalho.

[[v53-3-9]]

^<<v53-3-9,9>>^ Efetivamente, somos cooperadores de Deus. Vós sois cultura de Deus, sois edifício de Deus.

[[v53-3-10]]

^<<v53-3-10,10>>^ Segundo a graça de Deus que me foi dada, lancei (entre vós) o fundamento (da fé), como sábio arquiteto, mas outro edifica sobre ele. Veja cada um como edifica sobre ele.

[[v53-3-11]]

^<<v53-3-11,11>>^ Porque ninguém pode pôr outro fundamento, senão o que foi posto, isto é, Jesus Cristo.

[[v53-3-12]]

^<<v53-3-12,12>>^ Se alguém edifica sobre este fundamento com ouro, prata, pedras preciosas, madeira, feno, palha, (ver nota)

[[v53-3-13]]

^<<v53-3-13,13>>^ manifestada será a obra de cada um, pois o dia do Senhor a fará conhecer, visto que será revelado no fogo, e o fogo provará qual seja a obra de cada um.

[[v53-3-14]]

^<<v53-3-14,14>>^ Se subsistir a obra do que a sobreedificou, receberá prêmio. (ver nota)

[[v53-3-15]]

^<<v53-3-15,15>>^ Se a obra de algum arder, ele sofrerá o prejuízo, mas será salvo, apesar disso, como por meio do fogo.

[[v53-3-16]]

^<<v53-3-16,16>>^ Não sabeis que sois templo de Deus e que o Espírito de Deus habita em vós?

[[v53-3-17]]

^<<v53-3-17,17>>^ Se alguém destruir o templo de Deus, Deus o destruirá. Com efeito, é santo o templo de Deus, que vós sois.

[[v53-3-18]]

^<<v53-3-18,18>>^ Ninguém se iluda! Se algum dentre vós se tem por sábio, segundo este mundo, faça-se insensato para ser sábio.

[[v53-3-19]]

^<<v53-3-19,19>>^ Porque a sabedoria deste mundo é loucura diante de Deus, pois está escrito: Eu apanharei os sábios na sua própria astúcia (Job. 5, 13).

[[v53-3-20]]

^<<v53-3-20,20>>^ E outra vez: O Senhor conhece os pensamentos dos sábios; conhece que são vãos (Ps. 93, 11).

[[v53-3-21]]

^<<v53-3-21,21>>^ Portanto ninguém se glorie entre os homens.

[[v53-3-22]]

^<<v53-3-22,22>>^ Porque todas as coisas são vossas, ou seja Paulo, ou seja Apolo, ou seja Cefas, ou seja o mundo, ou seja a vida ou seja a morte, ou sejam as coisas presentes, ou sejam as futuras; tudo é vosso, (ver nota)

[[v53-3-23]]

^<<v53-3-23,23>>^ mas vós (sois) de Cristo, e Cristo de Deus.

'''

xref:053-i-corintios/053-i-corintios-002.adoc#v53-2-0[&#60; Capítulo Anterior] | <<v53-3-0,Topo>> | xref:053-i-corintios/053-i-corintios-004.adoc#v53-4-0[Próximo Capítulo &#62;]