include::./index.adoc[]

[[v53-14-0]]
=== I Coríntios, 14
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 14 de 1 Coríntios trata do uso correto dos dons espirituais na igreja, especialmente o dom de línguas e profecia. Paulo enfatiza que o objetivo principal dos dons é edificar a igreja e exorta os coríntios a buscarem os dons que mais edificam a comunidade. Ele também orienta sobre a importância da compreensão e interpretação dos dons para que todos possam ser edificados.
* 1 Coríntios 12:31b: "Contudo, eu lhes mostrarei o caminho mais excelente." Paulo destaca a importância da busca pelo amor, que é o caminho mais excelente e fundamental para o uso correto dos dons espirituais.
* Romanos 12:6-8: "Temos diferentes dons, de acordo com a graça que nos foi dada. Se alguém tem o dom de profecia, use-o na proporção da sua fé. Se o seu dom é servir, sirva; se é ensinar, ensine; se é dar ânimo, que assim faça; se é contribuir, contribua generosamente; se é liderar, lidere com zelo; se é mostrar misericórdia, que o faça com alegria." Paulo fala sobre a diversidade de dons e habilidades, enfatizando que cada um deve usar o seu dom para o bem da comunidade.
* 1 Coríntios 14:12: "Assim, visto que vocês estão ansiosos por terem dons espirituais, procurem-os com zelo para que possam contribuir com a igreja." Paulo incentiva os coríntios a buscarem os dons que mais edificam a igreja, mas de forma equilibrada e buscando a edificação mútua.
* 1 Coríntios 14:22: "Assim, as línguas são um sinal não para os crentes, mas para os descrentes; a profecia, porém, é para os crentes, não para os descrentes." Paulo destaca a importância da compreensão e interpretação dos dons para que sejam edificantes para todos, especialmente para os descrentes que podem ser impactados pela manifestação dos dons.
* 1 Coríntios 14:26: "Que faremos, pois, irmãos? Quando vocês se reunirem, cada um de vocês tem um salmo, ou uma palavra de ensino, uma revelação, uma palavra em outra língua ou uma interpretação. Tudo seja feito para a edificação da igreja." Paulo enfatiza que o objetivo principal dos dons é edificar a igreja, e que todos devem contribuir de forma equilibrada e visando a edificação mútua.
****

[[v53-14-1]]

^<<v53-14-1,1>>^ Procurai a caridade, aspirai aos dons espituais e, sobre todos, ao da profecia. (ver nota)

[[v53-14-2]]

^<<v53-14-2,2>>^ A razão é que, o que fala uma língua (desconhecida), não fala aos homens, mas a Deus. Com efeito, ninguém o compreende: pelo espírito fala coisas misteriosas. (ver nota)

[[v53-14-3]]

^<<v53-14-3,3>>^ Ao contrário, o que profetiza, fala aos homens para sua edificação, exortação e consolação.

[[v53-14-4]]

^<<v53-14-4,4>>^ O que fala uma língua (desconhecida), edifica-se a si mesmo; o que profetiza, edifica a Igreja de Deus.

[[v53-14-5]]

^<<v53-14-5,5>>^ Desejo que todos vós tenhais o dom das línguas; porém, muito mais que profetizeis. De facto, é maior o que profetiza, que o que fala diversas línguas, a não ser que também as interprete, a fim de que a Igreja receba edificação.

[[v53-14-6]]

^<<v53-14-6,6>>^ Assim, pois. Irmãos, se eu for ter convosco falando em diversas línguas, de que vos aproveitarei, se vos não falar com a revelação, ou com a ciência, ou com a profecia, ou com a doutrina?

[[v53-14-7]]

^<<v53-14-7,7>>^ Do mesmo modo as coisas inanimadas, que dão som, como a flauta ou a citara, se não derem sons distintos, como se distinguirá o que se toca na flauta ou na citara?

[[v53-14-8]]

^<<v53-14-8,8>>^ E, se a trombeta der um som confuso, quem se preparará para a batalha?

[[v53-14-9]]

^<<v53-14-9,9>>^ Assim também vós, se, falando uma língua, não proferirdes palavras claras, como se entenderá o que dizeis? Falareis ao vento.

[[v53-14-10]]

^<<v53-14-10,10>>^ Há, com efeito, muitos gêneros de línguas neste mundo, e todas têm a sua expressão.

[[v53-14-11]]

^<<v53-14-11,11>>^ Se eu, pois, não entender o que significam as palavras, serei bárbaro para aquele a quem falo; e o que fala será bárbaro para mim.

[[v53-14-12]]

^<<v53-14-12,12>>^ Assim também vós, já que sois desejosos de dons espirituais, procurai abundar neles para edificação da Igreja.

[[v53-14-13]]

^<<v53-14-13,13>>^ Por isso, o que fala uma língua desconhecida, peça o dom de a interpretar.

[[v53-14-14]]

^<<v53-14-14,14>>^ Se eu orar numa língua (desconhecida, verdade é que) o meu espírito ora, mas o meu entendimento fica sem fruto.

[[v53-14-15]]

^<<v53-14-15,15>>^ Que hei-de, pois, fazer? Orarei com o espírito, orarei também com a inteligência. Cantarei com o espírito, cantarei também com a inteligência.

[[v53-14-16]]

^<<v53-14-16,16>>^ Mas, se deres graças com o espírito, o que ocupa o lugar do simples povo como responderá Amen à tua acção de graças, não entendendo o que dizes?

[[v53-14-17]]

^<<v53-14-17,17>>^ Verdade é que tu dás bem a acção de graças, mas o outro não é edificado.

[[v53-14-18]]

^<<v53-14-18,18>>^ Dou graças ao meu Deus, porque falo em línguas mais que todos vós.

[[v53-14-19]]

^<<v53-14-19,19>>^ Mas na Igreja eu antes quero dizer cinco palavras, de modo a ser compreendido para instruir também os outros, do que dez mil palavras em línguas.

[[v53-14-20]]

^<<v53-14-20,20>>^ Irmãos, não sejais crianças no julgar. Em malícia sede pequeninos, mas no julgar sede homens maduros.

[[v53-14-21]]

^<<v53-14-21,21>>^ Na lei está escrito: Por outras línguas e por outros lábios falarei a este povo, e nem ainda assim me ouvirão, diz o Senhor (Is. 28, 11-12).

[[v53-14-22]]

^<<v53-14-22,22>>^ As línguas, pois, são um sinal, não para os fiéis, mas para os infiéis; porém as profecias (são um sinal) não para os infiéis mas para os fiéis.

[[v53-14-23]]

^<<v53-14-23,23>>^ Se, pois, toda a Igreja se reunir em assembleia, e todos falarem línguas diversas, e entrarem então pessoas não iniciadas ou infiéis, não dirão que estais loucos ?

[[v53-14-24]]

^<<v53-14-24,24>>^ Porém, se todos profetizarem, e entrar um infiel ou um não iniciado, por todos é convencido, por todos é julgado ;

[[v53-14-25]]

^<<v53-14-25,25>>^ as coisas ocultas do seu coração tornam-se manifestas e, assim, prostrado com a face por terra, adorará a Deus, declarando que Deus está verdadeiramente entre vós.

[[v53-14-26]]

^<<v53-14-26,26>>^ Que haveis, pois, de fazer, Irmãos ? Quando vos reunis, se um de vós tem um cântico, outro uma instrução, outro uma revelação, outro um discurso em línguas, outro uma interpretação, faça-se tudo de uma forma edificante.

[[v53-14-27]]

^<<v53-14-27,27>>^ Se alguém fala em línguas, falem dois, ou quando muito três, e um depois do outro, e haja um que interprete (o que eles disserem).

[[v53-14-28]]

^<<v53-14-28,28>>^ Se não houver intérprete, estejam calados na Igreja, não falem senão consigo e com Deus.

[[v53-14-29]]

^<<v53-14-29,29>>^ Pelo que toca, porém, aos profetas, falem dois ou três, e os outros julguem (o que ouvirem).

[[v53-14-30]]

^<<v53-14-30,30>>^ Se (neste tempo) for feita qualquer revelação a algum dos assistentes, cale-se o que falava primeiro.

[[v53-14-31]]

^<<v53-14-31,31>>^ Em verdade, vós podeis profetizar todos, um depois do outro, a fim de que todos aprendam e todos sejam exortados.

[[v53-14-32]]

^<<v53-14-32,32>>^ Os espíritos dos profetas estão sujeitos aos profetas. (ver nota)

[[v53-14-33]]

^<<v53-14-33,33>>^ Porquanto Deus não é Deus de discórdia, mas de paz. Como (se faz) em todas as igrejas dos santos,

[[v53-14-34]]

^<<v53-14-34,34>>^ as mulheres estejam caladas nas assembléias ; não lhes é permitido falar, mas devem estar sujeitas, como também o diz a lei.

[[v53-14-35]]

^<<v53-14-35,35>>^ Se querem ser instruídas sobre algum ponto, interroguem em casa os seus maridos, porque é vergonhoso para uma mulher falar numa assembleia.

[[v53-14-36]]

^<<v53-14-36,36>>^ Porventura é de vós que saiu a palavra de Deus ? Ou é só a vós que ela chegou ? (ver nota)

[[v53-14-37]]

^<<v53-14-37,37>>^ Se algum crê ser profeta ou rico em dons espirituais, reconheça que as coisas que vos escrevo são mandamentos do Senhor.

[[v53-14-38]]

^<<v53-14-38,38>>^ Se algum, porém, o ignora, é ignorado por Deus.

[[v53-14-39]]

^<<v53-14-39,39>>^ Por isso, Irmãos, desejai ardentemente o dom de profetizar e não proibaís o falar em línguas.

[[v53-14-40]]

^<<v53-14-40,40>>^ Mas faça-se tudo decentemente e com ordem.

'''

xref:053-i-corintios/053-i-corintios-013.adoc#v53-13-0[&#60; Capítulo Anterior] | <<v53-14-0,Topo>> | xref:053-i-corintios/053-i-corintios-015.adoc#v53-15-0[Próximo Capítulo &#62;]