include::./index.adoc[]

[[v66-3-0]]
=== São Tiago, 3
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 3 do livro de São Tiago aborda o tema do controle da língua, alertando sobre o poder destrutivo que ela pode ter. O capítulo destaca a importância de se ter autocontrole e sabedoria na forma como se fala e se relaciona com os outros. Segue abaixo cinco versículos selecionados de outros livros da Bíblia que estão relacionados com os temas abordados em São Tiago 3:
* Provérbios 12:18: "Há palavras que ferem como espada, mas a língua dos sábios traz a cura." Este versículo destaca o poder das palavras para ferir ou curar. Reforça a importância de se escolher cuidadosamente as palavras que são ditas.
* Provérbios 16:23-24: "O coração do sábio faz que a sua boca fale e acrescenta doutrina aos seus lábios. As palavras suaves são favos de mel, doces para a alma e saúde para os ossos." Esse versículo enfatiza a importância da sabedoria e como ela influencia a forma como falamos. Mostra que as palavras gentis podem ter um efeito curativo.
* Efésios 4:29: "Não saia da vossa boca nenhuma palavra torpe, e sim unicamente a que for boa para edificação, conforme a necessidade, e, assim, transmita graça aos que ouvem." Esse versículo destaca a importância de falar palavras que edificam e ajudam as pessoas.
* Provérbios 17:27: "Quem tem conhecimento modera as suas palavras, e o homem de discernimento é frio de espírito." Esse versículo destaca a importância de ter autocontrole e sabedoria na forma como se fala.
* Mateus 12:36-37: "Digo-vos que de toda palavra frívola que proferirem os homens, dela darão conta no Dia do Juízo; porque, pelas tuas palavras, serás justificado e, pelas tuas palavras, serás condenado." Esse versículo enfatiza a importância de se ter cuidado com as palavras que são ditas, pois elas têm o poder de influenciar o julgamento divino.
****

[[v66-3-1]]

^<<v66-3-1,1>>^ Não sejais, irmãos meus, muitos de vós a fazer-vos mestres, sabendo que vos expondes a um juízo mais severo,

[[v66-3-2]]

^<<v66-3-2,2>>^ porque todos pecamos em muitas coisas. Se alguém não peca em qualquer palavra, este (pode dizer-se que) é um homem perfeito, capaz de suster com freio todo o corpo (com as suas paixões).

[[v66-3-3]]

^<<v66-3-3,3>>^ Com efeito, quando pomos o freio na boca dos cavalos, para que nos obedeçam, também governamos todo o seu corpo.

[[v66-3-4]]

^<<v66-3-4,4>>^ Vede também as naus: ainda que sejam grandes e se achem agitadas de ventos impetuosos, com um pequeno leme se voltam para onde quiser o piloto.

[[v66-3-5]]

^<<v66-3-5,5>>^ Assim também a língua é um pequeno membro, mas pode gloriar-se de grandes coisas. Vede como um pouco de fogo incendeia um grande bosque!

[[v66-3-6]]

^<<v66-3-6,6>>^ Também a língua é um fogo, um mundo de iniquidade. A língua está entre os nossos membros e contamina todo o corpo e inflama (com o fogo das paixões) todo nosso viver, sendo ela mesma inflamada pelo inferno.

[[v66-3-7]]

^<<v66-3-7,7>>^ Todas as espécies de animais selvagens, de aves, de répteis e de animais marinhos se domam, têm sido domadas pelo homem,

[[v66-3-8]]

^<<v66-3-8,8>>^ porém a língua nenhum homem a pode domar: é um flagelo sem repouso, está cheia de veneno mortífero.

[[v66-3-9]]

^<<v66-3-9,9>>^ Com ela bendizemos o Senhor nosso Pai, e com ela amaldiçoamos os homens, que foram feitos à semelhança de Deus.

[[v66-3-10]]

^<<v66-3-10,10>>^ Da mesma boca procede a bênção e a maldição. Não convém, meus irmãos, que isto seja assim.

[[v66-3-11]]

^<<v66-3-11,11>>^ Porventura uma fonte lança pela mesma bica água doce e amargosa?

[[v66-3-12]]

^<<v66-3-12,12>>^ Porventura, irmãos meus, pode a figueira dar uvas, ou a videira figos? Uma fonte de água salgada não pode dar água doce,

[[v66-3-13]]

^<<v66-3-13,13>>^ Quem é entre vós sábio e inteligente? Mostre mediante uma boa vida as suas obras feitas com mansidão é sabedoria.

[[v66-3-14]]

^<<v66-3-14,14>>^ Mas se tendes um zelo amargo e espírito de contenda em vossos corações, não vos glorieis, nem sejais mentirosos contra a verdade.

[[v66-3-15]]

^<<v66-3-15,15>>^ Tal sabedoria não vem do alto, mas (é uma sabedoria) terrena, carnal, diabólica.

[[v66-3-16]]

^<<v66-3-16,16>>^ Em realidade, onde há ciúme e contenda, aí há também desordem e toda a obra má.

[[v66-3-17]]

^<<v66-3-17,17>>^ A sabedoria, porém, que vem do alto, primeiramente é pura, depois pacífica, indulgente, condescendente, cheia de misericórdia e de bons frutos, sem parcialidade, sem hipocrisia.

[[v66-3-18]]

^<<v66-3-18,18>>^ Ora o fruto da justiça é semeado na paz por aqueles que praticam a paz.

'''

xref:066-sao-tiago/066-sao-tiago-002.adoc#v66-2-0[&#60; Capítulo Anterior] | <<v66-3-0,Topo>> | xref:066-sao-tiago/066-sao-tiago-004.adoc#v66-4-0[Próximo Capítulo &#62;]