include::./index.adoc[]

[[v62-4-0]]
=== II Timóteo, 4
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 4 de 2 Timóteo trata sobre a responsabilidade de Timóteo em pregar a palavra de Deus e manter a fé, apesar das adversidades. Paulo aconselha Timóteo a perseverar em sua missão e a cumprir fielmente seu ministério. Além disso, Paulo faz referência a sua própria vida e ministério, reconhecendo que o fim de sua vida terrena está próximo. Abaixo estão cinco versículos relacionados aos temas abordados em 2 Timóteo 4:
* Provérbios 4:23: "Sobre tudo o que se deve guardar, guarda o teu coração, porque dele procedem as saídas da vida." Este versículo enfatiza a importância de manter o coração e a mente focados em Deus e sua palavra, algo que é fundamental para Timóteo cumprir fielmente sua missão.
* 1 Coríntios 15:58: "Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão no Senhor." Este versículo encoraja Timóteo a continuar firme em seu trabalho e a perseverar, mesmo em meio às adversidades.
* Hebreus 12:1: "Portanto, nós também, pois estamos rodeados de tão grande nuvem de testemunhas, deixemos todo embaraço, e o pecado que tão de perto nos rodeia, e corramos com paciência a carreira que nos está proposta." Este versículo encoraja Timóteo a manter a fé e a perseverar, lembrando-o que ele não está sozinho em sua jornada.
* Filipenses 3:14: "Prossigo para o alvo, pelo prêmio da soberana vocação de Deus em Cristo Jesus." Este versículo encoraja Timóteo a manter o foco em sua missão e a seguir em frente, sem desistir.
* Tiago 1:12: "Bem-aventurado o homem que suporta a tentação; porque, quando for provado, receberá a coroa da vida, a qual o Senhor tem prometido aos que o amam." Este versículo incentiva Timóteo a resistir à tentação e a perseverar, lembrando-o de que há uma recompensa para aqueles que permanecem fiéis a Deus.
****

[[v62-4-1]]

^<<v62-4-1,1>>^ Conjuro-te diante de Deus e de Jesus Cristo, que há-de julgar os vivos e os mortos, pela sua vinda e pelo seu reino:

[[v62-4-2]]

^<<v62-4-2,2>>^ prega a palavra, insiste a tempo e fora de tempo, repreende, corrige, admoesta com toda a paciência e doutrina,

[[v62-4-3]]

^<<v62-4-3,3>>^ porque virá tempo em que (muitos) não suportarão a sã doutrina, mas acumularão mestres em volta de si, ao sabor das suas paixões, (levados) pelo prurido de ouvir.

[[v62-4-4]]

^<<v62-4-4,4>>^ Afastarão os ouvidos da verdade e os aplicarão às fábulas.

[[v62-4-5]]

^<<v62-4-5,5>>^ Tu, porém, vigia sobre todas as coisas, suporta os trabalhos, faze a obra de evangelista, cumpre o teu ministério.

[[v62-4-6]]

^<<v62-4-6,6>>^ Quanto a mim, estou já oferecido em libação (derramando o meu sangue), e o tempo da minha partida avizinha-se.

[[v62-4-7]]

^<<v62-4-7,7>>^ Combati, até ao fim, o bom combate, acabei a minha carreira, guardei a fé.

[[v62-4-8]]

^<<v62-4-8,8>>^ De resto, está-me preparada a coroa da justiça que o Senhor, justo Juiz, me dará naquele dia; porém não só a mim, mas também àqueles que esperam com amor a sua vinda.

[[v62-4-9]]

^<<v62-4-9,9>>^ Apressa-te a vir ter comigo. Demas abandonou-me, por amor deste século, e foi para Tessalonica;

[[v62-4-10]]

^<<v62-4-10,10>>^ Crescente (foi) para a Galácia, Tito para a Dalmácia.

[[v62-4-11]]

^<<v62-4-11,11>>^ Só Lucas está comigo. Toma contigo Marcos e traze-o, porque me é útil para o ministério (evangélico). (ver nota)

[[v62-4-12]]

^<<v62-4-12,12>>^ Tíquico enviei-o a Éfeso.

[[v62-4-13]]

^<<v62-4-13,13>>^ Quando vieres, traze contigo a capa que deixei em Trôade, em casa de Carpo, e os livros, principalmente os pergaminhos.

[[v62-4-14]]

^<<v62-4-14,14>>^ Alexandre, o latoeiro, fez-me muitos males; o Senhor lhe pagará segundo as suas obras. (ver nota)

[[v62-4-15]]

^<<v62-4-15,15>>^ Tu também guarda-te dele, porque opõe uma forte resistência às nossas palavras.

[[v62-4-16]]

^<<v62-4-16,16>>^ Ninguém me assistiu na minha primeira defesa, mas todos me desampararam; que isto lhes não seja imputado.

[[v62-4-17]]

^<<v62-4-17,17>>^ O Senhor, porém, assistiu-me e confortou-me, para que fosse cumprida por mim a pregação, e a ouvissem todos os gentios, e, assim, fui livre da boca do leão. (ver nota)

[[v62-4-18]]

^<<v62-4-18,18>>^ O Senhor me livrará de toda a obra má e me salvará (fazendo-me entrar) no seu reino celestial: a ele seja dada glória pelos séculos dos séculos! Amen.

[[v62-4-19]]

^<<v62-4-19,19>>^ Saúda Prisca, Áquila e a família de Onesíforo.

[[v62-4-20]]

^<<v62-4-20,20>>^ Erasto ficou em Corinto. A Trófimo deixei-o doente, em Mileto.

[[v62-4-21]]

^<<v62-4-21,21>>^ Apressa-te a vir, antes do inverno. Saúdam-te Eubulo, Pudente. Lino, Cláudia e todos os irmãos (desta cidade).

[[v62-4-22]]

^<<v62-4-22,22>>^ O Senhor Jesus Cristo seja com o teu espírito. A graça seja convosco.

'''

xref:062-ii-timoteo/062-ii-timoteo-003.adoc#v62-3-0[&#60; Capítulo Anterior] | <<v62-4-0,Topo>> | xref:063-tito/063-tito-001.adoc#v63-1-0[Próximo Capítulo &#62;]