include::./index.adoc[]

[[v35-10-0]]
=== Oséias, 10
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 10 de Oséias fala sobre a punição que Israel sofrerá por causa de sua idolatria e infidelidade. O profeta compara o povo a uma vinha rebelde e prediz a destruição de seus altares e ídolos. A seguir estão cinco versículos de outras partes da Bíblia que se relacionam com os temas abordados em Oséias 10.
* Deuteronômio 28:58-59: "Se você não obedecer a todas as palavras desta lei, que estão escritas neste livro, e não temer este nome glorioso e temível, o Senhor, o seu Deus, enviarei sobre vocês e sobre seus descendentes desgraças terríveis e doenças duradouras e graves calamidades." Este trecho descreve as consequências da desobediência a Deus e seu julgamento sobre aqueles que se rebelam contra Ele.
* 2 Reis 17:7-8: "Isso aconteceu porque os israelitas tinham pecado contra o Senhor, seu Deus, que os havia tirado do Egito, da mão do faraó, rei do Egito. Eles adoraram outros deuses e seguiram os costumes das nações que o Senhor tinha expulsado de diante deles, assim como os costumes que os reis de Israel haviam introduzido." Este versículo fala sobre como o povo de Israel se afastou do caminho de Deus e se voltou para deuses falsos, seguindo as práticas dos povos pagãos ao seu redor.
* Jeremias 4:3-4: "Porque assim diz o Senhor aos homens de Judá e Jerusalém: ‘Lavrem para si um campo novo, e não semeiem entre os espinhos. Circuncidem-se ao Senhor, circuncidem o coração de vocês, ó homens de Judá e de Jerusalém, para que a minha ira não irrompa como fogo e queime, sem que ninguém a apague, por causa da maldade de vocês.’" Este trecho enfatiza a importância da verdadeira circuncisão do coração e do arrependimento para evitar a ira de Deus.
* Salmos 51:17: "Os sacrifícios que agradam a Deus são um espírito quebrantado; um coração quebrantado e contrito, ó Deus, não desprezarás." Este versículo mostra que Deus valoriza a humildade e a contrição em vez de sacrifícios externos ou formalidades religiosas.
* Isaías 45:9: "Ai daquele que contende com o seu Criador! O caco entre outros cacos de barro! Acaso o barro pode dizer ao oleiro que o modelou: ‘O que você está fazendo?’ ou: ‘A sua obra não tem alças’?" Este versículo destaca a soberania de Deus e a futilidade da rebelião contra Ele.
****

[[v35-10-1]]

^<<v35-10-1,1>>^ Israel era uma vinha frondosa, que dava os frutos correspondentes. Quanto mais abundou em frutos, tanto mais multiplicou os seus altares; quanto mais rica era a terra, mais ricas estelas construía.

[[v35-10-2]]

^<<v35-10-2,2>>^ É falso o seu coração: vão sofrer o castigo devido. Ele mesmo (o Senhor) quebrará os seus altares e deitará abaixo as suas estelas.

[[v35-10-3]]

^<<v35-10-3,3>>^ Dentro em breve eles dirão: Nós não temos rei (que possa salvarmos), porque não tememos o Senhor; e que faria por nós o rei (querendo Deus castigarmos)?

[[v35-10-4]]

^<<v35-10-4,4>>^ Proferem palavras vãs, juram falso, concluem alianças, mas o castigo de (Deus) brotará como erva venenosa sobre os sulcos dum campo (semeado).

[[v35-10-5]]

^<<v35-10-5,5>>^ Os habitantes da Samaria tremerão por causa do bezerro, (de ouro) de Betaven. O seu povo (que adorava este ídolo) toma luto por ele, e o bando dos seus sacerdotes faz lamentações por causa de a sua riqueza ter sido transferida para longe dele. (ver nota)

[[v35-10-6]]

^<<v35-10-6,6>>^ Ele também será levado para a Assíria, como um presente ao grande rei. A confusão apoderar-se-á de Efraim e Israel ficará envergonhado por ter seguido os seus caprichos.

[[v35-10-7]]

^<<v35-10-7,7>>^ A Samaria está aniquilada. O seu rei é como espuma sobre a superfície da água.

[[v35-10-8]]

^<<v35-10-8,8>>^ Os lugares altos de Betaven, que fazem o pecado de Israel, serão destruídos; sobre os seus altares crescerão espinhos e abrolhos. Então dirão às montanhas : Cobri-nos! — e aos outeiros: Caí sobre nós. (ver nota)

[[v35-10-9]]

^<<v35-10-9,9>>^ Desde os dias de Gabaa, tens pecado, ó Israel. Aí tomaram posições (contra mim). Não os apanhará em Gabaa a guerra (declarada) contra os filhos da iniquidade? (ver nota)

[[v35-10-10]]

^<<v35-10-10,10>>^ Castigá-los-ei à medida do meu desejo; porque devem ser punidos por causa das suas duas iniquidades, juntar-se-ão contra eles os povos.

[[v35-10-11]]

^<<v35-10-11,11>>^ Efraim era como uma novilha bem tratada, que gostava de pisar a eira (na ocasião da debulha); mas eu porei um jugo sobre o seu pescoço; atrelarei Efraim, Judá lavrará, Jacob puxará a grade, (ver nota)

[[v35-10-12]]

^<<v35-10-12,12>>^ Semeai para vós na justiça, segai segundo a misericórdia, rompei os vossos pousios, porque é tempo de buscar o Senhor, até que venha ensinar-vos a justiça _(ou santidade). (ver nota)

[[v35-10-13]]

^<<v35-10-13,13>>^ Cultivastes a impiedade, segastes a iniquidade, comestes o fruto da mentira. Confiaste nos teus caminhos e na multidão dos teus valentes.

[[v35-10-14]]

^<<v35-10-14,14>>^ Levantar-se-á tumulto entre o teu povo; todas as tuas fortificações serão destruídas, como Salmana destruiu Bet-Arbel, no dia da peleja, em que a mãe foi esmagada sobre os filhos.

[[v35-10-15]]

^<<v35-10-15,15>>^ Eis o que vos fez Betel, por causa da enormidade das vossas iniquidades.

'''

xref:035-oseias/035-oseias-009.adoc#v35-9-0[&#60; Capítulo Anterior] | <<v35-10-0,Topo>> | xref:035-oseias/035-oseias-011.adoc#v35-11-0[Próximo Capítulo &#62;]