include::./index.adoc[]

[[v69-2-0]]
=== I São João, 2
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 2 de 1 São João fala sobre a importância de obedecer aos mandamentos de Deus e seguir o exemplo de Jesus. Além disso, o autor adverte sobre a presença de falsos professores e ensina sobre o amor fraterno entre os irmãos na fé. Seguem abaixo cinco versículos relacionados com esses temas:
* Provérbios 19:16: "O que guarda o mandamento guarda a sua alma; mas o que despreza os seus caminhos morrerá." Este versículo enfatiza a importância de obedecer aos mandamentos de Deus, que trazem vida e proteção para aqueles que os seguem.
* João 15:10: "Se guardardes os meus mandamentos, permanecereis no meu amor; do mesmo modo que eu tenho guardado os mandamentos de meu Pai e permaneço no seu amor." Jesus é o exemplo máximo de obediência aos mandamentos de Deus, e ao segui-lo, também permanecemos no amor de Deus.
* Mateus 7:15: "Acautelai-vos dos falsos profetas, que se vos apresentam disfarçados em ovelhas, mas por dentro são lobos roubadores." Assim como 1 São João 2 adverte sobre a presença de falsos professores, este versículo de Mateus alerta sobre a necessidade de discernir os ensinamentos de quem se apresenta como líder religioso.
* Romanos 13:8: "Não devais a ninguém coisa alguma, a não ser o amor com que vos ameis uns aos outros; pois quem ama ao próximo cumpriu a lei." A prática do amor fraterno é uma das principais mensagens de 1 São João 2, e este versículo de Romanos enfatiza que amar ao próximo é cumprir a lei de Deus.
* Efésios 2:10: "Porque somos feitura sua, criados em Cristo Jesus para boas obras, as quais Deus de antemão preparou para que andássemos nelas." Assim como 1 São João 2 destaca a importância de seguir o exemplo de Jesus, este versículo de Efésios ensina que fomos criados em Cristo para realizar boas obras que foram preparadas por Deus para nós.
****

[[v69-2-1]]

^<<v69-2-1,1>>^ Filhinhos meus, eu vos escrevo estas coisas, para que não pequeis; mas, se algum pecar, (não desespere, pois) temos um advogado junto do Pai, Jesus Cristo, o justo.

[[v69-2-2]]

^<<v69-2-2,2>>^ Ele é a vítima de propiciação pelos nossos pecados, e não somente pelos nossos, mas também pelos de todo o mundo.

[[v69-2-3]]

^<<v69-2-3,3>>^ Sabemos que o conhecemos por isto: se guardamos os seus mandamentos.

[[v69-2-4]]

^<<v69-2-4,4>>^ Quem diz que o conhece e não guarda os seus mandamentos, é um mentiroso e a verdade não está nele.

[[v69-2-5]]

^<<v69-2-5,5>>^ Mas quem guarda a sua palavra, nesse o amor de Deus é verdadeiramente perfeito; por isto conhecemos que estamos nele.

[[v69-2-6]]

^<<v69-2-6,6>>^ Quem pretende estar nele, deve também andar como ele andou.

[[v69-2-7]]

^<<v69-2-7,7>>^ Caríssimos, não vos escrevo um mandamento novo, mas um mandamento velho, que recebestes desde o princípio; este mandamento velho é a palavra (do Evangelho) que ouvistes.

[[v69-2-8]]

^<<v69-2-8,8>>^ Mas, por outro lado, eu vos escrevo um mandamento novo — o qual é verdadeiro nele (Jesus Cristo) e em vós — pois que passaram as trevas e já resplandece a verdadeira luz.

[[v69-2-9]]

^<<v69-2-9,9>>^ Quem pretende estar na luz e odeia o seu irmão, está ainda nas trevas.

[[v69-2-10]]

^<<v69-2-10,10>>^ Quem ama o seu irmão, permanece na luz, e nele não há ocasião de queda.

[[v69-2-11]]

^<<v69-2-11,11>>^ Mas quem odeia seu irmão, está nas trevas, anda nas trevas e não sabe para onde vai, porque as trevas cegaram os seus olhos.

[[v69-2-12]]

^<<v69-2-12,12>>^ Eu vos escrevo, filhinhos, porque os vossos pecados vos são perdoados pelo seu nome.

[[v69-2-13]]

^<<v69-2-13,13>>^ Eu vos escrevo, pais, porque conhecestes aquele que é desde o princípio. Eu vos escrevo, adolescentes, porque vencestes o (espírito) maligno.

[[v69-2-14]]

^<<v69-2-14,14>>^ Eu vos escrevo, meninos, porque conhecestes o Pai. Eu vos escrevo, jovens, porque sois fortes, porque a palavra de Deus permanece em vós e porque vencestes o (espírito) maligno.

[[v69-2-15]]

^<<v69-2-15,15>>^ Não ameis o mundo nem as coisas do mundo. Se alguém ama o mundo, não há nele o amor do Pai,

[[v69-2-16]]

^<<v69-2-16,16>>^ porque tudo o que há no mundo — concupiscência da carne, concupiscência dos olhos e orgulho da riqueza — isto não vem do Pai, mas do mundo.

[[v69-2-17]]

^<<v69-2-17,17>>^ Ora o mundo passa, e a sua concupiscência com ele, mas o que faz a vontade de Deus permanece eternamente (no céu) .

[[v69-2-18]]

^<<v69-2-18,18>>^ Filhinhos, é a última hora. Como ouvistes dizer, o Anticristo está para vir, mas digo-vos que já há muitos Anticristos, donde conhecemos que é a última hora. (ver nota)

[[v69-2-19]]

^<<v69-2-19,19>>^ Eles saíram de entre nós, mas não eram dos nossos (verdadeiros fiéis), porque, se tivessem sido dos nossos, ficariam certamente conosco; mas (saíram de entre nós) para que se conheça que nem todos são dos nossos,

[[v69-2-20]]

^<<v69-2-20,20>>^ Porém vós recebestes a unção do Santo e tendes a ciência.

[[v69-2-21]]

^<<v69-2-21,21>>^ Não vos escrevi como a ignorantes da verdade, mas como a quem a conhece e (sabe) que da verdade não vem nenhuma mentira.

[[v69-2-22]]

^<<v69-2-22,22>>^ Quem é mentiroso senão aquele que nega que Jesus é o Cristo? Este é um Anticristo, que nega o Pai e o Filho.

[[v69-2-23]]

^<<v69-2-23,23>>^ Todo aquele que nega o Filho, também não possui o Pai; aquele que confessa o Filho, possui também o Pai.

[[v69-2-24]]

^<<v69-2-24,24>>^ O que ouvistes, desde o princípio (da vossa conversão), permanece em vós. Se em vós permanecer o que ouvistes desde o principio, também permanecereis no Filho e no Pai.

[[v69-2-25]]

^<<v69-2-25,25>>^ Esta é a promessa que ele mesmo nos fez: a vida eterna.

[[v69-2-26]]

^<<v69-2-26,26>>^ Eis o que eu vos tinha a escrever acerca daqueles que vos seduzem.

[[v69-2-27]]

^<<v69-2-27,27>>^ Permaneça em vós a unção que recebestes dele. Não tendes necessidade de que ninguém vos ensine (uma nova fé ); mas porque a sua unção vos ensina todas as coisas, e ela é verídica e não mentirosa, permanecei nele, segundo ela vos ensinou.

[[v69-2-28]]

^<<v69-2-28,28>>^ E agora, filhinhos, permanecei nele, para que, quando aparecer, tenhamos confiança e não sejamos confundidos por ele na sua vinda.

[[v69-2-29]]

^<<v69-2-29,29>>^ Se sabeis que ele é justo, sabei também que todo aquele, que pratica a justiça, nasceu dele.

'''

xref:069-i-sao-joao/069-i-sao-joao-001.adoc#v69-1-0[&#60; Capítulo Anterior] | <<v69-2-0,Topo>> | xref:069-i-sao-joao/069-i-sao-joao-003.adoc#v69-3-0[Próximo Capítulo &#62;]