include::./index.adoc[]

[[v69-3-0]]
=== I São João, 3
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* 1 São João 3 trata da filiação divina, do amor fraternal e da prática do pecado. O capítulo começa destacando o amor do Pai por nós, que somos chamados de filhos de Deus. Em seguida, o autor enfatiza que aquele que pratica o pecado é filho do diabo, pois o diabo peca desde o princípio. Ele também destaca a importância de amar ao próximo e mostra que esse amor é um sinal de que pertencemos a Deus. Por fim, o capítulo fala sobre a prática da justiça e como isso é evidência de que somos nascidos de Deus.
* Romanos 8:16: "O próprio Espírito testemunha ao nosso espírito que somos filhos de Deus." Esse versículo destaca a ideia de filiação divina mencionada em 1 São João 3. O autor de Romanos fala que o Espírito Santo testifica que somos filhos de Deus e, assim, podemos clamar a ele como "Abba, Pai".
* 1 Coríntios 15:33: "Não se deixem enganar: as más companhias corrompem os bons costumes." Esse versículo tem relação com o trecho em que o autor de 1 São João 3 enfatiza a importância de amar ao próximo. As más companhias podem levar uma pessoa a praticar o pecado, enquanto o amor ao próximo deve levá-la a fazer o bem.
* Hebreus 2:14-15: "Visto que os filhos têm em comum a carne e o sangue, também ele participou dessas coisas, para que pela sua morte derrotasse aquele que tem o poder da morte, isto é, o diabo, e libertasse aqueles que durante toda a vida estiveram escravizados pelo medo da morte." Esse versículo fala sobre a derrota do diabo, mencionado em 1 São João 3 como aquele que peca desde o princípio. A morte de Jesus na cruz liberta as pessoas do poder do diabo e do medo da morte.
* Tiago 2:14-17: "De que adianta, meus irmãos, alguém dizer que tem fé, se não tem obras? Acaso a fé pode salvá-lo? Se um irmão ou irmã estiver necessitando de roupas e do alimento de cada dia e um de vocês lhe disser: 'Vá em paz, aqueça-se e alimente-se até satisfazer-se', sem porém lhe dar nada, de que adianta isso? Assim também a fé, por si só, se não for acompanhada de obras, está morta." Esse versículo tem relação com a ideia de que a prática da justiça é evidência de que somos nascidos de Deus, mencionada em 1 São João 3. Tiago enfatiza que a fé sem obras está morta, ou seja, a fé deve ser acompanhada de ações que demonstrem o amor ao próximo.
****

[[v69-3-1]]

^<<v69-3-1,1>>^ Considerai que amor nos mostrou o Pai (em querer) que sejamos chamados filhos de Deus! E nós o somos. O mundo não nos conhece, porque não o conhece a ele.

[[v69-3-2]]

^<<v69-3-2,2>>^ Caríssimos, agora somos filhos de Deus, mas não se manifestou ainda o que seremos (um dia). Sabemos que, quando ele se manifestar, seremos semelhantes a ele (na glória), porque o veremos como ele é.

[[v69-3-3]]

^<<v69-3-3,3>>^ Todo o que tem esta esperança nele, torna-se puro, assim como também ele é puro.

[[v69-3-4]]

^<<v69-3-4,4>>^ Todo o que comete pecado transgride a lei, porque o pecado é uma transgressão da lei.

[[v69-3-5]]

^<<v69-3-5,5>>^ Sabeis que ele apareceu para tirar os pecados e que nele não há pecado.

[[v69-3-6]]

^<<v69-3-6,6>>^ Todo o que permanece nele, não peca; todo o que peca, não o viu, nem o conheceu (com amor).

[[v69-3-7]]

^<<v69-3-7,7>>^ Filhinhos, ninguém vos seduza. Aquele que pratica a justiça, é justo, como também ele é justo.

[[v69-3-8]]

^<<v69-3-8,8>>^ Aquele que comete o pecado, é do demônio, porque o demônio peca desde o principio. Para destruir as obras do demônio é que o Filho de Deus se manifestou.

[[v69-3-9]]

^<<v69-3-9,9>>^ Todo o que nasceu de Deus, não comete o pecado, porque a semente de Deus (que é a graça santificante) permanece nele: não pode pecar porque nasceu de Deus.

[[v69-3-10]]

^<<v69-3-10,10>>^ Nisto se distinguem os filhos de Deus dos filhos do demônio: todo o que não pratica a justiça, não é de Deus, e também não o é, o que não ama seu irmão,

[[v69-3-11]]

^<<v69-3-11,11>>^ visto que a mensagem que ouvistes, desde o princípio, é esta: Amemo-nos uns aos outros.

[[v69-3-12]]

^<<v69-3-12,12>>^ Não como Caim, que era do (espírito) maligno e matou seu irmão. E por que o matou? Porque as suas obras eram más, e as de seu irmão justas.

[[v69-3-13]]

^<<v69-3-13,13>>^ Não vos admireis, irmãos, de que o mundo vos tenha ódio.

[[v69-3-14]]

^<<v69-3-14,14>>^ Sabemos que fomos trasladados da morte (do pecado) para a vida (da graça), porque amamos os nossos irmãos. Aquele que não ama, permanece na morte.

[[v69-3-15]]

^<<v69-3-15,15>>^ Todo o que tem ódio a seu irmão é um homicida, e vós sabeis que a vida eterna não tem morada em nenhum homicida.

[[v69-3-16]]

^<<v69-3-16,16>>^ Nisto conhecemos o amor (de Deus): em ter dado a sua vida por nós. Igualmente nós devemos também (estar prontos a) dar a vida pelos nossos irmãos.

[[v69-3-17]]

^<<v69-3-17,17>>^ Se alguém que possua bens deste mundo, vir o seu irmão em necessidade e lhe fechar o seu coração, como está nele a caridade de Deus?

[[v69-3-18]]

^<<v69-3-18,18>>^ Meus filhinhos, não amemos (somente) de palavra e com a língua, mas por obra e em verdade.

[[v69-3-19]]

^<<v69-3-19,19>>^ Por isto conhecemos que somos da verdade e tranquilizaremos os nossos corações diante de Deus,

[[v69-3-20]]

^<<v69-3-20,20>>^ seja qual for a censura que o nosso coração nos dirija, porque Deus é maior do que o nosso coração e conhece todas as coisas.

[[v69-3-21]]

^<<v69-3-21,21>>^ Caríssimos, se o nosso coração nos não condenar, tenhamos confiança diante de Deus;

[[v69-3-22]]

^<<v69-3-22,22>>^ tudo o que lhe pedirmos, receberemos dele, porque guardamos os seus mandamentos e fazemos o que é agradável a seus olhos.

[[v69-3-23]]

^<<v69-3-23,23>>^ E (em resumo) este é o seu mandamento: que creiamos no nome de seu Filho Jesus Cristo e nos amemos uns aos outros, como ele nos mandou.

[[v69-3-24]]

^<<v69-3-24,24>>^ O que observa os seus mandamentos, está em Deus, e Deus nele; pelo Espírito que nos deu, sabemos que ele permanece em nós.

'''

xref:069-i-sao-joao/069-i-sao-joao-002.adoc#v69-2-0[&#60; Capítulo Anterior] | <<v69-3-0,Topo>> | xref:069-i-sao-joao/069-i-sao-joao-004.adoc#v69-4-0[Próximo Capítulo &#62;]