include::./index.adoc[]

[[v59-5-0]]
=== I Tessalonicenses, 5
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* 1 Tessalonicenses 5 é um capítulo que trata sobre a vinda do Senhor Jesus e o dia do Senhor. Ele encoraja os crentes a se manterem vigilantes e preparados para esse dia, exortando-os a viverem em santidade e amor uns pelos outros. Abaixo estão cinco versículos relacionados com esses temas:
* Mateus 24:42: "Vigiai, pois, porque não sabeis em que dia vem o vosso Senhor." Jesus exorta seus seguidores a permanecerem vigilantes e prontos para sua vinda.
* 2 Pedro 3:10: "Virá, pois, como ladrão o dia do Senhor, no qual os céus passarão com grande estrondo, e os elementos, ardendo, se dissolverão, e a terra, e as obras que nela há, serão descobertas." Pedro descreve a vinda do Senhor como um evento repentino e impactante, e adverte os cristãos a se prepararem para esse dia.
* 1 João 2:28: "E agora, filhinhos, permanecei nele, para que, quando ele se manifestar, tenhamos confiança e não sejamos confundidos por ele na sua vinda." João encoraja os crentes a permanecerem em Cristo, a fim de terem confiança e não serem confundidos em sua vinda.
* 1 Tessalonicenses 4:3: "Porque esta é a vontade de Deus, a vossa santificação; que vos abstenhais da prostituição." Paulo exorta os cristãos a viverem em santidade, em preparação para a vinda do Senhor.
* João 13:34: "Um novo mandamento vos dou: que vos ameis uns aos outros; como eu vos amei a vós, que também vós uns aos outros vos ameis." Jesus ensina a importância do amor mútuo entre os seguidores, um tema enfatizado em 1 Tessalonicenses 5.
****

[[v59-5-1]]

^<<v59-5-1,1>>^ Quanto, porém, ao tempo e ao momento (desta segunda vinda de Jesus Cristo) não tendes necessidade, irmãos, que vos escrevamos,

[[v59-5-2]]

^<<v59-5-2,2>>^ porque sabeis muito bem que o dia do Senhor virá como um ladrão durante a noite.

[[v59-5-3]]

^<<v59-5-3,3>>^ Quando (os ímpios) disserem: "Paz e segurança" então lhes sobrevirá uma destruição repentina, como as dores a uma mulher grávida, e não escaparão.

[[v59-5-4]]

^<<v59-5-4,4>>^ Mas vós, irmãos, não estais nas trevas, de modo que aquele dia vos surpreenda como um ladrão,

[[v59-5-5]]

^<<v59-5-5,5>>^ porque todos sois filhos da luz e filhos do dia. Não somos filhos da noite nem das trevas. (ver nota)

[[v59-5-6]]

^<<v59-5-6,6>>^ Não durmamos, pois, como os outros, mas vigiemos e sejamos sóbrios.

[[v59-5-7]]

^<<v59-5-7,7>>^ Os que dormem, dormem de noite; e os que se embriagam, embriagam-se de noite.

[[v59-5-8]]

^<<v59-5-8,8>>^ Mas nós, que somos (filhos) do dia (isto é da luz da fé), sejamos sóbrios, estando revestidos da couraça da fé e da caridade, e (tendo) por elmo a esperança da salvação,

[[v59-5-9]]

^<<v59-5-9,9>>^ pois Deus não nos destinou para a ira, mas para alcançar a salvação, por Nosso Senhor Jesus Cristo,

[[v59-5-10]]

^<<v59-5-10,10>>^ que morreu por nós, afim de que, ou vigiemos ou durmamos, vivamos juntamente com ele.

[[v59-5-11]]

^<<v59-5-11,11>>^ Pelo que, consolai-vos mutuamente e edificai-vos uns aos outros, como já fazeis.

[[v59-5-12]]

^<<v59-5-12,12>>^ Nós vos suplicamos, irmãos, que tenhais consideração com aqueles que trabalham entre vós, que vos governam no Senhor e vos admoestam.

[[v59-5-13]]

^<<v59-5-13,13>>^ Tende com eles uma caridade particular, por causa das funções que desempenham. Vivei em paz entre vós.

[[v59-5-14]]

^<<v59-5-14,14>>^ Pedimo-vos também, irmãos, que corrijais os que não observam a boa ordem, conforteis os pusilânimes, suporteis os fracos, sejais pacientes com todos.

[[v59-5-15]]

^<<v59-5-15,15>>^ Vede que nenhum retribua a outro mal por mal, mas procurai sempre fazer bem entre vós e para com todos.

[[v59-5-16]]

^<<v59-5-16,16>>^ Estai sempre alegres;

[[v59-5-17]]

^<<v59-5-17,17>>^ orai sem cessar; (ver nota)

[[v59-5-18]]

^<<v59-5-18,18>>^ por tudo dai graças (a Deus), porque esta é a vontade de Deus, em Jesus Cristo, em relação a todos vós.

[[v59-5-19]]

^<<v59-5-19,19>>^ Não extingais o Espírito (Santo); (ver nota)

[[v59-5-20]]

^<<v59-5-20,20>>^ não desprezeis as profecias;

[[v59-5-21]]

^<<v59-5-21,21>>^ examinai tudo e abraçai o que for bom;

[[v59-5-22]]

^<<v59-5-22,22>>^ guardai-vos de toda a espécie de mal.

[[v59-5-23]]

^<<v59-5-23,23>>^ O Deus de paz, em pessoa, vos santifique em tudo, a fim de que todo o vosso ser, o espírito, a alma e o corpo, se conservem sem culpa para a vinda de Nosso Senhor Jesus Cristo.

[[v59-5-24]]

^<<v59-5-24,24>>^ Fiel é aquele que vos chamou, o qual fará isso.

[[v59-5-25]]

^<<v59-5-25,25>>^ Irmãos, orai por nós.

[[v59-5-26]]

^<<v59-5-26,26>>^ Saudai todos os irmãos com ósculo santo.

[[v59-5-27]]

^<<v59-5-27,27>>^ Eu vos conjuro pelo Senhor que esta carta seja lida a todos os irmãos.

[[v59-5-28]]

^<<v59-5-28,28>>^ A graça de Nosso Senhor Jesus Cristo seja convosco.

'''

xref:059-i-tessalonicenses/059-i-tessalonicenses-004.adoc#v59-4-0[&#60; Capítulo Anterior] | <<v59-5-0,Topo>> | xref:060-ii-tessalonicenses/060-ii-tessalonicenses-001.adoc#v60-1-0[Próximo Capítulo &#62;]