include::./index.adoc[]

[[v9-31-0]]
=== I Samuel, 31
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 31 de 1 Samuel narra a batalha final entre Israel e os filisteus, na qual Saul e seus filhos são mortos. Os versículos selecionados abordam temas como morte, luto e derrota:
* Salmo 116:15 "Preciosa é à vista do SENHOR a morte dos seus santos." Esse versículo fala sobre como Deus considera preciosa a morte dos seus servos fiéis, indicando que a morte pode ser vista como um momento de transição para uma vida melhor.
* Salmo 126:5 "Os que semeiam em lágrimas, com cânticos de júbilo ceifarão." Este salmo fala sobre como aqueles que passam por tempos de tristeza e dificuldade, eventualmente colherão alegria e felicidade.
* Eclesiastes 7:2 "Melhor é ir à casa onde há luto do que ir à casa onde há banquete; porque naquela se vê o fim de todos os homens, e os vivos o aplicam ao seu coração." Este versículo ensina que é mais sábio estar presente em um funeral do que em uma festa, pois isso nos lembra da brevidade da vida e da importância de valorizá-la.
* Jeremias 22:10 "Não choreis o morto, nem o lastimeis; chorai antes aquele que sai, porque nunca mais voltará, nem verá a terra em que nasceu." Neste versículo, Jeremias aconselha que não devemos chorar aqueles que morreram, mas sim aqueles que estão partindo, pois eles nunca mais voltarão.
* 2 Coríntios 4:8-9 "Em tudo somos atribulados, mas não angustiados; perplexos, mas não desanimados. Perseguidos, mas não desamparados; abatidos, mas não destruídos." Paulo aqui fala sobre as dificuldades que enfrentamos na vida, mas nos encoraja a perseverar, confiando em Deus. Este versículo pode ser aplicado à derrota de Israel na batalha, mas também a qualquer situação em que nos encontramos em dificuldades.
****

[[v9-31-1]]

^<<v9-31-1,1>>^ Entretanto os Filisteus combatiam contra os Israelitas. Os homens de Israel fugiram diante dos Filisteus, e caíram mortos (muitos deles) no monte de Gelboé.

[[v9-31-2]]

^<<v9-31-2,2>>^ Os Filisteus investiram contra Saul e contra os seus filhos, matando Jónatas, Abinadab e Melquisua, filhos de Saul.

[[v9-31-3]]

^<<v9-31-3,3>>^ O maior peso do combate caiu sobre Saul, e os frecheiros alcançaram-no e feriram-no gravemente.

[[v9-31-4]]

^<<v9-31-4,4>>^ Saul disse ao seu escudeiro: Desembaínha a tua espada e atravessa-me com ela, para que não venham estes Incircuncidados, e me tirem a vida escarnecendo de mim. Todavia o seu escudeiro não o quis fazer, porque se apoderou dele um excessivo terror. Por isso Saul tomou a espada e deixou-se cair sobre ela. (ver nota)

[[v9-31-5]]

^<<v9-31-5,5>>^ O escudeiro, vendo que Saul estava morto, lançou-se também ele mesmo sobre a sua espada e morreu com ele.

[[v9-31-6]]

^<<v9-31-6,6>>^ Morreu, pois, Saul, com os seus três filhos, o seu escudeiro e todos os seus homens naquele dia.

[[v9-31-7]]

^<<v9-31-7,7>>^ Ora os Israelitas, que estavam da banda de além do vale, e além do Jordão, vendo que os Israelitas tinham fugido, e que tinha sido morto Saul com os seus filhos, abandonaram as suas cidades e fugiram. Os Filisteus vieram e estabeleceram-se nelas.

[[v9-31-8]]

^<<v9-31-8,8>>^ Ao outro dia foram os Filisteus para despojar os mortos, e encontraram Saul e os seus três filhos estendidos sobre o monte de Gelboé.

[[v9-31-9]]

^<<v9-31-9,9>>^ Cortaram a cabeça a Saul, despojaram-no das armas, e enviaram esta boa notícia a toda a terra dos Filisteus, para que se publicasse no templo dos seus ídolos e entre o povo.

[[v9-31-10]]

^<<v9-31-10,10>>^ Puseram as armas de Saul no templo de Astarot, e suspenderam o seu corpo no muro de Betsan.

[[v9-31-11]]

^<<v9-31-11,11>>^ Tendo os habitantes de Jabes de Galaad ouvido tudo o que os Filisteus tinham feito a Saul,

[[v9-31-12]]

^<<v9-31-12,12>>^ saíram todos os homens mais valentes, marcharam toda a noite, e tiraram o cadáver de Saul e os cadáveres de seus filhos do muro de Betsan. Voltaram para Jabes de Galaad, e ali os queimaram

[[v9-31-13]]

^<<v9-31-13,13>>^ Tomaram os seus ossos, sepultaram-nos no bosque de Jabes, e jejuaram sete dias.

'''

xref:009-i-samuel/009-i-samuel-030.adoc#v9-30-0[&#60; Capítulo Anterior] | <<v9-31-0,Topo>> | xref:010-ii-samuel/010-ii-samuel-001.adoc#v10-1-0[Próximo Capítulo &#62;]