include::./index.adoc[]

[[v9-28-0]]
=== I Samuel, 28
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 28 de 1 Samuel relata a história de Saul procurando orientação divina através de uma necromante, mesmo que ele mesmo havia proibido a prática de bruxaria em Israel. Durante a consulta, o espírito de Samuel é invocado e adverte Saul sobre sua morte iminente e a derrota de Israel na batalha. Abaixo estão cinco versículos relacionados aos temas abordados neste capítulo:
* Deuteronômio 18:10-12: "Não se ache no meio de ti quem faça passar pelo fogo seu filho ou sua filha, nem adivinhador, nem prognosticador, nem agoureiro, nem feiticeiro; nem encantador, nem necromante, nem mágico, nem quem consulte os mortos; pois todo aquele que faz estas coisas é abominável ao Senhor"
Este versículo proíbe claramente a prática de necromancia e consulta aos mortos, que Saul proibiu em Israel, mas acabou recorrendo em seu desespero.
* Levítico 19:31: "Não vos volteis para os necromantes, nem para os adivinhos; não os procureis para serdes contaminados por eles. Eu sou o Senhor vosso Deus."
Este versículo também adverte contra a prática da necromancia e outras formas de adivinhação, que são consideradas impuras e abomináveis perante Deus.
* Isaías 8:19: "Quando vos disserem: Consultai os necromantes e os adivinhos, que chilreiam e murmuram entre dentes, respondei: Não consultará um povo a seu Deus? Acaso a favor dos vivos se consultarão os mortos?"
Neste versículo, o profeta Isaías adverte o povo de Israel a não procurar aconselhamento com necromantes e adivinhos, mas sim confiar em Deus para orientação e proteção.
* 2 Crônicas 10:13-14: "E o rei respondeu-lhes duramente, desprezando o conselho dos anciãos, e falou-lhes conforme o conselho dos moços, dizendo: Meu pai agravou o vosso jugo, mas eu o aliviarei; meu pai vos castigou com açoites pesados, mas eu vos castigarei com açoites mais leves"
Este versículo ilustra o perigo de rejeitar o conselho dos anciãos experientes em favor do conselho dos jovens e inexperientes, como Saul fez ao rejeitar os conselhos de Samuel e procurar aconselhamento de uma necromante.
* Provérbios 28:13: "O que encobre as suas transgressões jamais prosperará, mas o que as confessa e deixa alcançará misericórdia."
Este versículo destaca a importância da confissão e do arrependimento para obter a misericórdia de Deus, algo que Saul parecia não estar disposto a fazer, já que tentou encobrir seus erros e fraquezas em vez de confessá-los e buscar o perdão divino.
****

[[v9-28-1]]

^<<v9-28-1,1>>^ Sucedeu naquele tempo que os Filisteus juntaram as suas tropas, a fim de se prepararem para a guerra contra Israel Aquis disse então a Davide: Tem por certo que hás-de vir comigo à campanha, tu e a tua gente.

[[v9-28-2]]

^<<v9-28-2,2>>^ Davide disse a Aquis: Tu verás agora o que há-de fazer o teu servo. Aquis disse a Davide: Eu te constituirei para sempre guarda da minha pessoa. (ver nota)

[[v9-28-3]]

^<<v9-28-3,3>>^ Samuel tinha falecido. Todo o Israel o havia chorado. A sua sepultura foi em Rama, sua pátria. Saul tinha lançado fora do país os magos e adivinhos.

[[v9-28-4]]

^<<v9-28-4,4>>^ Os Filisteus Juntaram-se e foram acampar em Sunam. Saul juntou também todas as tropas de Israel, e foi a Gelboé.

[[v9-28-5]]

^<<v9-28-5,5>>^ Vendo Saul o exército dos Filisteus, teve medo, e agitou-se muito o seu coração.

[[v9-28-6]]

^<<v9-28-6,6>>^ Consultou o Senhor, o qual não lhe respondeu nem por sonhos, nem por sacerdotes, nem por profetas.

[[v9-28-7]]

^<<v9-28-7,7>>^ Saul disse aos seus servos: Buscai-me uma mulher que tenha o espírito de Piton, e eu irei ter com ela, a fim de a consultar. Os seus servos disseram-lhe: Em Endor há uma mulher que evoca (os mortos).

[[v9-28-8]]

^<<v9-28-8,8>>^ Saul disfarçou-se, tomou outras vestes e partiu com dois homens. Chegaram de noite a casa da mulher, e Saul disse-lhe: Adivinha-me o futuro, evocando um morto, e faz-me aparecer quem eu te disser

[[v9-28-9]]

^<<v9-28-9,9>>^ A mulher respondeu-lhe: Tu bem sabes tudo o que fez Saul, como exterminou do país os magos e os adivinhos; por que armas, pois, ciladas á minha vida, para me matarem?

[[v9-28-10]]

^<<v9-28-10,10>>^ Saul jurou-lhe pelo Senhor, dizendo; Viva o Senhor, que disto não te virá mal algum.

[[v9-28-11]]

^<<v9-28-11,11>>^ A mulher disse-lhe: Quem queres tu que te apareça? Saul disse: Faze-me aparecer Samuel.

[[v9-28-12]]

^<<v9-28-12,12>>^ A mulher, tendo visto aparecer Samuel, deu um grande grito, e disse a Saul: Por que me enganaste? Tu és Saul.

[[v9-28-13]]

^<<v9-28-13,13>>^ O rei disse-lhe: Não temas; que viste tu? A mulher disse a Saul: Vejo um deus que sobe da terra.

[[v9-28-14]]

^<<v9-28-14,14>>^ Saul disse-lhe: Como é a sua figura? Ela respondeu: É um ancião, envolvido numa capa. Saul compreendeu que era Samuel, fez-lhe uma profunda reverência e prostrou-se por terra.

[[v9-28-15]]

^<<v9-28-15,15>>^ Samuel disse a Saul: Por que me Inquietaste, fazendo-me vir cá? Saul respondeu-lhe: Eu acho-me no último aperto, porque os Filisteus fazem-me guerra, e Deus retirou-se de mim, não me quis ouvir nem por profetas, nem por sonhos; por essa razão te chamei, para que me indiques o que devo fazer.

[[v9-28-16]]

^<<v9-28-16,16>>^ Samuel disse: Para que me interrogas, quando o Senhor se afastou de ti e passou para o teu rival?

[[v9-28-17]]

^<<v9-28-17,17>>^ O Senhor te tratará como eu te disse da sua parte, arrancará o teu reino da tua mão e o dará a Davide teu companheiro.

[[v9-28-18]]

^<<v9-28-18,18>>^ Tu não obedeceste à lei do Senhor, nem executaste o decreto da sua ira contra os Amalecitas; por isso te fez hoje o Senhor aquilo que padeces.

[[v9-28-19]]

^<<v9-28-19,19>>^ O Senhor entregará contigo também Israel nas mãos dos Filisteus, e amanhã tu e os teus filhos estareis comigo; o Senhor entregará também nas mãos dos Filisteus o acampamento de Israel. (ver nota)

[[v9-28-20]]

^<<v9-28-20,20>>^ Imediatamente Saul caiu estendido por terra, porque se aterrou com as palavras de Samuel, e estava sem forças, visto que não tinha comido nada todo aquele dia.

[[v9-28-21]]

^<<v9-28-21,21>>^ Estando Saul assim turbado, foi aquela mulher ter com ele e disse-lhe: A tua escrava obedeceu à tua voz, expondo a sua vida, acedendo às palavras que disseste.

[[v9-28-22]]

^<<v9-28-22,22>>^ Ouve, pois, agora também a voz da tua escrava: pôr-te-ei diante um bocado de pão, para que, comendo-o, recobres forças e possas fazer a tua viagem.

[[v9-28-23]]

^<<v9-28-23,23>>^ Ele recusou e disse: Não comerei. Porém, os seus servos e a mulher constrangeram-no, e, tendo enfim cedido a seus rogos, levantou-se do chão e sentou-se num leito.

[[v9-28-24]]

^<<v9-28-24,24>>^ A mulher tinha em casa um gordo novilho, que se apressou a matar; (em seguida) tomando farinha, amassou-a e cozeu pães ázimos,

[[v9-28-25]]

^<<v9-28-25,25>>^ e pôs tudo diante de Saul e dos servos. Eles, tendo comido, levantaram-se e caminharam toda aquela noite.

'''

xref:009-i-samuel/009-i-samuel-027.adoc#v9-27-0[&#60; Capítulo Anterior] | <<v9-28-0,Topo>> | xref:009-i-samuel/009-i-samuel-029.adoc#v9-29-0[Próximo Capítulo &#62;]