include::./index.adoc[]

[[v9-6-0]]
=== I Samuel, 6
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* 1 Samuel 6 descreve a devolução da Arca da Aliança pelos filisteus, após terem sofrido diversas calamidades em suas cidades. A passagem fala sobre a forma como os filisteus planejaram devolver a Arca a Israel e como ela foi recebida pelo povo. Os versículos selecionados abaixo abordam temas como o arrependimento dos filisteus, a presença divina e a santidade da Arca.
* 1 Samuel 6:9: "E observai: se subir pelo caminho do seu território para Bete-Semes, foi ele que nos fez este grande mal; mas, se não, saberemos que a sua mão não nos tocou; foi antes um acaso que nos aconteceu." Os filisteus pedem orientação a seus sacerdotes sobre como devolver a Arca e como saber se a praga que tinham sofrido era um castigo divino ou uma coincidência. Este verso mostra como acreditavam na intervenção divina em suas vidas.
* 1 Samuel 6:13: "Ora, os de Bete-Semes estavam segando o trigo no vale; levantaram os olhos e viram a arca e alegraram-se ao vê-la." Este verso retrata a alegria dos habitantes de Bete-Semes ao verem a Arca da Aliança retornando para Israel. A Arca representava a presença de Deus, e a sua devolução foi um sinal de que Deus não tinha abandonado o povo de Israel.
* 1 Samuel 6:19: "Mas o Senhor feriu alguns homens de Bete-Semes, porque tinham olhado para dentro da arca do Senhor; feriu cinquenta mil homens do povo, e o povo pranteou, porque o Senhor fizera grande mortandade entre o povo." Este verso destaca a santidade da Arca da Aliança e as consequências da profanação de um objeto sagrado. Os homens de Bete-Semes foram punidos por olharem dentro da Arca, algo que era proibido por lei.
* 1 Samuel 6:20: "Então disseram os homens de Bete-Semes: Quem poderá subsistir perante o Senhor, este Deus santo? A quem subirá ele, para se afastar de nós?" Este verso reflete a percepção dos habitantes de Bete-Semes sobre a santidade de Deus e a necessidade de se manterem afastados de qualquer coisa que pudesse profaná-la. A devolução da Arca foi uma lição sobre o respeito e a reverência que deviam ter pela presença divina.
* 1 Samuel 6:21: "Enviaram, pois, mensageiros aos habitantes de Quiriate-Jearim, dizendo: Os filisteus devolveram a arca do Senhor; vinde, e levai-a para vós." Este verso destaca a importância da Arca da Aliança como símbolo da presença de Deus em Israel. Mesmo após todos os problemas que tinham ocorrido, os habitantes de Quiriate-Jearim desejaram receber a Arca em sua cidade, a fim de honrar a Deus e manter viva a tradição religiosa de Israel.
****

[[v9-6-1]]

^<<v9-6-1,1>>^ Esteve a arca do Senhor na terra dos Filisteus sete meses.

[[v9-6-2]]

^<<v9-6-2,2>>^ Os Filisteus chamaram os sacerdotes e os adivinhos, e disseram: Que faremos da arca do Senhor? Dizei-nos como havemos de a remeter ao seu lugar. Eles responderam:

[[v9-6-3]]

^<<v9-6-3,3>>^ Se vós remeteis a arca do Deus de Israel, não a remetais vazia, mas dai-lhe o que deveis pelo pecado; então sereis curados e sabereis por que a sua mão (de Deus) se não afastou de vós.

[[v9-6-4]]

^<<v9-6-4,4>>^ Eles disseram: Que devemos nós dar-lhe pelo delito? Eles responderam:

[[v9-6-5]]

^<<v9-6-5,5>>^ Fareis cinco tumores de ouro e cinco ratos de ouro, segundo o número de príncipes dos Filisteus, porque vós e os vossos príncipes fostes feridos de uma mesma praga. Fareis pois figuras dos vossos tumores e dos ratos que devastaram a terra, e dareis glória ao Deus de Israel, para ver se tira a sua mão de cima de vós, dos vossos deuses e da vossa terra.

[[v9-6-6]]

^<<v9-6-6,6>>^ Por que endureceis os vossos corações, como o Egipto e Faraó endureceram o seu coração? Porventura não tiveram de deixar sair os filhos de Israel, depois de ele os haver castigado?

[[v9-6-7]]

^<<v9-6-7,7>>^ Agora pois fazei um carro novo, metei ao carro duas vacas que tenham tido há pouco as suas crias, às quais ainda se não tenha posto jugo, e encerrai os seus bezerros no curral.

[[v9-6-8]]

^<<v9-6-8,8>>^ Tomareis a arca do Senhor, pô-la-eis no carro, e poreis ao seu lado, numa pequena caixa, as figuras de ouro que lhe pagastes pelo pecado; depois deixai-a ir.

[[v9-6-9]]

^<<v9-6-9,9>>^ Segui-a com os olhos: se ela for pelo caminho dos seus limites para a banda, de Betsames, (sabei que) o Deus de Israel foi quem nos fez este grande mal; se (ela porém) não (for para lá), conheceremos que não foi a sua mão que nos feriu, mas que isso sucedeu por acaso.

[[v9-6-10]]

^<<v9-6-10,10>>^ Eles assim o fizeram: tomando duas vacas, que davam leite aos seus bezerros, puseram-nas ao carro e encerraram no curral os seus bezerros.

[[v9-6-11]]

^<<v9-6-11,11>>^ E puseram a arca do Senhor sobre o carro e a pequena caixa que continha os ratos de ouro e as figuras dos seus tumores.

[[v9-6-12]]

^<<v9-6-12,12>>^ As vacas foram diretamente pela estrada que conduz a Betsames; seguiram sempre o mesmo caminho sem parar e mugindo, e não declinaram nem para a direita nem para a esquerda. Os príncipes dos Filisteus também iam seguindo atrás, até os confins de Betsames.

[[v9-6-13]]

^<<v9-6-13,13>>^ Ora os Betsamitas segavam trigo no vale. Levantando os olhos, viram a arca, e alegraram-se quando a viram.

[[v9-6-14]]

^<<v9-6-14,14>>^ O carro foi para o campo de Josué Betsamita e parou ali. Havia lá uma grande pedra, e (os Betsamitas) fizeram em pedaços a madeira do carro, e puseram as vacas em cima em holocausto ao Senhor.

[[v9-6-15]]

^<<v9-6-15,15>>^ Os Levita s desceram a arca do Senhor e a pequena caixa que estava ao seu lado, onde vinham as figuras de ouro, e colocaram-na sobre aquela grande pedra. Os Betsamitas ofereceram holocaustos e imolaram vítimas naquele dia ao Senhor.

[[v9-6-16]]

^<<v9-6-16,16>>^ Os cinco príncipes dos Filisteus, depois de verem isto, voltaram no mesmo dia para Acaron.

[[v9-6-17]]

^<<v9-6-17,17>>^ Ora estes são os tumores de ouro, que os Filisteus deram ao Senhor pelo pecado: Azot deu um, Gaza um, Ascalon um, Get um, Acaron um

[[v9-6-18]]

^<<v9-6-18,18>>^ também os ratos de ouro eram segundo o número das cidades das cinco províncias dos Filisteus, desde as cidades muradas até às aldeias sem muros. Testemunho a grande pedra, sobre a qual puseram a arca do Senhor, a qual, até ao dia de hoje, está no campo de Josué Betsamita.

[[v9-6-19]]

^<<v9-6-19,19>>^ Ora (o Senhor) feriu os habitantes de Betsames, porque tinham olhado (com curiosidade e pouco respeito) para a arca do Senhor, e matou setenta homens do povo. O povo chorou, por ter o Senhor ferido a plebe com uma tão grande praga. (ver nota)

[[v9-6-20]]

^<<v9-6-20,20>>^ Os homens Betsamitas disseram: Quem poderá subsistir na presença do Senhor, deste Deus santo? E para quem irá (afastando-se) de nós?

[[v9-6-21]]

^<<v9-6-21,21>>^ Mandaram mensageiros aos habitantes de Cariatiarim, dizendo: Os Filisteus restituiram a arca do Senhor; vinde e levai-a para vós.

'''

xref:009-i-samuel/009-i-samuel-005.adoc#v9-5-0[&#60; Capítulo Anterior] | <<v9-6-0,Topo>> | xref:009-i-samuel/009-i-samuel-007.adoc#v9-7-0[Próximo Capítulo &#62;]