include::./index.adoc[]

[[v9-27-0]]
=== I Samuel, 27
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* 1 Samuel 27 narra a continuação da história de Davi, que, fugindo da perseguição do rei Saul, decide se refugiar entre os filisteus. Ele recebe a cidade de Ziclague do rei filisteu Aquis, e a utiliza como base para saques a outras cidades. Davi engana Aquis, fazendo-o acreditar que está lutando contra Israel, quando na verdade está atacando outros povos inimigos. Os temas presentes nesse capítulo incluem a fuga de Davi, a sua vida entre os filisteus, e a sua astúcia para enganar Aquis e manter-se seguro.
* 1 Crônicas 12:1-2: "Ora, estes são os que vieram ter com Davi em Ziclague, quando ele ainda se mantinha oculto por causa de Saul, filho de Quis; e eram dos mais valentes, ajudando-o na guerra, armados de escudos e lanças, e cujo rosto era como rosto de leão, e que eram tão ligeiros como os corços nos montes". Esses versículos mencionam a cidade de Ziclague, onde Davi se refugia em 1 Samuel 27, e falam dos homens valentes que se juntam a ele ali.
* 1 Samuel 29:6-7: "Então Aquis chamou Davi e disse-lhe: Tão certo como vive o Senhor, tu foste reto, e saíste comigo e entraste comigo no arraial, e nem achei em ti mal algum, desde o dia em que vieste ter comigo, até hoje; porém aos olhos dos príncipes não és bom. Volta, pois, e vai em paz, para que não faças nada que desagrade aos filhos de Amom". Nesses versículos, Aquis elogia Davi e o manda embora de sua corte, temendo que os outros líderes filisteus não confiem em Davi. Isso mostra como Davi conseguiu enganar Aquis e manter-se seguro entre os filisteus.
* Salmos 56:3-4: "Em qualquer tempo em que eu temer, confiarei em ti. Em Deus louvarei a sua palavra, em Deus pus a minha confiança; não temerei o que me possa fazer a carne". Davi escreveu esse Salmo durante sua fuga de Saul, e expressa a sua confiança em Deus, mesmo em meio à adversidade e ao medo. Esse sentimento pode ser aplicado a 1 Samuel 27, onde Davi busca refúgio entre os filisteus.
* Provérbios 21:30: "Não há sabedoria, nem inteligência, nem conselho contra o Senhor". Esse verso enfatiza a supremacia de Deus sobre todas as coisas, e pode ser aplicado a Davi em 1 Samuel 27. Embora ele esteja usando sua astúcia para enganar Aquis e se manter seguro entre os filisteus, no final das contas é a vontade de Deus que prevalece.
* Isaías 32:8: "Mas o nobre faz planos nobres, e em coisas nobres persistirá." Este versículo fala sobre a importância de ter boas intenções e agir de forma justa e nobre. Isso é algo que pode ser aplicado ao personagem de Davi em 1 Samuel 27, que apesar de estar agindo de forma questionável, ainda tinha a intenção de proteger a si mesmo e a seus homens.
****

[[v9-27-1]]

^<<v9-27-1,1>>^ Davide disse no seu coração: Por fim, algum dia cairei nas mãos de Saul; não será melhor que eu fuja e me salve no pais dos Filisteus, para que Saul perca de todo as esperanças e cesse de me buscar por todas as terras de Israel? Fugirei portanto das suas mãos.

[[v9-27-2]]

^<<v9-27-2,2>>^ Davide levantou-se, com os seus seiscentos homens, e foi para Aquis, filho de Maoque, rei de Get.

[[v9-27-3]]

^<<v9-27-3,3>>^ Davide habitou com Aquis em Get, ele e os seus, cada um com sua família, e Davide com as suas duas mulheres, Aquinoão de Jezrael, e Abigail, mulher que tinha sido de Nabal do Carmelo.

[[v9-27-4]]

^<<v9-27-4,4>>^ Saul foi avisado de que Davide se tinha refugiado em Get, e não cuidou mais em o buscar.

[[v9-27-5]]

^<<v9-27-5,5>>^ Davide disse a Aquis: Se eu encontrei graça diante dos teus olhos, seja-me dado lugar numa das cidades deste país, onde eu habite; pois por que há-de residir o teu servo contigo na cidade real?

[[v9-27-6]]

^<<v9-27-6,6>>^ Aquis deu-lhe naquele dia (a cidade de) Siceleg, e, deste modo, Siceleg tornou-se dos reis de Judá até ao dia de hoje.

[[v9-27-7]]

^<<v9-27-7,7>>^ O número de dias que Davide habitou nas terras dos Filisteus, foi de quatro meses.

[[v9-27-8]]

^<<v9-27-8,8>>^ Davide saía com a sua gente e fazia incursões contra os Gessurianos, Gerzianos e Amalecitas, porque naquela terra era antigamente habitada (por estes povos) sobre o caminho de Sur até à terra do Egipto.

[[v9-27-9]]

^<<v9-27-9,9>>^ Davide assolava toda aquela região sem deixar com vida nem homem nem mulher, tirando ovelhas, bois, jumentos, camelos e roupas. Depois voltava e ia para Aquis. (ver nota)

[[v9-27-10]]

^<<v9-27-10,10>>^ Aquis perguntava-lhe: Para que lado fizeste tu hoje incursão? Davide respondia; Para a parte meridional de Judá, ou para a parte meridional de Jerameel, ou para a parte meridional de Ceni.

[[v9-27-11]]

^<<v9-27-11,11>>^ Não deixava Davide com vida nem homem nem mulher, nem levava prisioneiro algum a Get, por temor de que dessem informações contra ele (e os seus) dizendo: Davide fez isto ou aquilo. Foi este o seu proceder durante todo o tempo que habitou no país dos Filisteus.

[[v9-27-12]]

^<<v9-27-12,12>>^ Aquis acreditava em Davide, dizendo: Ele tem feito muito mal a Israel, seu povo, por isso estará sempre ao meu serviço.

'''

xref:009-i-samuel/009-i-samuel-026.adoc#v9-26-0[&#60; Capítulo Anterior] | <<v9-27-0,Topo>> | xref:009-i-samuel/009-i-samuel-028.adoc#v9-28-0[Próximo Capítulo &#62;]