include::./index.adoc[]

[[v9-25-0]]
=== I Samuel, 25
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* 1 Samuel 25 narra a história de Abigail, esposa de Nabal, um homem rude e tolo que se recusa a ajudar Davi e seus homens em um momento de necessidade. Abigail, por sua vez, toma a iniciativa de fornecer alimento e suprimentos para Davi, evitando assim uma guerra entre seu marido e o futuro rei. Os versículos a seguir estão relacionados com temas abordados neste capítulo:
* Provérbios 15:1: "A resposta branda desvia o furor, mas a palavra dura suscita a ira." Abigail é um exemplo de como uma resposta gentil pode evitar conflitos e promover a paz.
* Provérbios 21:9: "É melhor morar num canto de telhado do que ter como companheira em casa ampla uma mulher briguenta." Nabal é um exemplo de um homem rude e briguento, que acaba se colocando em uma situação perigosa por causa de seu comportamento.
* Provérbios 25:21-22: "Se o teu inimigo tiver fome, dá-lhe pão para comer; e se tiver sede, dá-lhe água para beber; porque assim amontoarás brasas vivas sobre a sua cabeça, e o Senhor te recompensará." Abigail demonstra generosidade e compaixão ao fornecer alimento e suprimentos para Davi e seus homens, mesmo sabendo que seu marido era um homem rude e tolo.
* Eclesiastes 7:9: "Não te apresses em teu espírito a irar-te, porque a ira repousa no íntimo dos tolos." Davi mostra sabedoria ao recusar-se a retaliar contra Nabal e seus homens, apesar de ter sido insultado e desrespeitado.
* Romanos 12:19: "Não vos vingueis a vós mesmos, amados, mas dai lugar à ira de Deus, porque está escrito: Minha é a vingança; eu recompensarei, diz o Senhor." Davi confia em Deus para lidar com aqueles que o ofendem, em vez de buscar vingança por conta própria.
****

[[v9-25-1]]

^<<v9-25-1,1>>^ Entretanto morreu Samuel, e todo o Israel se juntou a chorá-lo. Sepultaram-no na sua casa em Rama. David e pôs-se em marcha, e desceu para o deserto de Faran.

[[v9-25-2]]

^<<v9-25-2,2>>^ Ora havia no deserto de Maon um homem, que tinha as suas possessões no Carmelo: este homem era muito rico, tinha três mil ovelhas e mil cabras, e encontrava-se no Carmelo para fazer a tosquia do seu gado.

[[v9-25-3]]

^<<v9-25-3,3>>^ O nome daquele homem era Nabal, e o nome da sua mulher Abigail. A mulher era muito prudente e formosa; seu marido, porém , era um homem duro e mau, descendente da linhagem de Caleb.

[[v9-25-4]]

^<<v9-25-4,4>>^ Davide, tendo sabido, no deserto que Nabal fazia a tosquia do seu rebanho,

[[v9-25-5]]

^<<v9-25-5,5>>^ enviou lá dez jovens e disse-lhes: Subi ao Carmelo, ide a casa de Nabal e saudai-o em meu nome pacificamente.

[[v9-25-6]]

^<<v9-25-6,6>>^ Dir-lhe-eis: A paz seja com contigo, com a tua casa e com tudo o que tens.

[[v9-25-7]]

^<<v9-25-7,7>>^ Ouvi dizer que os teus pastores, que viviam conosco no deserto, fazem a tosquia; nós nunca os molestámos, nem lhes faltou nunca coisa alguma no rebanho, durante todo o tempo que estiveram conosco no Carmelo.

[[v9-25-8]]

^<<v9-25-8,8>>^ Pergunta-o aos teus criados, e eles to dirão. Agora, pois, achem teus servos graça diante de teus olhos, visto que viemos em tão boa ocasião: dá a teus servos e a Davide, teu filho, qualquer coisa que tiveres à mão.

[[v9-25-9]]

^<<v9-25-9,9>>^ Quando os homens de Davide chegaram, disseram a Nabal todas estas coisas, da parte de Davide, e ficaram calados.

[[v9-25-10]]

^<<v9-25-10,10>>^ Respondendo, porém Nabal, aos criados de Davide, disse; Quem é Davide? E quem é o filho de Isai? Hoje são numerosos os servos que fogem aos seus senhores.

[[v9-25-11]]

^<<v9-25-11,11>>^ Pegarei eu no meu pão, na minha água e na carne dos animais que matei para os que tosquiam as minhas ovelhas, e dá-lo-ei a homens que não sei donde são?

[[v9-25-12]]

^<<v9-25-12,12>>^ Os criados de Davide retomaram o seu caminho e, tendo chegado, contaram-lhe todas as palavras que Nabal tinha dito.

[[v9-25-13]]

^<<v9-25-13,13>>^ Então Davide disse à sua gente: Cinja cada um a sua espada. E cingiram todos as suas espadas, cingindo também Davide a sua. Seguiram Davide cerca de quatrocentos homens, e ficaram duzentos com a equipagem

[[v9-25-14]]

^<<v9-25-14,14>>^ Um dos criados de Nabal disse a Abigail, sua mulher: Sabe que Davide enviou do deserto mensageiros, para saudarem o nosso amo, e ele os repeliu.

[[v9-25-15]]

^<<v9-25-15,15>>^ Estes homens têm-nos sido muito úteis, e nunca nos foram molestos; enquanto vivemos com eles no deserto, nada se perdeu.

[[v9-25-16]]

^<<v9-25-16,16>>^ Serviam-nos de muro, tanto de noite como de dia, durante todo o tempo que apascentámos entre eles os rebanhos.

[[v9-25-17]]

^<<v9-25-17,17>>^ Portanto considera o que deves fazer, porque uma grande desgraça está para cair sobre o teu marido e sobre a tua casa, e ele é um filho de Belial, (tão violento) que ninguém se atreve a falar-lhe.

[[v9-25-18]]

^<<v9-25-18,18>>^ Imediatamente Abigail tomou duzentos pães, dois odres de vinho, cinco carneiros cozidos, cinco medidas de farinha, cem cachos de uvas passas, duzentas pastas de figos secos, e pôs (tudo) em cima de jumentos,

[[v9-25-19]]

^<<v9-25-19,19>>^ dizendo aos seus criados: Ide adiante de mim, que eu irei atrás de vós. E não disse nada a seu marido Nabal.

[[v9-25-20]]

^<<v9-25-20,20>>^ Quando, montada num jumento, descia pelas faldas do monte, encontrou Davide e os seus homens, que desciam para ela.

[[v9-25-21]]

^<<v9-25-21,21>>^ Davide dizia: Em verdade, de nada me serviu ter guardado tudo o que este (homem) tinha no deserto, sem que se lhe perdesse nunca coisa alguma do que possuia: ele me tornou mal por bem.

[[v9-25-22]]

^<<v9-25-22,22>>^ Deus trate com todo o seu rigor os inimigos de Davide! E eu não deixarei vivo, desde agora até amanhã, nenhum dos seres masculinos que pertençam a Nabal.

[[v9-25-23]]

^<<v9-25-23,23>>^ Abigail, tendo visto Davide, apressou-se a descer do jumento e prostrou-se diante de Davide sobre o seu rosto, fez-lhe uma profunda reverência,

[[v9-25-24]]

^<<v9-25-24,24>>^ lançou-se a seus pés e disse: Sobre mim caia, meu senhor, esta iniquidade; peço-te que permitas à tua escrava falar aos teus ouvidos, e ouve as palavras da tua serva.

[[v9-25-25]]

^<<v9-25-25,25>>^ Não faças caso, te peço, meu senhor e meu rei, da injustiça de Nabal, porque, como o denota o seu próprio nome, é um insensato, e a loucura está com ele. Eu, tua escrava, não vi os criados que tu meu senhor, enviaste.

[[v9-25-26]]

^<<v9-25-26,26>>^ Agora, meu senhor, viva o Senhor e viva a tua alma, pois que o Senhor te impediu de derramar sangue, deteve a tua mão, agora sejam (tão fracos) como Nabal os teus inimigos, e os que procuram fazer mal ao meu senhor.

[[v9-25-27]]

^<<v9-25-27,27>>^ Portanto aceita esta bênção, que a tua escrava te trouxe, meu senhor, e reparte dela com os que te seguem, meu senhor.

[[v9-25-28]]

^<<v9-25-28,28>>^ Perdoa à tua escrava a iniquidade, porque certissimamente o Senhor te fará, meu senhor, uma casa estável, porque tu, meu senhor, combates pelo Senhor; não virá mal sobre ti, durante todos os dias da tua vida.

[[v9-25-29]]

^<<v9-25-29,29>>^ Se algum dia se levantar alguém para te perseguir e buscar a tua vida, a vida do meu senhor será guardada no ramalhete dos que vivem no Senhor teu Deus; e a alma de teu inimigos será agitada como um impetuoso girar de funda.

[[v9-25-30]]

^<<v9-25-30,30>>^ Quando o Senhor te tiver feito, meu senhor, todos os bens que ele predisse de ti, te tiver constituído chefe sobre Israel,

[[v9-25-31]]

^<<v9-25-31,31>>^ não terás no coração este pesar, nem este remorso, meu senhor, de ter derramado o sangue inocente, ou de te teres vingado por ti mesmo. Quando o Senhor tiver feito bem ao meu senhor, lembrar-te-ás, da tua escrava.

[[v9-25-32]]

^<<v9-25-32,32>>^ Davide disse a Abigail: Bem-dito seja o Senhor Deus de Israel, que te enviou hoje ao meu encontro!

[[v9-25-33]]

^<<v9-25-33,33>>^ Bem-dito o teu bom senso! Bem-dita sejas tu, que me impediste hoje de derramar sangue, vingar-me pela minha mão.

[[v9-25-34]]

^<<v9-25-34,34>>^ Doutro modo — juro-o pelo Senhor Deus de Israel, que me impediu que te fizesse mal! — se tu não viesses logo ao meu encontro, não teria ficado com vida desde hoje até amanhã, em casa de Nabal, nenhum ser masculino que lhe pertencesse.

[[v9-25-35]]

^<<v9-25-35,35>>^ Davide aceitou, da mão de Abigail, tudo o que lhe tinha trazido, e disse-Ihe: Vai em paz para tua casa: ouvi a tua voz e acolhi a tua petição.

[[v9-25-36]]

^<<v9-25-36,36>>^ Abigail voltou para Nabal, que dava em sua casa um banquete, como banquete de rei; o seu coração estava alegre, porque estava muito embriagado, e ela não lhe disse uma palavra nem pequena nem grande até pela manhã.

[[v9-25-37]]

^<<v9-25-37,37>>^ Ao outro dia muito cedo, quando Nabal tinha já digerido o vinho, sua mulher contou-lhe tudo o que se tinha passado, e o seu coração ficou como morto interiormente, e ele tornou-se (imóvel) como uma pedra.

[[v9-25-38]]

^<<v9-25-38,38>>^ Passados dez dias, o Senhor feriu Nabal, e ele morreu.

[[v9-25-39]]

^<<v9-25-39,39>>^ Tendo Davide ouvido dizer que Nabal morrera, disse: Bem-dito seja o Senhor que me vingou da afronta que me fez Nabal, preservou o seu servo de fazer mal e fez cair a iniquidade de Nabal sobre a sua cabeça. Davide enviou mensageiros a Abigail, para a tomar por sua mulher.

[[v9-25-40]]

^<<v9-25-40,40>>^ Os mensageiros de Davide foram ter com Abigail, ao Carmelo, e falaram-lhe assim; Davide mandou-nos ter contigo para te tom ar por sua mulher.

[[v9-25-41]]

^<<v9-25-41,41>>^ Ela, levantando-se, inclinou-se até à terra, e disse: Eis a tua serva, que será como uma escrava para lavar os pés aos criados do meu senhor.

[[v9-25-42]]

^<<v9-25-42,42>>^ Abigail, levantando-se depressa, montou no jumento, levou consigo cinco donzelas suas. Seguiu os mensageiros de Davide, e tornou-se sua mulher.

[[v9-25-43]]

^<<v9-25-43,43>>^ Davide desposou-se também com Aquinoão, (que era) de Jezrael. Ambas foram suas mulheres.

[[v9-25-44]]

^<<v9-25-44,44>>^ Saul porém, tinha dado sua filha Micol, mulher de Davide, a Faltl, filho de Lais, que era de Galim

'''

xref:009-i-samuel/009-i-samuel-024.adoc#v9-24-0[&#60; Capítulo Anterior] | <<v9-25-0,Topo>> | xref:009-i-samuel/009-i-samuel-026.adoc#v9-26-0[Próximo Capítulo &#62;]