include::./index.adoc[]

[[v68-2-0]]
=== II São Pedro, 2
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 2 de 2 Pedro trata principalmente dos falsos profetas e mestres que surgiriam no meio do povo cristão, trazendo heresias e promovendo a libertinagem. Eles negariam a soberania de Deus e a redenção em Jesus Cristo, levando muitos a seguir suas práticas perniciosas. Abaixo seguem cinco versículos relacionados com esses temas, excluindo os versículos de 2 São Pedro 2:
* Mateus 7:15: "Acautelai-vos dos falsos profetas, que se vos apresentam disfarçados em ovelhas, mas por dentro são lobos roubadores." Jesus Cristo advertiu os seus discípulos sobre a presença de falsos profetas, que se apresentariam como líderes espirituais, mas que, na verdade, buscariam desviar as pessoas da verdade.
* 2 Coríntios 11:13-15: "Porque tais falsos apóstolos são obreiros fraudulentos, transformando-se em apóstolos de Cristo. E não é de admirar, porque o próprio Satanás se transforma em anjo de luz. Não é muito, pois, que os seus próprios ministros se transformem em ministros de justiça; e o fim deles será conforme as suas obras." O apóstolo Paulo também alertou sobre a presença de falsos apóstolos, que fingiam serem enviados por Cristo, mas que na verdade eram enganadores que buscavam enganar o povo de Deus.
* 1 João 4:1: "Amados, não creiais em todo espírito, mas provai se os espíritos vêm de Deus, porque muitos falsos profetas têm saído pelo mundo." O apóstolo João também instruiu os cristãos a examinarem cuidadosamente os ensinamentos que ouviam, a fim de verificar se vinham de Deus ou de falsos profetas.
* 1 Timóteo 4:1: "Ora, o Espírito diz expressamente que, nos últimos tempos, alguns apostatarão da fé, por obedecerem a espíritos enganadores e a ensinos de demônios." O apóstolo Paulo novamente alertou sobre a presença de ensinamentos falsos que seriam promovidos por pessoas que não seguiam a Deus, mas a espíritos enganadores e a ensinamentos demoníacos.
* Judas 1:4: "Porque certos homens, cuja condenação já estava sentenciada há muito tempo, infiltraram-se dissimuladamente no meio de vocês. Estes são ímpios, que transformam a graça de nosso Deus em libertinagem e negam Jesus Cristo, nosso único Soberano e Senhor." O livro de Judas também fala sobre a presença de falsos mestres que negavam a verdade sobre Jesus Cristo e promoviam práticas libertinas.
****

[[v68-2-1]]

^<<v68-2-1,1>>^ Ora, assim como no povo (de Israel) houve falsos profetas, do mesmo modo haverá entre vós falsos doutores, que introduzirão seitas perniciosas e que, renegando àquele Senhor que os resgatou, atrairão sobre si mesmos uma pronta ruína.

[[v68-2-2]]

^<<v68-2-2,2>>^ Muitos seguirão as suas dissoluções, por causa dos quais será blasfemado o caminho da verdade. (ver nota)

[[v68-2-3]]

^<<v68-2-3,3>>^ Por cobiça, com palavras fingidas, farão negócio de vós, mas a sua condenação já desde há muito (pronunciada na pessoa de outros culpados) não repousa e a sua perdição não dorme. (ver nota)

[[v68-2-4]]

^<<v68-2-4,4>>^ Em realidade, se Deus não perdoou aos anjos que pecaram, mas, precipitados no Tártaro, os entregou às cadeias das trevas para serem reservados até ao juízo (final);

[[v68-2-5]]

^<<v68-2-5,5>>^ se não perdoou ao mundo antigo, mas sòmente salvou oito pessoas, incluindo Noé, pregador da justiça, quando fez vir o dilúvio sobre o mundo dos ímpios; (ver nota)

[[v68-2-6]]

^<<v68-2-6,6>>^ se condenou a uma total ruína as cidades de Sodoma e de Gomorra, reduzindo-as a cinzas, para servir de exemplo àqueles que venham a viver impiamente;

[[v68-2-7]]

^<<v68-2-7,7>>^ se, enfim, livrou o justo Loth, que se afligia pelo viver luxurioso desses infames,

[[v68-2-8]]

^<<v68-2-8,8>>^ (esse justo que habitava entre eles sentia, diariamente, a sua alma atormentada, vendo e ouvindo as suas obras iníquas),

[[v68-2-9]]

^<<v68-2-9,9>>^ (é porque) o Senhor sabe livrar os justos da tentação e reservar os maus para o dia do juízo, a fim de serem castigados,

[[v68-2-10]]

^<<v68-2-10,10>>^ principalmente aqueles que vão atrás da carne, na imunda concupiscência, e desprezam a soberania (de Cristo). Audaciosos, arrogantes, não temem blasfemar contra as glórias (anjos inferiores),

[[v68-2-11]]

^<<v68-2-11,11>>^ enquanto que os anjos (superiores), maiores em fortaleza e robustez, não levantam, diante do Senhor, acusação injuriosa contra elas. (ver nota)

[[v68-2-12]]

^<<v68-2-12,12>>^ Mas estes, como animais irracionais, naturalmente feitos para presa e para perdição, blasfemando das coisas que ignoram, perecerão da mesma morte (desses animais),

[[v68-2-13]]

^<<v68-2-13,13>>^ recebendo a injustiça como paga da injustiça. Fazem consistir a sua felicidade nas delicias de cada dia; eles que são manchados e viciados, põem o seu prazer em vos enganar banqueteando-se convosco.

[[v68-2-14]]

^<<v68-2-14,14>>^ Têm os olhos cheios de adultério e de um contínuo pecado; atraem com afago as almas inconstantes, têm o coração exercitado na cobiça, filhos da maldição!

[[v68-2-15]]

^<<v68-2-15,15>>^ Deixando o caminho direito, extraviaram-se seguindo o caminho de Balaão, filho de Bosor, o qual amou a recompensa de iniquidade,

[[v68-2-16]]

^<<v68-2-16,16>>^ mas foi repreendido pela sua culpa: um animal de carga, mudo, falando com voz humana, refreou a insânia do profeta.

[[v68-2-17]]

^<<v68-2-17,17>>^ São fontes sem água, e névoas agitadas por um turbilhão, para os quais está reservada a obscuridade das trevas.

[[v68-2-18]]

^<<v68-2-18,18>>^ Com palavras arrogantes e ocas atraem pelos desejos desregrados da carne aqueles que pouco antes tinham fugido dos que vivem no erro.

[[v68-2-19]]

^<<v68-2-19,19>>^ Prometem-lhes a liberdade, quando eles mesmos são escravos da corrupção, pois que se é escravo daquele por quem se foi vencido.

[[v68-2-20]]

^<<v68-2-20,20>>^ Assim, se, depois de terem fugido das corrupções do mundo pelo conhecimento do Senhor e Salvador Jesus Cristo, por elas são novamente envolvidos e vencidos, o seu segundo estado tornou-se-lhes pior do que o primeiro.

[[v68-2-21]]

^<<v68-2-21,21>>^ Melhor lhes era não conhecer o caminho da justiça, do que, depois de o terem conhecido, tornar para trás (afastando-se) daquele mandamento santo, que lhes havia sido dado.

[[v68-2-22]]

^<<v68-2-22,22>>^ Desta forma, se realizou neles aquele provérbio verdadeiro: Voltou o cão ao seu vômito (Pv. 26, 11), e estoutro: A porca lavada tornou a revolver-se no lamaçal.

'''

xref:068-ii-sao-pedro/068-ii-sao-pedro-001.adoc#v68-1-0[&#60; Capítulo Anterior] | <<v68-2-0,Topo>> | xref:068-ii-sao-pedro/068-ii-sao-pedro-003.adoc#v68-3-0[Próximo Capítulo &#62;]