include::./index.adoc[]

[[v33-47-0]]
=== Ezequiel, 47
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Ezequiel 47 descreve a visão de um rio fluindo do templo de Deus, que se torna cada vez mais profundo e abundante. As águas deste rio curam e dão vida a tudo o que tocam. A seguir, são apresentados cinco versículos relacionados com os temas deste capítulo:
* Salmos 46:4: "Há um rio cujos canais alegram a cidade de Deus, o Santo Lugar onde habita o Altíssimo." Este versículo fala sobre um rio que flui através da cidade de Deus, semelhante ao rio que flui do templo em Ezequiel 47.
* Apocalipse 22:1-2: "Então o anjo me mostrou o rio da água da vida, brilhante como cristal, que sai do trono de Deus e do Cordeiro. No meio da rua da cidade, e em ambos os lados do rio, estava a árvore da vida, que produz doze colheitas por ano, dando seu fruto a cada mês. E as folhas da árvore são para a cura das nações." Este versículo descreve uma cena semelhante ao rio de Ezequiel 47, com a água da vida curando as nações e a árvore da vida dando fruto abundante.
* João 7:37-38: "No último e mais importante dia da festa, Jesus levantou-se e disse em voz alta: 'Se alguém tem sede, venha a mim e beba. Quem crer em mim, como diz a Escritura, do seu interior fluirão rios de água viva.'" Este versículo descreve Jesus como a fonte de água viva, semelhante ao rio que flui do templo em Ezequiel 47.
* Jeremias 17:7-8: "Mas bendito é o homem cuja confiança está no Senhor, cuja confiança nele está. Ele será como uma árvore plantada junto às águas e que estende as suas raízes para o ribeiro. Ela não temerá quando chegar o calor, porque as suas folhas estão sempre verdes. Ela não se angustiará no ano da seca nem deixará de dar fruto." Este versículo fala sobre a confiança no Senhor e a prosperidade daqueles que confiam Nele, semelhante à prosperidade da vida que surge ao longo do rio de Ezequiel 47.
* Isaías 55:1: "Venham, todos vocês que estão com sede, venham às águas; e vocês que não têm dinheiro, venham, comprem e comam! Venham, comprem vinho e leite sem dinheiro e sem custo." Este versículo fala sobre a provisão gratuita de água, vinho e leite para todos aqueles que têm sede, semelhante à provisão de água abundante do rio de Ezequiel 47.
****

[[v33-47-1]]

^<<v33-47-1,1>>^ (Depois) fez-me voltar para a porta da casa (do Senhor). E eis que brotavam águas debaixo do limiar da porta, do lado do oriente, porque a face da casa olhava para o oriente; as águas desciam por baixo do lado direito do templo, ao meio-dia do altar.

[[v33-47-2]]

^<<v33-47-2,2>>^ Fez-me sair pelo pórtico do setentrião e dar a volta por fora até ao pórtico exterior, que olhava para o oriente; vi que as águas jorravam do lado direito.

[[v33-47-3]]

^<<v33-47-3,3>>^ Saindo para a banda do oriente, o homem, que tinha um cordel na mão, mediu mil côvados e fez-me atravessar a água, que me dava pelos tornozelos.

[[v33-47-4]]

^<<v33-47-4,4>>^ Mediu outros mil côvados e (ali) fez-me atravessar a água que me dava pelos joelhos.

[[v33-47-5]]

^<<v33-47-5,5>>^ Mediu outros mil côvados e fez-me atravessar a água, que me dava pelos rins. Mediu outros mil côvados, e era já uma torrente que não pude atravessar, porque se tinham empolado as águas, tornando-se uma profunda torrente, que não se podia passar a vau.

[[v33-47-6]]

^<<v33-47-6,6>>^ Então disse-me: Viste, filho de homem? Depois levou-me e reconduziu-me a borda da torrente.

[[v33-47-7]]

^<<v33-47-7,7>>^ Tendo eu, pois. tornado, vi sobre a borda da torrente muitíssimas árvores, de um e outro lado.

[[v33-47-8]]

^<<v33-47-8,8>>^ Disse-me; Estas águas vão para o distrito oriental e descem para a planície do deserto; entrarão no mar (Morto) e aí se difundirão, de maneira que as águas (do mar) ficarão saudáveis.

[[v33-47-9]]

^<<v33-47-9,9>>^ Todo o animal vivo, que se move (nas águas), viverá por toda a parte onde chegar a torrente; haverá peixes em abundância, porque, onde chegarem estas águas, as outras se tornarão sãs e haverá vida em toda a parte onde chegar esta torrente.

[[v33-47-10]]

^<<v33-47-10,10>>^ Os pescadores estarão sobre as suas margens desde Engadi até Engalim se estenderão redes; serão as espécies de seus peixes como as do Grande Mar, e com muita fartura.

[[v33-47-11]]

^<<v33-47-11,11>>^ Nas suas lagunas, porém, e nos seus charcos, não serão salutíferas as águas, porque destinadas à extracção de sal.

[[v33-47-12]]

^<<v33-47-12,12>>^ Ao longo da torrente nascerá nas suas ribanceiras, dum e doutro lado, toda a espécie de árvores frutíferas; não lhes cairá a folha, nem faltará o fruto. Darão frutos novos todos os meses, porque as suas águas manam do santuário; os seus frutos servirão de sustento, e as suas folhas de remédio.

[[v33-47-13]]

^<<v33-47-13,13>>^ Isto diz o Senhor Deus; Eis os limites, dentro dos quais possuireis a terra que se há-de repartir pelas doze tribos de Israel, dando a José um quinhão dobrado.

[[v33-47-14]]

^<<v33-47-14,14>>^ Possuireis todos Igualmente, cada um tanto como seu irmão, esta terra prometida por mim com juramento a vossos pais; será esta terra a vossa herança,

[[v33-47-15]]

^<<v33-47-15,15>>^ Eis os limites da terra: Pelo lado setentrional, desde o Grande Mar, pelo caminho de Hetalon, vindo a Sedad:

[[v33-47-16]]

^<<v33-47-16,16>>^ Hamat, Berota, Sabarim. que está entre os confins de Damasco e os confins de Hamat, Haser Hattikon, que está nos confins de Hauran.

[[v33-47-17]]

^<<v33-47-17,17>>^ Os seus limites irão, pois, desde o mar até Haser-Enon, tendo ao norte o termo de Damasco e a fronteira de Hamat. Isto pelo lado setentrional.

[[v33-47-18]]

^<<v33-47-18,18>>^ O seu limite oriental tomar-se-á entre Hauran e Damasco, entre Galaad e a terra de Israel, limitando-a o Jordão até ao mar oriental. Medireis a partir da fronteira (norte) até ao mar oriental. Tal é o lado do oriente.

[[v33-47-19]]

^<<v33-47-19,19>>^ O limite meridional irá desde Tamar até às águas de Meribot, de Cades. e até à torrente (do Egipto) que vai para o Grande Mar (ou Mediterrâneo). Este é o limite do meio-dia.

[[v33-47-20]]

^<<v33-47-20,20>>^ O limite (ocidental), do lado do mar. será o Grande Mar, desde o seu extremo até Hamat. Este será o lado do ocidente.

[[v33-47-21]]

^<<v33-47-21,21>>^ Dividireis esta terra entre vós, segundo as tribos de Israel;

[[v33-47-22]]

^<<v33-47-22,22>>^ sorteá-la-eis para herança vossa e daqueles estrangeiros que vierem juntar-se convosco, que tiverem filhos no meio de vós; considerá-los-eis como naturais entre os filhos de Israel; tomarão parte convosco na herança, no meio das tribos de Israel.

[[v33-47-23]]

^<<v33-47-23,23>>^ Em qualquer tribo em que se achar um estrangeiro, vós lhe dareis ali o seu quinhão (de terra), diz o Senhor Deus.

'''

xref:033-ezequiel/033-ezequiel-046.adoc#v33-46-0[&#60; Capítulo Anterior] | <<v33-47-0,Topo>> | xref:033-ezequiel/033-ezequiel-048.adoc#v33-48-0[Próximo Capítulo &#62;]