include::./index.adoc[]

[[v33-14-0]]
=== Ezequiel, 14
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Ezequiel 14 fala sobre a repreensão divina aos líderes idólatras de Israel que buscavam orientação do profeta enquanto ainda mantinham seus ídolos em seus corações. Deus afirma que aqueles que se apegam a seus ídolos não podem esperar ouvir sua voz. Aqui estão cinco versículos relacionados com os temas abordados em Ezequiel 14:
* Jeremias 7:9-10: "Vós fazeis furtos, homicídios, adultérios e juramentos falsos, queimais incenso a Baal, e andais após outros deuses que nunca conhecestes. E depois vindes, e vos apresentais diante de mim, nesta casa, que se chama pelo meu nome, e dizeis: Fomos libertados, para fazermos todas estas abominações?" Este versículo mostra que muitas pessoas em Israel estavam praticando atos pecaminosos e, ainda assim, continuavam a buscar a Deus em seu templo.
* Isaías 1:15: "Quando estenderdes as vossas mãos, esconderei de vós os meus olhos; e ainda que multipliqueis as vossas orações, não as ouvirei, porque as vossas mãos estão cheias de sangue." Este versículo destaca que Deus não ouve as orações daqueles que cometem pecados graves.
* Jeremias 11:11: "Portanto assim diz o Senhor: Eis que trarei sobre eles um mal de que não poderão escapar; e clamarão a mim, mas eu não os ouvirei." Este versículo enfatiza que Deus não atenderá as orações dos que buscam sua ajuda, se eles continuarem a seguir seus próprios caminhos.
* Salmos 66:18: "Se eu no coração contemplara a vaidade, o Senhor não me teria ouvido." Este versículo destaca que a iniquidade no coração de alguém pode impedir que Deus ouça suas orações.
* Provérbios 1:28-29: "Então me chamarão, mas não responderei; procurar-me-ão, porém não me hão de achar. Porquanto aborreceram a ciência e não preferiram o temor do Senhor." Este versículo mostra que aqueles que desprezam a sabedoria e o temor do Senhor não terão suas orações ouvidas.
****

[[v33-14-1]]

^<<v33-14-1,1>>^ Vieram ter comigo alguns dos anciães de Israel e sentaram-se diante de mim.

[[v33-14-2]]

^<<v33-14-2,2>>^ Então foi-me dirigida a palavra do Senhor, nestes termos:

[[v33-14-3]]

^<<v33-14-3,3>>^ Filho de homem, essas pessoas instalaram os seus ídolos nos seus corações, e põem incessantemente o escândalo da sua iniquidade diante da sua face: acaso deverei permitir que me consultem?

[[v33-14-4]]

^<<v33-14-4,4>>^ Por isso fala-lhes e dize-lhes: Assim fala o Senhor Deus: Se qualquer da casa de Israel, que tiver posto ídolos no seu coração e colocado o escândalo da sua iniquidade diante de seus olhos, for ter com algum profeta (para me interrogar per meio dele), eu mesmo, o Senhor, lhe responderei segundo a multidão dos seus ídolos.

[[v33-14-5]]

^<<v33-14-5,5>>^ a fim de apanhar a casa de Israel pelo seu próprio coração, ela que se retirou de mim por causa de todos os seus ídolos.

[[v33-14-6]]

^<<v33-14-6,6>>^ Por isso dize à casa de Israel: Assim fala o Senhor Deus: Convertei-vos, retirai-vos dos vossos ídolos, afastai o vosso rosto de todas as vossas abominações.

[[v33-14-7]]

^<<v33-14-7,7>>^ Com efeito, se um homem da casa de Israel, ou um estrangeiro estabelecido em Israel, se afastar de mim e puser ídolos no seu coração, e colocar o escândalo da sua iniquidade diante dos seus olhos, e for, depois, ter com algum profeta para me interrogar por melo dele, eu, o Senhor, lhes responderei por mim mesmo (castigando-o);

[[v33-14-8]]

^<<v33-14-8,8>>^ voltarei o meu rosto contra tal homem, farei dele um exemplo e um provérbio, exterminá-lo-ei do meio do meu povo e vós sabereis que eu sou o Senhor. (ver nota)

[[v33-14-9]]

^<<v33-14-9,9>>^ Se o profeta errar e proferir um (falso) oráculo, serei eu, o Senhor, que permitirei que se engane esse profeta; estenderei a minha mão sobre ele e exterminá-lo-ei do meio do meu povo de Israel.

[[v33-14-10]]

^<<v33-14-10,10>>^ (Desta forma) levarão sobre si (o castigo da) sua iniquidade a falta do profeta será como a do consulente

[[v33-14-11]]

^<<v33-14-11,11>>^ a fim de que a casa de Israel se não torne mais a extraviar, para longe de mim, e a fim de que ela se não corrompa por todas as suas prevaricações. Então serão o meu povo, e eu o seu Deus, diz o Senhor Iavé.

[[v33-14-12]]

^<<v33-14-12,12>>^ Foi-me dirigida a palavra do Senhor, nestes termos:

[[v33-14-13]]

^<<v33-14-13,13>>^ Filho de homem, se algum país pecar contra mim, cometendo grandes prevaricações, e eu estender a minha mão sobre ele, quebrando a vara do seu pão, enviando contra ele a fome, para exterminar animais e pessoas, (ver nota)

[[v33-14-14]]

^<<v33-14-14,14>>^ ainda que no meio dele se achem estes três homens, Noé, Daniel e Job, eles salvar-se-ão (apenas a si próprios) pela sua justiça, diz o Senhor Iavé. (ver nota)

[[v33-14-15]]

^<<v33-14-15,15>>^ Se eu enviar a essa terra animais ferozes, para a destruírem, e ela se tornar um deserto, em que ninguém possa passar por causa das feras,

[[v33-14-16]]

^<<v33-14-16,16>>^ ainda que estes três homens estejam nela, (juro) pela minha vida, diz o Senhor Deus, que eles não livrarão nem os seus filhos, nem as suas filhas; só eles serão livres, e a terra, será destruída.

[[v33-14-17]]

^<<v33-14-17,17>>^ Ou se eu fizer vir a espada sobre esta terra, dizendo: Passe a espada pelo meio desta terra e lhe matar os homens e os animais,

[[v33-14-18]]

^<<v33-14-18,18>>^ se estes três homens se acharem no meio dela, (juro) pela minha vida, diz o Senhor Deus, que eles não livrarão nem os seus filhos, nem as suas filhas: só eles serão livres.

[[v33-14-19]]

^<<v33-14-19,19>>^ Ou se eu enviar a peste contra essa terra, e saciar a minha indignação sobre ela no sangue, exterminando os homens e os animais,

[[v33-14-20]]

^<<v33-14-20,20>>^ se Noé, Daniel e Job se acharem no meio dela, (juro) pela minha vida, diz o Senhor Deus, que não livrarão nem os seus filhos, nem as suas filhas; só eles se salvarão pela sua própria justiça.

[[v33-14-21]]

^<<v33-14-21,21>>^ Assim fala o Senhor Deus; Se eu enviar contra Jerusalém os meus quatro terríveis flagelos, a espada e a fome, os animais ferozes e a peste para lhe matar os homens e o gado.

[[v33-14-22]]

^<<v33-14-22,22>>^ ficarão nela todavia alguns que se salvarão, que escaparão, filhos e filhas. Eis que eles virão ter convosco (aqui a Babilônia) e vós vereis o seu (mau) proceder e as suas obras, e consolar-vos-eis do mal que fiz vir sobre Jerusalém, de todas as calamidades que sobre ela descarreguei.

[[v33-14-23]]

^<<v33-14-23,23>>^ Eles vos consolarão, quando virdes o seu (mau) proceder e as suas obras; reconhecereis que não foi sem um justo motivo que eu fiz nela tudo o que fiz oráculo do Senhor Iavé.

'''

xref:033-ezequiel/033-ezequiel-013.adoc#v33-13-0[&#60; Capítulo Anterior] | <<v33-14-0,Topo>> | xref:033-ezequiel/033-ezequiel-015.adoc#v33-15-0[Próximo Capítulo &#62;]