include::./index.adoc[]

[[v33-17-0]]
=== Ezequiel, 17
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Ezequiel 17 é um capítulo em que o profeta usa uma metáfora para retratar a infidelidade de Israel em relação a Deus. Ele compara a nação a um grande cedro que, ao invés de confiar em Deus, busca apoio em outras nações e deuses, o que leva à sua queda e destruição. Para encontrar versículos relacionados com os temas abordados em Ezequiel 17, foram considerados os temas de infidelidade, confiança em outras nações e queda. A seguir estão cinco versículos escolhidos em ordem de proximidade com esses temas:
* Jeremias 2:13: "Pois o meu povo cometeu dois males: eles me abandonaram, a mim, a fonte de água viva; e cavaram para si cisternas, cisternas rachadas que não retêm água." Este versículo fala sobre a infidelidade de Israel ao abandonar a Deus, que é a fonte de vida e alegria, para buscar satisfação em outras coisas.
* Isaías 30:1-2: "Ai dos filhos rebeldes! - oráculo do Senhor - que tomam providências, mas não as minhas, que fazem alianças, mas sem o meu espírito, acumulando pecado sobre pecado! Que descem ao Egito sem consultar-me, buscando refúgio na força do Faraó, à sombra do Egito buscam abrigo!" Este versículo denuncia a confiança de Israel em outras nações, sem buscar a orientação de Deus, o que resulta em mais pecado e infidelidade.
* Jeremias 13:23: "Acaso um etíope pode mudar a sua pele, ou um leopardo as suas manchas? Da mesma forma, vocês, que se acostumaram a fazer o mal, são incapazes de fazer o bem." Este versículo fala sobre a inevitabilidade da queda de Israel, que se habituou a fazer o mal e se afastou de Deus.
* Oséias 14:3: "Assíria não nos salvará, não montaremos mais cavalos, não chamaremos mais 'deus nosso' às obras das nossas mãos. Em ti o órfão encontra compaixão." Este versículo retrata a transformação que deve ocorrer em Israel, que precisa abandonar sua confiança em outras nações e voltar para Deus, que é o único capaz de salvá-los.
* Isaías 31:1: "Ai dos que descem ao Egito em busca de ajuda, que confiam em cavalos, em carros de guerra, em multidões de carregadores, em cavalos e em cavaleiros, mas não põem a sua confiança no Santo de Israel, nem buscam o Senhor!" Este versículo reforça a mensagem de que a confiança em outras nações e em coisas terrenas leva à queda e à destruição, e que a única fonte segura de salvação é Deus.
****

[[v33-17-1]]

^<<v33-17-1,1>>^ Foi-me dirigida a palavra do Senhor, nestes termos:

[[v33-17-2]]

^<<v33-17-2,2>>^ Filho de homem, propõe um enigma, conta uma parábola à casa de Israel.

[[v33-17-3]]

^<<v33-17-3,3>>^ Dir-lhe-ás; Assim fala o Senhor Deus: uma grande águia, de grandes asas, de enorme envergadura coberta de penas multícolores, veio ao Líbano e levou o cimo do cedro.

[[v33-17-4]]

^<<v33-17-4,4>>^ arrancou as últimas pontas dos seus ramos, transportou-as à terra de Canaan e pô-las numa cidade de negociantes (que é Babilônia).

[[v33-17-5]]

^<<v33-17-5,5>>^ Depois tomou um rebento de planta daquele pais e pô-lo num terreno preparado, plantou-o como um salgueiro, junto de águas abundantes.

[[v33-17-6]]

^<<v33-17-6,6>>^ Depois de ter brotado, cresceu e tornou-se uma videira extensa, porém de pouca altura, cujos ramos olhavam para a águia, e cujas raízes estavam debaixo dela. Tornou-se uma cepa, lançou sarmentos e produziu renovos. (ver nota)

[[v33-17-7]]

^<<v33-17-7,7>>^ Havia uma grande águia, de grandes asas e de muitas penas; e eis que esta videira voltou as suas raízes e estendeu os seus sarmentos para ela, do talhão em que estava plantada, a fim de ser regada.

[[v33-17-8]]

^<<v33-17-8,8>>^ Estava plantada numa boa terra, junto de copiosas águas, a fim de lançar folhas e dar fruto, e tornar-se uma grande videira. (ver nota)

[[v33-17-9]]

^<<v33-17-9,9>>^ Dize; Assim fala o Senhor Deus: Será possível que ela venha a ser bem sucedida? (A primeira águia) não lhe arrancará as suas raízes, não deitará abaixo os seus frutos, não secará todos os sarmentos que tiver brotado, e não ficará ela árida, e isto sem necessidade de grande força, nem de muita gente para arrancar pela raiz?

[[v33-17-10]]

^<<v33-17-10,10>>^ Ei-la aí está plantada; mas prosperará? Quando a tocar um vento abrasador, não se secará ela, não ficará árida, no talhão em que foi plantada?

[[v33-17-11]]

^<<v33-17-11,11>>^ Foi-me dirigida a palavra do Senhor, nestes termos:

[[v33-17-12]]

^<<v33-17-12,12>>^ Dize a esta casa rebelde: Não sabeis o que isto significa? Dize: Eis que veio o rei de Babilônia sobre Jerusalém, tomou o rei e os seus príncipes e levou-os para o seu reino, para Babilônia.

[[v33-17-13]]

^<<v33-17-13,13>>^ Depois tomou um (membro) da estirpe real, fez aliança com ele e recebeu dele juramento; até os fortes do país ele tirou

[[v33-17-14]]

^<<v33-17-14,14>>^ para que o reino ficasse abatido e não se levantasse, mas guardasse a sua aliança e a observasse.

[[v33-17-15]]

^<<v33-17-15,15>>^ Porém este (príncipe), revoltou-se contra ele. enviando mensageiros ao Egipto, para que lhe desse cavalos e muita gente. Porventura prosperará ou encontrará salvação, quem isto fez? O que violou a aliança, escapará?

[[v33-17-16]]

^<<v33-17-16,16>>^ (Juro) pela minha vida. diz o Senhor Deus, que no país do monarca que o fez rei, cujo juramento desprezou, cuja aliança violou, (lá) no meio de Babilônia morrerá.

[[v33-17-17]]

^<<v33-17-17,17>>^ Faraó, com o seu grande exército e com o seu muito povo, não combaterá a seu favor, quando se levantarem plataformas e construírem muros, para matar muitas pessoas.

[[v33-17-18]]

^<<v33-17-18,18>>^ Desprezou o juramento, violou a aliança, apesar de ter dado a sua mão. Tendo feito todas estas coisas, não escapará. (ver nota)

[[v33-17-19]]

^<<v33-17-19,19>>^ Portanto isto diz o Senhor Deus: Juro pela minha vida que foi o meu juramento que ele desprezou, a minha aliança que violou: farei recair isso sobre a sua cabeça.

[[v33-17-20]]

^<<v33-17-20,20>>^ Estenderei a minha rede sobre ele, e será apanhado nos meus laços; levá-lo-ei a Babilônia e lá o julgarei pela prevaricação cometida contra mim.

[[v33-17-21]]

^<<v33-17-21,21>>^ Todos os fugitivos do seu exército cairão mortos a espada; os que ficarem serão espalhados a todo o vento, e sabereis que eu, o Senhor, é que falei.

[[v33-17-22]]

^<<v33-17-22,22>>^ Isto diz o Senhor Deus: Tomarei do cimo do elevado cedro, cortarei do mais alto de seus ramos um tenro garfo, e plantá-lo-ei sobre uma elevadíssima montanha, (ver nota)

[[v33-17-23]]

^<<v33-17-23,23>>^ Eu o plantarei na alta montanha de Israel, e ele deitará ramos e dará fruto, e tornar-se-á um grande cedro; todas as aves habitarão debaixo dele, todas as espécies de voláteis repousarão à sombra dos seus ramos.

[[v33-17-24]]

^<<v33-17-24,24>>^ E saberão todas as árvores dos campos que eu, o Senhor é que humilho a árvore elevada e exalto a árvore humilde, que seco a árvore verde e faço reverdecer a árvore seca. Eu o Senhor, o disse e o farei.

'''

xref:033-ezequiel/033-ezequiel-016.adoc#v33-16-0[&#60; Capítulo Anterior] | <<v33-17-0,Topo>> | xref:033-ezequiel/033-ezequiel-018.adoc#v33-18-0[Próximo Capítulo &#62;]