include::./index.adoc[]

[[v33-33-0]]
=== Ezequiel, 33
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 33 de Ezequiel começa com o profeta sendo novamente chamado por Deus para ser um atalaia e alertar o povo sobre a necessidade de arrependimento. Ezequiel é instruído a transmitir a mensagem de Deus com clareza e fidelidade, alertando sobre a consequência da desobediência e incentivando a mudança de comportamento. Abaixo estão cinco versículos relacionados com os temas abordados em Ezequiel 33:
* Jeremias 18:7-8: "Em qualquer momento falarei de uma nação ou de um reino, para arrancá-lo, para destruí-lo ou para derrubá-lo. Mas, se essa nação, sobre a qual falei, se converter da sua maldade, então me arrependerei do mal que pensava em fazer-lhe."
Este versículo enfatiza a mensagem central de Ezequiel 33: Deus deseja que as pessoas se arrependam e mudem seu comportamento para evitar o castigo.
* Mateus 3:8: "Produzi, pois, frutos dignos de arrependimento."
Esse versículo mostra a importância da ação como evidência de verdadeiro arrependimento, um tema abordado por Ezequiel no capítulo 33.
* Lucas 15:7: "Digo-vos que, assim, haverá maior júbilo no céu por um pecador que se arrepende do que por noventa e nove justos que não precisam de arrependimento."
Esse versículo destaca a alegria do céu com o arrependimento do pecador, o que reforça o ponto principal de Ezequiel 33.
* Atos 26:20: "Preguei primeiramente aos que estavam em Damasco e em Jerusalém, por toda a região da Judeia e aos gentios, exortando-os a que se arrependessem e se convertessem a Deus, praticando obras dignas de arrependimento."
Esse versículo enfatiza a importância da conversão e do fruto do arrependimento, um tema central em Ezequiel 33.
* 1 Timóteo 1:15: "Esta é uma palavra fiel e digna de toda a aceitação: que Cristo Jesus veio ao mundo para salvar os pecadores, dos quais eu sou o principal."
Esse versículo destaca a centralidade de Cristo na mensagem de arrependimento e salvação, um tema importante em todo o livro de Ezequiel.
****

[[v33-33-1]]

^<<v33-33-1,1>>^ Foi-me dirigida a palavra do Senhor nestes termos:

[[v33-33-2]]

^<<v33-33-2,2>>^ Filho de homem, fala aos filhos do teu povo. Dir-lhes-ás; Quando eu fizer cair a espada sobre um país, se o povo desse país tomar um homem do seu seio e o constituir sentinela para vigiar sobre eles,

[[v33-33-3]]

^<<v33-33-3,3>>^ e esta sentinela, vendo vir a espada sobre o pais, tocar a trombeta e avisar disto o povo,

[[v33-33-4]]

^<<v33-33-4,4>>^ se aquele, que ouvir o som da trombeta, não tomar em conta o aviso, de forma que sobrevenha a espada e o mate, o seu sangue cairá sobre a sua cabeça:

[[v33-33-5]]

^<<v33-33-5,5>>^ (porque) ouviu o som da trombeta e não tomou em conta o aviso, o seu sangue cairá sobre a sua cabeça. Quanto ao que tomou em conta o aviso, esse salvará a sua vida.

[[v33-33-6]]

^<<v33-33-6,6>>^ Mas, se a sentinela vir que vem a espada e não tocar a trombeta, de forma que o povo não seja avisado, se vier a espada e tirar a vida a um deles, este tal perecerá devido à sua iniquidade, mas eu pedirei contas do seu sangue à sentinela.

[[v33-33-7]]

^<<v33-33-7,7>>^ Ora tu, filho de homem, és aquele a quem constituí sentinela na casa de Israel; tu, pois, ouvindo as palavras da minha boca. lhas anunciarás a eles, da minha parte.

[[v33-33-8]]

^<<v33-33-8,8>>^ Se, dizendo eu ao ímpio: ímpio, com certeza morrerás tu não falares ao ímpio, para ele se afastar do seu (mau) caminho, morrerá esse ímpio na sua iniquidade, mas eu pedir-te-ei contas do seu sangue.

[[v33-33-9]]

^<<v33-33-9,9>>^ Porém se, admoestando tu o ímpio para que se converta dos seus caminhos, ele se não converter, morrerá na sua iniquidade, e tu terás salva a tua vida.

[[v33-33-10]]

^<<v33-33-10,10>>^ Filho de homem, dize à casa de Israel: Costumais dizer isto: Ás nossas Iniquidades e os nossos pecados estão sobre nós, e por causa deles nos vamos consumindo; como poderemos nós, pois, (ainda) viver?

[[v33-33-11]]

^<<v33-33-11,11>>^ Dize-lhes; (Juro) pela minha vida, diz o Senhor Deus. que não quero a morte do ímpio, mas sim que se converta do seu mau proceder e viva. Convertei-vos, convertei-vos dos vossos maus caminhos! Por que haveis de morrer, ó (vós da) casa de Israel?

[[v33-33-12]]

^<<v33-33-12,12>>^ Filho de homem, dize aos filhos do teu povo: Em qualquer dia em que o justo pecar, a sua justiça não o livrará; da mesma forma, em qualquer dia em que o ímpio se converter da sua impiedade, a impiedade, não lhe fará mal, (Sem dúvida) em qualquer dia em que o justo venha a pecar, não poderá viver da sua justiça.

[[v33-33-13]]

^<<v33-33-13,13>>^ Ainda quando eu disser ao justo que terá vida, se ele, confiado na sua justiça, cometer a iniquidade, todas as suas obras de justiça serão postas no esquecimento e ele morrerá na iniquidade que cometeu.

[[v33-33-14]]

^<<v33-33-14,14>>^ Se, por outro lado, eu tiver dito ao ímpio: Tu certamente morrerás e ele se desviar do seu pecado e praticar obras rectas e justas,

[[v33-33-15]]

^<<v33-33-15,15>>^ se restituir o penhor que lhe foi confiado, se tornar ao dono o que roubou, se andar nos mandamentos da vida e não fizer nada de injusto, viverá certamente, não morrerá.

[[v33-33-16]]

^<<v33-33-16,16>>^ Nenhum dos pecados que cometeu lhe será imputado; praticou o que era recto e justo, e assim certamente viverá.

[[v33-33-17]]

^<<v33-33-17,17>>^ Entretanto, os filhos do teu povo dizem; O caminho do Senhor não é justo. (Ora, não). O caminho deles é que é injusto.

[[v33-33-18]]

^<<v33-33-18,18>>^ Quando o justo se apartar da sua justiça e cometer obras de iniquidade, encontrará nela a morte

[[v33-33-19]]

^<<v33-33-19,19>>^ Pelo contrário, quando o ímpio deixar a sua impiedade e praticar obras de rectidão e justiça, encontrará nelas a vida.

[[v33-33-20]]

^<<v33-33-20,20>>^ Ainda assim vós dizeis: O caminho do Senhor não á recto! Ó casa de Israel, eu hei-de julgar cada um de vós segundo as suas obras.

[[v33-33-21]]

^<<v33-33-21,21>>^ No ano duodécimo da nossa transmigração, no décimo mês, aos cinco do mês. um homem, que tinha fugido de Jerusalém, veio ter comigo e disse: A cidade foi tomada.

[[v33-33-22]]

^<<v33-33-22,22>>^ Ora a mão do Senhor tinha-se-me dado a sentir na tarde anterior à chegada do fugitivo, e o Senhor tinha-me abrido a boca antes que esse homem viesse ter comigo pela manhã. Tendo-me sido aberta a boca. não fiquei mais em silêncio.

[[v33-33-23]]

^<<v33-33-23,23>>^ Foi-me dirigida a palavra do Senhor, nestes termos:

[[v33-33-24]]

^<<v33-33-24,24>>^ Filho de homem, os que habitam entre essas ruínas da terra de Israel, falam assim: Abraão era sozinho, quando possuíu esta terra por herança; a nós, que somos muitos, a nós é que foi dada esta terra para a usufruirmos.

[[v33-33-25]]

^<<v33-33-25,25>>^ Responde-lhes, pois: Assim fala o Senhor Deus: Vós que comeis (a carne com) sangue, levantais os olhos para os vossos ídolos e derramais o sangue (humano), porventura haveis de possuir esta terra?

[[v33-33-26]]

^<<v33-33-26,26>>^ Apoiais-vos sobre as vossas espadas, cometeis abominações, violais a mulher do vosso próximo, e então haveis de possuir esta terra?

[[v33-33-27]]

^<<v33-33-27,27>>^ Tu lhes dirás: Assim fala o Senhor Deus: (Juro), pela minha vida, que aqueles que habitam entre as ruínas (de Jerusalém) perecerão á espada; que os que estão nos campos, os entregarei como pasto às feras; que os que se acolheram aos lugares fortes e às cavernas, morrerão de peste.

[[v33-33-28]]

^<<v33-33-28,28>>^ Reduzirei esta terra a uma solidão e a um deserto, e terminará o orgulho da sua fortaleza; os montes de Israel serão desolados, sem que haja pessoa alguma que passe por eles.

[[v33-33-29]]

^<<v33-33-29,29>>^ Então se saberá que sou o Senhor, quando eu tiver reduzido o país a uma solidão e a um deserto, em castigo de todas as abominações que cometeram.

[[v33-33-30]]

^<<v33-33-30,30>>^ Quanto a ti, filho de homem, os filhos do teu povo, que falam de ti junto dos muros e ás portas de suas casas, dizem uns para os outros, cada um falando com o seu vizinho: Vinde, e ouçamos a palavra que saí da boca do Senhor (por meio do profeta).

[[v33-33-31]]

^<<v33-33-31,31>>^ Vêm ter contigo, em massa, sentam-se diante de ti os do meu povo, ouvem as tuas palavras, mas não as põem em prática. Fazem o que é agradável à sua boca, enquanto o seu coração anda atrás do interesse.

[[v33-33-32]]

^<<v33-33-32,32>>^ Tu para eles és como um cantor delicioso, dotado de bela voz e que toca bem a sua citara; ouvem as tuas palavras (com gosto), mas não as põem em prática.

[[v33-33-33]]

^<<v33-33-33,33>>^ Mas, quando suceder o que foi predito, (e eis que está a ponto de acontecer) então saberão que houve um profeta entre eles.

'''

xref:033-ezequiel/033-ezequiel-032.adoc#v33-32-0[&#60; Capítulo Anterior] | <<v33-33-0,Topo>> | xref:033-ezequiel/033-ezequiel-034.adoc#v33-34-0[Próximo Capítulo &#62;]