include::./index.adoc[]

[[v33-7-0]]
=== Ezequiel, 7
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Ezequiel 7 descreve a chegada do dia do juízo sobre Jerusalém por causa da sua desobediência e pecado. Os versículos selecionados abaixo refletem o julgamento de Deus sobre o povo de Jerusalém e a falta de arrependimento deles:
* Isaías 13:6: "Gritem de dor, pois o dia do Senhor está próximo; como uma destruição vinda do Todo-Poderoso, ele virá!" Este versículo anuncia a chegada do Dia do Senhor, um dia de julgamento para aqueles que se rebelaram contra Deus e sua vontade.
* Jeremias 30:7: "Ah! Que grande dia será aquele! Não haverá outro como ele. Será tempo de angústia para Jacó, mas ele será salvo dessa angústia." Este versículo fala sobre o dia do juízo, que será uma época de grande angústia, mas aqueles que se voltarem para Deus serão salvos.
* Sofonias 1:14-15: "O grande dia do Senhor está próximo, próximo e chegando rapidamente. O som do dia do Senhor é amargo; ali o guerreiro grita. Esse dia será dia de ira, dia de angústia e aflição, dia de devastação e destruição, dia de trevas e escuridão, dia de nuvens e densas trevas." Este versículo descreve vividamente a chegada do dia do juízo, um dia de grande destruição e escuridão.
* Zacarias 14:1-2: "Eis que o dia do Senhor está chegando, e o seu saque será repartido no meio de vocês. Pois eu ajuntarei todas as nações para lutarem contra Jerusalém; a cidade será tomada, as casas serão saqueadas, e as mulheres serão violentadas. Metade da cidade irá para o exílio, mas o restante do povo não será extirpado da cidade." Este versículo profetiza a queda de Jerusalém nas mãos dos seus inimigos por causa do seu pecado e desobediência a Deus.
* Ezequiel 18:30: "Portanto, ó nação de Israel, eu o julgarei a cada um segundo o seu procedimento, declara o Soberano, o Senhor. Arrependam-se! Desviem-se de todos os seus pecados, para que a maldade não seja para vocês motivo de tropeço." Este versículo destaca a importância do arrependimento e mudança de comportamento diante do julgamento de Deus.
****

[[v33-7-1]]

^<<v33-7-1,1>>^ Foi-me dirigida a palavra do Senhor, a qual dizia:

[[v33-7-2]]

^<<v33-7-2,2>>^ Tu, filho de homem, (atende) assim fala o Senhor Deus à terra de Israel: Eis o fim! Já vem o fim sobre os quatro lados desta terra.

[[v33-7-3]]

^<<v33-7-3,3>>^ Agora chega o fim para ti; desafogarei o meu furor contra ti, julgar-te-ei segundo o teu proceder, farei recair sobre ti todas as tuas abominações.

[[v33-7-4]]

^<<v33-7-4,4>>^ O meu olho não te poupará. não me compadecerei de ti, mas farei recair sobre ti as tuas obras, e as tuas abominações estarão no meio de ti. Então sabereis que eu sou o Senhor.

[[v33-7-5]]

^<<v33-7-5,5>>^ Isto diz o Senhor Deus: Uma desgraça única! Eis que uma calamidade (singularíssima) chega.

[[v33-7-6]]

^<<v33-7-6,6>>^ O fim vem, vem o fim; ele despertou contra ti; ei-lo aí vem!

[[v33-7-7]]

^<<v33-7-7,7>>^ Ó tu que habitas nesta terra, uma total ruína vem sobre ti! É chegado o tempo, está perto o dia (da mortandade)! É (chegada) a confusão! Não mais alegria sobre os montes.

[[v33-7-8]]

^<<v33-7-8,8>>^ E agora, vou já derramar a minha ira sobre ti, satisfazer em ti o meu furor; julgar-te-ei segundo os teus caminhos, farei recair sobre ti todas as tuas abominações.

[[v33-7-9]]

^<<v33-7-9,9>>^ O meu olho não perdoará, não me compadecerei de ti, mas farei recair sobre ti as tuas obras, e as tuas abominações estarão no meio de ti. Então sabereis que sou eu, o Senhor que castigo.

[[v33-7-10]]

^<<v33-7-10,10>>^ Eis o dia, ei-lo aí vem! Chegou o dia da total destruição, floresceu a vara, brotou-a soberba.

[[v33-7-11]]

^<<v33-7-11,11>>^ A iniquidade levantou-se com a vara da impiedade; não escapará nada deles, nem do povo, nem do seu ruído; e não haverá neles descanso.

[[v33-7-12]]

^<<v33-7-12,12>>^ Chegou o tempo, está próximo o dia! O que compra, não alegre; e o que vende, não chore, porque a ira (do Senhor) está sobre todo o seu povo.

[[v33-7-13]]

^<<v33-7-13,13>>^ O que vende, não tornará a possuir o que vendeu, ainda que esteja entre os viventes, porque a visão (que tive) relativa a toda a sua multidão não ficará sem efeito, e ninguém encontrará segurança por causa da sua iniquidade.

[[v33-7-14]]

^<<v33-7-14,14>>^ Soa a trombeta, tudo está pronto, mas ninguém vai à batalha, porque a minha ira está sobre todo o povo.

[[v33-7-15]]

^<<v33-7-15,15>>^ Fora, a espada; dentro, a peste e a fome; o que está no campo, morrerá à espada; os que estão na cidade, serão devorados pela peste e pela fome.

[[v33-7-16]]

^<<v33-7-16,16>>^ Os que dentre eles fugirem, andarão sobre as montanhas como pombas dos vales, todos gemendo, cada um por causa da sua iniquidade.

[[v33-7-17]]

^<<v33-7-17,17>>^ Todas as mãos se enfraquecerão, todos os joelhos se fundirão em água.

[[v33-7-18]]

^<<v33-7-18,18>>^ Cingir-se-ão de sacos, o medo os cobrirá; em todo o rosto haverá confusão, e todas as suas cabeças serão rapadas (em. sinal de dor).

[[v33-7-19]]

^<<v33-7-19,19>>^ A sua prata será lançada às ruas, e o seu ouro será reputado como esterco. A sua prata e o seu ouro não os poderão livrar no dia do furor do Senhor. Não saciarão (com, isso) a sua alma, e os seus ventres se não se encherão, porque a sua iniquidade fez disso um motivo de queda.

[[v33-7-20]]

^<<v33-7-20,20>>^ Orgulhavam-se dos seus adornos, e disso fizeram os seus ídolos abomináveis; por tal motivo farei que seja para eles uma imundicie,

[[v33-7-21]]

^<<v33-7-21,21>>^ pô-lo-ei nas mãos dos estranhos para ser saqueado: servirá de presa aos ímpios da terra, que o contaminarão.

[[v33-7-22]]

^<<v33-7-22,22>>^ Apartarei deles o meu rosto e será profanado o meu santuário; entrarão nele bárbaros que o macularão.

[[v33-7-23]]

^<<v33-7-23,23>>^ Prepara cadeias, porque a terra está cheia de delitos sanguinários, e a cidade repleta de violências.

[[v33-7-24]]

^<<v33-7-24,24>>^ Farei vir os mais perversos dentre as gentes, e eles se apoderarão das suas casas; farei cessar a soberba dos poderosos, e serão profanados os seus santuários.

[[v33-7-25]]

^<<v33-7-25,25>>^ Chega a ruína! Eles buscarão a paz, e não a haverá.

[[v33-7-26]]

^<<v33-7-26,26>>^ A um desastre sucederá outro, a uma notícia (funesta) outra notícia sucederá; buscarão visões junto dos profetas, e a lei não existirá no sacerdote, nem o conselho nos anciães.

[[v33-7-27]]

^<<v33-7-27,27>>^ O rei chorará, e o príncipe cobrir-se-á de tristeza, e as mãos do povo da terra tremerão de medo. Tratá-los-ei segundo as suas obras, julgá-los-ei conforme eles julgaram os outros. Então saberão que eu sou o Senhor.

'''

xref:033-ezequiel/033-ezequiel-006.adoc#v33-6-0[&#60; Capítulo Anterior] | <<v33-7-0,Topo>> | xref:033-ezequiel/033-ezequiel-008.adoc#v33-8-0[Próximo Capítulo &#62;]