include::./index.adoc[]

[[v33-39-0]]
=== Ezequiel, 39
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 39 do livro de Ezequiel fala sobre a destruição dos inimigos de Israel e a restauração da terra. Deus promete punir os invasores que tentaram conquistar Israel e mostrará sua santidade a todas as nações. Ele também promete restaurar a terra e abençoar seu povo. Abaixo estão cinco versículos relacionados com os temas abordados em Ezequiel 39:
* Isaías 66:15: "Porque eis que o Senhor virá com fogo, e os seus carros como um torvelinho; para tornar a sua ira em furor, e a sua repreensão em chamas de fogo." Este versículo fala sobre a vinda do Senhor com fogo para julgar seus inimigos, o que é semelhante à descrição da destruição dos inimigos de Israel em Ezequiel 39.
* Isaías 66:18: "E eu, conhecendo-lhes as obras e seus pensamentos, venho para ajuntar todas as nações e línguas; elas virão e contemplarão a minha glória." Este versículo fala sobre todas as nações vindo para contemplar a glória de Deus, o que é semelhante à promessa de Deus em Ezequiel 39 de mostrar sua santidade a todas as nações.
* Joel 3:17: "E vós sabereis que eu sou o Senhor vosso Deus, que habito em Sião, o meu santo monte; e Jerusalém será santa, e estranhos não passarão mais por ela." Este versículo fala sobre Jerusalém sendo um lugar santo onde Deus habita e nenhuma nação estrangeira poderá passar por ela, o que é semelhante à restauração prometida por Deus em Ezequiel 39.
* Joel 3:20: "Mas Judá será habitada para sempre, e Jerusalém de geração em geração." Este versículo fala sobre Judá e Jerusalém sendo habitados para sempre, o que é semelhante à promessa de Deus em Ezequiel 39 de restaurar a terra e abençoar seu povo.
* Zacarias 8:8: "E os trarei, e habitarão no meio de Jerusalém; e eles serão o meu povo, e eu serei o seu Deus em verdade e em justiça." Este versículo fala sobre Deus trazendo seu povo de volta a Jerusalém para que eles possam habitar ali, o que é semelhante à restauração prometida por Deus em Ezequiel 39.
****

[[v33-39-1]]

^<<v33-39-1,1>>^ Tu, filho do homem, profetiza contra Gog dize: Assim fala o Senhor Deus: Eis-me aqui contra ti, ó Gog. príncipe soberano de Mosoc e de Tubal;

[[v33-39-2]]

^<<v33-39-2,2>>^ far-té-ei ir e vir (para onde quiser), tirar-te-ei para fora, far-te-ei vir das bandas do aquilão e te conduzirei sobre os montes de Israel.

[[v33-39-3]]

^<<v33-39-3,3>>^ Quebrarei o teu arco na tua mão esquerda, e farei que te caiam da mão direita as tuas flechas.

[[v33-39-4]]

^<<v33-39-4,4>>^ Cairás sobre os montes de Israel, com todos os teus esquadrões e os povos que estão contigo; entregar-te-ei às aves de rapina, a todo o animal volátil e aos animais dá terra, para que te devorem.

[[v33-39-5]]

^<<v33-39-5,5>>^ Cairás sobre a superfície do campo, porque eu o decretei, diz o Senhor Deus.

[[v33-39-6]]

^<<v33-39-6,6>>^ Enviarei fogo sobre Magog assim como sobre os que habitam confiadamente nas ilhas, e saberão que eu sou o Senhor.

[[v33-39-7]]

^<<v33-39-7,7>>^ Tornarei, assim, conhecido meu santo nome no meio do meu povo de Israel não deixarei profanar mais o meu santo nome, e as nações saberão que eu sou o Senhor, o santo de Israel.

[[v33-39-8]]

^<<v33-39-8,8>>^ Eis que isto se abeira, vai já suceder, diz o Senhor Deus: eis o dia de que falei.

[[v33-39-9]]

^<<v33-39-9,9>>^ Os habitantes das cidades de Israel sairão delas, e queimarão e reduzirão a cinzas as armas, os escudos e os broquéis. os arcos e as flechas, os bastões e os piques; tudo isto consumirão no fogo durante sete _(durante muitos)_ anos.

[[v33-39-10]]

^<<v33-39-10,10>>^ Não mais trarão lenha dos campos, nem a cortarão das matas, porque sustentarão o seu fogo com estas armas; despojarão aqueles que os tinham despojado, pilharão aqueles que. os tinham pilhado, diz o Senhor Deus.

[[v33-39-11]]

^<<v33-39-11,11>>^ Naquele dia darei a Gog em Israel um lugar célebre por sepulcro, o vale dos Transeuntes, ao oriente do mar, que tapará o caminho aos viandantes. Lá sepultarão Gog com toda a sua multidão de tropas, e este vale se chamará Vale de Hamon-Gog.

[[v33-39-12]]

^<<v33-39-12,12>>^ A casa de Israel os sepultará durante sete meses, para purificar a terra.

[[v33-39-13]]

^<<v33-39-13,13>>^ Todo o povo da terra trabalhará no seu enterramento; será para eles célebre o dia em que eu for glorificado, diz o Senhor Deus.

[[v33-39-14]]

^<<v33-39-14,14>>^ Constituirão homens que incessantemente percorram o país para sepultarem e buscarem aqueles que tinham ficado sobre a face da terra, a fim de a purificarem; farão esta busca depois de sete meses.

[[v33-39-15]]

^<<v33-39-15,15>>^ Percorrerão todo o país; quando tiverem achado ossos humanos, pôr-lhes-ão ao pé um sinal, até que os enterradores dos mortos os sepultem no Vale de Hamon-Gog.

[[v33-39-16]]

^<<v33-39-16,16>>^ O nome da cidade será Hamona. Desta forma purificarão a terra.

[[v33-39-17]]

^<<v33-39-17,17>>^ E tu. filho de homem (ouve) Assim fala o Senhor Deus: Dize a todo o animal volátil e a todos os animais do campo: Juntai-vos, vinde, concorrei de todas as partes ao meu sacrifício que vos ofereço, a uni grande sacrifício sobre os montes de Israel, para que comais a carne e bebais o sangue.

[[v33-39-18]]

^<<v33-39-18,18>>^ Comereis as carnes dos heróis, bebereis o sangue dos príncipes da terra, dos carneiros, dos cordeiros, dos bodes, dos touros .gordos de Basan.

[[v33-39-19]]

^<<v33-39-19,19>>^ Comereis carnes gordas até vos fartardes, bebereis sangue até ficardes embriagados neste sacrifício que vos ofereço;

[[v33-39-20]]

^<<v33-39-20,20>>^ fartar-vos-eis à minha mesa da carne dos cavalos, e da carne dos cavaleiros valentes e de todos os homens de guerra, diz o Senhor Deus.

[[v33-39-21]]

^<<v33-39-21,21>>^ Manifestarei a minha glória entre as nações, e todas as nações verão o meu juízo, quando o executar, a minha mão, quando a descarregar sobre eles.

[[v33-39-22]]

^<<v33-39-22,22>>^ E os da casa de Israel saberão que eu sou o Senhor .seu Deus, desde aquele dia e dali em diante.

[[v33-39-23]]

^<<v33-39-23,23>>^ As nações saberão que a casa de Israel foi levada cativa por causa da sua iniquidade, porque me atraiçoaram; escondi deles a minha face. entreguei-os nas mãos de seus inimigos, e todos caíram mortos ao fio da espada.

[[v33-39-24]]

^<<v33-39-24,24>>^ Tratei-os segundo a sua impureza e maldade, escondendo deles a minha face.

[[v33-39-25]]

^<<v33-39-25,25>>^ Por isso, isto diz o Senhor Deus : Agora tornarei a trazer os cativos de Jacob, compadecer-que-ei de toda a casa de Israel, mostrarei o meu zelo pela honra do meu santo nome.

[[v33-39-26]]

^<<v33-39-26,26>>^ Trarão sobre si a confusão de todas as prevaricações que cometeram contra mira, quando habitarem tranquilamente na sua terra, sem ter medo de ninguém.

[[v33-39-27]]

^<<v33-39-27,27>>^ Quando eu os tiver trazido dentre os povos e os tiver juntado das terras de seus inimigos, quando tiver sido santificado no meio deles, aos olhos de muitíssimas nações,

[[v33-39-28]]

^<<v33-39-28,28>>^ saberão que eu sou o Senhor seu Deus, porque, depois de os haver levado ao exílio entre as nações, os fiz voltar todos juntos para a sua terra, sem lá deixar nenhum deles.

[[v33-39-29]]

^<<v33-39-29,29>>^ Não lhes esconderei mais a minha face, porque derramarei o meu espírito sobre toda a casa de Israel, diz o Senhor Deus.

'''

xref:033-ezequiel/033-ezequiel-038.adoc#v33-38-0[&#60; Capítulo Anterior] | <<v33-39-0,Topo>> | xref:033-ezequiel/033-ezequiel-040.adoc#v33-40-0[Próximo Capítulo &#62;]