include::./index.adoc[]

[[v33-16-0]]
=== Ezequiel, 16
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Ezequiel 16 é um capítulo que usa a metáfora de uma prostituta para descrever a infidelidade de Israel com outros deuses e sua traição a Deus. O capítulo mostra que Deus resgatou Israel do nada e a fez uma nação próspera, mas ela se entregou à idolatria e à imoralidade. Aqui estão cinco versículos relacionados com os temas abordados em Ezequiel 16:
* Êxodo 20:3-5: "Não terás outros deuses diante de mim. Não farás para ti imagem esculpida, nem figura alguma do que há em cima no céu, nem embaixo na terra, nem nas águas debaixo da terra. Não te encurvarás diante delas, nem as servirás; porque eu, o Senhor teu Deus, sou Deus zeloso, que visito a iniquidade dos pais nos filhos até a terceira e quarta geração daqueles que me aborrecem." Este versículo destaca a proibição da idolatria e a advertência de Deus sobre as consequências daqueles que adoram outros deuses.
* Oséias 2:13: "Porque ela diz: Irei após os meus amantes, que me dão o meu pão e a minha água, a minha lã e o meu linho, o meu azeite e as minhas bebidas." Este versículo retrata a atitude de Israel em buscar outros deuses e acreditar que eles são a fonte de seus bens materiais.
* Isaías 1:21: "Como se fez a cidade fiel em uma prostituta! Ela estava cheia de justiça, a retidão habitava nela; mas agora, assassinos." Este versículo usa a metáfora da prostituta para descrever a infidelidade de Israel com outros deuses.
* Jeremias 3:8: "E vi que por causa de tudo isso, por ter cometido adultério a rebelde Israel, a despedi, e lhe dei a sua carta de divórcio, que a aleivosa Judá, sua irmã, não temeu; mas se foi e também ela mesma se prostituiu." Este versículo fala sobre Deus rejeitando Israel por causa de sua infidelidade e o comparando a um marido que se divorcia de sua esposa adúltera.
* Isaías 62:5: "Como o jovem se casa com a virgem, assim teus filhos se casarão contigo; e como o noivo se alegra da noiva, assim se alegrará de ti o teu Deus." Este versículo destaca a restauração de Israel e a reconciliação com Deus depois de seu arrependimento.
****

[[v33-16-1]]

^<<v33-16-1,1>>^ Foi-me dirigida a palavra do Senhor, nestes termos:

[[v33-16-2]]

^<<v33-16-2,2>>^ Filho de homem, faze conhecer a Jerusalém as suas abominações.

[[v33-16-3]]

^<<v33-16-3,3>>^ Dir-lhe-iás: Assim fala o Senhor Deus a Jerusalém: Pela tua origem e pelo teu nascimento és da terra de Canaan; teu pai era Amorreu, e tua mãe Heteia. (ver nota)

[[v33-16-4]]

^<<v33-16-4,4>>^ Quando vieste ao mundo, no dia do teu nascimento, não te foi cortado o cordão umbilical, não foste lavada em água, não te esfregaram com sal, nem foste enfaixada.

[[v33-16-5]]

^<<v33-16-5,5>>^ Não houve olho que olhasse para ti com piedade, com o intuito de te prestar algum destes serviços, compadecido de ti; mas foste arrojada sobre a face da terra, com desprezo por ti, no dia em que nasceste.

[[v33-16-6]]

^<<v33-16-6,6>>^ Passando junto de ti, vi-te, debatendo-te no teu sangue, e disse-te: Vive no teu sangue. Ainda que coberta do teu sangue, vive!

[[v33-16-7]]

^<<v33-16-7,7>>^ Fiz-te crescer como a erva no campo, e cresceste, e te tornaste grande, e atingiste uma beleza perfeita, no tempo da puberdade, em que se te desenvolveram os seios e cresceu o cabelo; porém estavas nua, completamente nua.

[[v33-16-8]]

^<<v33-16-8,8>>^ Passei junto de ti, e vi-te: era (chegado) o teu tempo, o tempo dos amores (ou da puberdade). Estendi sobre ti o meu manto e cobri a tua nudez; jurei-te (fidelidade), fiz aliança contigo, diz o Senhor Deus, e tu ficaste sendo minha.

[[v33-16-9]]

^<<v33-16-9,9>>^ Lavei-te com água, limpei-te do teu sangue e ungi-te com óleo.

[[v33-16-10]]

^<<v33-16-10,10>>^ Vesti-te de roupas bordadas, dei-te calçado de couro fino, cingi-te de linho e cobri-te de seda

[[v33-16-11]]

^<<v33-16-11,11>>^ Ornei-te de preciosos enfeites, pus-te braceletes nas mãos, um colar ao pescoço.

[[v33-16-12]]

^<<v33-16-12,12>>^ uma argola no nariz, arrecadas nas orelhas, e um formoso diadema na cabeça.

[[v33-16-13]]

^<<v33-16-13,13>>^ Foste enfeitada de ouro e prata, vestida de linho fino, de seda e de roupas bordadas; nutriste-te da flor da farinha, de mel e de azeite; tornaste-te mui formosa e chegaste a ser rainha.

[[v33-16-14]]

^<<v33-16-14,14>>^ O teu renome espalhou-se entre as nações, por causa da tua formosura, porque era perfeita, graças ao esplendor de que eu te havia revestido, diz o Senhor Deus.

[[v33-16-15]]

^<<v33-16-15,15>>^ Mas puseste a tua confiança na tua beleza, aproveitaste-te da tua reputação para te prostituires, ofereceste a tua lascívia a todos os que passavam, entregando-te a eles.

[[v33-16-16]]

^<<v33-16-16,16>>^ Tomando dos teus vestidos, fizeste lugares altos para ti, de variadas cores, e ali fornicaste, como nunca sucedeu, nem sucederá

[[v33-16-17]]

^<<v33-16-17,17>>^ Pegaste nos teus belos adornos, feitos do meu ouro e da minha prata, que te tinha dado, e fizeste deles figuras humanas, às quais te prostituiste.

[[v33-16-18]]

^<<v33-16-18,18>>^ Pegaste nos teus vestidos bordados e cobriste com eles os teus ídolos, diante dos quais puseste o meu azeite e os meus perfumes.

[[v33-16-19]]

^<<v33-16-19,19>>^ Puseste diante deles, como oferenda de agradável odor, o pão que te dei, a flor da farinha, o azeite e o mel, com que te nutria. Eis o que foi feito, diz o Senhor Deus.

[[v33-16-20]]

^<<v33-16-20,20>>^ Pegaste nos teus filhos e nas tuas filhas, que me tinhas gerado, e sacrificaste-os a esses ídolos, para seu pasto. Porventura é pequena demais a tua fomicação?

[[v33-16-21]]

^<<v33-16-21,21>>^ Imolaste os meus filhos e entregaste-lhos, fazendo-os passar pelo fogo, em sua honra.

[[v33-16-22]]

^<<v33-16-22,22>>^ No meio de todas as tuas abominações e prostituições, não te lembraste dos dias da tua mocidade, quando estavas nua, completamente nua, rojando-te no teu sangue.

[[v33-16-23]]

^<<v33-16-23,23>>^ Depois de tanta malícia tua (ai, ai de ti! diz o Senhor Deus),

[[v33-16-24]]

^<<v33-16-24,24>>^ edificaste para ti um lupanar, e fizeste para ti em todas as praças públicas uma casa de prostituição.

[[v33-16-25]]

^<<v33-16-25,25>>^ Puseste à entrada de todas as ruas o sinal da tua prostituição, tornaste abominável a tua formosura, entregaste-te a todos os que passavam, e multiplicaste as tuas fornicações.

[[v33-16-26]]

^<<v33-16-26,26>>^ Prostituiste-te aos filhos do Egipto, teus vizinhos, muito corpulentos, multiplicaste as tuas prostituições para me irritares.

[[v33-16-27]]

^<<v33-16-27,27>>^ Eis que estendi a minha mão sobre ti, diminuí a tua porção, entreguei-te ao arbítrio das filhas dos Filisteu, tuas inimigas, que se envergonham do teu infame procedimento.

[[v33-16-28]]

^<<v33-16-28,28>>^ Não te dando ainda por satisfeita, prostituíste-te aos filhos dos Assírios; e, depois desta prostituição, nem ainda assim ficaste satisfeita.

[[v33-16-29]]

^<<v33-16-29,29>>^ Multiplicaste a tua fornicação (ou idolatria) na terra dos mercadores, entre os Caldeus, mas nem ainda assim ficaste saciada.

[[v33-16-30]]

^<<v33-16-30,30>>^ Quão fraco é o teu coração, diz o Senhor Deus, para teres feito todas estas obras próprias da mais descarada meretriz!

[[v33-16-31]]

^<<v33-16-31,31>>^ Edificaste a casa da tua prostituição à entrada de todas as ruas fizeste o teu alto em todas as praças públicas; nem foste como uma meretriz que com o seu desdém aumenta o preço, (ver nota)

[[v33-16-32]]

^<<v33-16-32,32>>^ mas como uma mulher adúltera, que, em vez de seu marido, recebe os estranhos.

[[v33-16-33]]

^<<v33-16-33,33>>^ A todas as prostitutas se dão presentes mas tu é que os deste a todos os teus amantes, que os recompensaste, para de todas as partes virem a tua casa para as tuas prostituições. (ver nota)

[[v33-16-34]]

^<<v33-16-34,34>>^ Assim, nas tuas prostituições, te sucedeu tudo ao contrário das mulheres (de má vida): ninguém te procurava, mas tu é que davas a paga, em vez de a receber, fazendo tudo ao contrário do que as outras fazem.

[[v33-16-35]]

^<<v33-16-35,35>>^ Por isso, ó meretriz, ouve a palavra do Senhor.

[[v33-16-36]]

^<<v33-16-36,36>>^ Isto diz o Senhor Deus: Porque gastaste mal o teu dinheiro e descobriste a tua nudez, nas tuas prostituições com teus amantes e com teus ídolos abomináveis e porque lhes deste o sangue de teus filhos,

[[v33-16-37]]

^<<v33-16-37,37>>^ eis que vou juntar todos os teus amantes, com quem luxuriaste todos os que amaste e todos os que aborreceste, juntá-los-ei de todas as partes contra ti, e descobrirei a tua nudez diante deles, e verão toda a tua nudez.

[[v33-16-38]]

^<<v33-16-38,38>>^ Julgar-te-ei segundo as leis que há sobre as adúlteras e sobre as que derramam sangue, e farei de ti uma vítima sangrenta de furor e do zelo.

[[v33-16-39]]

^<<v33-16-39,39>>^ Entregar-te-ei nas suas mãos, e eles destruirão o lugar da tua prostituição, demolirão os teus lugares altos, despir-te-ão dos teus vestidos, roubarão os teus adornos e deixar-te-ão despojada e nua.

[[v33-16-40]]

^<<v33-16-40,40>>^ Conduzirão contra ti uma multidão de gente, apedrejar-te-ão e atravessar-te-ão com as suas espadas;

[[v33-16-41]]

^<<v33-16-41,41>>^ queimarão as tuas casas, pondo-lhes fogo, e executarão contra ti juízos, aos olhos dum grande número de mulheres; porei fim às tuas prostituições e não tornai-ás mais a dar recompensas. (ver nota)

[[v33-16-42]]

^<<v33-16-42,42>>^ Saciarei a minha indignação contra ti, e o meu zelo se retirará de ti, e me apaziguarei, e não me tornarei mais a irar.

[[v33-16-43]]

^<<v33-16-43,43>>^ Porque te não lembraste dos dias da tua mocidade e me irritaste com todos estes excessos, por isso também fiz que recaísse sobre a tua cabeça o teu proceder, diz o Senhor Deus. Não cometeste o mal com todas as tuas práticas abomináveis?

[[v33-16-44]]

^<<v33-16-44,44>>^ Eis que todos os que proferem provérbios te aplicarão este: Tal mãe, tal filha. (ver nota)

[[v33-16-45]]

^<<v33-16-45,45>>^ Tu és bem a filha de tua mãe, a qual abandonou o seu esposo (místico, que ó Deus) e os seus filhos (sacrificando-os aos ídolos); e és a irmã de tuas irmãs, que abandonaram os seus esposos e os seus filhos; vossa mãe é Hetela e vosso pal Amorreu.

[[v33-16-46]]

^<<v33-16-46,46>>^ Tua irmã mais velha é a Samaria com as suas filhas (ou cidades) que habitam à tua mão esquerda; e tua irmã mais nova, que habita à tua mão direita, é Sodoma com suas filhas (ou cidades). (ver nota)

[[v33-16-47]]

^<<v33-16-47,47>>^ Porém tu não sòmente não ficaste atrás em seguir os seus caminhos e em obrar segundo as suas maldades, mas foste mais perversa que elas em teu proceder,

[[v33-16-48]]

^<<v33-16-48,48>>^ Por minha vida, diz o Senhor Deus. (juro) que o que fez Sodoma, tua irmã, ela e suas filhas, não foi tanto Como o que tu e suas filhas fizestes.

[[v33-16-49]]

^<<v33-16-49,49>>^ Eis qual foi a iniquidade de Sodoma, tua irmã: a soberba, a fartura de pão, a ociosidade dela e de suas filhas e o não estender a mão para o pobre e para o desgraçado.

[[v33-16-50]]

^<<v33-16-50,50>>^ Ensoberbeceram-se, cometeram abominações diante de mim, e eu as destruí, como tu viste.

[[v33-16-51]]

^<<v33-16-51,51>>^ A Samaria também não cometeu metade dos teus pecados; tu as ultrapassaste ambas com as tuas maldades, justificaste as tuas irmãs com todas as abominações que cometeste. (ver nota)

[[v33-16-52]]

^<<v33-16-52,52>>^ Leva, pois, a ignomínia das tuas faltas, com que justificaste tuas irmãs, procedendo mais culpàvelmente que elas: são mais justas do que tu. Por isso confunde-te, também, leva a tua ignomínia, tu que justificaste as suas irmãs.

[[v33-16-53]]

^<<v33-16-53,53>>^ Todavia eu as restabelecerei, fazendo que voltem os cativos de Sodoma e de suas filhas, como também os cativos da Samaria e de suas filhas; depois farei voltar os teus filhos cativos para o meio dos ídolos,

[[v33-16-54]]

^<<v33-16-54,54>>^ a fim de que suportes a tua ignomínia e te confundas de tudo o que tens feito para as consolar.

[[v33-16-55]]

^<<v33-16-55,55>>^ Tua irmã Sodoma e suas filhas tornarão ao seu antigo estado; Samaria e suas filhas tornarão também ao seu estado antigo; e tu e tuas filhas tomareis também ao vosso primitivo estado.

[[v33-16-56]]

^<<v33-16-56,56>>^ O nome da tua irmã Sodoma não foi ouvido na tua boca, no tempo da tua soberba. (ver nota)

[[v33-16-57]]

^<<v33-16-57,57>>^ antes que a tua malícia estivesse descoberta, como agora está, antes que tu fosses o opróbrio para as filhas da Síria e das suas redondezas, para todas as filhas dos Filisteus, que te insultam de todos os lados.

[[v33-16-58]]

^<<v33-16-58,58>>^ Levaste sobre ti as tuas maldades e a tua ignomínia, diz o Senhor Deus.

[[v33-16-59]]

^<<v33-16-59,59>>^ Porque isto diz o Senhor Deus: Procederei contigo como tu procedeste, tu que desprezaste o juramento, rompendo a aliança (que tinha feito contigo).

[[v33-16-60]]

^<<v33-16-60,60>>^ Apesar disso, lembrar-me-ei da aliança que tinha feito contigo, nos dias da tua mocidade, e estabelecerei contigo uma aliança eterna.

[[v33-16-61]]

^<<v33-16-61,61>>^ Então te recordarás do teu (mau) proceder e te confundirás, quando receberes tuas irmãs mais velhas e tuas irmãs mais novas, é eu tas der por filhas, mas isto não em virtude da tua aliança. (ver nota)

[[v33-16-62]]

^<<v33-16-62,62>>^ Eu é que renovarei a minha aliança contigo, e saberás que sou o Senhor,

[[v33-16-63]]

^<<v33-16-63,63>>^ a fim de que te recordes e te confundas, e não te atrevas a abrir mais a boca por causa da tua confusão, quando eu te tiver perdoado todas as coisas que fizeste, diz o Senhor Deus.

'''

xref:033-ezequiel/033-ezequiel-015.adoc#v33-15-0[&#60; Capítulo Anterior] | <<v33-16-0,Topo>> | xref:033-ezequiel/033-ezequiel-017.adoc#v33-17-0[Próximo Capítulo &#62;]