include::./index.adoc[]

[[v33-45-0]]
=== Ezequiel, 45
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Ezequiel 45 descreve as porções de terra que serão dadas aos príncipes e ao templo no futuro, bem como a distribuição da oferta e dos impostos. Os versículos a seguir fornecem temas relacionados com este capítulo:
* Isaías 61:8: "Porque eu, o Senhor, amo a justiça; odeio o roubo e a iniquidade. Em minha fidelidade os recompensarei e farei com eles uma aliança eterna." Este versículo destaca a importância da justiça e da fidelidade em relação às ofertas e impostos mencionados em Ezequiel 45.
* Deuteronômio 25:13-15: "Não tenha em sua bolsa dois tipos de peso, um pesado e outro leve. Não tenha em sua casa dois tipos de medida, uma grande e outra pequena. Use apenas uma medida, um peso justo e preciso, para que tenha uma vida longa na terra que o Senhor, o seu Deus, lhe dá." Este versículo fala sobre a importância da justiça em relação às medidas e pesos usados na troca de bens, o que pode ser aplicado às porções de terra mencionadas em Ezequiel 45.
* 1 Crônicas 29:3: "Além disso, porque amo a casa do meu Deus, o tesouro pessoal que possuo de ouro e prata, entrego-o para a casa do meu Deus, além de tudo o que preparei para o santo templo." Este versículo destaca a importância do templo mencionado em Ezequiel 45 e a dedicação de recursos para seu sustento.
* Deuteronômio 16:17: "Cada um dará conforme tiver decidido em seu coração, não com pesar ou por obrigação, pois Deus ama quem dá com alegria." Este versículo fala sobre a atitude de dar ofertas e como isso deve ser feito de forma voluntária e alegre, o que pode ser aplicado à oferta mencionada em Ezequiel 45.
* 1 Crônicas 29:9: "O povo se alegrou com as ofertas voluntárias, pois com coração sincero as davam livremente ao Senhor. O rei Davi também se encheu de alegria." Este versículo destaca a alegria do povo ao dar ofertas voluntárias e o valor dessa atitude, o que pode ser aplicado à oferta mencionada em Ezequiel 45.
****

[[v33-45-1]]

^<<v33-45-1,1>>^ Quando começardes a dividir a terra por sortes (entre as famílias) separai, como oferta reservada ao Senhor, um pedaço da terra., que será sagrado. Terá vinte e cinco mil medidas (ou côvados) de comprimento, e dez mil de largura; será sagrado em toda a sua extensão.

[[v33-45-2]]

^<<v33-45-2,2>>^ De todo este espaço separareis, para santuário, um quadrado de quinhentos côvados de cada lado, tendo em toda a volta uma cerca de cinqüenta côvados de espaço vazio.

[[v33-45-3]]

^<<v33-45-3,3>>^ Sobre esta superfície, medireis um comprimento de vinte e cinco mil (côvados), e uma largura de dez mil onde ficará o santuário, o Santo dos Santos.

[[v33-45-4]]

^<<v33-45-4,4>>^ Esta porção de terra consagrada (a Deus) será para os sacerdotes, ministros do santuário, que se aproximam para servir o Senhor; tal porção será destinada para suas casas e como lugar consagrado para o santuário.

[[v33-45-5]]

^<<v33-45-5,5>>^ Haverá também outros vinte e cinco mil côvados de comprimento e dez mil de largura para os levitas que servem no templo; aí terão cidades (ou povoações) para morar (destinadas aos que estiverem de serviço).

[[v33-45-6]]

^<<v33-45-6,6>>^ Dai-eis cinco mil côvados de largura e vinte e cinco mil de comprimento, paralelamente ao que está separado para o santuário., para domínio da cidade; isto pertencerá à casa de Israel.

[[v33-45-7]]

^<<v33-45-7,7>>^ Também ao príncipe (dareis a sua porção) duma e outra parte, junto ao que foi separado para o santuário e junto à possessão da cidade, em frente do que foi apartado para o santuário e em frente da possessão da cidade, do lado do ocidente., para ocidente, e, do lado do oriente, para oriente. O comprimento será igual ao de cada parte, desde a fronteira ocidental até á oriental do país.

[[v33-45-8]]

^<<v33-45-8,8>>^ Será a sua porção em Israel. Os príncipes não oprimirão mais o meu povo, mas deixarão a terra à casa de Israel, segundo as sua tribos.

[[v33-45-9]]

^<<v33-45-9,9>>^ Isto diz o Senhor Deus; Baste-vos, 6 príncipes de Israel, (o que tendes feito)! Cessai de cometer a violência e as rapinas, praticai o direito e a justiça, não sobrecarregueis com mais exacções o meu povo, diz o Senhor Deus.

[[v33-45-10]]

^<<v33-45-10,10>>^ Seja justa a vossa balança, justo o efa, justo o bato.

[[v33-45-11]]

^<<v33-45-11,11>>^ O efa e o bato serão duma mesma medida, de sorte que o bato (para os líquidos) tenha a décima parte do homer, e o efa (para os sólidos) tenha a mesma décima parte do homer; a sua capacidade será igual, comparada com a medida do homer.

[[v33-45-12]]

^<<v33-45-12,12>>^ O siclo tem vinte óbolos. E vinte siclos, com vinte e cinco siclos mais quinze siclos, fazem uma mina.

[[v33-45-13]]

^<<v33-45-13,13>>^ Eis as primícias que vós oferecereis. A sexta parte dum efa, de cada homer de trigo, e a sexta parte dum efa, de cada homer de cevada.

[[v33-45-14]]

^<<v33-45-14,14>>^ Quanto à medida do azeite, dareis a décima parte dum bato por cada cor, que é igual ao homer, pois tem dez batos, porque dez batos enchem um homer.

[[v33-45-15]]

^<<v33-45-15,15>>^ (Oferecereis) um carneiro de cada rebanho -de duzentas cabeças das pastagens de Israel, para a oblação, para os holocaustos e para os sacrifícios pacíficos, a fim de fazer expiação por eles, diz o Senhor Deus.

[[v33-45-16]]

^<<v33-45-16,16>>^ Todo o povo da terra será obrigado a pagar estas primícias ao que for príncipe em Israel.

[[v33-45-17]]

^<<v33-45-17,17>>^ Mas estarão a cargo do príncipe os holocaustos, as oferendas e as libações nos dias solenes, nos primeiros dias de cada mês, nos sábados, em todas as solenidades da casa de Israel; ele oferecerá (o necessário para) o sacrifício pelo pecado, para o holocausto e para os sacrifícios pacíficos, a fim de se fazer a explação pela casa de Israel.

[[v33-45-18]]

^<<v33-45-18,18>>^ Isto diz o Senhor Deus; No primeiro mês, no primeiro dia do mês, tomarás um novilho sem defeito e expiação, purificarás o santuário.

[[v33-45-19]]

^<<v33-45-19,19>>^ O sacerdote tomará do sangue da vítima oferecida pelo pecado, e espargirá com ele os postes do templo, os quatro cantos do quadro do altar e os postes da porta do átrio Interior.

[[v33-45-20]]

^<<v33-45-20,20>>^ O mesmo farás no sétimo dia do mês, por cada um que pecou por ignorância ou por irreflexão, e (assim) purificarás o templo.

[[v33-45-21]]

^<<v33-45-21,21>>^ No primeiro mês, a quatorze do mês, celebrareis a solenidade da páscoa, comendo pães ázimos durante sete dias.

[[v33-45-22]]

^<<v33-45-22,22>>^ O príncipe oferecerá nesse dia por si e por todo o povo da terra um novilho pelo pecado.

[[v33-45-23]]

^<<v33-45-23,23>>^ Depois, oferecerá em holocausto ao Senhor durante a solenidade dos sete dias, sete novilhos e sete carneiros sem defeito, cada dia, durante os sete dias; oferecerá também cada dia um bode pelo pecado.

[[v33-45-24]]

^<<v33-45-24,24>>^ Como oblação oferecerá um efa (de farinha) por cada novilho, e um efa por cada carneiro; juntará um hin de azeite a cada efa.

[[v33-45-25]]

^<<v33-45-25,25>>^ No sétimo mês, aos quinze do mês, em que se celebra a solenidade (dos Tabernáculos) fará durante sete dias contínuos as mesmas coisas que se disseram acima, tanto pela expiação do pecado como pelo holocausto, e a oblação (da farinha) e do azeite.

'''

xref:033-ezequiel/033-ezequiel-044.adoc#v33-44-0[&#60; Capítulo Anterior] | <<v33-45-0,Topo>> | xref:033-ezequiel/033-ezequiel-046.adoc#v33-46-0[Próximo Capítulo &#62;]