include::./index.adoc[]

[[v33-24-0]]
=== Ezequiel, 24
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Ezequiel 24 apresenta uma parábola sobre a destruição iminente de Jerusalém e a morte da esposa do profeta. Os versículos selecionados abaixo estão relacionados com a tristeza e a perda, que são temas presentes nesse capítulo:
* Salmos 34:18: "Perto está o Senhor dos que têm o coração quebrantado e salva os de espírito oprimido." Este versículo destaca que Deus está perto daqueles que estão sofrendo e quebrantados, oferecendo-lhes salvação e conforto.
* Isaías 61:2-3: "proclamar o ano aceitável do Senhor e o dia da vingança do nosso Deus; consolar todos os que choram e pôr sobre os que em Sião estão de luto uma coroa em vez de cinzas, óleo de alegria em vez de pranto, e um manto de louvor em vez de espírito deprimido." Este versículo destaca que Deus oferece consolo e alegria para aqueles que choram e sofrem, transformando sua tristeza em louvor.
* 2 Coríntios 1:3-4: "Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, o Pai das misericórdias e Deus de toda a consolação! É ele que nos conforta em toda a nossa tribulação, para podermos consolar os que estiverem em qualquer angústia, com a consolação com que nós mesmos somos contemplados por Deus." Este versículo enfatiza que Deus é o Deus de toda a consolação e que ele pode nos confortar em tempos de tribulação, para que possamos consolar os outros também.
* João 14:27: "Deixo-lhes a paz; a minha paz lhes dou. Não a dou como o mundo a dá. Não se perturbem os seus corações, nem tenham medo." Este versículo destaca que Jesus nos oferece paz, uma paz que é diferente da paz que o mundo pode oferecer, e que essa paz pode acalmar nossos corações em tempos de tristeza e medo.
* Romanos 8:18: "Considero que os nossos sofrimentos atuais não podem ser comparados com a glória que em nós será revelada." Este versículo enfatiza que, apesar do sofrimento atual, há uma glória que será revelada no futuro, dando-nos esperança e conforto.
****

[[v33-24-1]]

^<<v33-24-1,1>>^ No ano nono, no décimo mês, aos dez dias do mês, foi-me dirigida a palavra do Senhor nestes termos:

[[v33-24-2]]

^<<v33-24-2,2>>^ Filho de homem, escreve a data deste dia, porque é hoje que o rei de Babilônia assentou arraiais contra Jerusalém.

[[v33-24-3]]

^<<v33-24-3,3>>^ Expõe à casa (de Israel) rebelde esta parábola. Assim lhes falarás; Isto diz o Senhor Deus: Põe uma caldeira ao lume; põe-na, digo, e deita-lhe água dentro.

[[v33-24-4]]

^<<v33-24-4,4>>^ Mete nela pedaços de carne, todos escolhidos, coxa e espádua, e acaba de a encher com os melhores ossos.

[[v33-24-5]]

^<<v33-24-5,5>>^ Pega na carne das reses mais gordas, põe por baixo da caldeira um montão de ossos; faze que ferva em borbulhões. até que se cozam também os ossos que estão dentro dela.

[[v33-24-6]]

^<<v33-24-6,6>>^ Eis o que diz o Senhor Deus: Ai da cidade do sangue, que é como uma caldeira cheia de ferrugem, ferrugem que não pode ser tirada. Esvazia-a dos bocados que tem dentro, uns após outros, sem tirar à sorte.

[[v33-24-7]]

^<<v33-24-7,7>>^ O sangue (inocente) que derramou está ainda no meio dela; sobre pedra nua o derramou; não o derramou sobre a terra, para o cobrir com o pó.

[[v33-24-8]]

^<<v33-24-8,8>>^ Para fazer cair sobre ela a minha indignação, para me vingar (como ela merece), espalhei também o seu sangue sobre a pedra nua, para que não fosse coberto.

[[v33-24-9]]

^<<v33-24-9,9>>^ Portanto isto diz o Senhor Deus; Ai da cidade do sangue! Também eu vou fazer uma grande fogueira!

[[v33-24-10]]

^<<v33-24-10,10>>^ Junta muita lenha, acende o fogo, coze a carne prepara o tempero, e sejam queimados os ossos.

[[v33-24-11]]

^<<v33-24-11,11>>^ Põe, depois, a caldeira vazia sobre as brasas, para que ela aqueça e o seu cobre se abrase, e se funda dentro dela a sua imundície. e se consuma a sua ferrugem.

[[v33-24-12]]

^<<v33-24-12,12>>^ Vãos esforços! Não saiu dela a sua muita ferrugem, nem por meio do fogo.

[[v33-24-13]]

^<<v33-24-13,13>>^ Da iniundície do teu proceder eu quis limpar-te, mas não ficaste limpa das tuas impurezas; não mais serás limpa, até que satisfaça contra ti a minha indignação.

[[v33-24-14]]

^<<v33-24-14,14>>^ Eu. o Senhor, falei: isto acontecerá; agirei sem recuar, não perdoarei, não me aplacarei; segundo os teus caminhos e segundo as tuas obras far-se-á o teu julgamento, diz o Senhor.

[[v33-24-15]]

^<<v33-24-15,15>>^ Foi-me dirigida a palavra do Senhor nestes termos;

[[v33-24-16]]

^<<v33-24-16,16>>^ Filho de homem, eis que vou tirar-te dum golpe aquilo que é mais agradável aos teus olhos (a tua esposa), mas tu não te lamentarás, não chorarás. não te correrão as lágrimas (pelo rosto).

[[v33-24-17]]

^<<v33-24-17,17>>^ Geme em silêncio; não tomes luto, como se faz pelos mortos; põe na cabeça o teu turbante, o calçado nos teus pés; não cubras o rosto (com um véu) nem comas o pão que se dá aos que estão de luto.

[[v33-24-18]]

^<<v33-24-18,18>>^ Falei de manhã ao povo, e à tarde morreu minha mulher; ao outro dia, pela manhã, fiz o que me tinha sido ordenado.

[[v33-24-19]]

^<<v33-24-19,19>>^ Então me disse o povo; Por que nos não explicas o que significam estas coisas que fazes?

[[v33-24-20]]

^<<v33-24-20,20>>^ Respondi; Foi-me dirigida a palavra do Senhor, nestes termos;

[[v33-24-21]]

^<<v33-24-21,21>>^ Pala à casa de Israel; Isto diz o Senhor Deus; Eis que vou profanar o meu santuário, orgulho da vossa força, delícias dos vossos olhos, amor das vossas almas. Os vossos filhos e as vossas filhas que deixastes, cairão aos golpes da espada.

[[v33-24-22]]

^<<v33-24-22,22>>^ E vós fareis como eu fiz; não cobrireis o rosto (com véu) nem comereis do pão que se dá aos que estão de luto; (ver nota)

[[v33-24-23]]

^<<v33-24-23,23>>^ tereis os vossos turbantes nas vossas cabeças, e calçado nos pés; não vos lamentareis, não chorareis, mas consumir-vos-eis nas vossas iniquidades e gemereis uns dom os outros.

[[v33-24-24]]

^<<v33-24-24,24>>^ Ezequiel será para vós um sinal; tudo o que ele fez (na morte de sua esposa), fá-lo-eis vós igualmente, quando estas coisas acontecerem, e sabereis que eu sou o Senhor Deus.

[[v33-24-25]]

^<<v33-24-25,25>>^ E tu, filho de homem, no. dia em que eu tirar deles a sua fortaleza, a sua glória e a sua alegria, as delícias de seus olhos, o desejo das suas almas, a saber, seus filhos e suas filhas.

[[v33-24-26]]

^<<v33-24-26,26>>^ nesse dia, quando vier ter contigo algum que escapar, para te dar novas,

[[v33-24-27]]

^<<v33-24-27,27>>^ nesse dia, digo, abrir-se-á a tua boca para falares com o fugitivo; falarás e não ficarás mais em silêncio e serás para eles um sinal (ou vatícinio), e, assim, saberão que eu sou o Senhor.

'''

xref:033-ezequiel/033-ezequiel-023.adoc#v33-23-0[&#60; Capítulo Anterior] | <<v33-24-0,Topo>> | xref:033-ezequiel/033-ezequiel-025.adoc#v33-25-0[Próximo Capítulo &#62;]