include::./index.adoc[]

[[v33-26-0]]
=== Ezequiel, 26
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Ezequiel 26 contém uma profecia sobre a destruição da cidade de Tiro. Os versículos selecionados abaixo estão relacionados com a soberania de Deus e sua capacidade de julgar as nações:
* Salmos 75:6-7: "Nas mãos do Senhor está um cálice cheio de vinho espumante, misturado com especiarias; ele o derrama, e todos os ímpios da terra o bebem até o fim. Eu o proclamarei para sempre, cantarei louvores ao Deus de Jacó." Este versículo destaca que Deus tem o poder de julgar as nações e punir os ímpios, e que devemos proclamar sua soberania e louvá-lo por isso.
* Isaías 40:15: "Com quem vocês podem comparar a Deus? A que imagem poderão assemelhá-lo?" Este versículo enfatiza a grandeza e singularidade de Deus, destacando que não há nada no mundo que se possa comparar a ele.
* Daniel 4:35: "Todos os povos da terra são como nada diante dele. Ele age como lhe agrada com os exércitos dos céus e com os habitantes da terra. Ninguém é capaz de resistir à sua mão nem de questioná-lo: 'O que você está fazendo?'" Este versículo destaca a soberania de Deus sobre todas as nações e sua capacidade de agir como quiser com as coisas criadas.
* Miqueias 5:15: "Com fúria e ira castigarei as nações que não me obedeceram." Este versículo enfatiza que Deus pode e irá punir as nações que não obedecem seus mandamentos, mostrando sua capacidade de julgar a todos.
* Mateus 28:18: "Então Jesus aproximou-se deles e disse: 'Foi-me dada toda a autoridade no céu e na terra.'" Este versículo destaca a autoridade suprema de Jesus como Senhor e governante de todas as coisas, enfatizando sua soberania sobre todas as nações e poder de julgar.
****

[[v33-26-1]]

^<<v33-26-1,1>>^ No ano undécimo (do cativeiro), no primeiro do mês foi-me dirigida a palavra do Senhor, nestes termos:

[[v33-26-2]]

^<<v33-26-2,2>>^ Filho de homem, porque Tiro disse de Jerusalém: É bem feito! Foi quebrada a porta dos povos! Volta-se para mim! Vou-me encher (com os despojos) dela que ficou devastada!

[[v33-26-3]]

^<<v33-26-3,3>>^ por isso assim fala o Senhor Deus: Eis que vou contra ti, ó Tiro! Farei subir contra a ti muitas nações, como o mar faz subir as suas ondas quando se encrespa.

[[v33-26-4]]

^<<v33-26-4,4>>^ Elas destruirão os muros de Tiro e deitarão abaixo suas torres, Até o pó varrerei dela, torná-la-ei como uma pedra lisa.

[[v33-26-5]]

^<<v33-26-5,5>>^ Virá a ser no meio do mar como um enxugadouro das redes sou eu que o declaro, diz o Senhor Deus será presa das nações.

[[v33-26-6]]

^<<v33-26-6,6>>^ As suas filhas, que estão no campo, serão também passadas ao fio da espada. E saber-se-á que eu sou o Senhor.

[[v33-26-7]]

^<<v33-26-7,7>>^ Eis o que diz o Senhor Deus: Vou fazer vir, das partes do setentrião contra Tiro, a Nabucodonosor, rei de Babilônia, rei dos reis, com cavalos, carros, cavalaria e grande multidão de tropa.

[[v33-26-8]]

^<<v33-26-8,8>>^ Ele fará cair a golpes dá espada as tuas filhas, que estão no campo, por-te-á cerco, erguerá plataformas, levantará o escuro contra ti.

[[v33-26-9]]

^<<v33-26-9,9>>^ Disporá contra os teus muros os seus aríetes e destruirá as tuas torres com as suas máquinas de guerra.

[[v33-26-10]]

^<<v33-26-10,10>>^ A multidão dos seus cavalos te cobrirá de pó; ao estrondo da sua cavalaria, das rodas e dos carros, tremerão as tuas muralhas, quando ele entrar pelas tuas portas, como quem entra numa cidade destruída.

[[v33-26-11]]

^<<v33-26-11,11>>^ Com os cascos dos seus cavalos pisará todas as tuas ruas; passará o teu povo à espada, e cairão por terra as tuas imponentes estátuas.

[[v33-26-12]]

^<<v33-26-12,12>>^ Saquearão todas as tuas riquezas, pilharão as tuas mercadorias, demolirão as tuas muralhas, destruirão as tuas magníficas casas e lançarão ao meio das águas as tuas pedras, as tuas madeiras e o teu pó.

[[v33-26-13]]

^<<v33-26-13,13>>^ Farei cessar o ruído dos teus cantares, e não se ouvirá mais em ti o som das tuas citaras.

[[v33-26-14]]

^<<v33-26-14,14>>^ Tornar-te-ei como uma pedra nua, virás a ser um enxugadouro de redes, e não tomarás a ser edificada sou eu que o declaro, diz o Senhor Deus.

[[v33-26-15]]

^<<v33-26-15,15>>^ Assim fala o Senhor Deus a Tiro: Porventura não tremerão as ilhas ao estrondo da tua ruína, quando gemerem os teus feridos, quando no meio de ti se fizer a carnificina?

[[v33-26-16]]

^<<v33-26-16,16>>^ Todos os príncipes do mar descerão dos seus tronos e deporão os seus mantos, arrojarão de de si as suas vestes bordadas; revestir-se-ão de terror, sentar-se-ão na terra, e, atônitos com o teu caso, tremerão sem cessar.

[[v33-26-17]]

^<<v33-26-17,17>>^ Fazendo uma lamentação sobre ti. dirão: Como pereceste, tu que habitas no mar, ó cidade célebre, que tens sido poderosa no mar com os teus habitantes, a quem todos temiam!

[[v33-26-18]]

^<<v33-26-18,18>>^ Agora tremem as ilhas no dia da tua queda, ficam turbadas as ilhas do mar, vendo o teu destino.

[[v33-26-19]]

^<<v33-26-19,19>>^ Eis o que diz o Senhor Deus: Quando te tiver reduzido a uma cidade deserta, como as cidades que não são habitadas, quando tiver feito vir sobre ti o abismo (as ondas do mar), e te tiver coberto um dilúvio do águas,

[[v33-26-20]]

^<<v33-26-20,20>>^ precipitar-te-ei com aqueles que descem ao sepulcro, para te juntar aos mortos antigos, colocar-te-ei no fundo da terra, nas solidões eternas, com os que foram conduzidos ao túmulo, a fim de ficares para sempre desabitada, quando eu tiver ornado de esplendor a terra dos viventes.

[[v33-26-21]]

^<<v33-26-21,21>>^ Tornar-te-ei um objecto de terror, e tu não existirás mais. Ainda que te busquem, nunca mais te acharão, diz o Senhor Deus.

'''

xref:033-ezequiel/033-ezequiel-025.adoc#v33-25-0[&#60; Capítulo Anterior] | <<v33-26-0,Topo>> | xref:033-ezequiel/033-ezequiel-027.adoc#v33-27-0[Próximo Capítulo &#62;]