include::./index.adoc[]

[[v33-44-0]]
=== Ezequiel, 44
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Ezequiel 44 é um capítulo que trata sobre a restauração do templo e do serviço de adoração a Deus. Neste capítulo, Deus fala sobre a importância de ter sacerdotes fiéis e santos, que cumpram as suas funções de forma adequada e respeitem as suas leis. Também é mencionado o papel dos levitas, que ajudam os sacerdotes nas suas tarefas. A seguir, cinco versículos relacionados com os temas abordados em Ezequiel 44:
* Levítico 10:10-11: "Para que façais a diferença entre o santo e o profano e entre o impuro e o limpo. E para que ensineis aos filhos de Israel todos os estatutos que o Senhor lhes tem falado por meio de Moisés." Este versículo fala sobre a importância de distinguir entre o que é santo e o que é profano, e ensinar os mandamentos de Deus aos filhos de Israel.
* 1 Pedro 2:9: "Mas vós sois a geração eleita, o sacerdócio real, a nação santa, o povo adquirido, para que anuncieis as virtudes daquele que vos chamou das trevas para a sua maravilhosa luz." Este versículo fala sobre o papel dos cristãos como sacerdotes, que foram chamados para anunciar as virtudes de Deus e viver uma vida santa.
* 1 Timóteo 4:14: "Não desprezes o dom que há em ti, o qual te foi dado por profecia, com a imposição das mãos do presbitério." Este versículo fala sobre a importância de reconhecer e utilizar os dons espirituais que Deus nos deu, para servir ao seu povo e cumprir a sua vontade.
* 2 Crônicas 29:34: "Porém, os sacerdotes eram poucos e não podiam esfolar todos os holocaustos; pelo que seus irmãos, os levitas, os ajudaram, até que a obra se acabou, e até que outros sacerdotes se santificaram, porque os levitas foram mais retos de coração para se santificarem do que os sacerdotes." Este versículo fala sobre o papel dos levitas em ajudar os sacerdotes nas suas tarefas, e como eles eram mais cuidadosos em se santificar do que os próprios sacerdotes.
* Hebreus 7:26-27: "Porque nos convinha tal sumo sacerdote, santo, inocente, imaculado, separado dos pecadores e feito mais sublime do que os céus; que não necessita, como os sumos sacerdotes, de oferecer cada dia sacrifícios, primeiro por seus próprios pecados, e depois pelos do povo; porque isto fez ele uma vez, oferecendo-se a si mesmo." Este versículo fala sobre Jesus Cristo como o nosso sumo sacerdote perfeito, que ofereceu a si mesmo como sacrifício pelos nossos pecados e nos reconciliou com Deus.
****

[[v33-44-1]]

^<<v33-44-1,1>>^ Fez-me voltar depois para o pórtico exterior do santuário que olhava para o oriente, o qual estava fechado.

[[v33-44-2]]

^<<v33-44-2,2>>^ O Senhor disse-me; Este pórtico estará fechado: não se abrirá, ninguém passará por ele, porque o Senhor Deus de Israel por aí passou: ficará fechado.

[[v33-44-3]]

^<<v33-44-3,3>>^ Porém o príncipe, como príncipe sentar-se-à nele para comer o pão diante do Senhor; mas entrará pelo caminho do vestíbulo do pórtico, e pelo mesmo caminho sairá.

[[v33-44-4]]

^<<v33-44-4,4>>^ Levou-me pelo pórtico do setentrião, diante do templo; olhei e vi que a glória do Senhor enchia a casa do Senhor; (ao ver isto) prostrei-me sobre o meu rosto.

[[v33-44-5]]

^<<v33-44-5,5>>^ E o Senhor disse-me: Filho de homem, considera no teu coração, olha com os teus olhos e ouve com os teus ouvidos todas as coisas que te disser acerca de todas as ordenações da casa do Senhor. de todos os seus regulamentos; aplica o teu coração a conhecer como entrar no templo e a conhecer também todas as saídas do santuário.

[[v33-44-6]]

^<<v33-44-6,6>>^ Dirás à casa de Israel, a estes rebeldes: Assim fala o Senhor Deus: Bastem-vos já, casa de Israel, todas as vossas maldades:

[[v33-44-7]]

^<<v33-44-7,7>>^ introduzistes filhos estrangeiros, incircuncidados de coração e incircuncidados de carne, para estarem no meu santuário, profanando a minha casa, quando oferecíeis os meus pães. a gordura e o sangue, quebrando assim, o meu pacto com todas as vossas abominações.

[[v33-44-8]]

^<<v33-44-8,8>>^ Não observastes as leis do meu santuário estabelecestes (estes incircuncidados) para fazer o meu serviço no meu santuário, em lugar de vós (violando deste modo os preceitos divinos).

[[v33-44-9]]

^<<v33-44-9,9>>^ Isto diz o Senhor Deus: Nenhum estrangeiro, incircuncidado de coração e incircuncidado de carne, entrará no meu santuário, nenhum filho de estrangeiro, que viva no meio dos filhos de Israel.

[[v33-44-10]]

^<<v33-44-10,10>>^ Até os levitas, que se apartaram de mim, entregando-se ao erro dos filhos de Israel, quando estes se desencaminharam, desando-me a mim para irem atrás dos seus ídolos, suportarão o castigo da sua iniquidade.

[[v33-44-11]]

^<<v33-44-11,11>>^ Serão no meu santuário simples porteiros guardas das portas da casa e seus serventes; matarão os (animais destinados aos) holocaustos e sacrifícios pelo povo, e estarão na sua presença para o servir.

[[v33-44-12]]

^<<v33-44-12,12>>^ Visto que lhe prestaram o seu ministério na presença dos seus ídolos, e foram para a casa de Israel uma ocasião de escândalo e de iniquidade, por isso levantei a minha mão contra eles, diz o Senhor Deus, e eles levarão o peso da sua iniquidade.

[[v33-44-13]]

^<<v33-44-13,13>>^ Não mais se aproximarão de mim, para exercer as funções do sacerdócio na minha presença nem para tocar nas coisas santas, no lugar santíssimo, mas levarão sobre si a sua confusão e o castigo das maldades que cometeram.

[[v33-44-14]]

^<<v33-44-14,14>>^ Constituí-los-ei (simples) guardas da casa e seus serventes, para tudo o que nela for preciso fazer.

[[v33-44-15]]

^<<v33-44-15,15>>^ Porém aqueles sacerdotes levíticos., filhos de Sadoc, que guardaram as ordenações do meu santuário, quando os filhos de Israel se desencaminharam de mim, esses aproximar-se-ão de mim para me servirem de ministros, estarão na minha presença para me oferecerem a gordura e o sangue, diz o Senhor Deus.

[[v33-44-16]]

^<<v33-44-16,16>>^ Esses é que entrarão no meu santuário, que se aproximarão da minha mesa, para o meu serviço, observando as minhas ordenações.

[[v33-44-17]]

^<<v33-44-17,17>>^ Quando eles entrarem nas portas do átrio interior, estarão vestidos de roupas de linho; não terão nada sobre si que seja de lã, quando exercerem as funções do seu ministério nos pórticos do átrio interior e dentro.

[[v33-44-18]]

^<<v33-44-18,18>>^ Terão turbantes de linho na cabeça, e calções de linho sobre os rins; não se cingirão de modo a excitar o suor.

[[v33-44-19]]

^<<v33-44-19,19>>^ Quando saírem ao átrio exterior (para irem) ao povo. tirarão os hábitos com que tiverem exercido o seu ministério e depô-los-ão nas câmaras do santuário; vestirão outros hábitos, para não santificarem o povo com as suas vestes (sagradas).

[[v33-44-20]]

^<<v33-44-20,20>>^ Não raparão a cabeça, nem deixarão crescer livremente o cabelo, mas terão cuidado de o cortar.

[[v33-44-21]]

^<<v33-44-21,21>>^ Nenhum sacerdote bebei-á vinho., quando tiver de entrar no átrio interior.

[[v33-44-22]]

^<<v33-44-22,22>>^ Não se casarão, nem com viúva nem com repudiada, mas com donzelas de linhagem da casa de Israel; poderão todavia casar com uma viúva doutro sacerdote.

[[v33-44-23]]

^<<v33-44-23,23>>^ Ensinarão ao meu povo a diferença que há entre o santo e o profano, entre o puro e o impuro.

[[v33-44-24]]

^<<v33-44-24,24>>^ Quando se levantar alguma controvérsia, prestar-se-ão a decidi-la; julgarão segundo o direito que estabeleci. Observarão as minhas leis e os meus preceitos, em todas as minhas solenidades, e santificai'ão os meus sábados.

[[v33-44-25]]

^<<v33-44-25,25>>^ Não se aproximarão dum cadáver, para que se não manchem excepto se for pai ou mãe, filho ou filha, irmão ou irmã que não tenha marido.

[[v33-44-26]]

^<<v33-44-26,26>>^ Depois que qualquer deles tiver sido purificado, contar-se-lhe-ão sete dias.

[[v33-44-27]]

^<<v33-44-27,27>>^ No dia em que entrar no santuário, no átrio, interior, para exercer o seu ministério no santuário oferecerá um sacrifício pelo seu pecado, diz o Senhor Deus.

[[v33-44-28]]

^<<v33-44-28,28>>^ (Os sacerdotes) não terão herança, porque eu é que sou a sua herança; não lhes dareis quinhão em Israel, porque eu é que sou o seu quinhão.

[[v33-44-29]]

^<<v33-44-29,29>>^ Alimentar-se-ão das oblações e das vítimas que forem oferecidas, tanto pelo pecado como pelo delito, tudo o que for consagrado em Israel, será deles.

[[v33-44-30]]

^<<v33-44-30,30>>^ As primícias de todos os primogênitos e todas as oferendas de qualquer espécie pertencerão aos sacerdotes; dareis também ao sacerdote as primícias dos vossos alimentos,, para que repouse a bênção sobre a vossa casa.

[[v33-44-31]]

^<<v33-44-31,31>>^ Os sacerdotes não comerão nada de ave, nem de outro animal, que por si tenham morrido, ou que tenham sido despedaçados.

'''

xref:033-ezequiel/033-ezequiel-043.adoc#v33-43-0[&#60; Capítulo Anterior] | <<v33-44-0,Topo>> | xref:033-ezequiel/033-ezequiel-045.adoc#v33-45-0[Próximo Capítulo &#62;]