include::./index.adoc[]

[[v33-29-0]]
=== Ezequiel, 29
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Ezequiel 29 contém uma mensagem de julgamento contra o faraó e o Egito por terem se oposto ao povo de Deus. O capítulo começa com uma declaração de Deus de que Ele está contra o faraó e contra o Egito e termina com uma promessa de restauração para o povo de Israel. Os versículos a seguir fornecem uma ampliação do contexto histórico e das implicações do julgamento de Deus sobre o Egito:
* Isaías 31:1: "Ai dos que descem ao Egito a buscar socorro, e se estribam em cavalos; e têm confiança em carros, porque são muitos; e nos cavaleiros, porque são poderosíssimos; e não atentam para o Santo de Israel, e não buscam ao Senhor!" Este versículo adverte o povo de Deus contra buscar ajuda no Egito em vez de confiar em Deus. A mensagem de julgamento em Ezequiel 29 é uma consequência direta dessa falta de confiança em Deus.
* Êxodo 7:5: "E os egípcios saberão que eu sou o Senhor, quando estender a minha mão sobre o Egito, e tirar os filhos de Israel do meio deles." Deus promete libertar os filhos de Israel do Egito e mostrar seu poder sobre os deuses do Egito. A mensagem de julgamento em Ezequiel 29 é um cumprimento dessa promessa.
* Isaías 19:1: "Peso do Egito. Eis que o Senhor cavalga sobre uma nuvem ligeira, e entra no Egito; e os ídolos do Egito estremecerão diante dele, e o coração dos egípcios se derreterá no meio deles." Este versículo descreve a chegada de Deus ao Egito para julgamento. A mensagem de Ezequiel 29 é um exemplo dessa justiça divina.
* Jeremias 46:25: "O Senhor dos Exércitos, Deus de Israel, disse: Eis que eu trarei castigo sobre Amom de No, e sobre Faraó, e sobre o Egito, juntamente com os seus deuses, e os seus reis; sim, sobre Faraó, e sobre os que nele confiam." Este versículo prediz o julgamento de Deus sobre o Egito e seus deuses. A mensagem de Ezequiel 29 é uma confirmação desse julgamento.
* Oséias 9:3: "Eles não habitarão na terra do Senhor; mas voltará Efraim ao Egito, e comerão em Assíria comida impura." Este versículo profetiza a dispersão do povo de Israel e sua subsequente volta ao Egito. A mensagem de Ezequiel 29 é uma resposta a essa ação e uma afirmação da soberania de Deus sobre todas as nações, incluindo o Egito.
****

[[v33-29-1]]

^<<v33-29-1,1>>^ No ano décimo, no décimo mês, aos doze dias do mês, foi-me dirigida a palavra do Senhor, nestes termos:

[[v33-29-2]]

^<<v33-29-2,2>>^ Filho de homem, volta o teu rosto contra Faraó, rei do Egipto, e profetiza contra ele e contra o Egipto.

[[v33-29-3]]

^<<v33-29-3,3>>^ Fala e dize: Isto diz o Senhor Deus; Eis que venho contra ti, ó Faraó, rei do Egipto, crocodilo enorme, que te deitas no meio dos teus rios e que dizes: O rio (Nilo), é meu, fui eu que o fiz.

[[v33-29-4]]

^<<v33-29-4,4>>^ Pôr-te-ei um freio nos queixos, colarei os peixes dos teus rios às tuas escamas, e te tirarei do meio dos teus rios, assim como todos os peixes dos teus rios, pegados às tuas escamas.

[[v33-29-5]]

^<<v33-29-5,5>>^ Lançar-te-ei para o deserto com todos os peixes do teu rio; cairás sobre a face da terra, e não te recolherão nem sepultarão; dar-te-ei por pasto aos animais da terra e às aves do céu.

[[v33-29-6]]

^<<v33-29-6,6>>^ e todos os habitantes do Egipto saberão que eu sou o Senhor, porque tu foste para a casa de Israel um apoio (frágil) de cana. (ver nota)

[[v33-29-7]]

^<<v33-29-7,7>>^ Quando eles te tomaram na mão, quebraste, e lhes rasgaste todo o ombro; quando eles se apoiaram sobre ti. tu te partiste em pedaços e fizeste vacilar todos os seus rins.

[[v33-29-8]]

^<<v33-29-8,8>>^ Portanto isto diz o Senhor Deus: Vou fazer cair a espada sobre ti e exterminar do teu seio os homens e os animais.

[[v33-29-9]]

^<<v33-29-9,9>>^ A terra do Egipto será reduzida a um deserto e a uma solidão, e saber-se-á que eu sou o Senhor. Porque tu disseste; O rio é meu, eu é que o fiz

[[v33-29-10]]

^<<v33-29-10,10>>^ por isso, eis-me aqui contra ti e contra os teus rios; transformarei a terra do Egipto num deserto e numa solidão, desde Mígdol até Siene, até aos confins da Etiópia.

[[v33-29-11]]

^<<v33-29-11,11>>^ Não passará por ela pé de homem, nem andará nela pé de animal; não será habitada durante quarenta anos.

[[v33-29-12]]

^<<v33-29-12,12>>^ Farei do país do Egipto um deserto, no meio de outros países desertos, e as suas cidades ficarão destruídas no meio de outras cidades destruídas, estarão desoladas durante quarenta anos; espalharei por diversas nações os Egípcios, disseminá-los-ei por várias terras.

[[v33-29-13]]

^<<v33-29-13,13>>^ Porque isto diz o Senhor Deus: Ao fim de quarenta anos, juntarei os Egípcios do meio dos povos, entre os quais tinham sido espalhados;

[[v33-29-14]]

^<<v33-29-14,14>>^ tornarei a trazer os cativos do Egipto e estabelecê-los-ei na terra de Patros, na terra da sua nascença, onde formarão um reino humilde. (ver nota)

[[v33-29-15]]

^<<v33-29-15,15>>^ (O Egipto) será o mais humilde de todos os reinos, e não se tornará mais a levantar sobre as outras nações; diminui-los-ei, para que não dominem sobre elas.

[[v33-29-16]]

^<<v33-29-16,16>>^ Não serão mais motivo de confiança para a casa de Israel, recordarão a falta cometida por Israel em os seguir, e saber-se-á que eu sou o Senhor Deus.

[[v33-29-17]]

^<<v33-29-17,17>>^ No ano vinte e sete, no primeiro dia do primeiro mês, foi-me dirigida a palavra do Senhor, nestes termos;

[[v33-29-18]]

^<<v33-29-18,18>>^ Filho de homem, Nabucodonosor, rei de Babilónia, fatigou muito o seu exército na guerra contra Tiro: todas as cabeças ficaram calvas, e todos os ombros maltratados. Contudo, nem a ele, nem ao seu exército foi dada recompensa alguma pelo serviço realizado contra Tiro.

[[v33-29-19]]

^<<v33-29-19,19>>^ Portanto isto diz o Senhor Deus; Vou dar a Nabucodonosor, rei de Babilônia, o país do Egipto: levará as suas riquezas, fará dele a sua presa, repartirá os seus despojos: esta será a recompensa do’ seu exército.

[[v33-29-20]]

^<<v33-29-20,20>>^ Pelo serviço que prestou contra Tiro. dou-lhe o país do Egipto, porque ele trabalhou para mim, diz o Senhor Deus.

[[v33-29-21]]

^<<v33-29-21,21>>^ Nesse dia farei brotar um chifre (ou poderio) à casa de Israel, e abrir-te-ei a boca no meio deles. E saberão que eu sou o Senhor.

'''

xref:033-ezequiel/033-ezequiel-028.adoc#v33-28-0[&#60; Capítulo Anterior] | <<v33-29-0,Topo>> | xref:033-ezequiel/033-ezequiel-030.adoc#v33-30-0[Próximo Capítulo &#62;]