include::./index.adoc[]

[[v33-20-0]]
=== Ezequiel, 20
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Ezequiel 20 aborda a rebeldia do povo de Israel ao longo da história e como Deus lidou com essa situação. Os versículos selecionados abaixo estão relacionados com a punição divina e a busca de arrependimento por parte do povo:
* Jeremias 21:12: "Ó casa de Davi, assim diz o SENHOR: Executai justiça pela manhã e livrai o oprimido das mãos do opressor, para que o meu furor não saia como fogo e arda, sem que haja quem o apague, por causa da maldade das vossas obras." Este versículo reforça a ideia de que a justiça deve ser praticada e que Deus pune aqueles que cometem injustiças.
* Isaías 55:6-7: "Buscai o SENHOR enquanto se pode achar, invocai-o enquanto está perto. Deixe o ímpio o seu caminho, e o homem maligno os seus pensamentos, e se converta ao SENHOR, que se compadecerá dele; torne para o nosso Deus, porque grandioso é em perdoar." Aqui, é enfatizada a importância de buscar a Deus e abandonar o pecado, mostrando que Deus está disposto a perdoar aqueles que se arrependem.
* Salmo 81:11-12: "Mas o meu povo não quis ouvir a minha voz, e Israel não me quis. Portanto, entreguei-os aos desejos dos seus corações, e andaram nos seus próprios conselhos." Este salmo ilustra como Deus permitiu que as pessoas seguissem seus próprios desejos e sofreram as consequências de suas escolhas.
* Isaías 5:24: "Portanto, como a língua de fogo consome a palha, e o restolho se desfaz pela chama, assim será a sua raiz como podridão, e a sua flor se desvanecerá como pó; porquanto rejeitaram a lei do SENHOR dos Exércitos, e desprezaram a palavra do Santo de Israel." Esse versículo destaca que aqueles que rejeitam a lei de Deus acabam sendo consumidos pela sua própria maldade.
* Oséias 14:1: "Volta, ó Israel, para o SENHOR teu Deus, porque pelos teus pecados tens caído." Aqui, vemos um apelo para que o povo se arrependa e volte a Deus, reconhecendo que suas próprias escolhas os levaram à queda.
****

[[v33-20-1]]

^<<v33-20-1,1>>^ No ano sétimo, no quinto mês, aos dez dias do mês, vieram alguns dos anciães de Israel consultar, o Senhor e sentaram-se diante de mim.

[[v33-20-2]]

^<<v33-20-2,2>>^ Foi-me dirigida a palavra do Senhor, nos termos seguintes:

[[v33-20-3]]

^<<v33-20-3,3>>^ Filho de homem, fala assim aos anciães de Israel: Isto diz o Senhor Deus: Porventura viestes vós a consultar-me? (Juro) pela minha vida, que não vos responderei, diz o Senhor Deus.

[[v33-20-4]]

^<<v33-20-4,4>>^ Se tu os julgas, filho de homem, se tu os julgas, põe-lhes diante dos olhos as abominações de seus pais.

[[v33-20-5]]

^<<v33-20-5,5>>^ Dir-lhes-ás; Isto diz o Senhor Deus : No dia em que escolhi Israel, em que levantei a minha mão em favor da casa de Jacob e me dei a conhecer na terra do Egipto, em que levantei a minha mão a favor deles, dizendo: Eu sou o Senhor vosso Deus

[[v33-20-6]]

^<<v33-20-6,6>>^ nesse dia levantei a minha mão em seu favor, jurando transferi-los da terra do Egipto para a terra que lhes tinha preparado, a qual mana leite e mel, a mais excelente de todas as terras.

[[v33-20-7]]

^<<v33-20-7,7>>^ Disse-lhes então: Cada um afaste de si os ídolos sedutores dos seus olhos; não vos mancheis com os ídolos do Egipto; eu sou o Senhor vosso Deus.

[[v33-20-8]]

^<<v33-20-8,8>>^ Eles, porém, revoltaram-se contra mim, não me quiseram ouvir; nenhum lançou fora os abomináveis ídolos sedutores. dos seus olhos; não abandonaram os ídolos do Egipto. Pensei derramar a minha indignação sobre eles, saciar neles a minha ira no meio da terra do Egipto;

[[v33-20-9]]

^<<v33-20-9,9>>^ porém procedi (de outra forma) por amor do meu nome, para que ele não ficasse desacreditado diante das gentes, no melo das quais estavam, entre as quais me tinha dado a conhecer, para os tirar da terra do Egipto.

[[v33-20-10]]

^<<v33-20-10,10>>^ Tirei-os, pois, da terra do Egipto e conduzi-os ao deserto.

[[v33-20-11]]

^<<v33-20-11,11>>^ Dei-lhes os meus preceitos, ensinei-lhes as minhas leis, em cuja observância o homem encontrará a vida.

[[v33-20-12]]

^<<v33-20-12,12>>^ Além disto, dei-lhes os meus sábados, para que fossem um sinal entre mim e eles e para que soubessem que eu sou o Senhor que os santifico.

[[v33-20-13]]

^<<v33-20-13,13>>^ Mas, (depois de tudo isto) os filhos da casa de Israel irritaram-me no deserto, não andaram nos meus preceitos, rejeitaram as minhas leis, que dão vida ao que as observa, e profanaram inteiramente os meus sábados. Resolvi, pois, derramar o meu furor sobre eles no deserto e exterminá-los.

[[v33-20-14]]

^<<v33-20-14,14>>^ Mas, por amor do meu nome, procedi (de outra forma) de modo que ele não ficasse desacreditado diante das gentes, aos olhos das, quais eu os tinha feito sair,

[[v33-20-15]]

^<<v33-20-15,15>>^ Também levantei a minha mão contra eles no deserto, jurando não os introduzir na terra que lhes dei, a qual mana leite e mel, á melhor de todas as terras

[[v33-20-16]]

^<<v33-20-16,16>>^ porque eles rejeitaram as minhas leis. não andaram nos meus preceitos, profanaram os meus sábados, pois o seu coração ia após os ídolos.

[[v33-20-17]]

^<<v33-20-17,17>>^ Todavia olhei para eles com olhos de misericórdia, para os não matar, e (de facto) não os exterminei no deserto.

[[v33-20-18]]

^<<v33-20-18,18>>^ Disse a seus filhos no deserto: Não sigais os exemplos de vossos pais, não Imiteis os seus costumes, não vos mancheis com os seus ídolos.

[[v33-20-19]]

^<<v33-20-19,19>>^ Eu sou o Senhor vosso Deus; andai nos meus preceitos, guardai as minhas leis e praticai-as.

[[v33-20-20]]

^<<v33-20-20,20>>^ Santificai os meus sábados, para que eles sejam um sinal entre mim e vós, e para que se saiba que eu sou o Senhor vosso Deus.

[[v33-20-21]]

^<<v33-20-21,21>>^ Porém os filhos revoltaram-se contra mim. não andaram segundo os meus preceitos, não guardaram nem puseram em prática as minhas leis, que o homem deve cumprir para viver, e profanaram os meus sábados. Planeei derramar o meu furor sobre eles, satisfazer a minha ira contra eles no deserto.

[[v33-20-22]]

^<<v33-20-22,22>>^ Mas desviei a minha mão, o que fiz por causa do meu nome, para que ele não fosse profanado diante das gentes, aos olhos das quais eu os tinha feito sair.

[[v33-20-23]]

^<<v33-20-23,23>>^ Tornei outra vez a levantar a minha mão contra eles no deserto, jurando espalhá-los por entre as nações, disseminá-los por países estrangeiros,

[[v33-20-24]]

^<<v33-20-24,24>>^ visto não terem observado as minhas leis, haverem rejeitado os meus preceitos, profanado os meus sábados, e terem-se-lhes ido os olhos após os ídolos de seus pais.

[[v33-20-25]]

^<<v33-20-25,25>>^ Por isso cheguei mesmo a dar-lhes preceitos não bons, leis nas quais não podiam achar a vida.

[[v33-20-26]]

^<<v33-20-26,26>>^ Tornei-os impuros pelas suas oblações, quando faziam sacrificar os seus primogênitos (a Moloch) para os punir, a fim de que soubessem que eu sou o Senhor.

[[v33-20-27]]

^<<v33-20-27,27>>^ Portanto fala à casa de Israel, filho de homem, desta maneira: Isto diz o Senhor Deus: Ainda depois disto me ultrajaram vossos pais, sendo-me infiéis.

[[v33-20-28]]

^<<v33-20-28,28>>^ Quando os introduzi na terra, que com juramento tinha prometido dar-lhes, olharam para todos os outeiros elevados e para todas as árvores frondosas, e ali fizeram os seus sacrifícios, apresentaram as suas oferendas que me irritavam, ali trouxeram os seus agradáveis perfumes e ofereceram as suas libações.

[[v33-20-29]]

^<<v33-20-29,29>>^ Disse-lhes então: Que lugar alto é este aonde vós Ides? E até ao dia de hoje lhe ficou o nome de lugar alto.

[[v33-20-30]]

^<<v33-20-30,30>>^ Portanto dize à casa de Israel: Assim fala o Senhor Deus: É verdade que vos tornais imundos, segundo os caminhos de vossos pais, e vos entregais à mesma prostituição com os seus ídolos (ou idolatria).

[[v33-20-31]]

^<<v33-20-31,31>>^ Na oblação dos vossos dons (a Moloch), quando fazeis passar o.s vossos filhos pelo fogo. vós vos contaminais com todos os vossos ídolos até hoje. E (depois disto) deixar-me-ei ainda consultar por vós, casa de Israel? (Juro) pela minha vida, diz o Senhor Deus. que o não farei.

[[v33-20-32]]

^<<v33-20-32,32>>^ Nem se efectuará o que pensais no vosso espirito quando dizeis: Seremos (felizes) como as nações e como os povos da terra, adorando os paus e as pedras.

[[v33-20-33]]

^<<v33-20-33,33>>^ Juro pela minha vida. diz o Senhor Deus, que reinarei sobre vós com mão forte, com braço estendido, na efusão do meu furor.

[[v33-20-34]]

^<<v33-20-34,34>>^ Tirar-vos-ei do meio dos povos e vos juntarei dos países, para onde tínheis sido dispersos, com mão forte, com braço estendido, com efusão do meu furor,

[[v33-20-35]]

^<<v33-20-35,35>>^ e vos levarei ao deserto dos povos e lá entrarei em juízo convosco, cara a cara. (ver nota)

[[v33-20-36]]

^<<v33-20-36,36>>^ Assim como entrei em juízo com vossos pais no deserto da terra do Egipto, assim vos julgarei a vós. diz o Senhor Deus.

[[v33-20-37]]

^<<v33-20-37,37>>^ E vos submeterei ao meu ceptro, e vos farei entrar nos laços da minha aliança.

[[v33-20-38]]

^<<v33-20-38,38>>^ E separarei dentre vós os rebeldes, os que se revoltaram contra mim, e os farei sair da terra em que habitam como estrangeiros; porém não entrarão na terra de Israel, e vós sabereis que eu é que sou o Senhor.

[[v33-20-39]]

^<<v33-20-39,39>>^ A vós, casa de Israel, isto diz o Senhor Deus: Cada um de vós vá servir os seus ídolos. Porém, depois disto, com certeza me ouvireis e não profanareis mais o meu santo nome com as vossas oferendas e com os vosso ídolos. (ver nota)

[[v33-20-40]]

^<<v33-20-40,40>>^ (Eu sei que) sobre o meu santo monte sobre o alto monte de Israel, diz o Senhor Deus, ali me servirá toda a casa de Israel, toda ela estabelecida na terra; ali (os filhos de Israel) me serão agradáveis, ali requererei as vossas oferendas e as primícias dos vossos dons com tudo o que me consagrardes.

[[v33-20-41]]

^<<v33-20-41,41>>^ Então vos receberei como um perfume agradável quando vos tiver tirado do meio dos povos e vos tiver juntado dos países, por onde tínheis sido espalhados; e tornar-se-á manifesta em vós a minha santidade aos olhos das nações.

[[v33-20-42]]

^<<v33-20-42,42>>^ E sabereis que eu é que sou o Senhor, quando vos introduzir na terra de Israel, na terra que jurei, de mão levantada, dar a vossos pais.

[[v33-20-43]]

^<<v33-20-43,43>>^ Ali vos lembrareis dos vossos caminhos e de todas as maldades com as quais vos manchastes, e vos desagradareis de vós mesmos, à vista de todas as maldades que cometestes.

[[v33-20-44]]

^<<v33-20-44,44>>^ Então sabereis, casa de Israel, que eu é que sou o Senhor, quando eu proceder convosco (benignamente) por amor do meu nome, em vez de vos tratar conforme os vossos maus caminhos e os vossos detestáveis pecados, diz o Senhor Deus.

[[v33-20-45]]

^<<v33-20-45,45>>^ Foi-me dirigida a palavra do Senhor, nestes termos:

[[v33-20-46]]

^<<v33-20-46,46>>^ Filho de homem, volta o rosto para meio-dia fala para o sul, profetiza contra a floresta do meio-dia.

[[v33-20-47]]

^<<v33-20-47,47>>^ Dirás à floresta do meio-dia: Ouve a palavra do Senhor: Isto diz o Senhor Deus: Eis que vou acender em ti um fogo que queimará em ti todo o lenho verde e todo o lenho seco; não se apagará a chama deste Incêndio, e queimar-se-á nela todo o rosto, desde o meio-dia até ao aquilão.

[[v33-20-48]]

^<<v33-20-48,48>>^ Toda a carne verá que eu, o Senhor, lancei o fogo. o qual se não apagará.

[[v33-20-49]]

^<<v33-20-49,49>>^ Então eu disse: Ah! Senhor Deus! Eles dizem isto de mim: Este não nos fala, senão por parábolas (obscuras)

'''

xref:033-ezequiel/033-ezequiel-019.adoc#v33-19-0[&#60; Capítulo Anterior] | <<v33-20-0,Topo>> | xref:033-ezequiel/033-ezequiel-021.adoc#v33-21-0[Próximo Capítulo &#62;]