include::./index.adoc[]

[[v16-13-0]]
=== Neemias, 13
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Neemias 13 narra o retorno de Neemias a Jerusalém após um tempo afastado. Ele encontra muitas coisas erradas acontecendo, como a violação do sábado, a mistura de casamentos com os povos vizinhos e a negligência no sustento dos levitas. Neemias toma medidas drásticas para corrigir esses problemas e restaurar a santidade do povo de Deus. Abaixo estão cinco versículos relacionados com os temas abordados neste capítulo:
* Esdras 10:11: "Agora, pois, fazei confissão ao SENHOR, Deus de vossos pais, e fazei a sua vontade; e separai-vos dos povos desta terra e das mulheres estrangeiras." Este versículo se relaciona com a preocupação de Neemias com a mistura de casamentos entre os israelitas e os povos vizinhos. Ele toma medidas drásticas para separar o povo de Deus dessas influências estrangeiras e restaurar a santidade.
* Êxodo 20:8: "Lembra-te do dia do sábado, para o santificar." Neemias fica indignado ao encontrar o povo violando o sábado e toma medidas para restaurar a observância do dia de descanso como um sinal da aliança entre Deus e seu povo.
* Deuteronômio 23:21: "Quando fizeres algum voto ao SENHOR teu Deus, não tardarás em cumpri-lo; porque o SENHOR teu Deus certamente o requererá de ti, e em ti haverá pecado." Neemias descobre que os levitas não estavam sendo sustentados de acordo com a lei e toma medidas para restaurar a provisão adequada para esses servos de Deus.
* Malaquias 3:8-10: "Roubará o homem a Deus? Todavia vós me roubais, e dizeis: Em que te roubamos? Nos dízimos e nas ofertas alçadas. Com maldição sois amaldiçoados, porque me roubais, vós, toda a nação." Neemias confronta o povo pelo não pagamento dos dízimos e toma medidas para garantir que a provisão adequada seja feita para o serviço do templo.
* 1 Coríntios 5:6: "Não é boa a vossa jactância. Não sabeis que um pouco de fermento leveda toda a massa?" Neemias toma medidas drásticas para expulsar os que estão vivendo em pecado da comunidade e restaurar a pureza do povo de Deus. Este versículo destaca a importância da disciplina na igreja para preservar a santidade e o testemunho do povo de Deus.
****

[[v16-13-1]]

^<<v16-13-1,1>>^ Naquele dia leu-se no livro de Moisés na presença do povo, e achou-se escrito nele que os Amonitas e os Moabitas nunca deviam entrar na assembleia de Deus,

[[v16-13-2]]

^<<v16-13-2,2>>^ porque não tinham ido ao encontro dos filhos de Israel, com pão e água, e porque subornaram contra eles Balaão, para os amaldiçoar — maldição que o nosso Deus converteu em bênção.

[[v16-13-3]]

^<<v16-13-3,3>>^ Sucedeu que, quando ouviram a lei, separaram de Israel todos os estrangeiros.

[[v16-13-4]]

^<<v16-13-4,4>>^ Isto estava ao cuidado do sacerdote Eliasib, que tinha sido intendente do tesouro da casa do nosso Deus e que era parente de Tobias.

[[v16-13-5]]

^<<v16-13-5,5>>^ Ele havia posto à disposição deste (Tobias) uma câmara grande, no lugar onde antes se depositavam os donativos, o incenso, os vasos, os dízimos do trigo, do vinho e do azeite, as porções dos Levitas, dos cantores, dos porteiros e as primícias sacerdotais.

[[v16-13-6]]

^<<v16-13-6,6>>^ Enquanto se fazia tudo isto, eu não estava em Jerusalém, porque no ano trinta e dois de Artaxerxes, rei de Babilônia, fui ter com o rei. Ao cabo dum certo tempo, pedi licença ao rei (para voltar a Jerusalém).

[[v16-13-7]]

^<<v16-13-7,7>>^ Voltei para Jerusalém e soube do mal que Eliasib tinha cometido para servir a Tobias, cedendo-lhe um aposento nos átrios da casa de Deus.

[[v16-13-8]]

^<<v16-13-8,8>>^ O mal pareceu-me muito grande. Deitei os móveis da casa de Tobias fora do aposento,

[[v16-13-9]]

^<<v16-13-9,9>>^ e, por minha ordem, foi purificado o aposento; (depois) reconduzi para lá os vasos da casa de Deus, as oferendas e o incenso.

[[v16-13-10]]

^<<v16-13-10,10>>^ Soube também que os quinhões dos Levitas não lhes tinham sido dados, e que os Levitas, os cantores e os que serviam no templo, tinham fugido, cada qual para a sua terra.

[[v16-13-11]]

^<<v16-13-11,11>>^ Repreendi os magistrados e disse: Por que abandonamos nós a casa de Deus? Depois reuni os Levitas e os cantores, e obriguei-os a voltar às suas funções.

[[v16-13-12]]

^<<v16-13-12,12>>^ Então todo o Judá trouxe para os celeiros os dízimos do trigo, do vinho e do azeite.

[[v16-13-13]]

^<<v16-13-13,13>>^ Estabeleci por superintendentes dos celeiros a Selemias, sacerdote, a Sadoc, escriba, a Fadais, dos Levitas, e agreguei-lhes Hanan, filho de Zacur, filho de Matatias, porque tinham sido encontrados fiéis. Ficaram encarregados de fazer a distribuição das porções aos seus irmãos.

[[v16-13-14]]

^<<v16-13-14,14>>^ Lembra-te por isto de mim, ó meu Deus, e não apagues as boas obras que fiz na casa do meu Deus e nas suas cerimónias.

[[v16-13-15]]

^<<v16-13-15,15>>^ Naqueles dias vi em Judá homens, que pisavam nos lagares ao sábado, que acarretavam molhos, que carregavam sobre jumentos vinho, uvas, figos e toda a casta de fardos, que levavam a Jerusalém em dia de sábado. Ordenei-lhes expressamente que vendessem somente nos dias em que era lícito vender.

[[v16-13-16]]

^<<v16-13-16,16>>^ Havia também Tirios estabelecidos na cidade, que traziam peixe e mercadorias de toda a espécie, para vender em Jerusalém, aos filhos de Judá, nos sábados.

[[v16-13-17]]

^<<v16-13-17,17>>^ Repreendi os grandes de Judá, dizendo-lhes: Que maldade é esta que cometeis, profanando o dia de sábado?

[[v16-13-18]]

^<<v16-13-18,18>>^ Não é isto o mesmo que fizeram nossos pais, e não foi por isso que nosso Deus fez cair toda esta calamidade sobre nós e sobre esta cidade? Ides vós aumentar a sua ira sobre Israel, violando o sábado?

[[v16-13-19]]

^<<v16-13-19,19>>^ Mandei, pois, que quando descessem as sombras sobre as portas de Jerusalém, na véspera do sábado, se fechassem as mesmas portas e se não abrissem senão depois do sábado; pus alguns de meus criados às portas, para que ninguém fizesse entrar carga alguma em dia de sábado.

[[v16-13-20]]

^<<v16-13-20,20>>^ Os negociantes e os que traziam para vender toda a casta de mercadoria ficaram uma ou duas vezes fora de Jerusalém.

[[v16-13-21]]

^<<v16-13-21,21>>^ Adverti-os e disse-Ihes: Por que estais assim defronte dos muros? Se fizerdes isso outra vez, mandar-vos-ei castigar. Daquele tempo em diante, não tornaram mais no sábado.

[[v16-13-22]]

^<<v16-13-22,22>>^ Ordenei também aos Levitas que se purificassem, que fossem guardar as portas e santificar o dia de sábado. Também por isso lembra-te de mim, ó meu Deus, e perdoa-me segundo a multidão das tuas misericórdias.

[[v16-13-23]]

^<<v16-13-23,23>>^ Naqueles dias, vi Judeus que se tinham casado com mulheres de Azoto, de Amon e de Moab.

[[v16-13-24]]

^<<v16-13-24,24>>^ Metade dos seus filhos falavam língua azótica e não sabiam falar hebreu; o mesmo (que com a língua azótica) sucedia com a língua de outros povos. (ver nota)

[[v16-13-25]]

^<<v16-13-25,25>>^ E eu os repreendi e amaldiçoei. Feri alguns deles, arranquei-Ihes os cabelos e fi-los jurar por Deus que não dariam suas filhas aos filhos de estrangeiros, e não tomariam filhas estrangeiras para seus filhos nem para si mesmos.

[[v16-13-26]]

^<<v16-13-26,26>>^ Porventura, disse-lhes eu, não foi nisto mesmo que pecou Salomão, rei de Israel? Certamente não havia rei semelhante a ele entre todos os povos; ele era amado do seu Deus, e Deus tinha-o constituído rei sobre todo o Israel; contudo as mulheres estrangeiras fizeram-no cair no pecado.

[[v16-13-27]]

^<<v16-13-27,27>>^ Podemos nós ouvir dizer (e consentir) que cometeis este grande mal de tomar mulheres estrangeiras e que sois, assim, infiéis ao nosso Deus?

[[v16-13-28]]

^<<v16-13-28,28>>^ Um dos filhos de Jojada, filho de Eliasib, sumo sacerdote, era genro de Sanabalat, Horonita, a quem afastei de mim.

[[v16-13-29]]

^<<v16-13-29,29>>^ Senhor Deus meu, lembra-te de castigar aqueles que mancham o sacerdócio e o sagrado dever sacerdotal e levítico.

[[v16-13-30]]

^<<v16-13-30,30>>^ Foi assim que os purifiquei (ou separei) de todos os estrangeiros, que pus em vigor o regulamento dos sacerdotes e dos Levitas, colocando cada um no seu ministério,

[[v16-13-31]]

^<<v16-13-31,31>>^ e que restabeleci a oblação da lenha e das primícias, aos tempos devidos. Lembra-te de mim, Deus meu, para meu bem. Assim seja.

'''

xref:016-neemias/016-neemias-012.adoc#v16-12-0[&#60; Capítulo Anterior] | <<v16-13-0,Topo>> | xref:017-tobias/017-tobias-001.adoc#v17-1-0[Próximo Capítulo &#62;]