include::./index.adoc[]

[[v4-33-0]]
=== Números, 33
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 33 do livro de Números apresenta um registro dos acampamentos e jornadas dos filhos de Israel desde a sua saída do Egito até a chegada às planícies de Moabe, às margens do Jordão, como preparação para a entrada na terra prometida. Dessa forma, os versículos escolhidos serão relacionados a temas como a fidelidade de Deus em conduzir Seu povo, as consequências da desobediência, a necessidade de lembrar o passado e aprender com ele, o cumprimento das promessas divinas e a soberania de Deus sobre todas as coisas.
* Deuteronômio 1:30: "O Senhor, vosso Deus, que vai adiante de vós, ele pelejará por vós, conforme tudo o que fez convosco, diante de vossos olhos, no Egito" - Este versículo destaca a fidelidade de Deus em guiar e lutar por Seu povo, como visto no registro das jornadas em Números 33.
* Deuteronômio 1:32-33: "Mas, apesar disto, não crestes no Senhor, vosso Deus, que ia adiante de vós no caminho, buscando para vós lugar de descanso, com fogo de noite, para vos mostrar o caminho por onde havíeis de andar, e com nuvem de dia" - Esse versículo aponta para a desobediência e incredulidade do povo de Israel, que resultou em consequências como a prolongação do tempo de sua peregrinação.
* Deuteronômio 4:9: "Tão-somente guarda-te a ti mesmo e guarda bem a tua alma, para que não te esqueças daquelas coisas que os teus olhos têm visto, e para que não se apartem do teu coração todos os dias da tua vida; porém as farás saber a teus filhos e aos filhos de teus filhos" - Esse versículo enfatiza a importância de lembrar do passado e ensinar as lições aprendidas a gerações futuras.
* Deuteronômio 7:9: "Saberás, pois, que o Senhor, teu Deus, é que é Deus, o Deus fiel, que guarda a aliança e a misericórdia até mil gerações aos que o amam e guardam os seus mandamentos" - Esse versículo destaca a fidelidade de Deus em cumprir Suas promessas, como evidenciado na liderança do povo de Israel durante sua peregrinação.
* Deuteronômio 10:14-15: "Eis que dos céus e a terra são do Senhor, teu Deus; os céus são os céus do Senhor, mas a terra a deu aos filhos dos homens. Tão-somente o Senhor Se agradou de teus pais para os amar; e a vós, descendência deles, escolheu, dentre todos os povos, como hoje se vê" - Esse versículo destaca a soberania de Deus sobre todas as coisas, incluindo a escolha de Israel como Seu povo.
****

[[v4-33-1]]

^<<v4-33-1,1>>^ Estas são as paragens dos filhos de Israel, que saíram do Egito (divididos) pelas suas turmas sob a conduta de Moisés e de Aarão.

[[v4-33-2]]

^<<v4-33-2,2>>^ Moisés as descreveu, segundo os lugares dos acampamentos, que eles mudavam ao mandado do Senhor.

[[v4-33-3]]

^<<v4-33-3,3>>^ No primeiro mês, no dia quinze, ao outro dia da Páscoa, os filhos de Israel partiram de Ramessés com a mão levantada, à vista de todos os Egípcios,

[[v4-33-4]]

^<<v4-33-4,4>>^ que sepultavam os seus primogénitos, a quem o Senhor tinha ferido (até sobre os seus deuses lançou o seu castigo)

[[v4-33-5]]

^<<v4-33-5,5>>^ e foram acampar em Socoth.

[[v4-33-6]]

^<<v4-33-6,6>>^ De Socoth foram a Etam, que fica na extremidade do deserto.

[[v4-33-7]]

^<<v4-33-7,7>>^ Partindo dali, foram até defronte de Fiairoth, que olha para Beelsefon, e acamparam diante de Magdalo.

[[v4-33-8]]

^<<v4-33-8,8>>^ Partindo de Fiairoth, passaram pelo meio do mar para o deserto; tendo marchado três dias para o deserto de Etam, acamparam em Mara.

[[v4-33-9]]

^<<v4-33-9,9>>^ Partindo de Mara, foram a Elim, onde havia doze fontes de água e setenta palmeiras, e ali acamparam.

[[v4-33-10]]

^<<v4-33-10,10>>^ Tendo partido também de lá, assentaram as tendas junto do mar Vermelho. Partindo do mar Vermelho,

[[v4-33-11]]

^<<v4-33-11,11>>^ acamparam no deserto de Sin.

[[v4-33-12]]

^<<v4-33-12,12>>^ Partindo de lá, foram a Dafca.

[[v4-33-13]]

^<<v4-33-13,13>>^ Partindo de Dafca, foram acampar em Alus.

[[v4-33-14]]

^<<v4-33-14,14>>^ Tendo partido de Alus, levantaram as tendas em Rafidim, onde faltou ao povo a água para beber.

[[v4-33-15]]

^<<v4-33-15,15>>^ Partindo de Rafidim, acamparam no deserto do Sinai.

[[v4-33-16]]

^<<v4-33-16,16>>^ Partindo do deserto do Sinai, foram aos Sepulcros da Concupiscência.

[[v4-33-17]]

^<<v4-33-17,17>>^ Partindo dos Sepulcros da Concupiscência, acamparam em Haseroth.

[[v4-33-18]]

^<<v4-33-18,18>>^ De Haseroth, foram a Retma.

[[v4-33-19]]

^<<v4-33-19,19>>^ Partindo de Retma, acamparam em Remonfares.

[[v4-33-20]]

^<<v4-33-20,20>>^ Partindo de lá, foram a Lebna.

[[v4-33-21]]

^<<v4-33-21,21>>^ De Lebna foram acampar em Ressa.

[[v4-33-22]]

^<<v4-33-22,22>>^ Partindo de Ressa, foram a Ceelata.

[[v4-33-23]]

^<<v4-33-23,23>>^ Partindo daqui, acamparam no monte Sefer.

[[v4-33-24]]

^<<v4-33-24,24>>^ Deixando o monte Sefer, foram a Arada.

[[v4-33-25]]

^<<v4-33-25,25>>^ Partindo de lá, acamparam em Maceloth.

[[v4-33-26]]

^<<v4-33-26,26>>^ Partindo de Maceloth, foram a Taath.

[[v4-33-27]]

^<<v4-33-27,27>>^ De Taath foram acampar em Tare.

[[v4-33-28]]

^<<v4-33-28,28>>^ Partindo de lá, levantaram as tendas em Metca.

[[v4-33-29]]

^<<v4-33-29,29>>^ De Metca foram acampar em Hesmona.

[[v4-33-30]]

^<<v4-33-30,30>>^ Partindo de Hesmona, foram a Moseroth.

[[v4-33-31]]

^<<v4-33-31,31>>^ De Moseroth foram acampar em Benejaacan.

[[v4-33-32]]

^<<v4-33-32,32>>^ Partindo de Benejaacan, foram ao monte Gadgad.

[[v4-33-33]]

^<<v4-33-33,33>>^ Partindo de lá, acamparam em Jetebata.

[[v4-33-34]]

^<<v4-33-34,34>>^ De Jetebata foram a Hebrona.

[[v4-33-35]]

^<<v4-33-35,35>>^ Partindo de Hebrona, acamparam em Asiongaber.

[[v4-33-36]]

^<<v4-33-36,36>>^ Partindo de lá, foram ao deserto de Sin, que é Cades.

[[v4-33-37]]

^<<v4-33-37,37>>^ Partindo de Cades, acamparam sobre o monte Hor, nos confins do país de Edom.

[[v4-33-38]]

^<<v4-33-38,38>>^ O sacerdote Aarão subiu por mandado do Senhor ao monte Hor, e ali morreu no primeiro dia do mês, no ano quadragésimo, depois da saída dos filhos de Israel do Egito, no quinto mês,

[[v4-33-39]]

^<<v4-33-39,39>>^ tendo cento e vinte e três anos de idade.

[[v4-33-40]]

^<<v4-33-40,40>>^ (Foi então que) os filhos de Israel tinham chegado à terra de Canaan.

[[v4-33-41]]

^<<v4-33-41,41>>^ Partindo do monte Hor, acamparam em Salmona.

[[v4-33-42]]

^<<v4-33-42,42>>^ Partindo de lá foram a Funon.

[[v4-33-43]]

^<<v4-33-43,43>>^ Partindo de Funon, acamparam em Oboth.

[[v4-33-44]]

^<<v4-33-44,44>>^ De Oboth foram a Ijeabarim, que está nos confins dos Moabitas.

[[v4-33-45]]

^<<v4-33-45,45>>^ Partindo de Ijeabarim, levantaram as tendas em Dibongad.

[[v4-33-46]]

^<<v4-33-46,46>>^ Partindo de lá acamparam em Helmondeblataim.

[[v4-33-47]]

^<<v4-33-47,47>>^ Partindo de Helmondeblataim, foram aos montes de Abarim, defronte de Nabo.

[[v4-33-48]]

^<<v4-33-48,48>>^ Partindo dos montes de Abarim, passaram às planícies de Moab sobre o Jordão defronte de Jericó.

[[v4-33-49]]

^<<v4-33-49,49>>^ Aí acamparam desde Betsimoth até Abelsatim, nos lugares mais planos dos Moabitas.

[[v4-33-50]]

^<<v4-33-50,50>>^ Ai o Senhor disse a Moisés:

[[v4-33-51]]

^<<v4-33-51,51>>^ Dize aos filhos de Israel: Quando tiverdes passado o Jordão, entrando na terra de Canaan,

[[v4-33-52]]

^<<v4-33-52,52>>^ exterminai todos os habitantes daquele país: quebrai as esculturas, reduzi a pó as estátuas, devastai todos os seus lugares altos,

[[v4-33-53]]

^<<v4-33-53,53>>^ purificando a terra, e habitando nela, porque eu vos dou a sua posse.

[[v4-33-54]]

^<<v4-33-54,54>>^ Reparti-la-eis entre vós por sorte. Aos que forem em maior número, dareis uma porção maior, e aos que forem menos, uma porção mais pequena. Cada um receberá a sua herança, conforme o que lhe cair por sorte. A divisão será feita por tribos e por famílias.

[[v4-33-55]]

^<<v4-33-55,55>>^ Se vós não quiserdes expulsar os habitantes do país, os que ficarem serão para vós como espinhos nos olhos, e aguilhões nas ilhargas, e opor-se-ão a vós na terra da vossa habitação;

[[v4-33-56]]

^<<v4-33-56,56>>^ e todo o mal que eu tinha pensado fazer-lhes a eles, o farei a vós.

'''

xref:004-numeros/004-numeros-032.adoc#v4-32-0[&#60; Capítulo Anterior] | <<v4-33-0,Topo>> | xref:004-numeros/004-numeros-034.adoc#v4-34-0[Próximo Capítulo &#62;]