include::./index.adoc[]

[[v4-4-0]]
=== Números, 4
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 4 de Números trata das responsabilidades dos levitas em relação ao transporte do Tabernáculo e dos objetos sagrados durante a jornada pelo deserto. Os versículos selecionados são:
* Deuteronômio 31:25-26: "que Moisés ordenou aos levitas que transportassem a arca da aliança do Senhor, dizendo: Tomai este livro da lei e colocai-o ao lado da arca da aliança do Senhor, vosso Deus, para que ali esteja como testemunha contra ti." Esses versículos mostram a importância dos levitas no transporte dos objetos sagrados, incluindo a Arca da Aliança.
* 1 Crônicas 15:2: "Então disse Davi: Aqui está a arca de Deus, a qual mandamos buscar, para colocar sob uma tenda que lhe fizemos." Este versículo descreve a transferência da Arca da Aliança para Jerusalém, onde Davi construiu um tabernáculo para abrigá-la.
* 1 Crônicas 23:24-32: "Estas foram as responsabilidades deles em relação ao serviço no tabernáculo da casa de Deus, de acordo com as instruções de Arão, seu pai, como o Senhor, o Deus de Israel, lhe havia ordenado." Esses versículos detalham as responsabilidades dos levitas no serviço do Tabernáculo e como eles foram designados para cumprir essas funções.
* Salmos 84:1-2: "Quão amáveis são os teus tabernáculos, Senhor dos Exércitos! A minha alma anela, e até desfalece pelos átrios do Senhor; o meu coração e o meu corpo cantam de alegria ao Deus vivo." Este salmo descreve o desejo de adorar a Deus no Tabernáculo e como as pessoas se sentiam atraídas pela presença de Deus lá.
* Hebreus 9:1-5: "Ora, a primeira aliança também tinha ordenanças de culto e um santuário terrestre. Pois um tabernáculo foi preparado, o primeiro, em que havia o candelabro, e a mesa, e os pães da proposição; e a este chamavam o lugar santo. Mas, por detrás do segundo véu, estava o tabernáculo que se chama o santo dos santos, o qual tinha um incensário de ouro, e a arca da aliança toda coberta de ouro..." Esses versículos descrevem o Tabernáculo e seus objetos sagrados em detalhes, dando uma compreensão mais profunda de como tudo funcionava e como era importante para a adoração a Deus.
****

[[v4-4-1]]

^<<v4-4-1,1>>^ O Senhor falou a Moisés e Aarão, dizendo:

[[v4-4-2]]

^<<v4-4-2,2>>^ Faze a contagem dos filhos de Caath, dentre os Levitas, segundo as suas casas e as suas famílias,

[[v4-4-3]]

^<<v4-4-3,3>>^ desde a idade de trinta anos para cima até aos cinquenta, de todos os que entram para assistirem e ministrarem no tabernáculo da reunião.

[[v4-4-4]]

^<<v4-4-4,4>>^ Este é o serviço dos filhos de Caath, no tabernáculo da reunião: referir-se-á a coisas santíssimas.

[[v4-4-5]]

^<<v4-4-5,5>>^ Filtrarão Aarão e seus filhos, quando se tiverem de mover os acampamentos, descerão o véu, que está pendente diante da porta, envolverão nele a arca do testemunho,

[[v4-4-6]]

^<<v4-4-6,6>>^ cobri-la-ão ainda com uma coberta de peles roxas, e estenderão por cima um pano todo de púrpura violácea, e meterão os varais.

[[v4-4-7]]

^<<v4-4-7,7>>^ Envolverão, também, num pano de púrpura violácea a mesa da proposição, e porão com ela os turíbulos e os grãozinhos, os copos e as taças para as libações; os pães estarão sempre sobre ela.

[[v4-4-8]]

^<<v4-4-8,8>>^ Estender-lhe-ão por cima um pano carmesim, o qual cobrirão ainda com uma coberta de peles roxas, e meterão os varais.

[[v4-4-9]]

^<<v4-4-9,9>>^ Tomarão também um pano de púrpura violácea, com o qual cobrirão o candeeiro com as lâmpadas e as suas tenazes e espevitadores e todos os vasos de azeite, que são necessários para preparar as lâmpadas:

[[v4-4-10]]

^<<v4-4-10,10>>^ sobre todas estas coisas lançarão uma coberta de peles roxas, e meterão os varais.

[[v4-4-11]]

^<<v4-4-11,11>>^ Envolverão também o altar de ouro num pano de púrpura violáceas e estenderão por cima uma coberta de peles roxas e meterão os varais.

[[v4-4-12]]

^<<v4-4-12,12>>^ Envolverão, num pano de púrpura violácea, todos os utensílios, com que se faz serviço no santuário, estenderão por cima uma coberta de peles roxas e meterão os varais.

[[v4-4-13]]

^<<v4-4-13,13>>^ Limparão também as cinzas do altar, estenderão sobre ele um pano de púrpura;

[[v4-4-14]]

^<<v4-4-14,14>>^ porão em cima todos os utensílios que se usam no serviço, isto é, os braseiros, as tenazes e os tridentes, os garfos e as pás. Cobrirão todos os utensílios do altar com uma coberta de peles roxas, e meterão os varais.

[[v4-4-15]]

^<<v4-4-15,15>>^ Depois que Aarão e seus filhos tiverem envolvido o santuário com todos os seus utensílios ao levantar dos acampamentos, então entrarão os filhos de Caath para levarem o que estiver embrulhado; não tocarão nos utensílios do santuário, para que não morram. Estes são os cargos dos filhos de Caath relativamente ao tabernáculo da reunião,

[[v4-4-16]]

^<<v4-4-16,16>>^ O seu chefe será Eleázaro, filho do sacerdote Aarão, que terá a seu cuidado o azeite para preparar as lâmpadas, o incenso de composição, a oblação perpétua e o óleo da unção, bem como tudo o que pertence ao serviço do tabernáculo, e todos os utensílios que há no santuário.

[[v4-4-17]]

^<<v4-4-17,17>>^ O Senhor falou a Moisés e a Aarão, dizendo:

[[v4-4-18]]

^<<v4-4-18,18>>^ Não queirais exterminar os filhos da linhagem de Caath do meio dos Levitas.

[[v4-4-19]]

^<<v4-4-19,19>>^ Procedei de modo que vivam, e não morram ao tocarem as coisas santíssimas. Aarão e seus filhos entrarão, e eles mesmos disporão os encargos de cada um, e separarão o que deve cada um levar.

[[v4-4-20]]

^<<v4-4-20,20>>^ Os outros não olhem com curiosidade para as coisas que há no santuário antes de estarem embrulhadas, aliás morrerão.

[[v4-4-21]]

^<<v4-4-21,21>>^ O Senhor falou a Moisés, dizendo:

[[v4-4-22]]

^<<v4-4-22,22>>^ Tira também a conta dos filhos de Gerson, segundo as suas casas patriarcais, segundo as suas famílias,

[[v4-4-23]]

^<<v4-4-23,23>>^ desde os trinta anos para cima até aos cinquenta. Conta todos os que entram e servem no tabernáculo da reunião.

[[v4-4-24]]

^<<v4-4-24,24>>^ Este é o ofício da família dos Gersonitas:

[[v4-4-25]]

^<<v4-4-25,25>>^ Levarão as cortinas do tabernáculo, o texto da aliança, a segunda coberta, a coberta das peles roxas que está por cima, o véu que está pendurado à entrada do tabernáculo da reunião,

[[v4-4-26]]

^<<v4-4-26,26>>^ as cortinas do átrio, e o véu da entrada que está diante do tabernáculo. Todas as coisas que pertencem ao altar, os condões e os utensílios do ministério,

[[v4-4-27]]

^<<v4-4-27,27>>^ levá-las-ão os filhos de Gerson, debaixo das ordens de Aarão e de seus filhos, e cada um saberá que serviço deve prestar.

[[v4-4-28]]

^<<v4-4-28,28>>^ Este é o serviço da família dos Gersonitas no tabernáculo da reunião, e estarão sujeitos a Itamar, filho do sacerdote Aarão.

[[v4-4-29]]

^<<v4-4-29,29>>^ Contarás também os filhos de Merari, segundo as suas famílias e as casas de seus pais,

[[v4-4-30]]

^<<v4-4-30,30>>^ desde os trinta anos para cima até aos cinquenta, todos que têm algum ofício, que prestam serviço no tabernáculo da reunião.

[[v4-4-31]]

^<<v4-4-31,31>>^ Estes são os seus cargos: Levarão as tábuas do tabernáculo, os seus varais, as colunas, as suas bases,

[[v4-4-32]]

^<<v4-4-32,32>>^ e também as colunas que estão ao redor do átrio com as suas bases, estacas e cordas. Receberão por conta todos os vasos e alfaias, e assim as levarão.

[[v4-4-33]]

^<<v4-4-33,33>>^ Este é o serviço da família dos Meraritas e o seu ministério no tabernáculo da reunião; estarão às ordens de Itamar, filho do sacerdote Aarão,

[[v4-4-34]]

^<<v4-4-34,34>>^ Moisés, Aarão e os príncipes da sinagoga fizeram o recenseamento dos filhos de Caath segundo as famílias e as casas de seus pais,

[[v4-4-35]]

^<<v4-4-35,35>>^ desde os trinta anos para cima até aos cinqüenta, (isto é) de todos os que entram no serviço do tabernáculo da reunião:

[[v4-4-36]]

^<<v4-4-36,36>>^ Contaram dois mil e setecentos e cinqüenta.

[[v4-4-37]]

^<<v4-4-37,37>>^ Este é o número dos da estirpe de Caath, que entraram no tabernáculo da reunião, contados por Moisés e Aarão, segundo a ordem dada pelo Senhor por meio de Moisés.

[[v4-4-38]]

^<<v4-4-38,38>>^ Foram também contados os filhos de Gerson segundo as famílias e casas de seus pais,

[[v4-4-39]]

^<<v4-4-39,39>>^ desde os trinta anos para cima até aos cinqüenta, todos os que entram para ministrar no tabernáculo da reunião;

[[v4-4-40]]

^<<v4-4-40,40>>^ acharam-se dois mil e seiscentos e trinta.

[[v4-4-41]]

^<<v4-4-41,41>>^ Estes são os da estirpe dos Gersonitas, que Moisés e Aarão contaram segundo a ordem do Senhor.

[[v4-4-42]]

^<<v4-4-42,42>>^ Foram também contados os filhos de Merari segundo as famílias e casas de seus pais,

[[v4-4-43]]

^<<v4-4-43,43>>^ desde os trinta anos para cima até aos cinquenta, todos os que entram a exercer as suas funções no tabernáculo da reunião,

[[v4-4-44]]

^<<v4-4-44,44>>^ e foram achados três mil e duzentos.

[[v4-4-45]]

^<<v4-4-45,45>>^ Este é o número dos filhos de Merari, que Moisés e Aarão contaram, segundo a ordem dada pelo Senhor por meio de Moisés.

[[v4-4-46]]

^<<v4-4-46,46>>^ Todos os que foram contados dentre os Levitas, e de quem Moisés e Aarão e os príncipes de Israel fizeram o recenseamento segundo as famílias e casas de seus pais,

[[v4-4-47]]

^<<v4-4-47,47>>^ desde os trinta anos para cima até aos cinquenta, que entravam para o serviço do tabernáculo ou para o seu transporte,

[[v4-4-48]]

^<<v4-4-48,48>>^ foram ao todo oito mil quinhentos e oitenta.

[[v4-4-49]]

^<<v4-4-49,49>>^ Moisés, conforme a ordem do Senhor, contou-os cada um segundo o seu ofício e os seus cargos, como o Senhor lhe tinha ordenado.

'''

xref:004-numeros/004-numeros-003.adoc#v4-3-0[&#60; Capítulo Anterior] | <<v4-4-0,Topo>> | xref:004-numeros/004-numeros-005.adoc#v4-5-0[Próximo Capítulo &#62;]