include::./index.adoc[]

[[v4-7-0]]
=== Números, 7
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 7 de Números trata da dedicação do altar do tabernáculo pelos líderes das tribos de Israel. Cada líder apresenta ofertas e sacrifícios para consagrar o altar e expressar sua devoção a Deus. Os versículos relacionados aos temas deste capítulo são:
* Êxodo 29:37 - "Sete dias farás expiação pelo altar, e o santificarás, e o altar será santíssimo; tudo o que tocar o altar será santo." Este versículo fala sobre a importância de santificar o altar, o que é o tema principal do capítulo 7 de Números.
* Levítico 9:22-24 - "Arão levantou as mãos para o povo e o abençoou. Depois de oferecer a oferta pelo pecado, o holocausto e a oferta de comunhão, desceu. Moisés e Arão entraram na Tenda do Encontro. Quando saíram, abençoaram o povo, e a glória do Senhor apareceu a todo o povo." Este versículo fala sobre a cerimônia de dedicação do tabernáculo em geral, que é semelhante à dedicação do altar descrita em Números 7.
* Salmos 51:17 - "Sacrifícios agradáveis a Deus são o espírito quebrantado; coração compungido e contrito, não o desprezarás, ó Deus." Este versículo fala sobre a importância da atitude do coração em relação aos sacrifícios, que é um tema importante em Números 7.
* Hebreus 13:15 - "Por meio de Jesus, portanto, ofereçamos a Deus um sacrifício de louvor, que é fruto de lábios que confessam o seu nome." Este versículo fala sobre como, no Novo Testamento, o sacrifício de louvor substituiu os sacrifícios de animais como uma forma de adoração a Deus.
* Romanos 12:1 - "Rogo-vos, pois, irmãos, pela compaixão de Deus, que apresenteis os vossos corpos como um sacrifício vivo, santo e agradável a Deus, que é o vosso culto racional." Este versículo fala sobre como a vida cristã deve ser uma oferta viva e contínua de adoração a Deus, que é um tema relacionado com a dedicação do altar em Números 7.
****

[[v4-7-1]]

^<<v4-7-1,1>>^ No dia em que Moisés acabou o tabernáculo, o levantou, o ungiu e santificou com todos os seus utensílios, assim como o altar com todos os seus utensílios,

[[v4-7-2]]

^<<v4-7-2,2>>^ os principies de Israel, chefes das suas casas patriarcais, que haviam presidido ao recenseamento, ofereceram

[[v4-7-3]]

^<<v4-7-3,3>>^ os seus dons diante do Senhor: Seis carros cobertos e doze bois. Cada dois chefes ofereceram um carro, e cada um deles um boi, e os apresentaram diante do tabernáculo.

[[v4-7-4]]

^<<v4-7-4,4>>^ O Senhor disse a Moisés:

[[v4-7-5]]

^<<v4-7-5,5>>^ Recebe-os deles para que sirvam no ministério do tabernáculo, e entregá-los-ás aos Levitas segundo as necessidades do seu serviço.

[[v4-7-6]]

^<<v4-7-6,6>>^ Tendo, pois, Moisés recebido os carros e os bois, entregou-os aos Levitas.

[[v4-7-7]]

^<<v4-7-7,7>>^ Deu dois carros e quatro bois aos filhos de Gerson, segundo era a necessidade que deles tinham.

[[v4-7-8]]

^<<v4-7-8,8>>^ Deu aos filhos de Merari outros quatro carros e oito bois, atendendo aos ofícios e obrigações que tinham à ordem de Itamar, filho do sacerdote Aarão.

[[v4-7-9]]

^<<v4-7-9,9>>^ Aos filhos de Caath, porém, não deu carros nem bois, porque servem no santuário, levando as coisas santas aos seus próprios ombros.

[[v4-7-10]]

^<<v4-7-10,10>>^ Os chefes ofereceram as suas oblações diante do altar para a dedicação do altar, no dia em que foi ungido.

[[v4-7-11]]

^<<v4-7-11,11>>^ O Senhor disse a Moisés: Cada um dos chefes ofereça cada dia os seus dons para a dedicação do altar.

[[v4-7-12]]

^<<v4-7-12,12>>^ No primeiro dia fez a sua oferta Naasson, filho de Aminadab. da tribo de Judá:

[[v4-7-13]]

^<<v4-7-13,13>>^ a sua oferta foi um prato de prata, de cento e trinta siclos de peso, e uma taça de prata, de setenta siclos, segundo o peso do santuário, ambos cheios de farinha borrifada com azeite para o sacrifício;

[[v4-7-14]]

^<<v4-7-14,14>>^ um pequeno vaso de ouro que pesava dez siclos, cheio de incenso;

[[v4-7-15]]

^<<v4-7-15,15>>^ um boi da manada, um carneiro e um cordeiro de um ano, para o holocausto;

[[v4-7-16]]

^<<v4-7-16,16>>^ um bode pelo pecado;

[[v4-7-17]]

^<<v4-7-17,17>>^ para o sacrifício pacífico dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano. Esta foi a oferta de Naasson, filho de Aminadab.

[[v4-7-18]]

^<<v4-7-18,18>>^ No segundo dia, Natanael, filho de Suar, chefe da tribo de Issacar, ofereceu

[[v4-7-19]]

^<<v4-7-19,19>>^ um prato de prata, que pesava cento e trinta siclos, uma taça de prata de setenta siclos segundo o peso do santuário, ambos cheios de farinha borrifada com azeite para o sacrifício:

[[v4-7-20]]

^<<v4-7-20,20>>^ um pequeno vaso de ouro, que pesava dez sidos, cheio de incenso:

[[v4-7-21]]

^<<v4-7-21,21>>^ um boi da manada, um carneiro e um cordeiro de um ano, para o holocausto;

[[v4-7-22]]

^<<v4-7-22,22>>^ um bode pelo pecado;

[[v4-7-23]]

^<<v4-7-23,23>>^ para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano. Esta foi a oferta de Natanael, filho de Suar.

[[v4-7-24]]

^<<v4-7-24,24>>^ Ao terceiro dia, Eliab, filho de Helon e chefe dos filhos de Zabulon,

[[v4-7-25]]

^<<v4-7-25,25>>^ ofereceu um prato de prata, que pesava cento e trinta siclos, e uma taça de prata, que tinha setenta siclos segundo o peso do santuário, ambos cheios de farinha borrifada com azeite para o sacrifício;

[[v4-7-26]]

^<<v4-7-26,26>>^ um pequeno vaso de ouro que pesava dez siclos, cheio de incenso;

[[v4-7-27]]

^<<v4-7-27,27>>^ um boi da manada, um carneiro e um cordeiro de um ano, para o holocausto;

[[v4-7-28]]

^<<v4-7-28,28>>^ um bode pelo pecado;

[[v4-7-29]]

^<<v4-7-29,29>>^ para o sacrifico pacífico, dois bois, cinco carneiros, cinco bodes, cindo cordeiros de um ano. Esta foi a oferta de Eliab, filho de Helon,

[[v4-7-30]]

^<<v4-7-30,30>>^ Ao quarto dia Elisur, filho de Sedeur, e príncipe dos filhos de Ruben,

[[v4-7-31]]

^<<v4-7-31,31>>^ ofereceu um prato de prata, que pesava cento e trinta siclos, uma taça de prata, que tinha setenta siclos pelo peso do santuário, ambos cheias de flor de farinha borrifada com azeite para o sacrifício.

[[v4-7-32]]

^<<v4-7-32,32>>^ um pequeno vaso de ouro do peso de dez sidos, cheio de incenso;

[[v4-7-33]]

^<<v4-7-33,33>>^ um boi da manada, um carneiro e um cordeiro de um ano, para o holocausto;

[[v4-7-34]]

^<<v4-7-34,34>>^ um bode pelo pecado;

[[v4-7-35]]

^<<v4-7-35,35>>^ para o sacrifício pacifico, dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano. Esta foi a oferta de Elisur, filho de Sodeur.

[[v4-7-36]]

^<<v4-7-36,36>>^ Ao quinto dia Salamiel, filho de Surisadai, príncipe dos filhos de Simeão,

[[v4-7-37]]

^<<v4-7-37,37>>^ ofereceu um prato de prata, que pesava cento e trinta ciclos, uma taça de prata, que tinha setenta siclos pelo peso do santuário, ambos cheios de flor de farinha borrifada com azeite para o sacrifício;

[[v4-7-38]]

^<<v4-7-38,38>>^ um pequeno vaso de ouro, que pesava dez siclos, cheio de incenso;

[[v4-7-39]]

^<<v4-7-39,39>>^ um boi da manada, um carneiro e um cordeiro de um ano, para o holocausto;

[[v4-7-40]]

^<<v4-7-40,40>>^ um bode pelo pecado;

[[v4-7-41]]

^<<v4-7-41,41>>^ para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano. Esta foi a oferta de Salamiel, filho de Surisadai.

[[v4-7-42]]

^<<v4-7-42,42>>^ Ao sexto dia Eliasaph, filho de Duel, príncipe dos filhos de Gad,

[[v4-7-43]]

^<<v4-7-43,43>>^ ofereceu um prato de prata, que pesava cento e trinta siclos, uma taça de prata, que tinha setenta siclos, pelo peso do santuário, ambos cheios de flor de farinha borrifada com azeite para o sacrifício;

[[v4-7-44]]

^<<v4-7-44,44>>^ um pequeno vaso de ouro do peso de dez siclos, cheio de incenso;

[[v4-7-45]]

^<<v4-7-45,45>>^ um boi da manada, um carneiro e um cordeiro de um ano, para o holocausto;

[[v4-7-46]]

^<<v4-7-46,46>>^ um bode pelo pecado;

[[v4-7-47]]

^<<v4-7-47,47>>^ para o sacrifício pacífico dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano. Esta foi a oferta de Eliasaph, filho de Duel.

[[v4-7-48]]

^<<v4-7-48,48>>^ Ao sétimo dia Elisama, filho de Amiud, príncipe dos filhos de Efraim,

[[v4-7-49]]

^<<v4-7-49,49>>^ ofereceu um prato de prata, que pesava cento e trinta siclos, uma taça de prata, que tinha setenta siclos, pelo peso do santuário, ambos cheios de flor de farinha borrifada com azeite para o sacrifício;

[[v4-7-50]]

^<<v4-7-50,50>>^ um pequeno vaso de ouro do peso de dez siclos, cheio de incenso;

[[v4-7-51]]

^<<v4-7-51,51>>^ um boi da mamada, um carneiro e um cordeiro de um ano, para o holocausto;

[[v4-7-52]]

^<<v4-7-52,52>>^ um bode pelo pecado;

[[v4-7-53]]

^<<v4-7-53,53>>^ para o sacrifício pacifico, dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano. Este foi a oferta de Elisama, filho de Amiud.

[[v4-7-54]]

^<<v4-7-54,54>>^ Ao oitavo dia Gamaliel, filho de Fadassur, príncipe dos filhos de Manassés

[[v4-7-55]]

^<<v4-7-55,55>>^ ofereceu um prato de prata, que pesava cento e trinta siclos, uma taça de prata, que tinha setenta siclos pelo peso do santuário, ambos cheios de flor de farinha borrifada com azeite para o sacrifício;

[[v4-7-56]]

^<<v4-7-56,56>>^ um pequeno vaso de ouro do peso de dez siclos, cheio de incenso;

[[v4-7-57]]

^<<v4-7-57,57>>^ Um boi da manada, um carneiro e um cordeiro de um ano, para o holocausto;

[[v4-7-58]]

^<<v4-7-58,58>>^ um bode pelo pecado;

[[v4-7-59]]

^<<v4-7-59,59>>^ para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano. Esta foi a oferta de Gamaliel, filho de Fadassur,

[[v4-7-60]]

^<<v4-7-60,60>>^ Ao nono dia Abidan, filho de Gedeão e príncipe dos filhos de Benjamim,

[[v4-7-61]]

^<<v4-7-61,61>>^ ofereceu um prato de prata, que pesava cento e trinta siclos, uma taça de prata, que tinha setenta siclos pelo peso do santuário, ambos cheios de flor de farinha borrifada com azeite para o sacrifício;

[[v4-7-62]]

^<<v4-7-62,62>>^ um pequeno vaso de ouro do peso de dez siclos, cheio de incenso;

[[v4-7-63]]

^<<v4-7-63,63>>^ um boi da manada, um carneiro e um cordeiro de um ano, para o holocausto:

[[v4-7-64]]

^<<v4-7-64,64>>^ um bode pelo pecado;

[[v4-7-65]]

^<<v4-7-65,65>>^ para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano. Esta foi a oferta de Abidan, filho de Gedeão.

[[v4-7-66]]

^<<v4-7-66,66>>^ Ao décimo dia Aiezer, filho de Amisadai, príncipe dos filhos de Dan,

[[v4-7-67]]

^<<v4-7-67,67>>^ ofereceu um prato de prata, que pesava cento e trinta siclos, uma taça, que tinha trinta siclos pelo peso do santuário, ambos cheios de flor de farinha borrifada com azeite para o sacrifício;

[[v4-7-68]]

^<<v4-7-68,68>>^ um pequeno vaso de ouro do peso de dez siclos, cheio de incenso;

[[v4-7-69]]

^<<v4-7-69,69>>^ um boi da manada, um carneiro e um cordeiro de um ano, para o holocausto:

[[v4-7-70]]

^<<v4-7-70,70>>^ um bode pelo pecado;

[[v4-7-71]]

^<<v4-7-71,71>>^ para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano. Esta foi a oferta de Aiezer, filho de Amisadai.

[[v4-7-72]]

^<<v4-7-72,72>>^ Ao undécimo dia Fegiel, filho de Ocran, príncipe dos filhos de Aser,

[[v4-7-73]]

^<<v4-7-73,73>>^ ofereceu um prato de prata, que pesava cento e trinta siclos, uma taça de prata, que tinha setenta siclos pelo peso do santuário, ambos cheios de flor de farinha borrifada com azeite para o sacrifício;

[[v4-7-74]]

^<<v4-7-74,74>>^ um pequeno vaso de ouro do peso de dez ciclos cheio de incenso;

[[v4-7-75]]

^<<v4-7-75,75>>^ um boi da manada, um carneiro e um cordeiro de um ano, para o holocausto;

[[v4-7-76]]

^<<v4-7-76,76>>^ um bode pelo pecado;

[[v4-7-77]]

^<<v4-7-77,77>>^ para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano. Esta foi a oferta de Fegiel, filho Ocran.

[[v4-7-78]]

^<<v4-7-78,78>>^ Ao duodécimo dia Aira, filho de Enan e príncipe dos filhos de Neftali,

[[v4-7-79]]

^<<v4-7-79,79>>^ ofereceu um prato de prata, que pesava cento e trinta siclos, uma taça de praia, que tinha setenta siclos, pelo peso do santuário, ambos cheios de flor de farinha borrifada com azeite para o sacrifício;

[[v4-7-80]]

^<<v4-7-80,80>>^ um pequeno vaso de ouro do peso de dez siclos, cheio de incenso;

[[v4-7-81]]

^<<v4-7-81,81>>^ um boi da manada, um carneiro e um cordeiro de um ano, para o holocausto:

[[v4-7-82]]

^<<v4-7-82,82>>^ um bode pelo pecado;

[[v4-7-83]]

^<<v4-7-83,83>>^ para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano. Esta foi a oferta de Aira, filho de Enan.

[[v4-7-84]]

^<<v4-7-84,84>>^ As coisais, pois, oferecidas pelos príncipes de Israel, na dedicação do altar, no dia em que foi consagrado, foram estas; doze pratos de prata, doze taças de prata, doze pequenos vasos de ouro,

[[v4-7-85]]

^<<v4-7-85,85>>^ pesando cada prato cento e trinta siclos, e cada taça setenta, de sorte que todos os vasos de prata juntos pesavam dois mil e quatrocentos siclos, pelo peso do santuário.

[[v4-7-86]]

^<<v4-7-86,86>>^ os doze pequenos vasos de ouro cheios de incenso, de dez siclos cada um, pelo peso do santuário, pesavam todos juntos cento e vinte siclos de ouro.

[[v4-7-87]]

^<<v4-7-87,87>>^ Total dos animais para o holocausto: Doze bois da manada, doze carneiros, doze cordeiros de um ano com as suas libações, doze bodes pelo pecado.

[[v4-7-88]]

^<<v4-7-88,88>>^ Total dos animais para o sacrifício pacífico: vinte e quatro bois, sessenta carneiros, setenta bodes, sessenta cordeiros de um ano. Estes coisas foram oferecidas na dedicação do altar, quando foi ungido.

[[v4-7-89]]

^<<v4-7-89,89>>^ Quando Moisés entrava no tabernáculo da reunião, para falar com o Senhor, ouvia a voz daquele que lhe falava do propiciatório, colocado sobre a arca do testemunho, entre os dois querubins. Era assim que lhe falava.

'''

xref:004-numeros/004-numeros-006.adoc#v4-6-0[&#60; Capítulo Anterior] | <<v4-7-0,Topo>> | xref:004-numeros/004-numeros-008.adoc#v4-8-0[Próximo Capítulo &#62;]