include::./index.adoc[]

[[v4-30-0]]
=== Números, 30
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Números 30 trata sobre os votos que as pessoas fazem ao Senhor e a importância de cumpri-los. O capítulo também destaca a importância de honrar os compromissos feitos, especialmente no contexto do casamento. Abaixo estão cinco versículos relacionados com os temas abordados em Números 30:
* Deuteronômio 23:21: "Se fizeres algum voto ao Senhor, teu Deus, não tardes em cumpri-lo; pois o Senhor, teu Deus, certamente o requererá de ti e em ti haverá pecado." Este versículo destaca a importância de cumprir os votos feitos ao Senhor e a seriedade com que Ele os leva.
* Provérbios 20:25: "É uma armadilha para o homem fazer um voto precipitadamente e só refletir sobre ele depois." Este versículo adverte as pessoas para não fazerem votos precipitados, mas sim ponderar cuidadosamente antes de comprometerem-se com algo.
* Mateus 5:33-34: "Também ouvistes o que foi dito aos antigos: Não jurarás falso, mas cumprirás para com o Senhor os teus juramentos. Eu, porém, vos digo que de modo algum jureis; nem pelo céu, por ser o trono de Deus."
* Eclesiastes 5:4-5: "Quando a Deus fizeres algum voto, não tardes em cumpri-lo; porque não se agrada de tolos. Cumpre o voto que fazes. Melhor é que não votes do que votes e não cumpras."
* Efésios 5:21-22: "Sujeitai-vos uns aos outros no temor de Cristo. Vós, mulheres, sujeitai-vos a vossos maridos, como ao Senhor." Este versículo destaca a importância de honrar os compromissos feitos no casamento e de sujeitar-se uns aos outros em amor e respeito.
****

[[v4-30-1]]

^<<v4-30-1,1>>^ Moisés referiu aos filhos de Israel tudo o que o Senhor lhe tinha mandado

[[v4-30-2]]

^<<v4-30-2,2>>^ e disse aos príncipes das tribos dos filhos de Israel: Eis o que o Senhor ordenou:

[[v4-30-3]]

^<<v4-30-3,3>>^ Se um homem fizer um voto ao Senhor ou se obrigar com juramento, não faltará à sua palavra, mas cumprirá tudo o que prometeu,

[[v4-30-4]]

^<<v4-30-4,4>>^ Se uma mulher, ainda jovem, vivendo em casa de seu pai, fizer um voto e se obrigar com juramento, se o pai teve conhecimento do voto que ela fez e do juramento com que se obrigou, e não disse nada, ela está obrigada ao seu voto:

[[v4-30-5]]

^<<v4-30-5,5>>^ cumprirá de facto tudo o que prometeu e jurou fazer.

[[v4-30-6]]

^<<v4-30-6,6>>^ Porém, se o pai, logo que o soube, se opôs, tanto os votos como os juramentos dela serão nulos, e não ficará obrigada ao que prometeu porque o pai se opôs.

[[v4-30-7]]

^<<v4-30-7,7>>^ Se tiver marido, e fizer algum voto, e uma palavra saída uma vez da sua boca obrigar a sua alma com juramento,

[[v4-30-8]]

^<<v4-30-8,8>>^ se o seu marido, no dia em que tiver disso conhecimento, não se opuser, ela ficará obrigada ao voto, e cumprirá tudo o que prometeu.

[[v4-30-9]]

^<<v4-30-9,9>>^ Mas, se o marido, no dia em que tiver disso conhecimento, se opuser, tornará nulas as suas promessas e as palavras com que se tinha obrigado, e o Senhor lhe perdoará.

[[v4-30-10]]

^<<v4-30-10,10>>^ A viúva e a repudiada cumprirão todos os votos que fizerem,

[[v4-30-11]]

^<<v4-30-11,11>>^ A mulher que está em casa do marido, se se obrigar com voto ou juramento,

[[v4-30-12]]

^<<v4-30-12,12>>^ desde que o marido, ao sabê-lo, não diga nada, não se oponha à sua promessa, cumprirá tudo o que prometeu.

[[v4-30-13]]

^<<v4-30-13,13>>^ Porém, se ele se opuser logo, não estará obrigada à promessa, porque o marido se opôs. O Senhor lhe perdoará.

[[v4-30-14]]

^<<v4-30-14,14>>^ Se se comprometer por voto, ou se obrigar por juramento a afligir a sua alma, ficará ao arbítrio do marido ratificar ou anular tais compromissos.

[[v4-30-15]]

^<<v4-30-15,15>>^ Se o marido, tendo conhecimento disso, não disser nada, e diferir para outro dia o seu parecer, ela cumprirá tudo o que tiver prometido com voto, visto que o marido, logo que o soube, não disse nada.

[[v4-30-16]]

^<<v4-30-16,16>>^ Se, porém, se opôs depois que o soube, levará ele sobre si a iniquidade dela. (ver nota)

[[v4-30-17]]

^<<v4-30-17,17>>^ Estas são as leis que o Senhor intimou a Moisés (para serem observadas) entre o marido e a mulher, entre o pai e a filha, ainda jovem, que mora em casa de seu pai.

'''

xref:004-numeros/004-numeros-029.adoc#v4-29-0[&#60; Capítulo Anterior] | <<v4-30-0,Topo>> | xref:004-numeros/004-numeros-031.adoc#v4-31-0[Próximo Capítulo &#62;]