include::./index.adoc[]

[[v4-6-0]]
=== Números, 6
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Números 6 detalha as leis e os requisitos para aqueles que fazem um voto nazireu, que inclui abstinência de álcool, evitar contato com os mortos e deixar o cabelo crescer sem cortar durante todo o período do voto. Aqui estão cinco versículos relacionados com os temas abordados em Números 6:
* Juízes 13:5: "Pois eis que tu conceberás e terás um filho; e navalha não passará sobre a sua cabeça, porquanto o menino será nazireu a Deus desde o ventre; e ele começará a livrar a Israel da mão dos filisteus." Este versículo se relaciona com Números 6, já que a vida de Sansão foi dedicada a Deus como um nazireu desde antes do seu nascimento.
* 1 Samuel 1:11: "E fez um voto, dizendo: Senhor dos Exércitos, se benignamente atentares para a aflição da tua serva, e de mim te lembrares, e da tua serva não te esqueceres, mas à tua serva deres um filho homem, ao Senhor o darei todos os dias da sua vida, e sobre a sua cabeça não passará navalha." Este versículo é semelhante à prática de fazer um voto nazireu, em que alguém dedica uma parte da sua vida a Deus em troca de uma bênção.
* Amós 2:11: "E dentre os seus filhos suscitei profetas, e dentre os seus jovens nazireus. Não é assim, ó filhos de Israel? diz o Senhor." Este versículo destaca a importância dos nazireus na história de Israel e como Deus usou essas pessoas como profetas e líderes.
* Mateus 3:4: "E este João tinha as suas vestes de pelos de camelo, e um cinto de couro em torno de seus lombos; e alimentava-se de gafanhotos e de mel silvestre." João Batista pode ser considerado um nazireu, já que ele viveu uma vida de abstinência e simplicidade, semelhante às práticas de um nazireu.
* Atos 18:18: "E Paulo, tendo permanecido ali ainda muitos dias, despediu-se dos irmãos, e dali navegou para a Síria, levando consigo Priscila e Áquila, havendo rapado a sua cabeça em Cencreia, porque tinha um voto." Paulo faz um voto nazireu em Atos 18:18, semelhante aos nazireus mencionados em Números 6.
****

[[v4-6-1]]

^<<v4-6-1,1>>^ O Senhor falou a Moisés, dizendo:

[[v4-6-2]]

^<<v4-6-2,2>>^ Fala aos filhos de Israel e dize-lhes: Quando um homem ou uma mulher fizerem voto de se santificar, e se quiserem consagrar ao Senhor,

[[v4-6-3]]

^<<v4-6-3,3>>^ abster-se-ão de vinho, e de tudo o que pode embriagar. Não beberão vinagre de vinho ou de qualquer outra bebida (inebriante), nada do que se espreme da uva: não comerão uvas frescas nem passas

[[v4-6-4]]

^<<v4-6-4,4>>^ durante todo o tempo que estiverem consagrados ao Senhor pelo voto: não comerão nenhum produto da vinha, desde a uva passa ao bagulho.

[[v4-6-5]]

^<<v4-6-5,5>>^ Durante todo o tempo da sua separação não passará navalha pela sua cabeça; até que se completem os dias da sua consagração ao Senhor. Será santo, deixando crescer os cabelos da sua cabeça.

[[v4-6-6]]

^<<v4-6-6,6>>^ Durante todo o tempo da sua consagração não entrará onde haja algum morto,

[[v4-6-7]]

^<<v4-6-7,7>>^ nem se contaminará assistindo ao enterro mesmo de (seu) pai, ou de (sua) mãe, ou de (seu) irmão, ou de (sua) irmã, porque a consagração do seu Deus está sobre a sua cabeça.

[[v4-6-8]]

^<<v4-6-8,8>>^ Durante todos os dias da sua separação será santo para o Senhor.

[[v4-6-9]]

^<<v4-6-9,9>>^ Se alguém morrer subitamente diante dele, ficará manchada a consagração da sua cabeça, a qual rapará logo no mesmo dia da sua purificação, bem como no sétimo dia.

[[v4-6-10]]

^<<v4-6-10,10>>^ No oitavo dia, porém, oferecerá ao sacerdote, à entrada do tabernáculo da reunião, duas rolas ou dois pombos.

[[v4-6-11]]

^<<v4-6-11,11>>^ O sacerdote imolará um pelo pecado, e outro em holocausto, e rogará por ele, porque pecou, manchando-se com a presença do morto; santificará naquele dia a sua cabeça.

[[v4-6-12]]

^<<v4-6-12,12>>^ e consagrará ao Senhor os dias da sua separação, oferecendo um cordeiro de um ano pelo pecado, mas de sorte que os dias precedentes sejam perdidos, visto que a sua santificação foi manchada.

[[v4-6-13]]

^<<v4-6-13,13>>^ Esta é a lei da consagração. Completos que forem os dias, a que por voto se tinha obrigado, (o sacerdote) conduzi-lo-á à entrada do tabernáculo da reunião,

[[v4-6-14]]

^<<v4-6-14,14>>^ para fazer ao Senhor a sua oferta, (que será) um cordeiro de um ano sem defeito em holocausto, uma ovelha de um ano sem defeito pelo pecado, um carneiro sem mancha para o sacrifício pacífico,

[[v4-6-15]]

^<<v4-6-15,15>>^ e também um cesto de pães ázimos, borrifados com azeite, e tortas sem fermento untadas de azeite, cada coisa com as suas libações.

[[v4-6-16]]

^<<v4-6-16,16>>^ O sacerdote as oferecerá diante do Senhor, e o fará tanto pelo pecado como em holocausto.

[[v4-6-17]]

^<<v4-6-17,17>>^ O carneiro, porém, imolá-lo-á ao Senhor em sacrifício pacifico, oferecendo ao mesmo tempo o cesto dos pães ázimos e as libações, que por costume se devem.

[[v4-6-18]]

^<<v4-6-18,18>>^ Então será rapado ao Nazareno o cabelo consagrado diante da porta do tabernáculo da reunião; (o sacerdote) tomará os seus cabelo e os porá no fogo, que está por baixo da vitima pacífica.

[[v4-6-19]]

^<<v4-6-19,19>>^ Porá nas mãos do Nazareno, depois de lhe ter sido rapada a cabeça, a espádua do carneiro cozida, uma torta ázima tirada do cesto e uma filhó ázima.

[[v4-6-20]]

^<<v4-6-20,20>>^ Recebidas dele estas coisas, as elevará diante do Senhor; assim santificadas, pertencerão ao sacerdote, como também o peito, que se mandou separar, e a perna: depois disto o Nazareno pode beber vinho.

[[v4-6-21]]

^<<v4-6-21,21>>^ Esta é a lei do Nazareno, quando tiver feito voto, esta a sua oferta ao Senhor no tempo da sua consagração, além daquilo que os seus meios lhe permitirem fazer. Procederá conforme o voto que tiver feito na sua mente, para tornar perfeita a sua santificação.

[[v4-6-22]]

^<<v4-6-22,22>>^ O Senhor falou a Moisés, dizendo:

[[v4-6-23]]

^<<v4-6-23,23>>^ Dize a Aarão e a seus filhos: Assim abençoareis os filhos de Israel; dir-lhe-eis:

[[v4-6-24]]

^<<v4-6-24,24>>^ O Senhor te abençoe, e te guarde.

[[v4-6-25]]

^<<v4-6-25,25>>^ O Senhor te mostre a sua face e tenha piedade de ti.

[[v4-6-26]]

^<<v4-6-26,26>>^ O Senhor volva o seu rosto pala ti, e te dê a paz.

[[v4-6-27]]

^<<v4-6-27,27>>^ Assim invocarão o meu nome sobre os filhos de Israel, e eu os abençoarei.

'''

xref:004-numeros/004-numeros-005.adoc#v4-5-0[&#60; Capítulo Anterior] | <<v4-6-0,Topo>> | xref:004-numeros/004-numeros-007.adoc#v4-7-0[Próximo Capítulo &#62;]