include::./index.adoc[]

[[v4-28-0]]
=== Números, 28
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Números 28 detalha as ofertas diárias e semanais que deveriam ser apresentadas a Deus pelos israelitas. As ofertas incluem sacrifícios de animais, ofertas de grãos e ofertas de vinho. As ofertas eram uma forma de os israelitas demonstrarem sua devoção a Deus e reconhecer sua dependência dele. Abaixo estão quatro versículos relacionados aos temas abordados em Números 28:
* Levítico 23:37-38: "Estes são os dias de reunião do Senhor, quando vocês convocarão assembleias sagradas e apresentarão ofertas queimadas ao Senhor, sacrifícios de cereal e ofertas de vinho derramado, cada um em seu dia designado. Além dos sábados do Senhor e além do que vocês já deram, ofereçam ao Senhor uma oferta para cumprir um voto ou como oferta voluntária." Este versículo faz referência às ofertas que os israelitas deveriam apresentar em dias sagrados, além das ofertas diárias e semanais mencionadas em Números 28.
* Salmos 51:16-17: "Pois não te deleitas em sacrifícios, do contrário eu os ofereceria; tu não te comprazes em holocaustos. Os sacrifícios que agradam a Deus são um espírito quebrantado; um coração quebrantado e contrito, ó Deus, não desprezarás." Este verso enfatiza que, embora as ofertas e sacrifícios fossem uma parte importante da adoração a Deus, o que mais importava era o coração e a disposição do adorador.
* Hebreus 10:11-14: "Dia após dia, todo sacerdote apresenta repetidamente os mesmos sacrifícios, que nunca podem tirar os pecados. Mas quando este sacerdote [Jesus] ofereceu um único sacrifício pelos pecados, ele se assentou à direita de Deus. [...] pois com um único sacrifício ele aperfeiçoou para sempre os que estão sendo santificados." Este verso faz referência ao sacrifício final de Jesus, que foi oferecido uma vez por todas e substituiu a necessidade de sacrifícios contínuos.
* Efésios 5:1-2: "Portanto, sigam o exemplo de Deus, como filhos amados, e vivam em amor, como Cristo nos amou e se entregou por nós como oferta e sacrifício de aroma agradável a Deus." Este verso destaca que a oferta final de Jesus foi a oferta perfeita e aceitável a Deus, simbolizada pelas ofertas de aroma agradável mencionadas em Números 28.
****

[[v4-28-1]]

^<<v4-28-1,1>>^ Disse também o Senhor a Moisés:

[[v4-28-2]]

^<<v4-28-2,2>>^ Manda aos filhos de Israel, dize-lhes: Apresentai no tempo determinado a minha oferta, o necessário para alimentar os sacrifícios pelo fogo, que são, para mim, de suave odor.

[[v4-28-3]]

^<<v4-28-3,3>>^ Estes são os sacrifícios que deveis oferecer: Todos os dias, dois cordeiros de um ano. Sem defeito, em holocausto perpétuo.

[[v4-28-4]]

^<<v4-28-4,4>>^ Oferecereis um pelo manhã, outro pela tarde:

[[v4-28-5]]

^<<v4-28-5,5>>^ a décima parte de um efa de flor de farinha, amassada na quarta parte de um hin de azeite puríssimo.

[[v4-28-6]]

^<<v4-28-6,6>>^ Este é o holocausto perpétuo que vós oferecestes sobre o monte Sinai, consumido pelo fogo, de suave odor ao Senhor.

[[v4-28-7]]

^<<v4-28-7,7>>^ Derramareis em libação a quarta parte de um hin de vinho por cada cordeiro no santuário do Senhor,

[[v4-28-8]]

^<<v4-28-8,8>>^ Oferecereis da mesma sorte à tarde o outro cordeiro, com todos os ritos do sacrifício da manhã e das suas libações; oferta de suave odor ao Senhor.

[[v4-28-9]]

^<<v4-28-9,9>>^ No diá de sábado oferecereis dois cordeiros de um ano sem defeito, duas dízimas de flor de farinha amassada com azeite para o sacrifício e as libações,

[[v4-28-10]]

^<<v4-28-10,10>>^ que segundo o rito se derramam todos os sábados em holocausto perpétuo.

[[v4-28-11]]

^<<v4-28-11,11>>^ No começo dos meses oferecereis ao Senhor em holocausto dois bezerros da manada, um carneiro, sete cordeiros de um ano, sem defeito,

[[v4-28-12]]

^<<v4-28-12,12>>^ e três dízimas de flor de farinha amassada com azeite por cada bezerro, e duas dízimas de flor de farinha amassada com azeite por cada carneiro,

[[v4-28-13]]

^<<v4-28-13,13>>^ e a dízima da dízima de flor de farinha amassada com azeite por cada carneiro. É um holocausto de suave odor, um sacrifício feito pelo fogo ao Senhor.

[[v4-28-14]]

^<<v4-28-14,14>>^ As libações de vinho, que se devem derramar sobre cada vítima, serão estas: Metade de um hin por cada bezerro, um terço pelo carneiro, um quarto pelo cordeiro; este será o holocausto de todos os meses, que se sucedem no decurso do ano.

[[v4-28-15]]

^<<v4-28-15,15>>^ Oferecer-se-á também ao Senhor em bode pelos pecados, em holocausto perpétuo, com as suas libações.

[[v4-28-16]]

^<<v4-28-16,16>>^ No primeiro mês, no dia catorze do mês, será a páscoa do Senhor:

[[v4-28-17]]

^<<v4-28-17,17>>^ no dia quinze a solenidade; durante sete dias se comerão pães ázimos.

[[v4-28-18]]

^<<v4-28-18,18>>^ No primeiro dia haverá santa assembleia, e não fareis nele obra alguma servil,

[[v4-28-19]]

^<<v4-28-19,19>>^ Oferecereis em sacrifício feito com fogo um holocausto ao Senhor dois bezerros da manada, um carneiro, sete cordeiros de um ano, sem defeito;

[[v4-28-20]]

^<<v4-28-20,20>>^ as ofertas, por cada um deles, de flor de farinha, que seja amassada com azeite, serão de três dízimas por cada bezerro, duas dízimas pelo carneiro,

[[v4-28-21]]

^<<v4-28-21,21>>^ uma dízima da dízima por cada cordeiro, isto é, por cada um dos sete cordeiros.

[[v4-28-22]]

^<<v4-28-22,22>>^ (Oferecerás também) um bode pelo pecado, para obterdes a expiação dele,

[[v4-28-23]]

^<<v4-28-23,23>>^ além do holocausto da manhã, que vós oferecereis sempre.

[[v4-28-24]]

^<<v4-28-24,24>>^ Assim fareis em cada um dos sete dias para alimento do fogo, e em suavíssimo cheiro ao Senhor, que se exalará do holocausto e das libações de cada vitima.

[[v4-28-25]]

^<<v4-28-25,25>>^ No sétimo dia haverá santa assembleia, e não fareis nele obra alguma ervil.

[[v4-28-26]]

^<<v4-28-26,26>>^ Também no dia das primícias, quando, completas as (sete) semanas, oferecerdes ao Senhor as novas messes, haverá santa assembleia, e não fareis nele obra alguma servil.

[[v4-28-27]]

^<<v4-28-27,27>>^ Oferecereis em holocausto de suave odor, ao Senhor, dois bezerros da manada, um carneiro e sete cordeiros de um ano, sem defeito,

[[v4-28-28]]

^<<v4-28-28,28>>^ e nos sacrifícios destes (oferecereis) três dízimas de flor de farinha borrifada com azeite por cada bezerro, duas por cada carneiro,

[[v4-28-29]]

^<<v4-28-29,29>>^ uma dízima pelos cordeiros, isto é, por cada um dos sete cordeiros; (oferecereis, também) um bode,

[[v4-28-30]]

^<<v4-28-30,30>>^ o qual será imolado pela expiação, além do holocausto perpétuo, e das suas libações.

[[v4-28-31]]

^<<v4-28-31,31>>^ Oferecereis todas estas coisas sem mancha, com as suas libações.

'''

xref:004-numeros/004-numeros-027.adoc#v4-27-0[&#60; Capítulo Anterior] | <<v4-28-0,Topo>> | xref:004-numeros/004-numeros-029.adoc#v4-29-0[Próximo Capítulo &#62;]