include::./index.adoc[]

[[v4-3-0]]
=== Números, 3
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Números 3 descreve a designação dos filhos de Levi como sacerdotes e sua atribuição a tarefas específicas no serviço do tabernáculo. Os filhos de Levi são separados do resto dos israelitas e designados para cuidar da tenda da reunião e de todos os objetos sagrados nela contidos. Abaixo estão cinco versículos relacionados aos temas abordados neste capítulo:
* Êxodo 6:16-19: "São estes os nomes dos filhos de Levi, segundo a ordem de seus nascimentos: Gérson, Coate e Merari. [...] O filho de Gérson foi Libni e Simei, e suas famílias. [...] O filho de Coate foi Anrão, Izar, Hebrom e Uziel, e suas famílias. [...] O filho de Merari foi Mali e Musi. Estas são as famílias dos levitas, segundo a ordem de seus nascimentos." Este versículo se relaciona com Números 3 em geral, que descreve a designação dos filhos de Levi para o serviço no tabernáculo.
* Êxodo 28:1: "Agora, chame seu irmão Arão e seus filhos para se juntarem a você, os quais serão escolhidos dentre os israelitas para servirem como sacerdotes, para se aproximarem de mim e me servirem." Este versículo se relaciona com Números 3:10, que especifica que apenas Arão e seus filhos serão designados como sacerdotes para o serviço no tabernáculo.
* Êxodo 30:12-13: "Quando fizer o recenseamento dos israelitas, cada um deles terá que dar ao Senhor uma moeda de prata, de acordo com o peso padrão do santuário [...] O dinheiro do resgate dos primogênitos deverá ser usado para o serviço do tabernáculo da tenda da reunião." Este versículo se relaciona com Números 3:12-13, que descreve como os primogênitos dos israelitas serão redimidos e como o dinheiro do resgate será usado no serviço do tabernáculo.
* Êxodo 25:9: "Construam para mim um santuário e eu habitarei no meio de vocês." Este versículo se relaciona com Números 3 em geral, que descreve como os levitas são designados para cuidar do tabernáculo, onde Deus habita no meio do povo de Israel.
* Êxodo 40:38: "Porque a nuvem do Senhor ficava sobre o tabernáculo durante o dia, e durante a noite havia fogo nele, à vista de todo o povo de Israel, em todas as suas jornadas." Este versículo se relaciona com Números 3 em geral, que descreve como os levitas são designados para cuidar do tabernáculo, onde Deus se manifesta em nuvem e fogo.
****

[[v4-3-1]]

^<<v4-3-1,1>>^ Estas são as gerações de Aarão e de Moisés, no dia em que o Senhor falou a Moisés no monte Sinai.

[[v4-3-2]]

^<<v4-3-2,2>>^ Estes são os nomes dos filhos de Aarão: Nadab, o seu primogénito, depois Abiu, Eleazar e Itamar.

[[v4-3-3]]

^<<v4-3-3,3>>^ Estes são os nomes dos filhos de Aarão, sacerdotes ungidos e consagrados para exercerem as funções do sacerdócio.

[[v4-3-4]]

^<<v4-3-4,4>>^ Nadab e Abiu, tendo oferecido um fogo estranho na presença do Senhor no deserto do Sinai, morreram sem filhos: Eleazar e Itamar exerceram as funções do sacerdócio na presença de seu pai Aarão.

[[v4-3-5]]

^<<v4-3-5,5>>^ O Senhor falou a Moisés, dizendo:

[[v4-3-6]]

^<<v4-3-6,6>>^ Faze aproximar a tribo de Levi, e fá-la comparecer diante do sacerdote Aarão para o servirem, estarem de vigia,

[[v4-3-7]]

^<<v4-3-7,7>>^ observarem tudo o que diz respeito ao culto da multidão diante do tabernáculo da reunião,

[[v4-3-8]]

^<<v4-3-8,8>>^ e para guardarem os vasos do tabernáculo servindo no seu ministério.

[[v4-3-9]]

^<<v4-3-9,9>>^ Darás os Levitas

[[v4-3-10]]

^<<v4-3-10,10>>^ a Aarão e aos seus filhos, aos quais os darás inteiramente, de entre os filhos de Israel. Estabelecerás Aarão e seus filhos nas funções do sacerdócio. O estranho, que se aproximar para ministrar, morrerá.

[[v4-3-11]]

^<<v4-3-11,11>>^ O Senhor falou a Moisés, dizendo:

[[v4-3-12]]

^<<v4-3-12,12>>^ Eu tomei os Levitas dentre os filhos de Israel em lugar de todo o primogénito, que abre o seio de sua mãe entre os filhos de Israel, e os Levitas serão meus,

[[v4-3-13]]

^<<v4-3-13,13>>^ porque todo o primogénito é meu. Desde o dia em que feri os primogénitos na terra do Egito, consagrei para mim todo o que nasce primeiro em Israel, desde o homem até ao animal. São meus. Eu sou o Senhor.

[[v4-3-14]]

^<<v4-3-14,14>>^ O Senhor falou a Moisés no deserto do Sinai, dizendo:

[[v4-3-15]]

^<<v4-3-15,15>>^ Numera os filhos de Levi segundo as casas de seus pais e as suas famílias, todos os varões de um mês para cima.

[[v4-3-16]]

^<<v4-3-16,16>>^ Moisés fez o recenseamento conforme o Senhor lhe tinha ordenado.

[[v4-3-17]]

^<<v4-3-17,17>>^ Eis os filhos de Levi, segundo os seus nomes: Gerson, Caath e Merari.

[[v4-3-18]]

^<<v4-3-18,18>>^ Filhos de Gerson: Lební e Semei.

[[v4-3-19]]

^<<v4-3-19,19>>^ Filhos de Caath: Amrão, Jesaar, Hebron e Oziel.

[[v4-3-20]]

^<<v4-3-20,20>>^ Filhos de Merari: Mooli e Musi.

[[v4-3-21]]

^<<v4-3-21,21>>^ De Gerson saíram duas famílias, a de Lebni, e a de Semei,

[[v4-3-22]]

^<<v4-3-22,22>>^ toda a população masculina das quais, contada de um mês para cima, foi de sete mil e quinhentos.

[[v4-3-23]]

^<<v4-3-23,23>>^ Estes acamparão detrás do tabernáculo ao ocidente,

[[v4-3-24]]

^<<v4-3-24,24>>^ sob o príncipe Eliasaph, filho de Lael.

[[v4-3-25]]

^<<v4-3-25,25>>^ Quanto ao tabernáculo da reunião, terão cuidado da tenda, da sua coberta, do véu que se corre diante da porta do tabernáculo da aliança,

[[v4-3-26]]

^<<v4-3-26,26>>^ das cortinas do átrio e também do véu que está pendurado à entrada do átrio do tabernáculo, e de tudo o que pertence ao ministério do altar, das cordas do tabernáculo e de todos os seus utensílios.

[[v4-3-27]]

^<<v4-3-27,27>>^ De Caath procedem as famílias dos Amramitas, Jesaaritas, Hebronitas e Ozielitas. Estas são as famílias provenientes de Caath, recenseadas segundo os seus nomes.

[[v4-3-28]]

^<<v4-3-28,28>>^ O censo de todos os varões, de um mês para cima, deu oito mil e seiscentos, que velarão pela guarda do santuário,

[[v4-3-29]]

^<<v4-3-29,29>>^ e acamparão na parte meridional.

[[v4-3-30]]

^<<v4-3-30,30>>^ O seu príncipe será Elisafan, filho de Oziel.

[[v4-3-31]]

^<<v4-3-31,31>>^ Guardarão a arca, a mesa, o candeeiro, os altares e os vasos do santuário, que servem para o ministério, e o véu, e todos os outros objetos deste gênero.

[[v4-3-32]]

^<<v4-3-32,32>>^ Eleázaro, filho do sacerdote Aarão, e príncipe dos príncipes dos Levitas, terá a superintendência sobre os que velam pela guarda do santuário.

[[v4-3-33]]

^<<v4-3-33,33>>^ De Merari sairam as famílias dos Moolitas e dos Musitas, recenseados segundo os seus nomes.

[[v4-3-34]]

^<<v4-3-34,34>>^ Os varões, de um mês para cima, somaram seis mil e duzentos.

[[v4-3-35]]

^<<v4-3-35,35>>^ O seu príncipe é Suriel, filho de Abiaiel; acamparão na parte setentrional.

[[v4-3-36]]

^<<v4-3-36,36>>^ Debaixo da sua guarda estarão as tábuas do tabernáculo, os varais, as colunas com suas bases, com tudo o que pertence a estas coisas,

[[v4-3-37]]

^<<v4-3-37,37>>^ e as colunas que cercam o átrio com as suas bases, as suas estacas e as suas cordas.

[[v4-3-38]]

^<<v4-3-38,38>>^ Moisés e Aarão com seus filhos acamparão diante do tabernáculo da reunião, ao oriente, e terão a guarda do santuário no meio dos filhos de Israel: todo o estranho que se aproximar morrerá.

[[v4-3-39]]

^<<v4-3-39,39>>^ Todos os Levitas, que Moisés e Aarão recensearam, por ordem do Senhor, segundo as suas famílias, entre os varões de um mês para cima, foram vinte e dois mil.

[[v4-3-40]]

^<<v4-3-40,40>>^ O Senhor disse a Moisés: Conta os primogênitos varões dos filhos de Israel, de um mês para cima, e farás a soma deles.

[[v4-3-41]]

^<<v4-3-41,41>>^ Tomarás para mim os Levitas em lugar de todos os primogênitos dos filhos de Israel. Eu sou o Senhor: (tomarei) os gados dos Levitas em vez de todos os primogênitos dos gados dos filhos de Israel.

[[v4-3-42]]

^<<v4-3-42,42>>^ Fez Moisés o recenseamento dos primogênitos dos filhos de Israel como o Senhor tinha ordenado.

[[v4-3-43]]

^<<v4-3-43,43>>^ Os varões, contados segundo os seus nomes, de um mês para cima, foram vinte e dois mil e duzentos e setenta e três.

[[v4-3-44]]

^<<v4-3-44,44>>^ O Senhor falou a Moisés, dizendo:

[[v4-3-45]]

^<<v4-3-45,45>>^ Toma os Levitas em vez dos primogénitos dos filhos de Israel, e os gados dos Levitas em vez dos seus gados. Os Levitas serão meus. Eu sou o Senhor.

[[v4-3-46]]

^<<v4-3-46,46>>^ Pelo preço dos duzentos e setenta e três primogênitos dos filhos de Israel, que excedem o número dos Levitas,

[[v4-3-47]]

^<<v4-3-47,47>>^ receberás cinco siclos por cabeça, segundo a medida do santuário. O siclo tem vinte óbulos.

[[v4-3-48]]

^<<v4-3-48,48>>^ Darás este dinheiro a Aarão e a seus filhos como preço dos primogénitos que ultrapassam o número dos Levitas;

[[v4-3-49]]

^<<v4-3-49,49>>^ Tomou, pois, Moisés o dinheiro por aqueles que ultrapassavam o número dos resgatados pelos Levitas,

[[v4-3-50]]

^<<v4-3-50,50>>^ tomou o dinheiro do resgate dos primogênitos dos filhos de Israel, mil trezentos e sessenta e cinco siclos segundo a medida do santuário,

[[v4-3-51]]

^<<v4-3-51,51>>^ e deu-o a Aarão e a seus filhos, conforme a ordem que o Senhor lhe tinha dado.

'''

xref:004-numeros/004-numeros-002.adoc#v4-2-0[&#60; Capítulo Anterior] | <<v4-3-0,Topo>> | xref:004-numeros/004-numeros-004.adoc#v4-4-0[Próximo Capítulo &#62;]