include::./index.adoc[]

[[v45-12-0]]
=== Zacarias, 12
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Zacarias 12 descreve a restauração de Jerusalém e o retorno de Deus para o seu povo. É um capítulo cheio de profecias e visões sobre o papel de Israel e de outras nações nos últimos dias. Aqui estão cinco versículos de diferentes livros da Bíblia que se relacionam com os temas abordados em Zacarias 12:
* Isaías 41:14: "Não temas, ó verme de Jacó, povozinho de Israel; eu te ajudo, diz o Senhor, e o teu redentor é o Santo de Israel." Este versículo traz conforto e segurança para Israel em meio a tempos difíceis, afirmando que Deus é o seu redentor e protetor.
* Ezequiel 37:21-22: "Dize-lhes pois: Assim diz o Senhor Deus: Eis que eu tomarei os filhos de Israel de entre os gentios, para onde eles foram, e os congregarei de todas as partes, e os levarei à sua terra; e deles farei uma nação na terra, nos montes de Israel, e um rei será rei de todos eles; e nunca mais serão duas nações, nem de maneira alguma se dividirão para o futuro em dois reinos." Este versículo fala da restauração de Israel como uma nação unida sob um único rei, uma profecia que se cumpre em Zacarias 12.
* Salmos 83:4: "Vinde, digamos-lhes, vamos destruí-los para que não sejam nação, e não haja mais memória do nome de Israel." Este versículo descreve a intenção de outras nações de destruir Israel, uma ameaça que é confrontada em Zacarias 12.
* Jeremias 30:18: "Assim diz o Senhor: Eis que trarei do cativeiro os cativos das tendas de Jacó, e apiedar-me-ei das suas moradas; a cidade será edificada sobre o seu montão, e o palácio ficará no seu devido lugar." Este versículo fala da restauração de Jerusalém, uma profecia que é cumprida em Zacarias 12.
* Apocalipse 1:7: "Eis que vem com as nuvens, e todo o olho o verá, até mesmo aqueles que o traspassaram; e todas as tribos da terra se lamentarão sobre ele. Certamente. Amém." Este versículo descreve a segunda vinda de Cristo, um evento que é referido em Zacarias 12:10.
****

[[v45-12-1]]

^<<v45-12-1,1>>^ Oráculo. Palavra do Senhor contra Israel. Palavra do Senhor, que estendeu o céu, fundou a terra e formou o espírito que o homem tem dentro de si:

[[v45-12-2]]

^<<v45-12-2,2>>^ Eis que farei de Jerusalém um copo inebriante para todos os povos circunvizinhos. Esta palavra é também para Judá, quando se cercar Jerusalém.

[[v45-12-3]]

^<<v45-12-3,3>>^ Naquele dia farei de Jerusalém uma pedra pesada para todos os povos; todos aqueles que a levantarem, ficarão magoados; coligar-se-ão contra ela todos os reinos da terra.

[[v45-12-4]]

^<<v45-12-4,4>>^ Naquele dia, diz o Senhor, ferirei de pasmo todos os cavalos, e de delírio os que montam neles; abrirei os meus olhos sobre a casa de Judá, mas ferirei de cegueira os cavalos de todos os povos.

[[v45-12-5]]

^<<v45-12-5,5>>^ Então dirão os chefes de Judá no seu coração; A força dos habitantes de Jerusalém reside no Senhor dos exércitos, seu Deus.

[[v45-12-6]]

^<<v45-12-6,6>>^ Naquele dia farei que os chefes de Judá sejam como um tição de fogo, que se mete debaixo da lenha, como um facho aceso entre a palha; devorarão à direita e à esquerda todos os povos circunvizinhos, e Jerusalém permanecerá firme no seu lugar.

[[v45-12-7]]

^<<v45-12-7,7>>^ O Senhor salvará as tendas de Judá, para que a altivez da casa de Davide e a dos habitantes de Jerusalém não se elevem em detrimento de Judá. (ver nota)

[[v45-12-8]]

^<<v45-12-8,8>>^ Naquele dia o Senhor protegerá os habitantes de Jerusalém: o mais fraco dentre eles será (tão valente) como Davide, e a casa de Davide surgirá aos olhos deles como Deus, como um anjo do Senhor.

[[v45-12-9]]

^<<v45-12-9,9>>^ Naquele dia procurarei esmagar todas as nações que vierem contra Jerusalém.

[[v45-12-10]]

^<<v45-12-10,10>>^ Derramarei sobre a casa de Davide e sobre os habitantes de Jerusalém um espírito de graça e de preces, e eles porão os olhos em mim. Quanto àquele que traspassaram, chorá-lo-ao com pranto, como se chora um filho único, terão dele um sentimento, como se costuma ter na morte de um primogênito.

[[v45-12-11]]

^<<v45-12-11,11>>^ Naquele dia haverá um grande pranto em Jerusalém, como o pranto de Adadremmon, no campo de Magedon. (ver nota)

[[v45-12-12]]

^<<v45-12-12,12>>^ A terra chorará, família por família: a família da casa de Davide à parte, com suas mulheres à parte; (ver nota)

[[v45-12-13]]

^<<v45-12-13,13>>^ a família da casa de Natan à parte, com suas mulheres à parte; a família da casa de Levi à parte, com suas mulheres à parte; a família de Semei à parte, com suas mulheres à parte;

[[v45-12-14]]

^<<v45-12-14,14>>^ todas as outras famílias (se lamentarão), família por família, com suas mulheres à parte.

'''

xref:045-zacarias/045-zacarias-011.adoc#v45-11-0[&#60; Capítulo Anterior] | <<v45-12-0,Topo>> | xref:045-zacarias/045-zacarias-013.adoc#v45-13-0[Próximo Capítulo &#62;]