include::./index.adoc[]

[[v45-9-0]]
=== Zacarias, 9
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Zacarias 9 fala sobre a profecia da vinda do Messias e a restauração de Jerusalém. É um capítulo que retrata uma visão futura para a cidade e para o povo de Deus. Abaixo estão cinco versículos relacionados aos temas abordados em Zacarias 9:
* Isaías 62:6: "Ó Jerusalém, pus sentinelas sobre teus muros, que jamais ficarão em silêncio, nem de dia nem de noite; vós, que deveis lembrar-vos do Senhor, não descanseis," Este versículo retrata a importância de manter a vigilância e a oração constante em Jerusalém. Isso se relaciona com a visão de Zacarias 9 de uma Jerusalém restaurada e fortalecida.
* Salmos 118:26-27: "Bendito o que vem em nome do Senhor! Nós vos bendizemos desde a casa do Senhor. O Senhor é Deus, e ele nos ilumina." Esses versículos são frequentemente associados à entrada triunfal de Jesus em Jerusalém, o que está em linha com a visão de Zacarias 9 de um rei vindo para a cidade.
* Jeremias 30:18: "Assim diz o Senhor: Eis que mudarei a sorte das tendas de Jacó, e compadecer-me-ei das suas habitações; a cidade será reedificada sobre o seu próprio monte, e o palácio real voltará a ser habitado como antigamente." Este versículo fala sobre a restauração da cidade de Jerusalém e a habitação do palácio real, o que é semelhante à visão de Zacarias 9 de uma Jerusalém fortalecida.
* Isaías 9:6: "Porque um menino nos nasceu, um filho se nos deu; o governo está sobre os seus ombros; e o seu nome será Maravilhoso Conselheiro, Deus Forte, Pai da Eternidade, Príncipe da Paz." Este versículo é frequentemente associado à vinda do Messias, que é um tema central em Zacarias 9.
* Isaías 52:7: "Como são formosos sobre os montes os pés do que anuncia as boas novas, que faz ouvir a paz, que anuncia coisas boas, que faz ouvir a salvação, que diz a Sião: O teu Deus reina!" Este versículo fala sobre a pregação das boas novas da salvação, o que é semelhante ao tema central de Zacarias 9 - a vinda do Messias e a restauração de Jerusalém.
****

[[v45-9-1]]

^<<v45-9-1,1>>^ Oráculo. A palavra do Senhor (pesa) sobre a terra de Hadrac, repousa em Damasco, porque ao Senhor pertencem as cidades de Aram, assim como todas vizinhas as tribos de Israel.

[[v45-9-2]]

^<<v45-9-2,2>>^ (Este oráculo é) também contra Hamat, que confina com Damasco e contra Tiro e Sidónia, apesar da sua sabedoria.

[[v45-9-3]]

^<<v45-9-3,3>>^ Tiro levantou as suas fortificações, amontoou prata como terra, e ouro como lama das ruas.

[[v45-9-4]]

^<<v45-9-4,4>>^ Eis que o Senhor se apoderará dela, precipitará a sua fortaleza no mar, e será devorada pelo fogo.

[[v45-9-5]]

^<<v45-9-5,5>>^ Ascalon verá isto e ficará a tremer; vê-lo-á também Gaza e ficará possuída de intensa dor; Acaron se afligirá, porque foi enganada a sua esperança; em Gaza não haverá mais rei, e Ascalon ficará despovoada. (ver nota)

[[v45-9-6]]

^<<v45-9-6,6>>^ O estrangeiro (conquistador) terá a sua residência em Azot, e eu destruirei a soberba dos Filisteus.

[[v45-9-7]]

^<<v45-9-7,7>>^ Tirarei da boca deste povo o sangue, e as suas abominações dentre os seus dentes; ele também será um resto para o nosso Deus, será como uma família em Judá; Acaron será tratado como um Jebuseu. (ver nota)

[[v45-9-8]]

^<<v45-9-8,8>>^ Acamparei em volta da minha casa, guardando-a das idas e vindas (do inimigo); o opressor não passará mais por aí, porque eu olho agora para ela com olhos favoráveis.

[[v45-9-9]]

^<<v45-9-9,9>>^ Salta de alegria, ó filha de Sião, enche-te de júbilo, ó filha de Jerusalém. Eis que o teu rei vem a ti, justo e vitorioso; ele é humilde e vem montado sobre um jumento, sobre o potrinho duma jumenta. (ver nota)

[[v45-9-10]]

^<<v45-9-10,10>>^ Então exterminarei os carros de guerra de Efraim e os cavalos de Jerusalém; os arcos que servem na guerra serão quebrados. Ele anunciará a paz às nações; o seu poder se estenderá de um mar até ao outro mar, desde o rio até às extremidades da terra.

[[v45-9-11]]

^<<v45-9-11,11>>^ Quanto a ti, também, por causa do sangue da tua aliança, farei sair os teus cativos da fossa em que não há água. (ver nota)

[[v45-9-12]]

^<<v45-9-12,12>>^ Tornai para a vossa praça forte, ó cativos (cheios) de esperança: hoje também vos anuncio que vos darei dobrados bens.

[[v45-9-13]]

^<<v45-9-13,13>>^ Porque reteso Judá como um arco, ponho Efraim como flecha; suscitarei os teus filhos, ó Sião, contra os teus filhos, ó Grécia; e te farei (irresistível) como a espada dos valentes. (ver nota)

[[v45-9-14]]

^<<v45-9-14,14>>^ O Senhor Deus aparecerá sobre eles (os Judeus), e a sua flecha partirá como relâmpago; O Senhor Deus os animará pelo som da trombeta e marchará entre as borrascas do meio-dia. (ver nota)

[[v45-9-15]]

^<<v45-9-15,15>>^ O Senhor dos exércitos os protegerá; eles devorarão (os seus inimigos) e os sujeitarão com as pedras das suas fundas; bebendo (o seu sangue), se embriagarão como com vinho, ficarão cheios como os copos e como os ângulos do altar.

[[v45-9-16]]

^<<v45-9-16,16>>^ O Senhor seu Deus os salvará naquele dia, como rebanho do seu povo; à maneira de pedras santas, brilharão sobre a sua terra.

[[v45-9-17]]

^<<v45-9-17,17>>^ Que felicidade, que beleza a dele! O trigo dará crescimento aos jovens, e o vinho novo às virgens. (ver nota)

'''

xref:045-zacarias/045-zacarias-008.adoc#v45-8-0[&#60; Capítulo Anterior] | <<v45-9-0,Topo>> | xref:045-zacarias/045-zacarias-010.adoc#v45-10-0[Próximo Capítulo &#62;]