include::./index.adoc[]

[[v45-14-0]]
=== Zacarias, 14
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 14 de Zacarias trata da vinda do Senhor para julgar todas as nações da terra e estabelecer seu reino na Terra. Será um dia de trevas e de grande terremoto, mas também será um dia de esperança para os que crêem no Senhor. Aqui estão cinco versículos relacionados com os temas abordados em Zacarias 14:
* Isaías 2:4: "Ele julgará entre as nações e resolverá as disputas de muitos povos. De suas espadas, forjarão arados e de suas lanças, foices. Nenhuma nação levantará a espada contra a outra, nem aprenderão mais a guerrear." Este verso fala sobre o julgamento do Senhor sobre as nações da terra, o que é um tema importante em Zacarias 14. A paz que ele trará também é mencionada, indicando a estabilização do reinado de Deus.
* Salmos 97:5: "As montanhas se derretem como cera diante do Senhor, diante do Soberano de toda a terra." Este verso fala sobre a presença majestosa do Senhor e sua capacidade de destruir tudo o que se opõe a ele, o que é relevante para o grande terremoto e a escuridão mencionados em Zacarias 14.
* Malaquias 3:2: "Mas quem suportará o dia da sua vinda? Quem ficará em pé quando ele aparecer? Porque ele será como o fogo do ourives e como o sabão dos lavandeiros." Este verso descreve a vinda do Senhor e a intensidade do julgamento que ele trará, o que está em sintonia com os temas de Zacarias 14.
* Mateus 24:29: "Imediatamente após a tribulação daqueles dias, 'o sol escurecerá, a lua não dará a sua luz, as estrelas cairão do céu e os poderes dos céus serão abalados'". Este verso é uma referência direta a Zacarias 14:6-7, que descreve um dia de escuridão e terremoto. É uma confirmação da autenticidade das profecias de Zacarias.
* Apocalipse 22:5: "Não haverá mais noite. Eles não precisarão de luz de lamparina ou de luz do sol, pois o Senhor Deus os iluminará. Eles reinarão para todo o sempre." Este verso é uma referência ao reinado de Deus na terra, que é o tema final de Zacarias 14. É um lembrete da esperança que os crentes têm de um futuro glorioso na presença do Senhor.
****

[[v45-14-1]]

^<<v45-14-1,1>>^ Eis que está a chegar um dia do Senhor, em que os teus despojos serão divididos, no meio de ti.

[[v45-14-2]]

^<<v45-14-2,2>>^ Juntarei todas as nações para darem batalha contra Jerusalém: a cidade será tomada, as casas serão destruídas, as mulheres violadas; metade da cidade irá para o cativeiro, mas o resto do povo não será lançado fora da cidade.

[[v45-14-3]]

^<<v45-14-3,3>>^ Depois sairá o Senhor e pelejará contra aquelas nações, como peleja no dia do combate. (ver nota)

[[v45-14-4]]

^<<v45-14-4,4>>^ Nesse dia os seus pés pausarão sobre o monte das Oliveiras, que está defronte de Jerusalém para o oriente, e o monte das Oliveiras dividir-se-á em dois pelo meio, ao oriente e ao ocidente, formando uma muito grande abertura: uma metade do monte se separará para o setentrião, e a outra metade para o meio-dia.

[[v45-14-5]]

^<<v45-14-5,5>>^ Fugireis para o vale das minhas montanhas, porque o vale das montanhas chegará até Asai; fugireis como fugistes do terramoto nos dias de Ozias, rei de Judá. E virá o Senhor meu Deus, com todos os santos (para punir os inimigos do seu povo).

[[v45-14-6]]

^<<v45-14-6,6>>^ E naquele dia não haverá luz, nem frio nem gelo.

[[v45-14-7]]

^<<v45-14-7,7>>^ Será um dia contínuo, conhecido (somente) do Senhor, sem alternativas de dia e de noite: pela tarde não cessará a luz.

[[v45-14-8]]

^<<v45-14-8,8>>^ Nesse dia sairão de Jerusalém águas vivas, metade das quais correrá para o mar do oriente, e a outra metade para o mar do ocidente; correrão durante o estio e durante o inverno. (ver nota)

[[v45-14-9]]

^<<v45-14-9,9>>^ E o Senhor será o rei de toda a terra; naquele dia, Iavé será o único e o seu nome será único.

[[v45-14-10]]

^<<v45-14-10,10>>^ Toda a terra (de Judá) será transformada numa planície, desde Gabaa até Rimmon, ao meio-dia de Jerusalém. (Jerusalém) será exaltada e ocupará o seu lugar, desde a porta de Benjamim até ao sítio da antiga porta, até à porta do Ângulo, e desde a torre de Hananeel até aos lagares do rei.

[[v45-14-11]]

^<<v45-14-11,11>>^ Será habitada e não tornará mais a ser ferida de anátema; Jerusalém será habitada com segurança.

[[v45-14-12]]

^<<v45-14-12,12>>^ A praga com que o Senhor ferirá todas as nações que combaterem contra Jerusalém será esta: Apodrecerá a sua carne, enquanto (ainda) andarem de pé, apodrecer-lhes-ão os olhos dentro das suas órbitas, e apodrecer-lhes-á a língua dentro da boca.

[[v45-14-13]]

^<<v45-14-13,13>>^ Naquele dia haverá grande pânico entre eles excitado pelo Senhor; cada um pegará na mão do seu próximo, levantarão a mão uns contra os outros.

[[v45-14-14]]

^<<v45-14-14,14>>^ Também Judá pelejará em Jerusalém; juntar-se-ão as riquezas de todas as nações circunvizinhas: ouro, prata e roupa em grande abundância. (ver nota)

[[v45-14-15]]

^<<v45-14-15,15>>^ Os cavalos, os machos, os camelos, os asnos e todos os animais que se acharem naqueles arraiais, sofrerão a mesma ruína.

[[v45-14-16]]

^<<v45-14-16,16>>^ Todos os que restarem de todas as nações que vierem contra Jerusalém, irão (a ela) todos os anos adorar o Rei, Senhor dos exércitos, e celebrar a festa dos tabernáculos.

[[v45-14-17]]

^<<v45-14-17,17>>^ Qualquer das famílias da terra, que não for a Jerusalém adorar o Rei, Senhor dos exércitos, não receberá chuva.

[[v45-14-18]]

^<<v45-14-18,18>>^ Se a família do Egipto não subir nem vier, não cairá sobre ela (a chuva), mas será ferida da ruína, com que o Senhor atingirá todas as nações que não subirem a celebrar a festa dos tabernáculos. (ver nota)

[[v45-14-19]]

^<<v45-14-19,19>>^ Este será o (castigo do) pecado do Egipto, este o (castigo do) pecado de todas as nações que não subirem para celebrar a festa dos tabernáculos.

[[v45-14-20]]

^<<v45-14-20,20>>^ Naquele dia se verá (escrito) nas campainhas dos cavalos: Consagrado ao Senhor. As marmitas na casa do Senhor serão como vasos de aspersão diante do altar.

[[v45-14-21]]

^<<v45-14-21,21>>^ Todas as caldeiras que houver em Jerusalém e em Judá serão consagradas ao Senhor dos exércitos; virão todos os sacrificadores e se servirão delas para nelas cozerem (as carnes consagradas); naquele dia não tornará mais a haver mercador na casa do Senhor dos exércitos. (ver nota)

'''

xref:045-zacarias/045-zacarias-013.adoc#v45-13-0[&#60; Capítulo Anterior] | <<v45-14-0,Topo>> | xref:046-malaquias/046-malaquias-001.adoc#v46-1-0[Próximo Capítulo &#62;]