include::./index.adoc[]

[[v26-6-0]]
=== Cântico dos Cânticos, 6
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Cânticos 6 continua a narrativa do amor entre o noivo e a noiva, destacando a beleza e a atração mútua entre eles. O capítulo começa com a noiva procurando pelo seu amado e, ao encontrá-lo, expressando sua admiração por sua beleza. Em seguida, há uma descrição detalhada da aparência física da noiva, exaltando sua beleza. Abaixo estão cinco versículos relacionados aos temas abordados em Cânticos 6:
* Cânticos 4:7 - "Você é toda linda, minha querida; em você não há defeito algum." Esse verso fala sobre a beleza da noiva, assim como a descrição detalhada em Cânticos 6.
* Provérbios 31:30 - "A beleza é enganosa, e a formosura é passageira; mas a mulher que teme o Senhor será elogiada." Este verso destaca a importância de uma beleza interior que é mais valiosa do que a beleza física.
* 1 Samuel 16:7 - "Mas o Senhor disse a Samuel: Não considere sua aparência nem sua altura, pois eu o rejeitei. O Senhor não vê como o homem vê. O homem vê a aparência, mas o Senhor vê o coração." Este verso mostra que Deus valoriza o coração das pessoas acima de sua aparência.
* Isaías 52:7 - "Como são belos, nos montes, os pés do que traz boas-novas, do que anuncia a paz, do que traz boas-novas de alegria e salvação, e diz a Sião: ‘O seu Deus reina!’” Este verso fala sobre a beleza daqueles que pregam o evangelho, trazendo alegria e salvação.
* 1 Pedro 3:3-4 - "Não seja a beleza exterior a principal qualidade de vocês, como cabelos arrumados, jóias de ouro ou vestidos finos. Ao contrário, seja a interior, que não perece, a beleza de um espírito calmo e tranqüilo, o que é de grande valor para Deus." Esse verso destaca a importância de uma beleza interior que é duradoura, em oposição à beleza física que desvanece com o tempo.
****

[[v26-6-1]]

^<<v26-6-1,1>>^ O meu amado desceu ao seu jardim, ao canteiro dos balsameiros para apascentar o seu rebanho nos jardins, e para colher lírios.

[[v26-6-2]]

^<<v26-6-2,2>>^ Eu sou do meu amado, e o meu amado é meu, ele, que apascenta o seu rebanho entre os lírios. (ver nota)

[[v26-6-3]]

^<<v26-6-3,3>>^ Formosa és, amiga minha, como Tirsa, encantadora como Jerusalém, mas terrível como um exército em ordem de batalha.

[[v26-6-4]]

^<<v26-6-4,4>>^ Aparta os teus olhos de mim, porque eles me fascinam. Os teus cabelos são como um rebanho de cabras, suspensas nas vertentes dos montes de Galaad.

[[v26-6-5]]

^<<v26-6-5,5>>^ Os teus dentes são como rebanho de ovelhas, ao subir do lavadouro; cada uma leva dois cordeirinhos gémeos, e nenhuma entre elas é estéril. (ver nota)

[[v26-6-6]]

^<<v26-6-6,6>>^ Como metades de romãs, assim são as tuas faces, por detrás do teu véu.

[[v26-6-7]]

^<<v26-6-7,7>>^ São sessenta as rainhas, oitenta as esposas de segunda ordem, e inumeráveis as donzelas. (ver nota)

[[v26-6-8]]

^<<v26-6-8,8>>^ Porém uma só é a minha pomba, a minha perfeita: ela é a única para sua mãe, a predilecta da que lhe deu o ser. As donzelas viram-na, e proclamaram-na bem-aventurada: viram-na as rainhas e as esposas da segunda ordem, e deram-lhe muitos louvores.

[[v26-6-9]]

^<<v26-6-9,9>>^ Quem é esta, que vai caminhando como a aurora quando se levanta, formosa como a lua, brilhante como o sol, terrível como um exército formado em batalha?

[[v26-6-10]]

^<<v26-6-10,10>>^ Eu desci ao jardim das nogueiras, para ver a vegetação do vale, para examinar se a vinha tinha lançado flor, se as romãs tinham florido.

[[v26-6-11]]

^<<v26-6-11,11>>^ Eu não soube: a minha alma colocou-me sobre o carro de Aminadab.

[[v26-6-12]]

^<<v26-6-12,12>>^ Volta, volta, ó Sulamita; volta, volta, para que nós te contemplemos.

'''

xref:026-cantico-dos-canticos/026-cantico-dos-canticos-005.adoc#v26-5-0[&#60; Capítulo Anterior] | <<v26-6-0,Topo>> | xref:026-cantico-dos-canticos/026-cantico-dos-canticos-007.adoc#v26-7-0[Próximo Capítulo &#62;]