include::./index.adoc[]

[[v18-16-0]]
=== Judite, 16
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Judite 16 narra o canto de Judite após sua vitória sobre o general assírio Holofernes. Ela agradece a Deus por ter lhe dado força e coragem para vencer o inimigo de seu povo. Os versículos selecionados a seguir estão relacionados com a gratidão e o louvor a Deus pela sua ajuda e proteção.
* Salmos 66:19-20: "Mas Deus me ouviu; atendeu à minha oração. Bendito seja Deus, que não rejeitou a minha oração nem afastou de mim o seu amor!" Este salmo fala da gratidão a Deus por ter ouvido e respondido às orações daqueles que o buscam.
* Salmos 118:21: "Eu te agradeço porque me respondeste e foste a minha salvação." Este salmo também expressa a gratidão a Deus por ter respondido às orações e concedido a salvação.
* Salmos 144:1-2: "Bendito seja o Senhor, minha rocha, que adestrou minhas mãos para a batalha e meus dedos para a guerra. Ele é meu amor leal, minha fortaleza e minha torre alta, meu libertador, meu escudo, em quem me refugio. Ele submete a mim os povos." Este salmo fala sobre a ajuda de Deus em momentos de batalha e conflito.
* Isaías 25:1: "Ó Senhor, tu és o meu Deus; exaltar-te-ei e louvarei o teu nome, porque fizeste coisas maravilhosas; os teus conselhos antigos são verdade e firmeza." Este versículo expressa a adoração a Deus por suas obras maravilhosas e seus planos perfeitos.
* 2 Samuel 22:47: "Viva o Senhor, meu rochedo! Bendito seja o meu Deus, o rochedo da minha salvação!" Este versículo mostra a confiança em Deus como a fonte da salvação e da força em tempos difíceis.
****

[[v18-16-1]]

^<<v18-16-1,1>>^ Então cantou Judit ao Senhor este cântico:

[[v18-16-2]]

^<<v18-16-2,2>>^ Louvai o Senhor ao som dos tambores, cantai o Senhor ao som de címbalos, entoai-lhe um cântico novo, exaltai e invocai o seu nome.

[[v18-16-3]]

^<<v18-16-3,3>>^ O Senhor é quem põe fim às guerras. O Senhor é seu nome.

[[v18-16-4]]

^<<v18-16-4,4>>^ Ele pôs o seu acampamento no meio do seu povo, para nos livrar da mão de todos os nossos inimigos.

[[v18-16-5]]

^<<v18-16-5,5>>^ O Assírio veio dos montes, da parte do aquilão, com a multidão dos seus guerreiros; sua multidão obstruiu as torrentes, e os seus cavalos cobriam os vales.

[[v18-16-6]]

^<<v18-16-6,6>>^ Ele jurou que havia de queimar o meu país, que havia de passar ao fio da espada os meus jovens, que havia de dar em presa as minhas crianças, que havia de levar cativas as minhas donzelas.

[[v18-16-7]]

^<<v18-16-7,7>>^ Porém o Senhor todo poderoso o feriu e o entregou nas mãos duma mulher, que lhe tirou a vida.

[[v18-16-8]]

^<<v18-16-8,8>>^ O seu herói não foi prostrado ás mãos de jovens (guerreiros), nem o feriram os filhos de Titan, nem se lhe opuseram corpulentos gigantes, Mas Judit, filha de Merari, o derrubou com a formosura do seu rosto.

[[v18-16-9]]

^<<v18-16-9,9>>^ Ela se despiu do traje de viúva, e se ataviou com os vestidos de alegria, para o triunfo dos filhos de Israel.

[[v18-16-10]]

^<<v18-16-10,10>>^ Ela ungiu o seu rosto com perfumes, entrançou os seus cabelos sob um turbante e revestiu-se dum vestido novo para o seduzir.

[[v18-16-11]]

^<<v18-16-11,11>>^ As suas sandálias arrebataram-lhe os olhos, a sua beleza cativou-lhe a alma, e ela cortou-lhe a cabeça com o alfange.

[[v18-16-12]]

^<<v18-16-12,12>>^ Os Persas tremeram diante da sua valentia, os Medos diante da sua ousadia.

[[v18-16-13]]

^<<v18-16-13,13>>^ O acampamento dos Assírios ressoou em alaridos, quando apareceram os meus pobres (concidadãos) abrasados de sede.

[[v18-16-14]]

^<<v18-16-14,14>>^ Os filhos das jovens esposas traspassaram-nos, mataram-nos (sem resistência) como a meninos que fogem: pereceram no combate diante da face do Senhor meu Deus.

[[v18-16-15]]

^<<v18-16-15,15>>^ Cantemos um hino ao Senhor, cantemos um novo hino ao nosso Deus.

[[v18-16-16]]

^<<v18-16-16,16>>^ Adonai, Senhor, tu és grande, magnífico no teu poder, e ninguém pode superar-te.

[[v18-16-17]]

^<<v18-16-17,17>>^ Todas as tuas criaturas te obedeçam, porque tu falaste, e foram feitas; enviaste o teu espírito, e foram criadas, e ninguém resiste à tua voz.

[[v18-16-18]]

^<<v18-16-18,18>>^ Os montes e as águas são abalados desde os fundamentos, as pedras, qual cera, se derretem diante da tua face,

[[v18-16-19]]

^<<v18-16-19,19>>^ porém aqueles que vos temem, são grandes diante de ti em todas as coisas.

[[v18-16-20]]

^<<v18-16-20,20>>^ Ai da nação que se levantar contra o meu povo! porque o Senhor omnipotente se vingará dela, e a visitará no dia do juízo.

[[v18-16-21]]

^<<v18-16-21,21>>^ Ele enviará fogo e vermes sobre as suas carnes, para arderem e para sentirem (este suplício) eternamente.

[[v18-16-22]]

^<<v18-16-22,22>>^ Todo o povo, depois da vitória, foi a Jerusalém adorar o Senhor. Logo que se purificaram, todos ofereceram os seus holocaustos, cumprindo os seus votos e as suas promessas.

[[v18-16-23]]

^<<v18-16-23,23>>^ Judit ofereceu, em anátema de esquecimento, todos os instrumentos de guerra de Holofernes, que o povo lhe tinha dado, e o cortinado que ela mesma tinha tirado do leito dele.

[[v18-16-24]]

^<<v18-16-24,24>>^ O povo esteve em grande regozijo diante do santuário, e a alegria desta vitória foi celebrada com Judit por espaço de três meses.

[[v18-16-25]]

^<<v18-16-25,25>>^ Passados aqueles dias, cada um voltou para sua casa; Judit ficou sendo célebre em Betúlia, e com grande renome em toda a terra de Israel.

[[v18-16-26]]

^<<v18-16-26,26>>^ A coragem juntava a castidade, de tal sorte que nunca em todos os dias da sua vida conheceu outro homem, desde que morreu Manassés, seu marido.

[[v18-16-27]]

^<<v18-16-27,27>>^ Nos dias de festa aparecia em público com todos os seus Adornos.

[[v18-16-28]]

^<<v18-16-28,28>>^ Morou na casa de seu marido até à idade de cento e cinco anos, e deu a liberdade à sua escrava; morreu e foi sepultada em Betúlia com seu marido.

[[v18-16-29]]

^<<v18-16-29,29>>^ Todo o povo a chorou durante sete dias.

[[v18-16-30]]

^<<v18-16-30,30>>^ Em todo o tempo de sua vida, e muitos anos depois da sua morte, não houve quem perturbasse Israel.

[[v18-16-31]]

^<<v18-16-31,31>>^ O dia da festividade desta vitória foi posto pelo Hebreus na classe dos dias santos, e desde aquele tempo até hoje é festejado pelos judeus.

'''

xref:018-judite/018-judite-015.adoc#v18-15-0[&#60; Capítulo Anterior] | <<v18-16-0,Topo>> | xref:019-ester/019-ester-001.adoc#v19-1-0[Próximo Capítulo &#62;]