include::./index.adoc[]

[[v54-12-0]]
=== II Coríntios, 12
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 12 de 2 Coríntios fala sobre a experiência sobrenatural de Paulo de ter sido levado ao terceiro céu e a fim de não se gloriar demasiadamente, ele foi atormentado com um "espinho na carne". Além disso, Paulo defende sua autoridade apostólica e encoraja os coríntios a se arrependerem e se reconciliarem com Deus.
* 2 Coríntios 12:2-4: "Conheço um homem em Cristo que, há catorze anos, foi arrebatado até o terceiro céu. Se foi no corpo ou fora do corpo, não sei, Deus o sabe. E sei que esse homem – se no corpo ou fora dele, não sei, mas Deus o sabe –" Paulo fala de sua própria experiência sobrenatural de ter sido levado ao terceiro céu, mas não está certo se foi em corpo ou espírito.
* 2 Coríntios 12:7: "Para impedir que eu me exaltasse por causa da grandeza dessas revelações, foi-me dado um espinho na carne, um mensageiro de Satanás, para me atormentar." Paulo menciona seu "espinho na carne", que é uma fonte de grande sofrimento, mas que Deus permitiu para mantê-lo humilde.
* 2 Coríntios 12:9: "Mas ele me disse: “Minha graça é suficiente para você, pois o meu poder se aperfeiçoa na fraqueza”. Portanto, eu me gloriarei ainda mais alegremente em minhas fraquezas, para que o poder de Cristo repouse em mim." Deus responde a Paulo dizendo que Sua graça é suficiente para lidar com seu "espinho na carne", e que Seu poder é aperfeiçoado na fraqueza.
* 2 Coríntios 12:10: "Por isso, por amor de Cristo, regozijo-me nas fraquezas, nos insultos, nas necessidades, nas perseguições, nas angústias. Pois, quando sou fraco, é que sou forte." Paulo diz que, em vez de ficar desanimado com suas fraquezas e dificuldades, ele se alegra nelas porque é quando a força de Cristo é mais visível em sua vida.
* 2 Coríntios 12:19: "Será que vocês pensam que temos estado nos justificando diante de vocês? É diante de Deus que temos falado em Cristo, e tudo o que fazemos, amigos amados, é para edificá-los." Paulo reafirma sua autoridade apostólica e seu compromisso de edificar a igreja de Corinto em Cristo.
****

[[v54-12-1]]

^<<v54-12-1,1>>^ Se importa que alguém se glorie, o que não convém na verdade, farei agora menção das visões e das revelações do Senhor.

[[v54-12-2]]

^<<v54-12-2,2>>^ Conheço um homem em Cristo, o qual há catorze anos foi arrebatado, não sei se no corpo, se fora do corpo, (Deus o sabe) até ao terceiro céu. (ver nota)

[[v54-12-3]]

^<<v54-12-3,3>>^ E sei que este homem (se foi no corpo, se fora do corpo, não o sei, Deus o sabe)

[[v54-12-4]]

^<<v54-12-4,4>>^ foi arrebatado ao paraíso e ouviu palavras inefáveis que não é lícito (ou possível) a um homem proferi-las (explicando-as).

[[v54-12-5]]

^<<v54-12-5,5>>^ Relativamente a este homem me gloriarei, mas, quanto a mim, de nada me gloriarei, senão das minhas fraquezas. (ver nota)

[[v54-12-6]]

^<<v54-12-6,6>>^ Verdade é que, se me quiser gloriar, não serei insensato, porque direi a verdade; porém, abstenho-me disso, para que ninguém julgue de mim mais do que vê em mim ou ouve de mim.

[[v54-12-7]]

^<<v54-12-7,7>>^ E, para que a grandeza das revelações me não ensoberbecesse, foi-me dado o estímulo da minha carne, (que é como) um anjo de Satanás, que me esbofeteie, a fim de não me orgulhar. (ver nota)

[[v54-12-8]]

^<<v54-12-8,8>>^ Por cuja causa roguei ao Senhor três vezes que ele se apartasse de mim,

[[v54-12-9]]

^<<v54-12-9,9>>^ mas disse-me: "Basta-te a minha graça, porque é na fraqueza que o (meu) poder se manifesta por completo." Portanto, de boa vontade me gloriarei nas minhas fraquezas, para que habite em mim o poder de Cristo.

[[v54-12-10]]

^<<v54-12-10,10>>^ Por isso, sinto complacência nas minhas, enfermidades, nas afrontas, nas necessidades, nas perseguições, nas angústias por amor de Cristo, porque, quando estou fraco (quanto às forças da natureza), então sou forte (na graça).

[[v54-12-11]]

^<<v54-12-11,11>>^ Tornei-me insensato (falando de mim mesmo), mas fostes vós que me obrigastes a isso. De facto, era por vós que eu devia ser louvado, pois que em nada fui inferior a esses super-apóstolos, ainda que (por mim) nada sou:

[[v54-12-12]]

^<<v54-12-12,12>>^ entre vós contudo foram realizados os sinais do meu apostolado em toda a paciência, nos milagres, nos prodígios e atos de poder.

[[v54-12-13]]

^<<v54-12-13,13>>^ Porque, em que tendes sido inferiores às outras igrejas, excepto que em nada vos fui pesado? Perdoai-me esta injúria.

[[v54-12-14]]

^<<v54-12-14,14>>^ Eis que, pela terceira vez, estou disposto a ir ter convosco, e (também agora) não vos serei pesado, porque não busco as vossas coisas, mas a vós. Pois que não são os filhos que devem entesourar para os pais, mas os pais, para os filhos.

[[v54-12-15]]

^<<v54-12-15,15>>^ E eu de mui boa vontade darei o que é meu e me darei a mim pelas vossas almas, ainda que, amando-vos eu mais, seja por vós menos amado.

[[v54-12-16]]

^<<v54-12-16,16>>^ Mas seja assim (direis vós)! Eu (confirmo o que vos disse) não vos fui pesado, porém, como sou astuto (segundo dizem os meus adversários), tomei-vos por dolo.

[[v54-12-17]]

^<<v54-12-17,17>>^ Porventura por meio de algum daqueles que vos enviei, tirei de vós algum proveito?

[[v54-12-18]]

^<<v54-12-18,18>>^ Roguei a Tito e enviei com ele um irmão. Porventura Tito explorou-vos? Não andamos com o mesmo espírito? Não seguimos as mesmas pisadas?

[[v54-12-19]]

^<<v54-12-19,19>>^ Cuidais, desde há muito, que nos justificamos diante de vós. É diante de Deus, em Cristo, que falamos ; e tudo, meus muito amados, para vossa edificação.

[[v54-12-20]]

^<<v54-12-20,20>>^ Pois temo que, quando eu for, vos não encontre quais vos quero, e que vós me acheis qual não quereis; (temo) que haja entre vós contendas, invejas, rixas, dissenções, detrações, mexericos, soberbas, sedições ;

[[v54-12-21]]

^<<v54-12-21,21>>^ (temo) que, quando eu for outra vez, me humilhe Deus, entre vós, e que tenha de chorar a muitos daqueles que antes pecaram e não fizeram penitência da impureza, fornicação e dissolução que cometeram.

'''

xref:054-ii-corintios/054-ii-corintios-011.adoc#v54-11-0[&#60; Capítulo Anterior] | <<v54-12-0,Topo>> | xref:054-ii-corintios/054-ii-corintios-013.adoc#v54-13-0[Próximo Capítulo &#62;]