include::./index.adoc[]

[[v20-31-0]]
=== Jó, 31
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* No capítulo 31 de Jó, o personagem faz uma declaração solene de inocência, afirmando ter evitado todos os tipos de pecados, especialmente aqueles relacionados à luxúria e à injustiça. Ele se justifica diante de seus amigos e de Deus, afirmando que não merece a punição que está sofrendo. Os versículos relacionados com os temas abordados em Jó 31 são:
* Provérbios 6:25: "Não cobices no teu coração a sua formosura, nem te deixes prender pelos seus olhares." Jó afirma que não cobiçou a formosura de outras mulheres, nem se deixou prender pela tentação da luxúria.
* Mateus 5:28: "Eu, porém, vos digo que qualquer que olhar para uma mulher com intenção impura, em seu coração, já adulterou com ela." Jó afirma que não olhou para nenhuma mulher com intenção impura.
* Êxodo 22:21: "Ao estrangeiro não o afligirás, nem o oprimirás, pois estrangeiros fostes na terra do Egito." Jó afirma que não oprimiu nenhum estrangeiro, mas antes, ajudou a todos que precisavam de ajuda.
* Jó 24:2: "Há os que mudam os limites, roubam rebanhos e os apascentam." Jó afirma que não mudou os limites de ninguém nem roubou rebanhos.
* Isaías 33:15: "O que anda em justiça, e o que fala com retidão; o que rejeita o ganho da opressão, o que sacode das suas mãos todo o presente; o que tapa os seus ouvidos para não ouvir falar de sangue, e fecha os seus olhos para não ver o mal." Jó afirma que andou em justiça, falou com retidão e rejeitou o ganho da opressão.
****

[[v20-31-1]]

^<<v20-31-1,1>>^ Fiz pacto com os meus olhos de não olhar (cobiçosamente) para uma virgem.

[[v20-31-2]]

^<<v20-31-2,2>>^ Porque (doutra sorte), que comunicação teria comigo Deus lá de cima, ou que parte me daria o Omnipotente da sua celestial herança?

[[v20-31-3]]

^<<v20-31-3,3>>^ Porventura não está estabelecida a perdição para o malvado, e a desventura para os que praticam a injustiça?

[[v20-31-4]]

^<<v20-31-4,4>>^ Porventura não considera ele os meus caminhos, e não conta todos os meus passos?

[[v20-31-5]]

^<<v20-31-5,5>>^ Se caminhei na falsidade, se o meu pé se apressou para o engano,

[[v20-31-6]]

^<<v20-31-6,6>>^ pese-me Deus em sua balança justa, e conhecerá a minha integridade.

[[v20-31-7]]

^<<v20-31-7,7>>^ Se os meus pés se desviaram do (bom) caminho, se o meu coração seguiu os meus olhos, se às minhas mãos se pegou qualquer mácula,

[[v20-31-8]]

^<<v20-31-8,8>>^ semeie eu, e outro o coma. e sejam as minhas plantações arrancadas.

[[v20-31-9]]

^<<v20-31-9,9>>^ Se o meu coração foi seduzido por uma mulher, e se andei a vigiar (para cometer adultério) à porta do meu amigo,

[[v20-31-10]]

^<<v20-31-10,10>>^ seja minha mulher desonrada por outro, seja entregue à paixão de outros.

[[v20-31-11]]

^<<v20-31-11,11>>^ Porque este é um pecado vergonhoso, uma grave maldade,

[[v20-31-12]]

^<<v20-31-12,12>>^ é um fogo que consome até ao extermínio, e que destruiria todo o bem que juntei.

[[v20-31-13]]

^<<v20-31-13,13>>^ Se eu desprezei as razões do meu servo ou da minha serva, quando eles disputavam contra mim,

[[v20-31-14]]

^<<v20-31-14,14>>^ que será de mim quando Deus se levantar para me julgar? Quando me interrogar, que lhe responderei?

[[v20-31-15]]

^<<v20-31-15,15>>^ Porventura o que me formou no ventre materno não o criou também a ele, e não foi o mesmo Deus que nos formou no ventre materno?

[[v20-31-16]]

^<<v20-31-16,16>>^ Porventura neguei aos pobres o que pediam, e deixei desfalecer os olhos da viúva,

[[v20-31-17]]

^<<v20-31-17,17>>^ ou comi sózinho o meu bocado de pão, e o órfão não comeu dele?

[[v20-31-18]]

^<<v20-31-18,18>>^ Com efeito, desde a minha infância cresceu comigo a comiseração, e do ventre de minha mãe saiu comigo.

[[v20-31-19]]

^<<v20-31-19,19>>^ Se desprezei o que perecia, porque não linha de que vestir-se, e o pobre que não tinha com que cobrir-se,

[[v20-31-20]]

^<<v20-31-20,20>>^ se os seus membros me não abençoaram, ele _(o pobre)- não se aqueceu com a lã das minhas ovelhas;

[[v20-31-21]]

^<<v20-31-21,21>>^ se levantei a minha mão contra o órfão, ainda quando me via superior, (administrando justiça) à porta (da cidade),

[[v20-31-22]]

^<<v20-31-22,22>>^ caia o meu ombro da sua juntura, e quebre-se o meu braço com os seus ossos.

[[v20-31-23]]

^<<v20-31-23,23>>^ Porque eu sempre temi a mão de Deus, e nunca pude suportar o peso da sua majestade.

[[v20-31-24]]

^<<v20-31-24,24>>^ Não julguei que o ouro era a minha força, não disse ao ouro mais puro: tu és a minha confiança;

[[v20-31-25]]

^<<v20-31-25,25>>^ não me alegrei com as minhas grandes riquezas, com os grandes bens que juntei pela minha mão;

[[v20-31-26]]

^<<v20-31-26,26>>^ Se via o sol quando brilhava, e a lua quando caminhava na sua claridade (considerando-os como deuses),

[[v20-31-27]]

^<<v20-31-27,27>>^ porventura o meu coração sentiu algum oculto contentamento, e beijei a minha mão com a minha boca (em sinal de adoração)?

[[v20-31-28]]

^<<v20-31-28,28>>^ Isso seria uma grandíssima iniquidade, seria renunciar ao Deus altíssimo.

[[v20-31-29]]

^<<v20-31-29,29>>^ Acaso me alegrei com a ruína daquele que odiava, e exultei com o mal que lhe sobreveio?

[[v20-31-30]]

^<<v20-31-30,30>>^ (Não, não foi assim), pois, não permiti que a minha língua pecasse, demandando com imprecações a sua morte.

[[v20-31-31]]

^<<v20-31-31,31>>^ Acaso as pessoas da minha casa não diziam: Quem há que se não tenha saciado (com o pão) da sua mesa?

[[v20-31-32]]

^<<v20-31-32,32>>^ O peregrino não passava a noite fora, a minha porta estava sempre aberta ao viandante.

[[v20-31-33]]

^<<v20-31-33,33>>^ Nunca encobri, como homem, o meu pecado, ocultando no meu coração a minha iniquidade,

[[v20-31-34]]

^<<v20-31-34,34>>^ por temor da grande assembleia, ou com receio do desprezo dos meus parentes, a ponto de me conservar em silêncio, sem sair da minha porta.

[[v20-31-35]]

^<<v20-31-35,35>>^ Quem me dera um que (desapaixonadamente) me ouvisse! Eis a minha assinatura: que o Omnipotente me responda! Que o meu adversário escreva também o seu libelo de acusação!

[[v20-31-36]]

^<<v20-31-36,36>>^ Levá-lo-ei sobre os meus ombros, e cingirei a minha fronte com ele, como com um diadema!

[[v20-31-37]]

^<<v20-31-37,37>>^ Cada um dos meus passos contarei (a Deus, meu juiz), e apresentar-me-ia a ele, (sem receio) como um príncipe.

[[v20-31-38]]

^<<v20-31-38,38>>^ (Finalmente) se a terra que eu possuo clama contra mim. e se os seus sulcos choram com ela,

[[v20-31-39]]

^<<v20-31-39,39>>^ se comi seus frutos sem pagamento, se afligi o coração dos que a cultivaram,

[[v20-31-40]]

^<<v20-31-40,40>>^ ela me produza abrolhos em lugar de trigo, e espinhos em lugar de cevada. (Findaram as palavras de Job).

'''

xref:020-jo/020-jo-030.adoc#v20-30-0[&#60; Capítulo Anterior] | <<v20-31-0,Topo>> | xref:020-jo/020-jo-032.adoc#v20-32-0[Próximo Capítulo &#62;]