include::./index.adoc[]

[[v20-36-0]]
=== Jó, 36
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Jó 36 é um capítulo em que Eliú continua a falar com Jó sobre a justiça de Deus e a necessidade de confiar nele, mesmo em meio às dificuldades. Eliú enfatiza a soberania de Deus e sua sabedoria, e argumenta que os sofrimentos de Jó são uma correção divina para seu orgulho e pecado. Ele também enfatiza a necessidade de arrependimento e submissão a Deus.
* Provérbios 3:11-12: "Filho meu, não desprezes a correção do SENHOR, nem desmaies quando por ele fores repreendido; porque o SENHOR repreende aquele a quem ama, assim como o pai ao filho a quem quer bem." Assim como Eliú argumenta que os sofrimentos de Jó são uma correção divina, este versículo de Provérbios enfatiza a importância de aceitar a correção do Senhor, pois isso é um sinal de amor e cuidado.
* Salmos 119:75: "Bem sei eu, ó SENHOR, que os teus juízos são justos, e que em tua fidelidade me afligiste." Eliú argumenta que os sofrimentos de Jó são justos e destinados a corrigi-lo, e este verso do Salmo 119 mostra um reconhecimento semelhante da justiça e fidelidade de Deus, mesmo em meio à aflição.
* Tiago 4:10: "Humilhai-vos perante o Senhor, e ele vos exaltará." Eliú enfatiza a necessidade de Jó se humilhar diante de Deus e arrepender-se de qualquer orgulho ou pecado, e este verso em Tiago também enfatiza a importância da humildade diante de Deus.
* Salmos 147:5: "Grande é o nosso Senhor, e de grande poder; o seu entendimento é infinito." Eliú enfatiza a sabedoria e o conhecimento de Deus, e este verso do Salmo 147 também destaca a grandeza e a infinitude do entendimento divino.
* Provérbios 16:19: "Melhor é ser humilde de espírito com os mansos, do que repartir o despojo com os soberbos." Eliú enfatiza a necessidade de humildade e submissão a Deus, e este verso em Provérbios também destaca a importância da humildade em geral, em contraste com o orgulho dos soberbos.
****

[[v20-36-1]]

^<<v20-36-1,1>>^ Eliú, continuando, disse:

[[v20-36-2]]

^<<v20-36-2,2>>^ Suporta-me um pouco, e eu me explicarei contigo, porque ainda tenho que falar em defesa de Deus.

[[v20-36-3]]

^<<v20-36-3,3>>^ Tornarei a pegar no discurso desde o principio, e provarei que o meu criador é justo.

[[v20-36-4]]

^<<v20-36-4,4>>^ Verdadeiramente os meus discursos são sem mentira; far-te-ei ver que a (minha) doutrina é sólida.

[[v20-36-5]]

^<<v20-36-5,5>>^ Deus é poderoso, mas não desdenhoso. é poderoso pela sua ciência,

[[v20-36-6]]

^<<v20-36-6,6>>^ Não deixa florescer os ímpios, e faz justiça aos pobres.

[[v20-36-7]]

^<<v20-36-7,7>>^ Não tirará (nunca) os seus olhos dos justos, e, ao fim, os colocará, com os reis, sobre o trono, numa glória eterna.

[[v20-36-8]]

^<<v20-36-8,8>>^ E, se estiverem em cadeias, atados com os laços da pobreza,

[[v20-36-9]]

^<<v20-36-9,9>>^ ele lhes fará ver as suas obras, as suas maldades, cometidas por orgulho.

[[v20-36-10]]

^<<v20-36-10,10>>^ Abrir-lhes-ã os ouvidos à correção e lhes falará para que se convertam da sua iniquidade.

[[v20-36-11]]

^<<v20-36-11,11>>^ Se ouvirem e obedecerem, acabarão os seus dias na felicidade, os seus anos em delícias.

[[v20-36-12]]

^<<v20-36-12,12>>^ Porém, se não ouvirem, serão passados à espada, e perecerão na sua cegueira.

[[v20-36-13]]

^<<v20-36-13,13>>^ Os corações impios entregam-se à cólera, não clamam a Deus, quando se vêem aprisionados.

[[v20-36-14]]

^<<v20-36-14,14>>^ Morrerão em plena juventude, e a sua vida acabará como a dos dissolutos.

[[v20-36-15]]

^<<v20-36-15,15>>^ Pelo contrário Deus livra o pobre, pela sua angústia, e abre-lhe o ouvido com a tribulação,

[[v20-36-16]]

^<<v20-36-16,16>>^ Ele te salvará (ó Job) do abismo estreito da angústia e te porá ao largo, em plena liberdade, (se te converteres), e tu repousarás à tua mesa cheia de gordas viandas.

[[v20-36-17]]

^<<v20-36-17,17>>^ Mas se seguires as vias do impio, suportarás a sentença e o castigo.

[[v20-36-18]]

^<<v20-36-18,18>>^ Não te leve, pois, a ira, ao arrebatamento, nem te faça desanimar a grandeza da expiação.

[[v20-36-19]]

^<<v20-36-19,19>>^ Poderá tirar-te da angústia o teu clamor, e todos os teus vigorosos esforços?

[[v20-36-20]]

^<<v20-36-20,20>>^ Não suspires pela noite (da morte), na qual entram os povos, um após outro.

[[v20-36-21]]

^<<v20-36-21,21>>^ Guarda-te de declinares para a iniquidade, ainda que a abraçasses, levado pela miséria.

[[v20-36-22]]

^<<v20-36-22,22>>^ Olha como Deus é excelso na sua fortaleza. Quem, como ele, é terrível?

[[v20-36-23]]

^<<v20-36-23,23>>^ Quem lhe prescreveu normas de conduta? Ou quem poderá dizer-lhe: Tu fizeste mal?

[[v20-36-24]]

^<<v20-36-24,24>>^ Lembra-te que deves celebrar a sua obra, a qual tantos homens cantaram.

[[v20-36-25]]

^<<v20-36-25,25>>^ Todos os homens o vêem, mas cada um o vê de longe.

[[v20-36-26]]

^<<v20-36-26,26>>^ Com efeito. Deus é grande e ultrapassa toda a nossa ciência, o número dos seus anos é incalculável.

[[v20-36-27]]

^<<v20-36-27,27>>^ Ele atrai as gotas de água, e derrama-as em (forma de) chuva, na cerração.

[[v20-36-28]]

^<<v20-36-28,28>>^ Caem dás nuvens, abundantemente sobre os homens.

[[v20-36-29]]

^<<v20-36-29,29>>^ Quem compreende a extensão das nuvens, os fragores do pavilhão (do Altíssimo)?

[[v20-36-30]]

^<<v20-36-30,30>>^ Ele estende em volta de si a sua luz desde o alto, e cobre as extremidades do mar.

[[v20-36-31]]

^<<v20-36-31,31>>^ Por meio destas coisas exerce os seus juízos sobre os povos, e alimenta abundantemente os mortais (fecundando a terra),

[[v20-36-32]]

^<<v20-36-32,32>>^ Nas suas mãos esconde a luz, e manda-lhe que torne de novo.

[[v20-36-33]]

^<<v20-36-33,33>>^ Faz conhecer a quem ama, que ele é possessão sua, e que pode subir até ela. (ver nota)

'''

xref:020-jo/020-jo-035.adoc#v20-35-0[&#60; Capítulo Anterior] | <<v20-36-0,Topo>> | xref:020-jo/020-jo-037.adoc#v20-37-0[Próximo Capítulo &#62;]