include::./index.adoc[]

[[v20-23-0]]
=== Jó, 23
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Em Jó 23, Jó expressa sua angústia e desejo de encontrar Deus, mas sente que Ele está inacessível. Jó clama por um julgamento justo e acredita que, se ele pudesse comparecer diante de Deus, ele seria justificado. Abaixo estão cinco versículos relacionados aos temas abordados em Jó 23:
* Salmos 139:7-10: "Para onde poderia eu escapar do teu Espírito? Para onde poderia fugir da tua presença? Se subisse aos céus, lá estarias; se fizesse a minha cama na sepultura, também lá estarias. Se eu subisse com as asas da alvorada e fosse morar nos confins do mar, mesmo ali a tua mão direita me guiará e me susterá." Este versículo mostra que Deus está sempre presente, em todos os lugares e situações, e que não há lugar onde possamos escapar de Sua presença.
* Isaías 55:6: "Buscai ao Senhor enquanto se pode achar, invocai-o enquanto está perto." Este versículo enfatiza a importância de buscarmos a Deus enquanto podemos encontrá-lo e invocá-lo enquanto Ele está próximo.
* Deuteronômio 4:29: "Mas se dali buscares ao Senhor teu Deus, o acharás, se o buscares de todo o teu coração e de toda a tua alma." Este versículo fala sobre a importância de buscar a Deus de todo o coração e de toda a alma, e que se O buscarmos assim, O encontraremos.
* Salmos 34:18: "Perto está o Senhor dos que têm o coração quebrantado e salva os de espírito oprimido." Este versículo fala sobre a proximidade de Deus com aqueles que têm o coração quebrantado e espírito oprimido, mostrando que Ele está presente em tempos de angústia.
* Hebreus 4:16: "Cheguemos, pois, com confiança ao trono da graça, para que possamos alcançar misericórdia e achar graça, a fim de sermos ajudados em tempo oportuno." Este versículo nos encoraja a nos aproximarmos do trono da graça de Deus com confiança, para que possamos encontrar misericórdia e graça em tempos de necessidade.
****

[[v20-23-1]]

^<<v20-23-1,1>>^ Respondendo Job, disse:

[[v20-23-2]]

^<<v20-23-2,2>>^ Sim, hoje são cheias de amargura as minhas palavras, mas a violência da minha chaga é mais grave que os meus gemidos.

[[v20-23-3]]

^<<v20-23-3,3>>^ Quem me dera saber encontrar Deus, e chegar até ao seu trono!

[[v20-23-4]]

^<<v20-23-4,4>>^ Exporia ante ele a minha causa, e encheria a minha boca de argumentos.

[[v20-23-5]]

^<<v20-23-5,5>>^ Saberia o que ele me responderia, ouviria o que ele tivesse para me dizer.

[[v20-23-6]]

^<<v20-23-6,6>>^ Não quero que com muita fortaleza contenda comigo, nem que me oprima com o peso da sua grandeza.

[[v20-23-7]]

^<<v20-23-7,7>>^ Proponha contra mim a equidade, e a minha causa obtenha a vitória.

[[v20-23-8]]

^<<v20-23-8,8>>^ Se eu for ao Oriente, não aparece; se ao Ocidente, não o encontrarei. (ver nota)

[[v20-23-9]]

^<<v20-23-9,9>>^ Se o busco ao norte, não o acho, se, ao sul, não o descubro.

[[v20-23-10]]

^<<v20-23-10,10>>^ Mas ele conhece o meu caminho; se me provar, sairei puro como o ouro.

[[v20-23-11]]

^<<v20-23-11,11>>^ O meu pé seguiu as suas pisadas, eu guardei o seu caminho, e não me desviei dele.

[[v20-23-12]]

^<<v20-23-12,12>>^ Não me apartei dos preceitos de seus lábios, escondi no meu seio as palavras da sua boca,

[[v20-23-13]]

^<<v20-23-13,13>>^ Porém, quando decide uma coisa, ninguém pode frustrar os seus desígnios; e a sua vontade realiza o que quer.

[[v20-23-14]]

^<<v20-23-14,14>>^ Assim cumprirá em mim a sua vontade, e ainda tem à mão outros muitos projetos semelhantes.

[[v20-23-15]]

^<<v20-23-15,15>>^ Por isso eu estou turbado na sua presença, e, quando o considero, sou agitado de temor.

[[v20-23-16]]

^<<v20-23-16,16>>^ Deus tirou a coragem ao meu coração, e o Omnipotente me aterrou.

[[v20-23-17]]

^<<v20-23-17,17>>^ Realmente não são as trevas que me fazem perecer, nem a escuridão (das tribulações) de que está coberto o meu rosto.

'''

xref:020-jo/020-jo-022.adoc#v20-22-0[&#60; Capítulo Anterior] | <<v20-23-0,Topo>> | xref:020-jo/020-jo-024.adoc#v20-24-0[Próximo Capítulo &#62;]