include::./index.adoc[]

[[v20-8-0]]
=== Jó, 8
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Em Jó 8, o amigo de Jó, Bildade, continua a argumentar que a aflição de Jó é resultado de seu pecado e que a solução é se arrepender e buscar a Deus. Bildade também enfatiza que Deus é justo e recompensará os justos. Os versículos relacionados com os temas abordados em Jó 8 são:
* Jó 4:7-9: "Lembra-te, pois: quem jamais pereceu, sendo inocente? Ou quando foram os justos destruídos? Como eu tenho visto, os que lavram iniquidade e semeiam o mal segam essas coisas. Pelo sopro de Deus perecem, e pela ventania da sua ira são consumidos."
Este versículo reflete a crença de Bildade de que a aflição de Jó é resultado de seu pecado e que apenas os ímpios sofrem.
* Provérbios 11:18: "O perverso faz obra falsa, mas para o que semeia justiça haverá galardão fiel."
Bildade enfatiza que Deus recompensa os justos e pune os ímpios, o que é refletido neste versículo de Provérbios.
* Isaías 55:7: "Deixe o ímpio o seu caminho, e o homem maligno os seus pensamentos, e se converta ao Senhor, que se compadecerá dele; torne para o nosso Deus, porque grandioso é em perdoar."
Bildade sugere que a solução para a aflição de Jó é se arrepender e buscar a Deus, o que é enfatizado neste versículo de Isaías.
* Tiago 5:11: "Eis que temos por bem-aventurados os que sofreram. Ouvistes qual foi a paciência de Jó e vistes o fim que o Senhor lhe deu; porque o Senhor é muito misericordioso e piedoso."
Este versículo destaca a paciência de Jó e sua recompensa final, o que contradiz a crença de Bildade de que apenas os ímpios sofrem.
* 1 João 1:9: "Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda a injustiça."
Este versículo reflete a crença de Bildade de que a solução para a aflição de Jó é se arrepender e buscar a Deus, mas também enfatiza a misericórdia e a justiça de Deus em perdoar os pecados.
****

[[v20-8-1]]

^<<v20-8-1,1>>^ Mas Baldad de Suhé tomou a palavra e disse:

[[v20-8-2]]

^<<v20-8-2,2>>^ Até quando dirás tu semelhantes coisas, e as palavras da tua boca serão um vento impetuoso?

[[v20-8-3]]

^<<v20-8-3,3>>^ Porventura Deus perverte os seus juízos, ou o Omnipotente subverte a justiça?

[[v20-8-4]]

^<<v20-8-4,4>>^ Se teus filhos pecaram contra ele, abandonou-os ao poder da própria iniquidade.

[[v20-8-5]]

^<<v20-8-5,5>>^ Contudo, se tu recorreres prontamente a Deus. e, humilde, rogares ao Omnipotente.

[[v20-8-6]]

^<<v20-8-6,6>>^ se caminhares com pureza e retidão, logo despertará para te acudir. e fará prosperar a morada da tua justiça,

[[v20-8-7]]

^<<v20-8-7,7>>^ de tal sorte que os teus primeiros bens parecerão pequenos, de tão grandes que hão-de ser os últimos.

[[v20-8-8]]

^<<v20-8-8,8>>^ Interroga, pois, as gerações passadas, examina com cuidado as memórias de nossos pais.

[[v20-8-9]]

^<<v20-8-9,9>>^ - Com efeito, nós somos de ontem, e somos uns ignorantes, porquanto os nossos dias sobre a terra passam como a sombra. -

[[v20-8-10]]

^<<v20-8-10,10>>^ Eles te instruirão, te falarão, e do seu coração tirarão as suas sentenças:

[[v20-8-11]]

^<<v20-8-11,11>>^ Porventura um papiro pode crescer fora do paul? Pode crescer um junco sem água? (ver nota)

[[v20-8-12]]

^<<v20-8-12,12>>^ Quando está ainda verde, sem que mão alguma lhe toque, seca antes que as outras ervas.

[[v20-8-13]]

^<<v20-8-13,13>>^ Assim é a sorte de todos os que se esquecem de Deus, assim perecerá a esperança do ímpio.

[[v20-8-14]]

^<<v20-8-14,14>>^ Será despedaçada a sua esperança, a sua confiança será como a teia de aranha.

[[v20-8-15]]

^<<v20-8-15,15>>^ Ele se apoia sobre a sua casa, que se não segura, apega-se a ela, que não tem consistência.

[[v20-8-16]]

^<<v20-8-16,16>>^ (O ímpio é como) uma planta que se mostra fresca antes de vir o sol; quando ele nasce, brotará o seu rebento (da terra).

[[v20-8-17]]

^<<v20-8-17,17>>^ A s suas raízes se multiplicarão entre um montão de pedras, e ficará entre penhascos.

[[v20-8-18]]

^<<v20-8-18,18>>^ Se alguém a arrancar do seu lugar, este a desconhecerá e dirá: Não te conheço.

[[v20-8-19]]

^<<v20-8-19,19>>^ Eis onde termina o seu destino; outros, igualmente, brotarão da terra, em seu lugar.

[[v20-8-20]]

^<<v20-8-20,20>>^ Deus não rejeita o homem sincero, nem dá a mão aos malvados.

[[v20-8-21]]

^<<v20-8-21,21>>^ Um dia encherá a tua boca de riso, e os teus lábios de júbilo.

[[v20-8-22]]

^<<v20-8-22,22>>^ Os que te aborrecem, serão cobertos de confusão; e a casa dos impios não subsistirá.

'''

xref:020-jo/020-jo-007.adoc#v20-7-0[&#60; Capítulo Anterior] | <<v20-8-0,Topo>> | xref:020-jo/020-jo-009.adoc#v20-9-0[Próximo Capítulo &#62;]