include::./index.adoc[]

[[v20-42-0]]
=== Jó, 42
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Jó 42 conclui a narrativa do livro de Jó, onde Jó se arrepende e reconhece a soberania e justiça de Deus. Ele pede perdão por ter falado do que não entendia e intercede em favor de seus amigos. Deus então repreende os amigos de Jó e os instrui a pedir perdão a Jó por terem falado mal dele.
* Provérbios 17:10: "A repreensão penetra mais profundamente no prudente do que cem açoites no tolo." Neste versículo, vemos que a repreensão tem mais impacto em uma pessoa sábia do que a punição em um tolo. Esse princípio se aplica à situação dos amigos de Jó, que são repreendidos por Deus por falarem mal dele.
* Tiago 5:16: "Confessai as vossas culpas uns aos outros e orai uns pelos outros, para que sareis. A oração feita por um justo pode muito em seus efeitos." Este versículo destaca a importância da confissão e oração em relação à cura. Jó intercede por seus amigos, mostrando que ele está disposto a perdoá-los.
* Provérbios 16:18: "A soberba precede a ruína, e a altivez do espírito precede a queda." Esse versículo é aplicável a Jó, que se arrepende de ter falado demais e se humilha diante de Deus. Ele reconhece sua pequenez e dependência de Deus.
* Mateus 6:14-15: "Porque, se perdoardes aos homens as suas ofensas, também vosso Pai celestial vos perdoará a vós; se, porém, não perdoardes aos homens as suas ofensas, tampouco vosso Pai vos perdoará as vossas ofensas." Este versículo enfatiza a importância do perdão. Jó perdoa seus amigos e intercede por eles, mostrando sua disposição em seguir os princípios de Deus.
* 2 Coríntios 5:17: "Assim que, se alguém está em Cristo, nova criatura é; as coisas velhas já passaram; eis que tudo se fez novo." Este versículo destaca a mudança radical que pode ocorrer na vida de alguém que se arrepende e confia em Deus. Jó experimenta essa transformação em sua vida, depois de passar por suas aflições e ter um encontro pessoal com Deus.
****

[[v20-42-1]]

^<<v20-42-1,1>>^ Respondendo Job ao Senhor, disse:

[[v20-42-2]]

^<<v20-42-2,2>>^ Sei que podes tudo, e que nenhum projeto é, para ti, demasiado difícil.

[[v20-42-3]]

^<<v20-42-3,3>>^ Quem é este que, falto de ciência, encobre o conselho (de Deus)? (Confesso que) falei nèsciamente, sobre coisas que me ultrapassam e que eu ignoro.

[[v20-42-4]]

^<<v20-42-4,4>>^ "Ouve, e eu falarei, interrogar-te-ei, e responder-me-às."

[[v20-42-5]]

^<<v20-42-5,5>>^ Os meus ouvidos haviam escutado falar de ti, mas agora os meus próprios olhos te vêem. (ver nota)

[[v20-42-6]]

^<<v20-42-6,6>>^ Por isso acuso-me a mim mesmo, e faço penitência no pó e na cinza.

[[v20-42-7]]

^<<v20-42-7,7>>^ O Senhor, depois que falou naquela sorte de Job, disse a Elifaz de Teman: O meu furor se acendeu contra ti e contra os teus dois amigos, porque vós não falastes de mim, retamente, como falou o meu servo Job.

[[v20-42-8]]

^<<v20-42-8,8>>^ Tomai, pois, sete touros e sete carneiros, e ide ao meu servo Job. Oferecei um holocausto por vós; o meu servo Job orará por vós. Admitirei propicio a sua intercessão para que se vos não impute esta estulticia, porque vós não falastes de mim o que era recto, como o meu servo Job.

[[v20-42-9]]

^<<v20-42-9,9>>^ Foram pois, Elifaz de Teman, Baldad de Subé, e Sofar de Naama, e fizeram como o Senhor lhes tinha dito, e o Senhor atendeu a Job.

[[v20-42-10]]

^<<v20-42-10,10>>^ O Senhor também se deixou mover à vista da penitência de Job, quando orava pelos seus amigos, e deu-lhe o duplo de tudo o que ele antes possuía,

[[v20-42-11]]

^<<v20-42-11,11>>^ Foram ter com ele todos os seus irmãos, todas as suas irmãs e todos os que antes o tinham conhecido, comeram com ele em sua casa. Moveram sobre ele a cabeça (em sinal de terna compaixão) e consolaram-no de todas as tribulações que o Senhor lhe tinha enviado. Cada um deles deu-lhe uma peça de prata e um anel de ouro.

[[v20-42-12]]

^<<v20-42-12,12>>^ E o Senhor abençoou Job no seu último estado muito mais do que no primeiro. Job chegou a ter catorze mil ovelhas, seis mil camelos, mil juntas de bois e mil jumentas.

[[v20-42-13]]

^<<v20-42-13,13>>^ Teve também sete filhos e três filhas.

[[v20-42-14]]

^<<v20-42-14,14>>^ A ’ primeira pôs o nome de Jemima, à segunda o de Ketsia, e à terceira Kereu-Happouk.

[[v20-42-15]]

^<<v20-42-15,15>>^ Não houve em toda a terra mulheres tão formosas como as filhas de Job, e seu pai deu-lhes herança entre seus irmãos.

[[v20-42-16]]

^<<v20-42-16,16>>^ Depois disto viveu Job cento e quarenta anos, e viu seus filhos e os filhos de seus filhos até à quarta geração. Depois morreu, velho e saciado de dias.

'''

xref:020-jo/020-jo-041.adoc#v20-41-0[&#60; Capítulo Anterior] | <<v20-42-0,Topo>> | xref:021-salmos/021-salmos-001.adoc#v21-1-0[Próximo Capítulo &#62;]