include::./index.adoc[]

[[v20-18-0]]
=== Jó, 18
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Jó 18 apresenta o segundo discurso de Bildade, em que ele continua argumentando que a punição de Jó é resultado de seu próprio pecado. Ele descreve a destruição que virá sobre os ímpios e como suas vidas serão arruinadas. Os versículos abaixo são relacionados aos temas abordados em Jó 18:
* Jó 8:13: "Tais são as sendas de todos os que se esquecem de Deus; e a esperança do ímpio perecerá." Bildade acredita que a situação de Jó é resultado de sua falta de lembrança de Deus e de sua esperança ímpia.
* Provérbios 14:32: "No seu mal o ímpio é derribado, mas os justos até na morte têm refúgio." Bildade fala da destruição que virá sobre os ímpios, que serão derrubados em seu mal.
* Salmos 1:4-5: "Os ímpios não são assim; são, porém, como a palha que o vento dispersa. Por isso os ímpios não subsistirão no juízo, nem os pecadores na congregação dos justos." Bildade descreve a destruição que virá sobre os ímpios e sua incapacidade de subsistir no juízo.
* Isaías 8:22: "E olharão para a terra, e eis aí a angústia e escuridão, e sombras de tristeza; e serão empurrados para a escuridão." Bildade fala da escuridão que virá sobre os ímpios e como eles serão empurrados para ela.
* Salmos 35:8: "Caia sobre ele a destruição que não espera, e apanhe-o a rede que escondeu, caia ele na mesma destruição." Bildade fala sobre como a destruição virá sobre os ímpios de uma maneira que não esperam e como eles cairão na mesma destruição que prepararam.
****

[[v20-18-1]]

^<<v20-18-1,1>>^ Respondendo, Baldad de Suhé disse: (ver nota)

[[v20-18-2]]

^<<v20-18-2,2>>^ Até quando dirás palavras vãs? Reflete primeiro, e depois falaremos.

[[v20-18-3]]

^<<v20-18-3,3>>^ Por que nos consideras como animais, e nos tornas por estúpidos?

[[v20-18-4]]

^<<v20-18-4,4>>^ Ó tu, que no teu furor te despedaças, porventura, por causa de ti, será despovoada a terra, e serão transferidos os rochedos do seu lugar?

[[v20-18-5]]

^<<v20-18-5,5>>^ Sim, é certo que a luz (ou prosperidade) do ímpio se apagará, e que não resplandecerá a chama do seu fogo.

[[v20-18-6]]

^<<v20-18-6,6>>^ A luz se obscurecerá na sua casa, e a lâmpada (ou glória), que está sobre ele, se apagará.

[[v20-18-7]]

^<<v20-18-7,7>>^ Os seus passos firmes serão cortados, e o seu próprio conselho o precipitará.

[[v20-18-8]]

^<<v20-18-8,8>>^ Prendem-se os seus pés na rede, anda entre as suas malhas.

[[v20-18-9]]

^<<v20-18-9,9>>^ O seu pé ficará preso pelo laço, ficará fortemente apertado.

[[v20-18-10]]

^<<v20-18-10,10>>^ Está-lhe escondido debaixo da terra o laço, e ao longo da vereda a armadilha,

[[v20-18-11]]

^<<v20-18-11,11>>^ De todas as partes o amedrontarão temores, e lhe enredarão os pés.

[[v20-18-12]]

^<<v20-18-12,12>>^ A fome enfraquecerá a sua robustez, e a perdição o acompanhará.

[[v20-18-13]]

^<<v20-18-13,13>>^ A pele do seu corpo será devorada; o primogênito da morte devorará os seus membros.

[[v20-18-14]]

^<<v20-18-14,14>>^ Será arrancado da sua tenda onde se julgava seguro, e a morte, como um rei, o calcará.

[[v20-18-15]]

^<<v20-18-15,15>>^ Outros - não mais ele - habitarão na sua casa, e sobre a sua lenda se espalhará enxofre.

[[v20-18-16]]

^<<v20-18-16,16>>^ Por baixo as suas raízes secarão, e por cima serão cortados os seus ramos.

[[v20-18-17]]

^<<v20-18-17,17>>^ Á sua memória perecerá da terra, e não será celebrado o seu nome na região.

[[v20-18-18]]

^<<v20-18-18,18>>^ Será arrojado da luz para as trevas, será desterrado do mundo.

[[v20-18-19]]

^<<v20-18-19,19>>^ Não terá nem descendência nem família no seu povo, nem relíquia alguma no seu pais.

[[v20-18-20]]

^<<v20-18-20,20>>^ Os últimos pasmarão do seu dia (de ruína), e os primeiros serão invadidos pelo horror.

[[v20-18-21]]

^<<v20-18-21,21>>^ Tais serão as moradas do ímpio, tal é o lugar daquele que não conhece (nem teme) a Deus.

'''

xref:020-jo/020-jo-017.adoc#v20-17-0[&#60; Capítulo Anterior] | <<v20-18-0,Topo>> | xref:020-jo/020-jo-019.adoc#v20-19-0[Próximo Capítulo &#62;]