include::./index.adoc[]

[[v57-3-0]]
=== Filipenses, 3
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 3 de Filipenses fala sobre a superioridade de conhecer a Cristo e a busca pela perfeição na vida cristã. Paulo afirma que tudo o que ele considerava importante antes de conhecer a Cristo é como lixo em comparação com o valor de conhecê-lo. Ele também exorta os filipenses a seguir seu exemplo e a buscar a perfeição em Cristo. Com base nesses temas, seguem cinco versículos relacionados:
* Romanos 3:10: "como está escrito: 'Não há nenhum justo, nem um sequer'" - Paulo menciona em Filipenses 3:9 que sua justiça própria não vem da lei, mas da fé em Cristo. Este versículo de Romanos 3 reforça a ideia de que ninguém é justo por si só, todos precisam de Cristo para serem justificados.
* Colossenses 2:8: "Cuidado para que ninguém os escravize com filosofias vãs e enganosas, que se baseiam em tradições humanas e nos princípios elementares deste mundo, e não em Cristo." - Em Filipenses 3, Paulo adverte contra os falsos mestres que ensinam a salvação pela circuncisão. Este versículo de Colossenses destaca a importância de nos mantermos firmes em Cristo e não sermos levados por doutrinas enganosas.
* Mateus 6:33: "Mas busquem primeiro o Reino de Deus e a sua justiça, e todas essas coisas serão acrescentadas a vocês." - Em Filipenses 3:12-14, Paulo enfatiza a importância de prosseguir para o alvo e alcançar a ressurreição dos mortos. Este versículo de Mateus 6:33 nos encoraja a buscar primeiro o Reino de Deus, colocando-o em primeiro lugar em nossas vidas.
* 1 Coríntios 9:24: "Vocês não sabem que, numa corrida, todos os corredores competem, mas apenas um ganha o prêmio? Corram de tal modo que alcancem o prêmio." - Em Filipenses 3:13-14, Paulo usa a analogia de uma corrida para ilustrar a busca pela perfeição em Cristo. Este versículo de 1 Coríntios 9:24 também fala sobre uma corrida e encoraja os cristãos a correrem de tal modo que possam ganhar o prêmio.
* Efésios 2:8-9: "Porque vocês são salvos pela graça, por meio da fé, e isto não vem de vocês, é dom de Deus; não por obras, para que ninguém se glorie." - Em Filipenses 3:9, Paulo diz que deseja ser encontrado em Cristo, não tendo justiça própria, mas a que vem pela fé em Cristo. Este versículo de Efésios 2:8-9 destaca que a salvação é um dom de Deus, recebido pela fé em Cristo, e não pelas nossas obras.
****

[[v57-3-1]]

^<<v57-3-1,1>>^ Quanto ao mais, meus irmãos, alegrai-vos no Senhor. A mim não me é penoso, e a vós é salutar, que eu vos escreva as mesmas coisas.

[[v57-3-2]]

^<<v57-3-2,2>>^ Guardai-vos desses cães, guardai-vos desses maus operários, guardai-vos desses mutilados. (ver nota)

[[v57-3-3]]

^<<v57-3-3,3>>^ Em realidade, nós é que somos os verdadeiros circuncidados, nós que servimos a Deus em espírito, nos gloriamos em Jesus Cristo e não confiamos na carne, (ver nota)

[[v57-3-4]]

^<<v57-3-4,4>>^ se bem que também eu poderia ter confiança na carne. Se algum outro, pode confiar na carne, muito mais (o posso) eu,

[[v57-3-5]]

^<<v57-3-5,5>>^ (que fui) circuncidado no oitavo dia; (que sou) da geração de Israel, da tribo de Benjamim, (nascido) hebreu de pais hebreus; (que fui), segundo a lei, fariseu;

[[v57-3-6]]

^<<v57-3-6,6>>^ quanto ao zelo, perseguidor da Igreja; quanto à justiça da lei, irrepreensível no meu proceder.

[[v57-3-7]]

^<<v57-3-7,7>>^ Porém, aquelas coisas que (antes) eu considerara como lucro, considerei-as (depois da minha conversão) como perdas por amor de Cristo.

[[v57-3-8]]

^<<v57-3-8,8>>^ Sim, na verdade tudo isso tenho por perda, perante o eminente conhecimento de Jesus Cristo, meu Senhor, pelo qual renunciei a todas as coisas e as considero como esterco, para ganhar a Cristo

[[v57-3-9]]

^<<v57-3-9,9>>^ e ser encontrado nele, não tendo (já) a minha justiça que vem da (observância da) lei, mas aquela que nasce da fé em Jesus Cristo, a justiça que vem de Deus pela fé, (ver nota)

[[v57-3-10]]

^<<v57-3-10,10>>^ a fim de o conhecer a ele e a virtude da sua ressurreição e a participação dos seus sofrimentos, assemelhando-me à sua morte,

[[v57-3-11]]

^<<v57-3-11,11>>^ para ver se de algum modo posso chegar à ressurreição dos mortos.

[[v57-3-12]]

^<<v57-3-12,12>>^ Não que eu tenha já alcançado o prêmio ou seja já perfeito, mas prossigo para ver se de algum modo o poderei apreender, porque eu (que andava fugido e o perseguia) também fui apreendido por Jesus Cristo.

[[v57-3-13]]

^<<v57-3-13,13>>^ Irmãos, não julgo ter já alcançado a meta (da perfeição cristã). Mas somente faço uma coisa: esquecendo-me do que fica para trás e avançando para as coisas que estão adiante,

[[v57-3-14]]

^<<v57-3-14,14>>^ prossigo para a meta, para o prêmio da celeste vocação de Deus em Jesus Cristo.

[[v57-3-15]]

^<<v57-3-15,15>>^ Todos nós, pois, que somos adultos (na vida cristã), tenhamos estes sentimentos; e, se em algum ponto tendes pensamentos diferentes. Deus também vos esclarecerá sobre isso.

[[v57-3-16]]

^<<v57-3-16,16>>^ Quanto, porém, aquilo a que temos já chegado, continuemos na mesma regra.

[[v57-3-17]]

^<<v57-3-17,17>>^ Sede meus imitadores, irmãos, e ponde os olhos naqueles que andam conforme o modelo que tendes em nós.

[[v57-3-18]]

^<<v57-3-18,18>>^ Porque muitos, de quem muitas vezes vos falei e também agora falo com lágrimas, procedem (com a sua vida sensual) como inimigos da cruz de Cristo :

[[v57-3-19]]

^<<v57-3-19,19>>^ o fim deles é a perdição, o deus deles é o ventre, e fazem consistir a sua glória naquilo que é a sua vergonha, gostando somente das coisas terrenas.

[[v57-3-20]]

^<<v57-3-20,20>>^ Nós, porém, somos cidadãos dos céus, donde também esperamos o Salvador, o Senhor Jesus Cristo,

[[v57-3-21]]

^<<v57-3-21,21>>^ o qual transformará o nosso corpo de miséria, fazendo-o semelhante ao seu corpo glorioso, com aquele poder com que pode também sujeitar a si todas as coisas.

'''

xref:057-filipenses/057-filipenses-002.adoc#v57-2-0[&#60; Capítulo Anterior] | <<v57-3-0,Topo>> | xref:057-filipenses/057-filipenses-004.adoc#v57-4-0[Próximo Capítulo &#62;]