include::./index.adoc[]

[[v49-21-0]]
=== São Lucas, 21
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* São Lucas 21 trata sobre os ensinamentos de Jesus acerca dos sinais que precedem a sua segunda vinda e sobre a necessidade de estar preparado para esse momento. Abaixo estão cinco versículos relacionados com os temas abordados no capítulo:
* 2 Pedro 3:10: "Virá, pois, como ladrão o dia do Senhor, no qual os céus passarão com grande estrondo, e os elementos, ardendo, se dissolverão, e a terra, e as obras que nela há, serão descobertas." Esse versículo fala sobre a segunda vinda de Cristo e as consequências que ela terá para a Terra.
* Mateus 24:42: "Vigiai, pois, porque não sabeis em que dia vem o vosso Senhor." Assim como em São Lucas 21, Jesus enfatiza a importância da vigilância e da prontidão para a sua segunda vinda.
* 1 Tessalonicenses 5:2: "Porque vós mesmos sabeis muito bem que o dia do Senhor virá como o ladrão de noite." Neste versículo, Paulo faz uma comparação semelhante à usada por Jesus em São Lucas 21: a segunda vinda de Cristo será repentina e inesperada como um ladrão.
* Apocalipse 1:7: "Eis que vem com as nuvens, e todo o olho o verá, até mesmo aqueles que o traspassaram; e todas as tribos da terra se lamentarão sobre ele. Certamente. Amém." Esse versículo fala sobre a visibilidade e a universalidade da segunda vinda de Cristo.
* Mateus 24:30: "Então aparecerá no céu o sinal do Filho do Homem, e todas as tribos da terra se lamentarão, e verão vir o Filho do Homem sobre as nuvens do céu, com poder e grande glória." Esse versículo se relaciona com a descrição feita por Jesus em São Lucas 21:25-28 sobre os sinais celestiais que precederão a sua segunda vinda.
****

[[v49-21-1]]

^<<v49-21-1,1>>^ Levantando Jesus os olhos, viu vários ricos que lançavam as suas oferendas no gazofilácio.

[[v49-21-2]]

^<<v49-21-2,2>>^ Viu também uma viúva pobrezinha, que lançava duas pequenas moedas.

[[v49-21-3]]

^<<v49-21-3,3>>^ E disse: "Na verdade vos digo que esta pobre viúva lançou mais que todos os outros.

[[v49-21-4]]

^<<v49-21-4,4>>^ Porque todos esses fizeram a Deus oferta do que lhes sobejava; ela, porém, deu da sua mesma indigência tudo O que tinha para viver."

[[v49-21-5]]

^<<v49-21-5,5>>^ Dizendo alguns, a respeito do templo, que estava ornado de belas pedras e de ricas ofertas, Jesus disse;

[[v49-21-6]]

^<<v49-21-6,6>>^ "De tudo isto que vedes, virão dias em que não ficará pedra sobre pedra, que não seja demolida."

[[v49-21-7]]

^<<v49-21-7,7>>^ Então interrogaram-no: "Mestre, quando acontecerão estas coisas, e que sinal haverá, quando estiverem para acontecer?"

[[v49-21-8]]

^<<v49-21-8,8>>^ Ele respondeu: "Vede, não vos deixeis enganar; porque muitos virão com o meu nome, dizendo: Sou eu, está próximo o tempo. Não os sigais.

[[v49-21-9]]

^<<v49-21-9,9>>^ Quando ouvirdes falar de guerras e de tumultos, não vos assusteis; estas coisas devem suceder primeiro; mas não será logo o fim."

[[v49-21-10]]

^<<v49-21-10,10>>^ Depois disse-lhes: "Levantar-se-á nação contra nação, reino contra reino.

[[v49-21-11]]

^<<v49-21-11,11>>^ Haverá grandes terremotos por várias partes, pestes e fomes; aparecerão coisas espantosas, e extraordinários sinais no céu.

[[v49-21-12]]

^<<v49-21-12,12>>^ Mas antes de tudo isto, lançar-vos-ão as mãos, e vos perseguirão, entregando-vos nas sinagogas, nas prisões, e vos levarão à presença dos reis e dos governadores, por causa do meu nome.

[[v49-21-13]]

^<<v49-21-13,13>>^ Isto vos será ocasião de dardes testemunho.

[[v49-21-14]]

^<<v49-21-14,14>>^ Gravai, pois, nos vossos corações o não premeditar como vos haveis de defender,

[[v49-21-15]]

^<<v49-21-15,15>>^ porque eu vos darei uma linguagem e uma sabedoria, à qual não poderão resistir, nem contradizer todos os vossos inimigos.

[[v49-21-16]]

^<<v49-21-16,16>>^ Sereis entregues por vossos pais, irmãos, parentes, e amigos e farão morrer muitos de vós;

[[v49-21-17]]

^<<v49-21-17,17>>^ e sereis aborrecidos de todos por causa de meu nome;

[[v49-21-18]]

^<<v49-21-18,18>>^ mas não se perderá um cabelo da vossa cabeça.

[[v49-21-19]]

^<<v49-21-19,19>>^ Pela vossa perseverança salvareis as vossas almas.

[[v49-21-20]]

^<<v49-21-20,20>>^ Mas quando virdes que Jerusalém é sitiada por exércitos, então sabei que está próxima a sua desolação.

[[v49-21-21]]

^<<v49-21-21,21>>^ Os que então estiverem na Judeia, fujam para os montes; os que estiverem no meio da cidade, retirem-se; os que estiverem nos campos, não entrem nela;

[[v49-21-22]]

^<<v49-21-22,22>>^ porque estes são dias de vingança, para que se cumpram todas as coisas que estão escritas.

[[v49-21-23]]

^<<v49-21-23,23>>^ Aí das mulheres grávidas, e das que amamentarem naqueles dias! porque haverá grande angústia sobre a terra, e ira contra este povo.

[[v49-21-24]]

^<<v49-21-24,24>>^ Cairão ao fio da espada, serão levados cativos a todas as nações, e Jerusalém será calcada pelos gentios, até se completarem os tempos dos gentios. (ver nota)

[[v49-21-25]]

^<<v49-21-25,25>>^ Haverá sinais no sol, na lua e nas estrelas. Na terra haverá consternação dos povos pela confusão do bramido do mar e das ondas,

[[v49-21-26]]

^<<v49-21-26,26>>^ morrendo os homens de susto, na expectação do que virá sobre todo o mundo, porque as virtudes dos céus se abalarão.

[[v49-21-27]]

^<<v49-21-27,27>>^ Então verão o Filho do homem vir sobre uma nuvem com grande poder e majestade.

[[v49-21-28]]

^<<v49-21-28,28>>^ Quando começarem, pois, a suceder estas coisas, erguei-vos, levantai as vossas cabeças, porque está próxima a vossa libertação. (ver nota)

[[v49-21-29]]

^<<v49-21-29,29>>^ Acrescentou esta comparação: Vede a figueira e todas as árvores.

[[v49-21-30]]

^<<v49-21-30,30>>^ Quando começam a desabrochar, conheceis que está perto o estio.

[[v49-21-31]]

^<<v49-21-31,31>>^ Assim, também, quando virdes que acontecem estas coisas, sabei que está próximo o reino de Deus,

[[v49-21-32]]

^<<v49-21-32,32>>^ Em verdade vos digo que não passará esta geração, sem que todas estas coisas se cumpram.

[[v49-21-33]]

^<<v49-21-33,33>>^ Passará o céu e a terra, mas as minhas palavras não passarão.

[[v49-21-34]]

^<<v49-21-34,34>>^ Velai, pois, sobre vós, para que não suceda que os vossos corações se tornem pesados com as demasias do comer e do beber, com os cuidados desta vida, e para que aquele dia vos não apanhe de improviso;

[[v49-21-35]]

^<<v49-21-35,35>>^ porque ele virá como um laço sobre todos os que habitam sobre a face de toda a terra.

[[v49-21-36]]

^<<v49-21-36,36>>^ Vigiai, pois, orando sem cessar, a fim de que vos torneis dignos de evitar todos estes males que devem suceder, e de aparecer com confiança diante do Filho do homem."

[[v49-21-37]]

^<<v49-21-37,37>>^ Jesus estava de dia ensinando no templo, mas ao anoitecer saía para passar a noite no monte, que se chamava das Oliveiras.

[[v49-21-38]]

^<<v49-21-38,38>>^ E todo o povo madrugava para ir ao templo ouvi-lo.

'''

xref:049-sao-lucas/049-sao-lucas-020.adoc#v49-20-0[&#60; Capítulo Anterior] | <<v49-21-0,Topo>> | xref:049-sao-lucas/049-sao-lucas-022.adoc#v49-22-0[Próximo Capítulo &#62;]