include::./index.adoc[]

[[v49-2-0]]
=== São Lucas, 2
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 2 de Lucas descreve o nascimento de Jesus em Belém e eventos que ocorreram logo depois. Os pastores recebem a notícia do nascimento do Salvador, visitam o recém-nascido em sua manjedoura e compartilham a boa notícia. A seguir, Jesus é apresentado no templo, onde é reconhecido como o Messias por Simeão e Ana. Abaixo estão cinco versículos relacionados com esses temas:
* Mateus 1:23: "A virgem ficará grávida e dará à luz um filho, e o chamarão Emanuel" (que significa "Deus conosco"). Este versículo é uma profecia que se cumpre em Lucas 2, quando Maria dá à luz a Jesus.
* Isaías 9:6: "Porque um menino nos nasceu, um filho nos foi dado, e o governo está sobre os seus ombros. E ele será chamado Maravilhoso Conselheiro, Deus Poderoso, Pai Eterno, Príncipe da Paz." Este versículo é uma profecia sobre o nascimento de Jesus e a natureza de seu caráter e obra.
* Lucas 1:32: "Ele será grande e será chamado Filho do Altíssimo. O Senhor Deus lhe dará o trono de seu pai Davi." Este versículo é uma profecia sobre Jesus como o Messias, o cumprimento das promessas de Deus a Davi.
* Mateus 2:11: "E, entrando na casa, viram o menino com Maria, sua mãe, e prostrando-se, o adoraram; e abrindo seus tesouros, eles lhe ofereceram presentes: ouro, incenso e mirra." Este versículo descreve a visita dos magos, que trouxeram presentes ao recém-nascido Jesus.
* Lucas 2:40: "E o menino crescia e se fortalecia, enchendo-se de sabedoria; e a graça de Deus estava sobre ele." Este versículo indica o desenvolvimento da infância de Jesus, que cresceu em sabedoria e graça diante de Deus e dos homens.
****

[[v49-2-1]]

^<<v49-2-1,1>>^ Naqueles dias, saiu um édito de César Augusto, prescrevendo o recenseamento de todo o mundo. (ver nota)

[[v49-2-2]]

^<<v49-2-2,2>>^ Este recenseamento foi anterior ao que se realizou quando Quirino era governador da Síria.

[[v49-2-3]]

^<<v49-2-3,3>>^ Iam todos recensear-se, cada um à sua cidade.

[[v49-2-4]]

^<<v49-2-4,4>>^ José foi também da Galileia, da cidade de Nazaré, à Judeia, à cidade de David, que se chamava Belém, porque era da casa e família de David,

[[v49-2-5]]

^<<v49-2-5,5>>^ para se recensear juntamente com Maria, sua esposa, que estava grávida.

[[v49-2-6]]

^<<v49-2-6,6>>^ Ora, estando ali, aconteceu completarem-se os dias em que devia dar à luz,

[[v49-2-7]]

^<<v49-2-7,7>>^ e deu à luz o seu filho primogénito, e o enfaixou, e o reclinou numa manjedoura, porque não havia lugar para eles na estalagem. (ver nota)

[[v49-2-8]]

^<<v49-2-8,8>>^ Naquela mesma região, havia uns pastores que velavam e faziam de noite a guarda ao seu rebanho.

[[v49-2-9]]

^<<v49-2-9,9>>^ Apareceu-lhes um anjo do Senhor, e a glória do Senhor os envolveu com a sua luz, e tiveram grande temor.

[[v49-2-10]]

^<<v49-2-10,10>>^ Porém o anjo disse-lhes: "Não temais, porque eis que vos anuncio uma boa nova, que será de grande alegria para todo o povo:

[[v49-2-11]]

^<<v49-2-11,11>>^ Nasceu-vos hoje na cidade de David um Salvador, que é o Cristo, o Senhor.

[[v49-2-12]]

^<<v49-2-12,12>>^ Eis o que vos servirá de sinal: Encontrareis um Menino envolto em panos, e deitado numa manjedoura."

[[v49-2-13]]

^<<v49-2-13,13>>^ E subitamente apareceu com o anjo uma multidão da milícia celeste, louvando a Deus, e dizendo:

[[v49-2-14]]

^<<v49-2-14,14>>^ "Glória a Deus no mais alto dos céus, e paz na terra aos homens, objecto da boa vontade (de Deus)."

[[v49-2-15]]

^<<v49-2-15,15>>^ Depois que os anjos se retiraram deles para o céu, os pastores diziam entre si: "Vamos até Belém, e vejamos o que é que lá sucedeu, e o que é que o Senhor nos manifestou."

[[v49-2-16]]

^<<v49-2-16,16>>^ Foram a toda a pressa, e encontraram Maria, José, e o Menino deitado na manjedoura.

[[v49-2-17]]

^<<v49-2-17,17>>^ Vendo isto, conheceram o que lhes tinha sido dito acerca deste Menino.

[[v49-2-18]]

^<<v49-2-18,18>>^ E todos os que ouviram, se admiraram das coisas que lhes diziam os pastores.

[[v49-2-19]]

^<<v49-2-19,19>>^ Maria conservava todas estas coisas, meditando-as no seu coração,

[[v49-2-20]]

^<<v49-2-20,20>>^ Os pastores voltaram, glorificando e louvando a Deus por tudo o que tinham ouvido e visto, conforme lhes tinha sido dito.

[[v49-2-21]]

^<<v49-2-21,21>>^ Depois que se completaram os oito dias para ser circuncidado o Menino, foi-lhe posto o nome de Jesus, como lhe tinha chamado o anjo, antes que fosse concebido no ventre materno.

[[v49-2-22]]

^<<v49-2-22,22>>^ Depois que se completaram os dias da purificação de Maria, segundo a lei de Moisés, levaram-no a Jerusalém para o apresentar ao Senhor Lv. 12, 6,

[[v49-2-23]]

^<<v49-2-23,23>>^ segundo o que está escrito na lei do Senhor : Todo o varão primogênito será consagrado ao Senhor (Ex. 13, 2 ; Ex. 12, 15),

[[v49-2-24]]

^<<v49-2-24,24>>^ e para oferecerem em sacrifício, conforme o que também está escrito na lei do Senhor, um par de rolas ou dois pombinhos (Lv. 12, 8 ; Lv. 5, 11).

[[v49-2-25]]

^<<v49-2-25,25>>^ Havia então em Jerusalém um homem chamado Simeão. Este homem era justo e piedoso; esperava a consolação de Israel, e o Espírito Santo estava nele.

[[v49-2-26]]

^<<v49-2-26,26>>^ Tinha-lhe sido revelado pelo Espírito Santo que não veria a morte, sem ver primeiro o Cristo do Senhor.

[[v49-2-27]]

^<<v49-2-27,27>>^ Foi ao templo conduzido pelo Espírito (de Deus). E, levando os pais o Menino Jesus, para cumprirem as prescrições usuais da lei a seu respeito,

[[v49-2-28]]

^<<v49-2-28,28>>^ ele o tomou em seus braços, e louvou a Deus, dizendo:

[[v49-2-29]]

^<<v49-2-29,29>>^ "Agora, Senhor, podes deixar partir o teu servo em paz, segundo a tua palavra;

[[v49-2-30]]

^<<v49-2-30,30>>^ porque os meus olhos viram a tua salvação,

[[v49-2-31]]

^<<v49-2-31,31>>^ a qual preparaste em favor de todos os povos;

[[v49-2-32]]

^<<v49-2-32,32>>^ luz para iluminar as nações, e glória de Israel, teu povo."

[[v49-2-33]]

^<<v49-2-33,33>>^ Seu pai e sua mãe estavam admirados das coisas que dele se diziam.

[[v49-2-34]]

^<<v49-2-34,34>>^ Simeão os abençoou, e disse a Maria, sua mãe : "Eis que este Menino está posto para ruína e ressurgimento de muitos em Israel, e para ser alvo de contradição. (ver nota)

[[v49-2-35]]

^<<v49-2-35,35>>^ E uma espada trespassará a tua alma! Assim se descobrirão os pensamentos escondidos nos corações de muitos." (ver nota)

[[v49-2-36]]

^<<v49-2-36,36>>^ Havia também uma profetiza, chamada Ana, filha de Fanuel, da tribo de Aser. Estava em idade muito avançada. Tinha vivido sete anos com seu marido, desde a sua virgindade,

[[v49-2-37]]

^<<v49-2-37,37>>^ e tinha permanecido viúva até aos oitenta e quatro anos, e não se afastava do templo, servindo a Deus noite e dia com jejuns e orações.

[[v49-2-38]]

^<<v49-2-38,38>>^ Ela também, sobrevindo nesta mesma ocasião, louvava a Deus, e falava de Jesus a todos os de Jerusalém que esperavam a redenção.

[[v49-2-39]]

^<<v49-2-39,39>>^ Depois que cumpriram tudo, segundo o que mandava a lei do Senhor, voltaram para a Galileia, para a sua cidade de Nazaré.

[[v49-2-40]]

^<<v49-2-40,40>>^ O Menino crescia e se fortificava cheio de sabedoria, e a graça de Deus era com ele.

[[v49-2-41]]

^<<v49-2-41,41>>^ Seus pais iam todos os anos a Jerusalém, pela festa da Páscoa.

[[v49-2-42]]

^<<v49-2-42,42>>^ Quando chegou aos doze anos, indo eles a Jerusalém segundo o costume daquela festa,

[[v49-2-43]]

^<<v49-2-43,43>>^ acabados os dias que ela durava, quando voltaram, ficou o Menino Jesus em Jerusalém, sem que seus país o advertissem.

[[v49-2-44]]

^<<v49-2-44,44>>^ Julgando que ele fosse na comitiva, caminharam uma jornada, e depois procuraram-no entre os parentes e conhecidos.

[[v49-2-45]]

^<<v49-2-45,45>>^ Não o encontrando, voltaram a Jerusalém em busca dele.

[[v49-2-46]]

^<<v49-2-46,46>>^ Aconteceu que, três dias depois, o encontraram no templo sentado no meio dos doutores, ouvindo-os e interrogando-os.

[[v49-2-47]]

^<<v49-2-47,47>>^ E todos os que ouviam, estavam maravilhados da sua sabedoria e das suas respostas.

[[v49-2-48]]

^<<v49-2-48,48>>^ Quando o viram, admiraram-se. E sua mãe disse-lhe: "Filho, porque procedeste assim connosco? Eis que teu pai e eu te procurávamos cheios de aflição."

[[v49-2-49]]

^<<v49-2-49,49>>^ Ele disse-Ihes: "Para que me buscáveis? Não sabíeis que devo ocupar-me nas coisas de meu Pai?" (ver nota)

[[v49-2-50]]

^<<v49-2-50,50>>^ Eles porém não entenderam o que lhes disse. (ver nota)

[[v49-2-51]]

^<<v49-2-51,51>>^ Depois desceu com eles, e foi a Nazaré; e era-lhes submisso, Sua mãe conservava todas estas coisas no seu coração.

[[v49-2-52]]

^<<v49-2-52,52>>^ Jesus crescia em sabedoria, em estatura e em graça diante de Deus e dos homens.

'''

xref:049-sao-lucas/049-sao-lucas-001.adoc#v49-1-0[&#60; Capítulo Anterior] | <<v49-2-0,Topo>> | xref:049-sao-lucas/049-sao-lucas-003.adoc#v49-3-0[Próximo Capítulo &#62;]