include::./index.adoc[]

[[v49-10-0]]
=== São Lucas, 10
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* São Lucas 10 apresenta o envio de setenta discípulos por Jesus para pregar e curar em várias cidades da região. Além disso, o capítulo também contém a parábola do bom samaritano e a visita de Jesus à casa de Marta e Maria. Abaixo estão cinco versículos relacionados com os temas abordados em São Lucas 10:
* João 14:12 - "Em verdade, em verdade vos digo que aquele que crê em mim fará também as obras que eu faço e outras maiores fará, porque eu vou para junto do Pai." Jesus envia os setenta discípulos para pregar e curar em seu nome, e este versículo fala da continuidade de suas obras através dos seus seguidores.
* Tiago 5:16 - "Confessai, pois, os vossos pecados uns aos outros e orai uns pelos outros, para serdes curados. A oração feita por um justo pode muito em seus efeitos." Os discípulos enviados por Jesus realizam curas, e este versículo destaca a importância da oração e da confissão de pecados para a cura.
* Mateus 22:37-39 - "Amarás o Senhor, teu Deus, de todo o teu coração, de toda a tua alma e de todo o teu entendimento. Este é o grande e primeiro mandamento. O segundo, semelhante a este, é: Amarás o teu próximo como a ti mesmo." A parábola do bom samaritano enfatiza a importância de amar e cuidar do próximo, e este versículo resume os dois grandes mandamentos que Jesus ensinou.
* Lucas 10:41-42 - "Marta, Marta, andas inquieta e te preocupas com muitas coisas. Entretanto, pouco é necessário ou mesmo uma só coisa; Maria, pois, escolheu a boa parte, e esta não lhe será tirada." Jesus visita a casa de Marta e Maria, e este versículo destaca a importância de estar presente e ouvir a palavra de Deus em vez de se preocupar com tarefas mundanas.
* João 10:16 - "Ainda tenho outras ovelhas que não são deste aprisco; a estas também me importa conduzir, e ouvirão a minha voz, e haverá um rebanho e um pastor." Jesus envia seus discípulos para pregar em várias cidades, e este versículo fala da unidade entre as ovelhas de Jesus, independentemente de sua origem ou localização.
****

[[v49-10-1]]

^<<v49-10-1,1>>^ Depois disto, o Senhor escolheu outros setenta e dois mandou-os dois a dois adiante de si por todas as cidades e lugares onde ele estava para ir.

[[v49-10-2]]

^<<v49-10-2,2>>^ Disse-lhes: "Grande é na verdade a messe, mas os operários poucos. Rogai, pois, ao dono da messe que mande operários para a sua messe.

[[v49-10-3]]

^<<v49-10-3,3>>^ Ide; eis que eu vos envio como cordeiros entre lobos.

[[v49-10-4]]

^<<v49-10-4,4>>^ Não leveis bolsa, nem alforge, nem calçado, e pelo caminho não saudeis ninguém.

[[v49-10-5]]

^<<v49-10-5,5>>^ Na casa em que entrardes, dizei primeiro: A paz seja nesta casa.

[[v49-10-6]]

^<<v49-10-6,6>>^ Se ali houver algum filho de paz, repousará sobre ele a vossa paz; de contrário, tornará para vós.

[[v49-10-7]]

^<<v49-10-7,7>>^ Permanecei na mesma casa, comendo e bebendo do que tiverem; porque o operário é digno da sua recompensa. Não andeis de casa em casa.

[[v49-10-8]]

^<<v49-10-8,8>>^ Em qualquer cidade em que entrardes, e vos receberem, comei o que vos puserem diante;

[[v49-10-9]]

^<<v49-10-9,9>>^ curai os enfermos que nela houver, e dizei-lhes: Está próximo de vós o reino de Deus.

[[v49-10-10]]

^<<v49-10-10,10>>^ Mas, em qualquer cidade em que entrardes, e vos não receberem, saindo para as praças dizei; (ver nota)

[[v49-10-11]]

^<<v49-10-11,11>>^ Até o pó da vossa cidade, que se nos pegou aos pés, sacudimos contra vós; não obstante isto, sabei que o reino de Deus está próximo.

[[v49-10-12]]

^<<v49-10-12,12>>^ Digo-vos que, naquele dia, haverá menos rigor para Sodoma que para essa cidade.

[[v49-10-13]]

^<<v49-10-13,13>>^ Ai de ti, Corozain! Ai de ti, Betsaida! Porque, se em Tiro e em Sidónia se tivessem operado as maravilhas que se têm operado em vós, há muito tempo que teriam feito penitência, cobertas de cilício, e jazendo sobre a cinza.

[[v49-10-14]]

^<<v49-10-14,14>>^ Por isso haverá no dia de juízo menos rigor para Tiro e Sidónia que para vós.

[[v49-10-15]]

^<<v49-10-15,15>>^ E tu, Cafarnaum, que te elevas até ao céu, serás abatida até ao inferno (Is. 14, 13-15).

[[v49-10-16]]

^<<v49-10-16,16>>^ O que vos ouve, a mim ouve, o que vos rejeita, a mim rejeita, e quem me rejeita, rejeita aquele que me enviou."

[[v49-10-17]]

^<<v49-10-17,17>>^ Os setenta e dois voltaram alegres, dizendo: "Senhor, até os demônios se nos submetem em virtude do teu nome."

[[v49-10-18]]

^<<v49-10-18,18>>^ Ele disse-lhes: "Eu via Satanás cair do céu como um raio. (ver nota)

[[v49-10-19]]

^<<v49-10-19,19>>^ Eis que vos dei poder de caminhar impunemente sobre serpentes e escorpiões, e de vencer toda a força do inimigo, e nada vos fará dano.

[[v49-10-20]]

^<<v49-10-20,20>>^ Contudo não vos alegreis porque os espíritos maus vos estão sujeitos, mas alegrai-vos porque os vossos nomes estão escritos nos céus."

[[v49-10-21]]

^<<v49-10-21,21>>^ Naquela mesma hora Jesus exultou no Espírito Santo, e disse: "Graças te dou, ó Pai, Senhor do céu e da terra, porque escondeste estas coisas aos sábios e aos prudentes, e as revelaste aos pequeninos. Assim é, ó Pai, porque assim foi do teu agrado. (ver nota)

[[v49-10-22]]

^<<v49-10-22,22>>^ Todas as coisas me foram entregues por meu Pai; e ninguém sabe quem é o Filho, senão o Pai, nem quem é o Pai, senão o Filho, e aquele a quem o Filho quiser revelar."

[[v49-10-23]]

^<<v49-10-23,23>>^ Depois, tendo-se voltado para seus discípulos, disse: "Ditosos os olhos que vêem o que vós vedes.

[[v49-10-24]]

^<<v49-10-24,24>>^ Porque eu vos afirmo que muitos profetas e reis desejaram ver o que vós vedes, e não viram, ouvir o que vós ouvis, e não o ouviram."

[[v49-10-25]]

^<<v49-10-25,25>>^ Eis que se levantou um doutor da lei, e lhe disse para o tentar: "Mestre, que devo eu fazer para alcançar a vida eterna?"

[[v49-10-26]]

^<<v49-10-26,26>>^ Jesus respondeu-lhe: "O que é que está escrito na lei? Como lês tu?"

[[v49-10-27]]

^<<v49-10-27,27>>^ Ele respondeu: "Amarás o Senhor teu Deus com todo o teu coração, com toda a tua alma, com todas as tuas forças e com todo o teu entendimento, e o teu próximo como a ti mesmo."

[[v49-10-28]]

^<<v49-10-28,28>>^ Jesus disse-lhe: "Respondeste bem ; faz isso, e viverás (Lv. 18, 5)."

[[v49-10-29]]

^<<v49-10-29,29>>^ Mas ele, querendo justificar-se, disse a Jesus: "E quem é o meu próximo?"

[[v49-10-30]]

^<<v49-10-30,30>>^ Jesus, retomando a palavra, disse; "Um homem descia de Jerusalém para Jericó, e caiu nas mãos dos ladrões, que o despojaram, e, tendo-lhe feito feridas, retiraram-se, deixando-o meio morto.

[[v49-10-31]]

^<<v49-10-31,31>>^ Ora aconteceu que descia pelo mesmo caminho um sacerdote, o qual, quando o viu, passou de largo.

[[v49-10-32]]

^<<v49-10-32,32>>^ Igualmente um levita, chegando perto daquele lugar, e vendo-o, passou adiante.

[[v49-10-33]]

^<<v49-10-33,33>>^ Um samaritano, porém, que ia de viagem, chegou perto dele, e, quando o viu, moveu-se de compaixão.

[[v49-10-34]]

^<<v49-10-34,34>>^ Aproximou-se, ligou-lhe as feridas, lançando nelas azeite e vinho; e, pondo-o sobre o seu jumento, levou-o a uma estalagem, e teve cuidado dele.

[[v49-10-35]]

^<<v49-10-35,35>>^ No dia seguinte tirou dois dinheiros, deu-os ao estalajadeiro, e disse-lhe: Tem cuidado dele; quanto gastares a mais, eu to satisferei quando voltar.

[[v49-10-36]]

^<<v49-10-36,36>>^ Qual destes três te parece que foi o próximo daquele que caiu nas mãos dos ladrões?"

[[v49-10-37]]

^<<v49-10-37,37>>^ Ele respondeu: "O que usou com ele de misericórdia." Então Jesus disse-lhe: "Vai, e faz tu o mesmo."

[[v49-10-38]]

^<<v49-10-38,38>>^ Indo em viagem, entrou em uma aldeia, e uma mulher, chamada Marta, recebeu-o em sua casa.

[[v49-10-39]]

^<<v49-10-39,39>>^ Esta tinha uma irmã, chamada Maria que, sentada aos pés do Senhor, ouvia a sua palavra.

[[v49-10-40]]

^<<v49-10-40,40>>^ Marta, porém, afadigava-se muito na continua lida da casa. Aproximando-se, disse: "Senhor, não se te dá que minha irmã me tenha deixado só com o serviço da casa? Diz-lhe, pois, que me ajude."

[[v49-10-41]]

^<<v49-10-41,41>>^ O Senhor, respondeu-lhe: "Marta, Marta, tu afadigas-te e andas inquieta com muitas coisas.

[[v49-10-42]]

^<<v49-10-42,42>>^ Entretanto uma só coisa é necessária. Maria escolheu a melhor parte, que lhe não será tirada."

'''

xref:049-sao-lucas/049-sao-lucas-009.adoc#v49-9-0[&#60; Capítulo Anterior] | <<v49-10-0,Topo>> | xref:049-sao-lucas/049-sao-lucas-011.adoc#v49-11-0[Próximo Capítulo &#62;]