include::./index.adoc[]

[[v49-1-0]]
=== São Lucas, 1
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* São Lucas 1 descreve a concepção e nascimento de João Batista e de Jesus, além de relatar o encontro entre Maria e Isabel, e o cântico do Magnificat de Maria. Também é apresentada a história de Zacarias, pai de João Batista, e o anúncio do anjo Gabriel a ele. A seguir, estão cinco versículos relacionados com os temas abordados em São Lucas 1:
* Gênesis 18:14: "Acaso, para o SENHOR há coisa demasiadamente difícil? No tempo determinado, voltarei a ti, porventura, e Sara terá um filho." Este versículo apresenta um exemplo da fidelidade de Deus em cumprir suas promessas, mesmo que pareçam impossíveis.
* Isaías 40:3: "Uma voz clama: No deserto preparem o caminho do Senhor; na terra árida abram uma estrada para o nosso Deus." Este versículo profetiza a vinda de João Batista, que prepararia o caminho para Jesus.
* Miquéias 5:2: "Mas tu, Belém-Efrata, embora pequena demais para figurar como grupo de milhares de Judá, de ti me sairá o que há de reinar em Israel, e cujas origens são desde os tempos antigos, desde os dias da eternidade." Este versículo profetiza o nascimento de Jesus em Belém.
* 1 Samuel 1:11: "E fez um voto, dizendo: SENHOR dos Exércitos! Se benignamente atentares para a aflição da tua serva, e de mim te lembrares, e da tua serva não te esqueceres, mas lhe deres um filho varão, ao SENHOR o darei todos os dias da sua vida, e sobre a sua cabeça não passará navalha." Este versículo apresenta um exemplo de uma mulher estéril que ora a Deus por um filho, assim como Isabel e Ana, mãe de Samuel.
* Malaquias 4:5: "Eis que vos enviarei o profeta Elias, antes que venha o grande e terrível Dia do SENHOR." Este versículo é citado por Jesus ao falar sobre João Batista em Mateus 17:10-13, mostrando como as profecias do Antigo Testamento se cumpriram com o nascimento de João e de Jesus.
****

[[v49-1-1]]

^<<v49-1-1,1>>^ Visto que muitos já empreenderam pôr em ordem a narração das coisas que entre nós se cumpriram,

[[v49-1-2]]

^<<v49-1-2,2>>^ como no-las referiram os que, desde o princípio, as viram, e foram ministros da palavra,

[[v49-1-3]]

^<<v49-1-3,3>>^ pareceu-me bom também a mim, depois de ter investigado diligentemente tudo desde o princípio, escrever-te por ordem a sua narração, excelentíssimo Teófilo,

[[v49-1-4]]

^<<v49-1-4,4>>^ para que conheças a solidez dos ensinamentos que recebeste.

[[v49-1-5]]

^<<v49-1-5,5>>^ Houve no tempo de Herodes, rei da Judeia, um sacerdote chamado Zacarias, da turma de Abias, e sua mulher era da descendência de Arão, e chamava-se Isabel.

[[v49-1-6]]

^<<v49-1-6,6>>^ Ambos eram justos diante de Deus, caminhando irrepreensìvelmente em todos os mandamentos e preceitos do Senhor.

[[v49-1-7]]

^<<v49-1-7,7>>^ Não tinham filhos, porque Isabel era estéril, e ambos se achavam em idade avançada.

[[v49-1-8]]

^<<v49-1-8,8>>^ Sucedeu que, exercendo Zacarias diante de Deus as funções de sacerdote na ordem da sua turma,

[[v49-1-9]]

^<<v49-1-9,9>>^ segundo o costume do sacerdócio, tocou-lhe por sorte entrar no templo do Senhor a oferecer o incenso.

[[v49-1-10]]

^<<v49-1-10,10>>^ Toda a multidão do povo estava fazendo oração da parte de fora, à hora do incenso.

[[v49-1-11]]

^<<v49-1-11,11>>^ Apareceu-lhe um anjo do Senhor, posto de pé ao lado direito do altar do incenso.

[[v49-1-12]]

^<<v49-1-12,12>>^ Zacarias, ao vê-lo, ficou perturbado, e o temor o assaltou.

[[v49-1-13]]

^<<v49-1-13,13>>^ Mas o anjo disse-lhe: "Não temas, Zacarias, porque foi ouvida a tua oração; tua mulher Isabel te dará um filho, ao qual porás o nome de João.

[[v49-1-14]]

^<<v49-1-14,14>>^ Será para ti motivo de gozo e de alegria, e muitos se alegrarão no seu nascimento;

[[v49-1-15]]

^<<v49-1-15,15>>^ porque ele será grande diante do Senhor; não beberá vinho nem outra bebida inebriante; será cheio do Espírito Santo desde o ventre de sua mãe;

[[v49-1-16]]

^<<v49-1-16,16>>^ e converterá muitos dos filhos de Israel ao Senhor seu Deus.

[[v49-1-17]]

^<<v49-1-17,17>>^ Irá adiante de Deus com o espírito e a fortaleza de Elias, a fim de reconduzir os corações dos pais para os filhos (Ml. 4, 5-6), e os rebeldes à prudência dos justos, para preparar ao Senhor um povo bem disposto."

[[v49-1-18]]

^<<v49-1-18,18>>^ Zacarias disse ao anjo: "Como conhecerei isso? Porque eu sou velho, e minha mulher está avançada em anos."

[[v49-1-19]]

^<<v49-1-19,19>>^ O anjo respondeu-lhe: "Eu sou Gabriel, que assisto diante de Deus; fui enviado para te falar e te dar esta boa nova.

[[v49-1-20]]

^<<v49-1-20,20>>^ Eis que ficarás mudo, e não poderás falar até ao dia em que estas coisas sucedam, visto que não acreditaste nas minhas palavras, que se hão-de cumprir a seu tempo."

[[v49-1-21]]

^<<v49-1-21,21>>^ Entretanto o povo estava esperando Zacarias, e admirava-se de ver que ele se demorava tanto tempo no templo.

[[v49-1-22]]

^<<v49-1-22,22>>^ Quando saiu, não lhes podia falar, e compreenderam que tinha tido no templo alguma visão, o que lhes dava a entender por acenos; e ficou mudo.

[[v49-1-23]]

^<<v49-1-23,23>>^ Aconteceu que, depois de terem acabado os dias do seu ministério, retirou-se para sua casa.

[[v49-1-24]]

^<<v49-1-24,24>>^ Alguns dias depois, Isabel, sua mulher, concebeu, e durante cinco meses esteve escondida, dizendo:

[[v49-1-25]]

^<<v49-1-25,25>>^ "Isto é uma graça que me fez o Senhor nos dias em que me olhou para tirar o meu opróbrio de entre os homens." (ver nota)

[[v49-1-26]]

^<<v49-1-26,26>>^ Estando Isabel no sexto mês, foi enviado por Deus o anjo Gabriel a uma cidade da Galileia, chamada Nazaré,

[[v49-1-27]]

^<<v49-1-27,27>>^ a uma virgem desposada com um varão, chamado José, da casa de David; o nome da virgem era Maria.

[[v49-1-28]]

^<<v49-1-28,28>>^ Entrando o anjo onde ela estava, disse-Ihe: "Deus te salve, cheia de graça; o Senhor é contigo."

[[v49-1-29]]

^<<v49-1-29,29>>^ Ela, ao ouvir estas palavras, perturbou-se, e discorria pensativa que saudação seria esta.

[[v49-1-30]]

^<<v49-1-30,30>>^ O anjo disse-lhe: "Não temas, Maria, pois achaste graça diante de Deus;

[[v49-1-31]]

^<<v49-1-31,31>>^ eis que conceberás no teu ventre, e darás à luz um filho, a quem porás o nome de Jesus.

[[v49-1-32]]

^<<v49-1-32,32>>^ Será grande, será chamado Filho do Altíssimo, e o Senhor Deus lhe dará o trono de seu pai David; reinará sobre a casa de Jacob eternamente,

[[v49-1-33]]

^<<v49-1-33,33>>^ e o seu reino não terá fim."

[[v49-1-34]]

^<<v49-1-34,34>>^ Maria disse ao anjo: "Como se fará isso, pois eu não conheço varão?"

[[v49-1-35]]

^<<v49-1-35,35>>^ O anjo respondeu-lhe: "O Espírito Santo descerá sobre ti, e a virtude do Altíssimo te cobrirá com a sua sombra; por isso mesmo o Menino que há-de nascer de ti, será santo e será chamado Filho de Deus.

[[v49-1-36]]

^<<v49-1-36,36>>^ Eis que também Isabel, tua parenta, concebeu um filho na sua velhice; e este é o sexto mês da que se dizia estéril;

[[v49-1-37]]

^<<v49-1-37,37>>^ porque a Deus nada é impossível."

[[v49-1-38]]

^<<v49-1-38,38>>^ Então Maria disse: "Eis aqui a serva do Senhor, faça-se em mim a tua palavra." E o anjo afastou-se dela.

[[v49-1-39]]

^<<v49-1-39,39>>^ Naqueles dias, levantando-se Maria, foi com pressa às montanhas, a uma cidade de Judá.

[[v49-1-40]]

^<<v49-1-40,40>>^ Entrou em casa de Zacarias, e saudou Isabel.

[[v49-1-41]]

^<<v49-1-41,41>>^ Aconteceu que, apenas Isabel ouviu a saudação de Maria, o menino saltou no seu ventre, e Isabel ficou cheia do Espírito Santo;

[[v49-1-42]]

^<<v49-1-42,42>>^ e exclamou em alta voz: "Bendita és tu entre todas as mulheres, e bendito é o fruto do teu ventre.

[[v49-1-43]]

^<<v49-1-43,43>>^ Donde a mim esta dita, que a mãe do meu Senhor venha ter comigo?

[[v49-1-44]]

^<<v49-1-44,44>>^ Porque, logo que a voz da tua saudação chegou aos meus ouvidos, o menino saltou de alegria no meu ventre.

[[v49-1-45]]

^<<v49-1-45,45>>^ Bem-aventurada a que acreditou, porque se hão-de cumprir as coisas que da parte do Senhor foram ditas."

[[v49-1-46]]

^<<v49-1-46,46>>^ Então Maria disse : "A minha alma glorifica o Senhor; (ver nota)

[[v49-1-47]]

^<<v49-1-47,47>>^ e o meu espírito exulta em Deus meu Salvador,

[[v49-1-48]]

^<<v49-1-48,48>>^ porque lançou os olhos para a baixeza da sua serva. Portanto, eis que, de hoje em diante, todas as gerações me chamarão bem-aventurada.

[[v49-1-49]]

^<<v49-1-49,49>>^ Porque o Todo-poderoso fez em mim grandes coisas, o seu nome é santo.

[[v49-1-50]]

^<<v49-1-50,50>>^ E a sua misericórdia se estende de geração em geração sobre aqueles que o temem.

[[v49-1-51]]

^<<v49-1-51,51>>^ Manifestou o poder do seu braço, dispersou os homens de coração soberbo.

[[v49-1-52]]

^<<v49-1-52,52>>^ Depôs do trono os poderosos, e elevou os humildes.

[[v49-1-53]]

^<<v49-1-53,53>>^ Encheu de bens os famintos, e despediu vazios os ricos.

[[v49-1-54]]

^<<v49-1-54,54>>^ Tomou cuidado de Israel, seu servo, lembrado da sua misericórdia;

[[v49-1-55]]

^<<v49-1-55,55>>^ Conforme tinha prometido a nossos pais, a Abraão e à sua posteridade para sempre."

[[v49-1-56]]

^<<v49-1-56,56>>^ Maria ficou com Isabel cerca de três meses; depois voltou para sua casa.

[[v49-1-57]]

^<<v49-1-57,57>>^ Completou-se para Isabel o tempo de dar à luz, e deu à luz um filho.

[[v49-1-58]]

^<<v49-1-58,58>>^ Os seus vizinhos e parentes ouviram dizer que o Senhor tinha assinalado com ela a sua misericórdia, e congratulavam-se com ela.

[[v49-1-59]]

^<<v49-1-59,59>>^ Aconteceu que, ao oitavo dia, foram circuncidar o menino, e chamavam-lhe Zacarias do nome de seu pai.

[[v49-1-60]]

^<<v49-1-60,60>>^ Porém, interveio sua mãe, e disse: "De nenhuma sorte, mas será chamado João."

[[v49-1-61]]

^<<v49-1-61,61>>^ Disseram-lhe; "Ninguém há na tua parentela que tenha este nome."

[[v49-1-62]]

^<<v49-1-62,62>>^ E perguntavam por acenos ao pai do menino como queria que se chamasse.

[[v49-1-63]]

^<<v49-1-63,63>>^ Ele, pedindo uma tabuinha, escreveu assim: "O seu nome é João." Todos ficaram admirados.

[[v49-1-64]]

^<<v49-1-64,64>>^ E logo se abriu a sua boca, a sua língua se desprendeu, e falava, bendizendo a Deus.

[[v49-1-65]]

^<<v49-1-65,65>>^ O temor se apoderou de todos os seus vizinhos, e divulgaram-se todas estas maravilhas por todas as montanhas da Judeia.

[[v49-1-66]]

^<<v49-1-66,66>>^ Todos os que as ouviram, as ponderavam no seu coração, dizendo: "Quem virá a ser este menino?" Porque a mão do Senhor era com ele.

[[v49-1-67]]

^<<v49-1-67,67>>^ Zacarias, seu pai, foi cheio do Espírito Santo, e profetizou, dizendo:

[[v49-1-68]]

^<<v49-1-68,68>>^ "Bendito seja o Senhor, Deus de Israel, porque visitou e resgatou o seu povo; (ver nota)

[[v49-1-69]]

^<<v49-1-69,69>>^ e suscitou uma força para nos salvar, na casa de seu servo David, (ver nota)

[[v49-1-70]]

^<<v49-1-70,70>>^ conforme anunciou pela boca dos seus santos, de seus profetas, desde os tempos antigos;

[[v49-1-71]]

^<<v49-1-71,71>>^ que nos livraria de nossos inimigos, e das mãos de todos os que nos odeiam;

[[v49-1-72]]

^<<v49-1-72,72>>^ para exercer a sua misericórdia a favor de nossos pais, e lembrar-se da sua santa aliança, (ver nota)

[[v49-1-73]]

^<<v49-1-73,73>>^ segundo o juramento que fez a nosso pai Abraão, de nos conceder

[[v49-1-74]]

^<<v49-1-74,74>>^ que, livres das mãos dos nossos inimigos, o sirvamos sem temor,

[[v49-1-75]]

^<<v49-1-75,75>>^ (andando) diante dele com santidade e justiça, durante todos os dias da nossa vida.

[[v49-1-76]]

^<<v49-1-76,76>>^ E tu, menino, serás chamado o profeta do Altíssimo, porque irás adiante da face do Senhor, a preparar os seus caminhos;

[[v49-1-77]]

^<<v49-1-77,77>>^ para dar ao seu povo o conhecimento da salvação, pela remissão dos seus pecados,

[[v49-1-78]]

^<<v49-1-78,78>>^ graças à terna misericórdia do nosso Deus, que nos trará do alto a visita do sol nascente, (ver nota)

[[v49-1-79]]

^<<v49-1-79,79>>^ para alumiar os que jazem nas trevas e na sombra da morte; para dirigir os nossos pés no caminho da paz."

[[v49-1-80]]

^<<v49-1-80,80>>^ Ora o menino crescia e se fortificava no espírito. E habitou nos desertos até ao dia da sua manifestação a Israel.

'''

xref:048-sao-marcos/048-sao-marcos-016.adoc#v48-16-0[&#60; Capítulo Anterior] | <<v49-1-0,Topo>> | xref:049-sao-lucas/049-sao-lucas-002.adoc#v49-2-0[Próximo Capítulo &#62;]