include::./index.adoc[]

[[v49-22-0]]
=== São Lucas, 22
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* São Lucas 22 narra a última ceia de Jesus com seus discípulos antes da sua crucificação, incluindo a instituição da Santa Ceia e a traição de Judas. O capítulo também aborda a oração de Jesus no Getsêmani, a prisão de Jesus e o julgamento diante do Sinédrio. Abaixo estão cinco versículos relacionados aos temas abordados em São Lucas 22:
* Salmos 41:9: "Até o meu melhor amigo em quem eu confiava e que partilhava do meu pão, levantou contra mim o calcanhar" Este versículo profético do Salmo 41:9 se refere à traição de Judas contra Jesus, que era considerado seu amigo e companheiro.
* Marcos 14:22-24: "Enquanto comiam, Jesus tomou o pão, deu graças, partiu-o, e o deu aos seus discípulos, dizendo: "Tomem; isto é o meu corpo". Em seguida, tomou o cálice, deu graças e o ofereceu aos seus discípulos, e todos beberam dele. E lhes disse: "Isto é o meu sangue, o sangue da aliança, que é derramado em favor de muitos"" Esses versículos do Evangelho de Marcos relatam a instituição da Santa Ceia por Jesus durante a última ceia com seus discípulos, um evento também descrito em São Lucas 22.
* Mateus 26:41: "Vigiem e orem para que não caiam em tentação. O espírito está pronto, mas a carne é fraca". Jesus disse essas palavras aos seus discípulos no Getsêmani, quando pediu que eles o acompanhassem em oração, mas encontrou-os dormindo. Essas palavras de Jesus reforçam a importância da oração e da vigilância espiritual.
* Isaías 53:7: "Ele foi oprimido e afligido, contudo não abriu a sua boca; como um cordeiro foi levado para o matadouro, e como uma ovelha que diante dos seus tosquiadores fica calada, ele não abriu a sua boca." Este versículo profético de Isaías 53:7 descreve a submissão pacífica de Jesus durante seu julgamento e crucificação, que é narrado em São Lucas 22.
* João 18:38: "Pilatos lhe perguntou: "O que é a verdade?"" Essa é a pergunta feita por Pilatos a Jesus durante seu julgamento, uma cena também descrita em São Lucas 22. A resposta de Jesus não é registrada, mas essa pergunta de Pilatos continua a ecoar em questões filosóficas e teológicas sobre a natureza da verdade.
****

[[v49-22-1]]

^<<v49-22-1,1>>^ Aproximava-se a festa dos ázimos, chamada Páscoa.

[[v49-22-2]]

^<<v49-22-2,2>>^ Os príncipes dos sacerdotes e os escribas procuravam modo de matar Jesus; porém temiam o povo.

[[v49-22-3]]

^<<v49-22-3,3>>^ Ora Satanás entrou em Judas, que tinha por sobrenome Iscariotes, um dos doze,

[[v49-22-4]]

^<<v49-22-4,4>>^ o qual foi combinar com os príncipes dos sacerdotes e com os oficiais de que modo lho entregaria.

[[v49-22-5]]

^<<v49-22-5,5>>^ Eles ficaram contentes, e combinaram com ele dar-lhe dinheiro.

[[v49-22-6]]

^<<v49-22-6,6>>^ Judas deu a sua palavra, e buscava ocasião oportuna de lho entregar sem tumulto.

[[v49-22-7]]

^<<v49-22-7,7>>^ Chegou o dia dos ázimos, no qual se devia imolar a Páscoa.

[[v49-22-8]]

^<<v49-22-8,8>>^ Jesus enviou Pedro e João, dizendo: "Ide, preparai-nos a refeição pascal."

[[v49-22-9]]

^<<v49-22-9,9>>^ Eles perguntaram: "Onde queres que a preparemos?"

[[v49-22-10]]

^<<v49-22-10,10>>^ Ele disse-Ihes: "Logo que entrardes na cidade, sair-vos-á ao encontro um homem levando uma bilha de água; segui-o até à casa em que entrar;

[[v49-22-11]]

^<<v49-22-11,11>>^ e direis ao dono da casa: O Mestre manda-te dizer: Onde está o aposento em que hei-de comer a Páscoa com os meus discípulos?

[[v49-22-12]]

^<<v49-22-12,12>>^ Ele vos mostrará uma grande sala toda ornada; preparai aí o que for preciso."

[[v49-22-13]]

^<<v49-22-13,13>>^ Indo eles, encontraram tudo como Jesus Ihes dissera; e prepararam a Páscoa.

[[v49-22-14]]

^<<v49-22-14,14>>^ Chegada a hora, pôs-se Jesus à mesa com os Apóstolos, e

[[v49-22-15]]

^<<v49-22-15,15>>^ disse-lhes: "Tenho desejado ardentemente comer convosco esta Páscoa, antes de sofrer,

[[v49-22-16]]

^<<v49-22-16,16>>^ porque vos digo que não mais a comerei, até que ela se cumpra no reino de Deus."

[[v49-22-17]]

^<<v49-22-17,17>>^ Tendo tomado o cálice, deu graças, e disse: "Tomai e distribuí-o entre vós,

[[v49-22-18]]

^<<v49-22-18,18>>^ porque vos declaro que não tornarei a beber do fruto da vide, até que chegue o reino de Deus."

[[v49-22-19]]

^<<v49-22-19,19>>^ Depois tomou o pão, deu graças, partiu, e deu-lho, dizendo: "Isto é o meu corpo, que é dado por vós; fazei isto em memória de mim. (ver nota)

[[v49-22-20]]

^<<v49-22-20,20>>^ Tomou da mesma sorte o cálice, depois de cear, dizendo: "Este cálice é a nova Aliança em meu sangue, que é derramado por vós.

[[v49-22-21]]

^<<v49-22-21,21>>^ Entretanto, eis que a mão de quem me há-de entregar está à mesa comigo.

[[v49-22-22]]

^<<v49-22-22,22>>^ Na verdade, o Filho do homem vai, segundo o que está decretado, mas, ai daquele homem, por quem será entregue!"

[[v49-22-23]]

^<<v49-22-23,23>>^ Eles começaram a perguntar entre si qual deles seria o que haveria de fazer tal coisa.

[[v49-22-24]]

^<<v49-22-24,24>>^ Levantou-se também entre eles uma contenda sobre qual deles se devia considerar o maior.

[[v49-22-25]]

^<<v49-22-25,25>>^ Jesus, porém, disse-lhes: "Os reis das nações dominam sobre elas, e os que têm autoridade sobre elas chamam-se benfeitores.

[[v49-22-26]]

^<<v49-22-26,26>>^ Não assim entre vós, mas o que entre vós é o maior, faça-se como mais pequeno, e o que governa, seja como o que serve.

[[v49-22-27]]

^<<v49-22-27,27>>^ Porque, qual é maior, o que está à mesa, ou o que serve? Não é maior o que está sentado à mesa? Pois eu estou no meio de vós como um que serve.

[[v49-22-28]]

^<<v49-22-28,28>>^ Vós sois os que tendes permanecido comigo nas minhas tribulações.

[[v49-22-29]]

^<<v49-22-29,29>>^ Por isso eu preparo o reino para vós, como meu Pai o preparou para mim,

[[v49-22-30]]

^<<v49-22-30,30>>^ para que comais e bebais à minha mesa, no meu reino, e vos senteis sobre tronos a julgar as doze tribos de Israel.

[[v49-22-31]]

^<<v49-22-31,31>>^ Simão, Simão, eis que Satanás vos busca com instância para vos joeirar como trigo;

[[v49-22-32]]

^<<v49-22-32,32>>^ mas eu roguei por ti, para que a tua fé não desfaleça; e tu, uma vez convertido, conforta os teus irmãos."

[[v49-22-33]]

^<<v49-22-33,33>>^ Pedro disse-Ihe: "Senhor, eu estou pronto a ir contigo para a prisão e para a morte."

[[v49-22-34]]

^<<v49-22-34,34>>^ Jesus, porém, disse-lhe: Digo-te, Pedro, que não cantará hoje o galo, sem que tu, por três vezes, me tenhas negado que me conheces." Depois disse-lhes:

[[v49-22-35]]

^<<v49-22-35,35>>^ "Quando eu vos mandei sem bolsa, sem alforge, sem sandálias, faltou-vos porventura alguma coisa?"

[[v49-22-36]]

^<<v49-22-36,36>>^ Eles responderam: "Nada." Disse-Ihes, pois: "Mas agora quem tem bolsa, tome-a, e também alforge, quem não tem espada venda o seu manto, e compre uma. (ver nota)

[[v49-22-37]]

^<<v49-22-37,37>>^ Porque vos digo que é necessário que se cumpra em mim isto que está escrito: Foi posto entre os malfeitores (Is. 53,12), Porque as coisas que me dizem respeito estão perto do seu cumprimento."

[[v49-22-38]]

^<<v49-22-38,38>>^ Eles responderam; "Senhor, eis aqui duas espadas." Jesus disse-lhes: "Basta." (ver nota)

[[v49-22-39]]

^<<v49-22-39,39>>^ Tendo saído, foi, segundo o seu costume, para o monte das Oliveiras. Seus discípulos o seguiram.

[[v49-22-40]]

^<<v49-22-40,40>>^ Quando chegou àquele lugar, disse-lhes: "Orai, para não cairdes em tentação."

[[v49-22-41]]

^<<v49-22-41,41>>^ Afastou-se deles a distância de um tiro de pedra; e, posto de joelhos, orava,

[[v49-22-42]]

^<<v49-22-42,42>>^ dizendo: "Pai, se é do teu agrado, afasta de mim este cálice; não se faça, contudo, a minha vontade, mas a tua."

[[v49-22-43]]

^<<v49-22-43,43>>^ Então apareceu-lhe um anjo do céu, que o confortava. Posto em agonia orava mais instantemente.

[[v49-22-44]]

^<<v49-22-44,44>>^ O seu suor tornou-se como gotas de sangue, que corriam até à terra.

[[v49-22-45]]

^<<v49-22-45,45>>^ Tendo-se levantado da oração, e indo ter com seus discípulos, encontrou-os adormecidos pela tristeza.

[[v49-22-46]]

^<<v49-22-46,46>>^ Disse-lhes: "Porque dormis? Levantai-vos, e orai, para que não entreis em tentação."

[[v49-22-47]]

^<<v49-22-47,47>>^ Estando ele ainda falando, eis que chega um tropel de gente. Aquele que se chamava Judas, um dos doze, vinha à frente. Aproximou-se de Jesus para o abraçar.

[[v49-22-48]]

^<<v49-22-48,48>>^ Jesus disse-lhe: "Judas! com um beijo entregas o Filho do homem?"

[[v49-22-49]]

^<<v49-22-49,49>>^ Os que estavam com Jesus, vendo o que ia acontecer, disseram-lhe: "Senhor, se os feríssemos à espada?"

[[v49-22-50]]

^<<v49-22-50,50>>^ E um deles feriu um servo do Sumo Pontífice, e cortou-lhe a orelha direita.

[[v49-22-51]]

^<<v49-22-51,51>>^ Mas Jesus, tomando a palavra, disse: "Deixai, basta." E, tendo-lhe tocado a orelha, o sarou.

[[v49-22-52]]

^<<v49-22-52,52>>^ Disse depois Jesus aos príncipes dos sacerdotes, aos oficiais do templo, e aos anciães que tinham vindo contra ele: "Viestes armados de espadas e de varapaus como contra um ladrão.

[[v49-22-53]]

^<<v49-22-53,53>>^ Quando eu estava todos os dias convosco no templo, nunca estendestes a mão contra mim; porém, esta é a vossa hora, e o poder das trevas."

[[v49-22-54]]

^<<v49-22-54,54>>^ Prendendo-o, levaram-no a casa do príncipe dos sacerdotes. Pedro seguia-o de longe.

[[v49-22-55]]

^<<v49-22-55,55>>^ Tendo acendido fogo no meio do pátio, e, sentando-se em roda, estava também Pedro sentado no meio deles.

[[v49-22-56]]

^<<v49-22-56,56>>^ Uma criada, vendo-o sentado ao lume, e fixando-o bem, disse: "Este estava também com ele."

[[v49-22-57]]

^<<v49-22-57,57>>^ Mas Pedro o negou, dizendo: "Mulher, eu não o conheço."

[[v49-22-58]]

^<<v49-22-58,58>>^ Daí a pouco, vendo-o outro, disse-lhe: "Tu também és um deles." Pedro disse: " Ó homem, não sou."

[[v49-22-59]]

^<<v49-22-59,59>>^ Passado o intervalo quase de uma hora, um outro dizia com insistência: "Certamente que este também estava com ele, pois é galileu."

[[v49-22-60]]

^<<v49-22-60,60>>^ Pedro respondeu: "Ó homem, não sei o que dizes." Imediatamente, quando ele ainda falava, o galo cantou;

[[v49-22-61]]

^<<v49-22-61,61>>^ e, tendo-se voltado, o Senhor olhou para Pedro. Pedro então lembrou-se da palavra que lhe tinha sido dita pelo Senhor: "Antes que o galo cante, me negarás três vezes."

[[v49-22-62]]

^<<v49-22-62,62>>^ E, tendo saído para fora, chorou amargamente.

[[v49-22-63]]

^<<v49-22-63,63>>^ Os homens, que guardavam Jesus, escarneciam dele e feriam-no.

[[v49-22-64]]

^<<v49-22-64,64>>^ Vendaram-lhe os olhos, e interrogavam-no: "Adivinha, quem é que te deu?"

[[v49-22-65]]

^<<v49-22-65,65>>^ E proferiam muitas outras injúrias contra ele.

[[v49-22-66]]

^<<v49-22-66,66>>^ Quando foi dia, juntaram-se os anciães do povo, os príncipes dos sacerdotes, e os escribas. Levaram-no ao seu tribunal, e disseram-lhe: "Se tu és o Cristo, dize-no-lo."

[[v49-22-67]]

^<<v49-22-67,67>>^ Ele respondeu-lhes: "Se eu vo-lo disser, não me acreditareis;

[[v49-22-68]]

^<<v49-22-68,68>>^ também se vos fizer qualquer pergunta, não me respondereis, nem me dareis liberdade.

[[v49-22-69]]

^<<v49-22-69,69>>^ Mas, no futuro, estará sentado o Filho do homem à direita do poder de Deus."

[[v49-22-70]]

^<<v49-22-70,70>>^ Então disseram todos: "Logo tu és o Filho de Deus?" Ele respondeu: "Vós o dizeis, eu o sou."

[[v49-22-71]]

^<<v49-22-71,71>>^ Então eles disseram: "Que mais testemunho nos é necessário? Nós mesmos o ouvimos da sua boca."

'''

xref:049-sao-lucas/049-sao-lucas-021.adoc#v49-21-0[&#60; Capítulo Anterior] | <<v49-22-0,Topo>> | xref:049-sao-lucas/049-sao-lucas-023.adoc#v49-23-0[Próximo Capítulo &#62;]