include::./index.adoc[]

[[v55-1-0]]
=== Gálatas, 1
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 1 de Gálatas trata da autoridade apostólica de Paulo e da sua preocupação com o evangelho que está sendo pregado aos gálatas. Ele se surpreende com a rápida mudança que ocorreu neles e os adverte sobre aqueles que estão pregando um evangelho diferente do que eles receberam. Além disso, ele enfatiza que não recebeu o evangelho de homens, mas por meio de uma revelação de Jesus Cristo.
* 1 Coríntios 15:1-2: "Irmãos, quero lembrar-vos do evangelho que vos anunciei, o qual recebestes e no qual permaneceis firmes. Por meio dele também sois salvos, se retiverdes a palavra tal como vo-la anunciei; caso contrário, em vão teríeis crido." Esse versículo se relaciona com Gálatas 1 porque Paulo está preocupado com os gálatas que estão recebendo um evangelho diferente do que ele pregou. Ele quer lembrá-los do evangelho verdadeiro e reiterar sua importância para a salvação.
* 2 Timóteo 1:13-14: "Mantém o padrão das sãs palavras que de mim ouviste com fé e com o amor que há em Cristo Jesus. Guarda o bom depósito por meio do Espírito Santo que habita em nós." Esse versículo se relaciona com Gálatas 1 porque Paulo enfatiza que não recebeu o evangelho de homens, mas por meio de uma revelação de Jesus Cristo. Ele quer que o evangelho verdadeiro seja mantido e guardado com fidelidade e cuidado.
* Romanos 1:16-17: "Porque não me envergonho do evangelho, pois é o poder de Deus para a salvação de todo aquele que crê; primeiro do judeu, e também do grego. Porque no evangelho é revelada a justiça de Deus, uma justiça que do princípio ao fim é pela fé, como está escrito: 'O justo viverá pela fé'." Esse versículo se relaciona com Gálatas 1 porque Paulo enfatiza a importância do evangelho e como ele é o poder de Deus para a salvação. Ele quer que os gálatas entendam que a salvação é pela fé, e não pelas obras da lei.
* 1 Coríntios 1:17-18: "Pois Cristo não me enviou para batizar, mas para pregar o evangelho, não com sabedoria humana, para que a cruz de Cristo não seja esvaziada. Porque a mensagem da cruz é loucura para os que estão perecendo, mas para nós que estamos sendo salvos é o poder de Deus." Esse versículo se relaciona com Gálatas 1 porque Paulo enfatiza a centralidade da cruz de Cristo no evangelho. Ele não foi enviado para batizar, mas para pregar a mensagem da cruz, que é o poder de Deus para a salvação.
* Gálatas 2:15-16: "Nós somos judeus por natureza e não pecadores dentre os gentios. Sabendo, contudo, que o homem não é justificado por obras da lei, mas sim pela fé em Cristo Jesus, também temos crido em Cristo Jesus, para sermos justificados pela fé em Cristo e não por obras da lei, pois por obras da lei nenhuma carne será justificada." Esse versículo reforça a ideia de que a justificação não vem por meio das obras da lei, mas somente pela fé em Jesus Cristo.
****

[[v55-1-1]]

^<<v55-1-1,1>>^ Paulo, Apóstolo, não pelos homens nem por intermédio de um homem, mas por Jesus Cristo e por Deus Pai, que o ressuscitou dos mortos, (ver nota)

[[v55-1-2]]

^<<v55-1-2,2>>^ assim como todos os irmãos que estão comigo, às igrejas da Galácia.

[[v55-1-3]]

^<<v55-1-3,3>>^ Graças a vós e paz da parte de Deus nosso Pai e do Senhor Jesus Cristo,

[[v55-1-4]]

^<<v55-1-4,4>>^ o qual se deu a si mesmo por nossos pecados, para nos livrar da perversidade do mundo presente, segundo a vontade de Deus, nosso Pai,

[[v55-1-5]]

^<<v55-1-5,5>>^ ao qual seja dada glória por todos os séculos dos séculos. Assim seja.

[[v55-1-6]]

^<<v55-1-6,6>>^ Admiro-me de que, assim tão depressa, passeis daquele que vos chamou à graça de Cristo para outro Evangelho. (ver nota)

[[v55-1-7]]

^<<v55-1-7,7>>^ Evidentemente que não há outro (Evangelho diferente do que vos preguei), mas há alguns que vos perturbam e querem inverter o Evangelho de Cristo.

[[v55-1-8]]

^<<v55-1-8,8>>^ Mas, ainda que nós mesmos ou um anjo do céu vos anuncie um Evangelho diferente daquele que vos temos anunciado, seja anátema.

[[v55-1-9]]

^<<v55-1-9,9>>^ Como já vo-lo dissemos, agora de novo o digo: se alguém vos anunciar um Evangelho diferente daquele que recebestes, seja anátema.

[[v55-1-10]]

^<<v55-1-10,10>>^ Porventura é o favor dos homens que eu procuro, ou o de Deus? Porventura é aos homens que pretendo agradar? Se agradasse ainda aos homens, não seria servo de Cristo.

[[v55-1-11]]

^<<v55-1-11,11>>^ Ora eu declaro-vos, irmãos, que o Evangelho, que tem sido pregado por mim, não é segundo o homem,

[[v55-1-12]]

^<<v55-1-12,12>>^ porque não o recebi, nem aprendi de homem algum, mas por uma revelação de Jesus Cristo.

[[v55-1-13]]

^<<v55-1-13,13>>^ Ouvistes dizer de que modo vivi noutro tempo no judaísmo; com que excesso perseguia a Igreja de Deus e a devastava.

[[v55-1-14]]

^<<v55-1-14,14>>^ Avançava no judaísmo mais do que muitos meus coetâneos da minha nação, sendo em extremo zeloso das minhas tradições paternas.

[[v55-1-15]]

^<<v55-1-15,15>>^ Mas, quando aprouve àquele que me segregou desde o ventre de minha mãe e me chamou pela sua graça

[[v55-1-16]]

^<<v55-1-16,16>>^ o revelar seu Filho, em mim, para que eu o pregasse entre as gentes, imediatamente, sem consultar pessoa alguma,

[[v55-1-17]]

^<<v55-1-17,17>>^ sem ir a Jerusalém aos que eram Apóstolos antes de mim, parti para a Arábia e voltei a Damasco;

[[v55-1-18]]

^<<v55-1-18,18>>^ dali, no fim de três anos, fui a Jerusalém, para conhecer Cefas, e estive com ele quinze dias;

[[v55-1-19]]

^<<v55-1-19,19>>^ dos outros Apóstolos não vi nenhum, senão Tiago, irmão do Senhor.

[[v55-1-20]]

^<<v55-1-20,20>>^ No que vos escrevo, digo diante de Deus que não minto.

[[v55-1-21]]

^<<v55-1-21,21>>^ Depois fui para os países da Síria e da Cilícia.

[[v55-1-22]]

^<<v55-1-22,22>>^ As igrejas da Judeia, que criam em Cristo, nem mesmo de vista me conheciam,

[[v55-1-23]]

^<<v55-1-23,23>>^ mas somente tinham ouvido dizer: "Aquele que outrora nos perseguia, agora prega a fé que noutro tempo impugnava"

[[v55-1-24]]

^<<v55-1-24,24>>^ e por minha causa davam glória a Deus.

'''

xref:054-ii-corintios/054-ii-corintios-013.adoc#v54-13-0[&#60; Capítulo Anterior] | <<v55-1-0,Topo>> | xref:055-galatas/055-galatas-002.adoc#v55-2-0[Próximo Capítulo &#62;]