include::./index.adoc[]

[[v19-1-0]]
=== Ester, 1
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Ester 1 descreve um banquete oferecido pelo rei Assuero aos nobres e príncipes do seu reino. Durante sete dias, eles festejaram e beberam em abundância. No sétimo dia, o rei ordenou que sua rainha, Vasti, comparecesse diante dele e dos convidados para mostrar sua beleza. No entanto, Vasti recusou-se a obedecer ao rei, o que o deixou enfurecido. Abaixo estão cinco versículos relacionados com os temas abordados em Ester 1:
* Provérbios 20:1: "O vinho é escarnecedor, a bebida forte alvoroçadora; e todo aquele que neles errar nunca será sábio." O capítulo 1 de Ester descreve o excesso de bebida durante o banquete do rei Assuero. Esse versículo de Provérbios adverte sobre os perigos da bebida alcoólica em excesso.
* Isaías 5:11: "Ai dos que se levantam cedo para seguir a embriaguez e andam em busca de bebida forte, permanecendo até a noite, até que o vinho os esquente!" Este versículo denuncia aqueles que se entregam à bebida e alerta para os males que essa prática pode trazer.
* Provérbios 31:4-5: "Não é próprio dos reis, ó Lemuel, não é próprio dos reis beber vinho, nem dos príncipes desejar bebida forte; para que bebendo esqueçam a lei, e pervertam o direito de todos os aflitos." Este trecho de Provérbios adverte os governantes sobre o perigo do consumo de bebidas alcoólicas, que podem levá-los a esquecer suas obrigações e a prejudicar aqueles sob sua autoridade.
* Provérbios 15:1: "A resposta branda desvia o furor, mas a palavra dura suscita a ira." No capítulo 1 de Ester, o rei fica furioso com a recusa de Vasti em comparecer diante dele e dos convidados. Esse versículo de Provérbios destaca a importância da moderação e do cuidado ao falar para evitar conflitos.
* Provérbios 25:28: "Como cidade derrubada, que não tem muros, assim é o homem que não pode conter o seu espírito." O rei Assuero demonstra falta de autocontrole e temperança ao se enfurecer com Vasti. Esse versículo de Provérbios destaca a importância de controlar as emoções e cultivar a paciência.
****

[[v19-1-1]]

^<<v19-1-1,1>>^ No tempo de Assuero, que reinou desde a India até à Etiópia sobre cento e vinte e sete províncias,

[[v19-1-2]]

^<<v19-1-2,2>>^ quando ele se sentou no trono do seu reino, era a cidade de Susa a capital do seu império.

[[v19-1-3]]

^<<v19-1-3,3>>^ Ora, no ano terceiro do seu império ofereceu um grande festim, a todos os seus príncipes e a todos os seus ministros. Reuniu na sua presença os chefes do exército dos Persas e dos Medos, os grandes e os governadores das províncias,

[[v19-1-4]]

^<<v19-1-4,4>>^ para ostentar a riqueza e o esplendor do seu reino, a grandeza e o fausto do seu poder, (nesse festim que se prolongou) por muito tempo, a saber, por cento e oitenta dias.

[[v19-1-5]]

^<<v19-1-5,5>>^ Estando a terminar os dias do festim, convidou todo o povo, que se encontrava em Susa, desde o maior até ao menor, e ordenou que, durante sete dias, se preparasse um banquete no átrio do jardim do palácio real.

[[v19-1-6]]

^<<v19-1-6,6>>^ Pendiam de todas as partes pavilhões de cor celeste, branca e de jacinto, grinaldas de cordões de finíssimo linho e de púrpura, que passavam por anéis de marfim e se sustinham em colunas de mármore. Havia dispostos leitos de ouro e de prata sobre o pavimento de pórfiro, mármore branco, nácar e mármore negro.

[[v19-1-7]]

^<<v19-1-7,7>>^ Os convidados bebiam por vasos de ouro, de diferentes formas. O vinho era servido em abundância, graças à liberalidade do rei.

[[v19-1-8]]

^<<v19-1-8,8>>^ Ninguém constrangia a beber os que não queriam, antes tinha ordenado o rei aos da sua corte que deixassem cada um tomar o que quisesse.

[[v19-1-9]]

^<<v19-1-9,9>>^ A rainha Vasti também deu um banquete às mulheres, no palácio em que o rei Assuero costumava residir.

[[v19-1-10]]

^<<v19-1-10,10>>^ Ao sétimo dia, o rei, quando estava mais alegre pelo calor do vinho, que tinha bebido com excesso, ordenou a Msumau, Bazata, Harbona, Bagata, Abgata, Zetar e Carcas - os sete eunucos que lhe prestavam serviço -

[[v19-1-11]]

^<<v19-1-11,11>>^ que introduzissem à presença do rei a rainha Vasti, com o seu diadema, na cabeça, para que todos os seus povos e grandes da corte vissem a sua beleza, porque era em extremo formosa,

[[v19-1-12]]

^<<v19-1-12,12>>^ Ela, porém, recusou-se a obedecer à ordem do rei transmitida pelos eunucos. O rei, irado com isto, todo transportado em furor,

[[v19-1-13]]

^<<v19-1-13,13>>^ consultou os sábios, que andavam sempre junto dele, conforme o uso de todos os reis, e por cujo conselho fazia todas as coisas, pois conheciam as leis e costumes dos maiores.

[[v19-1-14]]

^<<v19-1-14,14>>^ (Os primeiros e os mais próximos eram Carasna, Setar, Admata, Tarsis, Mares, Marsana e Mamucan, que eram os sete principais dos Persas e dos Medos, que nunca perdiam o rei de vista e que costumavam ser os primeiros que se sentavam junto dele).

[[v19-1-15]]

^<<v19-1-15,15>>^ (Perguntou-lhes, pois, o rei) a que pena estava sujeita a rainha Vasti, por não ter obedecido à ordem que o rei Assuero lhe tinha intimado por meio dos eunucos.

[[v19-1-16]]

^<<v19-1-16,16>>^ Mamucan respondeu em presença do rei e dos grandes: A rainha Vasti não sòmente ofendeu o rei, mas também todos os povos e todos os principes que há por todas as províncias do rei Assuero.

[[v19-1-17]]

^<<v19-1-17,17>>^ Com efeito, o que a rainha fez chegará ao conhecimento de todas as mulheres, as quais serão assim levadas a desprezar os seus maridos e dirão: O rei Assuero mandou ir a rainha Vasti à sua presença, mas ela não foi.

[[v19-1-18]]

^<<v19-1-18,18>>^ De hoje em diante, as princesas da Pérsia e da Média, conhecendo o que a rainha fez, citarão isso mesmo a todos os grandes do rei, donde resultará muito desprezo e cólera.

[[v19-1-19]]

^<<v19-1-19,19>>^ Se é, pois, do teu agrado, publique-se por tua ordem um edito, e escreva-se conforme a lei dos Persas e Medos, (a qual não é permitido violar) que a rainha Vasti não torne a entrar jamais à presença do rei, e que a sua dignidade de rainha seja recebida por outra mais digna do que ela.

[[v19-1-20]]

^<<v19-1-20,20>>^ Quando isto for publicado por todas as províncias do teu império (que é vastíssimo), todas as mulheres, tanto dos grandes como dos pequenos, honrarão os seus maridos.

[[v19-1-21]]

^<<v19-1-21,21>>^ Pareceu bem este conselho ao rei e aos grandes, e o rei procedeu segundo o conselho de Mamucan.

[[v19-1-22]]

^<<v19-1-22,22>>^ Enviou cartas as todas as províncias do seu reino, a cada uma, conforme os seus caracteres, e a cada povo, conforme a sua língua, dizendo que os maridos são os senhores e os superiores em suas casas, e (mandando) que isto se publicasse por todos os povos.

'''

xref:018-judite/018-judite-016.adoc#v18-16-0[&#60; Capítulo Anterior] | <<v19-1-0,Topo>> | xref:019-ester/019-ester-002.adoc#v19-2-0[Próximo Capítulo &#62;]