include::./index.adoc[]

[[v25-11-0]]
=== Eclesiastes, 11
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Eclesiastes 11 fala sobre a importância da semeadura e da perseverança na incerteza do resultado, uma vez que o ser humano não tem controle sobre tudo o que acontece na vida. Os versículos a seguir estão relacionados com esse tema:
* Gênesis 8:22: "Enquanto durar a terra, sementeira e colheita, frio e calor, verão e inverno, dia e noite não cessarão." Este versículo fala sobre a constância das estações do ano e da importância da semeadura para a colheita.
* Provérbios 11:18: "O malvado recebe uma recompensa falsa, mas quem semeia a justiça tem verdadeira recompensa." Esse versículo destaca a importância de semear boas ações e atitudes para receber a recompensa adequada.
* Lucas 8:15: "Mas a semente que caiu em terra boa são os que ouvem a palavra com coração honesto e bom, retêm-na e perseveram até dar fruto." Este versículo fala sobre a importância da perseverança na fé e nas práticas religiosas para alcançar a salvação.
* Gálatas 6:7: "Não vos enganeis: de Deus não se zomba. O que o homem semeia, isso mesmo colherá." Este versículo destaca a importância de tomar cuidado com as ações que se pratica na vida, pois o resultado virá de acordo com o que foi semeado.
* 2 Coríntios 9:6: "Quem semeia pouco, pouco ceifará; e quem semeia muito, muito ceifará." Esse versículo destaca a importância de se investir com generosidade, alegria e devoção, para se obter uma recompensa maior.
****

[[v25-11-1]]

^<<v25-11-1,1>>^ Lança o teu pão sobre as águas que passam, porque depois de muito tempo o acharás.

[[v25-11-2]]

^<<v25-11-2,2>>^ Reparte dele com sete e mesmo com oito (ou mais pessoas), porque não sabes o mal que pode vir sobre a terra. (ver nota)

[[v25-11-3]]

^<<v25-11-3,3>>^ Quando as nuvens estiverem carregadas, derramarão chuva sobre a terra. Se a árvore cair para a parte do Meio-dia, ou para a do norte, onde cair, aí ficará. (ver nota)

[[v25-11-4]]

^<<v25-11-4,4>>^ O que observa o vento não semeia, e o que considera as nuvens nunca segará.

[[v25-11-5]]

^<<v25-11-5,5>>^ Do mesmo modo que ignoras qual é o caminho do espirito, e de que sorte se formam os ossos no ventre da mulher grávida, assim também não conheces as obras de Deus, que é o criador de todas as coisas.

[[v25-11-6]]

^<<v25-11-6,6>>^ Semeia de manhã a tua semente, e de tarde não deixes a tua mão repousar, porque não sabes o que terá bom êxito, se isto, se aquilo, ou se ambas as coisas são igualmente boas. (ver nota)

[[v25-11-7]]

^<<v25-11-7,7>>^ A luz é doce, e é coisa deleitável aos olhos o ver o sol.

[[v25-11-8]]

^<<v25-11-8,8>>^ Se um homem viver muitos anos, e em todos eles se alegrar, deve lembrar-se dos dias de trevas que serão numerosos: tudo o que sucede é vaidade.

[[v25-11-9]]

^<<v25-11-9,9>>^ Regozija-te, pois, ó jovem, na tua mocidade, e viva em alegria o teu coração na flor de teus anos; segue as inclinações do teu coração e o que agrada aos teus olhos, mas sabe que Deus te chamará a dar contas de todas estas coisas. (ver nota)

[[v25-11-10]]

^<<v25-11-10,10>>^ Lança fora do teu coração a tristeza, e afasta o mal da tua carne, porque a juventude e a adolescência são vaidade.

'''

xref:025-eclesiastes/025-eclesiastes-010.adoc#v25-10-0[&#60; Capítulo Anterior] | <<v25-11-0,Topo>> | xref:025-eclesiastes/025-eclesiastes-012.adoc#v25-12-0[Próximo Capítulo &#62;]