include::./index.adoc[]

[[v3-8-0]]
=== Levítico, 8
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Levítico 8 descreve a ordenação dos sacerdotes pelos filhos de Arão e o processo de consagração do Tabernáculo. Aqui estão cinco versículos relacionados aos temas abordados em Levítico 8:
* Êxodo 29:1-3: "Isso é o que você deve fazer para consagrá-los, para que me sirvam como sacerdotes: Pegue um novilho e dois carneiros sem defeito [...] Você os vestirá a Arão, seu irmão, e seus filhos com ele, e os ungirá, os consagrando" Este versículo é relevante porque descreve o processo de consagração dos sacerdotes, que é o tema central de Levítico 8.
* Hebreus 5:4: "Ninguém toma essa honra para si mesmo; deve ser chamado por Deus, assim como Arão foi." Este versículo se relaciona com a ordenação dos sacerdotes em Levítico 8 e destaca que não é uma posição que pode ser assumida por qualquer pessoa, mas sim algo que deve ser designado por Deus.
* Levítico 21:10: "O sumo sacerdote, entre seus irmãos, sobre cuja cabeça foi derramado o óleo da unção, e que foi consagrado para usar as vestes sacerdotais, não deixará o cabelo solto ou rasgar suas roupas." Este versículo está relacionado à consagração dos sacerdotes, destacando que os sacerdotes devem se comportar de maneira respeitosa e adequada ao seu papel como líderes religiosos.
* Êxodo 28:41: "Vista Arão com suas vestes sacerdotais e unja-o, consagrando-o. Então ele servirá como meu sacerdote." Este versículo se relaciona com a consagração dos sacerdotes em Levítico 8, descrevendo a importância de serem ungidos e vestidos com suas vestes sacerdotais.
* Levítico 8:30: "Depois Moisés pegou um pouco do óleo da unção e um pouco do sangue que estava no altar, e com ele aspergiu Arão e suas vestes, e também os filhos de Arão e as suas vestes. Assim santificou Arão e suas vestes, e também os filhos de Arão e suas vestes." Este versículo se relaciona com a consagração dos sacerdotes e destaca o uso do óleo da unção e do sangue para santificar e consagrar os sacerdotes e suas vestes.
****

[[v3-8-1]]

^<<v3-8-1,1>>^ O Senhor falou a Moisés, dizendo:

[[v3-8-2]]

^<<v3-8-2,2>>^ Toma Aarão com seus filhos, as suas vestes, o óleo da unção, o novilho pelo pecado, os dois carneiros e o cesto dos ázimos,

[[v3-8-3]]

^<<v3-8-3,3>>^ e juntarás toda a multidão à entrada do tabernáculo.

[[v3-8-4]]

^<<v3-8-4,4>>^ Moisés fez como o Senhor tinha ordenado. Junta toda a multidão diante da porta do tabernáculo,

[[v3-8-5]]

^<<v3-8-5,5>>^ disse: Eis o que o Senhor ordenou que se faça,

[[v3-8-6]]

^<<v3-8-6,6>>^ Depois apresentou Aarão e seus filhos, tendo-os lavado,

[[v3-8-7]]

^<<v3-8-7,7>>^ revestiu o pontífice da túnica de linho, cingiu-o com o cingulo, revestiu-o com o manto, pôs sobre ele o éfode,

[[v3-8-8]]

^<<v3-8-8,8>>^ e, apertando-o com o cíngulo ajustou-o ao peitoral em que estava (escrita): Doutrina e verdade.

[[v3-8-9]]

^<<v3-8-9,9>>^ Cobriu-lhe também a cabeça com a tiara, e, na frente dela, diante da testa, pôs a lâmina de ouro, o diadema sagrado, como o Senhor ordenara.

[[v3-8-10]]

^<<v3-8-10,10>>^ Tomou, além disso, o óleo da unção, com que ungiu, o tabernáculo e todas as suas alfaias.

[[v3-8-11]]

^<<v3-8-11,11>>^ Tendo aspergido sete vezes o altar para o santificar, ungiu-o com todos os seus utensílios, assim como a bacia com a sua base, e consagrou-os.

[[v3-8-12]]

^<<v3-8-12,12>>^ Derramando óleo sobre a cabeça de Aarão, ungiu-o e consagrou-o.

[[v3-8-13]]

^<<v3-8-13,13>>^ Depois de os ter apresentado, revestiu também os seus filhos de túnicas de linho, cingiu-os com os cíngulos pôs-lhes mitras na cabeça, como o Senhor tinha ordenado.

[[v3-8-14]]

^<<v3-8-14,14>>^ Ofereceu também um novilho pelo pecado. Depois de Aarão e seus filhos terem posto as suas mãos sobre a cabeça do novilho,

[[v3-8-15]]

^<<v3-8-15,15>>^ (Moisés) imolou-o, tomou o sangue e molhando nele o dedo, tocou as pontas do altar ao redor; tendo-o assim purificado e santificado, derramou o resto do sangue aos pés do altar.

[[v3-8-16]]

^<<v3-8-16,16>>^ Queimou sobre o altar a gordura, que estava sobre as vísceras, e o redanho do fígado, e os dois rins com a sua gordura.

[[v3-8-17]]

^<<v3-8-17,17>>^ Queimou fora dos acampamentos o novilho com a sua pele, as carnes e os excrementos, como o Senhor tinha ordenado.

[[v3-8-18]]

^<<v3-8-18,18>>^ Ofereceu também um carneiro em holocausto. Tendo Aarão e seus filhos posto as mãos sobre a sua cabeça,

[[v3-8-19]]

^<<v3-8-19,19>>^ imoIou-o e derramou-lhe o sangue ao redor do altar.

[[v3-8-20]]

^<<v3-8-20,20>>^ Dividindo em pedaços o carneiro, queimou no fogo a cabeça, os membros e a gordura.

[[v3-8-21]]

^<<v3-8-21,21>>^ Depois de haver lavado os intestinos e os pés, queimou sobre o altar o carneiro todo inteiro, por ser um holocausto de odor suave para o Senhor, como este lhe tinha ordenado.

[[v3-8-22]]

^<<v3-8-22,22>>^ Ofereceu mais o segundo carneiro, o da inauguração. Aarão e os seus filhos puseram as suas mãos sobre a cabeça dele,

[[v3-8-23]]

^<<v3-8-23,23>>^ e Moisés, tendo-o imolado, tomou do seu sangue e tocou com ele a extremidade da orelha direita de Aarão, e o dedo polegar da sua mão direita, e igualmente do pé.

[[v3-8-24]]

^<<v3-8-24,24>>^ Apresentou também os filhos de Aarão, e, tendo tocado com sangue do carneiro imolado a extremidade da orelha direita de cada um, e os dedos polegares da mão e do pé direito, derramou o resto (do sangue) em roda sobre o altar.

[[v3-8-25]]

^<<v3-8-25,25>>^ Separou a gordura, a cauda e toda a gordura que cobre os intestinos, e o redanho do fígado, e os dois rins com a sua gordura e a espádua direita.

[[v3-8-26]]

^<<v3-8-26,26>>^ Tornando do cesto dos ázimos, que estava diante do Senhor, um pão sem fermento, uma torta amassada em azeite, e uma filhó, pôs estas coisas sobre a gordura e a espádua direita,

[[v3-8-27]]

^<<v3-8-27,27>>^ entregando tudo juntamente a Aarão e aos seus filhos. Depois que eles elevaram estas coisas diante do Senhor,

[[v3-8-28]]

^<<v3-8-28,28>>^ Moisés recebeu-as novamente das suas mãos, e queimou-as sobre o altar do holocausto, porque era o sacrifício de inauguração, pelo fogo, de odor suave, ao Senhor.

[[v3-8-29]]

^<<v3-8-29,29>>^ Depois de ter elevado diante do Senhor o peito do carneiro da inauguração, tomou-o como porção sua, conforme lhe tinha ordenado o Senhor.

[[v3-8-30]]

^<<v3-8-30,30>>^ Tomando o óleo e o sangue que estava sobre o altar, aspergiu e consagrou com ele Aarão e as suas vestes. Os seus filhos e as vestes deles.

[[v3-8-31]]

^<<v3-8-31,31>>^ Moisés disse a Aarão e a seus filhos: Cozei as carnes diante da porta do tabernáculo e comei-as aí mesmo, e comei também os pães da inauguração que foram postos no cesto, como o Senhor me ordenou, dizendo: Aarão e seus filhos os comerão.

[[v3-8-32]]

^<<v3-8-32,32>>^ Aquilo, porém, que sobrar da carne e dos pães, consumi-lo-á o fogo.

[[v3-8-33]]

^<<v3-8-33,33>>^ Também não saireis da entrada do tabernáculo durante sete dias, até ao dia em que se completar o tempo da vossa inauguração, porque a inauguração completa-se em sete dias.

[[v3-8-34]]

^<<v3-8-34,34>>^ Aquilo que hoje se fez, o Senhor ordenou que se faça (também durante sete dias) a fim de fazer a expiação por vós.

[[v3-8-35]]

^<<v3-8-35,35>>^ De dia e de noite estareis no tabernáculo velando ao serviço do Senhor, para que não suceda morrerdes. Assim me foi ordenado.

[[v3-8-36]]

^<<v3-8-36,36>>^ Aarão e seus filhos fizeram tudo o que o Senhor lhes tinha ordenado por meio de Moisés.

'''

xref:003-levitico/003-levitico-007.adoc#v3-7-0[&#60; Capítulo Anterior] | <<v3-8-0,Topo>> | xref:003-levitico/003-levitico-009.adoc#v3-9-0[Próximo Capítulo &#62;]