include::./index.adoc[]

[[v3-20-0]]
=== Levítico, 20
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Levítico 20 apresenta uma lista de punições para diversas transgressões, incluindo relações sexuais proibidas, idolatria e outras práticas consideradas abomináveis aos olhos de Deus. Abaixo estão cinco versículos relacionados com os temas do capítulo:
* Deuteronômio 22:22 "Se for descoberto que um homem está se deitando com a mulher de outro homem, ambos devem morrer, o homem que está deitando com a mulher e a própria mulher. Assim você eliminará o mal de Israel". Este versículo mostra que a punição para adultério não é exclusiva de Levítico 20, mas é uma lei que aparece em outras partes da Bíblia.
* Deuteronômio 18:9-12 "Não sejam encontrados entre vocês quem pratique adivinhação, quem pratique magia, quem interprete presságios, quem pratique feitiçaria, quem faça encantamentos, quem consulte espíritos ou médiuns, ou quem invoque os mortos. Qualquer um que fizer essas coisas é abominável ao Senhor". Este versículo proíbe a prática da bruxaria, algo que é mencionado como uma das transgressões em Levítico 20.
* 2 Reis 23:10 "Ele [o rei Josias] desonrou os lugares de prostituição cultual que estavam no templo do Senhor, onde as mulheres teciam mantos em honra da deusa Asherah". A adoração de outros deuses, incluindo a deusa Asherah mencionada neste versículo, é proibida em Levítico 20.
* Levítico 20:13 "Se um homem se deitar com outro homem como se fosse com uma mulher, ambos cometeram um ato abominável. Eles devem ser executados por seus próprios pecados". Este versículo proíbe a homossexualidade masculina e é um exemplo da aplicação das punições mencionadas em Levítico 20.
* Jeremias 32:35 "Eles [o povo de Judá] construíram os lugares altos de Baal no vale de Ben-Hinom, para sacrificar seus filhos e suas filhas ao deus Moloque, embora eu nunca os tenha ordenado, nem jamais tenha passado pela minha mente que fizessem tal coisa abominável e levassem Judá a pecar". Este versículo mostra que o sacrifício de crianças a deuses pagãos era uma prática considerada abominável por Deus, o que também é proibido em Levítico 20.
****

[[v3-20-1]]

^<<v3-20-1,1>>^ O Senhor falou a Moisés, dizendo:

[[v3-20-2]]

^<<v3-20-2,2>>^ Dirás isto aos filhos de Israel: Se algum homem dentre os filhos de Israel e dos estrangeiros, que habitam em Israel, oferecer seus filhos a Moloch, será punido de morte: o povo o apedrejará.

[[v3-20-3]]

^<<v3-20-3,3>>^ Eu porei o meu rosto contra ele, e o cortarei do meio do seu povo, porque deu de seus filhos a Moloch, profanou o meu santuário e manchou o meu santo nome.

[[v3-20-4]]

^<<v3-20-4,4>>^ Porém, se o povo da terra, descuidando-se e, como que tendo em pouco o meu mandato, deixar ir o homem que deu de seus filhos a Moloch, e não quiser matá-lo,

[[v3-20-5]]

^<<v3-20-5,5>>^ porei o meu rosto contra esse homem e contra a sua família, e cortarei do meio do seu povo assim a ele, como a todos os que, como ele, se prostituem a Moloch.

[[v3-20-6]]

^<<v3-20-6,6>>^ A pessoa que se dirigir a magos e adivinhos, e fornicar com eles, eu porei o meu rosto contra ela, e a exterminarei do meio do seu povo. (ver nota)

[[v3-20-7]]

^<<v3-20-7,7>>^ Santificai-vos e sede santos, porque eu sou o Senhor vosso Deus.

[[v3-20-8]]

^<<v3-20-8,8>>^ Guardai os meus preceitos, e cumpri-os. Eu sou o Senhor que vos santifico.

[[v3-20-9]]

^<<v3-20-9,9>>^ O que amaldiçoar seu pai ou sua mãe, seja punido de morte; amaldiçoou o pai e a mãe: o seu sangue caia sobre ele.

[[v3-20-10]]

^<<v3-20-10,10>>^ Se algum (homem) se tomar réu de fornicação com a mulher de outro, se cometer adultério com a mulher do seu próximo, sejam punidos de morte, assim o adúltero como a adúltera.

[[v3-20-11]]

^<<v3-20-11,11>>^ O que peca com sua madrasta, e descobre (assim) a nudez de seu pai, sejam ambos punidos de morte: o seu sangue caia sobre eles.

[[v3-20-12]]

^<<v3-20-12,12>>^ Se algum pecar com sua nora, morram ambos, porque cometeram um crime: o seu sangue caía sobre elas.

[[v3-20-13]]

^<<v3-20-13,13>>^ Se um homem pecar com um homem, como se ele fosse uma mulher, ambos cometeram uma coisa execranda, sejam punidos de morte: o seu sangue caia sobre eles.

[[v3-20-14]]

^<<v3-20-14,14>>^ Aquele que toma por mulheres a filha e a mãe, cometeu um crime; será queimado vivo com elas, e não será tolerada entre vós tão grande iniquidade.

[[v3-20-15]]

^<<v3-20-15,15>>^ Aquele que peca com um animal grande ou pequeno, seja punido de morte; matai também o animal.

[[v3-20-16]]

^<<v3-20-16,16>>^ A mulher que pecar com qualquer animal, será morta juntamente com ele: o seu sangue caia sobre eles.

[[v3-20-17]]

^<<v3-20-17,17>>^ Se um tomar a sua irmã, filha de seu pai e filha de sua mãe, e vir a sua nudez, e ela vir a nudez do irmão, ambos fizeram uma coisa execranda: serão exterminados do seu povo, por terem descoberto um ao outro a sua nudez: levarão a sua iniquidade.

[[v3-20-18]]

^<<v3-20-18,18>>^ Se um se juntar com uma mulher, no tempo da menstruação e descobrir a sua nudez, e ela se deixar ver neste estado, ambos serão exterminados do meio do seu povo.

[[v3-20-19]]

^<<v3-20-19,19>>^ Não descobrirás a nudez de tua tia materna ou paterna; o que fizer isto, descobriu a ignominia de sua própria carne; ambos levarão a sua iniquidade.

[[v3-20-20]]

^<<v3-20-20,20>>^ Se um pecar com a mulher de seu tio paterno ou materno, e descobrir a nudez de seu tio; ambos levarão o seu pecado; morram sem filhos. (ver nota)

[[v3-20-21]]

^<<v3-20-21,21>>^ O que tomar a mulher de seu irmão, fez uma coisa ilícita: descobriu a nudez de seu irmão; não terão filhos.

[[v3-20-22]]

^<<v3-20-22,22>>^ Guardai as minhas leis e os meus mandamentos, ponde-os em prática, a fim de que a terra em que estais para entrar e para habitar, não vos vomite também a vós.

[[v3-20-23]]

^<<v3-20-23,23>>^ Não caminheis segundo os costumes das nações que eu estou para expulsar da vossa vista, porque fizeram todas estas coisas, e eu as abominei.

[[v3-20-24]]

^<<v3-20-24,24>>^ Mas eu vos digo: Possuireis esta terra, a qual eu vos darei em herança, terra onde corre o leite e o mel. Eu sou o Senhor vosso Deus, que vos separei de todos os outros povos.

[[v3-20-25]]

^<<v3-20-25,25>>^ Separai, pois, também os animais puros dos impuros, e as aves puras das impuras; não manchas as vossas pessoas com os animais, com as aves, e com tudo o que se move sobre a terra, e que eu vos declarei ser impuro.

[[v3-20-26]]

^<<v3-20-26,26>>^ Sereis para mim santos, porque Eu, o Senhor, sou santo, e vos separei de todos os outros povos, para serdes meus.

[[v3-20-27]]

^<<v3-20-27,27>>^ O homem ou mulher em que houver espírito pitónico ou de adivinho, seja punido de morte. Apedreja-los-ão: o seu sangue caia sobre eles.

'''

xref:003-levitico/003-levitico-019.adoc#v3-19-0[&#60; Capítulo Anterior] | <<v3-20-0,Topo>> | xref:003-levitico/003-levitico-021.adoc#v3-21-0[Próximo Capítulo &#62;]