include::./index.adoc[]

[[v13-11-0]]
=== I Crônicas, 11
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* 1 Crônicas 11 registra a ascensão do Rei Davi ao trono de Israel e o estabelecimento de sua capital em Jerusalém. O capítulo destaca seus valentes guerreiros, incluindo seus Três Grandes Heróis: Josheb-Basshebeth, Eleazar e Shammah. Eles se destacaram por suas habilidades de combate e pela devoção a Davi. A partir deste capítulo, escolhi cinco versículos relacionados aos temas de liderança, coragem, lealdade e vitória, que podem ser encontrados em outras partes da Bíblia.
* Josué 1:9: "Não te mandei eu? Sê forte e corajoso; não temas, nem te espantes, porque o SENHOR teu Deus é contigo, por onde quer que andares." Assim como Davi liderou seu povo com coragem e determinação, Deus também exortou Josué a liderar os filhos de Israel com força e coragem. Esta passagem mostra como a liderança requer coragem e confiança em Deus.
* Provérbios 17:17: "Em todo tempo ama o amigo e na angústia se faz o irmão." Davi e seus guerreiros compartilharam uma forte lealdade e compromisso um com o outro. Este versículo de Provérbios destaca a importância da amizade e lealdade, especialmente em tempos difíceis.
* Salmos 20:7: "Uns confiam em carros, outros em cavalos, mas nós faremos menção do nome do SENHOR nosso Deus." Davi e seus guerreiros reconheceram que a vitória não dependia de seus próprios recursos ou habilidades, mas da graça e poder de Deus. Este versículo do Salmo 20 destaca a importância de confiar em Deus em vez de confiar em nossa própria força.
* 2 Timóteo 2:3: "Sofre comigo como bom soldado de Jesus Cristo." Este versículo de 2 Timóteo destaca a importância de ser um soldado fiel de Cristo. Assim como Davi e seus guerreiros lutaram com coragem e devoção ao seu rei, também somos chamados a lutar como bons soldados de Cristo.
* 1 João 5:4: "Porque todo o que é nascido de Deus vence o mundo; e esta é a vitória que vence o mundo: a nossa fé." Este versículo de 1 João destaca que a verdadeira vitória é alcançada através da fé em Deus. Davi e seus guerreiros venceram muitas batalhas, mas sua verdadeira vitória veio da fidelidade e confiança em Deus.
****

[[v13-11-1]]

^<<v13-11-1,1>>^ Congregou-se todo o Israel com Davide em Hebron, dizendo: Nós somos teus ossos e tua carne.

[[v13-11-2]]

^<<v13-11-2,2>>^ Já antes, quando ainda reinava Saul, eras tu que conduzias Israel, porque a ti disse o Senhor teu Deus: Tu apascentarás o meu povo de Israel, tu serás o seu príncipe.

[[v13-11-3]]

^<<v13-11-3,3>>^ Todos os anciães de Israel foram, pois, ter com o rei a Hebron. Davide fez aliança com eles diante do Senhor, e eles ungiram-no rei sobre Israel, em conformidade com a palavra que o Senhor tinha proferido por meio de Samuel.

[[v13-11-4]]

^<<v13-11-4,4>>^ Davide marchou com todo o Israel sobre Jerusalém, que é Jebus, onde estavam os Jebuseus, habitantes do país.

[[v13-11-5]]

^<<v13-11-5,5>>^ Os que habitavam em Jebus disseram a Davide: Tu não entrarás aqui. Contudo Davide tomou a fortaleza de Sião, que é a cidade de Davide.

[[v13-11-6]]

^<<v13-11-6,6>>^ Davide disse: Aquele que primeiro ferir um Jebuseu será príncipe e chefe. O primeiro a subir foi Joab, filho de Sarvia, que, (por isso) foi feito chefe.

[[v13-11-7]]

^<<v13-11-7,7>>^ Davide habitou na fortaleza, que, por tal motivo, se chamou cidade de Davide.

[[v13-11-8]]

^<<v13-11-8,8>>^ Edificou a cidade ao redor, desde Melo até à outra extremidade: Joab reparou o resto da cidade.

[[v13-11-9]]

^<<v13-11-9,9>>^ Davide fazia progressos, adiantando-se e fortalecendo-se, e o Senhor dos exércitos era com ele.

[[v13-11-10]]

^<<v13-11-10,10>>^ São estes os principais entre os homens fortes de Davide, que o ajudaram no seu reinado sobre todo de o Israel, segundo a palavra que o Senhor tinha dito a Israel.

[[v13-11-11]]

^<<v13-11-11,11>>^ Este é o número dos valentes de Davide: Jesbaão, filho de Hacamoni, chefe dos trinta. Este levantou a sua lança sobre trezentos, que feriu duma só vez.

[[v13-11-12]]

^<<v13-11-12,12>>^ Depois deste, Eleazar Aoíta, filho de Dodo, era um dos três valentes.

[[v13-11-13]]

^<<v13-11-13,13>>^ Este achou-se com Davide em Fesdomim, quando os Filisteus se juntaram ali para dar batalha. Os campos daquela região estavam cheios de cevada, e o povo tinha fugido diante dos Filisteus,

[[v13-11-14]]

^<<v13-11-14,14>>^ mas estes (Eleazar e Sema) conservaram-se firmes no meio do campo e defenderam-no; tendo destroçado os Filisteus, deu o Senhor uma grande vitória ao seu povo.

[[v13-11-15]]

^<<v13-11-15,15>>^ Três dos trinta príncipes desceram à rocha, onde estava Davide, junto da caverna de Odolão quando os Filisteus tinham acampado no vale de Refain.

[[v13-11-16]]

^<<v13-11-16,16>>^ Davide estava na fortaleza, e uma guarnição de Filisteus estava em Belém.

[[v13-11-17]]

^<<v13-11-17,17>>^ Davide teve então um desejo e disse: Oh! quem me dera água da cisterna de Belém, que está junto da porta (da cidade)!

[[v13-11-18]]

^<<v13-11-18,18>>^ Imediatamente estes três homens atravessaram pelo meio do acampamento dos Filisteus, tiraram água da cisterna de Belém, que estava junto da porta, e levaram-na a Davide, para que bebesse; ele não a quis beber, mas antes a ofereceu em libação ao Senhor,

[[v13-11-19]]

^<<v13-11-19,19>>^ dizendo: Longe de mim que eu tal faça na presença do meu Deus, que beba o sangue destes homens! De facto trouxeram-me água com perigo das suas vidas. Por esta causa, não a quis beber. Isto fizeram aqueles três valentíssimos.

[[v13-11-20]]

^<<v13-11-20,20>>^ Abisai, irmão de Joab, era o primeiro dos outros três. Também ele levantou a sua lança contra trezentos, que matou, e era o mais famoso entre os três.

[[v13-11-21]]

^<<v13-11-21,21>>^ Era o mais notável dentre os três do segundo terno, e seu chefe, todavia nunca igualou os três primeiros.

[[v13-11-22]]

^<<v13-11-22,22>>^ Banaias, (natural) de Cabseel, filho de Jojada, homem valentíssimo que se assinalou em grandes feitos, matou os dois Arieis (ou grandes leões) de Moab. (Um dia) desceu e matou um leão no meio duma cisterna em tempo de neve.

[[v13-11-23]]

^<<v13-11-23,23>>^ Matou também um Egípcio, cuja estatura era de cinco côvados, e tinha uma lança como o órgão do tear dos tecelões. Foi contra ele com um pau, tirou-lhe a lança que tinha na mão, e com esta mesma lança o matou.

[[v13-11-24]]

^<<v13-11-24,24>>^ Estas coisas fez Banalaa, filho de Jojada, que era o mais afamado entre os três valentes,

[[v13-11-25]]

^<<v13-11-25,25>>^ o principal entre os trinta; todavia não igualava os três primeiros. Davide o admitiu para seu conselheiro íntimo.

[[v13-11-26]]

^<<v13-11-26,26>>^ Os mais valentes do exército eram: Asael irmão de Joab, Alcanan de Belém, filho de Dodo.

[[v13-11-27]]

^<<v13-11-27,27>>^ Samot de Arori, Heles de Falon,

[[v13-11-28]]

^<<v13-11-28,28>>^ Ira de Técua, filho de Aces, Abiezer de Anatot,

[[v13-11-29]]

^<<v13-11-29,29>>^ Sobocai de Husat, Ilai de Aó,

[[v13-11-30]]

^<<v13-11-30,30>>^ Maarai de Netofat, Heled, filho de Baana de Netofat,

[[v13-11-31]]

^<<v13-11-31,31>>^ Etai, filho de Ribai de Gabaa da tribo de Benjamim, Banaia de Faraton,

[[v13-11-32]]

^<<v13-11-32,32>>^ Hurai da torrente de Gaas, Abiel de Harbat, Azmot de Baurami, Eliab de Salaboni;

[[v13-11-33]]

^<<v13-11-33,33>>^ Bené-Assen Gezonita, Jonatan filho de Sage de Arari,

[[v13-11-34]]

^<<v13-11-34,34>>^ Aião filho de Sacar de Axari,

[[v13-11-35]]

^<<v13-11-35,35>>^ Elifal filho de Ur,

[[v13-11-36]]

^<<v13-11-36,36>>^ Efer de Mecerat, Aia de Felon,

[[v13-11-37]]

^<<v13-11-37,37>>^ Hesro do Carmelo. Naarai, filho de Asbal,

[[v13-11-38]]

^<<v13-11-38,38>>^ Joel, irmão de Natan, Mibaar, filho de Agaral,

[[v13-11-39]]

^<<v13-11-39,39>>^ Selec de Amoni, Naarai de Berot, escudeiro de Joab, filho de Sarvia,

[[v13-11-40]]

^<<v13-11-40,40>>^ Ira de Jeter, Gareb de Jeter,

[[v13-11-41]]

^<<v13-11-41,41>>^ Urias Heteu, Zabad filho de Ooli,

[[v13-11-42]]

^<<v13-11-42,42>>^ Adina filho de Siza da tribo de Ruben, chefe dos Rubenitas, e com ele outros trinta;

[[v13-11-43]]

^<<v13-11-43,43>>^ Hanan, filho de Maca, Josafat Matani,

[[v13-11-44]]

^<<v13-11-44,44>>^ Ozias Astarotita, Sama e Jeiel, filhos de Hotão de Arori,

[[v13-11-45]]

^<<v13-11-45,45>>^ Jediel, filho de Samri, Joa, seu irmão, de Tosa,

[[v13-11-46]]

^<<v13-11-46,46>>^ Eliel de Maumi, Jeribal e Josaia, filhos de Elnaem, Jetma de Moab, Eliel, Obed e Jeslel de Masobia.

'''

xref:013-i-cronicas/013-i-cronicas-010.adoc#v13-10-0[&#60; Capítulo Anterior] | <<v13-11-0,Topo>> | xref:013-i-cronicas/013-i-cronicas-012.adoc#v13-12-0[Próximo Capítulo &#62;]