include::./index.adoc[]

[[v13-4-0]]
=== I Crônicas, 4
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* 1 Crônicas 4 descreve a genealogia de Judá, com destaque para uma lista de nomes e as bênçãos que Deus concedeu a alguns deles. Além disso, o capítulo também apresenta a oração de Jabes, que pediu a Deus por bênçãos e proteção.
* Gênesis 12:2: "De ti farei uma grande nação, e te abençoarei, e te engrandecerei o nome. Sê tu uma bênção!" - A bênção de Deus sobre Abraão e sua descendência é reafirmada, o que se relaciona com o tema de bênçãos em 1 Crônicas 4.
* Salmos 20:4: "Conceda-te segundo o teu coração, e cumpra todo o teu desígnio." - Este versículo fala sobre a realização dos desejos do coração de alguém, que é algo que a oração de Jabes busca.
* 2 Crônicas 20:12: "Ó nosso Deus, porventura não julgarás tu? Pois em nós não há força perante esta grande multidão que vem contra nós, e não sabemos nós o que faremos; porém os nossos olhos estão postos em ti." - A oração de Jabes é um exemplo de confiança e dependência de Deus, semelhante à confiança que o rei Josafá depositou em Deus em 2 Crônicas 20.
* Neemias 11:6: "Todos os filhos de Pérez, que habitavam em Jerusalém, eram quatrocentos e sessenta e oito homens valentes." - Este versículo fala sobre os descendentes de Judá que viveram em Jerusalém, que é um tema abordado em 1 Crônicas 4.
* Êxodo 33:15: "Então respondeu Moisés ao Senhor: Se a tua presença não há de ir comigo, não nos faças subir daqui." - Este versículo enfatiza a importância da presença de Deus na vida de Seu povo, o que é uma questão central na oração de Jabes em 1 Crônicas 4.
****

[[v13-4-1]]

^<<v13-4-1,1>>^ Filhos (ou descendentes) de Judá foram: Farés, Hesron, Carmi, Hur e Sobal.

[[v13-4-2]]

^<<v13-4-2,2>>^ Raias, filho de Sobal, gerou Jaat, de quem nasceram Aumal e Laad. Estas são as famílias dos Saratitas.

[[v13-4-3]]

^<<v13-4-3,3>>^ Estes são os descendentes do pai de Etão: Jezrael, .Joseina e Jedebos, que tiveram uma irmã chamada Asalelfuni.

[[v13-4-4]]

^<<v13-4-4,4>>^ Fanuel foi pai de Gedor, e Ezer pai de Hosa. Estes são os filhos de Hur, primogênito de Efrata, pai de Belém,

[[v13-4-5]]

^<<v13-4-5,5>>^ Assur, pai de Tecua, teve duas mulheres: Halaa e Naara.

[[v13-4-6]]

^<<v13-4-6,6>>^ De Naara teve Oozão, Hefer, Temamos e Aastari; estes são os filhos de Naara.

[[v13-4-7]]

^<<v13-4-7,7>>^ Os filhos de Halaa foram: Seret, Isaar e Etnan.

[[v13-4-8]]

^<<v13-4-8,8>>^ Cós gerou Anob, Soboba e a família de Aareel, filho de Arum

[[v13-4-9]]

^<<v13-4-9,9>>^ Jabes foi mais ilustre do que seus irmãos, e sua mãe pôs-lhe o nome de Jabes, dizendo: Porque o dei à luz com dor.

[[v13-4-10]]

^<<v13-4-10,10>>^ Jabes invocou o Deus de Israel, dizendo: Oh! Se tu me cumulasses de bênçãos e dilatasses os meus limites, se a tua mão fosse comigo, e não permitisses que eu fosse oprimido pela malícia!... E Deus concedeu-lhe o que ele pediu.

[[v13-4-11]]

^<<v13-4-11,11>>^ Caleb, irmão de Sua, gerou Maír, que foi pai de Eston.

[[v13-4-12]]

^<<v13-4-12,12>>^ Eston gerou Betrafa, Fess e Teina, pai dos habitantes da cidade de Naas. Estes são os povoadores de Reca.

[[v13-4-13]]

^<<v13-4-13,13>>^ Filhos de Cenez: Otoniel e Saraia. Filhos de Otoniel: Hatat e Maonati.

[[v13-4-14]]

^<<v13-4-14,14>>^ Maonati gerou Ofra, Saraia gerou Joab, pai dos habitantes do Vale dos Artífices, (assim chamado) porque ali habitavam os artífices.

[[v13-4-15]]

^<<v13-4-15,15>>^ Os filhos de Caleb, filho de Jefone, foram: Hir, Ela e Naão. Filho de Ela: Cenez.

[[v13-4-16]]

^<<v13-4-16,16>>^ Os filhos de Jeleleel, foram: Zif, Zifa, Tiria e Asrael.

[[v13-4-17]]

^<<v13-4-17,17>>^ Os filhos de Ezra foram: Jeter, Mered, Efer e Jalon. A mulher de Mered (a egípcia) deu à lua Myriam, Sammai, e Jesba, pai dos habitantes de Estamo.

[[v13-4-18]]

^<<v13-4-18,18>>^ (Outra) sua mulher, Odala, deu à luz Jared, pai de Gedor, e Heber, pai de Soco, e Icutiel, pai de Zanoe. Estes são os filhos de Betia, filha de Faraó, com a qual casou Mered.

[[v13-4-19]]

^<<v13-4-19,19>>^ Os filhos de (sua) mulher Odala, irmã de Naão, pai de Ceila, foram: Garmi e Estamo, que era de Macati.

[[v13-4-20]]

^<<v13-4-20,20>>^ Os filhos de Simão foram: Amnon, Binna, filho de Hanan, e Tilon. Os filhos de Jesi foram: Zoet e Benzoet.

[[v13-4-21]]

^<<v13-4-21,21>>^ Os filhos de Sela, (terceiro) filho de Judá, foram: Her, pai de Leca, Laada, pai de Meresa, e as famílias da casa dos fabricantes de linho fino na casa do juramento,

[[v13-4-22]]

^<<v13-4-22,22>>^ e Joaquim (cujo nome significa) o que fez parar o sol, e os habitantes de Cozeba (isto é) os homens da Mentira, e Joás e Saraf (isto é) o Afouto e o Ardente, que foram príncipes em Moab e Laem. Estas memórias são antigas.

[[v13-4-23]]

^<<v13-4-23,23>>^ Estes são os oleiros que habitavam nas hortas e nos cercados, nas casas do rei: trabalhando para ele, ali moravam.

[[v13-4-24]]

^<<v13-4-24,24>>^ Os filhos de Simeão foram: Namuel, Jamin, Jarib, Zara, Saul.

[[v13-4-25]]

^<<v13-4-25,25>>^ Selum, seu filho, foi pai de Mabsão, o qual teve por filho a Masma.

[[v13-4-26]]

^<<v13-4-26,26>>^ Filhos de Masma: Hamuel, de quem foi filho Zacur, do qual foi filho Semei.

[[v13-4-27]]

^<<v13-4-27,27>>^ Semei teve dezasseis filhos e seis filhas, mas seus irmãos não tiveram muitos filhos, e toda a sua posteridade não pode igualar o número dos filhos de Judá.

[[v13-4-28]]

^<<v13-4-28,28>>^ Habitaram em Bersabé, em Molada, em Hasarsual,

[[v13-4-29]]

^<<v13-4-29,29>>^ em Bata, em Asom, em Tolad,

[[v13-4-30]]

^<<v13-4-30,30>>^ em Batuel, em Horma, em Siceleg,

[[v13-4-31]]

^<<v13-4-31,31>>^ em Betmarcabot, em Hasarsusim, em Betberal e em Saarim. Estas foram os suas cidades até ao reinado de Davide.

[[v13-4-32]]

^<<v13-4-32,32>>^ (Tinham também): Etão, Aen, Remon, Toquen e Asan, cinco cidades,

[[v13-4-33]]

^<<v13-4-33,33>>^ com todas as aldeias dos seus arredores, até Baal. Esta é a sua habitação e o seu registo genealógico.

[[v13-4-34]]

^<<v13-4-34,34>>^ Mosabab, Jemlec, Josa, filho de Amasias,

[[v13-4-35]]

^<<v13-4-35,35>>^ Joel, Jeú, filho de Josabia, filho de Saraia, filho de Asiel,

[[v13-4-36]]

^<<v13-4-36,36>>^ Elioenai, Jacoba, Isuaia, Asaia, Adlel, Ismiel, Banaia,

[[v13-4-37]]

^<<v13-4-37,37>>^ Ziza, filho de Sefei, filho de Alon, filho de Idaia, filho de Semri, filho de Samaia.

[[v13-4-38]]

^<<v13-4-38,38>>^ Estes são os príncipes ilustres nas suas famílias, e multiplicaram-se em extremo as suas casas patriarcais.

[[v13-4-39]]

^<<v13-4-39,39>>^ (Por isso) saíram a fim de ocupar Gadôr até no oriente do vale, em busca de pastos para os seus gados.

[[v13-4-40]]

^<<v13-4-40,40>>^ Encontraram pastagens abundantes e muito excelentes, e uma terra espaçosíssima, tranquila e fértil, onde antes tinham habitado os descendentes de Cam.

[[v13-4-41]]

^<<v13-4-41,41>>^ Estes pois, que acima nomeamos, vieram no tempo de Ezequias, rei de Judá; deitaram abaixo as suas tendas, mataram os habitantes que ali encontraram, destruindo-os (assim) até ao dia de hoje; habitaram em lugar deles, porque encontraram abundantíssimos pastos.

[[v13-4-42]]

^<<v13-4-42,42>>^ Igualmente quinhentos homens dos filhos de Simeão passaram ao monte de Seir, tendo por chefes a Faltias, Naarias, Rafaias e Oziel, filhos de Jezl,

[[v13-4-43]]

^<<v13-4-43,43>>^ e acabaram com os restos dos Amalecitas, que tinham podido salvar-se, ficando a habitar ali, em seu lugar, até ao dia de hoje.

'''

xref:013-i-cronicas/013-i-cronicas-003.adoc#v13-3-0[&#60; Capítulo Anterior] | <<v13-4-0,Topo>> | xref:013-i-cronicas/013-i-cronicas-005.adoc#v13-5-0[Próximo Capítulo &#62;]