include::./index.adoc[]

[[v30-49-0]]
=== Jeremias, 49
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 49 do livro de Jeremias traz uma série de profecias de julgamento contra várias nações vizinhas de Israel, incluindo Edom, Amom, Moabe e Babilônia. Os versículos relacionados com esses temas são:
* Isaías 21:9: "Eis que aqui vem um homem num carro com um par de cavalos. Ele os chama e diz: 'Caiu, caiu Babilônia; todas as imagens de seus deuses foram quebradas no chão.'" Este verso fala sobre a queda de Babilônia, uma das nações que recebe uma profecia de julgamento em Jeremias 49.
* Ezequiel 25:4: "Portanto, eis que entregarei Moabe para os orientais como herança, juntamente com os filhos de Amom." Esse verso fala sobre a punição que Deus trará sobre Moabe e Amom, dois dos povos que também são alvos das profecias de julgamento em Jeremias 49.
* Obadias 1:8: "Não naquele dia, diz o Senhor, eu destruirei os sábios de Edom e o entendimento da montanha de Esaú." Esse verso fala sobre a destruição que virá sobre Edom, outra nação mencionada em Jeremias 49.
* Isaías 16:6: "Ouvimos falar da arrogância de Moabe, de sua arrogância insuportável, de sua arrogância, orgulho e revolta; mas sua fanfarronice não é nada." Esse verso fala sobre a arrogância de Moabe, uma das nações que receberão a punição de Deus em Jeremias 49.
* Ezequiel 35:5: "Porque você mostrou uma inimizade eterna e entregou os israelitas ao fio da espada no tempo da calamidade final, no tempo da sua iniqüidade final." Este verso fala sobre a hostilidade que Edom mostrou para com Israel, o que levará a nação a receber a ira de Deus em Jeremias 49.
****

[[v30-49-1]]

^<<v30-49-1,1>>^ (Profecia) contra os filhos de Amon. Assim fala o Senhor: Porventura não tem filhos Israel, não tem herdeiro? Por que razão, pois, Melcom tomou conta de Gad, como de uma herança, e o seu povo morou nas suas cidades? (ver nota)

[[v30-49-2]]

^<<v30-49-2,2>>^ Portanto eis vem o tempo, diz o Senhor, em que farei ouvir em Rabat, (capital) dos filhos de Amon, o grito de guerra. Será reduzida a montão de ruínas, [as suas filhas} arderão no fogo. Israel tomará posse dos seus espoliadores. (ver nota)

[[v30-49-3]]

^<<v30-49-3,3>>^ Lamenta-te, Hesebon, porque Hai foi assolada; gritai, filhas de Habat, cingi-vos de cilícios, chorai e dai voltas pelos apriscos, porque Melcom será levado ao cativeiro, juntamente com os seus sacerdotes e os seus chefes.

[[v30-49-4]]

^<<v30-49-4,4>>^ Por que te glorias tu de teus (amenos) vales? É fértil o teu vale, filha rebelde, que confias nos teus tesouros e dizes: Quem virá contra mim?

[[v30-49-5]]

^<<v30-49-5,5>>^ Eis que farei vir sobre ti o terror, diz o Senhor Deus dos exércitos, por meio de todos os que estão à roda de ti: sereis dispersos, cada um por seu lado, e não haverá quem vos recolha na vossa fuga.

[[v30-49-6]]

^<<v30-49-6,6>>^ Mas, depois disto, farei voltar os cativos dos filhos de Amon, diz o Senhor.

[[v30-49-7]]

^<<v30-49-7,7>>^ Contra a Idumeia. Assim fala o Senhor dos exércitos. Pois quê, já não há sabedoria em Teman? Perdeu-se o conselho dos seus (homens) atilados, tornou-se vã a sua sabedoria?

[[v30-49-8]]

^<<v30-49-8,8>>^ Fugi, voltai as costas, descei às mais profundas cavernas da terra, habitantes de Dedan, porque faço vir a ruína sobre Esaú, o tempo do seu castigo.

[[v30-49-9]]

^<<v30-49-9,9>>^ Se vêm a ti vindimadores, não te deixam um cacho; se ladrões de noite, fazem uma pilhagem total.

[[v30-49-10]]

^<<v30-49-10,10>>^ Eu esquadrinho Esaú, ponho às claras os seus esconderijos; não poderá ocultar-se. Destruída foi a sua linhagem, os seus irmãos e os seus vizinhos; não subsiste mais.

[[v30-49-11]]

^<<v30-49-11,11>>^ Deixa (todavia) os teus órfãos, que eu lhes salvarei a vida; que as tuas viúvas esperem em mim.

[[v30-49-12]]

^<<v30-49-12,12>>^ Porque isto diz o Senhor: Eis que aqueles que não estavam condenados a beber o cálice (da ira do Senhor) de certo o beberão; e tu ficarás impune? Não ficarás impune, com certeza o beberás.

[[v30-49-13]]

^<<v30-49-13,13>>^ Por mim mesmo o juro, diz o Senhor; Brosra será um objecto de pasmo e de opróbrio, um deserto e uma maldição; todas as suas cidades serão ruínas sempiternas.

[[v30-49-14]]

^<<v30-49-14,14>>^ Recebi uma notícia do Senhor, um embaixador foi enviado às nações (para lhes dizer): Juntai-vos e vinde contra este povo. De pé, ao combate!

[[v30-49-15]]

^<<v30-49-15,15>>^ Vê que te fiz pequenino (ó Idumeu) entre as nações, desprezível entre os homens.

[[v30-49-16]]

^<<v30-49-16,16>>^ A tua arrogância enganou-te, assim como a soberba do teu coração, (ó Idumeu) tu que habitas nas concavidades dos rochedos, que ocupas o cume do outeiro. Ainda que pusesses no alto como águia, o teu ninho, eu te arrancaria de lá, diz o Senhor.

[[v30-49-17]]

^<<v30-49-17,17>>^ A Idumeia será um objecto de pasmo; todo o que atravessar pelas suas terras, pasmará e fará mofa de todas as suas desgraças.

[[v30-49-18]]

^<<v30-49-18,18>>^ Assim como na destruição de Sodoma, de Gomorra e das cidades vizinhas, diz o Senhor, também ninguém ali habitará, nenhum homem fará a sua morada.

[[v30-49-19]]

^<<v30-49-19,19>>^ Eis que (o inimigo), como leão, subirá das espessuras do Jordão às pastagens perenes (da Idumeia); farei fugir subitamente Edom, e colocarei em seu lugar desgraças, aquele que escolhi. Porque, quem há semelhante a mim? Quem me poderá pedir contas? Qual o pastor (ou capitão) que ousará resistir à minha face?

[[v30-49-20]]

^<<v30-49-20,20>>^ Portanto ouvi a resolução que o Senhor formou contra Edom, os seus projetos contra os moradores de Teman: Como os mais pequenos do rebanho serão arrastados (à morte), e a sua pastagem será devastada.

[[v30-49-21]]

^<<v30-49-21,21>>^ Ao estrondo da sua ruína se comove a terra: Chega ao Mar Vermelho o clamor da sua voz.

[[v30-49-22]]

^<<v30-49-22,22>>^ Eis que (o inimigo) subirá como águia, voará e estenderá as suas asas sobre Bosra; e o coração dos guerreiros da Idumeia será naquele dia como o coração duma mulher que está com dores de parto.

[[v30-49-23]]

^<<v30-49-23,23>>^ Contra Damasco: Foram confundidas Hamat e Arfad, porque ouviram uma notícia má; ficaram estarrecidos; agitados como o mar em tormenta, não podem ter repouso.

[[v30-49-24]]

^<<v30-49-24,24>>^ Damasco perdeu a coragem, lançou-se a fugir, o tremor apoderou-se dela; a angústia e as dores tomaram-na, como à mulher que está com dores de parto.

[[v30-49-25]]

^<<v30-49-25,25>>^ Como ficou abandonada a cidade famosa, a cidade da alegria?

[[v30-49-26]]

^<<v30-49-26,26>>^ Pois também cairão os seus jovens nas suas praças, e todos os homens de armas perecerão naquele dia, diz o Senhor dos exércitos.

[[v30-49-27]]

^<<v30-49-27,27>>^ E porei fogo aos muros de Damasco, que devorará as muralhas de Benadad.

[[v30-49-28]]

^<<v30-49-28,28>>^ Contra Cedar e contra os reinos de Hasor, que destruiu Nabucodonosor, rei de Babilônia. Isto diz o Senhor: Levantai-vos, marchai contra Cedar, exterminai os filhos do Oriente.

[[v30-49-29]]

^<<v30-49-29,29>>^ Tomem as suas tendas e os seus rebanhos; tomem as suas peles, todos os seus móveis e os seus camelos! Clamem sobre eles: Terror de todas as partes.

[[v30-49-30]]

^<<v30-49-30,30>>^ Fugi, ide-vos a toda a pressa, escondei-vos nas cavernas, vós que morais em Hasor, diz o Senhor, porque Nabucodonosor, rei de Babilônia, forjou um plano contra vós, formou projetos contra vós.

[[v30-49-31]]

^<<v30-49-31,31>>^ Levantai-vos e marchai contra uma nação tranquila e que vive sem receio, diz o Senhor (aos Caldeus), que não tem portas nem ferrolhos, que vive à parte.

[[v30-49-32]]

^<<v30-49-32,32>>^ Os seus camelos serão postos a saque, e a multidão dos seus animais será uma presa. Espalharei a todos os ventos os que rapam o cabelo das têmporas, e de todos os lados lançarei a desgraça sobre eles, diz o Senhor.

[[v30-49-33]]

^<<v30-49-33,33>>^ Hasor ficará sendo guarida de chacais, um deserto para sempre; ninguém ali habitará, nenhum filho do homem ali fará a sua morada.

[[v30-49-34]]

^<<v30-49-34,34>>^ Palavra do Senhor, que foi dirigida ao profeta Jeremias contra Elão, no princípio do reinado de Sedecias, rei de Judá, nestes termos:

[[v30-49-35]]

^<<v30-49-35,35>>^ Isto diz o Senhor dos exércitos: Vou quebrar o arco de Elão, a sua maior força.

[[v30-49-36]]

^<<v30-49-36,36>>^ Farei vir sobre Elão quatro ventos das quatro partes do céu, e espalharei os Elamitas por todos estes ventos: não haverá nação, aonde não cheguem os fugitivos de Elão.

[[v30-49-37]]

^<<v30-49-37,37>>^ Farei tremer Elão diante dos seus inimigos, na presença dos que procuram tirar-lhe a vida. Farei cair sobre eles a desgraça, o furor da minha cólera, diz o Senhor. Enviarei a espada após eles até os exterminar.

[[v30-49-38]]

^<<v30-49-38,38>>^ Estabelecerei o meu trono em Elão, e exterminarei de lá o rei e os chefes, diz o Senhor.

[[v30-49-39]]

^<<v30-49-39,39>>^ Nos últimos dias, porém, farei voltar os cativos de Elão, diz o Senhor.

'''

xref:030-jeremias/030-jeremias-048.adoc#v30-48-0[&#60; Capítulo Anterior] | <<v30-49-0,Topo>> | xref:030-jeremias/030-jeremias-050.adoc#v30-50-0[Próximo Capítulo &#62;]