include::./index.adoc[]

[[v30-4-0]]
=== Jeremias, 4
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Jeremias 4 aborda a temática do juízo vindouro de Deus sobre o povo de Judá, bem como a necessidade de arrependimento e retorno à fidelidade a Deus. A seguir, apresento cinco versículos relacionados com esses temas:
* Isaías 26:20: "Vai, meu povo, entra nos teus quartos, e fecha as tuas portas sobre ti; esconde-te só por um momento, até que passe a ira." Este verso traz uma mensagem semelhante à de Jeremias 4, alertando o povo de Deus a se refugiar diante da ira vindoura de Deus.
* Sofonias 2:3: "Buscai ao SENHOR, vós todos os mansos da terra, que tendes posto por obra o seu juízo; buscai a justiça, buscai a mansidão; pode ser que sejais escondidos no dia da ira do SENHOR." Esse versículo encoraja as pessoas a buscarem a Deus e praticarem a justiça e a mansidão, como forma de encontrarem refúgio durante o dia da ira de Deus.
* Ezequiel 18:30: "Portanto, eu vos julgarei, a cada um conforme os seus caminhos, ó casa de Israel, diz o Senhor JEOVÁ. Tornai-vos e convertei-vos de todas as vossas transgressões, e a iniquidade não vos servirá de tropeço." Esse verso reforça a ideia de que o juízo de Deus será baseado nas ações de cada pessoa, e encoraja as pessoas a se arrependerem e abandonarem seus pecados.
* Oséias 10:12: "Semeai para vós em justiça, colhei segundo a misericórdia; lavrai o campo de lavoura; porque é tempo de buscar ao SENHOR, até que venha e chova a justiça sobre vós." Esse verso enfatiza a importância de buscar a Deus e praticar a justiça, como forma de se preparar para o juízo vindouro.
* Isaías 55:6-7: "Buscai ao SENHOR enquanto se pode achar, invocai-o enquanto está perto. Deixe o ímpio o seu caminho, e o homem maligno os seus pensamentos; volte-se ao SENHOR, que se compadecerá dele; e para o nosso Deus, porque é abundante em perdoar." Este versículo encoraja as pessoas a buscarem a Deus enquanto há tempo, abandonando seus caminhos pecaminosos e voltando-se para o Senhor, que é abundante em perdoar.
****

[[v30-4-1]]

^<<v30-4-1,1>>^ Se tu, Israel, voltares, diz o Senhor, converter-te-ás a mim; se tirares de diante da minha face os teus horrores, não mais andarás errante.

[[v30-4-2]]

^<<v30-4-2,2>>^ Se jurares pela vida do Senhor, em verdade, com retidão e justiça, nele serão abençoados os povos e nele se gloriarão.

[[v30-4-3]]

^<<v30-4-3,3>>^ Porque isto diz o Senhor às gentes de Judá e de Jerusalém: Arroteai o vosso pousio; não semeeis sobre espinhos.

[[v30-4-4]]

^<<v30-4-4,4>>^ Circuncidai-vos para o Senhor, tirai os prepúcios de vossos corações, varões de Judá habitantes de Jerusalém, para que não suceda que, de repente, saia como fogo a minha indignação e abrase, e não haja quem a apague, por causa da maldade das vossas obras.

[[v30-4-5]]

^<<v30-4-5,5>>^ Anunciai em Judá, fazei ouvir em Jerusalém; publicai ao som de trombeta por (todo) o país; gritai em alta voz e dizei: Juntai-vos todos, entremos nas cidades fortificadas;

[[v30-4-6]]

^<<v30-4-6,6>>^ levantai o estandarte na direção de Sião, procurai abrigo, não estejais parados, porque eu farei vir do Aquilão uma desgraça; uma grande calamidade.

[[v30-4-7]]

^<<v30-4-7,7>>^ Saiu o leão do seu covil, pôs-se a caminho o destruidor das gentes; saiu do seu país, para reduzir a tua terra a um deserto; as tuas cidades serão destruídas, sem que nelas fique habitante algum. (ver nota)

[[v30-4-8]]

^<<v30-4-8,8>>^ Por isso cobri-vos de cilício, chorai e pranteai, porque não se apartou de nós o ardente furor do Senhor.

[[v30-4-9]]

^<<v30-4-9,9>>^ Acontecerá isto naquele dia, diz o Senhor: Desfalecerá o coração do rei, desfalecerá o coração dos chefes; pasmarão os sacerdotes, e os profetas ficarão estupefactos.

[[v30-4-10]]

^<<v30-4-10,10>>^ Dir-se-á (ao ouvir isto): Ai! Senhor Deus! Verdadeiramente enganaste este povo e Jerusalém, dizendo-lhes: Vós tereis paz quando agora chega a espada (do inimigo) até ao coração.

[[v30-4-11]]

^<<v30-4-11,11>>^ Naquele tempo dir-se-á a este povo e a Jerusalém: Um vento abrasador sopra das colinas do deserto sobre os caminhos que conduzem à filha do meu povo, não para aventar ou limpar (o grão, mas para queimar as plantas).

[[v30-4-12]]

^<<v30-4-12,12>>^ Daquele lado chega, às minhas ordens, um vento impetuoso; agora pronunciarei os meus juízos contra eles.

[[v30-4-13]]

^<<v30-4-13,13>>^ Eis que (o exército inimigo) vem como uma nuvem, como uma tempestade os seus carros, mais velozes que águias os seus cavalos. Ai de nós (dirão), porque somos destruídos.

[[v30-4-14]]

^<<v30-4-14,14>>^ Lava, ó Jerusalém, o teu coração de toda a maldade, para que sejas salva. Até quando permanecerão em ti pensamentos pecaminosos?

[[v30-4-15]]

^<<v30-4-15,15>>^ Já se escuta uma voz vinda de Dan, a dar o alarme, a notícia da calamidade vem do monte de Efraim.

[[v30-4-16]]

^<<v30-4-16,16>>^ Dizei às nações: Eis que se ouviu dizer em Jerusalém que vem gente de guerra de uma terra remota, que faz ouvir os seus gritos contra as cidades de Judá.

[[v30-4-17]]

^<<v30-4-17,17>>^ Estão (dia e noite) ao redor dela como guardas de campos, porque ela se revoltou contra mim, diz o Senhor.

[[v30-4-18]]

^<<v30-4-18,18>>^ Os teus caminhos e os teus pensamentos te trouxeram (ó Jerusalém) estas coisas; eis (o fruto da) tua malícia! Quão amargo é! Chega ao coração!

[[v30-4-19]]

^<<v30-4-19,19>>^ Minhas entranhas! Minhas entranhas! Sinto dor! O meu coração tumultua! Não me calarei, porque a minha alma ouviu a voz da trombeta, um alarido de batalha.

[[v30-4-20]]

^<<v30-4-20,20>>^ Anuncia-se desastre sobre desastre; foi assolada toda a terra. De improviso foram derrubadas as minhas tendas, os meus pavilhões abatidos.

[[v30-4-21]]

^<<v30-4-21,21>>^ Até quando verei o estandarte (inimigo) e ouvirei a voz da trombeta (inimiga)?

[[v30-4-22]]

^<<v30-4-22,22>>^ O meu povo é néscio, (diz o Senhor) não me conhece! Filhos insensatos são, sem inteligência: são sábios para fazer o mal, mas não sabem fazer o bem.

[[v30-4-23]]

^<<v30-4-23,23>>^ Olhei para a terra, e eis que estava informe e vazia; para os céus, e não havia neles luz,

[[v30-4-24]]

^<<v30-4-24,24>>^ Vi as montanhas, e elas tremiam, e todos os outeiros estremeciam.

[[v30-4-25]]

^<<v30-4-25,25>>^ Olhei e não havia homens, e todas as aves do céu tinham fugido.

[[v30-4-26]]

^<<v30-4-26,26>>^ Olhei, e (vi que) o vergel se tornara um deserto e todas as suas cidades haviam sido destruídas na presença do Senhor, ao sopro da sua cólera.

[[v30-4-27]]

^<<v30-4-27,27>>^ Eis, pois, o que diz o Senhor: Deserta ficará toda a terra (de Judá), porém não a destruirei de todo.

[[v30-4-28]]

^<<v30-4-28,28>>^ Chorará a terra e entristecer-se-ão os céus, lá em cima, porque decretei, resolvi, e não me arrependo, não desistirei.

[[v30-4-29]]

^<<v30-4-29,29>>^ À voz do cavaleiro e do que despede a seta, fugiu toda a cidade; correram a esconder-se nos bosques, subiram pelos rochedos; todas as cidades foram desamparadas, sem que ficasse nelas um só habitante.

[[v30-4-30]]

^<<v30-4-30,30>>^ E tu, desolada, que farás (ó Jerusalém)? Por mais que te vistas de púrpura, te adornes de enfeites de oiro, e alargues os teus olhos com pinturas, em vão te embelezarás: os teus amantes desprezam-te, querem tirar-te a vida.

[[v30-4-31]]

^<<v30-4-31,31>>^ Ouço uma voz como de mulher que está de parto, angústias como de puérpera: é a voz da filha de Sião, que grita, estendendo as suas mãos (e dizendo): Ai de mim, que desfalece a minha alma diante dos assassinos.

'''

xref:030-jeremias/030-jeremias-003.adoc#v30-3-0[&#60; Capítulo Anterior] | <<v30-4-0,Topo>> | xref:030-jeremias/030-jeremias-005.adoc#v30-5-0[Próximo Capítulo &#62;]