include::./index.adoc[]

[[v30-36-0]]
=== Jeremias, 36
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Jeremias 36 narra a época em que o Senhor ordenou a Jeremias que escrevesse todas as palavras que Ele havia falado contra Israel e Judá em um rolo e o lesse em voz alta ao povo no templo. O rolo foi lido ao rei Jeoaquim, mas ele não se arrependeu de seus caminhos. Os versículos relacionados aos temas abordados em Jeremias 36 são os seguintes:
* Salmos 119:11: "Guardo no coração as tuas palavras, para não pecar contra ti." O povo de Judá precisava guardar as palavras de Deus em seus corações para não pecarem contra Ele.
* Provérbios 29:1: "O homem que, depois de repreendido, endurece a cerviz será quebrantado de repente, sem que haja cura." O rei Jeoaquim foi repreendido pelas palavras do rolo, mas ele endureceu seu coração e foi quebrantado.
* Hebreus 4:12: "Porque a palavra de Deus é viva e eficaz, e mais cortante do que qualquer espada de dois gumes, e penetra até a divisão de alma e espírito, e de juntas e medulas, e é apta para discernir os pensamentos e intenções do coração." O rolo com as palavras de Deus era poderoso e capaz de discernir os pensamentos e intenções do coração do povo.
* João 8:32: "E conhecereis a verdade, e a verdade vos libertará." O povo precisava conhecer a verdade das palavras de Deus para serem libertados.
* 1 Pedro 1:25: "Mas a palavra do Senhor permanece para sempre. E esta é a palavra que entre vós foi evangelizada." As palavras de Deus são eternas e permanecem para sempre, e devem ser proclamadas a todos.
****

[[v30-36-1]]

^<<v30-36-1,1>>^ No quarto ano de Joaquim, filho de Josias, rei de Judá, foi dirigida a palavra do Senhor a Jeremias, a qual dizia:

[[v30-36-2]]

^<<v30-36-2,2>>^ Toma o rolo dum livro e escreve nele todas as palavras que te tenho dito contra Israel e Judá, e contra todas as nações, desde o dia em que te falei, no templo de Josias, até ao dia de hoje,

[[v30-36-3]]

^<<v30-36-3,3>>^ a ver se, ouvindo os da casa de Judá todos os males que estou resolvido a fazer-lhes, volta cada um do seu perverso caminho, de sorte que eu lhes possa perdoar as suas maldades e pecados.

[[v30-36-4]]

^<<v30-36-4,4>>^ Chamou, pois, Jeremias a Baruch, filho de Néria, e Baruch escreveu, ditando Jeremias, no rolo do livro todas as palavras que o Senhor lhe tinha dito.

[[v30-36-5]]

^<<v30-36-5,5>>^ Jeremias deu em seguida esta ordem a Baruch: Estou preso, não posso entrar na casa do Senhor.

[[v30-36-6]]

^<<v30-36-6,6>>^ Entra, pois, tu, e lê pelo livro em que escreveste, ditando eu, as palavras do Senhor, de modo que as ouça o povo da casa do Senhor no dia de jejum; além disto, também as lerás a todos os de Judá que vêm das suas cidades.

[[v30-36-7]]

^<<v30-36-7,7>>^ Pode ser que eles se prostrem, orando diante do Senhor, e se converta cada um do seu mau caminho, porque é grande o furor e a indignação que o Senhor manifestou contra este povo.

[[v30-36-8]]

^<<v30-36-8,8>>^ Baruch, filho de Néria, procedeu conforme tudo o que o profeta Jeremias lhe tinha mandado, lendo no livro as palavras do Senhor na casa do Senhor.

[[v30-36-9]]

^<<v30-36-9,9>>^ No quinto ano de Joaquim, filho de Josias, rei de Judá, no nono mês, publicaram um jejum diante do Senhor a todo o povo de Jerusalém e a toda a multidão que havia concorrido das cidades de Judá a Jerusalém.

[[v30-36-10]]

^<<v30-36-10,10>>^ Então Baruch leu no livro as palavras de Jeremias, na casa do Senhor, na câmara de Gamaxias, filho de Safan, secretário, no vestíbulo superior, à entrada da porta nova da casa do Senhor, ouvindo-o todo o povo.

[[v30-36-11]]

^<<v30-36-11,11>>^ Quando Miqueias, filho de Gamarias, filho de Safan, ouviu todas as palavras do Senhor, lidas pelo livro,

[[v30-36-12]]

^<<v30-36-12,12>>^ foi ao palácio do rei, à câmara do secretário, onde estavam sentados todos os grandes (da corte): Elisama, secretário, Dalaias, filho de Semeias, Elnatan, filho de Acobor Gamarias, filho de Safan, Sedecias, filho de Hananias, e todos os (outros) chefes.

[[v30-36-13]]

^<<v30-36-13,13>>^ Miqueias referiu-lhes todas as palavras que tinha ouvido, quando Baruch as lia pelo livro aos ouvidos do povo.

[[v30-36-14]]

^<<v30-36-14,14>>^ Com isto todos aqueles chefes enviaram a Baruch Judi, filho de Natanias, filho de Selemias, filho de Cusi, a dizer-lhe: Toma na tua mão o livro, pelo qual leste diante do povo, e vem cá. Tomou, pois, Baruch, filho de Néria, o livro na sua mão e foi ter com eles.

[[v30-36-15]]

^<<v30-36-15,15>>^ Disseram-lhe: Senta-te e lê essas coisas, para que as ouçamos. E Baruch leu, ouvindo-o eles.

[[v30-36-16]]

^<<v30-36-16,16>>^ Quando ouviram todas as palavras, voltaram-se espantados, cada um para o que tinha ao seu lado, e disseram a Baruch: É preciso que façamos saber ao rei todas estas coisas.

[[v30-36-17]]

^<<v30-36-17,17>>^ Depois interrogaram Baruch: Declara-nos como escreveste todos esses discursos da sua boca.

[[v30-36-18]]

^<<v30-36-18,18>>^ Baruch disse-lhes: Pela sua boca me ditava todas estas palavras, e eu as escrevia neste livro com tinta.

[[v30-36-19]]

^<<v30-36-19,19>>^ Então disseram os príncipes a Baruch: Vai e esconde-te com Jeremias, e que ninguém saiba onde estais.

[[v30-36-20]]

^<<v30-36-20,20>>^ Foram em seguida ter com o rei ao átrio do seu palácio, mas deixaram guardado o livro na câmara de Elisama, secretário, e participaram ao rei, em sua audiência, tudo o que tinha acontecido.

[[v30-36-21]]

^<<v30-36-21,21>>^ O rei mandou Judi buscar o livro. Judi, tomando-o da câmara de Elisama, secretário, leu-o diante do rei e de todos os grandes que estavam em volta do rei.

[[v30-36-22]]

^<<v30-36-22,22>>^ O rei estava sentado no seu aposento de inverno, no nono mês e diante dele estava posto um braseiro aceso.

[[v30-36-23]]

^<<v30-36-23,23>>^ A medida que Judi lia três ou quatro colunas, o rei cortava-as com o canivete do secretário e lançava-as ao fogo do braseiro, até que se queimou todo o livro no fogo do braseiro.

[[v30-36-24]]

^<<v30-36-24,24>>^ E não temeram nem rasgaram as suas vestes tanto o rei como todos os servos, que ouviram todas estas palavras (ou ameaças).

[[v30-36-25]]

^<<v30-36-25,25>>^ Todavia Elnatan, Dalaias e Gamarias tinham pedido ao rei que não queimasse o livro; mas ele não lhes deu ouvidos.

[[v30-36-26]]

^<<v30-36-26,26>>^ Depois o rei mandou a Jeremiei, príncipe, e a Saraias, filho de Azriel, a Selenias, filho de Abdeel, que prendessem Baruch, o secretário, e o profeta Jeremias, mas o Senhor escondeu-os.

[[v30-36-27]]

^<<v30-36-27,27>>^ Foi dirigida a palavra do Senhor ao profeta Jeremias, depois que o rei queimou o livro com as palavras que Baruch escrevera, recolhendo-as da boca de Jeremias, a qual dizia:

[[v30-36-28]]

^<<v30-36-28,28>>^ Toma de novo outro livro, e escreve nele todas as palavras que havia no primeiro livro, que Joaquim, rei de Judá, queimou.

[[v30-36-29]]

^<<v30-36-29,29>>^ E dirás a Joaquim, rei de Judá: Assim fala o Senhor: Tu queimaste aquele livro, dizendo: Por que escreveste nele e anunciaste que o rei de Babilônia virá, com certeza, e destruirá esta terra, fazendo que não fiquem nela homens nem animais?

[[v30-36-30]]

^<<v30-36-30,30>>^ Portanto isto diz o Senhor contra Joaquim, rei de Judá: Não sairá dele quem se sente sobre o trono de Davide e o seu cadáver será exposto ao ardor do dia e ao frio da noite.

[[v30-36-31]]

^<<v30-36-31,31>>^ Castigá-lo-ei a ele, à sua linhagem e aos seus servos pelas suas maldades, e farei cair sobre eles, sobre os habitantes de Jerusalém e sobre os varões de Judá todo o mal com que os tenho ameaçado, sem que eles me tenham ouvido.

[[v30-36-32]]

^<<v30-36-32,32>>^ Tomou, pois, Jeremias outro livro e deu-o a Baruch, filho de Néria, o secretário, o qual escreveu nele, ditando Jeremias, todas as palavras do livro que Joaquim, rei de Judá, tinha lançado no fogo. Ainda foram, além disso, acrescentadas muitas mais palavras do mesmo gênero.

'''

xref:030-jeremias/030-jeremias-035.adoc#v30-35-0[&#60; Capítulo Anterior] | <<v30-36-0,Topo>> | xref:030-jeremias/030-jeremias-037.adoc#v30-37-0[Próximo Capítulo &#62;]