include::./index.adoc[]

[[v30-20-0]]
=== Jeremias, 20
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Jeremias 20 relata o sofrimento e angústia do profeta Jeremias, que é perseguido e ridicularizado por falar a palavra do Senhor. Ele se sente enganado por Deus e desejaria não ter nascido. Abaixo estão cinco versículos relacionados com os temas abordados em Jeremias 20:
* Salmos 31:13: "Pois eu ouvi a maledicência de muitos; terror por todos os lados! Eles se ajuntavam e conspiravam contra mim, planejando tirar-me a vida." Assim como Jeremias, o salmista se encontra cercado por inimigos que tramam contra ele.
* Mateus 5:11-12: "Bem-aventurados sois vós, quando vos injuriarem e perseguiram e, mentindo, disserem todo mal contra vós, por minha causa. Alegrai-vos e exultai, porque é grande o vosso galardão nos céus, pois assim perseguiram aos profetas que foram antes de vós." Jesus fala sobre a perseguição que os seguidores dele sofrerão, lembrando que os profetas também foram perseguidos por falar a verdade.
* 2 Coríntios 4:8-9: "Em tudo somos atribulados, mas não angustiados; perplexos, mas não desesperados; perseguidos, mas não desamparados; abatidos, mas não destruídos." Paulo fala sobre as dificuldades enfrentadas pelos servos de Deus, mas também sobre a presença do Senhor em meio a elas.
* Romanos 8:38-39: "Porque estou certo de que, nem a morte, nem a vida, nem anjos, nem principados, nem coisas presentes, nem futuras, nem potestades, nem a altura, nem a profundidade, nem qualquer outra criatura nos poderá separar do amor de Deus, que está em Cristo Jesus nosso Senhor." Este versículo enfatiza a fidelidade de Deus para com seus servos, mesmo em meio às perseguições e sofrimentos.
* Tiago 5:10-11: "Meus irmãos, tomai por exemplo de aflição e paciência os profetas que falaram em nome do Senhor. Eis que temos por bem-aventurados os que sofreram. Ouvistes qual foi a paciência de Jó e vistes o fim que o Senhor lhe deu; porque o Senhor é muito misericordioso e piedoso." Tiago encoraja os crentes a seguir o exemplo dos profetas e a manter a paciência em meio às dificuldades, lembrando que Deus é misericordioso e justo.
****

[[v30-20-1]]

^<<v30-20-1,1>>^ Ora Fassur, sacerdote, filho de Emer, que era prefeito da casa do Senhor, ouviu Jeremias profetizar estas coisas.

[[v30-20-2]]

^<<v30-20-2,2>>^ Mandou vergastar o profeta Jeremias e pô-lo no cepo, que estava na porta superior de Benjamim, (porta) que pertence à casa do Senhor.

[[v30-20-3]]

^<<v30-20-3,3>>^ Ao outro dia, Fassur tirou Jeremias do cepo. Jeremias disse-lhe: O Senhor não mais te chama Fassur, mas Magor-Missabib.

[[v30-20-4]]

^<<v30-20-4,4>>^ Porque isto diz o Senhor: Vou encher-te de terror, a ti e a todos os teus amigos; cairão à espada de seus inimigos, e os teus olhos o verão. Porei também todo Judá na mão do rei de Babilônia, que transportará (os habitantes) a Babilônia, e os matará à espada.

[[v30-20-5]]

^<<v30-20-5,5>>^ Todas as riquezas desta cidade, todo o produto do seu trabalho, tudo o que tem de precioso, todos os tesouros dos reis de Judá, tudo porei nas mãos dos seus inimigos, os quais os saquearão, tomarão e levarão a Babilônia.

[[v30-20-6]]

^<<v30-20-6,6>>^ E tu, Fassur, com todos os moradores da tua casa, irás para o cativeiro; irás a Babilônia, ali morrerás e ali serás enterrado, tu e todos os teus amigos, a quem profetizaste a mentira.

[[v30-20-7]]

^<<v30-20-7,7>>^ Tu me seduziste, Senhor, e eu fui seduzido; foste mais forte do que eu e pudeste mais; tornei-me um objecto de escárnio todo o dia, todos me insultam.

[[v30-20-8]]

^<<v30-20-8,8>>^ Porque todas as vezes que falo, devo gritar, anunciar violência e ruína; e a palavra do Senhor tornou-se-me em opróbrio e em ludíbrio, todos os dias.

[[v30-20-9]]

^<<v30-20-9,9>>^ Eu dizia (comigo): Não me lembrarei mais dele, não falarei mais em seu nome; porém ardia no meu coração como que um fogo abrasador, encerrado nos meus ossos; esforçava-me por o conter, mas não podia.

[[v30-20-10]]

^<<v30-20-10,10>>^ Ouvia os maus intentos da plebe: Terror de todos os lados! Denunciai, vamos denunciá-lo! Todos os homens que viviam em paz comigo, espiam os meus passos: Vejamos se se deixa apanhar; então prevaleceremos contra ele, vingar-nos-emos dele.

[[v30-20-11]]

^<<v30-20-11,11>>^ Mas o Senhor está comigo como um poderoso herói; por isso os que me perseguem, cairão, não prevalecerão; serão cobertos de vergonha, porque não foram bem sucedidos, dum opróbrio eterno, que nunca se apagará da memória.

[[v30-20-12]]

^<<v30-20-12,12>>^ Tu, Senhor dos exércitos que provas o justo, que penetras os rins e o coração, (espero em ti que) verei a tua justa vingança contra eles, pois confiei-te a minha causa.

[[v30-20-13]]

^<<v30-20-13,13>>^ Cantai ao Senhor, louvai o Senhor, porque livrou a alma do pobre da mão dos malvados.

[[v30-20-14]]

^<<v30-20-14,14>>^ Maldito seja o dia em que nasci; não seja abençoado o dia em que minha mãe me deu à luz.

[[v30-20-15]]

^<<v30-20-15,15>>^ Maldito seja o homem que levou esta nova a meu pai: Nasceu-te um filho varão - e que o encheu de alegria.

[[v30-20-16]]

^<<v30-20-16,16>>^ Seja este homem como são as cidades que o Senhor destruiu sem compaixão; ouça gritos de manhã, e clamores de guerra no meio-dia.

[[v30-20-17]]

^<<v30-20-17,17>>^ Por que me não matou antes de sair do ventre materno, de sorte que minha mãe fosse o meu sepulcro, e nunca houvesse saído do seu ventre?

[[v30-20-18]]

^<<v30-20-18,18>>^ Por que saí eu do seio materno, para ver o trabalho e a dor, e consumirem-se os meus dias na confusão?

'''

xref:030-jeremias/030-jeremias-019.adoc#v30-19-0[&#60; Capítulo Anterior] | <<v30-20-0,Topo>> | xref:030-jeremias/030-jeremias-021.adoc#v30-21-0[Próximo Capítulo &#62;]