include::./index.adoc[]

[[v30-50-0]]
=== Jeremias, 50
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Jeremias 50 fala sobre a queda de Babilônia e a libertação do povo de Israel do cativeiro. A seguir, são apresentados cinco versículos de outros livros da Bíblia que se relacionam com os temas abordados nesse capítulo:
* Isaías 48:20: "Saí de Babilônia, fugi dos caldeus, com voz de júbilo anunciai, proclamai isto, divulgue-se até ao fim da terra; dizei: O Senhor remiu a seu servo Jacó!" Este versículo fala sobre a libertação do povo de Israel da Babilônia e a alegria que isso traz.
* Isaías 52:11: "Retirai-vos, retirai-vos, saí daí, não toqueis coisa imunda; saí do meio dela, purificai-vos, vós que levais os utensílios do Senhor." Esse versículo também fala sobre a saída do povo de Israel da Babilônia e a necessidade de se purificarem para estar em comunhão com Deus.
* Jeremias 51:6: "Fugi do meio de Babilônia, e cada um salve a sua vida; não sejais exterminados na sua injustiça; porque este é o tempo da vingança do Senhor; ele lhe dará o pago." Aqui, o profeta Jeremias exorta o povo de Israel a fugir de Babilônia e se salvar da destruição iminente.
* Jeremias 51:20-23: "Tu me és um martelo e armas de guerra; contigo despedaçarei nações, e contigo destruirei reinos; contigo despedaçarei o cavalo e seu cavaleiro; contigo despedaçarei o carro e seu condutor; contigo despedaçarei o homem e a mulher; contigo despedaçarei o velho e o moço; contigo despedaçarei o rapaz e a menina." Esses versículos falam sobre a utilização de Babilônia como um instrumento de destruição nas mãos de Deus.
* Apocalipse 18:2: "E clamou fortemente com grande voz, dizendo: Caiu, caiu a grande Babilônia, e se tornou morada de demônios, e guarida de todo espírito imundo, e guarida de toda ave imunda e aborrecível." Esse versículo fala sobre a queda final de Babilônia, que se torna um lugar de habitação de demônios e espíritos imundos.
****

[[v30-50-1]]

^<<v30-50-1,1>>^ Palavra que o Senhor pronunciou acerca de Babilônia e da terra dos Caldeus por intermédio do profeta Jeremias:

[[v30-50-2]]

^<<v30-50-2,2>>^ Anunciai entre as nações, fazei-lho ouvir; levantai a bandeira, publicai-o, não lho encobrais, dizei; Babilônia foi tomada, Bel ficou confundido, Marduk foi destroçado; confundidos foram os seus ídolos, abatidos os seus falsos deuses.

[[v30-50-3]]

^<<v30-50-3,3>>^ Porque avança contra ela um povo do norte, que reduzirá o seu país a um deserto: não haverá quem o povoe: desde o homem até ao animal, (todos) fugirão, desaparecerão.

[[v30-50-4]]

^<<v30-50-4,4>>^ Naqueles dias e naquele tempo, diz o Senhor, virão os filhos de Israel e, juntamente com eles, os filhos de Judá; caminharão chorando, à procura do Senhor seu Deus.

[[v30-50-5]]

^<<v30-50-5,5>>^ Perguntarão qual é o caminho que leva a Sião, para onde voltarão o seu rosto. Vinde, liguemo-nos ao Senhor com uma eterna aliança, a qual jamais se apagará da memória.

[[v30-50-6]]

^<<v30-50-6,6>>^ O meu povo tornou-se um rebanho de ovelhas perdidas; os seus pastores enganaram-nas e fizeram-nas andar desgarradas pelos montes; andavam de montanha em colina, esquecidas do seu aprisco.

[[v30-50-7]]

^<<v30-50-7,7>>^ Todos os que as encontravam devoravam-nas; os seus inimigos diziam: Não somos culpados, porque elas pecaram contra o Senhor, morada de justiça, contra o Senhor, esperança de seus pais.

[[v30-50-8]]

^<<v30-50-8,8>>^ Fugi (ó Judeus exilados) do meio de Babilônia, saí da terra dos Caldeus; sede como os cabritos que vão adiante do rebanho.

[[v30-50-9]]

^<<v30-50-9,9>>^ Porque vou suscitar e trazer contra Babilônia um conjunto de grandes nações do norte. Lançarão ataque contra ela e tomá-la-ão; as suas setas, como as dum hábil guerreiro, não serão disparadas em vão.

[[v30-50-10]]

^<<v30-50-10,10>>^ A Caldeia servirá de presa; todos os que a saquearem, se fartarão, diz o Senhor.

[[v30-50-11]]

^<<v30-50-11,11>>^ Sim, alegrai-vos, exultai saqueadores da minha herança; sim, retouçai como bezerros sobre a erva, relinchai como garanhões.

[[v30-50-12]]

^<<v30-50-12,12>>^ (Babilônia) vossa mãe, está em extremo confundida, coberta de vergonha aquela que vos gerou. Agora é a última entre as nações, um deserto, uma solidão, uma aridez.

[[v30-50-13]]

^<<v30-50-13,13>>^ Pela ira do Senhor ficará despovoada, será toda convertida numa solidão; todo o que passar por Babilónia, se espantará e assobiará (de escárnio) ao ver todas as suas ruínas.

[[v30-50-14]]

^<<v30-50-14,14>>^ Atacai Babilônia de todas as partes, todos os que sabeis manejar o arco; combatei-a, não poupeis as flechas, porque ela pecou contra o Senhor.

[[v30-50-15]]

^<<v30-50-15,15>>^ Lançai, de todos os lados, um grito de guerra contra ela; (já) estende as mãos, caem as suas torres, são destruídos os seus muros. É a vingança do Senhor; tomai vingança dela, fazei-lhe o mesmo que ela fez.

[[v30-50-16]]

^<<v30-50-16,16>>^ Exterminai de Babilônia o que semeia e o que tem a fouce no tempo da ceifa; ante o fio da espada destruidora cada um volte para o seu povo, cada um fuja para a sua terra.

[[v30-50-17]]

^<<v30-50-17,17>>^ Israel é uma ovelha desgarrada, que os leões perseguiam; o rei de Assur foi o primeiro a devorá-la; depois Nabucodonosor, rei de Babilônia, quebrou-lhe os ossos.

[[v30-50-18]]

^<<v30-50-18,18>>^ Por cuja causa, isto diz o Senhor dos exércitos, o Deus de Israel: Vou castigar o rei de Babilônia e a sua terra, assim como castiguei o rei de Assur.

[[v30-50-19]]

^<<v30-50-19,19>>^ E farei voltar Israel para o seu logradouro: pastará outra vez, nas pastagens do Carmelo e de Basan, e se fartará nos montes de Efraim e de Galaad.

[[v30-50-20]]

^<<v30-50-20,20>>^ Naqueles dias e naquele tempo, diz o Senhor, buscar-se-á a iniquidade (ou idolatria) de Israel, e não se achará, o pecado de Judá, e não se há-de encontrar, porque eu perdoarei aos que tiver reservado.

[[v30-50-21]]

^<<v30-50-21,21>>^ Sobe contra o país de Merataim e contra os habitantes de Pecod; destrói e mata, diz o Senhor, faze conforme tudo o que te mandei.

[[v30-50-22]]

^<<v30-50-22,22>>^ Ouviu-se uma voz de guerra na terra, e um grande destroço.

[[v30-50-23]]

^<<v30-50-23,23>>^ Como se quebrou e se fez em pedaços (Babilônia que era) o martelo de toda a terra? Como se transformou num objecto de horror esta Babilônia entre as nações?

[[v30-50-24]]

^<<v30-50-24,24>>^ Eu te enredei, ó Babilônia, e tu foste tomada sem saberes: foste surpreendida e apanhada, porque provocaste o Senhor.

[[v30-50-25]]

^<<v30-50-25,25>>^ O Senhor abriu o seu arsenal e dele tirou as armas da sua ira, porque o Senhor Deus dos exércitos tem uma obra (a cumprir) contra o país dos Caldeus.

[[v30-50-26]]

^<<v30-50-26,26>>^ Vinde contra ela dos últimos confins, abri os seus celeiros, amontoai os despojos como feixes, e destruí sem que fique resto algum.

[[v30-50-27]]

^<<v30-50-27,27>>^ Exterminai todos os seus touros: sejam conduzidos ao matadouro; ai deles, porque chegou o seu dia, o tempo do seu castigo!

[[v30-50-28]]

^<<v30-50-28,28>>^ Ouviu-se uma voz dos fugitivos e daqueles que escaparam da terra de Babilônia anunciando em Sião a vingança do Senhor nosso Deus, a vingança do seu templo.

[[v30-50-29]]

^<<v30-50-29,29>>^ Convocai todos os que estendem o arco, que venham contra Babilônia! Cercai-a de todas as partes: que não escape nenhum. Dai-lhe o pago das suas obras: segundo todas as coisas que fez, assim lhe fazei a ela, porque se levantou contra o Senhor, contra o santo de Israel.

[[v30-50-30]]

^<<v30-50-30,30>>^ Por isso os seus jovens cairão nas suas praças, e todos os seus homens de guerra perecerão naquele dia, diz o Senhor.

[[v30-50-31]]

^<<v30-50-31,31>>^ Aqui estou contra ti, ó soberba, diz o Senhor Deus dos exércitos; porque é chegado o teu dia, o tempo do teu castigo.

[[v30-50-32]]

^<<v30-50-32,32>>^ Cambaleará a soberba, dará consigo em terra, e não haverá quem a levante; e lançarei fogo às suas cidades, o qual devorará tudo o que estiver nos seus arrabaldes.

[[v30-50-33]]

^<<v30-50-33,33>>^ Isto diz o Senhor dos exércitos: Os filhos de Israel e juntamente os filhos de Judá sofrem opressão; todos os que os cativaram, os retêm, não os querem deixar ir.

[[v30-50-34]]

^<<v30-50-34,34>>^ Porém o vingador deles é forte: Senhor dos exércitos é o seu nome. Defenderá em juízo a sua causa, para dar repouso à terra e fazer tremer os moradores de Babilônia.

[[v30-50-35]]

^<<v30-50-35,35>>^ Espada contra os Caldeus, diz o Senhor, e contra os moradores de Babilônia, contra os seus chefes e sábios!

[[v30-50-36]]

^<<v30-50-36,36>>^ Espada contra os seus adivinhos, que ficarão insensatos! Espada contra os seus valentes que temerão!

[[v30-50-37]]

^<<v30-50-37,37>>^ Espada contra os seus cavalos, contra os seus carros, e contra toda a massa plebeia que está no meio dela: serão (tímidos) como mulheres! Espada contra os seus tesouros, que serão saqueados!

[[v30-50-38]]

^<<v30-50-38,38>>^ Espada contra as suas águas, que secarão, porque é um país de ídolos, e que se gloria dos seus feitiços.

[[v30-50-39]]

^<<v30-50-39,39>>^ Por isso os dragões virão morar nela com os chacais, nela habitarão os avestruzes. Não será jamais povoada, nunca mais aí se residirá.

[[v30-50-40]]

^<<v30-50-40,40>>^ Como quando o Senhor destruiu Sodoma e Gomorra e as outras cidades suas vizinhas, diz o Senhor, também não morará ali pessoa alguma, nenhum filho de homem ali fará a sua morada.

[[v30-50-41]]

^<<v30-50-41,41>>^ Eis que vem um povo do norte; uma grande nação e muitos reis se levantam dos confins da terra.

[[v30-50-42]]

^<<v30-50-42,42>>^ Armam-se de arco e de setas; são cruéis e desapiedados; o seu ruído é como o bramido do mar; vêm montados em cavalos, apetrechados para combater contra ti, filha de Babilônia.

[[v30-50-43]]

^<<v30-50-43,43>>^ Ouviu o rei de Babilônia esta notícia, e desfaleceram as suas mãos; ficou possuído de angústia e de dor, como uma mulher que está com dores de parto.

[[v30-50-44]]

^<<v30-50-44,44>>^ (O inimigo) sobe, como um leão, das espessuras do Jordão até às pastagens perpétuas (de Babilônia); subitamente os farei fugir, e aí estabelecerei aquele que escolhi. Pois quem há semelhante a mim? Quem me poderá pedir contas? Qual o pastor (o capitão) que se atreverá a resistir à minha face?

[[v30-50-45]]

^<<v30-50-45,45>>^ Portanto ouvi a resolução que o Senhor formou contra Babilônia, os projetos que concebeu contra a terra dos Caldeus: Serão arrastados como os mais pequenos do rebanho, a sua pastagem será devastada.

[[v30-50-46]]

^<<v30-50-46,46>>^ À voz da tomada de Babilônia, a terra foi abalada, e gritos foram ouvidos entre as nações.

'''

xref:030-jeremias/030-jeremias-049.adoc#v30-49-0[&#60; Capítulo Anterior] | <<v30-50-0,Topo>> | xref:030-jeremias/030-jeremias-051.adoc#v30-51-0[Próximo Capítulo &#62;]