include::./index.adoc[]

[[v30-48-0]]
=== Jeremias, 48
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Jeremias 48 descreve a destruição iminente de Moabe pelas mãos de Nabucodonosor, rei da Babilônia, por causa da sua arrogância e impiedade contra Deus. Os versículos selecionados abaixo descrevem o julgamento divino sobre Moabe, a lamentação de seu povo e a soberania de Deus sobre todas as nações.
* Isaías 16:6 - "Ouvimos falar da soberba de Moabe, da sua arrogância e orgulho, da sua insolência e das suas bravatas vazias." Este verso se refere à atitude arrogante de Moabe, que levou à sua condenação e punição.
* Salmos 60:8 - "Moabe é a minha bacia de lavar os pés; sobre Edom eu lanço a minha sandália; sobre a Filístia eu dou o meu brado de vitória". Este verso mostra como Deus controla as nações e as usa para executar a sua vontade.
* Jeremias 48:31 - "Por isso chorarei por Moabe, sim, gritarei por todo o Moabe; pelos homens de Quir-Heres suspirarei." Este verso retrata a lamentação e tristeza dos habitantes de Moabe diante da iminente destruição de sua terra.
* Jeremias 48:42 - "Moabe será destruído como nação porque zombou do Senhor." Este verso reitera a razão para a punição de Moabe e destaca a importância da obediência a Deus.
* Isaías 25:10 - "Pois a mão do Senhor repousará sobre este monte, e Moabe será pisado no lugar onde está, como a palha é pisada na água da esterqueira." Este verso descreve a destruição total de Moabe e a vitória final de Deus sobre seus inimigos.
****

[[v30-48-1]]

^<<v30-48-1,1>>^ Isto diz contra Moab o Senhor dos exércitos, o Deus de Israel: Ai de Nebo, porque foi devastada! Cariataim foi tomada e coberta de vergonha: a (cidade) forte confundiu-se e abateu-se.

[[v30-48-2]]

^<<v30-48-2,2>>^ Acabou-se a glória de Moab! Em Hesebon maquina-se a sua perda: Vinde, e exterminemo-la dentre as nações. E tu, Madmen, serás reduzida ao silêncio: a espada te irá seguindo.

[[v30-48-3]]

^<<v30-48-3,3>>^ Uma voz de tumulto se levantou de Oronaim: Estrago e grande ruína,

[[v30-48-4]]

^<<v30-48-4,4>>^ Moab foi abatida; ouvem-se gritos até Segor.

[[v30-48-5]]

^<<v30-48-5,5>>^ Pela encosta de Luit há lágrimas, sobe-se chorando; pela descida de Oronaim ouvem-se gritos de angústia.

[[v30-48-6]]

^<<v30-48-6,6>>^ Fugi, salvai as vossas vidas! Sede como cardo no deserto!

[[v30-48-7]]

^<<v30-48-7,7>>^ Porque puseste (ó Moab) a confiança nas tuas fortificações e nos teus tesouros, também tu serás tomada; Camos irá para o cativeiro, com os seus sacerdotes e os seus príncipes, juntamente.

[[v30-48-8]]

^<<v30-48-8,8>>^ O devastador (Nabucodonosor) virá a todas as cidades (de Moab), e nenhuma escapará; serão assolados os vales, serão taladas as campinas, porque o Senhor disse.

[[v30-48-9]]

^<<v30-48-9,9>>^ Dai asas a Moab, para levantar voo; as suas cidades ficarão desertas e despovoadas.

[[v30-48-10]]

^<<v30-48-10,10>>^ Maldito o que faz a obra do Senhor frouxamente! Maldito o que impede a sua espada de derramar sangue!

[[v30-48-11]]

^<<v30-48-11,11>>^ Moab esteve em repouso desde a sua mocidade, ficou tranquilo (como vinho) sobre as suas fezes; não foi trasfegado duma vasilha para outra, não foi para o cativeiro; por isso permaneceu o seu sabor nele, e o seu cheiro não se mudou.

[[v30-48-12]]

^<<v30-48-12,12>>^ Mas eis que chega o tempo, diz o Senhor, em que eu lhe enviarei trasfegadores que o trasfegarão, que esvaziarão os recipientes e quebrarão as vasilhas.

[[v30-48-13]]

^<<v30-48-13,13>>^ E Moab se envergonhará, por causa de Camos, como se envergonhou a casa de Israel por causa (dos ídolos) de Betei, em que tinha a sua confiança.

[[v30-48-14]]

^<<v30-48-14,14>>^ Como dizeis: Somos valentes, homens fortes para pelejar?

[[v30-48-15]]

^<<v30-48-15,15>>^ Destruído ficou Moab, com as suas cidades; os seus jovens escolhidos vão para o matadouro, diz o rei, cujo nome é Senhor dos exércitos.

[[v30-48-16]]

^<<v30-48-16,16>>^ Está iminente a ruína de Moab; o seu mal vem correndo com grande velocidade.

[[v30-48-17]]

^<<v30-48-17,17>>^ Consolai-o todos os que estais em volta dele; todos os que sabeis o seu nome, dizei: Como se fez em pedaços um cetro tão forte (de Moab), um cetro tão glorioso?

[[v30-48-18]]

^<<v30-48-18,18>>^ Desce da tua glória, e senta-te sobre a terra árida, ó filha moradora de Dibon, porque o devastador de Moab subiu contra ti, destruiu as tuas fortificações.

[[v30-48-19]]

^<<v30-48-19,19>>^ Pára no caminho e olha, ó habitante de Aroer; pergunta ao que foge e ao que escapou: Que aconteceu?

[[v30-48-20]]

^<<v30-48-20,20>>^ Confundido está Moab porque ficou vencido. Gemei e gritai, publicai em Arnon que Moab foi destruído.

[[v30-48-21]]

^<<v30-48-21,21>>^ O castigo (de Deus) veio sobre a terra da planície, sobre Helon, sobre Jasa, sobre Mefaat,

[[v30-48-22]]

^<<v30-48-22,22>>^ sobre Dibon, sobre Nebo, sobre Beth-Deblataim,

[[v30-48-23]]

^<<v30-48-23,23>>^ sobre Cariataim, sobre Betgamul, sobre Betmaon,

[[v30-48-24]]

^<<v30-48-24,24>>^ sobre Cariot, sobre Bosra e sobre todas as cidades da terra de Moab, as que estão longe e as que estão perto.

[[v30-48-25]]

^<<v30-48-25,25>>^ Abatido foi o poder de Moab, o seu braço foi quebrantado, diz o Senhor.

[[v30-48-26]]

^<<v30-48-26,26>>^ Embriagai-o (com o cálice da ira do Senhor), porque se levantou contra o Senhor: Moab revolver-se-á sobre o que vomitou, será também um objecto de escárnio.

[[v30-48-27]]

^<<v30-48-27,27>>^ Tu (ó Moab) não escarneceste de Israel? Como se tivesse sido surpreendido entre ladrões não abanavas sempre (com ar de mofa) a cabeça, ao falar dele?

[[v30-48-28]]

^<<v30-48-28,28>>^ Abandonai as cidades, moradores de Moab, vivei nos penhascos, sede como a pomba que faz o ninho sobre despenhadeiros.

[[v30-48-29]]

^<<v30-48-29,29>>^ Ouvimos falar da soberba de Moab que é soberbo em extremo, da sua sobranceria, da sua arrogância, do seu orgulho, da altivez do seu coração.

[[v30-48-30]]

^<<v30-48-30,30>>^ Eu conheço, diz o Senhor, as suas vãs palavras e as suas obras fúteis.

[[v30-48-31]]

^<<v30-48-31,31>>^ Portanto gemo sobre Moab, solto gritos por todo o Moab, gemo pelas gentes de Quir-Heres.

[[v30-48-32]]

^<<v30-48-32,32>>^ Mais do que chorei por Jazer, chorarei por ti, vinha de Sabama. Os teus sarmentos passaram o mar, chegaram até ao mar de Jaser; o roubador lançou-se sobre as tuas searas e sobre a tua vindima.

[[v30-48-33]]

^<<v30-48-33,33>>^ A alegria e o regozijo desapareceram dos vergéis da terra de Moab; fiz desaparecer o vinho das cubas; o pisador da uva não pisa mais, e não mais ressoam os gritos de alegria.

[[v30-48-34]]

^<<v30-48-34,34>>^ Os clamores de Hesebon chegam até Eleale, a sua voz chega até Jasa, desde Segor até Oronaim, Eglath-Selisia; as próprias águas de Nimrim convertem-se num deserto.

[[v30-48-35]]

^<<v30-48-35,35>>^ Tirarei de Moab, diz o Senhor, o que faz oferendas nos altos e oferece incenso aos seus deuses.

[[v30-48-36]]

^<<v30-48-36,36>>^ Por (tudo) isto o meu coração por causa de Moab geme como flauta, o meu coração geme como uma flauta sobre os habitantes de Quir-Heres: o tesouro acumulado está perdido.

[[v30-48-37]]

^<<v30-48-37,37>>^ Todas as cabeças estão rapadas, todas as barbas cortadas (em sinal de tristeza); em todas as mãos há incisões, sobre todos os rins há sacos.

[[v30-48-38]]

^<<v30-48-38,38>>^ Sobre todas as casas de Moab e nas suas praças sòmente se ouvem lamentos, porquanto fiz Moab em pedaços, como a vaso inútil, diz o Senhor.

[[v30-48-39]]

^<<v30-48-39,39>>^ Como foi despedaçado! Gemei! Como voltou Moab as costas, vergonhosamente! Moab tornou-se objecto de ludíbrio e de espanto para todos que o cercam.

[[v30-48-40]]

^<<v30-48-40,40>>^ Isto diz o Senhor: Eis que (o Caldeu) voa como águia e estende as suas asas sobre Moab.

[[v30-48-41]]

^<<v30-48-41,41>>^ As cidades são tomadas, as fortificações arrebatadas. O coração dos guerreiros de Moab será naquele dia como o coração da mulher que está com dores de parto.

[[v30-48-42]]

^<<v30-48-42,42>>^ Moab deixa de ser uma nação, porque se ensoberbeceu contra o Senhor.

[[v30-48-43]]

^<<v30-48-43,43>>^ O pavor, o fosso e o laço estão sobre ti, ó habitante de Moab, diz o Senhor.

[[v30-48-44]]

^<<v30-48-44,44>>^ O que fugir do pavor, cairá no fosso; o que sair do fosso, será apanhado no laço. Com efeito, vou fazer vir sobre Moab o ano do seu castigo, diz o Senhor.

[[v30-48-45]]

^<<v30-48-45,45>>^ À sombra de Hesebon fizeram alto, extenuados, os fugitivos, mas um fogo saiu de Hesebon, uma chama do meio de Sehon, a qual devora as têmporas de Moab, o crânio dos filhos do tumulto.

[[v30-48-46]]

^<<v30-48-46,46>>^ Ai de ti Moab! Pereceste, povo de Camos! Os teus filhos foram presos, as tuas filhas levadas para o cativeiro.

[[v30-48-47]]

^<<v30-48-47,47>>^ Mas farei voltar os cativos de Moab no fim dos dias, diz o Senhor. Até aqui o julgamento (do Senhor) contra Moab.

'''

xref:030-jeremias/030-jeremias-047.adoc#v30-47-0[&#60; Capítulo Anterior] | <<v30-48-0,Topo>> | xref:030-jeremias/030-jeremias-049.adoc#v30-49-0[Próximo Capítulo &#62;]