include::./index.adoc[]

[[v14-16-0]]
=== II Crônicas, 16
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* 2 Crônicas 16 descreve a vida do rei Asa de Judá, incluindo seu relacionamento com Deus e suas escolhas políticas. Após um período de paz e prosperidade, Asa entra em uma aliança com o rei da Síria, em vez de confiar em Deus, e se torna doente. Abaixo estão cinco versículos relacionados com os temas abordados em 2 Crônicas 16, em ordem de similaridade:
* Salmos 20:7: "Alguns confiam em carros e outros em cavalos, mas nós confiamos no nome do Senhor nosso Deus." Este versículo fala sobre a importância da confiança em Deus, em vez de confiar em coisas materiais, como carros e cavalos, para nossa segurança e proteção.
* Provérbios 3:5-6: "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas." Este versículo enfatiza a importância de confiar em Deus em vez de em nossa própria compreensão limitada e pede que reconheçamos Deus em todas as áreas da nossa vida.
* Isaías 31:1: "Ai dos que descem ao Egito em busca de ajuda, que confiam em cavalos e confiam em carros porque são muitos, e em cavaleiros porque são poderosos, mas não olham para o Santo de Israel e não buscam o Senhor!" Este versículo adverte contra confiar em alianças políticas e militares em vez de confiar em Deus.
* Jeremias 17:5-6: "Assim diz o Senhor: Maldito é o homem que confia no homem, que faz da carne o seu braço e cujo coração se afasta do Senhor. Ele será como um arbusto no deserto; ele não verá nenhum bem quando vier, mas habitará nas terras secas do deserto, em uma terra salgada e sem habitantes." Este versículo destaca as consequências negativas de confiar no homem e se afastar de Deus, comparando-o a um arbusto no deserto.
* João 14:27: "Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize." Este versículo enfatiza a paz que Deus oferece e nos lembra que a paz do mundo é temporária e superficial, em comparação com a paz que vem de Deus.
****

[[v14-16-1]]

^<<v14-16-1,1>>^ No ano trigésimo sexto do seu reinado, Baasa, rei de Israel, foi contra Judá, e circundou Rama com um muro, para que nenhum do reino de Asa pudesse com segurança sair ou entrar.

[[v14-16-2]]

^<<v14-16-2,2>>^ Então Asa tirou o ouro e a prata dos tesouros da casa do Senhor e dos tesouros do rei, e enviou-os a Benadad, rei da Síria, que habitava em Damasco, dizendo:

[[v14-16-3]]

^<<v14-16-3,3>>^ Há uma aliança entre mim e ti: também meu pai e o teu conservam concórdia entre si; por esta razão te mando prata e ouro, para que, rota a aliança que tens com Baasa, rei de Israel, o obrigues a retirar-se do meu país.

[[v14-16-4]]

^<<v14-16-4,4>>^ Sabido isto, Benadad mandou os generais dos seus exércitos contra as cidades de Israel, os quais destruíram Alon, Dan, Abelmain e todas as cidades muradas de Neftali.

[[v14-16-5]]

^<<v14-16-5,5>>^ Baasa, tendo ouvido isto, cessou de fortificar Rama e não prosseguiu na sua obra.

[[v14-16-6]]

^<<v14-16-6,6>>^ O rei Asa tomou consigo toda a gente de Judá, mandou tirar de Rama as pedras e a madeira, que Baasa tinha preparado para a fortificar, e com elas reparou Gabaa e Masfa.

[[v14-16-7]]

^<<v14-16-7,7>>^ Naquele tempo o profeta Hanani foi ter com Asa, rei de Judá, e disse-lhe: Porque confiaste no rei da Síria, e não no Senhor teu Deus, por isso o exército do rei da Síria escapou das tuas mãos.

[[v14-16-8]]

^<<v14-16-8,8>>^ Porventura não constituíam os Etíopes e os Líbios um grande exército, com numerosos carros e cavaleiros? Entretanto, quando tu confiaste no Senhor, ele tos entregou nas mãos.

[[v14-16-9]]

^<<v14-16-9,9>>^ Os olhos do Senhor contemplam toda a terra e inspiram força aos que confiam nele com um coração perfeito. Tu procedeste loucamente; por isso desde agora se levantarão guerras contra ti.

[[v14-16-10]]

^<<v14-16-10,10>>^ Asa, irado contra o vidente, mandou-o encarcerar, porque se tinha irritado muito por isto (que o profeta lhe tinha dito); nesta ocasião Asa oprimiu também alguns do povo (que eram partidários do profeta).

[[v14-16-11]]

^<<v14-16-11,11>>^ Quanto às ações de Asa, desde as primeiras até às últimas, estão escritas no livro dos reis de Judá e de Israel.

[[v14-16-12]]

^<<v14-16-12,12>>^ Mas confiou antes... Asa não é censurado por ter recorrido aos médicos, mas por ter confiado mais neles do que em Deus.

[[v14-16-13]]

^<<v14-16-13,13>>^ No ano trinta e nove do seu reinado. Asa adoeceu duma veementíssima dor nos pés; todavia, mesmo na sua enfermidade, não recorreu ao Senhor, mas confiou antes nos médicos.

[[v14-16-14]]

^<<v14-16-14,14>>^ Adormeceu com seus pais; morreu no ano quarenta e um do seu reinado.

[[v14-16-15]]

^<<v14-16-15,15>>^ Sepultaram-no no sepulcro, que ele tinha mandado fazer para si na cidade de Davide, puseram-no sobre o seu leito cheio de aromas e de unguentos delicadíssimos, que tinham sido compostos segundo a arte dos perfumadores, e queimaram uma grande quantidade deles.

'''

xref:014-ii-cronicas/014-ii-cronicas-015.adoc#v14-15-0[&#60; Capítulo Anterior] | <<v14-16-0,Topo>> | xref:014-ii-cronicas/014-ii-cronicas-017.adoc#v14-17-0[Próximo Capítulo &#62;]