include::./index.adoc[]

[[v14-23-0]]
=== II Crônicas, 23
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 23 de 2 Crônicas relata a ascensão de Joás ao trono de Judá, após a morte de Atalia, uma rainha perversa que havia usurpado o trono e eliminado os descendentes de Davi. O sacerdote Joiada liderou uma revolta e consagrou Joás como rei, restabelecendo a aliança do povo com Deus. Abaixo estão cinco versículos relacionados aos temas abordados neste capítulo:
* Gênesis 17:7: "Estabelecerei a minha aliança entre mim e ti e os teus descendentes no decurso das suas gerações, aliança perpétua, para ser o teu Deus e o Deus da tua descendência." A aliança entre Deus e o povo de Israel é um tema recorrente em toda a Bíblia, e neste capítulo é destacada a importância de restabelecer essa aliança que havia sido rompida pelo governo anterior.
* Deuteronômio 17:18-20: "Quando se assentar no trono do seu reino, mandará fazer para si, em rolo, uma cópia desta lei, segundo o original dos sacerdotes, levitas. Terá-a consigo e nela lerá todos os dias da sua vida, para aprender a temer o Senhor, seu Deus, e a observar todas as palavras desta lei e estes preceitos, para os cumprir; para que não se eleve o seu coração sobre seus irmãos e não se desvie deste mandamento nem para a direita nem para a esquerda; e para que prolongue os seus dias no seu reino, ele e seus filhos, no meio de Israel." A importância de seguir a lei de Deus é destacada neste versículo, e a consagração de Joás como rei incluiu o cumprimento dessas leis.
* Salmos 45:6: "Teu trono, ó Deus, é eterno e perpétuo; o cetro do teu reino é cetro de equidade." Este salmo descreve o rei como um instrumento de Deus, e a ascensão de Joás ao trono é vista como uma restauração da vontade de Deus para o povo de Judá.
* Jeremias 33:17: "Porque assim diz o Senhor: Nunca faltará a Davi homem que se assente sobre o trono da casa de Israel." Este versículo se refere à promessa de Deus a Davi de que sua descendência sempre governaria sobre Israel, e a ascensão de Joás é vista como o cumprimento dessa promessa.
* Malaquias 4:2: "Mas para vós outros que temeis o meu nome nascerá o sol da justiça, trazendo salvação nas suas asas; e vós saireis e saltareis como bezerros soltos no curral." Este versículo destaca a importância de temer a Deus e seguir sua vontade, e a consagração de Joás como rei é vista como um momento de renovação espiritual para o povo de Judá.
****

[[v14-23-1]]

^<<v14-23-1,1>>^ No sétimo ano, Jojada, cheio de intrepidez, tomou consigo os centuriões, a saber; Azarias, filho de Jeroão, Ismael, filho de Joanão, Azarias, filho de Obed, Maasias, filho de Adaia, Elisafat, filho de Zecri, e coligou-se com eles.

[[v14-23-2]]

^<<v14-23-2,2>>^ Eles, tendo percorrido Judá, congregaram os levitas de todas as cidades de Judá e os chefes das famílias de Israel, e foram a Jerusalém.

[[v14-23-3]]

^<<v14-23-3,3>>^ Toda esta multidão fez liga com o rei na casa de Deus. Jojada disse-lhes: Eis aqui o filho do rei, que deve reinar, segundo aquilo que o Senhor disse a favor dos descendentes de Davide.

[[v14-23-4]]

^<<v14-23-4,4>>^ Eis o que deveis fazer:

[[v14-23-5]]

^<<v14-23-5,5>>^ A terça parte de vós, sacerdotes, Levitas e porteiros, que entrais de serviço no templo, ao sábado, estará às portas; a outra terça parte colocar-se-á junto ao palácio do rei; a outra terça à porta, que se chama do Fundamento. Todo o resto do povo estará nos átrios da casa do Senhor.

[[v14-23-6]]

^<<v14-23-6,6>>^ Nenhum outro entre na casa do Senhor, senão os sacerdotes e os Levitas que estão de serviço; entrem sòmente estes, porque estão santificados; todo o resto do povo esteja guardando a porta da casa do Senhor.

[[v14-23-7]]

^<<v14-23-7,7>>^ Os Levitas rodearão o rei, tendo cada um as suas armas; se algum outro entrar no templo, seja morto. Acompanhareis o rei, quando ele entrar ou quando sair.

[[v14-23-8]]

^<<v14-23-8,8>>^ Os Levitas, pois, e todo o Judá executaram tudo o que o pontífice Jojada lhes tinha ordenado. Cada um tomou os que tinha às suas ordens, aqueles que entravam, tanto os que principiavam como os que acabavam o serviço, ao sábado, porque o pontífice e Jojada não tinha dispensado nenhuma das turmas, que costumavam suceder umas às outras todas os semanas.

[[v14-23-9]]

^<<v14-23-9,9>>^ O sacerdote Jojada deu aos centuriões as lanças e os escudos, tanto os grandes como os pequenos, do rei Davide, os quais ele tinha consagrado na casa do Senhor.

[[v14-23-10]]

^<<v14-23-10,10>>^ Depois dispôs todo o povo armado de espadas na mão, desde o lado direito do templo até ao lado esquerdo do templo, diante do altar e do templo, de forma a rodear o rei.

[[v14-23-11]]

^<<v14-23-11,11>>^ Então trouxeram o filho do rei, puseram-lhe a corôa na cabeça e o testemunho, deram-lhe a lei, para que a tivesse na mão, e proclamaram-no rei. O pontífice Jojada e seus filhos ungiram-no, aclamando-o aos gritos de: Viva o rei!

[[v14-23-12]]

^<<v14-23-12,12>>^ Atalia, tendo ouvido a voz dos que corriam e aclamavam o rei, apresentou-se ao povo no templo do Senhor.

[[v14-23-13]]

^<<v14-23-13,13>>^ Quando viu o rei posto de pé sobre um estrado, à entrada, e os príncipes e as tropas, ao redor dele, e todo o povo do país muito alegre; (quando ouviu) o toque das trombetas e os cantares, ao som de vários instrumentos, a dirigirem os cânticos de louvor, rasgou os seus vestidos e disse: Traição! traição!

[[v14-23-14]]

^<<v14-23-14,14>>^ Então o sacerdote Jojada, aproximando-se dos centuriões e dos chefes do exército, disse-lhes: Tirai-a para fora do recinto do templo, por entre as vossas fileiras; se alguém a seguir, seja morto à espada. Com efeito, o sacerdote ordenara que não fosse morta na casa do Senhor.

[[v14-23-15]]

^<<v14-23-15,15>>^ E agarraram-na pelo pescoço; e, quando ela tinha entrado a porta dos cavalos da casa do rei, ali a mataram.

[[v14-23-16]]

^<<v14-23-16,16>>^ Jojada fez aliança entre si e todo o povo e o rei, pela qual seriam o povo do Senhor.

[[v14-23-17]]

^<<v14-23-17,17>>^ Todo o povo entrou no templo de Baal e o destruiu; despedaçou altares e imagens e matou, diante dos altares, Matam, sacerdote de Baal.

[[v14-23-18]]

^<<v14-23-18,18>>^ Jojada estabeleceu oficiais para a guarda do templo do Senhor, subordinados aos sacerdotes e aos Levitas, segundo a distribuição que deles tinha feito Davide na casa do Senhor, para oferecerem holocaustos ao Senhor, como está escrito na lei de Moisés, com alegria e com cânticos, segundo a determinação de Davide.

[[v14-23-19]]

^<<v14-23-19,19>>^ Pôs também porteiros às portas da casa do Senhor, para nela não entrar imundo algum, por qualquer motivo que fosse.

[[v14-23-20]]

^<<v14-23-20,20>>^ Tomou os centuriões, os homens mais valentes e os chefes do povo, com toda a gente do país, e fez descer o rei da casa do Senhor. Entraram pela porta superior para o palácio do rei e puseram-no sobre o trono real.

[[v14-23-21]]

^<<v14-23-21,21>>^ Todo o povo do país se alegrou e a cidade ficou em paz. Atalia foi morta à espada.

'''

xref:014-ii-cronicas/014-ii-cronicas-022.adoc#v14-22-0[&#60; Capítulo Anterior] | <<v14-23-0,Topo>> | xref:014-ii-cronicas/014-ii-cronicas-024.adoc#v14-24-0[Próximo Capítulo &#62;]