include::./index.adoc[]

[[v14-6-0]]
=== II Crônicas, 6
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* 2 Crônicas 6 descreve a dedicação do templo de Salomão, com Salomão pedindo a Deus para abençoar e ouvir as orações daqueles que vêm ao templo para buscar o Senhor. Ele também faz uma oração de dedicação, pedindo a Deus que esteja presente no templo e atenda às orações que são feitas ali. Abaixo estão cinco versículos relacionados aos temas abordados em 2 Crônicas 6:
* 1 Reis 8:27: "Mas, na verdade, habitaria Deus na terra? Eis que os céus, e até o céu dos céus, não te podem conter, quanto menos esta casa que tenho edificado." Esse verso faz parte da oração de Salomão e reconhece que Deus é grande demais para ser contido em um único lugar, como o templo.
* 1 Reis 8:41-43: "E também, acerca do estrangeiro, que não é do teu povo Israel, quando vier de terras remotas, por amor do teu nome (porque ouvirão da tua grandeza, e da tua mão forte, e do teu braço estendido), e orar voltado para esta casa, ouve tu nos céus, lugar da tua habitação, e faze conforme a tudo o que o estrangeiro te pedir; a fim de que todos os povos da terra conheçam o teu nome, para te temerem como o teu povo Israel." Esses versos fazem parte da oração de Salomão, pedindo que Deus ouça as orações daqueles que vêm de outros países para adorá-Lo no templo e que todos os povos conheçam a grandeza de Deus.
* Salmos 132:13-14: "Porque o Senhor escolheu a Sião; desejou-a para a sua habitação, dizendo: Este é o meu lugar de repouso para sempre; aqui habitarei, pois o desejei." Esses versos mostram o desejo de Deus de habitar em Sião, onde o templo de Salomão foi construído.
* Isaías 56:7: "Também os levarei ao meu santo monte, e os alegrarei na minha casa de oração; os seus holocaustos e os seus sacrifícios serão aceitos no meu altar; porque a minha casa será chamada casa de oração para todos os povos." Esse verso mostra como o templo é visto como um lugar de oração e adoração para todos os povos.
* João 4:21-24: "Disse-lhe Jesus: Mulher, crê-me que a hora vem, em que nem neste monte, nem em Jerusalém adorareis o Pai. Vós adorais o que não sabeis; nós adoramos o que sabemos porque a salvação vem dos judeus. Mas a hora vem, e agora é, em que os verdadeiros adoradores adorarão o Pai em espírito e em verdade; porque o Pai procura a tais que assim o adorem." Esses versos mostram como a adoração a Deus não está limitada a um lugar físico, mas deve ser em espírito e em verdade.
****

[[v14-6-1]]

^<<v14-6-1,1>>^ Então disse Salomão: O Senhor declarou que habitaria na escuridão!

[[v14-6-2]]

^<<v14-6-2,2>>^ Eu edifiquei uma casa ao seu nome, para que habite nela para sempre.

[[v14-6-3]]

^<<v14-6-3,3>>^ Depois o rei voltou o seu rosto e abençoou toda a multidão de Israel (porque toda a gente estava de pé, atenta) e disse:

[[v14-6-4]]

^<<v14-6-4,4>>^ Bem-dito seja o Senhor, Deus de Israel, que cumpriu o que prometeu a Davide, meu pai, dizendo:

[[v14-6-5]]

^<<v14-6-5,5>>^ Desde o dia em que eu fiz sair o meu povo da terra do Egito, não escolhi cidade alguma entre todos as tribos de Israel, para nela se levantar uma casa ao meu nome, nem escolhi homem algum para ser chefe do meu povo de Israel;

[[v14-6-6]]

^<<v14-6-6,6>>^ mas escolhi Jerusalém, para nela se honrar o meu nome, e escolhi Davide, para o constituir sobre o meu povo de Israel.

[[v14-6-7]]

^<<v14-6-7,7>>^ Meu pai Davide desejou edificar uma casa ao nome do Senhor Deus de Israel,

[[v14-6-8]]

^<<v14-6-8,8>>^ mas o Senhor disse-lhe: Já que tu tiveste vontade de edificar uma casa ao meu nome, (digo-te que) certamente fizeste bem em ter tal vontade;

[[v14-6-9]]

^<<v14-6-9,9>>^ todavia não serás tu o que hás-de edificar a casa; teu filho, que sairá de tuas entranhas, esse edificará uma casa ao meu nome.

[[v14-6-10]]

^<<v14-6-10,10>>^ O Senhor, pois, cumpriu a palavra, que tinha dito: eu sucedi a Davide, meu pai, sentei-me sobre o trono de Israel, como o Senhor o disse, edifiquei uma casa ao nome do Senhor Deus de Israel,

[[v14-6-11]]

^<<v14-6-11,11>>^ e coloquei nela a arca, na qual está o pacto que o Senhor fez com os filhos de Israel.

[[v14-6-12]]

^<<v14-6-12,12>>^ Dito isto, Salomão pôs-se em pé diante do altar do Senhor, na presença de toda a multidão de Israel, e estendeu as mãos.

[[v14-6-13]]

^<<v14-6-13,13>>^ É de notar que Salomão tinha feito um estrado de bronze de cinco côvados de comprido, e outros tantos de largo, e três de alto, o qual tinha colocado ao meio do átrio. Subiu a ele e, posto de joelhos, com o rosto virado para toda a multidão de Israel e as mãos levantadas ao céu,

[[v14-6-14]]

^<<v14-6-14,14>>^ disse: Senhor, Deus de Israel, não há Deus semelhante a ti, nem no céu, nem na terra, a ti, que observas o pacto e a misericórdia com os teus servos, que andam diante de ti de todo o seu coração,

[[v14-6-15]]

^<<v14-6-15,15>>^ que cumpriste todas as promessas que fizeste a teu servo Davide, meu pai. Realizaste com a mão o que prometeste com a boca, como agora se verifica.

[[v14-6-16]]

^<<v14-6-16,16>>^ Cumpre, também agora, Senhor Deus de Israel, a favor da Davide, meu pai e teu servo, tudo o que lhe prometeste, quando disseste: Não faltará da tua descendência um homem que se sente na minha presença sobre o trono de Israel, contanto, porém, que teus filhos tenham cuidado com a sua conduta, andem segundo a minha lei, como tu também andaste na minha presença.

[[v14-6-17]]

^<<v14-6-17,17>>^ Agora, Senhor Deus de Israel, confirme-se a palavra, que deste a teu servo Davide.

[[v14-6-18]]

^<<v14-6-18,18>>^ Porém, como é crível que Deus habite com os homens sobre a terra? Se o céu e os céus dos céus te não podem conter, quanto menos esta casa, que eu edifiquei!

[[v14-6-19]]

^<<v14-6-19,19>>^ Contudo atende à oração e às súplicas do teu servo, Senhor meu Deus, ouve o grito e as preces, que o teu servo faz na tua presença.

[[v14-6-20]]

^<<v14-6-20,20>>^ Que, de dia e de noite, tenhas os teus olhos abertos sobre esta casa, sobre o lugar, ao qual prometeste que o teu nome seria invocado.

[[v14-6-21]]

^<<v14-6-21,21>>^ Escuta as súplicas do teu servo e as do teu povo de Israel, quando orarem neste lugar. Ouve, Senhor, da tua morada, que é o céu, todo aquele que neste lugar orar, e sê-lhe propício.

[[v14-6-22]]

^<<v14-6-22,22>>^ Se alguém pecar contra o seu próximo, e se apresentar para dar juramento contra ele, jurando diante do teu altar nesta casa,

[[v14-6-23]]

^<<v14-6-23,23>>^ ouve, do céu, e faze justiça aos teus servos, de maneira que faças recair a perfídia do culpado sobre a sua cabeça, e vingues o justo, retribuindo-lhe segundo a sua justiça.

[[v14-6-24]]

^<<v14-6-24,24>>^ Se o teu povo de Israel for vencido pelos seus inimigos (porque pecou contra ti) e, convertido, fizer penitência, e invocar o teu nome, e vier suplicar neste lugar,

[[v14-6-25]]

^<<v14-6-25,25>>^ ouve-o do céu, perdoa o pecado ao teu povo de Israel, e restitui-o à terra que lhe deste a ele e a seus pais.

[[v14-6-26]]

^<<v14-6-26,26>>^ Quando fechado o céu, a chuva não cair por causa dos pecados do povo, se te rogarem neste lugar e, dando glória ao teu nome, se converterem e fizerem penitência dos seus pecados, quando os afligires,

[[v14-6-27]]

^<<v14-6-27,27>>^ ouve-os lá do céu, Senhor, perdoa os pecados dos teus servos e do teu povo de Israel, ensina-lhes o bom caminho, por onde andem, e derrama a chuva sobre a terra que tu deste ao povo para possuir.

[[v14-6-28]]

^<<v14-6-28,28>>^ Quando sobrevier à terra fome, ou peste, mela ou corrupção do ar, ou gafanhotos, ou pulgão; quando os inimigos, depois de destruídos os campos, sitiarem os portas da cidade, ou qualquer outro flagelo ou doença oprimir (o teu povo),

[[v14-6-29]]

^<<v14-6-29,29>>^ se alguém do teu povo de Israel, considerando a sua praga e doença te suplicar e levantar as suas mãos para ti nesta casa,

[[v14-6-30]]

^<<v14-6-30,30>>^ ouve-o do céu, tua sublime morada, sê-lhe propício, dá a cada um conforme as obras que conheces que tem no seu coração, (pois que só tu conheces os corações dos filhos dos homens),

[[v14-6-31]]

^<<v14-6-31,31>>^ a fim de que eles te temam e andem pelos teus caminhos, todos os dias que viverem sobre a face da terra, que deste a nossos pais.

[[v14-6-32]]

^<<v14-6-32,32>>^ Quando um estrangeiro, que não é do teu povo de Israel vier dum país remoto, atraído pela fama do teu grande nome, da tua fortaleza e do poder do teu braço estendido, e te adorar neste lugar,

[[v14-6-33]]

^<<v14-6-33,33>>^ ouve-o do céu, tua firmíssima habitação, e concede-lhe todas as coisas que esse peregrino te pedir, para que todos os povos da terra conheçam o teu nome e te temam, como o teu povo de Israel, e reconheçam que o teu nome foi invocado nesta casa que eu edifiquei.

[[v14-6-34]]

^<<v14-6-34,34>>^ Quando o teu povo sair à campanha contra os seus inimigos, seguindo pelo caminho pelo qual tu o tiveres mandado, e te adorar com a face virada para o caminho, onde está situada esta cidade que tu escolheste e a casa que eu edifiquei ao teu nome,

[[v14-6-35]]

^<<v14-6-35,35>>^ ouve do céu as suas orações e as suas súplicas e vinga-o (dos seus inimigos).

[[v14-6-36]]

^<<v14-6-36,36>>^ Quando eles, porém, pecarem contra ti (porque não há homem que não peque), e tu, irado contra eles, os entregares aos inimigos, e estes os levarem cativos para um país remoto ou vizinho,

[[v14-6-37]]

^<<v14-6-37,37>>^ se eles, convertendo-se do seu coração na terra para onde foram levados cativos, fizerem penitência e recorrerem a ti, na terra do seu cativeiro, dizendo: Nós pecamos, nós cometemos a iniquidade, nós procedemos injustamente;

[[v14-6-38]]

^<<v14-6-38,38>>^ se se voltarem para ti de todo o seu coração e de toda a sua alma, no país do seu cativeiro a que foram levados, e te adorarem voltados para o caminho da sua terra que deste a seus pais, da cidade que escolheste, do templo que eu edifiquei ao teu nome,

[[v14-6-39]]

^<<v14-6-39,39>>^ ouve-os, do céu, da tua morada, as suas súplicas, faze-lhes justiça, perdoa ao teu povo, ainda que pecador.

[[v14-6-40]]

^<<v14-6-40,40>>^ Agora, ó meu Deus, abram-se, te peço, os teus olhos, e estejam atentos os teus ouvidos à oração que se fizer neste lugar.

[[v14-6-41]]

^<<v14-6-41,41>>^ Levanta-te, pois, Senhor Deus, e vem para o teu descanso, tu e a arca (por meio da qual mostras a) tua fortaleza. Os teus sacerdotes, Senhor Deus, sejam revestidos de força salutar, e os teus santos se alegrem nos teus bens.

[[v14-6-42]]

^<<v14-6-42,42>>^ Senhor Deus, não apartes o rosto deste teu ungido; lembra-te das misericórdias concedidas ao teu servo Davide.

'''

xref:014-ii-cronicas/014-ii-cronicas-005.adoc#v14-5-0[&#60; Capítulo Anterior] | <<v14-6-0,Topo>> | xref:014-ii-cronicas/014-ii-cronicas-007.adoc#v14-7-0[Próximo Capítulo &#62;]