include::./index.adoc[]

[[v14-26-0]]
=== II Crônicas, 26
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* 2 Crônicas 26 narra o reinado de Uzias, um rei de Judá que começou bem, mas que acabou caindo em orgulho e desobediência a Deus. Durante seu reinado, Judá prosperou e Uzias se tornou um rei poderoso, mas seu orgulho o levou a entrar no templo e tentar oferecer incenso, algo que apenas os sacerdotes eram autorizados a fazer. Como resultado, ele foi punido por Deus com a lepra. Abaixo estão cinco versículos relacionados com os temas abordados em 2 Crônicas 26:
* Provérbios 16:18: "O orgulho precede a ruína, e a arrogância vem antes da queda." Este versículo é relevante para o capítulo 26, já que Uzias caiu em desgraça por causa de seu orgulho e arrogância.
* 2 Crônicas 26:5: "Buscou a Deus durante a vida de Zacarias, mestre dos videntes que lhe dava instrução no temor de Deus." Este versículo mostra que Uzias começou seu reinado buscando a Deus e seguindo seus ensinamentos.
* Provérbios 16:32: "Melhor é o paciente do que o guerreiro, mais vale controlar o seu espírito do que conquistar uma cidade." Este versículo é relevante para Uzias, que foi um guerreiro bem-sucedido, mas que não conseguiu controlar seu espírito de orgulho e desobediência.
* 2 Crônicas 26:16: "Mas, quando já era poderoso, seu coração se tornou tão orgulhoso que agiu com infidelidade contra o Senhor, seu Deus. Entrou no templo do Senhor para queimar incenso no altar do incenso." Este versículo mostra como Uzias se tornou orgulhoso e desobediente a Deus, o que acabou levando à sua queda.
* Isaías 6:1: "No ano em que o rei Uzias morreu, eu vi o Senhor assentado num trono alto e exaltado, e a aba de sua veste enchia o templo." Este versículo mostra que Uzias foi um rei importante em Judá e que sua morte teve um grande impacto. Também pode ser interpretado como um sinal da punição divina sobre Uzias por sua desobediência.
****

[[v14-26-1]]

^<<v14-26-1,1>>^ Todo o povo de Judá constituiu rei a Ozias, que tinha a idade de dezasseis anos, em lugar de Amasias, seu pai.

[[v14-26-2]]

^<<v14-26-2,2>>^ Ele reedificou Ailat e restituiu-a ao domínio de Judá, depois que o rei (Amasias) adormeceu com seus pais.

[[v14-26-3]]

^<<v14-26-3,3>>^ Tinha Ozias dezasseis anos, quando começou a reinar, e reinou cinquenta e dois em Jerusalém. Sua mãe chamava-se Jequelia, de Jerusalém.

[[v14-26-4]]

^<<v14-26-4,4>>^ Fez o que era recto aos olhos do Senhor, conforme tudo o que tinha feito Amasias, seu pai.

[[v14-26-5]]

^<<v14-26-5,5>>^ Buscou o Senhor enquanto viveu Zacarias, homem inteligente e profeta de Deus; como ele buscava o Senhor, o Senhor o dirigiu em tudo.

[[v14-26-6]]

^<<v14-26-6,6>>^ Pôs-se em campanha contra os Filisteus, e destruiu os muros de Get, de Jabnia e os de Azoto; edificou também praças fortes em Azoto e nas terras dos Filisteus.

[[v14-26-7]]

^<<v14-26-7,7>>^ Deus ajudou-o contra os Filisteus, contra os Árabes, que habitavam em Gurbaal, e contra os Amonitas.

[[v14-26-8]]

^<<v14-26-8,8>>^ Os Amonitas pagavam tributos a Ozias. A sua reputação difundiu-se até à entrada do Egito, por causa das suas frequentes vitórias.

[[v14-26-9]]

^<<v14-26-9,9>>^ Ozias levantou torres em Jerusalém sobre a porta do ângulo, sobre a porta do vale e outras, no mesmo lado do muro, e fortificou-as.

[[v14-26-10]]

^<<v14-26-10,10>>^ Edificou também torres, no deserto, e mandou abrir muitas cisternas, porque tinha muito gado, assim nos campos, como pela vastidão do deserto; tinha também vinhas e vinhateiros nos montes e no Carmelo, porque era homem afeiçoado à agricultura.

[[v14-26-11]]

^<<v14-26-11,11>>^ O exército dos seus guerreiros, que saiam à campanha, contados segundo o recenseamento feito por Jeiel, secretário, e Maasias, comissário, sob o comando de Hanamias, que era um dos generais do rei.

[[v14-26-12]]

^<<v14-26-12,12>>^ O número completo dos chefes das famílias, guerreiros valorosos, montava a dois mil e seiscentos.

[[v14-26-13]]

^<<v14-26-13,13>>^ Estes tinham sob as suas ordens o exército, que era de trezentos e sete mil e quinhentos soldados, capazes de sustentar o rei contra os inimigos.

[[v14-26-14]]

^<<v14-26-14,14>>^ Para todo este exército, Ozias preparou escudos, lanças, capacetes, couraças, arcos e fundas para atirar pedras.

[[v14-26-15]]

^<<v14-26-15,15>>^ Mandou fazer em Jerusalém várias espécies de máquinas, as quais mandou pôr nas torres e nos cantos das muralhas, para disparar flechas e grossas pedras. A fama do seu nome espalhou-se até muito longe, porque o Senhor o auxiliava e o fortalecia.

[[v14-26-16]]

^<<v14-26-16,16>>^ Mas, ao ver-se poderoso, o seu coração elevou-se de soberba para sua ruína. Pecou contra o Senhor seu Deus, entrando no templo do Senhor para oferecer incenso sobre o altar dos perfumes.

[[v14-26-17]]

^<<v14-26-17,17>>^ Logo após ele, entrou o pontífice Azarias com oitenta sacerdotes do Senhor, homens corajosos,

[[v14-26-18]]

^<<v14-26-18,18>>^ que se opuseram ao rei, dizendo: Não pertence a ti, Ozias, queimar incenso ao Senhor, mas aos sacerdotes, isto é, aos filhos de Aarão, que foram consagrados para este ministério; sai do santuário, não queiras fazer este desprezo, porque esta ação não será gloriosa para ti diante do Senhor Deus.

[[v14-26-19]]

^<<v14-26-19,19>>^ Então Ozias, irado, tendo na mão o turíbulo para oferecer incenso, ameaçou os sacerdotes. Imediatamente apareceu-lhe lepra na fronte em presença dos sacerdotes, no templo do Senhor, junto ao altar dos perfumes.

[[v14-26-20]]

^<<v14-26-20,20>>^ Tendo o pontífice Azarias e todos os outros sacerdotes posto os olhos nele, viram a lepra na sua fronte e, sem mais demora, o lançaram fora. Ele mesmo, cheio de medo, apressou-se a sair, porque tinha sentido logo a praga com que o Senhor o tinha ferido.

[[v14-26-21]]

^<<v14-26-21,21>>^ O rei Ozias foi, pois, leproso até ao dia da sua morte; habitou numa casa separada, cheio de lepra, por causa da qual tinha sido lançado fora da casa do Senhor. Joatão, seu filho, governava a casa do rei e administrava justiça ao povo.

[[v14-26-22]]

^<<v14-26-22,22>>^ O resto das ações de Ozias, assim as primeiras como as últimas, foi escrito pelo profeta Isaías, filho de Amós.

[[v14-26-23]]

^<<v14-26-23,23>>^ Ozias adormeceu com seus pais, e foi enterrado no campo dos sepulcros reais, porque era leproso. Seu filho Joatão reinou em seu lugar.

'''

xref:014-ii-cronicas/014-ii-cronicas-025.adoc#v14-25-0[&#60; Capítulo Anterior] | <<v14-26-0,Topo>> | xref:014-ii-cronicas/014-ii-cronicas-027.adoc#v14-27-0[Próximo Capítulo &#62;]