include::./index.adoc[]

[[v34-14-0]]
=== Daniel, 14
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 14 de Daniel é um apêndice encontrado em algumas versões da Bíblia que conta a história de um jovem profeta chamado Habacuque, que foi levado pelo anjo de Deus para alimentar Daniel na cova dos leões. Nesse capítulo, Habacuque é retratado como um homem de grande fé e coragem, que se dispõe a arriscar sua vida para obedecer à vontade de Deus. A seguir, estão cinco versículos relacionados com os temas abordados em Daniel 14:
* Atos 5:29: "Então Pedro e os outros apóstolos responderam e disseram: Mais importa obedecer a Deus do que aos homens." Esse verso destaca a importância de seguir a vontade de Deus, mesmo quando isso vai contra a vontade ou os desejos dos homens.
* 1 Coríntios 16:13: "Vigiai, estai firmes na fé; portai-vos varonilmente, e fortalecei-vos." Essa passagem exorta os cristãos a permanecerem firmes na fé, mesmo diante de adversidades ou tentações.
* Romanos 1:17: "Porque nele se descobre a justiça de Deus de fé em fé, como está escrito: Mas o justo viverá da fé." Esse verso destaca a importância da fé em Deus como meio de alcançar a justiça e a salvação.
* Tiago 2:14: "Meus irmãos, que aproveita se alguém disser que tem fé e não tiver as obras? Porventura a fé pode salvá-lo?" Essa passagem enfatiza a importância de ter uma fé ativa, que se manifesta em ações concretas e boas obras.
* Hebreus 11:6: "Ora, sem fé é impossível agradar-lhe, porque é necessário que aquele que se aproxima de Deus creia que ele existe e que é galardoador dos que o buscam." Esse verso destaca a importância da fé como meio de se aproximar de Deus e agradá-lo.
****

[[v34-14-1]]

^<<v34-14-1,1>>^ Ora Daniel comia à mesa do rei, que o tinha elevado em honra acima de todos os seus amigos.

[[v34-14-2]]

^<<v34-14-2,2>>^ Entre os Babilônios havia um ídolo chamado Bel; gastavam-se com ele todos os dias doze artabes de flor de farinha, quarenta ovelhas e seis medidas de vinho. (ver nota)

[[v34-14-3]]

^<<v34-14-3,3>>^ O rei também honrava esse ídolo e todos os dias o ia adorar. Daniel, porém, adorava o seu Deus. O rei disse-Ihe: Por que não adoras Bel?

[[v34-14-4]]

^<<v34-14-4,4>>^ Daniel respondeu-lhe: Porque eu não adoro os ídolos, que são feitos por mãos de homens, mas sim o Deus vivo, que criou o céu e a terra e que tem debaixo do seu poder toda a carne.

[[v34-14-5]]

^<<v34-14-5,5>>^ O rei disse-lhe: Não te parece que Bel é um Deus vivo? Não vês o que ele come e bebe todos os dias?

[[v34-14-6]]

^<<v34-14-6,6>>^ Daniel respondeu-lhe, sorrindo: Ó rei, não te iludas; esse ídolo é de barro por dentro, e de bronze, por fora, e nunca comeu.

[[v34-14-7]]

^<<v34-14-7,7>>^ Então o rei, todo irado, chamou os sacerdotes de Bel e disse-lhes: Se me não indicardes quem é que come as oferendas (feitas a Bel) morrereis.

[[v34-14-8]]

^<<v34-14-8,8>>^ Mas, se mostrardes que Bel é quem come tudo isso, morrerá Daniel, porque blasfemou contra Bel. Daniel disse ao rei: Faça-se segundo a tua palavra.

[[v34-14-9]]

^<<v34-14-9,9>>^ Ora os sacerdotes de Bel eram setenta, sem contar as suas mulheres e os seus filhos. O rei foi com Daniel ao templo de Bel.

[[v34-14-10]]

^<<v34-14-10,10>>^ Os sacerdotes de Bel disseram-lhe: Nós vamos sair; e tu, ó rei, manda pôr os alimentos e o vinho, depois de feita a mistura, fecha a porta do templo e sela-a com o teu anel.

[[v34-14-11]]

^<<v34-14-11,11>>^ Quando entrares amanhã, de manhã, se não achares que Bel comeu tudo, morreremos; caso contrário, morrerá Daniel que mentiu contra nós.

[[v34-14-12]]

^<<v34-14-12,12>>^ Estavam muito confiados, porque tinham feito debaixo da mesa do altar uma entrada secreta, por onde entravam sempre para levar as oferendas.

[[v34-14-13]]

^<<v34-14-13,13>>^ Logo que os sacerdotes saíram, mandou o rei pôr os alimentos diante de Bel; Daniel, porém, mandou aos seus criados que lhe trouxessem cinza, e espalhou-a por todo o templo, na presença do rei, fazendo-a passar por um crivo. Ao sair, fecharam a porta do templo; depois selaram-na com o anel do rei e retiraram-se.

[[v34-14-14]]

^<<v34-14-14,14>>^ Os sacerdotes entraram durante a noite, segundo o seu costume, com suas mulheres e filhos, e comeram e beberam tudo.

[[v34-14-15]]

^<<v34-14-15,15>>^ O rei levantou-se, ao romper da manhã, e Daniel com ele.

[[v34-14-16]]

^<<v34-14-16,16>>^ O rei disse: Estão intactos os selos? Ele respondeu: Estão intactos, ó rei.

[[v34-14-17]]

^<<v34-14-17,17>>^ Imediatamente o rei, tendo aberto a porta, olhou para a mesa e exclamou em alta voz: Tu és grande, é Bel, e não há em ti engano algum.

[[v34-14-18]]

^<<v34-14-18,18>>^ Daniel começou a rir e, detendo o rei para não passar mais adiante, disse: Olha para este pavimento e considera de quem são estas pegadas.

[[v34-14-19]]

^<<v34-14-19,19>>^ O rei disse: Vejo pegadas de homens, de mulheres e de crianças. E o rei irritou-se.

[[v34-14-20]]

^<<v34-14-20,20>>^ Então mandou prender os sacerdotes, sua mulheres e filhos, os quais lhe mostraram as portas secretas, por onde entravam para consumir tudo o que estava sobre a mesa.

[[v34-14-21]]

^<<v34-14-21,21>>^ O rei mandou-os matar e entregou Bel ao arbítrio de Daniel, que o destruiu, assim como ao seu templo.

[[v34-14-22]]

^<<v34-14-22,22>>^ Havia também naquele lugar um grande dragão que os Babilônios veneravam. (ver nota)

[[v34-14-23]]

^<<v34-14-23,23>>^ O rei disse a Daniel: Dirás ainda que este é de bronze? Ele vive, come e bebe. Não podes dizer que não é um deus vivo. Adora-o, pois.

[[v34-14-24]]

^<<v34-14-24,24>>^ Daniel respondeu-lhe: Eu adoro o Senhor meu Deus, porque ele é um Deus vivo; este não é um Deus vivo.

[[v34-14-25]]

^<<v34-14-25,25>>^ Tu, é rei, dá-me licença, e eu matarei este dragão, sem espada, nem vara. O rei disse-lhe: Eu ta dou.

[[v34-14-26]]

^<<v34-14-26,26>>^ Daniel tomou pês, gordura e pêlos; cozeu tudo junto, fez umas bolas e meteu-as pela boca do dragão, e o dragão arrebentou. Daniel disse: Eis o que adoráveis.

[[v34-14-27]]

^<<v34-14-27,27>>^ Os Babilônios, tendo sabido isto, indignaram-se fortemente, e, tendo-se juntado contra o rei, disseram: O rei tornou-se judeu! Destruiu Bel, matou o dragão e mandou matar os sacerdotes.

[[v34-14-28]]

^<<v34-14-28,28>>^ Eles, pois, indo ter com o rei, disseram-lhe: Entrega-nos Daniel, senão nós te mataremos a ti e a toda a tua casa.

[[v34-14-29]]

^<<v34-14-29,29>>^ Viu o rei que apertavam com ele fortemente, e, constrangido da necessidade, entregou-lhes Daniel.

[[v34-14-30]]

^<<v34-14-30,30>>^ Eles lançaram-no na cova dos leões, onde esteve seis dias.

[[v34-14-31]]

^<<v34-14-31,31>>^ Havia no lago sete leões, aos quais, todos os dias, davam dois cadáveres e duas ovelhas; mas por então não lhos deram, a fim de que devorassem Daniel.

[[v34-14-32]]

^<<v34-14-32,32>>^ Estava então o Profeta Habacuc na Judeia.Tinha cozido um caldo e migado uns pães dentro duma vasilha, e ia levá-los ao campo, aos ceifeiros que lá trazia.

[[v34-14-33]]

^<<v34-14-33,33>>^ O anjo do Senhor disse a Habacuc: Leva a Babilônia essa refeição que tens, para a dares a Daniel, que está na cova dos leões.

[[v34-14-34]]

^<<v34-14-34,34>>^ Habacuc respondeu; Senhor, nunca vi Babilônia e não sei onde é a cova.

[[v34-14-35]]

^<<v34-14-35,35>>^ Então o anjo do Senhor tomou-o pelo alto da cabeça, e, tendo-o pelos cabelos, levou-o com a impetuosidade do seu espírito até Babilônia, sobre a cova.

[[v34-14-36]]

^<<v34-14-36,36>>^ Habacuc levantou a voz, dizendo; Daniel, Daniel, servo de Deus, toma a refeição que Deus te mandou.

[[v34-14-37]]

^<<v34-14-37,37>>^ Daniel disse: Tu, ó Deus, te lembraste de mim, não desamparaste os que te amam.

[[v34-14-38]]

^<<v34-14-38,38>>^ Então, levantando-se, Daniel comeu. E o anjo do Senhor reconduziu logo Habacuc ao seu lugar.

[[v34-14-39]]

^<<v34-14-39,39>>^ Ao sétimo dia veio o rei para chorar Daniel; aproximou-se da cova, olhou para dentro e viu Daniel assentado.

[[v34-14-40]]

^<<v34-14-40,40>>^ Deu um grande grito, dizendo: Tu és grande, ó Senhor Deus de Daniel! Não há outro Deus, além de ti! E mandou-o tirar da cova dos leões.

[[v34-14-41]]

^<<v34-14-41,41>>^ Depois mandou lançar na mesma cova os que tinham maquinado a sua perdição, os quais foram devorados diante dele num momento.

[[v34-14-42]]

^<<v34-14-42,42>>^ Então o rei disse: Todos os habitantes da terra temam o Deus de Daniel, porque ele é o Salvador, que opera sinais e maravilhas sobre a terra, que livrou Daniel da cova dos leões.

'''

xref:034-daniel/034-daniel-013.adoc#v34-13-0[&#60; Capítulo Anterior] | <<v34-14-0,Topo>> | xref:035-oseias/035-oseias-001.adoc#v35-1-0[Próximo Capítulo &#62;]