include::./index.adoc[]

[[v34-12-0]]
=== Daniel, 12
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 12 do livro de Daniel fala sobre o tempo do fim e a ressurreição dos mortos, bem como sobre a conclusão das visões proféticas que foram reveladas ao profeta. Ele também enfatiza a importância de perseverar na fé, mesmo diante de dificuldades e perseguições. A seguir, estão cinco versículos relacionados com os temas abordados em Daniel 12:
* 2 Pedro 3:9: "O Senhor não retarda a sua promessa, ainda que alguns a têm por tardia; mas é longânimo para convosco, não querendo que alguns se percam, senão que todos venham a arrepender-se." Esse verso destaca a paciência e o amor de Deus para com seus filhos, mesmo diante de circunstâncias que parecem indicar um atraso em suas promessas.
1 Coríntios 15:52: "Num momento, num abrir e fechar de olhos, ante a última trombeta; porque a trombeta soará, e os mortos ressuscitarão incorruptíveis, e nós seremos transformados." Essa passagem fala sobre a ressurreição dos mortos, um dos temas centrais do capítulo 12 de Daniel.
Hebreus 10:36: "Porque necessitais de paciência, para que, depois de haverdes feito a vontade de Deus, possais alcançar a promessa." Esse versículo enfatiza a importância da perseverança e da paciência na espera pela realização das promessas de Deus.
Tiago 1:2-4: "Meus irmãos, tende grande gozo quando cairdes em várias tentações, sabendo que a prova da vossa fé produz a paciência. Tenha, porém, a paciência a sua obra perfeita, para que sejais perfeitos e completos, sem faltar em coisa alguma." Essa passagem destaca o valor da perseverança e da paciência diante de testes e provações, como uma forma de aprimorar a nossa fé.
Apocalipse 22:7: "Eis que venho sem demora. Bem-aventurado aquele que guarda as palavras da profecia deste livro." Esse verso reforça a ideia da importância de perseverar na fé e manter-se fiel às palavras proféticas de Deus, que foram reveladas em visões como as de Daniel.
****

[[v34-12-1]]

^<<v34-12-1,1>>^ Nesse tempo se levantará Miguel, o grande príncipe, protector dos filhos do teu povo. Será um tempo de tal angústia, qual não houve desde que os povos começaram a existir até então. Nesse tempo o teu povo será salvo; (sê-lo-á) todo aquele que estiver inscrito no livro (da vida). (ver nota)

[[v34-12-2]]

^<<v34-12-2,2>>^ Muitos dos que dormem no pó da terra acordarão, uns para a vida eterna, e outros para a vergonha, o horror eterno.

[[v34-12-3]]

^<<v34-12-3,3>>^ Aqueles que tiverem sido doutos, resplandecerão como a luz do firmamento ; e os que tiverem ensinado a muitos o caminho da justiça, brilharão como as estrelas por toda a eternidade.

[[v34-12-4]]

^<<v34-12-4,4>>^ Tu, porém, Daniel, conserva guardadas estas palavras e sela o livro até ao tempo do fim ; muitos o passarão pelos olhos e acrescentarão a sua ciência.

[[v34-12-5]]

^<<v34-12-5,5>>^ Então eu, Daniel, olhei e vi que estavam em pé outros dois homens; um, duma parte sobre a margem do rio, e outro, da outra parte sobre a outra margem do mesmo rio.

[[v34-12-6]]

^<<v34-12-6,6>>^ um deles disse ao homem que estava vestido de roupas de linho, o qual se sustinha em pé sobre as águas do rio : Quando se cumprirão estas coisas extraordinárias?

[[v34-12-7]]

^<<v34-12-7,7>>^ E ouvi o homem, vestido de roupas de linho, o qual se sustinha em pé sobre as águas do rio; tendo levantado ao céu a mão direita e a mão esquerda, jurou por aquele (Senhor) que vive eternamente, que isso seria depois dum tempo; (dois) tempos e metade dum tempo, que todas estas coisas se cumpririam, quando acabasse de ser despedaçada a força do povo santo. (ver nota)

[[v34-12-8]]

^<<v34-12-8,8>>^ Ouvi (o que ele dizia), mas não o entendi, e disse: Meu Senhor, qual será o fim de tudo isto?

[[v34-12-9]]

^<<v34-12-9,9>>^ Respondeu: Vai, Daniel, porque estas palavras estão fechadas e seladas até ao tempo do fim.

[[v34-12-10]]

^<<v34-12-10,10>>^ Muitos serão purificados, branqueados e provados; os ímpios procederão impiamente, e nenhum ímpio compreenderá, mas os sábios compreenderão. (ver nota)

[[v34-12-11]]

^<<v34-12-11,11>>^ Desde o tempo em que o sacrifício perpétuo for abolido, e a abominação da desolação for estabelecida (no templo), passarão mil e duzentos e noventa dias.

[[v34-12-12]]

^<<v34-12-12,12>>^ Bem-aventurado o que esperar e chegar até mil e trezentos e trinta e cinco dias! (ver nota)

[[v34-12-13]]

^<<v34-12-13,13>>^ Tu vai até ao fim e (depois) descansa; levantar-te-ás para (receber) a tua porção no fim dos dias.Até aqui (diz S. Jerónimo) lemos Daniel no texto hebreu.O que segue, até ao fim do livro, foi traduzido segundo a edição de Teodocião. (ver nota)

'''

xref:034-daniel/034-daniel-011.adoc#v34-11-0[&#60; Capítulo Anterior] | <<v34-12-0,Topo>> | xref:034-daniel/034-daniel-013.adoc#v34-13-0[Próximo Capítulo &#62;]