include::./index.adoc[]

[[v34-6-0]]
=== Daniel, 6
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Daniel 6 é o capítulo que narra a história de Daniel na cova dos leões. O rei Dario havia decretado que ninguém poderia orar a nenhum outro deus ou homem que não ele próprio, mas Daniel desobedeceu essa ordem e continuou orando a Deus, como de costume. Como resultado, foi lançado na cova dos leões, mas Deus o protegeu e ele sobreviveu. Abaixo estão cinco versículos relacionados com os temas abordados nesse capítulo:
* Salmo 55:17: "De tarde, e de manhã, e ao meio-dia, farei as minhas queixas e lamentarei; e ele ouvirá a minha voz." Essa passagem mostra a importância da oração constante, como a que Daniel praticava, mesmo sabendo que poderia ser condenado à morte por isso.
* Mateus 6:6: "Mas tu, quando orares, entra no teu quarto e, fechando a porta, ora a teu Pai que está em secreto; e teu Pai, que vê em secreto, te recompensará." Jesus ensina aqui sobre a importância da oração em segredo, sem se preocupar com a opinião dos outros.
* 1 Pedro 5:8: "Sede sóbrios, vigiai, porque o diabo, vosso adversário, anda em derredor, bramando como leão, buscando a quem possa tragar." Essa passagem fala sobre o diabo agindo como um leão faminto, prontos para devorar aqueles que são fiéis a Deus, como os leões na cova com Daniel.
* Hebreus 11:33-34: "Os quais, pela fé, venceram reinos, praticaram a justiça, alcançaram promessas, fecharam as bocas dos leões, apagaram a força do fogo, escaparam do fio da espada, da fraqueza tiraram forças, na batalha se esforçaram, puseram em fuga os exércitos dos estranhos." Essa passagem descreve os muitos atos de fé que foram praticados pelos heróis da fé, como Daniel, que fechou a boca dos leões pela sua fé em Deus.
* Tiago 1:12: "Bem-aventurado o homem que suporta a tentação; porque, quando for provado, receberá a coroa da vida, a qual o Senhor tem prometido aos que o amam." Essa passagem encoraja os crentes a perseverar em meio à provação e tribulação, como Daniel fez na cova dos leões, lembrando que Deus prometeu recompensa aos que o amam e o servem fielmente.
****

[[v34-6-1]]

^<<v34-6-1,1>>^ Aprouver a Dario estabelecer para o governo do reino cento e vinte sátrapas (ou governadores) repartidos por todo o reino.

[[v34-6-2]]

^<<v34-6-2,2>>^ Sobre eles constituíu três chefes dos quais Daniel era um, a fim de que estes sátrapas lhes dessem conta dos negócios, para que o rei não fosse lesado.

[[v34-6-3]]

^<<v34-6-3,3>>^ Ora Daniel avantajava-se a todos os chefes e sátrapas, porque era superior o seu espírito (de forma que) o rei pensava em o estabelecer sobre todo o reino.

[[v34-6-4]]

^<<v34-6-4,4>>^ Então os chefes e os sátrapas buscavam ocasião de o acusar no respeitante aos negócios do reino, mas não puderam achar pretexto algum ou falta, porque ele era fiel, não se achava nele culpa alguma, nem negligência.

[[v34-6-5]]

^<<v34-6-5,5>>^ Disseram, pois, aqueles homens entre si: Nós não acharemos ocasião alguma de acusar este Daniel, senão talvez pelo que diz respeito ao seu Deus.

[[v34-6-6]]

^<<v34-6-6,6>>^ Então os chefes e os sátrapas surpreenderam o rei e falaram-lhe assim: ó rei Dario, vive eternamente!

[[v34-6-7]]

^<<v34-6-7,7>>^ Todos os chefes do teu reino, os prefeitos, os sátrapas, os conselheiros e os governadores são de parecer que o rei promulgue um decreto ordenando que todo aquele que, por espaço de trinta dias, pedir alguma coisa a qualquer deus ou a qualquer homem, que não tu, ó rei, seja lançado na cova dos leões.

[[v34-6-8]]

^<<v34-6-8,8>>^ Agora, pois, ó rei, estabelece esta proibição, assina este decreto, para que, segundo o estabelecido pela lei dos Medos e dos Persas — lei irrevogável — não possa ser alterado.

[[v34-6-9]]

^<<v34-6-9,9>>^ O rei Dario, pois, assinou o decreto com a (dita) proibição.

[[v34-6-10]]

^<<v34-6-10,10>>^ Tendo sabido Daniel que havia sido publicada esta lei, entrou em casa e, abrindo as janelas da sua câmara superior, voltadas para o lado de Jerusalém, cada dia a três horas diferentes, punha-se de joelhos, orava a Deus e rendia-lhe acções de graças, como antes costumava fazer.

[[v34-6-11]]

^<<v34-6-11,11>>^ Então aqueles homens vieram todos e encontraram Daniel orando e fazendo súplicas ao seu Deus.

[[v34-6-12]]

^<<v34-6-12,12>>^ Indo ter com o rei, falaram-lhe acerca do decreto dizendo: Ó rei, não ordenaste que, durante o espaço de trinta dias, todo o homem que fizesse oração a qualquer dos deuses ou dos homens, que não fosses tu, ó rei fosse lançado na cova dos leões? O rei, respondendo-lhes disse: O que vós dizeis é verdade, segundo a lei dos Medos e dos Persas, que é irrevogável.

[[v34-6-13]]

^<<v34-6-13,13>>^ Então, tornando eles disseram ao rei: Pois Daniel, um dos cativos dos filhos de Judá, não fez caso de ti, ó rei, nem da proibição que assinaste antes faz a sua oração três vezes ao dia.

[[v34-6-14]]

^<<v34-6-14,14>>^ Quando o rei ouviu estas palavras, ficou muito desgostoso e resolveu em seu coração salvar Daniel, e até ao pôr do sol esforçou-se por salvá-lo.

[[v34-6-15]]

^<<v34-6-15,15>>^ Mas aqueles homens, voltando todos pressurosos ao rei disseram-lhe: Sabe, ó rei, que, segundo a lei dos Medos e dos Persas, é imutável todo o decreto que o rei passar.

[[v34-6-16]]

^<<v34-6-16,16>>^ Então o rei deu ordem de levar Daniel e de o deitar na cova dos leões. E o rei disse a Daniel: O teu Deus, que incessantemente serves, livrar-te-á.

[[v34-6-17]]

^<<v34-6-17,17>>^ Ao mesmo tempo levaram uma pedra e puseram-na sobre a boca da cova, a qual o rei selou com o seu anel e com o anel dos grandes da sua corte, para que se não modificasse a situação de Daniel. (ver nota)

[[v34-6-18]]

^<<v34-6-18,18>>^ O rei voltou para o seu palácio e deitou-se sem ter ceado, nem deixou que lhe trouxessem mulheres; além disso, não pôde conciliar o sono.

[[v34-6-19]]

^<<v34-6-19,19>>^ Ao outro dia, levantando-se o rei logo ao romper da manhã, foi a toda a pressa à cova dos leões;

[[v34-6-20]]

^<<v34-6-20,20>>^ aproximando-se da cova, chamou por Daniel com voz angustiada, dizendo: Daniel, servo do Deus vivo, o teu Deus, a quem tu incessantemente serves, pôde livrar-te dos leões?

[[v34-6-21]]

^<<v34-6-21,21>>^ Daniel, respondendo ao rei, disse: ó rei, vive eternamente!

[[v34-6-22]]

^<<v34-6-22,22>>^ O meu Deus enviou o seu anjo e fechou a boca aos leões, que não me fizeram mal algum, porque foi achada em mim justiça diante dele; e também diante de ti, ó rei, não cometi delito algum.

[[v34-6-23]]

^<<v34-6-23,23>>^ Então o rei ficou sobremaneira cheio de alegria e mandou que Daniel fosse tirado da cova. Daniel foi tirado da cova, e não se encontrou nele lesão alguma, porque creu no seu Deus.

[[v34-6-24]]

^<<v34-6-24,24>>^ Por ordem do rei, foram trazidos aqueles homens, que tinham acusado Daniel, e lançados na cova dos leões, com as suas mulheres e os seus filhos. Ainda não tinham bem chegado ao fundo da cova, quando os leões os apanharam e lhes despedaçaram todos os ossos.

[[v34-6-25]]

^<<v34-6-25,25>>^ Então o rei Dario escreveu a todos os povos, nações e línguas, que habitavam sobre toda a terra: Muita paz sobre vós!

[[v34-6-26]]

^<<v34-6-26,26>>^ Decreto que em todo o meu reino se respeite e tema o Deus de Daniel, porque ele é o Deus vivo que vive por todos os séculos; o seu reino não será destruído e o seu império não terá fim,

[[v34-6-27]]

^<<v34-6-27,27>>^ Ele é o libertador e o salvador, que faz sinais e maravilhas no céu e na terra; ele livrou Daniel da cova dos leões.

[[v34-6-28]]

^<<v34-6-28,28>>^ E Daniel prosperou sempre durante o reinado de Dario e o reinado de Ciro o Persa.

'''

xref:034-daniel/034-daniel-005.adoc#v34-5-0[&#60; Capítulo Anterior] | <<v34-6-0,Topo>> | xref:034-daniel/034-daniel-007.adoc#v34-7-0[Próximo Capítulo &#62;]