include::./index.adoc[]

[[v34-3-0]]
=== Daniel, 3
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 3 do livro de Daniel narra a história dos três jovens hebreus, Sadraque, Mesaque e Abednego, que se recusaram a adorar a estátua de ouro feita pelo rei Nabucodonosor. Eles foram jogados na fornalha ardente, mas foram protegidos por Deus e saíram ilesos. Abaixo estão cinco versículos relacionados aos temas abordados nesse capítulo:
* Isaías 43:2: "Quando você atravessar as águas, eu estarei com você; quando você atravessar os rios, eles não o encobrirão. Quando você andar através do fogo, você não se queimará; as chamas não o deixarão em brasas." Este versículo fala da presença de Deus com aqueles que confiam Nele em meio às dificuldades e adversidades, o que é exemplificado na história dos três jovens hebreus na fornalha.
* 1 Coríntios 10:13: "Nenhuma tentação os assolou, exceto a que é comum aos homens. E Deus é fiel; ele não permitirá que vocês sejam tentados além do que podem suportar. Mas, quando forem tentados, ele lhes providenciará um escape, para que possam suportá-la." Este versículo fala da fidelidade de Deus em nos ajudar a suportar as tentações, e os três jovens hebreus são um exemplo de como Deus pode nos ajudar a resistir a pressão para ceder à idolatria.
* Êxodo 20:3: "Não terás outros deuses diante de mim." Este versículo é o primeiro dos Dez Mandamentos e aborda o tema da adoração a Deus exclusivamente. É um princípio que os três jovens hebreus seguiram, mesmo diante da ameaça de morte, e nos desafia a fazer o mesmo em nossas vidas.
* Atos 5:29: "Pedro e os outros apóstolos responderam: ‘Devemos obedecer a Deus como governante antes que aos homens." Este versículo é parte da resposta de Pedro e dos apóstolos às autoridades que tentaram impedir sua pregação. É um exemplo de como devemos escolher obedecer a Deus, mesmo que isso signifique desobedecer às autoridades humanas.
* 2 Timóteo 1:7: "Pois Deus não nos deu espírito de covardia, mas de poder, amor e autocontrole." Este versículo fala do poder que Deus nos dá para resistir ao medo e à pressão de conformidade com as expectativas da sociedade. Os três jovens hebreus demonstraram esse poder ao resistir à ordem do rei Nabucodonosor de adorar a estátua de ouro.
****

[[v34-3-1]]

^<<v34-3-1,1>>^ Fez o rei Nabucodonosor uma estátua de ouro, de sessenta côvados de alto e seis de largo, e pô-la na planície de Dura, na província de Babilónia.

[[v34-3-2]]

^<<v34-3-2,2>>^ Em seguida o rei Nabucodonosor mandou juntar os sátrapas, os prefeitos, os governadores, os conselheiros, os tesoureiros, os legistas, os juizes e todas as autoridades, das províncias, para que assitissem à dedicação da estátua, que o rei Nabucodonosor tinha levantado.

[[v34-3-3]]

^<<v34-3-3,3>>^ Juntaram-se, pois, os prefeitos, os governadores, os conselheiros, os tesoureiros, os legistas, os juizes e todas as autoridades das províncias, para assistirem à dedicação da estátua que o rei Nabucodonosor tinha levantado. Estavam em pé diante da estátua que o rei Nabucodonosor tinha levantado.

[[v34-3-4]]

^<<v34-3-4,4>>^ Um pregoeiro clamou com vigor: A vós, povos, nações e (gente de todas as) línguas, se vos ordena;

[[v34-3-5]]

^<<v34-3-5,5>>^ No momento em que ouvirdes o som da trombeta. da flauta, da citara, da harpa, do saltério, da cornamusa e de todo o géuero de instrumentos músicos; prostrando-vos em terra, adorareis a estátua de ouro que o rei Nabucodonosor levantou.

[[v34-3-6]]

^<<v34-3-6,6>>^ Se alguém não a adorar prostrado, será no mesmo, instante lançado numa fornalha incandescente.

[[v34-3-7]]

^<<v34-3-7,7>>^ Portanto, logo que os povos ouviram o som da trombeta, da flauta, da citara, da arpa, do saltério, da cornamusa e de todo o gênero de instrumentos músicos, prostraram-se em terra todos os povos, nações e (gentes de todas as) línguas, adorando a estátua de ouro, que o rei Nabucodonosor tinha levantado.

[[v34-3-8]]

^<<v34-3-8,8>>^ No mesmo momento, aproximando-se uns homens Caldeus, acusaram os Judeus.

[[v34-3-9]]

^<<v34-3-9,9>>^ Disseram ao rei Nabucodonosor: Ó rei vive eternamente!

[[v34-3-10]]

^<<v34-3-10,10>>^ Tu ó rei, decretaste que todo o homem que ouvisse o som da trombeta, da flauta, da citara, da harpa, do saltério, da cornamusa e de todo o gênero de instrumentos músicos, se prostrasse em terra e adorasse a estátua de ouro,

[[v34-3-11]]

^<<v34-3-11,11>>^ e que, se alguém não a adorasse, prostrado, seria lançado numa fornalha incandescente.

[[v34-3-12]]

^<<v34-3-12,12>>^ Não obstante isto, há (três) homens Judeus, que constituíste superintendentes dos negócios da província de Babilônia, Sidrac, Jlisac e Abdenago, os quais desprezaram, ó rei, o teu decreto; não honram os teus deuses, nem adoram a estátua de ouro que levantaste. (ver nota)

[[v34-3-13]]

^<<v34-3-13,13>>^ Então Nabucodonosor cheio de furor e de ira, ordenou que trouxessem à sua presença Sidrac, Misac e Abdenago, que foram logo conduzidos à presença do rei.

[[v34-3-14]]

^<<v34-3-14,14>>^ E o rei Nabucodonosor, tomando a palavra disse-lhes: É verdade, Sidrac, Misac e Abdenago, que não honrais os meus deuses e não adorais a estátua de ouro que erigi?

[[v34-3-15]]

^<<v34-3-15,15>>^ Agora estais prontos (a obedecer-me) no momento em que ouvirdes o som da trombeta, da flauta, da citara, da harpa, do saltério, da cornamusa e de todo o gênero de instrumentos músicos, a prostrar-vos em terra e adorar a estátua que fiz? Se a não adorardes, no mesmo instante sereis lançados numa fornalha incandescente. E qual é o Deus que vos poderá livrar da minha mão?

[[v34-3-16]]

^<<v34-3-16,16>>^ Respondendo, Sidrac, Misac e Abdenago disseram ao rei Nabucodonosor: Não há necessidade alguma de que te respondamos sobre isto,

[[v34-3-17]]

^<<v34-3-17,17>>^ porque o nosso Deus, a quem adoramos, pode tirar-nos da fornalha de fogo ardente e livrar-nos ó rei, das tuas mãos.

[[v34-3-18]]

^<<v34-3-18,18>>^ Porém, se ele o não quiser fazer assim, fica sabendo, ó rei, que nós não honraremos os teus deuses, nem adoraremos a estátua de ouro que erigiste.

[[v34-3-19]]

^<<v34-3-19,19>>^ A estas palavras, encheu-se Nabucodonosor de furor, e mudou-se o seu semblante contra Sidrac, Misac e Abdenago. Mandou que se acendesse a fornalha com um fogo sete vezes mais ardente do que se costumava acender.

[[v34-3-20]]

^<<v34-3-20,20>>^ Ordenou (então) a valentes soldados do seu exército que, ligados os pés a Sidrac, Misac, e Abdenago, os lançassem na fornalha incandescente.

[[v34-3-21]]

^<<v34-3-21,21>>^ Imediatamente foram aqueles (três) homens ligados e lançados no meio da fornalha de fogo ardente, com as suas roupas, tiaras, sapatos e vestidos.

[[v34-3-22]]

^<<v34-3-22,22>>^ Porque o mandado do rei era urgente e a fornalha estava extraordinariamente aquecida, as chamas do fogo mataram aqueles homens que tinham lançado nelas a Sidrac, Misac e Abdenago.

[[v34-3-23]]

^<<v34-3-23,23>>^ Entretanto estes três homens, Sidrac. Misac e Abdenago caíram ligados no meio da fornalha de fogo ardente.

[[v34-3-24]]

^<<v34-3-24,24>>^ Ora eles passeavam pelo meio das chamas, louvando a Deus e bem-dizendo ao Senhor. (ver nota)

[[v34-3-25]]

^<<v34-3-25,25>>^ Azarias de pé, abrindo a sua boca no meio do fogo, orou, dizendo assim:

[[v34-3-26]]

^<<v34-3-26,26>>^ Bem-dito sejas Senhor Deus de nossos pais! Seja o teu nome louvado e glorificado por todos os séculos

[[v34-3-27]]

^<<v34-3-27,27>>^ Porque tu és justo em todas as coisas que fizeste, e todas as tuas obras são verdadeiras, e os teus caminhos rectos, e todos os teus juízos a verdade.

[[v34-3-28]]

^<<v34-3-28,28>>^ Porque exerceste justos juízos em todas as coisas (más) que fizeste vir sobre nós e sobre Jerusalém, cidade santa de nossos pais; mandaste-nos todos estes castigos em verdade e justiça, por causa dos nossos pecados.

[[v34-3-29]]

^<<v34-3-29,29>>^ Pecámos e procedemos iniquamente, retirando-nos de ti, em todas as coisas temos delinquido;

[[v34-3-30]]

^<<v34-3-30,30>>^ não atendemos aos teus preceitos, não os observámos, não os praticámos, como nos tinhas ordenado, para que fôssemos, felizes.

[[v34-3-31]]

^<<v34-3-31,31>>^ Todos os castigos pois, que fizeste vir sobre nos, todos os males que nos tens feito padecer, tudo com verdadeira justiça o tens feito.

[[v34-3-32]]

^<<v34-3-32,32>>^ Entregaste-nos nas mãos de nossos inimigos iníquos, de ímpios odiosos, e a um rei injusto, o pior que há em toda a terra.

[[v34-3-33]]

^<<v34-3-33,33>>^ Agora nem sequer ousamos abrir a boca; a confusão e o opróbrio acabrunham teus servos e todos os que te adoram.

[[v34-3-34]]

^<<v34-3-34,34>>^ Não nos abandones para sempre, por amor do teu nome, não destruas a tua aliança (com Israel);

[[v34-3-35]]

^<<v34-3-35,35>>^ não retires de nós a tua misericórdia, por amor de Abraão, teu amado, de Isaac, teu servo, de Israel, teu santo,

[[v34-3-36]]

^<<v34-3-36,36>>^ aos quais prometeste multiplicar a sua descendência como as estrelas do céu e como a areia que está nas praias do mar.

[[v34-3-37]]

^<<v34-3-37,37>>^ Senhor, estamos reduzidos a um número mais pequeno que todas as outras nações, encontramo-nos hoje humilhados em toda a terra, por causa dos nossos pecados.

[[v34-3-38]]

^<<v34-3-38,38>>^ Já não há príncipe, nem chefe, nem profeta, nem holocausto, nem sacrifício, nem oblação, nem incenso, nem lugar em que te possamos oferecer as nossas primícias

[[v34-3-39]]

^<<v34-3-39,39>>^ e obter a tua misericórdia. Porém, de coração contrito e espírito humilhado, sejamos recebidos por ti,

[[v34-3-40]]

^<<v34-3-40,40>>^ como se trouxéssemos holocaustos de carneiros e de touros, como se te oferecêssemos milhares de cordeiros gordos; seja assim (aceite) o nosso sacrifício, hoje, diante de ti, seja (considerado) perfeito, porque jamais são confundidos aqueles que em ti confiam.

[[v34-3-41]]

^<<v34-3-41,41>>^ Agora seguimos-te de todo o coração, tememos-te e buscamos a tua face.

[[v34-3-42]]

^<<v34-3-42,42>>^ Não nos confundas, mas trata-nos segundo a tua mansidão, segundo a abundância das tuas misericórdias.

[[v34-3-43]]

^<<v34-3-43,43>>^ Livra-nos, por meio das maravilhas do teu poder, e glorifica, Senhor, o teu nome.

[[v34-3-44]]

^<<v34-3-44,44>>^ Sejam confundidos todos aqueles que fazem sofrer tribulações aos teus servos, sejam confundidos pela perda de todo o seu poder, e seja quebrada a sua força;

[[v34-3-45]]

^<<v34-3-45,45>>^ saibam que só tu és Deus e Senhor, que enches de glória toda a terra.

[[v34-3-46]]

^<<v34-3-46,46>>^ Entretanto os servos do rei, que os tinham lançado no fogo, não cessavam de alimentar a fornalha com nafta, estopa, pez e sarmentos.

[[v34-3-47]]

^<<v34-3-47,47>>^ A labareda, que se levantava quarenta e nove côvados acima da fornalha,

[[v34-3-48]]

^<<v34-3-48,48>>^ inclinando-se abrasou os Caldeus que encontrou próximo da fornalha.

[[v34-3-49]]

^<<v34-3-49,49>>^ Mas o anjo do Senhor desceu para junto de Azarias e seus companheiros, à fornalha, e desviou da fornalha a chama do fogo,

[[v34-3-50]]

^<<v34-3-50,50>>^ fez que soprasse no meio da fornalha uma espécie de fresca viração acompánhada de orvalho, de forma que o fogo não os tocou de modo algum, não os atormentou, nem lhes causou moléstia.

[[v34-3-51]]

^<<v34-3-51,51>>^ Então aqueles três (jovens), como por uma só boca, louvavam a Deus na fornalha, glorificavam-no nestes termos;

[[v34-3-52]]

^<<v34-3-52,52>>^ Tu és bem-dito, Senhor Deus de nossos pais, digno de ser louvado e exaltado para sempre. Bem-dito é o teu nome santo e glorioso, digno de todo o louvor e exaltação para sempre.

[[v34-3-53]]

^<<v34-3-53,53>>^ Tu és bem-dito no templo da tua sauta glória, digno do máximo louvor e exaltação, por todos os séculos.

[[v34-3-54]]

^<<v34-3-54,54>>^ Tu és bem-dito sobre o trono do teu reino, digno do máximo louvor e exaltação, por todos os séculos.

[[v34-3-55]]

^<<v34-3-55,55>>^ Tu és bem-dito, tu que penetras o fundo dos abismos e estás assentado sobre os Querubins, digno do máximo louvor e glória, por todos os séculos.

[[v34-3-56]]

^<<v34-3-56,56>>^ Tu és bem-dito no firmamento do céu.e digno de louvor e de glória, por todos os séculos.

[[v34-3-57]]

^<<v34-3-57,57>>^ Obras do Senhor, bem-dizei todas o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-58]]

^<<v34-3-58,58>>^ Anjos do Senhor, bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-59]]

^<<v34-3-59,59>>^ Céus, bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-60]]

^<<v34-3-60,60>>^ Águas que estais por cima dos céus, bem-dizei todas o Senhor. louvai-o e exaltai-o por todos os séculos.

[[v34-3-61]]

^<<v34-3-61,61>>^ Forças do Senhor, bem-dizei todas o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-62]]

^<<v34-3-62,62>>^ Sol e lua, bem-dizei o Senhor.louvai-o e exaltai-o por todos os séculos.

[[v34-3-63]]

^<<v34-3-63,63>>^ Astros do céu, bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-64]]

^<<v34-3-64,64>>^ Chuvas e orvalhos- bem-dizei todos o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-65]]

^<<v34-3-65,65>>^ Ventos, bem-dizei todos o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-66]]

^<<v34-3-66,66>>^ Fogos e calores, bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-67]]

^<<v34-3-67,67>>^ Frios e ardor, bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-68]]

^<<v34-3-68,68>>^ Orvalhos e geadas, bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-69]]

^<<v34-3-69,69>>^ Gelos e frialdade, bem:dizei o Senhor. louvai-o e exaltai-o por todos os séculos.

[[v34-3-70]]

^<<v34-3-70,70>>^ Gelos e neves, bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-71]]

^<<v34-3-71,71>>^ Noites e dias, bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-72]]

^<<v34-3-72,72>>^ Luz e trevas, bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-73]]

^<<v34-3-73,73>>^ Relâmpagos e nuvens, bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-74]]

^<<v34-3-74,74>>^ Que a terra bem-diga o Senhor que o louve e exalte por todos os séculos.

[[v34-3-75]]

^<<v34-3-75,75>>^ Montanhas e colinas, bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-76]]

^<<v34-3-76,76>>^ Plantas que brotais da terra, bem-dizei todas o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-77]]

^<<v34-3-77,77>>^ Pontes, bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-78]]

^<<v34-3-78,78>>^ Mares e rios, bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-79]]

^<<v34-3-79,79>>^ Monstros e tudo o que se move nas águas, bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-80]]

^<<v34-3-80,80>>^ Aves do céu, bem-dizei todas o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-81]]

^<<v34-3-81,81>>^ Animais selvagens e rebanhos, bem-dizei o Senhor.louvai-o e exaltai-o por todos os séculos.

[[v34-3-82]]

^<<v34-3-82,82>>^ Filhos dos homens, bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-83]]

^<<v34-3-83,83>>^ Bem-diga Israel o Senhor, louve-o e exalte-o por todos os séculos.

[[v34-3-84]]

^<<v34-3-84,84>>^ Sacerdotes do Senhor, bem-dizei o Senhor, louvai-o e exaltaí-o por todos os séculos.

[[v34-3-85]]

^<<v34-3-85,85>>^ Servos do Senhor, bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-86]]

^<<v34-3-86,86>>^ Espíritos e almas dos justos, bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-87]]

^<<v34-3-87,87>>^ Santos e humildes do coração bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos.

[[v34-3-88]]

^<<v34-3-88,88>>^ Ananias, Azarias e Misael, bem-dizei o Senhor, louvai-o e exaltai-o por todos os séculos; porque ele nos tirou da morada dos mortos, salvou-nos da mão da morte, livrou-nos do meio das chamas ardentes, tirou-nos do meio do fogo.

[[v34-3-89]]

^<<v34-3-89,89>>^ Dai graças ao Senhor, porque ele é bom, porque a sua misericórdia é eterna.

[[v34-3-90]]

^<<v34-3-90,90>>^ Vós todos que adorais o Senhor, bem-dizei o Deus dos deuses, louvai-o e rendei-lhe acções de graças.porque a sua misericórdia permanece por todos os séculos.

[[v34-3-91]]

^<<v34-3-91,91>>^ Então o rei Nabucodonosor ficou estupefacto: levantou-se de repente e disse para os seus conselheiros: Não lançámos nós no meio do fogo três homens atados? Eles, respondendo ao rei, disseram: Assim é, ó rei. (ver nota)

[[v34-3-92]]

^<<v34-3-92,92>>^ Ao que ele replicou: Contudo eu vejo quatro homens soltos, passeando no meio do fogo, sem sofrer mal algum; o aspecto do quarto é semelhante ao dum filho dos deuses.

[[v34-3-93]]

^<<v34-3-93,93>>^ Então Nabucodonosor aproximou-se da porta da fornalha incandescente e disse; Sidrac, Misac e Abdenago, servos do Deus Altíssimo, saí e vinde. E logo Sidrac, Misac e Abdenago saíram do meio do fogo.

[[v34-3-94]]

^<<v34-3-94,94>>^ Reunidos os sátrapas, os prefeitos, os governadores e os conselheiros do rei, olharam para aqueles homens e viram que o fogo não tinha tido poder algum sobre os seus corpos, que nem um só cabelo da sua cabeça se tinha queimado, que as suas roupas estavam intactas e que nem sequer cheiravam a chamusco.

[[v34-3-95]]

^<<v34-3-95,95>>^ Então Nabucodonosor exclamou: Bem-dito seja o Deus de Sidrac, Misac e Abdenago, que enviou o seu anjo e livrou os seus servos, que creram nele e que resistindo ao mandamento do rei, entregaram os seus corpos para não servirem e não adorarem a nenhum outro deus, além do seu Deus.

[[v34-3-96]]

^<<v34-3-96,96>>^ Decreto, pois, o seguinte: Todo o homem de qualquer povo, nação ou língua, que disser algum mal contra o Deus de Sidrac de Misac e de Abdenago, será feito em pedaços, e a sua casa destruída, porque não há outro Deus, que assim possa salvar, senão este.

[[v34-3-97]]

^<<v34-3-97,97>>^ Então o rei elevou em dignidade a Sidrac, Misac e Abdenago, na província de Babilónia.

[[v34-3-98]]

^<<v34-3-98,98>>^ O rei Nabucodonosor a todos os povos, nações e línguas que habitam sobre toda a terra: A paz seja em vós abundante.

[[v34-3-99]]

^<<v34-3-99,99>>^ Aprouve-me dar a conhecer os sinais e maravilhas que o Deus Altíssimo operou em meu favor.

[[v34-3-100]]

^<<v34-3-100,100>>^ Quão grandes os seus sinais, quão poderosas as suas maravilhas. O seu reino é um reino eterno, e o seu império estende-se de geração em geração.

'''

xref:034-daniel/034-daniel-002.adoc#v34-2-0[&#60; Capítulo Anterior] | <<v34-3-0,Topo>> | xref:034-daniel/034-daniel-004.adoc#v34-4-0[Próximo Capítulo &#62;]