include::./index.adoc[]

[[v1-10-0]]
=== Gênesis, 10
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Gênesis 10 é conhecido como a "Tabela das Nações", pois apresenta a genealogia dos filhos de Noé e suas respectivas nações. O capítulo também descreve a distribuição geográfica dessas nações.
* 1 Crônicas 1:5 - "Os filhos de Jafé: Gomer, Magogue, Madai, Javã, Tubal, Meseque e Tiras." Este versículo se relaciona com Gênesis 10 porque Jafé é um dos filhos de Noé e sua descendência é listada na tabela das nações.
* Isaías 11:10 - "Naquele dia a raiz de Jessé surgirá como estandarte dos povos; as nações se voltarão para ele, e o lugar de descanso dele será glorioso." Este versículo se relaciona com Gênesis 10 porque descreve a esperança de que todas as nações, incluindo as que foram listadas na tabela das nações, se voltarão para o Messias.
* Atos dos Apóstolos 2:9-11 - "Partos, medos, elamitas; habitantes da Mesopotâmia, Judéia e Capadócia, do Ponto e da Ásia, da Frígia e da Panfília, do Egito e das regiões da Líbia próximas a Cirene; visitantes de Roma (tanto judeus como convertidos ao judaísmo); cretenses e árabes - ouvimos estes homens falando em nossas próprias línguas sobre as maravilhas de Deus." Este versículo se relaciona com Gênesis 10 porque menciona muitos dos lugares que foram listados na tabela das nações.
* Ezequiel 27:13 - "Javã, Tubal e Meseque negociaram com você; eles trocaram escravos e objetos de bronze trabalhados por você." Este versículo se relaciona com Gênesis 10 porque menciona Javã, Tubal e Meseque, que são listados como filhos de Jafé na tabela das nações.
* Apocalipse 7:9 - "Depois disso olhei, e diante de mim estava uma grande multidão que ninguém podia contar, de todas as nações, tribos, povos e línguas, em pé diante do trono e do Cordeiro, vestidos de vestes brancas, com palmas nas mãos." Este versículo se relaciona com Gênesis 10 porque descreve uma visão futura da adoração a Deus, que incluirá pessoas de todas as nações, tribos e línguas, incluindo as que foram listadas na tabela das nações.
****

[[v1-10-1]]

^<<v1-10-1,1>>^ Eis a posteridade dois filhos de Noé: Sem, Cam e Jafeth. A estes nasceram filhos depois do dilúvio.

[[v1-10-2]]

^<<v1-10-2,2>>^ Filhos de Jafeth: Gomer, Magog, Madai, Javan, Tubal, Mosoch e Tiras.

[[v1-10-3]]

^<<v1-10-3,3>>^ Filhos de Gomer: Arcenez, Rifath e Togorma.

[[v1-10-4]]

^<<v1-10-4,4>>^ Filhos de Javan: Elisa e Tarsis, Cetim e Dodanim.

[[v1-10-5]]

^<<v1-10-5,5>>^ Destes saíram (os habitantes) das ilhas das nações nas suas (diversas) regiões, cada um segundo a sua língua, segundo as suas famílias, segundo as suas nações.

[[v1-10-6]]

^<<v1-10-6,6>>^ Filhos de Cam: Cus, Mesraim, Futh e Canaan.

[[v1-10-7]]

^<<v1-10-7,7>>^ Filhos de Cus: Saba, Hevila, Sabata, Regma e Sabataca. Filhos de Regma: Saba e Dadan.

[[v1-10-8]]

^<<v1-10-8,8>>^ Cus gerou Nemrod, o qual começou a ser poderoso na terra.

[[v1-10-9]]

^<<v1-10-9,9>>^ Era um robusto caçador diante do Senhor. Daqui veio este provérbio: Robusto caçador diante do Senhor como Nemrod.

[[v1-10-10]]

^<<v1-10-10,10>>^ O princípio do seu reino foi Babilônia, Arach, Acad e Calane, na terra de Senaar.

[[v1-10-11]]

^<<v1-10-11,11>>^ Daquela terra foi para Assur, e edificou Nínive, e Rechoboth-Ir, e Calé,

[[v1-10-12]]

^<<v1-10-12,12>>^ e também Resen, a grande cidade, entre Nínive e Calé.

[[v1-10-13]]

^<<v1-10-13,13>>^ Mesraim gerou Ludim, Anamim, Laabim, Neftuim,

[[v1-10-14]]

^<<v1-10-14,14>>^ Fretusim e Casluim, dos quais saíram os Filisteus e os Caftoreus.

[[v1-10-15]]

^<<v1-10-15,15>>^ Canaan gerou Sidónio, seu filho primogênito,

[[v1-10-16]]

^<<v1-10-16,16>>^ Hete, (sendo também o pai dos) Jebuseus, Amorreus, Gergeseus,

[[v1-10-17]]

^<<v1-10-17,17>>^ Heveus, Araceus, Sineus,

[[v1-10-18]]

^<<v1-10-18,18>>^ Aradeus, Samareus e Amateus. Depois disto, espalharam-se as famílias dos Cananeus,

[[v1-10-19]]

^<<v1-10-19,19>>^ indo os limites dos seus territórios, desde Sidónia, na direção de Gerara, até Gaza, e, na direção de Sodoma, Gomorra, Adamam e Seboim, até Lesa.

[[v1-10-20]]

^<<v1-10-20,20>>^ Estes são os filhos de Cam, segundo as suas famílias, línguas, regiões e nações.

[[v1-10-21]]

^<<v1-10-21,21>>^ De Sem, pai de todos os filhos de Heber e irmão mais velho de Jafeth, nasceram também filhos.

[[v1-10-22]]

^<<v1-10-22,22>>^ Filhos de Sem: Elam, Assur, Arfaxad, Lud e Arão.

[[v1-10-23]]

^<<v1-10-23,23>>^ Filhos de Arão: Us, Hul, Geter e Més.

[[v1-10-24]]

^<<v1-10-24,24>>^ Arfaxad gerou Salé, de quem nasceu Heber.

[[v1-10-25]]

^<<v1-10-25,25>>^ A Heber nasceram dois filhos: um chamou-se Faleg, porque em seu tempo foi dividida a terra, e seu irmão chamou-se Jectan.

[[v1-10-26]]

^<<v1-10-26,26>>^ Este Jectan gerou Elmodad, Saleph, Asarmoith, Jaré,

[[v1-10-27]]

^<<v1-10-27,27>>^ Adurão, Usai, Decla,

[[v1-10-28]]

^<<v1-10-28,28>>^ Ebal, Abimael, Saba,

[[v1-10-29]]

^<<v1-10-29,29>>^ Ofir, Hévila e Jobab; todos estes são filhos de Jectan.

[[v1-10-30]]

^<<v1-10-30,30>>^ O país onde eles habitaram estendia-se desde Messa até Sefar, monte que está ao oriente.

[[v1-10-31]]

^<<v1-10-31,31>>^ Estes são os filhos de Sem, Segundo as suas famílias, línguas, regiões e nações.

[[v1-10-32]]

^<<v1-10-32,32>>^ Estas são as familias dos filhos de Noé, segundo as suas gerações e nações. Delas saíram todos os povos da terra depois do dilúvio.

'''

xref:001-genesis/001-genesis-009.adoc#v1-9-0[&#60; Capítulo Anterior] | <<v1-10-0,Topo>> | xref:001-genesis/001-genesis-011.adoc#v1-11-0[Próximo Capítulo &#62;]