include::./index.adoc[]

[[v1-7-0]]
=== Gênesis, 7
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Gênesis 7 descreve o dilúvio global que Deus trouxe para destruir toda a vida na terra, exceto por Noé, sua família e os animais que foram levados para a arca. Aqui estão cinco versículos relacionados aos temas deste capítulo:
* Isaías 54:9: "Porque isto será para mim como as águas de Noé; pois jurei que as águas de Noé não passariam mais sobre a terra; assim jurei que não me irarei mais contra ti, nem te repreenderei." Este versículo lembra a promessa de Deus de nunca mais destruir toda a vida na terra com um dilúvio.
* Mateus 24:38-39: "Porquanto, assim como nos dias anteriores ao dilúvio, comiam, bebiam, casavam e davam-se em casamento, até o dia em que Noé entrou na arca, e não o perceberam, até que veio o dilúvio e os levou a todos; assim será também a vinda do Filho do homem." Neste versículo, Jesus compara a época anterior à sua segunda vinda com os dias de Noé antes do dilúvio.
* 2 Pedro 2:5: "E não poupou o mundo antigo, mas preservou a Noé, pregador da justiça, com mais sete pessoas, quando fez vir o dilúvio sobre o mundo de ímpios." Este versículo lembra a escolha de Deus de salvar Noé e sua família do dilúvio.
* 1 Pedro 3:20: "os quais noutro tempo foram rebeldes, quando a longanimidade de Deus esperava nos dias de Noé, enquanto se preparava a arca; na qual poucas, isto é, oito almas se salvaram através da água." Este versículo fala sobre a longanimidade de Deus durante a época de Noé e sua escolha de salvar apenas Noé e sua família.
* Gênesis 9:11: "Estabelecerei a minha aliança convosco: não será mais destruída toda a carne pelas águas do dilúvio, nem haverá mais dilúvio para destruir a terra." Este versículo marca o final do dilúvio e a promessa de Deus de nunca mais destruir a terra com um dilúvio.
****

[[v1-7-1]]

^<<v1-7-1,1>>^ E o Senhor disse-lhe: entra na arca tu e toda a tua casa, porque te reconheci justo diante de mim no meio desta geração.

[[v1-7-2]]

^<<v1-7-2,2>>^ Toma de todos os animais puros sete pares, macho e fêmea: e dos animais impuros um par, macho e fêmea.

[[v1-7-3]]

^<<v1-7-3,3>>^ Toma também das aves do céu sete pares, macho e fêmea, para se conservar a raça sobre a face de toda a terra,

[[v1-7-4]]

^<<v1-7-4,4>>^ porque, daqui a sete dias, farei chover sobre a terra, durante quarenta dias e quarenta noites, e exterminarei da superfície da terra todos seres (vivos) que fiz.

[[v1-7-5]]

^<<v1-7-5,5>>^ Fez, pois, Noé tudo o que o Senhor lhe havia ordenado.

[[v1-7-6]]

^<<v1-7-6,6>>^ Tinha seiscentos anos de idade, quando as águas do dilúvio inundaram a terra.

[[v1-7-7]]

^<<v1-7-7,7>>^ Noé entrou na arca com seus filhos, sua mulher e as mulheres de seus filhos, para se salvarem das águas do dilúvio.

[[v1-7-8]]

^<<v1-7-8,8>>^ Também dos animais puros e impuros, e das aves, e de tudo o que se move sobre a terra,

[[v1-7-9]]

^<<v1-7-9,9>>^ entraram na arca com Noé, dois a dois, macho e fêmea, conforme o Senhor tinha mandado a Noé.

[[v1-7-10]]

^<<v1-7-10,10>>^ E, passados os sete dias, cairam sobre a terra as águas do dilúvio.

[[v1-7-11]]

^<<v1-7-11,11>>^ No ano seiscentos da vida de Noé, no segundo mês, aos dezessete do mês romperam-se todas as fontes do grande abismo, abriam-se as cataratas do céu,

[[v1-7-12]]

^<<v1-7-12,12>>^ e caiu chuva sobre a terra durante quarenta dias e quarenta noites.

[[v1-7-13]]

^<<v1-7-13,13>>^ Naquele mesmo dia entrou Noé na arca com seus filhos Sem, Cam e Jafeth, sua mulher e as três mulheres de Seus filhos,

[[v1-7-14]]

^<<v1-7-14,14>>^ e com eles entraram todos os animais (selváticos), segundo a sua espécie, todos os animais (domésticos). Segundo a sua espécie, tudo o que rasteja Sobre a terra, segundo a sua espécie, tudo o que voa, segundo a sua espécie, todas as aves, e tudo o que tem asas;

[[v1-7-15]]

^<<v1-7-15,15>>^ (todos estes animais), entraram com Noé na arca, dois a dois, de toda a espécie, em que havia sopro de vida.

[[v1-7-16]]

^<<v1-7-16,16>>^ Os que entraram eram macho e fêmea de toda a espécie, conforme Deus tinha mandado a Noé; e o Senhor aí o fechou por fora.

[[v1-7-17]]

^<<v1-7-17,17>>^ Veio o dilúvio sobre a terra durante quarenta dias, e as águas cresceram e elevaram a arca muito alto por cima da terra.

[[v1-7-18]]

^<<v1-7-18,18>>^ Inundaram tudo com violência e cobriram tudo na superfície da terra; a arca, porém, era levada sobre as águas.

[[v1-7-19]]

^<<v1-7-19,19>>^ Tanto cresceram as águas que todos os mais elevados montes, que há sob todo o Céu, ficaram cobertos.

[[v1-7-20]]

^<<v1-7-20,20>>^ A água elevou-se quinze côvados acima delas,

[[v1-7-21]]

^<<v1-7-21,21>>^ Toda a carne que se movia sobre a terra pereceu: as aves, os animais domesticados, as feras e todos os répteis que andam de rastos sobre a terra, e todos os homens.

[[v1-7-22]]

^<<v1-7-22,22>>^ Tudo o que respira e tem vida sobre a terra, tudo morreu.

[[v1-7-23]]

^<<v1-7-23,23>>^ Foram exterminados todos os sereis (vivos) que havia sobre a terra, desde o homem até às bestas, tanto os répteis como as aves do céu, tudo foi exterminado da terra: ficou somente Noé, e os que estavam com ele na arca.

[[v1-7-24]]

^<<v1-7-24,24>>^ As águas cobriram a terra durante cento e cinquenta dias.

'''

xref:001-genesis/001-genesis-006.adoc#v1-6-0[&#60; Capítulo Anterior] | <<v1-7-0,Topo>> | xref:001-genesis/001-genesis-008.adoc#v1-8-0[Próximo Capítulo &#62;]