include::./index.adoc[]

[[v1-9-0]]
=== Gênesis, 9
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 9 de Gênesis descreve a aliança de Deus com Noé e seus filhos após o dilúvio, incluindo a proibição do assassinato e o estabelecimento do arco-íris como um sinal do pacto. Abaixo estão cinco versículos relacionados com os temas abordados nesse capítulo:
* Gênesis 9:5-6: "Certamente pedirei contas do sangue de vocês. Pedirei contas a todos os animais e a cada ser humano; pedirei contas da vida do homem por parte do seu semelhante. Quem derramar o sangue do homem, pelo homem o seu sangue será derramado; porque à imagem de Deus foi o homem criado." Este versículo estabelece a proibição do assassinato e a importância da vida humana como um reflexo da imagem de Deus.
* Gênesis 9:11-13: "Eu estabeleço a minha aliança com vocês: Nunca mais serão mortas todas as criaturas pelos dilúvios, nem haverá outro dilúvio para destruir a terra. E Deus disse: Este é o sinal da aliança que estou estabelecendo entre mim e vocês e todos os seres vivos que estão com vocês, por todas as gerações futuras." Este versículo apresenta a aliança de Deus com Noé e seus filhos após o dilúvio, incluindo o sinal do arco-íris.
* Gênesis 9:7: "E vocês, sejam férteis e multipliquem-se; espalhem-se pela terra e proliferem nela." Este versículo reitera a importância da multiplicação e da propagação da humanidade após o dilúvio.
* Gênesis 9:20-21: "Noé, que era agricultor, foi o primeiro a plantar uma vinha. Bebeu do vinho, embriagou-se e ficou nu dentro da sua tenda." Este versículo descreve a embriaguez de Noé após o dilúvio e as consequências que isso teve em sua família.
* Gênesis 9:25-27: "Disse então: 'Maldito seja Canaã! Escravo dos escravos será para seus irmãos'. E acrescentou: 'Bendito seja o Senhor, o Deus de Sem! Que Canaã seja seu escravo. Que Deus amplie o território de Jafé; habite ele nas tendas de Sem, e Canaã seja seu escravo'." Este versículo descreve a maldição e a bênção de Noé para seus filhos, que tiveram consequências significativas na história posterior da humanidade.
****

[[v1-9-1]]

^<<v1-9-1,1>>^ Deus abençoou Noé e seus filhos, e disse-lhes: crescei e multiplicai-vos, e enchei a terra.

[[v1-9-2]]

^<<v1-9-2,2>>^ Temam e tremam na vossa presença todos os animais da terra, todas as aves do céu, tudo o que se move sobre a terra e todos os peixes do mar: todos ficam sujeitos ao vosso poder.

[[v1-9-3]]

^<<v1-9-3,3>>^ Tudo o que Se move e vive será vosso alimento: eu vos dou todas estas coisas, como (vos dei) os legumes verdes.

[[v1-9-4]]

^<<v1-9-4,4>>^ Sòmente não comereis carne com sangue, (ver nota)

[[v1-9-5]]

^<<v1-9-5,5>>^ porque eu vingarei o vosso sangue da mão de todos os animais (que o derramarem); e ao homem que matar seu irmão, pedirei contas da vida deste homem.

[[v1-9-6]]

^<<v1-9-6,6>>^ Todo o que derramar o sangue humano, (será castigado) com a efusão do seu próprio sangue, porque o homem foi feito à imagem de Deus.

[[v1-9-7]]

^<<v1-9-7,7>>^ Crescei, pois, e multiplicai-vos, espalhai-vos sobre a terra e enchá-a.

[[v1-9-8]]

^<<v1-9-8,8>>^ Disse também Deus a Noé e a seus filhos com ele:

[[v1-9-9]]

^<<v1-9-9,9>>^ eis que vou fazer a minha aliança convosco, com a vossa posteridade,

[[v1-9-10]]

^<<v1-9-10,10>>^ e com todos os seres viventes que estão convosco, tanto aves, como animais domésticos e selváticos, que saíram da arca.

[[v1-9-11]]

^<<v1-9-11,11>>^ Farei a minha aliança convosco, e não tornará mais a perecer nenhuma criatura pelas águas do dilúvio, nem haverá mais para o futuro dilúvio que assole a terra.

[[v1-9-12]]

^<<v1-9-12,12>>^ E Deus disse: eis o Sinal de aliança, que faço convosco e com todos os animais viventes, que estão convosco, por todas as gerações futuras:

[[v1-9-13]]

^<<v1-9-13,13>>^ porei o meu arco nas nuvens, e ele será o sinal da aliança entre mim e a terra. (ver nota)

[[v1-9-14]]

^<<v1-9-14,14>>^ Quando eu cobrir o céu de nuvens, o meu arco aparecerá nas nuvens,

[[v1-9-15]]

^<<v1-9-15,15>>^ e me lembrarei da minha aliança convosco e com todos os seres vivos da terra, e não voltarão as águas do dilúvio a exterminar toda a carne (que vive).

[[v1-9-16]]

^<<v1-9-16,16>>^ O arco estará nas nuvens, eu o verei e me lembrarei da aliança eterna que foi feita entre Deus e todas as almas viventes e toda a carne que existe sobre a terra.

[[v1-9-17]]

^<<v1-9-17,17>>^ E Deus disse a Noé: este será o sinal da aliança que eu constituí entre mim e toda a carne (que vive) sobre a terra.

[[v1-9-18]]

^<<v1-9-18,18>>^ Ora os filhos de Noé, que saíram da arca, eram Sem, Cam e Jafeth. Cam é o pai de Canaan.

[[v1-9-19]]

^<<v1-9-19,19>>^ Estes são os três filhos de Noé, e por eles se propagou todo o género humano sobre toda a terra.

[[v1-9-20]]

^<<v1-9-20,20>>^ Noé, que era agricultor, começou a cultivar a terra e plantou vinha.

[[v1-9-21]]

^<<v1-9-21,21>>^ Tendo bebido vinho, embriagou-se e apareceu nu na sua tenda.

[[v1-9-22]]

^<<v1-9-22,22>>^ Cam, pai de Canaan, tendo visto a nudez de seu pai, saiu fora a dizê-lo a seus dois irmãos.

[[v1-9-23]]

^<<v1-9-23,23>>^ Porém Sem e Jafeth puseram uma capa sobre os seus ombros, e, andando para trás, cobriram a nudez de seu pai: assim, tendo o rosto voltado, não viram a sua nudez.

[[v1-9-24]]

^<<v1-9-24,24>>^ Quando Noé, despertando da embriaguez, soube o que lhe tinha feito o seu filho mais novo, disse:

[[v1-9-25]]

^<<v1-9-25,25>>^ maldito seja Canaan! Ele será o servo dos servos de seus irmãos.

[[v1-9-26]]

^<<v1-9-26,26>>^ Depois disse: Bendito seja o Senhor Deus de Sem, e Canaan seja seu escravo.

[[v1-9-27]]

^<<v1-9-27,27>>^ Dilate Deus a Jafeth, e habite Jafeth nas tendas de Sem, e Canaan seja seu escravo.

[[v1-9-28]]

^<<v1-9-28,28>>^ Ora Noé viveu ainda depois do dilúvio trezentos e cinquenta anos.

[[v1-9-29]]

^<<v1-9-29,29>>^ Todo o tempo da sua vida foi de novecentos e cinquenta anos, e morreu.

'''

xref:001-genesis/001-genesis-008.adoc#v1-8-0[&#60; Capítulo Anterior] | <<v1-9-0,Topo>> | xref:001-genesis/001-genesis-010.adoc#v1-10-0[Próximo Capítulo &#62;]