include::./index.adoc[]

[[v1-38-0]]
=== Gênesis, 38
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Gênesis 38 é um capítulo que narra a história de Judá, filho de Jacó, e sua relação com Tamar, a esposa de seu filho. O capítulo aborda temas como traição, prostituição e justiça. Abaixo estão cinco versículos relacionados a esses temas:
* Deuteronômio 22:22 - "Se for apanhado em flagrante o homem que estiver com uma mulher casada com outro homem, ambos deverão morrer, o homem que se deitou com a mulher e a mulher também. Assim vocês eliminarão o mal de Israel." O adultério é um tema recorrente em Gênesis 38 e é considerado um pecado grave na lei de Moisés.
* Provérbios 6:32 - "O que comete adultério não tem juízo; quem assim procede a si mesmo se destrói." Esse versículo destaca as consequências graves da prática do adultério, que incluem não apenas punições legais, mas também a destruição pessoal.
* Tiago 4:4 - "Adúlteros, vocês não sabem que a amizade com o mundo é inimizade com Deus? Quem quer ser amigo do mundo faz-se inimigo de Deus." Tiago reforça a gravidade do pecado do adultério e enfatiza que aqueles que se envolvem em práticas imorais estão se afastando de Deus.
* Ezequiel 18:20 - "O filho não pagará pelos pecados do pai, e o pai não pagará pelos pecados do filho. A justiça do justo lhe será creditada, e a impiedade do ímpio lhe será cobrada." Esse versículo destaca a importância da justiça e da responsabilidade individual pelos pecados cometidos, que é um tema importante em Gênesis 38.
* 1 Coríntios 6:18 - "Fujam da imoralidade sexual. Todos os outros pecados que alguém cometer são fora do corpo; mas quem peca sexualmente, peca contra o seu próprio corpo." Paulo adverte contra a imoralidade sexual e enfatiza que, além das consequências legais e espirituais, essa prática pode ter efeitos negativos na saúde física e mental da pessoa.
****

[[v1-38-1]]

^<<v1-38-1,1>>^ No mesmo tempo, apartando-se Judá de seus irmãos, foi ter a casa de um homem odolamita, chamado Hirão,

[[v1-38-2]]

^<<v1-38-2,2>>^ e viu ali a filha de um homem cananeu, chamado Sue, recebeu-a por mulher e viveu com ela.

[[v1-38-3]]

^<<v1-38-3,3>>^ Ela concebeu e deu à luz um filho, a que pôs o nome de Her.

[[v1-38-4]]

^<<v1-38-4,4>>^ Concebendo outra vez, pôs ao filho nascido o nome de Onan.

[[v1-38-5]]

^<<v1-38-5,5>>^ Deu à luz ainda um terceiro filho, a quem chamou Sela. Nascido este, cessou de dar à luz.

[[v1-38-6]]

^<<v1-38-6,6>>^ Judá deu uma mulher, chamada Tamar, ao seu primogênito Her.

[[v1-38-7]]

^<<v1-38-7,7>>^ Her, primogênito de Judá, foi um homem mau, na presença do Senhor, e (o Senhor) o fez morrer.

[[v1-38-8]]

^<<v1-38-8,8>>^ Disse, pois, Judá a Onan, seu filho: Desposa a mulher de teu irmão, vive com ela, para suscitares descendência a teu irmão.

[[v1-38-9]]

^<<v1-38-9,9>>^ Ele, porém, sabendo que os filhos que nascessem não seriam seus, quando se juntava com a mulher de seu irmão, impedia que ela concebesse a fim de que não nascessem filhos em nome de seu irmão.

[[v1-38-10]]

^<<v1-38-10,10>>^ Por isso, o Senhor o feriu de morte, porque fazia uma coisa detestável.

[[v1-38-11]]

^<<v1-38-11,11>>^ Pelo que Judá disse a Tamar, sua nora: Conserva-te viúva em casa de teu pai até que cresça Sela, meu filho. Com efeito, temia que ele também morresse, como seus irmãos. Ela retirou-se e habitou em casa de seu pai.

[[v1-38-12]]

^<<v1-38-12,12>>^ Passados muitos dias, morreu a filha de Sue, mulher de Judá, o qual, depois de a ter chorado, e terminado o luto, foi a Tamnas ter com os tosquiadores das suas ovelhas, juntamente com Hiras odolamita, pastor dos rebanhos.

[[v1-38-13]]

^<<v1-38-13,13>>^ Noticiaram a Tamar que seu sogro ia a Tamnas para tosquiar as ovelhas. (ver nota)

[[v1-38-14]]

^<<v1-38-14,14>>^ Então ela, depondo os vestidos de viúva, tomou um véu e, disfarçada, sentou-se na encruzilhada do caminho, que conduz a Tamnas, porque (via que) Sela tinha crescido, e (o pai dele) não lho tinha dado por marido.

[[v1-38-15]]

^<<v1-38-15,15>>^ Judá, tendo-a visto, julgou que era meretriz, porque tinha coberto o seu rosto para não ser reconhecida.

[[v1-38-16]]

^<<v1-38-16,16>>^ Chegando-se a ela, disse: Deixa que me junte contigo. De facto ignorava que fosse sua nora. Ela disse: Que me darás por isso?

[[v1-38-17]]

^<<v1-38-17,17>>^ Ele respondeu: Mandar-te-ei um cabrito dos (meus) rebanhos. Ela replicou: Consentirei no que queres, contanto que me dês um penhor, até que mandes o que prometes.

[[v1-38-18]]

^<<v1-38-18,18>>^ Judá disse: Que queres tu que te dê por penhor? Respondeu: O teu anel, e o cordão e o cajado que tens na mão. Ele deu-lhos, esteve com ela, e a mulher concebeu com esse ajuntamento.

[[v1-38-19]]

^<<v1-38-19,19>>^ Depois, levantando-se, retirou-se, e, deposto o traje que havia tomado, vestiu-se com os vestidos de viúva.

[[v1-38-20]]

^<<v1-38-20,20>>^ Ora Judá mandou o cabrito pelo seu pastor odolamita, para receber o penhor que tinha dado à mulher; ele, porém, não a tendo encontrado,

[[v1-38-21]]

^<<v1-38-21,21>>^ perguntou aos habitantes daquele lugar: onde se encontra aquela mulher que estava sentada na encruzilhada? Responderam-lhe todos: Neste lugar não esteve meretriz alguma.

[[v1-38-22]]

^<<v1-38-22,22>>^ Voltou para Judá, e disse-lhe: Não a encontrei; além disso, os homens daquele lugar disseram-me que nunca ali estivera sentada meretriz alguma.

[[v1-38-23]]

^<<v1-38-23,23>>^ Judá disse: Guarde ela (o penhor que lhe dei); ao menos não pode acusar-me de mentira: mandei o cabrito que tinha prometido e tu não a encontraste.

[[v1-38-24]]

^<<v1-38-24,24>>^ Mas, três meses depois, foram dizer a Judá: Tamar, tua nora, prostituiu-se, e vê-se que está grávida. Judá disse: Tirai-a para fora para ser queimada.

[[v1-38-25]]

^<<v1-38-25,25>>^ Enquanto era conduzida ao suplício, mandou dizer a seu sogro: Eu concebi do varão, de quem são estas coisas: vê de quem é o anel, e o cordão, e o cajado.

[[v1-38-26]]

^<<v1-38-26,26>>^ Ele, reconhecidas as dádivas disse: Ela é mais justa do que eu, pois que a não entreguei a meu filho Sela. Ele, todavia, não a conheceu mais.

[[v1-38-27]]

^<<v1-38-27,27>>^ Mas, quando estava para dar ã luz, apareceram dois gêmeos no ventre: e, na saída dos meninos, um deitou de fora a mão, na qual a parteira atou um fio vermelho, dizendo;

[[v1-38-28]]

^<<v1-38-28,28>>^ Este sairá primeiro.

[[v1-38-29]]

^<<v1-38-29,29>>^ Porém, recolhendo ele a mão, saiu o outro: e a mulher disse: Que brecha tu abriste! Por este motivo pôs-lhe o nome de Farés.

[[v1-38-30]]

^<<v1-38-30,30>>^ Depois saiu seu irmão, em cuja mão estava o fio vermelho, e chamou-o Zara.

'''

xref:001-genesis/001-genesis-037.adoc#v1-37-0[&#60; Capítulo Anterior] | <<v1-38-0,Topo>> | xref:001-genesis/001-genesis-039.adoc#v1-39-0[Próximo Capítulo &#62;]