include::./index.adoc[]

[[v1-30-0]]
=== Gênesis, 30
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Em Gênesis 30, vemos a continuação da história de Jacó e suas esposas Raquel e Lia, e suas servas, que competem para ter filhos com ele. O capítulo é marcado por uma série de rivalidades e estratégias para aumentar a prole.
* Provérbios 14:1: "A mulher sábia edifica a sua casa, mas com as próprias mãos a insensata derruba a sua." Este versículo destaca a importância da sabedoria e da edificação da família, que é um tema importante em Gênesis 30, à medida que Jacó constrói sua família por meio de suas esposas e servas.
* Salmos 127:3: "Herança do Senhor são os filhos; o fruto do ventre, seu galardão." Este versículo destaca a importância da criação de filhos como uma bênção de Deus. Jacó busca ter mais filhos com suas esposas e servas, e a questão da fertilidade é uma das principais preocupações em Gênesis 30.
* Provérbios 31:28: "Seus filhos se levantam e a chamam bem-aventurada; seu marido também, e ele a louva dizendo." Este versículo destaca a importância da maternidade e do papel das mães como líderes em suas casas. Em Gênesis 30, vemos as esposas e servas de Jacó competindo para ter filhos com ele, buscando ser bem-aventuradas e reconhecidas por sua prole.
* 1 Samuel 1:27: "Por este menino orava eu, e o Senhor me concedeu a minha petição que eu lhe tinha feito." Este versículo destaca a importância da oração na busca por filhos. Raquel e Lia recorrem a estratégias como dar suas servas a Jacó e usar ervas para aumentar sua fertilidade, mas também oram a Deus por filhos em Gênesis 30.
* Salmos 113:9: "Faz que a mulher estéril habite em casa, e seja alegre mãe de filhos. Louvai ao Senhor." Este versículo destaca a capacidade de Deus de conceder filhos mesmo a mulheres estéreis. Em Gênesis 30, Lia inicialmente tem mais filhos do que Raquel, que é estéril, mas eventualmente Raquel tem um filho de Jacó, José, que se torna um dos personagens mais importantes da Bíblia.
****

[[v1-30-1]]

^<<v1-30-1,1>>^ Ora Raquel, vendo-se infecunda, teve inveja da sua irmã e disse a seu marido: Dá-me filhos, senão morrerei.

[[v1-30-2]]

^<<v1-30-2,2>>^ Jacob, enfadado, respondeu-lhe: Acaso estou eu em lugar de Deus, que te privou do fruto do teu ventre?

[[v1-30-3]]

^<<v1-30-3,3>>^ Ela disse: Tenho (minha) serva Bala: toma-a, para que ela dê à luz sobre os meus joelhos, e eu tenha filhos dela. (ver nota)

[[v1-30-4]]

^<<v1-30-4,4>>^ E deu-lhe Bala por mulher, a qual,

[[v1-30-5]]

^<<v1-30-5,5>>^ depois que Jacob a tomou, concebeu, e deu à luz um filho.

[[v1-30-6]]

^<<v1-30-6,6>>^ Raquel disse: O Senhor julgou a meu favor, e ouviu a minha voz, dando-me um filho; por isso o chamou Dan.

[[v1-30-7]]

^<<v1-30-7,7>>^ Concebendo ela segunda vez, deu à luz outro filho,

[[v1-30-8]]

^<<v1-30-8,8>>^ do qual Raquel disse: O Senhor me fez entrar em competência com minha irmã, e eu vendi; e chamou-o Neftali,

[[v1-30-9]]

^<<v1-30-9,9>>^ Lia, vendo que tinha cessado de ter filhos, deu a seu marido sua escrava Zelfa.

[[v1-30-10]]

^<<v1-30-10,10>>^ E, tendo ela concebido e dado à luz um filho,

[[v1-30-11]]

^<<v1-30-11,11>>^ Lia disse: Em boa hora: por isto lhe pôs o nome de Gad.

[[v1-30-12]]

^<<v1-30-12,12>>^ Zelfa deu à luz ainda outro filho.

[[v1-30-13]]

^<<v1-30-13,13>>^ Lia disse: Isto é por minha dita, porque as mulheres me chamarão ditosa: por isso o chalou Aser.

[[v1-30-14]]

^<<v1-30-14,14>>^ Ora Ruben, tendo saído ao campo no tempo da ceifa do trigo, achou umas mandrágoras e levou-as a Lia, sua mãe. Raquel disse (a Lia): Dá-me parte das mandrágoras do teu filho.

[[v1-30-15]]

^<<v1-30-15,15>>^ Ela respondeu-lhe: Porventura parece-te pouco teres-me roubado o marido. Senão que também me queres levar as mandrágoras de meu filho? Raquel disse: (consinto que ele) durma esta noite contigo pelas mandrágoras de teu filho.

[[v1-30-16]]

^<<v1-30-16,16>>^ Quando Jacob à tarde voltava do campo, Lia saiu-lhe ao encontro e disse-lhe: Virás comigo, porque eu te tomei pelo preço das mandrágoras de meu filho. E (Jacob) dormiu aquela noite com ela.

[[v1-30-17]]

^<<v1-30-17,17>>^ Deus ouviu os seus rogos, e ela concebeu deu à luz o quinto filho,

[[v1-30-18]]

^<<v1-30-18,18>>^ e disse: Deus me deu o pago, dei a minha escrava ao meu marido; e pôs-lhe o nome de Issacar.

[[v1-30-19]]

^<<v1-30-19,19>>^ Concebendo novamente Lia, deu à luz o sexto filho,

[[v1-30-20]]

^<<v1-30-20,20>>^ e disse: Deus me dotou com um bom dote; meu marido estará comigo ainda esta vez, porque eu lhe dei seis filhos; por isso lhe pôs o nome de Zabulon.

[[v1-30-21]]

^<<v1-30-21,21>>^ Depois disto (Lia) deu à luz uma filha, chamada Dina.

[[v1-30-22]]

^<<v1-30-22,22>>^ O Senhor lembrou-se também de Raquel, ouviu-a e tornou-a fecunda.

[[v1-30-23]]

^<<v1-30-23,23>>^ Concebeu e deu luz um filho, dizendo: Deus tirou o meu opróbrio;

[[v1-30-24]]

^<<v1-30-24,24>>^ e pôs-lhe o nome de José, dizendo: o Senhor me dê ainda outro filho.

[[v1-30-25]]

^<<v1-30-25,25>>^ Nascido, porém, José, disse Jacob a seu sogro: Deixa que eu volte para a (minha) pátria, para a minha terra.

[[v1-30-26]]

^<<v1-30-26,26>>^ Dá-me as mulheres e os meus filhos, pelos quais eu tenho servido, para que eu me vá: tu sabes que serviços eu tenho prestado.

[[v1-30-27]]

^<<v1-30-27,27>>^ Labão disse-lhe; ache eu graça diante de teus olhos. Reconheci, por experiência, que Deus me abençoou por causa de ti.

[[v1-30-28]]

^<<v1-30-28,28>>^ Determina tu a recompensa que deverei dar-te.

[[v1-30-29]]

^<<v1-30-29,29>>^ Mas ele respondeu: Tu sabes de que modo te servi, e quanto os teus bens aumentaram nas minhas mãos.

[[v1-30-30]]

^<<v1-30-30,30>>^ Tinhas pouco, antes que eu viesse para ti, e agora tornaste-te rico; o Senhor te abençoou com a minha vinda. É, pois, justo que eu pense também agora (em estabelecer) a minha casa.

[[v1-30-31]]

^<<v1-30-31,31>>^ Labão disse-lhe: Que te hei-de eu dar? Respondeu- lhe Jacob: Não quero nada (em dinheiro); mas, se fizeres o que vou pedir-te. continuarei a apascentar e a guardar os teus rebanhos.

[[v1-30-32]]

^<<v1-30-32,32>>^ Passarei, hoje, pelo meio de todos os teus rebanhos, e porei à parte todas as ovelhas negras ou de diversas cores e de pêlo malhado; tudo o que for negro, malhado e vário, tanto entre as ovelhas como entre as cabras, será a minha recompensa.

[[v1-30-33]]

^<<v1-30-33,33>>^ E amanhã me dará testemunho a minha justiça, quando chegar o tempo combinado entre nós; tudo o que não for de cores variegadas, malhado ou negro, tanto entre as ovelhas como entre as cabras, me arguirá de furto.

[[v1-30-34]]

^<<v1-30-34,34>>^ Labão disse: agrada-me o que pedes.

[[v1-30-35]]

^<<v1-30-35,35>>^ E, naquele dia, Labão separou as cabras, as ovelhas, os bodes e os carneiros variegados e manchados: e entregou nas mãos de seus filhos todo o rebanho que era duma só cor, isto é, de pêlo branco e negro.

[[v1-30-36]]

^<<v1-30-36,36>>^ E pôs a distância de três dias de jornada entre si e o genro, o qual apascentava o restante dos seus rebanhos.

[[v1-30-37]]

^<<v1-30-37,37>>^ Jacob, pois, tomando varas verdes de choupo e de amendoeira e de plátano, tirou-lhes parte da casca; tirada a casca, (nos lugares) onde as varas tinham sido descascadas, apareceu o branco; e onde tinham ficado intactas permaneceram verdes; e isto causou (nas varas) uma variedade de cores.

[[v1-30-38]]

^<<v1-30-38,38>>^ E pô-las nos canais, onde se lançava a água, para que, quando os rebanhos fossem beber, tivessem as varas diante dos olhos, e concebessem olhando para elas.

[[v1-30-39]]

^<<v1-30-39,39>>^ E aconteceu que, no mesmo calor do coito, as ovelhas olhavam para as varas, e davam à luz cordeiros manchados e variegados e pintados de diversas cores. (ver nota)

[[v1-30-40]]

^<<v1-30-40,40>>^ Jacob separou o seu gado, e pôs as varas nos canais diante dos olhos das cabras; tudo o que era branco ou negro pertencia a Labão, e o restante a Jacob, tendo os rebanhos separados entre si.

[[v1-30-41]]

^<<v1-30-41,41>>^ Quando, pois, na primavera, as ovelhas deviam conceber, Jacob punha as varas nos canais da água diante dos olhos dos carneiros e das ovelhas, para que elas concebessem olhando para as varas.

[[v1-30-42]]

^<<v1-30-42,42>>^ Mas, quando as ovelhas concebiam no outono pela segunda vez, não punha as varas. Assim o que era concebido no outono, era para Labão, e o que era concebido na primavera, era para Jacob.

[[v1-30-43]]

^<<v1-30-43,43>>^ Assim tornou-se extraordinàriamente rico, teve muitos rebanhos, escravas e escravos, camelos e jumentos.

'''

xref:001-genesis/001-genesis-029.adoc#v1-29-0[&#60; Capítulo Anterior] | <<v1-30-0,Topo>> | xref:001-genesis/001-genesis-031.adoc#v1-31-0[Próximo Capítulo &#62;]