include::./index.adoc[]

[[v1-48-0]]
=== Gênesis, 48
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Gênesis 48 narra o momento em que Jacó abençoa seus netos Efraim e Manassés, os filhos de José. Jacó concede a bênção da primogenitura a Efraim, o mais novo, em vez de Manassés, o mais velho, o que foi incomum na cultura da época. Os cinco versículos a seguir foram selecionados por sua relevância com os temas abordados neste capítulo.
* 1 Timóteo 4:14: "Não desprezes o dom que há em ti, o qual te foi dado por profecia, com a imposição das mãos do presbítero." A bênção de Jacó sobre Efraim e Manassés é um exemplo de como um líder pode identificar e abençoar aqueles que têm dons e habilidades especiais, mesmo que não sejam os mais velhos ou mais óbvios.
* Romanos 8:17: "E, se nós somos filhos, somos logo herdeiros também, herdeiros de Deus, e co-herdeiros de Cristo: se é certo que com ele padecemos, para que também com ele sejamos glorificados." A bênção da primogenitura concedida a Efraim e não a Manassés é um exemplo de como Deus muitas vezes escolhe os menos óbvios ou aparentemente menos capazes para receber bênçãos e honras.
* Provérbios 17:6: "Coroa dos velhos são os filhos dos filhos; e a glória dos filhos são seus pais." Jacó demonstra amor e cuidado por seus netos, abençoando-os e reconhecendo a importância da próxima geração para a continuidade da família e do legado.
* 1 Pedro 2:9: "Mas vós sois a geração eleita, o sacerdócio real, a nação santa, o povo adquirido, para que anuncieis as virtudes daquele que vos chamou das trevas para a sua maravilhosa luz." A bênção concedida a Efraim e Manassés é um exemplo de como Deus pode usar a próxima geração para realizar seus propósitos e transmitir seus valores.
* Hebreus 11:21: "Pela fé, Jacó, próximo da morte, abençoou cada um dos filhos de José, e adorou, inclinado sobre a extremidade do seu bordão." A bênção de Jacó sobre seus netos é um exemplo de como a fé pode inspirar um pai ou avô a abençoar e transmitir valores espirituais à próxima geração.
****

[[v1-48-1]]

^<<v1-48-1,1>>^ Passadas assim estas coisas, foi anunciado a José que seu pai estava doente, e ele, tomando consigo os dois filhos, Manassés e Efraim, foi vê-lo.

[[v1-48-2]]

^<<v1-48-2,2>>^ Disseram ao velho: Teu filho José vem visitar-te. Ele, reunidas as suas forças, sentou-se sobre o leito.

[[v1-48-3]]

^<<v1-48-3,3>>^ Logo que (José) entrou, disse-lhe: O Deus Omnipotente apareceu-me em Luza, que é a terra de Canaan, abençoou-me

[[v1-48-4]]

^<<v1-48-4,4>>^ e disse: Eu te aumentarei e multiplicarei, e farei de ti uma multidão de povos: darei esta terra a ti e à tua descendência depois de ti, para sempre.

[[v1-48-5]]

^<<v1-48-5,5>>^ Portanto os teus dois filhos, que te nasceram na terra do Egito, antes que eu para aqui viesse ter contigo, serão meus: Efraim e Manassés serão considerados meus (filhos), como Ruben e Simeão. (ver nota)

[[v1-48-6]]

^<<v1-48-6,6>>^ Mas os outro, que tiveres depois destes, serão teus, e serão chamados com o nome de seus irmãos nas suas possessões. (ver nota)

[[v1-48-7]]

^<<v1-48-7,7>>^ Quando eu voltava da Mesopotâmia, morreu-me Raquel na terra de Canaan, mesmo durante a viagem, na Primavera; eu estava para entrar em Efrata, e enterrei-a junto do caminho de Efrata, que, por outro nome, se chama Belém,

[[v1-48-8]]

^<<v1-48-8,8>>^ Vendo Israel os filhos (de José), disse-lhe: Quem são estes?

[[v1-48-9]]

^<<v1-48-9,9>>^ (José) respondeu: São os meus filhos, que Deus me deu aqui. Faze-os aproximar de mim, disse (Jacob), para que eu os abençoe.

[[v1-48-10]]

^<<v1-48-10,10>>^ Com efeito. Os olhos de Israel se tinham escurecido por causa da grande velhice, e não podia ver claramente. José aproximou-os, e ele, beijando-os, e abraçando-os

[[v1-48-11]]

^<<v1-48-11,11>>^ disse a seu filho: Não fui privado de te ver, e, além disso, Deus mostrou-me a tua geração.

[[v1-48-12]]

^<<v1-48-12,12>>^ José, tendo-os tirado de entre os joelhos do pai, inclinou-se profundamente por terra.

[[v1-48-13]]

^<<v1-48-13,13>>^ Em seguida pôs Efraim à sua direita, isto é, à esquerda de Israel, e Manassés à sua esquerda, isto é, à direita de seu pai, e fez que ambos se aproximassem dele.

[[v1-48-14]]

^<<v1-48-14,14>>^ Israel, estendendo a mão direita, pô-la sobre a cabeça de Efraim, irmão mais novo, e a esquerda sobre a cabeça de Manassés, o mais velho, cruzando, assim as mãos.

[[v1-48-15]]

^<<v1-48-15,15>>^ Jacob abençoou José (nos seus filhos), dizendo: O Deus, em cuja presença andaram meus pais Abraão e Isaac, o Deus que me sustentou desde a minha mocidade até este dia,

[[v1-48-16]]

^<<v1-48-16,16>>^ o Anjo, que me livrou de todos os males, abençoe estes meninos; que eles sejam chamados com o meu nome, e também com os nomes de meus pais Abraão e Isaac, e se multipliquem em abundância sobre a terra. (ver nota)

[[v1-48-17]]

^<<v1-48-17,17>>^ José, vendo que o pai tinha posto a mão direita sobre a cabeça de Efraim, teve com isto grande pena, e, pegando na mão de seu pai, procurava afastá-la da cabeça de Efraim, e levá-la sobre a cabeça de Manassés.

[[v1-48-18]]

^<<v1-48-18,18>>^ Disse ao pai; Não está assim bem, pai: visto que este é o primogênito, põe a tua direita sobre sua cabeça.

[[v1-48-19]]

^<<v1-48-19,19>>^ Ele, porém, recusando, disse: Eu o sei, meu filho, eu o sei: este também será chefe de povos, e se multiplicará, mas seu irmão mais novo será maior do que ele, e a sua descendência se tornará uma multidão de nações.

[[v1-48-20]]

^<<v1-48-20,20>>^ Então os abençoou, dizendo: Por ti será bendito Israel, quando se disser: Deus te faça como Efraim e como Manassés. E pôs Efraim adiante de Manassés.

[[v1-48-21]]

^<<v1-48-21,21>>^ Disse a seu filho José: Vou morrer, mas Deus será convosco e vos reconduzirá à terra de vossos pais.

[[v1-48-22]]

^<<v1-48-22,22>>^ Eu te dou, de mais que a teus irmãos, aquela parte que ganhei da mão dos Amorreus, com a espada e com o meu arco.

'''

xref:001-genesis/001-genesis-047.adoc#v1-47-0[&#60; Capítulo Anterior] | <<v1-48-0,Topo>> | xref:001-genesis/001-genesis-049.adoc#v1-49-0[Próximo Capítulo &#62;]