include::./index.adoc[]

[[v1-1-0]]
=== Gênesis, 1
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Gênesis 1 é o primeiro capítulo da Bíblia e trata da criação do mundo por Deus. Ele descreve como Deus criou o universo, a terra, os céus, a luz, as águas, a vegetação, o sol, a lua, as estrelas, os animais e o homem. A seguir, estão cinco versículos da Bíblia que se relacionam com temas abordados em Gênesis 1:
* Salmos 8:3-4: "Quando contemplo os teus céus, obra dos teus dedos, a lua e as estrelas que estabeleceste, que é o homem, para que te lembres dele? E o filho do homem, para que o visites?" Esse salmo destaca a obra da criação de Deus, incluindo a lua e as estrelas mencionadas em Gênesis 1, e questiona o papel do homem no universo.
* Isaías 45:12: "Eu fiz a terra, e criei nela o homem; eu o fiz; as minhas mãos estenderam os céus, e a todo o seu exército dei as minhas ordens." Esse versículo reafirma a criação da terra e do homem por Deus, conforme descrito em Gênesis 1.
* João 1:3: "Todas as coisas foram feitas por ele, e sem ele nada do que foi feito se fez." Esse versículo se refere a Jesus como o criador de todas as coisas, incluindo o mundo criado por Deus em Gênesis 1.
* Colossenses 1:16: "Porque nele foram criadas todas as coisas nos céus e na terra, as visíveis e as invisíveis, sejam tronos, sejam dominações, sejam principados, sejam potestades. Tudo foi criado por ele e para ele." Esse versículo enfatiza a criação de todas as coisas por meio de Jesus e como todas as coisas são destinadas para ele.
* Apocalipse 4:11: "Digno és, Senhor, de receber glória, e honra, e poder; porque tu criaste todas as coisas, e por tua vontade são e foram criadas." Esse versículo destaca a glória de Deus como criador de todas as coisas, incluindo o mundo criado em Gênesis 1.
****

[[v1-1-1]]

^<<v1-1-1,1>>^ No principio criou Deus o céu e a terra.

[[v1-1-2]]

^<<v1-1-2,2>>^ A terra, porém, estava informe e vazia, e as trevas cobriam a face do abismo, e o Espírito de Deus movia-Se sobre as águas.

[[v1-1-3]]

^<<v1-1-3,3>>^ E Deus disse: Exista a luz. E a luz existiu.

[[v1-1-4]]

^<<v1-1-4,4>>^ E Deus viu que a luz era boa, e separou a luz das trevas.

[[v1-1-5]]

^<<v1-1-5,5>>^ Chamou à luz dia. e às trevas noite. E fez-se tarde e manhã, (e foi) o primeiro dia.

[[v1-1-6]]

^<<v1-1-6,6>>^ Disse também Deus: Faça-se o firmamento no meio das águas, e separe umas águas das outras águas.

[[v1-1-7]]

^<<v1-1-7,7>>^ E fez Deus o firmamento, e separou as águas que estavam por baixo, das águas que estavam por cima do firmamento. E assim se fez.

[[v1-1-8]]

^<<v1-1-8,8>>^ E Deus chamou ao firmamento céu. E fez-se tarde e manhã, (e foi) o segundo dia.

[[v1-1-9]]

^<<v1-1-9,9>>^ Disse também Deus: As águas, que estão debaixo do céu, juntem-se num só lugar, e apareça o (elemento) árido. E assim se fez.

[[v1-1-10]]

^<<v1-1-10,10>>^ E Deus chamou ao (elemento) árido terra, e ao conjunto das águas chamou mares. E Deus viu que isto era bom.

[[v1-1-11]]

^<<v1-1-11,11>>^ Deus disse: produza a terra verdura, plantas germinadoras de semente e árvores frutíferas, que dêem fruto segundo a sua espécie, cuja semente esteja nelas mesmas (para se reproduzirem) sobre a terra. E assim se fez.

[[v1-1-12]]

^<<v1-1-12,12>>^ E a terra produziu verdura, plantas germinadoras de semente e árvores que dão fruto, e cada uma das quais tem semente segundo a sua espécie. E viu Deus que isto era bom.

[[v1-1-13]]

^<<v1-1-13,13>>^ E fez-se tarde e manhã, (e foi) o terceiro dia.

[[v1-1-14]]

^<<v1-1-14,14>>^ Disse também Deus: Sejam feitos luzeiros no firmamento do céu, que separem o dia da noite e sirvam para sinais, e que distingam as estações, os dias e os anos,

[[v1-1-15]]

^<<v1-1-15,15>>^ e que resplandeçam no firmamento do céu, para alumiar a terra. E assim se fez.

[[v1-1-16]]

^<<v1-1-16,16>>^ Deus fez os dois grandes luzeiros: o luzeiro maior para presidir ao dia, e o luzeiro menor para presidir à noite, e (fez também) as estrelas.

[[v1-1-17]]

^<<v1-1-17,17>>^ E colocou-as no firmamento do céu, para luzirem sobre a terra.

[[v1-1-18]]

^<<v1-1-18,18>>^ e presidirem ao dia e à noite, e separarem a luz das trevas. E Deus viu que isto era bom.

[[v1-1-19]]

^<<v1-1-19,19>>^ E fez-se tarde e manhã, (e foi) o quarto dia.

[[v1-1-20]]

^<<v1-1-20,20>>^ Disse também Deus: encham-se as águas de seres vivos, e voem aves sobre a terra, debaixo do firmamento do céu.

[[v1-1-21]]

^<<v1-1-21,21>>^ Deus criou os grandes animais aquáticos, e todos os animais que têm vida e movimento e que abundam nas águas, segundo a sua espécie, e todas as aves seguindo a sua espécie. E Deus viu que isto era bom.

[[v1-1-22]]

^<<v1-1-22,22>>^ E os abençoou, dizendo: Crescei e multiplicai-vos, e enchei as águas do mar: e as aves se multipliquem sobre a terra.

[[v1-1-23]]

^<<v1-1-23,23>>^ E fez-se tarde e manhã (e foi) o quinto dia.

[[v1-1-24]]

^<<v1-1-24,24>>^ Disse também Deus: Produza a terra animais viventes segundo a sua espécie, animais domésticos, e répteis, e animais selváticos segundo a sua espécie. E assim se fez.

[[v1-1-25]]

^<<v1-1-25,25>>^ E fez Deus os animais selváticos, segundo a sua espécie, e os animais domésticos, e todos os répteis da terra (cada um) segundo a sua espécie. E viu Deus que isto era bom,

[[v1-1-26]]

^<<v1-1-26,26>>^ e (por fim) disse: Façamos o homem à nossa imagem e semelhança, e presida aos peixes do mar, e as aves do Céu, e aos animais selváticos, e a toda a terra, e a todos os répteis, que se movem sobre a terra.

[[v1-1-27]]

^<<v1-1-27,27>>^ E criou Deus o homem à sua imagem; criou-o à imagem de Deus, varão e fêmea os criou. (ver nota)

[[v1-1-28]]

^<<v1-1-28,28>>^ E Deus os abençoou, e disse: Crescei e multiplicai-vos, e enchei a terra, e sujeitai-a, e dominai sobre os peixes do mar e sobre as aves do céu, e sobre todos os animais que se movem sobre a terra.

[[v1-1-29]]

^<<v1-1-29,29>>^ E Deus disse: Eis que vos dei todas as ervas, que dão semente sobre a terra, e todas as árvores, que encerram em si mesmas a semente do seu gênero, para que vos sirvam de alimento,

[[v1-1-30]]

^<<v1-1-30,30>>^ e a todos os animais da terra, e a todas as aves do céu, e a tudo o que se move, sobre a terra, e em que há alma vivente, para que tenham que comer. E assim se fez.

[[v1-1-31]]

^<<v1-1-31,31>>^ E Deus viu todas as coisas que tinha feito, e eram muito boas. E fez-se tarde e manhã, (e foi) o sexto dia.

'''

**&#60; Capítulo Anterior** | <<v1-1-0,Topo>> | xref:001-genesis/001-genesis-002.adoc#v1-2-0[Próximo Capítulo &#62;]