include::./index.adoc[]

[[v1-41-0]]
=== Gênesis, 41
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Gênesis 41 descreve como José interpretou os sonhos do faraó, que previam sete anos de fartura seguidos de sete anos de fome, e como ele foi elevado à posição de governador do Egito para administrar a armazenagem de alimentos durante os anos de fartura para se preparar para os anos de fome. Aqui estão cinco versículos relacionados aos temas do capítulo:
* Isaías 41:10: "Não temas, porque estou contigo; não te assombres, porque sou teu Deus; eu te fortaleço, e te ajudo, e te sustento com a minha destra fiel." José foi levado do fundo da prisão para se tornar governador do Egito, algo que só poderia ter acontecido por meio da intervenção divina. Este versículo mostra como Deus é fiel e nos sustenta durante os momentos difíceis.
* Salmos 105:16-17: "Fez com que passasse fome a toda a terra, e cortou-lhes o sustento. Enviou perante eles um homem; foi vendido como escravo, José." Deus usou a vida de José para salvar todo o povo do Egito e da região durante a fome prevista nos sonhos do faraó. Este versículo demonstra como Deus pode usar circunstâncias difíceis para cumprir Seus propósitos.
* Provérbios 3:5-6: "Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento. Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas." José confiou em Deus e, por meio disso, foi elevado à posição de governador do Egito. Este versículo nos ensina a confiar em Deus e permitir que Ele guie nossos caminhos.
* João 15:5: "Eu sou a videira, vós as varas; quem está em mim, e eu nele, esse dá muito fruto; porque sem mim nada podeis fazer." José foi usado por Deus para produzir um grande fruto ao salvar o Egito e a região da fome. Este versículo nos lembra que, sem a presença de Deus em nossas vidas, não podemos fazer nada.
* Salmos 46:1: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia." José enfrentou muitas dificuldades em sua vida, mas sempre encontrou força e refúgio em Deus. Este versículo nos lembra que Deus está sempre presente e disposto a nos ajudar em nossos momentos de necessidade.
****

[[v1-41-1]]

^<<v1-41-1,1>>^ Dois anos depois Faraó teve um sonho. Parecia-lhe que estava na margem do rio,

[[v1-41-2]]

^<<v1-41-2,2>>^ do qual saiam sete vacas, muito formosas e gordas, as quais pastavam nos lugares palustres.

[[v1-41-3]]

^<<v1-41-3,3>>^ Saiam também outras sete do rio, desfiguradas e consumidas de magreza, as quais pastavam na mesma margem do rio, em lugares cheios de erva:

[[v1-41-4]]

^<<v1-41-4,4>>^ (estas) devoravam aquelas que eram belas de aspecto e gordas de corpo. Tendo Faraó despertado,

[[v1-41-5]]

^<<v1-41-5,5>>^ adormeceu novamente, e teve outro sonho; sete espigas saiam do mesmo caule, cheias de grãos e formosas;

[[v1-41-6]]

^<<v1-41-6,6>>^ e nasciam também outras tantas espigas delgadas e queimadas do vento,

[[v1-41-7]]

^<<v1-41-7,7>>^ as quais devoravam todas as primeiras que eram tão belas. Despertando Faraó do sono,

[[v1-41-8]]

^<<v1-41-8,8>>^ de manhã, cheio de pavor, mandou chamar todos os adivinhos do Egito e todos os sábios; estando reunidos, contou-lhes o sonho e não havia quem lho esplicasse.

[[v1-41-9]]

^<<v1-41-9,9>>^ Então, finalmente, lembrando-se o copeiro-mór (de José) disse: Confesso a minha falta.

[[v1-41-10]]

^<<v1-41-10,10>>^ Tendo-se o rei irado contra os seus servos, mandou que eu e o padeiro-mór fôssemos metidos no cárcere do chefe da guarda;

[[v1-41-11]]

^<<v1-41-11,11>>^ ai, uma noite, ambos nós tivemos um sonho que presagiava o futuro.

[[v1-41-12]]

^<<v1-41-12,12>>^ Achava-se lá um jovem hebreu, servo do mesmo chefe da guarda. Tendo-lhe nós referidos os sonhos,

[[v1-41-13]]

^<<v1-41-13,13>>^ ouvimos tudo o que depois os factos comprovaram: Eu fui restituído ao meu ofício e o outro foi pendurado em uma forca.

[[v1-41-14]]

^<<v1-41-14,14>>^ Imediatamente José foi tirado do cárcere por mandado do rei. Barbeou-se, mudou de roupa e foi ter com Faraó.

[[v1-41-15]]

^<<v1-41-15,15>>^ Este disse-lhe; Tive uns sonhos, e não há quem os interprete; ouvi dizer que tu sabes explicar os sonhos que te contam.

[[v1-41-16]]

^<<v1-41-16,16>>^ José respondeu: Não sou eu, é Deus quem dará uma resposta favorável a Faraó,

[[v1-41-17]]

^<<v1-41-17,17>>^ Faraó, pois, contou o que tinha visto: Parecia-me estar sobre a margem do rio,

[[v1-41-18]]

^<<v1-41-18,18>>^ e que saíam do rio sete vacas, em extremo formosas, e muito gordas, as quais pastavam a erva verde nos lugares palustres;

[[v1-41-19]]

^<<v1-41-19,19>>^ a seguir, atrás destas, vinham outras sete vacas tão disformes e magras, que nunca as vi semelhantes na terra do Egito,

[[v1-41-20]]

^<<v1-41-20,20>>^ as quais devoraram e consumiram as primeiras,

[[v1-41-21]]

^<<v1-41-21,21>>^ Sem que parecessem tê-las engolido, pois ficaram tão macilentas e feias como antes. Acordei, fui novamente oprimido pelo sono,

[[v1-41-22]]

^<<v1-41-22,22>>^ e tive este sonho: sete espigas saíam do mesmo caule cheias (de grãos) e formosas:

[[v1-41-23]]

^<<v1-41-23,23>>^ outras sete, delgadas e queimadas do vento nasciam doutro caule,

[[v1-41-24]]

^<<v1-41-24,24>>^ as quais devoravam as primeiras, que eram tão belas. Referi aos adivinhos o sonho, e não há quem o explique.

[[v1-41-25]]

^<<v1-41-25,25>>^ José respondeu: O sonho do rei reduz-se a um só: Deus mostrou a Faraó o que está para fazer.

[[v1-41-26]]

^<<v1-41-26,26>>^ As sete vacas formosas, e as sete espigas cheias, (de grãos), são sete anos de abundância: no sonho têm a mesma significação.

[[v1-41-27]]

^<<v1-41-27,27>>^ As sete vacas magras e macilentas, que subiram (do rio) após as primeiras, e as sete espigas delgadas e queimadas do vento, são sete anos de fome que estão para vir.

[[v1-41-28]]

^<<v1-41-28,28>>^ Isto cumprir-se-á por esta ordem:

[[v1-41-29]]

^<<v1-41-29,29>>^ virão sete anos de grande fertilidade por toda a terra do Egito,

[[v1-41-30]]

^<<v1-41-30,30>>^ depois dos quais se seguirão outros sete anos de tanta esterilidade que será esquecida toda a abundância passada; com efeito, a fome há-de consumir toda a terra.

[[v1-41-31]]

^<<v1-41-31,31>>^ e a grandeza da penúria há-de absorver a grandeza da abundância.

[[v1-41-32]]

^<<v1-41-32,32>>^ Quanto ao segundo sonho que tivestes, que se refere à mesma coisa, é um sinal certo de que se há-de executar a palavra de Deus, e prontamente se cumprirá.

[[v1-41-33]]

^<<v1-41-33,33>>^ Agora, pois, escolha, o rei um homem sábio e ativo, a quem dê autoridade sobre a terra do Egito:

[[v1-41-34]]

^<<v1-41-34,34>>^ este ;(homem) estabeleça superintendentes por todas as províncias: a quinta parte dos frutos nos sete anos de fertilidade,

[[v1-41-35]]

^<<v1-41-35,35>>^ que já estão para começar, seja recolhida nos celeiros: guarde-se todo o trigo debaixo do poder do Faraó, conserve-se nas cidades,

[[v1-41-36]]

^<<v1-41-36,36>>^ e tenha-se preparado para a futura fome dos sete anos, que há-de oprimir o Egito. Assim o país não será consumido pela fome.

[[v1-41-37]]

^<<v1-41-37,37>>^ Agradou o conselho a Faraó e a todos os seus ministros.

[[v1-41-38]]

^<<v1-41-38,38>>^ Disse-lhes: Poderemos nós encontrar um homem como este, que esteja (tão) cheio de espirito de Deus?

[[v1-41-39]]

^<<v1-41-39,39>>^ Disse, pois, a José; Visto que Deus te manifestou tudo o que disseste, poderei eu encontrar alguém mais inteligente e sábio do que tu?

[[v1-41-40]]

^<<v1-41-40,40>>^ Tu governarás a minha casa, e, ao mando da tua voz, obedecerá todo o povo; eu não terei sobre ti outra precedência além do trono.

[[v1-41-41]]

^<<v1-41-41,41>>^ Faraó disse mais a José: Dou-te autoridade sobre toda a terra do Egito.

[[v1-41-42]]

^<<v1-41-42,42>>^ E tirou o anel da sua mão, meteu-o na mão dele, mandou-lhe um hábito branco de linho fino, e pôs-lhe ao pescoço um colar de oiro;

[[v1-41-43]]

^<<v1-41-43,43>>^ fê-lo subir para o seu segundo coche, clamando o pregoeiro que todos ajoelhassem, diante dele, e soubessem que era o superintendente de toda a terra do Egito.

[[v1-41-44]]

^<<v1-41-44,44>>^ Disse também o rei a José: Eu sou Faraó; sem o teu mando ninguém moverá mão ou pé em toda a terra do Egito.

[[v1-41-45]]

^<<v1-41-45,45>>^ Mudou-lhe o nome, e chamou-o, na lingua egípcia, Salvador do Mundo. Deu-lhe por mulher a Aseneth, filha de Putifar, sacerdote de Heliópolis. Saiu, portanto, José a correr a terra do Egito,

[[v1-41-46]]

^<<v1-41-46,46>>^ (tinha trinta anos quando se apresentou diante do rei Faraó), e percorreu todas as provindas do Egito.

[[v1-41-47]]

^<<v1-41-47,47>>^ Veio a fertilidade dos sete anos, e, atado o trigo aos molhos, foi recolhido nos celeiros do Egito.

[[v1-41-48]]

^<<v1-41-48,48>>^ Recolheu-se também em cada uma das cidades toda a abundância de frutos.

[[v1-41-49]]

^<<v1-41-49,49>>^ Foi tanta a abundância do trigo, que igualava a areia do mar, e a quantidade excedia toda a medida.

[[v1-41-50]]

^<<v1-41-50,50>>^ Nasceram a José dois filhos antes de chegar a fome, os quais lhe foram dados à luz por Aseneth, filha de Putifar, sacerdote de Heliópolis.

[[v1-41-51]]

^<<v1-41-51,51>>^ Ao primogênito pôs o nome de Manassés, dizendo: Deus me fez esquecer de todos os meus trabalhos, e da casa de meu pai.

[[v1-41-52]]

^<<v1-41-52,52>>^ Ao segundo pôs o nome de Efraim, dizendo: Deus me fez crescer, na terra da minha aflição.

[[v1-41-53]]

^<<v1-41-53,53>>^ Passados os sete anos da abundância, que houve no Egito,

[[v1-41-54]]

^<<v1-41-54,54>>^ começaram a vir os sete anos de escassez que José prognosticara. Em todo o mundo, se fez sentir a fome: porém em toda a terra do Egito havia pão.

[[v1-41-55]]

^<<v1-41-55,55>>^ Quando também o Egito sentiu a fome, o povo clamou a Faraó, pedindo sustento. Ele respondeu-lhes: Ide a José e fazei tudo o que ele vos disser.

[[v1-41-56]]

^<<v1-41-56,56>>^ Ora a fome crescia todos os dias em toda a terra, e José abriu todos os celeiros, e vendia aos Egípcios, porque também a eles oprimia a fome.

[[v1-41-57]]

^<<v1-41-57,57>>^ De todas as partes vinham ao Egito, para comprar de comer porque a fome era grande em toda a terra.

'''

xref:001-genesis/001-genesis-040.adoc#v1-40-0[&#60; Capítulo Anterior] | <<v1-41-0,Topo>> | xref:001-genesis/001-genesis-042.adoc#v1-42-0[Próximo Capítulo &#62;]