include::./index.adoc[]

[[v44-2-0]]
=== Ageu, 2
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 2 de Ageu fala sobre a restauração do Templo de Jerusalém, que havia sido destruído pelos babilônios. Ageu profetiza que a glória deste Templo será maior do que a do Templo anterior e que Deus trará prosperidade para o povo de Judá. Abaixo estão cinco versículos relacionados com os temas abordados em Ageu 2:
* 2 Crônicas 36:23: "Assim diz Ciro, rei da Pérsia: O SENHOR Deus dos céus me deu todos os reinos da terra, e me encarregou de lhe edificar uma casa em Jerusalém, que está em Judá. Quem há entre vós de todo o seu povo? O SENHOR seu Deus seja com ele, e suba." Este verso fala sobre a ordem de Ciro, rei da Pérsia, para a reconstrução do Templo em Jerusalém, o que é o tema principal de Ageu 2.
* Esdras 6:14: "E os anciãos dos judeus iam edificando e prosperando, pela profecia do profeta Ageu e de Zacarias, filho de Ido. Edificaram a casa e a aperfeiçoaram, conforme ao mandado do Deus de Israel, e conforme ao mandado de Ciro, e de Dario, e de Artaxerxes, reis da Pérsia." Este verso mostra que a profecia de Ageu sobre a restauração do Templo se cumpriu e que os judeus foram abençoados com prosperidade.
* Isaías 60:7: "Todo o rebanho de Quedar se congregarão a ti; os carneiros de Nebaiote te servirão; subirão aceitavelmente ao meu altar, e eu glorificarei a casa da minha glória." Este verso fala sobre a glória que Deus trará para o seu povo e para o seu Templo, o que se relaciona com a profecia de Ageu sobre a glória do novo Templo.
* 1 Reis 8:10-11: "E sucedeu que, saindo os sacerdotes do santuário, uma nuvem encheu a casa do SENHOR, de maneira que os sacerdotes não podiam ter-se em pé para ministrar, por causa da nuvem, porque a glória do SENHOR enchera a casa do SENHOR." Este verso fala sobre a glória de Deus que encheu o Templo de Salomão, o que se relaciona com a profecia de Ageu sobre a glória do novo Templo.
* Salmos 72:16: "Haverá abundância de trigo na terra, até aos cimos dos montes; o seu fruto fará ruído como o Líbano, e os homens florescerão nas cidades como a erva da terra." Este verso fala sobre a prosperidade que Deus trará para o seu povo, o que se relaciona com a profecia de Ageu sobre a prosperidade que virá para Judá após a restauração do Templo.
****

[[v44-2-1]]

^<<v44-2-1,1>>^ (Começaram) aos vinte e quatro dias do sexto mês, no ano segundo do reinado de Dario.

[[v44-2-2]]

^<<v44-2-2,2>>^ No sétimo mês, aos vinte e um dias do mês, fez-se ouvir a palavra do Senhor, por intermédio do profeta Ageu, nestes termos:

[[v44-2-3]]

^<<v44-2-3,3>>^ Fala a Zorobabel, filho de Salatiel, governador de Judá, e a Josué, sumo sacerdote, filho de Josedec, e ao resto do povo, assim:

[[v44-2-4]]

^<<v44-2-4,4>>^ Quem há dentre os que ficaram de vós, que visse esta casa na sua primeira glória? E em que estado a vedes vós agora? Não parece ela a vossos olhos como uma coisa de nada (comparada com o que foi)?

[[v44-2-5]]

^<<v44-2-5,5>>^ Todavia ó Zorobabel, cobra força, diz o Senhor; cobra força, ó Josué, sumo sacerdote, filho de Josedec; cobra força, povo inteiro do país, diz o Senhor dos exércitos! Mãos à obra, porque eu sou convosco, diz o Senhor dos exércitos.

[[v44-2-6]]

^<<v44-2-6,6>>^ Há o pacto que fiz convosco, quando saístes da terra do Egipto; o meu espírito estará no meio de vós. Não temais!

[[v44-2-7]]

^<<v44-2-7,7>>^ Porque isto diz o Senhor dos exércitos: Ainda um pouco, e eu comoverei o céu e a terra, os mares e os continentes.

[[v44-2-8]]

^<<v44-2-8,8>>^ Abalarei todas as nações, afluirão riquezas de todos os povos, e encherei de glória esta casa, diz o Senhor dos exércitos.

[[v44-2-9]]

^<<v44-2-9,9>>^ Minha é a prata, meu o ouro, diz o Senhor dos exércitos. (ver nota)

[[v44-2-10]]

^<<v44-2-10,10>>^ A glória desta última casa será maior do que a da primeira diz o Senhor dos exércitos e eu darei a paz neste lugar, diz o Senhor dos exércitos.

[[v44-2-11]]

^<<v44-2-11,11>>^ Aos vinte e quatro dias do nono mês, no segundo ano do reinado de Dario, foi dirigida ao profeta Ageu a palavra do Senhor, nestes termos:

[[v44-2-12]]

^<<v44-2-12,12>>^ Isto diz o Senhor dos exércitos: Propõe aos sacerdotes a questão seguinte:

[[v44-2-13]]

^<<v44-2-13,13>>^ Se um homem trouxer na orla do seu vestido um pedaço de carne santificada e tocar com ele no pão, ou nas iguarias, ou no vinho, ou no azeite, ou em qualquer outra coisa de comer, porventura ficará santificada tal coisa? Respondendo os sacerdotes disseram: Não.

[[v44-2-14]]

^<<v44-2-14,14>>^ Ageu prosseguiu: Se um homem, manchado por ter tocado num cadáver, tocar alguma de todas estas coisas, porventura ficará ela por Isso contaminada? Os sacerdotes, respondendo, disseram: Ficará contaminada. (ver nota)

[[v44-2-15]]

^<<v44-2-15,15>>^ Então Ageu retomou a palavra e disse: Assim é este povo, assim é esta gente diante da minha face, diz o Senhor, e assim são também todas as obras das suas mãos: tudo o que me oferecem neste lugar está manchado. (ver nota)

[[v44-2-16]]

^<<v44-2-16,16>>^ Agora reflecti nos vossos corações sobre o que tem acontecido desde este dia para trás, antes que se lançasse pedra sobre pedra no templo do Senhor.

[[v44-2-17]]

^<<v44-2-17,17>>^ Quando vos aproximáveis dum montão de trigo (que parecia) de vinte medidas, só tinha dez; quando íeis à cuba para tirar cinquenta medidas, não tiráveis mais de vinte.

[[v44-2-18]]

^<<v44-2-18,18>>^ Eu vos feri com um vento abrasador, e (feri) com ferrugem e saraiva todas as obras das vossas mãos; todavia não houve entre vós quem se voltasse para mim, diz o Senhor.

[[v44-2-19]]

^<<v44-2-19,19>>^ Gravai nos vossos corações o que há-de suceder desde este dia para futuro, desde este dia vinte e quatro do nono mês, desde este dia, em que foram lançados os alicerces do templo do Senhor; gravai-o no vosso coração.

[[v44-2-20]]

^<<v44-2-20,20>>^ Vede se a semente falta ainda no celeiro, se a vinha, a figueira, a romãzeira e a oliveira continuam improdutivas. Com efeito, a partir deste dia abençoarei tudo.

[[v44-2-21]]

^<<v44-2-21,21>>^ Aos vinte e quatro dias do mês, foi dirigida pela segunda vez a palavra do Senhor a Ageu, a qual dizia:

[[v44-2-22]]

^<<v44-2-22,22>>^ Fala a Zorobabel, governador de Judá, nestes termos: Abalarei o céu e a terra,

[[v44-2-23]]

^<<v44-2-23,23>>^ farei cair o trono dos reinos, quebrarei a fortaleza dos reinos das gentes; destruirei os carros (de guerra) e os que vão sobre eles; os cavalos e os seus cavaleiros cairão (m ortos); cada um será passado pela espada do seu Irmão.

[[v44-2-24]]

^<<v44-2-24,24>>^ Naquele dia, diz o Senhor dos exércitos, eu te tomarei (debaixo da minha protecção) ó Zorobabel, meu servo, filho de Salatiel, diz o Senhor, e te guardarei como um sinete, porque te escolhi, diz o Senhor dos exércitos. (ver nota)

'''

xref:044-ageu/044-ageu-001.adoc#v44-1-0[&#60; Capítulo Anterior] | <<v44-2-0,Topo>> | xref:045-zacarias/045-zacarias-001.adoc#v45-1-0[Próximo Capítulo &#62;]