include::./index.adoc[]

[[v51-23-0]]
=== Atos dos Apóstolos, 23
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 23 de Atos dos Apóstolos narra a continuação das perseguições sofridas por Paulo após a sua pregação em Jerusalém. Ele comparece perante o Sinédrio e faz sua defesa, mas é atacado pelos saduceus e precisa ser protegido pelos soldados romanos. Paulo é transferido para Cesaréia para protegê-lo dos judeus que queriam matá-lo. Abaixo seguem cinco versículos relacionados com os temas abordados nesse capítulo:
* Salmos 27:1: "O SENHOR é a minha luz e a minha salvação; de quem terei medo? O SENHOR é o refúgio da minha vida; a quem temerei?" Este salmo fala sobre confiar no Senhor em meio a tempos difíceis e buscar refúgio nele.
* Salmos 31:15: "Os meus tempos estão nas tuas mãos; livra-me das mãos dos meus inimigos e dos que me perseguem." Esse versículo é um apelo a Deus para proteger o salmista dos seus inimigos.
* Provérbios 19:21: "Muitos são os planos no coração do homem, mas o propósito do SENHOR prevalecerá." Esse provérbio destaca a soberania de Deus sobre os planos dos homens e como Ele pode transformar situações difíceis para cumprir o Seu propósito.
* Jeremias 1:8: "Não tenha medo deles, pois estou com você para protegê-lo", diz o SENHOR." Essa é uma mensagem de encorajamento de Deus para Jeremias, que o chamou para ser profeta em tempos difíceis.
* Romanos 8:28: "Sabemos que Deus age em todas as coisas para o bem daqueles que o amam, dos que foram chamados de acordo com o seu propósito." Esse versículo fala sobre como Deus pode usar todas as coisas, mesmo as difíceis, para cumprir o Seu propósito em nossas vidas.
****

[[v51-23-1]]

^<<v51-23-1,1>>^ Paulo, fitando os olhos no Sinédrio, disse: "Irmãos, até hoje tenho-me portado diante de Deus com toda a boa consciência."

[[v51-23-2]]

^<<v51-23-2,2>>^ Nisto Ananias, príncipe dos sacerdotes, ordenou aos que estavam junto dele que lhe batessem na boca. (ver nota)

[[v51-23-3]]

^<<v51-23-3,3>>^ Então disse-lhe Paulo: "Deus te baterá a ti, parede branqueada. Tu estás sentado a julgar-me segundo a lei, e contra a lei ordenas que me batam?" (ver nota)

[[v51-23-4]]

^<<v51-23-4,4>>^ Os assistentes disseram: "Tu injurias o sumo sacerdote de Deus!"

[[v51-23-5]]

^<<v51-23-5,5>>^ Paulo respondeu: "Eu não sabia, irmãos, que é o príncipe dos sacerdotes. Efectivamente está escrito: Não dirás mal do príncipe do teu povo (Ex. 22,28)."

[[v51-23-6]]

^<<v51-23-6,6>>^ Ora, sabendo Paulo que uma parte do Sinédrio era de saduceus e outra de fariseus, exclamou em alta voz, diante deles: "Irmãos, eu sou fariseu, filho de fariseus, e sou julgado por causa da esperança na ressurreição dos mortos." (ver nota)

[[v51-23-7]]

^<<v51-23-7,7>>^ Quando disse isto, estabeleceu-se uma grande dissenção entre os fariseus e os saduceus, e dividiu-se a assembleia.

[[v51-23-8]]

^<<v51-23-8,8>>^ Porque os saduceus dizem que não há ressurreição, nem anjo, nem espírito; ao passo que os fariseus reconhecem ambas as coisas.

[[v51-23-9]]

^<<v51-23-9,9>>^ Houve grande vozearia. Levantando-se alguns fariseus, altercavam dizendo: "Não achamos mal algum neste homem; quem sabe se lhe falou algum espírito ou anjo?"

[[v51-23-10]]

^<<v51-23-10,10>>^ Como a discórdia aumentava de violência, temendo o tribuno que Paulo fosse despedaçado por eles, mandou que descessem os soldados, que o tirassem do meio deles e o levassem à fortaleza.

[[v51-23-11]]

^<<v51-23-11,11>>^ Na noite seguinte, aparecendo-lhe o Senhor, disse-lhe: "Coragem! Assim como deste testemunho de mim em Jerusalém, assim importa que também o dês em Roma."

[[v51-23-12]]

^<<v51-23-12,12>>^ Quando se fez dia, coligaram-se alguns judeus e juraram com imprecações contra eles próprios que não haviam de comer nem beber enquanto não matassem contra Paulo.

[[v51-23-13]]

^<<v51-23-13,13>>^ Eram mais de quarenta os que tinham feito esta conjuração.

[[v51-23-14]]

^<<v51-23-14,14>>^ Foram ter com os príncipes dos sacerdotes e com os anciães, e disseram: "Nós obrigamo-nos por voto, sob pena de maldição, a não tomar nenhum alimento até que matemos Paulo.

[[v51-23-15]]

^<<v51-23-15,15>>^ Vós, pois, agora, com o Sinédrio, fazei saber ao tribuno que o conduza à vossa presença, como se fosse para descobrir alguma coisa de mais seguro acerca dele. Nós estaremos preparados para o matar, antes que ele chegue."

[[v51-23-16]]

^<<v51-23-16,16>>^ Mas um filho da irmã de Paulo, tendo tido conhecimento desta conspiração, foi à fortaleza, entrou nela e avisou Paulo.

[[v51-23-17]]

^<<v51-23-17,17>>^ Então Paulo, chamando um dos centuriões, disse: "Leva este jovem ao tribuno, porque tem alguma coisa a comunicar-lhe."

[[v51-23-18]]

^<<v51-23-18,18>>^ Tomando-o ele consigo, o levou ao tribuno e disse: "O preso Paulo rogou-me que trouxesse à tua presença este jovem, que tem alguma coisa a dizer-te."

[[v51-23-19]]

^<<v51-23-19,19>>^ O tribuno, tomando-o pela mão, o levou à parte e perguntou-lhe: "Que tens tu a comunicar-me?"

[[v51-23-20]]

^<<v51-23-20,20>>^ Ele disse: "Os Judeus combinaram pedir-te que amanhã apresentes Paulo ao Sinédrio, sob o pretexto de examinarem mais a fundo a sua causa.

[[v51-23-21]]

^<<v51-23-21,21>>^ Mas não acredites, porque mais de quarenta homens deles lhe preparam uma armadilha, os quais juraram, sob pena de maldição, não comer nem beber, enquanto o não matarem, e agora estão preparados, esperando que lhes concedas o que pedem."

[[v51-23-22]]

^<<v51-23-22,22>>^ Então o tribuno despediu o jovem, mandando-lhe que a ninguém dissesse que lhe tinha dado aviso disto.

[[v51-23-23]]

^<<v51-23-23,23>>^ Chamando, então, dois centuriões, disse-lhes: "Tende prontos à hora terceira da noite duzentos soldados para que vão até Cesareia, e setenta cavaleiros e duzentos lanceiros.

[[v51-23-24]]

^<<v51-23-24,24>>^ Aparelhai as cavalgaduras, para nelas fazer montar Paulo, a fim de o conduzir são e salvo ao presidente Félix."

[[v51-23-25]]

^<<v51-23-25,25>>^ Redigiu uma carta nos seguintes termos:

[[v51-23-26]]

^<<v51-23-26,26>>^ "Cláudio Lisias ao óptimo presidente Félix, saúde!

[[v51-23-27]]

^<<v51-23-27,27>>^ Este homem foi preso pelos Judeus, e estava prestes a ser morto por eles, mas, sobrevindo eu com os soldados, o livrei, tendo sabido que é cidadão romano.

[[v51-23-28]]

^<<v51-23-28,28>>^ Querendo saber de que delito o acusavam, levei-o ao Sinédrio.

[[v51-23-29]]

^<<v51-23-29,29>>^ Achei que era acusado por questões da lei deles, sem haver delito algum digno de morte ou prisão.

[[v51-23-30]]

^<<v51-23-30,30>>^ Tendo chegado a mim a notícia de uma armadilha que lhe estavam a preparar, eu to envio, intimando também os acusadores a que falem diante de ti. Adeus."

[[v51-23-31]]

^<<v51-23-31,31>>^ Os soldados, pois, conforme a ordem que tinham, tomaram Paulo com eles e levaram-no de noite a Antípatro.

[[v51-23-32]]

^<<v51-23-32,32>>^ No dia seguinte, deixando que os cavaleiros fossem com ele, voltaram para a fortaleza.

[[v51-23-33]]

^<<v51-23-33,33>>^ Aqueles, tendo chegado a Cesareia e tendo entregado a carta ao presidente, apresentaram-lhe Paulo.

[[v51-23-34]]

^<<v51-23-34,34>>^ Ele, depois de a ler e de perguntar de que província era, sabendo que era da Cilicia, disse:

[[v51-23-35]]

^<<v51-23-35,35>>^ "Ouvir-te-ei quando chegarem os teus acusadores." E mandou que Paulo fosse guardado no pretório (chamado) de Herodes.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-022.adoc#v51-22-0[&#60; Capítulo Anterior] | <<v51-23-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-024.adoc#v51-24-0[Próximo Capítulo &#62;]