include::./index.adoc[]

[[v51-10-0]]
=== Atos dos Apóstolos, 10
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Atos dos Apóstolos 10 relata a história de Cornélio, um centurião romano que teve uma visão e enviou mensageiros a Pedro para que ele viesse até ele. Pedro teve sua própria visão, que o levou a compreender que Deus não faz acepção de pessoas, e pregou o evangelho para Cornélio e sua família. Os versículos relacionados com os temas abordados em Atos dos Apóstolos 10 são:
* Atos dos Apóstolos 10:34-35: "Então Pedro começou a falar: 'Agora percebo verdadeiramente que Deus não trata as pessoas com parcialidade, mas de todas as nações aceita todo aquele que o teme e faz o que é justo.'" Neste versículo, Pedro compreende a mensagem de sua visão e percebe que Deus não faz distinção entre as pessoas com base em sua nacionalidade ou origem étnica.
* Atos dos Apóstolos 10:44-45: "Enquanto Pedro ainda falava estas palavras, o Espírito Santo desceu sobre todos os que ouviam a mensagem. Os fiéis circuncisos que haviam vindo com Pedro ficaram admirados, porque o dom do Espírito Santo tinha sido derramado até mesmo sobre os gentios." Este versículo mostra que, apesar das expectativas dos judeus convertidos de que apenas os circuncisos seriam agraciados com o Espírito Santo, este foi derramado sobre todos os que ouviam a mensagem de Pedro, incluindo os gentios.
* Atos dos Apóstolos 10:38: "Como Deus ungiu a Jesus de Nazaré com o Espírito Santo e poder, e como ele andou por toda parte fazendo o bem e curando todos os oprimidos pelo Diabo, porque Deus estava com ele." Neste versículo, Pedro resume o ministério de Jesus e enfatiza que Deus estava com ele.
* Atos dos Apóstolos 10:43: "Todos os profetas dão testemunho dele, de que todo aquele que nele crê recebe o perdão dos pecados mediante o seu nome." Aqui, Pedro proclama que o perdão dos pecados está disponível para todos aqueles que creem em Jesus.
* Atos dos Apóstolos 10:47-48: "Então Pedro disse: 'Será que alguém pode recusar a água do batismo a estas pessoas que receberam o Espírito Santo da mesma forma que nós?' E ordenou que fossem batizados em nome de Jesus Cristo. Então pediram a Pedro que ficasse com eles por alguns dias." Este versículo mostra que Pedro reconheceu a validade da fé de Cornélio e de sua família e os batizou em nome de Jesus Cristo.
****

[[v51-10-1]]

^<<v51-10-1,1>>^ Havia então em Cesareia um homem chamado Cornélio, centurião da coorte chamada Itálica,

[[v51-10-2]]

^<<v51-10-2,2>>^ religioso e temente a Deus com toda a sua casa, o qual dava muitas esmolas ao povo e orava a Deus assiduamente.

[[v51-10-3]]

^<<v51-10-3,3>>^ Este viu claramente numa visão, cerca da hora nona, que um anjo de Deus se apresentava diante dele e lhe dizia: "Cornélio."

[[v51-10-4]]

^<<v51-10-4,4>>^ Ele, fixando os olhos no anjo, possuído de temor, disse: "Que é isto, Senhor?" O anjo respondeu-lhe: "As tuas orações e as tuas esmolas subiram como um memorial à presença de Deus.

[[v51-10-5]]

^<<v51-10-5,5>>^ Agora envia homens a Jope e manda vir um certo Simão, que tem por sobrenome Pedro,

[[v51-10-6]]

^<<v51-10-6,6>>^ o qual se encontra hospedado em casa de um tal Simão, curtidor, cuja casa fica junto ao mar."

[[v51-10-7]]

^<<v51-10-7,7>>^ Tendo-se retirado o anjo que lhe falava, (Cornélio) chamou dois dos seus criados e um soldado temente a Deus, daqueles que estavam às suas ordens,

[[v51-10-8]]

^<<v51-10-8,8>>^ e, tendo-lhes contado tudo isto, os enviou a Jope.

[[v51-10-9]]

^<<v51-10-9,9>>^ No dia seguinte, indo eles em viagem e estando perto da cidade, subiu Pedro à parte superior da casa para fazer oração, cerca da hora sexta.

[[v51-10-10]]

^<<v51-10-10,10>>^ Como tivesse fome, quis comer. Mas, enquanto lho preparavam, caiu em êxtase:

[[v51-10-11]]

^<<v51-10-11,11>>^ viu o céu aberto, e descer um objecto, semelhante a um grande lençol, suspenso pelos quatro cantos, que baixava para a terra,

[[v51-10-12]]

^<<v51-10-12,12>>^ no qual havia de todos os quadrúpedes, répteis da terra e aves do céu.

[[v51-10-13]]

^<<v51-10-13,13>>^ Ouviu esta voz: "Levanta-te, Pedro, mata e come."

[[v51-10-14]]

^<<v51-10-14,14>>^ Mas Pedro disse: "De nenhum modo. Senhor, porque nunca comi nada manchado ou impuro."

[[v51-10-15]]

^<<v51-10-15,15>>^ Mas a voz tornou-lhe segunda vez a dizer: "Não chames impuro ao que Deus declarou puro."

[[v51-10-16]]

^<<v51-10-16,16>>^ Isto repetiu-se três vezes, e logo o objecto foi retirado para o céu.

[[v51-10-17]]

^<<v51-10-17,17>>^ Enquanto Pedro estava incerto dentro de si sobre o que queria significar a visão que tinha tido, eis que os homens enviados por Cornélio, perguntando pela casa de Simão, chegaram à porta.

[[v51-10-18]]

^<<v51-10-18,18>>^ Tendo chamado, perguntaram se estava ali hospedado Simão, que tinha por sobrenome Pedro.

[[v51-10-19]]

^<<v51-10-19,19>>^ Estando Pedro a pensar na visão, disse-lhe o Espírito: "Eis três homens que te procuram.

[[v51-10-20]]

^<<v51-10-20,20>>^ Levanta-te, pois, desce e vai com eles sem duvidar, porque fui eu que os enviei."

[[v51-10-21]]

^<<v51-10-21,21>>^ Descendo Pedro para ir ter com os homens, disse: "Aqui me tendes, sou eu quem buscais; qual é a causa por que viestes aqui?"

[[v51-10-22]]

^<<v51-10-22,22>>^ Eles disseram: "O centurião Cornélio, homem justo e temente a Deus, tido em consideração por toda a nação dos Judeus, recebeu ordem de um anjo santo para te mandar chamar a sua casa, para ouvir as tuas palavras."

[[v51-10-23]]

^<<v51-10-23,23>>^ Então (Pedro), mandando-os entrar, os hospedou. No dia seguinte, levantando-se, partiu com eles, em companhia de alguns irmãos de Jope.

[[v51-10-24]]

^<<v51-10-24,24>>^ No dia seguinte, entraram em Cesareia. Cornélio estava-os esperando, tendo convidado os seus parentes e mais íntimos amigos.

[[v51-10-25]]

^<<v51-10-25,25>>^ Quando Pedro estava para entrar, saiu Cornélio a recebê-lo, prostrando-se a seus pés.

[[v51-10-26]]

^<<v51-10-26,26>>^ Mas Pedro o levantou, dizendo: "Levanta-te, que eu também sou um homem."

[[v51-10-27]]

^<<v51-10-27,27>>^ E, conversando com ele, entrou em casa, onde encontrou muitas pessoas reunidas.

[[v51-10-28]]

^<<v51-10-28,28>>^ Disse-lhes: "Vós sabeis como é coisa abominável, para um homem judeu, o unir-se a um estrangeiro ou aproximar-se dele; mas Deus mostrou-me que a nenhum homem chamasse manchado ou impuro.

[[v51-10-29]]

^<<v51-10-29,29>>^ Por isso vim sem hesitação, logo que fui chamado. Pergunto, pois, por que motivo me chamastes?"

[[v51-10-30]]

^<<v51-10-30,30>>^ Cornélio disse: "Faz hoje quatro dias que eu estava orando em minha casa, à hora nona, quando apareceu diante de mim um homem de vestes resplandecentes, que me disse:

[[v51-10-31]]

^<<v51-10-31,31>>^ Cornélio, a tua oração foi atendida, e as tuas esmolas foram lembradas na presença de Deus.

[[v51-10-32]]

^<<v51-10-32,32>>^ Manda, pois, a Jope chamar Simão, que tem por sobrenome Pedro, o qual está hospedado em casa de Simão, curtidor, junto do mar.

[[v51-10-33]]

^<<v51-10-33,33>>^ Por isso mandei imediatamente chamar-te, e tu fizeste bem em vir. Agora todos nós, reunidos aqui, na presença de Deus, estamos dispostos a ouvir tudo o que o Senhor te ordenou que nos digas."

[[v51-10-34]]

^<<v51-10-34,34>>^ Então Pedro, tomando a palavra, disse: "Na verdade reconheço que Deus não faz acepção de pessoas,

[[v51-10-35]]

^<<v51-10-35,35>>^ mas que, em qualquer nação, aquele que o teme e pratica a justiça, lhe é agradável.

[[v51-10-36]]

^<<v51-10-36,36>>^ Deus enviou a sua palavra aos filhos de Israel, anunciando-lhes a boa nova da paz por meio de Jesus Cristo, que é o Senhor de todos.

[[v51-10-37]]

^<<v51-10-37,37>>^ Sabeis o que aconteceu por toda a Judeia, começando pela Galileia, depois do baptismo que João pregou:

[[v51-10-38]]

^<<v51-10-38,38>>^ Como Deus ungiu com o Espírito Santo e com poder a Jesus de Nazaré, o qual andou, de lugar em lugar, fazendo bem e sarando todos os oprimidos do demônio, porque Deus era com ele.

[[v51-10-39]]

^<<v51-10-39,39>>^ Nós somos testemunhas de tudo o que ele fez no país dos Judeus e em Jerusalém; mas mataram-no, suspendendo-o num madeiro.

[[v51-10-40]]

^<<v51-10-40,40>>^ Deus, porém, ressuscitou-o, ao terceiro dia, e fez que se manifestasse,

[[v51-10-41]]

^<<v51-10-41,41>>^ não a todo o povo, mas às testemunhas que Deus tinha escolhido antes, a nós que comemos e bebemos com ele, depois que ressuscitou dos mortos.

[[v51-10-42]]

^<<v51-10-42,42>>^ Mandou-nos pregar ao povo e dar testemunho de que ele é o que Deus constituiu juiz dos vivos e dos mortos.

[[v51-10-43]]

^<<v51-10-43,43>>^ Dele dão este testemunho todos os profetas: todo o que crê nele, recebe por meio do seu nome, a remissão dos pecados." (ver nota)

[[v51-10-44]]

^<<v51-10-44,44>>^ Estando Pedro ainda proferindo estas palavras, desceu o Espírito Santo sobre todos os que ouviam a pregação.

[[v51-10-45]]

^<<v51-10-45,45>>^ E os fiéis circuncisos, que tinham ido com Pedro, admiraram-se de ver que a graça do Espírito Santo foi também difundida sobre os gentios, (ver nota)

[[v51-10-46]]

^<<v51-10-46,46>>^ porque os ouviam falar línguas e glorificar a Deus. Então Pedro disse:

[[v51-10-47]]

^<<v51-10-47,47>>^ "Porventura pode alguém recusar a água do baptismo àqueles que receberam o Espírito Santo como nós?"

[[v51-10-48]]

^<<v51-10-48,48>>^ E mandou que fossem baptizados em nome de Jesus Cristo. Então rogaram-lhe que ficasse alguns dias com eles.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-009.adoc#v51-9-0[&#60; Capítulo Anterior] | <<v51-10-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-011.adoc#v51-11-0[Próximo Capítulo &#62;]