include::./index.adoc[]

[[v51-9-0]]
=== Atos dos Apóstolos, 9
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Em Atos dos Apóstolos 9 é narrada a conversão de Saulo de Tarso, que se tornaria o apóstolo Paulo. No capítulo, é descrito como Saulo, que era conhecido por perseguir os cristãos, teve um encontro com Jesus no caminho de Damasco e, a partir daí, passou a pregar o evangelho. Os versículos relacionados com os temas abordados em Atos 9 são:
* Romanos 8:28: "E sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus, daqueles que são chamados segundo o Seu propósito." Este versículo pode ser relacionado à conversão de Saulo, que era um perseguidor dos cristãos, mas que acabou se tornando um grande apóstolo e propagador da mensagem de Jesus.
* Efésios 2:8-9: "Porque pela graça sois salvos, mediante a fé; e isto não vem de vós, é dom de Deus; não de obras, para que ninguém se glorie." A conversão de Saulo é um exemplo claro da graça de Deus, que o escolheu e o transformou, independentemente das suas próprias obras.
* Gálatas 2:20: "Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim; e a vida que agora vivo na carne, vivo-a pela fé no Filho de Deus, o qual me amou e se entregou a Si mesmo por mim." Este versículo pode ser relacionado à transformação que ocorreu na vida de Saulo, que deixou para trás a sua vida anterior e passou a viver pela fé em Jesus.
* Filipenses 3:7-8: "Mas o que para mim era lucro, isto considerei perda por causa de Cristo. Sim, na verdade, considero tudo como perda, por causa da sublimidade do conhecimento de Cristo Jesus, meu Senhor; por amor do qual perdi todas as coisas e as considero como refugo, para ganhar a Cristo." A história de Saulo mostra claramente como ele abandonou sua posição privilegiada na sociedade judaica e considerou tudo como perda por causa de Cristo.
* Colossenses 1:24: "Agora me regozijo no meio dos meus sofrimentos por vós e cumpro na minha carne o que resta das aflições de Cristo, por causa do seu corpo, que é a igreja." Paulo foi um apóstolo que sofreu muito em sua vida, mas que nunca deixou de se alegrar no Senhor e de se dedicar à propagação do evangelho.
****

[[v51-9-1]]

^<<v51-9-1,1>>^ Entretanto Saulo, respirando ainda ameaças e morte contra os discípulos do Senhor, apresentou-se ao sumo sacerdote

[[v51-9-2]]

^<<v51-9-2,2>>^ e pediu-lhe cartas para as sinagogas de Damasco, com o fim de levar presos a Jerusalém quantos adeptos deste caminho (doutrina) encontrasse, homens e mulheres.

[[v51-9-3]]

^<<v51-9-3,3>>^ Prosseguindo ele a sua jornada, aconteceu que, ao aproximar-se de Damasco, subitamente o cercou uma luz fulgurante vinda do céu.

[[v51-9-4]]

^<<v51-9-4,4>>^ Caindo por terra, ouviu uma voz que lhe dizia: "Saulo, Saulo, por que me persegues?" (ver nota)

[[v51-9-5]]

^<<v51-9-5,5>>^ Ele disse: "Quem és tu, Senhor?" Ele (respondeu); "Eu sou Jesus, a quem tu persegues, (ver nota)

[[v51-9-6]]

^<<v51-9-6,6>>^ Levanta-te, entra na cidade, e ai te será dito o que deves fazer."

[[v51-9-7]]

^<<v51-9-7,7>>^ Aqueles que o acompanhavam, estavam estupefactos, ouvindo a voz, mas não vendo ninguém.

[[v51-9-8]]

^<<v51-9-8,8>>^ Saulo levantou-se da terra e, tendo os olhos abertos, não via nada. Eles, porém, levando-o pela mão, o conduziram a Damasco.

[[v51-9-9]]

^<<v51-9-9,9>>^ Esteve ali três dias sem ver, sem comer nem beber.

[[v51-9-10]]

^<<v51-9-10,10>>^ Ora em Damasco havia um discípulo chamado Ananias. O Senhor, numa visão, disse-lhe: "Ananias!" Ele respondeu: "Eis-me aqui, Senhor."

[[v51-9-11]]

^<<v51-9-11,11>>^ O Senhor disse-lhe: "Levanta-te, vai à rua chamada Direita, e busca em casa de Judas um (homem) de Tarso, chamado Saulo, porque ei-lo que está orando."

[[v51-9-12]]

^<<v51-9-12,12>>^ (Neste mesmo tempo Saulo, em uma visão) viu um homem, chamado Ananias, que entrava e lhe impunha as mãos para recobrar a vista.

[[v51-9-13]]

^<<v51-9-13,13>>^ Ananias respondeu: "Senhor, tenho ouvido dizer a muitos quantos males este homem fez aos teus santos em Jerusalém:

[[v51-9-14]]

^<<v51-9-14,14>>^ e aqui ele tem poder dos príncipes dos sacerdotes para prender todos os que invocam o teu nome."

[[v51-9-15]]

^<<v51-9-15,15>>^ Mas o Senhor disse-lhe: "Vai, porque este é um instrumento escolhido por mim para levar o meu nome diante das gentes, dos reis e dos filhos de Israel.

[[v51-9-16]]

^<<v51-9-16,16>>^ Mostrar-lhe-ei quanto deve sofrer pelo meu nome."

[[v51-9-17]]

^<<v51-9-17,17>>^ Foi Ananias e entrou na casa, e, impondo-lhe as mãos, disse: "Irmão Saulo, o Senhor Jesus, que te apareceu no caminho por onde vinhas, enviou-me para que recuperes a vista e fiques cheio do Espírito Santo."

[[v51-9-18]]

^<<v51-9-18,18>>^ Imediatamente, lhe caíram dos olhos umas como escamas, recuperou a vista, levantou-se e foi baptizado.

[[v51-9-19]]

^<<v51-9-19,19>>^ Depois que tomou alimento, recuperou as forças. Esteve alguns dias com os discípulos que se encontravam em Damasco.

[[v51-9-20]]

^<<v51-9-20,20>>^ Imediatamente, começou a pregar nas sinagogas que Jesus era o Filho de Deus.

[[v51-9-21]]

^<<v51-9-21,21>>^ Pasmavam todos os que ouviam e diziam: "Não é este aquele que perseguia em Jerusalém os que invocavam este nome, e não veio ele cá com o fim de os levar presos aos príncipes dos sacerdotes"

[[v51-9-22]]

^<<v51-9-22,22>>^ Entretanto Saulo muito mais se esforçava e confundia os Judeus que habitavam em Damasco, demonstrando-lhes que Jesus é o Cristo.

[[v51-9-23]]

^<<v51-9-23,23>>^ Tendo-se passado muitos dias, os Judeus em conselho resolveram matá-lo.

[[v51-9-24]]

^<<v51-9-24,24>>^ Porém Saulo foi advertido das suas ciladas. Eles faziam guarda às portas (da cidade), de dia e de noite, para o matarem.

[[v51-9-25]]

^<<v51-9-25,25>>^ Mas os discípulos, tomando-o de noite, desceram-no numa cesta, pela muralha.

[[v51-9-26]]

^<<v51-9-26,26>>^ Tendo chegado a Jerusalém, procurava juntar-se com os discípulos, mas todos o temiam, não acreditando que ele fosse discípulo.

[[v51-9-27]]

^<<v51-9-27,27>>^ Então Barnabé, tomando-o consigo, o levou aos Apóstolos, e ele contou-lhes como tinha visto o Senhor no caminho, o qual lhe tinha falado, e como em Damasco pregara corajosamente em nome de Jesus.

[[v51-9-28]]

^<<v51-9-28,28>>^ Desde então ficou com eles em Jerusalém, entrando e saindo, e pregando corajosamente em nome do Senhor.

[[v51-9-29]]

^<<v51-9-29,29>>^ Falava e discutia com os Helenistas; mas eles procuravam matá-lo.

[[v51-9-30]]

^<<v51-9-30,30>>^ Tendo sabido isto os irmãos, conduziram-no a Cesareia, e dai o enviaram a Tarso.

[[v51-9-31]]

^<<v51-9-31,31>>^ Tinha então paz a Igreja por toda a Judeia, Galileia e Samaria, edificava-se e caminhava no temor do Senhor, e com a assistência do Espirito Santo ia-se multiplicando.

[[v51-9-32]]

^<<v51-9-32,32>>^ Ora aconteceu que Pedro, indo por toda a parte, de cidade em cidade, foi também aos santos que habitavam em Lida.

[[v51-9-33]]

^<<v51-9-33,33>>^ Encontrou ali um homem, chamado Eneias, que havia oito anos jazia num leito, porque estava paralítico.

[[v51-9-34]]

^<<v51-9-34,34>>^ Pedro disse-lhe: "Eneias, Jesus Cristo cura-te. Levanta-te, e faze tu mesmo a tua cama." Imediatamente se levantou.

[[v51-9-35]]

^<<v51-9-35,35>>^ Viram-no todos os que habitavam em Lida e em Sarou, os quais se converteram ao Senhor.

[[v51-9-36]]

^<<v51-9-36,36>>^ Havia em Jope, entre os discípulos, uma mulher, chamada Tabita, (palavra) que, traduzida (em grego), quer dizer Dorcas. Estava cheia de boas obras e de esmolas que fazia.

[[v51-9-37]]

^<<v51-9-37,37>>^ Aconteceu naqueles dias que, caindo enferma, morreu. Tendo-a lavado, puseram-na num quarto alto. (ver nota)

[[v51-9-38]]

^<<v51-9-38,38>>^ Como Lida estava perto de Jope, os discípulos, ouvindo dizer que Pedro se encontrava lá, enviaram-lhe dois homens, rogando-lhe: "Não te demores em vir ter convosco."

[[v51-9-39]]

^<<v51-9-39,39>>^ Pedro, levantando-se, foi com eles. Logo que chegou, levaram-no ao quarto alto, e cercaram-no todas as viúvas, chorando e mostrando-lhe as túnicas e os vestidos que Dorcas em vida lhes fazia.

[[v51-9-40]]

^<<v51-9-40,40>>^ Então Pedro, tendo mandado sair todos, pondo-se de joelhos, orou. Depois, voltando-se para o corpo, disse: "Tabita, levanta-te." Ela abriu os olhos, e, vendo Pedro, sentou-se.

[[v51-9-41]]

^<<v51-9-41,41>>^ Ele a fez levantar, dando-lhe a mão. Então, tendo chamado os santos e as viúvas, lha entregou viva.

[[v51-9-42]]

^<<v51-9-42,42>>^ Este facto foi sabido por toda Jope, e muitos creram no Senhor.

[[v51-9-43]]

^<<v51-9-43,43>>^ Pedro ficou em Jope muitos dias, em casa de um certo Simão, curtidor.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-008.adoc#v51-8-0[&#60; Capítulo Anterior] | <<v51-9-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-010.adoc#v51-10-0[Próximo Capítulo &#62;]