include::./index.adoc[]

[[v51-15-0]]
=== Atos dos Apóstolos, 15
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Em Atos dos Apóstolos 15, os apóstolos e anciãos se reúnem para discutir a questão da circuncisão entre os gentios convertidos ao cristianismo. Depois de uma discussão, eles chegam a uma decisão de que os gentios não precisam ser circuncidados para serem salvos. Aqui estão cinco versículos relacionados com os temas abordados em Atos dos Apóstolos 15:
* Gálatas 5:2-3: "Eis que eu, Paulo, vos digo que, se vos deixardes circuncidar, Cristo de nada vos aproveitará. E de novo protesto a todo o homem, que se deixar circuncidar, que está obrigado a guardar toda a lei." Neste versículo, Paulo está alertando os cristãos da Galácia sobre os perigos da circuncisão e como isso pode afetar sua salvação.
* Romanos 2:28-29: "Pois não é judeu quem o é exteriormente, nem é circuncisão a que o é exteriormente na carne. Mas é judeu quem o é interiormente, e circuncisão é a do coração, no espírito, não na letra; cujo louvor não provém dos homens, mas de Deus." Aqui, Paulo está explicando que a verdadeira circuncisão é a do coração e que a salvação não depende da circuncisão física.
* Colossenses 2:11: "Nele também fostes circuncidados com circuncisão não feita por mão no despojar do corpo da carne, a circuncisão de Cristo." Este versículo fala sobre a circuncisão espiritual que acontece através da fé em Cristo.
* Filipenses 3:3: "Porque a circuncisão somos nós, que servimos a Deus no espírito, e nos gloriamos em Cristo Jesus, e não confiamos na carne." Neste versículo, Paulo está enfatizando a importância da circuncisão espiritual e como isso é mais importante do que a circuncisão física.
* Atos dos Apóstolos 15:28-29: "Porque pareceu bem ao Espírito Santo e a nós não vos impor mais encargo algum, senão estas coisas necessárias: que vos abstenhais das coisas sacrificadas aos ídolos, e do sangue, e da carne sufocada, e da prostituição, das quais coisas bem fazeis se vos guardardes." Este versículo é parte da decisão tomada pelos apóstolos e anciãos em relação à questão da circuncisão e quais outros requisitos os gentios convertidos precisavam seguir.
****

[[v51-15-1]]

^<<v51-15-1,1>>^ Ora alguns vindos da Judeia ensinavam aos irmãos: "Se vos não circuncidais segundo o rito de Moisés, não podeis ser salvos."

[[v51-15-2]]

^<<v51-15-2,2>>^ Tendo-se levantado uma discussão e uma viva altercação entre eles e Paulo e Barnabé, resolveram que fossem Paulo e Barnabé e alguns dos outros consultar os Apóstolos e os presbíteros de Jerusalém sobre esta questão.

[[v51-15-3]]

^<<v51-15-3,3>>^ Eles, pois, acompanhados (durante algum tempo) pelos membros da Igreja, iam passando pela Fenícia e pela Samaria, contando a conversão dos gentios, o que causava grande contentamento a todos os irmãos.

[[v51-15-4]]

^<<v51-15-4,4>>^ Tendo chegado a Jerusalém, foram recebidos pela Igreja, pelos Apóstolos e pelos anciães, e contaram todas as coisas que havia feito Deus com eles.

[[v51-15-5]]

^<<v51-15-5,5>>^ Mas levantaram-se alguns da seita dos fariseus, que tinham abraçado a fé, dizendo que era necessário (que os gentios) fossem circuncidados e que se lhes intimasse a observância da lei de Moisés.

[[v51-15-6]]

^<<v51-15-6,6>>^ Reuniram-se, pois, os Apóstolos e os presbíteros para examinar esta questão.

[[v51-15-7]]

^<<v51-15-7,7>>^ Tendo-se suscitado uma grande discussão, levantando-se Pedro, disse-lhes: "Irmãos, sabeis que Deus, há muito tempo, me escolheu entre vós para que da minha boca ouvissem os gentios a palavra do Evangelho e abraçassem a fé.

[[v51-15-8]]

^<<v51-15-8,8>>^ Deus, que conhece os corações, deu testemunho em favor deles, conferindo-lhes o Espírito Santo, como também a nós,

[[v51-15-9]]

^<<v51-15-9,9>>^ e não fez diferença alguma entre nós e eles, purificando com a fé os seus corações.

[[v51-15-10]]

^<<v51-15-10,10>>^ Logo, por que tentais agora a Deus, impondo um jugo sobre as cervizes dos discípulos, que nem nossos pais, nem nós podemos suportar?

[[v51-15-11]]

^<<v51-15-11,11>>^ Pelo contrário, pela graça do Senhor Jesus Cristo, cremos ser salvos, do mesmo modo que eles."

[[v51-15-12]]

^<<v51-15-12,12>>^ Toda a assembleia se calou; e ouviam Barnabé e Paulo contar todos os milagres e prodígios que Deus tinha feito por intervenção deles entre os gentios.

[[v51-15-13]]

^<<v51-15-13,13>>^ Depois que se calaram, Tiago tomou a palavra, dizendo: "Irmãos, ouvi-me.

[[v51-15-14]]

^<<v51-15-14,14>>^ Simeão contou como Deus, desde o princípio, cuidou em tirar do meio dos gentios um povo que fosse seu. (ver nota)

[[v51-15-15]]

^<<v51-15-15,15>>^ Com isto concordaram as palavras dos profetas, como está escrito:

[[v51-15-16]]

^<<v51-15-16,16>>^ Depois disto voltarei e reedificarei o tabernáculo de David que caiu, repararei as suas ruínas e o levantarei,

[[v51-15-17]]

^<<v51-15-17,17>>^ a fim de que busquem a Deus todos os outros homens e todas as gentes, sobre as quais tem sido invocado o meu nome, diz o Senhor, que faz estas coisas,

[[v51-15-18]]

^<<v51-15-18,18>>^ determinadas desde a eternidade (Am. 9, 11-12).

[[v51-15-19]]

^<<v51-15-19,19>>^ Por isso sou de opinião que se não devem inquietar os que, dentre os gentios, se convertem a Deus,

[[v51-15-20]]

^<<v51-15-20,20>>^ mas que se lhes escreva que se abstenham das contaminações dos ídolos, da fornicação, das carnes sufocadas e do sangue. (ver nota)

[[v51-15-21]]

^<<v51-15-21,21>>^ Porque Moisés, desde tempos antigos, tem em cada cidade homens que o pregam nas sinagogas, onde é lido todos sábados."

[[v51-15-22]]

^<<v51-15-22,22>>^ Então pareceu bem aos Apóstolos e aos presbíteros, com toda a Igreja, eleger algumas pessoas dentre eles, e enviá-las a Antioquia, com Paulo e Barnabé. (Elegeram) Judas, que tinha o sobrenome de Barsabas, e Silas, pessoas eminentes entre os irmãos,

[[v51-15-23]]

^<<v51-15-23,23>>^ mandando por mão deles esta carta: "Os Apóstolos e os presbíteros irmãos, aos irmãos convertidos dos gentios, que estão em Antioquia, na Síria e na Cilícia, saúde.

[[v51-15-24]]

^<<v51-15-24,24>>^ Tendo nós sabido que alguns, indo do meio de nós, sem nenhuma ordem da nossa parte, vos perturbaram com discursos que agitaram as vossas almas,

[[v51-15-25]]

^<<v51-15-25,25>>^ aprouve-nos, depois de nos termos reunido, escolher alguns homens, e enviá-los a vós com os nossos muito amados Barnabé e Paulo,

[[v51-15-26]]

^<<v51-15-26,26>>^ homens que têm exposto as suas vidas pelo nome de Nosso Senhor Jesus Cristo.

[[v51-15-27]]

^<<v51-15-27,27>>^ Enviamos portanto Judas e Silas, que vos exporão as mesmas coisas e de viva voz.

[[v51-15-28]]

^<<v51-15-28,28>>^ Com efeito, pareceu bem ao Espírito Santo e a nós não vos impor mais encargos além destes indispensáveis:

[[v51-15-29]]

^<<v51-15-29,29>>^ Que vos abstenhais das coisas imoladas aos ídolos, do sangue, das carnes sufocadas e da fornicação, das quais coisas fareis bem em vos guardar. Adeus."

[[v51-15-30]]

^<<v51-15-30,30>>^ Eles, pois, tendo-se despedido, foram a Antioquia, e, tendo reunido a multidão (dos fiéis), entregaram a carta.

[[v51-15-31]]

^<<v51-15-31,31>>^ Tendo-a eles lido, encheram-se de contentamento pela coragem que lhes dava.

[[v51-15-32]]

^<<v51-15-32,32>>^ Judas e Silas, como eram também profetas, consolaram e confortaram com muitas palavras os irmãos.

[[v51-15-33]]

^<<v51-15-33,33>>^ Tendo-se demorado ali algum tempo, foram remetidos em paz pelos irmãos aos que lhos tinham enviado.

[[v51-15-34]]

^<<v51-15-34,34>>^ Aprouve, porém, a Silas ficar ali, e Judas voltou só para Jerusalém. (ver nota)

[[v51-15-35]]

^<<v51-15-35,35>>^ Paulo e Barnabé demoraram-se em Antioquia, ensinando e evangelizando com outros muitos a palavra do Senhor.

[[v51-15-36]]

^<<v51-15-36,36>>^ Passados alguns dias, disse Paulo a Barnabé: "Tornem os a ir visitar os irmãos por todas as cidades em que temos pregado a palavra do Senhor, para ver em que estado se encontram."

[[v51-15-37]]

^<<v51-15-37,37>>^ Barnabé queria levar consigo também João, que tinha por sobrenome Marcos.

[[v51-15-38]]

^<<v51-15-38,38>>^ Paulo, porém, procurava fazer-lhe ver que um homem, que se tinha separado deles na Panfília e não tinha ido com eles àquela obra, não devia ser admitido.

[[v51-15-39]]

^<<v51-15-39,39>>^ E houve tal desacordo entre eles, que se separaram um do outro. Barnabé, levando consigo Marcos, embarcou para Chipre.

[[v51-15-40]]

^<<v51-15-40,40>>^ Paulo, tendo escolhido Silas, partiu, recomendado pelos irmãos à graça de Deus.

[[v51-15-41]]

^<<v51-15-41,41>>^ Percorreu a Síria e a Cilicia, confirmando as igrejas.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-014.adoc#v51-14-0[&#60; Capítulo Anterior] | <<v51-15-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-016.adoc#v51-16-0[Próximo Capítulo &#62;]