include::./index.adoc[]

[[v51-5-0]]
=== Atos dos Apóstolos, 5
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Atos dos Apóstolos 5 apresenta a história de Ananias e Safira, que venderam uma propriedade e trouxeram apenas uma parte do dinheiro para os apóstolos, mentindo sobre o valor total. Pedro confronta Ananias, que morre imediatamente, e também Safira, que também morre após mentir para Pedro. O capítulo também descreve muitos milagres e curas realizados pelos apóstolos.
* Salmos 5:6: "Destruirás aqueles que falam mentiras; o SENHOR abominará o homem sanguinário e fraudulento." Esse versículo mostra a importância da honestidade e como Deus é contra a mentira, assim como é demonstrado na história de Ananias e Safira.
* Provérbios 12:22: "Os lábios mentirosos são abomináveis ao SENHOR, mas os que agem fielmente são o seu deleite." Novamente, a importância da honestidade é ressaltada nesse versículo, e o destino trágico de Ananias e Safira demonstra a consequência da desonestidade.
* Mateus 5:37: "Seja, porém, o vosso falar: Sim, sim; Não, não; pois o que passa daí, vem do Maligno." Esse versículo enfatiza a importância de falar a verdade e de não se envolver em enganos, assim como Ananias e Safira tentaram fazer.
* Colossenses 3:9: "Não mintais uns aos outros, uma vez que vos despistes do velho homem com os seus feitos," Esse versículo fala da necessidade de se livrar da velha natureza e do pecado, o que inclui a mentira.
* João 8:44: "Vós tendes por pai o Diabo e quereis satisfazer os desejos de vosso pai. Ele foi homicida desde o princípio e não se firmou na verdade, porque não há verdade nele. Quando ele profere mentira, fala do que lhe é próprio, porque é mentiroso e pai da mentira." Esse versículo mostra a relação entre a mentira e Satanás, que é chamado de pai da mentira. A história de Ananias e Safira é um exemplo dessa mentira e sua consequência trágica.
****

[[v51-5-1]]

^<<v51-5-1,1>>^ Um homem, porém, chamado Ananias, de combinação com sua mulher Safira, vendeu uma propriedade,

[[v51-5-2]]

^<<v51-5-2,2>>^ e, com a cumplicidade de sua mulher, reteve parte do preço, e, levando uma parte, a pôs aos pés dos Apóstolos.

[[v51-5-3]]

^<<v51-5-3,3>>^ Pedro disse: "Ananias, como é que Satanás se apossou de teu coração, para que mentisses ao Espírito Santo e retivesses parte do preço do campo?

[[v51-5-4]]

^<<v51-5-4,4>>^ Não é verdade que, conservando-o (sem vender), era teu, e mesmo, depois de vendido, não estava em teu poder (o preço)? Por que motivo puseste em teu coração (fazer) tal coisa? Não mentiste aos homens, mas a Deus."

[[v51-5-5]]

^<<v51-5-5,5>>^ Ananias, ao ouvir estas palavras, caiu e expirou. Infundiu-se um grande temor em todos os que ouviram isto.

[[v51-5-6]]

^<<v51-5-6,6>>^ Levantando-se alguns jovens, cobriram o seu corpo e levaram-no a enterrar.

[[v51-5-7]]

^<<v51-5-7,7>>^ Passado quase o espaço de três horas, entrou também sua mulher, não sabendo o que tinha acontecido.

[[v51-5-8]]

^<<v51-5-8,8>>^ Pedro disse-lhe: "Dize-me, é verdade que vendeste por tanto o campo?" Ela disse: "Sim, por tanto."

[[v51-5-9]]

^<<v51-5-9,9>>^ Pedro então disse para ela: "Por que vos combinastes para tentar o Espírito do Senhor? Eis que estão à porta os pés daqueles que sepultaram teu marido, e te levarão a ti."

[[v51-5-10]]

^<<v51-5-10,10>>^ Imediatamente, ela caiu a seus pés e expirou. Os jovens, entrando, encontraram-na morta, levaram-na e enterraram-na junto do seu marido. (ver nota)

[[v51-5-11]]

^<<v51-5-11,11>>^ Então difundiu-se um grande temor por toda a Igreja, e entre todos os que ouviram estas coisas.

[[v51-5-12]]

^<<v51-5-12,12>>^ Entretanto eram feitos pelas mãos dos Apóstolos muitos milagres e prodígios entre o povo. Reuniam-se todos unanimemente no pórtico de Salomão.

[[v51-5-13]]

^<<v51-5-13,13>>^ E nenhum dos outros (que não eram cristãos) ousava juntar-se com eles; mas o povo dava-lhes grandes louvores.

[[v51-5-14]]

^<<v51-5-14,14>>^ Cada vez aumentava mais o número dos homens e mulheres que criam no Senhor,

[[v51-5-15]]

^<<v51-5-15,15>>^ de maneira que traziam os doentes para as ruas e punham-nos em leitos e enxergões, a fim de que, ao passar Pedro, cobrisse ao menos a sua sombra algum deles.

[[v51-5-16]]

^<<v51-5-16,16>>^ Concorria também muita gente das cidades vizinhas de Jerusalém, trazendo enfermos e vexados dos espíritos imundos, os quais eram curados todos.

[[v51-5-17]]

^<<v51-5-17,17>>^ Então, levantando-se o príncipe dos sacerdotes e todos os do seu partido, que é a seita dos saduceus, encheram-se de inveja,

[[v51-5-18]]

^<<v51-5-18,18>>^ deitaram as mãos sobre os Apóstolos e meteram-nos na cadeia pública.

[[v51-5-19]]

^<<v51-5-19,19>>^ Mas um anjo do Senhor, abrindo de noite as portas da prisão e tirando-os para fora, disse:

[[v51-5-20]]

^<<v51-5-20,20>>^ "Ide, e, apresentando-vos no templo, pregai ao povo todas as palavras desta vida."

[[v51-5-21]]

^<<v51-5-21,21>>^ Eles obedecendo a esta ordem, entraram ao amanhecer no templo e puseram-se a ensinar. Entretanto, tendo chegado o príncipe dos sacerdotes e os do seu partido, convocaram o Sinédrio e todo o Senado dos filhos de Israel, e mandaram à prisão buscar os Apóstolos, para que fossem ali trazidos.

[[v51-5-22]]

^<<v51-5-22,22>>^ Tendo lá ido os guardas, não os encontraram, e voltaram a dar a notícia,

[[v51-5-23]]

^<<v51-5-23,23>>^ dizendo: "Encontramos a prisão fechada cuidadosamente, e os guardas de pé diante das portas, mas, abrindo-as não encontramos ninguém dentro."

[[v51-5-24]]

^<<v51-5-24,24>>^ Ao ouvirem tais palavras, o oficial do templo e os príncipes dos sacerdotes estavam perplexos e perguntavam entre si o que aquilo queria dizer.

[[v51-5-25]]

^<<v51-5-25,25>>^ Neste momento, alguém foi dizer-lhes: "Eis que aqueles homens, que metestes na prisão, estão no templo e ensinam o povo."

[[v51-5-26]]

^<<v51-5-26,26>>^ Então foi o chefe da polícia com os seus agentes e trouxe-os sem violência, porque temiam que o povo os apedrejasse.

[[v51-5-27]]

^<<v51-5-27,27>>^ Tendo-os conduzido, os apresentaram ao Sinédrio. O príncipe dos sacerdotes os interrogou:

[[v51-5-28]]

^<<v51-5-28,28>>^ "Expressamente vos ordenámos que não ensinásseis nesse nome, e eis que tendes enchido Jerusalém da vossa doutrina, e quereis tornar-nos responsáveis pelo sangue desse homem."

[[v51-5-29]]

^<<v51-5-29,29>>^ Pedro e os Apóstolos responderam: "Deve-se obedecer antes a Deus que aos homens.

[[v51-5-30]]

^<<v51-5-30,30>>^ O Deus dos nossos pais ressuscitou Jesus, a quem vós matastes, suspendendo-o num madeiro.

[[v51-5-31]]

^<<v51-5-31,31>>^ A este elevou Deus com a sua dextra como Chefe e Salvador, para dar a Israel o arrependimento e a remissão dos pecados.

[[v51-5-32]]

^<<v51-5-32,32>>^ E nós somos testemunhas destas coisas, assim como o Espírito Santo, dado por Deus a todos os que lhe obedecem."

[[v51-5-33]]

^<<v51-5-33,33>>^ Tendo ouvido isto, enraiveciam-se e formavam tenção de os matar,

[[v51-5-34]]

^<<v51-5-34,34>>^ mas, levantando-se no Sinédrio um fariseu, chamado Gamaliel, doutor da lei, respeitado por todo o povo, mandou que saíssem para fora aqueles homens por um pouco de tempo,

[[v51-5-35]]

^<<v51-5-35,35>>^ e disse aos sinedritas: "Varões israelitas, considerai bem o que estais para fazer com estes homens.

[[v51-5-36]]

^<<v51-5-36,36>>^ Não há muito tempo apareceu Teudas, que dizia ser um grande homem, ao qual se associou um número de cerca de quatrocentos homens. Ele foi morto, e todos aqueles que o acreditavam foram dispersos e reduzidos a nada.

[[v51-5-37]]

^<<v51-5-37,37>>^ Depois deste surgiu Judas, o Galileu, nos dias do recenseamento, e levou o povo após si, mas também pereceu; e foram dispersos todos os seus sequazes.

[[v51-5-38]]

^<<v51-5-38,38>>^ Agora aconselho-vos a que não vos metais com estes homens e que os deixeis. Porque, se esta ideia ou esta obra vem dos homens, por si mesma se desfará;

[[v51-5-39]]

^<<v51-5-39,39>>^ mas, se vem de Deus, não a podereis desfazer; assim não correie o risco de fazer oposição ao próprio Deus." Eles seguiram o seu conselho.

[[v51-5-40]]

^<<v51-5-40,40>>^ Tendo chamado os Apóstolos, depois de os terem mandado açoutar, ordenaram-lhes que não falassem mais no nome de Jesus, e soltaram-nos.

[[v51-5-41]]

^<<v51-5-41,41>>^ Porém eles saíam da presença do Sinédrio, contentes por terem sido achados dignos de sofrer afrontas pelo nome (de Jesus).

[[v51-5-42]]

^<<v51-5-42,42>>^ E todos os dias não cessavam de ensinar e de anunciar a boa nova de Jesus, o Cristo, no templo e pelas casas.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-004.adoc#v51-4-0[&#60; Capítulo Anterior] | <<v51-5-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-006.adoc#v51-6-0[Próximo Capítulo &#62;]