include::./index.adoc[]

[[v51-12-0]]
=== Atos dos Apóstolos, 12
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Atos dos Apóstolos 12 relata a prisão de Pedro e sua subsequente libertação sobrenatural pelos anjos de Deus. Também é mencionada a morte de Tiago, irmão de João, pelas mãos de Herodes. Os versículos selecionados são:
* Isaías 43:2: "Quando passares pelas águas, estarei contigo, e quando pelos rios, eles não te submergirão; quando passares pelo fogo, não te queimarás, nem a chama arderá em ti." Pedro passou por um momento de grande perigo e angústia ao ser preso e colocado na prisão, mas o Senhor estava com ele, protegendo-o da ira de Herodes.
* Salmos 34:19: "Muitas são as aflições do justo, mas o Senhor o livra de todas." Pedro era um homem justo que foi preso injustamente. No entanto, o Senhor o livrou das mãos de Herodes e o libertou da prisão.
* Provérbios 21:1: "O coração do rei está na mão do Senhor como águas profundas; ele o inclina para onde quer." Herodes estava determinado a matar Pedro, mas Deus tinha outros planos. Ele usou um anjo para libertá-lo da prisão e frustrar os planos do rei.
* João 16:33: "No mundo, tereis aflições; mas tende bom ânimo; eu venci o mundo." A morte de Tiago e a prisão de Pedro são exemplos das aflições que os discípulos de Jesus enfrentaram. No entanto, Jesus lhes deu a promessa de que eles teriam paz em meio às tribulações, pois Ele havia vencido o mundo.
* Atos dos Apóstolos 12:24: "Mas a palavra de Deus crescia e se multiplicava." Apesar da perseguição e das tentativas de silenciar a mensagem do evangelho, a palavra de Deus continuou a se espalhar e a alcançar mais pessoas. A prisão de Pedro e a morte de Tiago não conseguiram deter o avanço do reino de Deus.
****

[[v51-12-1]]

^<<v51-12-1,1>>^ Naquele mesmo tempo o rei Herodes mandou prender alguns membros da Igreja para os maltratar.

[[v51-12-2]]

^<<v51-12-2,2>>^ Matou à espada Tiago, irmão de João.

[[v51-12-3]]

^<<v51-12-3,3>>^ Vendo que isso agradava aos Judeus, mandou também prender Pedro. Eram então os dias dos ázimos.

[[v51-12-4]]

^<<v51-12-4,4>>^ Tendo-o mandado prender, meteu-o na prisão, dando-o a guardar a quatro piquetes de quatro soldados cada um, tendo intenção de o apresentar ao povo depois da Páscoa.

[[v51-12-5]]

^<<v51-12-5,5>>^ Pedro, pois, estava guardado no cárcere. Entretanto a Igreja fazia sem cessar oração a Deus por ele.

[[v51-12-6]]

^<<v51-12-6,6>>^ Ora, na mesma noite em que Herodes estava para o apresentar (ao povo), Pedro dormia entre dois soldados, ligados com duas cadeias; e os guardas à porta vigiavam a prisão.

[[v51-12-7]]

^<<v51-12-7,7>>^ De repente sobreveio um anjo do Senhor, e resplandeceu uma luz no aposento. O anjo, batendo no lado de Pedro, despertou-o, dizendo: "Levanta-te depressa." E caíram as cadeias das suas mãos.

[[v51-12-8]]

^<<v51-12-8,8>>^ O anjo disse-lhe: "Toma o teu cinto e calça as tuas sandálias." Ele assim fez. E disse-lhe: "Põe sobre ti a tua capa e segue-me."

[[v51-12-9]]

^<<v51-12-9,9>>^ Ele, saindo, seguia-o sem dar conta de que era realidade o que se fazia por intervenção do anjo, antes julgava ter uma visão.

[[v51-12-10]]

^<<v51-12-10,10>>^ Depois de passarem a primeira e a segunda guarda, chegaram à porta de ferro, que dá para a cidade, a qual se lhes abriu por si mesma. Saindo, passaram uma rua, e imediatamente, o anjo afastou-se dele.

[[v51-12-11]]

^<<v51-12-11,11>>^ Então Pedro, voltando a si, disse: "Agora sei verdadeiramente que o Senhor mandou o seu anjo e me livrou da mão de Herodes e de tudo o que esperava o povo dos Judeus."

[[v51-12-12]]

^<<v51-12-12,12>>^ Depois de um momento de reflexão, foi a casa de Maria, mãe de João, que tem por sobrenome Marcos, onde estavam muitos reunidos em oração.

[[v51-12-13]]

^<<v51-12-13,13>>^ Tendo ele batido à porta da entrada, uma donzela, chamada Rode, foi escutar.

[[v51-12-14]]

^<<v51-12-14,14>>^ Logo que reconheceu a voz de Pedro, com a alegria, não lhe abriu (logo) a porta, mas, correndo dentro, deu a nova de que Pedro estava à porta.

[[v51-12-15]]

^<<v51-12-15,15>>^ Eles, porém, disseram-lhe: "Estás louca." Mas ela afirmava que era assim. Eles diziam: "É o seu anjo." (ver nota)

[[v51-12-16]]

^<<v51-12-16,16>>^ Entretanto Pedro continuava a bater. Tendo aberto (a porta ), viram-no e ficaram estupefactos.

[[v51-12-17]]

^<<v51-12-17,17>>^ Ele, porém, tendo-lhes feito sinal com a mão para que se calassem, contou-lhes de que modo o Senhor o tinha livrado da prisão. Disse: "Fazei saber isto a Tiago e aos irmãos." Depois, tendo saído, foi para outra parte.

[[v51-12-18]]

^<<v51-12-18,18>>^ Ora, quando foi dia, houve não pequena perturbação entre os soldados, sobre o que tinha sido feito de Pedro.

[[v51-12-19]]

^<<v51-12-19,19>>^ Herodes, tendo-o mandado buscar, e não o encontrando, feito inquérito a respeito dos guardas, mandou-os conduzir (ao suplício). Depois, passando da Judeia a Cesareia, aí habitou.

[[v51-12-20]]

^<<v51-12-20,20>>^ Ora (Herodes) estava em conflito com os de Tiro e de Sidónia. Mas estes, de comum acordo, foram ter com ele, e, com o favor de Blasto, camareiro do rei, pediram paz, porque das terras do rei é que o seu país recebia a subsistência.

[[v51-12-21]]

^<<v51-12-21,21>>^ No dia marcado, Herodes, vestido de traje real, sentou-se sobre o trono e arengava-lhes.

[[v51-12-22]]

^<<v51-12-22,22>>^ E o povo o aplaudia, dizendo: "É voz de um deus, e não de um homem!"

[[v51-12-23]]

^<<v51-12-23,23>>^ Porém subitamente o anjo do Senhor o feriu, porque não tinha dado glória a Deus, e, roído de vermes, expirou.

[[v51-12-24]]

^<<v51-12-24,24>>^ Entretanto a palavra do Senhor crescia e multiplicava-se.

[[v51-12-25]]

^<<v51-12-25,25>>^ Barnabé e Saulo, tendo concluído o seu ministério, voltaram de Jerusalém, levando consigo João, que tem por sobrenome Marcos.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-011.adoc#v51-11-0[&#60; Capítulo Anterior] | <<v51-12-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-013.adoc#v51-13-0[Próximo Capítulo &#62;]