include::./index.adoc[]

[[v51-20-0]]
=== Atos dos Apóstolos, 20
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 20 de Atos dos Apóstolos narra a despedida de Paulo dos anciãos da igreja de Éfeso, bem como sua jornada até Jerusalém. Paulo relembra seu ministério entre eles e os adverte sobre os perigos futuros que a igreja enfrentaria. Os versículos relacionados aos temas abordados em Atos 20 são:
* Efésios 4:11-12: "E ele mesmo concedeu uns para apóstolos, outros para profetas, outros para evangelistas e outros para pastores e mestres, com vistas ao aperfeiçoamento dos santos para o desempenho do seu serviço, para a edificação do corpo de Cristo" - Esses versículos falam sobre a variedade de dons que Deus concede aos membros da igreja para edificação do corpo de Cristo, algo que Paulo discute com os anciãos em sua despedida.
* 2 Timóteo 4:5: "Você, porém, seja sóbrio em tudo, suporte os sofrimentos, faça a obra de um evangelista e cumpra plenamente o seu ministério" - Esse verso traz a exortação de Paulo a Timóteo para que ele continue a fazer a obra de um evangelista, um chamado que também é relevante para a igreja de Éfeso.
* 1 Pedro 5:1-2: "Aos presbíteros, que estão entre vocês, eu, também presbítero como eles, testemunha dos sofrimentos de Cristo e participante da glória que será revelada, peço o seguinte: cuidem do rebanho de Deus que está sob sua responsabilidade. Vocês podem fazê-lo como quem presta contas, não por vontade própria, mas porque assim Deus quer" - Esse verso fala sobre a responsabilidade dos líderes da igreja de cuidar do rebanho de Deus, algo que Paulo reforça em sua despedida aos anciãos de Éfeso.
* Atos 20:29-30: "Sei que, depois da minha partida, lobos ferozes penetrarão no meio de vocês e não pouparão o rebanho. E dentre vocês mesmos se levantarão homens que torcerão a verdade, a fim de atrair os discípulos para si" - Esse verso é uma advertência de Paulo aos anciãos de Éfeso sobre os perigos futuros que a igreja enfrentaria, incluindo a entrada de falsos líderes e o afastamento de alguns membros da verdade.
* Colossenses 4:17: "Diga a Arquipo: 'Veja bem o ministério que você recebeu do Senhor e procure cumpri-lo com diligência'" - Esse verso é um chamado de Paulo a Arquipo, mencionado em Filemom como líder da igreja de Colossos, para que ele cumpra com diligência o ministério que recebeu do Senhor. Esse chamado é relevante para a igreja de Éfeso e para qualquer líder que deseja cumprir bem o seu papel na igreja.
****

[[v51-20-1]]

^<<v51-20-1,1>>^ Depois que o tumulto cessou, chamando Paulo os discípulos e fazendo-lhes uma exortação, despediu-se e partiu para ir à Macedônia.

[[v51-20-2]]

^<<v51-20-2,2>>^ Depois de ter percorrido aquelas regiões e de ter feito muitas exortações, passou à Grécia,

[[v51-20-3]]

^<<v51-20-3,3>>^ onde se demorou três meses. Quando se dispunha a navegar para a Síria, foram-lhe armadas ciladas pelos Judeus, e, por isso, tomou a resolução de voltar pela Macedônia.

[[v51-20-4]]

^<<v51-20-4,4>>^ Acompanharam-no Sopatro, filho de Pirro, de Bereia; Aristarco e Secundo, de Tessalonica; Gaio, de Derbe, e Timóteo; e dos asiáticos (acompanharam-no) Tíquito e Trofimo.

[[v51-20-5]]

^<<v51-20-5,5>>^ Estes, tendo partido adiante, esperaram-nos em Tróade.

[[v51-20-6]]

^<<v51-20-6,6>>^ Nós, depois dos dias dos ázimos, fizemo-nos à vela de Filipos, e, em cinco dias, fomos ter com eles a Tróade, onde nos demoramos sete dias.

[[v51-20-7]]

^<<v51-20-7,7>>^ No primeiro dia da semana, tendo-nos reunido para a fracção do pão, Paulo que devia partir no dia seguinte, falava com eles. Prolongou o discurso até à meia-noite.

[[v51-20-8]]

^<<v51-20-8,8>>^ Havia muitas lâmpadas na sala superior, onde estávamos reunidos.

[[v51-20-9]]

^<<v51-20-9,9>>^ Ora um jovem, chamado Eutico, que estava sentado sobre o peitoril da janela, num profundo sono, enquanto Paulo ia prolongando o seu discurso; vencido pelo sono, caiu abaixo do terceiro andar da casa e foi levantado morto.

[[v51-20-10]]

^<<v51-20-10,10>>^ Paulo, tendo descido, recostou-se sobre ele, tomou-o nos braços e disse: "Não vos perturbeis, porque ele ainda está vivo."

[[v51-20-11]]

^<<v51-20-11,11>>^ Tendo voltado acima e partido o pão e comido, ainda lhes falou largamente, até que surgiu a aurora; depois disto partiu.

[[v51-20-12]]

^<<v51-20-12,12>>^ Levaram vivo o jovem, do que receberam grande consolação.

[[v51-20-13]]

^<<v51-20-13,13>>^ Nós, porém, embarcando num navio, navegámos até Asso, para recebermos ali Paulo, pois assim o tinha ordenado, devendo ele fazer a viagem por terra.

[[v51-20-14]]

^<<v51-20-14,14>>^ Tendo-se juntado connosco em Asso, depois de o tomarmos a bordo, fomos a Mitilene.

[[v51-20-15]]

^<<v51-20-15,15>>^ Continuando dali a navegar, chegámos, no dia seguinte, às alturas de Quio; no outro dia, aportámos em Samos, e, no seguinte, chegámos a Mileto;

[[v51-20-16]]

^<<v51-20-16,16>>^ Com efeito, Paulo tinha determinado passar ao largo de Éfeso, para se não demorar na Ásia. Apressava-se, pois, para estar em Jerusalém, se possível lhe fosse, no dia de Pentecostes.

[[v51-20-17]]

^<<v51-20-17,17>>^ De Mileto mandou a Éfeso chamar os anciães da Igreja.

[[v51-20-18]]

^<<v51-20-18,18>>^ Indo estes ter com ele, disse-lhes: "Sabeis, desde o primeiro dia que entrei na Ásia, de que modo tenho procedido convosco durante todo este tempo,

[[v51-20-19]]

^<<v51-20-19,19>>^ servindo o Senhor com toda a humildade, entre as lágrimas e as provações que me sobrevieram das maquinações dos Judeus.

[[v51-20-20]]

^<<v51-20-20,20>>^ Sabeis que nada tenho negligenciado do que podia ser-vos útil, pregando-vos e instruindo-vos publicamente, e pelas casas,

[[v51-20-21]]

^<<v51-20-21,21>>^ anunciando aos Judeus e aos gentios a conversão a Deus e a fé em Nosso Senhor Jesus.

[[v51-20-22]]

^<<v51-20-22,22>>^ E agora, impelido pelo Espírito, vou a Jerusalém, não sabendo as coisas que ali me hão-de acontecer,

[[v51-20-23]]

^<<v51-20-23,23>>^ senão que o Espirito Santo, por todas as cidades, me assegura e diz que me esperam em Jerusalém prisões e tribulações.

[[v51-20-24]]

^<<v51-20-24,24>>^ Porém, de qualquer modo, a minha vida importa-me pouco, contanto que termine a minha carreira e a missão que recebi do Senhor Jesus de dar testemunho ao Evangelho da graça de Deus.

[[v51-20-25]]

^<<v51-20-25,25>>^ Agora eis que sei que não tomareis mais a ver a minha face todos vós, entre os quais passei pregando o reino (de Deus).

[[v51-20-26]]

^<<v51-20-26,26>>^ Por isso eu vos protesto, neste dia, que estou limpo do sangue de todos, (ver nota)

[[v51-20-27]]

^<<v51-20-27,27>>^ porque não me esquivei a anunciar-vos todas as disposições de Deus.

[[v51-20-28]]

^<<v51-20-28,28>>^ Atendei a vós mesmos e a todo o rebanho, sobre que o Espírito Santo vos constituiu bispos, para governardes a Igreja de Deus, que ele adquiriu com o seu próprio sangue.

[[v51-20-29]]

^<<v51-20-29,29>>^ Eu sei que, depois da minha partida, se introduzirão entre vós, lobos arrebatadores, que não pouparão o rebanho.

[[v51-20-30]]

^<<v51-20-30,30>>^ E de entre vós mesmos hão-de levantar-se homens a ensinar doutrinas perversas, que tentarão levar atrás de si discípulos.

[[v51-20-31]]

^<<v51-20-31,31>>^ Por isso estai vigilantes, lembrando-vos que, durante três anos, não cessei, de noite e de dia, de admoestar com lágrimas a cada um de vós.

[[v51-20-32]]

^<<v51-20-32,32>>^ Agora encomendo-vos a Deus e à palavra da sua graça, àquele que é poderoso para edificar e dar-vos a herança com todos os santificados.

[[v51-20-33]]

^<<v51-20-33,33>>^ Não cobicei prata, nem ouro, nem vestes de ninguém,

[[v51-20-34]]

^<<v51-20-34,34>>^ como vós mesmos sabeis, porque estas mãos me serviram para as coisas que me eram necessárias a mim e àqueles que comigo estavam.

[[v51-20-35]]

^<<v51-20-35,35>>^ Em tudo vos mostrei que, trabalhando assim, é preciso acudir aos fracos, e lembrar-se das palavras do Senhor Jesus, porquanto ele mesmo disse: "É maior ventura dar, que receber."

[[v51-20-36]]

^<<v51-20-36,36>>^ Dito isto, pôs-se de joelhos e orou com todos eles. (ver nota)

[[v51-20-37]]

^<<v51-20-37,37>>^ Levantou-se entre todos um grande pranto, e, lançando-se ao pescoço de Paulo, o abraçavam,

[[v51-20-38]]

^<<v51-20-38,38>>^ aflitos principalmente pela palavra que tinha dito que não tornariam mais a ver a sua face. Em seguida acompanharam-no até ao navio.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-019.adoc#v51-19-0[&#60; Capítulo Anterior] | <<v51-20-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-021.adoc#v51-21-0[Próximo Capítulo &#62;]