include::./index.adoc[]

[[v51-19-0]]
=== Atos dos Apóstolos, 19
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 19 de Atos dos Apóstolos descreve a chegada de Paulo a Éfeso, onde ele encontra um grupo de discípulos que não tinham ouvido falar do Espírito Santo. Paulo prega o Evangelho na sinagoga e na escola de Tirano, onde Deus realiza muitos milagres e curas pelas mãos de Paulo. Também ocorre um conflito com os filhos de Ceva, que tentam expulsar demônios pelo nome de Jesus sem terem autoridade para isso. Depois disso, a cidade é abalada por um tumulto causado por um ourives que se sente ameaçado pela pregação de Paulo. Os versículos relacionados com os temas do capítulo são:
* Mateus 10:8: "Curai enfermos, ressuscitai mortos, purificai leprosos, expeli demônios; de graça recebestes, de graça dai." Esse versículo se relaciona com a atuação de Paulo em Éfeso, onde Deus realiza muitos milagres e curas pelas mãos de Paulo, mostrando o poder e a autoridade de Deus.
* Marcos 9:38: "E João lhe respondeu, dizendo: Mestre, vimos um que, em teu nome, expulsava demônios, o qual não nos segue; e nós lho proibimos, porque não nos seguia." Esse versículo se relaciona com o conflito entre Paulo e os filhos de Ceva, que tentam expulsar demônios pelo nome de Jesus sem terem autoridade para isso. Paulo demonstra que só aqueles que crêem em Jesus e têm autoridade dada por Ele podem fazer tal obra.
* João 16:33: "Tenho-vos dito isto, para que em mim tenhais paz; no mundo tereis aflições, mas tende bom ânimo; eu venci o mundo." Esse versículo se relaciona com o tumulto em Éfeso causado pelo ourives que se sentiu ameaçado pela pregação de Paulo. A perseguição e oposição são uma realidade para aqueles que seguem a Jesus, mas a paz de Cristo e o bom ânimo nos são garantidos, pois Ele já venceu o mundo.
* 2 Timóteo 1:7: "Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação." Esse versículo se relaciona com a pregação de Paulo em Éfeso, onde muitos eram amedrontados pelas práticas ocultas e feitiçarias. Paulo anuncia a verdade de que em Jesus temos a fortaleza, o amor e a moderação que vêm do Espírito Santo.
* 1 Coríntios 14:33: "Porque Deus não é Deus de confusão, senão de paz, como em todas as igrejas dos santos." Esse versículo se relaciona com o conflito em Éfeso causado pelo ourives, que levou a cidade a uma grande confusão. Deus é um Deus de paz, e a mensagem de Cristo traz a paz e a reconciliação para aqueles que crêem.
****

[[v51-19-1]]

^<<v51-19-1,1>>^ Ora aconteceu que, estando Apolo em Corinto, Paulo, depois de ter atravessado as províncias superiores (da Ásia), chegou a Éfeso, onde encontrou alguns discípulos.

[[v51-19-2]]

^<<v51-19-2,2>>^ Disse-lhes: "Vós recebestes o Espírito Santo, quando abraçastes a fé? "Responderam-lhe: "Nem sequer ouvimos dizer que há Espírito Santo."

[[v51-19-3]]

^<<v51-19-3,3>>^ Ele replicou: "Em que baptismo, pois, fostes baptizados?" Responderam: "No baptismo de João."

[[v51-19-4]]

^<<v51-19-4,4>>^ Então disse Paulo: "João baptizou o povo com baptismo de penitência, dizendo que cressem naquele que havia de vir depois dele, isto é, em Jesus."

[[v51-19-5]]

^<<v51-19-5,5>>^ Ouvindo isto, foram baptizados em nome do Senhor Jesus.

[[v51-19-6]]

^<<v51-19-6,6>>^ E, tendo-lhes Paulo imposto as mãos, veio sobre eles o Espírito Santo, e falavam (diversas) línguas e profetizavam.

[[v51-19-7]]

^<<v51-19-7,7>>^ Eram ao todo cerca de doze pessoas.

[[v51-19-8]]

^<<v51-19-8,8>>^ Paulo, entrando na sinagoga, falou com liberdade durante três meses, disputando e persuadindo-os acerca do reino de Deus.

[[v51-19-9]]

^<<v51-19-9,9>>^ Mas, endurecendo-se alguns, e não crendo e dizendo mal do caminho do Senhor diante da multidão, (Paulo), apartando-se deles, formou um grupo à parte com os discípulos e ensinou todos os dias na escola de Tirano.

[[v51-19-10]]

^<<v51-19-10,10>>^ Isto durante dois anos, de tal maneira que todos os que habitavam na Ásia (pro-consular) ouviram a palavra do Senhor, Judeus e Gregos.

[[v51-19-11]]

^<<v51-19-11,11>>^ Deus fazia milagres não vulgares por mão de Paulo,

[[v51-19-12]]

^<<v51-19-12,12>>^ de tal modo que até, sendo aplicados aos enfermos os lenços e aventais que tinham tocado no seu corpo, não só saíam deles as doenças, mas também os espíritos malignos se retiravam. (ver nota)

[[v51-19-13]]

^<<v51-19-13,13>>^ Alguns dos exorcistas judeus, que percorriam o país, também tentaram invocar o nome do Senhor Jesus sobre os que tinham espíritos malignos, dizendo: "Eu vos esconjuro por Jesus, a quem Paulo prega."

[[v51-19-14]]

^<<v51-19-14,14>>^ Os que faziam isto eram sete filhos de um tal Scevas, judeu e príncipe dos sacerdotes.

[[v51-19-15]]

^<<v51-19-15,15>>^ Mas o espírito maligno, respondendo, disse-lhes: "Eu conheço Jesus e sei quem é Paulo. Mas vós quem sois?"

[[v51-19-16]]

^<<v51-19-16,16>>^ E o homem, possesso do espírito mau, saltando sobre eles e apoderando-se de ambos, maltratou-os de tal maneira que, nus e feridos, fugiram daquela casa.

[[v51-19-17]]

^<<v51-19-17,17>>^ Este facto tornou-se notório a todos os Judeus e Gregos, que habitavam em Êfeso, caiu sobre todos eles o temor, e o nome do Senhor Jesus era glorificado,

[[v51-19-18]]

^<<v51-19-18,18>>^ Muitos dos que tinham crido, iam confessar e manifestar as suas obras.

[[v51-19-19]]

^<<v51-19-19,19>>^ Muitos também daqueles que se tinham entregado à magia, trouxeram os seus livros e queimaram-nos diante de todos. Calculando o seu valor, acharam que montava a cinqüenta mil moedas de prata. (ver nota)

[[v51-19-20]]

^<<v51-19-20,20>>^ Deste modo crescia poderosamente e firmava-se a palavra de Deus.

[[v51-19-21]]

^<<v51-19-21,21>>^ Concluídas estas coisas, Paulo concebeu o projecto de ir a Jerusalém, atravessando a Macedônia e a Acaia, dizendo: "Depois de ir lá, é necessário que veja também Roma."

[[v51-19-22]]

^<<v51-19-22,22>>^ E, enviando à Macedônia dois dos que lhe assistiam, Timóteo e Erasto, demorou-se ainda algum tempo na Asia.

[[v51-19-23]]

^<<v51-19-23,23>>^ Neste tempo, surgiu um grande tumulto a propósito do caminho (do Senhor).

[[v51-19-24]]

^<<v51-19-24,24>>^ Com efeito, um certo ourives de prata, chamado Demétrio, que fazia de prata uns pequenos templos de Ártemis, dava muito ganho aos (seus) artífices.

[[v51-19-25]]

^<<v51-19-25,25>>^ Convocando ele estes e outros que trabalhavam em obras semelhantes, disse: "Amigos, sabeis que o nosso ganho nos vem desta indústria.

[[v51-19-26]]

^<<v51-19-26,26>>^ Ora vedes e ouvis dizer que não só em Éfeso, mas em quase toda a Ásia, este Paulo, com as suas persuasões seduziu e afastou muita gente, dizendo que não são deuses aqueles que se fabricam com as mãos.

[[v51-19-27]]

^<<v51-19-27,27>>^ É, pois, para temer, não só que a nossa indústria caia em descrédito, mas também que o templo da grande Ártemis, seja tido em nada, e comece a cair por terra a majestade daquela, a quem toda a Ásia e o mundo adoram."

[[v51-19-28]]

^<<v51-19-28,28>>^ Ouvindo isto, encheram-se de ira e exclamaram: "Grande é a Ártemis dos Efésios!"

[[v51-19-29]]

^<<v51-19-29,29>>^ Encheu-se a cidade de confusão, e todos, à uma, arremeteram ao teatro, arrastando consigo Gaio e Aristarco, macedônios, companheiros de Paulo.

[[v51-19-30]]

^<<v51-19-30,30>>^ Paulo queria apresentar-se ao povo, mas os discípulos não o deixaram.

[[v51-19-31]]

^<<v51-19-31,31>>^ Até alguns dos asíarcas, que eram seus amigos, lhe mandaram pedir que não se apresentasse no teatro. (ver nota)

[[v51-19-32]]

^<<v51-19-32,32>>^ Uns gritavam de um modo, outros de outro modo. Porquanto aquela concorrência (do povo) estava em confusão, e a maior parte não sabia por que se tinha juntado.

[[v51-19-33]]

^<<v51-19-33,33>>^ Então tiraram Alexandre de entre a turba, levando-o aos empurrões os Judeus. Mas Alexandre, pedindo silêncio com a mão, queria defender-se perante o povo.

[[v51-19-34]]

^<<v51-19-34,34>>^ Todavia, logo que conheceram que ele era judeu, todos, a uma voz, gritaram pelo espaço de quase duas horas: "Grande é a Ártemis dos Efésios!"

[[v51-19-35]]

^<<v51-19-35,35>>^ Então o secretário, tendo apaziguado a multidão, disse: "Homens de Éfeso, qual é o homem que não saiba que a cidade de Éfeso é a guarda da grande Ártemis e da sua estátua caída do céu!

[[v51-19-36]]

^<<v51-19-36,36>>^ Não podendo contradizer-se isto, convém que sossegueis e que nada façais inconsideradamente.

[[v51-19-37]]

^<<v51-19-37,37>>^ Porque estes homens, que conduzistes aqui, nem são sacrílegos, nem blasfemadores da vossa deusa.

[[v51-19-38]]

^<<v51-19-38,38>>^ Mas, se Demétrio e os artistas que estão com ele têm alguma queixa contra algum, audiências forenses se realizam e há procônsules; discutam lá entre si.

[[v51-19-39]]

^<<v51-19-39,39>>^ Se pretendeis alguma outra coisa, poderá decidir-se em assembléia legal.

[[v51-19-40]]

^<<v51-19-40,40>>^ Com efeito, até corremos risco de ser arguidos de sedição pelo que hoje se passou, não havendo nenhum motivo com que possamos justificar este ajuntamento tumultuoso." Tendo dito isto, despediu o ajuntamento.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-018.adoc#v51-18-0[&#60; Capítulo Anterior] | <<v51-19-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-020.adoc#v51-20-0[Próximo Capítulo &#62;]