include::./index.adoc[]

[[v51-13-0]]
=== Atos dos Apóstolos, 13
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 13 de Atos dos Apóstolos começa com a seleção de Barnabé e Saulo para uma missão especial, enviados pelo Espírito Santo. Eles viajam para Chipre e pregam a Palavra de Deus em várias sinagogas. Logo após, chegam a Antioquia da Pisídia, onde Paulo prega um sermão na sinagoga. Este capítulo é marcado pela evangelização dos gentios e pela missão dos apóstolos.
* Romanos 10:14-15: "Como invocarão aquele em quem não creram? E como crerão naquele de quem não ouviram falar? E como ouvirão, se não houver quem pregue? E como pregarão, se não forem enviados? Como está escrito: “Como são belos os pés dos que anunciam boas-novas!” Este versículo está relacionado com a missão dos apóstolos em Atos 13, que foram enviados pelo Espírito Santo para pregar a Palavra de Deus em várias regiões.
* Atos 10:45: "Os fiéis circuncisos que haviam vindo com Pedro ficaram admirados, porque o dom do Espírito Santo tinha sido derramado também sobre os gentios." Esse versículo fala sobre a conversão dos gentios, um tema importante em Atos 13, já que Paulo e Barnabé foram escolhidos para pregar para eles.
* João 15:16: "Não fostes vós que me escolhestes a mim; pelo contrário, eu vos escolhi a vós outros e vos designei para que vades e deis fruto, e o vosso fruto permaneça; a fim de que tudo quanto pedirdes ao Pai em meu nome, ele vo-lo conceda." Este versículo se relaciona com a seleção de Barnabé e Paulo para a missão especial em Atos 13. Eles foram escolhidos e designados pelo Espírito Santo para pregar a Palavra de Deus.
* Atos 11:20-21: "Alguns deles, porém, homens de Chipre e de Cirene, foram a Antioquia e começaram a falar também aos gregos, anunciando-lhes o Senhor Jesus. A mão do Senhor estava com eles, e muitos creram e se converteram ao Senhor." Esse versículo fala sobre a evangelização dos gentios, um tema importante em Atos 13, já que Paulo e Barnabé foram escolhidos para pregar para eles.
* Colossenses 1:28: "A ele anunciamos, advertindo a todo homem e ensinando a todo homem em toda a sabedoria, a fim de que apresentemos todo homem perfeito em Cristo." Este versículo se relaciona com a missão de Paulo e Barnabé em Atos 13, que foram enviados pelo Espírito Santo para pregar a Palavra de Deus e ensinar a sabedoria de Cristo para as pessoas.
****

[[v51-13-1]]

^<<v51-13-1,1>>^ Havia na Igreja de Antioquia profetas e doutores, entre os quais Barnabé, Simão, chamado o Negro, Lúcio de Cirene, Manahen, colaço de Herodes Tetrarca, e Saulo.

[[v51-13-2]]

^<<v51-13-2,2>>^ Estando eles a celebrar o culto do Senhor e a jejuar, disse-lhes o Espírito Santo: "Separai-me Barnabé e Saulo para a obra a que os destinei."

[[v51-13-3]]

^<<v51-13-3,3>>^ Então, depois de terem jejuado e orado, impuseram-lhes as mãos e despediram-nos.

[[v51-13-4]]

^<<v51-13-4,4>>^ Eles, pois, enviados pelo Espirito Santo, foram a Selêucia, e dali navegaram para Chipre.

[[v51-13-5]]

^<<v51-13-5,5>>^ Quando chegaram a Salamina, pregavam a palavra de Deus nas sinagogas dos Judeus. Tinham com eles João, como auxiliar.

[[v51-13-6]]

^<<v51-13-6,6>>^ Tendo percorrido toda a ilha até Pafos, encontraram um certo homem mago, falso profeta, judeu, que tinha por nome Barjesus,

[[v51-13-7]]

^<<v51-13-7,7>>^ o qual vivia com o procônsul Sérgio Paulo, homem prudente. Este, tendo mandado chamar Barnabé e Saulo, mostrou desejos de ouvir a palavra de Deus.

[[v51-13-8]]

^<<v51-13-8,8>>^ Mas Elimas, o mago (porque assim se interpreta o seu nome) se lhes opunha, procurando afastar da fé o procônsul.

[[v51-13-9]]

^<<v51-13-9,9>>^ Porém Saulo, que também se chama Paulo, cheio do Espírito Santo, fixando nele os olhos,

[[v51-13-10]]

^<<v51-13-10,10>>^ disse: "Ó (tu, que estás) cheio de todo o engano e de toda a astúcia, filho do demônio, inimigo de toda a justiça, não acabarás de perverter os caminhos rectos do Senhor?

[[v51-13-11]]

^<<v51-13-11,11>>^ Pois agora eis que a mão do Senhor está sobre ti, ficarás cego, sem ver o sol durante certo tempo." Caíram logo sobre ele a obscuridade e as trevas: andando à roda, buscava quem lhe desse a mão.

[[v51-13-12]]

^<<v51-13-12,12>>^ Então o procônsul, vendo este facto, creu, maravilhado com a doutrina do Senhor.

[[v51-13-13]]

^<<v51-13-13,13>>^ Tendo-se feito à vela de Pafos, Paulo e os que com ele se encontravam, chegaram a Perge da Panfilia, Aqui João, apartando-se deles, voltou a Jerusalém.

[[v51-13-14]]

^<<v51-13-14,14>>^ Eles, porém, passando além de Perge, foram a Antioquia da Pisídia, e, tendo entrado na sinagoga em dia de sábado, tomaram assento.

[[v51-13-15]]

^<<v51-13-15,15>>^ Depois da leitura da lei e dos profetas, os chefes da sinagoga mandaram-lhes dizer: "Irmãos, se tendes alguma exortação a fazer ao povo, falai."

[[v51-13-16]]

^<<v51-13-16,16>>^ Então Paulo, levantando-se e fazendo com a mão sinal de silêncio, disse: "Varões israelitas, e vós que temeis a Deus, ouvi:

[[v51-13-17]]

^<<v51-13-17,17>>^ O Deus deste povo de Israel escolheu nossos pais e exaltou este povo, enquanto eram estrangeiros na terra do Egipto, de onde os tirou com o poder do seu braço.

[[v51-13-18]]

^<<v51-13-18,18>>^ Alimentou-os no deserto, durante cerca de quarenta anos,

[[v51-13-19]]

^<<v51-13-19,19>>^ e, destruindo sete nações na terra de Canaan, distribuiu entre eles o território delas

[[v51-13-20]]

^<<v51-13-20,20>>^ e deu-lhas, em herança, por espaço de cerca de quatrocentos e cinqüenta anos. Depois disso, deu-lhes juízes até ao profeta Samuel.

[[v51-13-21]]

^<<v51-13-21,21>>^ Então pediram um rei, e Deus deu-lhes Saul, Filho de Cie, homem da tribo de Benjamim, por espaço de quarenta anos.

[[v51-13-22]]

^<<v51-13-22,22>>^ Rejeitado este, suscitou-lhes como rei a David, ao qual, dando testemunho, disse: Achei David, filho de Jessé, homem segundo o meu coração, que fará todas as minhas vontades.

[[v51-13-23]]

^<<v51-13-23,23>>^ Da descendência deste, Deus, segundo a sua promessa, suscitou um Salvador a Israel, Jesus,

[[v51-13-24]]

^<<v51-13-24,24>>^ tendo João pregado, antes da sua vinda, o baptismo da penitência a todo o povo de Israel.

[[v51-13-25]]

^<<v51-13-25,25>>^ João, chegando ao termo da sua missão, dizia: Eu não sou quem vós pensais, mas eis que, depois de mim, vem aquele, de quem não sou digno de desatar o calçado dos pés.

[[v51-13-26]]

^<<v51-13-26,26>>^ Irmãos, filhos da descendência de Abraão, e os que entre vós temem a Deus, a nós é que foi enviada esta palavra de salvação.

[[v51-13-27]]

^<<v51-13-27,27>>^ Efectivamente, os habitantes de Jerusalém e os seus chefes, não conhecendo Jesus nem as vozes dos profetas que cada sábado se lêem, condenando-o, as cumpriram.

[[v51-13-28]]

^<<v51-13-28,28>>^ Não encontrando nele nenhuma causa de morte, pediram a Pilatos para lhe tirar a vida.

[[v51-13-29]]

^<<v51-13-29,29>>^ Depois, tendo consumado todas as coisas que estavam escritas, tirando-o do madeiro, o puseram no sepulcro.

[[v51-13-30]]

^<<v51-13-30,30>>^ Deus, porém, ressuscitou-o dos mortos,

[[v51-13-31]]

^<<v51-13-31,31>>^ e ele foi visto durante muitos dias por aqueles que o tinham acompanhado da Galileia a Jerusalém, os quais agora são suas testemunhas perante o povo.

[[v51-13-32]]

^<<v51-13-32,32>>^ E nós vos anunciamos que aquela promessa, que foi feita a nossos pais,

[[v51-13-33]]

^<<v51-13-33,33>>^ Deus a cumpriu com seus filhos que somos nós, ressuscitando Jesus, como está escrito no salmo segundo: Tu és meu Filho, eu te gerei hoje ([Ps. 2,7).

[[v51-13-34]]

^<<v51-13-34,34>>^ Que o ressuscitou dos mortos, para nunca mais tornar à corrupção, ele o disse deste modo: Dar-vos-ei fielmente os favores sagrados prometidos a David ().

[[v51-13-35]]

^<<v51-13-35,35>>^ Por isso também diz noutro lugar: Não permitirás que o teu Santo experimente corrupção (Ps. 16,10).

[[v51-13-36]]

^<<v51-13-36,36>>^ Porque David, tendo durante a sua vida servido os desígnios de Deus, morreu, foi reunir-se com seus pais e experimentou a corrupção.

[[v51-13-37]]

^<<v51-13-37,37>>^ Porém, aquele que Deus ressuscitou dos mortos, não experimentou a corrupção.

[[v51-13-38]]

^<<v51-13-38,38>>^ Seja-vos, pois, notório, irmãos, que por ele vos é anunciada a remissão dos pecados e de tudo aquilo de que não pudestes ser justificados pela lei de Moisés.

[[v51-13-39]]

^<<v51-13-39,39>>^ Por ele é justificado todo aquele que crê.

[[v51-13-40]]

^<<v51-13-40,40>>^ Tomai, pois, cuidado que não venha sobre vós o que foi dito nos profetas:

[[v51-13-41]]

^<<v51-13-41,41>>^ Vede, ó desprezadores, admirai-vos e desaparecei, que eu vou fazer uma obra em vossos dias, uma obra que vós não crereis, se alguém vo-la contar (Hc. 1, 5).

[[v51-13-42]]

^<<v51-13-42,42>>^ Quando eles saiam da sinagoga, rogavam que, no sábado seguinte, lhes falassem sobre o mesmo assunto.

[[v51-13-43]]

^<<v51-13-43,43>>^ Tendo-se dissolvido a reunião, muitos Judeus e prosélitos piedosos seguiram Paulo e Barnabé, os quais, com as suas palavras, os exortavam a que perseverassem na graça de Deus.

[[v51-13-44]]

^<<v51-13-44,44>>^ No sábado seguinte, concorreu quase toda a cidade a ouvir a palavra de Deus.

[[v51-13-45]]

^<<v51-13-45,45>>^ Mas os Judeus, vendo aquela concorrência (de gente), encheram-se de inveja e responderam com injúrias às palavras de Paulo.

[[v51-13-46]]

^<<v51-13-46,46>>^ Então Paulo e Barnabé disseram-lhes resolutamente; "Vós éreis os primeiros a quem se devia anunciar a palavra de Deus, mas, porque a rejeitais e vos julgais indignos da vida eterna, eis que nos voltamos para os gentios,

[[v51-13-47]]

^<<v51-13-47,47>>^ porque assim nos ordenou o Senhor: Eu te constitui luz das nações para que sejas a salvação até à extremidade da terra (Is. 49, 6).

[[v51-13-48]]

^<<v51-13-48,48>>^ Os gentios, ouvindo isto, alegraram-se e glorificavam a palavra do Senhor. Creram todos os que eram ordenados para a vida eterna.

[[v51-13-49]]

^<<v51-13-49,49>>^ A palavra de Deus espalhava-se por toda aquela região.

[[v51-13-50]]

^<<v51-13-50,50>>^ Mas os Judeus instigaram algumas mulheres devotas e nobres, assim como os principais da cidade, e suscitaram uma perseguição contra Paulo e Barnabé, que lançaram fora do seu território.

[[v51-13-51]]

^<<v51-13-51,51>>^ Então estes, tendo sacudido contra eles o pó dos seus pés, foram para Icónio.

[[v51-13-52]]

^<<v51-13-52,52>>^ Entretanto os discípulos estavam cheios de alegria e do Espírito Santo.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-012.adoc#v51-12-0[&#60; Capítulo Anterior] | <<v51-13-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-014.adoc#v51-14-0[Próximo Capítulo &#62;]