include::./index.adoc[]

[[v51-28-0]]
=== Atos dos Apóstolos, 28
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Atos dos Apóstolos 28 narra a chegada de Paulo em Roma e sua interação com os líderes judeus e romanos da cidade. Ele continua a pregar o Evangelho e muitos ouvem a mensagem com fé, enquanto outros a rejeitam. O capítulo também menciona a cura de muitos doentes e a chegada de outros cristãos para se juntar a Paulo em Roma. Com base nesses temas, os cinco versículos relacionados são:
* Romanos 10:17: "Logo a fé é pelo ouvir, e o ouvir pela palavra de Cristo." Este versículo destaca a importância de ouvir a palavra de Cristo para desenvolver a fé. Isso se relaciona com a pregação contínua de Paulo em Atos 28, na qual ele fala sobre o Evangelho e muitos ouvem a mensagem com fé.
* 2 Coríntios 4:8-9: "Em tudo somos atribulados, mas não angustiados; perplexos, mas não desesperados; perseguidos, mas não desamparados; abatidos, mas não destruídos." Este versículo fala sobre a capacidade de resistência e perseverança dos cristãos, mesmo em meio a adversidades. Isso se relaciona com a situação de Paulo em Atos 28, em que ele enfrenta oposição e perseguição, mas continua a pregar o Evangelho.
* Tiago 5:14: "Está alguém entre vós doente? Chame os presbíteros da igreja, e orem sobre ele, ungindo-o com azeite em nome do Senhor." Este versículo menciona a prática de oração e cura dentro da comunidade cristã. Isso se relaciona com a cura de muitos doentes mencionada em Atos 28.
* Efésios 4:11-12: "E ele mesmo deu uns para apóstolos, e outros para profetas, e outros para evangelistas, e outros para pastores e mestres, tendo em vista o aperfeiçoamento dos santos, para a obra do ministério, para edificação do corpo de Cristo." Este versículo fala sobre a diversidade de dons e papéis dentro da igreja, com o objetivo de edificar o corpo de Cristo. Isso se relaciona com a chegada de outros cristãos em Roma para se juntar a Paulo em Atos 28.
* Colossenses 4:5-6: "Andai com sabedoria para com os que estão de fora, remindo o tempo, aproveitando ao máximo cada oportunidade. A vossa palavra seja sempre agradável, temperada com sal, para que saibais como deveis responder a cada um." Este versículo fala sobre a importância de ter sabedoria e gentileza ao compartilhar a mensagem do Evangelho com aqueles que não são cristãos. Isso se relaciona com a interação de Paulo com os líderes judeus e romanos em Atos 28, em que ele continua a pregar o Evangelho, mesmo diante de oposição e rejeição.
****

[[v51-28-1]]

^<<v51-28-1,1>>^ Estando fora de perigo, reconhecemos então que a ilha se chamava Malta. Os indígenas trataram-nos com muita humanidade.

[[v51-28-2]]

^<<v51-28-2,2>>^ Acesa uma grande fogueira, nos alentaram a todos contra a chuva, que caía, e contra o frio.

[[v51-28-3]]

^<<v51-28-3,3>>^ Paulo, tendo juntado e posto sobre o lume uma porção de sarmentos, uma víbora, que fugira do calor, agarrou-se-lhe à mão.

[[v51-28-4]]

^<<v51-28-4,4>>^ Vendo os indígenas a víbora pendente da sua mão, diziam uns para os outros: "Certamente este homem é algum assassino, porque, tendo escapado do mar, a (deusa) Justiça não o deixa viver."

[[v51-28-5]]

^<<v51-28-5,5>>^ Ele, porém, sacudindo a víbora no fogo, não sofreu mal algum.

[[v51-28-6]]

^<<v51-28-6,6>>^ Ora os indígenas esperavam que ele viesse a inchar, que caísse súbitamente e morresse. Mas, depois de esperarem muito tempo, vendo que lhe não sucedia mal nenhum, mudando de parecer, diziam que era um deus.

[[v51-28-7]]

^<<v51-28-7,7>>^ Naquelas cercanias havia umas terras do maioral da ilha, chamado Públio, o qual, hospedando-nos em sua casa, nos tratou bem durante três dias.

[[v51-28-8]]

^<<v51-28-8,8>>^ Ora encontrava-se então no leito, doente de febre e de disenteria, o pai de Públio. Paulo foi vê-lo, e, tendo feito oração e impondo-lhe as mãos, o sarou.

[[v51-28-9]]

^<<v51-28-9,9>>^ Depois disto, todos os que na ilha tinham doenças, iam ter com ele e eram curados.

[[v51-28-10]]

^<<v51-28-10,10>>^ Também nos cumularam de honras, e, quando embarcámos, forneceram-nos o necessário.

[[v51-28-11]]

^<<v51-28-11,11>>^ Ao cabo de três meses, embarcámos num navio de Alexandria, que invernara na ilha, e tinha a insígnia dos Dióscoros. (ver nota)

[[v51-28-12]]

^<<v51-28-12,12>>^ Arribados a Siracusa, ficámos lá três dias.

[[v51-28-13]]

^<<v51-28-13,13>>^ Daí, correndo a costa, chegámos a Régio. Um dia depois, começou a soprar o vento sul, e no segundo dia chegámos a Putéolos,

[[v51-28-14]]

^<<v51-28-14,14>>^ onde, tendo encontrado irmãos, nos rogaram que ficássemos com eles sete dias. Em seguida encaminhámo-nos para Roma.

[[v51-28-15]]

^<<v51-28-15,15>>^ De lá, tendo os irmãos ouvido falar da nossa chegada, saíram ao nosso encontro até ao foro de Ápio e até às Três Tabernas. Paulo, tendo-os visto, deu graças a Deus e ficou cheio de confiança.

[[v51-28-16]]

^<<v51-28-16,16>>^ Chegados a Roma, foi permitido a Paulo que ficasse onde quisesse, com um soldado a guardá-lo.

[[v51-28-17]]

^<<v51-28-17,17>>^ Três dias depois, Paulo convocou os principais judeus. Tendo-se eles juntado, disse-lhes; "Eu, irmãos, sem ter feito nada contra o povo, nem contra os costumes de nossos pais, tendo sido preso em Jesusalém, fui entregue nas mãos dos Romanos,

[[v51-28-18]]

^<<v51-28-18,18>>^ os quais, tendo-me examinado, quiseram soltar-me, visto que não achavam em mim crime algum digno de morte.

[[v51-28-19]]

^<<v51-28-19,19>>^ Mas, opondo-se os Judeus, vi-me obrigado a apelar para César, sem intentar contudo acusar em alguma coisa a minha nação.

[[v51-28-20]]

^<<v51-28-20,20>>^ Por tal motivo, pois, pedi para vos ver e vos falar, porquanto é por causa da esperança de Israel que estou preso com estas cadeias." (ver nota)

[[v51-28-21]]

^<<v51-28-21,21>>^ Eles responderam-lhe: "Nós nem recebemos carta da Judeia acerca de ti, nem de lá veio nenhum que nos dissesse ou falasse algum mal de ti.

[[v51-28-22]]

^<<v51-28-22,22>>^ Porém queríamos ouvir dá tua boca o que pensas, porque o que nós sabemos desta seita, é que em toda a parte a impugnam."

[[v51-28-23]]

^<<v51-28-23,23>>^ Tendo-lhe fixado o dia, foram muitos ter com ele à casa onde estava hospedado, aos quais expunha (a doutrina sobre) o reino de Deus, esforçando-se por convencê-los acerca de Jesus, por meio da lei de Moisés e dos profetas, desde manhã até à noite.

[[v51-28-24]]

^<<v51-28-24,24>>^ Uns criam no que ele dizia, outros não criam.

[[v51-28-25]]

^<<v51-28-25,25>>^ Como não estivessem concordes entre si, retiravam-se, enquanto Paulo lhes dizia só esta palavra: "Bem falou o Espírito Santo pelo profeta Isaías a nossos pais,

[[v51-28-26]]

^<<v51-28-26,26>>^ quando disse: Vai a esse povo e dize-lhe: Com o ouvido ouvireis e não entendereis; com os olhos olhareis e não vereis.

[[v51-28-27]]

^<<v51-28-27,27>>^ Porque o coração deste povo tornou-se insensível; são duros dos ouvidos, e fecharam os olhos, para que não vejam com os olhos, ouçam com os ouvidos, entendam com o coração, e se convertam, e eu os sare (Is. 6,9-10).

[[v51-28-28]]

^<<v51-28-28,28>>^ Seja-vos, pois, notório que esta salvação de Deus é enviada aos gentios, e eles a ouvirão."

[[v51-28-29]]

^<<v51-28-29,29>>^ (Tendo dito estas coisas, saíram dali os Judeus, entre grandes altercações.)

[[v51-28-30]]

^<<v51-28-30,30>>^ Dois anos inteiros permaneceu Paulo num aposento que alugara, onde recebia todos os que iam ter com ele,

[[v51-28-31]]

^<<v51-28-31,31>>^ pregando o reino de Deus e ensinando o que diz respeito ao Senhor Jesus Cristo, com toda a liberdade, sem proibição.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-027.adoc#v51-27-0[&#60; Capítulo Anterior] | <<v51-28-0,Topo>> | xref:052-romanos/052-romanos-001.adoc#v52-1-0[Próximo Capítulo &#62;]