include::./index.adoc[]

[[v60-1-0]]
=== II Tessalonicenses, 1
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* 2 Tessalonicenses 1 fala sobre a justiça de Deus e sua retribuição aos que perseguem os cristãos. O capítulo enfatiza que Deus é justo e que trará juízo aos que fazem o mal, enquanto recompensa os que permanecem fiéis a Ele. A seguir, estão cinco versículos relacionados aos temas abordados em 2 Tessalonicenses 1:
* Salmos 94:23 - "Ele fará recair sobre eles a sua própria maldade e os destruirá na sua própria malícia; sim, o Senhor nosso Deus os destruirá." Este versículo fala sobre como Deus trará justiça para aqueles que praticam o mal e os destruirá em sua própria maldade, assim como é enfatizado em 2 Tessalonicenses 1.
* Apocalipse 19:2 - "Porque verdadeiros e justos são os seus juízos, pois julgou a grande prostituta que havia corrompido a terra com a sua prostituição e das mãos dela vingou o sangue dos seus servos." Aqui, vemos que Deus é justo em seus juízos e traz justiça aos seus servos, assim como é destacado em 2 Tessalonicenses 1.
* Romanos 2:5 - "Mas, segundo a tua dureza e teu coração impenitente, entesouras ira para ti no dia da ira e da revelação do justo juízo de Deus." Este versículo fala sobre como a dureza de coração e a falta de arrependimento levam à ira de Deus no dia do julgamento. Isso se relaciona com o tema de justiça e retribuição de Deus em 2 Tessalonicenses 1.
* Hebreus 10:30-31 - "Porque nós conhecemos aquele que disse: Minha é a vingança, eu darei a recompensa, diz o Senhor. E outra vez: O Senhor julgará o seu povo. Horrível coisa é cair nas mãos do Deus vivo." Este versículo destaca que Deus é o juiz justo e que trará retribuição aos que o rejeitam. Isso se relaciona com o tema de justiça e julgamento em 2 Tessalonicenses 1.
* Salmo 50:3-4 - "O nosso Deus vem, e não guarda silêncio; perante ele arde um fogo devorador, e grande tormenta há ao redor dele. Ele chama os céus lá em cima, e a terra, para julgar o seu povo." Este versículo enfatiza que Deus é um juiz justo e que trará julgamento para o seu povo. Isso se relaciona com o tema de justiça e retribuição de Deus em 2 Tessalonicenses 1.
****

[[v60-1-1]]

^<<v60-1-1,1>>^ Paulo, Silvano e Timóteo, à Igreja dos Tessalonicenses, em Deus nosso Pai e no Senhor Jesus Cristo.

[[v60-1-2]]

^<<v60-1-2,2>>^ Graça e paz vos sejam dadas, da parte de Deus, nosso Pai, e da do Senhor Jesus Cristo.

[[v60-1-3]]

^<<v60-1-3,3>>^ Nós devemos, irmãos, dar sempre graças a Deus por vós, como é justo, porque a vossa fé vai em grande aumento e abunda em cada um de vós a caridade mútua.

[[v60-1-4]]

^<<v60-1-4,4>>^ Também nós mesmos nos gloriamos de vós na igrejas de Deus, pela vossa paciência e fé, no meio de todas as perseguições e tribulações que sofreis.

[[v60-1-5]]

^<<v60-1-5,5>>^ Elas são prova do justo juízo de Deus, (que deste modo vos purifica) para que sejais tidos por dignos do reino de Deus, pelo qual padeceis. (ver nota)

[[v60-1-6]]

^<<v60-1-6,6>>^ Com efeito, é justo diante de Deus dar tribulação aqueles que vos atribulam,

[[v60-1-7]]

^<<v60-1-7,7>>^ e a vós, que sois atribulados, (dar) descanso (eterno) connosco, quando aparecer o Senhor Jesus (descendo) do céu com os anjos (mensageiros) do seu poder,

[[v60-1-8]]

^<<v60-1-8,8>>^ em uma chama de fogo, para tomar vingança daqueles que (por sua culpa) não conhecem a Deus e não obedecem ao Evangelho de Nosso Senhor Jesus.

[[v60-1-9]]

^<<v60-1-9,9>>^ Esses tais serão punidos com a perdição eterna, longe da face do Senhor e da glória do seu poder,

[[v60-1-10]]

^<<v60-1-10,10>>^ quando ele vier naquele dia, para ser glorificado nos seus santos, e para se fazer admirável em todos os que creram, porque vós crestes no testemunho que demos diante de vós.

[[v60-1-11]]

^<<v60-1-11,11>>^ Por isso oramos incessantemente por vós, para que o nosso Deus vos faça dignos da vossa vocação (isto é, do estado a que vos chamou), que realize com o seu poder todo o desejo de fazer bem e a atividade da vossa fé,

[[v60-1-12]]

^<<v60-1-12,12>>^ a fim de que o nome de Nosso Senhor Jesus Cristo seja glorificado em vós, e vós nele, pela graça do nosso Deus e do Senhor Jesus Cristo.

'''

xref:059-i-tessalonicenses/059-i-tessalonicenses-005.adoc#v59-5-0[&#60; Capítulo Anterior] | <<v60-1-0,Topo>> | xref:060-ii-tessalonicenses/060-ii-tessalonicenses-002.adoc#v60-2-0[Próximo Capítulo &#62;]