include::./index.adoc[]

[[v27-18-0]]
=== Sabedoria, 18
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Sabedoria 18 narra a história da noite da libertação do povo de Israel da escravidão no Egito e da passagem pelo Mar Vermelho. O capítulo destaca o papel de Deus como protetor e libertador do seu povo e a importância da fé em sua intervenção divina.
* Êxodo 14:21: "Então Moisés estendeu a mão sobre o mar, e o Senhor, por um forte vento oriental toda aquela noite, fez o mar recuar. Ele o transformou em terra seca, e as águas se dividiram." Este versículo descreve o milagre da abertura do Mar Vermelho, que foi um dos eventos mais significativos da história de Israel e é mencionado em Sabedoria 18:15.
* Êxodo 15:1: "Então Moisés e os israelitas cantaram este cântico ao Senhor: ‘Cantarei ao Senhor, pois ele é grandioso! Precipitou no mar o cavalo e o seu cavaleiro!’" Este cântico de louvor a Deus é uma resposta ao seu livramento poderoso do povo de Israel do exército egípcio no Mar Vermelho. A canção de Moisés mencionada em Sabedoria 18:9-10 também celebra esse evento.
* Êxodo 14:13: "Moisés respondeu ao povo: ‘Não tenham medo! Fiquem firmes e vejam o livramento que o Senhor trará hoje para vocês. Os egípcios que hoje vocês estão vendo, nunca mais vocês os verão!’" Moisés encorajou o povo de Israel a confiar em Deus e a acreditar que Ele seria capaz de libertá-los do poder dos egípcios. Essa mensagem de esperança e confiança é um tema importante em Sabedoria 18.
* Êxodo 15:13: "Com a tua graça conduziste o povo que resgataste; com teu poder os levaste à tua santa habitação." Este versículo é parte do cântico de Moisés e destaca o papel de Deus como salvador e guia do seu povo. Sabedoria 18 também enfatiza o poder salvador de Deus e a importância de confiar nele.
* Êxodo 15:16: "Estremecerão de medo os povos; agarrarão os habitantes da Filístia um pavor súbito." O poder de Deus e a sua intervenção no livramento do seu povo foram tão significativos que as nações vizinhas tremiam de medo. A resposta divina à opressão dos egípcios e a libertação do povo de Israel são temas centrais em Sabedoria 18.
****

[[v27-18-1]]

^<<v27-18-1,1>>^ Entretanto (Senhor) os teus santos tinham uma luz brilhantíssima; (os Egípcios) ouviam a sua voz, porém não viam a sua forma, e, apesar dos sofrimentos passados, proclamavam-nos (aos Israelitas) venturosos.

[[v27-18-2]]

^<<v27-18-2,2>>^ Davam-lhes graças porque, depois de haverem sido ofendidos, não se vingavam, e pediam-lhes perdão de os haverem tratado como inimigos.

[[v27-18-3]]

^<<v27-18-3,3>>^ Tu deste (Senhor), em vez das trevas, uma coluna de fogo (aos teus fiéis), como guia num caminho desconhecido, como sol inofensivo na sua gloriosa peregrinação.

[[v27-18-4]]

^<<v27-18-4,4>>^ Bem mereciam ser privados da luz e sofrer um cárcere de trevas, aqueles que tinham encerrado em prisões os teus filhos, por meio dos quais devia ser dada ao mundo a luz incorruptível da tua lei.

[[v27-18-5]]

^<<v27-18-5,5>>^ Quando eles resolveram matar os filhos dos justos, e foi salvo um destes meninos que tinha sido exposto, tu Ihes tiraste, para seu castigo, a multidão de seus filhos, e juntos os destruístes no abismo das águas. (ver nota)

[[v27-18-6]]

^<<v27-18-6,6>>^ Aquela noite tinha sido conhecida, de antemão por nossos pais para que, sabendo eles com verdade a que promessas deram crédito, ficassem os seus ânimos mais corajosos. (ver nota)

[[v27-18-7]]

^<<v27-18-7,7>>^ E assim o teu povo esperou a salvação dos justos e o extermínio dos injustos.

[[v27-18-8]]

^<<v27-18-8,8>>^ Da mesma forma que tu castigaste os nossos adversários, assim também, chamando-nos a ti, nos engrandeceste.

[[v27-18-9]]

^<<v27-18-9,9>>^ Os justos, filhos dos bons, ofereciam-te, em segredo, o sacrifício, e estabeleciam de comum acordo este pacto divino: Que (no mundo) os santos participariam igualmente tanto dos bens como dos males, cantando já os hinos de seus pais. (ver nota)

[[v27-18-10]]

^<<v27-18-10,10>>^ (Ao mesmo tempo) ouviam-se as vozes confusas dos seus inimigos, e os lamentáveis prantos dos que choravam a morte dos meninos.

[[v27-18-11]]

^<<v27-18-11,11>>^ Com a mesma pena foram afligidos o servo e o senhor, e o homem plebeu padeceu o mesmo que o rei.

[[v27-18-12]]

^<<v27-18-12,12>>^ Todos, igualmente, tinham inumeráveis mortos, feridos com a mesma morte. Nem já os vivos bastavam para os enterrar, porque, num instante, foi exterminada a parte mais nobre da nação.

[[v27-18-13]]

^<<v27-18-13,13>>^ Então os que tinham incrédulos, por causa dos seus sortilégios, logo que sucedeu o extermínio dos primogênitos, confessaram que aquele era o povo de Deus.

[[v27-18-14]]

^<<v27-18-14,14>>^ Quando tudo repousava num profundo silêncio, e a noite estava no meio do seu curso,

[[v27-18-15]]

^<<v27-18-15,15>>^ a tua palavra omnipotente, baixando do céu, do trono real, saltou de improviso ao meio da terra condenada ao extermínio, como um implacável guerreiro,

[[v27-18-16]]

^<<v27-18-16,16>>^ levando, como aguda espada, o teu irrevogável decreto; estando de pé tudo encheu de morte, e, pisando a terra, chegava até ao céu. (ver nota)

[[v27-18-17]]

^<<v27-18-17,17>>^ Então foram imediatamente perturbados por visões de sonhos horríveis, e temores inesperados os assaltaram.

[[v27-18-18]]

^<<v27-18-18,18>>^ Arrojados para um lado e para outro, semimortos, manifestavam a causa da morte que os atingia. (ver nota)

[[v27-18-19]]

^<<v27-18-19,19>>^ As visões, que os perturbavam, tinham-lhes revelado isso, para não suceder que morressem sem saber a causa dos males que sofriam.

[[v27-18-20]]

^<<v27-18-20,20>>^ É verdade que também feriu os justos uma prova de morte, e no deserto houve uma mortandade na multidão, mas a (tua) ira não durou muito tempo. (ver nota)

[[v27-18-21]]

^<<v27-18-21,21>>^ porque um homem irrepreensível se apressou a interceder pelo povo, servindo-se das armas do seu ministério, a oração e a expiação do incenso. Atalhou os progressos da tua ira e pôs fim ao flagelo, mostrando que era teu servo.

[[v27-18-22]]

^<<v27-18-22,22>>^ Não dominou a sedição com a força do corpo, nem com o poder das armas, mas sim com a sua palavra deteve o (anjo) exterminador, recordando os juramentos feitos aos patriarcas e a aliança.

[[v27-18-23]]

^<<v27-18-23,23>>^ Quando já os mortos jaziam uns sobre os outros, ele, metendo-se de permeio, deteve a cólera e cortou-lhe o caminho que ia ter aos vivos.

[[v27-18-24]]

^<<v27-18-24,24>>^ Na vestidura talar que trazia estava simbolizado todo o mundo; os nomes gloriosos dos antepassados estavam gravados nas quatro ordens de pedras (preciosas), e a tua soberania estava gravada no diadema da sua cabeça.

[[v27-18-25]]

^<<v27-18-25,25>>^ Diante destas coisas retrocedeu o exterminador porque bastava esta simples amostra da ira divina.

'''

xref:027-sabedoria/027-sabedoria-017.adoc#v27-17-0[&#60; Capítulo Anterior] | <<v27-18-0,Topo>> | xref:027-sabedoria/027-sabedoria-019.adoc#v27-19-0[Próximo Capítulo &#62;]