include::./index.adoc[]

[[v27-14-0]]
=== Sabedoria, 14
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Sabedoria 14 trata da loucura dos povos que adoram ídolos e dos males que isso causa, enquanto exalta a sabedoria em Deus. Aqui estão cinco versículos relacionados com os temas do capítulo:
* Isaías 44:20: "Ele se alimenta de cinzas, o coração enganoso o desvia; ele não consegue salvar-se nem dizer: 'Não é mentira o que tenho nas mãos?'" Este versículo descreve a futilidade da adoração de ídolos e como isso leva à enganação e à falta de salvação.
* Salmos 96:5: "Todos os deuses dos povos são ídolos, mas o Senhor fez os céus." Este versículo destaca a superioridade de Deus sobre os ídolos e aponta para a verdadeira adoração a Ele.
* Isaías 2:18: "E todos os ídolos desaparecerão completamente." Aqui, o profeta Isaías fala do fim dos ídolos e como eles serão deixados para trás quando a verdadeira adoração a Deus for estabelecida.
* Atos 17:29: "Sendo, pois, descendência de Deus, não devemos pensar que a Divindade é semelhante ao ouro, à prata, ou à pedra, esculpida pela arte e imaginação do homem." O apóstolo Paulo fala aos gregos em Atenas sobre a verdadeira natureza de Deus e como Ele não pode ser representado por ídolos feitos por mãos humanas.
* 1 Coríntios 10:19-20: "Será que quero dizer com isso que o sacrifício oferecido aos ídolos é alguma coisa? Ou que um ídolo é alguma coisa? Não! Mas digo que aquilo que os pagãos sacrificam, eles sacrificam aos demônios, e não a Deus. E eu não quero que vocês tenham comunhão com os demônios." O apóstolo Paulo adverte os cristãos em Corinto sobre a perigosa adoração de ídolos e como ela pode levar à comunhão com demônios em vez de Deus.
****

[[v27-14-1]]

^<<v27-14-1,1>>^ Um outro ainda, fazendo tenção de se fazer ao mar, preparando-se para atravessar as impetuosas ondas, invoca um madeiro mais frágil do que o barco que o leva.

[[v27-14-2]]

^<<v27-14-2,2>>^ Com efeito, a cobiça de ganhar inventou o navio, e um artista pela sua sabedoria o fabricou. (ver nota)

[[v27-14-3]]

^<<v27-14-3,3>>^ Mas a tua providência, ó Pai, é que o governa, porque tu até no mar abriste caminho, e uma derrota seguríssima por entre as ondas, (ver nota)

[[v27-14-4]]

^<<v27-14-4,4>>^ mostrando que és poderoso para salvar de todos (os perigos), ainda que alguém se meta no mar sem conhecimento da arte (de marear).

[[v27-14-5]]

^<<v27-14-5,5>>^ Queres, entretanto, que as obras da tua sabedoria não sejam vãs, e, por isso, os homens confiam a um pequeno lenho as suas vidas, e, atravessando o mar sobre uma embarcação, chegam a salvamento. (ver nota)

[[v27-14-6]]

^<<v27-14-6,6>>^ Desta sorte, nos primeiros tempos, quando pereceram os soberbos gigantes, refugiou-se a esperança de toda a terra numa barca, conservando para o mundo a semente das novas gerações, graças à tua mão que a governava. (ver nota)

[[v27-14-7]]

^<<v27-14-7,7>>^ O madeiro, do qual se faz bom uso, é bendito.

[[v27-14-8]]

^<<v27-14-8,8>>^ mas o ídolo, obra das mãos (do homem), é maldito, ele e o seu autor; este, porque de facto o fabricou, e aquele, porque, sendo uma coisa corruptível foi chamado deus.

[[v27-14-9]]

^<<v27-14-9,9>>^ Deus aborrece, de facto, igualmente o ímpio e a sua impiedade.

[[v27-14-10]]

^<<v27-14-10,10>>^ A obra será castigada juntamente com o seu autor.

[[v27-14-11]]

^<<v27-14-11,11>>^ Por esta causa serão também julgados os ídolos das nações, porque, no meio da criação de Deus, tornaram-se uma abominação, objecto de escândalo para as almas dos homens, e um laço para os pés dos insensatos. (ver nota)

[[v27-14-12]]

^<<v27-14-12,12>>^ A ideia de fazer ídolos foi o princípio da fornicação, a sua invenção foi a perda da vida. (ver nota)

[[v27-14-13]]

^<<v27-14-13,13>>^ Eles não existiam no princípio, nem durarão sempre.

[[v27-14-14]]

^<<v27-14-14,14>>^ Foi a vaidade dos homens que os introduziu no mundo, e por isso, em breve, se verá o seu fim, decidido por Deus.

[[v27-14-15]]

^<<v27-14-15,15>>^ Penetrado um pai de dor amarga, fez a imagem de seu filho, que prematuramente lhe tinha sido arrebatado, e aquele, que não era mais que um morto, começou a adorar como deus, transmitindo aos seus servos ritos secretos e cerimônias.

[[v27-14-16]]

^<<v27-14-16,16>>^ Depois, com o andar do tempo, firmando-se este ímpio costume, foi observado como uma lei, e por ordem dos príncipes foram também adorados os simulacros.

[[v27-14-17]]

^<<v27-14-17,17>>^ Aqueles que não podiam honrar em presença os que estavam distantes, mandavam representar a sua figura que se achava longe, mandavam fazer a imagem visível do Rei, a quem queriam honrar, a fim de prestar aquele que estava ausente um culto tão zeloso como se estivesse presente.

[[v27-14-18]]

^<<v27-14-18,18>>^ A ambição do artista excitou também este culto mesmo no espírito dos que não conheciam o rei,

[[v27-14-19]]

^<<v27-14-19,19>>^ porque, desejando o artista agradar ao soberano, esmerou-se com a sua arte em tornar a representação mais bela que a realidade;

[[v27-14-20]]

^<<v27-14-20,20>>^ o vulgo, seduzido pela beleza da obra, tomou por um Deus aquele que até ali tinha honrado como homem.

[[v27-14-21]]

^<<v27-14-21,21>>^ Isto foi ocasião de queda para a vida (humana), (proveniente) de que os homens, sujeitando-se à lei da desgraça ou da tirania, deram às pedras e à madeira o nome incomunicável. (ver nota)

[[v27-14-22]]

^<<v27-14-22,22>>^ Como se não bastasse terem errado acerca do conhecimento de Deus, os homens, vivendo em grande guerra de ignorância, deram o nome de paz a tão grandes males. (ver nota)

[[v27-14-23]]

^<<v27-14-23,23>>^ Sacrificando os seus próprios filhos, celebrando mistérios clandestinos, entregando-se a orgias desenfreadas de ritos estranhos,

[[v27-14-24]]

^<<v27-14-24,24>>^ não conservam puros nem o seu proceder nem os seu matrimônios, mas um mata outro por traição ou o ultraja com o adultério.

[[v27-14-25]]

^<<v27-14-25,25>>^ Há em toda a parte, numa confusão completa, sangue, homicídio, furto, engano, corrupção, infidelidade, revolta, perjúrio, perseguição dos bons,

[[v27-14-26]]

^<<v27-14-26,26>>^ esquecimento dos benefícios, contaminação das almas, crimes contra a natureza, instabilidade dos matrimônios, adultério e impudicícia.

[[v27-14-27]]

^<<v27-14-27,27>>^ Porque o culto dos ídolos sem nome é o princípio, a causa e o fim de todo o mal.

[[v27-14-28]]

^<<v27-14-28,28>>^ Praticam loucuras enquanto se divertem, ou fazem vaticínios cheios de mentira, ou vivem na Injustiça, ou juram falso sem escrúpulo.

[[v27-14-29]]

^<<v27-14-29,29>>^ Como depositam a sua confiança nos ídolos, que não têm vida, esperam não receber punição de tais perjúrios.

[[v27-14-30]]

^<<v27-14-30,30>>^ Porém sobre eles virá o merecido castigo por ambos estes crimes: porque pensaram mal de Deus aderindo aos ídolos, e com fraude juraram injustamente, desprezando a santidade.

[[v27-14-31]]

^<<v27-14-31,31>>^ Não é o poder daqueles, por quem juraram, mas a pena devida aos pecadores que anda sempre no alcance da prevaricação dos injustos.

'''

xref:027-sabedoria/027-sabedoria-013.adoc#v27-13-0[&#60; Capítulo Anterior] | <<v27-14-0,Topo>> | xref:027-sabedoria/027-sabedoria-015.adoc#v27-15-0[Próximo Capítulo &#62;]