include::./index.adoc[]

[[v43-1-0]]
=== Sofonias, 1
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 1 de Sofonias começa com a profecia da destruição que virá sobre Judá e Jerusalém devido à sua idolatria e injustiça. O próprio Deus irá puni-los por sua desobediência. Abaixo estão cinco versículos relacionados com os temas abordados em Sofonias 1:
* Jeremias 25:34: "Uivai, pastores, e clamai; e revolvei-vos na cinza, líderes do rebanho; porque já se cumpriram os vossos dias para serdes mortos; e eu vos dispersarei, e caireis como vaso desejável." Este verso mostra que o julgamento de Deus é iminente e inevitável, e ninguém escapará dele.
* Isaías 2:12: "Porque o dia do SENHOR dos Exércitos será contra todo o soberbo e altivo, e contra todo o que se exalta, para que seja abatido." Este verso fala sobre como Deus punirá aqueles que se acham superiores e arrogantes, o que se relaciona com o tema da justiça divina em Sofonias 1.
* Ezequiel 30:3: "Porque se aproxima o dia, sim, já está próximo o dia do SENHOR; dia de nuvens será, o tempo das nações." Este verso destaca a proximidade do Dia do Senhor, que é uma tema importante em Sofonias 1.
* Isaías 13:9: "Eis que vem o dia do SENHOR, horrendo, com furor e ira ardente, para pôr a terra em assolação, e dela destruir os pecadores." Este verso fala sobre a vinda do Dia do Senhor e sua ira sobre os pecadores, que é um tema principal em Sofonias 1.
* Amós 5:18: "Ai dos que desejam o dia do SENHOR! Para que quereis vós este dia do SENHOR? Ele é trevas e não luz." Este verso destaca que o Dia do Senhor é um dia de julgamento e punição, não um dia de alegria, e se relaciona com o tema do juízo divino em Sofonias 1.
****

[[v43-1-1]]

^<<v43-1-1,1>>^ Palavra do Senhor, que foi dirigida a Sofonias, filho de Cusi, filho de Godolias, filho de Amarias, filho de Bzequias, no tempo de Josias, filho de Amon, rei de Judá. (ver nota)

[[v43-1-2]]

^<<v43-1-2,2>>^ Destruirei tudo sobre a face da terra, diz o Senhor;

[[v43-1-3]]

^<<v43-1-3,3>>^ destruirei os homens e os animais, destruirei as aves do céu e os peixes do mar; farei desaparecer os escândalos com os ímpios; exterminarei da terra os homens, diz o Senhor.

[[v43-1-4]]

^<<v43-1-4,4>>^ Estenderei a minha mão contra Judá e contra todos os habitantes de Jerusalém; exterminarei deste lugar os restos (da idolatria) de Baal, até os nomes (ou a memória) dos seus ministros e sacerdotes;

[[v43-1-5]]

^<<v43-1-5,5>>^ (exterminarei) os que adoram a milícia (ou os astros) do céu sobre os telhados, os que adoram o Senhor e Juram pelo seu nome, mas ao mesmo tempo juram (realmente) pelo nome de Melcom;

[[v43-1-6]]

^<<v43-1-6,6>>^ e os que deixam de seguir o Senhor, os que não buscam o Senhor, nem procuram encontrá-lo.

[[v43-1-7]]

^<<v43-1-7,7>>^ Silêncio diante da face do Senhor Deus, porque o dia (terrível) do Senhor está perto, porque o Senhor preparou um sacrifício, santificou os convidados.

[[v43-1-8]]

^<<v43-1-8,8>>^ No dia do sacrifício do Senhor castigarei (diz Deus) os chefes e os príncipes reais (de Jerusalém) e todos os que se vestem de trajes estrangeiros;

[[v43-1-9]]

^<<v43-1-9,9>>^ castigarei nesse dia todos os que entram com arrogância pelo limiar (do templo) e que enchem de violência e de fraude a casa do seu senhor.

[[v43-1-10]]

^<<v43-1-10,10>>^ Naquele dia haverá, diz o Senhor, muitos clamores à Porta dos Peixes, gemidos das bandas da cidade nova, grande tumulto do lado das colinas. (ver nota)

[[v43-1-11]]

^<<v43-1-11,11>>^ Habitantes do Maktesh lamentai-vos, porque todo o povo dos mercadores foi aniquilado, todos os que traziam cargas de prata pereceram. (ver nota)

[[v43-1-12]]

^<<v43-1-12,12>>^ Naquele tempo acontecerá isto: esquadrinharei Jerusalém com lanternas e castigarei os homens que estão sentados sobre as suas fezes, que dizem nos seus corações: O Senhor não faz bem nem mal (a ninguém). (ver nota)

[[v43-1-13]]

^<<v43-1-13,13>>^ As suas riquezas serão saqueadas, as suas casas devastadas; edificarão casas, mas não as habitarão; plantarão vinhas, mas não lhes beberão o vinho.

[[v43-1-14]]

^<<v43-1-14,14>>^ O dia grande do Senhor está próximo; está próximo, vai chegando com velocidade! Tremendo é o ruído do dia do Senhor; o forte se verá nele em grande aperto.

[[v43-1-15]]

^<<v43-1-15,15>>^ Esse dia será um dia de ira, um dia de tribulação e angústia, um dia de calamidade e miséria, um dia de trevas e escuridão, um dia de nuvens e espesso nevoeiro,

[[v43-1-16]]

^<<v43-1-16,16>>^ um dia de trombeta e de gritos guerreiros contra as cidades fortificadas e contra as torres elevadas. (ver nota)

[[v43-1-17]]

^<<v43-1-17,17>>^ Atribularei os homens, e eles andarão como cegos, porque pecaram contra o Senhor; o seu sangue será espalhado como poeira, e os seus corpos serão (tratados) como esterco.

[[v43-1-18]]

^<<v43-1-18,18>>^ Nem a sua prata, nem o seu ouro os poderão livrar no dia da ira do Senhor; no fogo do seu zelo será devorada toda a terra, porque ele se apressará a exterminar completamente todos os habitantes da mesma terra.

'''

xref:042-habacuc/042-habacuc-003.adoc#v42-3-0[&#60; Capítulo Anterior] | <<v43-1-0,Topo>> | xref:043-sofonias/043-sofonias-002.adoc#v43-2-0[Próximo Capítulo &#62;]