include::./index.adoc[]

[[v48-4-0]]
=== São Marcos, 4
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* São Marcos 4 apresenta várias parábolas de Jesus sobre o Reino de Deus e sua mensagem. A primeira parábola é sobre o semeador que espalha a semente em diferentes tipos de solo. A segunda parábola é sobre a semente que cresce por si mesma. A terceira parábola é sobre o grão de mostarda que se torna uma árvore grande. Jesus também acalma a tempestade no mar e cura o endemoninhado geraseno.
* Lucas 8:15: "Mas a que caiu em boa terra são aqueles que, com coração bom e perfeito, ouvem a palavra, a retêm e dão fruto com perseverança." Esse versículo se relaciona diretamente com a primeira parábola de Jesus sobre o semeador. Ele enfatiza a importância de ouvir a palavra de Deus e de ter um coração aberto e receptivo para que a mensagem possa frutificar.
* 1 Coríntios 3:6-7: "Eu plantei, Apolo regou; mas Deus deu o crescimento. De maneira que, nem o que planta é alguma coisa, nem o que rega, mas Deus, que dá o crescimento." Esses versículos se relacionam com a segunda parábola de Jesus sobre a semente que cresce por si mesma. Eles lembram que Deus é quem dá o crescimento e a vida, independentemente do trabalho humano.
* Ezequiel 17:22-24: "Assim diz o Senhor Deus: Também tomarei do cimo da copa do alto cedro, e o porei; do principal dos seus renovos cortarei um ramo, e o plantarei sobre um monte alto e sublime. Na montanha alta de Israel o plantarei, e ele dará ramos, e produzirá fruto, e se fará um cedro soberbo; e debaixo dele habitarão aves de toda a sorte; à sombra dos seus ramos habitarão todas as aves do céu." Esses versículos se relacionam com a terceira parábola de Jesus sobre o grão de mostarda que se torna uma árvore grande. Eles lembram que Deus pode usar coisas pequenas para fazer grandes obras e que sua obra é frutífera e acolhedora.
* Salmo 107:29: "Faz cessar a tempestade, e acalmam-se as suas ondas." Este versículo se relaciona com o episódio em que Jesus acalma a tempestade no mar. Ele mostra o poder de Jesus sobre as forças da natureza e a confiança que podemos ter nele, mesmo em momentos de medo e perigo.
* Atos 16:18: "E isto ela fazia por muitos dias. Mas Paulo, perturbado, voltou-se e disse ao espírito: Em nome de Jesus Cristo, te mando que saias dela. E na mesma hora saiu." Esse versículo se relaciona com a cura do endemoninhado geraseno. Ele destaca a autoridade de Jesus sobre os espíritos malignos e a capacidade de Jesus de trazer cura e libertação às pessoas em necessidade.
****

[[v48-4-1]]

^<<v48-4-1,1>>^ Começou de novo a ensinar à beira do mar; e juntou-se à roda dele tão grande multidão que teve de subir para uma barca e sentar-se dentro dela no mar, enquanto que toda a multidão estava em terra na praia.

[[v48-4-2]]

^<<v48-4-2,2>>^ E ensinava-lhes muitas coisas por meio de parábolas. Dizia-lhes segundo o seu meio de ensinar :

[[v48-4-3]]

^<<v48-4-3,3>>^ "Ouvi: Eis saiu o semeador a semear.

[[v48-4-4]]

^<<v48-4-4,4>>^ Enquanto semeava, uma parte da semente caiu ao longo do caminho, e vieram as aves do céu, e comeram-na.

[[v48-4-5]]

^<<v48-4-5,5>>^ Outra parte caiu sobre pedregulho, onde tinha pouca terra; e nasceu logo, porque não havia profundidade de terra;

[[v48-4-6]]

^<<v48-4-6,6>>^ mas, quando saiu o sol, foi crestada pelo calor, e, como não tinha raiz, secou.

[[v48-4-7]]

^<<v48-4-7,7>>^ Outra parte caiu entre espinhos; e cresceram os espinhos, e a sufocaram, e não deu fruto.

[[v48-4-8]]

^<<v48-4-8,8>>^ Outra caiu em boa terra; e deu fruto que vingou, e cresceu, e um grão deu trinta, outro sessenta, e outro cem ."

[[v48-4-9]]

^<<v48-4-9,9>>^ E acrescentava; "Quem tem ouvidos para ouvir, ouça."

[[v48-4-10]]

^<<v48-4-10,10>>^ Quando se encontrou só, os doze, que estavam com ele, interrogaram-no sobre a parábola.

[[v48-4-11]]

^<<v48-4-11,11>>^ Disse-lhes; "A vós é concedido conhecer o mistério do reino de Deus; porém, aos que são de fora, tudo se lhes propõe em parábolas,

[[v48-4-12]]

^<<v48-4-12,12>>^ para que, olhando, não vejam, ouvindo, não entendam, de sorte que não se convertam, e lhes sejam perdoados os pecados." (ver nota)

[[v48-4-13]]

^<<v48-4-13,13>>^ E acrescentou: "Não entendeis esta parábola? Então como entendereis todas as outras? (ver nota)

[[v48-4-14]]

^<<v48-4-14,14>>^ O que o semeador semeia é a palavra.

[[v48-4-15]]

^<<v48-4-15,15>>^ Uns encontram-se ao longo do caminho onde ela é semeada; logo que a ouviram, vem Satanás tirar a palavra semeada neles. (ver nota)

[[v48-4-16]]

^<<v48-4-16,16>>^ Outros recebem a semente em terreno pedregoso; ouvem a palavra, logo a recebem com gosto;

[[v48-4-17]]

^<<v48-4-17,17>>^ mas não têm raízes em si, são inconstantes; depois, levantando-se a tribulação ou a perseguição por causa da palavra, sucumbem imediatamente.

[[v48-4-18]]

^<<v48-4-18,18>>^ Outros recebem a semente entre espinhos; ouvem a palavra,

[[v48-4-19]]

^<<v48-4-19,19>>^ mas as solicitudes do século, a sedução das riquezas, e os outros afetos desordenados, entrando, afogam a palavra, e ela fica infrutuosa.

[[v48-4-20]]

^<<v48-4-20,20>>^ Outros recebem a semente em boa terra; ouvem a palavra, recebem-na, e dão fruto, um a trinta, outro a sessenta, e outro a cem por um.

[[v48-4-21]]

^<<v48-4-21,21>>^ Dizia-lhes mais; "Porventura traz-se a lucerna para a meter debaixo do alqueire ou debaixo do leito? Não é para ser posta sobre o candelabro? (ver nota)

[[v48-4-22]]

^<<v48-4-22,22>>^ Porque não há coisa alguma escondida que não venha a ser manifesta, nem que seja feita para estar oculta, mas para vir a descoberto.

[[v48-4-23]]

^<<v48-4-23,23>>^ Se alguém tem ouvidos para ouvir, ouça. (ver nota)

[[v48-4-24]]

^<<v48-4-24,24>>^ Dizia-lhes mais: "Atendei ao que ouvis. Com a medida com que medirdes, vos medirão a vós, e ainda se vos acrescentará. (ver nota)

[[v48-4-25]]

^<<v48-4-25,25>>^ Porque ao que tem, dar-se-lhe-á ainda mais e ao que não tem, ainda o que tem, lhe será tirado."

[[v48-4-26]]

^<<v48-4-26,26>>^ Dizia também: "O reino de Deus é como um homem que lança a semente à terra.

[[v48-4-27]]

^<<v48-4-27,27>>^ Dorme e se levanta, noite e dia, e a semente brota e cresce sem ele saber como. (ver nota)

[[v48-4-28]]

^<<v48-4-28,28>>^ Porque a terra por si mesma produz, primeiramente, a erva, depois a espiga, e por último o trigo grado na espiga.

[[v48-4-29]]

^<<v48-4-29,29>>^ E, quando o fruto está maduro, mete logo a fouce, porque está chegado o tempo da ceifa."

[[v48-4-30]]

^<<v48-4-30,30>>^ Dizia mais: "A que coisa compararemos nós o reino de Deus? Com que parábola o figuraremos?

[[v48-4-31]]

^<<v48-4-31,31>>^ É como um grão de mostarda que, quando se semeia na terra, é a menor de todas as sementes que há na terra;

[[v48-4-32]]

^<<v48-4-32,32>>^ mas, depois que é semeado, cresce e torna-se maior que todas as hortaliças, e cria grandes ramos, de modo que as aves do céu podem vir pousar à sua sombra (Dn. 4, 9 e Dn. 4, 18; Ez. 17, 23 e Ez. 31, 6).

[[v48-4-33]]

^<<v48-4-33,33>>^ Assim lhes propunha a palavra com muitas parábolas como estas, conforme o permitia a capacidade dos ouvintes.

[[v48-4-34]]

^<<v48-4-34,34>>^ Não lhes falava sem parábolas; porém, tudo explicava em particular a seus discípulos.

[[v48-4-35]]

^<<v48-4-35,35>>^ Naquele mesmo dia, já sobre a tarde, disse-lhes: "Passemos à outra banda."

[[v48-4-36]]

^<<v48-4-36,36>>^ Deixando a multidão, o levaram, assim como estava, na barca. Outras embarcações o seguiram.

[[v48-4-37]]

^<<v48-4-37,37>>^ Então levantou-se uma grande tormenta de vento, e as ondas lançavam-se sobre a barca, de sorte que a barca se enchia de água. (ver nota)

[[v48-4-38]]

^<<v48-4-38,38>>^ Jesus estava dormindo na popa, sobre um travesseiro. Acordaram-no, e disseram-lhe : "Mestre, não se te dá que pereçamos?

[[v48-4-39]]

^<<v48-4-39,39>>^ Ele levantou-se, ameaçou o vento, e disse para o mar: "Cala-te, emudece." O vento amainou, e seguiu-se uma grande bonança.

[[v48-4-40]]

^<<v48-4-40,40>>^ Depois disse-lhes : "Porque sois tão tímidos? Ainda não tendes fé?" Ficaram cheios de grande temor, e diziam uns para os outros: "Quem será este, que até o vento e o mar lhe obedecem?"

'''

xref:048-sao-marcos/048-sao-marcos-003.adoc#v48-3-0[&#60; Capítulo Anterior] | <<v48-4-0,Topo>> | xref:048-sao-marcos/048-sao-marcos-005.adoc#v48-5-0[Próximo Capítulo &#62;]