include::./index.adoc[]

[[v48-13-0]]
=== São Marcos, 13
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 13 de Marcos é conhecido como o "Discurso do Monte das Oliveiras", no qual Jesus fala sobre a destruição do templo, o fim dos tempos e a sua segunda vinda. Os versículos escolhidos são:
* Mateus 24:42: "Portanto, vigiem, porque vocês não sabem em que dia virá o seu Senhor." Neste versículo, Jesus está instruindo seus discípulos a ficarem atentos e preparados para a sua segunda vinda, que virá de forma inesperada.
* Mateus 24:14: "E este evangelho do Reino será pregado em todo o mundo como testemunho a todas as nações, e então virá o fim." Jesus afirma que o evangelho será pregado em todo o mundo antes do fim dos tempos, indicando que a salvação estará disponível para todas as nações.
* Apocalipse 1:7: "Eis que ele vem com as nuvens, e todo olho o verá, até mesmo aqueles que o traspassaram; e todas as tribos da terra se lamentarão por causa dele. Certamente isso acontecerá! Amém!" Este versículo se refere à segunda vinda de Cristo, quando todos verão a sua glória e autoridade.
* Apocalipse 22:12: "Eis que venho em breve! A minha recompensa está comigo, e eu retribuirei a cada um de acordo com o que fez." Aqui, Jesus reafirma a sua vinda e promete recompensar cada pessoa de acordo com as suas obras.
* 1 Tessalonicenses 4:16-17: "Pois o Senhor mesmo descerá do céu com brado de comando, com voz de arcanjo e com trombeta de Deus, e os mortos em Cristo ressuscitarão primeiro. Depois nós, os que estivermos vivos, seremos arrebatados juntamente com eles nas nuvens, para o encontro com o Senhor nos ares. E assim estaremos com o Senhor para sempre." Este trecho se refere à segunda vinda de Cristo, quando os mortos serão ressuscitados e os crentes que estiverem vivos serão arrebatados para encontrar o Senhor nos ares.
****

[[v48-13-1]]

^<<v48-13-1,1>>^ Quando saía do templo, disse-lhe um dos seus discípulos: "Olha, Mestre, que pedras e que construções!"

[[v48-13-2]]

^<<v48-13-2,2>>^ Jesus disse-lhe: "Vês estes grandes edifícios? Não ficará pedra sobre pedra, que não seja derribada."

[[v48-13-3]]

^<<v48-13-3,3>>^ Estando sentado sobre o monte das Oliveiras, defronte do templo, interrogaram-no aparte Pedro, Tiago, João e André:

[[v48-13-4]]

^<<v48-13-4,4>>^ "Diz-nos quando sucederão estas coisas, e que sinal haverá, quando tudo isto estiver para se cumprir?"

[[v48-13-5]]

^<<v48-13-5,5>>^ Então Jesus começou a dizer-lhes : "Vede que ninguém vos engane. (ver nota)

[[v48-13-6]]

^<<v48-13-6,6>>^ Muitos virão em meu nome, dizendo; Sou eu; e enganarão muitos.

[[v48-13-7]]

^<<v48-13-7,7>>^ Quando ouvirdes falar de guerras e de rumores de guerras, não temais; porque importa que estas coisas aconteçam; mas não será ainda o fim.

[[v48-13-8]]

^<<v48-13-8,8>>^ Levantar-se-á nação contra nação, reino contra reino. Haverá terremotos em diversas partes, e fomes. Estas coisas serão o princípio das dores.

[[v48-13-9]]

^<<v48-13-9,9>>^ Tomai, porém, cuidado convosco. Hão-de-vos entregar nos tribunais, sereis açoutados nas sinagogas, sereis, por minha causa, levados diante dos governadores e dos reis, para dar testemunho de mim perante eles.

[[v48-13-10]]

^<<v48-13-10,10>>^ Mas, antes, deve o Evangelho ser pregado a todas as nações.

[[v48-13-11]]

^<<v48-13-11,11>>^ Quando, pois, vos levarem para vos entregar, não premediteis no que haveis de dizer, mas dizei o que vos for inspirado nessa hora; porque não sois vós que falais, mas o Espírito Santo.

[[v48-13-12]]

^<<v48-13-12,12>>^ Então o irmão entregará à morte o seu irmão, o pai o filho; os filhos levantar-se-ão contra os pais e lhes darão a morte.

[[v48-13-13]]

^<<v48-13-13,13>>^ Sereis odiados de todos por causa do meu nome. Mas o que perseverar até ao fim, esse será salvo.

[[v48-13-14]]

^<<v48-13-14,14>>^ Quando, pois, virdes a abominação da desolação posta onde não devia estar - leitor, atende bem! - então os que estiverem na Judeia fujam para os montes,

[[v48-13-15]]

^<<v48-13-15,15>>^ o que estiver sobre o telhado, não desça nem entre para levar coisa alguma de sua casa;

[[v48-13-16]]

^<<v48-13-16,16>>^ e o que se encontrar no campo, não volte atrás a buscar o seu manto.

[[v48-13-17]]

^<<v48-13-17,17>>^ Ai das mulheres grávidas, e das que tiverem crianças de peito naqueles dias!

[[v48-13-18]]

^<<v48-13-18,18>>^ Rogai, pois, que não suceda isto no inverno.

[[v48-13-19]]

^<<v48-13-19,19>>^ Porque, naqueles dias, haverá tribulações, quais não houve desde o principio do mundo, que Deus criou, até agora, nem mais haverá.

[[v48-13-20]]

^<<v48-13-20,20>>^ E se o Senhor não abreviasse aqueles dias, nenhuma pessoa se salvaria; mas ele os abreviou, em atenção aos eleitos que escolheu. (ver nota)

[[v48-13-21]]

^<<v48-13-21,21>>^ Então, se alguém vos disser: Eis aqui está o Cristo, ei-lo acolá, não deis crédito.

[[v48-13-22]]

^<<v48-13-22,22>>^ Porque se levantarão falsos cristos e falsos profetas, e farão milagres e prodígios para enganarem, se fosse possível, até os mesmos escolhidos. (ver nota)

[[v48-13-23]]

^<<v48-13-23,23>>^ Estai, pois, de sobreaviso, eis que eu vos predisse tudo.

[[v48-13-24]]

^<<v48-13-24,24>>^ Naqueles dias, depois daquela tribulação, o sol escurecerá, a lua não dará o seu resplendor,

[[v48-13-25]]

^<<v48-13-25,25>>^ as estrelas cairão do céu, e serão abaladas as potestades que estão nos céus.

[[v48-13-26]]

^<<v48-13-26,26>>^ Então verão o Filho do homem vir sobre as nuvens, com grande poder e glória.

[[v48-13-27]]

^<<v48-13-27,27>>^ E enviará logo os seus anjos, e juntará os seus escolhidos dos quatro ventos, desde a extremidade da terra até à extremidade do céu.

[[v48-13-28]]

^<<v48-13-28,28>>^ Ouvi uma comparação tirada da figueira: Quando os seus ramos estão já tenros e as folhas brotam, sabeis que está perto o estio;

[[v48-13-29]]

^<<v48-13-29,29>>^ assim também quando virdes acontecer estas coisas, sabei que (a vinda do Filho do homem para o juízo final) está perto, às portas.

[[v48-13-30]]

^<<v48-13-30,30>>^ Na verdade vos digo que não passará esta geração, sem que se cumpram todas estas coisas.

[[v48-13-31]]

^<<v48-13-31,31>>^ O céu e a terra passarão, mas as minhas palavras não passarão.

[[v48-13-32]]

^<<v48-13-32,32>>^ A respeito, porém, desse dia ou dessa hora, ninguém sabe, nem os anjos do céu, nem o Filho, mas só o Pai. (ver nota)

[[v48-13-33]]

^<<v48-13-33,33>>^ Estai de sobreaviso, vigiai, porque não sabeis quando será o momento.

[[v48-13-34]]

^<<v48-13-34,34>>^ Será como um homem que, empreendendo uma viagem, deixou a sua casa, deu autoridade, aos seus servos, indicando a cada um a sua tarefa, e ordenou ao porteiro que estivesse vigilante.

[[v48-13-35]]

^<<v48-13-35,35>>^ Vigiai, pois, visto que não sabeis quando virá o senhor da casa, se de tarde, se à meia-noite, se ao cantar do galo, se pela manhã,

[[v48-13-36]]

^<<v48-13-36,36>>^ para que, vindo de repente, vos não encontre dormindo.

[[v48-13-37]]

^<<v48-13-37,37>>^ O que eu, pois, digo a vós, o digo a todos: Vigiai!"

'''

xref:048-sao-marcos/048-sao-marcos-012.adoc#v48-12-0[&#60; Capítulo Anterior] | <<v48-13-0,Topo>> | xref:048-sao-marcos/048-sao-marcos-014.adoc#v48-14-0[Próximo Capítulo &#62;]