include::./index.adoc[]

[[v48-15-0]]
=== São Marcos, 15
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* São Marcos 15 descreve a prisão, julgamento e crucificação de Jesus. O capítulo é rico em detalhes e emoção, e revela a injustiça que Jesus sofreu nas mãos dos líderes religiosos e políticos de seu tempo. Aqui estão cinco versículos da Bíblia que estão relacionados aos temas abordados em São Marcos 15:
* Isaías 53:5: "Mas ele foi ferido pelas nossas transgressões, e moído pelas nossas iniquidades; o castigo que nos traz a paz estava sobre ele, e pelas suas pisaduras fomos sarados." Este versículo profético de Isaías fala sobre o sofrimento que Jesus suportou em nome da humanidade. Ele carregou nossos pecados e foi punido em nosso lugar.
* Romanos 5:8: "Mas Deus prova o seu amor para conosco, em que Cristo morreu por nós, sendo nós ainda pecadores." Este versículo nos lembra que, embora sejamos pecadores, Deus nos amou tanto que enviou seu filho Jesus para morrer por nós na cruz.
* João 19:17: "E ele, levando a sua cruz, saiu para o lugar chamado Calvário, que em hebraico se chama Gólgota." Esse versículo nos lembra do fardo que Jesus carregou quando foi para a cruz. Ele carregou sua própria cruz pelas ruas de Jerusalém antes de ser crucificado no Calvário.
* Filipenses 2:8: "E, achado na forma de homem, humilhou-se a si mesmo, sendo obediente até à morte, e morte de cruz." Este versículo fala sobre a humildade de Jesus, que se tornou homem e se submeteu à morte na cruz para salvar a humanidade.
* Hebreus 12:2: "Olhando para Jesus, autor e consumador da fé, o qual pelo gozo que lhe estava proposto suportou a cruz, desprezando a afronta, e assentou-se à destra do trono de Deus." Este versículo nos encoraja a seguir o exemplo de Jesus, que suportou a cruz e superou a tentação, para que possamos ter a vida eterna com ele no céu.
****

[[v48-15-1]]

^<<v48-15-1,1>>^ Logo pela manhã, tiveram conselho os príncipes dos sacerdotes com os anciães, os escribas e com todo o Sinédrio. Manietando Jesus, o levaram e entregaram a Pilatos.

[[v48-15-2]]

^<<v48-15-2,2>>^ Pilatos perguntou-lhe: "Tu és o Rei dos Judeus?" Ele respondeu-lhes: "Tu o dizes."

[[v48-15-3]]

^<<v48-15-3,3>>^ Os príncipes dos sacerdotes acusavam-no de muitas coisas.

[[v48-15-4]]

^<<v48-15-4,4>>^ Pilatos interrogou-o novamente: "Não respondes coisa alguma? Vê de quantas coisas te acusam."

[[v48-15-5]]

^<<v48-15-5,5>>^ Mas Jesus não respondeu mais nada, de sorte que Pilatos estava admirado.

[[v48-15-6]]

^<<v48-15-6,6>>^ Ora ele costumava no dia da festa (de Páscoa) soltar-lhes um dos presos, qualquer que eles pedissem.

[[v48-15-7]]

^<<v48-15-7,7>>^ Havia um chamado Barrabás, que estava preso com outros sediciosos, o qual, num motim, tinha cometido um homicídio.

[[v48-15-8]]

^<<v48-15-8,8>>^ Juntando-se o povo, começou a pedir o (indulto) que sempre lhes concedia.

[[v48-15-9]]

^<<v48-15-9,9>>^ Pilatos respondeu-lhes: "Quereis que vos solte o Rei dos Judeus?"

[[v48-15-10]]

^<<v48-15-10,10>>^ Porque sabia que os príncipes dos sacerdotes o tinham entregado por inveja.

[[v48-15-11]]

^<<v48-15-11,11>>^ Porém, os príncipes dos sacerdotes, incitaram o povo a que pedisse antes a liberdade de Barrabás.

[[v48-15-12]]

^<<v48-15-12,12>>^ Pilatos, falando outra vez, disse-lhes: "Que quereis pois que eu faça ao Rei dos Judeus?"

[[v48-15-13]]

^<<v48-15-13,13>>^ Eles tornaram a gritar: "Crucifica-o!"

[[v48-15-14]]

^<<v48-15-14,14>>^ Pilatos, porém, dizia-lhes: "Que mal fez ele?" Mas eles cada vez gritavam mais: "Crucifica-o!"

[[v48-15-15]]

^<<v48-15-15,15>>^ Então Pilatos, querendo satisfazer o povo, soltou-lhes Barrabás. Depois de fazer açoutar Jesus, entregou-o para ser crucificado.

[[v48-15-16]]

^<<v48-15-16,16>>^ Os soldados conduziram-no ao interior do átrio, isto é, ao Pretório, e ali juntaram toda a coorte.

[[v48-15-17]]

^<<v48-15-17,17>>^ Revestiram-no de púrpura e cingiram-lhe a cabeça com uma coroa entretecida de espinhos.

[[v48-15-18]]

^<<v48-15-18,18>>^ E começaram a saudá-lo: "Salve, Rei dos Judeus!"

[[v48-15-19]]

^<<v48-15-19,19>>^ E davam-lhe na cabeça com uma cana, cuspiam-lhe no rosto, e, pondo-se de joelhos, faziam-lhe reverências.

[[v48-15-20]]

^<<v48-15-20,20>>^ Depois de o terem escarnecido, despojaram-no da púrpura, vestiram-lhe os seus vestidos, e levaram-no para o crucificar.

[[v48-15-21]]

^<<v48-15-21,21>>^ Obrigarem um certo homem que a a passar, Simão de Cirene, que vinha do campo, pai de Alexandre e de Rufo, a levar a cruz.

[[v48-15-22]]

^<<v48-15-22,22>>^ Conduziram-no ao lugar do Gólgota, que quer dizer lugar do Crânio. (ver nota)

[[v48-15-23]]

^<<v48-15-23,23>>^ Davam-lhe a beber vinho misturado com mirra, mas ele não o tomou.

[[v48-15-24]]

^<<v48-15-24,24>>^ Tendo-o crucificado, dividiram os seus vestidos, lançando sortes sobre eles, para ver a parte que cada um levaria.

[[v48-15-25]]

^<<v48-15-25,25>>^ Era a hora tércia quando o crucificaram.

[[v48-15-26]]

^<<v48-15-26,26>>^ A causa da sua condenação estava escrita nesta inscrição: O REI DOS JUDEUS.

[[v48-15-27]]

^<<v48-15-27,27>>^ Com ele crucificaram dois ladrões, um à sua direita, e outro à esquerda.

[[v48-15-28]]

^<<v48-15-28,28>>^ Cumpriu-se a Escritura, que diz: Foi contado entre os maus (Is. 53, 12). (ver nota)

[[v48-15-29]]

^<<v48-15-29,29>>^ Os que iam passando blasfemavam, abanando as suas cabeças, e dizendo: "Ah! tu, que destróis o templo de Deus, e o reedificas em três dias,

[[v48-15-30]]

^<<v48-15-30,30>>^ salva-te a ti mesmo, descendo da cruz."

[[v48-15-31]]

^<<v48-15-31,31>>^ Do mesmo modo, escarnecendo-o também os príncipes dos sacerdotes e os escribas, diziam entre si: "Salvou os outros, e não se pode salvar a si mesmo.

[[v48-15-32]]

^<<v48-15-32,32>>^ O Cristo, o Rei de Israel desça agora da cruz, para que vejamos e acreditemos." Também os que tinham sido crucificados com ele o insultavam. (ver nota)

[[v48-15-33]]

^<<v48-15-33,33>>^ Chegada a hora sexta, cobriu-se toda a terra de trevas até à hora nona.

[[v48-15-34]]

^<<v48-15-34,34>>^ E, à hora nona, exclamou Jesus em alta voz: "Eloí, Eloí, lamma sabachtani?" que quer dizer: "Deus meu. Deus meu, porque me desamparaste?"

[[v48-15-35]]

^<<v48-15-35,35>>^ Ouvindo isto, alguns dos circunstantes diziam: "Eis que chama por Elias."

[[v48-15-36]]

^<<v48-15-36,36>>^ Correndo um, e ensopando uma esponja em vinagre, e atando-a numa cana, dava-lhe de beber, dizendo: "Deixai, vejamos se Elias vem tirá-lo." (ver nota)

[[v48-15-37]]

^<<v48-15-37,37>>^ Mas Jesus, dando um grande brado, expirou.

[[v48-15-38]]

^<<v48-15-38,38>>^ O véu do templo rasgou-se em duas partes, de alto a baixo.

[[v48-15-39]]

^<<v48-15-39,39>>^ O centurião, que estava defronte, vendo que Jesus expirava dando este brado, disse: "Verdadeiramente este homem era Filho de Deus."

[[v48-15-40]]

^<<v48-15-40,40>>^ Encontravam-se também ali algumas mulheres vindo de longe, entre as quais estava Maria Madalena, Maria, mãe de Tiago menor e de José, e Salomé,

[[v48-15-41]]

^<<v48-15-41,41>>^ as quais já o seguiam e serviam quando ele estava na Galileia, e muitas outras, que, juntamente com ele, tinham subido a Jerusalém.

[[v48-15-42]]

^<<v48-15-42,42>>^ Quando era já tarde - pois era a Preparação, isto é, a vigília de sábado - ,

[[v48-15-43]]

^<<v48-15-43,43>>^ foi José de Arimateia, membro ilustre do Sinédrio, que também esperava o reino de Deus, apresentou-se corajosamente a Pilatos, e pediu-lhe o corpo de Jesus.

[[v48-15-44]]

^<<v48-15-44,44>>^ Pilatos admirou-se de que estivesse já morto; mandando chamar o centurião, perguntou-lhe se estava já morto.

[[v48-15-45]]

^<<v48-15-45,45>>^ Informado pelo centurião, deu o corpo a José.

[[v48-15-46]]

^<<v48-15-46,46>>^ José, tendo comprado um lençol, e tirando-o da cruz, envolveu-o no lençol, depositou-o num sepulcro, que estava aberto na rocha, e rolou uma pedra para diante da boca do sepulcro.

[[v48-15-47]]

^<<v48-15-47,47>>^ Entretanto Maria Madalena e Maria, mãe de José, estavam observando onde era depositado.

'''

xref:048-sao-marcos/048-sao-marcos-014.adoc#v48-14-0[&#60; Capítulo Anterior] | <<v48-15-0,Topo>> | xref:048-sao-marcos/048-sao-marcos-016.adoc#v48-16-0[Próximo Capítulo &#62;]