include::./index.adoc[]

[[v48-1-0]]
=== São Marcos, 1
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O primeiro capítulo de São Marcos apresenta o início do ministério de Jesus, incluindo seu batismo, tentação no deserto e o chamado dos primeiros discípulos. Além disso, ele também realiza curas e expulsa demônios, mostrando seu poder divino. Seguem abaixo cinco versículos selecionados de outros livros da Bíblia que estão relacionados com os temas abordados em São Marcos 1.
* Isaías 42:1: "Eis aqui o meu servo, a quem sustenho, o meu escolhido, em quem a minha alma se compraz; pus sobre ele o meu Espírito, e ele promulgará o direito aos gentios." Este versículo se refere ao servo de Deus que seria enviado para anunciar a justiça aos gentios, que é identificado pelos cristãos como Jesus. Ele mostra a escolha divina de Jesus como seu servo e o envio do Espírito Santo sobre ele.
* Salmos 2:7: "Proclamarei o decreto do SENHOR: Ele me disse: Tu és meu Filho, eu hoje te gerei." Este salmo é uma referência ao Messias, que é identificado pelos cristãos como Jesus. Ele mostra a filiação divina de Jesus e sua posição como Filho de Deus.
* Isaías 40:3: "Voz do que clama no deserto: Preparai o caminho do SENHOR; endireitai no ermo vereda a nosso Deus." Este versículo se refere ao precursor do Messias, que é identificado pelos cristãos como João Batista. Ele mostra a preparação para a vinda do Messias e a importância da mensagem de João como uma voz que clama no deserto.
* Isaías 53:4-5: "Verdadeiramente ele tomou sobre si as nossas enfermidades, e carregou com as nossas dores; e nós o reputávamos por aflito, ferido de Deus, e oprimido. Mas ele foi ferido por causa das nossas transgressões, e moído por causa das nossas iniquidades; o castigo que nos traz a paz estava sobre ele, e pelas suas pisaduras fomos sarados." Este versículo se refere à morte expiatória de Jesus, que é vista pelos cristãos como um sacrifício pelos pecados da humanidade. Ele mostra o sofrimento que Jesus enfrentou e seu papel como o Cordeiro de Deus que tira o pecado do mundo.
* Isaías 61:1: "O Espírito do SENHOR Deus está sobre mim, porque o SENHOR me ungiu para pregar boas novas aos quebrantados, enviou-me a curar os quebrantados de coração, a proclamar libertação aos cativos, e a pôr em liberdade os algemados." Este versículo se refere ao ministério de Jesus, que é visto pelos cristãos como cumprimento da profecia de Isaías. Ele mostra a missão de Jesus de proclamar a libertação e cura para aqueles que estão sofrendo.
****

[[v48-1-1]]

^<<v48-1-1,1>>^ Princípio do Evangelho de Jesus Cristo, Filho de Deus.

[[v48-1-2]]

^<<v48-1-2,2>>^ Conforme está escrito no profeta Isaías: Eis que envio o meu anjo ante a tua presença, o qual preparará o teu caminho (Ml. 3, 1).

[[v48-1-3]]

^<<v48-1-3,3>>^ Voz do que clama no deserto: Preparai o caminho do Senhor, endireitai as suas veredas (Is. 40, 3).

[[v48-1-4]]

^<<v48-1-4,4>>^ Apareceu João Batista no deserto, pregando o batismo de penitência, para remissão dos pecados.

[[v48-1-5]]

^<<v48-1-5,5>>^ E ia ter com ele toda a região da Judeia e todos os de Jerusalém, e eram baptizados por ele no rio Jordão, confessando os seus pecados.

[[v48-1-6]]

^<<v48-1-6,6>>^ João andava vestido de pêlo de camelo, trazia uma cinta de couro em volta dos rins, alimentava-se de gafanhotos e de mel silvestre. E pregava, dizendo:

[[v48-1-7]]

^<<v48-1-7,7>>^ "Vem após de mim quem é mais forte do que eu, ao qual eu não sou digno de desatar, prostrado em terra, a correia doa sapatos.

[[v48-1-8]]

^<<v48-1-8,8>>^ Eu tenho-vos baptizado em água, ele, porém, baptizar-vos-á no Espírito Santo."

[[v48-1-9]]

^<<v48-1-9,9>>^ Ora aconteceu naqueles dias que Jesus veio de Nazaré da Galileia, e foi baptizado por João no Jordão.

[[v48-1-10]]

^<<v48-1-10,10>>^ No momento de sair da água, viu os céus abertos, e o Espírito Santo que descia sobre ele em forma de pomba;

[[v48-1-11]]

^<<v48-1-11,11>>^ e ouviu-se dos céus uma voz: "Tu és o meu Filho amado, em ti pus as minhas complacências."

[[v48-1-12]]

^<<v48-1-12,12>>^ Imediamente o Espírito o impeliu para o deserto.

[[v48-1-13]]

^<<v48-1-13,13>>^ E permaneceu no deserto quarenta dias, sendo tentado por Satanás. Vivia entre os animais selvagens, e os anjos o serviam.

[[v48-1-14]]

^<<v48-1-14,14>>^ Depois que João foi preso, foi Jesus para a Galileia, pregando o Evangelho de Deus,

[[v48-1-15]]

^<<v48-1-15,15>>^ e dizendo: "Está completo o tempo e aproxima-se o reino de Deus; fazei penitência, crede no Evangelho.

[[v48-1-16]]

^<<v48-1-16,16>>^ Passando ao longo do mar da Galileia, viu Simão e André, seu irmão, que lançavam as redes ao mar, pois eram pescadores.

[[v48-1-17]]

^<<v48-1-17,17>>^ Jesus disse-lhes: "Segui-me, e eu vos farei pescadores de homens."

[[v48-1-18]]

^<<v48-1-18,18>>^ Imediatamente, deixadas as redes, o seguiram.

[[v48-1-19]]

^<<v48-1-19,19>>^ Tendo passado um pouco adiante dali, viu Tiago, filho de Zebedeu, e João, seu irmão, que estavam também numa barca consertando as redes.

[[v48-1-20]]

^<<v48-1-20,20>>^ Chamou-os logo. Eles, tendo deixado na barca seu pai Zebedeu com os jornaleiros, seguiram-no.

[[v48-1-21]]

^<<v48-1-21,21>>^ Depois foram a Cafarnaum; e Jesus tendo entrado no sábado na sinagoga, ensinava.

[[v48-1-22]]

^<<v48-1-22,22>>^ Os ouvintes ficavam admirados com a sua doutrina, porque os ensinava, como quem tem autoridade, e não como os escribas. (ver nota)

[[v48-1-23]]

^<<v48-1-23,23>>^ Na sinagoga estava um homem possesso do espírito imundo, o qual começou a vociferar:

[[v48-1-24]]

^<<v48-1-24,24>>^ "Que tens tu que ver connosco, ó Jesus Nazareno? Vieste para nos perder? Sei quem és, o Santo de Deus."

[[v48-1-25]]

^<<v48-1-25,25>>^ Mas Jesus o ameaçou, dizendo: "Cala-te, e sai desse homem!"

[[v48-1-26]]

^<<v48-1-26,26>>^ Então o espírito imundo, agitando-o violentamente, e dando um grande grito, saiu dele.

[[v48-1-27]]

^<<v48-1-27,27>>^ Ficaram todos tão admirados, que se interrogavam uns aos outros: "Que é isto? Que nova doutrina é esta? Ele manda com autoridade até aos espíritos imundos, e obedecem-lhe."

[[v48-1-28]]

^<<v48-1-28,28>>^ E divulgou-se logo a sua fama por toda a terra da Galileia.

[[v48-1-29]]

^<<v48-1-29,29>>^ Logo que saíram da sinagoga, foram a casa de Simão e de André, com Tiago e João.

[[v48-1-30]]

^<<v48-1-30,30>>^ A sogra de Simão estava de cama com febre. Falaram-lhe logo dela.

[[v48-1-31]]

^<<v48-1-31,31>>^ Jesus, aproximando-se e tomando-a pela mão, levantou-a. Imediatamente a deixou a febre, e ela pôs-se a servi-los.

[[v48-1-32]]

^<<v48-1-32,32>>^ De tarde, sendo já sol-posto, traziam-lhe todos os enfermos e possessos,

[[v48-1-33]]

^<<v48-1-33,33>>^ e toda a cidade se tinha juntado diante da porta.

[[v48-1-34]]

^<<v48-1-34,34>>^ Curou muitos que se achavam oprimidos com várias doenças, expeliu muitos demônios, e não lhes permitia dizer que o conheciam.

[[v48-1-35]]

^<<v48-1-35,35>>^ Levantando-se muito antes de amanhecer, saiu, e foi a um lugar solitário, e lá fazia oração. (ver nota)

[[v48-1-36]]

^<<v48-1-36,36>>^ Simão e os seus companheiros foram procurá-lo.

[[v48-1-37]]

^<<v48-1-37,37>>^ Tendo-o encontrado, disseram-lhe: "Todos te procuram."

[[v48-1-38]]

^<<v48-1-38,38>>^ Ele respondeu: "Vamos para outra parte, para as aldeias vizinhas, a fim de que eu também lá pregue, pois para isso é que vim."

[[v48-1-39]]

^<<v48-1-39,39>>^ E andava pregando nas sinagogas, por toda a Galileia, e expelia os demônios.

[[v48-1-40]]

^<<v48-1-40,40>>^ Foi ter com ele um leproso, fazendo-lhe suas súplicas, e, pondo-se de joelhos, disse-lhe: Se queres, podes limpar-me.

[[v48-1-41]]

^<<v48-1-41,41>>^ Jesus, compadecido dele, estendeu a mão e, tocando-o, disse-lhe: "Quero, sê limpo."

[[v48-1-42]]

^<<v48-1-42,42>>^ Imediatamente desapareceu dele a lepra e ficou limpo.

[[v48-1-43]]

^<<v48-1-43,43>>^ E logo o mandou retirar, dizendo-lhe com tom severo:

[[v48-1-44]]

^<<v48-1-44,44>>^ "Guarda-te de o dizer a alguém, mas vai, mostra-te ao sacerdote, e oferece pela purificação o que Moisés ordenou, para lhes servir de testemunho.

[[v48-1-45]]

^<<v48-1-45,45>>^ Ele, porém, retirando-se começou a contar e a publicar o sucedido, de sorte que Jesus já não podia entrar descobertamente numa cidade, mas ficava fora nos lugares desertos, e de todas as partes iam ter com ele.

'''

xref:047-sao-mateus/047-sao-mateus-028.adoc#v47-28-0[&#60; Capítulo Anterior] | <<v48-1-0,Topo>> | xref:048-sao-marcos/048-sao-marcos-002.adoc#v48-2-0[Próximo Capítulo &#62;]