include::./index.adoc[]

[[v48-9-0]]
=== São Marcos, 9
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 9 de Marcos começa com a transfiguração de Jesus diante de Pedro, Tiago e João. Em seguida, Jesus cura um menino endemoninhado, ensina sobre a importância da humildade e da tolerância, e adverte sobre o perigo do pecado. Abaixo estão cinco versículos relacionados com esses temas:
* Provérbios 16:18 - "A soberba precede a ruína, e a altivez do espírito precede a queda." A lição sobre a importância da humildade em Marcos 9:35-37 é enfatizada neste versículo, que adverte sobre as consequências da arrogância.
* Tiago 4:7 - "Portanto, submetei-vos a Deus. Resisti ao diabo, e ele fugirá de vós." A cura do menino endemoninhado em Marcos 9:14-29 demonstra o poder de Jesus sobre o mal. Tiago 4:7 incentiva os cristãos a resistirem ao diabo e a se aproximarem de Deus.
* Colossenses 3:12 - "Revesti-vos, pois, como eleitos de Deus, santos e amados, de ternos afetos de misericórdia, de bondade, de humildade, de mansidão, de longanimidade." Marcos 9:33-34 descreve uma discussão entre os discípulos sobre quem é o maior entre eles. Colossenses 3:12 ensina que os cristãos devem se revestir de humildade e outras virtudes.
* Romanos 12:18 - "Se possível, quanto depender de vós, tende paz com todos os homens." Em Marcos 9:50, Jesus adverte sobre o perigo do pecado e incentiva seus seguidores a ter paz uns com os outros. Romanos 12:18 encoraja os cristãos a buscar a paz com todos os homens.
* Mateus 5:29-30 - "Se o teu olho direito te faz tropeçar, arranca-o e lança-o longe de ti; pois te é melhor que se perca um dos teus membros do que seja todo o teu corpo lançado no inferno. E, se a tua mão direita te faz tropeçar, corta-a e lança-a longe de ti; pois te é melhor que se perca um dos teus membros do que vá todo o teu corpo para o inferno." Em Marcos 9:42-48, Jesus adverte sobre o perigo do pecado e incentiva seus seguidores a evitar a tentação. Mateus 5:29-30 usa linguagem semelhante para enfatizar a importância de se livrar de tudo o que pode levar à tentação e ao pecado.
****

[[v48-9-1]]

^<<v48-9-1,1>>^ E dizia-lhes: "Em verdade vos digo que, dos que aqui se encontram, alguns não morrerão sem terem visto antes o reino de Deus vir com poder." (ver nota)

[[v48-9-2]]

^<<v48-9-2,2>>^ Seis dias depois, tomou Jesus consigo Pedro, Tiago e João, e conduziu-os sós, aparte, a um alto monte, e transfigurou-se diante deles.

[[v48-9-3]]

^<<v48-9-3,3>>^ Os seus vestidos tornaram-se resplandecentes, em extremo brancos, como nenhum lavandeiro sobre a terra os poderia tornar tão brancos.

[[v48-9-4]]

^<<v48-9-4,4>>^ Depois apareceu-lhes Elias com Moisés, que estavam falando com Jesus.

[[v48-9-5]]

^<<v48-9-5,5>>^ Pedro, tomando a palavra, disse a Jesus: "Mestre, é bom que estejamos aqui: façamos três tendas, uma para ti, outra para Moisés, outra para Elias."

[[v48-9-6]]

^<<v48-9-6,6>>^ Porque não sabia o que dizia, pois estavam atônitos de medo.

[[v48-9-7]]

^<<v48-9-7,7>>^ E formou-se uma nuvem que os cobriu com a sua sombra, e saiu uma voz da nuvem, que dizia: "Este é o meu Filho caríssimo, ouvi-o."

[[v48-9-8]]

^<<v48-9-8,8>>^ Olhando logo em roda, não viram mais ninguém com eles senão Jesus.

[[v48-9-9]]

^<<v48-9-9,9>>^ Ao descerem do monte, ordenou-lhes que a ninguém contassem o que tinham visto, senão quando o Filho do homem tivesse ressuscitado dos mortos.

[[v48-9-10]]

^<<v48-9-10,10>>^ Observaram esta ordem, investigando entre si o que queria dizer: "Quando tiver ressuscitado dos mortos."

[[v48-9-11]]

^<<v48-9-11,11>>^ Interrogaram-no, dizendo: "Porque dizem os escribas que Elias deve vir primeiro?" (ver nota)

[[v48-9-12]]

^<<v48-9-12,12>>^ Jesus respondeu-lhes: "Elias efetivamente há-de vir primeiro e pôr tudo em ordem. Como está escrito acerca do Filho do homem, que terá de sofrer muito e ser desprezado?

[[v48-9-13]]

^<<v48-9-13,13>>^ Mas digo-vos que Elias já veio, e fizeram dele quanto quiseram, como está escrito dele." (ver nota)

[[v48-9-14]]

^<<v48-9-14,14>>^ Chegando junto dos seus discípulos, viu uma grande multidão em volta deles, e os escribas disputando com eles.

[[v48-9-15]]

^<<v48-9-15,15>>^ E logo toda aquela multidão surpreendida ao ver Jesus, correu para o saudar.

[[v48-9-16]]

^<<v48-9-16,16>>^ Perguntou-lhes: "Que estais disputando entre vós?"

[[v48-9-17]]

^<<v48-9-17,17>>^ Um de entre a multidão respondeu-lhe: "Mestre, eu trouxe-te meu filho que está possesso de um espirito mudo,

[[v48-9-18]]

^<<v48-9-18,18>>^ o qual, onde quer que se apodere dele, o lança por terra, e o menino espuma, range com os dentes, e fica entorpecido. Roguei a teus discípulos que o expelissem, e não puderam."

[[v48-9-19]]

^<<v48-9-19,19>>^ Jesus respondeu-lhes: "Ó geração incrédula! Até quando hei-de estar convosco? Até quando vos hei-de suportar? Trazei-mo cá."

[[v48-9-20]]

^<<v48-9-20,20>>^ Levaram-lho. Tendo visto Jesus, imediatamente o espírito o agitou com violência, e, caído por terra, revolvia-se espumando.

[[v48-9-21]]

^<<v48-9-21,21>>^ Jesus perguntou ao pai dele: "Há quanto tempo lhe sucede isto?" Ele respondeu: "Desde a infância.

[[v48-9-22]]

^<<v48-9-22,22>>^ O demônio tem-no lançado muitas vezes no fogo e na água, para o matar; porém tu, se podes alguma coisa, vale-nos, tem compaixão de nós."

[[v48-9-23]]

^<<v48-9-23,23>>^ Jesus disse-lhe: "Se podes... tudo é possível ao que crê." (ver nota)

[[v48-9-24]]

^<<v48-9-24,24>>^ Imediatamente o pai do menino exclamou; "Eu creio! Auxilia a minha falta de fé."

[[v48-9-25]]

^<<v48-9-25,25>>^ Jesus, vendo aumentar a multidão, ameaçou o espírito imundo, dizendo-lhe : "Espírito mudo e surdo, eu te mando; sai desse menino, e não tornes a entrar nele!"

[[v48-9-26]]

^<<v48-9-26,26>>^ Então, dando gritos e agitando-o com violência, saiu dele, e o menino ficou como morto, de sorte que muitos diziam: "Está morto."

[[v48-9-27]]

^<<v48-9-27,27>>^ Porém Jesus, tomando-o pela mão, levantou-o, e ele ergueu-se.

[[v48-9-28]]

^<<v48-9-28,28>>^ Depois que entrou em casa, seus discípulos perguntaram-lhe particularmente: "Porque o não pudemos nós expelir?"

[[v48-9-29]]

^<<v48-9-29,29>>^ Respondeu-lhes: "Esta casta de demônios não se pode expelir, senão mediante a oração e o jejum."

[[v48-9-30]]

^<<v48-9-30,30>>^ Tendo partido dali, atravessaram a Galileia; e Jesus não queria que se soubesse.

[[v48-9-31]]

^<<v48-9-31,31>>^ Ia instruindo os seus discípulos, e dizia-lhes: "O Filho do homem vai ser entregue às mãos dos homens, e lhe darão a morte, e ressuscitará ao terceiro dia, depois da sua morte."

[[v48-9-32]]

^<<v48-9-32,32>>^ Mas eles não compreendiam estas palavras, e temiam interrogá-lo.

[[v48-9-33]]

^<<v48-9-33,33>>^ Nisto chegaram a Cafarnaum. Quando estavam em casa, Jesus perguntou-lhes: "De que vínheis vós discutindo pelo caminho?

[[v48-9-34]]

^<<v48-9-34,34>>^ Eles, porém, calaram-se, porque no caminho tinham discutido entre si qual deles era o maior.

[[v48-9-35]]

^<<v48-9-35,35>>^ Então, sentando-se, chamou os doze, e disse-lhes: "Se alguém quer ser o primeiro, será o último de todos e o servo de todos."

[[v48-9-36]]

^<<v48-9-36,36>>^ Em seguida, tomando um menino, pô-lo no meio deles, e, depois de o abraçar, disse-lhes:

[[v48-9-37]]

^<<v48-9-37,37>>^ "Todo o que receber um destes meninos em meu nome, a mim recebe, e todo o que me receber a mim, não me recebe a mim, mas aquele que me enviou."

[[v48-9-38]]

^<<v48-9-38,38>>^ João disse-lhe: "Mestre, vimos um, que não anda connosco, expelir os demônios em teu nome, e nós lho proibimos, porque não nos segue."

[[v48-9-39]]

^<<v48-9-39,39>>^ Jesus, porém, respondeu : "Não lho proibais, porque não há ninguém que faça um milagre em meu nome e que possa logo dizer mal de mim.

[[v48-9-40]]

^<<v48-9-40,40>>^ Porque quem não é contra nós, está connosco.

[[v48-9-41]]

^<<v48-9-41,41>>^ Quem vos der um copo de água, por que sois de Cristo, em verdade vos digo que não perderá a sua recompensa.

[[v48-9-42]]

^<<v48-9-42,42>>^ Quem escandalizar um destes pequeninos que, creem em mim, melhor lhe fora que lhe atassem à roda do pescoço a mó que um asno faz girar, e que o lançassem ao mar.

[[v48-9-43]]

^<<v48-9-43,43>>^ Se a tua mão é para ti ocasião de queda, corta-a; melhor te é entrar na vida eterna manco, do que, tendo duas mãos, ir para a geena, para o fogo inextinguível,

[[v48-9-44]]

^<<v48-9-44,44>>^ onde o seu verme não morre, e o fogo não se apaga (Is. 66, 24). (ver nota)

[[v48-9-45]]

^<<v48-9-45,45>>^ Se o teu pé é para ti ocasião de queda, corta-o; melhor te é entrar na vida eterna coxo, do que, tendo dois pés, ser lançado na geena,

[[v48-9-46]]

^<<v48-9-46,46>>^ onde o seu verme não morre, e o fogo não se apaga (Is. 66, 24).

[[v48-9-47]]

^<<v48-9-47,47>>^ Se o teu olho é para ti ocasião de queda, lança-o fora; melhor te é entrar no reino de Deus sem um olho, do que, lendo dois, ser lançado na geena,

[[v48-9-48]]

^<<v48-9-48,48>>^ onde o seu verme não morre, e o fogo não se apaga (Is. 66, 24).

[[v48-9-49]]

^<<v48-9-49,49>>^ Todo o homem será salgado pelo fogo. (ver nota)

[[v48-9-50]]

^<<v48-9-50,50>>^ O sal é uma coisa boa, porém, se se tornar insípido, com que haveis de lhe dar o sabor? Tende sal em vós, e tende paz uns com os outros."

'''

xref:048-sao-marcos/048-sao-marcos-008.adoc#v48-8-0[&#60; Capítulo Anterior] | <<v48-9-0,Topo>> | xref:048-sao-marcos/048-sao-marcos-010.adoc#v48-10-0[Próximo Capítulo &#62;]