include::./index.adoc[]

[[v48-14-0]]
=== São Marcos, 14
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* São Marcos 14 narra os eventos que antecedem a crucificação de Jesus, incluindo a conspiração dos líderes religiosos para matá-lo, a unção em Betânia, a última ceia de Jesus com seus discípulos e sua prisão no Getsêmani. Abaixo estão cinco versículos relacionados aos temas abordados nesse capítulo:
* Salmo 41:9 - "Até o meu melhor amigo, em quem eu confiava e que partilhava do meu pão, levantou contra mim o calcanhar." Esse versículo é citado por Jesus na Última Ceia, quando Ele prediz a traição de Judas.
Isaías 53:3 - "Era desprezado e o mais rejeitado entre os homens, homem de dores e experimentado no sofrimento; e, como um de quem os homens escondiam o rosto, era desprezado, e não fizemos dele caso algum." Esse verso é frequentemente citado em relação à crucificação de Jesus e seu sofrimento como o Servo Sofredor.
Salmo 27:12 - "Não me entregues à vontade dos meus adversários, pois testemunhas falsas se levantaram contra mim, e os que respiram crueldade tramam contra mim." Esse verso pode ser aplicado à conspiração dos líderes religiosos contra Jesus e sua prisão.
Isaías 53:5 - "Mas ele foi traspassado por causa das nossas transgressões, foi esmagado por causa das nossas iniquidades; o castigo que nos trouxe a paz estava sobre ele, e pelas suas feridas fomos sarados." Esse verso é outro que é frequentemente associado à crucificação de Jesus e ao motivo pelo qual Ele se entregou à morte.
Salmo 22:16 - "Perfuraram as minhas mãos e os meus pés." Esse verso é mais uma profecia do Antigo Testamento sobre a crucificação de Jesus, que foi perfurado nas mãos e nos pés pelos cravos.
****

[[v48-14-1]]

^<<v48-14-1,1>>^ Dali a dois dias era a Páscoa e os ázimos; os príncipes dos sacerdotes e os escribas andavam buscando modo de o prender por traição, para o matar.

[[v48-14-2]]

^<<v48-14-2,2>>^ Porém, diziam: "Não convém que isto se faça no dia da festa, para que se não levante nenhum motim entre o povo."

[[v48-14-3]]

^<<v48-14-3,3>>^ Estando Jesus em Betânia, em casa de Simão o leproso, enquanto estava à mesa, veio uma mulher trazendo um vaso de alabastro cheio de um bálsamo feito de verdadeiro nardo de um grande valor, e, quebrado o vaso, derramou-lho sobre a cabeça.

[[v48-14-4]]

^<<v48-14-4,4>>^ Alguns dos que estavam presentes indignaram-se, e diziam entre si: "Para que foi este desperdício de bálsamo?

[[v48-14-5]]

^<<v48-14-5,5>>^ Pois podia vender-se por mais de trezentos dinheiros, e dá-los aos pobres. E irritavam-se contra ela.

[[v48-14-6]]

^<<v48-14-6,6>>^ Mas Jesus disse: "Deixai-a. Porque a molestais ? Ela fez-me uma boa obra,

[[v48-14-7]]

^<<v48-14-7,7>>^ porque vós tereis sempre convosco pobres, e, quando quiserdes, podeis fazer-lhes bem; porém, a mim, não me tendes sempre.

[[v48-14-8]]

^<<v48-14-8,8>>^ Ela fez o que podia: embalsamou com antecipação o meu corpo para a sepultura.

[[v48-14-9]]

^<<v48-14-9,9>>^ Em verdade vos digo: Onde quer que for pregado este Evangelho por todo o mundo, será também contado, para sua memória, o que ela fez."

[[v48-14-10]]

^<<v48-14-10,10>>^ Então Judas Iscariotes, um dos doze, foi ter com os príncipes dos sacerdotes, para lhes entregar Jesus.

[[v48-14-11]]

^<<v48-14-11,11>>^ Eles, ouvindo-o, alegraram-se e prometeram dar-lhe dinheiro. E ele procurava ocasião oportuna para o entregar.

[[v48-14-12]]

^<<v48-14-12,12>>^ No primeiro dia dos ázimos, quando imolavam a Páscoa, os discípulos lhe disseram: "Onde queres que vamos preparar-te a refeição da Páscoa?"

[[v48-14-13]]

^<<v48-14-13,13>>^ Então ele enviou dois dos seus discípulos, e disse-lhes: "Ide à cidade, e encontrareis um homem levando uma bilha de água; ide atrás dele,

[[v48-14-14]]

^<<v48-14-14,14>>^ e, onde entrar, dizei ao dono da casa: o Mestre diz: Onde está a minha sala em que eu hei-de comer a Páscoa com os meus discípulos?

[[v48-14-15]]

^<<v48-14-15,15>>^ E ele vos mostrará uma sala superior, grande, mobilada e posta em ordem. Preparai-me lá o que é preciso."

[[v48-14-16]]

^<<v48-14-16,16>>^ Os discípulos partiram, chegaram à cidade, encontraram tudo como ele lhes tinha dito, e prepararam a Páscoa.

[[v48-14-17]]

^<<v48-14-17,17>>^ Chegada a tarde, foi Jesus com os doze.

[[v48-14-18]]

^<<v48-14-18,18>>^ Quando estavam à mesa e comiam, disse Jesus: "Em verdade vos digo que um de vós, que come comigo, me há-de entregar.

[[v48-14-19]]

^<<v48-14-19,19>>^ Então começaram a entristecer-se, e a dizer-lhe cada um de per si: Sou porventura eu?

[[v48-14-20]]

^<<v48-14-20,20>>^ Ele disse-lhes: É um dos doze que se serve comigo no mesmo prato.

[[v48-14-21]]

^<<v48-14-21,21>>^ O Filho do homem vai, segundo está escrito dele, mas, ai daquele homem por quem for entregue o Filho do homem! Melhor fora a esse homem não ter nascido."

[[v48-14-22]]

^<<v48-14-22,22>>^ Enquanto comiam, Jesus tomou pão e, depois de o benzer, partiu-o, deu-lho e disse: "Tomai, isto é o meu corpo."

[[v48-14-23]]

^<<v48-14-23,23>>^ Em seguida, tendo tomado o cálice, dando graças, deu-lho, e todos beberam dele.

[[v48-14-24]]

^<<v48-14-24,24>>^ E disse-lhes : "Isto é o meu sangue, o sangue da Aliança, que será derramado por muitos.

[[v48-14-25]]

^<<v48-14-25,25>>^ Em verdade vos digo que não beberei mais desse fruto da vide, até àquele dia em que o beberei novo no reino de Deus."

[[v48-14-26]]

^<<v48-14-26,26>>^ Cantados os salmos, foram para o monte das Oliveiras,

[[v48-14-27]]

^<<v48-14-27,27>>^ Então, Jesus, disse-lhes: "Todos vos escandalizareis, pois está escrito: Ferirei o pastor, e as ovelhas se dispersarão (Zc. 3, 7).

[[v48-14-28]]

^<<v48-14-28,28>>^ Mas, depois que eu ressuscitar, preceder-vos-ei na Galileia."

[[v48-14-29]]

^<<v48-14-29,29>>^ Pedro, porém, disse-lhe: "Ainda que todos se escandalizem a teu respeito, eu não."

[[v48-14-30]]

^<<v48-14-30,30>>^ Jesus disse-lhe: "Em verdade te digo que hoje, nesta mesma noite, antes que o galo cante a segunda vez, me negarás três vezes."

[[v48-14-31]]

^<<v48-14-31,31>>^ Porém, ele, insistia ainda mais: "Ainda que me seja preciso morrer contigo, não te negarei." E todos diziam o mesmo.

[[v48-14-32]]

^<<v48-14-32,32>>^ Chegando a uma herdade, chamada Getsemani, Jesus disse a seus discípulos: "Sentai-vos aqui enquanto vou orar."

[[v48-14-33]]

^<<v48-14-33,33>>^ Levou consigo Pedro, Tiago e João; e começou a sentir pavor e angústia.

[[v48-14-34]]

^<<v48-14-34,34>>^ E disse-lhes: "A minha alma está numa tristeza mortal; ficai aqui, e vigiai."

[[v48-14-35]]

^<<v48-14-35,35>>^ Tendo-se adiantado um pouco, prostrou-se por terra, e pedia que, se era possível, se afastasse dele aquela hora.

[[v48-14-36]]

^<<v48-14-36,36>>^ Dizia: "Abba, Pai, todas as coisas te são possíveis; afasta de mim este cálice; porém, não se faça o que eu quero, mas o que tu queres." (ver nota)

[[v48-14-37]]

^<<v48-14-37,37>>^ Depois voltou, e encontrou-os dormindo, e disse a Pedro: "Simão, dormes? Não pudeste vigiar uma hora?

[[v48-14-38]]

^<<v48-14-38,38>>^ Vigiai e orai, para que não entreis em tentação. O espirito na verdade está pronto, mas a carne é fraca."

[[v48-14-39]]

^<<v48-14-39,39>>^ Tendo-se retirado novamente, pôs-se a orar, repetindo as mesmas palavras.

[[v48-14-40]]

^<<v48-14-40,40>>^ Voltando, encontrou-os outra vez a dormir, porque tinham os olhos pesados. Não sabiam que responder-lhe.

[[v48-14-41]]

^<<v48-14-41,41>>^ Voltou terceira vez, e disse-lhes: "Dormi agora e descansai. Basta, é chegada a hora; eis que o Filho do homem vai ser entregue nas mãos dos pecadores.

[[v48-14-42]]

^<<v48-14-42,42>>^ Levantai-vos, vamos; eis que se aproxima o que me há-de entregar."

[[v48-14-43]]

^<<v48-14-43,43>>^ Ainda falava, quando chega Judas Iscariotes, um dos doze, e com ele muita gente armada de espadas e varapaus, enviada pelos príncipes dos sacerdotes, pelos escribas e pelos anciães.

[[v48-14-44]]

^<<v48-14-44,44>>^ O traidor tinha-lhes dado uma senha, dizendo: "Aquele a quem eu oscular, é esse; prendei-o, e levai-o com cuidado."

[[v48-14-45]]

^<<v48-14-45,45>>^ Logo que chegou, aproximando-se imediatamente de Jesus, disse-lhe: "Mestre!" e osculou-o.

[[v48-14-46]]

^<<v48-14-46,46>>^ Então eles lançaram-lhe as mãos, e prenderam-no.

[[v48-14-47]]

^<<v48-14-47,47>>^ Um dos circunstantes, tirando da espada, feriu um servo do sumo sacerdote, e cortou-lhe uma orelha.

[[v48-14-48]]

^<<v48-14-48,48>>^ Jesus, tomando a palavra, disse-lhes: "Como se eu fosse um ladrão, viestes com espadas e varapaus a prender-me?

[[v48-14-49]]

^<<v48-14-49,49>>^ Todos os dias estava entre vós ensinando no templo, e não me prendestes. Mas isto acontece para que se cumpram as Escrituras."

[[v48-14-50]]

^<<v48-14-50,50>>^ Então os seus discípulos, abandonando-o, fugiram todos.

[[v48-14-51]]

^<<v48-14-51,51>>^ Um jovem seguia Jesus coberto sòmente com um lençol, e prenderam-no.

[[v48-14-52]]

^<<v48-14-52,52>>^ Mas ele, largando o lençol, escapou-se-lhes nu.

[[v48-14-53]]

^<<v48-14-53,53>>^ Levaram Jesus ao sumo sacerdote, e juntaram-se todos os príncipes dos sacerdotes, os anciães e os escribas,

[[v48-14-54]]

^<<v48-14-54,54>>^ Pedro foi-o seguindo de longe, até dentro do pátio do sumo sacerdote. Estava sentado ao fogo com os criados, e aquecia-se.

[[v48-14-55]]

^<<v48-14-55,55>>^ Os príncipes dos sacerdotes e todo o conselho buscavam algum testemunho contra Jesus, para o fazerem morrer, e não o encontravam,

[[v48-14-56]]

^<<v48-14-56,56>>^ Porque muitos depunham falsamente contra ele, mas não concordavam os seus depoimentos.

[[v48-14-57]]

^<<v48-14-57,57>>^ Levantando-se uns certos, depunham falsamente contra ele, dizendo:

[[v48-14-58]]

^<<v48-14-58,58>>^ "Nós ouvimos-lhe dizer: Destruirei este templo, feito pela mão do homem, e em três dias edificarei outro, que não será feito pela mão do homem."

[[v48-14-59]]

^<<v48-14-59,59>>^ Porém nem este seu testemunho era concorde.

[[v48-14-60]]

^<<v48-14-60,60>>^ Então, levantando-se no meio da assembleia o sumo sacerdote, interrogou Jesus, dizendo: "Não respondes nada? O que é que estes depõem contra ti?"

[[v48-14-61]]

^<<v48-14-61,61>>^ Ele, porém, estava em silêncio, e nada respondeu. Interrogou-o de novo o sumo sacerdote, e disse-lhe: "És tu o Cristo, o Filho de Deus bendito?"

[[v48-14-62]]

^<<v48-14-62,62>>^ Jesus respondeu: "Eu o sou, e vereis o Filho do homem sentado á direita do poder de Deus, e vir sobre as nuvens do céu (Ps. 109, 1 ; Dn. 7, 13)."

[[v48-14-63]]

^<<v48-14-63,63>>^ Então o sumo sacerdote, rasgando os seus vestidos, disse: "Que necessidade temos de mais testemunhas?

[[v48-14-64]]

^<<v48-14-64,64>>^ Ouvistes a blasfêmia. Que vos parece?" E todos o condenaram como réu de morte.

[[v48-14-65]]

^<<v48-14-65,65>>^ Então começaram alguns a cuspir-lhe, a velar-lhe o rosto, e a dar-lhe punhadas, dizendo-lhe: "Profetiza!" Os criados receberam-no a bofetadas.

[[v48-14-66]]

^<<v48-14-66,66>>^ Entretanto, estando Pedro em baixo no átrio, chegou uma das criadas do sumo sacerdote.

[[v48-14-67]]

^<<v48-14-67,67>>^ Vendo Pedro, que se aquecia, encarando nele, disse: "Tu também estavas com Jesus Nazareno."

[[v48-14-68]]

^<<v48-14-68,68>>^ Mas ele negou: "Não sei, nem compreendo o que dizes." E saiu fora para a entrada do pátio, e o galo cantou.

[[v48-14-69]]

^<<v48-14-69,69>>^ Tendo-o visto a criada, começou novamente a dizer aos que estavam presentes: "Este é daqueles."

[[v48-14-70]]

^<<v48-14-70,70>>^ Mas ele o negou de novo. Pouco depois, os que ali estavam diziam de novo a Pedro: "Verdadeiramente tu és um deles, porque és galileu."

[[v48-14-71]]

^<<v48-14-71,71>>^ Ele começou a fazer imprecações e a jurar: "Não conheço esse homem de quem falais."

[[v48-14-72]]

^<<v48-14-72,72>>^ Imediatamente cantou o galo segunda vez. Pedro recordou-se da palavra que Jesus tinha dito: "Antes que o galo cante duas vezes, me negarás três vezes." E começou a chorar.

'''

xref:048-sao-marcos/048-sao-marcos-013.adoc#v48-13-0[&#60; Capítulo Anterior] | <<v48-14-0,Topo>> | xref:048-sao-marcos/048-sao-marcos-015.adoc#v48-15-0[Próximo Capítulo &#62;]