include::./index.adoc[]

[[v48-5-0]]
=== São Marcos, 5
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Em Marcos 5, Jesus realiza vários milagres impressionantes, incluindo a cura de um homem possuído por demônios, a cura de uma mulher com hemorragia e a ressurreição da filha de um líder da sinagoga. Os temas centrais deste capítulo incluem a autoridade de Jesus sobre as forças espirituais malignas, a fé e a cura. Abaixo estão cinco versículos relacionados com esses temas:
* Lucas 10:19: "Eis que vos dei autoridade para pisar serpentes e escorpiões e sobre todo o poder do inimigo; e nada vos fará mal algum."
Este versículo fala sobre a autoridade que Jesus deu aos seus seguidores sobre as forças espirituais malignas, reforçando a autoridade demonstrada por Jesus em Marcos 5.
* Tiago 5:14-15: "Está alguém entre vós doente? Chame os presbíteros da igreja, e orem sobre ele, ungindo-o com azeite em nome do Senhor; e a oração da fé salvará o doente, e o Senhor o levantará; e se houver cometido pecados, ser-lhe-ão perdoados." Este versículo fala sobre a cura através da oração da fé, um tema importante em Marcos 5.
* João 5:8-9: "Jesus lhe disse: Levanta-te, toma o teu leito e anda. E logo o homem ficou são, e tomou o seu leito, e andava." Este versículo descreve a cura instantânea realizada por Jesus, semelhante às curas milagrosas que ele realiza em Marcos 5.
* Isaías 53:5: "Mas ele foi ferido pelas nossas transgressões, e moído pelas nossas iniquidades; o castigo que nos traz a paz estava sobre ele, e pelas suas pisaduras fomos sarados." Este versículo profético fala sobre a cura que Jesus traria através do seu sacrifício na cruz, uma cura que é vista em pequena escala em Marcos 5.
* Efésios 2:8-9: "Porque pela graça sois salvos, mediante a fé; e isto não vem de vós, é dom de Deus; não vem das obras, para que ninguém se glorie." Este versículo fala sobre a importância da fé na salvação, um tema que está presente em Marcos 5 e é demonstrado na fé da mulher com hemorragia e do líder da sinagoga que pede a Jesus para curar sua filha.
****

[[v48-5-1]]

^<<v48-5-1,1>>^ Chegaram à outra banda do mar, ao território dos gerasenos.

[[v48-5-2]]

^<<v48-5-2,2>>^ Ao sair Jesus da barca, foi logo ter com ele, saindo dos sepulcros, um homem possesso de um espírito imundo.

[[v48-5-3]]

^<<v48-5-3,3>>^ Tinha o seu domicílio nos sepulcros, e nem com cadeias o podia alguém ter preso.

[[v48-5-4]]

^<<v48-5-4,4>>^ Tendo sido atado por muitas vezes com grilhões e com cadeias, tinha quebrado as cadeias e despedaçado os grilhões, e ninguém o podia domar.

[[v48-5-5]]

^<<v48-5-5,5>>^ E sempre, dia e noite, andava pelos sepulcros e pelos montes, gritando e ferindo-se com pedras.

[[v48-5-6]]

^<<v48-5-6,6>>^ Vendo, porém, a Jesus de longe, correu e prostrou-se diante dele,

[[v48-5-7]]

^<<v48-5-7,7>>^ e clamou em alta voz: "Que tens tu comigo, Jesus, Filho de Deus Altíssimo? Eu te conjuro por Deus que me não atormentes."

[[v48-5-8]]

^<<v48-5-8,8>>^ Porque Jesus dizia-lhe : "Espírito imundo sai desse homem."

[[v48-5-9]]

^<<v48-5-9,9>>^ Depois perguntou-lhe: "Que nome é o teu?" Ele respondeu: "O meu nome é Legião, porque somos muitos."

[[v48-5-10]]

^<<v48-5-10,10>>^ E suplicava-lhe instantemente que o não expulsasse daquele pais.

[[v48-5-11]]

^<<v48-5-11,11>>^ Andava ali pastando ao redor do monte uma grande vara de porcos.

[[v48-5-12]]

^<<v48-5-12,12>>^ Os espíritos imundos suplicaram-lhe : "Manda-nos para os porcos, para nos metermos neles."

[[v48-5-13]]

^<<v48-5-13,13>>^ Jesus deu-lhes essa permissão. Então os espíritos imundos saíram e entraram nos porcos, e a vara, que era de cerca de dois mil, precipitou-se por um despinhadeiro no mar, onde se afogaram.

[[v48-5-14]]

^<<v48-5-14,14>>^ Os que andavam apascentando fugiram e foram espalhar a noticia pela cidade e pelos campos. E o povo foi ver o que tinha sucedido.

[[v48-5-15]]

^<<v48-5-15,15>>^ Foram ter com Jesus, e viram o que tinha sido vexado do demônio sentado, vestido e são do juízo, ele, que tinha estado possesso de uma legião inteira; e tiveram medo.

[[v48-5-16]]

^<<v48-5-16,16>>^ Os que tinham visto contaram-lhes o que tinha acontecido ao endemoninhado e aos porcos.

[[v48-5-17]]

^<<v48-5-17,17>>^ Então começaram a rogar a Jesus que se retirasse do território deles.

[[v48-5-18]]

^<<v48-5-18,18>>^ Quando Jesus subia para a barca, começou o que fora vexado do demônio a pedir-lhe que lhe permitisse acompanhá-lo.

[[v48-5-19]]

^<<v48-5-19,19>>^ Mas Jesus não o permitiu, antes lhe disse: "Vai para tua casa, para os teus, e anuncia-lhes quão grandes coisas o Senhor te fez, e como teve piedade de ti."

[[v48-5-20]]

^<<v48-5-20,20>>^ Ele retirou-se e começou a publicar pela Decápole quão grandes coisas lhe linha feito Jesus; e todos se admiravam.

[[v48-5-21]]

^<<v48-5-21,21>>^ Tendo passado Jesus novamente para a outra banda na barca, concorreu a ele muita gente, e ele estava junto do mar.

[[v48-5-22]]

^<<v48-5-22,22>>^ Chegou um dos chefes da sinagoga, chamado Jairo, o qual, vendo-o, lançou-se a seus pés,

[[v48-5-23]]

^<<v48-5-23,23>>^ e suplicava-lhe com instância: "Minha filha está nas últimas; vem, impõe sobre ela a mão, para que seja salva, e viva."

[[v48-5-24]]

^<<v48-5-24,24>>^ Jesus foi com ele, e uma grande multidão o seguia e o apertava.

[[v48-5-25]]

^<<v48-5-25,25>>^ Então uma mulher, que há doze anos padecia um fluxo de sangue,

[[v48-5-26]]

^<<v48-5-26,26>>^ que tinha sofrido muito de muitos médicos, e tinha gastado tudo quanto possuía, sem ter sentido melhoras, antes cada vez se achava pior,

[[v48-5-27]]

^<<v48-5-27,27>>^ tendo ouvido falar de Jesus, foi por detrás, entre a turba, e tocou o seu vestido.

[[v48-5-28]]

^<<v48-5-28,28>>^ Porque dizia: "Se eu tocar, ainda que seja só o seu vestido, ficarei curada."

[[v48-5-29]]

^<<v48-5-29,29>>^ Imediatamente parou o fluxo de sangue, e sentiu no seu corpo estar curada do mal.

[[v48-5-30]]

^<<v48-5-30,30>>^ Jesus, conhecendo logo em si mesmo a virtude que saíra dele, voltado para a multidão, disse: "Quem tocou os meus vestidos?"

[[v48-5-31]]

^<<v48-5-31,31>>^ Os seus discípulos responderam: "Tu vês que a multidão te comprime, e perguntas: Quem me tocou?"

[[v48-5-32]]

^<<v48-5-32,32>>^ E Jesus olhava em roda para ver a que tinha feito isto.

[[v48-5-33]]

^<<v48-5-33,33>>^ Então a mulher, que sabia o que se tinha passado nela, cheia de medo, e tremendo, foi prostrar-se diante dele, e disse-lhe toda a verdade.

[[v48-5-34]]

^<<v48-5-34,34>>^ Jesus disse-lhe: "Filha, a tua fé te salvou; vai em paz, e fica curada do teu mal."

[[v48-5-35]]

^<<v48-5-35,35>>^ Ainda ele falava, quando chegaram de casa do chefe da sinagoga, dizendo: "Tua filha morreu; para que incomodar mais o Mestre?"

[[v48-5-36]]

^<<v48-5-36,36>>^ Porém, Jesus, tendo ouvido o que eles diziam, disse ao príncipe da sinagoga: "Não temas; crê sòmente."

[[v48-5-37]]

^<<v48-5-37,37>>^ E não permitiu que ninguém o acompanhasse, senão Pedro, Tiago e João, irmão de Tiago.

[[v48-5-38]]

^<<v48-5-38,38>>^ Chegando a casa do príncipe da sinagoga, viu Jesus o alvoroço, os que estavam chorando e fazendo grandes prantos.

[[v48-5-39]]

^<<v48-5-39,39>>^ Tendo entrado, disse-lhes: "Por que vos perturbais e chorais? A menina não está morta, mas dorme."

[[v48-5-40]]

^<<v48-5-40,40>>^ E zombavam dele. Mas ele, tendo feito sair todos, tomou o pai e a mãe da menina, e os que o acompanhavam, e entrou onde a menina estava deitada.

[[v48-5-41]]

^<<v48-5-41,41>>^ Tomando a mão da menina, disse-Ihe : "Talitha koum, que quer dizer: Menina, eu te mando, levanta-te."

[[v48-5-42]]

^<<v48-5-42,42>>^ Imediatamente se levantou a menina, e andava; pois tinha já doze anos. Ficaram cheios de grande espanto.

[[v48-5-43]]

^<<v48-5-43,43>>^ Jesus ordenou-lhes rigorosamente que ninguém o soubesse. Depois disse que dessem de comer à menina.

'''

xref:048-sao-marcos/048-sao-marcos-004.adoc#v48-4-0[&#60; Capítulo Anterior] | <<v48-5-0,Topo>> | xref:048-sao-marcos/048-sao-marcos-006.adoc#v48-6-0[Próximo Capítulo &#62;]