include::./index.adoc[]

[[v56-3-0]]
=== Efésios, 3
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Efésios 3 trata da revelação do mistério de Deus em relação à salvação dos gentios, que antes eram considerados excluídos. O apóstolo Paulo enfatiza a importância da graça de Deus nessa revelação e a necessidade de pregá-la a todos. Além disso, ele destaca a importância da oração e do amor de Cristo, que ultrapassa todo o entendimento. A seguir estão cinco versículos relacionados com esses temas:
* Atos 22:21: "Mas ele me disse: Vai, porque eu te enviarei aos gentios de longe." Esse versículo mostra a intenção de Deus de incluir os gentios na salvação, que é o mistério revelado em Efésios 3.
* Romanos 16:25-27: "Ora, àquele que é poderoso para vos confirmar segundo o meu evangelho e a pregação de Jesus Cristo, conforme a revelação do mistério que desde tempos eternos esteve oculto, mas que se manifestou agora e se tornou manifesto pela Escrituras dos profetas, segundo o mandamento do Deus eterno, a todas as nações para obediência da fé." Esse versículo fala sobre a revelação do mistério que antes estava oculto e agora é manifesto, assim como em Efésios 3.
* Colossenses 4:2-3: "Perseverai na oração, velando nela com ações de graças; orai também por nós, para que Deus nos abra porta à palavra, a fim de falarmos do mistério de Cristo, pelo qual também estou preso." Esse versículo destaca a importância da oração, assim como em Efésios 3, e também a necessidade de pregar o mistério de Cristo.
* João 13:34: "Um novo mandamento vos dou: que vos ameis uns aos outros; assim como eu vos amei, que também vos ameis uns aos outros." Esse versículo destaca o amor de Cristo, que ultrapassa todo o entendimento, assim como em Efésios 3.
* 1 João 4:11-12: "Amados, se Deus assim nos amou, também nós devemos amar uns aos outros. Ninguém jamais viu a Deus; se nos amarmos uns aos outros, Deus está em nós, e em nós é perfeito o seu amor." Esse versículo fala sobre a importância do amor, que é um tema presente em Efésios 3, e também destaca a presença de Deus em nós quando amamos uns aos outros.
****

[[v56-3-1]]

^<<v56-3-1,1>>^ Por esta causa, eu, Paulo, prisioneiro de Jesus Cristo por amor de vós gentios... (ver nota)

[[v56-3-2]]

^<<v56-3-2,2>>^ se é que tivestes conhecimento da concessão da graça de Deus, que me foi dada para vós:

[[v56-3-3]]

^<<v56-3-3,3>>^ pela revelação me foi manifestado este mistério, como acabo de expor em poucas palavras. (ver nota)

[[v56-3-4]]

^<<v56-3-4,4>>^ Podeis, lendo-as, conhecer a inteligência que tenho do mistério de Cristo,

[[v56-3-5]]

^<<v56-3-5,5>>^ o qual não foi conhecido nas outras gerações pelos filhos dos homens, como agora foi revelado aos seus santos apóstolos e profetas pelo Espírito,

[[v56-3-6]]

^<<v56-3-6,6>>^ (isto é, que) os gentios são co-herdeiros (com os Judeus), membros do mesmo corpo e participantes da mesma promessa em Jesus Cristo, mediante o Evangelho,

[[v56-3-7]]

^<<v56-3-7,7>>^ do qual fui feito ministro, segundo o dom da graça de Deus, que me foi comunicada segundo a eficácia do seu poder.

[[v56-3-8]]

^<<v56-3-8,8>>^ A mim, o mínimo de todos os santos, me foi dada esta graça de anunciar entre os gentios as riquezas incompreensíveis de Cristo

[[v56-3-9]]

^<<v56-3-9,9>>^ e de manifestar o plano deste mistério escondido, desde o principio dos séculos, em Deus, que tudo criou,

[[v56-3-10]]

^<<v56-3-10,10>>^ para que a multiforme sabedoria de Deus seja manifestada por meio da Igreja aos principados e potestades nos céus,

[[v56-3-11]]

^<<v56-3-11,11>>^ conforme a determinação eterna que ele realizou em Jesus Cristo Nosso Senhor,

[[v56-3-12]]

^<<v56-3-12,12>>^ no qual temos segurança e acesso a Deus com confiança, por meio da fé nele.

[[v56-3-13]]

^<<v56-3-13,13>>^ Pelo que vos rogo que não desanimeis por causa das tribulações que sofro por vós: elas são a vossa glória. (ver nota)

[[v56-3-14]]

^<<v56-3-14,14>>^ Por esta causa dobro os joelhos diante do Pai,

[[v56-3-15]]

^<<v56-3-15,15>>^ do qual toda a paternidade nos céus e na terra toma o nome,

[[v56-3-16]]

^<<v56-3-16,16>>^ para que, segundo a riqueza da sua glória, faça crescer em vós o homem interior, pelo seu Espírito,

[[v56-3-17]]

^<<v56-3-17,17>>^ e que Cristo habite pela fé nos vossos corações, de sorte que, arraigados e fundados na caridade,

[[v56-3-18]]

^<<v56-3-18,18>>^ possais compreender, com todos os santos, qual a largura, o comprimento, a altura e a profundidade (do amor de Cristo para com os homens),

[[v56-3-19]]

^<<v56-3-19,19>>^ e conhecer também aquele amor de Cristo, que excede toda a ciência, de maneira que fiqueis cheios de toda a plenitude (dos dons) de Deus.

[[v56-3-20]]

^<<v56-3-20,20>>^ Àquele que é poderoso para fazer todas as coisas mais abundantemente do que pedimos ou entendemos, segundo a virtude que opera em nós,

[[v56-3-21]]

^<<v56-3-21,21>>^ a esse (seja dada) glória na Igreja e em Jesus Cristo, por todas as gerações e por todos os séculos. Assim seja.

'''

xref:056-efesios/056-efesios-002.adoc#v56-2-0[&#60; Capítulo Anterior] | <<v56-3-0,Topo>> | xref:056-efesios/056-efesios-004.adoc#v56-4-0[Próximo Capítulo &#62;]