include::./index.adoc[]

[[v56-5-0]]
=== Efésios, 5
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 5 de Efésios trata sobre a conduta cristã em relação ao amor, pureza e submissão. Paulo enfatiza a importância de seguir o exemplo de Cristo e ser cheios do Espírito Santo, evitando a imoralidade sexual, as palavras corrompidas e as atitudes impuras. Além disso, ele instrui sobre o papel do marido e da esposa no casamento e exorta os cristãos a viverem em harmonia e unidade como membros do corpo de Cristo. A seguir, são apresentados cinco versículos de outros livros da Bíblia que se relacionam com os temas abordados em Efésios 5.
* Provérbios 10:19: "No muito falar não falta transgressão, mas o que modera os lábios é prudente." Este versículo enfatiza a importância da moderação nas palavras, algo que Paulo também aborda em Efésios 5:4. Ele alerta os cristãos para que não falem palavras corrompidas, obscenas ou tolas, mas sim para que falem aquilo que é bom e edificante para os outros.
* Colossenses 3:18: "Vós, mulheres, sujeitai-vos a vossos maridos, como convém no Senhor." Assim como em Efésios 5, Paulo instrui as mulheres a se submeterem a seus maridos de forma amorosa e voluntária. Ele ressalta que esta submissão é uma forma de honrar a Cristo e contribuir para a unidade no casamento.
* 1 Pedro 3:7: "Igualmente vós, maridos, coabitai com elas com entendimento, dando honra à mulher, como vaso mais fraco; como sendo vós os seus coerdeiros da graça da vida; para que não sejam impedidas as vossas orações." Pedro também instrui os maridos a serem amorosos e respeitosos com suas esposas, algo que Paulo aborda em Efésios 5:25-33.
* 1 Tessalonicenses 5:23: "E o mesmo Deus de paz vos santifique em tudo; e todo o vosso espírito, e alma, e corpo sejam plenamente conservados irrepreensíveis para a vinda de nosso Senhor Jesus Cristo." Este versículo destaca a importância da santificação e da pureza, temas que Paulo também enfatiza em Efésios 5:3-14.
* Romanos 12:5: "Assim nós, que somos muitos, somos um só corpo em Cristo, mas individualmente somos membros uns dos outros." Paulo exorta os cristãos em Efésios 5:21 a se sujeitarem uns aos outros no temor de Cristo, reconhecendo que todos são membros do mesmo corpo. Este versículo em Romanos 12 também enfatiza a unidade do corpo de Cristo, que é composto de muitos membros diferentes.
****

[[v56-5-1]]

^<<v56-5-1,1>>^ Sede, pois, imitadores de Deus, como filhos muito amados.

[[v56-5-2]]

^<<v56-5-2,2>>^ Andai no amor, a exemplo de Cristo, que nos amou e se entregou a si mesmo por nós a Deus, como oferenda e sacrifício de suave odor.

[[v56-5-3]]

^<<v56-5-3,3>>^ Nem sequer se nomeie entre vós a fornicação ou qualquer impureza ou avareza, como convém a santos;

[[v56-5-4]]

^<<v56-5-4,4>>^ nem conversas torpes, nem loucas, nem chocarrices, que são coisas inconvenientes, mas antes (saiam da vossa boca) ações de graças (a Deus).

[[v56-5-5]]

^<<v56-5-5,5>>^ Com efeito, sabei-o bem, nenhum fornicador ou impudico ou avaro, o qual é um idólatra (do dinheiro), terá herança no reino de Cristo e de Deus.

[[v56-5-6]]

^<<v56-5-6,6>>^ Ninguém vos seduza com palavras vãs, porque por estas desordens vem a ira de Deus sobre os filhos rebeldes.

[[v56-5-7]]

^<<v56-5-7,7>>^ Não queirais, pois, ter comunicação com eles.

[[v56-5-8]]

^<<v56-5-8,8>>^ Outrora éreis trevas, mas agora sois luz no Senhor. Andai como filhos da luz,

[[v56-5-9]]

^<<v56-5-9,9>>^ porque o fruto da luz consiste em toda a espécie de bondade, de justiça e de verdade.

[[v56-5-10]]

^<<v56-5-10,10>>^ Examinando o que é agradável a Deus,

[[v56-5-11]]

^<<v56-5-11,11>>^ não tomeis parte nas obras infrutuosas (dos filhos) das trevas, mas antes condenai-as.

[[v56-5-12]]

^<<v56-5-12,12>>^ Porque as coisas que eles fazem em secreto, vergonha é até dizê-las.

[[v56-5-13]]

^<<v56-5-13,13>>^ Mas todas as coisas condenadas são postas a descoberto pela luz, e tudo o que é manifestado torna-se luz.

[[v56-5-14]]

^<<v56-5-14,14>>^ Por isso (a Escritura) diz: Desperta, tu que dormes (no sono do pecado); levanta-te dentre os mortos, e Cristo te alumiará (com a sua graça) (Is. 26, 19).

[[v56-5-15]]

^<<v56-5-15,15>>^ Cuidai, pois, Irmãos, em andar com prudência, não como insensatos,

[[v56-5-16]]

^<<v56-5-16,16>>^ mas como circunspectos. Aproveitai o tempo, pois que os dias são maus. (ver nota)

[[v56-5-17]]

^<<v56-5-17,17>>^ Portanto não sejais imprudentes, mas considerai qual a vontade do Senhor.

[[v56-5-18]]

^<<v56-5-18,18>>^ Não vos embriagueis com vinho, no qual está a luxúria, mas enchei-vos do Espírito Santo,

[[v56-5-19]]

^<<v56-5-19,19>>^ recitando entre vós salmos, hinos e canções espirituais, cantando e salmodiando ao Senhor com todo o vosso coração,

[[v56-5-20]]

^<<v56-5-20,20>>^ dando sempre graças a Deus e Pai, por tudo, em nome de Nosso Senhor Jesus Cristo.

[[v56-5-21]]

^<<v56-5-21,21>>^ Sede submissos uns aos outros no temor de Cristo.

[[v56-5-22]]

^<<v56-5-22,22>>^ As mulheres sejam sujeitas a seus maridos, como ao Senhor,

[[v56-5-23]]

^<<v56-5-23,23>>^ porque o marido é cabeça da mulher, como Cristo é cabeça da Igreja, seu corpo, do qual ele é o Salvador.

[[v56-5-24]]

^<<v56-5-24,24>>^ Assim como a Igreja está sujeita a Cristo, assim o estejam também as mulheres a seus maridos em tudo (o que não é contra a lei de Deus).

[[v56-5-25]]

^<<v56-5-25,25>>^ Maridos, amai as vossas mulheres, como também Cristo amou a Igreja e por ela se entregou a si mesmo,

[[v56-5-26]]

^<<v56-5-26,26>>^ para a santificar, purificando-a no batismo da água pela palavra,

[[v56-5-27]]

^<<v56-5-27,27>>^ para apresentar a si mesmo esta Igreja gloriosa, sem mácula, nem ruga ou coisa semelhante, mas santa e imaculada.

[[v56-5-28]]

^<<v56-5-28,28>>^ Do mesmo modo os maridos devem amar as suas mulheres, como ao seu próprio corpo. O que ama a sua mulher, ama-se a si mesmo.

[[v56-5-29]]

^<<v56-5-29,29>>^ Com efeito, ninguém aborreceu jamais a sua própria carne, mas nutre-a e cuida dela, como também Cristo o faz à Igreja,

[[v56-5-30]]

^<<v56-5-30,30>>^ porque somos membros do seu corpo (místico).

[[v56-5-31]]

^<<v56-5-31,31>>^ Por isso deixará o homem seu pai e sua mãe e se unirá a sua mulher; e serão dois numa só carne (Gn. 2, 24). (ver nota)

[[v56-5-32]]

^<<v56-5-32,32>>^ Grande mistério é este; eu o entendo em relação a Cristo e à Igreja.

[[v56-5-33]]

^<<v56-5-33,33>>^ Por isso também cada um de vós (a exemplo de Cristo, que ama a sua Igreja) ame a sua mulher como a si mesmo, e a mulher respeite a seu marido.

'''

xref:056-efesios/056-efesios-004.adoc#v56-4-0[&#60; Capítulo Anterior] | <<v56-5-0,Topo>> | xref:056-efesios/056-efesios-006.adoc#v56-6-0[Próximo Capítulo &#62;]