include::./index.adoc[]

[[v63-1-0]]
=== Tito, 1
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Tito 1 aborda as qualidades necessárias para os líderes da igreja, incluindo bispos e presbíteros. Paulo enfatiza a importância de ter líderes que sejam irrepreensíveis em seu comportamento e ensino, e que sejam capazes de refutar aqueles que ensinam falsas doutrinas. Além disso, ele destaca a necessidade de líderes que sejam bons administradores e que saibam liderar suas famílias. Aqui estão cinco versículos relacionados com os temas abordados em Tito 1:
* 1 Timóteo 3:2: "É necessário, pois, que o bispo seja irrepreensível, marido de uma só mulher, sóbrio, prudente, honesto, hospitaleiro e apto para ensinar." Este versículo se concentra nas qualidades necessárias para ser um bispo, que incluem ser irrepreensível, ter um bom comportamento e ser capaz de ensinar.
* 1 Pedro 5:2: "Apascentai o rebanho de Deus que está entre vós, não por constrangimento, mas espontaneamente, como Deus quer; nem por sórdida ganância, mas de boa vontade." Este versículo destaca a importância de liderar o rebanho de Deus de forma voluntária e com boas intenções, em vez de ser motivado pela ganância.
* 1 Timóteo 3:4-5: "Ele deve governar bem a própria casa, tendo seus filhos em sujeição, com todo o respeito, pois, se alguém não sabe governar a própria casa, como cuidará da igreja de Deus?" Esse versículo enfatiza a importância de um líder ter habilidades de liderança em sua própria família antes de liderar a igreja.
* Tito 2:7: "Em tudo te dá por exemplo de boas obras; na doutrina mostra integridade, sobriedade." Este versículo fala sobre a importância de ter integridade e sobriedade na doutrina, bem como dar um bom exemplo através de boas obras.
* 2 Timóteo 2:15: "Procura apresentar-te a Deus aprovado, como obreiro que não tem de que se envergonhar, que maneja bem a palavra da verdade." Este versículo destaca a importância de manejar bem a palavra da verdade e ser aprovado por Deus como um obreiro sem vergonha.
****

[[v63-1-1]]

^<<v63-1-1,1>>^ Paulo, servo de Deus e apóstolo de Jesus Cristo, segundo a fé dos escolhidos de Deus e o conhecimento da verdade, que é segundo a piedade,

[[v63-1-2]]

^<<v63-1-2,2>>^ na esperança da vida eterna, que Deus, que não mente, prometeu antes do começo dos séculos,

[[v63-1-3]]

^<<v63-1-3,3>>^ e manifestou a seu tempo a sua palavra por meio da pregação que me foi confiada, por ordem de Deus nosso Salvador,

[[v63-1-4]]

^<<v63-1-4,4>>^ a Tito, meu verdadeiro filho segundo a fé que nos é comum, graça e paz da parte de Deus Pai e de Jesus Cristo, nosso Salvador.

[[v63-1-5]]

^<<v63-1-5,5>>^ Deixei-te em Creta para que regules o que falta e estabeleças presbíteros nas cidades, segundo as prescrições que te dei.

[[v63-1-6]]

^<<v63-1-6,6>>^ (É necessário que o presbítero) seja irrepreensível, casado uma só vez, que tenha filhos fiéis, que não possam ser acusados de dissolução e que não sejam desobedientes. (ver nota)

[[v63-1-7]]

^<<v63-1-7,7>>^ Porque é preciso que o bispo seja sem crime, como despenseiro de Deus; que não seja soberbo, nem iracundo, nem dado ao vinho, nem violento, nem ávido de sórdidos lucros, (ver nota)

[[v63-1-8]]

^<<v63-1-8,8>>^ mas hospitaleiro, amigo do bem, ponderado, justo, santo, continente,

[[v63-1-9]]

^<<v63-1-9,9>>^ que dê ensino seguro, conforme a doutrina, para que possa exortar segundo a sã doutrina e refutar os que a contradizem.

[[v63-1-10]]

^<<v63-1-10,10>>^ Porque há ainda muitos desobedientes, vãos faladores e sedutores, principalmente entre os da circuncisão, (ver nota)

[[v63-1-11]]

^<<v63-1-11,11>>^ aos quais é necessário fechar a boca, a eles que transtornam casas inteiras, ensinando o que não convém, por amor de um vil interesse.

[[v63-1-12]]

^<<v63-1-12,12>>^ Um deles, seu próprio profeta disse: Os Cretenses são sempre mentirosos, más bestas, ventres preguiçosos. (ver nota)

[[v63-1-13]]

^<<v63-1-13,13>>^ Este testemunho é verdadeiro. Portanto repreende-os asperamente, para que sejam sãos na fé,

[[v63-1-14]]

^<<v63-1-14,14>>^ não dêem ouvidos a fábulas judaicas nem a mandamentos de homens que se afastam da verdade.

[[v63-1-15]]

^<<v63-1-15,15>>^ Para os puros todas as coisas são puras; para os impuros e infiéis nada é puro, mas estão contaminados o seu espírito e sua consciência.

[[v63-1-16]]

^<<v63-1-16,16>>^ Confessam que conhecem a Deus, mas negam-no com as obras, sendo abomináveis, rebeldes e incapazes de toda a obra boa.

'''

xref:062-ii-timoteo/062-ii-timoteo-004.adoc#v62-4-0[&#60; Capítulo Anterior] | <<v63-1-0,Topo>> | xref:063-tito/063-tito-002.adoc#v63-2-0[Próximo Capítulo &#62;]