include::./index.adoc[]

[[v23-6-0]]
=== II Macabeus, 6
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 6 de 2 Macabeus relata a perseguição dos judeus pelo rei Antíoco Epifânio, que proibiu a prática do judaísmo e exigiu que os judeus adorassem os deuses gregos. Além disso, muitos judeus foram torturados e mortos por se recusarem a obedecer às ordens do rei. Abaixo estão cinco versículos relacionados a esse tema:
* 2 Macabeus 6:9: "Quem quer que não se submetesse à ordem do rei seria condenado à morte." Esse versículo mostra a crueldade do rei Antíoco Epifânio, que ameaçou matar aqueles que não seguissem suas ordens.
* 2 Macabeus 6:12: "Aconteceu que alguns homens, perto do lago, que se recusaram a se contaminar, foram presos e levados ao rei." Esse versículo ilustra a coragem daqueles que preferiram morrer a desobedecer às leis de Deus.
* 2 Macabeus 6:18: "Ele ordenou que suas línguas fossem arrancadas, que fossem rasgados seus couros cabeludos, e que lhes cortassem as pontas dos dedos." Esse versículo descreve a tortura cruel que os judeus sofreram por causa de sua fé.
* 2 Macabeus 6:30: "Estando prestes a morrer sob os golpes, ele suspirou profundamente e disse: 'O Senhor, em virtude da sua santa ciência, sabe perfeitamente que, embora eu pudesse escapar à morte, estou sendo submetido a dores cruéis em meu corpo, sob o açoite dos carrascos, mas em minha alma, alegro-me com a esperança que tenho de que o Senhor me ressuscite um dia'." Esse versículo mostra a fé e a coragem daqueles que morreram em nome de sua religião.
* 2 Macabeus 6:31: "Depois dessas palavras, ele se entregou à morte com toda a alma, deixando em seu martírio um modelo de coragem e aguardando do Senhor a reconciliação com seus irmãos." Esse versículo enfatiza a importância da coragem e da fé em momentos difíceis e a confiança em Deus mesmo diante da morte.
****

[[v23-6-1]]

^<<v23-6-1,1>>^ Pouco tempo depois, mandou o rei um certo velho ateniense para forçar os Judeus a deixarem as leis de Deus e as de seus pais,

[[v23-6-2]]

^<<v23-6-2,2>>^ para profanar o templo de Jerusalém e dedicá-lo a Júpiter Olímpico, e consagrar o templo de Garizim a Júpiter Hospitaleiro, conforme o carácter dos habitantes daquele lugar.

[[v23-6-3]]

^<<v23-6-3,3>>^ Era pernicioso e grave para todos este crescimento de males,

[[v23-6-4]]

^<<v23-6-4,4>>^ porque o templo estava cheio de lascívias e de festins dos Gentios, que se divertiam com prostitutas e tinham comércio com mulheres aos santos átrios, e levaram lá para dentro o que não era permitido.

[[v23-6-5]]

^<<v23-6-5,5>>^ O altar também estava cheio de vítimas impuras, proibidas pelas leis.

[[v23-6-6]]

^<<v23-6-6,6>>^ Não se podia guardar os sábados nem celebrar já as festas antigas, e ninguém se atrevia a confessar que era Judeu.

[[v23-6-7]]

^<<v23-6-7,7>>^ Eram levados à viva força aos sacrifícios mensais (profanos) no dia dos anos do rei; e quando se celebrava a festa de Baco, obrigavam-nos a ir pelas ruas, coroados de hera, em honra do mesmo Baco.

[[v23-6-8]]

^<<v23-6-8,8>>^ Também, por sugestão dos habitantes de Ptolemaida, foi publicado um édito em todas as cidades gregas vizinhas (da Judeia), pelo qual deviam proceder do mesmo modo contra os Judeus, constrangendo-os a sacrificarem,

[[v23-6-9]]

^<<v23-6-9,9>>^ ou matando os que não quisessem abraçar os costumes helénicos. Em toda a parte se viam aflições.

[[v23-6-10]]

^<<v23-6-10,10>>^ Assim duas mulheres, acusadas de ter circuncidado seus filhos, foram levadas publicamente por toda a cidade, com os filhos pendurados aos peitos, e depois precipitadas do alto das muralhas.

[[v23-6-11]]

^<<v23-6-11,11>>^ Outros, que se juntaram nas cavernas vizinhas e celebraram ali secretamente o dia de sábado, foram denunciados a Filipe e queimados, porque tiveram escrúpulo de se defender pelo respeito à santidade desse dia.

[[v23-6-12]]

^<<v23-6-12,12>>^ Eu conjuro, porém, os que lerem este livro, a que se não deixem abater por tais calamidades, antes considerem que todos estes males, que sucederam, não foram para ruína, mas para castigo da nossa raça.

[[v23-6-13]]

^<<v23-6-13,13>>^ Por que é sinal de grande misericórdia de Deus para com os pecadores, não deixar por muito tempo impunes, mas aplicar-lhes prontamente o castigo.

[[v23-6-14]]

^<<v23-6-14,14>>^ Com efeito o Senhor suporta as outras nações com paciência, para as castigar na plenitude de seus pecados. Conosco não procede assim,

[[v23-6-15]]

^<<v23-6-15,15>>^ para evitar aquela punição que seria aplicada quando chegassem ao cúmulo os nossos pecados.

[[v23-6-16]]

^<<v23-6-16,16>>^ Portanto ele nunca retira de nós a sua misericórdia, e, quando castiga o seu povo com adversidades, não o desampara.

[[v23-6-17]]

^<<v23-6-17,17>>^ Ditas em poucas palavras estas coisas, a modo de lembrança, voltemos ao fio da narração.

[[v23-6-18]]

^<<v23-6-18,18>>^ A Eleázar, um dos primeiros doutores da lei, varão provecto na idade e de venerável presença, depois de lhe abrirem a boca à força queriam obrigar a comer carne de porco.

[[v23-6-19]]

^<<v23-6-19,19>>^ Mas ele, preferindo uma morte gloriosa a uma vida infame, voluntariamente caminhava para o suplício, depois de ter lançado fora da boca (a carne),

[[v23-6-20]]

^<<v23-6-20,20>>^ procedendo como devem os que possuem coragem para repelir o que o amor da vida não desculpa de comer.

[[v23-6-21]]

^<<v23-6-21,21>>^ Os que presidiam a este ímpio banquete sacrifical, por causa da antigo amizade que tinham com ele, tomando-o à parte, rogavam-lhe que trouxesse e preparasse ele próprio as carnes que lhe era lícito comer, para assim poder fingir que tinha comido das carnes do sacrifício, como o rei havia mandado.

[[v23-6-22]]

^<<v23-6-22,22>>^ Tudo, a fim de que, por tal modo, fosse salvo da morte; usavam com Eleázar desta espécie de humanidade, por causa da antiga amizade que lhe professavam.

[[v23-6-23]]

^<<v23-6-23,23>>^ Ele, porém, fazendo altas considerações, dignas da sua idade, do respeito devido à sua velhice, do prestígio das suas cãs, dos irrepreensíveis costumes em que sempre vivera desde menino, e, sobretudo, das ordenações da lei santa estabelecida por Deus, respondeu que o fizessem baixar imediatamente à sepultura.

[[v23-6-24]]

^<<v23-6-24,24>>^ Realmente não é digno da nossa idade, lhes dizia ele, usar de fingimento; daí poderia resultar que muitos jovens, julgando que Eleázar, aos noventa anos, passara para a vida dos pagãos,

[[v23-6-25]]

^<<v23-6-25,25>>^ viessem também eles, por causa deste meu fingimento para conservar um pequeno resto duma vida efémera, a cair em erro, o que atrairia a vergonha e a execração sobre a minha velhice.

[[v23-6-26]]

^<<v23-6-26,26>>^ Ainda que eu me livrasse presentemente dos suplícios dos homens, não poderia todavia fugir à mão do Todo-Poderoso, nem na vida, nem depois da morte.

[[v23-6-27]]

^<<v23-6-27,27>>^ Pelo que, morrendo valorosamente, mostrar-me-ei digno da velhice em que estou

[[v23-6-28]]

^<<v23-6-28,28>>^ e deixarei aos jovens um nobre exemplo de fortaleza, para sofrer, com ânimo pronto e valoroso, a morte em defesa das veneráveis e santas leis. Logo que acabou de proferir, estas palavras, caminhou para o suplício.

[[v23-6-29]]

^<<v23-6-29,29>>^ Aqueles que o levavam, e que pouco antes tinham sido brandos, enfureceram-se por causa das palavras que Eleázar acabara de dizer, as quais Julgaram desatinadas.

[[v23-6-30]]

^<<v23-6-30,30>>^ Quando estava para morrer pela veemência dos golpes, deu um grande suspiro e disse: O Senhor, que tem a ciência santa, bem sabe que, podendo eu livrar-me da morte, sofro em meu corpo, sob os açoites, acerbas dores; mas na alma sinto alegria em as padecer pelo temor que lhe tenho.

[[v23-6-31]]

^<<v23-6-31,31>>^ Assim acabou a vida, deixando, com a sua morte, não somente aos jovens mas também a toda a sua nação, um exemplo de valor e memória de virtude.

'''

xref:023-ii-macabeus/023-ii-macabeus-005.adoc#v23-5-0[&#60; Capítulo Anterior] | <<v23-6-0,Topo>> | xref:023-ii-macabeus/023-ii-macabeus-007.adoc#v23-7-0[Próximo Capítulo &#62;]