include::./index.adoc[]

[[v2-35-0]]
=== Êxodo, 35
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 35 do livro de Êxodo trata da contribuição voluntária do povo para a construção do tabernáculo e dos objetos sagrados que seriam utilizados nos rituais religiosos. Os versículos relacionados com os temas abordados neste capítulo são:
* 1 Crônicas 29:9 - "E o povo se alegrou com estas ofertas voluntárias, pois as fizeram de coração sincero para o SENHOR. E Davi, o rei, também se alegrou grandemente." Este versículo mostra a alegria do povo em contribuir voluntariamente para a obra do SENHOR, assim como aconteceu na construção do tabernáculo.
* 2 Coríntios 9:7 - "Cada um dê conforme propôs no seu coração, não com tristeza ou por necessidade; porque Deus ama ao que dá com alegria." Paulo instrui os coríntios a contribuírem voluntariamente para a obra de Deus, sem tristeza ou pressão, mas com alegria no coração.
* Provérbios 3:9-10 - "Honra ao SENHOR com os teus bens e com as primícias de toda a tua renda; e se encherão fartamente os teus celeiros, e transbordarão de vinho os teus lagares." Este versículo destaca a importância de honrar ao SENHOR com as nossas posses, e promete que aqueles que o fazem serão abençoados abundantemente.
* 1 Timóteo 6:17-19 - "Manda aos ricos deste mundo que não sejam altivos, nem depositem a sua esperança na incerteza das riquezas, mas em Deus, que nos concede abundantemente todas as coisas para delas gozarmos; que pratiquem o bem, sejam ricos de boas obras, generosos em dar e prontos a repartir; que acumulem para si mesmos tesouros que sirvam de alicerce para o futuro, a fim de se apoderarem da verdadeira vida." Paulo ensina que aqueles que são ricos devem ser generosos em dar e repartir, acumulando tesouros para si mesmos no céu.
* 2 Coríntios 8:1-5 - "Irmãos, fazemos-vos conhecer a graça de Deus concedida às igrejas da Macedônia; pois, no meio de muita prova de tribulação, manifestaram abundância de alegria, e a profunda pobreza deles superabundou em grande riqueza da sua generosidade; porque, dou testemunho, segundo as suas posses e mesmo acima delas, espontaneamente deram, pedindo-nos, com muito encarecimento, o privilégio de participarem deste serviço em favor dos santos. E não somente fizeram como nós esperávamos, mas a si mesmos se deram primeiro ao Senhor, e depois a nós, pela vontade de Deus." Este versículo relata a generosidade dos irmãos da Macedônia, que, mesmo em meio à pobreza e tribulação, contribuíram voluntariamente para a obra do SENHOR.
****

[[v2-35-1]]

^<<v2-35-1,1>>^ Moisés, congregada toda a multidão dos filhos de Israel, disse-lhes: Estas são as coisas que o Senhor mandou que se fizessem:

[[v2-35-2]]

^<<v2-35-2,2>>^ Trabalhareis seis dias: o dia sétimo será para vós santo, Será um dia de repouso completo (em honra) do Senhor; o que nele trabalhar, será morto.

[[v2-35-3]]

^<<v2-35-3,3>>^ Não acendereis lume em todas as vossas moradas no dia de sábado.

[[v2-35-4]]

^<<v2-35-4,4>>^ Moisés disse mais a toda a multidão dos filhos de Israel: Eis o que o Senhor ordenou:

[[v2-35-5]]

^<<v2-35-5,5>>^ Ponde à parte junto de vós primícias para o Senhor. Cada um, voluntária e espontaneamente, ofereça ao Senhor ouro, prata e cobre,

[[v2-35-6]]

^<<v2-35-6,6>>^ púrpura violácea, púrpura escarlate e carmesim e linho fino, pêlos de cabra,

[[v2-35-7]]

^<<v2-35-7,7>>^ peles de carneiro tintas de vermelho, peles roxas, e madeira de acácia,

[[v2-35-8]]

^<<v2-35-8,8>>^ azeite para acender as lâmpadas e para fazer o bálsamo e os perfumes de suave fragrância,

[[v2-35-9]]

^<<v2-35-9,9>>^ pedras de ônix, e (outras) pedras preciosas para ornato do éfode e do peitoral.

[[v2-35-10]]

^<<v2-35-10,10>>^ Qualquer de vós que tenha habilidade, venha e faça o que o Senhor mandou,

[[v2-35-11]]

^<<v2-35-11,11>>^ isto é, o tabernáculo, com a sua tenda e a sua cobertura, as argolas, e as tábuas, e os barrotes, e as escápulas, e as bases;

[[v2-35-12]]

^<<v2-35-12,12>>^ a arca e os varais, o propiciatório e o véu, que deve pender diante dele;

[[v2-35-13]]

^<<v2-35-13,13>>^ a mesa com os varais e com os (seus) utensílios, e os pães da proposição;

[[v2-35-14]]

^<<v2-35-14,14>>^ o candeeiro para sustentar as lâmpadas, os seus utensílios, e as lâmpadas, e o azeite para manter as luzes;

[[v2-35-15]]

^<<v2-35-15,15>>^ o altar dos perfumes, e os varais, e o óleo da unção, e o perfume aromático; o véu para a entrada do tabernáculo;

[[v2-35-16]]

^<<v2-35-16,16>>^ o altar dos holocaustos e a sua grelha de bronze com os seus varais e seus utensílios; a bacia e a sua base:

[[v2-35-17]]

^<<v2-35-17,17>>^ as cortinas do átrio com as colunas e as bases, o véu à entrada do átrio,

[[v2-35-18]]

^<<v2-35-18,18>>^ as escápulas do tabernáculo e do átrio com os seus cordões;

[[v2-35-19]]

^<<v2-35-19,19>>^ as vestes de que se usa no ministério do santuário, as vestes do pontífice Aarão e de seus filhos, para que exerçam as funções do meu sacerdócio.

[[v2-35-20]]

^<<v2-35-20,20>>^ Saindo toda a multidão dos filhos de Israel da presença de Moisés,

[[v2-35-21]]

^<<v2-35-21,21>>^ ofereceram ao Senhor com uma vontade pronta e cheia de afecto as primícias para fazer a obra do tabernáculo da reunião e para tudo aquilo que era necessário para o culto e vestes sagradas.

[[v2-35-22]]

^<<v2-35-22,22>>^ Vieram, tanto os homens como as mulheres, e todos aqueles, cujo coração estava bem disposto, trouxeram braceletes, arecadas, aneis, colares: todos trouxeram as suas ofertas de ouro destinadas ao Senhor.

[[v2-35-23]]

^<<v2-35-23,23>>^ Se alguém tinha jacinto, e púrpura, e escarlate tinto duas vezes, linho fino e pelos de cabra, peles de carneiros tintas de vermelho ou de roxo,

[[v2-35-24]]

^<<v2-35-24,24>>^ metais de prata e cobre, ofereceram-nos ao Senhor, e também madeira de acácia para os diversos usos.

[[v2-35-25]]

^<<v2-35-25,25>>^ Além disto, as mulheres habilidosas deram do que tinham fiado de jacinto, púrpura, escarlate e linho fino,

[[v2-35-26]]

^<<v2-35-26,26>>^ e pêlos de cabra, dando tudo de espontânea vontade.

[[v2-35-27]]

^<<v2-35-27,27>>^ Os príncipes, porém, ofereceram pedras de ônix e (outras) pedras preciosas para o éfode e o peitoral,

[[v2-35-28]]

^<<v2-35-28,28>>^ aromas e azeite para manter as luzes, preparar o bálsamo e compor o perfume de suavíssimo cheiro.

[[v2-35-29]]

^<<v2-35-29,29>>^ Todos os homens e mulheres ofereceram os seus dons com coração devoto, para se fazerem as obras que o Senhor tinha mandado por meio de Moisés. Todos os filhos de Israel dedicaram ao Senhor ofertas voluntárias.

[[v2-35-30]]

^<<v2-35-30,30>>^ Moisés disse aos filhos de Israel: Eis que o Senhor chamou por seu nome a Beseleel, filho de Uri, filho de Hur, da tribo de Judá,

[[v2-35-31]]

^<<v2-35-31,31>>^ e o encheu do espírito de Deus, de sabedoria, de inteligência e saber,

[[v2-35-32]]

^<<v2-35-32,32>>^ para inventar e executar trabalhos de ouro, prata e cobre,

[[v2-35-33]]

^<<v2-35-33,33>>^ para lavrar pedras, para trabalhos de carpintaria e para todas as espécies de trabalhos artísticos.

[[v2-35-34]]

^<<v2-35-34,34>>^ Concedeu-lhe também o dom de ensinar, assim como a Ooliab, filho de Aquisamech, da tribo de Dan.

[[v2-35-35]]

^<<v2-35-35,35>>^ A ambos comunicou habilidade para fazerem trabalhos de carpinteiro, de tecelão em várias cores, e bordados de purpura violácea, escarlate e carmesim, e de linho fino, e para fazerem toda a espécie de tecidos, e inventarem novidades de toda a sorte.

'''

xref:002-exodo/002-exodo-034.adoc#v2-34-0[&#60; Capítulo Anterior] | <<v2-35-0,Topo>> | xref:002-exodo/002-exodo-036.adoc#v2-36-0[Próximo Capítulo &#62;]