include::./index.adoc[]

[[v2-38-0]]
=== Êxodo, 38
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Êxodo 38 detalha a construção do altar do holocausto e da bacia para as ofertas no pátio do Tabernáculo. Também apresenta um registro das ofertas que foram feitas para a construção do Tabernáculo. Os versículos a seguir estão relacionados com os temas abordados em Êxodo 38:
* Números 4:13-14: "E tirarão as cinzas do altar, e estenderão sobre ele um pano de púrpura; e lhe porão todos os seus utensílios com que se serve, os braseiros, os garfos, as pás, as bacias; todos os utensílios do altar; e sobre ele estenderão uma coberta de peles de texugos, e porão suas varas" Este versículo fala sobre a limpeza do altar do holocausto, que foi construído no pátio do Tabernáculo.
* Êxodo 30:18-19: "Farás também uma pia de cobre, com sua base também de cobre, para lavar; e pô-la-ás entre a tenda da congregação e o altar, e nela porás água. E Arão e seus filhos nela lavarão as suas mãos e os seus pés" Este versículo se refere à construção da bacia para as ofertas no pátio do Tabernáculo, mencionada em Êxodo 38.
* Êxodo 25:1-2: "Disse mais o SENHOR a Moisés: Fala aos filhos de Israel que me tragam uma oferta alçada; de todo homem cujo coração se mover voluntariamente, dele tomareis a minha oferta alçada" Este versículo fala sobre as ofertas que foram coletadas para a construção do Tabernáculo, o qual é detalhado em Êxodo 38.
* Êxodo 38:8: "Fez também a bacia de cobre, com sua base de cobre, dos espelhos das mulheres que se reuniam à porta da tenda da congregação" Este versículo se refere à construção da bacia para as ofertas no pátio do Tabernáculo.
* Êxodo 38:24-25: "Todo o ouro empregado na obra, em toda a obra do santuário, o ouro das ofertas alçadas, foi vinte e nove talentos e setecentos e trinta siclos, segundo o siclo do santuário" Este versículo apresenta um registro das ofertas que foram feitas para a construção do Tabernáculo, que é descrito em detalhes em Êxodo 38.
****

[[v2-38-1]]

^<<v2-38-1,1>>^ Fez de pau de acácia o altar dos holocaustos, que tinha cinco covados em comprimento e em largura, e três de alto,

[[v2-38-2]]

^<<v2-38-2,2>>^ de cujos ângulos saíam as pontas, e cobriu-o com lâminas de bronze.

[[v2-38-3]]

^<<v2-38-3,3>>^ Para o seu serviço preparou diversos utensílios de bronze, caldeiras, tenazes, garfos, ganchos e braseiros.

[[v2-38-4]]

^<<v2-38-4,4>>^ E fez a sua grelha de bronze em forma de rode, que colocou em baixo, sob o rebordo do altar, a meia altura dele,

[[v2-38-5]]

^<<v2-38-5,5>>^ tendo vazado quatro argolas para pôr nos quatro cantos da grelha, a fim de por elas fazer passar os varais para o transporte;

[[v2-38-6]]

^<<v2-38-6,6>>^ fez esses mesmos varais de pau de acácia, cobriu-os com lâminas de bronze,

[[v2-38-7]]

^<<v2-38-7,7>>^ e meteu-os nas argolas, que sobressaíam dos lados do altar. O altar, porém, não era maciço, mas (feito) de tábuas, oco por dentro.

[[v2-38-8]]

^<<v2-38-8,8>>^ Fez também a bacia de bronze e a sua base com os espelhos das mulheres, que velavam à porta do tabernáculo. (ver nota)

[[v2-38-9]]

^<<v2-38-9,9>>^ Fez mais o átrio, a cujo lado meridional estavam cortinas de linho fino retorcido, com o comprimento de cem côvados.

[[v2-38-10]]

^<<v2-38-10,10>>^ Havia vinte colunas de bronze com suas bases; os capitéis das colunas e todos os ornatos da obra eram de prata.

[[v2-38-11]]

^<<v2-38-11,11>>^ Do mesmo modo do lado setentrional as cortinas, as colunas, as bases e os capitéis das colunas eram da mesma medida, lavor e metal.

[[v2-38-12]]

^<<v2-38-12,12>>^ Mas, do lado que olha para o ocidente, havia cortinas de cinqüenta côvados, e dez colunas de bronze com suas bases; os capitéis das colunas e todos os ornatos da obra eram de prata.

[[v2-38-13]]

^<<v2-38-13,13>>^ Pelo lado do oriente dispôs cortinas de cinqüenta côvados;

[[v2-38-14]]

^<<v2-38-14,14>>^ delas deu quinze côvados de cortina e três colunas com suas bases a um lado,

[[v2-38-15]]

^<<v2-38-15,15>>^ e ao outro lado (porque entre um e outro fez a entrada do tabernáculo) deu igualmente quinze côvados de cortina e três colunas com outras tantas bases.

[[v2-38-16]]

^<<v2-38-16,16>>^ Todas as cortinas do átrio eram tecidas de linho fino retorcido.

[[v2-38-17]]

^<<v2-38-17,17>>^ As bases das colunas eram de bronze, e os seus capitéis, com todos os seus ornatos, de prata; as mesmas colunas do átrio revestiu-as também de prata.

[[v2-38-18]]

^<<v2-38-18,18>>^ À entrada do átrio, fez uma cortina com trabalho de bordados de jacinto, de púrpura, de escarlate e de linho fino retorcido, que tinha vinte côvados de comprimento, e cinco côvados de altura, segundo a medida que tinham as cortinas do átrio.

[[v2-38-19]]

^<<v2-38-19,19>>^ Havia, pois, à entrada quatro colunas com bases de bronze, e seus capitéis e ornatos de prata.

[[v2-38-20]]

^<<v2-38-20,20>>^ Fez de bronze as escápulas do tabernáculo e do átrio em redor.

[[v2-38-21]]

^<<v2-38-21,21>>^ Estas são as partes em redor do tabernáculo do testemunho que foram enumeradas segundo a ordem de Moisés por trabalho dos Levitas sob a direcção de Itamar, filho do Sacerdote Aarão,

[[v2-38-22]]

^<<v2-38-22,22>>^ e que foram completadas por Beseleel, filho de Uri, filho de Hur, da tribo de Judá, segundo a ordem que o Senhor tinha dado por meio de Moisés,

[[v2-38-23]]

^<<v2-38-23,23>>^ tendo servido a Beseleel de ajudante Ooliab, filho de Àquisamech, da tribo de Dan, o qual foi artista hábil em obras de madeira, em tecidos de várias cores, e em bordados de púrpura violácea e escarlate e carmesim, e de linho fino.

[[v2-38-24]]

^<<v2-38-24,24>>^ Todo o ouro que foi empregado na obra do santuário, produto de ofertas, foi de vinte e nove talentos, e setecentos e trinta siclos segundo a medida do santuário.

[[v2-38-25]]

^<<v2-38-25,25>>^ Estas ofertas foram feitas pelos que entraram no recenseamento, de vinte anos para cima, isto e, por seiscentos e trés mil quinhentos e cinqüenta homens de armas.

[[v2-38-26]]

^<<v2-38-26,26>>^ Recolheram-se, além disto, cem talentos de prata de que foram feitas as bases (das colunas) do santuário, e a entrada onde estava suspenso o véu.

[[v2-38-27]]

^<<v2-38-27,27>>^ Foram feitas cem bases de cem talentos, contando-se um talento por cada base.

[[v2-38-28]]

^<<v2-38-28,28>>^ Com mil e setecentos e setenta e cinco (siclos) fez os capitéis das colunas, as quais também revestiu de prata.

[[v2-38-29]]

^<<v2-38-29,29>>^ Foram também oferecidos setenta talentos, e dois mil e quatrocentos siclos de bronze,

[[v2-38-30]]

^<<v2-38-30,30>>^ com que foram fundidas as bases (das colunas) para a entrada do tabernáculo da reunião e o altar de bronze com a sua grelha, todos os instrumentos pertencentes ao seu uso,

[[v2-38-31]]

^<<v2-38-31,31>>^ as bases do átrio, tanto as do redor dele, como as da entrada, e as escápulas do tabernáculo e do átrio em redor.

'''

xref:002-exodo/002-exodo-037.adoc#v2-37-0[&#60; Capítulo Anterior] | <<v2-38-0,Topo>> | xref:002-exodo/002-exodo-039.adoc#v2-39-0[Próximo Capítulo &#62;]