include::./index.adoc[]

[[v2-26-0]]
=== Êxodo, 26
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 26 de Êxodo descreve as especificações para a construção do tabernáculo. Ele deve ser feito com cortinas de linho fino, com querubins de tecido azul, vermelho e púrpura bordados nelas. As cortinas devem ser suspensas por colunas de madeira de acácia revestidas de ouro e fixadas com ganchos e barras. A seguir estão cinco versículos relacionados com temas abordados em Êxodo 26:
* Hebreus 9:11: "Mas vindo Cristo, o sumo sacerdote dos bens futuros, por um maior e mais perfeito tabernáculo, não feito por mãos, isto é, não desta criação," Este versículo se relaciona com Êxodo 26, pois fala sobre o tabernáculo celestial, que é superior ao tabernáculo terreno construído de acordo com as especificações detalhadas no capítulo 26.
* 1 Coríntios 6:19: "Ou não sabeis que o nosso corpo é o templo do Espírito Santo, que habita em vós, proveniente de Deus, e que não sois de vós mesmos?" Esse versículo se relaciona com Êxodo 26, pois o tabernáculo terreno era um símbolo do lugar onde Deus habitava com o seu povo, assim como o Espírito Santo habita nos cristãos.
* João 1:14: "E o Verbo se fez carne, e habitou entre nós, e vimos a sua glória, como a glória do unigênito do Pai, cheio de graça e de verdade." Esse versículo se relaciona com Êxodo 26, pois o tabernáculo terreno era o lugar onde Deus habitava com o seu povo, assim como Jesus, que é a encarnação de Deus, habitou entre os homens.
* 1 Pedro 2:5: "Vós também, como pedras vivas, sois edificados casa espiritual e sacerdócio santo, para oferecer sacrifícios espirituais agradáveis a Deus por Jesus Cristo." Esse versículo se relaciona com Êxodo 26, pois o tabernáculo terreno era o lugar onde o povo oferecia sacrifícios a Deus, assim como os cristãos oferecem sacrifícios espirituais em suas próprias vidas como parte do sacerdócio santo.
* Apocalipse 21:3: "E ouvi uma grande voz do céu, que dizia: Eis aqui o tabernáculo de Deus com os homens, pois com eles habitará, e eles serão o seu povo, e o mesmo Deus estará com eles, e será o seu Deus." Esse versículo se relaciona com Êxodo 26, pois o tabernáculo terreno era um símbolo do lugar onde Deus habitava com o seu povo, assim como o tabernáculo celestial descrito em Apocalipse será o lugar onde Deus habitará com os seus escolhidos.
****

[[v2-26-1]]

^<<v2-26-1,1>>^ O tabernáculo, fá-lo-ás assim: Farás dez cortinas de linho fino retorcido, de púrpura violácea, de púrpura escarlate e carmesim, sobre as quais serão artisticamente bordados querubins.

[[v2-26-2]]

^<<v2-26-2,2>>^ O comprimento duma cortina será de vinte e oito côvados: a largura será de quatro côvados. Todas as cortinas se farão da mesma medida.

[[v2-26-3]]

^<<v2-26-3,3>>^ Cinco cortinas serão unidas entre si, e outras cinco serão unidas do mesmo modo entre si.

[[v2-26-4]]

^<<v2-26-4,4>>^ Farás umas presilhas de púrpura violácea nos lados e extremidades das cortinas, para que se possam unir umas às outras.

[[v2-26-5]]

^<<v2-26-5,5>>^ Cada cortina terá cinquenta presilhas de cada lado, de tal sorte (dispostas) que uma presilha fique em frente da outra, e possa uma ligar-se com a outra.

[[v2-26-6]]

^<<v2-26-6,6>>^ Farás também cinco argolas de ouro, com as quais se devem juntar os panos das cortinas, para que se forme um só tabernáculo.

[[v2-26-7]]

^<<v2-26-7,7>>^ Farás mais onze cobertas de pêlo de cabras, para cobrir a parte superior do tabernáculo.

[[v2-26-8]]

^<<v2-26-8,8>>^ O comprimento duma coberta será de trinta côvados, e a largura de quatro; será igual a medida de todas as cobertas.

[[v2-26-9]]

^<<v2-26-9,9>>^ Juntarás cinco delas à parte, e unirás entre si as outras seis, de sorte que possas dobrar a sexta por diante do tabernáculo.

[[v2-26-10]]

^<<v2-26-10,10>>^ Farás também cinquenta presilhas na ourela duma coberta, para que possa ligar-se com outra: e cinqüenta presilhas na ourela desta, para que se una com a que lhe corresponde.

[[v2-26-11]]

^<<v2-26-11,11>>^ Farás também cinquenta fivelas de bronze, por meio das quais se unam as presilhas, para que de todas se faça uma só coberta.

[[v2-26-12]]

^<<v2-26-12,12>>^ O que sobejar das cobertas destinadas a cobrir o tabernáculo, que vem a ser uma coberta que há de mais, com metade desta cobrirás a parte de trás do tabernáculo.

[[v2-26-13]]

^<<v2-26-13,13>>^ Ficará pendente um côvado duma parte, e outro doutra, o que sobeja no comprimento das cobertas, para cobrir os dois lados de tabernáculo.

[[v2-26-14]]

^<<v2-26-14,14>>^ Farás mais uma outra coberta para o tabernáculo, de peles de carneiros tintas de vermelho; sobre esta, porás uma outra coberta de peles de cor roxa.

[[v2-26-15]]

^<<v2-26-15,15>>^ Farás também de pau de acácia as tábuas do tabernáculo, que hão-de estar levantadas.

[[v2-26-16]]

^<<v2-26-16,16>>^ Cada uma delas terá dez côvados de comprimento, e côvado e meio de largura.

[[v2-26-17]]

^<<v2-26-17,17>>^ Nos lados de cada tábua far-se-ão dois encaixes, com que cada tábua se una com a outra; deste modo se aparelharão todas as tábuas,

[[v2-26-18]]

^<<v2-26-18,18>>^ vinte das quais estarão ao lado meridional, que olha para o sul.

[[v2-26-19]]

^<<v2-26-19,19>>^ Para elas farás fundir quarenta bases de prata, de sorte que duas bases sejam postas sob cada tábua nos dois ângulos.

[[v2-26-20]]

^<<v2-26-20,20>>^ Estarão também vinte tábuas no segundo lado do tabernáculo, que olha para o aquilão,

[[v2-26-21]]

^<<v2-26-21,21>>^ tendo quarenta bases de prata; serão postas duas bases debaixo de cada tábua.

[[v2-26-22]]

^<<v2-26-22,22>>^ Para o lado ocidental do tabernáculo farás seis tábuas,

[[v2-26-23]]

^<<v2-26-23,23>>^ e, além desta, mais duas, que se levantem nos ângulos do fundo do tabernáculo.

[[v2-26-24]]

^<<v2-26-24,24>>^ (Estas tábuas) estarão unidas desde baixo até cima, e todas encaixadas umas nas outra. A mesma união se observará com as duas tábuas que devem ser postas nos ângulos.

[[v2-26-25]]

^<<v2-26-25,25>>^ Serão oito tábuas ao todo com dezasseis bases de prata, contando-se duas bases para cada tábua.

[[v2-26-26]]

^<<v2-26-26,26>>^ Farás também uns barrotes de pau de acácia, cinco para conter as tábuas dum lado do tabernáculo.

[[v2-26-27]]

^<<v2-26-27,27>>^ e outros cinco para o outro lado, e outros tantos para o lado ocidental,

[[v2-26-28]]

^<<v2-26-28,28>>^ os quais serão aplicados pelo meio das tábuas duma extremidade à outra.

[[v2-26-29]]

^<<v2-26-29,29>>^ Revestirás de ouro as próprias tábuas, e pôr-lhes-ás umas argolas de ouro, pelas quais passem os barrotes, que hão-de segurar as tábuas, e revestirás de ouro os barrotes.

[[v2-26-30]]

^<<v2-26-30,30>>^ Levantarás o tabernáculo conforme o modelo que te foi mostrado no monte.

[[v2-26-31]]

^<<v2-26-31,31>>^ Farás também um véu de cor de jacinto, e de púrpura e de escarlate tinto duas vezes, e de linho fino retorcido, tecido com formosa variedade, figurando querubins.

[[v2-26-32]]

^<<v2-26-32,32>>^ Suspendê-lo-ás de quatro colunas de pau de acácia, que serão revestidas de ouro, terão capiteis de ouro e bases de prata.

[[v2-26-33]]

^<<v2-26-33,33>>^ O véu será suspenso por meio de argolas, e dentro dele porás a arca do testemunho, e por meio dele serão divididos o Santo e o Santo dos Santos.

[[v2-26-34]]

^<<v2-26-34,34>>^ Porás também o propiciatório sobre a arca do testemunho no Santo dos Santos.

[[v2-26-35]]

^<<v2-26-35,35>>^ (Porás) a mesa fora do véu; defronte da mesa, o candeeiro, na parte meridional do tabernáculo; a mesa estará do lado do aquilão.

[[v2-26-36]]

^<<v2-26-36,36>>^ Farás também, para a entrada do tabernáculo, um véu de linho retorcido. cor de jacinto, e de púrpura, e de escarlate tinto duas vezes, trabalhando com desenhos vários.

[[v2-26-37]]

^<<v2-26-37,37>>^ Este véu estará suspenso de cinco colunas de pau de acácia, revestidas de ouro, cujos capiteis Serão de ouro, e as bases de bronze.

'''

xref:002-exodo/002-exodo-025.adoc#v2-25-0[&#60; Capítulo Anterior] | <<v2-26-0,Topo>> | xref:002-exodo/002-exodo-027.adoc#v2-27-0[Próximo Capítulo &#62;]