include::./index.adoc[]

[[v2-37-0]]
=== Êxodo, 37
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 37 do livro de Êxodo descreve a fabricação do altar de incenso, da arca da aliança e da mesa dos pães da proposição, todos com suas respectivas medidas e ornamentos. Para encontrar cinco versículos relacionados com os temas abordados neste capítulo, foram selecionados trechos de outros livros da Bíblia que também falam sobre a construção desses objetos sagrados.
* 1 Reis 7:48: "Salomão fez também todos os utensílios que pertenciam à casa do SENHOR: o altar de ouro; a mesa de ouro em que se punham os pães da proposição;” Este versículo menciona a mesa dos pães da proposição, objeto que foi fabricado no capítulo 37 de Êxodo.
* 2 Crônicas 4:19: "Salomão fez todos os utensílios que pertenciam à Casa de Deus; o altar de ouro; as mesas em que se colocavam os pães da proposição;” Esse versículo também menciona as mesas dos pães da proposição, assim como o anterior.
* Hebreus 9:4: "que tinha o altar de ouro do incenso, e a arca da aliança, coberta de ouro por todos os lados, na qual estava um vaso de ouro contendo o maná, a vara de Arão que floresceu e as tábuas da aliança" Esse versículo fala sobre a arca da aliança, que também foi fabricada no capítulo 37 de Êxodo.
* 1 Reis 6:20: "O oráculo, que estava no fundo da casa, tinha vinte côvados de comprimento, vinte de largura e vinte de altura; recobriu-o de ouro puro e também recobriu de ouro o altar de cedro." Esse versículo fala sobre o revestimento de ouro que foi feito no altar de incenso, objeto que também é mencionado no capítulo 37 de Êxodo.
* 2 Crônicas 5:10: "Nada havia nas tábuas que Moisés colocara na arca da aliança, senão somente as duas tábuas que foram postas ali por Moisés, em Horebe, quando o SENHOR fez aliança com os filhos de Israel, ao saírem eles do Egito." Esse versículo fala sobre as tábuas da aliança, que foram colocadas dentro da arca da aliança, objeto que foi fabricado no capítulo 37 de Êxodo.
****

[[v2-37-1]]

^<<v2-37-1,1>>^ Beseleel fez a arca de pau de acácia, a qual tinha dois côvados e meio de comprido, côvado e meio de largo, e também côvado e meio de alto. Revestiu-a de ouro finíssimo por dentro e por fora,

[[v2-37-2]]

^<<v2-37-2,2>>^ e fez-lhe uma cornija de ouro ao redor,

[[v2-37-3]]

^<<v2-37-3,3>>^ e fundiu quatro argolas de ouro para os seus quatro cantos: duas argolas de um lado, e duas do outro.

[[v2-37-4]]

^<<v2-37-4,4>>^ Fez também os varais de acácia, os quais revestiu de ouro,

[[v2-37-5]]

^<<v2-37-5,5>>^ e fê-los entrar pelas argolas que estavam nos lados da arca, para a levar.

[[v2-37-6]]

^<<v2-37-6,6>>^ Fez mais o propiciatório de ouro puríssimo, com dois côvados e meio de comprido, e côvado e meio de largo.

[[v2-37-7]]

^<<v2-37-7,7>>^ Também fez de querubins de ouro batido, os quais pôs aos dois lados do propiciatório:

[[v2-37-8]]

^<<v2-37-8,8>>^ um querubim na extremidade de um lado, e outro querubim na extremidade do outro lado; (estes) dois querubins (ficavam) nas duas extremidades do propiciatório,

[[v2-37-9]]

^<<v2-37-9,9>>^ de asas estendidas, a cobrir o propiciatório, olhando um para o outro, (mas inclinados) para o propiciatório.

[[v2-37-10]]

^<<v2-37-10,10>>^ Fez também uma mesa de acácia, com dois côvados de comprido, um côvado de largo, e côvado e meio de alto.

[[v2-37-11]]

^<<v2-37-11,11>>^ Cobriu-a de ouro puríssimo, fez-lhe ao redor uma orla de ouro,

[[v2-37-12]]

^<<v2-37-12,12>>^ e sobre a mesma orla uma cornija de ouro entalhada, da altura de quatro dedos, e sobre esta uma outra cornija de ouro.

[[v2-37-13]]

^<<v2-37-13,13>>^ Fundiu também quatro argolas de ouro, que pós nos quatro cantos em cada um dos pés da mesa,

[[v2-37-14]]

^<<v2-37-14,14>>^ e enfiou por elas os varais, para a mesa poder ser levada.

[[v2-37-15]]

^<<v2-37-15,15>>^ Fez estes mesmos varais de pau de acácia e revestiu-os de ouro.

[[v2-37-16]]

^<<v2-37-16,16>>^ Fez os utensílios para os diferentes usos da mesa, pratos, copos, taças e turíbulos de ouro puríssimo, em que se hão-de oferecer as libações.

[[v2-37-17]]

^<<v2-37-17,17>>^ Fez também o candeeiro de finíssimo ouro batido, de cuja haste saiam os ramos, os copos, as esferazinhas e as açucenas.

[[v2-37-18]]

^<<v2-37-18,18>>^ Seis (ramos saiam) dos dois lados, três ramos de um lado, e três do outro.

[[v2-37-19]]

^<<v2-37-19,19>>^ Havia três copos em forma de noz e esferazinhas e açucenas, tanto no primeiro, como no segundo, como no terceiro ramo. Era igual o lavor dos seis ramos, que saíam da haste do candeeiro.

[[v2-37-20]]

^<<v2-37-20,20>>^ Porém na mesma haste havia quatro copos em forma de noz, e cada um tinha as suas esferazinhas e as suas açucenas,

[[v2-37-21]]

^<<v2-37-21,21>>^ e havia três esferazinhas em três lugares da haste, e de cada uma saíam dois ramos, ficando ao todo seis ramos a sair da mesma haste.

[[v2-37-22]]

^<<v2-37-22,22>>^ Assim as esferazinhas e os ramos saiam dela, tudo de ouro puríssimo e trabalhado a martelo.

[[v2-37-23]]

^<<v2-37-23,23>>^ Fez também de finíssimo ouro sete lâmpadas com seus espevitadores, bem como os vasos onde se apagasse o morrão.

[[v2-37-24]]

^<<v2-37-24,24>>^ O candeeiro com todos os seus vasos pesava um talento de ouro.

[[v2-37-25]]

^<<v2-37-25,25>>^ Fez de pau de acácia o altar dos perfumes, que tinha um côvado de comprimento, outro de largura, e dois côvados de alto, de cujos cantos saíam as pontas.

[[v2-37-26]]

^<<v2-37-26,26>>^ Revestiu-o de ouro puríssimo, juntamente com as grelhas e as paredes e as pontas.

[[v2-37-27]]

^<<v2-37-27,27>>^ Fez-lhe uma cornija de ouro ao redor e duas argolas de ouro debaixo da cornija, a cada lado, para se meterem por elas os varais, e se poder levar o altar.

[[v2-37-28]]

^<<v2-37-28,28>>^ Fez os mesmos varais de pau de acácia e cobriu-os com lâminas de ouro.

[[v2-37-29]]

^<<v2-37-29,29>>^ Compôs também o óleo para a unção das sagrações, e o perfume dos aromas mais puros, segundo as regras da perfumaria.

'''

xref:002-exodo/002-exodo-036.adoc#v2-36-0[&#60; Capítulo Anterior] | <<v2-37-0,Topo>> | xref:002-exodo/002-exodo-038.adoc#v2-38-0[Próximo Capítulo &#62;]