include::./index.adoc[]

[[v2-14-0]]
=== Êxodo, 14
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Êxodo 14 narra a história da travessia do Mar Vermelho pelo povo de Israel, enquanto eles fugiam da escravidão no Egito. O capítulo começa com Deus dando instruções a Moisés sobre como acampar diante do mar e continua com a perseguição do faraó e seu exército até a chegada do momento em que o Mar Vermelho é dividido e o povo de Israel é salvo. Abaixo estão cinco versículos relacionados aos temas abordados em Êxodo 14:
* Salmos 77:19: "Teu caminho passou pelo mar, o teu caminho pelas águas poderosas, e ninguém conheceu as tuas pegadas." Este versículo fala sobre a maravilhosa intervenção de Deus na travessia do Mar Vermelho, destacando a grandeza e o poder do seu caminho.
* Isaías 43:2: "Quando passares pelas águas, estarei contigo, e quando pelos rios, eles não te submergirão; quando passares pelo fogo, não te queimarás, nem a chama arderá em ti." Este versículo traz a promessa de Deus de que estará com o seu povo em todos os momentos, inclusive nas situações mais difíceis e perigosas.
* 1 Coríntios 10:1-2: "Porque não quero, irmãos, que ignoreis que nossos pais estiveram todos debaixo da nuvem, e todos passaram pelo mar; e todos foram batizados em Moisés, na nuvem e no mar." Este versículo faz referência ao evento da travessia do Mar Vermelho como um batismo, simbolizando a separação do povo de Israel da escravidão e sua união com Deus.
* Hebreus 11:29: "Pela fé atravessaram o Mar Vermelho como por terra seca; tentando-o os egípcios, foram tragados pelas águas." Este versículo destaca a importância da fé na travessia do Mar Vermelho, mostrando que foi a confiança no poder e na fidelidade de Deus que permitiu que o povo de Israel passasse a salvo.
* Salmos 106:9: "Repreendeu o Mar Vermelho, e este se secou; ele os fez caminhar pelos abismos como pelo deserto." Este salmo faz referência ao evento que aconteceu em Êxodo 14:21, quando Deus abriu o Mar Vermelho para que os israelitas pudessem atravessá-lo a pé enxuto.
****

[[v2-14-1]]

^<<v2-14-1,1>>^ o Senhor falou a Moisés, dizendo:

[[v2-14-2]]

^<<v2-14-2,2>>^ Dize aos Filhos de Israel que retrocedam e vão acampar diante de Fiairoth, que fica entre Magdalum e o mar, defronte de Bedsefon: assentareis o acampamento defronte deste sítio junto do mar.

[[v2-14-3]]

^<<v2-14-3,3>>^ Faraó há-de dizer acerca dos filhos de Israel; Eles andam errantes pelo país, estão encerrados no deserto.

[[v2-14-4]]

^<<v2-14-4,4>>^ Eu endurecerei o seu coração, e ele virá no vosso encalço: eu serei glorificado em Faraó, e em todo o seu exército; e os Egípcios saberão que eu sou o Senhor. Eles assim fizeram. (ver nota)

[[v2-14-5]]

^<<v2-14-5,5>>^ Entretanto foi anunciado ao rei dos Egípcios que o povo tinha fugido. Então mudou-se o coração de Faraó e de seus servos a respeito do povo, e disseram: Que quisemos nós fazer, deixando partir Israel, para que ele nos não servisse?

[[v2-14-6]]

^<<v2-14-6,6>>^ (Faraó), pois, mandou pôr os cavalos ao seu carro, e tomou consigo todo o seu povo. (ver nota)

[[v2-14-7]]

^<<v2-14-7,7>>^ Tomou seiscentos carros escolhidos, com homens de guerra sobre cada um deles.

[[v2-14-8]]

^<<v2-14-8,8>>^ O Senhor endureceu o coração de Faraó, rei do Egipto, que foi no alcance dos filhos de Israel. Mas eles tinham saído debaixo da protecção duma poderosa mão.

[[v2-14-9]]

^<<v2-14-9,9>>^ Como os Egípcios seguissem os vestígios dos (Israelitas) que iam adiante, alcançaram-nos quando estavam acampados junto do mar. Toda a cavalaria e os carros de Faraó e o exército estavam em Fiairoth defronte de Beelssefon.

[[v2-14-10]]

^<<v2-14-10,10>>^ Como Faraó se aproximasse, levantando os filhos de Israel os olhos, viram os Egípcios nas suas costas, tiveram grande medo, e clamaram ao Senhor.

[[v2-14-11]]

^<<v2-14-11,11>>^ Disseram a Moisés: Não havia talvez sepulturas no Egipto, e por isso nos tiraste de lá para morrermos no deserto. Que fizeste, tirando-nos do Egipto?

[[v2-14-12]]

^<<v2-14-12,12>>^ Não é isto que te dizíamos no Egipto: Retira-te de nós, a fim de que sirvamos os Egípcios, porque é muito melhor servi-los do que morrer no deserto?

[[v2-14-13]]

^<<v2-14-13,13>>^ Moisés disse ao povo: Não temais: estai firmes, e considerai as maravilhas que o Senhor fará hoje, porque os Egípcios, que agora vedes, nunca jamais os tornareis a ver.

[[v2-14-14]]

^<<v2-14-14,14>>^ O Senhor combaterá por vós, e vós estai tranquilos.

[[v2-14-15]]

^<<v2-14-15,15>>^ O Senhor disse a Moisés: Por que clamas tu a mim? Dize aos filhos de Israel que marchem.

[[v2-14-16]]

^<<v2-14-16,16>>^ E tu levanta a tua vara, estende a mão sobre o mar e divide-o, para que os filhos de Israel caminhem em seco pelo meio do mar.

[[v2-14-17]]

^<<v2-14-17,17>>^ Eu endurecerei o coração dos Egípcios, para que eles vos sigam, e serei glorificado em Faraó e em todo o exército, nos seus carros e nos seus cavaleiros.

[[v2-14-18]]

^<<v2-14-18,18>>^ Os Egípcios saberão que eu sou o Senhor, quando for glorificado em Faraó, nos seus carros e nos seus cavaleiros.

[[v2-14-19]]

^<<v2-14-19,19>>^ O Anjo de Deus, que caminhava na frente do acampamento de Israel, levantou-se e foi para detrás deles; com ele, ao mesmo tempo, a coluna de nuvem, deixando a frente,

[[v2-14-20]]

^<<v2-14-20,20>>^ parou detrás deles entre o acampamento dos Egípcios e o acampamento de Israel, e esta nuvem era tenebrosa (do lado dos Egípcios) e tornava clara a noite (do lado dos Israelitas), de sorte que uns e outros não puderam aproximar-se durante o tempo da noite.

[[v2-14-21]]

^<<v2-14-21,21>>^ Tendo Moisés estendido a mão sobre o mar, o Senhor, soprando toda a noite um vento forte e ardente, o redrou e secou: e a água dividiu-se.

[[v2-14-22]]

^<<v2-14-22,22>>^ Os filhos de Israel entraram pelo meio do mar enxuto: a água estava como um muro à direita e à esquerda deles.

[[v2-14-23]]

^<<v2-14-23,23>>^ Os Egípcios, que os perseguiam, entraram atrás deles pelo meio do mar, e toda a cavalaria de Faraó, os seus carros e cavaleiros.

[[v2-14-24]]

^<<v2-14-24,24>>^ E já tinha chegado a vigília da manhã, quando o Senhor, olhando para o acampamento dos Egípcios por entre a coluna de fogo e de nuvem, perturbou o seu exército. (ver nota)

[[v2-14-25]]

^<<v2-14-25,25>>^ Transtornou as rodas dos canos, que só, a muito custo, avançavam. Disseram, pois, os Egípcios: Fujamos de Israel, porque o Senhor combate por eles contra nós.

[[v2-14-26]]

^<<v2-14-26,26>>^ O Senhor disse a Moisés: Estende a tua mão sobre o mar, para que as águas se voltem para os Egípcios, sobre os seus carros e os seus cavaleiros.

[[v2-14-27]]

^<<v2-14-27,27>>^ Moisés, tendo estendido a mão sobre o mar, (este) ao romper da manhã, voltou para o lugar habitual, e, fugindo os Egípcios, foram as águas sobre eles, e o Senhor os envolveu no meio das ondas.

[[v2-14-28]]

^<<v2-14-28,28>>^ As águas voltaram, e cobriram os carros e cavaleiros de todo o exército de Faraó, os quais, em seguimento (dos Israelitas), tinham entrado no mar; e não escapou um só deles.

[[v2-14-29]]

^<<v2-14-29,29>>^ Mas os filhos de Israel passaram pelo meio do mar enxuto; as águas eram para eles como um muro à direita e à esquerda.

[[v2-14-30]]

^<<v2-14-30,30>>^ O Senhor, naquele dia, livrou Israel da mão dos Egípcios.

[[v2-14-31]]

^<<v2-14-31,31>>^ Os Israelitas viram os Egípcios mortos sobre a praia do mar, e o grande poder que o Senhor tinha mostrado contra eles; o povo temeu o Senhor, e acreditou no Senhor e em Moisés seu servo.

'''

xref:002-exodo/002-exodo-013.adoc#v2-13-0[&#60; Capítulo Anterior] | <<v2-14-0,Topo>> | xref:002-exodo/002-exodo-015.adoc#v2-15-0[Próximo Capítulo &#62;]