include::./index.adoc[]

[[v2-28-0]]
=== Êxodo, 28
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Êxodo 28 trata da vestimenta que os sacerdotes deveriam usar para realizar os serviços sagrados no tabernáculo. Abaixo estão cinco versículos relacionados a temas abordados no capítulo, excluindo versículos de Êxodo 28:
* Levítico 8:13: "Fez também aproximar Aarão e seus filhos e os lavou com água." Este versículo descreve a preparação dos sacerdotes para o serviço sagrado, que incluía lavagem. Isso se relaciona com Êxodo 28, que fala da vestimenta sacerdotal, uma parte importante da preparação para o serviço.
* Levítico 10:10: "Para fazer diferença entre o santo e o profano e entre o impuro e o puro." Este versículo fala sobre a distinção entre o sagrado e o profano, o puro e o impuro. Isso se relaciona com Êxodo 28, que fala da vestimenta sacerdotal como uma forma de santificação e separação do serviço sagrado.
* Isaías 61:10: "Muito me regozijo no Senhor, a minha alma se alegra no meu Deus; porque me vestiu de vestes de salvação, cobriu-me com o manto de justiça." Este versículo fala sobre a alegria do povo de Deus por serem vestidos com vestes de salvação e justiça. Isso se relaciona com Êxodo 28, que fala da vestimenta sacerdotal como um símbolo de justiça e salvação.
* Hebreus 4:14: "Tendo, pois, um grande sumo sacerdote que penetrou os céus, Jesus, o Filho de Deus, apeguemo-nos com firmeza à confissão da nossa esperança." Este versículo fala sobre Jesus como sumo sacerdote que intercede por nós. Isso se relaciona com Êxodo 28, que fala da vestimenta sacerdotal como uma forma de representação do sumo sacerdote que intercede por Israel.
* Apocalipse 1:6: "E nos fez reis e sacerdotes para Deus e seu Pai; a ele glória e poder para todo o sempre. Amém." Este versículo fala sobre a identidade do povo de Deus como reis e sacerdotes. Isso se relaciona com Êxodo 28, que fala da vestimenta sacerdotal como uma forma de identidade sacerdotal e como um meio de aproximação de Deus.
****

[[v2-28-1]]

^<<v2-28-1,1>>^ Manda também vir junto de ti Aarão teu irmão, com seus filhos, do meio dos filhos de Israel, para que exerçam diante de mim as funções do sacerdócio: Aarão, Nadab e Abiu, Eteazar e Itamar.

[[v2-28-2]]

^<<v2-28-2,2>>^ Farás uma veste sagrada para Aarão, teu irmão, para (indicar a sua) dignidade e para (lhe servir de) adorno.

[[v2-28-3]]

^<<v2-28-3,3>>^ Falarás a todos os sábios de coração, a quem eu enchi do espírito de prudência, para que façam as vestes de Aarão, com as quais, sendo santificado, exercerá o meu sacerdócio.

[[v2-28-4]]

^<<v2-28-4,4>>^ Estas são as vestes que hão-de fazer: O peitoral e o éfode, o manto e a túnica de linho estreita, a tiara e o cíngulo. Farão estas vestes sagradas para Aarão, teu irmão, e para seus filhos, para que exerçam as funções do meu sacerdócio.

[[v2-28-5]]

^<<v2-28-5,5>>^ Tomarão outo, púrpura violácea, púrpura escarlate e carmesim, e linho finta.

[[v2-28-6]]

^<<v2-28-6,6>>^ Farão o éfode de ouro, de púrpura violácea, púrpura escarlate e carmesim, e de linho fino retorcido, artisticamente entretecidos.

[[v2-28-7]]

^<<v2-28-7,7>>^ (O éfode) terá nos dois lados das suas extremidades duas aberturas unidas de modo a formarem um (só vestido).

[[v2-28-8]]

^<<v2-28-8,8>>^ O cíngulo que atará o éfode, fará com ele uma só peça e será do mesmo trabalho: de ouro, de púrpura violácea, escarlate, carmesim e linho fino retorcido

[[v2-28-9]]

^<<v2-28-9,9>>^ E tomarás duas pedras de ónix, e gravarás nelas os nomes dos filhos de Israel:

[[v2-28-10]]

^<<v2-28-10,10>>^ Seis nomes numa pedra, e outros seis na outra, segundo a ordem do seu nascimento.

[[v2-28-11]]

^<<v2-28-11,11>>^ Com obra de escultor e de lapidário gravarás nelas os nomes dos filhos de Israel, tendo-as engastado e metido em ouro;

[[v2-28-12]]

^<<v2-28-12,12>>^ pô-las-ás sobre um e outro lado do éfode, (para que sirvam) de memória aos filhos de Israel. Aarão levará os seus nomes diante do Senhor sobre os seus dois ombros para lembrança.

[[v2-28-13]]

^<<v2-28-13,13>>^ Farás também ganchos de ouro,

[[v2-28-14]]

^<<v2-28-14,14>>^ e duas pequenas cadeias de ouro puríssimo ligadas entre si, as quais meterás nos ganchos.

[[v2-28-15]]

^<<v2-28-15,15>>^ Farás também o peitoral do juízo com trabalho a muitas cores, tecidos, como o éfode, de ouro, de jacinto, e de púrpura, e de escarlate tinto duas vezes, e de linho fino retorcido. (ver nota)

[[v2-28-16]]

^<<v2-28-16,16>>^ Será quadrado e dobrado; terá um palmo, tanto de comprimento como de largura.

[[v2-28-17]]

^<<v2-28-17,17>>^ Engastarás nele quatro ordens de pedras; na primeira ordem estará um sardio, um topázio e uma esmeralda;

[[v2-28-18]]

^<<v2-28-18,18>>^ o a segunda, um carbúnculo, uma safira e um jaspe;

[[v2-28-19]]

^<<v2-28-19,19>>^ na terceira uma turqueza, uma ágata e uma ametista;

[[v2-28-20]]

^<<v2-28-20,20>>^ na quarta um crisólito, um ónix e um berilo. Elas serão encastoadas em ouro, ordem por ordem.

[[v2-28-21]]

^<<v2-28-21,21>>^ Terão os nomes dos filhos de Israel: estarão nelas gravados doze nomes, em cada pedra o nome de uma das doze tribos.

[[v2-28-22]]

^<<v2-28-22,22>>^ Farás para o peitoral pequenas cadeias de ouro puríssimo, que se unam entre si,

[[v2-28-23]]

^<<v2-28-23,23>>^ e duas argolinhas de ouro, que porás nas duas extremidades superiores do peitoral.

[[v2-28-24]]

^<<v2-28-24,24>>^ Farás passar cadeias de ouro pelas argolinhas, que estão nas extremidades dele,

[[v2-28-25]]

^<<v2-28-25,25>>^ e adaptarás as extremidades das mesmas cadeias a dois ganchos dum e doutro lado do éfode, que corresponde ao peitoral.

[[v2-28-26]]

^<<v2-28-26,26>>^ Farás também duas argolinhas de ouro, que porás nas extremidades (inferiores) do peitoral, nas ourelas que estão de fronte do éfode, e estão voltadas para a parte de trás.

[[v2-28-27]]

^<<v2-28-27,27>>^ (Farás), além disso, outras duas argolinhas de ouro, que se hão-de pôr em baixo, aos dois lados do éfode, que estão diante da juntura inferior, a fim de que (o peitoral) possa adaptar-se ao éfode,

[[v2-28-28]]

^<<v2-28-28,28>>^ esteja ligado com as suas argolinhas às do éfode, por uma fita (cor) de jacinto, de modo que fique firme o enlace feito com arte, e o peitoral e o éfode, não possam separar-se um do outro.

[[v2-28-29]]

^<<v2-28-29,29>>^ Aarão, quando entrar no santuário, levará os nomes dos filhos de Israel do peitoral do juízo sobre o peso, para perpétua memória diante do Senhor.

[[v2-28-30]]

^<<v2-28-30,30>>^ No peitoral do juízo porás (estas duas palavras): Doutrina e Verdade, as quais estarão sobre o peito de Aarão, quando ele entrar à presença do Senhor; assim trará sempre sobre o seu peito o juízo dos filhos de Israel na presença do Senhor. (ver nota)

[[v2-28-31]]

^<<v2-28-31,31>>^ Farás também a túnica do éfode toda (de cor) de jacinto,

[[v2-28-32]]

^<<v2-28-32,32>>^ no meio da qual no alto haverá uma abertura para a cabeça, e em volta uma orla tecida, como se costuma fazer na ourela dos vestidos, para que (a túnica) se não rompa facilmente.

[[v2-28-33]]

^<<v2-28-33,33>>^ Em baixo, porém, na extremidade inferior da mesma túnica, farás ao redor umas como romãs de púrpura violácea, púrpura escarlate e carmesim, (tendo) misturadas pelo meio campainhas,

[[v2-28-34]]

^<<v2-28-34,34>>^ de sorte que haja uma campainha de ouro e uma romã, e logo outra campainha de ouro e outra romã.

[[v2-28-35]]

^<<v2-28-35,35>>^ Aarão a vestirá nas funções do seu ministério, para que se ouça o som ao entrar no santuário, à presença do Senhor, e ao sair, e para que não morra.

[[v2-28-36]]

^<<v2-28-36,36>>^ Farás também uma lâmina de ouro puríssimo, na qual farás abrir por mão de gravador: Santidade ao Senhor.

[[v2-28-37]]

^<<v2-28-37,37>>^ Atá-la-ás com uma fita de púrpura violácea, e estará sobre a tiara, dominando a fronte

[[v2-28-38]]

^<<v2-28-38,38>>^ do pontífice. Aarão levará as iniquidades cometidas pelos filhos de Israel em todas as suas oblações, e nos dons que tiverem oferecido e consagrado. Esta lâmina estará sempre sobre a sua fronte, para que o Senhor lhes seja propício. (ver nota)

[[v2-28-39]]

^<<v2-28-39,39>>^ Farás a túnica estreita de linho fino, farás a tiara de linho fino, e o cíngulo será de várias cores.

[[v2-28-40]]

^<<v2-28-40,40>>^ Para os filhos de Aarão, prepararás túnicas de linho cíngulos e tiaras, para (indicar a sua) dignidade e (servir-lhes de) adorno;

[[v2-28-41]]

^<<v2-28-41,41>>^ de tudo isto vestirás Aarão, teu irmão, e os seus filhos com ele. Sagrarás as mãos de todos, e sacrificá-los-ás, para que me exerçam o sacerdócio.

[[v2-28-42]]

^<<v2-28-42,42>>^ Farás também calções de linho, para cobrirem a nudez da sua carne, desde os rins até às coxas.

[[v2-28-43]]

^<<v2-28-43,43>>^ Aarão e seus filhos usarão deles quando entrarem no tabernáculo do testemunho, ou quando se aproximarem do altar para servir no santuário, para que não morram como réus de iniquidade. Isto será uma lei perpétua para Aarão e para a sua posteridade depois dele.

'''

xref:002-exodo/002-exodo-027.adoc#v2-27-0[&#60; Capítulo Anterior] | <<v2-28-0,Topo>> | xref:002-exodo/002-exodo-029.adoc#v2-29-0[Próximo Capítulo &#62;]