include::./index.adoc[]

[[v2-18-0]]
=== Êxodo, 18
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Êxodo 18 descreve a visita de Jetro, sogro de Moisés, ao acampamento de Israel no deserto. Jetro aconselha Moisés a delegar autoridade a outros líderes e a estabelecer um sistema judicial para aliviar o fardo de liderança que estava sobre ele. Além disso, Jetro oferece um sacrifício a Deus e se regozija com a libertação do povo de Israel. Abaixo estão cinco versículos da Bíblia que abordam temas relacionados a Êxodo 18:
* Deuteronômio 1:9-13: "Naqueles dias, eu disse a vocês: ‘Não posso carregar sozinho todo esse povo; não posso levá-los sozinho. (...) Por isso, escolham homens sábios, inteligentes e experientes de cada uma das suas tribos, e eu os colocarei como líderes sobre vocês.’" Esse trecho da Bíblia faz referência ao conselho que Jetro dá a Moisés sobre a necessidade de delegar autoridade a outros líderes, para que ele não tivesse que carregar todo o fardo sozinho.
* Deuteronômio 16:18-19: "Nomeie juízes e autoridades em cada cidade que o Senhor, o seu Deus, lhe dá para que julguem o povo com justiça. Não torça a justiça nem mostre parcialidade. Não aceite suborno, pois o suborno cega os olhos dos sábios e perverte as palavras dos justos." Esse versículo se relaciona com a sugestão de Jetro para que Moisés estabelecesse um sistema judicial para ajudá-lo a lidar com as demandas do povo.
* Salmos 78:70-71: "Escolheu Davi, seu servo, e o tirou dos apriscos de ovelhas, do cuidado com os cordeiros, para ser o pastor do seu povo, Jacó, sua herança." Esse versículo é um exemplo de como Deus escolhe líderes para guiar seu povo, assim como Jetro aconselhou Moisés a escolher outros líderes para ajudá-lo a liderar os israelitas.
* Provérbios 11:14: "Sem conselhos os planos fracassam, mas com muitos conselheiros eles se cumprem." Esse provérbio se relaciona com a sabedoria de Jetro em aconselhar Moisés a delegar autoridade e estabelecer um sistema judicial para ajudá-lo a liderar o povo de Israel.
* 1 Crônicas 26:29: "Dos filhos de Isaque, (isto é, os de Tola) foram dois chefes de famílias; de Jezer, os de Jeuel." Esse versículo se refere a um dos homens que Moisés escolheu como líder para ajudá-lo a governar o povo, destacando a importância da delegação de tarefas para uma liderança mais eficiente.
****

[[v2-18-1]]

^<<v2-18-1,1>>^ Ora, tendo ouvido Jetro, sacerdote de Madian, sogro de Moisés, tudo o que Deus tinha feito a Moisés e a Israel, seu povo, tirando-o do Egipto,

[[v2-18-2]]

^<<v2-18-2,2>>^ tomou Séfora, mulher de Moisés, a qual ele lhe tinha deixado,

[[v2-18-3]]

^<<v2-18-3,3>>^ e os dois filhos dela, um dos quais se chamava Gersão, por seu pai ter dito: "Eu fui peregrino numa terra estrangeira",

[[v2-18-4]]

^<<v2-18-4,4>>^ e o outro (se chamava) Elieser, por seu pai ter dito: "O Deus de meu pai foi o meu defensor, e me salvou da espada de Faraó".

[[v2-18-5]]

^<<v2-18-5,5>>^ Foi, pois, Jetro, sogro de Moisés, com seus filhos e sua mulher, ter com Moisés ao deserto, onde ele estava acampado junto ao monte de Deus,

[[v2-18-6]]

^<<v2-18-6,6>>^ e mandou dizer a Moisés: Eu, Jetro, teu sogro, venho ter contigo com tua mulher e os teus dois filhos com ela.

[[v2-18-7]]

^<<v2-18-7,7>>^ Moisés, saindo ao encontro de seu sogro, prostrou-se (diante dele) e o beijou, e saudaram-se mutuamente com palavras amigas. Tendo entrado na tenda,

[[v2-18-8]]

^<<v2-18-8,8>>^ Moisés contou a seu sogro tudo o que o Senhor tinha feito contra Faraó e os Egípcios, por causa de Israel, todo o trabalho que lhe sobreviera no caminho, e como o Senhor os tinha livrado.

[[v2-18-9]]

^<<v2-18-9,9>>^ Jetro alegrou-se por todos os bens que o Senhor tinha feito a Israel, e porque o tinha livrado da mão dos Egipcios,

[[v2-18-10]]

^<<v2-18-10,10>>^ e disse: Bendito (seja) o Senhor, que vos livrou da mão dos Egípcios e da mão de Faraó, e que livrou o seu povo da mão dos Egípcios.

[[v2-18-11]]

^<<v2-18-11,11>>^ Agora conheci que o Senhor é grande sobre todos os deuses, porque se mostrou grande quando os Egípcios oprimiam Israel.

[[v2-18-12]]

^<<v2-18-12,12>>^ Jetro, sogro de Moisés, ofereceu a Deus holocaustos e hóstias, e Aarão e todos os anciães de Israel vieram comer com ele diante do Senhor. (ver nota)

[[v2-18-13]]

^<<v2-18-13,13>>^ No dia seguinte, Moisés assentou-se para julgar o povo que esteve diante dele desde manhã até à tarde.

[[v2-18-14]]

^<<v2-18-14,14>>^ Seu sogro, tendo visto tudo o que ele fazia com o povo disse: Que é isto que fazes com o povo? Por que te sentas só tu (no tribunal), e todo o povo está esperando desde manhã até à tarde?

[[v2-18-15]]

^<<v2-18-15,15>>^ Moisés respondeu-lhe: O povo vem a mim para ouvir a sentença de Deus,

[[v2-18-16]]

^<<v2-18-16,16>>^ Quando entre eles nasce alguma contenda, vêm ter comigo, para que eu julgue entre eles, e lhes mostre os preceitos de Deus e as suas leis.

[[v2-18-17]]

^<<v2-18-17,17>>^ Mas Jetro disse: Não fazes bem.

[[v2-18-18]]

^<<v2-18-18,18>>^ Consomes-te com um trabalho vão, a ti e a este povo que está contigo: este trabalho é sobre as tuas forças, e tu só não o poderás aturar.

[[v2-18-19]]

^<<v2-18-19,19>>^ Ouve as minhas palavras e conselhos, e Deus será contigo. Sê mediador do povo naquelas coisas que dizem respeito a Deus, para lhe expores os pedidos que lhe são dirigidos,

[[v2-18-20]]

^<<v2-18-20,20>>^ e para ensinares ao povo as cerimônias e o modo de honrar a Deus, o caminho por onde devem andar e as obras que devem fazer.

[[v2-18-21]]

^<<v2-18-21,21>>^ Mas escolhe entre todo o povo homens capazes e tementes a Deus, nos quais haja verdade e que aborreçam a avareza: faz deles chefes de mil, de cem, de cinquenta e de dez homens,

[[v2-18-22]]

^<<v2-18-22,22>>^ os quais julguem o povo em todo o tempo, te dêem conta coisas mais graves, e eles julguem sòmente as coisas menos graves. Desta sorte o peso que te oprime será mais leve, sendo repartido com outros.

[[v2-18-23]]

^<<v2-18-23,23>>^ Se fizeres isto, cumprirás a ordem de Deus e poderás executar os seus preceitos: e todo este povo voltará em paz para as suas moradas.

[[v2-18-24]]

^<<v2-18-24,24>>^ Moisés, tendo ouvido isto, fez tudo o que seu sogro lhe sugerira.

[[v2-18-25]]

^<<v2-18-25,25>>^ Tendo escolhido entre todo o povo de Israel homens de valor, constituiu chefes de mil, de cem, de cinqüenta e de dez homens.

[[v2-18-26]]

^<<v2-18-26,26>>^ Eles faziam justiça ao povo em todo o tempo, e davam conta a Moisés de todas as coisas mais graves, julgando eles sòmente as mais fáceis.

[[v2-18-27]]

^<<v2-18-27,27>>^ Moisés despediu-se de seu sogro, o qual voltou para o seu país.

'''

xref:002-exodo/002-exodo-017.adoc#v2-17-0[&#60; Capítulo Anterior] | <<v2-18-0,Topo>> | xref:002-exodo/002-exodo-019.adoc#v2-19-0[Próximo Capítulo &#62;]