include::./index.adoc[]

[[v2-11-0]]
=== Êxodo, 11
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Em Êxodo 11, Deus anuncia a última praga que será lançada sobre o Egito, a morte de todos os primogênitos. Moisés comunica isso ao faraó e à nação egípcia. Aqui estão cinco versículos relacionados com os temas abordados neste capítulo:
* Salmos 105:36: "Ele feriu a todos os primogênitos no Egito, as primícias da força deles nas tendas de Cão." Este salmo relembra as ações de Deus durante a libertação do povo de Israel do Egito, incluindo a morte dos primogênitos.
* Êxodo 12:12: "Naquela noite passarei pelo Egito e matarei todos os primogênitos, tanto dos homens como dos animais, e executarei juízo sobre todos os deuses do Egito. Eu sou o Senhor." Este versículo é uma continuação da última praga que será lançada sobre o Egito.
* Números 3:12-13: "Eu tomei todos os primogênitos dos filhos de Israel para mim, tanto dos homens como dos animais; no dia em que feri todo primogênito na terra do Egito, eu os separei para mim. Mas tomei os levitas em lugar de todos os primogênitos dos filhos de Israel." Aqui, Deus explica que os levitas serão escolhidos para servi-lo em vez dos primogênitos dos filhos de Israel.
* João 1:29: "No dia seguinte, João viu Jesus aproximando-se e disse: 'Eis o Cordeiro de Deus, que tira o pecado do mundo!'" Este versículo faz uma conexão entre a morte do primogênito em Êxodo e a morte de Jesus como o cordeiro de Deus que tira o pecado do mundo.
* Hebreus 11:28: "Pela fé, ele celebrou a Páscoa e aplicou o sangue, para que o destruidor não tocasse nos primogênitos dos israelitas." Este versículo destaca a importância da celebração da Páscoa e da aplicação do sangue do cordeiro para proteger os primogênitos dos filhos de Israel da última praga no Egito.
****

[[v2-11-1]]

^<<v2-11-1,1>>^ O Senhor disse a Moisés: Flagelarei ainda com uma praga a Faraó e ao Egipto, e, depois disso, vos deixará partir, e até vos constrangerá a sair.

[[v2-11-2]]

^<<v2-11-2,2>>^ Dirás, pois, a todo o povo que cada homem peça ao seu amigo, e cada mulher à sua vizinha objectos de prata e ouro.

[[v2-11-3]]

^<<v2-11-3,3>>^ O Senhor fez que o seu povo achasse graça diante dos Egipcios. O próprio Moisés foi um homem muito grande na terra do Egipto, aos olhos dos servos de Faraó e de todo o povo.

[[v2-11-4]]

^<<v2-11-4,4>>^ Moisés disse: Estas coisas diz o Senhor: A meia-noite passarei pelo Egipto, (ver nota)

[[v2-11-5]]

^<<v2-11-5,5>>^ e todo o primogênito morrerá na terra do Egipto, desde o primogênito de Faraó que se assenta sobre o seu trono, até ao primogênito da escrava, que está à mó, e até aos primogênitos dos animais.

[[v2-11-6]]

^<<v2-11-6,6>>^ Haverá em toda a terra do Egipto um grande clamor qual nunca antes houve, nem haverá jamais.

[[v2-11-7]]

^<<v2-11-7,7>>^ Mas entre todos os filhos de Israel, desde os homens até aos animais, não se ouvirá ganir um cão, para que saibais com que grande milagre o Senhor separa os Egípcios de Israel.

[[v2-11-8]]

^<<v2-11-8,8>>^ Todos estes teus servos virão a mim, e se prostrarão diante de mim, dizendo; Sai tu e todo o teu povo, que te está sujeito: depois disto sairemos.

[[v2-11-9]]

^<<v2-11-9,9>>^ E Moisés saiu da presença de Faraó muito irado. O Senhor disse a Moisés: Faraó não vos ouvirá, para que se multipliquem os meus prodígios na terra do Egipto.

[[v2-11-10]]

^<<v2-11-10,10>>^ Moisés e Aarão fizeram diante de Faraó todos os prodígios que estão escritos, mas o Senhor endureceu o coração de Faraó, e ele não deixou partir os filhos de Israel da sua terra.

'''

xref:002-exodo/002-exodo-010.adoc#v2-10-0[&#60; Capítulo Anterior] | <<v2-11-0,Topo>> | xref:002-exodo/002-exodo-012.adoc#v2-12-0[Próximo Capítulo &#62;]