include::./index.adoc[]

[[v2-6-0]]
=== Êxodo, 6
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 6 do livro de Êxodo narra a continuação da conversa entre Deus e Moisés, na qual Deus reafirma sua promessa de libertar o povo de Israel da escravidão no Egito. Moisés então relata a mensagem divina para os israelitas, mas eles não acreditam nele devido à sua aflição. Em seguida, a genealogia de Moisés e Arão é registrada. Aqui estão cinco versículos relacionados aos temas abordados em Êxodo 6:
* Gênesis 15:13-14: "Então o Senhor disse a Abrão: "Saiba com certeza que seus descendentes serão estrangeiros em um país que não é deles, e eles serão escravizados e oprimidos por quatrocentos anos. Mas eu também julgarei a nação que servirão como escravos, e depois disso eles sairão com grande riqueza." Este versículo antecipa o destino dos descendentes de Abraão, que foram escravizados no Egito por 400 anos antes de serem libertados por Deus por meio de Moisés.
* Deuteronômio 7:8: "Mas foi porque o Senhor os amou e manteve o juramento que fez aos seus antepassados que ele os tirou com mão poderosa e os resgatou da escravidão no Egito." Este versículo destaca o amor de Deus por seu povo e a fidelidade à sua promessa de libertá-los da escravidão.
* Salmos 81:6-7: "Eu os removi dos ombros do opressor; suas mãos foram liberadas dos cestos de trabalho. Na sua angústia, vocês clamaram por mim e eu os livrei, eu os respondi da colina sagrada, eu os salvei." Este salmo lembra o povo de Israel da libertação que Deus lhes concedeu do Egito e como ele os libertou de sua opressão.
* Isaías 43:1-2: "Mas agora, assim diz o Senhor, aquele que criou você, ó Jacó, aquele que formou você, ó Israel: 'Não tenha medo, pois eu o redimi; eu o chamei pelo nome; você é meu. Quando você passar pelas águas, eu estarei com você; e quando você passar pelos rios, eles não o inundarão. Quando você andar através do fogo, você não será queimado; as chamas não o consumirão." Este versículo é um lembrete do cuidado de Deus pelo povo de Israel, mesmo durante os momentos difíceis, e sua promessa de estar sempre com eles.
* Jeremias 32:20-21: "Você realizou milagres e maravilhas no Egito e os realizou até hoje, tanto em Israel como entre outras pessoas, e se tornou famoso. Com sua mão poderosa e braço estendido, você redimiu seu povo, os descendentes de Jacó e José." Este versículo destaca o poder de Deus e a libertação que ele concedeu ao povo de Israel no Egito, que continuou a ser lembrada e celebrada.
****

[[v2-6-1]]

^<<v2-6-1,1>>^ O Senhor disse a Moisés: Agora verás o que eu farei a Faraó: (obrigado) por mão poderosa, deixará sair (os filhos de Israel) (obrigado) por mão poderosa os expulsará da sua terra.

[[v2-6-2]]

^<<v2-6-2,2>>^ O Senhor falou a Moisés, dizendo: Eu sou o Senhor,

[[v2-6-3]]

^<<v2-6-3,3>>^ que apareci a Abraão, a Isaac e a Jacob, como o Deus omnipotente: mas não lhes revelei o meu nome Javé.

[[v2-6-4]]

^<<v2-6-4,4>>^ Fiz aliança com eles para lhes dar a terra de Canaan, a terra da sua peregrinação, na qual foram forasteiros.

[[v2-6-5]]

^<<v2-6-5,5>>^ Ouvi o gemido dos filhos de Israel, que os Egípcios têm oprimido, e lembrei-me da minha aliança.

[[v2-6-6]]

^<<v2-6-6,6>>^ Por isso, dize aos filhos de Israel: Eu sou o Senhor, que vos tirarei de sob o jugo dos Egipcios, vos livrarei da escravidão, vos resgatarei com o braço estendido e com grandes juízos. (ver nota)

[[v2-6-7]]

^<<v2-6-7,7>>^ Farei de vós o meu povo, serei o vosso Deus e sabereis que eu sou o Senhor vosso Deus, que vos tirarei de sob o jugo dos Egipcios,

[[v2-6-8]]

^<<v2-6-8,8>>^ e vos introduzirei na terra que jurei dar a Abraão, Isaac e Jacob, terra que entreguei ao vosso domínio. Eu sou o Senhor.

[[v2-6-9]]

^<<v2-6-9,9>>^ Moisés contou tudo isto aos filhos de Israel; eles, porém, não o ouviram por causa da angústia do (seu) espirito e do seu trabalho duríssimo.

[[v2-6-10]]

^<<v2-6-10,10>>^ O Senhor falou a Moisés, dizendo:

[[v2-6-11]]

^<<v2-6-11,11>>^ Vai dizer a Faraó, rei do Egipto, que deixe partir da sua terra os filhos de Israel.

[[v2-6-12]]

^<<v2-6-12,12>>^ Moisés respondeu na presença do Senhor; Os filhos de Israel não me ouvem; ora, como me ouvirá Faraó, a mim que tenho dificuldade em falar?

[[v2-6-13]]

^<<v2-6-13,13>>^ O Senhor falou a Moisés e a Aarão, e deu-lhes ordens para os filhos de Israel e para Faraó, rei dó Egipto, a fim de tirarem os filhos de Israel da terra do Egipto.

[[v2-6-14]]

^<<v2-6-14,14>>^ Estes são os chefes das casas seguindo as Suas famílias. Filhos de Ruben, primogênito de Israel: Henoch, Faliu, Hesron e Carmi.

[[v2-6-15]]

^<<v2-6-15,15>>^ Estas são as famílias de Ruben. Filhos de Simeão: Jamuel, Jamim, Aod, Jaquin, Soar, e Saul, filho de uma cananeia. Esta é a progénie de Simeão.

[[v2-6-16]]

^<<v2-6-16,16>>^ E estes são os nomes dos filhos de Levi, com as suas descendências: Gerson, Caath e Merari. Os anos da vida de Levi foram cento e trinta e sete.

[[v2-6-17]]

^<<v2-6-17,17>>^ Filhos de Gerson: Lobni e Semei, com as suas gerações.

[[v2-6-18]]

^<<v2-6-18,18>>^ Filhos de Caath, Amrão, Isaar, Hebron e Oziel. Os anos da vida de Caath, foram cento e trinta e três.

[[v2-6-19]]

^<<v2-6-19,19>>^ Filhos de Merari: Mooli e Musi: estes (são) os descendentes de Levi, segundo as suas famílias.

[[v2-6-20]]

^<<v2-6-20,20>>^ Amrão tomou por mulher a Jocabed, filha de seu tio paterto, a qual lhe deu à luz Aarão e Moisés. Os anos de vida de Amrão foram cento e trinta e sete.

[[v2-6-21]]

^<<v2-6-21,21>>^ Filhos de Isaar: Coré, Nefeg e Zecri.

[[v2-6-22]]

^<<v2-6-22,22>>^ Filhos de Oziel: Misael, Elisafan e Setri.

[[v2-6-23]]

^<<v2-6-23,23>>^ Aarão tomou por mulher a Isabel, filha de Aminadab, irmã de Naason, a qual lhe deu à luz Nadab, Abiu, Eleazar e Itamar.

[[v2-6-24]]

^<<v2-6-24,24>>^ Filhos de Coré: Aser, Elcana e Abiasaph. Estas são as famílias dos descendentes de Coré.

[[v2-6-25]]

^<<v2-6-25,25>>^ Eleazar, filho de Aarão, tomou por mulher uma das filhas de Futiel, a qual lhe deu à luz Fineias. Estes são os chefes das linhagens dos levitas segundo as suas familias.

[[v2-6-26]]

^<<v2-6-26,26>>^ Estes são o Aarão e o Moisés a quem o Senhor ordenou que tirassem da terra do Egipto os filhos de Israel segundo os seus grupos.

[[v2-6-27]]

^<<v2-6-27,27>>^ Este Moisés e este Aarão são aqueles que falaram a Faraó, rei do Egipto, para tirarem do Egipto os filhos de Israel.

[[v2-6-28]]

^<<v2-6-28,28>>^ No dia em que o Senhor falou a Moisés na terra do Egipto,

[[v2-6-29]]

^<<v2-6-29,29>>^ o Senhor disse a Moisés: Eu sou o Senhor; dize a Faraó, rei do Egipto, tudo o que eu te digo.

[[v2-6-30]]

^<<v2-6-30,30>>^ Moisés respondeu ao Senhor: Tenho dificuldade em falar: como ouvirá Faraó?

'''

xref:002-exodo/002-exodo-005.adoc#v2-5-0[&#60; Capítulo Anterior] | <<v2-6-0,Topo>> | xref:002-exodo/002-exodo-007.adoc#v2-7-0[Próximo Capítulo &#62;]