include::./index.adoc[]

[[v2-36-0]]
=== Êxodo, 36
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Êxodo 36 narra a construção do Tabernáculo por Bezalel e Ooliabe, de acordo com as instruções que Deus deu a Moisés. Os versículos abaixo estão relacionados aos temas abordados em Êxodo 36:
* Êxodo 25:8: "E me farão um santuário, para que eu possa habitar no meio deles." Este versículo é a primeira instrução de Deus para Moisés sobre a construção do Tabernáculo, mostrando a importância de ter um lugar para a presença de Deus no meio do povo.
* Êxodo 35:35: "Encheu-os de sabedoria de coração, para que fizessem toda a obra do serviço do santuário, segundo tudo o que o Senhor tinha ordenado." Este versículo destaca a habilidade e a sabedoria que Deus deu a Bezalel e Ooliabe para construir o Tabernáculo de acordo com as instruções divinas.
* Salmos 84:1: "Quão amáveis são os teus tabernáculos, Senhor dos Exércitos!" Este versículo é um exemplo da admiração que os salmistas tinham pelo Tabernáculo como um lugar de adoração e da presença de Deus.
* Hebreus 9:11: "Mas, vindo Cristo como sumo sacerdote dos bens futuros, por um maior e mais perfeito tabernáculo, não feito por mãos, isto é, não desta criação." Este versículo fala do Tabernáculo como uma pré-figuração do próprio Cristo, o verdadeiro sumo sacerdote e o lugar de encontro com Deus.
* Apocalipse 21:3: "E ouvi uma grande voz do céu, que dizia: Eis aqui o tabernáculo de Deus com os homens, pois com eles habitará, e eles serão o seu povo, e o mesmo Deus estará com eles, e será o seu Deus." Este versículo fala do cumprimento da promessa do Tabernáculo, quando Deus habitará para sempre com o seu povo e será o seu Deus.
****

[[v2-36-1]]

^<<v2-36-1,1>>^ Beseleel, pois, e Ooliab, e todos os homens hábeis, a quem o Senhor deu habilidade e inteligência para saberem fazer com arte o que era necessário para o uso do santuário, executaram o que o Senhor tinha mandado.

[[v2-36-2]]

^<<v2-36-2,2>>^ Moisés tendo-os chamado, e igualmente todos os homens hábeis, a quem o Senhor tinha dado habilidade, e que espontaneamente se tinham oferecido para trabalhar nestas obras,

[[v2-36-3]]

^<<v2-36-3,3>>^ entregou-lhes todas as ofertas dos filhos de Israel. Enquanto eles se empregavam, diligentes, no trabalho, todos os dias pela manhã o povo oferecia donativos voluntários,

[[v2-36-4]]

^<<v2-36-4,4>>^ pelo que os artistas foram obrigados a ir

[[v2-36-5]]

^<<v2-36-5,5>>^ dizer a Moisés: O povo oferece mais do que é necessário.

[[v2-36-6]]

^<<v2-36-6,6>>^ Mandou, pois, Moisés que um pregoeiro gritasse: Nenhum homem, nem mulher, ofereça mais nada para a obra do santuário. Assim se deixou de oferecer donativos,

[[v2-36-7]]

^<<v2-36-7,7>>^ porque o que tinha sido oferecido bastava e superabundava.

[[v2-36-8]]

^<<v2-36-8,8>>^ Todos os homens hábeis se deram ao trabalho para concluirem a obra do tabernáculo, dez cortinas de linho fino retorcido, de púrpura violácea, escarlate é carmesim, com variedade de bondados e de cores.

[[v2-36-9]]

^<<v2-36-9,9>>^ Cada uma delas tinha vinte e oito côvados de comprido, quatro de largo; esta mesma era a medida de todas as cortinas.

[[v2-36-10]]

^<<v2-36-10,10>>^ (Beseleel) uniu cinco cortinas uma com outra, e uniu também as outras cinco entre si.

[[v2-36-11]]

^<<v2-36-11,11>>^ Fez também umas presilhas de púrpura violácea na ourela duma cortina de um e de outro lado, e o mesmo na ourela da outra cortina,

[[v2-36-12]]

^<<v2-36-12,12>>^ de modo que as presilhas correspondessem umas ás outras, e se unissem entre si.

[[v2-36-13]]

^<<v2-36-13,13>>^ Para isso fundiu cinquenta argolas, de ouro, em que se atassem as presilhas das cortinas, e assim se formasse um só tabernáculo.

[[v2-36-14]]

^<<v2-36-14,14>>^ Fez também onze cobertas de pêlos de cabra para cobrir o tecto do tabernáculo.

[[v2-36-15]]

^<<v2-36-15,15>>^ Uma destas cobertas tinha trinta côvados de comprido e quatro de largo: todas elas tinham a mesma medida.

[[v2-36-16]]

^<<v2-36-16,16>>^ Destas, uniu cinco de uma banda e seis da outra.

[[v2-36-17]]

^<<v2-36-17,17>>^ Fez cinquenta presilhas na ourela duma coberta, e cinquenta na ourela da outra, para que se pudessem unir entre si,

[[v2-36-18]]

^<<v2-36-18,18>>^ e de forma que de todas as cobertas se fizesse um todo.

[[v2-36-19]]

^<<v2-36-19,19>>^ Fez, além disto, a cobertura do tabernáculo de peles de carneiro tintas de vermelho, e sobre esta uma outra cobertura de peles de carneiro tintas de cor de jacinto.

[[v2-36-20]]

^<<v2-36-20,20>>^ Fez também de acácia as tábuas do tabernáculo para estarem ao alto.

[[v2-36-21]]

^<<v2-36-21,21>>^ O comprimento duma tábua era de dez côvados, e a largura de côvado e meio.

[[v2-36-22]]

^<<v2-36-22,22>>^ Em cada tábua havia dois encaixes, para que uma se encaixasse na outra. O mesmo foi feito em todas as tábuas do tabernáculo,

[[v2-36-23]]

^<<v2-36-23,23>>^ das quais vinte estavam na parte do meio-dia, que olha para o austro,

[[v2-36-24]]

^<<v2-36-24,24>>^ com quarenta bases de prata. Punham-se duas bases debaixo de uma tábua nas suas duas esquinas, onde terminam as ensambladuras dos lados.

[[v2-36-25]]

^<<v2-36-25,25>>^ Para a parte do tabernáculo que olha para o aquilão, fez vinte tábuas,

[[v2-36-26]]

^<<v2-36-26,26>>^ com quarenta bases de prata, duas bases para cada tábua.

[[v2-36-27]]

^<<v2-36-27,27>>^ Para o ocidente, isto é, para aquela parte do tabernáculo que olha para o mar, fez seis tábuas,

[[v2-36-28]]

^<<v2-36-28,28>>^ e outras duas para cada ângulo do tabernáculo, no fundo dele,

[[v2-36-29]]

^<<v2-36-29,29>>^ as quais estavam unidas entre si, debaixo até cima, e vinham a formar um só corpo. O mesmo fez nos ângulos dos dois lados,

[[v2-36-30]]

^<<v2-36-30,30>>^ de modo que ao todo fossem oito tábuas, e tivessem dezasseis bases de prata, isto é, duas bases debaixo de cada tábua

[[v2-36-31]]

^<<v2-36-31,31>>^ Fez também cinco barrotes de acácia, para ajustar as tábuas de um lado do tabernáculo;

[[v2-36-32]]

^<<v2-36-32,32>>^ outros cinco para ajustar as tábuas do outro lado; além destes, outros cinco barrotes ao lado ocidental do tabernáculo (voltado) para o mar.

[[v2-36-33]]

^<<v2-36-33,33>>^ Fez também outro barrote, que passava pelo meio das tábuas duma extremidade à outra extremidade.

[[v2-36-34]]

^<<v2-36-34,34>>^ E cobriu as mesmas tábuas de ouro, tendo fundido as suas bases de prata. Fez de ouro as suas argolas, por onde se pudessem meter os barrotes, e cobriu os mesmos barrotes com lâminas de ouro.

[[v2-36-35]]

^<<v2-36-35,35>>^ Fez mais um véu de púrpura violácea e escarlate e carmesim, e de linho fino retorcido, tecido com variedade de cores e com diversos recamos.

[[v2-36-36]]

^<<v2-36-36,36>>^ Para ele se fizeram quatro colunas de acácia, as quais os seus capitéis cobriu de ouro, sendo as suas bases de prata.

[[v2-36-37]]

^<<v2-36-37,37>>^ Fez também para a entrada do tabernáculo um véu de púrpura violácea e escarlate e carmesim, e de linho fino retorcido, com trabalhos de recamo.

[[v2-36-38]]

^<<v2-36-38,38>>^ Para ele se fizeram cinco colunas com seus capitéis, as quais cobriu de ouro, sendo as suas bases de bronze.

'''

xref:002-exodo/002-exodo-035.adoc#v2-35-0[&#60; Capítulo Anterior] | <<v2-36-0,Topo>> | xref:002-exodo/002-exodo-037.adoc#v2-37-0[Próximo Capítulo &#62;]