include::./index.adoc[]

[[v2-21-0]]
=== Êxodo, 21
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Êxodo 21 é um capítulo que apresenta diversas leis e regulamentações para a justiça e a convivência pacífica entre as pessoas. Entre os temas abordados estão a escravidão, a responsabilidade civil, a pena de morte e outras questões jurídicas relevantes. A partir disso, podemos encontrar os seguintes versículos relacionados:
* Provérbios 22:7: "O rico domina sobre os pobres, e o que toma emprestado é servo do que empresta." Esse versículo faz referência à questão da escravidão, que é abordada em Êxodo 21. Na época bíblica, a escravidão era uma prática comum, mas a Bíblia apresenta regulamentações para proteger os escravos e evitar abusos.
* Levítico 24:17: "E aquele que matar qualquer homem, certamente será morto." A pena de morte é um tema presente em Êxodo 21 e em outras partes da Bíblia. Esse versículo apresenta a determinação de que aquele que tirar a vida de outro ser humano deve ser punido com a morte.
* Deuteronômio 19:21: "Não terás piedade; vida por vida, olho por olho, dente por dente, mão por mão, pé por pé." Esse versículo apresenta o princípio da justiça retributiva, que é abordado em Êxodo 21. A ideia é que a punição deve ser proporcional ao crime cometido, e não deve haver excessos ou abusos.
* Romanos 13:1-4: "Toda alma esteja sujeita às autoridades superiores; porque não há autoridade que não venha de Deus; e as que existem foram ordenadas por Deus. Por isso, quem resiste à autoridade, resiste à ordenação de Deus; e os que resistem trarão sobre si mesmos condenação. Porque os magistrados não são para temor quando se faz o bem, mas quando se faz o mal. Queres tu, pois, não temer a autoridade? Faze o bem, e terás louvor dela." Esse trecho do Novo Testamento apresenta a ideia de que as autoridades civis são instituídas por Deus para manter a ordem e a justiça na sociedade. Esse princípio está em sintonia com as regulamentações apresentadas em Êxodo 21.
* Lucas 6:31: "E como vós quereis que os homens vos façam, da mesma maneira fazei-lhes vós também." Esse versículo apresenta o princípio da empatia e do respeito ao próximo, que é um dos fundamentos da lei apresentada em Êxodo 21. A ideia é tratar os outros com justiça e compaixão, assim como gostaríamos de ser tratados.
****

[[v2-21-1]]

^<<v2-21-1,1>>^ Estas são as leis que lhes darás:

[[v2-21-2]]

^<<v2-21-2,2>>^ Se comprares um escravo hebreu, de te servirá seis anos; ao sétimo, sairá forro, sem pagar nada. (ver nota)

[[v2-21-3]]

^<<v2-21-3,3>>^ Se entrou só, sairá só; se tiver mulher, também a mulher sairá juntamente com ele.

[[v2-21-4]]

^<<v2-21-4,4>>^ Mas, se o senhor lhe tiver dado mulher, e ela tiver dado a luz filhos e filhas, a mulher e os seus filhos serão do seu senhor, e ele sairá só.

[[v2-21-5]]

^<<v2-21-5,5>>^ Porém, se o escravo disser: "Eu tenho amor ao meu senhor, à minha mulher e aos meus filhos, não quero sair forro,"

[[v2-21-6]]

^<<v2-21-6,6>>^ então o senhor o fará comparecer diante de Deus, e o fará encostar à porta e às ombreiras, e lhe furará a orelha com uma sovela; e ele ficará seu escravo para sempre. (ver nota)

[[v2-21-7]]

^<<v2-21-7,7>>^ Se algum vender sua filha para ser serva, esta não sairá como costumam sair as escravas.

[[v2-21-8]]

^<<v2-21-8,8>>^ Se ela desagradar aos olhos de seu Senhor, a quem tinha sido entregue, despedi-la-á; porém não terá direito de a vender a um povo estrangeiro, se a rejeitar.

[[v2-21-9]]

^<<v2-21-9,9>>^ Se, porém, a casar com seu filho, tratá-la-á como de ordinário se tratam as filhas.

[[v2-21-10]]

^<<v2-21-10,10>>^ Mas, se ele dá outra esposa a seu filho, nada tirará à primeira do alimento, vestuário e direito conjugal.

[[v2-21-11]]

^<<v2-21-11,11>>^ Se ele não fizer estas três coisas, ela sairá (livre) gratuitamente, sem pagar o resgate.

[[v2-21-12]]

^<<v2-21-12,12>>^ O que ferir um homem, querendo matá-lo, seja punido de morte

[[v2-21-13]]

^<<v2-21-13,13>>^ Aquele, porém, que não armou ciladas, mas (foi) Deus (quem) lho entregou nas suas mãos, eu te designarei um lugar no qual se deva refugiar. (ver nota)

[[v2-21-14]]

^<<v2-21-14,14>>^ Se alguém matar o seu próximo de caso pensado e a traição, tu o arrancarás mesmo do meu altar para que morra.

[[v2-21-15]]

^<<v2-21-15,15>>^ O que feri seu pai ou sua mãe, seja punido de morte.

[[v2-21-16]]

^<<v2-21-16,16>>^ Aquele tiver roubado um homem, e o tiver vendido ou o retiver em seu poder, seja morto.

[[v2-21-17]]

^<<v2-21-17,17>>^ O que amaldiçoar seu pai ou sua mãe, seja punido de morte,

[[v2-21-18]]

^<<v2-21-18,18>>^ Se alguns homens se travarem de razões, e um ferir o seu próximo com uma pedra ou com o punho, e ele não morrer, mas for para o leito,

[[v2-21-19]]

^<<v2-21-19,19>>^ se ele (depois) se levantar e andar por fora encostado ao seu bordão, será (declarado) inocente o que o feriu, com a condição, porém, de que o compense do seu trabalho (interrompido) e das despesas feitas com o tratamento.

[[v2-21-20]]

^<<v2-21-20,20>>^ O que ferir o seu escravo ou a sua escrava com uma vara, e eles morrerem nas suas mãos, será réu de crime.

[[v2-21-21]]

^<<v2-21-21,21>>^ Mas, se o escravo sobreviver um dia ou dois, não ficará sujeito à pena, porque é propriedade sua. (ver nota)

[[v2-21-22]]

^<<v2-21-22,22>>^ Se alguns homens renhirem, e um deles ferir uma mulher grávida e for causa de que aborte, mas ficando ela com vida, será obrigado a resarcír o dano segundo o que pedir o marido, e os árbitros julgarem.

[[v2-21-23]]

^<<v2-21-23,23>>^ Se, porém, se seguiu a morte dela, dará vida por vida.

[[v2-21-24]]

^<<v2-21-24,24>>^ Olho por olho, dente por dente, mão por mão, pé por pé, (ver nota)

[[v2-21-25]]

^<<v2-21-25,25>>^ queimadura por queimadura, ferida por ferida, pisadura por pisadura.

[[v2-21-26]]

^<<v2-21-26,26>>^ Se alguém ferir o olho do seu escravo ou da sua escrava, e os deixar cegos (de um dos olhos), deixá-los-á ir livres pelo olho que lhes tirou.

[[v2-21-27]]

^<<v2-21-27,27>>^ Se também fizer cair um dente ao escravo ou à escrava, do mesmo modo os deixará ir livres.

[[v2-21-28]]

^<<v2-21-28,28>>^ Se um boi ferir com as pontas um homem ou uma mulher, e daí resultar a morte, será apedrejado, e não se comerão as suas carnes: mas o dono do boi será (declarado) inocente.

[[v2-21-29]]

^<<v2-21-29,29>>^ Todavia se o boi já marrava há algum tempo e o dono foi avisado, e não o guardou, no caso de matar um homem ou uma mulher, o boi será apedrejado e o seu dono será morto.

[[v2-21-30]]

^<<v2-21-30,30>>^ Porém, se se lhe impuser uma multa pelo resgate da sua vida, dará tudo o que lhe for exigido.

[[v2-21-31]]

^<<v2-21-31,31>>^ Se o boi ferir com as pontas um rapaz ou uma rapariga, o dono estará sujeito à mesma sentença.

[[v2-21-32]]

^<<v2-21-32,32>>^ Se acometer um escravo ou uma escrava, pagará ao dono trinta siclos de prata, e o boi será apedrejado.

[[v2-21-33]]

^<<v2-21-33,33>>^ Se alguém abrir uma cisterna, ou a cavar e não a cobrir, e nela cair um boi ou um jumento,

[[v2-21-34]]

^<<v2-21-34,34>>^ o dono da cisterna pagará o valor dos animais, mas o animal morto será seu.

[[v2-21-35]]

^<<v2-21-35,35>>^ Se o boi de um homem ferir o boi de outro, e este morrer, venderão o boi vivo e, entre ambos, repartirão o seu valor, assim como dividirão entre si o boi morto.

[[v2-21-36]]

^<<v2-21-36,36>>^ Se, porém, o dono sabia que o boi marrava já há algum tempo, e não o guardou, pagará boi por boi, e receberá inteiro o boi morto.

'''

xref:002-exodo/002-exodo-020.adoc#v2-20-0[&#60; Capítulo Anterior] | <<v2-21-0,Topo>> | xref:002-exodo/002-exodo-022.adoc#v2-22-0[Próximo Capítulo &#62;]