include::./index.adoc[]

[[v2-29-0]]
=== Êxodo, 29
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Êxodo 29 trata da consagração dos sacerdotes levitas, onde Moisés recebe instruções detalhadas de Deus sobre como deve ser feita a cerimônia. Os sacerdotes deveriam ser lavados, vestidos com roupas sagradas e ungidos com óleo. A cerimônia de consagração era importante para que os sacerdotes estivessem em condições de servir a Deus e oferecer sacrifícios no tabernáculo. Abaixo seguem cinco versículos relacionados com os temas abordados em Êxodo 29:
* Levítico 8:6: "Então Moisés apresentou Arão e seus filhos e os lavou com água." Este versículo descreve um momento importante na cerimônia de consagração, quando Moisés lava Arão e seus filhos antes de vesti-los com as roupas sagradas.
* Levítico 8:12: "Derramou também do óleo da unção sobre a cabeça de Arão e o ungiu para santificá-lo." Aqui, vemos a importância da unção com óleo durante a consagração dos sacerdotes. Esse gesto simbolizava a separação e a santificação dos sacerdotes para o serviço a Deus.
* Levítico 8:30: "Tomou também Moisés do óleo da unção e do sangue que estava sobre o altar, e o espargiu sobre Arão e sobre suas vestes, como também sobre seus filhos e sobre as vestes deles; assim santificou a Arão, suas vestes, seus filhos e as vestes deles." Este versículo descreve como Moisés ungiu Arão e seus filhos com óleo e sangue do altar, seguindo as instruções de Deus para consagrá-los como sacerdotes.
* Levítico 8:33: "Não saireis da porta da tenda da congregação por sete dias, até ao dia em que se cumprirem os dias da vossa consagração; porquanto por sete dias sereis consagrados." Este versículo enfatiza a importância da cerimônia de consagração e da separação dos sacerdotes por um período de sete dias, antes que eles possam começar a exercer suas funções no tabernáculo.
* Números 18:7: "Mas a ti e a teus filhos contigo guardareis o vosso sacerdócio em tudo o que se relaciona com o altar e com o que está detrás do véu; e servireis. Dar-vos-ei, pois, o vosso sacerdócio por dádiva; e o estranho que se aproximar morrerá." Este versículo destaca a exclusividade do sacerdócio levita e como apenas aqueles que foram consagrados para esse serviço podem exercê-lo. Isso era uma questão séria, e qualquer um que tentasse se aproximar do altar sem autorização poderia ser morto.
****

[[v2-29-1]]

^<<v2-29-1,1>>^ Eis o que farás também para que me sejam consagrados no sacerdócio. Toma um novilho da manada, dois carneiros sem mancha,

[[v2-29-2]]

^<<v2-29-2,2>>^ pães ázimos e uma torta sem fermento, que seja amassada com azeite, e filhós ázimas, untadas com azeite, tudo isto de flor de farinha de trigo.

[[v2-29-3]]

^<<v2-29-3,3>>^ Depois de as teres posto num cesto, as oferecerás; (oferecerás ao mesmo tempo) o novilho e os dois carneiros.

[[v2-29-4]]

^<<v2-29-4,4>>^ Farás aproximar Aarão e seus filhos da porta do tabernáculo do testemunho. Depois que tiveres lavado com água o pai e os seus filhos,

[[v2-29-5]]

^<<v2-29-5,5>>^ revestirás Aarão com as suas veste, isto é, com a túnica de linho, com o manto, com o éfode e com o peitoral que apertarás com o cíngulo.

[[v2-29-6]]

^<<v2-29-6,6>>^ Pôr-lhe-ás a tiara na cabeça, e sobre a tiara a lâmina santa.

[[v2-29-7]]

^<<v2-29-7,7>>^ Derramarás sobre a sua cabeça o óleo da unção, e com este rito será consagrado.

[[v2-29-8]]

^<<v2-29-8,8>>^ Farás também aproximar seus filhos, revesti-los-ás com túnicas de linho, e cingi-los-ás com o cíngulo.

[[v2-29-9]]

^<<v2-29-9,9>>^ Assim farás a Aarão e aos seus filhos, e lhes porás as mitras. Serão meus sacerdotes para um culto perpétuo. Depois que tiveres sagrado as suas mãos,

[[v2-29-10]]

^<<v2-29-10,10>>^ farás aproximar também o novilho diante do tabernáculo do testemunho, sobre cuja cabeça Aarão e seus filhos imporão as mãos.

[[v2-29-11]]

^<<v2-29-11,11>>^ Tu o degolarás na presença do Senhor, junto da porta do tabernáculo do testemunho.

[[v2-29-12]]

^<<v2-29-12,12>>^ Tendo tomado do sangue do novilho, o porás com o teu dedo sobre as pontas do altar, e o resto do sangue derramá-lo-ás ao pé dele.

[[v2-29-13]]

^<<v2-29-13,13>>^ Tomarás também toda a gordura que cobre as entranhas, o redanho do fígado, os dois rins e a gordura que está por cima deles, e oferecerás (tudo isto) queimando-o sobre o altar:

[[v2-29-14]]

^<<v2-29-14,14>>^ as carnes do novilho, o seu couro e os excrementos, queimá-los-ás fora do acampamento, por ser (uma hóstia) pelo pecado.

[[v2-29-15]]

^<<v2-29-15,15>>^ Tomarás também um carneiro, sobre a cabeça do qual Aarão e seus filhos porão as mãos.

[[v2-29-16]]

^<<v2-29-16,16>>^ Depois de o teres degolado, tomarás do seu sangue e derramá-lo-ás em torno do altar.

[[v2-29-17]]

^<<v2-29-17,17>>^ Depois cortarás o mesmo carneiro em pedaços, e, lavados os intestinos e os pés, os porás sobre as carnes despedaçadas e sobre a sua cabeça,

[[v2-29-18]]

^<<v2-29-18,18>>^ e oferecerás todo o carneiro, queimando-o sobre o altar. É uma oblação ao Senhor, de suave odor, é um sacrifício pelo fogo ao Senhor.

[[v2-29-19]]

^<<v2-29-19,19>>^ Tomarás ainda outro carneiro, sobre cuja cabeça Aarão e seus filhos porão as mãos.

[[v2-29-20]]

^<<v2-29-20,20>>^ Depois de o teres imolado, tomarás do seu sangue e pô-lo-ás na extremidade da orelha direita de Aarão e de seus filhos, e sobre os dedos polegares da sua mão direita e do seu pé direito, e derramarás o sangue ao redor do altar. (ver nota)

[[v2-29-21]]

^<<v2-29-21,21>>^ Tendo tomado do sangue que está sobre o altar, e do óleo da unção, aspergirás (com ele) Aarão e suas vestes, seus filhos e suas vestes. Depois de os teres sagrado e às suas vestes,

[[v2-29-22]]

^<<v2-29-22,22>>^ tomarás a gordura do carneiro e a cauda, a gordura que cobre as entranhas, o redanho do fígado, os dois rins, e a gordura que está em cima deles, e a espádua direita, porque este é o carneiro da sagração;

[[v2-29-23]]

^<<v2-29-23,23>>^ (tomarás) do cesto dos ázimos, que está diante do Senhor, um bolo de pão, uma torta amassada em azeite e uma filhó;

[[v2-29-24]]

^<<v2-29-24,24>>^ porás todas estas coisas sobre as mãos de Aarão e de seus filhos, e agitá-la-ás, elevando-as diante do Senhor.

[[v2-29-25]]

^<<v2-29-25,25>>^ Depois receberás todas estas coisas das suas mãos, e queimá-las-ás sobre o altar em holocausto, para cheiro suavíssimo diante do Senhor, porque é a sua oblação.

[[v2-29-26]]

^<<v2-29-26,26>>^ Tomarás também o peito do carneiro imolado para a sagração de Aarão, e agitá-lo-ás, elevando-o diante do Senhor: esta será a tua parte.

[[v2-29-27]]

^<<v2-29-27,27>>^ Santificarás também o peito consagrado e a espádua que separaste do carneiro.

[[v2-29-28]]

^<<v2-29-28,28>>^ imolado para a sagração de Aarão e de seus filhos: estas serão as porções de Aarão e de seus filhos por um direito perpétuo entre os filhos de Israel, porque são as primícias e as primeiras partes das vitimas pacíficas, que eles oferecem ao Senhor.

[[v2-29-29]]

^<<v2-29-29,29>>^ As vestes santas de que Aarão usar, tê-las-ão seus filhos depois dele, para que, vestidos com elas, sejam ungidos, e as suas mãos sejam consagradas.

[[v2-29-30]]

^<<v2-29-30,30>>^ Durante sete dias usará delas aquele de seus filhos que for constituído pontífice em seu lugar, e que entrar no tabernáculo do testemunho para ministrar no santuário.

[[v2-29-31]]

^<<v2-29-31,31>>^ Tomarás o carneiro da sagração, e cozerás as suas carnes no lugar santo;

[[v2-29-32]]

^<<v2-29-32,32>>^ Aarão e seus filhos as comerão. Comerão também à entrada do tabernáculo do testemunho os pães que estão no cesto,

[[v2-29-33]]

^<<v2-29-33,33>>^ para que seja um sacrifício propiciatório, e sejam sacrificadas as mãos dos oferentes. O estrangeiro não comerá deles, porque são coisas santas.

[[v2-29-34]]

^<<v2-29-34,34>>^ Porém, se sobrar das carnes consagradas, ou dos pães até pela manhã, queimarás no fogo o que restar: não se comerão (estas coisas), porque estão santificadas.

[[v2-29-35]]

^<<v2-29-35,35>>^ Farás tudo isto que te mandei relativo a Aarão e a seus filhos. Sagrarás as suas mãos, durante sete dias,

[[v2-29-36]]

^<<v2-29-36,36>>^ e oferecerás cada dia um novilho em expiação pelo pecado. Depois que tiveres imolado a hóstia da expiação, purificarás o altar e o ungirás para o santificar.

[[v2-29-37]]

^<<v2-29-37,37>>^ Durante sete dias purificarás o altar e o santificarás, e ele será santíssimo; todo o que o tocar será santificado.

[[v2-29-38]]

^<<v2-29-38,38>>^ Eis o que sacrificarás sobre o altar: Dois cordeiros de um ano todos os dias, perpetuamente,

[[v2-29-39]]

^<<v2-29-39,39>>^ um cordeiro de manhã e outro de tarde.

[[v2-29-40]]

^<<v2-29-40,40>>^ Com o primeiro cordeiro (oferecerás) uma décima parte (do eti) de flor de farinha amassada com uma quarta parte do hin de azeite de azeitonas pisadas, e uma libação de um quarto de hin de vinho.

[[v2-29-41]]

^<<v2-29-41,41>>^ Oferecerás de tarde o outro cordeiro com a mesma oblação e libação da manhã, em odor de suavidade.

[[v2-29-42]]

^<<v2-29-42,42>>^ Este é um sacrifício, que com um culto perpétuo por todas as vossas gerações se deve oferecer ao Senhor à entrada do tabernáculo do testemunho diante do Senhor, onde eu me encontrei para te falar,

[[v2-29-43]]

^<<v2-29-43,43>>^ De lá darei eu as minhas ordens aos filhos de Israel, e o altar será santificado com a minha glória. (ver nota)

[[v2-29-44]]

^<<v2-29-44,44>>^ Santificarei também o tabernáculo do testemunho e o altar, e Aarão com seus filhos, para que exerçam o meu sacerdócio.

[[v2-29-45]]

^<<v2-29-45,45>>^ Habitarei no meio dos filhos de Israel, serei o seu Deus,

[[v2-29-46]]

^<<v2-29-46,46>>^ e saberão que eu sou o Senhor seu Deus que os tirei da terra do Egipto para habitar entre eles, eu o Senhor seu Deus.

'''

xref:002-exodo/002-exodo-028.adoc#v2-28-0[&#60; Capítulo Anterior] | <<v2-29-0,Topo>> | xref:002-exodo/002-exodo-030.adoc#v2-30-0[Próximo Capítulo &#62;]