include::./index.adoc[]

[[v2-8-0]]
=== Êxodo, 8
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Êxodo 8 narra a continuação das pragas enviadas por Deus ao Egito para que Faraó liberte o povo de Israel. Neste capítulo, Moisés e Arão apresentam a Faraó a praga dos sapos, e diante da sua recusa em libertar o povo, Deus envia uma grande quantidade de mosquitos para a terra. Os versículos escolhidos são:
* Salmos 78:45-46: "Ele enviou enxames de mosquitos que os devoraram, e rãs que os arruinaram. Ele entregou as suas colheitas ao gafanhoto, e o fruto do seu trabalho aos gafanhotos famintos." Este salmo faz referência às pragas enviadas por Deus ao Egito e mostra como as colheitas foram destruídas pelas pragas.
* Êxodo 8:10: "Disse Faraó: Amanhã". Moisés respondeu: "Conforme a tua palavra, para que saibas que não há ninguém como o Senhor, nosso Deus." Moisés reafirma a autoridade de Deus sobre Faraó e a sua capacidade de controlar as pragas.
* Mateus 12:39-40: "Ele respondeu: Uma geração má e adúltera pede um sinal! Mas nenhum sinal lhe será dado, a não ser o sinal do profeta Jonas. Pois assim como Jonas esteve três dias e três noites no ventre de um grande peixe, assim o Filho do homem estará três dias e três noites no coração da terra." Neste versículo, Jesus faz uma referência ao profeta Jonas e ao seu papel como sinal para o povo de Israel.
* Isaías 51:9-11: "Desperta, desperta, veste-te de força, ó braço do Senhor; desperta, como nos dias passados, como nas gerações antigas. Não és tu aquele que cortou em pedaços o Egito, que feriu o dragão? Não és tu aquele que secou o mar, as águas do grande abismo, que fez do fundo do mar um caminho, para que passassem os remidos? Os que o Senhor resgatou voltarão, entrarão em Sião com cânticos de júbilo; alegria eterna coroará as suas cabeças; o regozijo e a alegria os alcançarão, e deles fugirá a tristeza e o gemido." Este versículo destaca a soberania de Deus e a sua capacidade de libertar o seu povo.
* João 2:18-21: "Então os judeus perguntaram: Que sinal nos mostras para fazeres estas coisas? Jesus respondeu: Destruí este santuário, e em três dias o levantarei de novo. Disseram os judeus: Este templo foi construído em quarenta e seis anos, e tu o levantarás em três dias? Mas o santuário de que ele falava era o seu próprio corpo." Este versículo faz uma referência à ressurreição de Jesus e mostra como Deus tem o poder de levantar o que foi destruído.
****

[[v2-8-1]]

^<<v2-8-1,1>>^ O Senhor disse novamente a Moisés: Vai ter com Faraó e lhe dirás: Estas coisas diz o Senhor: Deixa ir o meu povo, para que me ofereça sacrifícios.

[[v2-8-2]]

^<<v2-8-2,2>>^ Se, porém, o não quiseres deixar ir, flagelarei com rãs todo o teu país.

[[v2-8-3]]

^<<v2-8-3,3>>^ No rio fervilharão rãs, e elas subirão e entrarão em tua casa, na câmara onde dormes, sobre o teu leito, nas casas dos teus servos, no meio do teu povo, nos teus fornos e nos sobejos dos teus alimentos;

[[v2-8-4]]

^<<v2-8-4,4>>^ e as rãs irão sobre ti, sobre o teu povo e sobre todos os teus servos.

[[v2-8-5]]

^<<v2-8-5,5>>^ O Senhor disse a Moisés: Dize a Aarão: Estende a tua mão sobre os rios, ribeiras e lagoas, e faze sair rãs sobre a terra do Egipto.

[[v2-8-6]]

^<<v2-8-6,6>>^ Aarão estendeu a sua mão sobre as águas do Egipto, e as rãs sairam e cobriram a terra do Egipto.

[[v2-8-7]]

^<<v2-8-7,7>>^ Os magos, porém, fizeram coisa semelhante, por meio dos seus encantamentos, e fizeram sair rãs sobre a terra do Egipto. (ver nota)

[[v2-8-8]]

^<<v2-8-8,8>>^ Faraó chamou Moisés e Aarão, e disse-lhes: Rogai ao Senhor que afaste as rãs de mim e do meu povo, e eu deixarei ir o povo para que ofereça sacrifícios ao Senhor.

[[v2-8-9]]

^<<v2-8-9,9>>^ Moisés disse a Faraó: Determina-me quando deverei rogar por ti, pelos teus servos e pelo teu povo, a fim de que as rãs sejam afastadas de ti, da tua casa, dos teus servos e do teu povo, e somente fiquem no rio.

[[v2-8-10]]

^<<v2-8-10,10>>^ Ele respondeu: Amanhã. Moisés disse: Farei segundo a tua palavra, para que saibas que não há quem seja como o Senhor nosso Deus.

[[v2-8-11]]

^<<v2-8-11,11>>^ As rãs afastar-se-ão de ti, da tua casa, dos teus servos e do teu povo, e sòmente ficarão no rio.

[[v2-8-12]]

^<<v2-8-12,12>>^ Moisés e Aarão saíram da presença de Faraó, e Moisés clamou ao Senhor pelo cumprimento da promessa que tinha feito a Faraó relativamente às rãs.

[[v2-8-13]]

^<<v2-8-13,13>>^ O Senhor fez conforme a palavra de Moisés, e morreram as rãs das casas, das granjas e dos campos.

[[v2-8-14]]

^<<v2-8-14,14>>^ Juntaram-nas em imensos montões, e a terra ficou infeccionada.

[[v2-8-15]]

^<<v2-8-15,15>>^ Mas Faraó, vendo que lhe era dado alívio, endureceu o seu coração e não os ouviu, como o Senhor tinha mandado.

[[v2-8-16]]

^<<v2-8-16,16>>^ O Senhor disse a Moisés: Dize a Aarão: Estende a tua vara, fere o pó da terra, e haja mosquitos em toda a terra do Egipto.

[[v2-8-17]]

^<<v2-8-17,17>>^ Eles fizeram assim. Aarão, pegando na vara, estendeu a mão, feriu o pó da terra, e os mosquitos caíram sobro os homens e sobre os animais; todo o pó da terra se converteu em mosquitos por toda a terra do Egipto.

[[v2-8-18]]

^<<v2-8-18,18>>^ Os magos fizeram dum modo semelhante com os seus encantamentos para produzir mosquitos, e não puderam. Os mosquitos existiam, tanto sobre os homens, como sobre os animais.

[[v2-8-19]]

^<<v2-8-19,19>>^ Então os magos disseram a Faraó: O dedo de Deus está aqui. Porém o coração de Faraó endureceu-se, e não os ouviu, como o Senhor tinha anunciado.

[[v2-8-20]]

^<<v2-8-20,20>>^ O Senhor disse outra vez a Moisés; Levanta-te de madrugada, e apresenta-te a Faraó, quando ele sair para ir junto da água, e dize-lhe: Assim fala o Senhor: Deixa ir o meu povo, a fim de que me ofereça sacrifícios,

[[v2-8-21]]

^<<v2-8-21,21>>^ Por que, se o não deixares ir, eu mandarei contra ti, contra os teus servos, contra o teu povo, contra as tuas casas, todo o gênero de moscas: e as casas dos Egipcios e toda a terra que habitam, serão cheias de moscas de vários gêneros.

[[v2-8-22]]

^<<v2-8-22,22>>^ Contudo eu, nesse dia, distinguirei a terra de Gessen, onde habita o meu povo, de modo que não haja aí moscas, a fim de que saibas que eu, o Senhor, estou no meio desta terra.

[[v2-8-23]]

^<<v2-8-23,23>>^ Estabelecerei (assim) uma distinção entre o meu povo e o teu povo: amanhã terá lugar este sinal.

[[v2-8-24]]

^<<v2-8-24,24>>^ E o Senhor assim fez. Vieram moscas molestíssimas sobre as casas de Faraó e dos seus servos, e sobre toda a terra do Egipto; e a terra foi devastada por tais moscas.

[[v2-8-25]]

^<<v2-8-25,25>>^ Faraó chamou Moisés e Aarão, e disse-lhes; Ide, e sacrificai ao vosso Deus nesta terra.

[[v2-8-26]]

^<<v2-8-26,26>>^ Moisés respondeu: Não se pode fazer assim, porque sacrificaremos ao Senhor nosso Deus coisas que para os Egípcios é sacrilégio matar; se nós, diante dos Egípcios matarmos o que eles adoram, nos apedrejarão.

[[v2-8-27]]

^<<v2-8-27,27>>^ Andaremos três dias de viagem no deserto, e sacríficaremos ao Senhor nosso Deus, como ele nos ordenou.

[[v2-8-28]]

^<<v2-8-28,28>>^ Faraó disse: Eu vos deixarei ir para que sacrifiqueis ao Senhor vosso Deus no deserto, mas não vos afasteis muito, e rogai por mim.

[[v2-8-29]]

^<<v2-8-29,29>>^ Moisés disse: Logo que eu tiver saído da tua presença, rogarei ao Senhor, e amanhã as moscas se afastarão de Faraó, dos seus servos e do seu povo: mas não queiras mais enganar-me, não deixando sair o povo a fazer sacrifícios ao Senhor.

[[v2-8-30]]

^<<v2-8-30,30>>^ Tendo Moisés saído da presença de Faraó, orou ao Senhor.

[[v2-8-31]]

^<<v2-8-31,31>>^ Ele fez o que Moisés lhe tinha pedido e tirou as moscas de Faraó, dos seus servos, e do seu povo: não ficou uma só.

[[v2-8-32]]

^<<v2-8-32,32>>^ Porém o coração de Faraó endureceu-se de tal sorte, que nem ainda desta vez deixou ir o povo.

'''

xref:002-exodo/002-exodo-007.adoc#v2-7-0[&#60; Capítulo Anterior] | <<v2-8-0,Topo>> | xref:002-exodo/002-exodo-009.adoc#v2-9-0[Próximo Capítulo &#62;]