include::./index.adoc[]

[[v2-9-0]]
=== Êxodo, 9
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Em Êxodo 9, Deus continua a enviar pragas sobre o Egito como forma de mostrar seu poder e forçar o faraó a libertar o povo de Israel. As pragas incluem a morte do gado, úlceras nos animais e nos humanos, granizo e gafanhotos.
* Jó 37:13: "Ele os faz cair, quer para disciplina, quer para demonstrar o seu amor misericordioso." Esse versículo fala sobre como Deus usa eventos naturais para disciplinar ou mostrar misericórdia aos seres humanos, o que pode ser aplicado à envio de pragas para o Egito em Êxodo 9.
* Isaías 45:7: "Eu formo a luz e crio as trevas, promovo a paz e causo a desgraça; eu, o Senhor, faço todas essas coisas." Este versículo fala sobre como Deus tem controle absoluto sobre tudo o que acontece na terra, incluindo a capacidade de enviar pragas e desgraças.
* Jeremias 5:12: "Eles negam ao Senhor, dizendo: ‘Ele não existe! Não acontecerá nada de mal. Não veremos espada nem fome.’" Este versículo pode ser aplicado à atitude do faraó em Êxodo 9, que se recusou a ouvir os avisos de Deus e sofreu as consequências das pragas.
* Deuteronômio 7:15: "O Senhor removerá de você todas as doenças. Ele não permitirá que você sofra nenhuma das doenças terríveis que você conheceu no Egito; mas as imporá a todos os que os odeiam." Este versículo fala sobre como Deus pode curar e proteger os seus seguidores de doenças e pragas, enquanto as impõe aos seus inimigos.
* Salmos 105:27-28: "Eles executaram seus sinais miraculosos entre eles, suas maravilhas na terra de Cam. Ele enviou trevas que os envolveram, e a escuridão os cobriu." Este versículo fala sobre os sinais e maravilhas que Deus realizou no Egito, incluindo a praga das trevas em Êxodo 9.
****

[[v2-9-1]]

^<<v2-9-1,1>>^ O Senhor disse a Moisés: Vai ter com Faraó e dize-lhe: Assim fala o Senhor Deus dos Hebreus: Deixa ir o meu povo para que me ofereça sacrifícios,

[[v2-9-2]]

^<<v2-9-2,2>>^ porque, se ainda recusas e o reténs,

[[v2-9-3]]

^<<v2-9-3,3>>^ a minha mão será sobre (o gado dos) teus campos e (virá) uma pestilência gravíssima sobre os cavalos, jumentos, camelos, bois e ovelhas.

[[v2-9-4]]

^<<v2-9-4,4>>^ O Senhor fará a maravilha de separar o que pertence aos filhos de Israel do que pertence aos Egípcios, de sorte que não pereça absolutamente nada da que pertence aos filhos de Israel.

[[v2-9-5]]

^<<v2-9-5,5>>^ E o Senhor determinou o tempo, dizendo: Amanhã cumprirá o Senhor esta palavra no país.

[[v2-9-6]]

^<<v2-9-6,6>>^ Ao outro dia, pois, fez o Senhor o que tinha dito, e todos os animais dos Egípcios morreram; dos animais dos filhos de Israel não morreu nenhum.

[[v2-9-7]]

^<<v2-9-7,7>>^ Faraó mandou ver, e nada estava morto do que possuía Israel. O coração de Faraó, porém, endureceu-se, e não deixou ir o povo.

[[v2-9-8]]

^<<v2-9-8,8>>^ O Senhor disse a Moisés e a Aarão: Tomai mãos cheias de cinza dum forno, e Moisés a lance ao ar diante de Faraó,

[[v2-9-9]]

^<<v2-9-9,9>>^ para que se converta num pó fino, sobre toda a terra do Egipto, donde resultarão nos homens e nos animais úlceras e tumores, por toda essa terra.

[[v2-9-10]]

^<<v2-9-10,10>>^ Tomaram cinza dum forno, e apresentaram-se a Faraó. Moisés lançou-a ao ar, e formaram-se úlceras e tumores nos homens e nos animais.

[[v2-9-11]]

^<<v2-9-11,11>>^ Os magos não podiam ter-se de pé diante de Moisés, por causa das úlceras, que estavam sobre eles, como sobre todos os Egípcios. (ver nota)

[[v2-9-12]]

^<<v2-9-12,12>>^ O Senhor endureceu o coração de Faraó, que não os ouviu, como o Senhor tinha dito a Moisés.

[[v2-9-13]]

^<<v2-9-13,13>>^ O Senhor disse a Moisés: Levanta-te de manhã cedo, apresenta-te a Faraó e dize-lhe: Assim fala o Senhor Deus dos Hebreus: Deixa ir o meu povo para que me ofereça sacrifícios,

[[v2-9-14]]

^<<v2-9-14,14>>^ porque desta vez mandarei todas as minhas pragas sobre o teu coração, sobre os teus servos, sobre o teu povo, para que saibas que não há quem seja semelhante a mim em toda a terra.

[[v2-9-15]]

^<<v2-9-15,15>>^ Se eu tivesse estendido a minha mão e te tivesse ferido de peste a ti e ao teu povo, haveríeis já desaparecido da terra.

[[v2-9-16]]

^<<v2-9-16,16>>^ Porém conservei-te com vida, para mostrar em ti o meu poder e para que o meu nome seja celebrado em toda a terra.

[[v2-9-17]]

^<<v2-9-17,17>>^ Ainda reténs o meu povo, e o não queres deixar ir?

[[v2-9-18]]

^<<v2-9-18,18>>^ Pois fica sabendo que amanhã, a esta mesma hora, farei chover granizo abundantíssimo, qual se não viu nunca no Egipto, desde o dia em que foi fundado até ao presente.

[[v2-9-19]]

^<<v2-9-19,19>>^ Manda, portanto, imediatamente juntar os teus animais e tudo o que tens no campo, porque os homens e os animais que se acharem fora, que não estiverem recolhidos, cairá sobre eles o granizo, e morrerão. (ver nota)

[[v2-9-20]]

^<<v2-9-20,20>>^ Aqueles dos servos de Faraó, que temeram a palavra do Senhor, fizeram retirar os seus servas e os seus animais para as casas.

[[v2-9-21]]

^<<v2-9-21,21>>^ Aqueles porém, que desprezaram a palavra do Senhor, deixaram ficar os seus servos e os seus animais nos campos.

[[v2-9-22]]

^<<v2-9-22,22>>^ O Senhor disse a Moisés; Estende a tua mão para o céu, a fim de que chova granizo em toda a terra do Egipto sobre os homens, sobre os animais e sobre toda a verdura do campo, na terra do Egipto.

[[v2-9-23]]

^<<v2-9-23,23>>^ Moisés estendeu a vara para o céu, e o Senhor despediu trovões, granizo e raios, que se precipitavam sobre a terra. O Senhor fez cair granizo sobre a terra do Egipto,

[[v2-9-24]]

^<<v2-9-24,24>>^ e, misturado com ele, caiu fogo; o granizo foi de tal grandeza, que nunca antes se viu igual em toda a terra do Egipto, desde que aquela nação foi fundada.

[[v2-9-25]]

^<<v2-9-25,25>>^ O granizo feriu em toda a terra do Egipto tudo o que estava nos campos, desde os homens até aos animais, feriu toda a erva do campo e destroçou todas as árvores do país.

[[v2-9-26]]

^<<v2-9-26,26>>^ Só na terra de Gessen, onde estavam os filhos de Israel, não caiu granizo.

[[v2-9-27]]

^<<v2-9-27,27>>^ Faraó mandou chamar Moisés e Aarão e disse-lhes: Eu pequei ainda desta vez; o Senhor é justo; eu e o meu povo somos ímpios.

[[v2-9-28]]

^<<v2-9-28,28>>^ Rogai ao Senhor para que cessem os trovões de Deus e o granizo, a fim de que eu vos deixe ir, e não permaneçais mais aqui.

[[v2-9-29]]

^<<v2-9-29,29>>^ Moisés disse: Depois que eu tiver saído da cidade, estenderei as minhas mãos para o Senhor, cessarão os trovões e não choverá mais granizo, a fim de que saibas que (toda) a terra é do Senhor.

[[v2-9-30]]

^<<v2-9-30,30>>^ Mas eu sei que nem tu nem os teus servos temem ainda o Senhor Deus.

[[v2-9-31]]

^<<v2-9-31,31>>^ O linho e a cevada perderam-se, porque a cevada estava verde e o linho estava em flores.

[[v2-9-32]]

^<<v2-9-32,32>>^ O trigo, porém, e o farro não foram danificados, porque eram serôdios.

[[v2-9-33]]

^<<v2-9-33,33>>^ Moisés, tendo deixado Faraó e saído da cidade, ergueu as mãos para o Senhor, e cessaram os trovões e o granizo, e não caiu mais chuva, sobre a terra.

[[v2-9-34]]

^<<v2-9-34,34>>^ Faraó, porém, vendo que tinha cessado a chuva, assim como o granizo e os trovões, aumentou o seu pecado:

[[v2-9-35]]

^<<v2-9-35,35>>^ o seu coração se obstinou e endureceu extraordinariamente, e não deixou partir os filhos de Israel, como o Senhor tinha mandado por meio de Moisés.

'''

xref:002-exodo/002-exodo-008.adoc#v2-8-0[&#60; Capítulo Anterior] | <<v2-9-0,Topo>> | xref:002-exodo/002-exodo-010.adoc#v2-10-0[Próximo Capítulo &#62;]