include::./index.adoc[]

[[v24-19-0]]
=== Provérbios, 19
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Provérbios 19 aborda diversos temas relacionados à sabedoria, justiça, riquezas e relacionamentos. O capítulo destaca a importância de agirmos com prudência e sabedoria em nossas ações, de sermos justos e honestos em nossas relações, de valorizarmos mais a sabedoria do que as riquezas materiais e de mantermos um coração puro diante de Deus.
* Provérbios 16:3: "Confia ao SENHOR as tuas obras, e teus pensamentos serão estabelecidos." Este verso destaca a importância de confiarmos em Deus em todas as áreas da nossa vida e de buscarmos a orientação divina em nossas decisões.
* Provérbios 22:1: "Mais digno de ser escolhido é o bom nome do que as muitas riquezas; e a boa fama vale mais do que a prata e o ouro." Este verso enfatiza que o valor de uma boa reputação é mais importante do que a acumulação de riquezas materiais.
* Provérbios 17:27: "O que guarda a sua boca conserva a sua alma, mas o que abre muito os seus lábios a si mesmo se traz a ruína." Este verso destaca a importância de guardarmos nossas palavras e de agirmos com prudência em nossas conversas e interações com os outros.
* Provérbios 19:11: "A prudência do homem faz reter a sua ira, e é glória sua o passar por cima da transgressão." Este verso destaca a importância de agirmos com prudência e sabedoria em nossas emoções e relacionamentos, e de aprendermos a perdoar e deixar de lado as ofensas.
* Provérbios 19:20: "Ouve o conselho, e recebe a correção, para que no fim sejas sábio." Este verso enfatiza a importância de ouvirmos conselhos e correções, e de aprendermos com nossos erros para crescermos em sabedoria e maturidade.
****

[[v24-19-1]]

^<<v24-19-1,1>>^ Mais vale o pobre que anda na sua integridade, do que o rico de lábios perversos e insensato.

[[v24-19-2]]

^<<v24-19-2,2>>^ Sem a ciência, nem o zelo é bom, e quem anda precipitado, tropeçará.

[[v24-19-3]]

^<<v24-19-3,3>>^ A estultícia do homem perverte os seus passos, e depois o seu coração irrita-se contra Deus (a quem lança as culpas).

[[v24-19-4]]

^<<v24-19-4,4>>^ As riquezas multiplicam muito os amigos; mas o pobre do seu (porventura único) amigo é abandonado.

[[v24-19-5]]

^<<v24-19-5,5>>^ A testemunha falsa não ficará impune; e o que diz mentiras não escapará.

[[v24-19-6]]

^<<v24-19-6,6>>^ São muitos os que adulam o homem generoso, e todos são amigos de quem dá. Todos os irmãos do homem pobre aborrecem-no; com maior razão os seus amigos se retirarão para longe dele.

[[v24-19-7]]

^<<v24-19-7,7>>^ Aquele que só busca palavras, não terá nada,

[[v24-19-8]]

^<<v24-19-8,8>>^ O possuidor do bom senso ama a sua alma; e o que guarda a prudência encontrará a felicidade.

[[v24-19-9]]

^<<v24-19-9,9>>^ A testemunha falsa não ficará impune, e o que diz mentiras, perecerá.

[[v24-19-10]]

^<<v24-19-10,10>>^ Ao insensato não estão bem as delícias, nem ao escravo o dominar os príncipes.

[[v24-19-11]]

^<<v24-19-11,11>>^ A sabedoria do homem conhece-se pela paciência, e a sua glória é passar por cima das injúrias a ele feitas.

[[v24-19-12]]

^<<v24-19-12,12>>^ Como (é terrível) o bramido do leão, assim a ira do rei; e o seu favor é como o orvalho sobre a erva.

[[v24-19-13]]

^<<v24-19-13,13>>^ O filho insensato é a dor do pai, e a mulher amiga de litígios é como o telhado, que está gotejando continuamente.

[[v24-19-14]]

^<<v24-19-14,14>>^ Os pais dão casas e riquezas, mas uma mulher sensata é um dom do Senhor.

[[v24-19-15]]

^<<v24-19-15,15>>^ A preguiça dá de si sono, e a alma frouxa terá fome.

[[v24-19-16]]

^<<v24-19-16,16>>^ Aquele que observa o mandamento (de Deus) guarda a sua vida; o que porém não cuida da sua conduta padecerá a morte.

[[v24-19-17]]

^<<v24-19-17,17>>^ O que se compadece do pobre empresta ao Senhor, e este lhe tornará o que lhe tiver emprestado.

[[v24-19-18]]

^<<v24-19-18,18>>^ Castiga o teu filho, não percas a esperança da (emenda), mas não chegue a tua severidade ao excesso de lhe dares a morte.

[[v24-19-19]]

^<<v24-19-19,19>>^ O que é muito iracundo sofrerá o castigo, e mais ainda, se guarda rancor.

[[v24-19-20]]

^<<v24-19-20,20>>^ Ouve o conselho e recebe a correcção, para que sejas sábio para futuro.

[[v24-19-21]]

^<<v24-19-21,21>>^ No coração do homem (agitam-se) muitos pensamentos; porém o desígnio do Senhor é que se realiza.

[[v24-19-22]]

^<<v24-19-22,22>>^ O atractivo dum homem é a sua bondade: e melhor é o pobre que o mentiroso.

[[v24-19-23]]

^<<v24-19-23,23>>^ O temor do Senhor conduz à vida, e (quem o possui) habitará na abundância sem a visita da desgraça.

[[v24-19-24]]

^<<v24-19-24,24>>^ O preguiçoso mete a mão no prato; e não quer ter o trabalho de a levar à boca.

[[v24-19-25]]

^<<v24-19-25,25>>^ Castigado o corrompido, tornar-se-á mais sábio o insensato; mas, se repreenderes o sábio, ele compreenderá a repreensão.

[[v24-19-26]]

^<<v24-19-26,26>>^ Aquele que maltrata o seu pai e que faz fugir sua mãe, é infame e desgraçado.

[[v24-19-27]]

^<<v24-19-27,27>>^ Não cesses, filho, de ouvir as advertências, nem ignores os ditames da ciência.

[[v24-19-28]]

^<<v24-19-28,28>>^ A testemunha falsa ri-se da justiça; e a boca dos ímpios devora a iniquidade.

[[v24-19-29]]

^<<v24-19-29,29>>^ Estão preparados os juízos (de Deus) para (castigar) os mofadores, e os açoutes para o dorso dos insensatos.

'''

xref:024-proverbios/024-proverbios-018.adoc#v24-18-0[&#60; Capítulo Anterior] | <<v24-19-0,Topo>> | xref:024-proverbios/024-proverbios-020.adoc#v24-20-0[Próximo Capítulo &#62;]