include::./index.adoc[]

[[v24-25-0]]
=== Provérbios, 25
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 25 do livro de Provérbios contém uma coleção de provérbios que lidam com vários temas, como a humildade, a paciência, a sabedoria, a bondade e a honestidade. Provérbios 25:2 destaca a importância de se buscar a sabedoria e a honra. Já Provérbios 25:6-7 enfatiza a importância da humildade, e como é melhor ser convidado a um lugar de honra do que presumir um lugar que não nos pertence. Provérbios 25:11-12 destaca a beleza das palavras bem escolhidas e o efeito positivo que elas podem ter na vida de alguém. Provérbios 25:21-22 enfatiza a importância da bondade, e como ser gentil com os inimigos pode levá-los a mudar de atitude. Finalmente, Provérbios 25:28 destaca a importância da paciência e do autocontrole.
* Provérbios 4:7: "A sabedoria é a principal coisa; adquire pois a sabedoria, emprega tudo o que possuis na aquisição de entendimento." Este versículo destaca a importância de buscar a sabedoria, assim como Provérbios 25:2.
* Provérbios 16:32: "Melhor é o longânimo do que o valente, e o que governa o seu espírito do que o que toma uma cidade." Este versículo enfatiza a importância da paciência e do autocontrole, assim como Provérbios 25:28.
* Efésios 4:29: "Não saia da vossa boca nenhuma palavra torpe, e sim unicamente a que for boa para edificação, conforme a necessidade, e, assim, transmita graça aos que ouvem." Este versículo destaca a beleza das palavras bem escolhidas, assim como Provérbios 25:11-12.
* Romanos 12:20-21: "Pelo contrário, se o teu inimigo tiver fome, dá-lhe de comer; se tiver sede, dá-lhe de beber; porque, fazendo isto, amontoarás brasas vivas sobre a sua cabeça. Não te deixes vencer pelo mal, mas vence o mal com o bem." Este versículo enfatiza a importância da bondade, assim como Provérbios 25:21-22.
* Provérbios 11:2: "Vindo a soberba, sobrevém a desonra; mas com os humildes está a sabedoria." Este versículo destaca a importância da humildade, assim como Provérbios 25:6-7.
****

[[v24-25-1]]

^<<v24-25-1,1>>^ Estas são também sentenças de Salomão as quais foram recolhidas pelos homens de Ezequias, rei de Judá.

[[v24-25-2]]

^<<v24-25-2,2>>^ A glória de Deus é encobrir as coisas, e a glória dos reis é investigá-las.

[[v24-25-3]]

^<<v24-25-3,3>>^ (Como) o céu na sua altura, e a terra na sua profundidade, assim o coração dos reis é impenetrável. (ver nota)

[[v24-25-4]]

^<<v24-25-4,4>>^ Tira as escórias da prata, e sairá um vaso puríssimo;

[[v24-25-5]]

^<<v24-25-5,5>>^ Tira o iníquo da presença do rei, e o seu trono se firmará na justiça.

[[v24-25-6]]

^<<v24-25-6,6>>^ Não apareças ufano diante do rei, e não te ponhas no lugar dos grandes.

[[v24-25-7]]

^<<v24-25-7,7>>^ É melhor que te digam: "Sobe para cá", do que seres humilhado diante dum grande.

[[v24-25-8]]

^<<v24-25-8,8>>^ O que teus olhos viram, não o descubras com precipitação numa contenda, pois, que farás, no fim, quando o teu próximo te houver confundido?

[[v24-25-9]]

^<<v24-25-9,9>>^ Defende a tua causa contra o teu próximo, mas não descubras o segredo de outrém,

[[v24-25-10]]

^<<v24-25-10,10>>^ não suceda que te envergonhe o que te ouvir, e se não apague a tua ignomínia.

[[v24-25-11]]

^<<v24-25-11,11>>^ Como maçãs de oiro em bandejas de prata, assim as palavras ditas no seu devido tempo.

[[v24-25-12]]

^<<v24-25-12,12>>^ Como uma arrecada de oiro e uma jóia refulgente, assim é a repreensão dada por um sábio a um ouvido dócil.

[[v24-25-13]]

^<<v24-25-13,13>>^ Como a frescura da neve no tempo da ceifa, assim é o embaixador fiel para quem o enviou: ele dá descanso à alma de seu senhor.

[[v24-25-14]]

^<<v24-25-14,14>>^ Como o vento e as nuvens que não trazem chuva, assim é o homem que se vangloria de liberalidade que não praticou.

[[v24-25-15]]

^<<v24-25-15,15>>^ O príncipe deixar-se-á aplacar pela paciência. e a língua doce quebrantará a dureza.

[[v24-25-16]]

^<<v24-25-16,16>>^ Se achaste mel, come só o suficiente, para que não suceda que, depois de farto, o vomites.

[[v24-25-17]]

^<<v24-25-17,17>>^ Põe raramente o teu pé na casa do teu próximo, para que não sucede que ele, enfastiado, te venha a aborrecer.

[[v24-25-18]]

^<<v24-25-18,18>>^ Maça, espada, seta penetrante, isso é o homem que diz um falso testemunho contra o seu próximo.

[[v24-25-19]]

^<<v24-25-19,19>>^ Como um dente podre e um pé que resvala, assim é o apoio do desleal no dia da desventura.

[[v24-25-20]]

^<<v24-25-20,20>>^ Tirar a capa num dia de frio, lançar vinagre sobre uma chaga, isso faz aquele que canta canções a um coração aflito.

[[v24-25-21]]

^<<v24-25-21,21>>^ Se o teu inimigo tiver fome, dá-lhe de comer, se tiver sede, dá-lhe água para beber, (ver nota)

[[v24-25-22]]

^<<v24-25-22,22>>^ porque assim amontoarás brasas vivas sobre a sua cabeça, e o Senhor te dará a paga.

[[v24-25-23]]

^<<v24-25-23,23>>^ O vento do aquilão traz as chuvas, e a língua detractora, às ocultas, ensombra os semblantes.

[[v24-25-24]]

^<<v24-25-24,24>>^ É melhor habitar a um canto do terraço, do que viver com uma mulher litigiosa em espaçosa casa.

[[v24-25-45]]

^<<v24-25-45,45>>^ Como a água fresca para pessoa que tem sede, assim é uma boa nova que vem dum país remoto.

[[v24-25-26]]

^<<v24-25-26,26>>^ Como uma fonte turbada, como uma nascente de água corrompida, assim é o justo que vacila diante do ímpio.

[[v24-25-27]]

^<<v24-25-27,27>>^ Assim como não faz bem o mel àquele que o come em demasia, assim o que quer sondar a majestade (divina) será oprimido pela sua glória.

[[v24-25-28]]

^<<v24-25-28,28>>^ Como uma cidade desmantelada, sem muros, assim é aquele que, quando fala. não pode conter o seu espírito.

'''

xref:024-proverbios/024-proverbios-024.adoc#v24-24-0[&#60; Capítulo Anterior] | <<v24-25-0,Topo>> | xref:024-proverbios/024-proverbios-026.adoc#v24-26-0[Próximo Capítulo &#62;]