include::./index.adoc[]

[[v24-9-0]]
=== Provérbios, 9
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Provérbios 9 apresenta a sabedoria personificada como uma mulher que convida os simples a comerem do seu banquete e a se tornarem sábios. O capítulo contrasta a sabedoria com a tolice, enfatizando a importância de seguir o caminho da sabedoria para se alcançar uma vida plena e satisfatória.
* Tiago 1:5: "E, se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente e não o lança em rosto; e ser-lhe-á dada." Este versículo destaca a importância de buscar a sabedoria de Deus em todas as situações e reconhecer que Ele é a fonte da verdadeira sabedoria.
* Provérbios 3:13-14: "Bem-aventurado o homem que acha sabedoria, e o homem que adquire conhecimento; porque é melhor a sua mercadoria do que a mercadoria de prata, e maior o seu lucro do que o ouro mais fino." Este versículo destaca a importância da sabedoria como um bem mais valioso do que o dinheiro e o ouro.
* Colossenses 2:2-3: "Para que os seus corações sejam consolados, e estejam unidos em amor e enriquecidos da plenitude da inteligência, para conhecimento do mistério de Deus e Pai, e de Cristo, em quem estão escondidos todos os tesouros da sabedoria e da ciência." Este versículo destaca a importância de conhecer a sabedoria de Deus em Cristo, como meio de se alcançar um entendimento pleno da verdade.
* Provérbios 10:14: "Os sábios entesouram o conhecimento, mas a boca do insensato é uma destruição iminente." Este versículo destaca a importância de valorizar e guardar a sabedoria, em contraste com a tolice que leva à destruição.
* Provérbios 16:16: "Quanto melhor é adquirir a sabedoria do que o ouro! e quanto mais excelente, adquirir a prudência do que a prata!" Este versículo enfatiza novamente a importância de se buscar a sabedoria e a prudência, como tesouros mais valiosos do que o dinheiro e as posses materiais.
****

[[v24-9-1]]

^<<v24-9-1,1>>^ A sabedoria edificou para si uma casa, levantou sete colunas.

[[v24-9-2]]

^<<v24-9-2,2>>^ Imolou as suas vitimas, preparou o vinho, pôs a sua mesa. (ver nota)

[[v24-9-3]]

^<<v24-9-3,3>>^ Enviou as suas criadas a fazer o convite dos pontos mais altos da cidade:

[[v24-9-4]]

^<<v24-9-4,4>>^ Todo o que é simples, venha a mim. Aos insensatos disse:

[[v24-9-5]]

^<<v24-9-5,5>>^ Vinde, comei o pão que eu vos dou, bebei o vinho que vos preparei.

[[v24-9-6]]

^<<v24-9-6,6>>^ Deixai as ninharias, e vivereis (felizes), e progredireis pelos caminhos da prudência.

[[v24-9-7]]

^<<v24-9-7,7>>^ Aquele que corrige o mofador, atraí o escárnio sobre si, e aquele que repreende o ímpio, arrisca-se a (sofrer) um ultraje.

[[v24-9-8]]

^<<v24-9-8,8>>^ Não repreendas o mofador, para que ele te não odeie. Repreende o sábio, e ele te amará. (ver nota)

[[v24-9-9]]

^<<v24-9-9,9>>^ Dá ao sábio ocasião (de aprender), e se lhe acrescentará sabedoria: ensina ao justo, e ele aumentará o seu saber.

[[v24-9-10]]

^<<v24-9-10,10>>^ O princípio da sabedoria é o temor do Senhor, e o conhecimento do Santo (Deus) é a inteligência.

[[v24-9-11]]

^<<v24-9-11,11>>^ Por mim se multiplicarão os teus dias, e serão acrescentados anos de vida.

[[v24-9-12]]

^<<v24-9-12,12>>^ Se fores sábio, para teu proveito o serás; se fores mofador. só tu experimentarás o mal.

[[v24-9-13]]

^<<v24-9-13,13>>^ A Senhora Loucura é irrequieta. é uma estulta que nada sabe (senão seduzir).

[[v24-9-14]]

^<<v24-9-14,14>>^ Assentou-se à porta de sua casa, sobre uma cadeira, num lugar alto da cidade,

[[v24-9-15]]

^<<v24-9-15,15>>^ para chamar os que passavam pela estrada, e que iam andando o seu caminho, (dizendo):

[[v24-9-16]]

^<<v24-9-16,16>>^ O que é simples venha cá. E ao insensato disse:

[[v24-9-17]]

^<<v24-9-17,17>>^ As águas furtivas são mais doces. e o pão tomado às escondidas é mais gostoso.

[[v24-9-18]]

^<<v24-9-18,18>>^ Ele ignora que lá (na casa da Loucura) há sombras (da morte) e que os seus convidados estão nas profundezas do inferno.

'''

xref:024-proverbios/024-proverbios-008.adoc#v24-8-0[&#60; Capítulo Anterior] | <<v24-9-0,Topo>> | xref:024-proverbios/024-proverbios-010.adoc#v24-10-0[Próximo Capítulo &#62;]