include::./index.adoc[]

[[v24-11-0]]
=== Provérbios, 11
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 11 de Provérbios aborda temas relacionados à justiça, honestidade, generosidade e humildade. Ele destaca que Deus abençoa aqueles que buscam fazer o que é certo, enquanto aqueles que agem de forma desonesta e egoísta acabam se prejudicando. Os versículos a seguir foram escolhidos por sua relevância aos temas tratados neste capítulo:
* Salmo 37:21: "O ímpio toma emprestado e não devolve, mas o justo é generoso e dá." Este versículo destaca a importância da generosidade e da honestidade, prometendo que aqueles que agem com justiça e bondade serão recompensados.
* Provérbios 16:5: "O Senhor detesta todos os corações arrogantes. Tenha certeza de que eles não ficarão impunes." Este versículo destaca a importância da humildade e da modéstia, prometendo que aqueles que são arrogantes e orgulhosos acabarão enfrentando a consequência de seus atos.
* Provérbios 15:27: "O ganancioso provoca desavenças em sua casa, mas quem odeia presentes viverá em paz." Este versículo destaca a importância de priorizar relacionamentos saudáveis e amorosos, prometendo que aqueles que são generosos e desapegados de bens materiais terão uma vida mais pacífica.
* Provérbios 21:3: "Fazer o que é justo e certo é mais aceitável ao Senhor do que oferecer sacrifícios." Este versículo destaca a importância de colocar a justiça e a moralidade acima de rituais religiosos e cerimônias, enfatizando a importância da ação ética em nossas vidas.
* Salmo 101:6: "Meus olhos estarão sobre os fiéis da terra, para que habitem comigo; aquele que anda num caminho perfeito me servirá." Este versículo destaca a importância da fidelidade e da integridade em nossas vidas, prometendo que aqueles que seguem o caminho da perfeição serão bem-sucedidos e honrados por Deus.
****

[[v24-11-1]]

^<<v24-11-1,1>>^ A balança falsa é abominação diante do Senhor, mas o peso justo é-lhe agradável.

[[v24-11-2]]

^<<v24-11-2,2>>^ Onde houver soberba, aí haverá também ignomínia; onde porém há humildade, ai há igualmente sabedoria.

[[v24-11-3]]

^<<v24-11-3,3>>^ A integridade dos justos conduzi-los-á felizmente; porém os enganos dos perversos serão a sua ruína.

[[v24-11-4]]

^<<v24-11-4,4>>^ As riquezas não servirão de nada no dia da cólera, mas a justiça livra da morte.

[[v24-11-5]]

^<<v24-11-5,5>>^ A justiça do homem honesto aplana-lhe o caminho, o mau porém cairá pela sua maldade.

[[v24-11-6]]

^<<v24-11-6,6>>^ A justiça dos rectos livrá-los-á, os iníquos, porém, serão apanhados em seus próprios laços.

[[v24-11-7]]

^<<v24-11-7,7>>^ Quando morre o ímpio, desaparece toda a sua esperança; e a expectativa dos iníquos é aniquilada.

[[v24-11-8]]

^<<v24-11-8,8>>^ O justo é livre da angústia, e o ímpio será entregue a ela, em lugar dele.

[[v24-11-9]]

^<<v24-11-9,9>>^ O ímpio arruína o seu próximo com a boca, mas os justos serão livres pela ciência.

[[v24-11-10]]

^<<v24-11-10,10>>^ Na prosperidade dos justos exultará a cidade, e na perdição dos ímpios haverá festa.

[[v24-11-11]]

^<<v24-11-11,11>>^ A cidade será exaltada pela bênção dos justos, e destruída pela boca dos ímpios.

[[v24-11-12]]

^<<v24-11-12,12>>^ Despreza o seu próximo quem tem pouco senso, mas o homem prudente calar-se-á.

[[v24-11-13]]

^<<v24-11-13,13>>^ O que procede com deslealdade descobre os segredos, mas o que é de coração leal cala o que se lhe confiou.

[[v24-11-14]]

^<<v24-11-14,14>>^ Onde não há quem governe perecerá o povo; onde há muitos conselheiros, ali haverá salvação.

[[v24-11-15]]

^<<v24-11-15,15>>^ Aquele que (incautamente) fica por fiador dum estranho, cairá na desventura: mas o que evita os compromissos, viverá tranqüilo.

[[v24-11-16]]

^<<v24-11-16,16>>^ A mulher gentil (pela sua virtude) alcançará louvor, e os diligentes obterão riquezas.

[[v24-11-17]]

^<<v24-11-17,17>>^ O homem caritativo faz bem à sua alma, mas o que é cruel, a si próprio prejudica.

[[v24-11-18]]

^<<v24-11-18,18>>^ A obra do ímpio não subsiste, mas para o que semeia (obras de) justiça há recompensa certa.

[[v24-11-19]]

^<<v24-11-19,19>>^ A justiça abre o caminho para a vida, e a afeição ao mal conduz à morte.

[[v24-11-20]]

^<<v24-11-20,20>>^ São abomináveis para o Senhor os de coração corrompido, são-lhe gratos os de conduta perfeita.

[[v24-11-21]]

^<<v24-11-21,21>>^ Cedo ou tarde o mau não ficará impune, porém a linhagem dos justos será salva.

[[v24-11-22]]

^<<v24-11-22,22>>^ Um anel de ouro no focinho dum porco, tal é a mulher formosa mas insensata.

[[v24-11-23]]

^<<v24-11-23,23>>^ Todo o desejo dos justos se dirige ao bem; o que espera os ímpios é o furor (divino).

[[v24-11-24]]

^<<v24-11-24,24>>^ Uns repartem liberalmente e ficam mais ricos, outros poupam demais, estão sempre na pobreza.

[[v24-11-25]]

^<<v24-11-25,25>>^ A alma beneficente será cumulada de bens, e o que largamente dá, largamente receberá.

[[v24-11-26]]

^<<v24-11-26,26>>^ O que esconde o trigo será amaldiçoado entre os povos; a bênção virá sobre a cabeça dos que o vendem.

[[v24-11-27]]

^<<v24-11-27,27>>^ Aquele que faz o bem, bens atrai (sobre si); aquele porém que busca fazer o mal, será por ele oprimido.

[[v24-11-28]]

^<<v24-11-28,28>>^ O que confia nas suas riquezas, cairá; mas os justos germinarão como uma folhagem verde.

[[v24-11-29]]

^<<v24-11-29,29>>^ O que perturba a sua casa não possuirá senão ventos; e o que é insensato servirá o sábio.

[[v24-11-30]]

^<<v24-11-30,30>>^ O fruto do justo é árvore de vida; e o que ganha as almas (para Deus) é sábio.

[[v24-11-31]]

^<<v24-11-31,31>>^ Se o justo é punido sobre a terra, quanto mais será o ímpio e o pecador?

'''

xref:024-proverbios/024-proverbios-010.adoc#v24-10-0[&#60; Capítulo Anterior] | <<v24-11-0,Topo>> | xref:024-proverbios/024-proverbios-012.adoc#v24-12-0[Próximo Capítulo &#62;]