include::./index.adoc[]

[[v24-5-0]]
=== Provérbios, 5
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Provérbios 5 fala sobre a importância da fidelidade conjugal e do perigo da imoralidade sexual. O capítulo adverte que ceder à tentação da imoralidade pode ter graves consequências, incluindo a ruína pessoal e a destruição de relacionamentos.
* 1 Coríntios 6:18: "Fugi da imoralidade sexual. Todos os outros pecados que alguém comete, fora do corpo os comete; mas quem peca sexualmente, peca contra o seu próprio corpo." Este versículo destaca a seriedade do pecado sexual e a necessidade de evitar a tentação da imoralidade.
* Hebreus 13:4: "Digno de honra entre todos seja o matrimônio, bem como o leito sem mácula; porque Deus julgará os impuros e adúlteros." Este versículo enfatiza a importância da fidelidade conjugal e a responsabilidade de manter o casamento puro.
* 2 Samuel 11:2-4: "E aconteceu que, numa tarde, Davi levantou-se do seu leito, e andava passeando no terraço da casa real; e viu dalí uma mulher que se estava lavando; e era esta mulher mui formosa à vista. E enviou Davi, e perguntou a respeito da mulher. E disseram-lhe: Porventura não é esta Bate-Seba, filha de Eliã, mulher de Urias, o heteu?" Este versículo conta a história de Davi, que cedeu à tentação da imoralidade sexual e teve graves consequências em sua vida e em seu reinado.
* 1 Tessalonicenses 4:3-5: "Porque esta é a vontade de Deus, a vossa santificação; que vos abstenhais da prostituição; que cada um de vós saiba possuir o seu vaso em santificação e honra, não na paixão da concupiscência, como os gentios que não conhecem a Deus." Este versículo exorta os cristãos a viverem uma vida santa e a se absterem da imoralidade sexual.
* Mateus 5:28: "Eu, porém, vos digo que qualquer que olhar para uma mulher com intenção impura, em seu coração, já adulterou com ela." Este versículo destaca a importância do controle da mente e dos pensamentos, e que a fidelidade conjugal não se limita apenas às ações físicas, mas também aos pensamentos e desejos.
****

[[v24-5-1]]

^<<v24-5-1,1>>^ Meu filho, atende à minha sabedoria, inclina o teu ouvido à minha prudência,

[[v24-5-2]]

^<<v24-5-2,2>>^ para conservares a reflexão e manteres em teus lábios a ciência.

[[v24-5-3]]

^<<v24-5-3,3>>^ Os lábios da mulher estranha são como o favo que destila o mel, e as suas palavras são mais suaves do que o azeite;

[[v24-5-4]]

^<<v24-5-4,4>>^ porém o seu fim é amargo como o absinto, e cortante como uma espada de dois gumes.

[[v24-5-5]]

^<<v24-5-5,5>>^ Os seus pés encaminham-se para a morte, e os seus passos levara até aos Infernos.

[[v24-5-6]]

^<<v24-5-6,6>>^ Ela não anda pela vereda da vida. Os seus passos vagabundos vão errando, sem saber para onde.

[[v24-5-7]]

^<<v24-5-7,7>>^ Agora, pois, meu filho, ouve-me, e não te apartes das palavras da minha boca.

[[v24-5-8]]

^<<v24-5-8,8>>^ Afasta dela o teu caminho, e não te aproximes da porta de sua casa.

[[v24-5-9]]

^<<v24-5-9,9>>^ Não (lês a tua honra a estranhos, nem os tens anos a um cruel, (ver nota)

[[v24-5-10]]

^<<v24-5-10,10>>^ para que não suceda que os estranhos enriqueçam com os teus bens, e que (os frutos dos) teus trabalhos passem para a casa doutrem, (ver nota)

[[v24-5-11]]

^<<v24-5-11,11>>^ e que tu gemas no fim, quando tiveres consumido as tuas carnes e o teu corpo, e digas:

[[v24-5-12]]

^<<v24-5-12,12>>^ Por que detestei a disciplina, e o meu coração não cedeu às repreensões,

[[v24-5-13]]

^<<v24-5-13,13>>^ nem ouvi a voz dos que ensinavam, nem dei ouvidos aos mestres?

[[v24-5-14]]

^<<v24-5-14,14>>^ Quase cheguei ao cúmulo da desgraça, no meio da assembleia cio povo e dos anciães.

[[v24-5-15]]

^<<v24-5-15,15>>^ Bebe da água da tua cisterna, e das correntes do teu poço.

[[v24-5-16]]

^<<v24-5-16,16>>^ Queres que corram fora as tuas fontes, queres espalhar as tuas águas nas praças públicas? (ver nota)

[[v24-5-17]]

^<<v24-5-17,17>>^ Possui-as tu só, e não tenham parte nelas os estranhos.

[[v24-5-18]]

^<<v24-5-18,18>>^ Abençoada a tua nascente! Vive alegre com a mulher que tornaste na tua juventude.

[[v24-5-19]]

^<<v24-5-19,19>>^ (Seja ela para ti como) uma corça que muito amas e (como) uma gazela cheia de graça; os seus encantos sejam o teu recreio em todo o tempo;no seu amor busca sempre as tuas delícias.

[[v24-5-20]]

^<<v24-5-20,20>>^ Por que te deixas, meu filho, enganar pela mulher alheia, e repousas no seio duma estranha?

[[v24-5-21]]

^<<v24-5-21,21>>^ O Senhor olha atentamente para os caminhos do homem, considera todos os seus passos.

[[v24-5-22]]

^<<v24-5-22,22>>^ O ímpio é presa das suas próprias iniquidades, e é ligado com as cadeias dos seus pecados.

[[v24-5-23]]

^<<v24-5-23,23>>^ Éle morrerá (infeliz), porque não recebeu a correcção, e se achará enganado pelo excesso da sua loucura.

'''

xref:024-proverbios/024-proverbios-004.adoc#v24-4-0[&#60; Capítulo Anterior] | <<v24-5-0,Topo>> | xref:024-proverbios/024-proverbios-006.adoc#v24-6-0[Próximo Capítulo &#62;]