include::./index.adoc[]

[[v24-23-0]]
=== Provérbios, 23
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 23 do livro de Provérbios trata sobre a importância da disciplina, a moderação na alimentação e o cuidado com as más companhias. Provérbios 23:4-5 adverte sobre a inutilidade de buscar riquezas e a importância de manter o foco nas coisas mais importantes. Já Provérbios 23:13-14 destaca a importância da disciplina e da correção, enquanto Provérbios 23:20-21 adverte sobre os perigos do excesso na bebida alcoólica e da má companhia. Finalmente, Provérbios 23:22-25 enfatiza a importância do respeito aos pais e a valorização da sabedoria.
* Provérbios 22:6: "Ensina a criança no caminho em que deve andar, e mesmo quando for velho não se desviará dele." Este versículo destaca a importância da disciplina e da correção, assim como Provérbios 23:13-14.
* 1 Coríntios 6:12: "Todas as coisas me são lícitas, mas nem todas as coisas convêm; todas as coisas me são lícitas, mas eu não me deixarei dominar por nenhuma." Este versículo adverte sobre a importância da moderação e do autocontrole, assim como Provérbios 23:1-3 e 23:20-21.
* Provérbios 1:10: "Filho meu, se os pecadores procuram te seduzir, não o consintas." Este versículo adverte sobre os perigos da má companhia, assim como Provérbios 23:20-21.
* Efésios 6:1-3: "Filhos, obedecei a vossos pais no Senhor, pois isto é justo. Honra a teu pai e a tua mãe (que é o primeiro mandamento com promessa), para que te vá bem, e sejas de longa vida sobre a terra." Este versículo enfatiza a importância do respeito aos pais, assim como Provérbios 23:22-25.
* Colossenses 3:23-24: "E tudo o que fizerdes, fazei-o de todo o coração, como para o Senhor e não para homens, sabendo que do Senhor recebereis como recompensa a herança. Servi a Cristo, o Senhor." Este versículo destaca a importância de manter o foco nas coisas mais importantes, assim como Provérbios 23:4-5.
****

[[v24-23-1]]

^<<v24-23-1,1>>^ Quando te assentares a comer com um grande, considera com atenção o que está diante de ti,

[[v24-23-2]]

^<<v24-23-2,2>>^ e põe uma faca na tua garganta, se sentes muito apetite.

[[v24-23-3]]

^<<v24-23-3,3>>^ Não desejes comer dos seus manjares, porque são manjares enganosos.

[[v24-23-4]]

^<<v24-23-4,4>>^ Não te afadigues por ser rico, evita pôr nisso o teu pensamento.

[[v24-23-5]]

^<<v24-23-5,5>>^ Não ponhas os teus olhos em riquezas que não podes ter, porque elas tomarão asas como de águia, e voarão para o céu.

[[v24-23-6]]

^<<v24-23-6,6>>^ Não comas com o homem invejoso, e não desejes os seus manjares,

[[v24-23-7]]

^<<v24-23-7,7>>^ porque ele se mostra tal qual calculou em si mesmo. Come e bebe, te dirá ele; mas o seu coração não está contigo.

[[v24-23-8]]

^<<v24-23-8,8>>^ Vomitarás os manjares que tiveres comido, e desperdiçarás as tuas belas palavras.

[[v24-23-9]]

^<<v24-23-9,9>>^ Não fales aos ouvidos dos insensatos, porque eles desprezarão a sabedoria das tuas palavras.

[[v24-23-10]]

^<<v24-23-10,10>>^ Não toques nos limites antigos, e não entres no campo dos órfãos;

[[v24-23-11]]

^<<v24-23-11,11>>^ porque o seu curador é (Todo) poderoso, e ele mesmo.se fará contra ti o defensor da sua causa.

[[v24-23-12]]

^<<v24-23-12,12>>^ Aplica o teu coração à instrução e os teus ouvidos às palavras da ciência.

[[v24-23-13]]

^<<v24-23-13,13>>^ Não poupes a correcção ao menino. porque, se lhe bateres com a vara, não morrerá.

[[v24-23-14]]

^<<v24-23-14,14>>^ Tu lhe baterás com a vara, e livrarás a sua alma da morada dos mortos.

[[v24-23-15]]

^<<v24-23-15,15>>^ Meu filho, se o teu espírito for sábio, alegrar-se-á contigo o meu coração;

[[v24-23-16]]

^<<v24-23-16,16>>^ e as minhas entranhas exultarão de prazer, quando os teus lábios proferirem palavras rectas.

[[v24-23-17]]

^<<v24-23-17,17>>^ O teu coração não tenha inveja aos pecadores, mas conserva-te sempre firme no temor do Senhor,

[[v24-23-18]]

^<<v24-23-18,18>>^ porque certamente terás um futuro (feliz) e não será frustrada a tua expectação.

[[v24-23-19]]

^<<v24-23-19,19>>^ Ouve, meu filho, e sê sábio; dirige a tua alma pelo caminho direito.

[[v24-23-20]]

^<<v24-23-20,20>>^ Não te queiras achar nos banquetes dos ébrios ou dos devoradores de carnes,

[[v24-23-21]]

^<<v24-23-21,21>>^ porque o ébrio e o glutão se empobrecem, e a sonolência andará vestida de andrajos.

[[v24-23-22]]

^<<v24-23-22,22>>^ Ouve o teu pai, que te gerou, e não desprezes tua mãe, quando for velha.

[[v24-23-23]]

^<<v24-23-23,23>>^ Adquire (a todo o custo) a verdade, e não a vendas, adquire sabedoria, instrução, inteligência.

[[v24-23-24]]

^<<v24-23-24,24>>^ O pai justo salta de prazer; o que gerou um filho sábio terá nele a sua alegria.

[[v24-23-25]]

^<<v24-23-25,25>>^ Tenham esta alegria o teu pai e a tua mãe, exulte a que te deu à luz.

[[v24-23-26]]

^<<v24-23-26,26>>^ Dá-me, filho meu, o teu coração, e os teus olhos guardem os meus caminhos,

[[v24-23-27]]

^<<v24-23-27,27>>^ porque a mulher prostituta é uma cova funda, e a alheia é um poço estreito.

[[v24-23-28]]

^<<v24-23-28,28>>^ Ela está de emboscada no caminho como um salteador, e multiplica, entre os homens, os prevaricadores.

[[v24-23-29]]

^<<v24-23-29,29>>^ Para quem os ah!? Para quem os ais? Para quem as contendas? Para quem as queixas? Para quem as feridas sem motivo? Para quem o vermelho dos olhos?

[[v24-23-30]]

^<<v24-23-30,30>>^ Para quem, senão para aqueles que passam o tempo a beber vinho, que vão saborear o vinho aromatizado?

[[v24-23-31]]

^<<v24-23-31,31>>^ Não estejas a reparar como o vinho é vermelho, como brilha no copo, como corre suavemente.

[[v24-23-32]]

^<<v24-23-32,32>>^ No fim morde como uma serpente, e espalha o seu veneno como um basilisco.

[[v24-23-33]]

^<<v24-23-33,33>>^ Os teus olhos verão coisas estranhas, e o teu coração dirá palavras desacertadas.

[[v24-23-34]]

^<<v24-23-34,34>>^ E tu serás como um homem adormecido no meio do mar. e como um marinheiro na tempestade.

[[v24-23-35]]

^<<v24-23-35,35>>^ E dirás: Espancaram-me, mas não me doeu; bateram-me mas não senti. Quando despertarei eu? Quero buscar mais vinho para beber.

'''

xref:024-proverbios/024-proverbios-022.adoc#v24-22-0[&#60; Capítulo Anterior] | <<v24-23-0,Topo>> | xref:024-proverbios/024-proverbios-024.adoc#v24-24-0[Próximo Capítulo &#62;]