include::./index.adoc[]

[[v21-69-0]]
=== Salmos, 69
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O Salmo 69 é um salmo de lamentação em que o salmista expressa sua dor, angústia e sofrimento diante das aflições e perseguições que enfrenta. Ele clama por ajuda e salvação, ao mesmo tempo que se volta para Deus em busca de conforto e proteção. A seguir, seguem cinco versículos relacionados com os temas abordados no Salmo 69:
* Salmos 34:18: "O Senhor está perto dos que têm o coração quebrantado e salva os de espírito abatido." Este versículo mostra como Deus é sensível à dor daqueles que sofrem e que Ele está sempre pronto a oferecer conforto e ajuda.
* Salmos 119:81: "Minha alma desfalece esperando por tua salvação, mas ponho minha esperança em tua palavra." O salmista se encontra em um momento de desespero, mas encontra força e consolo na palavra de Deus, que é fonte de esperança e salvação.
* Romanos 12:15: "Alegrai-vos com os que se alegram e chorai com os que choram." Este versículo nos lembra da importância de compartilhar o sofrimento dos outros e de ser solidário com aqueles que passam por momentos difíceis.
* 2 Coríntios 1:3-4: "Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, Pai das misericórdias e Deus de toda consolação, que nos consola em todas as nossas tribulações, para que, com a consolação que recebemos de Deus, possamos consolar os que estão passando por tribulações." Este versículo destaca como Deus é o consolador de todos aqueles que sofrem e nos chama a sermos agentes de consolação para aqueles que passam por dificuldades.
* Hebreus 4:14-16: "Assim, visto que temos um grande sumo sacerdote que penetrou nos céus, Jesus, o Filho de Deus, apeguemo-nos com toda a firmeza à fé que professamos, pois não temos um sumo sacerdote que não possa compadecer-se das nossas fraquezas, mas sim alguém que, como nós, passou por todo tipo de tentação, porém, sem pecado. Assim sendo, aproximemo-nos do trono da graça com toda a confiança, a fim de recebermos misericórdia e encontrarmos graça que nos ajude no momento da necessidade." Este versículo nos lembra que Jesus é o nosso sumo sacerdote, que compreende as nossas fraquezas e nos convida a nos achegarmos a Deus em busca de ajuda e graça.
****

[[v21-69-1]]

^<<v21-69-1,1>>^ Ao mestre do coro. De Davide. Para memória.

[[v21-69-2]]

^<<v21-69-2,2>>^ Apraza-te, ó Deus, libertar-me. Senhor, apressa-te em me socorrer.

[[v21-69-3]]

^<<v21-69-3,3>>^ Sejam confundidos e envergonhados os que procuram tirar-me a vida, Voltem atrás e sejam envergonhados, os que se comprazem nos meus males.

[[v21-69-4]]

^<<v21-69-4,4>>^ Retirem-se cheios de confusão, os que (insultando) me dizem: "Bem feito, bem feito!"

[[v21-69-5]]

^<<v21-69-5,5>>^ Regozijem-se e alegrem-se em ti todos os que te buscam; e os que desejam o teu caminho digam sempre: "Glorificado seja o Senhor!"

[[v21-69-6]]

^<<v21-69-6,6>>^ Eu, porém, sou miserável e pobre, ó Deus, socorre-me. Tu és o meu protector e o meu libertador: Senhor, não te demores.

'''

xref:021-salmos/021-salmos-068.adoc#v21-68-0[&#60; Capítulo Anterior] | <<v21-69-0,Topo>> | xref:021-salmos/021-salmos-070.adoc#v21-70-0[Próximo Capítulo &#62;]