include::./index.adoc[]

[[v21-115-0]]
=== Salmos, 115
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O Salmo 115 é um salmo de louvor ao Deus verdadeiro e vivo, contrastando-o com os ídolos inúteis feitos pelas mãos humanas. Os versículos escolhidos a seguir destacam a grandeza e a fidelidade de Deus, enfatizando a confiança que devemos ter nele em detrimento de qualquer outra coisa:
* Isaías 44:6: "Assim diz o Senhor, o Rei de Israel, seu Redentor, o Senhor dos Exércitos: Eu sou o primeiro e o último, além de mim não há Deus." Este versículo destaca a unicidade de Deus e seu papel como criador e governante do universo.
* Provérbios 3:5-6: "Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento. Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas." Este versículo enfatiza a importância de confiar em Deus e buscar a sua orientação em todas as circunstâncias.
* Deuteronômio 7:9: "Saberás, pois, que o Senhor teu Deus é Deus, o Deus fiel, que guarda o concerto e a misericórdia até mil gerações aos que o amam e guardam os seus mandamentos." Este versículo destaca a fidelidade de Deus em cumprir suas promessas e manter suas alianças com seu povo.
* Salmos 118:8-9: "É melhor confiar no Senhor do que confiar no homem. É melhor confiar no Senhor do que confiar nos príncipes." Este versículo reforça a mensagem de que a confiança deve ser depositada em Deus em vez de nas pessoas ou instituições humanas.
* Romanos 8:28: "E sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus, daqueles que são chamados por seu decreto." Este versículo traz conforto e segurança ao lembrar que Deus trabalha para o bem de seus filhos, mesmo em meio a circunstâncias difíceis.
****

[[v21-115-1]]

^<<v21-115-1,1>>^ Tive confiança mesmo quando disse: "Estou muito aflito."

[[v21-115-2]]

^<<v21-115-2,2>>^ Eu disse no meu pavor: "Todo o homem é falaz!"

[[v21-115-3]]

^<<v21-115-3,3>>^ Que darei eu em retribuição ao Senhor, por todos os benefícios que me tem feito?

[[v21-115-4]]

^<<v21-115-4,4>>^ Tomarei o cálice da salvação, e invocarei o nome do Senhor.

[[v21-115-5]]

^<<v21-115-5,5>>^ Cumprirei os meus votos ao Senhor, diante de todo o seu povo.

[[v21-115-6]]

^<<v21-115-6,6>>^ É preciosa aos olhos do Senhor a morte dos seus santos.

[[v21-115-7]]

^<<v21-115-7,7>>^ Ó Senhor, eu sou teu servo, eu sou teu servo e filho da tua escrava: quebraste as minhas cadeias.

[[v21-115-8]]

^<<v21-115-8,8>>^ Eu te oferecerei um sacrifício de louvor, e invocarei o nome do Senhor.

[[v21-115-9]]

^<<v21-115-9,9>>^ Cumprirei os meus votos ao Senhor, diante de todo o seu povo,

[[v21-115-10]]

^<<v21-115-10,10>>^ nos átrios da casa do Senhor, no meio de ti, ó Jerusalém.

'''

xref:021-salmos/021-salmos-114.adoc#v21-114-0[&#60; Capítulo Anterior] | <<v21-115-0,Topo>> | xref:021-salmos/021-salmos-116.adoc#v21-116-0[Próximo Capítulo &#62;]