include::./index.adoc[]

[[v21-73-0]]
=== Salmos, 73
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O Salmo 73 aborda a questão da prosperidade dos ímpios e da justiça divina. O salmista se questiona por que os ímpios parecem estar em vantagem e vivem uma vida próspera, enquanto ele, que busca seguir a Deus, passa por dificuldades e sofrimentos. Ele reflete sobre como é fácil ser tentado a se desviar do caminho da justiça ao ver a aparente felicidade dos ímpios. No entanto, ele encontra consolo ao perceber que a verdadeira prosperidade vem de estar próximo a Deus e que a justiça divina não falha.
* Salmos 37:7-8: "Descanse no Senhor e aguarde por ele com paciência; não se aborreça com o sucesso dos outros, nem com aqueles que maquinam o mal. Evite a ira e rejeite a fúria; não se preocupe, isso só leva ao mal." Este versículo incentiva a paciência e confiança em Deus, mesmo diante da aparente prosperidade dos ímpios. Ele aconselha a evitar a inveja e o ódio e a confiar que Deus agirá de acordo com a justiça.
* Salmos 37:16: "É melhor o pouco do justo do que a riqueza de muitos ímpios." Este versículo destaca que a verdadeira riqueza não está na posse de bens materiais, mas em estar em paz com Deus e ter uma vida justa.
* Salmos 49:16-17: "Não tenha medo quando alguém ficar rico, quando a glória da sua casa aumentar; pois, quando morrer, nada levará consigo; a sua glória não descerá com ele." Este versículo lembra que a prosperidade material é temporária e que a verdadeira riqueza é encontrada em Deus.
* Provérbios 3:5-6: "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento; em todos os seus caminhos, reconheça-o, e ele endireitará as suas veredas." Este versículo incentiva a confiança em Deus e a lembrar que Ele está no controle, mesmo quando a vida parece difícil e desafiadora.
* Romanos 8:28: "E sabemos que Deus age em todas as coisas para o bem daqueles que o amam, dos que foram chamados de acordo com o seu propósito." Este versículo lembra que Deus está trabalhando em todas as coisas para o bem daqueles que O amam, mesmo quando a vida é difícil e não entendemos os caminhos Dele.
****

[[v21-73-1]]

^<<v21-73-1,1>>^ Maskil. Do Asaf, Por que razão, ó Deus, nos desamparaste para sempre? (Por que razão) se acende a tua ira contra as ovelhas do teu pasto?

[[v21-73-2]]

^<<v21-73-2,2>>^ Lembra-te da tua família, que fundaste desde a antiguidade, da tribo que para propriedade tua resgataste, do monte de Sião, em que estabeleceste a tua morada.

[[v21-73-3]]

^<<v21-73-3,3>>^ Dirige os teus passos para essas ruínas irreparáveis: o inimigo tudo devastou no santuário.

[[v21-73-4]]

^<<v21-73-4,4>>^ Rugiram os teus adversários no lugar da tua assembleia, arvoraram os seus estandartes como troféu.

[[v21-73-5]]

^<<v21-73-5,5>>^ Pareciam-se cora os que no bosque vibram o machado, (ver nota)

[[v21-73-6]]

^<<v21-73-6,6>>^ e com o machado e o martelo igualmente despedaçam as suas portas.

[[v21-73-7]]

^<<v21-73-7,7>>^ Puseram fogo ao teu santuário; na terra profanaram o tabernáculo do teu nome.

[[v21-73-8]]

^<<v21-73-8,8>>^ Disseram no seu coração: "Destruámo-los todos juntamente; incendiai todos os santuários de Deus na terra."

[[v21-73-9]]

^<<v21-73-9,9>>^ Já não vemos os nossos prodígios, já não há um profeta (que nos guie); nem há entre nós quem saiba até quando.

[[v21-73-10]]

^<<v21-73-10,10>>^ Até quando, ó Deus, nos insultará o inimigo? O adversário há-de blasfemar sempre o teu nome?

[[v21-73-11]]

^<<v21-73-11,11>>^ Por que retraia a tua mão? Por que reténs a tua direita no teu seio?

[[v21-73-12]]

^<<v21-73-12,12>>^ Deus, todavia, é meu rei desde outrora, ele que opera a salvação no meio da terra.

[[v21-73-13]]

^<<v21-73-13,13>>^ Tu com o teu poder abriste o mar (Vermelho), pisaste as cabeças dos dragões nas águas.

[[v21-73-14]]

^<<v21-73-14,14>>^ Tu quebraste as cabeças do Leviatã, deste-lo por comida aos monstros marinhos.

[[v21-73-15]]

^<<v21-73-15,15>>^ Tu fizeste brotar fontes e torrentes; tu secaste os rios caudalosos.

[[v21-73-16]]

^<<v21-73-16,16>>^ Teu é o dia, e tua é a noite; tu fixaste a lua e o sol.

[[v21-73-17]]

^<<v21-73-17,17>>^ Tu estabeleceste todos os limites da terra, o estio e o inverno, tu os formaste.

[[v21-73-18]]

^<<v21-73-18,18>>^ Lembra-te disto: o inimigo ultrajou-te. Senhor, e um povo insensato blasfemou do teu nome.

[[v21-73-19]]

^<<v21-73-19,19>>^ Não abandones ao abutre a vida da tua rola, e não esqueças para sempre as vidas dos teus pobres. (ver nota)

[[v21-73-20]]

^<<v21-73-20,20>>^ Olha para a tua aliança, porque todos os esconderijos do país e os campos estão cheios de violência.

[[v21-73-21]]

^<<v21-73-21,21>>^ Não se volte confundido o humilde: o pobre e o desvalido louvam o teu nome.

[[v21-73-22]]

^<<v21-73-22,22>>^ Levanta-te, ó Deus, defende a tua causa; lembra-te do ultraje que o néscio te dirige continuamente.

[[v21-73-23]]

^<<v21-73-23,23>>^ Não te esqueças dos gritos dos teus adversários: o tumulto dos que se insurgem contra ti aumenta continuamente.

'''

xref:021-salmos/021-salmos-072.adoc#v21-72-0[&#60; Capítulo Anterior] | <<v21-73-0,Topo>> | xref:021-salmos/021-salmos-074.adoc#v21-74-0[Próximo Capítulo &#62;]