include::./index.adoc[]

[[v21-93-0]]
=== Salmos, 93
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O Salmo 93 é um hino que exalta a soberania e majestade do Senhor, que é descrito como aquele que reina acima de todas as coisas e mantém o mundo firmemente estabelecido. Os versículos selecionados abaixo destacam a grandeza de Deus e a sua autoridade sobre toda a criação.
* Salmos 24:1-2: "Do Senhor é a terra e tudo o que nela existe, o mundo e os que nele vivem; pois foi ele quem a fundou sobre os mares e a firmou sobre as águas." Esse versículo fala da autoridade e soberania de Deus sobre toda a criação, incluindo a terra e todos os seus habitantes.
* Salmos 47:7-8: "Pois Deus é o Rei de toda a terra; cantem louvores com harmonioso cântico. Deus reina sobre as nações; Deus está sentado em seu santo trono." Este versículo destaca a soberania de Deus sobre todas as nações da terra.
* Salmos 96:10: "Digam entre as nações: O Senhor reina! Dele são os céus, e a terra o seu domínio." Esse versículo enfatiza que o Senhor é o governante supremo de todo o universo, incluindo os céus e a terra.
* Isaías 6:1: "No ano em que o rei Uzias morreu, eu vi o Senhor assentado num trono alto e exaltado, e a aba de sua veste enchia o templo." Este versículo descreve uma visão de Isaías em que ele vê o Senhor sentado em um trono, o que é uma imagem semelhante à descrição do salmista no Salmo 93.
* Apocalipse 19:6: "Então ouvi o que parecia ser a voz de uma grande multidão, como o som de muitas águas e de fortes trovões, que clamava: Aleluia! Pois reina o Senhor, nosso Deus, o Todo-poderoso." Esse versículo retrata uma cena no céu em que uma multidão celebra a soberania de Deus e o fato de que Ele reina para sempre.
****

[[v21-93-1]]

^<<v21-93-1,1>>^ Ó Deus das vinganças, ó Senhor, ó Deus das vinganças, mostra o teu esplendor.

[[v21-93-2]]

^<<v21-93-2,2>>^ Levanta-te (ó Deus), que julgas a terra; dá aos soberbos o que merecem.

[[v21-93-3]]

^<<v21-93-3,3>>^ Até quando é que os ímpios, Senhor, até quando é que os ímpios se hão-de gloriar?

[[v21-93-4]]

^<<v21-93-4,4>>^ (Até quando) proferirão necedades, falarão com arrogância, se jactarão os que praticam, a iniquidade?

[[v21-93-5]]

^<<v21-93-5,5>>^ Calçam, Senhor, o teu povo, e oprimem a tua herança;

[[v21-93-6]]

^<<v21-93-6,6>>^ trucidam a viúva e o peregrino, tiram a vida aos órfãos.

[[v21-93-7]]

^<<v21-93-7,7>>^ E dizem; "Não o vê o Senhor, nem o nota o Deus de Jacob."

[[v21-93-8]]

^<<v21-93-8,8>>^ Reflecti, insensatos do povo, e vós, néscios, quando sereis atilados?

[[v21-93-9]]

^<<v21-93-9,9>>^ Porventura aquele (Senhor) que plantou o ouvido, não ouvirá? Ou o que formou os olhos, não verá?

[[v21-93-10]]

^<<v21-93-10,10>>^ O que educa as gentes, não castigará? — ele que ensina ao homem a ciência...

[[v21-93-11]]

^<<v21-93-11,11>>^ O Senhor conhece os pensamentos dos homens, (ele sabe) que são vãos.

[[v21-93-12]]

^<<v21-93-12,12>>^ Bem-aventurado o homem a quem tu educas, Senhor, e instruis na tua lei, (ver nota)

[[v21-93-13]]

^<<v21-93-13,13>>^ para lhe dar descanso a seguir aos dias infaustos, até que se abra a cova para o ímpio.

[[v21-93-14]]

^<<v21-93-14,14>>^ Com efeito o Senhor não rejeitará o seu povo, nem abandonará a sua herança;

[[v21-93-15]]

^<<v21-93-15,15>>^ antes o julgamento voltará à justiça, e segui-la-ão todos os rectos de coração.

[[v21-93-16]]

^<<v21-93-16,16>>^ Quem se levantará por mim contra os malfeitores? Quem estará por mim contra os que praticam a iniquidade?

[[v21-93-17]]

^<<v21-93-17,17>>^ Se o Senhor me não socoresse, em breve a minha alma habitaria na região do silêncio.

[[v21-93-18]]

^<<v21-93-18,18>>^ Quando penso: "O meu pé está vacilante", a tua graça, Senhor, me sustenta.

[[v21-93-19]]

^<<v21-93-19,19>>^ Quando se multiplicam as angústias no meu coração, as tuas consolações deleitam a minha alma.

[[v21-93-20]]

^<<v21-93-20,20>>^ Porventura tem alguma coisa de comum contigo o tribunal iníquo, que forja vexames sob pretextos legais?

[[v21-93-21]]

^<<v21-93-21,21>>^ Atentem, muito embora, contra a vida do justo, e condenem o sangue do inocente:

[[v21-93-22]]

^<<v21-93-22,22>>^ o Senhor há-de ser a minha defesa, e o meu Deus a rocha do meu refúgio.

[[v21-93-23]]

^<<v21-93-23,23>>^ Devolver-lhes-á em paga a sua própria iniquidade, com a sua maldade os exterminará, destruí-los-á o Senhor nosso Deus.

'''

xref:021-salmos/021-salmos-092.adoc#v21-92-0[&#60; Capítulo Anterior] | <<v21-93-0,Topo>> | xref:021-salmos/021-salmos-094.adoc#v21-94-0[Próximo Capítulo &#62;]