include::./index.adoc[]

[[v21-84-0]]
=== Salmos, 84
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O Salmo 84 é um cântico que expressa o desejo profundo do salmista pela presença de Deus em sua vida e alegria em estar em Sua casa. O capítulo começa com o salmista descrevendo o quão amável é o lugar onde Deus habita e o quão grande é o seu desejo de estar ali. Em seguida, ele expressa sua admiração pela graça de Deus e confiança em sua proteção. Aqui estão cinco versículos relacionados aos temas do Salmo 84:
* Salmos 27:4: "Uma coisa peço ao Senhor, é o que procuro: que eu possa viver na casa do Senhor todos os dias da minha vida, para contemplar a bondade do Senhor e buscar sua orientação no seu templo." Este verso expressa o mesmo desejo do salmista em Salmo 84 de habitar na casa de Deus e desfrutar de Sua presença.
* Salmos 85:10: "A misericórdia e a verdade se encontraram; a justiça e a paz se beijaram." O salmista de Salmo 84 descreve a bondade e a misericórdia de Deus, e este verso em Salmos 85 também enfatiza a misericórdia de Deus.
* Salmos 118:8: "É melhor confiar no Senhor do que confiar no homem." O salmista de Salmo 84 expressa sua confiança em Deus e em sua proteção. Este verso em Salmos 118 reforça essa confiança em Deus em vez de confiar em seres humanos.
* Salmos 119:105: "Lâmpada para os meus pés é a tua palavra, e luz para o meu caminho." O salmista de Salmo 84 busca a orientação de Deus, e a Palavra de Deus é vista como uma fonte de orientação e sabedoria para os crentes. Este verso enfatiza a importância da Palavra de Deus como uma bússola para a vida dos crentes.
* Salmos 146:5: "Como feliz é aquele que tem o Deus de Jacó para ajudá-lo e cuja esperança está no Senhor, seu Deus." Este verso destaca a felicidade que o salmista de Salmo 84 encontra na presença de Deus e em Sua proteção e ajuda.
****

[[v21-84-1]]

^<<v21-84-1,1>>^ Ao mestre do coro. Dos filhos de Coré. Salmo.

[[v21-84-2]]

^<<v21-84-2,2>>^ Foste propício, Senhor, à tua terra; mudaste em bem a sorte de Jacob.

[[v21-84-3]]

^<<v21-84-3,3>>^ Perdoaste a culpa do teu povo; cobriste todos os seus pecados.

[[v21-84-4]]

^<<v21-84-4,4>>^ Reprimiste toda a tua ira; desististe do furor da tua indignação.

[[v21-84-5]]

^<<v21-84-5,5>>^ Restaura-nos, ó Deus, salvador nosso, e depõe a tua indignação contra nós.

[[v21-84-6]]

^<<v21-84-6,6>>^ Porventura estarás sempre irado contra nós, ou estenderás a tua ira a todas as gerações?

[[v21-84-7]]

^<<v21-84-7,7>>^ Porventura não nos tornarás a dar a vida, e o teu povo não se alegrará em ti?

[[v21-84-8]]

^<<v21-84-8,8>>^ Mostra-nos, Senhor, a tua misericórdia, e dá-nos a tua salvação.

[[v21-84-9]]

^<<v21-84-9,9>>^ Ouvirei o que o Senhor diz: sem dúvida fala de paz ao seu povo e aos seus santos, e àqueles que de coração se convertem.

[[v21-84-10]]

^<<v21-84-10,10>>^ Sim, a sua salvação está perto dos que o temem, a fim de que a glória habite na nossa terra.

[[v21-84-11]]

^<<v21-84-11,11>>^ A misericórdia e a fidelidade se encontraram juntas, a justiça e a paz se oscularam.

[[v21-84-12]]

^<<v21-84-12,12>>^ A fidelidade germinará da terra, a justiça olhará do alto do céu.

[[v21-84-13]]

^<<v21-84-13,13>>^ Também o Senhor dará o bem, e a nossa terra produzirá o seu fruto.

[[v21-84-14]]

^<<v21-84-14,14>>^ A justiça irá adiante dele, e a salvação (irá) pelo caminho dos seus passos.

'''

xref:021-salmos/021-salmos-083.adoc#v21-83-0[&#60; Capítulo Anterior] | <<v21-84-0,Topo>> | xref:021-salmos/021-salmos-085.adoc#v21-85-0[Próximo Capítulo &#62;]