include::./index.adoc[]

[[v21-9-0]]
=== Salmos, 9
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O Salmo 9 é um salmo de ação de graças no qual o salmista expressa sua gratidão a Deus por sua proteção e salvação em tempos difíceis. Ele também clama por justiça contra seus inimigos. Abaixo estão cinco versículos relacionados com os temas abordados em Salmo 9:
* Salmo 10:17-18: "O Senhor ouve os desamparados e os conforta; ele protege os estrangeiros e os ajuda a sobreviver. Ele defende os órfãos e as viúvas, mas frustra os planos dos ímpios." Este versículo destaca o cuidado de Deus pelos desamparados e sua justiça contra os ímpios, temas presentes em Salmo 9.
* Salmo 18:2: "O Senhor é minha rocha, minha fortaleza e meu libertador; meu Deus é minha rocha, em quem encontro proteção. Ele é meu escudo, o poder que me salva e meu lugar seguro." O salmista de Salmo 9 também reconhece a proteção de Deus contra seus inimigos, o que é enfatizado neste versículo.
* Salmo 31:7: "Eu confio em ti, Senhor; digo: 'Tu és o meu Deus'." Salmo 9 é uma expressão de confiança no Senhor, e este versículo destaca a importância da confiança em Deus para a salvação e a proteção.
* Salmo 34:17: "Os justos clamam por ajuda, e o Senhor os ouve; ele os livra de todas as suas tribulações." O salmista de Salmo 9 também clama por ajuda e é salvo pelo Senhor, assim como os justos mencionados neste versículo.
* Salmo 106:1: "Aleluia! Deem graças ao Senhor, pois ele é bom; seu amor dura para sempre." O Salmo 9 é um salmo de ação de graças no qual o salmista expressa sua gratidão a Deus por sua proteção e salvação. Este versículo enfatiza a importância de dar graças a Deus por suas bênçãos.
****

[[v21-9-1]]

^<<v21-9-1,1>>^ Ao mestre do coro. Segundo a melodia do cântico "Mút labben". Salmo. De Davide.

[[v21-9-2]]

^<<v21-9-2,2>>^ Eu te louvarei. Senhor, com todo o meu coração contarei todas as tuas maravilhas.

[[v21-9-3]]

^<<v21-9-3,3>>^ Alegrar-me-ei e regozijar-me-ei em ti, cantarei salmos ao teu nome, ó (Deus) Altíssimo,

[[v21-9-4]]

^<<v21-9-4,4>>^ porque os meus inimigos retrocederam, à tua vista caíram e pereceram.

[[v21-9-5]]

^<<v21-9-5,5>>^ Com efeito, defendeste o meu direito e a minha causa, sentaste-te sobre o trono, como justo juiz.

[[v21-9-6]]

^<<v21-9-6,6>>^ Repreendeste as nações, exterminaste o ímpio, apagaste o seu nome para sempre.

[[v21-9-7]]

^<<v21-9-7,7>>^ Os inimigos desfaleceram, arruinados para sempre, e destruíste as suas cidades: a memória deles pereceu.

[[v21-9-8]]

^<<v21-9-8,8>>^ Porém o Senhor permanece eternamente, preparou o seu trono para exercer o juízo.

[[v21-9-9]]

^<<v21-9-9,9>>^ Ele mesmo julgará o mundo com justiça, julgará os povos com equidade.

[[v21-9-10]]

^<<v21-9-10,10>>^ E o Senhor será refúgio do oprimido, refúgio oportuno nas horas de angústia.

[[v21-9-11]]

^<<v21-9-11,11>>^ E em ti esperarão os que conhecem o teu nome, porque tu, Senhor, não desamparas os que te buscam.

[[v21-9-12]]

^<<v21-9-12,12>>^ Cantai ao Senhor, que habita em Sião, divulgai entre os povos as suas obras,

[[v21-9-13]]

^<<v21-9-13,13>>^ porque, vingando o sangue (dos seus servos, mostrou que) se lembrou deles, não se esqueceu do clamor dos pobres.

[[v21-9-14]]

^<<v21-9-14,14>>^ Tem compaixão de mim, Senhor: vê a aflição que sofro da parte dos meus inimigos, arranca-me das portas da morte,

[[v21-9-15]]

^<<v21-9-15,15>>^ para que publique todos os teus louvores às portas da filha de Sião, e exulte com o teu auxilio.

[[v21-9-16]]

^<<v21-9-16,16>>^ As gentes (que me perseguiam) caíram na fossa que cavaram, no mesmo laço, que esconderam (para me prenderem), ficou preso a seu pé.

[[v21-9-17]]

^<<v21-9-17,17>>^ (Deste modo) o Senhor manifestou-se, fez justiça; nas obras das suas (próprias) mãos ficou enredado o pecador.

[[v21-9-18]]

^<<v21-9-18,18>>^ Retirem-se para o túmulo os pecadores, todas as gentes que se esqueceram de Deus.

[[v21-9-19]]

^<<v21-9-19,19>>^ Com efeito, não estará para sempre esquecido o pobre, nem a confiança dos infelizes será para sempre frustrada.

[[v21-9-20]]

^<<v21-9-20,20>>^ Levanta-te, Senhor, não prevaleça o homem (malvado), sejam julgadas as gentes em tua presença.

[[v21-9-21]]

^<<v21-9-21,21>>^ Ó Senhor, incute-lhes terror, para que as gentes saibam que são homens.

[[v21-9-22]]

^<<v21-9-22,22>>^ Por que te conservas afastado ó Senhor, te escondes nas horas de angústia, (10,1)

[[v21-9-23]]

^<<v21-9-23,23>>^ enquanto o ímpio se ensoberbece e o mísero é maltratado, é colhido nos embustes que aquele lhe armou? (10,2)

[[v21-9-24]]

^<<v21-9-24,24>>^ Porque o pecador gloria-se da sua cobiça, e, salteador, blasfema, despreza o Senhor. (10,3)

[[v21-9-25]]

^<<v21-9-25,25>>^ Diz o ímpio na arrogância do seu espírito: "Não castigará; Deus não existe": eis todos os pensamentos. (10,4) (ver nota)

[[v21-9-26]]

^<<v21-9-26,26>>^ Prósperos são os seus caminhos a toda a hora; muito afastados estão os teus juízos do seu pensamento; escarnece de todos os seus contrários. (10,5)

[[v21-9-27]]

^<<v21-9-27,27>>^ Diz no seu coração: "Não serei abalado: de geração em geração não serei infeliz." (10,6)

[[v21-9-28]]

^<<v21-9-28,28>>^ A sua boca está cheia de maldição, de fraude e de dolo; debaixo da sua língua estão a opressão e o vexame (para o próximo). (10,7)

[[v21-9-29]]

^<<v21-9-29,29>>^ Põe-se de emboscada, junto dos povoados, e, às escondidas, mata o inocente; os seus olhos espiam o pobre. (10,9)

[[v21-9-30]]

^<<v21-9-30,30>>^ Arma ciladas nos esconderijos, como o leão na sua cova; arma ciladas para arrebatar o mísero: arrebata o mísero e o arrasta para a sua rede. (10,9)

[[v21-9-31]]

^<<v21-9-31,31>>^ Inclina-se, debruça-se por terra, e com a sua violência caem os infelizes. (10,10)

[[v21-9-32]]

^<<v21-9-32,32>>^ Diz no seu coração: "Deus esqueceu-se, apartou o seu rosto, não vê jamais." (10,11)

[[v21-9-33]]

^<<v21-9-33,33>>^ Levanta-te, Senhor Deus, ergue a tua mão! não te esqueças dos pobres! (10,12)

[[v21-9-34]]

^<<v21-9-34,34>>^ Por que razão despreza o ímpio a Deus, e diz no seu coração: "Não castigará?" (10,13)

[[v21-9-35]]

^<<v21-9-35,35>>^ Porém tu vês: consideras o trabalho e a dor (do oprimido), para os tomar nas tuas mãos. A ti se abandona o infeliz, tu és o amparo do órfão. (10,14)

[[v21-9-36]]

^<<v21-9-36,36>>^ Quebra o braço do pecador e do mau; castiga a sua malícia, e não subsistirá. (10,15)

[[v21-9-37]]

^<<v21-9-37,37>>^ O Senhor é rei pelos séculos dos séculos, as gentes foram exterminadas da sua terra. (10,16)

[[v21-9-38]]

^<<v21-9-38,38>>^ Ouviste, Senhor, o desejo dos infelizes, confortaste o seu coração, deste-lhes ouvidos, (10,17)

[[v21-9-39]]

^<<v21-9-39,39>>^ para protegeres o direito do órfão e do oprimido, e para que o homem terreno não volte a incutir terror. (10,18)

'''

xref:021-salmos/021-salmos-008.adoc#v21-8-0[&#60; Capítulo Anterior] | <<v21-9-0,Topo>> | xref:021-salmos/021-salmos-010.adoc#v21-10-0[Próximo Capítulo &#62;]