include::./index.adoc[]

[[v21-131-0]]
=== Salmos, 131
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O Salmo 131 é um salmo de humildade e confiança em Deus. Nele, o salmista expressa sua confiança em Deus e sua submissão à Sua vontade. Abaixo estão cinco versículos relacionados aos temas abordados neste salmo:
* Provérbios 3:5-6: "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas." Este versículo fala sobre a confiança em Deus e a submissão à Sua vontade, que são temas importantes no Salmo 131.
* Mateus 18:4: "Portanto, quem se tornar humilde como este menino, este é o maior no Reino dos céus." A humildade é outro tema importante no Salmo 131, e este versículo enfatiza a importância da humildade para a vida cristã.
* Filipenses 4:6: "Não se preocupem com nada, mas em todas as orações peçam a Deus o que vocês precisam e orem sempre com o coração agradecido." A confiança em Deus e a importância da oração são temas abordados no Salmo 131, e este versículo destaca a importância de orar com gratidão e confiança.
* Tiago 4:10: "Humilhem-se diante do Senhor, e ele os exaltará." Este versículo enfatiza a importância da humildade e submissão diante de Deus, o que é um tema central do Salmo 131.
* 1 Pedro 5:6: "Portanto, humilhem-se debaixo da poderosa mão de Deus, para que ele os exalte no tempo devido." Este versículo novamente enfatiza a importância da humildade e submissão diante de Deus, e destaca que Deus é aquele que exalta no tempo certo.
****

[[v21-131-1]]

^<<v21-131-1,1>>^ Cântico das subidas. Lembra-te, Senhor, em favor de Davide, de toda a sua solicitude: (ver nota)

[[v21-131-2]]

^<<v21-131-2,2>>^ (lembra-te) como fez este juramento ao Senhor, esta promessa ao poderoso de Jacob:

[[v21-131-3]]

^<<v21-131-3,3>>^ "Não entrarei na tenda da minha casa, não subirei ao estrado do meu leito,

[[v21-131-4]]

^<<v21-131-4,4>>^ não darei sono aos meus olhos, nem repouso às minhas pálpebras,

[[v21-131-5]]

^<<v21-131-5,5>>^ até que encontre um lugar para o Senhor, uma morada para o Poderoso de Jacob."

[[v21-131-6]]

^<<v21-131-6,6>>^ Nós ouvimos dizer que a arca estava em Efrata; fomos achá-la nos campos de laar.

[[v21-131-7]]

^<<v21-131-7,7>>^ Entremos na sua morada, prostremo-nos ante o escabelo de seus pés.

[[v21-131-8]]

^<<v21-131-8,8>>^ Levanta-te, Senhor, para o lugar do teu repouso, tu e a arca da tua majestade.

[[v21-131-9]]

^<<v21-131-9,9>>^ Revistam-se os teus sacerdotes de justiça (ou santidade), e dêem os teus fiéis largas à sua alegria.

[[v21-131-10]]

^<<v21-131-10,10>>^ Por amor de Davide, teu servo, não rejeites o rosto do teu ungido.

[[v21-131-11]]

^<<v21-131-11,11>>^ Jurou o Senhor a Davide uma promessa firme, que jamais retratará: "Um descendente da tua linhagem porei sobre o teu trono.

[[v21-131-12]]

^<<v21-131-12,12>>^ Se os teus filhos guardarem a minha aliança e os preceitos que eu lhes ensinar, também os seus filhos para sempre se sentarão sobre o teu trono."

[[v21-131-13]]

^<<v21-131-13,13>>^ Com efeito o Senhor escolheu Sião, desejou-a para sua habitação:

[[v21-131-14]]

^<<v21-131-14,14>>^ "Este é o meu repouso para sempre, aqui habitarei, porque a desejei;

[[v21-131-15]]

^<<v21-131-15,15>>^ abençoarei copiosamente o seu alimento, saciarei de pão os seus pobres.

[[v21-131-16]]

^<<v21-131-16,16>>^ Vestirei os seus sacerdotes de salvação, e os seus santos exultarão de júbilo.

[[v21-131-17]]

^<<v21-131-17,17>>^ Ali dilatarei o poder de Davide, prepararei uma lâmpada para o meu ungido"

[[v21-131-18]]

^<<v21-131-18,18>>^ Cobrirei de confusão os seus inimigos, enquanto sobre ele brilhará o meu diadema,"

'''

xref:021-salmos/021-salmos-130.adoc#v21-130-0[&#60; Capítulo Anterior] | <<v21-131-0,Topo>> | xref:021-salmos/021-salmos-132.adoc#v21-132-0[Próximo Capítulo &#62;]