include::./index.adoc[]

[[v21-49-0]]
=== Salmos, 49
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Salmo 49 aborda a sabedoria e a incerteza da riqueza e da mortalidade humana. O salmista nos convida a ouvir seus conselhos e refletir sobre a transitoriedade dos bens materiais e a importância de buscar a verdadeira riqueza, que é encontrada em Deus. Abaixo estão cinco versículos relacionados a esses temas:
* Provérbios 11:4: "Não servirão de nada as riquezas no dia da ira, mas a justiça livra da morte." Este verso destaca a importância da justiça e da retidão, que são mais valiosas do que a riqueza.
* Eclesiastes 5:10: "Quem ama o dinheiro jamais terá o suficiente; quem ama as riquezas jamais ficará satisfeito com os seus rendimentos. Isso também não faz sentido." Este verso adverte sobre a ilusão de que a riqueza pode trazer felicidade e realização pessoal.
* Mateus 16:26: "De que adianta alguém ganhar o mundo inteiro e perder a sua alma? Ou, o que alguém poderia dar em troca de sua alma?" Este verso nos lembra que a verdadeira riqueza é encontrada em nossa relação com Deus e em nossa vida eterna com Ele.
* Tiago 1:10-11: "Mas o rico deve orgulhar-se em sua humilhação, pois ele passará como a flor do campo. O sol se levanta, e o sol se põe, e com pressa volta ao lugar de onde se levanta." Este verso nos lembra que a riqueza e a posição social são transitórias e que devemos encontrar nossa alegria e satisfação em Deus.
* 1 Timóteo 6:17-19: "Ordene aos que são ricos no presente mundo que não sejam arrogantes nem ponham sua esperança na incerteza da riqueza, mas em Deus, que nos dá ricamente todas as coisas para a nossa satisfação. Ordene-lhes que façam o bem, que sejam ricos em boas obras, generosos e prontos a compartilhar." Este verso nos encoraja a usar nossa riqueza para ajudar os outros e para a glória de Deus, ao invés de nos orgulharmos dela ou dependermos dela para nossa segurança e satisfação.
****

[[v21-49-1]]

^<<v21-49-1,1>>^ Salmo. De Asaf. Deus Senhor falou e convocou a terra desde o oriente até ao ocidente.

[[v21-49-2]]

^<<v21-49-2,2>>^ Desde Sião, cheia de beleza, Deus resplandeceu;

[[v21-49-3]]

^<<v21-49-3,3>>^ ele, o nosso Deus, vem e não ficará em silêncio. Um fogo devorador o precede, e ruge a tempestade em torno dele.

[[v21-49-4]]

^<<v21-49-4,4>>^ Chama do alto os céus e a terra, para julgar o seu povo:

[[v21-49-5]]

^<<v21-49-5,5>>^ "Congregai diante de mim os meus santos, que firmaram a minha aliança com o sacrifício."

[[v21-49-6]]

^<<v21-49-6,6>>^ E os céus anunciam a sua justiça, porquanto o próprio Deus é o juiz.

[[v21-49-7]]

^<<v21-49-7,7>>^ "Ouve, meu povo, e eu falarei, ouve, Israel, e eu darei testemunho contra ti: Deus, o teu Deus sou eu.

[[v21-49-8]]

^<<v21-49-8,8>>^ Não te repreendo por causa dos teus sacrifícios, porque os teus holocaustos estão sempre diante de mim.

[[v21-49-9]]

^<<v21-49-9,9>>^ Não receberei de tua casa bezerro, nem cabritos dos teus rebanhos:

[[v21-49-10]]

^<<v21-49-10,10>>^ em verdade são minhas todas as feras das selvas, milhares de animais há nos meus montes.

[[v21-49-11]]

^<<v21-49-11,11>>^ Conheço (como seu dono que sou) todas as aves do céu, e tudo o que se move nos campos me é conhecido.

[[v21-49-12]]

^<<v21-49-12,12>>^ Se tiver fome, não to direi a ti, porque meu é o universo e aquilo que o enche.

[[v21-49-13]]

^<<v21-49-13,13>>^ Porventura comerei a carne dos touros, ou beberei o sangue dos cabritos?

[[v21-49-14]]

^<<v21-49-14,14>>^ Oferece a Deus um sacrifício de louvor, e paga ao Altíssimo os teus votos.

[[v21-49-15]]

^<<v21-49-15,15>>^ E invoca-me no dia da angústia: livrar-te-ei, e tu me honrarás."

[[v21-49-16]]

^<<v21-49-16,16>>^ Mas ao pecador diz Deus: "Porque relatas tu os meus preceitos, e tens (constantemente) a minha aliança na tua boca?

[[v21-49-17]]

^<<v21-49-17,17>>^ Tu que aborreces a disciplina, e rejeitaste as minhas palavras

[[v21-49-18]]

^<<v21-49-18,18>>^ Se vias um ladrão, corrias com ele, e fazias sociedade com os adúlteros.

[[v21-49-19]]

^<<v21-49-19,19>>^ Soltavas a tua boca para o mal, e a tua língua urdia enganos.

[[v21-49-20]]

^<<v21-49-20,20>>^ Estando sentado, falavas contra teu irmão, e difamavas o filho da tua mãe.

[[v21-49-21]]

^<<v21-49-21,21>>^ Isto fizeste, e eu hei-de calar-me? Julgaste que eu sou semelhante a ti? Arguir-te-ei e porei (tudo) diante dos teus olhos.

[[v21-49-22]]

^<<v21-49-22,22>>^ Entendei isto, vós que vos esqueceis de Deus, não suceda que vos arrebate, e não haja quem vos salve.

[[v21-49-23]]

^<<v21-49-23,23>>^ O que oferece sacrifício de louvor (é o que) me honra, e ao que caminha com rectidão mostrarei a salvação de Deus."

'''

xref:021-salmos/021-salmos-048.adoc#v21-48-0[&#60; Capítulo Anterior] | <<v21-49-0,Topo>> | xref:021-salmos/021-salmos-050.adoc#v21-50-0[Próximo Capítulo &#62;]