include::./index.adoc[]

[[v21-101-0]]
=== Salmos, 101
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O Salmo 101 é uma oração de um líder justo que busca viver de acordo com a vontade de Deus e governar com integridade. Ele se compromete a ser vigilante em sua conduta e a não permitir a presença do mal em sua vida. Alguns temas presentes nesse Salmo incluem justiça, integridade, fidelidade, pureza e liderança. Seguem abaixo cinco versículos relacionados com esses temas:
* Provérbios 20:28: "A bondade e a fidelidade preservam o rei; pela bondade ele mantém o seu trono." Este versículo destaca a importância da bondade e da fidelidade na liderança, o que está em consonância com o compromisso do salmista em ser um líder justo.
* Salmos 18:25: "Ao fiel te mostras fiel, ao íntegro, íntegro." A integridade é um valor muito importante para o salmista, que se esforça para governar com honestidade e justiça. Esse versículo afirma a promessa de Deus de recompensar a integridade daqueles que o seguem.
* Provérbios 4:23: "Sobre tudo o que se deve guardar, guarda o coração, porque dele procedem as fontes da vida." O salmista reconhece a importância de manter o coração puro e livre de pensamentos e atitudes más. Ele se compromete a vigiar sua conduta e a não permitir que o mal entre em sua vida.
* Salmos 26:1: "Faze-me justiça, Senhor, pois tenho andado na minha integridade; e confio no Senhor sem vacilar." O salmista confia em Deus para fazer justiça e reconhece sua própria integridade. Ele busca viver de acordo com a vontade de Deus e confia que será recompensado por isso.
* Tiago 1:27: "A religião pura e sem mácula, para com o nosso Deus e Pai, é esta: visitar os órfãos e as viúvas nas suas tribulações e guardar-se isento da corrupção do mundo." Esse versículo destaca a importância da pureza e da compaixão, valores que estão presentes no Salmo 101. O salmista se compromete a ser um líder justo e a não permitir que a corrupção do mundo o contamine.
****

[[v21-101-1]]

^<<v21-101-1,1>>^ Súplicas dum aflito que, desalentado, derrama a sua angústia diante do Senhor, (ver nota)

[[v21-101-2]]

^<<v21-101-2,2>>^ Senhor, ouve a minha oração, chegue a ti o meu clamor.

[[v21-101-3]]

^<<v21-101-3,3>>^ Não me escondas o teu rosto no dia da minha angústia. Inclina para mim o teu ouvido; quando eu te invocar, ouve-me prontamente.

[[v21-101-4]]

^<<v21-101-4,4>>^ Porque os meus dias dissipam-se como fumo, e os meus ossos ardem como fogo.

[[v21-101-5]]

^<<v21-101-5,5>>^ Queimado, como a erva, o meu coração fica ressequido, esqueço-me até de comer o meu pão.

[[v21-101-6]]

^<<v21-101-6,6>>^ A força de soltar gemidos, os meus ossos estão pegados à pele.

[[v21-101-7]]

^<<v21-101-7,7>>^ Sou semelhante ao pelicano do deserto, tornei-me como uma coruja entre ruínas.

[[v21-101-8]]

^<<v21-101-8,8>>^ Não durmo e suspiro, como um pássaro solitário no telhado.

[[v21-101-9]]

^<<v21-101-9,9>>^ Continuamente me insultam os meus inimigos; enfurecidos contra mim, proferem imprecações em meu nome.

[[v21-101-10]]

^<<v21-101-10,10>>^ Porque eu como cinza, como se fosse pão, e misturo a minha bebida com lágrimas,

[[v21-101-11]]

^<<v21-101-11,11>>^ por causa da tua indignação e do teu furor, pois me levantaste e me arrojaste.

[[v21-101-12]]

^<<v21-101-12,12>>^ Os meus dias são semelhantes a uma sombra prolongada, e eu vou-me secando como erva.

[[v21-101-13]]

^<<v21-101-13,13>>^ Ao contrário, tu, Senhor, permaneces para sempre, e o teu nome por toda as gerações.

[[v21-101-14]]

^<<v21-101-14,14>>^ Levanta-te, tem piedade de Sião, porque é tempo de teres piedade dela, visto que chegou a hora.

[[v21-101-15]]

^<<v21-101-15,15>>^ De facto os teus servos amam as pedras dela (Sião) e sentem compaixão das suas ruínas.

[[v21-101-16]]

^<<v21-101-16,16>>^ E as gentes reverenciarão o teu nome, Senhor, e todos os reis da terra a tua glória:

[[v21-101-17]]

^<<v21-101-17,17>>^ Quando o Senhor tiver reconstruído Sião, se tiver manifestado na sua glória,

[[v21-101-18]]

^<<v21-101-18,18>>^ se tiver voltado para a súplica dos indigentes, nem tiver rejeitado a sua oração.

[[v21-101-19]]

^<<v21-101-19,19>>^ Sejam escritas estas coisas para a geração futura, e o povo, que há-de ser criado, louve o Senhor.

[[v21-101-20]]

^<<v21-101-20,20>>^ Porque olhou do seu santuário excelso, o Senhor do céu olhou sobre a terra,

[[v21-101-21]]

^<<v21-101-21,21>>^ para ouvir os gemidos dos encarcerados, para libertar os condenados à morte.

[[v21-101-22]]

^<<v21-101-22,22>>^ a fim de que em Sião seja proclamado o nome do Senhor, e o seu louvor em Jerusalém,

[[v21-101-23]]

^<<v21-101-23,23>>^ quando os povos se juntarem todos e os reinos para servirem ao Senhor.

[[v21-101-24]]

^<<v21-101-24,24>>^ Consumiu as minhas forças no caminho, encurtou os meus dias.

[[v21-101-25]]

^<<v21-101-25,25>>^ Eu digo: Meu Deus, não me leves na metade dos meus dias; os teus anos duram por todas as gerações. (ver nota)

[[v21-101-26]]

^<<v21-101-26,26>>^ Nos princípios, fundaste a terra, e o céu é obra das tuas mãos.

[[v21-101-27]]

^<<v21-101-27,27>>^ Estas coisas perecerão, mas tu permanecerás, e todas envelhecerão como um vestido. Muda-las como uma vestidura, e ficam mudadas

[[v21-101-28]]

^<<v21-101-28,28>>^ tu porém és sempre o mesmo, e os teus anos não têm fim.

[[v21-101-29]]

^<<v21-101-29,29>>^ Os filhos dos teus servos habitarão seguros (em Jerusalém), e a sua posteridade subsistirá diante de ti.

'''

xref:021-salmos/021-salmos-100.adoc#v21-100-0[&#60; Capítulo Anterior] | <<v21-101-0,Topo>> | xref:021-salmos/021-salmos-102.adoc#v21-102-0[Próximo Capítulo &#62;]