include::./index.adoc[]

[[v10-15-0]]
=== II Samuel, 15
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* 2 Samuel 15 fala sobre a conspiração de Absalão para se tornar rei em lugar de Davi. Ele engana o povo, obtém seguidores e conquista o coração de muitos israelitas. Davi, ao tomar conhecimento da conspiração, foge de Jerusalém com sua família e seus seguidores. A seguir, são apresentados cinco versículos relacionados com os temas abordados em 2 Samuel 15:
* Salmos 3:1-2: "Ó Senhor, como se têm multiplicado os meus adversários! São muitos os que se levantam contra mim. Muitos dizem da minha alma: Não há salvação para ele em Deus." Este salmo, escrito por Davi, expressa sua angústia diante da conspiração de Absalão e da ameaça que ele representa ao seu reinado.
* Salmos 41:9: "Até o meu amigo íntimo, em quem eu confiava, que comia do meu pão, levantou contra mim o seu calcanhar." Davi lamenta a traição de Aitofel, um dos seus conselheiros, que passou para o lado de Absalão e conspirou contra ele.
* Salmos 55:12-14: "Porque não era um inimigo que me afrontava; então eu o teria suportado; nem era o que me odiava que se engrandecia contra mim, porque dele me teria escondido; mas eras tu, homem meu igual, meu guia e meu íntimo amigo. Consultávamos juntos suavemente, e andávamos na casa de Deus como companheiros." Davi se refere a Aitofel, seu antigo conselheiro e amigo, que se uniu à conspiração de Absalão e traiu a sua confiança.
* Salmos 59:1-3: "Livra-me, meu Deus, dos meus inimigos; defende-me daqueles que se levantam contra mim. Livra-me dos que praticam a iniquidade, e salva-me dos homens sanguinários. Pois eis que põem ciladas à minha alma; os fortes se ajuntam contra mim, não por transgressão minha ou por pecado meu, ó Senhor." Davi clama a Deus por proteção diante da ameaça representada por Absalão e seus seguidores.
* Salmos 63:1: "Ó Deus, tu és o meu Deus; cedo te buscarei; a minha alma tem sede de ti; a minha carne te deseja muito em uma terra seca e cansada, onde não há água." Este salmo expressa a devoção de Davi a Deus, mesmo diante das dificuldades enfrentadas na fuga de Absalão.
****

[[v10-15-1]]

^<<v10-15-1,1>>^ Depois disto mandou Absalão aprontar para si carros e cavaleiros, e cinqüenta homens, que andassem diante dele.

[[v10-15-2]]

^<<v10-15-2,2>>^ Levantava-se Absalão de manhã cedo, punha-se à entrada da porta (da cidade) e, a todo o que tinha algum negócio e vinha pedir justiça ao rei, Absalão chamava-o a si, e dizia-lhe: De que cidade és tu? Ele respondia: Eu, teu servo, sou de tal tribo de Israel.

[[v10-15-3]]

^<<v10-15-3,3>>^ Absalão dizia-lhe: As tuas pretensões parecem-me razoáveis e justas, mas não há pessoa constituída pelo rei para te ouvir. E Absalão acrescentava:

[[v10-15-4]]

^<<v10-15-4,4>>^ Oh! quem me dera ser juiz desta terra, para que viessem a mim todos os que têm negócios, e eu os decidisse segundo a justiça

[[v10-15-5]]

^<<v10-15-5,5>>^ Além disso, quado se aproximava dele algum homem para o saudar, estendia a sua mão e, abraçando-o, o beijava.

[[v10-15-6]]

^<<v10-15-6,6>>^ Fazia isto com todos os de Israel, que vinham para que o rei os ouvisse e julgasse, e (deste modo) atraía a si o coração dos homens de Israel.

[[v10-15-7]]

^<<v10-15-7,7>>^ Passados quatro anos, Absalão disse ao rei Davide: Permite-me que vá a Hebron para cumprir os votos que fiz ao Senhor,

[[v10-15-8]]

^<<v10-15-8,8>>^ porque, quando o teu servo estava em Gessur da Síria, fez este voto: Se o Senhor me reconduzir a Jerusalém, eu oferecerei um sacrifício ao Senhor.

[[v10-15-9]]

^<<v10-15-9,9>>^ O rei Davide disse-lhe: Vai em paz. Ele saiu, e foi para Hebron.

[[v10-15-10]]

^<<v10-15-10,10>>^ Absalão enviou emissários por todas as tribos de israel, dizendo: Logo que ouvirdes o som da trombeta, dizei: Absalão reina em Hebron.

[[v10-15-11]]

^<<v10-15-11,11>>^ Com Absalão foram duzentos homens de Jerusalém, convocados por ele, que o seguiam com simplicidade do coração, sem nada saberem dos seus desígnios.

[[v10-15-12]]

^<<v10-15-12,12>>^ Absalão mandou também chamar Aquitofel, Gilonita, conselheiro de Davide, à sua cidade de Gilo. Enquanto imolava as vítimas, fez-se um a poderosa conjuração, e crescia o número de gente que tomava o partido de Absalão.

[[v10-15-13]]

^<<v10-15-13,13>>^ Chegou pois um mensageiro a Davide, dizendo: Todo o Israel segue Absalão de todo o coração.

[[v10-15-14]]

^<<v10-15-14,14>>^ Davide disse aos seus criados, que estavam com ele em Jerusalém: Levantai-vos, fujamos, porque não poderemos escapar das mãos de Absalão; apressai-vos a sair, não suceda que ele, chegando, nos apanhe, traga sobre nós a ruína e mande passar a cidade a fio da espada.

[[v10-15-15]]

^<<v10-15-15,15>>^ Os servos do rei disseram-lhe: Nós, teus servos, executaremos de boa vontade tudo o que mandar o rei nosso senhor.

[[v10-15-16]]

^<<v10-15-16,16>>^ Saiu, pois, o rei, a pé, com toda a sua família, e deixou dez das suas mulheres secundárias para guardarem o palácio.

[[v10-15-17]]

^<<v10-15-17,17>>^ Tendo saído o rei, com todo o Israel a pé, parou, estando já longe de sua casa.

[[v10-15-18]]

^<<v10-15-18,18>>^ Todos os seus servos iam aos lados dele; (porém) as legiões dos Cereteus e Felesteus, e todos os Geteus, fortes guerreiros, em número de seiscentos homens a pé, que o tinham seguido desde Get, iam adiante do rei.

[[v10-15-19]]

^<<v10-15-19,19>>^ O rei dIsse a Etai Geteu: Por que vens tu conosco? Volta, e vai viver com o (novo) rei, porque és estrangeiro, estás fora da tua terra.

[[v10-15-20]]

^<<v10-15-20,20>>^ Chegaste ontem, e hoje vou fazer que andes errante conosco, quando eu próprio ignoro para onde irei? Volta, e leva contigo os teus irmãos, e o Senhor usará contigo de misericórdia e de justiça, porque deste mostras da tua gratidão e fidelidade.

[[v10-15-21]]

^<<v10-15-21,21>>^ Etai respondeu ao rei, dizendo: Viva o Senhor, e viva o rei meu senhor, que, em qualquer lugar em que tu te encontrares, ó rei meu senhor, quer seja na morte quer na vida, aí se encontrará o teu servo.

[[v10-15-22]]

^<<v10-15-22,22>>^ Davide disse a Etai: Vem e passa (o Cedron). Etai Geteu passou, com todos os homens que estavam com ele e com toda a sua família.

[[v10-15-23]]

^<<v10-15-23,23>>^ Todos choravam em alta voz, enquanto passava o povo; e o rei também passava a torrente do Cedron, e todo o povo tomava o caminho que olha para o deserto.

[[v10-15-24]]

^<<v10-15-24,24>>^ Veio também o pontífice Sadoc, e com ele todos os levitas, que levavam a arca do Testamento de Deus. Assentaram a arca de Deus, enquanto Abiatar subia, e até que tivesse passado todo o povo que tinha saído da cidade.

[[v10-15-25]]

^<<v10-15-25,25>>^ O rei disse a Sadoc: Torna a levar a arca de Deus para a cidade; se eu achar graça diante dos olhos do Senhor, ele me reconduzirá e fará que eu veja a sua arca e o seu tabernáculo.

[[v10-15-26]]

^<<v10-15-26,26>>^ Se ele porém me disser: Tu não me agradas eu estou pronto: faça de mim o que bem lhe parecer.

[[v10-15-27]]

^<<v10-15-27,27>>^ O rei disse ao pontífice Sadoc: ó vidente, volta em paz para a cidade com Aquimaas, teu filho, e Jónatas, filho de Abiatar; estes vossos dois filhos estejam convosco.

[[v10-15-28]]

^<<v10-15-28,28>>^ Eu vou esconder-me nas campinas do deserto, até que vós me mandeis novas do estado das coisas.

[[v10-15-29]]

^<<v10-15-29,29>>^ Sadoc e Abiatar tornaram a levar para Jerusalém a arca de Deus, e lá ficaram.

[[v10-15-30]]

^<<v10-15-30,30>>^ Entretanto Davide ia subindo a encosta do Monte das Oliveiras, e subia-a chorando, caminhando com os pés descalços e a cabeça coberta; todo o povo que ia com ele, subia também com cabeça coberta, a chorar.

[[v10-15-31]]

^<<v10-15-31,31>>^ Foi referido a Davide que Aquitofel também entrava na conjuração de Absalão, e David e disse: Peço-te, Senhor, que tornes insensato o conselho de Aquitofel.

[[v10-15-32]]

^<<v10-15-32,32>>^ Quando Davide chegou ao cume do monte, lá onde se adora o Senhor, veio ao seu encontro Chusai Araquita, com as vestes rasgadas e a cabeça coberta de pó.

[[v10-15-33]]

^<<v10-15-33,33>>^ Davide disse-lhe: Se vieres comigo, ser-me-ás pesado;

[[v10-15-34]]

^<<v10-15-34,34>>^ mas, se voltares para a cidade e disseres a Absalão: Eu, ó rei, sou teu servo, e eu te servirei a ti, como servi a teu pai então desconcertarás (em meu favor) os conselhos de Aquitofel.

[[v10-15-35]]

^<<v10-15-35,35>>^ Tu tens contigo os sacerdotes Sadoc e Abiatar; tudo o que ouvires na casa do rei, o farás saber aos sacerdotes Sadoc e Abiatar.

[[v10-15-36]]

^<<v10-15-36,36>>^ Com eles estão os seus dois filhos, Aquimaas, filho de Sadoc, e Jónatas, filho de Abiatar; por eles me avisareis de tudo o que ouvirdes.

[[v10-15-37]]

^<<v10-15-37,37>>^ Chusai, amigo de Davide, voltou à cidade, ao mesmo tempo que Absalão fazia a sua entrada em Jerusalém.

'''

xref:010-ii-samuel/010-ii-samuel-014.adoc#v10-14-0[&#60; Capítulo Anterior] | <<v10-15-0,Topo>> | xref:010-ii-samuel/010-ii-samuel-016.adoc#v10-16-0[Próximo Capítulo &#62;]