include::./index.adoc[]

[[v10-24-0]]
=== II Samuel, 24
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* No capítulo 24 de 2 Samuel, Davi ordena que um censo seja realizado em Israel e Judá, o que desagrada a Deus. Como punição, Deus envia uma praga que mata muitos israelitas. Davi se arrepende e oferece sacrifícios para apaziguar a ira de Deus. Abaixo estão cinco versículos relacionados aos temas abordados no capítulo:
* 1 Crônicas 21:7: "Isso desagradou a Deus, e ele feriu Israel." Este verso mostra a ira de Deus sobre o censo que Davi ordenou.
* 2 Samuel 24:10: "Davi sentiu remorsos depois de haver contado o povo e disse ao Senhor: 'Cometi um grande erro. Agora, Senhor, perdoa a culpa deste teu servo, pois agi de modo insensato'." Este verso mostra o arrependimento de Davi por sua decisão de contar o povo.
* 2 Samuel 24:15: "Então o Senhor mandou um anjo, e ele destruiu todo o exército dos assírios, inclusive o acampamento e o povo." Este verso mostra como Deus interveio para salvar seu povo da praga que ele havia enviado.
* 2 Samuel 24:24: "Não! Eu quero comprá-lo pelo seu valor justo. Não oferecerei ao Senhor, meu Deus, holocaustos que não me custem nada." Este verso mostra a atitude de Davi em relação aos sacrifícios que ofereceu a Deus como forma de arrependimento.
* 2 Samuel 24:25: "Ali Davi construiu um altar ao Senhor e ofereceu holocaustos e ofertas de paz. Então o Senhor atendeu às suas orações em favor da terra, e a praga em Israel foi interrompida." Este verso mostra como as orações de Davi e seus sacrifícios foram aceitos por Deus e como a praga foi interrompida.
****

[[v10-24-1]]

^<<v10-24-1,1>>^ O furor do Senhor tornou-se de novo a acender contra Israel e excitou David e contra ele, permitindo que dissesse (cheio de vaidade): Vai e faze o recenseamento de Israel, e de Judá.

[[v10-24-2]]

^<<v10-24-2,2>>^ Disse, pois, Davide a Joab, general do seu exército; Percorre todas as tribos de Israel, desde Dan até Bersabé, e faze o recenseamento do povo, para eu saber o seu número.

[[v10-24-3]]

^<<v10-24-3,3>>^ Joab respondeu ao rei; O Senhor teu Deus queira multiplicar o teu povo outro tanto do que agora é, e ainda cem vezes mais aos olhos do rei meu senhor, mas, que pretende o rei meu senhor com isto?

[[v10-24-4]]

^<<v10-24-4,4>>^ Todavia a ordem do rei prevaleceu sobre as representações de Joab e dos generais do exército. Então saiu Joab da presença do rei com os primeiros oficiais do exército, a contar o povo de Israel.

[[v10-24-5]]

^<<v10-24-5,5>>^ Tendo eles passado o Jordão, foram a Aroer, ao lado direito da cidade que está no vale de Gad

[[v10-24-6]]

^<<v10-24-6,6>>^ foram até Jazer, passaram a Galaad e à terra baixa de Hodsl, e chegaram aos bosques de Dan. Caminhando pelo contorno de Sidónia,

[[v10-24-7]]

^<<v10-24-7,7>>^ passaram perto das muralhas de Tiro, e por toda a terra dos Heveus e dos Cananeus, chegando até Bersabé, parte meridional de Judá.

[[v10-24-8]]

^<<v10-24-8,8>>^ Tendo percorrido todo o país, voltaram a Jerusalém, depois de nove meses e vinte dias.

[[v10-24-9]]

^<<v10-24-9,9>>^ Deu Joab ao rei a lista do povo; acharam-se em Israel oitocentos mil homens robustos, capazes de puchar pela espada, e em Judá, quinhentos mil combatentes.

[[v10-24-10]]

^<<v10-24-10,10>>^ Depois que foi contado o povo, sentiu Davide um remorso no seu coração. Disse Davide ao Senhor: Eu cometi nesta acção um grande pecado, mas rogo-te, ó Senhor, que perdoes a iniquidade do teu servo, porque procedeu muito nèsciamente.

[[v10-24-11]]

^<<v10-24-11,11>>^ Quando Davide se levantou, pela manhã, o Senhor dirigiu a sua palavra a Gad, profeta e vidente de Davide, dizendo;

[[v10-24-12]]

^<<v10-24-12,12>>^ Vai e dize a Davide: Eis o que diz o Senhor: De três coisas (para castigo) se te dá opção; escolhe qual destas queres que te mande.

[[v10-24-13]]

^<<v10-24-13,13>>^ Gad, tendo-se apresentado a Davide, deu-lhe a conhecer a ordem do Senhor, dizendo: Ou virá a fome durante sete anos à tua terra; ou durante três meses irás fugindo dos teus inimigos, que te perseguirão; ou pelo menos haverá peste na tua terra durante três dias. Delibera, pois, agora, e vê que resposta hei-de levar a quem me enviou.

[[v10-24-14]]

^<<v10-24-14,14>>^ Davide respondeu a Gad: Encontro-me muito perplexo, mas melhor é que eu caia nas mãos do Senhor (porque são grandes as suas misericórdias) do que nas mãos dos homens.

[[v10-24-15]]

^<<v10-24-15,15>>^ Mandou, pois, o Senhor a peste a Israel, desde aquela manhã até ao tempo assinalado, morrendo do povo, desde Dan até Bersabé, setenta mil homens.

[[v10-24-16]]

^<<v10-24-16,16>>^ Tendo estendido o anjo do Senhor a sua mão sobre Jerusalém para a destruir, o Senhor compadeceu-se da sua aflição e disse ao anjo exterminador do povo: Basta, detém agora a tua mão. O anjo do Senhor estava junto da eira de Areuna Jebuseu.

[[v10-24-17]]

^<<v10-24-17,17>>^ Davide, logo que viu o anjo ferindo o povo, disse ao Senhor: Eu sou o que pequei, eu fui o que procedi mal; que fizeram estes, que são as ovelhas? Volte-se, te peço, a tua mão contra mim, e contra a casa de meu pai.

[[v10-24-18]]

^<<v10-24-18,18>>^ Gad foi naquele dia ter com Davide, e disse-lhe: Vai, e levanta um altar ao Senhor na eira de Areuna Jebuseu.

[[v10-24-19]]

^<<v10-24-19,19>>^ E Davide foi, conforme o que Gad lhe tinha dito, por ordem do Senhor.

[[v10-24-20]]

^<<v10-24-20,20>>^ Tendo Areuna levantado os olhos, viu que vinham para ele o rei e os seus servos,

[[v10-24-21]]

^<<v10-24-21,21>>^ e, adiantando-se, fez ao rei uma profunda reverência, prostrado o rosto em terra, e disse: Que motivo há para que o rei meu senhor venha a casa do seu servo? Davide respondeu-lhe: Para comprar a tua eira e edificar nela um altar ao Senhor, para que cesse a mortandade que grassa no povo.

[[v10-24-22]]

^<<v10-24-22,22>>^ Areuna disse a Davide: Tome-a o rei meu senhor, e sacrifique como bem lhe parecer; eis aqui estão bois para o holocausto um carro e jugos de bois que servirão de lenha.

[[v10-24-23]]

^<<v10-24-23,23>>^ Areuna deu tudo ao rei. Areuna disse mais ao rei: O Senhor teu Deus receba o teu voto.

[[v10-24-24]]

^<<v10-24-24,24>>^ O rei respondeu-lhe: Eu não posso receber o que tu me ofereces, mas comprar-te-ei pelo que vale, e não oferecerei ao Senhor meu Deus holocaustos que me não custem nada. Comprou, pois, Davide a eira e os bois por cincoenta siclos de prata.

[[v10-24-25]]

^<<v10-24-25,25>>^ Davide edificou ali um altar ao Senhor, e ofereceu holocaustos e hóstias pacíficas. O Senhor compadeceu-se da terra, e cessou o flagelo que assolava Israel.

'''

xref:010-ii-samuel/010-ii-samuel-023.adoc#v10-23-0[&#60; Capítulo Anterior] | <<v10-24-0,Topo>> | xref:011-i-reis/011-i-reis-001.adoc#v11-1-0[Próximo Capítulo &#62;]