include::./index.adoc[]

[[v10-18-0]]
=== II Samuel, 18
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* 2 Samuel 18 narra a batalha entre as forças de Davi e as de seu filho Absalão, que havia liderado uma rebelião contra o pai. Durante a batalha, Absalão é morto por Joabe, o comandante do exército de Davi. Davi lamenta a morte de seu filho e reconhece que sua vitória na batalha não trouxe alegria, mas tristeza e dor.
* Provérbios 16:18: "A soberba precede a ruína, e a altivez de espírito precede a queda." A rebelião de Absalão contra Davi foi motivada em parte por sua própria arrogância e orgulho. Este verso em Provérbios adverte sobre o perigo da soberba, lembrando-nos que a humildade é uma virtude valiosa.
* Provérbios 29:23: "O orgulho do homem o abate, mas o de espírito humilde obterá honra." A queda de Absalão na batalha em 2 Samuel 18 é um exemplo da verdade deste verso em Provérbios. A arrogância e o orgulho podem levar à destruição, enquanto a humildade pode levar à honra.
* Isaías 57:15: "Porque assim diz o Alto e o Sublime, que habita na eternidade e cujo nome é santo: Habito no alto e santo lugar, mas habito também com o contrito e abatido de espírito, para vivificar o espírito dos abatidos e para vivificar o coração dos contritos." Este verso em Isaías fala sobre a presença de Deus com aqueles que têm um espírito humilde e contrito. Quando enfrentamos a dor e a tristeza como Davi faz em 2 Samuel 18, podemos confiar que Deus está presente conosco, consolando-nos e renovando nossos espíritos.
* Salmo 34:18: "Perto está o SENHOR dos que têm o coração quebrantado e salva os de espírito oprimido." Davi experimenta grande tristeza e dor com a morte de seu filho em 2 Samuel 18, mas este Salmo nos lembra que Deus está perto daqueles que estão sofrendo e oprimidos. Podemos confiar em Deus para nos salvar e nos consolar em tempos de dificuldade.
* Salmo 147:3: "Cura os quebrantados de coração e liga-lhes as feridas." Este Salmo fala sobre a bondade e misericórdia de Deus, que cura os corações quebrantados e cuida dos feridos. Em 2 Samuel 18, Davi enfrenta a perda de seu filho, mas pode encontrar consolo na confiança em Deus como um curador e consolador.
****

[[v10-18-1]]

^<<v10-18-1,1>>^ Davide, tendo feito resenha da sua gente, nomeou sobre ela chefes de milhar e chefes de centena.

[[v10-18-2]]

^<<v10-18-2,2>>^ Pôs um terço das suas tropas sob o mando de Joab, outro terço sob o mando de Abisai, filho de Sarvia irmão de Joab, e outro terço sob o mando de Etai de Get. O rei disse ao povo: Eu sairei também convosco.

[[v10-18-3]]

^<<v10-18-3,3>>^ Todavia o povo respondeu: Não sairás, porque, ainda que os inimigos nos ponham em fuga, não terão isto por uma grande coisa; mesmo que morra metade de nós, não lhes dará isso maior cuidado. Tu, porém és considerado como dez mil. Logo é melhor que fiques na cidade para nos socorrer.

[[v10-18-4]]

^<<v10-18-4,4>>^ O rei disse-lhes: Farei o que vos parecer bem. E pôs-se o rei junto à porta (da cidade), e o povo Ia desfilando, formado em esquadrões de cem e de mil homens.

[[v10-18-5]]

^<<v10-18-5,5>>^ O rei deu esta ordem a Joab, a Abisai e a Etai: Poupai-me o meu filho Absalão. E todo o povo ouviu a ordem que o rei dava a todos os seus generais em favor de Absalão.

[[v10-18-6]]

^<<v10-18-6,6>>^ Saiu, enfim , o povo à campanha contra Israel, e deu-se a batalha no bosque de Efraim

[[v10-18-7]]

^<<v10-18-7,7>>^ Ali o povo de Israel foi derrotado pelo exército de Davide, e naquele dia houve um a grande mortandade de vinte mil homens.

[[v10-18-8]]

^<<v10-18-8,8>>^ O combate estendeu-se sobre a superfície de toda aquela terra, e foram muito mais os que pereceram (fugindo) pelo bosque, do que aqueles que pereceram à espada.

[[v10-18-9]]

^<<v10-18-9,9>>^ Ora aconteceu que, indo Absalão montado num macho, se encontrou com a gente de Davide. Tendo entrado o macho por baixo dum frondoso e grande carvalho, enredou-se a cabeleira (de Absalão) nos ramos do carvalho; pasando adiante o macho em que la montado, ficou ele pendurado entre o céu e a terra.

[[v10-18-10]]

^<<v10-18-10,10>>^ Vendo isto um homem, avisou Joab, dizendo: Eu vi Absalão pendurado dum carvalho.

[[v10-18-11]]

^<<v10-18-11,11>>^ Joab disse ao homem que lhe dava esta notícia: Se o viste, por que o não abateste? Eu dar-te-ia dez siclos de prata e um cinto.

[[v10-18-12]]

^<<v10-18-12,12>>^ Ele respondeu a Joab: Ainda que pusesses nas minhas mãos mil siclos de prata, de nenhuma sorte estenderia minha mão contra o filho do rei, porque todos nós ouvimos a ordem que o rei deu a ti, a Abisai, e a Etai, quando disse: Poupai-me o meu filho Absalão.

[[v10-18-13]]

^<<v10-18-13,13>>^ Se eu, com risco da minha vida, tivesse procedido tão temerariamente, de nenhum modo isto se poderia ocultar ao rei; e tu mesmo opor-te-ias (ao rei, defendendo-me)?

[[v10-18-14]]

^<<v10-18-14,14>>^ Joab disse: Não será o que dizes, mas à tua vista o matarei. Tomou, pois, na mão três langas, e traspassou com elas o coração de Absalão. Quando ele ainda palpitava pendurado no carvalho,

[[v10-18-15]]

^<<v10-18-15,15>>^ correram dez jovens escudeiros de Joab, que, a golpes, o acabaram de matar.

[[v10-18-16]]

^<<v10-18-16,16>>^ Joab tocou a trombeta, e, querendo poupar a multidão (dos vencidos). Impediu que a sua gente fosse no alcance dos Israelitas que fugiram.

[[v10-18-17]]

^<<v10-18-17,17>>^ Tomaram Absalão, lançaram-no numa grande cova no bosque, e arremessaram sobre ele um grandíssimo montão de pedras. Todos os Israelitas fugiram para as suas tendas.

[[v10-18-18]]

^<<v10-18-18,18>>^ Absalão, quando ainda vivia, tinha feito levantar para si um monumento no vale do Rei, porque tinha dito: Eu (já) não tenho filhos, e este será uma memória do meu nome. E deu o seu nome a este monumento, o qual ainda hoje se chama a Mão de Absalão.

[[v10-18-19]]

^<<v10-18-19,19>>^ Aquimaas, filho de Sadoc, disse: Deixa-me correr a levar ao rei a boa notícia de que o Senhor lhe fez justiça (libertando-o) do poder de seus inimigos.

[[v10-18-20]]

^<<v10-18-20,20>>^ Joab disse-lhe: Não lhe levarás hoje a notícia, mas outro dia; não quero que lha leves hoje, porque morreu o filho do rei.

[[v10-18-21]]

^<<v10-18-21,21>>^ Joab disse a um cusita: Parte e vai anunciar ao rei o que viste. Ele fez-lhe uma profunda reverência e partiu a correr.

[[v10-18-22]]

^<<v10-18-22,22>>^ Aquimaas, filho de Sadoc, disse novamente a Joab: Que embaraço há para que eu não vá também correndo atrás do cusita? Joab respondeu-lhe: Por que queres tu correr, ó meu filho? Esta mensagem não te aproveitaria.

[[v10-18-23]]

^<<v10-18-23,23>>^ (Aquimaas) respondeu: Seja o que for, eu correrei. Joab disse-lhe: Corre. Correndo, pois, Aquimaas por um atalho, passou adiante do cusita.

[[v10-18-24]]

^<<v10-18-24,24>>^ Davide estava sentado entre as duas portas. A sentinela que estava por cima da porta, sobre a muralha, levantando os olhos, viu vir um homem correndo sozinho e gritou para advertir o rei. O rei respondeu: Se vem só, traz alguma boa nova. Entretanto, apressando-se ele e estando já próximo,

[[v10-18-25]]

^<<v10-18-25,25>>^ .

[[v10-18-26]]

^<<v10-18-26,26>>^ a sentinela descobriu outro homem que corria, e, gritando de cima, disse: Eu vejo lá vir correndo outro homem só. O rei disse: Também este traz alguma boa nova.

[[v10-18-27]]

^<<v10-18-27,27>>^ A sentinela disse: Observo que o modo de correr do primeiro me parece ser o correr de Aquimaas, filho de Sadoc. O rei disse: É um homem de bem, e vem (certamente) trazer boas novas.

[[v10-18-28]]

^<<v10-18-28,28>>^ Aquimaas, gritando, disse ao rei: Vitória! E, prostrado em terra, diante do rei, e fazendo-lhe uma profunda reverência; disse: Bem-dito seja o Senhor, teu Deus, que destroçou os homens que se tinham sublevado contra o rei, meu senhor.

[[v10-18-29]]

^<<v10-18-29,29>>^ O rei disse: Está vivo o meu filho Absalão? Aquimaas respondeu-lhe: Quando o teu servo Joab me enviou a ti, que (também) sou teu servo, ó rei, eu vi um grande tumulto; não sei mais nada. (ver nota)

[[v10-18-30]]

^<<v10-18-30,30>>^ O rei disse-lhe: Afasta-te e espera aí. Tendo ele passado e estando no seu lugar,

[[v10-18-31]]

^<<v10-18-31,31>>^ chegou o cusita que disse: Ó rei, meu senhor, trago-te um a boa nova, porque o Senhor julgou hoje em teu favor, libertando-te da mão de todos aqueles que se sublevaram contra ti.

[[v10-18-32]]

^<<v10-18-32,32>>^ O rei disse ao cusita: Está vivo o meu filho Absalão? Cusi, respondendo-lhe, disse: Assim suceda aos inimigos do rei, meu senhor, e a todos os que se sublevam contra ele para o perderem, como sucedeu àquele jovem.

[[v10-18-33]]

^<<v10-18-33,33>>^ Então o rei, cheio de tristeza subiu ao quarto, que estava por cima da porta, e pôs-se a chorar. E, andando, dizia assim: Meu filho Absalão! Absalão, filho meu! Quem me dera ter morrido por ti, Absalão, meu filho, filho meu, Absalão.

'''

xref:010-ii-samuel/010-ii-samuel-017.adoc#v10-17-0[&#60; Capítulo Anterior] | <<v10-18-0,Topo>> | xref:010-ii-samuel/010-ii-samuel-019.adoc#v10-19-0[Próximo Capítulo &#62;]