include::./index.adoc[]

[[v10-7-0]]
=== II Samuel, 7
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* 2 Samuel 7 narra um importante diálogo entre Deus e o rei Davi, no qual Deus promete a Davi uma descendência duradoura e um reino eterno. Além disso, o capítulo também descreve como Davi deseja construir um templo para Deus, mas é informado que essa tarefa será realizada por seu filho. Abaixo estão cinco versículos relacionados com os temas abordados em 2 Samuel 7:
* 2 Samuel 7:12: "Quando se completarem os teus dias e descansares com teus pais, estabelecerei depois de ti um filho teu, e confirmarei a sua realeza." Este versículo é o início da promessa que Deus faz a Davi de uma descendência duradoura e um reino eterno.
* 2 Samuel 7:16: "A tua casa e o teu reino serão para sempre seguros diante de mim; teu trono será estabelecido para sempre." Deus promete a Davi que sua dinastia será eterna.
* Salmos 89:3-4: "Fiz aliança com o meu escolhido, jurei ao meu servo Davi: Estabelecerei a tua descendência para sempre e firmarei o teu trono por todas as gerações." Este Salmo reafirma a promessa de Deus a Davi de uma descendência duradoura.
* Isaías 9:6-7: "Porque um menino nos nasceu, um filho nos foi dado; o governo está sobre os seus ombros; e o seu nome será: Maravilhoso Conselheiro, Deus Forte, Pai Eterno, Príncipe da Paz. Ele estenderá o seu domínio, e haverá paz sem fim sobre o trono de Davi e sobre o seu reino, que ele estabelecerá e manterá com justiça e retidão desde agora e para sempre. O zelo do Senhor dos Exércitos fará isso." Este trecho profético se refere à promessa de Deus a Davi de uma descendência eterna e um reino justo.
* Atos 2:29-31: "Irmãos, seja-me permitido dizer-vos com franqueza que o patriarca Davi morreu e foi sepultado, e o seu túmulo está entre nós até o dia de hoje. Sendo ele profeta, sabia que Deus lhe havia prometido com juramento que um dos seus descendentes se assentaria no seu trono. Prevendo isso, Davi falou da ressurreição de Cristo, que ele não foi abandonado no Hades, nem o seu corpo experimentou corrupção." Pedro cita Davi para demonstrar que a ressurreição de Jesus é uma evidência da fidelidade de Deus à promessa de uma descendência eterna a Davi.
****

[[v10-7-1]]

^<<v10-7-1,1>>^ Ora aconteceu que, estando o rei estabelecido em sua casa, e tendo-lhe o Senhor dado paz por todas as partes com todos os seus inimigos,

[[v10-7-2]]

^<<v10-7-2,2>>^ disse ele ao profeta Natan: Tu não vês que habito numa casa de cedro, enquanto a arca de Deus está posta debaixo dumas peles?

[[v10-7-3]]

^<<v10-7-3,3>>^ Natan respondeu ao rei: Vai e faze tudo o que tens no coração, porque o Senhor é contigo.

[[v10-7-4]]

^<<v10-7-4,4>>^ Naquela mesma noite, o Senhor falou a Natan, dizendo:

[[v10-7-5]]

^<<v10-7-5,5>>^ Vai e dize ao meu servo Davide: Eis o que o diz o Senhor: Porventura serás tu que me edificarás uma casa para eu habitar?

[[v10-7-6]]

^<<v10-7-6,6>>^ Vê que eu, desde que tirei da terra do Egipto os filhos de Israel até ao dia de hoje, não habitei em nenhum a casa, mas tenho caminhado debaixo dum pavilhão e duma tenda.

[[v10-7-7]]

^<<v10-7-7,7>>^ Em todos os lugares, por onde passei com todos os filhos de Israel, falei eu porventura a algum dos chefes de Israel, a esses que mandei pastorear o meu povo de Israel, dizendo: Por que não me edificais uma casa de cedro?

[[v10-7-8]]

^<<v10-7-8,8>>^ Dirás, pois, ao meu servo Davide: Eis o que diz O Senhor dos exércitos: Eu tirei-te das pastagens, quando ias seguindo os gados, para que fosses o condutor do meu povo de Israel;

[[v10-7-9]]

^<<v10-7-9,9>>^ por toda a parte por onde andaste, estive contigo, exterminei diante de ti todos os teus inimigos, e fiz o teu nome tão ilustre como o nome dos grandes que há na terra;

[[v10-7-10]]

^<<v10-7-10,10>>^ fixei um lugar ao meu povo de Israel e coloquei-o nele, onde habitará, sem ser mais perturbado (se permanecer fiel aos meus preceitos); os filhos da iniquidade não tornarão a afligi-lo como dantes,

[[v10-7-11]]

^<<v10-7-11,11>>^ desde o dia em que eu constituí juízes sobre o meu povo de Israel; dei-te paz, (livrando-te) de todos os teus inimigos. (Pois agora) o Senhor te anuncia (desde já) que te fará uma casa. (ver nota)

[[v10-7-12]]

^<<v10-7-12,12>>^ Quando se completarem os teus dias, e dormires com teus pais, suscitarei depois de ti a tua posteridade, que nascerá de ti, e firmarei o seu reino. (ver nota)

[[v10-7-13]]

^<<v10-7-13,13>>^ Ele edificará uma casa em meu nome, e eu estabelecerei para sempre o trono de seu reino.

[[v10-7-14]]

^<<v10-7-14,14>>^ Eu serei para ele um pai, e ele será para mim um filho. Se ele cometer alguma coisa iníqua, eu o castigarei com vara de homens, e com açoutes de filhos de homens.

[[v10-7-15]]

^<<v10-7-15,15>>^ Porém , não retirarei dele a minha misericórdia, como a retirei de Saul, a quem expulsei de diante da minha face.

[[v10-7-16]]

^<<v10-7-16,16>>^ A tua casa será estável, o teu reino se perpetuará diante do teu rosto, e o teu trono será firme para sempre.

[[v10-7-17]]

^<<v10-7-17,17>>^ Seguindo todas estas palavras e toda esta visão, falou Natan a Davide.

[[v10-7-18]]

^<<v10-7-18,18>>^ Entrou o rei Davide, sentou-se diante, do Senhor e disse: Quem sou eu, ó Senhor Deus, e que casa é a minha, para tu me teres elevado a este ponto?

[[v10-7-19]]

^<<v10-7-19,19>>^ Mas isto mesmo te pareceu pouco, ó Senhor Deus, pois falaste também (prometendo a permanência) da casa de teu servo para tempos distantes; porque esta é a lei do homem, ó Senhor Deus.

[[v10-7-20]]

^<<v10-7-20,20>>^ Que poderá, pois, acrescentar ainda Davide, falando contigo? Tu, ó Senhor Deus, conheces o teu servo.

[[v10-7-21]]

^<<v10-7-21,21>>^ Por atenção à tua palavra e segundo o teu coração, fizeste todas estas maravilhas, até ao ponto de as dares a saber ao teu servo.

[[v10-7-22]]

^<<v10-7-22,22>>^ Por isso, ó Senhor Deus, mostraste a tua grandeza! Ninguém há semelhante a ti, nem há Deus, fora de ti, segundo tudo o que temos ouvido com os nossos ouvidos.

[[v10-7-23]]

^<<v10-7-23,23>>^ Que nação há, na terra, igual ao teu povo de Israel, a quem Deus foi resgatar, para o fazer seu povo, dar-lhe um nome célebre, e operar em seu favor prodígios (tão) terríveis, a fim de o tirar da escravidão do Egipto, (e a fim de punir aquela terra), o seu povo, e o seu (falso) deus?

[[v10-7-24]]

^<<v10-7-24,24>>^ Tu estabeleceste o povo de Israel, para ser eternamente o teu povo, e tu te fizeste o seu Deus, ó Senhor Deus.

[[v10-7-25]]

^<<v10-7-25,25>>^ Agora, pois, ó Senhor Deus, faze que tenha efeito para sempre a palavra que pronunciaste acerca do teu servo e da sua casa, e faze como disseste,

[[v10-7-26]]

^<<v10-7-26,26>>^ para que o teu nome seja eternamente engrandecido e se diga: O Senhor dos exércitos é o Deus de Israel. A casa de teu servo Davide permanecerá estável diante do Senhor,

[[v10-7-27]]

^<<v10-7-27,27>>^ porque tu, ó Senhor dos exércitos, Deus de Israel, te revelaste ao ouvido do teu servo, dizendo: Eu te edificarei uma casa; por isso o teu servo se animou a dirigir-te esta prece.

[[v10-7-28]]

^<<v10-7-28,28>>^ Agora, ó Senhor Deus, tu és Deus e as tuas palavras são verdadeiras. Ora tu mesmo prometeste ao teu servo estes bens;

[[v10-7-29]]

^<<v10-7-29,29>>^ começa, pois, e abençoa a casa de teu servo, para que ela subsista para sempre diante de ti, porque tu, ó Senhor Deus, é que falaste, e com a tua bênção será para sempre bem-dita a casa do teu servo.

'''

xref:010-ii-samuel/010-ii-samuel-006.adoc#v10-6-0[&#60; Capítulo Anterior] | <<v10-7-0,Topo>> | xref:010-ii-samuel/010-ii-samuel-008.adoc#v10-8-0[Próximo Capítulo &#62;]