include::./index.adoc[]

[[v7-19-0]]
=== Juízes, 19
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 19 de Juízes conta a história chocante de um levita que, viajando com sua concubina, decide passar a noite na cidade de Gibéia, em Benjamim. Lá, eles são hospedados por um velho, mas a cidade é cercada por homens perversos que exigem que o levita seja entregue para que eles possam abusá-lo sexualmente. Em vez disso, o velho oferece sua própria filha e a concubina do levita para os homens, que acabam violentando e matando a concubina. O levita então corta o corpo dela em pedaços e envia os pedaços para todas as tribos de Israel, provocando uma guerra contra a tribo de Benjamim.
* Deuteronômio 22:25-27: "Mas se um homem achar uma moça desposada no campo, e o homem a forçar, e se deitar com ela, então morrerá só o homem que se deitou com ela. Porém, à moça não farás nada; não há nela pecado digno de morte; pois, como quando alguém se levanta contra o seu próximo, e lhe tira a vida, assim é este caso. Porque ele a achou no campo; a moça desposada gritou, mas não houve quem a livrasse." Este versículo destaca a importância de proteger a dignidade e a integridade das mulheres e condena a violência sexual.
* Provérbios 16:29: "O homem violento persuade o seu companheiro, e guia-o por caminho não bom." Este versículo condena a violência e a influência negativa que os homens violentos podem ter sobre os outros.
* Isaías 1:15-17: "E, quando estenderdes as vossas mãos, esconderei de vós os meus olhos; sim, quando multiplicardes a oração, não ouvirei; porque as vossas mãos estão cheias de sangue. Lavai-vos, purificai-vos, tirai de diante dos meus olhos a maldade dos vossos atos; cessai de fazer mal, aprendei a fazer bem; buscai a justiça, acabai com a opressão; fazei justiça ao órfão, defendei a causa da viúva." Este versículo condena a injustiça e a violência e chama as pessoas a se arrependerem e a buscar a justiça.
* Salmo 82:3-4: "Fazei justiça ao pobre e ao órfão; justificai o aflito e o necessitado. Livrai o pobre e o necessitado; tirai-os das mãos dos ímpios." Este versículo chama as pessoas a defenderem os necessitados e a fazerem justiça, especialmente em face da opressão e violência.
* Amós 5:15: "Odeiai o mal e amai o bem, e estabelecei a justiça na porta; talvez o SENHOR Deus dos Exércitos se compadeça do remanescente de José." Este versículo enfatiza a importância de odiar o mal e amar o bem, e a necessidade de estabelecer a justiça em todas as áreas da vida.
****

[[v7-19-1]]

^<<v7-19-1,1>>^ Houve um certo Levita, que habitava ao lado do monte de Efraim, o qual se tinha casado com uma mulher de Belém de Judá.

[[v7-19-2]]

^<<v7-19-2,2>>^ Esta mulher deixou-o, voltou para Belém, para casa de seu pai, e ficou morando com ele quatro meses.

[[v7-19-3]]

^<<v7-19-3,3>>^ Seu marido foi-a buscar, querendo reconciliar-se com ela, acariciá-la e reconduzi-la consigo, levando um criado e dois jumentos. Ela o acolheu e o introduziu em casa de seu pai. O sogro, quando soube isto e o viu, saiu a recebê-lo, alegre,

[[v7-19-4]]

^<<v7-19-4,4>>^ e abraçou-o. E o genro esteve três dias em casa do sogro, comendo, e bebendo com ele familiarmente.

[[v7-19-5]]

^<<v7-19-5,5>>^ Ao quarto dia porém, levantando-se antes de amanhecer, quis partir, mas o sogro o deteve e lhe disse: Come primeiro um pouco de pão, conforta o estômago, e depois partirás.

[[v7-19-6]]

^<<v7-19-6,6>>^ Sentaram-se ambos, comeram e beberam. O pai da moça disse ao seu genro: Peço-te que fiques aqui ainda hoje, a passar a noite alegremente.

[[v7-19-7]]

^<<v7-19-7,7>>^ Mas ele, levantando-se, começou a querer partir. Todavia o sogro, com as suas instâncias, deteve-o e fê-lo ficar consigo.

[[v7-19-8]]

^<<v7-19-8,8>>^ Chegando a manhã, o Levita preparava-se para partir. O sogro disse-lhe novamente: Peço-te que comas primeiro um pouco de alimento, para cobrar forças, e espera até à tarde. Comeram pois juntamente.

[[v7-19-9]]

^<<v7-19-9,9>>^ O jovem levantou-se para partir com sua mulher e com o criado. Mas o sogro disse-lhe outra vez: Olha que o dia está muito perto do ocaso e a noite aproxima-se; fica comigo ainda hoje, e passa um dia alegre, e amanhã partirás muito cedo a fim de ires para tua casa.

[[v7-19-10]]

^<<v7-19-10,10>>^ O genro não quis aceder a estes rogos, mas partiu logo. Chegou à vista de Jebus, que por outro nome se chama Jerusalém, levando consigo dois jumentos carregados e sua mulher.

[[v7-19-11]]

^<<v7-19-11,11>>^ Quando já estavam perto de Jebus, o dia mudava-se em noite, e o criado disse ao seu amo: Vem, te peço, dirijamo-nos à cidade dos Jebuseus, e fiquemos nela.

[[v7-19-12]]

^<<v7-19-12,12>>^ O amo respondeu-lhe: Eu não entrarei numa cidade de gente estrangeira, que não é dos filhos de Israel, mas passarei até Gabaa;

[[v7-19-13]]

^<<v7-19-13,13>>^ depois que lá chegar, descansaremos nela ou ao menos na cidade de Rama.

[[v7-19-14]]

^<<v7-19-14,14>>^ Ultrapassaram, pois, Jebus, e, continuando o seu caminho, se lhes pôs o sol junto de Gabaa, que é da tribo de Benjamim.

[[v7-19-15]]

^<<v7-19-15,15>>^ Entraram nela, para ali pousarem. Tendo entrado, sentaram-se na praça da cidade, e ninguém lhes quis dar hospitalidade.

[[v7-19-16]]

^<<v7-19-16,16>>^ Nisto apareceu um homem velho, que voltava do campo e do seu trabalho ao anoitecer, o qual também era do monte de Efraim e habitava como forasteiro em Gabaa. Os homens daquela região eram filhos de Jemini (ou Benjamitas).

[[v7-19-17]]

^<<v7-19-17,17>>^ O velho, levantando os olhos, viu o Levita sentado na praça da cidade com a sua pequena bagagem e disse-lhe: Donde vens tu? e para onde vais?

[[v7-19-18]]

^<<v7-19-18,18>>^ Ele respondeu-lhe: Nós partimos de Belém de Judá e vamos para nossa casa, que é ao lado do monte de Efraim, donde tínhamos ido a Belém; agora vamos à casa de Deus, mas ninguém nos quer acolher sob o seu teto,

[[v7-19-19]]

^<<v7-19-19,19>>^ tendo nós palha e feno para sustento dos jumentos, o pão e vinho para mim e para esta tua serva, e para o criado, que está comigo; de nenhuma coisa necessitamos mais que de pousada.

[[v7-19-20]]

^<<v7-19-20,20>>^ O velho respondeu-lhe: A paz seja contigo, eu te darei tudo o que for necessário; rogo-te somente que não fiques na praça.

[[v7-19-21]]

^<<v7-19-21,21>>^ Conduziu-o a sua casa, deu de comer aos jumentos, e, depois que (os viajantes) lavaram os pés, serviu-lhes uma refeição.

[[v7-19-22]]

^<<v7-19-22,22>>^ Enquanto restauravam os seus corpos com a comida e bebida, chegaram uns homens daquela cidade, filhos de Belial (isto é, sem jugo), e, cercando a casa do velho, começaram a bater fortemente à porta, dizendo ao dono da casa: Deita cá para fora esse homem, que enfarou para tua casa, a fim de abusarmos dele.

[[v7-19-23]]

^<<v7-19-23,23>>^ O velho saiu fora, a ter com eles, e disse: Não queirais, irmãos, não queirais cometer semelhante maldade, pois eu hospedei este homem em minha casa. Não façais tal infâmia.

[[v7-19-24]]

^<<v7-19-24,24>>^ Eu tenho uma filha virgem e este homem tem a sua mulher, eu vo-Ias tirarei cá para fora, para abusardes delas e satisfazerdes a vossa paixão; somente vos peço que não cometais contra este homem tal infâmia. (ver nota)

[[v7-19-25]]

^<<v7-19-25,25>>^ Eles não queriam ceder às suas razões. Então aquele homem (Levita), vendo isto, trouxe-lhes sua mulher e abandonou-a aos seus ultrajes; eles, depois de terem abusado dela toda a noite, largaram-na ao amanhecer. (ver nota)

[[v7-19-26]]

^<<v7-19-26,26>>^ A mulher, ao amanhecer, foi à porta da casa, onde estava o seu senhor, e lá caiu por terra.

[[v7-19-27]]

^<<v7-19-27,27>>^ Chegada a manhã, levantou-se o marido e, ao abrir a porta para continuar a viagem começada, viu que sua mulher jazia (morta) diante da porta, com as mãos estendidas sobre a soleira.

[[v7-19-28]]

^<<v7-19-28,28>>^ Ele, julgando que ela estava morta, tomou-a, pô-la sobre o jumento e voltou para sua casa.

[[v7-19-29]]

^<<v7-19-29,29>>^ Logo que entrou, tomou um culeto, dividiu o cadáver de sua mulher, membro por membro, em doze partes,e enviou-as por todos os confins de Israel.

[[v7-19-30]]

^<<v7-19-30,30>>^ Quando tal viram, exclamavam: Nunca tal coisa se fez em Israel, desde o dia em que os nossos pais saíram do Egipto até hoje; pronunciai uma sentença e resolvei de comum acordo o que se deve fazer.

'''

xref:007-juizes/007-juizes-018.adoc#v7-18-0[&#60; Capítulo Anterior] | <<v7-19-0,Topo>> | xref:007-juizes/007-juizes-020.adoc#v7-20-0[Próximo Capítulo &#62;]