include::./index.adoc[]

[[v7-12-0]]
=== Juízes, 12
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Juízes 12 narra a disputa entre os homens de Gileade e os efraimitas. Os efraimitas questionam a exclusão de sua tribo da guerra contra Amom e ameaçam invadir Gileade. Jefé, líder de Gileade, lidera suas tropas para derrotar os efraimitas e controlar as passagens do rio Jordão.
* Josué 22:10: "E, quando chegaram às terras de Gileade, que pertenciam a Israel, os filhos de Rúben, os filhos de Gade e a meia tribo de Manassés edificaram ali um altar junto ao Jordão, um altar grande em aparência." Este verso fala sobre a construção de um altar pelos filhos de Rúben, Gade e Manassés em Gileade, onde a batalha entre Gileade e Efraim aconteceu.
* Salmos 60:8: "Em Deus faremos proezas, porque Ele mesmo calcará aos pés os nossos adversários." Este verso fala sobre a confiança em Deus para ajudar a vencer os inimigos, algo que os homens de Gileade fizeram na batalha contra os efraimitas.
* Isaías 9:21: "Manassés a Efraim, e Efraim a Manassés, e ambos se unam contra Judá. Contudo, nem assim a sua ira se desviou, e ainda está estendida a mão para ferir." Este verso fala sobre a rivalidade entre as tribos de Efraim e Manassés, uma rivalidade que se manifestou na batalha contra Gileade.
* Provérbios 15:1: "A resposta branda desvia o furor, mas a palavra dura suscita a ira." Este verso fala sobre a importância de responder com calma e gentileza para evitar conflitos, algo que os efraimitas não fizeram ao ameaçar Gileade.
* Romanos 12:18: "Se for possível, quanto depender de vós, tende paz com todos os homens." Este verso fala sobre a importância da paz e da reconciliação, algo que os homens de Gileade buscaram após a batalha contra os efraimitas.
****

[[v7-12-1]]

^<<v7-12-1,1>>^ Levantou-se uma sedição na tribo de Efraim.(Os desta tribo), passando para o setentrião, disseram a Jefté: por que razão, indo tu combater contra os filhos do Amon, não quiseste chamar-nos para irmos contigo? Por isso queimaremos a tua casa.

[[v7-12-2]]

^<<v7-12-2,2>>^ Ele respondeu-lhes: Eu e o meu povo estávamos metidos numa grande contenda com os filhos de Amon; chamei-vos, para que mo désseis socorro, e vós não o quisestes fazer.

[[v7-12-3]]

^<<v7-12-3,3>>^ Vendo isto, arrisquei a minha vida e marchei contra os filhos de Amon, e o Senhor entregou-os nas minhas mãos. Em que é que eu mereci que vos levanteis contra mim a fazer-me guerra?

[[v7-12-4]]

^<<v7-12-4,4>>^ Convocados todos os homens de Galaad, combateu contra Efraim, e os homens de Galaad derrotaram Efraim, porque este tinha dito: Galaad é um fugitivo de Efraim, e habita entre Efraim e Manassés.

[[v7-12-5]]

^<<v7-12-5,5>>^ Os Galaaditas ocuparam os vaus do Jordão, por onde Efraim havia de voltar. Quando algum fugitivo de Efraim chegava a eles e dizia: Peço-vos que me deixeis passar — os Galaaditas respondiam-lhe: Acaso és tu efraimita? Se ele respondesse: Não sou —

[[v7-12-6]]

^<<v7-12-6,6>>^ replicavam-Ihe: Dize pois Schibolet, que significa espiga. Ele pronunciava Sibolet, não podendo exprimir a palavra espiga com as mesmas letras. Imediatamente preso, degolavam-no na mesma passagem do Jordão. Naquele tempo morreram quarenta e dois mil homens de Efraim.

[[v7-12-7]]

^<<v7-12-7,7>>^ Jefté Galaadita julgou Israel durante seis anos; depois morreu, e foi sepultado na sua cidade de Galaad.

[[v7-12-8]]

^<<v7-12-8,8>>^ Depois deste, foi juiz de lsrael Abesan, de Belém,

[[v7-12-9]]

^<<v7-12-9,9>>^ O qual teve trinta filhos, e outras tantas filhas, que casou fora de sua casa; fez vir de fora e recebeu em sua casa igual número de mulheres como esposas dos seus filhos. Julgou Israel durante sete anos.

[[v7-12-10]]

^<<v7-12-10,10>>^ Morreu, e foi sepultado em Belém.

[[v7-12-11]]

^<<v7-12-11,11>>^ Sucedeu-lhe Aialon Zabulonita, que julgou Israel durante dez anos.

[[v7-12-12]]

^<<v7-12-12,12>>^ Morreu, e foi sepultado em Zabulon.

[[v7-12-13]]

^<<v7-12-13,13>>^ Depois deste, foi juiz de Israel Abdon, filho de Del, de Faraton,

[[v7-12-14]]

^<<v7-12-14,14>>^ que teve quarenta filhos e trinta netos, que montavam em setenta jumentos, e julgou Israel durante oito anos.

[[v7-12-15]]

^<<v7-12-15,15>>^ Morreu, e foi sepultado em Faraton, na terra de Efraim, sobre o monte de Amalec.

'''

xref:007-juizes/007-juizes-011.adoc#v7-11-0[&#60; Capítulo Anterior] | <<v7-12-0,Topo>> | xref:007-juizes/007-juizes-013.adoc#v7-13-0[Próximo Capítulo &#62;]