include::./index.adoc[]

[[v7-2-0]]
=== Juízes, 2
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Juízes 2 relata a morte de Josué e a falta de liderança que se seguiu, levando o povo à apostasia e idolatria. Deus se ira com a desobediência do povo e permite que eles sofram nas mãos de seus inimigos. Em resposta às suas orações, Deus levanta juízes para libertá-los da opressão.
* Deuteronômio 31:16: "E disse o Senhor a Moisés: Eis que tu estás para dormir com teus pais; e este povo se levantará, e se prostituirá com os deuses estranhos da terra, para onde vai, no meio dela; e me deixará, e anulará o meu pacto, que tenho feito com ele." Este versículo retrata a previsão de Deus de que o povo de Israel se afastaria Dele e se voltaria para os deuses estranhos, que é precisamente o que acontece em Juízes 2.
* Juízes 2:11-12: "Então, os filhos de Israel fizeram o que era mau aos olhos do Senhor e serviram aos baalins. E deixaram ao Senhor, Deus de seus pais, que os tinha tirado da terra do Egito, e foram após outros deuses, dentre os deuses dos povos que havia ao seu redor, e se prostraram a eles, e provocaram a ira do Senhor." Estes versículos são uma descrição direta da desobediência do povo de Israel a Deus e de como eles se voltaram para outros deuses, o que provocou a ira do Senhor.
* Juízes 2:14: "Então, a ira do Senhor se acendeu contra Israel, e ele os entregou nas mãos dos despojadores que os despojaram; e os vendeu nas mãos de seus inimigos ao redor, para que não pudessem mais resistir diante de seus inimigos." Aqui vemos a resposta de Deus à desobediência de Israel: Ele permite que eles sofram nas mãos de seus inimigos.
* Juízes 2:16: "E levantou o Senhor juízes que os livraram da mão daqueles que os despojaram." Aqui vemos a resposta de Deus às orações de Israel: Ele levanta juízes para libertá-los da opressão.
* 1 Samuel 12:10: "E clamaram ao Senhor e disseram: Pecamos, porque deixamos ao Senhor e servimos aos baalins e astarotes; agora, pois, livra-nos da mão de nossos inimigos, e te serviremos." Este versículo retrata a resposta correta do povo de Israel à opressão: eles clamam a Deus e se arrependem de sua desobediência, prometendo servi-lo.
****

[[v7-2-1]]

^<<v7-2-1,1>>^ O anjo do Senhor subiu de Galgala ao lugar o (chamado) dos Chorosos, e disse: Eu vos tirei do Egipto e vos introduzi na terra, que eu tinha jurado a vossos pais (dar-vos), e prometi-vos não mais romper o pacto (que fiz) convosco,

[[v7-2-2]]

^<<v7-2-2,2>>^ com a condição, porém, de que não faríeis aliança com os habitantes desta terra, mas que destruiríeis os seus altares. Vós não quisestes ouvir a minha voz; por que fizestes isto?

[[v7-2-3]]

^<<v7-2-3,3>>^ Por esta razão eu não quis expulsá-los, à vossa frente, para que os tenhais por inimigos, e os seus deuses sejam a vossa ruína.

[[v7-2-4]]

^<<v7-2-4,4>>^ Ao dizer o anjo do Senhor estas palavras a todos os filhos de Israel, levantaram estes a sua voz e choraram.

[[v7-2-5]]

^<<v7-2-5,5>>^ Pelo que chamaram aquele lugar, o lugar dos Chorosos, ou das lágrimas, e ofereceram ali sacrifícios ao Senhor.

[[v7-2-6]]

^<<v7-2-6,6>>^ Josué despediu o povo, e os filhos de Israel foram cada um para a terra da sua herança, a fim de a ocuparem.

[[v7-2-7]]

^<<v7-2-7,7>>^ Serviram ao Senhor, durante todos os dias da vida de Josué, e dos anciães que lhe sobreviveram por largo tempo, e que tinham conhecido todas as obras que o Senhor fizera em favor de Israel.

[[v7-2-8]]

^<<v7-2-8,8>>^ Morreu Josué, filho de Nun, servo do Senhor, com cento e dez anos,

[[v7-2-9]]

^<<v7-2-9,9>>^ e sepultaram-no nos confins da sua possessão em Tamnatsare, sobre o monte de Efraim, ao norte do monte Gaas.

[[v7-2-10]]

^<<v7-2-10,10>>^ Toda aquela geração se foi unir a seus pais, e sucedeu-lhe outra que não conhecia o Senhor, nem as obras que tinha feito em favor de Israel.

[[v7-2-11]]

^<<v7-2-11,11>>^ E os filhos de Israel fizeram o mal diante do Senhor, serviram os Baalins, (ver nota)

[[v7-2-12]]

^<<v7-2-12,12>>^ e abandonaram o Senhor Deus de seus pais, que os tinha tirado da terra do Egipto; seguiram deuses estranhos, deuses dos povos, que habitavam em torno deles, e adoraram-nos; provocaram o Senhor à ira,

[[v7-2-13]]

^<<v7-2-13,13>>^ abandonando-o para servirem a Baal e a Astarot.

[[v7-2-14]]

^<<v7-2-14,14>>^ O Senhor, irado contra (os filhos de) Israel, entregou-os nas mãos dos saqueadores, que os tomaram e venderam aos inimigos, que habitavam ao redor; eles não puderam resistir aos seus adversários.

[[v7-2-15]]

^<<v7-2-15,15>>^ Para qualquer parte que quisessem ir, a mão do Senhor estava sobre eles, como lhes tinha dito e jurado, e viram-se em extremo aflitos,

[[v7-2-16]]

^<<v7-2-16,16>>^ O Senhor suscitou-lhes juízes, que os livrassem das mãos dos opressores, mas nem a eles quiseram ouvir,

[[v7-2-17]]

^<<v7-2-17,17>>^ prostituindo-se a deuses estranhos e adorando-os. Abandonaram depressa o caminho, por onde seus pais tinham andado, seguindo os mandamentos do Senhor; tudo fizeram ao contrário.

[[v7-2-18]]

^<<v7-2-18,18>>^ Quando o Senhor suscitava juízes, enquanto estes viviam, ele deixava-se dobrar da misericórdia, ouvia os gemidos dos aflitos e livrava-os da crueldade dos opressores.

[[v7-2-19]]

^<<v7-2-19,19>>^ Mas, depois que o juiz morria, reincidiam, faziam coisas muito piores do que tinham feito seus pais, seguindo os deuses estranhos, servindo-os e adorando-os. Não abandonaram os seus desatinos, nem o caminho duríssimo, por onde tinham costume de andar.

[[v7-2-20]]

^<<v7-2-20,20>>^ Acendeu-se, pois, contra Israel o furor do Senhor, e ele disse: Visto que este povo violou o pacto, que eu tinha feito com seus pais, e recusou ouvir a minha voz,

[[v7-2-21]]

^<<v7-2-21,21>>^ também eu não destruirei as nações (inimigas), que Josué deixou quando morreu, a fim de, por meio delas,

[[v7-2-22]]

^<<v7-2-22,22>>^ pôr à prova Israel, (para ver) se procura seguir ou não o caminho do Senhor, como seus pais procuraram.

[[v7-2-23]]

^<<v7-2-23,23>>^ Por isso o Senhor deixou todas estas nações, não as quis destruir logo, nem as entregou nas mãos de Josué.

'''

xref:007-juizes/007-juizes-001.adoc#v7-1-0[&#60; Capítulo Anterior] | <<v7-2-0,Topo>> | xref:007-juizes/007-juizes-003.adoc#v7-3-0[Próximo Capítulo &#62;]