include::./index.adoc[]

[[v17-11-0]]
=== Tobias, 11
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* Tobias 11 conta a história de Tobias e Sara se casando e a cura da cegueira do pai de Tobias por meio do uso do fel do peixe que ele havia capturado. Alguns temas que podem ser abordados nesse capítulo incluem o casamento, a cura divina e a importância de manter a fé em Deus. Abaixo estão cinco versículos relacionados a esses temas:
* Gênesis 2:24: "Por essa razão, o homem deixará pai e mãe e se unirá à sua mulher, e eles se tornarão uma só carne." Este versículo fala sobre o casamento e a união entre homem e mulher.
* Tiago 5:15: "E a oração feita com fé curará o doente, e o Senhor o levantará; e se tiver cometido pecados, ser-lhe-ão perdoados." Este versículo fala sobre a cura divina por meio da oração e da fé em Deus.
* Mateus 19:6: "Assim, já não são dois, mas uma só carne. Portanto, o que Deus uniu, ninguém o separe." Este versículo fala sobre a importância da união matrimonial e do compromisso entre o casal.
* João 14:1: "Não se turbe o vosso coração; credes em Deus, crede também em mim." Este versículo fala sobre manter a fé em Deus, mesmo diante de dificuldades e incertezas.
* Tiago 1:6: "Peça-a, porém, com fé, sem duvidar; pois aquele que duvida é semelhante à onda do mar, que é levada e agitada pelo vento." Este versículo fala sobre a importância de ter fé em Deus e não duvidar de sua capacidade de realizar milagres e curas.
****

[[v17-11-1]]

^<<v17-11-1,1>>^ De regresso, chegaram no undécimo dia a Caran, que está no meio do caminho para Nínive.

[[v17-11-2]]

^<<v17-11-2,2>>^ O anjo disse: Irmão Tobias, tu sabes o estado em que deixaste teu pai.

[[v17-11-3]]

^<<v17-11-3,3>>^ Se assim, pois, te parece bem, vamos nós adiante, e os teus domésticos sigam-nos devagar com tua mulher e com os gados

[[v17-11-4]]

^<<v17-11-4,4>>^ Tendo Tobias achado bom este parecer, disse-lhe Rafael: Traz contigo do fel do peixe, porque será necessário. Tomou, portanto, Tobias do fel, e partiram.

[[v17-11-5]]

^<<v17-11-5,5>>^ Entretanto Ana todos os dias se ia assentar junto da estrada, no alto duma colina, donde podia ver ao longe,

[[v17-11-6]]

^<<v17-11-6,6>>^ Enquanto desse lugar espreitava a sua vinda, viu ao longe e logo reconheceu seu filho que vinha; (logo) correu a dar a nova a seu marido, dizendo: Eis ai vem teu filho.

[[v17-11-7]]

^<<v17-11-7,7>>^ Ao mesmo tempo Rafael disse a Tobias: Quando tiveres entrado em tua casa, adora logo ao Senhor teu Deus e dá-lhe graças; depois aproxima-te de teu pai e dá-lhe um beijo.

[[v17-11-8]]

^<<v17-11-8,8>>^ Unta-lhe imediatamente os seus olhos com este fel do peixe, que trazes contigo, porque está certo que logo os seus olhos se abrirão, que teu pai verá a luz do céu e se alegrará em te ver,

[[v17-11-9]]

^<<v17-11-9,9>>^ Então o cão, que os tinha seguido pelo caminho, correu adiante e, como que trazendo a nova, mostrava o seu contentamento e fazia festas, abanando a cauda.

[[v17-11-10]]

^<<v17-11-10,10>>^ O pai, levantando-se, começou a correr cego, tropeçando. Dando, então, a mão a um criado, foi ao encontro de seu filho.

[[v17-11-11]]

^<<v17-11-11,11>>^ Abraçou-o e beijou-o, fazendo o mesmo sua mulher, e ambos começaram a chorar de alegria.

[[v17-11-12]]

^<<v17-11-12,12>>^ Depois que adoraram a Deus e lhe deram graças, assentaram-se.

[[v17-11-13]]

^<<v17-11-13,13>>^ Então Tobias, tomando do fel do peixe, untou os olhos de seu pai.

[[v17-11-14]]

^<<v17-11-14,14>>^ Esperou quase meia hora, e, (então), começou a sair de seus olhos uma belida, como a película dum ovo.

[[v17-11-15]]

^<<v17-11-15,15>>^ Tobias, pegando nela, tirou-a dos olhos do pai, que imediatamente recobrou a vista,

[[v17-11-16]]

^<<v17-11-16,16>>^ E glorificaram a Deus, ele, sua mulher e todos os que ó conheciam.

[[v17-11-17]]

^<<v17-11-17,17>>^ Tobias dizia: Eu te bendigo. Senhor Deus de Israel, por me teres castigado e por me teres curado; eis que vejo o meu filho Tobias!

[[v17-11-18]]

^<<v17-11-18,18>>^ Passados sete dias, chegou também Sara, mulher de seu filho, com todos os seus servidores, de boa saúde, com os rebanhos, os camelos, o grande dote do seu casamento e com o dinheiro restituído por Gabelo.

[[v17-11-19]]

^<<v17-11-19,19>>^ Tobias contou a seus pais todos os benefícios que Deus Ihe tinha feito, por meio desse homem, que o conduzira.

[[v17-11-20]]

^<<v17-11-20,20>>^ Aquior e Nabat, primos de Tobias, foram regozijar-se com Tobias, congratular-se com ele por todos os favores que Deus lhe tinha feito.

[[v17-11-21]]

^<<v17-11-21,21>>^ Banqueteando-se durante sete dias, todos se regozijaram com a maior alegria.

'''

xref:017-tobias/017-tobias-010.adoc#v17-10-0[&#60; Capítulo Anterior] | <<v17-11-0,Topo>> | xref:017-tobias/017-tobias-012.adoc#v17-12-0[Próximo Capítulo &#62;]