include::./index.adoc[]

[[v17-12-0]]
=== Tobias, 12
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 12 do livro de Tobias descreve a celebração do casamento de Tobias e Sara, com a participação de seus familiares e amigos. Além disso, o capítulo também apresenta o papel do anjo Rafael na cura de Tobit e na realização do casamento. Seguem abaixo cinco versículos relacionados com os temas abordados em Tobias 12:
* Salmos 126:3 - "O Senhor fez grandes coisas por nós, e por isso estamos alegres." A celebração do casamento de Tobias e Sara é um momento de grande alegria para todos os envolvidos, e este versículo expressa a gratidão pelo que Deus fez por eles.
* Provérbios 18:22 - "Quem encontra uma esposa encontra algo excelente; recebeu uma bênção do Senhor." Este versículo fala sobre a importância de encontrar uma esposa e como isso é uma bênção de Deus. Para Tobias, a sua união com Sara é um presente divino.
* Eclesiastes 4:12 - "E se alguém quiser prevalecer contra um, os dois lhe resistirão; e o cordão de três dobras não se quebra tão depressa." Este versículo destaca a importância da união e da parceria em momentos difíceis, e isso é visto na relação entre Tobias e o anjo Rafael em sua jornada.
* Marcos 10:9 - "Portanto, o que Deus uniu, ninguém o separe." Este versículo fala sobre a santidade do matrimônio e como ele é uma união divina. Tobias e Sara são unidos por Deus e ninguém pode separá-los.
* Filipenses 4:4 - "Alegrem-se sempre no Senhor. Novamente direi: alegrem-se!" Este versículo expressa a importância da alegria em todas as circunstâncias e é aplicável à celebração do casamento de Tobias e Sara, que é um momento de grande felicidade.
****

[[v17-12-1]]

^<<v17-12-1,1>>^ Então Tobias chamou seu filho e disse-lhe: Que podemos nós dar a este santo homem que te acompanhou ?

[[v17-12-2]]

^<<v17-12-2,2>>^ Ele respondeu: Meu pai, que galardão lhe daremos nós? que coisa poderá haver proporcionada aos seus benefícios?

[[v17-12-3]]

^<<v17-12-3,3>>^ Ele levou-me e trouxe-me são e salvo; recebeu de Gabelo o dinheiro; fez-me ter mulher e afugentou dela o demónio; encheu de alegria os seus pais; livrou-me a mim mesmo de ser tragado pelo peixe; a ti fez-te ver a luz do céu: por ele nós fomos cheios de todos os bens. Que lhe poderemos dar que iguale tais benefícios?

[[v17-12-4]]

^<<v17-12-4,4>>^ Rogo-te, meu pai, que lhe peças se digne tomar para si metade de tudo o que trouxemos.

[[v17-12-5]]

^<<v17-12-5,5>>^ O pai e o filho chamaram-no, pois, à parte, e começaram a rogar-lhe que se dignasse aceitar metade de tudo o que tinham trazido.

[[v17-12-6]]

^<<v17-12-6,6>>^ Então ele falou-lhes particularmente; Bendizei o Deus do céu, dai-lhe glória diante de todos os viventes, por ter usado convosco da sua misericórdia.

[[v17-12-7]]

^<<v17-12-7,7>>^ E bom conservar escondido o segredo do rei, mas é coisa louvável manifestar e publicar as obras de Deus.

[[v17-12-8]]

^<<v17-12-8,8>>^ E boa a oração acompanhada do jejum, e dar esmola vale mais do que juntar tesouros de ouro,

[[v17-12-9]]

^<<v17-12-9,9>>^ porque a esmola livra da morte (eterna): apaga os pecados e faz encontrar a misericórdia e a vida eterna.

[[v17-12-10]]

^<<v17-12-10,10>>^ Mas os que cometem pecado e iniquidade, são inimigos das suas almas.

[[v17-12-11]]

^<<v17-12-11,11>>^ Eu vou descobrir-vos a verdade, não quero ocultar-vos nada.

[[v17-12-12]]

^<<v17-12-12,12>>^ Quando tu oravas com lágrimas, enterravas os mortos, quando deixavas o teu jantar, para esconder os mortos em tua casa de dia, e os enterrar de noite, eu apresentei as tuas orações ao Senhor.

[[v17-12-13]]

^<<v17-12-13,13>>^ Porque tu eras aceito a Deus, por isso foi necessário que a tentação te provasse.

[[v17-12-14]]

^<<v17-12-14,14>>^ Agora o Senhor enviou-me a curar-te e a livrar do demônio a Sara, mulher de teu filho.

[[v17-12-15]]

^<<v17-12-15,15>>^ Eu sou o anjo Rafael, um dos sete (espíritos principais) que assistimos diante do Senhor.

[[v17-12-16]]

^<<v17-12-16,16>>^ Ao ouvir estas palavras, ficaram fora de si, e, tremendo, caíram com o rosto em terra.

[[v17-12-17]]

^<<v17-12-17,17>>^ O anjo disse-lhe: A paz seja convosco, não temais.

[[v17-12-18]]

^<<v17-12-18,18>>^ Quando eu estava convosco, eu o estava por vontade de Deus; bendizei-o, cantai-lhe louvores.

[[v17-12-19]]

^<<v17-12-19,19>>^ Parecia-vos que eu comia e bebia convosco, mas eu sustento-me dum manjar invisível, duma bebida (que consiste na visão de Deus) a qual não pode ser vista pelos homens.

[[v17-12-20]]

^<<v17-12-20,20>>^ É , pois, tempo que eu volte para aquele que me enviou; vós, porém, bendizei a Deus, e contai todas as suas maravilhas.

[[v17-12-21]]

^<<v17-12-21,21>>^ Proferidas estas palavras, desapareceu diante deles, e eles não o puderam ver mais.

[[v17-12-22]]

^<<v17-12-22,22>>^ Então prostrando-se com o rosto por terra durante três horas, bendisseram a Deus; depois, erguendo-se, publicaram todas as suas maravilhas.

'''

xref:017-tobias/017-tobias-011.adoc#v17-11-0[&#60; Capítulo Anterior] | <<v17-12-0,Topo>> | xref:017-tobias/017-tobias-013.adoc#v17-13-0[Próximo Capítulo &#62;]