include::./index.adoc[]

[[v72-1-0]]
=== São Judas, 1
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* São Judas 1 trata principalmente sobre a necessidade de se defender a fé cristã contra os falsos ensinamentos e os falsos mestres que estavam infiltrados na comunidade cristã. É enfatizado o perigo dessas pessoas que distorcem a verdade e corrompem a fé dos crentes. Abaixo estão cinco versículos da Bíblia que tratam de temas relacionados ao livro de São Judas:
* 2 Pedro 2:1: "Entretanto, surgiram falsos profetas no meio do povo, como também surgirão entre vós falsos mestres, os quais introduzirão, dissimuladamente, heresias destruidoras, até ao ponto de renegarem o Soberano Senhor que os resgatou, trazendo sobre si mesmos repentina destruição." Este versículo fala sobre o surgimento de falsos mestres e profetas, assim como descrito em São Judas 1, que introduzem heresias que podem corromper a fé dos crentes.
* 1 João 4:1: "Amados, não creiais a todo espírito, mas provai se os espíritos vêm de Deus; porque muitos falsos profetas têm saído pelo mundo fora." Este versículo exorta os cristãos a examinar cuidadosamente as doutrinas que são apresentadas a eles e a testar os espíritos, para evitar serem enganados por falsos profetas.
* Mateus 7:15: "Acautelai-vos dos falsos profetas, que se vos apresentam disfarçados em ovelhas, mas por dentro são lobos roubadores." Este versículo adverte os crentes a estarem atentos aos falsos profetas, que podem parecer inofensivos, mas na verdade estão disfarçados para enganá-los.
* 1 Timóteo 4:1: "O Espírito Santo afirma expressamente que, nos últimos tempos, alguns apostatarão da fé, por obedecerem a espíritos enganadores e a ensinos de demônios." Este versículo alerta sobre a possibilidade de alguns abandonarem a fé por causa de doutrinas falsas e ensinos enganosos.
* 2 Coríntios 11:13-15: "Porque tais falsos apóstolos são obreiros fraudulentos, transfigurando-se em apóstolos de Cristo. E não é de admirar, porque o próprio Satanás se transfigura em anjo de luz. Não é muito, pois, que os seus próprios ministros se transfigurem em ministros da justiça; e o fim deles será conforme as suas obras." Este versículo descreve os falsos apóstolos e ministros que se disfarçam como trabalhadores da justiça, mas na verdade são fraudulentos e seguem os ensinamentos de Satanás.
****

[[v72-1-1]]

^<<v72-1-1,1>>^ Judas, servo de Jesus Cristo e irmão de Tiago, aos eleitos, amados por Deus Pai e guardados por Jesus Cristo.

[[v72-1-2]]

^<<v72-1-2,2>>^ A misericórdia, a paz e a caridade vos sejam dadas abundantemente.

[[v72-1-3]]

^<<v72-1-3,3>>^ Caríssimos, desejando eu com toda a solicitude escrever-vos acerca da nossa comum salvação, tive necessidade de o fazer, para vos exortar a combater pela fé, que foi dada aos santos, uma vez por todas.

[[v72-1-4]]

^<<v72-1-4,4>>^ Efectivamente, introduziram-se entre vós certos homens ímpios (dos quais está escrito há muito tempo que viriam a cair nesta condenação), os quais trocam a graça do nosso Deus em luxúria, e negam a Jesus Cristo, nosso único Dominador e Senhor.

[[v72-1-5]]

^<<v72-1-5,5>>^ Ora eu quero recordar-vos, embora já saibais tudo, que Jesus, salvando o povo da terra do Egipto, destruiu depois aqueles que não creram;

[[v72-1-6]]

^<<v72-1-6,6>>^ e os anjos, que não conservaram o seu principado, mas abandonaram o seu domicílio, os reteve com cadeias eternas, nas trevas, para o juízo do grande dia.

[[v72-1-7]]

^<<v72-1-7,7>>^ Assim Sodoma, Gomorra e as cidades circunvizínhas, que com elas se entregaram à luxúria e se abandonaram aos vícios contra a natureza, foram postas por escarmento, sofrendo a pena do fogo eterno.

[[v72-1-8]]

^<<v72-1-8,8>>^ Da mesma maneira também estes, no seu delírio, contaminam a sua carne, desprezam a Dominação (de Cristo) e insultam as glórias.

[[v72-1-9]]

^<<v72-1-9,9>>^ Quando o Arcanjo Miguel, disputando com o demônio, altercava sobre o corpo de Moisés, não se atreveu a proferir contra ele uma acusação injuriosa, mas disse (somente): Reprima-te o Senhor. (ver nota)

[[v72-1-10]]

^<<v72-1-10,10>>^ Estes, porém, blasfemam de todas as coisas que ignoram, e perdem-se como animais sem razão, em todas aquelas coisas que conhecem naturalmente.

[[v72-1-11]]

^<<v72-1-11,11>>^ Ai deles, porque andaram pelo caminho de Caim, e, por (causa de um aviltante) lucro, precipitaram-se no erro de Balaão e pereceram na rebelião de Coré.

[[v72-1-12]]

^<<v72-1-12,12>>^ Eles são as máculas dos vossos festins, em que se banqueteiam sem respeito, apascentando-se a si mesmos, nuvens sem água, que os ventos levam de uma parte para a outra, árvores de fim de outono, sem fruto, duas vezes mortas, desarraigadas,

[[v72-1-13]]

^<<v72-1-13,13>>^ ondas furiosas do mar, que arrojam as espumas da sua torpeza, estrelas errantes, para quem espessas trevas estão reservadas por toda a eternidade.

[[v72-1-14]]

^<<v72-1-14,14>>^ Também Henoch, o sétimo patriarca depois de Adão, profetizou destes, dizendo: Eis que vem o Senhor, com as suas santas miríades,

[[v72-1-15]]

^<<v72-1-15,15>>^ a fazer juízo contra todos, é a confundir todos os ímpios de todas as obras de impiedade, que cometeram, e de todas as palavras injuriosas, que os pecadores impios têm proferido contra ele (Deus).

[[v72-1-16]]

^<<v72-1-16,16>>^ Eles são uns murmuradores queixosos, que andam segundo as suas paixões, e a sua boca profere coisas soberbas, as quais mostram admiração pelas pessoas segundo convém ao seu próprio interesse.

[[v72-1-17]]

^<<v72-1-17,17>>^ Mas vós, caríssimos, lembrai-vos do que foi predito pelos Apóstolos de Nosso Senhor Jesus Cristo,

[[v72-1-18]]

^<<v72-1-18,18>>^ os quais vos diziam : "Nos últimos tempos virão impostores, que andarão segundo as suas paixões, cheias de impiedade."

[[v72-1-19]]

^<<v72-1-19,19>>^ Estes são os que provocam divisões, seres sensuais que não têm o Espírito (de Deus).

[[v72-1-20]]

^<<v72-1-20,20>>^ Vós, porém, caríssimos, edificando-vos a vós mesmos sobre o fundamento da vossa santíssima fé, orando no Espírito Santo,

[[v72-1-21]]

^<<v72-1-21,21>>^ conservai-vos no amor de Deus, esperando a misericórdia de Nosso Senhor Jesus Cristo para (alcançar) a vida eterna.

[[v72-1-22]]

^<<v72-1-22,22>>^ Esforçai-vos por convencer os hesitantes,

[[v72-1-23]]

^<<v72-1-23,23>>^ salvai aqueles que podeis arrancar ao fogo. Dos mais, tende compaixão com temor (de serdes contaminados), aborrecendo até a túnica que está contaminada pela sua carne.

[[v72-1-24]]

^<<v72-1-24,24>>^ Aquele que é poderoso para vos conservar sem pecado e para vos apresentar imaculados e cheios de alegria diante da sua glória,

[[v72-1-25]]

^<<v72-1-25,25>>^ ao Deus único, Salvador nosso, por Jesus Cristo Nosso Senhor, seja dada glória, magnificência, força e poder, antes de todos os tempos, e agora e por todos os séculos. Amém.

'''

xref:071-iii-sao-joao/071-iii-sao-joao-001.adoc#v71-1-0[&#60; Capítulo Anterior] | <<v72-1-0,Topo>> | xref:073-apocalipse/073-apocalipse-001.adoc#v73-1-0[Próximo Capítulo &#62;]