include::./index.adoc[]

[[v12-7-0]]
=== II Reis, 7
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* 2 Reis 7 trata da libertação de Samaria da fome imposta pelos sírios, por meio da intervenção divina. O capítulo começa com a profecia do profeta Eliseu de que haveria um grande abastecimento de alimentos na cidade. Isso acontece por meio do medo que Deus impõe aos sírios, que abandonam seus mantimentos e fogem. Quatro leprosos, excluídos da cidade, encontram o tesouro deixado pelos sírios e compartilham a notícia com os samaritanos, que finalmente desfrutam da fartura. Abaixo estão cinco versículos relacionados aos temas abordados em 2 Reis 7.
* Salmos 33:18: "Mas os olhos do Senhor estão sobre os que o temem, sobre os que esperam na sua misericórdia." O profeta Eliseu confia na intervenção de Deus para salvar o povo de Samaria da fome, e essa confiança é reforçada pela certeza de que Deus está atento aos que o temem e esperam em sua misericórdia.
* Provérbios 21:1: "O coração do rei é como correntes de água na mão do Senhor; ele o inclina para onde quer." A intervenção divina na situação de Samaria é uma demonstração do poder e soberania de Deus, que é capaz de influenciar até mesmo os governantes de nações estrangeiras para cumprir seus propósitos.
* Isaías 33:6: "E haverá estabilidade em teus tempos, abundância de salvação, sabedoria e conhecimento; e o temor do Senhor será o teu tesouro." A fartura que chega a Samaria após a fuga dos sírios é um sinal da bondade e do cuidado de Deus para com seu povo, que pode desfrutar da estabilidade e da salvação.
* Jeremias 51:10: "O Senhor trouxe à luz a nossa justiça; vinde e declaremos em Sião a obra do Senhor, nosso Deus." A descoberta do tesouro deixado pelos sírios pelos leprosos é um testemunho da obra de Deus em libertar o seu povo da fome e da opressão.
* João 6:35: "Disse-lhes Jesus: Eu sou o pão da vida; aquele que vem a mim não terá fome, e quem crê em mim nunca terá sede." A intervenção divina em Samaria é uma prefiguração do amor e cuidado de Deus por seu povo em todas as épocas, culminando na pessoa de Jesus, o pão da vida que satisfaz todas as necessidades espirituais e físicas.
****

[[v12-7-1]]

^<<v12-7-1,1>>^ Eliseu disse: Ouvi a palavra do Senhor: Eis o que diz o Senhor: Amanhã, a esta hora, dar-se-á uma medida de flor de farinha por siclo, e por um siclo se darão duas medidas de cevada, à porta de Samaria.

[[v12-7-2]]

^<<v12-7-2,2>>^ Respondendo um dos capitães, a cujo braço o rei estava encostado, ao homem de Deus, disse: Quando o Senhor abrir janelas no céu, (para chover trigo) poderá acaso ser o que tu dizes? Eliseu respondeu: Tu o verás com os teus olhos, mas não comerás dele.

[[v12-7-3]]

^<<v12-7-3,3>>^ Ora estavam quatro homens leprosos à entrada da porta, os quais disseram entre si: Para que estamos nós aqui até morrermos?

[[v12-7-4]]

^<<v12-7-4,4>>^ Se quisermos entrar na cidade, morreremos de fome; se ficarmos aqui, morreremos também. Vamo-nos, pois, e passemo-nos para o acampamento dos Sírios. Se eles se compadecerem de nós, viveremos; se nos quiserem matar, sem dúvida morreremos.

[[v12-7-5]]

^<<v12-7-5,5>>^ Partiram, pois, ao anoitecer, para o acampamento dos Sírios, mas, tendo chegado à entrada do acampamento, não encontraram ali ninguém.

[[v12-7-6]]

^<<v12-7-6,6>>^ Com efeito, o Senhor tinha feito ouvir no campo dos Sírios um estrondo de carros, de cavalos e dum exército muito numeroso, de forma que os Sírios disseram entre si: Sem dúvida, o rei de Israel mandou assoldadar contra nós os reis dos Heteus e dos Egípcios, e ei-los aí vêm sobre nós.

[[v12-7-7]]

^<<v12-7-7,7>>^ Levantaram-se, pois, e fugiram de noite, deixando no acampamento as suas tendas, os seus cavalos e jumentos, e cuidando sòmente em salvar as suas vidas.

[[v12-7-8]]

^<<v12-7-8,8>>^ Tendo, pois, chegado aqueles leprosos à entrada do acampamento, entraram numa barraca, comeram, beberam e levaram dali prata e ouro e roupas, que foram esconder; depois tornaram a outra barraca e esconderam também o que pilharam.

[[v12-7-9]]

^<<v12-7-9,9>>^ Então disseram um para o outro: Não fazemos bem, porque este é um dia de boa nova. Se nos calarmos e não quisermos avisar até amanhã, seremos arguidos de crime; vamos e levemos a nova à corte do rei.

[[v12-7-10]]

^<<v12-7-10,10>>^ Tendo chegado à porta da cidade, contaram o sucedido: Nós fomos ao campo dos Sírios e não encontramos lá homem algum, mas sòmente cavalos, jumentos presos, e as suas tendas armadas.

[[v12-7-11]]

^<<v12-7-11,11>>^ Foram os guardas da porta dar aviso aos de dentro do palácio do rei,

[[v12-7-12]]

^<<v12-7-12,12>>^ o qual se levantou de noite e disse aos seus oficiais: Eu vos direi o que fizeram os Sírios contra nós: Sabem que a fome nos aperta, e por isso saíram do seu arraial e esconderam-se pelos campos, dizendo: Logo que saírem da cidade, nós os apanharemos vivos, e então poderemos entrar na cidade.

[[v12-7-13]]

^<<v12-7-13,13>>^ Mas um dos servos do rei respondeu: Tomem os os cinco cavalos, que ficaram na cidade (porque só estes restaram de tão grande número que havia em Israel, porque os outros foram consumidos) e, mandando estes, poderemos descobrir o que há.

[[v12-7-14]]

^<<v12-7-14,14>>^ Tomaram, pois, dois carros com os seus cavalos, e o rei mandou (gente) seguir os dos Sírios, dizendo: Ide e vede.

[[v12-7-15]]

^<<v12-7-15,15>>^ Eles foram em busca dos Sírios, até ao Jordão, e acharam que todo o caminho estava cheio de vestes e de armas, que os Sírios tinham arrojado na sua precipitação. Os mensageiros, voltando, deram conta ao rei.

[[v12-7-16]]

^<<v12-7-16,16>>^ Então o povo saiu e saqueou o acampamento dos Sírios. Uma medida de flor de farinha foi vendida por um siclo, e duas medidas de cevada por um siclo, conforme a palavra do Senhor.

[[v12-7-17]]

^<<v12-7-17,17>>^ Ora o rei pôs à porta (da cidade) aquele oficial, no braço do qual ele se apoiava, mas a multidão atropelou-o à entrada da porta, e morreu, conforme lhe tinha predito o homem de Deus, quando o rei foi ter com ele.

[[v12-7-18]]

^<<v12-7-18,18>>^ (Tudo) aconteceu segundo a palavra que o homem de Deus tinha predito ao rei, quando lhe disse: Amanhã a esta mesma hora, à porta de Samaria, serão vendidas por um siclo duas medidas de cevada, e por um siclo uma medida de flor de farinha.

[[v12-7-19]]

^<<v12-7-19,19>>^ Quando aquele oficial tinha respondido ao homem de Deus: Quando o Senhor abrir janelas no céu (para chover trigo), poderá acaso ser o que tu dizes?- - Eliseu replicou: Tu o verás com os teus olhos, mas não comerás dele.

[[v12-7-20]]

^<<v12-7-20,20>>^ Como Eliseu lhe tinha predito, assim sucedeu: o povo o atropelou à porta, e ele morreu.

'''

xref:012-ii-reis/012-ii-reis-006.adoc#v12-6-0[&#60; Capítulo Anterior] | <<v12-7-0,Topo>> | xref:012-ii-reis/012-ii-reis-008.adoc#v12-8-0[Próximo Capítulo &#62;]