include::./index.adoc[]

[[v12-6-0]]
=== II Reis, 6
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 6 de 2 Reis conta a história do profeta Eliseu e seus discípulos, que vivem cercados de conflitos e desafios em meio a uma sociedade dividida e em guerra. Em meio a essas dificuldades, eles aprendem a confiar em Deus e a enfrentar as adversidades com coragem e fé. Abaixo estão cinco versículos da Bíblia que se relacionam com os temas abordados em 2 Reis 6:
* Salmos 34:7: "O anjo do Senhor acampa-se ao redor dos que o temem, e os livra." Esse versículo fala sobre a proteção divina que está disponível para aqueles que confiam em Deus. Assim como Eliseu e seus discípulos foram protegidos dos inimigos, podemos confiar que Deus também nos protege em meio aos nossos próprios desafios e conflitos.
* Isaías 41:10: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te fortaleço, e te ajudo, e te sustento com a minha destra fiel." Este versículo traz uma mensagem de coragem e conforto para aqueles que enfrentam dificuldades. Ele nos lembra que Deus está conosco em todas as situações e que podemos encontrar força e ajuda nele.
* Filipenses 4:13: "Posso todas as coisas naquele que me fortalece." Essa passagem nos lembra que, com a ajuda de Deus, podemos enfrentar qualquer desafio. Como Eliseu e seus discípulos, podemos encontrar a força e a coragem necessárias para perseverar, mesmo em momentos de dificuldade e incerteza.
* Romanos 8:28: "Sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus, daqueles que são chamados segundo o seu propósito." Esse versículo nos lembra que Deus tem um propósito para as nossas vidas e que todas as coisas que acontecem podem ser usadas para o nosso bem. Mesmo em meio a situações difíceis, podemos confiar que Deus está trabalhando para cumprir seus planos em nossas vidas.
* Provérbios 3:5-6: "Confie no Senhor de todo o seu coração e não se apóie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas." Essa passagem nos lembra da importância de confiar em Deus e buscar sua sabedoria em todas as áreas da nossa vida. Em 2 Reis 6, Eliseu e seus discípulos confiaram em Deus para ajudá-los a enfrentar os desafios que enfrentaram. Podemos aprender com eles e também buscar a orientação divina em nossas próprias lutas e conflitos.
****

[[v12-6-1]]

^<<v12-6-1,1>>^ Os filhos dos profetas disseram a Eliseu: Vê que o lugar, em que moramos contigo, é estreito para nós.

[[v12-6-2]]

^<<v12-6-2,2>>^ Vamos até ao Jordão, e cada um de nós corte madeira do bosque, a fim de edificarmos aí uma habitação. Ele respondeu: Ide.

[[v12-6-3]]

^<<v12-6-3,3>>^ Um deles disse-lhe: Pois vem tu também com os teus servos. Ele respondeu: Eu irei.

[[v12-6-4]]

^<<v12-6-4,4>>^ E foi com eles. Chegados ao Jordão, puseram-se a cortar madeiras.

[[v12-6-5]]

^<<v12-6-5,5>>^ Aconteceu, porém, que um, ao cortar uma árvore, deixou cair na água o ferro do machado; gritou e disse: Ai! meu senhor! Este mesmo o tinha pedido emprestado.

[[v12-6-6]]

^<<v12-6-6,6>>^ E o homem de Deus disse: Onde caiu? Ele mostrou-lhe o lugar. Então Eliseu cortou um pau, lançou-o no mesmo lugar, e o ferro veio acima nadando.

[[v12-6-7]]

^<<v12-6-7,7>>^ E disse: Tira-o. Ele estendeu a mão e tirou-o.

[[v12-6-8]]

^<<v12-6-8,8>>^ O rei da Síria, que combatia contra Israel, teve conselho com os seus oficiais e disse-lhes: Armemos emboscadas em tal e em tal lugar.

[[v12-6-9]]

^<<v12-6-9,9>>^ Mandou então o homem de Deus dizer ao rei de Israel: Acautela-te, não passes por tal lugar, porque os Sírios estão lá de emboscada.

[[v12-6-10]]

^<<v12-6-10,10>>^ O rei de Israel enviou (gente sua) ao lugar que o homem de Deus lhe indicara, para o vigiar, e isto sucedeu não apenas uma ou duas vezes.

[[v12-6-11]]

^<<v12-6-11,11>>^ O coração do rei da Síria turbou-se com este acidente, e, convocados os seus servos, disse: Por que me não descobris vós quem é o que me faz traição junto do rei de Israel?

[[v12-6-12]]

^<<v12-6-12,12>>^ Um dos seus servos respondeu: Não é nada disso, ó rei meu Senhor, mas o profeta Eliseu, que está em Israel, faz saber ao rei de Israel tudo o que tu dizes no teu gabinete.

[[v12-6-13]]

^<<v12-6-13,13>>^ Ele disse-lhes: Ide e vede onde ele está, para eu o mandar prender. Avisaram-no dizendo: Eliseu está em Dotan.

[[v12-6-14]]

^<<v12-6-14,14>>^ O rei mandou logo cavalaria, carros e boas tropas; tendo eles chegado de noite, cercaram a cidade.

[[v12-6-15]]

^<<v12-6-15,15>>^ Porém, levantando-se ao amanhecer o criado do homem de Deus, saindo fora, viu o exército em volta da cidade, a cavalaria e os carros, e avisou-o disso, dizendo: Ai! meu senhor! Que havemos de fazer?

[[v12-6-16]]

^<<v12-6-16,16>>^ Eliseu respondeu: Não temas; muitos mais estão conosco do que com eles.

[[v12-6-17]]

^<<v12-6-17,17>>^ Eliseu, fazendo oração, disse: Senhor, abre os olhos deste, para que veja. E o Senhor abriu os olhos do criado, que viu o monte cheio de cavalos e de carros de fogo, ao redor de Eliseu.

[[v12-6-18]]

^<<v12-6-18,18>>^ Nisto os inimigos desceram para ele, e Eliseu fez a sua oração ao Senhor, dizendo: Fere, te peço, de cegueira a esta gente. E o Senhor os feriu de cegueira, conforme a palavra de Eliseu.

[[v12-6-19]]

^<<v12-6-19,19>>^ Eliseu disse-lhes: Não é este o caminho, nem é esta a cidade; segui-me, e eu vos mostrarei o homem que vós buscais. Ele pois, os levou a Samaria.

[[v12-6-20]]

^<<v12-6-20,20>>^ Tendo eles entrado em Samaria, disse Eliseu: Senhor, abre-lhes os olhos, para que vejam. E o Senhor abriu-lhes os olhos, e viram que estavam no meio da Samaria.

[[v12-6-21]]

^<<v12-6-21,21>>^ O rei de Israel, tendo-os visto, disse a Eliseu: Matá-los-ei, meu pai?

[[v12-6-22]]

^<<v12-6-22,22>>^ Ele respondeu: Não os matarás, porque não os fizeste prisioneiros com a tua espada nem com o teu arco, mas manda-lhes pôr diante pão e água para que comam e bebam, e voltem para o seu senhor.

[[v12-6-23]]

^<<v12-6-23,23>>^ E foi posta diante deles uma grande quantidade de alimentos; comeram e beberam, e despediu-os, e eles voltaram para o seu senhor. Os guerrilheiros da Síria não tornaram mais às terras de Israel.

[[v12-6-24]]

^<<v12-6-24,24>>^ Aconteceu, depois, que Benadad, rei da Síria, juntou todas as suas tropas e foi sitiar Samaria.

[[v12-6-25]]

^<<v12-6-25,25>>^ Houve uma grande fome em Samaria, e o cerco durou tanto que se chegou a vender a cabeça de um jumento por oitenta moedas de prata, e a quarta parte dum cab de esterco de pombas por cinco moedas de prata.

[[v12-6-26]]

^<<v12-6-26,26>>^ Passando o rei de Israel pelo muro, gritou-lhe uma mulher: Salva-me, ó rei meu senhor.

[[v12-6-27]]

^<<v12-6-27,27>>^ Ele disse: Se o Senhor não te salva, como posso eu salvar-te? Com trigo da eira, ou vinho do lagar? E o re i acrescentou: Que é que tu queres? Ela respondeu:

[[v12-6-28]]

^<<v12-6-28,28>>^ Esta mulher disse-me: Dá-me o teu filho, para o comermos hoje; amanhã comeremos o meu filho.

[[v12-6-29]]

^<<v12-6-29,29>>^ Cozemos, pois, o meu filho, e comemo-lo. Ao outro dia disse-lhe eu: Dá o teu filho para o comermos. E ela escondeu o seu filho.

[[v12-6-30]]

^<<v12-6-30,30>>^ O rei, tendo ouvido isto, rasgou os seus vestidos; como ia passando pelo muro, todo o povo viu o cilício que ele levava vestido interiormente sobre a carne.

[[v12-6-31]]

^<<v12-6-31,31>>^ O rei disse: Deus me trate com todo o seu rigor, se a cabeça de Eliseu, filho de Safat, lhe ficar hoje sobre os ombros.

[[v12-6-32]]

^<<v12-6-32,32>>^ Eliseu estava sentado em sua caso, e estavam sentados com ele os anciães. Mandou, pois, (o rei) um homem, mas antes que este mensageiro chegasse (Eliseu) disse aos anciães: Não sabeis que este filho do homicida (Acab) mandou cortar-me a cabeça? Tende pois cuidado; quando o mensageiro chegar, fechai a porta, e não o deixeis entrar, porque eis que eu ouço o ruído dos passos do seu senhor, que vem após ele.

[[v12-6-33]]

^<<v12-6-33,33>>^ Quando Eliseu ainda estava falando com eles, apareceu o rei, que vinha para ele e lhe disse: Vede que tão grande mal nos vem do Senhor; que mais esperarei eu do Senhor?

'''

xref:012-ii-reis/012-ii-reis-005.adoc#v12-5-0[&#60; Capítulo Anterior] | <<v12-6-0,Topo>> | xref:012-ii-reis/012-ii-reis-007.adoc#v12-7-0[Próximo Capítulo &#62;]