include::./index.adoc[]

[[v12-10-0]]
=== II Reis, 10
// matos-soares-1956 2005-02-05, Matos Soares (1956)

.Notas do capítulo
****
* O capítulo 10 de 2 Reis narra a vingança de Jeú contra a descendência de Acabe e Jezabel, incluindo a execução dos setenta filhos de Acabe e a matança dos adoradores de Baal em Israel. Jeú é retratado como um líder implacável e zeloso, mas também como alguém que se desvia da Lei de Deus em sua busca pelo poder. A seguir, estão cinco versículos que tratam dos temas presentes nesse capítulo:
* Salmos 94:1: "Ó Senhor Deus, a quem a vingança pertence, ó Deus, a quem a vingança pertence, mostra-te resplandecente!" Esse salmo clama pela justiça divina e pela vingança contra os ímpios que oprimem os justos. O desejo de Jeú de punir os adoradores de Baal pode ser visto como uma busca pela justiça divina, mas suas ações também podem ser vistas como excessivamente violentas.
* Jeremias 9:24: "Mas o que se gloriar, glorie-se nisto: em me entender e me conhecer, que eu sou o Senhor, que faço beneficência, juízo e justiça na terra; porque destas coisas me agrado, diz o Senhor." Esse versículo destaca a importância do conhecimento e compreensão de Deus e de suas ações. Jeú pode ter se desviado da Lei de Deus em sua busca pelo poder e vingança, e isso pode ser visto como uma falta de compreensão da vontade divina.
* Provérbios 28:1: "O ímpio foge, sem que haja ninguém a persegui-lo; mas o justo está confiante como um leão." Esse provérbio enfatiza a confiança e segurança dos justos, mesmo diante de ameaças e perseguições. Jeú pode ser visto como alguém que busca a segurança e o poder por meio da eliminação de seus inimigos, enquanto os justos confiam em Deus e em sua proteção.
* Isaías 59:7-8: "Os seus pés correm para o mal, e se apressam para derramarem o sangue inocente; os seus pensamentos são pensamentos de iniquidade; destruição e quebrantamento há nas suas estradas. Não conhecem caminho de paz, nem há justiça nos seus caminhos; torcem as suas veredas para eles mesmos; qualquer que anda por elas não tem conhecimento da paz." Esses versículos descrevem a maldade dos ímpios e sua falta de conhecimento da paz e da justiça. A busca de Jeú pela vingança e poder pode ser vista como uma manifestação dessa maldade e ignorância.
* Ezequiel 18:30: "Portanto, eu vos julgarei a cada um conforme os seus caminhos, ó casa de Israel, diz o Senhor Deus. Tornai-vos e convertei-vos de todas as vossas transgressões, para que a iniquidade não vos leve à perdição." Esse versículo destaca a importância do arrependimento e da conversão diante do julgamento divino. A busca de Jeú pela justiça pode ser vista como positiva, mas sua falta de arrependimento e conversão em relação à sua violência e desvio da Lei de Deus pode ser vista como uma falha em seguir o caminho da justiça divina. Assim, esse versículo destaca a importância de reconhecer as próprias transgressões e buscar a mudança de comportamento, para evitar a perdição e o julgamento divino.
****

[[v12-10-1]]

^<<v12-10-1,1>>^ Acab tinha setenta filhos em Samaria. Jeú escreveu uma carta e mandou-a a Samaria aos principais da cidade, aos anciães e aos aios dos filhos de Acab. Nela dizia:

[[v12-10-2]]

^<<v12-10-2,2>>^ Logo que receberdes esta carta, vós que tendes em vosso poder os filhos do vosso senhor, os carros, os cavalos, as cidades fortes e as armas,

[[v12-10-3]]

^<<v12-10-3,3>>^ escolhei o melhor, aquele que mais vos agradar dentre os filhos do vosso senhor, colocai-o sobre o trono de seu pai e pelejai pela casa de vosso Senhor.

[[v12-10-4]]

^<<v12-10-4,4>>^ Eles atemorizaram-se muito e disseram: Dois reis não puderam fazer-lhe frente, como poderemos nós resistir-lhe?

[[v12-10-5]]

^<<v12-10-5,5>>^ Pelo que os mordomos do palácio do rei, os oficiais da cidade, os anciães e os aios, mandaram dizer a Jeú: Nós somos teus servos, faremos tudo o que nos ordenares; não elegeremos rei sobre nós; faze tudo o que te agradar.

[[v12-10-6]]

^<<v12-10-6,6>>^ Então Jeú tornou-lhes a escrever segunda carta, dizendo: Se vós sois por mim e me obedeceis, cortai as cabeças aos filhos do vosso senhor, e vinde ter comigo amanhã, a esta mesma hora, a Jezrael. Os filhos do rei, em número de setenta, criavam-se em casa dos grandes da cidade.

[[v12-10-7]]

^<<v12-10-7,7>>^ Logo que eles receberam a carta, pegaram nos setenta filhos do rei, mataram-nos, meteram as suas cabeças em cestas e mandaram-nas a Jeú, a Jezrael.

[[v12-10-8]]

^<<v12-10-8,8>>^ Foi, pois, o mensageiro, e avisou-o: Trouxeram as cabeças dos filhos do rei. Ele respondeu: Ponde-as em dois montes à entrada da porta até pela manhã.

[[v12-10-9]]

^<<v12-10-9,9>>^ Quando amanheceu, saiu, e, posto em pé, disse a todo o povo: Vós_(que)_sois justos (dizei-me): Se eu conspirei contra o meu senhor e se o matei, quem é que matou todos estes?

[[v12-10-10]]

^<<v12-10-10,10>>^ Considerai, pois, agora que não caiu por terra palavra alguma do Senhor, que o Senhor proferiu contra a casa de Acab e como o Senhor cumpriu o que predisse pela boca do seu servo Elias.

[[v12-10-11]]

^<<v12-10-11,11>>^ Mandou Jeú matar todos os que restavam da casa de Acab em Jezrael, todos os grandes da sua corte, os seus familiares e os sacerdotes, até não ficar resto algum.

[[v12-10-12]]

^<<v12-10-12,12>>^ E levantou-se e foi para Samaria. Tendo chegado a uma cabana de pastores, que está junto do caminho,

[[v12-10-13]]

^<<v12-10-13,13>>^ encontrou os irmãos de Ocozias, rei de Judá, e disse-lhes: Quem sois vós? Eles responderam: Somos os irmãos de Ocozias e viemos saudar os filhos do rei e os filhos da rainha.

[[v12-10-14]]

^<<v12-10-14,14>>^ Jeú disse: Tomai-os vivos. Tendo-os tomado vivos, degolaram-nos numa cisterna perto da cabana, em número de quarenta e dois homens, e não deixou nenhum deles.

[[v12-10-15]]

^<<v12-10-15,15>>^ Partindo dali, encontrou Jonadab, fllho de Recab, que lhe vinha ao encontro. Jeú saudou-o, dizendo-lhe: Porventura tens tu o coração recto, como o meu o é com o teu coração? Jonadab respondeu: Tenho. Se assim é, disse Jeú, dá-me a tua mão. Jonadab deu-lhe a sua mão. Jeú mandou-o subir para o seu carro

[[v12-10-16]]

^<<v12-10-16,16>>^ e disse-lhe: Vem comigo e verás o meu zelo pelo Senhor. Tendo-o feito sentar no seu carro,

[[v12-10-17]]

^<<v12-10-17,17>>^ levou-o a Samaria, e mandou matar todos os que restavam da casa de Acab, em Samaria, sem perdoar a um só, conforme a palavra que o Senhor tinha pronunciado por meio de Elias.

[[v12-10-18]]

^<<v12-10-18,18>>^ Juntou, depois, Jeú todo o povo e disse-lhe: Acab tributou algum culto a Baal, mas eu lhe tributarei maior culto.

[[v12-10-19]]

^<<v12-10-19,19>>^ Chamai-me, pois, agora todos os profetas de Baal, todos os seus sacerdotes; nenhum deixe de vir, porque quero fazer um grande sacrifício a Baal; todo o que faltar morrerá. Isto em Jeú era artifício, para exterminar os adoradores de Baal.

[[v12-10-20]]

^<<v12-10-20,20>>^ Depois Jeú deu esta ordem: Fazei uma festa solene a Baal. Depois mandou

[[v12-10-21]]

^<<v12-10-21,21>>^ chamá-los por todos os limites de Israel, e vieram todos os servos de Baal; não ficou um só que não viesse. Entraram no templo de Baal, e encheu-se a casa de Baal desde uma extremidade até à outra.

[[v12-10-22]]

^<<v12-10-22,22>>^ (Jeú) disse aos que guardavam as vestimentas: Tirai vestimentas para todos os ministros de Baal. Eles levaram-lhes as vestimentas.

[[v12-10-23]]

^<<v12-10-23,23>>^ Tendo entrado Jeú com Jonadab, filho de Recab, no templo de Baal, disse aos adoradores de Baal: Examinai, vede bem que não esteja entre vós algum dos ministros do Senhor, mas sòmente os servos de Baal.

[[v12-10-24]]

^<<v12-10-24,24>>^ Entraram eles, pois, para oferecerem as suas vítimas e os seus holocaustos. Ora Jeú tinha prontos da parte de fora oitenta homens, aos quais dissera: Se escapar um só homem destes que eu vos entregar às mãos, a vossa vida me será responsável pela sua.

[[v12-10-25]]

^<<v12-10-25,25>>^ Quando acabaram de oferecer o holocausto, Jeú deu aos seus soldados e oficiais esta ordem: Entrai e matai-os; não escape nenhum. Os soldados e os capitães passaram-nos ao fio da espada, e lançaram-nos fora; depois foram à cidade do templo de Baal,

[[v12-10-26]]

^<<v12-10-26,26>>^ tiraram do templo a estátua de Baal, queimaram-na

[[v12-10-27]]

^<<v12-10-27,27>>^ e reduziram-na a pó. Destruíram também o templo de Baal e, em lugar dele, fizeram umas latrinas que ainda hoje existem.

[[v12-10-28]]

^<<v12-10-28,28>>^ Assim exterminou Jeú a Baal de Israel,

[[v12-10-29]]

^<<v12-10-29,29>>^ mas ele não se apartou dos pecados de Jeroboão, filho de Nabat, que fez pecar Israel, nem abandonou os bezerros de ouro, que estavam em Betel e em Dan.

[[v12-10-30]]

^<<v12-10-30,30>>^ Disse, pois, o Senhor a Jeú: Visto que cumpriste cuidadosamente o que era justo e agradável aos meus olhos e executaste contra a casa de Acab tudo o que eu tinha no meu coração, teus filhos se sentarão sobre o trono de Israel até à quarta geração.

[[v12-10-31]]

^<<v12-10-31,31>>^ Todavia, Jeú não teve o cuidado de andar de todo o seu coração na lei do Senhor Deus de Israel, porque não se apartou dos pecados de Jeroboão, que tinha feito pecar Israel.

[[v12-10-32]]

^<<v12-10-32,32>>^ Naquele tempo o Senhor começou a indignar-se contra Israel. Hazael derrotou-os em todas as fronteiras,

[[v12-10-33]]

^<<v12-10-33,33>>^ desde o Jordão, para a banda do oriente, (devastou) toda a terra de Galaad, de Gad, de Ruben e de Manassés, desde Aroer, que estava sobre a torrente de Arnon, até Galaad e Basan.

[[v12-10-34]]

^<<v12-10-34,34>>^ O resto das acções de Jeú, todos os seus feitos e o seu valor, não estão todas estas coisas escritas no livro das Crônicas dos reis de Israel?

[[v12-10-35]]

^<<v12-10-35,35>>^ Jeú adormeceu com seus pais e foi sepultado em Samaria. Em seu lugar reinou seu filho Joacaz.

[[v12-10-36]]

^<<v12-10-36,36>>^ O reinado de Jeú sobre Israel, em Samaria, foi de vinte e oito anos.

'''

xref:012-ii-reis/012-ii-reis-009.adoc#v12-9-0[&#60; Capítulo Anterior] | <<v12-10-0,Topo>> | xref:012-ii-reis/012-ii-reis-011.adoc#v12-11-0[Próximo Capítulo &#62;]